### ISSUE TITLE
Using fiji with DLC2; corner size for occluded feature

### ISSUE THREAD

**Issue by mschart** [DeepLabCut/DeepLabCut#100]
Hello,

I think single point labelling with auto-advance frame in fiji is substantially faster than the GUI of DLC2. Once I labelled all single points and save their locations as separate cvs files (as in DLC1), how can I integrate them to DLC2?

Also, where can I set the size of the upper left box in each frame, where one clicked to ignore that frame for training, say for occluded features (again, as was done in DLC1)?

Many thanks!

**Comment by MMathisLab** [comment]
You’ll have to use the step1/step2 code from DLC1 as of now. 

In the DLC2 GUI you don’t have to click in the top left corner, you just skip that item now, so that’s faster at least ;).

**Comment by AlexEMG** [comment]
Yeah, now you only need to click on identified body parts (much simpler!). Will try to put the DLC1_to_2 code online soon!

**Comment by mschart** [comment]
Excellent, thanks! I like dlc2, I'm just missing the single body part labelling option with fiji, as it had the auto-next-frame option that very much sped things up :)

**Comment by AlexEMG** [comment]
Finally some example conversion code here: https://github.com/AlexEMG/DLCutils Hope it makes sense. Perhaps you could write a import function for the xls files from Fiji, if you like it so much?

**Comment by mschart** [comment]
Thanks Alex, That's great. Yea, the auto-next slice option of fiji for the single body part labelling (which advances the frame at each measurement click, i.e. one kills two birds with one stone) is clearly the fastest method to create a training set. I'll try your conversion script and see how that all works in practice. I'll also contribute an import script to put the cvs location files of the single body parts - created with fiji - in the format DLC2 likes and add it to the DLCutils scripts. Cheers

![image](https://user-images.githubusercontent.com/17218515/48343406-95483e00-e672-11e8-90cb-4d820a3c8d83.png)

**Comment by AlexEMG** [comment]
Also, check out the edits by @FedeClaudi  to the labeling toolbox, now it "auto-advances" and there are hot keys.... [a few more hot keys could be added]

**Comment by mschart** [comment]
> Finally some example conversion code here: https://github.com/AlexEMG/DLCutils Hope it makes sense. Perhaps you could write a import function for the xls files from Fiji, if you like it so much?

I just used your convertDLC1TO2.py to convert fiji-labeled points to DLC2, works well! Also, no need to write any more function, just having the .csv with the labels, then applying step 1,2,3,4 of DLC1 and following your instructions in convertDLC1TO2.py made me able to train using DLC2 syntax.

I'll try the GUI labeling soon (although I have 400 images and 27 features, so maybe I need that single feature labeling in order not to go crazy).

Cheers
