### ISSUE TITLE
Automatic and uniform frame extraction is not uniform, it is random.

### ISSUE THREAD

**Issue by gabrielDiaz-performlab** [DeepLabCut/DeepLabCut#1000]
I have just extracted frames 3 times from the same video, using the same project, and the same config, only moving the contents of the labelled data folder to a new location between runs so that I can compare the frame numbers of the extracted frames.  The issue is that the extracted frames are non-uniformly spaced throughout the video, and differ each time I run extract_frames(). 

My guess is that this is because [the Index argument passed to UniformFramesCV2 is None by default](https://github.com/DeepLabCut/DeepLabCut/blob/cd4f2f558424ed26e4b431097db1ced607c9adc9/deeplabcut/utils/frameselectiontools.py#L80), and not set correctly [when the function is called in extract_frames](https://github.com/DeepLabCut/DeepLabCut/blob/cd4f2f558424ed26e4b431097db1ced607c9adc9/deeplabcut/generate_training_dataset/frame_extraction.py#L258).

When extracting, I used the following code: 

`deeplabcut.extract_frames(config_path, mode='automatic', algo='uniform', userfeedback=False, crop=False) grabs unique frame numbers each time.
`

**Desktop (please complete the following information about your system):**
 - OS: MacOS 10.15.7 (Catalina)
 - DeepLabCut Version 2.1.8.2
 - DeepLabCut mode: single animal tracking 

**To Reproduce**
Steps to reproduce the behavior, i.e.:
1. Create a project.
2. Extract frames using the auto/uniform setting.
3. Copy the extracted frames to a new directory.
4. Repeat the frame extraction and compare frame numbers.

<details><summary>TRACEBACK</summary><p>

```python

^do not delete the above "<details><summary>TRACEBACK</summary><p>" or the ```python part!
PLACE YOUR CODE HERE!!!  
do not delete below this line, leave the blank line and the ```

```
</p></details>

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. (but please post the code output above, not images of code!)

**Additional context**

**Comment by MMathisLab** [comment]
Sorry for any confusion in the naming, but as we explain a bit more here: https://www.nature.com/articles/s41596-019-0176-0

It’s random temporally sampled: 
![AEE03046-0543-4C01-AF17-11BDDC444C76](https://user-images.githubusercontent.com/28102185/99734260-c611a800-2ac2-11eb-988e-4363a8c96fde.png)

**Comment by MMathisLab** [comment]
(Discussed on gitter— all set!) and edited here: https://github.com/DeepLabCut/DeepLabCut/commit/7e88d156ef2012a932f7ce21dac2426140816de9
