### ISSUE TITLE
Command ‘ffmprobe -i 

### ISSUE THREAD

**Issue by Charly77220** [DeepLabCut/DeepLabCut#1002]
Windows-GPU with an Anaconda Env & DeepLabCut 2.1.8.2 (re-uploaded today)

OS: Windows
DeepLabCut Version: 2.1.8.2
Anaconda env used: DLC-GPU

**Describe the problem**

Hi developers, as of today and without any change in my environment or the way I use DLC, a "CalledProcessError" message appears without knowing why when I want to extract outlier frames. Have you ever faced this, and do you have a potential solution to my problem? I attach a screenshot of the terminal returning the error and all the packages of my configuration.

<details><summary>Code output</summary><p>

![Screen Trouble](https://user-images.githubusercontent.com/53442625/99887690-4bf13880-2c14-11eb-9151-930973d5d14a.PNG)

**Screenshots**

![screen list 1](https://user-images.githubusercontent.com/53442625/99887713-91ae0100-2c14-11eb-8cbf-1f57a4cf116a.PNG)
![screen list 2](https://user-images.githubusercontent.com/53442625/99887714-92469780-2c14-11eb-85f6-0333f2024586.PNG)
![screen list 3](https://user-images.githubusercontent.com/53442625/99887716-9377c480-2c14-11eb-8eff-4a616f62b878.PNG)

**Comment by blogeman** [comment]
Hey @Charly77220. Not a developer here but I've had problems with ffmpeg before on Windows, which is what it looks like you are having as well. I would try to re-install ffmpeg and see if that alleviates the problem.

**Comment by MMathisLab** [comment]
perhaps a windows update did you in; once in your env, run this: https://anaconda.org/conda-forge/ffmpeg

**Comment by Charly77220** [comment]
Thanks for your two answers, it perfectly solved the issue !

**Comment by TimOnofrychuk** [comment]
I had this same issue following a Windows 10 update and will add that re-downloading FFmpeg following these instructions (https://www.wikihow.com/Install-FFmpeg-on-Windows#/Image:Install-FFmpeg-on-Windows-Step-18.jpg) or this video (https://www.youtube.com/watch?v=r1AtmY-RMyQ), followed by 'conda install -c conda-forge/label/cf202003 ffmpeg' in my env did the trick for me. Thank you!
