### ISSUE TITLE
Using Box instead of Google Drive for DeepLabCut

### ISSUE THREAD

**Issue by Hydraulic343** [DeepLabCut/DeepLabCut#1003]
I am working on a project using deeplabcut, however the videos I am using are all on the Box platform instead of Google Drive. Each video is over 1 GB and it would take too long to move each video to the Google Drive and I don't have enough space for all of them. Is it possible for me link the DeepLabCut Colab, such as Colab_TrainNetwork_VideoAnalysis, to Box instead of Google Drive? Or would a new Colab need to be created to accommodate this?

What would suggest doing if this is not possible?

**Comment by MMathisLab** [comment]
HI @Hydraulic343 we are you follow the template for code bug reports, and for help and to get input from other users, please follow the links here: https://github.com/DeepLabCut/DeepLabCut#community-support-developers--help 

(i.e., your question is not DLC specific, i.e. you just want to know how to link "Box" to google colaboratory, so I would suggest posting that as the question on the user forum! cheers)
