### ISSUE TITLE
which Snapshot to pick in MultiAnimal project

### ISSUE THREAD

**Issue by blogeman** [DeepLabCut/DeepLabCut#1005]
Windows 10, Anaconda Python 3.6, Deeplabcut 2.2b8

Hi there DLC developers/users, 

I've labeled and trained a multi-animal project and would like to evaluate which Snapshot I should select to move forward with. The nicely written [maDLC_AdvUserGuide](https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/maDLC_AdvUserGuide.md) makes clear the difference between Pose Estimation and Tracking, so I know I must make sure Pose Estimation is adequate before performing cross-validation and conversion to Tracklets. To evaluate multiple Snapshots I run `deeplabcut.evaluate_network` and would like to evaluate based on either RMSE or rPCK. For single animal projects it looks like the function https://github.com/DeepLabCut/DeepLabCut/blob/7e88d156ef2012a932f7ce21dac2426140816de9/deeplabcut/pose_estimation_tensorflow/evaluate.py#L968 is called and generates .h5 and .csv files with the evaluation metics for each Snapshot. However, it looks like this function is not called for MultiAnimal projects. Rather, `evaluate_multianimal_full` is called and generates '_full.pickle' and '_meta.pickle'. I read through #947 but I don't seem to be getting the .h5 and .csv files. Am I missing something?

**Comment by MMathisLab** [comment]
I agree the evaluation results for maDLC should behave like normal DLC, i.e. it should be save .h5 and .csv files! @jeylau can we please add this? @AlexEMG

**Comment by MMathisLab** [comment]
Hi @blogeman we will be adding the csv with the stats like in "normal" DLC asap! 👍 @jeylau @AlexEMG

**Comment by blogeman** [comment]
Great to hear! Thanks for letting me know @MMathisLab.
