### ISSUE TITLE
Feeding my own frames for labeling instead of the kmeans selected frames

### ISSUE THREAD

**Issue by monajalal** [DeepLabCut/DeepLabCut#1010]
Is there any feasibility to feed in the frames I have randomly picked (if I have the frame numbers) instead of having the DLC pick the random frames using K-means clustering? 

I have two identical cameras however each of them randomly drop frames (not the same frames). So I need to pick a set of frames across the two that are existent. Overall, I wonder what people do in such cases?

**Comment by MMathisLab** [comment]
you can do this two ways:

(1) put the path of the video in the config.yaml, as it would be if you extracted the frames (or easier, just manually extract 1 frame anyhow and this is done automatically; DLC allows you to manually extract frames with a GUI). Then in the `labeled_data` directory, make a folder with the video name, and put in your frames. Then you can just label as normal. 

(2) if you have annotations, you can follow this: https://github.com/DeepLabCut/DeepLabCut/wiki/Using-labeled-data-in-DeepLabCut-that-was-annotated-elsewhere

**Comment by monajalal** [comment]
Thank you so much. 1 is what I am considering since I prefer to annotate with DLC GUI.

Do I need to have two synchronized video to feed into DLC to get 3D coordinates or is DLC able to synchronize the two videos? Both are approximately 11 minutes however are not synchronized. One is started later than the other. Thanks for any suggestion.
