### ISSUE TITLE
failed to load module atk-bridge module + canberra-gtk-module

### ISSUE THREAD

**Issue by orchidwen** [DeepLabCut/DeepLabCut#1012]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). 
Please fill out the template completely, including the full "TRACEBACK" and input code that you ran to hit this error.

**Describe the bug**
whenever I launch deeplabcut, it will appear 

> failed to load module "atk-bridge" 
> faied to locate module "canberra-gtk-module"

but when I try to locate atk-bridge and canberra-gtk-module, these packges already exist.

as follows:
 source activate dlc-ubuntu-GPU
 python -m deeplabcut
 Starting GUI...
Gtk-Message: 14:20:25.387: Failed to load module "atk-bridge"
Gtk-Message: 14:20:25.389: Failed to load module "canberra-gtk-module"

**Desktop :**
 - ubantu 18.04
 - deeplabcut2.2b8
 - multi-animal tracking
 - chrome
NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2
gcc version 7.5.0  
I have checked the driver and the CUDA version, it seems ok.
**To Reproduce**
Steps to reproduce the behavior, i.e.:
4. the input code you used (i.e. `deeplabcut.train_network( .... )`)
4. See error:

<details><summary>TRACEBACK</summary><p>

```python

 source activate dlc-ubuntu-GPU
 python -m deeplabcut
 Starting GUI...
Gtk-Message: 14:20:25.387: Failed to load module "atk-bridge"
Gtk-Message: 14:20:25.389: Failed to load module "canberra-gtk-module"
```
</p></details>

**Expected behavior**
this bug no longer exist 
**Screenshots**
If applicable, add screenshots to help explain your problem. (but please post the code output above, not images of code!)

**Additional context**

**Comment by jeylau** [comment]
Does this keep the GUI from opening? Or are those just warnings?

**Comment by Wutaijing9** [comment]
> Does this keep the GUI from opening? Or are those just warnings?
This disappeared after I upgrade my wxpython to 4.1.1

**Comment by Wutaijing9** [comment]
> Does this keep the GUI from opening? Or are those just warnings?

This disappeared after I updated wxpython to 4.1.1. Great thanks !

**Comment by JohnKirwan** [comment]
I get the same error when running:

>  python -m deeplabcut

> Starting GUI...
Gtk-Message: 10:42:06.764: Failed to load module "atk-bridge"
Gtk-Message: 10:42:06.767: Failed to load module "canberra-gtk-module"

**Details:**
Deeplabcut 2.2.0.3
Ubuntu 20.04.3 LTS
Kernel: 5.11.0-43-generic x86_64
NVIDIA Driver Version: 495.29.05 
CUDA Version: 11.5
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
nvcc Cuda compilation tools, release 10.1, V10.1.243
wxpython: '4.1.1 gtk2 (phoenix) wxWidgets 3.1.5'

**Comment by JohnKirwan** [comment]
It now works since i reverted to wxpython 4.1.0
