### ISSUE TITLE
Save error when saving labeled data in DLC 2.2b8 Index / Key error

### ISSUE THREAD

**Issue by felixhol** [DeepLabCut/DeepLabCut#1018]
DLC is awesome!

Here is a short summary of a conversation on [forum.image.sc](https://forum.image.sc/t/error-when-labeling-saving/45661/2) regarding a saving issue experienced when labeling data in DLC 2.2b8. As it seems to be a bug, I thought it was good to mention it here:

I have been getting a KeyError or IndexError which occurs the second or third time I try to save my labeling. It has to do with the indexing of the CollectedData.h5 file - it uses the file names of the images in the folder as indexes, yet after saving for a second time, it removes all the not-yet-labeled images from the index of the h5 file. Hence when clicking advance to go the next frame it cannot find the next index image (as the index does not exist anymore in the h5 file).
My only solution so far has been to only save after all images in a folder are done - this is of course bad practice.
I’ve experienced this using DLC 2.2b8 on both macOS and ubuntu 18.04. User WSin initially posted this on forum.image.sc and noted that rolling back to 2.2b7 resolves the issue. 

 - OS: Linux 18.04 and macOS
 - DeepLabCut Version: 2.2b8
 - DeepLabCut mode: multi animal

**To Reproduce**
Steps to reproduce the behavior, i.e.:
1. deeplabcut.label_frames(config_path)
2. start labelling in a new project (or any folder that does not have Collected Data)
3. add some labels
4. click save.
5. advance to next frame.
6. crash, see error:

<details><summary>Traceback (most recent call last):

```python
  File "/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/multiple_individuals_labeling_toolbox.py", line 1081, in nextImage
    self.buttonCounter = MainFrame.plot(self, self.img)
  File "/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/multiple_individuals_labeling_toolbox.py", line 1180, in plot
    self.dataFrame[self.scorer][ind][bp]["x"].values[self.iter],
IndexError: index 2 is out of bounds for axis 0 with size 1</summary><p>

```
</p></details>

**Expected behavior**
no crash, if I don't until I'm on the last file it all works fine. 

 **Additional context**
This does not happen when using 2.2b7

**Comment by jeylau** [comment]
Hey @felixhol! Thanks for opening the issue and troubleshooting, that's very helpful! I'll have a look and get back to you.
