### ISSUE TITLE
Extracting Frames

### ISSUE THREAD

**Issue by kebanfi** [DeepLabCut/DeepLabCut#1019]
**Your Operating system and DeepLabCut version**

OS: Windows 10
DeepLabCut Version: 2.2
Anaconda env used: python

Problem:

Frames started extracting over a day ago and it is still not completed. 

**Screenshots**

![Extractions](https://user-images.githubusercontent.com/72465861/100812706-b02dac80-340b-11eb-80e4-cc61e1e02928.jpg)

**Comment by jeylau** [comment]
Hey @kebanfi, what specific version of DLC are you using? Did you change the `cluster_resizewidth` default value?

**Comment by kebanfi** [comment]
Hi,

I'm on version 2.1.8.2. I don't believe the cluster_resizewidth value was
changed.

Thank you,

Caroline

**Comment by MMathisLab** [comment]
It should not take more than a few min; I also am concerned about the warnings above; I would kill the process and try again (perahps using our demo data first to be sure all is working well).

**Comment by MMathisLab** [comment]
any updates, @kebanfi ?

**Comment by kebanfi** [comment]
Hi, yes we were able to figure out the issue. It appears we just needed to
put 1 cluster instead of 3.

Thank you
