### ISSUE TITLE
Issues with labeling using the dlc-gui (unresponsive on clicking on body parts)

### ISSUE THREAD

**Issue by mokkelrekords17** [DeepLabCut/DeepLabCut#1020]
**Describe the bug**

Please provide the minimal required code to reproduce the error and the full output (please edit ONLY the section below that says `PLACE YOUR CODE HERE!!! `.

**Desktop (please complete the following information about your system):**
 - OS: Ubuntu 18.04
 - DeepLabCut 2.2b8
 - DeepLabCut single animal tracking, 

**To Reproduce**
Steps to reproduce the behavior, i.e.:

- Activated DLC-GPU
- ipython
- import deeplabcut==2,2b8
- deeplabcut.dlc()
- Created a new project and added new videos succesfully and frames extracted succesfully. However unable to put markers on body parts. GUI unresponsive on clicking over the body parts
- Running it on ubuntu 18.04

**Screenshots**
If applicable, add screenshots to help explain your problem. (but please post the code output above, not images of code!)
![image](https://user-images.githubusercontent.com/75369528/100868670-372a6580-349c-11eb-97da-203d36591793.png)

**Additional context**

**Comment by MMathisLab** [comment]
can you confirm you are using a "RIGHT" mouse click? (can you click buttons, i.e., next, previous, help?)

**Comment by basicvisual** [comment]
Thanks for the tip thanks for the answer . I can now continue to work , Highly appreciated.

**Comment by mokkelrekords17** [comment]
My mistake, i double checked it with right click and it worked. highly appreciated.
