### ISSUE TITLE
Frame extraction not equal to that specified in config.yaml

### ISSUE THREAD

**Issue by npranav9** [DeepLabCut/DeepLabCut#1022]
OS: Windows 10
DeepLabCut Version: 2.1.6
Anaconda env used: conda 

**Describe the problem**

After I created my project and loaded my video, I tried to extract 500 frames, but the total frames loaded in the "label frames" GUI shows only 260. 

<details><summary>Code output</summary><p>

```python

Config file read successfully.
Do you want to extract (perhaps additional) frames for video: /projectnb2/hasselmogrp/pnambiar/dlc/rat113020red-pranav-2020-11-30/videos/HSDR-112420_red_1.wmv ?
yes/noyes
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 630.12  seconds.
Extracting and downsampling... 630121  frames from the video.
630121it [25:19, 414.71it/s] 
Kmeans clustering ... (this might take a while)
/projectnb/hasselmogrp/.conda/envs/DLC-GPU-DC/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py:1676: RuntimeWarning: init_size=300 should be larger than k=500. Setting it to 3*k
  init_size=init_size)
/projectnb/hasselmogrp/.conda/envs/DLC-GPU-DC/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py:1676: RuntimeWarning: init_size=300 should be larger than k=500. Setting it to 3*k
  init_size=init_size)
/projectnb/hasselmogrp/.conda/envs/DLC-GPU-DC/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py:1676: RuntimeWarning: init_size=300 should be larger than k=500. Setting it to 3*k
  init_size=init_size)
Frame 630119  not found!
Frames were successfully extracted.
```

You can now label the frames using the function 'label_frames' (if you extracted enough frames for all videos).

</p></details>

**How to Reproduce the problem**
1. Open DLC
2. Create project and edit config.yaml to include numframes2pick = 500
3. Extract frames
4. Load frames for labeling
5. See 260 total frames

**Screenshots**

![image](https://user-images.githubusercontent.com/18171814/101211924-e9516100-3645-11eb-937b-d8298acfb872.png)

![image](https://user-images.githubusercontent.com/18171814/101212204-5533c980-3646-11eb-81ba-f829f5a3d5eb.png)

**Comment by MMathisLab** [comment]
these are not "normal" warnings though, suggesting you video is perhaps corrupted (amongst other things):

```python

Frame 630119 not found!


/projectnb/hasselmogrp/.conda/envs/DLC-GPU-DC/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py:1676: RuntimeWarning: init_size=300 should be larger than k=500. Setting it to 3k
init_size=init_size)
/projectnb/hasselmogrp/.conda/envs/DLC-GPU-DC/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py:1676: RuntimeWarning: init_size=300 should be larger than k=500. Setting it to 3k
init_size=init_size)
/projectnb/hasselmogrp/.conda/envs/DLC-GPU-DC/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py:1676: RuntimeWarning: init_size=300 should be larger than k=500. Setting it to 3*k
init_size=init_size)
Frame 630119 not found!
```

**Comment by MMathisLab** [comment]
also, I would strongly recommend installing 2.1.9!

**Comment by npranav9** [comment]
I'm connecting to a remote desktop to run DLC and I'm unable to extract 500+ frames. I've tried changing the video and I get the same issue. What else could this be?

**Comment by MMathisLab** [comment]
Is there a reason you are extracting 500 frames for 1 video?! This would be a very atypical use of DeepLabCut, maybe you can tell me more about your needs?

**Comment by monajalal** [comment]
@MMathisLab thanks a lot for your feedback. For a 10 min video with approximately 25000 frames how many frames do you suggest extracting such that we could achieve <3-5 pixel error? We had tried 100 and 200 and hoped 500 will yield better accuracy.

**Comment by MMathisLab** [comment]
Pixel error as a hard number is only meaningful in relation to the human ground truth error. If the human labels are > 5pixels (which is very common), you have hit the ceiling. In general, it is much better to pick ~40-50 frames per video but many different videos, not one. The idea is to not only use a network on the video you label, but to new videos. Therefore, I would pick more videos. 

![workflow](https://user-images.githubusercontent.com/28102185/101767590-b2b39480-3ae4-11eb-9029-8974685c2563.jpg)

Figure from a new paper, that might be of interest: https://www.sciencedirect.com/science/article/pii/S0896627320307170 (and open access: https://arxiv.org/abs/2009.00564)

**Comment by jeylau** [comment]
@npranav9, your video contains 600k+ frames; given the default batchsize of 100 and max_iter of 50, at most 5k frames have been seen when fitting k-means. According to this great answer here: [https://github.com/scikit-learn/scikit-learn/issues/13476#issuecomment-474794763](url), this may explain why 'only' 260 representative and distinct frames are found for the whole video. A possible solution is to increase batchsize. But given that kmeans fails to identify more clusters, it is likely that the 240 extra frames you wanted would be redundant and unnecessary.
