### ISSUE TITLE
key error during X-val and create Tracklet

### ISSUE THREAD

**Issue by deepbraincut** [DeepLabCut/DeepLabCut#1023]
Hi, I am using multi-animal tracking for characterizing mouse social behaviors, and really enjoying using DLC. :) 
But now I have a key error after the expansion of training set, and not sure if the error has been up because of wrong parameter set ups, or wrong training process. The error is repeating after X-val or creating tracklet files. 

 - OS: Windows10 
 - DLC-GPU deeplabcut2.2b8 
 - multi-animal tracking
 - ms edge

I've created a test training set for 3-animals tracking in one consistent context, created 50 labeling files with 1 video, and ran the 1st training without cropping. After the 1st training, I found tracking errors in the result tracklet video, and added the crop option, and ran the 2nd training with the same iteration index, which did not cause any problem until tracklet creation. Since I found the tracking wasn't still satisfying yet, so that I increased skeleton connections, and ran the training again with same iteration index, which start causing key error '5_9' during X-validation and the tracklet creation. Also, when I re-ran with increased labeling frames, and training went well without any problems but the same key error is still there during X-val. 

![error_key5_9](https://user-images.githubusercontent.com/75436015/101258357-f165db00-36ef-11eb-8896-cd0665c0997c.PNG)

Do you have any idea which part of my process caused this error?
Thank you!

**Comment by MMathisLab** [comment]
When you merge data, you really should run "merge_datasets" and always use a new iteration number (which it does automatically if you follow our steps :). You can severely impact the data loading if not-- it sounds like this is the issue; I would (I hope you have a copy) roll back and be sure to run merge_datasets first before training over it.

**Comment by deepbraincut** [comment]
Thank you for the reply! I thought "merge data sets" should be done only after 'refine' the tracklets, so I skipped the part after adding labeling. Will correct it. Many thanks again.
