### ISSUE TITLE
analyze_videos() failing for all but one job when run in parallel

### ISSUE THREAD

**Issue by brettellebi** [DeepLabCut/DeepLabCut#1027]
**Operating system and DeepLabCut version**

- OS: Red Hat Enterprise Linux Server release 7.4 (Maipo)
- DeepLabCut Version: 2.2b8
- Anaconda env used: DLC-CPU

**Describe the problem**

I'm trying to run `analyze_videos()` with a trained `maDLC` model on ~600 videos in parallel, using our institute's cluster with regular CPU nodes (which, although slow, is fine if I can run them all simulatenously).

I'm using [Snakemake](https://snakemake.readthedocs.io/en/stable/index.html) to manage the pipeline with a simple python script for this step. Snakemake submits a separate job for each video, all to be run in parallel. 

However, only one video completes successfully. 

Code:

<details><summary>Code output</summary><p>

```python
############# Snakemake rule

rule analyse_videos:
    input:
        join(config["dlc_project_path"], "videos/{sample}_{quadrant}_{assay}.mp4")
    params:
        dlc_project_path = config["dlc_project_path"] # DLC config.yml path to feed into script
    output:
        join(config["dlc_project_path"], "videos/{sample}_{quadrant}_{assay}") + config["dlc_scorer_name"] + "_full.pickle"
    conda:
        config["dlc-cpu_env"] # this is the DLC-CPU conda env
    script:
        config["dlc_analyze_script"]

############# Python script (config["dlc_analyze_script"])

#!/usr/bin/env python3

# Import libaries

import os
os.environ["DLClight"]="True" # suppress GUI

import deeplabcut

# Setup project variables

config_path = os.path.join(snakemake.params.dlc_project_path, 'config.yaml')

target_video = snakemake.input[0]

# Analyse video

deeplabcut.analyze_videos(config_path, target_video, videotype='mp4', save_as_csv=True)
```
</p></details>

**How to Reproduce the problem**
1. Submit two or more separate jobs to a cluster to run the above python script simultaneously on different videos.
2. One will complete successfully, the others will proceed normally but then fail (perhaps when the successful one completes?)

**Screenshots**
This is the error log for one of the failed jobs. They were all neary complete when they failed:
<img width="1045" alt="Screenshot 2020-12-09 at 08 47 29" src="https://user-images.githubusercontent.com/42971601/101546011-3b0a3a80-39fc-11eb-96a2-8443634be509.png">

**Comment by MMathisLab** [comment]
target_video can be a folder with all the videos. This seems specific to your code, not DLC, so unfortunately I can't help beyond that. If you want to see how we analyze videos, here is a demo script: 

https://github.com/DeepLabCut/DLCutils/blob/master/SCALE_YOUR_ANALYSIS/scale_analysis_oversubfolders.py
