### ISSUE TITLE
DeepLabCut on long videos > 30 secondes 

### ISSUE THREAD

**Issue by anaphelippeau** [DeepLabCut/DeepLabCut#1028]
Hi ! 

First of all, I have to thank you for your work. 

I would like to know if DLC if efficient for long videos (such as videos longer than 30 seconds) ?. 
I want to use it to track the upper limb joint of children in a writing task but the task is quite long and I'm afraid that DLC won't work (or take too much time to process). 

Thank you very much for your answer and your help. 
Ana Phelippeau
PhD student, National Museum of Natural History, Paris, France.

**Comment by MMathisLab** [comment]
Hi, yes -- DLC runs frame-by-frame. You can run videos that are as long as you want. We routinely run videos that are over 1 hour. The time to run videos is documented in the publications, but also here (you can see up to 2500 FPS):

![image](https://user-images.githubusercontent.com/28102185/101662162-741ccc00-3a49-11eb-9b41-12a579a53a3e.png)

from this paper: https://arxiv.org/abs/1909.11229

Also, please note we have a user forum that is best for questions (and searching others too!) Hope this helps: https://forum.image.sc/tag/deeplabcut
