### ISSUE TITLE
question: how to check gpu usage

### ISSUE THREAD

**Issue by WasifRaza123** [DeepLabCut/DeepLabCut#1030]
Hello, i have a Gaming laptop with Intel HD graphics and Nvidia 1050ti 4gb descrete graphic card. When i run the code in jupyter notebook, i can see in task manager only Intel graphics is being used. How do i make sure my code used Nvidia GPU

_Originally posted by @Vinod-13 in https://github.com/DeepLabCut/DeepLabCut/issues/91#issuecomment-583256399_

**Comment by jeylau** [comment]
Hello @WasifRaza123! What code specifically are you running? If you refer to model training, you could pass the ID of your GPU to the argument `gputouse`, or manually set the environment variable as follows:
```
import os
os.environ['CUDA_DEVICE_ORDER'] = 'PCI_BUS_ID'
os.environ['CUDA_VISIBLE_DEVICES'] = '1'
```
for example, assuming the ID is 1. You can get the ID with the command `nvidia-smi` in the terminal.

**Comment by MMathisLab** [comment]
@WasifRaza123 you can use the call `nvidia-smi` to look at GPU usage (and find the GPU number)
