### ISSUE TITLE
Error message when extracting frames

### ISSUE THREAD

**Issue by CourtneyC-P** [DeepLabCut/DeepLabCut#1032]
**describe the bug**
I am having trouble extracting frames from my videos. I successfully extracted frames from my first video but when trying to extract frames from the next video I received an error message. I tried to extract additional frames from the first video and now receive the error message with that video as well. Someone else working on this project, @neurologic , is able to extract frames from all videos using the same Deeplabcut version and Mac OS. I have tried extracting frames using both the command line interface and the GUI and run into the same error message.  

**Desktop (please complete the following information about your system):**
 - OS: MacOS Catalina
 - DeepLabCut Version 2.2b8
 - DeepLabCut mode: multi-animal tracking

**To Reproduce**
Steps to reproduce the behavior, i.e.:
1. deeplabcut.extract_frames(config_path,"automatic", "kmeans", True)
2. See error:

<details><summary>TRACEBACK</summary><p>

```python

Do you want to extract (perhaps additional) frames for video: /Users/courtney/Documents/Wesleyan/Perks_Lab/mnt/GoogleDrive/Team Drives/PerksLab_DLC/DLC_projects/GroupBehavior0-LAB-2020-11-24/videos/Basler_acA1300-200um__23511574__20201122_121610140.avi ?
yes/noyes
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 40.67  seconds.
Extracting and downsampling... 610  frames from the video.
610it [00:22, 27.58it/s]
Kmeans clustering ... (this might take a while)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/courtney/Documents/Wesleyan/Perks_Lab/DeepLabCut/deeplabcut/generate_training_dataset/frame_extraction.py", line 276, in extract_frames
    color=cluster_color,
  File "/Users/courtney/Documents/Wesleyan/Perks_Lab/DeepLabCut/deeplabcut/utils/frameselectiontools.py", line 392, in KmeansbasedFrameselectioncv2
    kmeans.fit(data)
  File "/Users/courtney/Documents/Wesleyan/Perks_Lab/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py", line 1666, in fit
    order='C', accept_large_sparse=False)
  File "/Users/courtney/Documents/Wesleyan/Perks_Lab/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/sklearn/base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "/Users/courtney/Documents/Wesleyan/Perks_Lab/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/Users/courtney/Documents/Wesleyan/Perks_Lab/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/sklearn/utils/validation.py", line 645, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/Users/courtney/Documents/Wesleyan/Perks_Lab/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/sklearn/utils/validation.py", line 99, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

```
</p></details>

**Expected behavior**
Expected frames to be extracted successfully

**Screenshots**
<img width="801" alt="Screen Shot 2020-12-07 at 5 31 09 PM" src="https://user-images.githubusercontent.com/74376868/101956142-1913e200-3bcd-11eb-9018-3d3f28534172.png">

**Comment by MMathisLab** [comment]
>> Someone else working on this project, @neurologic , is able to extract frames from all videos using the same Deeplabcut version and Mac OS

So, it sounds like not a DLC bug, as the code is working. 

It could be a version mismatch of numpy or such. 

are you both using the same conda env? 

it also may be that video's meta data is corrupted...

**Comment by neurologic** [comment]
Thanks for getting back to us quickly!

We are both using DLC-CPU (but downloaded on different dates; I downloaded
mine around June I think). Though I have macOS 10.14 (Mojave) instead of
Catalina.

I am also now getting the same error as well even though previously
extraction on the project videos was successful from my machine. I am,
however, able to extract via uniform method. Would kmeans access metadata
in a way that uniform would not?

I can try copying the original videos (saved on a different computer's HD)
into the videos project folder (which is on a Google Teams drive that we
both have access to so that we can both work on the same project) to see if
that solves the issue (which would confirm it was something that is
happening to the files?). I will let you know how that goes.

**Comment by MMathisLab** [comment]
in the env, can you run:

```python
import numpy
numpy._version__

import sklearn
sklearn.__version__
```
and report back? thanks

**Comment by CourtneyC-P** [comment]
We both checked our version numbers and both had numpy version 1.16.4. @neurologic has sklearn version 0.23.1 but I have sklearn version 0.23.2. 

@neurologic was able to extract frames via kmeans after re-saving the original video file into the project directory. However, I am still getting the same error message even after re-saving the same original video in the directory. 

I am able to successfully extract frames using the uniform method, but the kmeans method remains unsuccessful.

**Comment by MMathisLab** [comment]
@CourtneyC-P sounds like something is off with your installation then; I would remove the env. and just do a fresh install.

**Comment by jeylau** [comment]
It looks like a NaN slipped in the empty array and never got overwritten. With #1057, we will handle this rare case just fine!

**Comment by MMathisLab** [comment]
A likely fix for this is now in the github code, you can install the code directly from github using these instructions: https://github.com/DeepLabCut/DeepLabCut/wiki/How-to-use-the-latest-GitHub-code
