### ISSUE TITLE
Analyzing video doesn't succeed

### ISSUE THREAD

**Issue by alecarlucci97** [DeepLabCut/DeepLabCut#1035]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: Windows 8.1 Pro
DeepLabCut Version: 2.2
Anaconda env used: Anaconda prompt 3, GPU, ipython

**Describe the problem**

I made 3 different trials for the same video. At first I thought the number of iterations were too low, so I left the program run with 100.000 iterations to make sure that wasn't the problem. However, when I analyze the video, the full.mp4 file video shows tracking for around 1-2 seconds and then it disappears. It happened for all the previous trials. Of course this leads to empty tracklets or 1-2 seconds tracking when refining them. Any solution?
I don't know if this could be useful, but when I tried to plot the maps, I got another error on the way. I'll post both error.

P.S. I'm not much familiar with coding, this is part of a training for a research internship

Please place code inside this: Error in plotting maps

<details><summary>Code output</summary><p>

[CancelledError (see above for traceback): Enqueue operation was cancelled
         [[node fifo_queue_enqueue (defined at C:\ProgramData\Anaconda3\envs\dlc
-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train_multia
nimal.py:64) ]]

The network is now trained and ready to evaluate. Use the function 'evaluate_net
work' to evaluate the network.

Config:
{'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10]],
 'all_joints_names': ['midline',
                      'leftelbow',
                      'rightelbow',
                      'rightwrist',
                      'leftwrist',
                      'leftMCP2',
                      'leftPIP2',
                      'leftDIP2',
                      'rightMCP2',
                      'rightPIP2',
                      'rightDIP2'],
 'batch_size': 1,
 'crop_pad': 0,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Test '
            '2Dec11\\Test 2_Alessandro Carlucci95shuffle1.pickle',
 'dataset_type': 'multi-animal-imgaug',
 'deterministic': False,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'C:\\ProgramData\\Anaconda3\\envs\\dlc-windowsGPU\\lib\\site-pa
ckages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50
.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 1.0,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'mean_pixel': [123.68, 116.779, 103.939],
 'minconfidence': 0.01,
 'mirror': False,
 'net_type': 'resnet_50',
 'nmsradius': 5.0,
 'num_joints': 11,
 'num_limbs': 10,
 'optimizer': 'sgd',
 'pairwise_huber_loss': True,
 'pairwise_predict': False,
 'partaffinityfield_graph': [[0, 1],
                             [6, 7],
                             [4, 5],
                             [5, 6],
                             [1, 4],
                             [3, 8],
                             [8, 9],
                             [9, 10],
                             [2, 3],
                             [0, 2]],
 'partaffinityfield_predict': True,
 'regularize': False,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'C:\\Users\\r0810013\\Test 2-Alessandro '
                    'Carlucci-2020-12-11\\dlc-models\\iteration-0\\Test '
                    '2Dec11-trainset95shuffle1\\test\\snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Initializing ResNet
Activating extracting of PAFs
2020-12-14 09:24:29.382969: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
512] Adding visible gpu devices: 0
2020-12-14 09:24:29.388962: I tensorflow/core/common_runtime/gpu/gpu_device.cc:9
84] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-12-14 09:24:29.397121: I tensorflow/core/common_runtime/gpu/gpu_device.cc:9
90]      0
2020-12-14 09:24:29.402139: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
003] 0:   N
2020-12-14 09:24:29.407389: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 wit
h 3199 MB memory) -> physical GPU (device: 0, name: Quadro K2200, pci bus id: 00
00:03:00.0, compute capability: 5.0)
Analyzing data...
990it [01:46,  9.28it/s]
Saving plots...
 41%|████████████████?                       | 405/990 [06:32<09:49,  1.01s/it]-
--------------------------------------------------------------------------
wxAssertionError                          Traceback (most recent call last)
C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\gui\ev
aluate_network.py in evaluate_network(self, event)
    328         if self.plot_scoremaps.GetStringSelection() == "Yes":
    329             for shuffle in Shuffles:
--> 330                 deeplabcut.extract_save_all_maps(self.config, shuffle=sh
uffle)
    331
    332         if len(self.bodyparts) == 0:

C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_e
stimation_tensorflow\visualizemaps.py in extract_save_all_maps(config, shuffle,
trainingsetindex, comparisonbodyparts, all_paf_in_one, gputouse, rescale, Indice
s, modelprefix, dest_folder)
    513                         cmap = plt.cm.get_cmap(cfg["colormap"], n_inds)
    514                         colors = cmap(range(n_inds))
--> 515                         fig3, _ = visualize_paf(image, paf[:, :, inds],
colors=colors)
    516                         temp = dest_path.format(
    517                             imname=imname,

C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_e
stimation_tensorflow\visualizemaps.py in visualize_paf(image, paf, step, colors)

    332 def visualize_paf(image, paf, step=5, colors=None):
    333     ny, nx = np.shape(image)[:2]
--> 334     fig, ax = form_figure(nx, ny)
    335     ax.imshow(image)
    336     n_fields = paf.shape[2]

C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_e
stimation_tensorflow\visualizemaps.py in form_figure(nx, ny)
    288
    289 def form_figure(nx, ny):
--> 290     fig, ax = plt.subplots(frameon=False)
    291     ax.set_xlim(0, nx)
    292     ax.set_ylim(0, ny)

C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\matplotlib\pyplot
.py in subplots(nrows, ncols, sharex, sharey, squeeze, subplot_kw, gridspec_kw,
**fig_kw)
   1207
   1208     """
-> 1209     fig = figure(**fig_kw)
   1210     axs = fig.subplots(nrows=nrows, ncols=ncols, sharex=sharex, sharey=s
harey,
   1211                        squeeze=squeeze, subplot_kw=subplot_kw,

C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\matplotlib\pyplot
.py in figure(num, figsize, dpi, facecolor, edgecolor, frameon, FigureClass, cle
ar, **kwargs)
    543                                         frameon=frameon,
    544                                         FigureClass=FigureClass,
--> 545                                         **kwargs)
    546
    547         if figLabel:

C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\matplotlib\backen
ds\backend_wx.py in new_figure_manager(cls, num, *args, **kwargs)
   1967             # garbage collected.
   1968             _BackendWx._theWxApp = wxapp
-> 1969         return super().new_figure_manager(num, *args, **kwargs)
   1970
   1971     @classmethod

C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\matplotlib\backen
d_bases.py in new_figure_manager(cls, num, *args, **kwargs)
   3259         fig_cls = kwargs.pop('FigureClass', Figure)
   3260         fig = fig_cls(*args, **kwargs)
-> 3261         return cls.new_figure_manager_given_figure(num, fig)
   3262
   3263     @classmethod

C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\matplotlib\backen
ds\backend_wx.py in new_figure_manager_given_figure(cls, num, figure)
   1971     @classmethod
   1972     def new_figure_manager_given_figure(cls, num, figure):
-> 1973         frame = cls._frame_class(num, figure)
   1974         figmgr = frame.get_figure_manager()
   1975         if matplotlib.is_interactive():

C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\matplotlib\backen
ds\backend_wx.py in __init__(self, num, fig)
   1101             self.statusbar = StatusBarWx(self)
   1102         self.SetStatusBar(self.statusbar)
-> 1103         self.toolbar = self._get_toolbar(self.statusbar)
   1104
   1105         if self.toolmanager:

C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\matplotlib\backen
ds\backend_wx.py in _get_toolbar(self, statbar)
   1129     def _get_toolbar(self, statbar):
   1130         if rcParams['toolbar'] == 'toolbar2':
-> 1131             toolbar = NavigationToolbar2Wx(self.canvas)
   1132             toolbar.set_status_bar(statbar)
   1133         elif matplotlib.rcParams['toolbar'] == 'toolmanager':

C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\matplotlib\backen
ds\backend_wx.py in __init__(self, canvas)
   1375     def __init__(self, canvas):
   1376         wx.ToolBar.__init__(self, canvas.GetParent(), -1)
-> 1377         NavigationToolbar2.__init__(self, canvas)
   1378         self.canvas = canvas
   1379         self._idle = True

C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\matplotlib\backen
d_bases.py in __init__(self, canvas)
   2634         # This cursor will be set after the initial draw.
   2635         self._lastCursor = cursors.POINTER
-> 2636         self._init_toolbar()
   2637         self._idDrag = self.canvas.mpl_connect(
   2638             'motion_notify_event', self.mouse_move)

C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\matplotlib\backen
ds\backend_wx.py in _init_toolbar(self)
   1411                       id=self.wx_ids[text])
   1412
-> 1413         self.Realize()
   1414
   1415     def zoom(self, *args):

wxAssertionError: C++ assertion "Assert failure" failed at ..\..\src\msw\toolbar
.cpp(938) in wxToolBar::Realize(): Could not add bitmap to toolbar
]

</p></details>

<details><summary>Code output</summary><p>

['dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Test '
            '2Dec11\\Test 2_Alessandro Carlucci95shuffle1.pickle',
 'dataset_type': 'multi-animal-imgaug',
 'deterministic': False,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'C:\\ProgramData\\Anaconda3\\envs\\dlc-windowsGPU\\lib\\site-pa
ckages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50
.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 1.0,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'mean_pixel': [123.68, 116.779, 103.939],
 'minconfidence': 0.01,
 'mirror': False,
 'net_type': 'resnet_50',
 'nmsradius': 5.0,
 'num_joints': 11,
 'num_limbs': 10,
 'optimizer': 'sgd',
 'pairwise_huber_loss': True,
 'pairwise_predict': False,
 'partaffinityfield_graph': [[0, 1],
                             [6, 7],
                             [4, 5],
                             [5, 6],
                             [1, 4],
                             [3, 8],
                             [8, 9],
                             [9, 10],
                             [2, 3],
                             [0, 2]],
 'partaffinityfield_predict': True,
 'regularize': False,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'C:\\Users\\r0810013\\Test 2-Alessandro '
                    'Carlucci-2020-12-11\\dlc-models\\iteration-0\\Test '
                    '2Dec11-trainset95shuffle1\\test\\snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Using snapshot-100000 for model C:\Users\r0810013\Test 2-Alessandro Carlucci-202
0-12-11\dlc-models\iteration-0\Test 2Dec11-trainset95shuffle1
Initializing ResNet
Activating extracting of PAFs
2020-12-14 10:05:38.677838: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
512] Adding visible gpu devices: 0
2020-12-14 10:05:38.683544: I tensorflow/core/common_runtime/gpu/gpu_device.cc:9
84] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-12-14 10:05:38.690728: I tensorflow/core/common_runtime/gpu/gpu_device.cc:9
90]      0
2020-12-14 10:05:38.695146: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
003] 0:   N
2020-12-14 10:05:38.699666: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 wit
h 3199 MB memory) -> physical GPU (device: 0, name: Quadro K2200, pci bus id: 00
00:03:00.0, compute capability: 5.0)
Starting to analyze %  C:\Users\r0810013\Test 2-Alessandro Carlucci-2020-12-11\v
ideos\GH010052.MP4
C:\Users\r0810013\Test 2-Alessandro Carlucci-2020-12-11\videos  already exists!
Loading  C:\Users\r0810013\Test 2-Alessandro Carlucci-2020-12-11\videos\GH010052
.MP4
Duration of video [s]:  22.92 , recorded with  59.94 fps!
Overall # of frames:  1374  found with (before cropping) frame dimensions:  1920
 1080
Starting to extract posture
                                                                               D
etected frames:  49
  4%|██                                      | 52/1374 [00:34<14:33,  1.51it/s]
Saving results in C:\Users\r0810013\Test 2-Alessandro Carlucci-2020-12-11\videos
...
The videos are analyzed. Time to assemble animals and track 'em...
 Call 'create_video_with_all_detections' to check multi-animal detection quality
 before tracking.
If the tracking is not satisfactory for some videos, consider expanding the trai
ning set. You can use the function 'extract_outlier_frames' to extract a few rep
resentative outlier frames.
DLC_resnet50_Test 2Dec11shuffle1_100000
Creating labeled video for  GH010052
                                                                               E
rror: %s axis 2 is out of bounds for array of dimension 0
49 no data                                   | 47/1374 [00:01<00:29, 45.74it/s]
49 frame writing error.
Error: %s axis 2 is out of bounds for array of dimension 0
50 no data
50 frame writing error.
Error: %s axis 2 is out of bounds for array of dimension 0
51 no data
51 frame writing error.
Error: %s axis 2 is out of bounds for array of dimension 0
52 no data
52 frame writing error.
53 no data
54 no data
                                                                               5
5 no data
56 no data                                   | 55/1374 [00:01<00:25, 52.37it/s]
57 no data
58 no data
59 no data
60 no data
                                                                               6
1 no data
62 no data                                   | 61/1374 [00:01<00:25, 51.89it/s]
63 no data
64 no data
65 no data
66 no data
                                                                               6
7 no data
68 no data                                   | 67/1374 [00:01<00:25, 51.97it/s]
69 no data
70 no data
71 no data
72 no data
                                                                               7
3 no data
74 no data                                   | 73/1374 [00:01<00:25, 51.88it/s]
75 no data
76 no data
77 no data
78 no data
                                                                               7
9 no data
80 no data                                   | 79/1374 [00:01<00:24, 51.82it/s]
81 no data
82 no data
83 no data
84 no data
                                                                               8
5 no data
86 no data                                   | 85/1374 [00:01<00:24, 51.78it/s]
87 no data
88 no data
89 no data
90 no data
                                                                               9
1 no data
92 no data                                   | 91/1374 [00:01<00:24, 51.62it/s]
93 no data
94 no data
95 no data
96 no data
                                                                               9
7 no data
98 no data                                   | 97/1374 [00:01<00:24, 51.64it/s]
99 no data
100 no data
101 no data
102 no data
                                                                               1
03 no data
104 no data                                 | 103/1374 [00:02<00:24, 51.79it/s]
105 no data
106 no data
107 no data
108 no data
                                                                               1
09 no data
110 no data                                 | 109/1374 [00:02<00:25, 49.45it/s]
111 no data
112 no data
113 no data
114 no data
                                                                               1
15 no data
116 no data                                 | 115/1374 [00:02<00:25, 50.10it/s]
117 no data
118 no data
119 no data
120 no data
                                                                               1
21 no data
122 no data                                 | 121/1374 [00:02<00:24, 50.57it/s]
123 no data
124 no data
125 no data
126 no data
                                                                               1
27 no data
128 no data                                 | 127/1374 [00:02<00:24, 51.03it/s]
129 no data
130 no data
131 no data
132 no data
                                                                               1
33 no data
134 no data                                 | 133/1374 [00:02<00:24, 51.22it/s]
135 no data
136 no data
137 no data
138 no data
                                                                               1
39 no data
140 no data                                 | 139/1374 [00:02<00:24, 51.36it/s]
141 no data
142 no data
143 no data
144 no data
                                                                               1
45 no data
146 no data                                 | 145/1374 [00:02<00:23, 51.46it/s]
147 no data
148 no data
149 no data
150 no data
                                                                               1
51 no data
152 no data                                 | 151/1374 [00:03<00:23, 51.39it/s]
153 no data
154 no data
155 no data
156 no data
                                                                               1
57 no data
158 no data                                 | 157/1374 [00:03<00:23, 51.48it/s]
159 no data
160 no data
161 no data
162 no data
                                                                               1
63 no data
164 no data                                 | 163/1374 [00:03<00:23, 51.81it/s]
165 no data
166 no data
167 no data
168 no data
                                                                               1
69 no data
170 no data                                 | 169/1374 [00:03<00:23, 51.91it/s]
171 no data
172 no data
173 no data
174 no data
                                                                               1
75 no data
176 no data                                 | 175/1374 [00:03<00:23, 51.84it/s]
177 no data
178 no data
179 no data
180 no data
                                                                               1
81 no data
182 no data                                 | 181/1374 [00:03<00:23, 51.79it/s]
183 no data
184 no data
185 no data
186 no data
                                                                               1
87 no data
188 no data                                 | 187/1374 [00:03<00:22, 51.76it/s]
189 no data
190 no data
191 no data
192 no data
                                                                               1
93 no data
194 no data                                 | 193/1374 [00:03<00:22, 51.87it/s]
195 no data
196 no data
197 no data
198 no data
                                                                               1
99 no data
200 no data                                 | 199/1374 [00:03<00:22, 51.82it/s]
201 no data
202 no data
203 no data
204 no data
                                                                               2
05 no data
206 no data                                 | 205/1374 [00:04<00:22, 51.78it/s]
207 no data
208 no data
209 no data
210 no data
                                                                               2
11 no data
212 no data                                 | 211/1374 [00:04<00:22, 51.75it/s]
213 no data
214 no data
215 no data
216 no data
                                                                               2
17 no data
218 no data?                                | 217/1374 [00:04<00:22, 51.86it/s]
219 no data
220 no data
221 no data
222 no data
                                                                               2
23 no data
 16%|██████?                                | 223/1374 [00:04<00:22, 51.81it/s]

                                                                               1
119 no data
1120 no data███████████████████████?       | 1119/1374 [00:49<00:04, 52.43it/s]
1121 no data
1122 no data
1123 no data
1124 no data
                                                                               1
125 no data
1126 no data████████████████████████       | 1125/1374 [00:49<00:04, 52.48it/s]
1127 no data
1128 no data
1129 no data
1130 no data
                                                                               1
131 no data
1132 no data████████████████████████?      | 1131/1374 [00:49<00:04, 52.65it/s]
1133 no data
1134 no data
1135 no data
1136 no data
                                                                               1
137 no data
1138 no data████████████████████████?      | 1137/1374 [00:50<00:04, 52.63it/s]
1139 no data
1140 no data
1141 no data
1142 no data
                                                                               1
143 no data
1144 no data█████████████████████████      | 1143/1374 [00:50<00:04, 52.76it/s]
1145 no data
1146 no data
1147 no data
1148 no data
                                                                               1
149 no data
1150 no data████████████████████████?      | 1149/1374 [00:50<00:04, 52.85it/s]
1151 no data
1152 no data
1153 no data
1154 no data
                                                                               1
155 no data
1156 no data████████████████████████?      | 1155/1374 [00:50<00:04, 53.05it/s]
1157 no data
1158 no data
1159 no data
1160 no data
                                                                               1
161 no data
1162 no data█████████████████████████      | 1161/1374 [00:50<00:04, 53.06it/s]
1163 no data
1164 no data
1165 no data
1166 no data
                                                                               1
167 no data
1168 no data█████████████████████████?     | 1167/1374 [00:50<00:03, 53.20it/s]
1169 no data
1170 no data
1171 no data
1172 no data
                                                                               1
173 no data
1174 no data█████████████████████████?     | 1173/1374 [00:50<00:03, 53.02it/s]
1175 no data
1176 no data
1177 no data
1178 no data
                                                                               1
179 no data
1180 no data██████████████████████████     | 1179/1374 [00:50<00:03, 53.17it/s]
1181 no data
1182 no data
1183 no data
1184 no data
                                                                               1
185 no data
1186 no data█████████████████████████?     | 1185/1374 [00:50<00:03, 51.36it/s]
1187 no data
1188 no data
1189 no data
1190 no data
                                                                               1
191 no data
1192 no data█████████████████████████?     | 1191/1374 [00:51<00:03, 51.86it/s]
1193 no data
1194 no data
1195 no data
1196 no data
                                                                               1
197 no data
1198 no data██████████████████████████     | 1197/1374 [00:51<00:03, 51.94it/s]
1199 no data
1200 no data
1201 no data
1202 no data
                                                                               1
203 no data
1204 no data██████████████████████████?    | 1203/1374 [00:51<00:03, 52.14it/s]
1205 no data
1206 no data
1207 no data
1208 no data
                                                                               1
209 no data
1210 no data██████████████████████████?    | 1209/1374 [00:51<00:03, 52.41it/s]
1211 no data
1212 no data
1213 no data
1214 no data
                                                                               1
215 no data
1216 no data███████████████████████████    | 1215/1374 [00:51<00:03, 52.60it/s]
1217 no data
1218 no data
1219 no data
1220 no data
                                                                               1
221 no data
1222 no data██████████████████████████?    | 1221/1374 [00:51<00:02, 52.46it/s]
1223 no data
1224 no data
1225 no data
1226 no data
                                                                               1
227 no data
1228 no data██████████████████████████?    | 1227/1374 [00:51<00:02, 52.36it/s]
1229 no data
1230 no data
1231 no data
1232 no data
                                                                               1
233 no data
1234 no data███████████████████████████    | 1233/1374 [00:51<00:02, 52.30it/s]
1235 no data
1236 no data
1237 no data
1238 no data
                                                                               1
239 no data
1240 no data███████████████████████████?   | 1239/1374 [00:52<00:02, 48.92it/s]
1241 no data
1242 no data
1243 no data
1244 no data
                                                                               1
245 no data
1246 no data███████████████████████████?   | 1245/1374 [00:52<00:02, 49.85it/s]
1247 no data
1248 no data
1249 no data
1250 no data
                                                                               1
251 no data
1252 no data████████████████████████████   | 1251/1374 [00:52<00:02, 50.38it/s]
1253 no data
1254 no data
1255 no data
1256 no data
                                                                               1
257 no data
1258 no data███████████████████████████?   | 1257/1374 [00:52<00:02, 50.77it/s]
1259 no data
1260 no data
1261 no data
1262 no data
                                                                               1
263 no data
1264 no data███████████████████████████?   | 1263/1374 [00:52<00:02, 51.57it/s]
1265 no data
1266 no data
1267 no data
1268 no data
                                                                               1
269 no data
1270 no data████████████████████████████   | 1269/1374 [00:52<00:02, 51.87it/s]
1271 no data
1272 no data
1273 no data
1274 no data
                                                                               1
275 no data
1276 no data████████████████████████████?  | 1275/1374 [00:52<00:01, 52.09it/s]
1277 no data
1278 no data
1279 no data
1280 no data
                                                                               1
281 no data
1282 no data████████████████████████████?  | 1281/1374 [00:52<00:01, 52.24it/s]
1283 no data
1284 no data
1285 no data
1286 no data
                                                                               1
287 no data
1288 no data█████████████████████████████  | 1287/1374 [00:52<00:01, 51.80it/s]
1289 no data
1290 no data
1291 no data
1292 no data
                                                                               1
293 no data
1294 no data████████████████████████████?  | 1293/1374 [00:53<00:01, 51.63it/s]
1295 no data
1296 no data
1297 no data
1298 no data
                                                                               1
299 no data
1300 no data████████████████████████████?  | 1299/1374 [00:53<00:01, 51.78it/s]
1301 no data
1302 no data
1303 no data
1304 no data
                                                                               1
305 no data
1306 no data█████████████████████████████  | 1305/1374 [00:53<00:01, 51.49it/s]
1307 no data
1308 no data
1309 no data
1310 no data
                                                                               1
311 no data
1312 no data█████████████████████████████? | 1311/1374 [00:53<00:01, 51.81it/s]
1313 no data
1314 no data
1315 no data
1316 no data
                                                                               1
317 no data
1318 no data█████████████████████████████? | 1317/1374 [00:53<00:01, 51.64it/s]
1319 no data
1320 no data
1321 no data
1322 no data
                                                                               1
323 no data
1324 no data██████████████████████████████ | 1323/1374 [00:53<00:00, 51.92it/s]
1325 no data
1326 no data
1327 no data
1328 no data
                                                                               1
329 no data
1330 no data█████████████████████████████? | 1329/1374 [00:53<00:00, 51.99it/s]
1331 no data
1332 no data
1333 no data
1334 no data
                                                                               1
335 no data
1336 no data█████████████████████████████? | 1335/1374 [00:53<00:00, 52.30it/s]
1337 no data
1338 no data
1339 no data
1340 no data
                                                                               1
341 no data
1342 no data██████████████████████████████ | 1341/1374 [00:54<00:00, 52.25it/s]
1343 no data
1344 no data
1345 no data
1346 no data
                                                                               1
347 no data
1348 no data██████████████████████████████?| 1347/1374 [00:54<00:00, 52.22it/s]
1349 no data
1350 no data
1351 no data
1352 no data
                                                                               1
353 no data
1354 no data██████████████████████████████?| 1353/1374 [00:54<00:00, 52.06it/s]
1355 no data
1356 no data
1357 no data
1358 no data
                                                                               1
359 no data
1360 no data███████████████████████████████| 1359/1374 [00:54<00:00, 52.08it/s]
1361 no data
1362 no data
1363 no data
1364 no data
                                                                               1
365 no data
1366 no data██████████████████████████████?| 1365/1374 [00:54<00:00, 52.10it/s]
1367 no data
1368 no data
1369 no data
1370 no data
                                                                               1
371 no data
1372 no data██████████████████████████████?| 1371/1374 [00:54<00:00, 52.38it/s]
1373 no data
100%|██████████████████████████████████████| 1374/1374 [00:54<00:00, 25.15it/s]
]

</p></details>

**How to Reproduce the problem**
1. Go to 'Analyze video'
2. Click on 'Select video' (.mp4)
3. Click Step 1: analyze video
4. Click Step 2: convert into tracklets
5. When proceeding to refining tracklets, I launch GUI and I can only see/refine 1-2 seconds of the video (with less iteration, 20.000 for instance, I could not even see this and the "OSError: tracklets are empty" error showed up)

**Screenshots**
![Screenshot (8)](https://user-images.githubusercontent.com/75975343/102067968-1d721200-3dfc-11eb-91d8-2db409fe8f5d.png)
![Screenshot (9)](https://user-images.githubusercontent.com/75975343/102067983-24008980-3dfc-11eb-8b44-cd37f244b703.png)

**Additional context**
I hope I filled in the form in the right way and gave enough information

**Comment by MMathisLab** [comment]
Did you search other issues?

**Comment by alecarlucci97** [comment]
> Did you search other issues?

It looks like when I try to analyze the video, it counts only few frames (usually around 50, last trial it was 49) and then it stops. When processing all the frames it says "no data" as shown in the second screenshot.
I read on other threads that it could be due to a corrupted video? Could you guide me through the steps for using VideoReader to make sure that is the problem? I tried to run the code, but I'm at the beginning with programming and I must have missed something.
It's still weird that all the videos taken with a GoPro Hero 8 turn out to be corrupted...
Any help/insight is well accepted.
Thank you!

**Comment by jeylau** [comment]
Hey @alecarlucci97, a quick search would point you there https://github.com/DeepLabCut/DeepLabCut/issues/982#issuecomment-723480607. Give it a try and let us know :)
