### ISSUE TITLE
3Deeplabcut calibration

### ISSUE THREAD

**Issue by maristanye** [DeepLabCut/DeepLabCut#1039]
**Your Operating system and DeepLabCut version**
Windows 10
Version 2.1.8.2 on Google Collab

**Describe the problem**

Hello,
while trying to calibrate my cameras for 3D deeplabcut usage I always get the following message: Corners not found for the image xxx. Even after binarizing the image to enhance contrasts it was not able to find the corners (see image).
![camera1_1](https://user-images.githubusercontent.com/62014527/102777107-406a6c00-4390-11eb-9bce-99ec24ecc054.jpg).
Any other deeplabcut usage is working perfectly.

Please place code inside this:

<details><summary>Code output</summary><p>
import os
os.environ["DLClight"]="True"
import deeplabcut
lel = '/content/drive/My Drive/3DLick-Edu-2020-10-19-3d/config.yaml'
deeplabcut.calibrate_cameras(lel, cbrow =7,cbcol =9,calibrate=False,alpha=0.9)
[Corners not found for the image camera1_1.jpg]

**Config.yaml:**

Project definitions (do not edit)
Task: 3DLick
scorer: Edu
date: Oct19

Project path (change when moving around)
project_path: /content/drive/My Drive/3DLick-Edu-2020-10-19-3d

Plotting configuration
skeleton:     # Note that the pairs must be defined, as you want them linked!
- -
    
- - tongue
  - Lickport
- - Nose
skeleton_color: black
pcutoff: 0.4
colormap: jet
dotsize: 15
alphaValue: 0.8
markerType: '*'
markerColor: r

Number of cameras, camera names, path of the config files, shuffle index and trainingsetindex used to analyze videos:
num_cameras: 2
camera_names:
- camera1_
- camera2_
scorername_3d: DLC_3D # Enter the scorer name for the 3D output
video_sets:
bodyparts:
start:
stop:
numframes2pick:
alphavalue:
TrainingFraction:
iteration:
resnet:
snapshotindex:
batch_size:
cropping:
x1:
x2:
y1:
y2:
corner2move2:
move2corner:
config_file_right_: C:\Users\deepl\RightTrackLicking-Edu-2020-10-05\config.yaml
config_file_left_: C:\Users\deepl\LeftTrackLicking-Edu-2020-09-30\config.yaml
shuffle_camera-1: 1
trainingsetindex_camera-1: 0
shuffle_camera-2: 1
trainingsetindex_camera-2: 0

**Comment by MMathisLab** [comment]
This is based on openCV code; you should try with the demo data first to be sure the code works for you. If it cannot find the corners, that indicates you either have the # of corners set wrongly, or your images will not work. 

also note your skeleton is incorrectly defined.

**Comment by jeylau** [comment]
Hey @maristanye, we sadly have no control over corner detection, as it is handled by OpenCV. One suggestion though: since it seems that a white border is expected around the board, you could try to invert the image (this is the relevant post I had found https://stackoverflow.com/a/60625610, maybe that helps). I'm closing the issue for now, but feel free to reopen it if you feel there is anything we can do on DLC's side.
