### ISSUE TITLE
Missing resnet_v1_50.ckpt - No valid checkpoint. (Downloading pre-trained weights from TensorFlow)

### ISSUE THREAD

**Issue by Donnypickels** [DeepLabCut/DeepLabCut#104]
**Your Operating system and DeepLabCut version**

Windows 10, with an Anaconda Env, & DeepLabCut 2.0

I've done the installation of DLC and am trying to get through the "Demo_labeledexample_MouseReaching".
However, when I'm trying to train I get the following message:
ValueError: The passed save_path is not a valid checkpoint: C:\Users\Beheerder\Anaconda3\envs\Deeplabcut\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt

I've checked and the resnet_v1_50.ckpt does not exist. 
Is there any way to resolve this?

Thanks,
Donny

**Comment by MMathisLab** [comment]
I understand. You just need to go to that folder in “cmd” - you’ll need git bash - and then run download as described. Otherwise, the other issue is permissions. Check out the other troubleshooting tips... and/or consider joining slack.

**Comment by AlexEMG** [comment]
You can also dowloand it "manually" from ```http://download.tensorflow.org/models/resnet_v1_50_2016_08_28.tar.gz```
```http://download.tensorflow.org/models/resnet_v1_101_2016_08_28.tar.gz```
then unpack it and put in that folder... 

Anyway, the bash script should take care of this...

**Comment by Donnypickels** [comment]
Thanks for the help, I figured it out!
It's running now and I believe it is working fine!

Thanks!

**Comment by sidi021** [comment]
Hello,
![Screenshot_20211027_164103](https://user-images.githubusercontent.com/86066864/139089967-baf39122-b348-4185-af8f-35b1ee79f435.png)


I have a some problem, those instruction don't work in Singuarity ?

thanks !
Sidi

**Comment by MMathisLab** [comment]
if you don't have the permission in the container, this indeed will not work; but you can download independently (or change permissions)

**Comment by sidi021** [comment]
thanks you,
I have the permission, just I don't know why 'sudo' don't work in singularity ?
when I don't work in singularity,  the folder is not compress. I downloaded the site tensorflow .
![Screenshot_20211027_174953](https://user-images.githubusercontent.com/86066864/139102110-1967ab95-cb11-4997-8871-2bf73be1cf2d.png)

how I can change permission or solve it with command lines ?

**Comment by MMathisLab** [comment]
I'm not sure, as we don't use singularity; maybe post on the forum and see if other users have thoughts! https://forum.image.sc/tag/deeplabcut 

(we use docker, and provide new containers now, so maybe worth checking out)

**Comment by sidi021** [comment]
okay, thank you !
