### ISSUE TITLE
CalledProcessError: Command 'ffprobe -i [ windows 10 updates break ffmpeg installtion]

### ISSUE THREAD

**Issue by FelixSWue** [DeepLabCut/DeepLabCut#1041]
- OS: Windows10
 - DeepLabCut Version 2.1.9
 - DeepLabCut mode: multi-animal tracking

### I analyzed a video which I after that wanted to use for refining the network. At the step of outlier frames, there was popping up the attached error (see attached picture)

CODE:
`Method`  jump  found  7060  putative outlier frames.
Do you want to proceed with extracting  10  of those?
If this list is very large, perhaps consider changing the parameters (start, stop, p_bound, comparisonbodyparts) or use a different method.
yes/noyes
Frames from video new_trim_1  already extracted (more will be added)!
Loading video...
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
~\.conda\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\extract_outlier_frames.py in extract_outlier_frames(self, event)
    213             trainingsetindex=self.trainingindex.GetValue(),
    214             outlieralgorithm=self.algotype.GetValue(),
--> 215             track_method=tracker,
    216         )
    217 

~\.conda\envs\DLC-GPU\lib\site-packages\deeplabcut\refine_training_dataset\outlier_frames.py in extract_outlier_frames(config, videos, videotype, shuffle, trainingsetindex, outlieralgorithm, comparisonbodyparts, epsilon, p_bound, ARdegree, MAdegree, alpha, extractionalgorithm, automatic, cluster_resizewidth, cluster_color, opencv, savelabeled, destfolder, modelprefix, track_method)
    268                         cluster_resizewidth,
    269                         cluster_color,
--> 270                         savelabeled,
    271                     )
    272                 else:

~\.conda\envs\DLC-GPU\lib\site-packages\deeplabcut\refine_training_dataset\outlier_frames.py in ExtractFramesbasedonPreselection(Index, extractionalgorithm, Dataframe, dataname, video, cfg, config, opencv, cluster_resizewidth, cluster_color, savelabeled)
    425         vid = VideoWriter(video)
    426         fps = vid.fps
--> 427         duration = vid.calc_duration()
    428     else:
    429         from moviepy.editor import VideoFileClip

~\.conda\envs\DLC-GPU\lib\site-packages\deeplabcut\utils\auxfun_videos.py in calc_duration(self, robust)
     83             )
     84             output = subprocess.check_output(
---> 85                 command, shell=True, stderr=subprocess.STDOUT
     86             )
     87             return float(output)

~\.conda\envs\DLC-GPU\lib\subprocess.py in check_output(timeout, *popenargs, **kwargs)
    409 
    410     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--> 411                **kwargs).stdout
    412 
    413 

~\.conda\envs\DLC-GPU\lib\subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    510         if check and retcode:
    511             raise CalledProcessError(retcode, process.args,
--> 512                                      output=stdout, stderr=stderr)
    513     return CompletedProcess(process.args, retcode, stdout, stderr)
    514 

CalledProcessError: Command 'ffprobe -i "D:\DeepLabCut_Projekte\2020_Tail_Suspension_Rodent_DLC_network\2020-12-18_neue_Videos_DYT1KI_zum_Trainieren\new_Videos_trim\new_trim_1.mp4" -show_entries format=duration -v quiet -of csv="p=0"' returned non-zero exit status 1.

![Unbenannt](https://user-images.githubusercontent.com/76441980/102794453-b16b4d00-43ab-11eb-9b49-f026f5fc9f32.png)

**Comment by jeylau** [comment]
Before that commit 53b44a02262934c2c2ca898e9ff6f88a5c0cc6a0, we relied on ffprobe to get a video's duration in a robust manner. Since something may be wrong or missing with your ffmpeg installation, you could either download it here [https://ffmpeg.org/download.html](url) or reinstall it directly using chocolatey [https://chocolatey.org/packages/ffmpeg](url)

**Comment by MMathisLab** [comment]
If you search the issues first, it will take you to this. Windows update can break ffmpeg, so you just need to reinstall it: https://github.com/DeepLabCut/DeepLabCut/issues/1002
