### ISSUE TITLE
3D pose estimation using deeplabcut /3deeplabcut

### ISSUE THREAD

**Issue by RebWeb** [DeepLabCut/DeepLabCut#1043]
Hi everyone, 

I have a question regarding the **3d** project function and I hope to find some answers here.. Is it possible to create a 3d project by using just **one camera recording different perspectives** at the same time (see video below)? I have a mouse walking from one end of a plexiglas container to the other (we are using a _Motorater_), thereby being recorded from below. Since the Motorater is equipped with mirrors, the camera catches three perspectives at one time. Now, before I start figuring out how to address this issue, I would like to know if you could tell me if it is even possible at all to use just one camera to create a 3d project?

https://user-images.githubusercontent.com/67375306/102892271-ea64f980-445f-11eb-8568-bfdcea6828f0.mp4

**Comment by MMathisLab** [comment]
Hi @RebWeb we kindly ask you ask questions on the user forum: https://forum.image.sc/tag/deeplabcut

The way the package is written is it requires two cameras in stereo view, please see docs here: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/Overviewof3D.md
