### ISSUE TITLE
Can DeepLabCut create a trail of where the animal was in the video?

### ISSUE THREAD

**Issue by Hydraulic343** [DeepLabCut/DeepLabCut#1048]
Is there an option in DeepLabCut where the animal leaves behind a colored trail to track where it has been? I have never seen this advertised as a function of DeepLabCut before and I am more used to having skeletons and dots to track body parts.

Is it possible to create an animal trail using DeepLabCut, and if so what would be the code or commands to insert it into the video?

**Comment by MMathisLab** [comment]
HI @Hydraulic343 as you might remember, we really ask you post questions on the user forum, not as github issues. Please see here: https://github.com/DeepLabCut/DeepLabCut#community-support-developers--help

And, yes, if you look at the docstring for `create_labeled_video` fxn you will see you can plot the history of points by passing `trailpoints=10` etc.
