### ISSUE TITLE
Errors running Testscript.py: 

### ISSUE THREAD

**Issue by ghost** [DeepLabCut/DeepLabCut#1050]
**Describe the bug**
I ran the testscript.py in the conda dlc-gpu environment (as defined in DLC-GPU.yaml, downloaded as part of the projefct from github). Initially when running the first time, I got the following error:
ERROR: Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED

As advised in issue #458, to work around this apparent tensorflow issue I added "os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true' " in the testscript.py on line 24, straight after the existing imports (because I'm pretty sure my tensorflow-cuda-cudnn versions are the right combination).
However, I now run into another error when running the testscript.py, right after the 4th training iteration. 

Also, this error causes the testscript to seemingly run itself over and over again, and it cannot be terminated from the terminal (as it keeps starting over, it keeps trying to create the project anew, and generates the error over and over again that the project folder already exists, duh). 

**Desktop (please complete the following information about your system):**
 - OS: Windows10
 - DeepLabCut Version 2.1.9 
- python=3.7, tensorflow-gpu==1.13.1, cudatoolkit  10.0.130, cudnn  7.6.5

**To Reproduce**
1. conda activate dlc-gpu
2. python testscript.py (from the examples folder).
3. See error:

<details><summary>
Starting training....
iteration: 2 loss: 1.4638 lr: 0.001
iteration: 4 loss: 0.7428 lr: 0.001
2020-12-31 10:30:30.966427: W tensorflow/core/kernels/queue_base.cc:277] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[{{node fifo_queue_enqueue}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py", line 91, in load_and_enqueue
    sess.run(enqueue_op, feed_dict=food)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[node fifo_queue_enqueue (defined at C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py:77) ]]

Caused by op 'fifo_queue_enqueue', defined at:
  File "testscript.py", line 138, in <module>
    deeplabcut.train_network(path_config_file)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 189, in train_network
    allow_growth=allow_growth,
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py", line 172, in train
    batch, enqueue_op, placeholders = setup_preloading(batch_spec)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py", line 77, in setup_preloading
    enqueue_op = q.enqueue(placeholders_list)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 345, in enqueue
    self._queue_ref, vals, name=scope)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 4158, in queue_enqueue_v2
    timeout_ms=timeout_ms, name=name)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

CancelledError (see above for traceback): Enqueue operation was cancelled
         [[node fifo_queue_enqueue (defined at C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py:77) ]]</summary><p>

```python

#my modified testscript.py, the only line I added to the original was line 25, to set allow growth to true.
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct  2 13:56:11 2018
@author: alex

DEVELOPERS:
This script tests various functionalities in an automatic way.

It should take about 3:30 minutes to run this in a CPU.
It should take about 1:30 minutes on a GPU (incl. downloading the ResNet weights)

It produces nothing of interest scientifically.
"""

task = "TEST"  # Enter the name of your experiment Task
scorer = "Alex"  # Enter the name of the experimenter/labeler

import os, subprocess, deeplabcut
from pathlib import Path
import pandas as pd
import numpy as np
import platform

os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'

print("Imported DLC!")
basepath = os.path.dirname(os.path.abspath("testscript.py"))
videoname = "reachingvideo1"
video = [
    os.path.join(
        basepath, "Reaching-Mackenzie-2018-08-30", "videos", videoname + ".avi"
    )
]

# For testing a color video:
# videoname='baby4hin2min'
# video=[os.path.join('/home/alex/Desktop/Data',videoname+'.mp4')]
# to test destination folder:
# dfolder=basepath

dfolder = None
net_type = "resnet_50"  #'mobilenet_v2_0.35' #'resnet_50'
augmenter_type = "default"  # = imgaug!!
augmenter_type2 = "scalecrop"

if platform.system() == "Darwin" or platform.system() == "Windows":
    print("On Windows/OSX tensorpack is not tested by default.")
    augmenter_type3 = "imgaug"
else:
    augmenter_type3 = "tensorpack"  # Does not work on WINDOWS

numiter = 5

print("CREATING PROJECT")
path_config_file = deeplabcut.create_new_project(task, scorer, video, copy_videos=True)

cfg = deeplabcut.auxiliaryfunctions.read_config(path_config_file)
cfg["numframes2pick"] = 5
cfg["pcutoff"] = 0.01
cfg["TrainingFraction"] = [0.8]
cfg["skeleton"] = [["bodypart1", "bodypart2"], ["bodypart1", "bodypart3"]]

deeplabcut.auxiliaryfunctions.write_config(path_config_file, cfg)

print("EXTRACTING FRAMES")
deeplabcut.extract_frames(path_config_file, mode="automatic", userfeedback=False)

print("CREATING-SOME LABELS FOR THE FRAMES")
frames = os.listdir(os.path.join(cfg["project_path"], "labeled-data", videoname))
# As this next step is manual, we update the labels by putting them on the diagonal (fixed for all frames)
for index, bodypart in enumerate(cfg["bodyparts"]):
    columnindex = pd.MultiIndex.from_product(
        [[scorer], [bodypart], ["x", "y"]], names=["scorer", "bodyparts", "coords"]
    )
    frame = pd.DataFrame(
        100 + np.ones((len(frames), 2)) * 50 * index,
        columns=columnindex,
        index=[os.path.join("labeled-data", videoname, fn) for fn in frames],
    )
    if index == 0:
        dataFrame = frame
    else:
        dataFrame = pd.concat([dataFrame, frame], axis=1)

dataFrame.to_csv(
    os.path.join(
        cfg["project_path"],
        "labeled-data",
        videoname,
        "CollectedData_" + scorer + ".csv",
    )
)
dataFrame.to_hdf(
    os.path.join(
        cfg["project_path"],
        "labeled-data",
        videoname,
        "CollectedData_" + scorer + ".h5",
    ),
    "df_with_missing",
    format="table",
    mode="w",
)

print("Plot labels...")

deeplabcut.check_labels(path_config_file)

print("CREATING TRAININGSET")
deeplabcut.create_training_dataset(
    path_config_file, net_type=net_type, augmenter_type=augmenter_type
)

posefile = os.path.join(
    cfg["project_path"],
    "dlc-models/iteration-"
    + str(cfg["iteration"])
    + "/"
    + cfg["Task"]
    + cfg["date"]
    + "-trainset"
    + str(int(cfg["TrainingFraction"][0] * 100))
    + "shuffle"
    + str(1),
    "train/pose_cfg.yaml",
)

DLC_config = deeplabcut.auxiliaryfunctions.read_plainconfig(posefile)
DLC_config["save_iters"] = numiter
DLC_config["display_iters"] = 2
DLC_config["multi_step"] = [[0.001, numiter]]

print("CHANGING training parameters to end quickly!")
deeplabcut.auxiliaryfunctions.write_plainconfig(posefile, DLC_config)

print("TRAIN")
deeplabcut.train_network(path_config_file)

print("EVALUATE")
deeplabcut.evaluate_network(path_config_file, plotting=True)
# deeplabcut.evaluate_network(path_config_file,plotting=True,trainingsetindex=33)
print("CUT SHORT VIDEO AND ANALYZE (with dynamic cropping!)")

# Make super short video (so the analysis is quick!)

try:  # you need ffmpeg command line interface
    # subprocess.call(['ffmpeg','-i',video[0],'-ss','00:00:00','-to','00:00:00.4','-c','copy',newvideo])
    newvideo = deeplabcut.ShortenVideo(
        video[0],
        start="00:00:00",
        stop="00:00:01",
        outsuffix="short",
        outpath=os.path.join(cfg["project_path"], "videos"),
    )
except:  # if ffmpeg is broken/missing
    print("using alternative method")
    newvideo = os.path.join(cfg["project_path"], "videos", videoname + "short.mp4")
    from moviepy.editor import VideoFileClip, VideoClip

    clip = VideoFileClip(video[0])
    clip.reader.initialize()

    def make_frame(t):
        return clip.get_frame(1)

    newclip = VideoClip(make_frame, duration=1)
    newclip.write_videofile(newvideo, fps=30)

vname = Path(newvideo).stem

deeplabcut.analyze_videos(
    path_config_file,
    [newvideo],
    save_as_csv=True,
    destfolder=dfolder,
    dynamic=(True, 0.1, 5),
)

print("analyze again...")
deeplabcut.analyze_videos(
    path_config_file, [newvideo], save_as_csv=True, destfolder=dfolder
)

print("CREATE VIDEO")
deeplabcut.create_labeled_video(
    path_config_file, [newvideo], destfolder=dfolder, save_frames=True
)

print("Making plots")
deeplabcut.plot_trajectories(path_config_file, [newvideo], destfolder=dfolder)

print("EXTRACT OUTLIERS")
deeplabcut.extract_outlier_frames(
    path_config_file,
    [newvideo],
    outlieralgorithm="jump",
    epsilon=0,
    automatic=True,
    destfolder=dfolder,
)

deeplabcut.extract_outlier_frames(
    path_config_file,
    [newvideo],
    outlieralgorithm="fitting",
    automatic=True,
    destfolder=dfolder,
)

file = os.path.join(
    cfg["project_path"],
    "labeled-data",
    vname,
    "machinelabels-iter" + str(cfg["iteration"]) + ".h5",
)

print("RELABELING")
DF = pd.read_hdf(file, "df_with_missing")
DLCscorer = np.unique(DF.columns.get_level_values(0))[0]
DF.columns.set_levels([scorer.replace(DLCscorer, scorer)], level=0, inplace=True)
DF = DF.drop("likelihood", axis=1, level=2)
DF.to_csv(
    os.path.join(
        cfg["project_path"], "labeled-data", vname, "CollectedData_" + scorer + ".csv"
    )
)
DF.to_hdf(
    os.path.join(
        cfg["project_path"], "labeled-data", vname, "CollectedData_" + scorer + ".h5"
    ),
    "df_with_missing",
    format="table",
    mode="w",
)

print("MERGING")
deeplabcut.merge_datasets(path_config_file)  # iteration + 1

print("CREATING TRAININGSET")
deeplabcut.create_training_dataset(
    path_config_file, net_type=net_type, augmenter_type=augmenter_type2
)

cfg = deeplabcut.auxiliaryfunctions.read_config(path_config_file)
posefile = os.path.join(
    cfg["project_path"],
    "dlc-models/iteration-"
    + str(cfg["iteration"])
    + "/"
    + cfg["Task"]
    + cfg["date"]
    + "-trainset"
    + str(int(cfg["TrainingFraction"][0] * 100))
    + "shuffle"
    + str(1),
    "train/pose_cfg.yaml",
)
DLC_config = deeplabcut.auxiliaryfunctions.read_plainconfig(posefile)
DLC_config["save_iters"] = numiter
DLC_config["display_iters"] = 1
DLC_config["multi_step"] = [[0.001, numiter]]

print("CHANGING training parameters to end quickly!")
deeplabcut.auxiliaryfunctions.write_config(posefile, DLC_config)

print("TRAIN")
deeplabcut.train_network(path_config_file)

try:  # you need ffmpeg command line interface
    # subprocess.call(['ffmpeg','-i',video[0],'-ss','00:00:00','-to','00:00:00.4','-c','copy',newvideo])
    newvideo2 = deeplabcut.ShortenVideo(
        video[0],
        start="00:00:00",
        stop="00:00:01",
        outsuffix="short2",
        outpath=os.path.join(cfg["project_path"], "videos"),
    )

except:  # if ffmpeg is broken
    newvideo2 = os.path.join(cfg["project_path"], "videos", videoname + "short2.mp4")
    from moviepy.editor import VideoFileClip, VideoClip

    clip = VideoFileClip(video[0])
    clip.reader.initialize()

    def make_frame(t):
        return clip.get_frame(1)

    newclip = VideoClip(make_frame, duration=1)
    newclip.write_videofile(newvideo2, fps=30)

vname = Path(newvideo2).stem

print("Inference with direct cropping")
deeplabcut.analyze_videos(
    path_config_file,
    [newvideo2],
    save_as_csv=True,
    destfolder=dfolder,
    cropping=[0, 50, 0, 50],
)

print("Extracting skeleton distances, filter and plot filtered output")
deeplabcut.analyzeskeleton(
    path_config_file, [newvideo2], save_as_csv=True, destfolder=dfolder
)
deeplabcut.filterpredictions(path_config_file, [newvideo2])

# deeplabcut.create_labeled_video(path_config_file,[newvideo], destfolder=dfolder,filtered=True)
deeplabcut.create_labeled_video(
    path_config_file,
    [newvideo2],
    destfolder=dfolder,
    displaycropped=True,
    filtered=True,
)

print("Creating a Johansson video!")
deeplabcut.create_labeled_video(
    path_config_file, [newvideo], destfolder=dfolder, keypoints_only=True
)

deeplabcut.plot_trajectories(
    path_config_file, [newvideo2], destfolder=dfolder, filtered=True
)

print("ALL DONE!!! - default cases without Tensorpack loader are functional.")

print("CREATING TRAININGSET for shuffle 2")
print("will be used for 3D testscript...")
# TENSORPACK could fail in WINDOWS...
deeplabcut.create_training_dataset(
    path_config_file, Shuffles=[2], net_type=net_type, augmenter_type=augmenter_type3
)

posefile = os.path.join(
    cfg["project_path"],
    "dlc-models/iteration-"
    + str(cfg["iteration"])
    + "/"
    + cfg["Task"]
    + cfg["date"]
    + "-trainset"
    + str(int(cfg["TrainingFraction"][0] * 100))
    + "shuffle"
    + str(2),
    "train/pose_cfg.yaml",
)

DLC_config = deeplabcut.auxiliaryfunctions.read_plainconfig(posefile)
DLC_config["save_iters"] = 10
DLC_config["display_iters"] = 2
DLC_config["multi_step"] = [[0.001, 10]]

print("CHANGING training parameters to end quickly!")
deeplabcut.auxiliaryfunctions.write_plainconfig(posefile, DLC_config)

print("TRAINING shuffle 2, with smaller allocated memory")
deeplabcut.train_network(path_config_file, shuffle=2, allow_growth=True)

print("ANALYZING some individual frames")
deeplabcut.analyze_time_lapse_frames(
    path_config_file, os.path.join(cfg["project_path"], "labeled-data/reachingvideo1/")
)

print("Export model...")
deeplabcut.export_model(path_config_file, shuffle=2, make_tar=False)


trainIndices, testIndices = deeplabcut.mergeandsplit(
    path_config_file, trainindex=0, uniform=True
)

deeplabcut.create_training_dataset(
    path_config_file,
    Shuffles=[4, 5],
    trainIndices=[trainIndices, trainIndices],
    testIndices=[testIndices, testIndices],
)

print("ALL DONE!!! - default cases are functional.")
print("Re-import DLC with env. variable set to test DLC light mode.")
os.environ["DLClight"] = "True"
subprocess.call(["python3", "-c", "import deeplabcut"])


```
</p></details>

**Expected behavior**
Testscript running without errors, and not running itself over and over again.

**Screenshots**

**Additional context**

**Comment by MMathisLab** [comment]
if you don't force growth like this, does this happen? Note, that is not the prefered way to deal with `ERROR: Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED` >> allow growth should  be called within the train function, and that is for memory errors, not CUDNN_STATUS_ALLOC_FAILED. 

I would rather follow this: https://github.com/DeepLabCut/DeepLabCut/issues/786#issuecomment-659033233

**Comment by ghost** [comment]
If I don't force growth, I get the 'Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED' error. 
I installed the latest drivers for my nvidia gpu (driver version 460.89), the cuda toolkit 10.0.130  
(alongside previously installed versions 11.2 to run with tensorflow 2.4 for an earlier project),  and cudnn 7.6.5. 
However, as listed here (https://www.tensorflow.org/install/source#gpu), it needs cudnn 7.4. So I installed the 7.4 files in my cuda toolkit 10.0. However, when I do conda list in the dlc-gpu environment, it still lists it is using the cudnn 7.6.5 version and not the 7.4 version. Also after deleting the complete environment and creating it again. System Path variables point to the 10.0 toolkit first, newer versions added to the path after that.
So I really don't know what else to try...

**Comment by ghost** [comment]
Okay I'm pretty sure I have the right versions installed (again, cuda 10.0 and cudnn 7.6.5) and I'm using your conda defined environment. The testscript gives the CUDNN_STATUS_ALLOC_FAILED error, which is all over the internet as a memory issue when it using the GeForce RTX GPU. Anyway, setting force growth (even only as a parameter of the train_network steps in the testscript) does fix this error (again leading me to believe that memory issues were the problem of the earlier CUDNN_STATUS_ALLOC_FAILED error, as stated many times in a lot of issues). However, then initially described queueing error is thrown.

**Comment by ghost** [comment]
See issue #458. As described there, I changed the train_network call in testscript.py to add flag allow growth: deeplabcut.train_network(path_config_file, allow_growth=True) such that it is called within the train function as mentioned.
However, this gives the following warning in the output of the testscript: 
```python
[E tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:50] The TF_FORCE_GPU_ALLOW_GROWTH environment variable is set but could not be parsed: "True". Valid values are "true" or "false". Using original config value of 1. The warning disappears when the train network in the script is changed to deeplabcut.train_network(path_config_file, allow_growth=1). 
```


When I run this testscript though, I'm still getting the error
```python
2021-01-03 23:31:21.935310: W tensorflow/core/kernels/queue_base.cc:277] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[{{node fifo_queue_enqueue}}]].

```
Any clues as to why this happens and how to fix??

**Comment by MMathisLab** [comment]
does the testscript finish? that is just the normal error that stops the training, and we crash it out after a few iterations:

```python
Starting training....
 iteration: 2 loss: 1.4638 lr: 0.001 
iteration: 4 loss: 0.7428 lr: 0.001 
.....

tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled [[{{node fifo_queue_enqueue}}]]
```

**Comment by jeylau** [comment]
@Anske, the CancelledError after the 4th iteration you saw in the console is the expected behavior at testing (as @MMathisLab rightly noted).

**Comment by ghost** [comment]
Ah okay thanks, I have been trying for days to resolve this queueing error, but I can just ignore it :-)...

The next thing going wrong with the testscript on windows is somewhere in executing 
deeplabcut.create_labeled_video(
    path_config_file, [newvideo], destfolder=dfolder, save_frames=True
)
Somehow, something goes wrong here and it starts a never ending loop of importing DLC and creating the project over and over again, output is like this:

The videos are analyzed. Now your research can truly start!
 You can create labeled videos with 'create_labeled_video'
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
CREATE VIDEO
Imported DLC!
On Windows/OSX tensorpack is not tested by default.
CREATING PROJECT
Project "E:\Projects\DeepLabCut\DeepLabCut\examples\TEST-Alex-2021-01-04" already exists!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Projects\DeepLabCut\DeepLabCut\examples\testscript.py", line 56, in <module>
    cfg = deeplabcut.auxiliaryfunctions.read_config(path_config_file)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 165, in read_config
    path = Path(configname)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\pathlib.py", line 1027, in __new__
    self = cls._from_parts(args, init=False)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\pathlib.py", line 674, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\pathlib.py", line 658, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Imported DLC!
On Windows/OSX tensorpack is not tested by default.
CREATING PROJECT
Project "E:\Projects\DeepLabCut\DeepLabCut\examples\TEST-Alex-2021-01-04" already exists!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Projects\DeepLabCut\DeepLabCut\examples\testscript.py", line 56, in <module>
    cfg = deeplabcut.auxiliaryfunctions.read_config(path_config_file)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 165, in read_config
    path = Path(configname)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\pathlib.py", line 1027, in __new__
    self = cls._from_parts(args, init=False)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\pathlib.py", line 674, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Users\avlui\anaconda3\envs\dlc-gpu\lib\pathlib.py", line 658, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

I tried replacing the slashes in the path variables to double slashes but this does not change anything...
