### ISSUE TITLE
Multi-animal DeepLabCut Colab only Analyzes first few seconds of video

### ISSUE THREAD

**Issue by Hydraulic343** [DeepLabCut/DeepLabCut#1051]
I have tried to use the Multi-Animal Colab for DeepLabCut to analyze a 5-6 minute video. I complete all the correct steps, but when I get to the Analyze step, it only analyzes the first couple seconds of the video, but nothing after that. This is an issue that has popped up multiple times and I haven't gotten an answer as to what the issue could be. My video has 22287 total frames, but only 58 of them are detected. Why is it only detecting 58 when it knows there are way more:

Below is the code:

Using snapshot-42000 for model /content/drive/My Drive/Mouse Cohort-Nicole-2020-12-30/dlc-models/iteration-0/Mouse CohortDec30-trainset95shuffle1
Initializing ResNet
Analyzing all the videos in the directory...
Starting to analyze %  /content/drive/My Drive/Mouse Cohort-Nicole-2020-12-30/videos/GOPR1561.mp4
/content/drive/My Drive/Mouse Cohort-Nicole-2020-12-30/videos  already exists!
Loading  /content/drive/My Drive/Mouse Cohort-Nicole-2020-12-30/videos/GOPR1561.mp4
  0%|          | 0/22287 [00:00<?, ?it/s]Duration of video [s]:  371.82 , recorded with  59.94 fps!
Overall # of frames:  22287  found with (before cropping) frame dimensions:  1920 1080
Starting to extract posture
Detected frames:  58
  1%|          | 222/22287 [00:23<38:49,  9.47it/s]
Saving results in /content/drive/My Drive/Mouse Cohort-Nicole-2020-12-30/videos...
The videos are analyzed. Now your research can truly start! 
 You can create labeled videos with 'create_labeled_video'
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
DLC_resnet50_Mouse CohortDec30shuffle1_42000

**Comment by MMathisLab** [comment]
your video is corrupted. This is answered here: https://github.com/DeepLabCut/DeepLabCut/issues/1035, https://github.com/DeepLabCut/DeepLabCut/issues/1001, https://github.com/DeepLabCut/DeepLabCut/issues/1004 -- I have answered your other issues, and you don't respond (see above). Thus, I am not willing to answer new issues asking the same things again.
