### ISSUE TITLE
Corrupt video - Why is my video corrupt?

### ISSUE THREAD

**Issue by Hydraulic343** [DeepLabCut/DeepLabCut#1052]
I am running into errors with analyzing my video in Colab, and I'm being told that the issue is that the video is corrupt. I am not sure what caused the corruption; did the video became corrupted during the DeepLabCut process, or was the video was always corrupted?

Below is the code:

_Using snapshot-42000 for model /content/drive/My Drive/Mouse Cohort-Nicole-2020-12-30/dlc-models/iteration-0/Mouse CohortDec30-trainset95shuffle1
Initializing ResNet
Analyzing all the videos in the directory...
Starting to analyze % /content/drive/My Drive/Mouse Cohort-Nicole-2020-12-30/videos/GOPR1561.mp4
/content/drive/My Drive/Mouse Cohort-Nicole-2020-12-30/videos already exists!
Loading /content/drive/My Drive/Mouse Cohort-Nicole-2020-12-30/videos/GOPR1561.mp4
0%| | 0/22287 [00:00<?, ?it/s]Duration of video [s]: 371.82 , recorded with 59.94 fps!
Overall # of frames: 22287 found with (before cropping) frame dimensions: 1920 1080
Starting to extract posture
Detected frames: 58
1%| | 222/22287 [00:23<38:49, 9.47it/s]
Saving results in /content/drive/My Drive/Mouse Cohort-Nicole-2020-12-30/videos...
The videos are analyzed. Now your research can truly start!
You can create labeled videos with 'create_labeled_video'
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
DLC_resnet50_Mouse CohortDec30shuffle1_42000_

I've seen that there is a command to check for video integrity, but I do not know how to run the command or where.

**"from deeplabcut.utils.auxfun_videos import VideoReader

vid = VideoReader('path_to_your_video')
vid.check_integrity()"**

Where do I run this command to check for corruption? In iPython? In Colab? Do I need to have the CPU or the GPU installed?

**Comment by backyardbiomech** [comment]
Think of video files like DNA. Mutations (corruption) occurs when new copies are made, not when it's read, so Deeplabcut cannot corrupt your original videos. Some cameras seem to generate more corrupted files than others. And it doesn't mean that the whole file is ruined or that data is missing; it just means that the modules that deeplabcut depends on for reading videos can't read all of the data. Check the integrity. If it's corrupted, then simply re-encoding the video usually helps.

You can run those lines in ipython or colab, no GPU is needed. 

There are existing discussions and examples in the documentation and on the image.sc forum.
