### ISSUE TITLE
Flickering Skeleton, Dots on Animal Appearing Outside the Cropped Area

### ISSUE THREAD

**Issue by Hydraulic343** [DeepLabCut/DeepLabCut#1053]
I am running into an issue with my labeled video where the dots on the animal are randomly appearing on objects outside of the video area that I cropped during the frame extraction step. I set the cropped area to only be within the box. I thought cropping was meant to prevent DeepLabCut from putting dots anywhere outside of the cropped zone. How do I prevent this from happening? Do I have to crop the original video before I start using DeepLabCut to only include the zone of interest?

Also, when the animal isn't in the frame, the dots go wild and will appear on objects even though the animal clearly isn't in the frame. Are these issues because additional training is needed? My video ran for about 40000 iterations since I am still trying to figure out how DeepLabCut works.

![Picture2](https://user-images.githubusercontent.com/43321657/103462676-f15bf980-4cf4-11eb-9913-33bd8d5571d1.png)
![Picture1](https://user-images.githubusercontent.com/43321657/103462677-f15bf980-4cf4-11eb-9841-43797882a8db.png)

I’m not super familiar with all the different functions of DeepLabCut yet. I haven’t tried training multiple videos at a time, and I haven’t messed around with the different variables in the config file such as pcutoff, alphavalue, or batch_size since I didn’t know what they did. I’ve just been trying to create one video that was relatively stable.

I have multiple videos using mice in various tests: CPA box, restraint test, forced swim, marble test. If I analyze multiple videos at a time, as long as those videos are using the same test in the same setting, can I extract multiple frames from each one to achieve 300+ frames to increase accuracy and tracking?

**Comment by jeylau** [comment]
`displaycropped` is False by default in `deeplabcut.create_labeled_video`, explaining why your labeled video is the full-size one. Anyhow, after only such a short training, it may be that the network will mistake a feature on an object for a bodypart. This detection will most certainly be of very low likelihood though, so increasing pcutoff (the confidence below which detections are not shown in the video) should give you a cleaner output.
