### ISSUE TITLE
Ideal number of frames extracted for 5-6 minute videos

### ISSUE THREAD

**Issue by Hydraulic343** [DeepLabCut/DeepLabCut#1054]
I am running DeepLabCut on multiple 5-6 minute videos, each one has 1 mouse in a fixed room from a top-down angle. How many frames should I extract, and how many iterations should I run, to ensure good tracking and a stable skeleton?

**Comment by jeylau** [comment]
Let us continue the discussion on the forum to avoid duplicates: [https://forum.image.sc/t/ideal-number-of-frames-extracted-for-5-6-minute-videos/47113/3](url)
