### ISSUE TITLE
feature request: frame# choice

### ISSUE THREAD

**Issue by WeissShahaf** [DeepLabCut/DeepLabCut#1055]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i have to relabel a frame, of having to hit "next" on every frame before it, instead of being able to jump to that labeled frame

**Describe the solution you'd like**
a jump to frame button would really help speed relabeling and refining.

**Describe alternatives you've considered**
none

thanks
Shahaf

**Comment by MMathisLab** [comment]
to note, this is a non-standard use of DeepLabCut. We assume you can correctly label as you go, and if you save and close the GUI, it automatically jumps to the first unlabeled frame.

**Comment by WeissShahaf** [comment]
in my case, it always jumps to the first frame. which is already labled.

**Comment by MMathisLab** [comment]
Hmm, that should not happen. What version of DLC are you using? 

@jeylau we rolled back this delete bottom PR, right? // I suspect that might be the culprit ;/.

**Comment by jeylau** [comment]
@MMathisLab, maybe I got it wrong, but I understood it would be a nice feature to have in the refinement GUI if it's not done in one shot. @WeissShahaf, is that correct?

**Comment by WeissShahaf** [comment]
@MMathisLab version 2.2b8.
I'm also having trouble if i delete labels, and try to save it crashes. but if i restart DLC again it works.

@jeylau, i meant in the labeling part. If for some reason a couple labels are off when checking the "check labels" part.

**Comment by MMathisLab** [comment]
^^ @WeissShahaf - please update to 2.1.10.2; the issue is solved; i.e. it will now (again) jump to the last unlabeled frame. Please let me know if that is sufficient.

**Comment by WeissShahaf** [comment]
thanks
