### ISSUE TITLE
issue with ubuntu GPU cuda installation

### ISSUE THREAD

**Issue by ykogr** [DeepLabCut/DeepLabCut#1056]
Hello, I am really new to Deeplabcut. 

I have been troubled with installing Deeplabcut.

OS: Ubuntu 18.04.5 LTS
GPU: NVIDIA GeForce RTX 2080 SUPER 8GB
Anaconda3-2019.07, using the official vertual env (DLC-GPU.yaml; thus Deeplabcut 2.0)

First I followed the official installation guide (https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/installation.md) and I tried to install NVIDIA 384.111 driver. But it yielded an installation error.

```
ERROR: An error occurred while performing the step: "Building kernel modules". See /var/log/nvidia-installer.log for details.

ERROR: An error occurred while performing the step: "Checking to see whether the nvidia kernel module was successfully built".
See /var/log/nvidia-installer.log for details.

ERROR: The nvidia kernel module was not created.

ERROR: Installation has failed. Please see the file '/var/log/nvidia-installer.log' for details. You may find suggestions on
fixing installation problems in the README available on the Linux driver download page at www.nvidia.com.
```

According to NVIDIA developer website, the driver 384.xx is outdated.
https://forums.developer.nvidia.com/t/i-cant-install-nvidia-driver-an-error-occurred-while-performing-the-step-building-kernel-modules/72239
I also tried 410.93 driver referring to this web site, but I got the same error.
https://optogeneticsandneuralengineeringcore.gitlab.io/ONECoreSite/projects/DeepLabCut/

I have tried the newer 450.80.02 driver, but CUDA 11.0 was automatically installed and yielded an error when I ran deeplabcut.train_network(). The error message was like that:
`Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.`

What version of driver should I use? Thank you in advance.

**Comment by MMathisLab** [comment]
Welcome! 

You can use any driver that is compatible with CUDA 10, this being he latest: `CUDA 10.0: 410.48` 

hope that helps: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/installation.md#troubleshooting

**Comment by ykogr** [comment]
Thank you for your prompt reply. Thank you again for developing and maintaining such wonderful software!

According to NVIDIA website, it seems that I can use any driver NVIDIA 410.48 or upper version.
https://docs.nvidia.com/deploy/cuda-compatibility/index.html

Actually, however, before I tried NVIDIA 384.111 driver, I installed 450.80.02 driver.
First, I installed the NVIDIA driver.
`sudo bash NVIDIA-Linux-x86_64-450.80.02.run`.
Next, I tried to install CUDA 10.0 by running
```
sudo dpkg -i cuda-repo-ubuntu1804-10-0-local-10.0.130-410.48_1.0-1_amd64.deb
sudo apt-key add /var/cuda-repo-10-0-local-10.0.130-410.48/7fa2af80.pub
sudo apt-get update
sudo apt-get install cuda-toolkit-10.0
```
Even though I ran these codes, the command `nvidia-smi` returned `CUDA Version: 11.0`. I'm afraid CUDA 11 is out of the support of deeplabcut 2.0.
I guess it is not good for me to install NVIDIA driver first in this case, but is it right? I could really benefit from your expertise.

**Comment by MMathisLab** [comment]
the nvidia-smi can actually show the highest possible CUDA given the driver, it's a bit annoying in that way! So, you likely have cuda 10 installed, you can check in the terminal with: `nvcc -V` 

edit to add, this is exactly how I install it on my machines! https://github.com/DeepLabCut/Docker4DeepLabCut2.0/wiki/Installation-of-NVIDIA-driver-and-CUDA-10

**Comment by ykogr** [comment]
Okay, to know the version of CUDA, I should use `nvcc -V` instead of `nvidia-smi`.
And thank you very much for sharing your installation instructions! I will try your tips now. I'll give you feedback on the results here.

**Comment by ykogr** [comment]
Unfortunately, when I ran the script `sudo sh cuda_10.1.243_418.87.00_linux.run`, my Ubuntu did not accept NVIDIA 418.87.00 driver. Here is the error log (cuda-installer.log):
```
[INFO]: Driver not installed.
[INFO]: Checking compiler version...
[INFO]: gcc location: /usr/bin/gcc

[INFO]: gcc version: gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 

[INFO]: Initializing menu
[INFO]: Setup complete
[INFO]: Components to install: 
[INFO]: Driver
[INFO]: 418.87.00
[INFO]: Executing NVIDIA-Linux-x86_64-418.87.00.run --ui=none --no-questions --accept-license --disable-nouveau --no-cc-version-check --install-libglvnd  2>&1
[INFO]: Finished with code: 256
[ERROR]: Install of driver component failed.
[ERROR]: Install of 418.87.00 failed, quitting
```
I guess newer NVIDIA driver (>418.87) is needed, but upper version of CUDA is automatically accompanies...
Are there any successful installations with newer CUDA and NVIDIA drivers?

**Comment by MMathisLab** [comment]
then I think it is related to your computer/GPU; I just ran this a few days ago successfully... do you have sudo rights on the computer?

**Comment by ykogr** [comment]
Thank you for your prompt response.
Yes, I have sudo rights on my computer. When I ran `sudo sh cuda_10.1.243_418.87.00_linux.run`, the terminal prompted me to enter the password. After I input the password, the process seemed to have progressed halfway.
Here is the output of `ubuntu-drivers devices`. I guess driver 418 is too old for my GPU...
```
== /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0 ==
modalias : pci:v000010DEd00001ED3sv00001558sd00007714bc03sc00i00
vendor   : NVIDIA Corporation
driver   : nvidia-driver-450 - distro non-free
driver   : nvidia-driver-440-server - distro non-free
driver   : nvidia-driver-450-server - distro non-free
driver   : nvidia-driver-455 - distro non-free recommended
driver   : xserver-xorg-video-nouveau - distro free builtin

== /sys/devices/pci0000:00/0000:00:14.3 ==
modalias : pci:v00008086d000006F0sv00008086sd00000074bc02sc80i00
vendor   : Intel Corporation
manual_install: True
driver   : backport-iwlwifi-dkms - distro free

```

**Comment by MMathisLab** [comment]
what GPU do you have?

**Comment by ykogr** [comment]
NVIDIA GeForce RTX 2080 SUPER 8GB.

**Comment by MMathisLab** [comment]
you can use https://www.nvidia.com/Download/driverResults.aspx/164073/en-us; the driver should be installed first. Then computer restarted. Then CUDA, etc

**Comment by ykogr** [comment]
Thank you for your response. Actually, the driver 450.80.02 is the first one I have tried. Then I installed CUDA 10.0 (local deb file), which resulted in the convolution error after I ran `deeplabcut.train_network()`.

**Comment by MMathisLab** [comment]
what version of tensorflow are you using; it would be helpful to put the full traceback here.

**Comment by ykogr** [comment]
Thank you very much. Because I used the virtual environment DLC-GPU downloaded from http://www.mousemotorlab.org/deeplabcut, the version of Tensorflow should have been 1.13.1. Unfortunately, however, Ubuntu in that configuration no longer boot, so I can't find out exactly what it is at this time.

**Comment by MMathisLab** [comment]
note I updated the docs with #1060; I will close this now, but I will check in once you respond again after the restart.
