### ISSUE TITLE
deeplabcut.extract_frames pop-up image does not close in windows

### ISSUE THREAD

**Issue by WernTanj** [DeepLabCut/DeepLabCut#106]
**Your Operating system and DeepLabCut version**
Windows 7, Anaconda Env, DeeplabCut2.x
Browser [firefox]

**Describe the bug**
Call 'deeplabcut.extract_frames(config_path,'automatic','uniform', crop=True, checkcropping=**True**)' the first pop-up image appears. If you close the image, the code stops working i.e. no message appears and no more pop-up images are opened. If you set' checkcropping=**False**' the code works fine and frames from all movies are extracted. 

**To Reproduce**
1. Call 'deeplabcut.extract_frames(config_path,'automatic','uniform', crop=True, checkcropping=True)' on a list of movies 
2. Close the pop-up image
3. Interrupt kernel

**Error**
Reading config file successfully...
Make sure you change the crop parameters in the config.yaml file. The default parameters are set to the video dimensions.

---------------------------------------------------------------------------
```
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-9-b95afbf50395> in <module>
----> 1 deeplabcut.extract_frames(config_path,'automatic','uniform', crop=True, checkcropping=True)

C:\Utilities\Miniconda3\envs\fmi-deeplabcut\lib\site-packages\deeplabcut\generate_training_dataset\frame_extraction.py in extract_frames(config, mode, algo, crop, checkcropping)
    110                     # Add the patch to the Axes
    111                     ax.add_patch(rect)
--> 112                     plt.show()
    113 
    114                     print("The red boundary indicates how the cropped image will look.")

C:\Utilities\Miniconda3\envs\fmi-deeplabcut\lib\site-packages\matplotlib\pyplot.py in show(*args, **kw)
    251     """
    252     global _show
--> 253     return _show(*args, **kw)
    254 
    255 

C:\Utilities\Miniconda3\envs\fmi-deeplabcut\lib\site-packages\matplotlib\backend_bases.py in show(cls, block)
    206                 block = True
    207         if block:
--> 208             cls.mainloop()
    209 
    210     # This method is the one actually exporting the required methods.

C:\Utilities\Miniconda3\envs\fmi-deeplabcut\lib\site-packages\matplotlib\backends\_backend_tk.py in mainloop()
   1071     @staticmethod
   1072     def mainloop():
-> 1073         Tk.mainloop()

C:\Utilities\Miniconda3\envs\fmi-deeplabcut\lib\tkinter\__init__.py in mainloop(n)
    558 def mainloop(n=0):
    559     """Run the main loop of Tcl."""
--> 560     _default_root.tk.mainloop(n)
    561 
    562 getint = int

KeyboardInterrupt: 
```

**Comment by AlexEMG** [comment]
This is why recommend using ```checkcropping=False``` for multiple videos. In other words the workflow would be: check the dimensions for extraction for the first one, set them and then extract all the frames in a cropped way.

**Comment by WernTanj** [comment]
Maybe there is a misunderstanding. If you select checkcropping=true only the first frame pops up and when closing this from the code stops working. If you select checkcropping=false no cropping at all will occur and the frames are imported as 640x480. This means, with multiple videos you are not able to crop. In addition, why would every movie path have the selection‘ crop’ if in the end you can only crop with the default x1,x2,y1,y2 setting?

Sent from my iPhone

On 13 Nov 2018, at 21:24, Alexander Mathis <notifications@github.com<mailto:notifications@github.com>> wrote:


This is why recommend using checkcropping=False for multiple videos. In other words the workflow would be: check the dimensions for extraction for the first one, set them and then extract all the frames in a cropped way.

**Comment by AlexEMG** [comment]
As I pointed out in the other issue, was fixed. On Linux this works fine now, let me know if it also works for you.
