### ISSUE TITLE
Cannot see images in labeled-data folder after frame extraction (while inside labeling GUI)

### ISSUE THREAD

**Issue by Okanius** [DeepLabCut/DeepLabCut#1064]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). 
Please fill out the template completely, including the full "TRACEBACK" and input code that you ran to hit this error.

**Describe the bug**

Hello I am a little new to deeplabcut. First of all, thank you very much for your work. I have a problem when viewing frames. I cannot extract the frames because pictures(jpg) are not visible when I go into the related file. However when I enter the same file from the desktop, I see the files are there.

**Desktop (please complete the following information about your system):**
 - OS: [e.g. Windows10 Home 19042.685]
 - DeepLabCut Version [2.1.9] 
 - DeepLabCut mode: single animal tracking, 
 - Browser, if applicable [chrome,]

**To Reproduce**
Steps to reproduce the behavior, i.e.:
4. the input code you used (i.e. `deeplabcut.train_network( .... )`)
4. See error:

<details><summary>TRACEBACK</summary><p>

```python

^do not delete the above "<details><summary>TRACEBACK</summary><p>" or the ```python part!
PLACE YOUR CODE HERE!!!  
do not delete below this line, leave the blank line and the ```



```
</p></details>

**Expected behavior**
When I want to extract the necessary frames from the file, I expect the jpgs to come instead of the empty folder.

**Screenshots**
Here are the steps that i followed.
![aşama 1](https://user-images.githubusercontent.com/70771176/103692547-f648d380-4fa8-11eb-82f1-7f4020a6055c.png)
![aşama 2](https://user-images.githubusercontent.com/70771176/103692564-fb0d8780-4fa8-11eb-8348-a55f6ac2be68.png)

After this stage, a message appears as:

Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 5.0  seconds.
Extracting and downsampling... 150  frames from the video.
150it [00:01, 147.33it/s]
Kmeans clustering ... (this might take a while)
C:\Users\OkanT\anaconda3\envs\DLC-CPU\lib\site-packages\sklearn\cluster\_kmeans.py:888: UserWarning: MiniBatchKMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can prevent it by setting batch_size >= 1024 or by setting the environment variable OMP_NUM_THREADS=1
  f"MiniBatchKMeans is known to have a memory leak on "
Frames were successfully extracted, for the videos of interest.

You can now label the frames using the function 'label_frames' (if you extracted enough frames for all videos).

![aşama 3](https://user-images.githubusercontent.com/70771176/103692812-65262c80-4fa9-11eb-8b2f-25f53bbca0cb.png)
![aşama 4](https://user-images.githubusercontent.com/70771176/103692826-68211d00-4fa9-11eb-9836-7a46cf79a6dc.png)

**Additional context**

**Comment by MMathisLab** [comment]
HI, first it is extracted correctly. You will not "see" them pop up or anything; you just need to click on the folder to load in the labeling GUI as the next step. But also, just to be clear you don't need to click on the image to label, if you say open the folder in the labeling GUI, what happens? No images appear?

It is odd your folder ends in .mp4. Can you rename the folder to be just the video file name, and try again? (if the above does not work)

**Comment by Okanius** [comment]
First of all, thank you for your return. I made both options you said. However, when I come to label frames option from label and click load frames, no image appears on the screen.
![aşama5](https://user-images.githubusercontent.com/70771176/103741049-72730380-5009-11eb-91a4-ec5ea2d04122.png)

These are the codes after I click load frames and select the related file.
![aşama6](https://user-images.githubusercontent.com/70771176/103741247-c978d880-5009-11eb-82a6-3c326b1c902e.png)

**Comment by MMathisLab** [comment]
in this image https://user-images.githubusercontent.com/70771176/103692826-68211d00-4fa9-11eb-9836-7a46cf79a6dc.png it seems your files have no ending; can you look at the images and be sure they say .png at the end? (display as a list). This seems some setting in your windows OS that is changing this then.

**Comment by Okanius** [comment]
I tried it on another computer and this time I did not encounter the same problem. Thank you. I think the problem is with my computer. What should I do to fix this problem on my own computer?

**Comment by MMathisLab** [comment]
sorry, I have no idea what is wrong with your computer settings. I would check the windows forums to understanding why the end of the file name is dropped. Glad DLC working otherwise!
