### ISSUE TITLE
utils/visualization/make_labeled_images_from_dataframe can produce error when draw_skeleton is false

### ISSUE THREAD

**Issue by wangt-github** [DeepLabCut/DeepLabCut#1066]
When all_same_shape is True, line 299 calls:
coll = LineCollection([], colors=cfg["skeleton_color"], alpha=alpha)

But it could be valid for skeleton_color to not exist when draw_skeleton is False

Lines 299 and 300 should be conditioned on if ind_bones is defined like it is when all_same_shape is False.

**Comment by MMathisLab** [comment]
Pleas edit to use the required template, then we will assist you.

**Comment by MMathisLab** [comment]
the skeleton color is never blank by default https://github.com/DeepLabCut/DeepLabCut/blob/acfbd414ef7dfab1d3e0ba8ddc8a5dfe90c8dba4/deeplabcut/create_project/new.py#L227 thus, if you delete something in the config.yaml file and expect it to work, that is a non-standard use of our code.
