### ISSUE TITLE
Batch Size keeps defaulting to 1

### ISSUE THREAD

**Issue by AmeetR** [DeepLabCut/DeepLabCut#1067]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Your Operating system and DeepLabCut version**

Please complete the following information about your system:

OS: Windows 10
DeepLabCut Version: [e.g. 2.2]: 2.1.8.2

Every time I train a DLC network (resnet101 in this case), the training defaults to a batch size of 1, even though it's specified to be higher than that in the config file. I get the following error: 

Switching batchsize to 1, as default/tensorpack/deterministic loaders do not support batches >1. Use imgaug loader.
Starting with standard pose-dataset loader.

**Comment by AmeetR** [comment]
Using the imgaug augmenter doesn't have the same error, but still defaults to a batch size of one: 
`
Starting with imgaug pose-dataset loader.
Batch Size is 1
`

**Comment by MMathisLab** [comment]
Where are you setting the batch size? Ihe the correct pose_cnfg.yaml file? See here for the default parameters; you find this in the dlc-model folder, under train: https://github.com/DeepLabCut/DeepLabCut/blob/master/deeplabcut/pose_cfg.yaml

And, you can find on the wiki how to set this; note if you change batch size in training, you will need to adjust other parameters: https://github.com/DeepLabCut/DeepLabCut/wiki/Data-Augmentation

**Comment by AmeetR** [comment]
I was editing the wrong config file, thanks! Would anything ad happen if I removed batch size from config.yaml so I can prevent confusion?

**Comment by MMathisLab** [comment]
you would not be able to analyze videos ;). Glad that resolved it.
