### ISSUE TITLE
Designate GPU for Training

### ISSUE THREAD

**Issue by AmeetR** [DeepLabCut/DeepLabCut#1068]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: Windows 10
DeepLabCut Version:  2.2

I want to train different networks on a different GPU (my system has two quadro 5000s), but it defaults to the first GPU no matter what. Is there a way to designate the GPU without changing it in the code and recompiling it?

**Comment by jeylau** [comment]
Have you tried changing `gputouse` in `deeplabcut.train_network`? You could pass whatever integer identifies your GPU in `nvidia-smi`.
