### ISSUE TITLE
 deeplabcut.add_new_videos - import a list of movies

### ISSUE THREAD

**Issue by WernTanj** [DeepLabCut/DeepLabCut#107]
**Your Operating system and DeepLabCut version**
Windows 7, Anaconda Env, DeeplabCut2.x
Browser [firefox]

In DLC1.x it was possible to select all movies in a folder by setting in myconfig.py filename='all'. In DLC2.x this option is not available and it is necessary to copy each movie path separately into the  function 'deeplabcut.add_new_videos'. We worked around this by adding the lines below to the notebook.

import os
importpath = 'D:\\UserData\\werntanj\\DLCprojects\\movies_3'
pathlist = [os.path.join(importpath, path) for path in os.listdir(importpath)]

**Comment by AlexEMG** [comment]
In the next update this will work, i.e. 
```deeplabcut.create_new_project('reaching-task','Linus','/data/videos',videotype='.mp4')```
Will import all videos from ```/data/videos``` of type ```mp4```.
To use this feature, just pass a directory (as string).
