### ISSUE TITLE
csv file not created when running analyze_video with save_as_csv set to True

### ISSUE THREAD

**Issue by hummuscience** [DeepLabCut/DeepLabCut#1075]
**Describe the bug**

Wanted to create csv files to use the data in R but the analysis does not output any csv file, even though `save_as_csv` is set to `True`

Using maDLC Analyze video in the GUI works fine and is able to create video.

Tried in terminal with ipython as well as jupyter notebook, with not luck. There is also no error indicating the failure to produce a csv file.

The file to be analyzed is on a mounted samba share. Just stating it here since DLC had some troubles with such shares (symlinks etc.)

```
import deeplabcut
videos = ['Y:/Muad/thermicnator/cohort1/10_29_2019/20191029-H17M25S35.avi']
deeplabcut.analyze_videos(config = "D:/muad/config.yaml",
                          videos= videos,
                        save_as_csv= True,
                         batchsize = 16,
                         dynamic = True)
```

```
Using snapshot-25000 for model D:/muad\dlc-models\iteration-2\thermicnatorDec19-trainset95shuffle1
Initializing ResNet
Activating extracting of PAFs

  0%|                                                                                        | 0/28510 [00:00<?, ?it/s]

Starting to analyze %  Y:/Muad/thermicnator/cohort1/10_29_2019/20191029-H17M25S35.avi
Y:\Muad\thermicnator\cohort1\10_29_2019  already exists!
Loading  Y:/Muad/thermicnator/cohort1/10_29_2019/20191029-H17M25S35.avi
Duration of video [s]:  1425.5 , recorded with  20.0 fps!
Overall # of frames:  28510  found with (before cropping) frame dimensions:  640 480
Starting to extract posture

28785it [18:00, 26.63it/s]                                                                                             

Saving results in Y:\Muad\thermicnator\cohort1\10_29_2019...

```

Only two files produced by the analysis:
```
20191029-H17M25S35DLC_resnet50_thermicnatorDec19shuffle1_25000_full.pickle
20191029-H17M25S35DLC_resnet50_thermicnatorDec19shuffle1_25000_meta.pickle

```
**Desktop (please complete the following information about your system):**
 - OS: Windows Server 2019
 - DeepLabCut Version: 2.2b8
 - DeepLabCut mode: multi-animal tracking (but single animal)
 - Browser: firefox

**Comment by jeylau** [comment]
Hello @Cumol, this is the expected behavior in multi-animal projects. There are extra steps that need to be taken (assembling the detections into animals and tracking these over time, importantly) before you get the final h5/csv output file. Where you are at, for example, the next function call should be `deeplabcut.convert_detections2tracklets`, but please have a look here https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/functionDetails.md#madeeplabcut-critical-point---assemble--refine-tracklets and there https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/maDLC_AdvUserGuide.md#---------------------decision--break-point--------------------, functions and workflow are very well explained 😊

**Comment by hummuscience** [comment]
Thank you for the quick response @jeylau. What if, however, I want a csv file with all predictions (same as is used to create the video)?

I always have only a single animal but wanted to use the options to mark corners etc.

**Comment by jeylau** [comment]
A user shared a script to convert the pickle of all detections into a .csv, this may help you [https://forum.image.sc/t/using-the-full-pickle-file/44403/5?u=jeylau](url).
Note that with multi-animal projects, we make the distinction between `multianimalbodyparts` and `uniquebodyparts`; you could use the latter to label corners.

**Comment by hummuscience** [comment]
I tried to go through the route suggested in the tutorial. Apart from DLC crashing every time I close the refine tracklet window, there are not tracklets shown of the animal even though the detections are fine when creating the video.

I set the pafthreshold lower (all the way down to 0), with no luck.

Anything else I can change?
