### ISSUE TITLE
Save labeled frames, "DLL load failed" (Tables installation Windows)

### ISSUE THREAD

**Issue by zxy126** [DeepLabCut/DeepLabCut#108]
Environment
Win10 x64, DLC2, CUDA8.0, TF-GPU1.4.0, python3.5.5, Cython, Anaconda Env

Hello, I labeled frames and pressed "SAVE".
In CMD terminal show

Traceback (most recent call last):
  File "D:\Anaconda3\envs\DLC2\lib\site-packages\pandas\io\pytables.py", line 447, in __init__
    import tables  # noqa
  File "D:\Anaconda3\envs\DLC2\lib\site-packages\tables\__init__.py", line 93, in <module>
    from .utilsextension import (
ImportError: DLL load failed: The specified procedure could not be found.

**Screenshots**
![image](https://user-images.githubusercontent.com/36796433/48417155-01b76000-e78d-11e8-8940-38104b36c7f6.png)

I tried to reinstall the tables and cython, but it's useless.

Many thanks!

**Comment by AlexEMG** [comment]
Googling brings: https://github.com/conda-forge/pytables-feedstock/issues/31

**Comment by zxy126** [comment]
WAAAGH!!!
Now, "conda install pytables -c conda-forge" can fix it perfectly.
