### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by yrleftbrain** [DeepLabCut/DeepLabCut#1081]
**Your Operating system and DeepLabCut version**
Windows 10 Pro 64bit, with an Anaconda Env, & DeepLabCut 2.1.9

**Describe the problem**
After labeling all body points of interest, we use the GUI to 'check labels' and 'create skeleton'. When we click check labels, we receive an error (shown below). Thanks for the help!

<details><summary>Code output</summary><p>

[Creating images with labels by ANT.
Traceback (most recent call last):
  File "C:\Users\Ant-Lab\.conda\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\label_frames.py", line 132, in check_labelF
    deeplabcut.check_labels(self.config, visualizeindividuals=False)
  File "C:\Users\Ant-Lab\.conda\envs\DLC-GPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 506, in check_labels
    color_by=color_by,
  File "C:\Users\Ant-Lab\.conda\envs\DLC-GPU\lib\site-packages\deeplabcut\utils\visualization.py", line 262, in make_labeled_images_from_dataframe
    for bp1, bp2 in cfg["skeleton"]:
ValueError: too many values to unpack (expected 2)]

</p></details>

**Additional context**
I'm thinking it has something to do with the config file. Other issues reported seem to suggest it is because of extra dots (or periods) in the path. However we do not have that. See config file attached. [
[config_copy.txt](https://github.com/DeepLabCut/DeepLabCut/files/5811123/config_copy.txt)
](url)

**Comment by yrleftbrain** [comment]
I believe I know the issue. In this project, we combined two videos at different angles into one. See attached image below. I suppose for this we would've needed to choose two animal project?

![image](https://user-images.githubusercontent.com/77409975/104595800-17609280-5641-11eb-8eed-49083273680a.png)

**Comment by brokensm1le** [comment]
I have the exact same problem, how did you solve it?

**Comment by thomasdeneux** [comment]
I had the same problem and then solved it: as appears in the error this has to do with the "skeleton" part of the config file.

I initially thought that skeleton to be displayed on top of video frames should be defined as a set of lines, hence i defined two lines, one going from the nose of the mouse to its tail tip, the second joining left and right ears.

```
skeleton:
- - nose
  - tail-start
  - tail-center
  - tail-end
- - ear-left
  - ear-right
```

Then i understood that each individual skeleton "bone" must be defined, i.e. only pairs of points. I changed the skeleton definition as follows and the error vanished:

```
skeleton:
- - nose
  - tail-start
- - tail-start
  - tail-center
- - tail-center
  - tail-end
- - ear-left
  - ear-right
```

**Comment by chance-time** [comment]
I wanted to add my similar mistake in case it helps anyone. I thought I needed to put free standing markers in the skeleton portion as well which also resulted in this error so before I had: 
```
- - Ankle_L
- - Ankle_R

- - TailBase
  - ProxTail1
- - ProxTail1
  - ProxTail2
```
When I should have just had the connected pieces, once I removed the free-standing markers (Ankle L and Ankle R) it worked.
