### ISSUE TITLE
New ID# when animal enters frame

### ISSUE THREAD

**Issue by felixhol** [DeepLabCut/DeepLabCut#1085]
**Specific use case** 
I image mosquitoes that can go in and out of the field of view. In a given experiment there may be >30 animals, yet there typically are not more than 10 in a frame. Animals are indistinguishable and can leave and enter the frame as they please. I need to assign new IDs to animals that come into the frame, instead of reassigning animals to a previously used, currently vacant ID (default practice in deeplabcut).

**Additional context /  proposed solution**
I train my network with 20 individuals, and as there are never more than 20 individuals visible at any given time I can track all of them. However, when animal # 1 leaves the field of view, and another random animal comes into the field of view a couple of frames later, that animal gets # 1 assigned (or any other vacant number). However, I would like this new animal to be labelled 21, and any new animal that appears in the field of view n + 1 (so in a long experiment I may use 100s of IDs). In this way I will be able to analyze all behavioral trajectories separately, instead of wrongly/randomly grouping them into 20 ‘individuals’.

**I’m curious about two things:**
	1	is anyone else encountering this issue, and if yes, did anyone solve this?
	2	I’m working on some code to reassign trajectories to new ID numbers (i.e. when there is a ‘gap’ in a trajectory, slice that trajectory into multiple IDs), would people be interested in such a function?

**Comment by jeylau** [comment]
There are a couple of things you could be doing. 1) Make sure that `max_age` in the inference_cfg.yaml under dlc_models/.../test is set to 1; this will prevent the re-identification of a detected mosquito after it has left the frame. 2) You are likely more interested in the raw tracklets (in contrast to the fully formed tracks); i.e., typically short, uninterrupted tracklets indexed by tracker IDs that are contained in the pickle file you get after running `deeplabcut.convert_detections2tracklets`.

**Comment by felixhol** [comment]
Thanks for the suggestions @jeylau ! In the mean while I wrote a little [function](https://github.com/felixhol/biteOscope/blob/master/playground/DLC_maPlots_renewID.ipynb) that reassigns IDs, but I'll certainly look into your suggestions.
