### ISSUE TITLE
Question marks in config/videopath

### ISSUE THREAD

**Issue by FelixSWue** [DeepLabCut/DeepLabCut#1086]
OS: Windows 10
DeepLabCut Version: 2.1.9

After I refined, trained & evaluated my network, there appeared a question mark in front of the videopath in the config-file of the recently added videos. Also, train & test errors did not Change after the last Iteration so that I guess, DLC did not include the Videos for the training. What could be the reason and how can I get the refined frames included to the training?

<img width="1012" alt="Bildschirmfoto 2021-01-19 um 14 36 56" src="https://user-images.githubusercontent.com/76441980/105042021-0ad6a280-5a64-11eb-811b-117105b6226c.png">

**Comment by jeylau** [comment]
@FelixSWue, I have seen question marks too in some of my config files. This is just a mapping used by YAML (particularly for long keys, like file paths, or keys containing special characters). You could use `deeplabcut.utils.auxiliaryfunctions.read_config` to verify that DLC parses the config properly, but there should be no issue there normally 😊
