### ISSUE TITLE
The GUI can output CSV files, but the "refine" command in batch processing cannot

### ISSUE THREAD

**Issue by Huangjiahui1** [DeepLabCut/DeepLabCut#1088]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Your Operating system and DeepLabCut version**
Operating system: Ubuntu,Anaconda Env, Deeplabcut 2.2

Please complete the following information about your system:

OS: [e.g. MacOS, Windows 10, etc]
DeepLabCut Version: [e.g. 2.2] (please check with import deeplabcut, deeplabcut.__version__)
Anaconda env used:

**Describe the problem**
I directly execute refine on the command line to get only ".h5" and no .csv files, whereas I can get .csv files using "Filter Tracks" in Refine tracklets of GUI. When I want to batch processing, how can I get CSV files without a GUI interface? Thank you for reading.

A clear and concise description of what the problem is.

Please place code inside this:

<details><summary>Code output</summary><p>
![MC0V_1Z~C3ANJBU KIK_DZD](https://user-images.githubusercontent.com/77730747/105174657-d8a96b80-5b5d-11eb-915b-4e0e9def7990.png)
![MC0V_1Z~C3ANJBU KIK_DZD](https://user-images.githubusercontent.com/77730747/105174703-ec54d200-5b5d-11eb-8336-9bac83abc004.png)

`import os
import deeplabcut

prefix= '/mnt/Ti_Cr-hjh-2021-01-18/addvideos/'

config_path = '/mnt/Ti_Cr-hjh-2021-01-18/config.yaml'

datanames = os.listdir('/mnt/Ti_Cr-hjh-2021-01-18/addvideos/')

_bx = []
vd = [] 
for dataname in datanames:
    print(dataname[-10:])
    if dataname[-10:] == '_bx.pickle':
        dataname1 = prefix + dataname
        _bx.append(dataname1)
        
            
for dataname in datanames:
    if os.path.splitext(dataname)[1] == '.MP4':
        dataname1 = prefix + dataname
        vd.append(dataname1)
        
vd.sort()
_bx.sort()

print(len(_bx),len(vd))
for i in range(50):
    bx_file_path = _bx[i]
    videofile_path = vd[i]
    print(_bx[i],vd[i])
    deeplabcut.refine_tracklets(config_path, bx_file_path, videofile_path, min_swap_len=2, min_tracklet_len=2, trail_len=50)
    print("good")`

</p></details>

**How to Reproduce the problem**

**Screenshots**

**Additional context**

No more questions, thank you

**Comment by Huangjiahui1** [comment]
import os
import deeplabcut

prefix= '/mnt/Ti_Cr-hjh-2021-01-18/addvideos/'

config_path = '/mnt/Ti_Cr-hjh-2021-01-18/config.yaml'

datanames = os.listdir('/mnt/Ti_Cr-hjh-2021-01-18/addvideos/')

_bx = []
vd = [] 
for dataname in datanames:
    print(dataname[-10:])
    if dataname[-10:] == '_bx.pickle':
        dataname1 = prefix + dataname
        _bx.append(dataname1)
        
            
for dataname in datanames:
    if os.path.splitext(dataname)[1] == '.MP4':
        dataname1 = prefix + dataname
        vd.append(dataname1)
        
vd.sort()
_bx.sort()

print(len(_bx),len(vd))
for i in range(50):
    bx_file_path = _bx[i]
    videofile_path = vd[i]
    print(_bx[i],vd[i])
    deeplabcut.refine_tracklets(config_path, bx_file_path, videofile_path, min_swap_len=2, min_tracklet_len=2, trail_len=50)
    print("good")

**Comment by Huangjiahui1** [comment]
>>> deeplabcut.filterpredictions(config_path,['/mnt/Ti_Cr-hjh-2021-01-18/addvideos/T63_0500_3_Cr.MP4'], videotype='.mp4',filtertype= 'arima',ARdegree=5,MAdegree=2)
Filtering with arima model /mnt/Ti_Cr-hjh-2021-01-18/addvideos/T63_0500_3_Cr.MP4
No unfiltered data file found in /mnt/Ti_Cr-hjh-2021-01-18/addvideos for video T63_0500_3_Cr and scorer DLC_resnet50_Ti_CrJan18shuffle1_62000.

I always make this mistake "No unfiltered data file found in" when I try to filterpredictions.

**Comment by Huangjiahui1** [comment]
Sorry for the trouble.Now I find that using deeplabcut.analyze_videos_converth5_to_csv can convert CSV files, but I keep getting errors when filtering(GUI does not have this problem).

**Comment by jeylau** [comment]
You need to pass `track_method='box'` to `deeplabcut.filterpredictions` in multi-animal projects.
