### ISSUE TITLE
extract_frames: no cropping with crop=True, checkCropping=False (bug fixed)

### ISSUE THREAD

**Issue by WernTanj** [DeepLabCut/DeepLabCut#109]
When running `deeplabcut.extract_frames` with `crop=True` and `checkCropping=False`, no cropping ever happens, as line 133 is only executed if `checkCropping=True`

https://github.com/AlexEMG/DeepLabCut/blob/2807d123eef9d7fd4f5fc89c701fccbfbfea44b3/deeplabcut/generate_training_dataset/frame_extraction.py#L104-L137

To fix this, `clip=clip.crop(y1 = int(coords[2]),y2 = int(coords[3]),x1 = int(coords[0]), x2 = int(coords[1]))` should be added in an `else` clause.

Operating system: Windows 7;

**Comment by MMathisLab** [comment]
Yes, that is the expected behavior since you’re not checking the cropping...

**Comment by WernTanj** [comment]
Please check issue
deeplabcut.extract_frames pop-up image does not close in windows #106

I ticked checkCropping false because of a windows error.

Nevertheless it would be good to be able to use the cropping function independent of visual inspection or not.

On 13 Nov 2018, at 17:13, Mathis Lab <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, that is the expected behavior since you’re not checking the cropping...

**Comment by AlexEMG** [comment]
This was a bug, thanks for pointing this out. Fixed! Also ```checkcropping=True``` now also works for multiple videos.
