### ISSUE TITLE
DLC Output Dimensions?

### ISSUE THREAD

**Issue by AmeetR** [DeepLabCut/DeepLabCut#1090]
Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: Windows 10
DeepLabCut Version: DeepLabCut 2.2

When I look at the output trajectory plots (and whenever I handle the data myself), it looks like the the output tracking operates in the frame 640 * 480. However, my input videos are 1440 * 1080 and when I run the label video command, I get out 1440 * 1080. Is there an internal conversion happening somewhere that converts from 1440p to 640 and back? IE. The network predicts in 640 * 480 and then whenever working with the video, it converts to 1440? This is important for me, since I'm converting to centimeters for kinematics and I need to make sure my conversion factor is the same.

**Comment by MMathisLab** [comment]
^ can you post the first 6 rows of your H5 file? I'm not sure I understand the issue fully yet.

**Comment by AlexEMG** [comment]
Video predictions/Evaluation are/is carried out at the same resolution as the input video/image.
