### ISSUE TITLE
wxAssertionError

### ISSUE THREAD

**Issue by ashwin-miriyala** [DeepLabCut/DeepLabCut#1093]
deeplabcut.label_frames(configPath)
---------------------------------------------------------------------------
wxAssertionError                          Traceback (most recent call last)
<ipython-input-11-8565d1b30c72> in <module>
----> 1 deeplabcut.label_frames(configPath)

~/anaconda3/envs/DLC/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py in label_frames(config, multiple_individualsGUI, imtypes)
    429         from deeplabcut.generate_training_dataset import labeling_toolbox
    430 
--> 431         labeling_toolbox.show(config, imtypes=imtypes)
    432 
    433     os.chdir(startpath)

~/anaconda3/envs/DLC/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/labeling_toolbox.py in show(config, imtypes)
   1009 def show(config, imtypes=["*.png"]):
   1010     app = wx.App()
-> 1011     frame = MainFrame(None, config, imtypes).Show()
   1012     app.MainLoop()
   1013 

~/anaconda3/envs/DLC/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/labeling_toolbox.py in __init__(self, parent, config, imtypes)
    257         widgetsizer.AddStretchSpacer(15)
    258         self.quit = wx.Button(self.widget_panel, id=wx.ID_ANY, label="Quit")
--> 259         widgetsizer.Add(self.quit, 1, wx.ALL | wx.ALIGN_RIGHT, 15)
    260         self.quit.Bind(wx.EVT_BUTTON, self.quitButton)
    261 

wxAssertionError: C++ assertion "!(flags & wxALIGN_RIGHT)" failed at /home/conda/feedstock_root/build_artifacts/wxpython_1611143352103/work/ext/wxWidgets/src/common/sizer.cpp(2094) in DoInsert(): Horizontal alignment flags are ignored in horizontal sizers

This is an issue within the wxpython package I assume, but I thought I'd ask here anyway before playing around with the files.  I just used conda install wxpython during installation and I'm using ubuntu 18.04.5 LTS 64 bit .  Any help is appreciated!

edit- tried with conda install -n conda-forge wxpython , but found same issue.

**Comment by ashwin-miriyala** [comment]
For now, commenting out line 259 in file ~/anaconda3/envs/DLC/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/labeling_toolbox.py works.  The Quit button overlaps slightly with the load frames button, but nothing else drastic!

'seems wxWidgets 3.1+ has tightened it's rules on sizers' - https://github.com/maxmods/wx.mod/issues/12

**Comment by MMathisLab** [comment]
Hi @ashwin-miriyala yes, this is why you need to use `pip install -U wxPython==4.0.7.post2` ; please see the other same issues, #682, #1079.
