### ISSUE TITLE
results error (no trajectory, no labels in video) thank you!

### ISSUE THREAD

**Issue by sofiaitorres** [DeepLabCut/DeepLabCut#1095]
**Your Operating system and DeepLabCut version**

MacOS High Sierra, version 10.13.6,  DeepLabCut (CPU version 2.1.9)
Anaconda env used: don't know what this is...

**Describe the problem**

Hey everyone!

I’ve been trying to get my DeepLabCut to work (CPU version 2.1.9), but have encountered some problems. The program runs well (except for “TensorFlow.python.framework.erros_impl.CancelledError: Enqueue operation was cancelled” right after training). I installed anaconda recently, so I believe I have the newest version of that.

The actual problem I have lies in the results. I have tried to run the program with a small amount of iterations to make sure it works. However, in the plot-poses folder after analyzing the videos, the trajectory.png and plot.png appear blank. Additionally, with the “create a video” feature, the labeled video appears the same as the original video (no labels or skeleton on it). I use the same video for training and analyzing, and I make sure to put the correct format every time (.mov, .mp4). I attached a picture of the plots so you can see how they look (blank). When I check the labels before training, they look okay, so it’s not like they’re not saving (I believe). Also, the plot-poses and labeled video files don’t appear in the project folder, they are saved to some random place in the computer.

I tried to use the Google Collab with my data, and still got the same error in the results.

I don’t have the “tracklets” feature in my program either, as one of the youtube videos portrayed.

Last thing, how do people actually access the code of DeepLabCut?

If any of these happened to you, or have an idea how to fix them, please let me know!

Thanks a lot! You can request more information as needed.

**Screenshots**

![plot](https://user-images.githubusercontent.com/77503430/106075239-a2329a00-60e3-11eb-9987-cc0ca1790766.png)
![trajectory](https://user-images.githubusercontent.com/77503430/106075241-a2cb3080-60e3-11eb-92b4-b5253d1fd718.png)

**Comment by jeylau** [comment]
Hey @sofiaitorres, only detections with a likelihood greater than `pcutoff` (as defined in your config.yaml) will be shown. Given that you have not trained your model very long, likelihood most certainly remains very low. A simple test is to edit your config file and set `pcutoff` to 0.01; your plots should no longer be blank then.

**Comment by sofiaitorres** [comment]
> Hey @sofiaitorres, only detections with a likelihood greater than `pcutoff` (as defined in your config.yaml) will be shown. Given that you have not trained your model very long, likelihood most certainly remains very low. A simple test is to edit your config file and set `pcutoff` to 0.01; your plots should no longer be blank then.

Thanks a million! This helped a lot!
