### ISSUE TITLE
Changing from a single to a multi-animal project using the same model and recognising different views

### ISSUE THREAD

**Issue by salucas2** [DeepLabCut/DeepLabCut#1097]
Hello, I am using DLC 2.2b8 to track Praying Mantis strikes. 

To begin with I was using a single animal model with a lateral view of the strike. Is it possible to retrospectively add another animal to the model or will I need to start a new project (I wasn't counting the prey item that the mantis was striking as a separate animal but now would like to). 

Secondly, I'd also like to track the dorsal views of mantises in separate videos (these are not the same videos as the lateral views and we don't require to track them simultaneously. We are trying to get the model to recognise and track videos of either a dorsal view or a lateral view) - would this be possible in the same model? 

Thanks, 
Sol

**Comment by KonradDanielewski** [comment]
If the prey item is not a mantis looking exactly like the one you're tracking you can add labels to your single animal project for this item. You can actually do all of the things you listed in one single animal project either by making a new one or expanding on the one you have. 

BTW, it's more of a "looking for advice" not a software issue, so better place would be either Gitter or imagesc forum.

**Comment by salucas2** [comment]
Great, thanks Konrad and thanks for the advice on Gitter too!
