### ISSUE TITLE
How can I use the model which was trained on videos with 2 mice to track the videos with 3 mice?

### ISSUE THREAD

**Issue by jamesbond2012** [DeepLabCut/DeepLabCut#1098]
I have trained a model on the videos with 2 mice. I am using DLC 2.2b7. I am trying to use that model to track the videos with 3 mice, but I am not successful. Could you instruct me how to do that? Thanks

**Comment by backyardbiomech** [comment]
Just set `topktoretain: 3` in `inference_cfg.yaml`. That affects how the detections are converted to tracklets, so you don't need to reanalyze the videos (if you already have).

**Comment by jamesbond2012** [comment]
Thanks. I also need to add one more individual into config.yaml.
