### ISSUE TITLE
No labels for each frame

### ISSUE THREAD

**Issue by kebanfi** [DeepLabCut/DeepLabCut#1100]
Hi everyone, 

I'm hoping someone might be able to help me with the issue I'm having.

When I load my frames to label in deeplabcut all the frames show up however after labeling the first frame and clicking to the next one the annotations from the first frame transfer to the next one and the rest of the frames as well. It almost seems as though there is only one "set" of label markers for all the 500 frames I'm trying to label. I wonder if there might be a solution to this?

Thank you

**Comment by jeylau** [comment]
Hi @kebanfi, what version of DLC are you using? Is that with the multi-animal labeling toolbox?

**Comment by kebanfi** [comment]
Hi @jeylau, I believe it is. I'm not sure what version I'm on but I've labeled frames before without having this issue.

Do you recommend perhaps updating DLC?

**Comment by AlexEMG** [comment]
if you type `deeplabcut.__version__` once you imported it you could share the version number :)
