### ISSUE TITLE
EfficientNets in version 2.1.10 

### ISSUE THREAD

**Issue by GPU-Shuttle** [DeepLabCut/DeepLabCut#1101]
**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Ubuntu 18.04 LTS, with an Anaconda Env 3, & DeepLabCut2.1.10.

Please complete the following information about your system:

OS: [Windows 10]
DeepLabCut Version: [2.1.10] 
Anaconda env used: 3

**Describe the problem**
Efficientnets don't seems to have been added to the new release in version 2.1.10?! at least no such network is being displayed on the dropdown list of the GUI at the "creating training dataset" step!

**How to Reproduce the problem**
1. Go to 'GUI'
2. Click on 'create training dataset'
3. Scroll down to 'select network'
4. See there's no Efficientnet listed in the dropdown networks!

**Screenshots**
![No Effnets](https://user-images.githubusercontent.com/74163973/106679540-c6313680-6621-11eb-9c3a-bb95cbeec413.png)

**Comment by jeylau** [comment]
They are only available programmatically, but will soon be added to the GUI 😊.

**Comment by GPU-Shuttle** [comment]
Hmmm, I thought so too, but what's the appropriate command to utilize them when training a net with them?
