### ISSUE TITLE
pythonw testscript.py produces FileNotFoundError: File .../DeepLabCut/examples/TEST-Alex-2021-02-04/labeled-data/reachingvideo1short/machinelabels-iter0.h5 does not exist

### ISSUE THREAD

**Issue by DanielSanchezDiaz** [DeepLabCut/DeepLabCut#1106]
OS: macOS Catalina 10.15.6
DeepLabCut Version: DeepLabCut 2.1.10
Anaconda env used: DLC-CPU

**Describe the problem**

I've been trying to run testscript.py located in DeepLabCut/examples. I have been following the video located [here](https://www.youtube.com/watch?v=IOWtKn3l33s) but the program keeps crashing and I keep getting "FileNotFoundError" errors.

When I run pythonw testscript.py, I get a series of error messages. The last one and also the one that end my run in an error is
```python
RELABELING
Traceback (most recent call last):
  File "testscript.py", line 228, in <module>
    DF = pd.read_hdf(file, "df_with_missing")
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/pandas/io/pytables.py", line 387, in read_hdf
    raise FileNotFoundError(f"File {path_or_buf} does not exist")
FileNotFoundError: File /Users/shawtylow/Desktop/DLCTest/DeepLabCut/examples/TEST-Alex-2021-02-04/labeled-data/reachingvideo1short/machinelabels-iter0.h5 does not exist
```
I also get "No video(s)" were found errors at other stages of this program but it doesn't seem to kill it.

**How to Reproduce the problem**
1. install anaconda
2. git clone deeplabcut 
3. create the dlc-cpu environment
4. activate this environment
5. cd into deeplabcut/examples
6. run "pythonw testscript.py"
7. wait for error

**Screenshots**
<img width="1194" alt="Screen Shot 2021-02-04 at 8 29 38 PM" src="https://user-images.githubusercontent.com/47653762/106977237-eea35880-6727-11eb-9178-f249cf372f61.png">
Here is what my terminal output looks like right before crashing

**Additional Context**
It appears to me that testscript.py is responsible for creating all these files since they are not on the original GitHub. Am I correct in believing this?
Also, the first thing to be missing is reachingvideo1short. That directory does not appear under labeled-data.
Thanks so much!

**Comment by kesiwilson** [comment]
I love u

**Comment by kesiwilson** [comment]
I'm having a similar error!

**Comment by mem1-create** [comment]
I am also having the exact same issue!

**Comment by mem1-create** [comment]
I am also having the exact same issue!

I have been trying to fix it by checking the included packages, but I think I have made it worse since my numpy and tensorflow versions are no longer compatible. I am too new to coding to break down the issue well, so any help on the initial issue would be really appreciated!

**Comment by jeylau** [comment]
It looks like ffmpeg failed to create the video required for the test script to successfully complete. Could you alternatively run the tests/test_video.py script and let me know if it passes? Note that you may have to `pip install pytest`.

**Comment by AlexEMG** [comment]
Yes, I also think that's due to ffmpeg (the shortened video is not being created).

**Comment by AlexEMG** [comment]
Details on ffmpeg installation see here: https://github.com/DeepLabCut/DeepLabCut/blob/373dc7efd99388ae3961a545329bece3e7fdb084/docs/installation.md#troubleshooting

**Comment by MMathisLab** [comment]
Hi @DanielSanchezDiaz @mem1-create @kesiwilson -- this happens is ffmpeg is not installed, or you don't have permissions (typically a windows issue, i.e. in Windows you must right click and open the terminal "as an admin."). 

In MacOS, I also have Catalina, and can confirm it is working for me fully with the latest DLC, 2.1.10.1, also you should note if you are using the `testscipt`, it will be for the latest, code, so a simple `pip install --upgrade deeplabcut` is good to run once after you activate `DLC-CPU`. 

![Screen Shot 2021-02-07 at 10 42 19 PM](https://user-images.githubusercontent.com/28102185/107160310-c751c300-6995-11eb-9ab2-54c22ec379e5.png)


Note, you should check the terminal output, do you see the short video being cut correctly? It would look like this:

![Screen Shot 2021-02-07 at 10 39 18 PM](https://user-images.githubusercontent.com/28102185/107160242-62966880-6995-11eb-87a0-8048f7cd6a2c.png)


If not, then again once you are inside the nv (DLC-CPU), please run: `conda install -c conda-forge ffmpeg` and that would solve it!

**Comment by mem1-create** [comment]
@MMathisLab The test script ran perfect with the "conda install -c conda-forge ffmpeg" addition. Thank you so much for your help. I can't wait to get started on using DeepLabCut for my data!
