### ISSUE TITLE
Extract Outlier Frames Problem/Adding Tracking Line 

### ISSUE THREAD

**Issue by sofiaitorres** [DeepLabCut/DeepLabCut#1109]
Hii, thanks for everything!

Two questions:
1. How can I add a line tracking (or tail tracking) feature to the labeled video? (Where a body part (or multiple) leave lines, I attached a picture of an example I saw in a paper).

![PHOTO-2021-02-07-14-35-29](https://user-images.githubusercontent.com/77503430/107393155-d9844c00-6ad0-11eb-8052-bc21f20cfbbb.jpg)

2. When I try to extract outlier frames for a second time (using google Colab), I'm pretty sure it gives me the same frames as the first time. How can I do it multiple times? Which h5 file is the correct one? Is there a way to re-label more than 20 frames? I had to go back to the program on my computer to label, then replace the files, then run Colab again the first time. Does this erase the training or make it better? [[I trained 700k, then 500k, Mac OS high Sierra 10.13.6]]

If you have questions for me, feel free to ask.

**Comment by MMathisLab** [comment]
HI @sofiaitorres you set the # of frames you want to extract in the config.yaml file. 

For plotting, see docstring where you can set "trailpoints" , which is the length of the plots behind the mouse, in the example: https://github.com/DeepLabCut/DeepLabCut/wiki/DOCSTRINGS#create_labeled_video

Also, we please ask for questions if you can post on the Image Forum, thanks!
