### ISSUE TITLE
DLC 2.0 GUI refinement not working (Adjusting size of GUI depending on screen)

### ISSUE THREAD

**Issue by Donnypickels** [DeepLabCut/DeepLabCut#111]
Windows 10, with an Anaconda Env, & DeepLabCut2.0.

Hi,

I'm working with the Demo with the labled example.
When I try to open the GUI with:
```
#GUI pops up! 

%gui wx
deeplabcut.refine_labels(path_config_file)
```

The GUI just stays blank as shown in the screenshot:

![image](https://user-images.githubusercontent.com/44989800/48458303-a0de6500-e82a-11e8-9fb2-8818ebea9a7f.png)

Any idea what is wrong? 

Thanks for all the help!

**Comment by Donnypickels** [comment]
Ooofff, just found it a few minutes after finally deciding to ask here...
I had to drag the vage gray line a little bit up to reveal the menu, thats all.

Sorry! haha

**Comment by Donnypickels** [comment]
So, now with the labels loaded, I'm able to fill in a likelihood and they will change in filled or hollow when above or beneath. But after that I'm not able to correct any datapoints, I cant click on anything but help, next or previous, save and exit. It seems that everything above that menu is not working.

Anyone knows about this problem?

Sorry for all the posts...

**Comment by MMathisLab** [comment]
Yeah we are working to make the GUI better automatically read ones screen dimensions (see Alex' issue he just opened). 
https://github.com/AlexEMG/DeepLabCut/issues/110

Re not clicking that’s strange; sorry this sounds silly to ask, but are you using the “right” click to label? That is how it should be (see help button). One can also now use the arrow key to advance to the next t frame, and once you right click for the first label it auto-selects the next one down, so you just need to right click again.

**Comment by Donnypickels** [comment]
I can't click anywhere. Not with left or right. Only the lower menu works.
So clicking anywhere else won't work, like the datapoints or the upper left menu.
Also hovering over the labels gives nothing.

This is what it looks like (I believe thats correct)

![image](https://user-images.githubusercontent.com/44989800/48459836-c66e6d00-e830-11e8-8f41-92421067588f.png)

**Comment by AlexEMG** [comment]
As @MMathisLab said, it looks like it works, but see https://github.com/AlexEMG/DeepLabCut/issues/110

The refinement GUI parameters are in here: https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/refine_training_dataset/refinement.py

The labeling GUI parameters in here:
https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/generate_training_dataset/labeling_toolbox.py

In your case, consider changing the image size! 
https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/generate_training_dataset/labeling_toolbox.py#L116

Note: of course you need to change this in the location where deeplabcut is installed. You can find this location by typing:
```
import deeplabcut
deeplabcut.__file__
```

Then go to this tree and change the files in ```generate_training_dataset/labeling_toolbox.py```. The the layout will be different the next time you import deeplabcut...

**Comment by banningjoe** [comment]
Encountering a similar GUI problem as Donnypickels. Running DeepLabCut 2.0 with an Anaconda env on Windows 10. When using the Demo_yourowndata.ipynb, I get a grey screen when l  try to start labelling after running the following line of code:
![capture](https://user-images.githubusercontent.com/16569257/48511523-eb5ce300-e824-11e8-8f77-9aad7edbacd4.PNG)
Unlike Donnypickels, I don't get a grey line which I can grab to resize. It is just a blank screen. It looks like this:
![capture2](https://user-images.githubusercontent.com/16569257/48511628-3c6cd700-e825-11e8-9b20-deeb3d2c19e9.PNG)
I have tried modifying the GUI size like you have suggested in order to make sure it fits my screen resolution. I changed the following line in order to do that:
![capture3](https://user-images.githubusercontent.com/16569257/48511728-8d7ccb00-e825-11e8-820a-ebcbdd6f9357.PNG)
However, whether I leave the original size that is hardcoded in DLC or when I input my own screen size, I get the same result. The grey screen takes up the whole screen .

Any idea what the problem might be, and how to fix it?

**Comment by AlexEMG** [comment]
Any idea what the problem might be, and how to fix it?
Yes, change the dimensions. In particular https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/generate_training_dataset/labeling_toolbox.py#L116

Same applies to the two other bars (status bar and e.g. 
self.Button2 = wx.Button(self.bottom_split, -1, "Next Frame", **size=(120, 40), pos=(640, 25)**))

**Comment by banningjoe** [comment]
Thanks! That worked

**Comment by AlexEMG** [comment]
Great, I'm closing this for now, but would be great if someone could contribute to https://github.com/AlexEMG/DeepLabCut/issues/110

**Comment by Donnypickels** [comment]
It doesn't work for me yet. I still can't click anywhere...

I'm changing the size of the toolbox in the folder where I installed it, but nothing changes.

Nothing happens when I change: "https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/generate_training_dataset/labeling_toolbox.py#L116" 
Or other sizes. Am I doing something wrong?
Is there any more information you need to help me?

**Comment by MMathisLab** [comment]
Hey there, can you try this one? (i.e. at https://github.com/AlexEMG/DeepLabCut/issues/110) what you need to do is `` git clone https://github.com/MMathisLab/DeepLabCut`` then go to the DeepLabCut folder in terminal, i.e. I put it in a folder called DEEPLABCUT.
![image](https://user-images.githubusercontent.com/28102185/48527725-19a8e580-e85a-11e8-9939-cd0f060189c7.png)

You'll know it is this version as I made the bottom panel darker grey:

![image](https://user-images.githubusercontent.com/28102185/48527802-68ef1600-e85a-11e8-8cf2-a96776c1babc.png)

Also, check what the terminal says when you have the GUI open... let me kniw if it is throwing an error
![image](https://user-images.githubusercontent.com/28102185/48527880-9a67e180-e85a-11e8-8de7-898cb5e8eb2c.png)

**Comment by AlexEMG** [comment]
@Donnypickels : If nothing changes, then you are probably changing it at the wrong spot... 

Note: of course you need to change this in the location where deeplabcut is installed. You can find this location by typing:

``import deeplabcut``
``deeplabcut.__file__``

Then go to this tree and change the files in ``generate_training_dataset/labeling_toolbox.py.`` The the layout will be different the next time you import deeplabcut...

**Comment by MMathisLab** [comment]
@AlexEMG  it also requires one to comment out  https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/generate_training_dataset/labeling_toolbox.py#L43 (i.e. #self.Maximize(True)) otherwise the edits don't take effect. That is gone from my tinkering branch ;)

**Comment by MMathisLab** [comment]
@Donnypickels The GUI has been updated now even more so, and with @FedeClaudi we hacked around to get a interim solution; namely, you can pass a variable called winHack=.5 and it will load a small window where you can drag this and it will fill most of your screen size. See new code that was just updated, and new instructions here: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#d-label-frames and a short demo to show you how it should look: https://youtu.be/quZGGLaittQ

**Comment by Donnypickels** [comment]
Ah, forgot to mention. My labeling GUI works alright!
My problem was, just like FedeClaudi, that the refinement GUI did not work.
That's what also caused some confusion at my side. It appears that `deeplabcut.label_frames` and `deeplabcut.refine_labels` call for different GUI's, so changing `generate_training_dataset/labeling_toolbox.py` did not do anything to the refine labels GUI, right?. The refinement one gives me the problems, and is the one where I can't click anything and hovering over the labels doesn't do anything.

**Comment by MMathisLab** [comment]
okay! nonetheless the labeling GUI is better now,  :) so I'll check out the refinement GUI next!

**Comment by Donnypickels** [comment]
Just to let you all know, the newest update - that is `deeplabcut 2.0.0` - which I'm running currently works great!
Both the labelling and refinement GUI work!
Thanks!
