### ISSUE TITLE
Support for tensorflow2

### ISSUE THREAD

**Issue by luofang34** [DeepLabCut/DeepLabCut#1112]
Current DLC release crushes on import if tensorflow 2.x is installed.

Also, lower version of tensorflow doesn't support python 3.8 & 3.9, adding support to tf2 will greatly improve the compatibility of DLC and make it easier to use with pip&pypi, will be extremely helpful for embedded usage on which conda is not easily available.

The work may include:

disable eager execution
saving as h5

**Comment by MMathisLab** [comment]
HI @luofang34 yes, please see the other issues on this; and the DLC blog. `Deeplabcutcore`  supports TF2. https://github.com/DeepLabCut/DeepLabCut-core
