### ISSUE TITLE
Labelling unique body parts or objects in single animal DLC projects

### ISSUE THREAD

**Issue by AyusoAa** [DeepLabCut/DeepLabCut#1113]
Dear DLC developers,
I'd like to track videos where one single animal faces a moving entity that I'd like to track, too, to analyze distances to the moving object. I see there is the possibility to do that with multi animal DLC projects, but I can´t find how to do so in single animal projects. 
Could it be possible to implement uniquebodyparts in single animal projects? I would like to then analyze the poses with SimBA
Best,
Irene

**Comment by KonradDanielewski** [comment]
Simba also has multianimal support. If you want to use single you should just create labels for the moving object and label it. If it's not another similar animal there should be no problem whatsoever.

**Comment by AlexEMG** [comment]
@AyusoAa, you don't need to use multi-animal in this case. In fact you can just add the additional object to the bodypart list and label (i.e. bodyparts: ["snout", "ear", "tail", "movingball"]).
