### ISSUE TITLE
Mismatch between video annotations in DLC and Bonsai-DLC for the same trained network

### ISSUE THREAD

**Issue by edmundchong** [DeepLabCut/DeepLabCut#1114]
There is a mismatch between video annotations produced by DLC versus Bonsai-DLC, for the same videos and using the same trained networks [exported for Bonsai using `deeplabcut.export_model(path_to_config)`. The mismatch appears to worsen if the networks are trained on more iterations. I am using the default settings from the GUI, and resnet_50. I have been working with Gonçalo to try to solve this.

Images:
[bonsai_mismatch.pdf](https://github.com/DeepLabCut/DeepLabCut/files/5978230/bonsai_mismatch.pdf)

Others have reported [similar issues](https://groups.google.com/g/bonsai-users/c/wXJpUjZayWM/m/FRTA7YaEBwAJ)

Per @MMathisLab suggestion to Gonçalo, I tried changing the global_scale in pose_cfg.yaml (in both train/test folder) parameter. No luck--the mismatch occurs whether global_scale=0.5,0.8,1.0

Gonçalo was able to reproduce the mismatch on his machine using my dataset (but not others).

My system: Windows10, DeepLabCut 2.2b, single animal tracking

Gonçalo seems to think that the problem lies in the fact that the DLC GUI performs some additional steps during video annotation, as opposed to Bonsai-DLC which outputs the raw result from the tensorflow inference. We were wondering then what these additional steps were, if any? Gonçalo also wonders if [this was one such step](https://github.com/DeepLabCut/DeepLabCut/blob/d04c5da1b76033cf1b43d323eec45f74e36bf6ab/deeplabcut/pose_estimation_tensorflow/nnet/predict.py#L74)

Thanks!

**Comment by MMathisLab** [comment]
Hi @edmundchong can we move this then to DLC-Live or the Bonsai-DLC code base please, as this is not related to the DLC code base; also there is no processing in the GUI. Also, you can only change global_scale BEFORE training, it will do nothing afterwards. But I highly doubt this is the issue. It sounds your DLC network is accurate/working, DLC-Live works, etc. I would also caution that you MUST use the same version of tensorflow you exported the model with when you LOAD it into DLC-Live, Bonsai, etc.
