### ISSUE TITLE
resnet v1 50 error in training

### ISSUE THREAD

**Issue by CarlaFilosa** [DeepLabCut/DeepLabCut#1115]
Hi!

I am using deeplabcut for multianimal pose estimation.
During the training step I get an error linked to the resnet: Keyerror: resnet_v1_50 (see screenshot). I tought it was somehow related to the download rights, but the error persists even after having changed the rights following the instruction of the issue 276 (https://github.com/DeepLabCut/DeepLabCut/issues/276).
Could you please help me to uderstand what I am doing wrong here?
Thanks!
C.
![Error](https://user-images.githubusercontent.com/32203127/107967936-0b545180-6fae-11eb-9a5b-c553d9d3c2f5.png)

**Comment by KonradDanielewski** [comment]
Hi,

easiest solve would be to manually download and unpack it in the pretrained folder (link do download manually http://download.tensorflow.org/models/resnet_v1_50_2016_08_28.tar.gz )
