### ISSUE TITLE
Frame extraction failed. Video files must be corrupted.

### ISSUE THREAD

**Issue by ashwin-miriyala** [DeepLabCut/DeepLabCut#1117]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Ubuntu 18.04.5 LTS, with an Anaconda Env, DLC version 2.1.10.1**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: [Ubuntu 18.04.5 LTS]
DeepLabCut Version: 2.1.10.1
Anaconda env used: True

**Describe the problem**

The videos I'm recording are in .avi format.  I can create a new project pointing to an .avi file. 
However, when I try to extract frames, the function quits with the error Video could not be opened... 

import deeplabcut
deeplabcut.create_new_project('FlyonBall','Ash',['/home/ashwin/Documents/Droso/fic_20210212_123845.avi'],copy_videos=False,videotype='.avi',multianimal=False)
deeplabcut.extract_frames(config_path,mode='automatic',algo='kmeans',crop=True,userfeedback=False)

<details><summary>Code output</summary><p>

Config file read successfully.
Video could not be opened. Skipping...
Frame extraction failed. Video files must be corrupted.

</p></details>

**How to Reproduce the problem**
1. Install deeplabcut:
conda create -n DLC python=3.7 tensorflow=1.13.1
conda activate DLC
pip install deeplabcut
conda install -c anaconda wxpython    
##(pip install -U wxPython==4.0.7.post2 #exits installation with errors)

2. Create new project using an .avi video:
deeplabcut.create_new_project('FlyonBall','Ash',['/home/ashwin/Documents/Droso/fic_20210212_123845.avi'],copy_videos=False,videotype='.avi',multianimal=False)

3. extract Frames:
deeplabcut.extract_frames(config_path,mode='automatic',algo='kmeans',crop=True,userfeedback=False)

Config file read successfully.
Video could not be opened. Skipping...
Frame extraction failed. Video files must be corrupted.

**Screenshots**

**Additional context**
The extract frames function runs when I convert my .avi to .mp4 using ffmpeg in Ubuntu, and then pointing to the .mp4 file instead during create_new_project(). 
Perhaps this is an openCV issue?  When I set the field deeplabcut.extract_frames(...,opencv=False), I get the following error messages:
Traceback (most recent call last):
  File "/home/ashwin/anaconda3/envs/DLC/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py", line 291, in ffmpeg_parse_infos
    match = re.findall("([0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9])", line)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ashwin/anaconda3/envs/DLC/lib/python3.7/site-packages/deeplabcut/gui/extract_frames.py", line 243, in extract_frames
    slider_width=slider_width,
  File "/home/ashwin/anaconda3/envs/DLC/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/frame_extraction.py", line 216, in extract_frames
    clip = VideoFileClip(video)
  File "/home/ashwin/anaconda3/envs/DLC/lib/python3.7/site-packages/moviepy/video/io/VideoFileClip.py", line 91, in __init__
    fps_source=fps_source)
  File "/home/ashwin/anaconda3/envs/DLC/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py", line 33, in __init__
    fps_source)
  File "/home/ashwin/anaconda3/envs/DLC/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py", line 296, in ffmpeg_parse_infos
    filename, infos))
OSError: MoviePy error: failed to read the duration of file /home/ashwin/Documents/Droso/fic_20210212_123845.avi.
Here are the file infos returned by ffmpeg:

ffmpeg version 4.2.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, avi, from '/home/ashwin/Documents/Droso/fic_20210212_123845.avi':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: mjpeg (Baseline) (MJPG / 0x47504A4D), yuvj420p(pc, bt470bg/unknown/unknown), 1376x1376 [SAR 1:1 DAR 1:1], 66 fps, 66 tbr, 66 tbn, 66 tbc
At least one output file must be specified

**Comment by KonradDanielewski** [comment]
Looking at the errors seems that metadata is corrupted. Duration and bitrate are unknown. After reencoding this metadata probably gets corrected by the encoder. 

Depending on the encoder you used when recording videos there might issues with proper frame indexing and other metadata if your avi file is larger than 2 or 4 GB. It usually easily gets solved by reencoding - hence why it worked for you. I would advise to go for mp4 encoded with libx265 (considering your resolution) with crf 18, veryfast preset. You should obtain high compression without perceivable loss of quality.

**Comment by ashwin-miriyala** [comment]
Thanks for the insight!
