### ISSUE TITLE
No bx.pickle file

### ISSUE THREAD

**Issue by RobertoEnrique** [DeepLabCut/DeepLabCut#1118]
After analyzing videos for multitracking, I get the full pickle and the meta pickle files, but I don't get the bx pickle which is needed for the next steps. I re-analyzed and still the same. Any ideas what could I be doing wrong?

Thanks

**Comment by jeylau** [comment]
Hey @RobertoEnrique, you only get the box pickle after calling `deeplabcut.convert_detections2tracklets()`. You can learn more about it and the remaining steps here https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/UseOverviewGuide.md#assemble--refine-tracklets-in-madeeplabcut  😊
