### ISSUE TITLE
Consider deploying DLC on conda-forge (CONDA ENVIRONMENT INSTALLATION WINDOWS)

### ISSUE THREAD

**Issue by imagejan** [DeepLabCut/DeepLabCut#112]
Since you already recommend Anaconda in your [installation instructions](https://github.com/AlexEMG/DeepLabCut/blob/master/docs/installation.md#Installation), and installation with conda is indeed straight-forward (see also https://github.com/AlexEMG/DeepLabCut/issues/20#issuecomment-438661814), I'd like to suggest that you deploy a DeepLabCut package via conda/conda-forge in addition to the current package on PyPI.

Instructions for how to create a conda recipe for your package can be found here:
https://conda-forge.org/docs/recipe.html

**Comment by imagejan** [comment]
See also my comment on #20.

In addition to the considerations posted there, I have sporadically seen permission issues with non-admin users on multi-user Windows systems running `pip install` in a conda environments they created. The issue still needs to be investigated, but having a native conda package (instead of telling conda to install via pip as above) would certainly have simplified installation in these cases.

I hope you don't mind if we ship a conda package of DLC via our own conda channel (or conda-forge) in the future, to make it easier for Windows users in our facility (and probably elsewhere). Should you decide to maintain your own conda package at some point, I'd be happy to retire any other packages we created until then.

**Comment by MMathisLab** [comment]
And yes, see our troubleshooting guide at the wiki, on Windows you have to run as admin.


I’m fine making it a conda forge package, I’m not not excited about providing six yml files, (3 operating platforms and cpu vs gpu). I can work on it next week.

**Comment by AlexEMG** [comment]
Sounds interesting - I guess, https://conda.io/docs/user-guide/tasks/create-custom-channels.html allows it to serve different OSs. Perhaps we should all discuss this.

**Comment by MMathisLab** [comment]
Well they can certainly join the development channel on slack if they want. It’s open to whomever.

**Comment by 170987karan** [comment]
Unable to create process using 'C:\Users\KARAN AGGARWAL\Anaconda3\python.exe "C:
\Users\KARAN AGGARWAL\Anaconda3\Scripts\conda-script.py" shell.cmd.exe activate
activate "C:\Users\KARAN AGGARWAL\Anaconda3"'
when i open anaconda prompt then it shows this on prompt. what does it mean?

**Comment by 170987karan** [comment]
what does it mean?

**Comment by 170987karan** [comment]
i want to install deeplabcut in idle but m using window 8. is there anyone who using deeplabcut in window 8 on idle python?
please suggest how and if no please alternate method
