### ISSUE TITLE
Best way to use DLC to limit ID switching 

### ISSUE THREAD

**Issue by catubc** [DeepLabCut/DeepLabCut#1120]
Hello
I previously raised this issue last summer: 

[Suggestions for improvement of DLC multi-animal tracking #747 ](https://github.com/DeepLabCut/DeepLabCut/issues/747
)

and was wondering if any progress has been made in DLC to improve tracking of unique animals over time by learning the shapes/patterns of the animals.  Right now for a 4 animal experiment, DLC outputs great feature tracks- but the IDs are completely scrambled (at chance results).

Any advice is appreciated.
Thank you so much,
catubc

**Comment by MMathisLab** [comment]
If this is still the hamster/gerbil scenario, where your animals are very different looking, you need to use our identity tracker. ;)

**Comment by catubc** [comment]
Great, thanks, where is the identity tracker branch?
C

**Comment by MMathisLab** [comment]
it's not a branch actually,  you set `identity: true` in the `config.yaml`; it's not documented yet, but will be with the paper. @AlexEMG can correct me if that's not exactly correct ^
