### ISSUE TITLE
ma-dlc for single animal project

### ISSUE THREAD

**Issue by levintom** [DeepLabCut/DeepLabCut#1121]
Hello,

My goal is to track a single fish, I want to track the edges of the fish's head and also to track points on its tail. I am using 2.2b8 version. I would very appreciate if someone could help me with the following questions.

1. does the "skeleton" feature can improve the performances of single animal tracking?

2. so far I opened a project with "multianimalproject: true" in the config.yml. while doing so, I am struggling to understand if I should set all of the body parts as "uniquebodyparts"? or as "multianimalbodyparts"? (under only one individual)

3. also, sometimes the tip of the tail cannot be seen when the fish is moving. When that happens, should  I skip this label? or its better to mark the end of the visible tail as a consistent label?

4.  I am using a low dim videos (high saturated grayscale images) - when the fish is on the side I am seeing a different figure (hard to asses depth). because of that, is it ok to also use labels such as "center of the head" which will be marked in different locations due to the posture of the fish? or labels that are suppose to be the edges of the fish without considering the posture of the fish?

5. if the answer to 4 is "yes", should I add those labels also to the skeleton?

Thanks!

edit: I am new here and not sure if this is the right place for those questions, I also opened a topic about this in image.sc because of that. [https://forum.image.sc/t/ma-dlc-for-single-animal-project/49192](url)

**Comment by imagejan** [comment]
You posted exactly the same on the image.sc forum [here](https://forum.image.sc/t/ma-dlc-for-single-animal-project/49192?u=imagejan).

Please:
1. When cross-posting on any two different channels, disclose that you're doing so by including a link to the other post, and
2. Let's keep the discussion on the forum, that's more discoverable for others having similar questions/issues.
