### ISSUE TITLE
How can I merge these two weights together? (the weight of Full_Macaque Model Zoo and the video I labeled)

### ISSUE THREAD

**Issue by yingxuanshi** [DeepLabCut/DeepLabCut#1122]
**Your Operating system and DeepLabCut version**
OS: Ubuntu 18.04 LTS
DeepLabCut Version: 2.1.9
Anaconda env used:Anaconda 3-5.3.1-Linux-x86_64
cuda 10.0, 
cudnn 7.6.5, 
tensorflow-gpu = 1.13.1
python = 3.7

**Describe the problem**
I want to use DeepLabCut to recognize the monkey’s body movements. 
 
Firstly, I downloaded the Full_Macaque weight from the DeepLabCut Model Zoo, and then use this weight to recognize the macaque video that I took. However, the recognition result of my macaque’s body movement video is not that good. 
 
Secondly, I used the DeepLabCut GUI to create a new project, and then labeled 70 pictures of the macaque’s body joint points (The position and order of the points that I labeled are consistent with the Full_Macaque Model Zoo provided). I want to train a new weight.
 
The question is how can I merge these two weights together? 

**How to Reproduce the problem**

1. Go to GUI and create a new project, then I labeled 70 pictures. (I took a macaque video by myself)
2. I closed the GUI. Then I copied the full_macaque weight and renamed into the picture below
![image](https://user-images.githubusercontent.com/54396039/108730784-d4121180-7566-11eb-87b4-5c7f271b0f76.png)
3. I changed many config path. e.g. the path inside the "train/pose_cfg.yamal", "test/pose_cfg.yaml"
4. I typed the code below
![image](https://user-images.githubusercontent.com/54396039/108731141-39660280-7567-11eb-87b5-db0d1e7a6e14.png)
5.  After I typed “deeplabcut.create_training_dataset(path_config_file)” I found that the "init_weights" changed into “/home/yingxuanshi/.conda/envs/DLC/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt”.
So I changed this line into “/home/yingxuanshi/DeepLabCut-master/Monkey-test2_skle_help-2021-02-22/dlc-models/iteration-0/MonkeyFeb22-trainset95shuffle1/train/snapshot-1030000”
![image](https://user-images.githubusercontent.com/54396039/108731219-4f73c300-7567-11eb-8e80-bb22b3413884.png)
6. Then I typed this blew
![image](https://user-images.githubusercontent.com/54396039/108731389-7cc07100-7567-11eb-870d-b8c6b554281b.png)
![image](https://user-images.githubusercontent.com/54396039/108731423-83e77f00-7567-11eb-82d3-f59ff53eb568.png)
![image](https://user-images.githubusercontent.com/54396039/108731446-8944c980-7567-11eb-861a-5365209ce6ea.png)
![image](https://user-images.githubusercontent.com/54396039/108731473-8ea21400-7567-11eb-8cb3-f4d37b115aa7.png)
![image](https://user-images.githubusercontent.com/54396039/108731485-9366c800-7567-11eb-8ec1-ca7c02d28cdb.png)
![image](https://user-images.githubusercontent.com/54396039/108731516-9a8dd600-7567-11eb-9efc-592889049999.png)
7. Then I want to analyse the new video, so I opened the GUI and selected picture below
![image](https://user-images.githubusercontent.com/54396039/108731674-c01adf80-7567-11eb-9d02-5b1da1ff8c80.png)
![image](https://user-images.githubusercontent.com/54396039/108731685-c315d000-7567-11eb-9608-1b92bb92d829.png)

**Additional context**
I don't think the final video merge two weights together, I think the final video only use the weight of "Full_Macaque Model Zoo". 
I tried many times but I do not know how to merge two training weights together and then generate a new weight. 

Forgave me, I only set the (maxiters = 1500) this time. 
This is because I set (maxiters = 5000) before and did the same experiment, still can't get a better result.

**Comment by KonradDanielewski** [comment]
The issue is more suitable for the forum (https://forum.image.sc/tag/deeplabcut) since it's usage help and not code issue. 

Anyhow, correct way is to create training dataset from your labeled videos and train the model with init_weights set to the model downloaded from zoo - which, if I understand correctly, you did. The problem is you only trained for 5k iters, which is way to little, especially considering your batchsize=1. Try to train for 50k and check again. Consider changing batchsize to higher value if your memory capacity allows you to do this.

**Comment by yingxuanshi** [comment]
> The issue is more suitable for the forum (https://forum.image.sc/tag/deeplabcut) since it's usage help and not code issue.
> 
> Anyhow, correct way is to create training dataset from your labeled videos and train the model with init_weights set to the model downloaded from zoo - which, if I understand correctly, you did. The problem is you only trained for 5k iters, which is way to little, especially considering your batchsize=1. Try to train for 50k and check again. Consider changing batchsize to higher value if your memory capacity allows you to do this.

**Comment by yingxuanshi** [comment]
> > The issue is more suitable for the forum (https://forum.image.sc/tag/deeplabcut) since it's usage help and not code issue.
> > Anyhow, correct way is to create training dataset from your labeled videos and train the model with init_weights set to the model downloaded from zoo - which, if I understand correctly, you did. The problem is you only trained for 5k iters, which is way to little, especially considering your batchsize=1. Try to train for 50k and check again. Consider changing batchsize to higher value if your memory capacity allows you to do this.

**Comment by yingxuanshi** [comment]
Thank you so much! 
Yes, you understand me correctly! I will follow your suggestion and try again.

**Comment by yingxuanshi** [comment]
Thank you so much!
Yes, you understand me correctly! I will follow your suggestion and try again.

**Comment by yingxuanshi** [comment]
> The issue is more suitable for the forum (https://forum.image.sc/tag/deeplabcut) since it's usage help and not code issue.
> 
> Anyhow, correct way is to create training dataset from your labeled videos and train the model with init_weights set to the model downloaded from zoo - which, if I understand correctly, you did. The problem is you only trained for 5k iters, which is way to little, especially considering your batchsize=1. Try to train for 50k and check again. Consider changing batchsize to higher value if your memory capacity allows you to do this.



Thank you so much! It worked very well. (I trained for 40K and the batchsize = 1.)
