### ISSUE TITLE
Could not run conda env create -f DLC-GPU.yaml

### ISSUE THREAD

**Issue by Xawwell** [DeepLabCut/DeepLabCut#1123]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Your Operating system and DeepLabCut version**
MacOS Big Sur 11.2.1, I just installed DLC so I believe it should be the latest version, with an Anaconda Env
*****Note, I am trying to run DLC on a remote server from my school.

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: Mac OS
DeepLabCut Version: n/a
Anaconda env used: conda 4.9.2
Tensorflow Version: 2.3.0

**Describe the problem**

When I am trying to run conda env create -f DLC-GPU.yaml
I was encountered with 'ResolvePackageNotFound: '

Please place code inside this:

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - tensorflow-gpu==1.13.1
  - cudnn=7

<details><summary>Code output</summary><p>

ResolvePackageNotFound: 
  - tensorflow-gpu==1.13.1
  - cudnn=7

</p></details>

**How to Reproduce the problem**

**Screenshots**

**Additional context**

**Comment by Xawwell** [comment]
The remoter server os is Darwin Kernel Version 20.3.0

**Comment by MMathisLab** [comment]
@Xawwell macOS is not supported for GPU use, nor is tensorflow 2.3. Please see here for advice on installation! https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/installation.md
