### ISSUE TITLE
pip install downloads many versions of opencv (with 3.8 python)

### ISSUE THREAD

**Issue by svenkreiss** [DeepLabCut/DeepLabCut#1124]
After running `pip install deeplabcut`:

<img width="578" alt="image" src="https://user-images.githubusercontent.com/2775078/108826140-3c431080-75c4-11eb-8d2e-83451b864c13.png">

Versions:
* pip 21.0.1
* python 3.8.6

**Comment by svenkreiss** [comment]
Same with the latest beta: `pip install deeplabcut==2.2b8`

<img width="583" alt="image" src="https://user-images.githubusercontent.com/2775078/108826807-1833ff00-75c5-11eb-9b6a-d8aa1ad9649d.png">

**Comment by MMathisLab** [comment]
Hi @svenkreiss yes, this is with 3.8; if you use 3.7 (and the DLC conda files) it will force you to use 3.7, and then this does not happen :)

**Comment by MMathisLab** [comment]
Hey @svenkreiss I should add, right now tensorflow 1.x is not supported in 3.8 (is my understanding at least(, and currently we require TF 1.x; we do have a dlc-core branch that is for 2.x support, but without any GUI support, etc: https://github.com/DeepLabCut/DeepLabCut-core

https://www.tensorflow.org/install/pip

![Screen Shot 2021-02-25 at 3 09 02 PM](https://user-images.githubusercontent.com/28102185/109165144-83bfcd00-777b-11eb-83de-5f32089d5ec3.png)

**Comment by svenkreiss** [comment]
Thanks for the extra info. I'll wait until Python 3.8 is supported.

**Comment by MMathisLab** [comment]
^ yeah, I was hoping for 3.8 TF1 support; it was initially promised in Dec, I have low hopes now... 

We are currently working on bumping up to TF2 (as is in the core), but some models are not supported, so that limits enthusiasm for a full roll over to TF2.

**Comment by MMathisLab** [comment]
Hi @svenkreiss `pip install deeplabcut-core` now supports TF2, so 3.8 is more doable ;). Hope that helps!
