### ISSUE TITLE
wxPython cannot be ran within a virtual environment in Mac OSX

### ISSUE THREAD

**Issue by m-beau** [DeepLabCut/DeepLabCut#1125]
**Bug:**

It is impossible to use wxPython in a conda (or virtualenv) environment on a Mac. wxPython is the GUI package used, in particular, to label frames in `deeplabcut.label_frames(path_to_config_file)`.

**The workaround** so far is to setup deeplabcut in your root environment (for instance using homebrew to install a python@3.7 version), which isn't ideal as it makes it impossible to use conda altogether. But I thought it would be useful to others to write it here. Another workaround would be to mess with the python interpreter actually used within an environment with symlinks, but this is even more of a mess.

**System:**
 - OS: MacOS Mojave 10.14.6
 - Python version: 3.7.10
 - DeepLabCut Version 2.1.10.2
 - DeepLabCut mode: single animal tracking
 - ran from command line (ipython)
 - wxPython version: 4.0.7.post2 (most recent version 4.1.1 was crashing with the bug [reported here](URL), had to pin the version)

**Steps to reproduce:**
```
$ ipython
>>> import wx
>>> wx.App()
```

**Error:**
`SystemExit: This program needs access to the screen. Please run with a Framework build of python, and only when you are logged in on the main display of your Mac.`

**Comment by backyardbiomech** [comment]
Just use pythonw instead of ipython as stated in the [docs](https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/UseOverviewGuide.md#option-2-using-the-project-manager-gui).. E.g.:
```
pythonw -m deeplabcut
```

or 

```
pythonw
>>> import wx
>>> wx.App()
```

**Comment by m-beau** [comment]
pythonw is an interpreter installed at the system level (/usr/bin/pythonw), so if you do that you do not run the interpreter of your virtual environment - this doesn't solve the issue of having to install DLC at the root level.

**Comment by backyardbiomech** [comment]
If you installed DLC using the DLC-CPU.yaml, then you should have wxpython installed in that env already. 
Activate the env with `conda activate DLC-CPU`, then use pythonw instead of ipython.

Many of us users, plus some of the developers, work on Macs. This works.
```
thismac ~ % conda activate dlc
(dlc) thismac ~ % which pythonw
/Users/thisuser/opt/miniconda3/envs/dlc/bin/pythonw
```

**Comment by m-beau** [comment]
Ok thank you for the tip! I had setup my environment manually, and I didn't think at all that running a regular command-line python session wouldn't work.

Maybe using PyQt for a future upgrade would prevent future users using custom environments from having issues setting DLC up - this is a feature request rather than a bug. Thank you for you help!

**Comment by m-beau** [comment]
> If you installed DLC using the DLC-CPU.yaml, then you should have wxpython installed in that env already.
> Activate the env with `conda activate DLC-CPU`, then use pythonw instead of ipython.
> 
> Many of us users, plus some of the developers, work on Macs. This works.
> 
> ```
> thismac ~ % conda activate dlc
> (dlc) thismac ~ % which pythonw
> /Users/thisuser/opt/miniconda3/envs/dlc/bin/pythonw
> ```

The reason why I didn't have wxPython setup in my environment was because several forums explained that it could simply not be ran from a virtual environment on mac, advising to install it at root level. I was simply confused, sorry!
