### ISSUE TITLE
Analyze_Videos not creating any files

### ISSUE THREAD

**Issue by ghost** [DeepLabCut/DeepLabCut#1127]
I am using DeepLabCut (2.1.10.2) on Google Colab. After labeling the images on my Mac using the GUI, I trained a network for 120,000 iterations on Google Colab and evaluated the network. The trained network seems to be working well with a train error of 3.01 and test error of 5.32. However, when I try to analyze the videos on google Colab, it does not do anything. I have attached an image of the google Colab output below. It does not produce any errors and seems to work well, but then when I go to my videos folder on google drive nothing new has been created, and I am unable to do the plot_trajectories step or extract_outlier_frames step on Google Colab. I found another post similar to this where you were able to help resolve the issue, but I do not think there are any issues with my config file, so I am unsure how to proceed. Thanks for your help.

<img width="1218" alt="Screen Shot 2021-02-26 at 12 08 52 PM" src="https://user-images.githubusercontent.com/70550808/109338200-8b3eaf00-782b-11eb-87f8-4b9c7a481760.png">
<img width="1221" alt="Screen Shot 2021-02-26 at 12 09 08 PM" src="https://user-images.githubusercontent.com/70550808/109338210-8f6acc80-782b-11eb-9d43-718c381b538e.png">
<img width="1228" alt="Screen Shot 2021-02-26 at 12 10 29 PM" src="https://user-images.githubusercontent.com/70550808/109338224-942f8080-782b-11eb-972f-907609f1ca86.png">

Here are images of my config file so that you can make sure everything has been formatted properly:

<img width="649" alt="Screen Shot 2021-02-26 at 12 12 44 PM" src="https://user-images.githubusercontent.com/70550808/109338494-f7b9ae00-782b-11eb-894b-f65b5b36696d.png">
<img width="684" alt="Screen Shot 2021-02-26 at 12 12 56 PM" src="https://user-images.githubusercontent.com/70550808/109338502-fb4d3500-782b-11eb-8f51-7251af8727e0.png">

**Comment by MMathisLab** [comment]
in the` video` folder, there should be a file that ends in `.H5` and `.CSV`; those should be there, given your screenshots, i,e, the video is analyzed, so that function is working.

The `plot_trajectories` you edited in the format of multianimal, i,e, tracker="box" will not work. Not sure why you have this? 

Here is the normal colab notebook you should look to use/build on: https://github.com/DeepLabCut/DeepLabCut/blob/master/examples/COLAB_YOURDATA_TrainNetwork_VideoAnalysis.ipynb

`deeplabcut.plot_trajectories(path_config_file,videofile_path, videotype=VideoType)`
and
`deeplabcut.create_labeled_video(path_config_file,videofile_path, videotype=VideoType)`

Note, your Project Path likely also has an error ... typically in colab/google drive the format is:
 `['/content/drive/My Drive/'+ProjectFolderName+'/videos/'] ` <--- note the space between **My** and **Drive**

**Comment by ghost** [comment]
Thanks for replying! The problem that I'm running into is that the .h5 and .csv files are not present in the video folder. I agree that they should be appearing, so I'm confused why they are not showing up. Here is a screenshot of my Google Drive. Do you have any suggestions on troubleshooting this issue?

<img width="1007" alt="Screen Shot 2021-02-27 at 7 38 10 PM" src="https://user-images.githubusercontent.com/70550808/109405157-39814c00-7933-11eb-9c72-ab31c06393ec.png">

**Comment by MMathisLab** [comment]
very odd then; are you sure it has permission to write/you are truly in that same folder? I can't see any other explanation (sorry!)

**Comment by backyardbiomech** [comment]
Try fixing that lack of space between "My" and "Drive" in the paths in the config file and analyze again. It might seem like it's able to ignore that difference, but figuring out what is actually happening is near impossible until that is corrected.

**Comment by paulapeixotomoledo** [comment]
Hi, I have the same problem as @withercp but I do have an output. The thing is I only get a pickle output, I dont get the h5 or .csv files, I dont know why and I tried doing it in my computer with the GUI and the option to generate a csv does not appear. I am doing a multianimal analysis, is this the reason why I don't get the other outputs? 

Thank you for your help!

**Comment by backyardbiomech** [comment]
@paulapeixotomoledo, Yes, the multi animal tracking first outputs a pickle. You need to convert that to tracklets, which makes another pickle, then saving the refined tracklets will create your h5 and csv.

**Comment by paulapeixotomoledo** [comment]
@backyardbiomech Thank you so much!

**Comment by ghost** [comment]
@backyardbiomech @MMathisLab Thank you for the help. I edited the file paths to make sure that there was a space between My and Drive, and I restarted the project from the beginning to ensure that I had not made an error along the way. Once again,  however, the .h5 and .csv files were not created through running the analyze_videos() functions. I have no idea why this might be occurring. I trained a similar network last year and did not run into this issue. I took screenshots of the outputs from October and the present day, and I observed some differences. For example, I am noticing now that it does not say that csv files are being saved, as it did back in October. Maybe there is something in here that will help you identify the problem. I am using .mp4 files now instead of the .mov files I used previously, so maybe that is contributing to the issues? Another difference is that I am now cropping my videos, whereas previously I did not have to crop them during the analysis step. Here are the screenshots of the outputs below. Let me know if there is anything else I can possibly take a screenshot of or send you to help diagnose the problem. Thanks!

Screenshot from back in October:
<img width="811" alt="Screen Shot 2021-03-05 at 1 16 05 AM" src="https://user-images.githubusercontent.com/70550808/110080740-8492c900-7d50-11eb-89a5-d215530f506c.png">


New screenshots:
<img width="814" alt="Screen Shot 2021-03-05 at 1 21 20 AM" src="https://user-images.githubusercontent.com/70550808/110081119-139fe100-7d51-11eb-9f24-511f897de57d.png">
<img width="784" alt="Screen Shot 2021-03-05 at 1 21 34 AM" src="https://user-images.githubusercontent.com/70550808/110081166-23b7c080-7d51-11eb-9cda-4d2160c2bb0d.png">
<img width="824" alt="Screen Shot 2021-03-05 at 1 21 48 AM" src="https://user-images.githubusercontent.com/70550808/110081185-2b776500-7d51-11eb-9fb5-684248d48c3d.png">

**Comment by backyardbiomech** [comment]
There is a flag (save_as_csv=True), and a checkbox in the GUI to set when calling analyze videos in order to save the output as csv. It's not set to true by default, so that's not a big deal.

Notice when it loads the video (`Starting to analyze % /content/drive/MyDrive/SAP...`) it still shows no space between My and Drive. That would be the path you are entering for the video itself. My "concern" here is that you could actually have two very different folders in your Google Drive: one at `/content/drive/My Drive/`, and one at `/content/drive/MyDrive/`. Since it's finding the videos at `MyDrive`, it should be saving the outputs at `MyDrive`, but you're looking in `My Drive` for the outputs. At least, this would be the case on a local drive. Since this is Google, I'm not sure if `MyDrive` can actually exist (though I suspect it does), and if it does I don't know if you can actually access it. Since it loads the videos, it either does exist and you can't see it, or it doesn't exist and Colab is kindly correcting the typo by remapping the file load with the space, but it may not be so kind when writing new files.

**Comment by ghost** [comment]
Thank you for pointing out that there were still places in the code where I omitted the space between My and Drive! I just went through and fixed all of those locations, but it did not help. Here are screenshots of the function call outputs from this morning.

<img width="1214" alt="Screen Shot 2021-03-05 at 12 04 40 PM" src="https://user-images.githubusercontent.com/70550808/110155734-aa998700-7dab-11eb-95f5-c5165634c13f.png">

<img width="1232" alt="Screen Shot 2021-03-05 at 12 04 52 PM" src="https://user-images.githubusercontent.com/70550808/110155747-ae2d0e00-7dab-11eb-94ba-87e18da242b7.png">

A few other things:
- I checked to see if the video file is corrupt using the VideoReader functions and there was no error raised, so this makes me thing that the issue is not the video itself.
- I tried running the command %ls once inside of content/drive/ and this was the output

<img width="237" alt="Screen Shot 2021-03-05 at 12 12 18 PM" src="https://user-images.githubusercontent.com/70550808/110155876-e46a8d80-7dab-11eb-9b54-a484dbc67809.png">

This makes me think that MyDrive and My Drive are the same possibly?

- I also have this error from when I first install deeplabcut using "pip". Is it possible that these incompatibility errors are affecting the function failure?

<img width="926" alt="Screen Shot 2021-03-05 at 1 50 23 AM" src="https://user-images.githubusercontent.com/70550808/110155983-0a902d80-7dac-11eb-934f-924adb517552.png">

**Comment by ghost** [comment]
Important update!!

I just tried a different video file that was .MOV with the same network and it works properly! It is definitely the .MP4 file that is not working for me. Why might this be the case?

<img width="1168" alt="Screen Shot 2021-03-05 at 12 25 09 PM" src="https://user-images.githubusercontent.com/70550808/110157411-bf771a00-7dad-11eb-9531-4b1b11d784e1.png">

<img width="1228" alt="Screen Shot 2021-03-05 at 12 25 31 PM" src="https://user-images.githubusercontent.com/70550808/110157419-c30aa100-7dad-11eb-986d-9e30c4e3b897.png">

Note that in these screenshots, I changed VideoType from "mp4" to "MOV," and I changed the cropping setting in the .config file to false because this .MOV file has a smaller dimension and does not need to be cropped.

**Comment by ghost** [comment]
As information for future people encountering this problem, I was finally able to move past this challenge by converting my .MP4 file into a .MOV file. I am unsure why .mp4 is not working with the analyze_videos function for me, but I used this code to make a conversion:

`!ffmpeg -i 12Feb2021-SAPAP3-264-1.MP4 -vcodec copy -acodec copy 12Feb2021-SAPAP3-264-1.MOV`

@backyardbiomech If you are aware of why I might need to convert to .MOV files, then your advice would be helpful, but otherwise I will proceed with converting all of my files to .MOV using this code. Thanks for your help.

**Comment by MMathisLab** [comment]
@withercp my sense is if you re-code them even as MP4 it would work (perhaps some meta data is corrupted); seems some corruption or path issue. I can confirm I am currently running MP4 videos on colab tonight ;)
