### ISSUE TITLE
Web Variant => No Installation

### ISSUE THREAD

**Issue by AlexanderMath** [DeepLabCut/DeepLabCut#1129]
**Is your feature request related to a problem? Please describe.**
It seems most users waste 1-10 hours installing DLC. I don't see any technical issues that prevent a similar system to work as a homepage with HTML5 using TensorFlow.js. 

**Describe the solution you'd like**
Homepage allow video upload (or recording w/ camera from smartphone) and subsequent labeling. Then trains model and allow sharing trained model through link. Opening the link automatically opens camera on smartphone and runs mobilenet version of model for live tracking. 

Emphasis: this will save users hours of time failing to install dependencies AND allow users with no tech savvy.

Emphasis: this is surprisingly easy to do with HTML5.

**Describe alternatives you've considered**
I'm going to write this myself when I get ~3 weeks free time. I have to write thesis, grant proposal and do an internship the next few months, but I expect to find time on weekends to finish this before September. 

I write here to
- Hear any concerns for developing such system
- Make sure this is not already being developed so i waste my time.
- Find people to discuss the system with. 
- Discuss idea to reduce training time to ~10seconds using linear algebra trick and a novel data augmentation.

**Comment by AlexEMG** [comment]
Thanks for the comment and welcome to the community. Most users (in biology), want to run the sofware on their system, but a web based system is of course of interest for some users. We have made a python based web-app and are happy share it. 

Anyway, I think most users can install a conda file in just a few minutes (based on our user survey), and of course can use colab (without installation). But of course anything that makes the installation for users easier, is of interest.

I'm certainly most interested in your final idea to reduce the training time to 10s!

**Comment by AlexanderMath** [comment]
> I'm certainly most interested in your final idea to reduce the training time to 10s!

Thanks for the feedback. Then I'll spend most of my time on this and let you know if it works out. 

> We have made a python based web-app and are happy share it.

That would be very useful.

> I think most users can install a conda file in just a few minutes (based on our user survey).

Did you chose the users by uniform random sampling a biology department? I imagine there is a sampling bias if the survey is based on biologists that already use the system. 

Disclaimer: I think DLC is awesome, more ML people should be working on making ML applicable like you are.

**Comment by jeylau** [comment]
Hey @AlexanderMath, any update on your exciting proposal? 🤩

**Comment by fhvilshoj** [comment]
This is a very interesting feature request - an awesome tool, even more accessible! :trophy: 

> I think most users can install a conda file in just a few minutes (based on our user survey).

I am an ML phd. Conda installation is easy, but I spent ~3 hours before I had your code running properly on my system - in case you want another datapoint for your survey :sweat_smile: 

I will start developing an open source, MIT licensed, web-based solution during the summer. @AlexanderMath I will be very happy to include any improvements on training speed, should you manage to come up with any linear algebra magic :mage: 

You can follow or contribute to the project on my github: [https://github.com/fhvilshoj/DeepWebCut](https://github.com/fhvilshoj/DeepWebCut) :slightly_smiling_face:

**Comment by MMathisLab** [comment]
@fhvilshoj we already have a web-based labeling version that will be made available soon: https://contrib.deeplabcut.org/

you also cannot license DLC under MIT, it must stay within our licensing guidelines.

**Comment by fhvilshoj** [comment]
Awesome that you are making a web-based labeling solution. It will be really valuable!

**Comment by lnguyen** [comment]
Do you know when this web based label is going to be released?
