### ISSUE TITLE
can't upload frames

### ISSUE THREAD

**Issue by sinal23** [DeepLabCut/DeepLabCut#1131]
Hello, 
I've recently downloaded deeplabcut and I am using it with windows 10, anaconda, deeplabcut=2.1.10.2, python= 3.7.9 and I am using the GUI version on CPU. 
I was able to run the test code, and open a new project and extract frames. 
However, when I try to open these frames the GUI shows no images, even though I do have them there. 
can you help me fix this problem? 
Thank you.

**Comment by KonradDanielewski** [comment]
Since you report no error I assume that you're trying to select image files. When trying to load images to labelling GUI you select a folder containing extracted frames not the frames themselves.
