### ISSUE TITLE
testscript_multianimal ERROR

### ISSUE THREAD

**Issue by neurologic** [DeepLabCut/DeepLabCut#1135]
**Describe the bug**

I am getting an error from testscript_multianimal as described below. The final error is a 'FileNotFoundError' for the 'm3v1mp4shortDLC_resnet_50_multi_mouseMar5shuffle1_5_full.pickle' file in the videos directory of the multi_mouse directory created by the testscript.

**Desktop:**
 - OS: Mac Catalina (10.15)
 - Anaconda environment DLC-CPU
 - DeepLabCut Version 2.1.10.2 
            > ***This is also part of my question though (and might provide a quick answer to the 'bug'), so I will elaborate briefly here. I was previously using version 2.2b8 and achieving successful testscript_multianimal testing. However, in a recent query to the forum on dealing with variable numbers of animals across different videos/experiments (https://forum.image.sc/t/training-variable-number-of-animals-in-multi-animal/38374), I was advised that v2.2b8 was no longer supported and to use v2.1.10.2 instead; and that in v2.1.10.2, multianimal tracking was now supported. Is this true? If so, then I need to solve this error that I am getting with the testscript. But if not, and if I am supposed to be using v2.2b8, then I do not have this error.***
 - DeepLabCut mode = multi-animal tracking

**To Reproduce**
1. Activate DLC-CPU
2. Navigate to the cloned git deeplabcut/examples
3. run `pythonw testscript_multianimal.py`
4. See error:

<details><summary>TRACEBACK</summary><p>

```python

Using snapshot-5 for model /Users/kperks/DeepLabCut/examples/multi_mouse-dlc_team-2021-03-05/dlc-models/iteration-0/multi_mouseMar5-trainset80shuffle1
Initializing ResNet
Activating extracting of PAFs
No video(s) were found. Please check your paths and/or 'video_type'.
Video analyzed.
Create video with all detections...
Creating labeled video for  m3v1mp4short
Traceback (most recent call last):
  File "testscript_multianimal.py", line 135, in <module>
    deeplabcut.create_video_with_all_detections(config_path, [new_video_path], scorer)
  File "/Users/kperks/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/utils/make_labeled_video.py", line 810, in create_video_with_all_detections
    with open(full_pickle, "rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kperks/DeepLabCut/examples/multi_mouse-dlc_team-2021-03-05/videos/m3v1mp4shortDLC_resnet_50_multi_mouseMar5shuffle1_5_full.pickle'

```
</p></details>

**Expected behavior**
Testscript completes

**Additional context**
I suppose the elaboration I wrote in the first section should have gone here, but if it was the obvious issue then I wanted to nip it in the bud earlier in the post.

THANK YOU!

**Comment by MMathisLab** [comment]
indeed 2.10.2 has maDLC in it; it might be that the github code is slightly farther ahead for maDLC though. if you use the "bleeding" edge, I can confirm it's working in my hands. 

Here is how to install the latest: https://github.com/DeepLabCut/DeepLabCut/wiki/How-to-use-the-latest-GitHub-code
