### ISSUE TITLE
Question Labeling Frame using Google Colab

### ISSUE THREAD

**Issue by JiHyunKu** [DeepLabCut/DeepLabCut#1136]
Hello! I am new to DeepLabCut. I am currently using Google Colab for analyzing the video. When we are supposed to label the frames locally, are there any tips as to how to? Should we use GUI or terminal (I am using Mac here)?

**Comment by MMathisLab** [comment]
HI @JiHyunKu welcome. Also, please note GitHUb should be for code bug reports For questions, please go to the user forum here: https://forum.image.sc/tag/deeplabcut. 

For all the docs, video tutorials, etc please go here: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/UseOverviewGuide.md

**Comment by JiHyunKu** [comment]
> HI @JiHyunKu welcome. Also, please note GitHUb should be for code bug reports For questions, please go to the user forum here: https://forum.image.sc/tag/deeplabcut.
> 
> For all the docs, video tutorials, etc please go here: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/UseOverviewGuide.md

Thank you!
