### ISSUE TITLE
Request for hotkeys in labbeling GUI

### ISSUE THREAD

**Issue by joeribordes** [DeepLabCut/DeepLabCut#1137]
**Is your feature request related to a problem? Please describe.**
Not a big problem, but when I am labeling, I am always constantly clicking on "zoom", "home" and "pan" buttons, which would be great if one can quickly access the functions. 

**Describe the solution you'd like**
I would like to have hot keys for the functions, so for zoom for instance pressing "z", for home pressing "h" and maybe for panning you can hold the space bar to perform the pan.

Would be great! Let me know if that would be possible. 

Joeri

**Comment by austin2118ace** [comment]
Plan to take a swing at this here in a few days here

**Comment by arjunt19** [comment]
> Plan to take a swing at this here in a few days here

Did you figure out how to do this? I tried, but I couldn't find where the zoom/pan functionality was implemented.

**Comment by austin2118ace** [comment]
I briefly took a look but was also having trouble getting my own custom keybinds to execute the functions that were attached to the buttons. I had to move on to other things and didn't get to put a lot of time into it though unfortunately.

**Comment by jeylau** [comment]
@austin2118ace @arjunt19 @joerikb, please take a look at the alpha release of our napari-based labeling GUI. It grants you guys more freedom in how you can interact with your images/annotations, notably with new labeling modes, easy toggle between labeling/pan, etc. There are hotkeys for most action 😊
