### ISSUE TITLE
tf2.4 maDLC Exception: Unsupported dataset_type: "multi-animal-imgaug"

### ISSUE THREAD

**Issue by Huangjiahui1** [DeepLabCut/DeepLabCut#1138]
linux centos18.04 GTX 3090 TF 2.4  deeplabcutcore

I tried to use "deeplabcutcore.train_network" to start the training, but the following error occurred
Exception: Unsupported dataset_type: "multi-animal-imgaug"
Is 3090 not currently supported for MADLC?Is there an alternative solution? thank you

[GCC 7.3.0] :: Anaconda, Inc. on linux
>>> config_path="/mnt/jump8-hjh-2021-03-04/config.yaml"
>>> deeplabcutcore
<module 'deeplabcutcore' from '/root/miniconda3/lib/python3.7/site-packages/deeplabcutcore/__init__.py'>
>>> Deeplabcutcore.train_network(config_path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Deeplabcutcore' is not defined
>>> Deeplabcut.train_network(config_path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Deeplabcut' is not defined
>>> deeplabcutcore.train_network(config_path)
Config:
{'all_joints': [[0], [1], [2], [3], [4]],
 'all_joints_names': ['b1', 'b2', 'b3', 'b4', 'b5'],
 'alpha_r': 0.02,
 'batch_size': 8,
 'bottomheight': 400,
 'crop': False,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_jump8Mar4/jump8_hjh95shuffle1.pickle',
 'dataset_type': 'multi-animal-imgaug',
 'decay_steps': 30000,
 'deterministic': False,
 'display_iters': 50,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': '/root/miniconda3/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'lr_init': 0.0005,
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_jump8Mar4/Documentation_data-jump8_95shuffle1.pickle',
 'min_input_size': 64,
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.0001, 7500], [5e-05, 12000], [1e-05, 200000]],
 'net_type': 'resnet_50',
 'num_joints': 5,
 'num_limbs': 4,
 'optimizer': 'adam',
 'pafwidth': 20,
 'pairwise_huber_loss': False,
 'pairwise_loss_weight': 0.1,
 'pairwise_predict': False,
 'partaffinityfield_graph': [[0, 1], [3, 4], [2, 3], [1, 2]],
 'partaffinityfield_predict': True,
 'pos_dist_thresh': 20,
 'project_path': '/mnt/jump8-hjh-2021-03-04',
 'regularize': False,
 'rightwidth': 400,
 'rotation': 25,
 'rotratio': 0.4,
 'save_iters': 1000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': '/mnt/jump8-hjh-2021-03-04/dlc-models/iteration-0/jump8Mar4-trainset95shuffle1/train/snapshot',
 'stride': 8.0,
 'topheight': 400,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/lib/python3.7/site-packages/deeplabcutcore/pose_estimation_tensorflow/training.py", line 134, in train_network
    raise e
  File "/root/miniconda3/lib/python3.7/site-packages/deeplabcutcore/pose_estimation_tensorflow/training.py", line 132, in train_network
    train(str(poseconfigfile),displayiters,saveiters,maxiters,max_to_keep=max_snapshots_to_keep,keepdeconvweights=keepdeconvweights,allow_growth=allow_growth) #pass on path and file name for pose_cfg.yaml!
  File "/root/miniconda3/lib/python3.7/site-packages/deeplabcutcore/pose_estimation_tensorflow/train.py", line 118, in train
    dataset = create_dataset(cfg)
  File "/root/miniconda3/lib/python3.7/site-packages/deeplabcutcore/pose_estimation_tensorflow/dataset/factory.py", line 42, in create
    raise Exception("Unsupported dataset_type: \"{}\"".format(dataset_type))
Exception: Unsupported dataset_type: "multi-animal-imgaug"

**Comment by KonradDanielewski** [comment]
I'm pretty sure maDLC is not supported for deeplabcut-core yet, though may be wrong (I don't see code for maDLC in core repo)

**Comment by AlexEMG** [comment]
@KonradDanielewski is absolutely correct. This will be updated soon though.

**Comment by AlexEMG** [comment]
Yes!
