### ISSUE TITLE
running the test

### ISSUE THREAD

**Issue by sinal23** [DeepLabCut/DeepLabCut#1139]
I am using deeplabcut 2.1.10.2, on windows 10, anaconda.

**Describe the problem**
I tried running the testing code in one of the youtube tutorial (python testscript.py) and ran into this error: 
"You passed a split with the following fraction: 77%
The training dataset is successfully created. Use the function 'train_network' to start training. Happy training!
The training dataset is successfully created. Use the function 'train_network' to start training. Happy training!
ALL DONE!!! - default cases are functional.
Re-import DLC with env. variable set to test DLC light mode.
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~\Desktop\DeepLabCut\examples\testscript.py in <module>
    405     print("Re-import DLC with env. variable set to test DLC light mode.")
    406     os.environ["DLClight"] = "True"
--> 407     subprocess.call(["python3", "-c", "import deeplabcut"])

~\anaconda3\envs\dlc-cpu\lib\subprocess.py in call(timeout, *popenargs, **kwargs)
    337     retcode = call(["ls", "-l"])
    338     """
--> 339     with Popen(*popenargs, **kwargs) as p:
    340         try:
    341             return p.wait(timeout=timeout)

~\anaconda3\envs\dlc-cpu\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    798                                 c2pread, c2pwrite,
    799                                 errread, errwrite,
--> 800                                 restore_signals, start_new_session)
    801         except:
    802             # Cleanup if the child failed starting.

~\anaconda3\envs\dlc-cpu\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1205                                          env,
   1206                                          os.fspath(cwd) if cwd is not None else None,
-> 1207                                          startupinfo)
   1208             finally:
   1209                 # Child is launched. Close the parent's copy of those pipe

FileNotFoundError: [WinError 2] The system cannot find the file specified"

**How to Reproduce the problem**
1. git clone https://github.com/AlexEMG/DeepLabCut.git
2. ran into problems (video not found) when I ran the test in the examples so reinstalled ffmpeg (conda install -c conda-forge ffmpeg)
3. still did not work and gave me the issue presented here 
4. deleted and cloned the files again 
5. still gave this issue when ran the test 

thank you!

**Comment by jeylau** [comment]
The fact that it printed out that all cases were functional indicates that the test script ran until the end without issues.
It is that redundant subprocess call at the end that is problematic; could you maybe try with subprocess.run instead?
