### ISSUE TITLE
Error installing DeepLabCut docker in AWS 

### ISSUE THREAD

**Issue by Shachafbe** [DeepLabCut/DeepLabCut#1140]
Hi,

I followed the instructions on GitHub - DeepLabCut/Docker4DeepLabCut2.0: Docker container for running DeepLabCut 2.0+ (linux support only)

I tried to run the command below:

GPU=1 bash ./dlc-docker run -d -p 2351:8888 -e USER_HOME=$HOME/DeepLabCut --name containername dlc_username/dlcdocker

And I received the following error:

1 nvidia-docker run -v /home/ubuntu:/home/ubuntu -p 55187:22 -p 2351:8888 -e USER_GROUPS=sudo -e USER=ubuntu -e USER_ID=1000 -e USER_ENCRYPTED_PASSWORD=aa5V9MSdgw5ec -e USER_HOME=/home/ubuntu -e GPU=1 -e DISPLAY= -d -e USER_HOME=/home/ubuntu/DeepLabCut --name MyTestContainer dlc_username/dlcdocker

3be1723913b655ae06a3b8b0bdb43503fdcfc9316c73f665bfab18c645be9c0d

docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: Running hook #1:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: device error: 1: unknown device: unknown.

I appreciate any help you can provide.
Shachaf.

**Comment by MMathisLab** [comment]
Hi @Shachafbe please open issues where the code is the issue, i.e. on the link you reference ` DeepLabCut/Docker4DeepLabCut2.0`
