### ISSUE TITLE
FileNotFoundError when running triangulate in 3D DLC

### ISSUE THREAD

**Issue by maimechevee** [DeepLabCut/DeepLabCut#1143]
OS:  Windows 10
DeepLabCut Version: 2.2b8
Anaconda env used: DLC-GPU

**Describe the problem**

Hello, I seem to be missing the .h5 basic output file from the 2d DLC analyses, which gives me the error below when I run deeplabcut.triangulate(config_path3d, Videos_folder_path, filterpredictions=True). 

I have tried pre-analyzing the videos, in which case I get output files with the following endings (I'm happy with these):
'_bx.h5'
'_bx.pickle'
'_bx_filtered.csv'
'_bx_filtered.h5'
'_bx_filtered_bp_labeled.mp4'
'_filtered.csv'
'_filtered.h5'
'_full.pickle'
'_meta.pickle'

Or letting the triangulate function run the deeplabcut.analyze_videos() command. in which case the only outputs created (before it errors) are:
'_full.pickle'
'_meta.pickle'

Please place code inside this:
config_path3d='C:\\Users\Brown Lab\Desktop\Calipari Lab\Mice\Test3D-Maxime-2021-03-05-3d\config.yaml'
deeplabcut.calibrate_cameras(config_path3d, cbrow=7, cbcol=5, calibrate=True, alpha=0.9)
deeplabcut.check_undistortion(config_path3d, cbrow=7, cbcol=5)
Videos_folder_path='C:\\Users\\Brown Lab\\Desktop\\Calipari Lab\\Mice\\Inscopix\\3146-210226-135049'
deeplabcut.triangulate(config_path3d, Videos_folder_path, filterpredictions=True)

<details><summary>Code output</summary><p>
List of pairs: [['C:\\Users\\Brown Lab\\Desktop\\Calipari Lab\\Mice\\Inscopix\\3146-210226-135049\\Inscopix-210208-082641_3146-210226-135049_Cam1.avi', 'C:\\Users\\Brown Lab\\Desktop\\Calipari Lab\\Mice\\Inscopix\\3146-210226-135049\\Inscopix-210208-082641_3146-210226-135049_Cam2.avi']]
Analyzing video C:\Users\Brown Lab\Desktop\Calipari Lab\Mice\Inscopix\3146-210226-135049\Inscopix-210208-082641_3146-210226-135049_Cam1.avi using config_file_Cam1
Using snapshot-70000 for model C:\Users\Brown Lab\Desktop\Calipari Lab\Mice\cueFR5-Maxime-2021-02-23\dlc-models\iteration-0\cueFR5Feb23-trainset95shuffle1
Initializing ResNet
Activating extracting of PAFs
  0%|                                                                                        | 0/12549 [00:00<?, ?it/s]
Starting to analyze %  C:\Users\Brown Lab\Desktop\Calipari Lab\Mice\Inscopix\3146-210226-135049\Inscopix-210208-082641_3146-210226-135049_Cam1.avi
C:\Users\Brown Lab\Desktop\Calipari Lab\Mice\Inscopix\3146-210226-135049  already exists!
Loading  C:\Users\Brown Lab\Desktop\Calipari Lab\Mice\Inscopix\3146-210226-135049\Inscopix-210208-082641_3146-210226-135049_Cam1.avi
Duration of video [s]:  627.45 , recorded with  20.0 fps!
Overall # of frames:  12549  found with (before cropping) frame dimensions:  640 480
Starting to extract posture
12625it [14:57, 13.99it/s]                                                                                             
Detected frames:  12549
12625it [15:01, 14.00it/s]
Saving results in C:\Users\Brown Lab\Desktop\Calipari Lab\Mice\Inscopix\3146-210226-135049...
The videos are analyzed. Time to assemble animals and track 'em... 
 Call 'create_video_with_all_detections' to check multi-animal detection quality before tracking.
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
C:\Users\Brown Lab\Desktop\Calipari Lab\Mice\Inscopix\3146-210226-135049 Inscopix-210208-082641_3146-210226-135049_Cam1 DLC_resnet50_cueFR5Feb23shuffle1_70000
Filtering with median model C:\Users\Brown Lab\Desktop\Calipari Lab\Mice\Inscopix\3146-210226-135049\Inscopix-210208-082641_3146-210226-135049_Cam1.avi
No unfiltered data file found in C:\Users\Brown Lab\Desktop\Calipari Lab\Mice\Inscopix\3146-210226-135049 for video Inscopix-210208-082641_3146-210226-135049_Cam1 and scorer DLC_resnet50_cueFR5Feb23shuffle1_70000.
Analyzing video C:\Users\Brown Lab\Desktop\Calipari Lab\Mice\Inscopix\3146-210226-135049\Inscopix-210208-082641_3146-210226-135049_Cam2.avi using config_file_Cam2
Using snapshot-40000 for model C:\Users\Brown Lab\Desktop\Calipari Lab\Mice\cueFR5-Maxime-2021-02-11\dlc-models\iteration-0\cueFR5Feb11-trainset95shuffle1
Initializing ResNet
Activating extracting of PAFs
  0%|                                                                                        | 0/12527 [00:00<?, ?it/s]
Starting to analyze %  C:\Users\Brown Lab\Desktop\Calipari Lab\Mice\Inscopix\3146-210226-135049\Inscopix-210208-082641_3146-210226-135049_Cam2.avi
C:\Users\Brown Lab\Desktop\Calipari Lab\Mice\Inscopix\3146-210226-135049  already exists!
Loading  C:\Users\Brown Lab\Desktop\Calipari Lab\Mice\Inscopix\3146-210226-135049\Inscopix-210208-082641_3146-210226-135049_Cam2.avi
Duration of video [s]:  417.57 , recorded with  30.0 fps!
Overall # of frames:  12527  found with (before cropping) frame dimensions:  640 480
Starting to extract posture
12625it [17:39, 11.80it/s]                                                                                             
Detected frames:  12527
12625it [17:41, 11.89it/s]
Saving results in C:\Users\Brown Lab\Desktop\Calipari Lab\Mice\Inscopix\3146-210226-135049...
The videos are analyzed. Time to assemble animals and track 'em... 
 Call 'create_video_with_all_detections' to check multi-animal detection quality before tracking.
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
C:\Users\Brown Lab\Desktop\Calipari Lab\Mice\Inscopix\3146-210226-135049 Inscopix-210208-082641_3146-210226-135049_Cam2 DLC_resnet50_cueFR5Feb11shuffle1_40000
Filtering with median model C:\Users\Brown Lab\Desktop\Calipari Lab\Mice\Inscopix\3146-210226-135049\Inscopix-210208-082641_3146-210226-135049_Cam2.avi
No unfiltered data file found in C:\Users\Brown Lab\Desktop\Calipari Lab\Mice\Inscopix\3146-210226-135049 for video Inscopix-210208-082641_3146-210226-135049_Cam2 and scorer DLC_resnet50_cueFR5Feb11shuffle1_40000.
Undistorting...
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-19-4a6d0d62bfee> in <module>
----> 1 deeplabcut.triangulate(config_path3d, Videos_folder_path, filterpredictions=True)

~\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_3d\triangulation.py in triangulate(config, video_path, videotype, filterpredictions, filtertype, gputouse, destfolder, save_as_csv)
    302                 path_stereo_file,
    303             ) = undistort_points(
--> 304                 config, dataname, str(cam_names[0] + "-" + cam_names[1]), destfolder
    305             )
    306             if len(dataFrame_camera1_undistort) != len(dataFrame_camera2_undistort):

~\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_3d\triangulation.py in undistort_points(config, dataframe, camera_pair, destfolder)
    451     if True:
    452         # Create an empty dataFrame to store the undistorted 2d coordinates and likelihood
--> 453         dataframe_cam1 = pd.read_hdf(dataframe[0])
    454         dataframe_cam2 = pd.read_hdf(dataframe[1])
    455         scorer_cam1 = dataframe_cam1.columns.get_level_values(0)[0]

~\Anaconda3\envs\DLC-GPU\lib\site-packages\pandas\io\pytables.py in read_hdf(path_or_buf, key, mode, errors, where, start, stop, columns, iterator, chunksize, **kwargs)
    385 
    386         if not exists:
--> 387             raise FileNotFoundError(f"File {path_or_buf} does not exist")
    388 
    389         store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)

FileNotFoundError: File C:\Users\Brown Lab\Desktop\Calipari Lab\Mice\Inscopix\3146-210226-135049\Inscopix-210208-082641_3146-210226-135049_Cam1DLC_resnet50_cueFR5Feb23shuffle1_70000.h5 does not exist

</p></details>

**How to Reproduce the problem**
1. After calibrating the videos, I ran this line which generated the error copied above: deeplabcut.triangulate(config_path3d, Videos_folder_path, filterpredictions=True)
2. When I tested it by pre-analyzing each video separately, this was the code:
Home_dir='C://Users//Brown Lab//Desktop//Calipari Lab//Mice'
mice=['Inscopix']
for mouse in mice:
    mouse_dir=os.path.join(Home_dir,mouse)
    Dates=['3146-210226-135049']
    for date in Dates:
        date_dir=os.path.join(mouse_dir, date)
        #path_config_file='C:\\Users\\Brown Lab\\Desktop\\Calipari Lab\\Mice\\cueFR5-Maxime-2021-02-11\\config.yaml'
        path_config_file='C:\\Users\\Brown Lab\\Desktop\\Calipari Lab\\Mice\\cueFR5-Maxime-2021-02-23\\config.yaml'

        videofile=[x for x in os.listdir(date_dir) if 'Cam2' in x][0]
         #define video location
        videofile_path =os.path.join(date_dir,videofile)

        #Analyze video
        scorename=deeplabcut.analyze_videos(path_config_file,videofile_path, videotype='.avi')

        #convert detections to tracklets
        deeplabcut.convert_detections2tracklets(path_config_file, videofile_path, videotype='mp4', shuffle=1, trainingsetindex=0, track_method='box', overwrite=True)

        #formatting of outputs
        tracklet_file_path =os.path.join(date_dir,[f for f in os.listdir(date_dir) if f[-10:]=='_bx.pickle'][0])
        deeplabcut.convert_raw_tracks_to_h5(path_config_file,tracklet_file_path, min_tracklet_len=0) 

        #filter
        deeplabcut.filterpredictions(path_config_file,videofile_path, track_method='box')

        #Save results
        deeplabcut.refine_training_dataset.convert_raw_tracks_to_h5(path_config_file, tracklet_file_path)

        #Make and save labeled video
        deeplabcut.create_labeled_video(path_config_file,videofile_path, track_method='box', filtered=True, draw_skeleton=True)

Thank you!

**Comment by jeylau** [comment]
Hello! The fonction `triangulate` only works on multi-animal projects since recently (https://github.com/DeepLabCut/DeepLabCut/commit/daac6d38978961f02a182e55e0e41588a3162af9#diff-39881479f7528a628b4233cd7f553297b3ddf89aa7da33e0870a5395612eecda). You'd need DLC 2.1.10 at least 😊

**Comment by maimechevee** [comment]
Hi!
Sorry I’m a little confused.. in this case I did use maDLC to analyze the 2D videos, so shouldn’t it be ok? Also I’m scared that installing an older version will mess up the rest, which is currently working great :)

**Comment by jeylau** [comment]
No problem! The analysis of 2D videos with maDLC produces slightly different outputs, which are only accounted for since the link I posted earlier. 2.1.10 is more recent than 2.2b8 :)

**Comment by maimechevee** [comment]
Oh ok perfect. I will try today, thanks!

**Comment by maimechevee** [comment]
Hi again, 

I installed 2.1.10 and re-ran triangulate with both approaches but get the exact same results.
Specifically:
- If I run triangulate on unanalyzed videos it only outputs pickle files, not h5.
- If I pre-analyze each video, I don't seem to output the 'right' h5 file.

Thanks again for your help :)

**Comment by jeylau** [comment]
Could you please give me some more details? Is there any error? What do you mean by not getting the "right" h5 file?

**Comment by maimechevee** [comment]
Hi,

Yes the error  is:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-6-4a6d0d62bfee> in <module>
----> 1 deeplabcut.triangulate(config_path3d, Videos_folder_path, filterpredictions=True)

~\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_3d\triangulation.py in triangulate(config, video_path, videotype, filterpredictions, filtertype, gputouse, destfolder, save_as_csv)
    300                 path_stereo_file,
    301             ) = undistort_points(
--> 302                 config, dataname, str(cam_names[0] + "-" + cam_names[1])
    303             )
    304             if len(dataFrame_camera1_undistort) != len(dataFrame_camera2_undistort):

~\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_3d\triangulation.py in undistort_points(config, dataframe, camera_pair)
    449     if True:
    450         # Create an empty dataFrame to store the undistorted 2d coordinates and likelihood
--> 451         dataframe_cam1 = pd.read_hdf(dataframe[0])
    452         dataframe_cam2 = pd.read_hdf(dataframe[1])
    453         scorer_cam1 = dataframe_cam1.columns.get_level_values(0)[0]

~\Anaconda3\envs\DLC-GPU\lib\site-packages\pandas\io\pytables.py in read_hdf(path_or_buf, key, mode, errors, where, start, stop, columns, iterator, chunksize, **kwargs)
    385 
    386         if not exists:
--> 387             raise FileNotFoundError(f"File {path_or_buf} does not exist")
    388 
    389         store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)

FileNotFoundError: File C:\Users\Brown Lab\Desktop\Calipari Lab\Mice\Inscopix\3146-210226-135049\Inscopix-210208-082641_3146-210226-135049_Cam1DLC_resnet_50_cueFR5Feb23shuffle1_70000.h5 does not exist


And what I mean is that when I pre-analyze the videos, the only h5 files I output have either 'box' or 'box_filtered' or 'filtered' tacked on at the end. I don't produce one with no additional label, as the triangulate function seems to be looking for.

And if I don't pre-analyze and simply run triangulate, no h5 are produced at all, only pickle files. So it crashes with the same error.

So I guess my question is how to produce this file, using either method?

Sorry, I hope this is clearer. Thanks!

**Comment by MMathisLab** [comment]
windows has path limit rules, so I bet this is just too long; can you move the folder to the desktop? "File C:\Users\Brown Lab\Desktop\Calipari Lab\Mice\Inscopix\3146-210226-135049\Inscopix-210208-082641_3146-210226-135049_Cam1DLC_resnet_50_cueFR5Feb23shuffle1_70000.h5 d"

**Comment by maimechevee** [comment]
Thanks for the suggestion! 
I ended up working around the need for 3D for now, but I will give it a try again when I get the chance and post here whether that solved the problem. Thanks again :)
