### ISSUE TITLE
Error loading backend 'WxAgg' during import of deeplabcut

### ISSUE THREAD

**Issue by aaroncherian** [DeepLabCut/DeepLabCut#1149]
**Your Operating system and DeepLabCut version**

OS: Windows 10
DeepLabCut Version: 2.1.10.2
Anaconda env used: I loaded up the environment from the DLC-GPU.yaml

**Describe the problem**

I just installed deeplabcut, but whenever I try and import it, I get an issue that says 'ImportError: Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'qt5' is currently running', and I'm not sure how to get around that. The environment is just the DLC-GPU.yaml, running on Python 3.7.10. Thanks!

Please place code inside this:

<details><summary>Code output</summary><p>

Traceback (most recent call last):

  File "C:\Users\Rontc\untitled0.py", line 7, in <module>
    import deeplabcut

  File "C:\Users\Rontc\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\__init__.py", line 37, in <module>
    mpl.use("WxAgg")

  File "C:\Users\Rontc\anaconda3\envs\DLC-GPU\lib\site-packages\matplotlib\cbook\deprecation.py", line 307, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\Rontc\anaconda3\envs\DLC-GPU\lib\site-packages\matplotlib\__init__.py", line 1307, in use
    switch_backend(name)

  File "C:\Users\Rontc\anaconda3\envs\DLC-GPU\lib\site-packages\matplotlib\pyplot.py", line 236, in switch_backend
    newbackend, required_framework, current_framework))

ImportError: Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'qt5' is currently running

</p></details>

**Comment by KonradDanielewski** [comment]
Looks like wxpython issue? Can you try:

`pip install -U wxPython==4.0.7.post2` inside environment?

**Comment by jeylau** [comment]
Was your environment clean before the installation? I am surprised you'd have pyqt installed otherwise.

**Comment by aaroncherian** [comment]
> Looks like wxpython issue? Can you try:
> 
> `pip install -U wxPython==4.0.7.post2` inside environment?

No luck there, still got the same issue. Thanks for the suggestion though!



> Was your environment clean before the installation? I am surprised you'd have pyqt installed otherwise.

Good thought! The environments I tested were either brand new or installed from the DLC yaml, but this made me go hunting for why pyqt might be getting installed in these environments. Of note is that I use the Spyder IDE that comes with Anaconda - I noticed that all my environments had the Qt console program installed (a PyQt GUI), even though I had never installed that program. I did some tests and it seems like installing Spyder in an environment also automatically installs the Qt console. Uninstalling also seems like an all or nothing deal, where uninstalling one uninstalls both. 

Does it seem likely that's the source of the problem then?

**Comment by KonradDanielewski** [comment]
Can you try:

```
import matplotlib
matplotlib.use('WXAgg')

import deeplabcut
```

**Comment by jeylau** [comment]
@aaroncherian, could you share the script you're using to import deeplabcut? I see it's being imported on line 7; could there be an import to matplotlib made before?

**Comment by mrhe13** [comment]
> Can you try:
> 
> ```
> import matplotlib
> matplotlib.use('WXAgg')
> 
> import deeplabcut
> ```

This is really helpful for me,,,,Thanks so much!!

**Comment by RoniGerbi** [comment]
> > Can you try:
> > ```
> > import matplotlib
> > matplotlib.use('WXAgg')
> > 
> > import deeplabcut
> > ```
> 
> This is really helpful for me,,,,Thanks so much!!

Helped me too
I updated today my DLC to the latest release (April 22)
