### ISSUE TITLE
Can't create conda DLC-CPU env: tensorflow 1.15.5 not found 

### ISSUE THREAD

**Issue by kjohnsen** [DeepLabCut/DeepLabCut#1150]
**Describe the bug**

I try to install using conda and the provided DLC-CPU.yaml file. `conda env create -f DLC-CPU.yaml` and it looks like tensorflow 1.15.5 just isn't in Anaconda's package repository:
```
ResolvePackageNotFound:
  - tensorflow==1.15.5
```

I can't find it [on Anaconda's website](https://anaconda.org/search?q=tensorflow) either. I don't see anything about using non-standard channels in [the instructions](https://github.com/DeepLabCut/DeepLabCut/blob/master/conda-environments/README.md).

**System:**
 - OS: Windows 10
- conda version: 4.9.2
- conda-build version: 3.21.4

**Expected behavior**
Being able to create the `DLC-CPU` environment successfully using the provided `.yaml` file.

**Comment by backyardbiomech** [comment]
I just hit that problem, too. Open the yaml file with a text editor, **cut** the tensor flow line out of the conda section, paste it in the pip section. That worked for me.

**Comment by MMathisLab** [comment]
Hi @kjohnsen are you sure you are using python 3.7 actually?

**Comment by kjohnsen** [comment]
@MMathisLab, I was using conda to install, and the 3.7 was stipulated by the .yaml. Looks like the new commit fixes it though.
