### ISSUE TITLE
Backwards compatibility issue in v2.1.10.2 vs. beta release

### ISSUE THREAD

**Issue by CalvinLloyd117** [DeepLabCut/DeepLabCut#1151]
**Describe the bug**
Hello. I've been using DLC 2.2b8 for a while and I've encountered an issue with the file naming scheme since updating to v2.1.10.2.

I first noticed this issue when attempting to manually extract outlier frames from previously analyzed videos using 2.2b8. I would receive the following error in my terminal. 
`No unfiltered data file found in D:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\MVI_1917 for video MVI_1917 and scorer DLC_resnet50_VigilenceJul2shuffle1_100000 and box tracker.
It seems the video has not been analyzed yet, or the video is not found! You can only refine the labels after the a video is analyzed. Please run 'analyze_video' first. Or, please double check your video file path`

After some investigation as to why this might be the case I noticed that the video analysis (in v2.1.10.2) is generating tracker data in files with the following naming convention:
`MVI_1917DLC_resnet_50_VigilenceJul2shuffle1_100000_bx.pickle`

However, the program is looking for files that look like:
`MVI_1917DLC_resnet50_VigilenceJul2shuffle1_100000_bx.pickle`

i.e there is an extraneous _ placed between resnet and 50. This is preventing previously analyzed videos using 2.2b8 from being analyzed further in v2.1.10.2. After renaming the file and removing the underscore, manual extraction works as expected.

**Desktop (please complete the following information about your system):**
 - OS: Windows10
 - DeepLabCut Version: v2.1.10.2 (up from v2.2b8)
 - DeepLabCut mode: multi-animal tracking

**To Reproduce**
Steps to reproduce the behavior, i.e.:
1. Analyze videos using DLC v2.2b8
2. Update DLC to 2.1.10.2
3. Attempt to extract outlier frames (manually) from videos previously analyzed using DLC v2.2b8

<details><summary>TRACEBACK</summary><p>

```python

^do not delete the above "<details><summary>TRACEBACK</summary><p>" or the ```python part!
No unfiltered data file found in D:\Documents\Barret-HenziRA\Vigilence-Calvin-2020-07-02\videos\MVI_1917 for video MVI_1917 and scorer DLC_resnet50_VigilenceJul2shuffle1_100000 and box tracker.
It seems the video has not been analyzed yet, or the video is not found! You can only refine the labels after the a video is analyzed. Please run 'analyze_video' first. Or, please double check your video file path
do not delete below this line, leave the blank line and the ```

```
</p></details>

**Expected behavior**
Expected to be able to analyze videos in a backwards compatible manner.

**Comment by MMathisLab** [comment]
HI Calvin, yes, indeed beta releases are NOT stable and should not be considered production ready. i.e. b8 is a BETA release, and not going to be backwards compatible. We release non-stable beta releases for testing for the community to give us feedback. 

The convention in 2.10.2 will be continued into the new full 2.2, which will be released soon.

**Comment by CalvinLloyd117** [comment]
Oh, alright. I did know it was a beta release, but I wasn't aware it was designed NOT to work with future versions. This does clear up my confusion. Thanks for the reply!
