### ISSUE TITLE
Multiposition issue: correct tracklets, slow GUI - Good GPU but problem with CPU? 

### ISSUE THREAD

**Issue by Agulore** [DeepLabCut/DeepLabCut#1153]
Hi all,

I installed DLC on the computer which has the best GPU of the imaging platform of my institute. 
Here is the hardware:

Intel Xeon Bronze 3104
M.2 1TB SSD
128 GB DDR4 RAM
NVIDIA titan RTX

To start. Let say I am not familiar at all with Xeon and multicore stuff. I saw in (Mathis&Warren, 2018), the team is using this exact processor. I thought I am in the best condition to work, in term of hardware !

**My problem:** When I started to use DLC multi-position, The GUI starts to struggle with only 6 animals and 6 body parts each. Like  quite slow. Compare to regular One animal annotation. Learning step is GREAT! But... Then when it comes to correct and refine Tracklets, the GUI is struggling a lot to refresh and so slow to process it is impossible de do anything at this step.

Besides this, I tried to run some Matlab codes which runs perfectly on other kind of CPU (not multicores), even on laptop and here it is **so slow**.

Altogether seems to point this specific CPU: Intel Xeon Bronze 3104

Do you know if there is something specific I have to do to use properly this kind of CPU?

Thank a lot for your help.

Raphael

**Comment by KonradDanielewski** [comment]
That's a really slow cpu (I mean, if you have a datacenter that let's you use a 1000 of them at once they might be fine, but on a workstation - really bad idea when you have different types of workflow). I'm pretty sure it doesn't even boost and just works at 1.7GHz. Maybe use a different computer to do the GUI steps and just train on this one.
