### ISSUE TITLE
labeling gui : when zoomed, delete option is targeting the wrong point

### ISSUE THREAD

**Issue by MaloM-CVision** [DeepLabCut/DeepLabCut#1154]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). 
Please fill out the template completely, including the full "TRACEBACK" and input code that you ran to hit this error.

**Describe the bug**

when zoomed, delete option is targeting the wrong point.

**To Reproduce**
Steps to reproduce the behavior, i.e.:
1. deeplabcut.label_frames(config_path)
2. label one point.
3. zoom on a part of the image
4. place a 2nd point
5. try to delete the 2nd point
6. BUG : the warning message is : Do you want to remove the label [1st point] ?

**Comment by jeylau** [comment]
Thanks for reporting the issue! This will be fixed with eaf1ca04df3ae7c864e5b772b0cca2e583eb61b3 :)
