### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_send_event' - Google Colab

### ISSUE THREAD

**Issue by Mahathy95** [DeepLabCut/DeepLabCut#1156]
Implemented DLC on Google Colab with Deeplabcut version : 2.1.10.2
I implemented upto labelling of frames on my laptop which I recently changed to SSD. 
The laptop uses , and
OS: Windows 10
DeepLabCut Version:  '2.2b8'
Anaconda env used: conda 4.8.5 
I am able to label frames, upload the data and create the training dataset. While evaluating the dataset I have specified:
displayiters=1000,saveiters=1000,maxiters=200000
The network runs upto 100,000 without any issue but after that stops without any error at random iterations like 125000 or 175000 or 150000. Initially thought this might be due to the space on the RAM/disk. So I bought additonal space on my google drive. That didn't fix the issue. I also monitored the iterations to see if the GPU was timing out but found no error. Today when I ran the network and monitored it, it ran till about 8.50 pm without any issue then saw a message saying Completed at 7.45 pm at the bottom of the page. At this point, it was on 122000 iteration and loss was 0.0005
Went ahead and evaluated the network anyway but I am getting this error: 

```python
/content/drive/My Drive/ComSG-Mahathy-2021-03-20/evaluation-results/  already exists!
/content/drive/My Drive/ComSG-Mahathy-2021-03-20/evaluation-results/iteration-0/ComSGMar20-trainset95shuffle1  already exists!
Running  DLC_resnet_50_ComSGMar20shuffle1_139000  with # of trainingiterations: 139000
/content/drive/My Drive/ComSG-Mahathy-2021-03-20/evaluation-results/iteration-0/ComSGMar20-trainset95shuffle1/LabeledImages_DLC_resnet_50_ComSGMar20shuffle1_139000_snapshot-139000  already exists!
Initializing ResNet
Activating extracting of PAFs
0it [00:00, ?it/s]Analyzing data...
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/matplotlib/backend_bases.py in _wait_cursor_for_draw_cm(self)
   2805 
-> 2806         self.press(event)
   2807 

13 frames
AttributeError: 'NoneType' object has no attribute '_send_event'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/matplotlib/backends/backend_webagg_core.py in send_event(self, event_type, **kwargs)
    344 
    345     def send_event(self, event_type, **kwargs):
--> 346         self.manager._send_event(event_type, **kwargs)
    347 
    348 

AttributeError: 'NoneType' object has no attribute '_send_event'

```

**How to Reproduce the problem**
1. Go to Evaluate Network 
2. Click on Run
3. See error :   AttributeError: 'NoneType' object has no attribute '_send_event'

Any help will be great! Thank you!

**Comment by MMathisLab** [comment]
HI, firstly, beta 8 is depreciated. Please use 2.1.10.2. 

secondly, when you install at the top of the colab notebook, you need to wait then click the large "RESART RUNTIME" so the correct version of matplotlib is used, then this shouldn't happen. 

You can also pass plotting = False to bypass this matplotlib step.

**Comment by Mahathy95** [comment]
Thank you @MMathisLab ! Its evaluating now. But how do I choose the most recent snapshot for evaluation and analysis? Since I ran it in two slots - first upto 122000 and then for 80000 iterations more, its taking 122000 and not the most recent one for evaluation(I want it to use the 200000 iteration results for analysis).
If I say plotting= False, wont it affect the plotting of poses? 
Thank you so much for your help!

**Comment by jeylau** [comment]
Hey @Mahathy95, you could set `snapshotindex` to 0 in the config.yaml, to indicate that you want the "first" snapshot (the lowest numerically). `plotting=False` prevents DLC from saving all train & test images during evaluation, but does not affect anything else :)
