### ISSUE TITLE
"No suitable videos found" attempting to "Extract Outlier Frames"

### ISSUE THREAD

**Issue by SIM0N-W** [DeepLabCut/DeepLabCut#1161]
**Your Operating system and DeepLabCut version**
OS: Windows 10
DLC: 2.2b8
anaconda-env: tensorflow:1.15.5, wxpython:4.0.2

**Describe the problem**

I can't find the "Tracking Method" GUI button, in my "Analyze Video" tab.

This is what the tabs look like for me, which differ from the GUI in the YouTube videos (which have "convert to tracklets" button).

![image](https://user-images.githubusercontent.com/76114144/112392740-88ff3180-8cbf-11eb-933c-808dd8a133ed.png)
vs.
![image](https://user-images.githubusercontent.com/76114144/112391522-a92df100-8cbd-11eb-9764-1bcfba54cd50.png)

I am also missing tabs in the GUI like "refine tracklets"

________________________________________________________________________________________________________________________________________

I have trained a the network using 80 labelled frames, with 1,030,000 iterations.

Analyzing a new video "C2773.mp4", produced these 3 files:
![image](https://user-images.githubusercontent.com/76114144/112391791-0b86f180-8cbe-11eb-8870-94aa0628f777.png)
1. .h file
2. resnet.mp4
3. pickle file

![image](https://user-images.githubusercontent.com/76114144/112391936-48eb7f00-8cbe-11eb-92fa-6556a12e4dce.png)
When I select the resnet.mp4 in "Extract Outlier Frames", (using the "jump" algorithm) I get this error:

`(DLC) C:\Windows\system32>python -m deeplabcut
2021-03-24 16:25:43.957770: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Starting GUI...
No suitable videos found in ['E:\\ShArEd\\Karyne Rats 2021\\Videos\\Winter 2021 (cut)\\Baseline v2\\C2773DLC_resnet_50_Baseline RatsMar18shuffle1_1030000_labeled.mp4']`

**How to Reproduce the problem**
1. Enter DLC env: activate DLC (I named the env "DLC", but it uses tensorflow-gpu)
1. Open DLC GUI: python -m deeplabcut
3. Import config file.
4. Extract outlier frames: select Resnet.mp4 (C2773DLC_resnet_50_Baseline RatsMar18shuffle1_1030000_labeled.mp4)
5. Specify the algorithm: 'jump' (this was default)
6. See error:
`(DLC) C:\Windows\system32>python -m deeplabcut
2021-03-24 16:25:43.957770: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Starting GUI...
No suitable videos found in ['E:\\ShArEd\\Karyne Rats 2021\\Videos\\Winter 2021 (cut)\\Baseline v2\\C2773DLC_resnet_50_Baseline RatsMar18shuffle1_1030000_labeled.mp4']`

Thanks for your help in advance, this has been a great learning experience!
~ Simon

**Comment by jeylau** [comment]
Hey @sizhesim, the tabs relevant to multi-animal tracking are missing because your project is for single animals.
As for the error, select the original video rather than the labeled one (and make sure videotype is 'mp4') 😊

**Comment by MMathisLab** [comment]
^^ also, don't pass the LABELED video, only pass the ORIGINAL video: `... atsMar18shuffle1_1030000_labeled.mp4']`

**Comment by SIM0N-W** [comment]
Thank you very much you guys, I really appreciate it!

Silly me...

Here is the cmd code that comes out sucessfully.

`(base) C:\WINDOWS\system32>activate DLC`

`(DLC) C:\WINDOWS\system32>python -m DLC`
`C:\Build\envs\DLC\python.exe: No module named DLC`

`(DLC) C:\WINDOWS\system32>python -m deeplabcut`
`Starting GUI...`
`Method  jump  found  329  putative outlier frames.`
`Do you want to proceed with extracting  20  of those?`
`If this list is very large, perhaps consider changing the parameters (start, stop, p_bound, comparisonbodyparts) `or `use a different method.`
`yes/no yes`
`Frames from video C2773  already extracted (more will be added)!`
`Loading video...`
`Duration of video [s]:  7.540874207540875 , recorded @  59.94 fps!`
`Overall # of frames:  452 with (cropped) frame dimensions:`
`Kmeans-quantization based extracting of frames from 0.0  seconds to 7.54  seconds.`
`Extracting and downsampling... 329  frames from the video.`
`329it [00:19, 17.31it/s]`
`Kmeans clustering ... (this might take a while)`
`Let's select frames indices: [205, 435, 106, 57, 282, 193, 32, 295, 19, 135, 176, 347, 43, 242, 306, 73, 189, 154, 164,` `149]`
`Creating the symbolic link of the video`
`New video was added to the project! Use the function 'extract_frames' to select frames for labeling.`
`The outlier frames are extracted. They are stored in the subdirectory labeled-data\C2773.`
`Once you extracted frames for all videos, use 'refine_labels' to manually correct the labels.`

Best regards,
Simon
