### ISSUE TITLE
Issue with re-training

### ISSUE THREAD

**Issue by deepbraincut** [DeepLabCut/DeepLabCut#1162]
Hi,

First of all, thank you so much for the wonderful program, I am working on multi-mouse behavior tracking during their social interactions. I have a trouble when I try to expend training set, could help me to understand the error?

OS: Windows 10 with an Anaconda Env
DeepLabCut Version: maDLC-GPU 2.2b8 

**Describe the problem**

I got an error message when I tried to train network with expended training set. After the initial training, I refined the tracklets using refine tracklet GUI, and merge refine data. After done this, I also refined label using refine label GUI, merge the dataset afterwards, which successfully created a new 'iteration-1' folder in trainingset folder. I created training set using Create training set, (I set the "specify the training dataset index" as 1), which works well. After creating the new training set, I tried to train network, and when I set  "specify the training dataset index" as 1, DLC gives me an error IndexError: list index out of range

Which part I was missing here? Could you help me to understand the error? Many thanks!

<details><summary>Code output</summary><p>
(DLC-GPu) C:\Users\sahay>python -m deeplabcut
Starting GUI...
note to user: currently only ResNet50-v1 is available for maDLC
note to user: currently model comparison is not available in maDLC
D:\DLC\invivoMashBax_social-ac-2021-03-12\training-datasets\iteration-1\UnaugmentedDataSet_invivoMashBax_socialMar12  already exists!
Utilizing the following graph: [[1, 3], [5, 6], [0, 2], [1, 6], [2, 5], [0, 3], [1, 2], [1, 5], [3, 6], [0, 4], [2, 6], [4, 5], [1, 4], [2, 3], [3, 5], [0, 1], [4, 6], [3, 4], [2, 4]]
Creating training data for  1 0.95
This can take some time...
100%|██████████████████████████████████████████████████████████████████████████████| 3450/3450 [01:07<00:00, 50.83it/s]
D:\DLC\invivoMashBax_social-ac-2021-03-12\dlc-models\iteration-1\invivoMashBax_socialMar12-trainset95shuffle1  already exists!
D:\DLC\invivoMashBax_social-ac-2021-03-12\dlc-models\iteration-1\invivoMashBax_socialMar12-trainset95shuffle1\train  already exists!
D:\DLC\invivoMashBax_social-ac-2021-03-12\dlc-models\iteration-1\invivoMashBax_socialMar12-trainset95shuffle1\test  already exists!
The training dataset is successfully created. Use the function 'train_network' to start training. Happy training!
Traceback (most recent call last):
  File "C:\Users\sahay\Anaconda3\envs\DLC-GPu\lib\site-packages\deeplabcut\gui\train_network.py", line 329, in train_network
    maxiters=maxiters,
  File "C:\Users\sahay\Anaconda3\envs\DLC-GPu\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 140, in train_network
    cfg["TrainingFraction"][trainingsetindex], shuffle, cfg, modelprefix=modelprefix
  File "C:\Users\sahay\Anaconda3\envs\DLC-GPu\lib\site-packages\ruamel\yaml\compat.py", line 273, in __getitem__
    return self.__getsingleitem__(index)
  File "C:\Users\sahay\Anaconda3\envs\DLC-GPu\lib\site-packages\ruamel\yaml\comments.py", line 388, in __getsingleitem__
    return list.__getitem__(self, idx)
IndexError: list index out of range

</p></details>

**How to Reproduce the problem**
1. Go to 'train network'
2. Click on 'specify training set index -> 1'
list index out of range

![error for retraining](https://user-images.githubusercontent.com/75436015/112492802-f5c60a80-8d57-11eb-9164-eae2870f4e00.PNG)
![Capture](https://user-images.githubusercontent.com/75436015/112492938-168e6000-8d58-11eb-807b-22106f1e7f7a.PNG)

**Comment by MMathisLab** [comment]
> I created training set using Create training set, (I set the "specify the training dataset index" as 1), which works well

After merging, it auto-updates the config.yaml to be iteration-1. You should not re-set the training index when you create a new set, just simply leave `interation: 1` in the project `config.yaml` and run create_training_multi_animal ... just with the conf path passed.  :)

**Comment by deepbraincut** [comment]
thank you!, 
So what I need to do is, set training index as 0, and run create trainingset again and training as setting of training index as 0.
Since the config file is already updated.
Is it right? 


then in which case I need to specify the training index in both taps of "create trainingset" and "Train network"?

![Capture1](https://user-images.githubusercontent.com/75436015/112503937-b6042080-8d61-11eb-9a2d-fd9258a54abf.PNG)
![Capture2](https://user-images.githubusercontent.com/75436015/112503938-b69cb700-8d61-11eb-8417-9b84084c867f.PNG)

?

**Comment by DuanWei-fudan** [comment]
well,so how many factors will influence the train of network? Is it  just the times of training? Are there more details?

**Comment by MMathisLab** [comment]
@DuanWei-fudan I would suggest reading the papers; there are a large number of parameters one can change. See here for a list of key papers, especially the primer on deep learning for pose estimation. www.deeplabcut.org :) 

the nature protocol paper has a whole box (box 2) dedicated to parameters for training
