### ISSUE TITLE
DeepLabCut using CPU instead of GPU

### ISSUE THREAD

**Issue by msgch** [DeepLabCut/DeepLabCut#1163]
**Your Operating system and DeepLabCut version**

OS: Windows 10
DeepLabCut Version: 2.1.10.2
Anaconda env used: base
Python: 3.7
Tensorflow: 1.13.1
CUDA: 10.0 
cuDNN: 7.4.2

**Describe the problem**

After desintalling, I managed to install everything in the right versions (I believe since I followed your explanations).
As a result, DLC seems to work since I managed to go until training, but it was so long that I checked (and stopped before it finished) and my CPU was at 100% whereas my GPU almost at 0%... 
So when I run nvidia-smi, first I don't see CUDA listed whereas it is installed (version 10.0). Second, it tells "Internal Error" after GPU... (see 1st picture). However, the tests done in the second picture look fine for the GPU...
Do you have any idea on what problem this is referring to ? I saw that a lot of people had this problem, but never found the solution for my case...
Thanks a lot in advance

Please place code inside this:

<details><summary>Code output</summary><p>

nvidia-smi

</p></details>

**Screenshots**
![image](https://user-images.githubusercontent.com/81379843/112515353-7d326e80-8d96-11eb-9520-496df296544b.png)
![image](https://user-images.githubusercontent.com/81379843/112519022-3fcfe000-8d9a-11eb-8c64-d37b32bfd59f.png)

**Comment by MMathisLab** [comment]
hi @msgch firstly, that GPU won't work, it must be a GPU with at least 8 GB of memory, like the 2080 from NVIDIA. Also, if CUDA is not showing up, it's likely not installed properly. I would suggest checking out the resources we put in out Troubleshooting guide (click on wiki, also on installation.md doc!). Lastly, we ask that questions go to the User forum, thank you! https://forum.image.sc/tag/deeplabcut
