### ISSUE TITLE
How to change p-value during refine labels step?

### ISSUE THREAD

**Issue by SIM0N-W** [DeepLabCut/DeepLabCut#1164]
**Your Operating system and DeepLabCut version**

OS: Windows 10
DLC: 2.2b8
anaconda-env: tensorflow:1.15.5, wxpython:4.0.2

**Describe the problem**

While going through the extracted frames in the "Refine Labels" tab, a step prior to re-training the network, I was wondering, how I could change the p-values for the labels?

![image](https://user-images.githubusercontent.com/76114144/112576590-2dfd3580-8db8-11eb-96b4-31b332cbe81d.png)

Here we see that the network has decided for this particular extracted frame, the snout is not the snout. In this case, should I remove the label or just keep it there?

**How to Reproduce the problem**
1. Enter DLC env: activate DLC (I named the env "DLC", but it uses tensorflow-gpu)
2. Open DLC GUI: python -m deeplabcut
3. Import config file.
5. Extract frames from raw mp4 file (after analyzing a video)
6. Refine Labels (Launch).

Thank you very much for your detailed help so far!

Best,
Simon

**Comment by jeylau** [comment]
Hey @sizhesim! the snout is indeed a snout, as it was correctly detected by the network; its confidence in the prediction just isn't as high as for the other body parts.
When you launch the refinement GUI, you're asked what threshold you want to use. You apparently left it at its default of 0.4, but if you set it to 0.01 for example, all points with greater probability will be filled. That's merely to draw your attention to potential outliers though, so I wouldn't set it too low.
