### ISSUE TITLE
It is possible analyze videos using multiple evaluated snapshots?

### ISSUE THREAD

**Issue by viniciustenorio** [DeepLabCut/DeepLabCut#1165]
I'm applying DLC with DLC_Analyzer by using Google Colab. I'm trying to train snapshots with 1.03M iterations, but Colab always disconnects near 300,000 iterations. I already trained 5 different snapshots with 250,000 iterations and evaluated them in a same model by setting snapshotindex: "all" in the config.YAML file.

But when trying to analyze videos with then, it is warned "Snapshotindex is set to 'all' in the config.yaml file. Running video analysis with all snapshots is very costly! Use the function 'evaluate_network' to choose the best the snapshot. For now, changing snapshot index to -1!" and the code uses the most recent snapshot.

Is there a way to analyze_videos using multiple snapshots?

**Comment by MMathisLab** [comment]
You can write a script to loop over and edit the config.yaml to be -1 (last), to x y z; typically this is not done, so we leave that up to you. Check out DLC Utils for example scripts for looping over videos. 

Also of course thanks also for using DLC, but we please ask you ask user questions on the forum, vs. openning github issues (please see here: https://github.com/DeepLabCut/DeepLabCut#community-support-developers--help) and see you on the forum! https://forum.image.sc/tag/deeplabcut
