### ISSUE TITLE
GPU out of memory when using create_labeled_video

### ISSUE THREAD

**Issue by AmeetR** [DeepLabCut/DeepLabCut#1167]
OS: Windows - Deeplabcut 2.2 with anaconda

When I try to run create_labeled_video() on a dataset, it gives me a cuda out of memory error. I was able to train and analyze videos using this GPU. For reference, I have two Quadro RTX 5000s (only using one) with 16 gb vram each and I trained a ResNet 101. I'm able to train with this environment without many issues as well. As far as I know, create_labeled_video isn't even supposed to use the GPU - just the already analyzed video data.

**Comment by MMathisLab** [comment]
Hi @AmeetR please fill out the template, then we can assist you (and indeed, it does not use the GPU).
