### ISSUE TITLE
Issue to skip frames during labeling. 

### ISSUE THREAD

**Issue by DorianBattivelli** [DeepLabCut/DeepLabCut#1170]
Hello, 

I am using DLC 2.2b8, multi animal project, on Windows 10.
I cannot skip from one frame to the other when I label the frames and here the message the prompt returns:

![Untitled](https://user-images.githubusercontent.com/66886884/112995541-9eff6d00-916b-11eb-84a6-6138a326dc0f.png)

Would you have a suggestion to solve this issue?

Thank you very much, 
Best,

**Comment by MMathisLab** [comment]
beta8 is outdated; please install 2.1.10.2

**Comment by DorianBattivelli** [comment]
Thanks a lot, it solved the issue,

Best, 
Dorian
