### ISSUE TITLE
"ResourceExhaustedError" training 

### ISSUE THREAD

**Issue by DorianBattivelli** [DeepLabCut/DeepLabCut#1173]
Hello, 

I created a ma-project on Windows 10, using the 2.1.10.2 dlc version. 
All went well, until the training crashed on Colab. Here what it returns: 

![Schermata 2021-03-31 alle 15 26 20](https://user-images.githubusercontent.com/66886884/113151779-b9058200-9235-11eb-9815-9fdc8daf7ad9.png)

2 videos are used for the training, each being 297 mo, 8486kbps, mp4, 20fps, WxH=2040.4140, almost 5 min length. 
Would you have any suggestion to solve this issue? 

Thank you, 
Best,

**Comment by backyardbiomech** [comment]
"Resource exhausted" means that you have run out of GPU memory because your images are too large and/or batch size is too large. I think the free version Colab limits you to 12 GB GPUs. You can crop or downsample your training images, or decrease batch size.

**Comment by DorianBattivelli** [comment]
Thank you, so solutions are either: 

- reduce duration
- reduce fps
- cropping

?

**Comment by DorianBattivelli** [comment]
Thank you very much for this exhaustive and clear answer. 
One doubt: with the croptrainingimagesandlabels command, cropping means reducing the field of the frame right? If it is the case, it not suits for me, cause I need all the frame, otherwise I'll loose animal's trace regularly. 
Instead, if it's only about reducing the resolution, without changing the portion of picture that is analyzed, ok I can give a go.

**Comment by MMathisLab** [comment]
@DorianBattivelli it will not limit your tracking performance later. training is only about good pose estimation. In fact, the default data augmentation includes cropping as well. If you are interested more in this, check out our recent paper on the science behind how this works: https://www.sciencedirect.com/science/article/pii/S0896627320307170
