### ISSUE TITLE
ResourceExhaustedError

### ISSUE THREAD

**Issue by sinal23** [DeepLabCut/DeepLabCut#1176]
Hello, I recently installed DLC on a windows 10, GPU of GeForce GTX 750 Ti, using anaconda.
![thumbnail_image](https://user-images.githubusercontent.com/79872083/113331511-70fa6400-92f6-11eb-8502-e7c7d37d4ff9.png)

I had taken the following steps during installation and usage: 
- installed anaconda
- downloaded visual studios 2015 community 
- installed cuda 10 
-  installed the files from website
- activated and ran pip install -U 
wxPython==4.0.7
-used GUI and created a multianimal projects using the instructions in your video.

everything worked fine until I reached to training network, in which I got the following errors:
![image](https://user-images.githubusercontent.com/79872083/113331643-95564080-92f6-11eb-9629-a00fe73475ed.png)
![image (1)](https://user-images.githubusercontent.com/79872083/113331689-a010d580-92f6-11eb-87a8-5c78f544c16c.png)

I think it may be a memory issue, so I tried minimizing all the inputs of training network (set them all to one) and used only a 20 second video, but it still did not work. 
Do you have any possible solutions?
Thank you!

**Comment by MMathisLab** [comment]
HI, I cannot see the code in the screen shots; please follow the template, which has an area for you to copy / paste the code so it's formatted correctly. 

Secondly, a 750 will not be large enough. The minimum GB required is 8GB; this is a 2GB card. I would recommend uploading your project to google drive, and using COLAB GPUs for free, just use this: https://github.com/DeepLabCut/DeepLabCut/blob/master/examples/COLAB_maDLC_TrainNetwork_VideoAnalysis.ipynb
