### ISSUE TITLE
Using the GUI, I am having trouble exporting the model to a PB file for use in Bonsai

### ISSUE THREAD

**Issue by GabrielBonassi77** [DeepLabCut/DeepLabCut#1177]
I am currently running windows with Anoconda 3, running the GPU_DLC environment where I import deeplabcut and launch the GUI. 

The main issue that I am facing is that there is no clear option to export my model to the .pb format that I need to use my model in Bonsai. 

What I have tried is to do to solve this is:

I set the config-path = to the location of the file

 deeplabcut.export_model(cfg_path,  iteration=None, shuffle=1, trainingsetindex=0, snapshotindex=None, TFGPUinference=True, overwrite=False, make_tar=True)

which did not work, so I tried running:

 deeplabcut.export_model(r'C:\Users\gabri\Downloads\Tail\Tail-FirstModel-2021-02-26\config',  iteration=None, shuffle=1, trainingsetindex=0, snapshotindex=None, TFGPUinference=True, overwrite=False, make_tar=True)

to which the terminal responded:

  313         FileNotFoundError("The config.yaml file at %s does not exist." % cfg_path)
    314
--> 315     cfg["project_path"] = os.path.dirname(os.path.realpath(cfg_path))
    316     cfg["iteration"] = iteration if iteration is not None else cfg["iteration"]
    317     cfg["batch_size"] = cfg["batch_size"] if cfg["batch_size"] > 1 else 2

UnboundLocalError: local variable 'cfg' referenced before assignment

I am not sure if this is an error setting the config_path, or if I am missing something. Any help would be greatly appreciated!

**Comment by tokioshima** [comment]
Hey GabrielBonassi77!

I have the same error message as you ("UnboundLocalError: local variable 'cfg' referenced before assignment") when I use your way : 

- deeplabcut.export_model(r'C:\Users\jersa\Desktop\meilleure test avec gpu-jessy-2024-02-14\config', iteration=None, shuffle=1, trainingsetindex=0, snapshotindex=None, TFGPUinference=True, overwrite=False, make_tar=True)

or when I use the method explain in Kane et al. eLife 2020 (https://elifesciences.org/articles/61909) wich say to enter this 

"import deeplabcut as dlc
dlc .export_model(”/path/to/config.yaml”)"

and the result are the following : 

- In [2]: dlc.export_model("C:\\Users\\jersa\\Desktop\\meilleure test avec gpu-jessy-2024-02-14")
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Cell In[2], line 1
----> 1 dlc.export_model("C:\\Users\\jersa\\Desktop\\meilleure test avec gpu-jessy-2024-02-14")

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\export.py:299, in export_model(cfg_path, shuffle, trainingsetindex, snapshotindex, iteration, TFGPUinference, overwrite, make_tar, wipepaths, modelprefix)
    296 ### read config file
    298 try:
--> 299     cfg = auxiliaryfunctions.read_config(cfg_path)
    300 except FileNotFoundError:
    301     FileNotFoundError("The config.yaml file at %s does not exist." % cfg_path)

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py:210, in read_config(configname)
    206 else:
    207     raise FileNotFoundError(
    208         "Config file is not found. Please make sure that the file exists and/or that you passed the path of the config file correctly!"
    209     )
--> 210 return cfg

UnboundLocalError: local variable 'cfg' referenced before assignment

So can you explain me how you have result this problem or maybe someone else can help me?
Thanks in advance!
