### ISSUE TITLE
FileNotFoundError("The config.yaml file at %s does not exist." % cfg_path)

### ISSUE THREAD

**Issue by GabrielBonassi77** [DeepLabCut/DeepLabCut#1178]
OS: Windows 10
DeepLabCut Version: 2.2
Anaconda env used: 3

I am currently running windows with Anoconda 3, running the GPU_DLC environment where I import deeplabcut and launch the GUI. 

The main issue that I am facing is that there is no clear option to export my model to the .pb format that I need to use my model in Bonsai. 

What I have tried is to do to solve this is:

I set the config-path = to the location of the file

 deeplabcut.export_model(cfg_path,  iteration=None, shuffle=1, trainingsetindex=0, snapshotindex=None, TFGPUinference=True, overwrite=False, make_tar=True)

which did not work, so I tried running:

 deeplabcut.export_model(r'C:\Users\gabri\Downloads\Tail\Tail-FirstModel-2021-02-26\config',  iteration=None, shuffle=1, trainingsetindex=0, snapshotindex=None, TFGPUinference=True, overwrite=False, make_tar=True)

to which the terminal responded:

  313         FileNotFoundError("The config.yaml file at %s does not exist." % cfg_path)
    314
--> 315     cfg["project_path"] = os.path.dirname(os.path.realpath(cfg_path))
    316     cfg["iteration"] = iteration if iteration is not None else cfg["iteration"]
    317     cfg["batch_size"] = cfg["batch_size"] if cfg["batch_size"] > 1 else 2

UnboundLocalError: local variable 'cfg' referenced before assignment

I am not sure if this is an error setting the config_path, or if I am missing something. Any help would be greatly appreciated!

**How to Reproduce the problem**

Make a project in the GUI and try to export the model to PB format

**Comment by MMathisLab** [comment]
HI @Man677 indeed there is no "export model" button in the GUI. 

Here is the docs to do this in the terminal:
https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/HelperFunctions.md#new-model-export-function
```python
deeplabcut.export_model(cfg_path, iteration=None, shuffle=1, trainingsetindex=0, snapshotindex=None, TFGPUinference=True, overwrite=False, make_tar=True)
```
note, the error message (`FileNotFoundError("The config.yaml file at %s does not exist." % cfg_path)`) above is correct, you did not put the path to your config.yaml file correctly:

```python
r'C:\Users\gabri\Downloads\Tail\Tail-FirstModel-2021-02-26\config'
```

SHOULD BE:
```python
r'C:\Users\gabri\Downloads\Tail\Tail-FirstModel-2021-02-26\config.yaml'
```

Also, please note, 2.2 as a version does not exist yet , ;), so please put the exact version you are using for future issues, and multi-animal projects are not supported for export.
