### ISSUE TITLE
request a scroll bar or "fast forward" for the label refinement toolbox

### ISSUE THREAD

**Issue by deepbraincut** [DeepLabCut/DeepLabCut#1180]
**Is your feature request related to a problem? Please describe.**
1) for refinement of tracklet, the screenshot is too small, I know there is zoom in, but still is there any option I can make the editing screen bigger? 

2) During refinement of the labeling, if I stopped in the middle of labeling refinement before, I have to click Next button to reach to the frame I worked on, which was sometimes up to hundreds of frames. 

**Describe the solution you'd like**
It would be great if there is scroll bar or fast forward option in the label refinement GUI. 

**Describe alternatives you've considered**
I really appreciate the play-stop function in refinement of tracklet GUI. it would be great to have the similar function in labeling refinement GUI too.

**Comment by MMathisLab** [comment]
Hello @deepbraincut - as we mentioned, maDLC is out of beta, and will change dramatically next week, and is not backwards compatible. I would would. Also, you can easily change the size of the window in the tracklet GUI if you modify this code: https://github.com/DeepLabCut/DeepLabCut/blob/master/deeplabcut/gui/tracklet_toolbox.py

also, again, please fill out the template as we ask! :)

**Comment by deepbraincut** [comment]
Look forward to using the new version, And I will make sure to fill out the template next time. Thank you so much!
