### ISSUE TITLE
Issue when adding new videos

### ISSUE THREAD

**Issue by DorianBattivelli** [DeepLabCut/DeepLabCut#1181]
Hello, 

I am using the last version of DLC for a ma-project on Windows 10.
I would like to label frames from a new video in an existing project. But I fail to use the "add new videos" function.
When I click it after having loaded the video, here what my cmd returns:

![Untitled](https://user-images.githubusercontent.com/66886884/113781013-52e69680-9730-11eb-9fa7-1d6e4326166d.png)
Would you have a suggestion to fix this issue?

Thank you, 
Best,
Dorian

**Comment by DorianBattivelli** [comment]
I managed to add the video manually in the video folder, modifying also the config file, but the add function still returns error...

**Comment by backyardbiomech** [comment]
That’s a permissions issue. You can run the anaconda command window as an admin, or permanently change symlink permissions following [this](https://stackoverflow.com/a/65504258).
