### ISSUE TITLE
stuck here(Starting training....)  for hours

### ISSUE THREAD

**Issue by FengZhiheng** [DeepLabCut/DeepLabCut#1183]
It's been stuck here(Starting training....) for hours.

**Your Operating system**:  Windows10
**DeepLabCut version** : 2.1.10.3
**env** as flow:
absl-py                0.12.0
astor                  0.8.1
backcall               0.2.0
bayesian-optimization  1.2.0
cached-property        1.5.2
certifi                2020.12.5
chardet                4.0.0
click                  7.1.2
colorama               0.4.4
cycler                 0.10.0
Cython                 0.29.22
decorator              4.4.2
deeplabcut             2.1.10.3
filterpy               1.4.5
gast                   0.4.0
grpcio                 1.36.1
h5py                   3.2.1
idna                   2.10
imageio                2.9.0
imageio-ffmpeg         0.4.3
imgaug                 0.4.0
importlib-metadata     3.10.0
intel-openmp           2021.2.0
ipython                7.22.0
ipython-genutils       0.2.0
jedi                   0.18.0
joblib                 1.0.1
Keras-Applications     1.0.8
Keras-Preprocessing    1.1.2
kiwisolver             1.3.1
llvmlite               0.34.0
Markdown               3.3.4
matplotlib             3.1.3
mock                   4.0.3
moviepy                1.0.1
msgpack                1.0.2
msgpack-numpy          0.4.7.1
networkx               2.5.1
numba                  0.51.1
numexpr                2.7.3
numpy                  1.17.5
opencv-python          4.5.1.48
opencv-python-headless 3.4.9.33
pandas                 1.2.3
parso                  0.8.2
patsy                  0.5.1
pickleshare            0.7.5
Pillow                 8.2.0
pip                    21.0.1
proglog                0.1.9
prompt-toolkit         3.0.18
protobuf               3.15.7
psutil                 5.8.0
Pygments               2.8.1
pyparsing              2.4.7
python-dateutil        2.8.1
pytz                   2021.1
PyWavelets             1.1.1
PyYAML                 5.4.1
pyzmq                  22.0.3
requests               2.25.1
ruamel.yaml            0.17.2
ruamel.yaml.clib       0.2.2
scikit-image           0.18.1
scikit-learn           0.24.1
scipy                  1.6.2
setuptools             52.0.0.post20210125
Shapely                1.7.1
six                    1.15.0
statsmodels            0.12.2
tables                 3.6.1
tabulate               0.8.9
tensorboard            1.13.1
tensorflow-estimator   1.13.0
tensorflow-gpu         1.13.1
tensorpack             0.9.8
termcolor              1.1.0
threadpoolctl          2.1.0
tifffile               2021.3.31
tqdm                   4.60.0
traitlets              5.0.5
typing-extensions      3.7.4.3
urllib3                1.26.4
wcwidth                0.2.5
Werkzeug               1.0.1
wheel                  0.36.2
wincertstore           0.2
wxPython               4.0.7
zipp                   3.4.1

----------
**GPU**:1080 Ti
**cudnn**:cudnn-10.0-windows10-x64-v7.6.2.24
**tensorflow**:tensorflow-gpu==1.13.1

When I use DeepLabCut GUI, and click on the button("OK" in Train network tab )
![image](https://user-images.githubusercontent.com/27288257/114014976-c8bb4100-989b-11eb-8f2e-09b7c47f62fd.png)

It's been stuck here, for hours. 
![image](https://user-images.githubusercontent.com/27288257/114015028-d83a8a00-989b-11eb-9385-3de001a6fd88.png)

I really need your help. Thank you very much.

And my GPU has not been used. Very Wired!
![image](https://user-images.githubusercontent.com/27288257/114015314-2485ca00-989c-11eb-9314-8528731077fc.png)

**Comment by MMathisLab** [comment]
sounds like your display iterations is likely set to the default 1000, and you are using the CPU; using the CPU would take several hours to hit 1000 iterations. In the GUI you can change display iters, set this to 1, and at least you will see it's training. But, I would recommend using a GPU!

**Comment by elolearnsDLC** [comment]
Hello!
I am working on a macbookpro, going through anaconda navigator and initiating the deeplabcut GUI through the terminal there (>pythonw -m deeplabcut) and am having the same issue with the amount of time it takes to train a network. My videos are of my cat with my iphone so I don't know if that plays a role in the time it's been taking. Do you have any suggestions? 
Thank you!

**Comment by perveratilla** [comment]
> 

Hello, is there a button or short script to force app to work on GPU? Or just downloading CUDA, Tensorflow etc. is enough to make it work on GPU?

**Comment by MMathisLab** [comment]
@perveratilla please see here: https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html#how-to-confirm-that-your-gpu-is-being-used-by-deeplabcut
