### ISSUE TITLE
Coordinate missmatch in CSV and labeled video during multianimal tracking

### ISSUE THREAD

**Issue by pavolbauer** [DeepLabCut/DeepLabCut#1184]
Dear DLC Team,

I encountered the following problem using the current master version of DLC. We labeled several keypoints for two individual animals in a video and trained a multianimal detection model. When visualizing the tracking results using the labeled video, everything seems fine. However, when visualizing the keypoint coordinates obtained from the CSV file, there seem to be a shift/rotation in relation to the original video coordinates. I am attaching a screenshot from the labeled video as well as the plot from our custom visualization script, which both show the same video frame and the individual keypoints plotted. Note that in the lower subplot, I only plot the tailbase and back paw keypoints (the dark blue and yellow markers that can be found in the labeled video), but these clearly seem to be mismatched in relation to the animal body. Is this perhaps a known issue or am I missing some step here? Note that the video has an unusual dimensionality (1024x445 pixels), perhaps this could contribute to the error.
Best regards
Pavol
![multianimal_shift](https://user-images.githubusercontent.com/2625621/114015214-bcb68b80-9869-11eb-89eb-2608d2a8e4f4.jpg)

**Comment by MMathisLab** [comment]
hey @pavolbauer thanks for the report, we will look into it! We never use the CSV files for analysis (only H5, meaning the video, plot_trajectories, tracklets, etc all use H5 files never CSV), so this might indeed be something we missed-- @jeylau can you check it out? 

also, can you @pavolbauer confirm how you got the CSV file -- which fxn did you use at this step (there are a few ways)? i.e.,  which tracker you used (ellipse, box, etc?); then once you had that pickle, it's loaded in the tracking GUI, saved, then exported to CSV?

**Comment by pavolbauer** [comment]
Hey @MMathisLab, thanks for having a look at it! I now plotted the coordinates from the h5 file and the offset is the same as in the csv. I got the h5 out of convert_detections2tracklets and then ran refine_tracklets which also created the csv. The tracking method is "skeleton", would you suggest to try any other procedure instead?
Best,
Pavol

**Comment by MMathisLab** [comment]
hmm... then I am concerned maybe it's your custom code? Could you compare how you plot it to how we plot it for the videos:  https://github.com/DeepLabCut/DeepLabCut/blob/87e18282c0ea354780cbf16ddfed85869a887664/deeplabcut/utils/plotting.py#L35 (but we will check it out too ;).

**Comment by pavolbauer** [comment]
Dear @MMathisLab,
You were right, the bug was one our side, somehow an overlooked "extent" parameter sneaked in to the imshow command, which shifted the background image plane in relation to the plotted points. My bad, sorry to have bothered you guys :)
Best,
Pavol

**Comment by MMathisLab** [comment]
No worries at all, yeah everything seems to check out on our side, so I will close :)
