### ISSUE TITLE
Error message when trying to import DeeplabCut on MacOs Big Sur No such file or directory

### ISSUE THREAD

**Issue by gmqueens** [DeepLabCut/DeepLabCut#1186]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

MACOS 11.2.3 Big Sur, Anaconda3, DeepLabCut Version ??

Please complete the following information about your system:

OS:  MAC OS
DeepLabCut Version: Cannot determine
Anaconda env used: DLC-CPU

I am able to load the DLC-CPU but when I call pythonw import deeplabcut I receive the following error

<details><summary>Code output</summary><p>

[/Users/gerome/opt/anaconda3/envs/DLC-CPU/python.app/Contents/MacOS/python: can't open file 'import': [Errno 2] No such file or directory]

</p></details>

**How to Reproduce the problem**
1.  Run conda activate DLC-CPU
2. pythonw  import deeplabcut

**Screenshots**
![image](https://user-images.githubusercontent.com/82047714/114124793-362e9800-98c3-11eb-9eb8-720851ea4abb.png)

**Additional context**
I have tried deleting and reinstalling  the Conda Env
I have tried uninstalling and resintalling Anaconda3 (multiple times)
I have xcode comnand line installed
I am able to import numpy and matlibplot outside of the DLC-CPU env

**Comment by backyardbiomech** [comment]
The pythonw and import deeplabcut need to be on separate lines (hit enter after pythonw). Or, instead of that, try 
pythonw -m deeplabcut

**Comment by gmqueens** [comment]
Wow.... that was easy (I n00bed out). Thank you very much.
