### ISSUE TITLE
Installation error: Config option kernel_spec_manager_class not recognized by EnableNBExtensionApp

### ISSUE THREAD

**Issue by BrainOdyssey2050** [DeepLabCut/DeepLabCut#1187]
Hey there

WIN10+Anaconda

I followed the installation instruction here: 
https://github.com/DeepLabCut/DeepLabCut/blob/master/conda-environments/README.md
I git clone the repo, and run conda env create -f DLC-CPU.yaml or conda env create -f DLC-GPU.yaml in the "conda-environments" folder. 

However, no matter whether CPU or GPU version installation I followed (BTW I have a Nvidia GPU), there were always errors like this:
---------------------------------------------------------------------------------------
Enabling nb_conda_kernels…
CONDA_PREFIX: G:\STUDY\Anaconda3\envs\DLC-GPU
Status: enabled

**Config option kernel_spec_manager_class not recognized by EnableNBExtensionApp.**
Traceback (most recent call last):
File “G:\STUDY\Anaconda3\envs\DLC-GPU\Scripts\jupyter-nbextension-script.py”, line 10, in 
   ........
  import _ssl...
**ImportError: DLL load failed: The specified module could not be found.**

An error occurred while installing package 'conda-forge::nb_conda-2.2.1-py37h03978a9_4'.
LinkError: post-link script failed for package conda-forge::nb_conda-2.2.1-py37h03978a9_4
running your command again with `-v` will provide additional information
location of failed script: G:\STUDY\Anaconda3\envs\DLC-GPU\Scripts\.nb_conda-post-link.bat
---------------------------------------------------------------------------------------
Then the installation stuck.

Anyone know how to solve this?? thank you!

**Comment by MMathisLab** [comment]
Hi @BrainOdyssey2050 did you check out the related issues? Most always this is a cuda/TF mismatch: https://github.com/DeepLabCut/DeepLabCut/search?q=ImportError%3A+DLL+load+failed%3A+The+specified+module+could+not+be+found&type=issues

**Comment by jeylau** [comment]
Seems like a conda issue https://github.com/conda/conda/issues/9761.
Could you try `conda update conda --yes`?

**Comment by BrainOdyssey2050** [comment]
I reinstalled anaconda (I had an relatively old version before), and now everything works!
Thank you!
