### ISSUE TITLE
testscript.py issue --- ImportError: No module named deeplabcut

### ISSUE THREAD

**Issue by rshteyn** [DeepLabCut/DeepLabCut#1188]
OS: Mac OS 10.13.6
DeepLabCut Version: unsure, likely the most recent one as of 4/12/2021
Anaconda env used: 3.0

I am having trouble installing DLC on my Mac. The main issue is that I cannot get the test code in /examples to run with testscript.py -- I keep getting "ImportError: No module named deeplabcut"

All of the following code runs fine, except for the final testscript.py line:

(base) OSXLAP05710:~ rshteyn$ git clone https://github.com/DeepLabCut/DeepLabCut.git
(base) OSXLAP05710:desktop rshteyn$ cd DeepLabCut/conda-environments
(base) OSXLAP05710:conda-environments rshteyn$ conda env create -f DLC-CPU.yaml
conda activate DLC-CPU
cd
cd desktop/DeepLabCut/examples
pythonw testscript.py

Here is the output with the error:

<img width="442" alt="Screen Shot 2021-04-12 at 12 19 13 PM" src="https://user-images.githubusercontent.com/82400459/114428097-c69dfe80-9b89-11eb-9b4c-4ad01b919f62.png">

**Comment by MMathisLab** [comment]
seems it's not installed then; also if you want to use the github version, you'd need to cd into "DeepLabCut", then it would import the deeplabcut folder.

**Comment by rshteyn** [comment]
I just tried to do it the other way, by downloading the .yaml file on the site homepage. However, when I try to run "pip install deeplabcut==2.2b8", or simply just "pip install deeplabcut" (DLC-CPU is activated), terminal runs into a bunch of issues when it gets to the part where it is
"Building wheels for collected packages: numba
 Building wheel for numba (setup.py) ... error"


Basically any output related to numba comes out in red error text. At this point I am worried that there might be some leftover odds and ends from the other installation attempts I made. No idea how to proceed... am I completely missing something with this installation?

**Comment by MMathisLab** [comment]
You should not run pip install. I would ask you to read this page, which explains how to use the conda file to install properly: https://github.com/DeepLabCut/DeepLabCut/tree/master/conda-environments

**Comment by rshteyn** [comment]
I finally got it to work through [this resource](https://guillermohidalgogadea.com/openlabnotebook/installing-deeplabcut/)! All it took was an update from MacOSX High Sierra to Big Sur and downloading X code.

DLC does open when I type "pythonw -m deeplabcut", however these warnings still come up. Any idea what they might mean?


(DLC-CPU) OSXLAP05710:~ rshteyn$ pythonw -m deeplabcut

/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

**Comment by jeylau** [comment]
Hi @rshteyn, these tensorflow warnings are not harmful (https://github.com/tensorflow/tensorflow/issues/30427) but if they annoy you, you could get rid of them by downgrading numpy to 1.16.4 😊

**Comment by rshteyn** [comment]
oh awesome! thank you.
