### ISSUE TITLE
Same labels for following frames

### ISSUE THREAD

**Issue by giuliacimi88** [DeepLabCut/DeepLabCut#1189]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). 
Please fill out the template completely, including the full "TRACEBACK" and input code that you ran to hit this error.

**Describe the bug**
After loading my project, clicking on Label Frames, loading my frames, and labelling the first frame, the following frames have the same labels already on the image. 

**Desktop (please complete the following information about your system):**
 - OS: Windows10
 - DeepLabCut Version: 2.1.9
 - DeepLabCut mode:  single animal tracking
 

**To Reproduce**

1) In the GUI, Load project, Label frames, Label frames, Load frame 
2) label the first frame 
3) go on the next frame
4) next frame and all the following ones will have the first frame labels already on the image

<details><summary>TRACEBACK</summary><p>

```python

^do not delete the above "<details><summary>TRACEBACK</summary><p>" or the ```python part!

do not delete below this line, leave the blank line and the ```

```
</p></details>

**Expected behavior**
I expected the labels to be only 
on the labeled frames, in this case my first frame, and I expected the following frame to not have any labels on, before I manually label them.

**Screenshots**
![labeled frame](https://user-images.githubusercontent.com/82583438/114861326-044a9380-9de5-11eb-9b94-87ce717b989a.png)
![second frame](https://user-images.githubusercontent.com/82583438/114861332-06145700-9de5-11eb-986b-f2099ad01942.png)
![4th frame](https://user-images.githubusercontent.com/82583438/114861347-0ad90b00-9de5-11eb-8dfe-1331510059b6.png)
![Output](https://user-images.githubusercontent.com/82583438/114861352-0d3b6500-9de5-11eb-9906-183634a9c254.png)

**Additional context**

**Comment by jeylau** [comment]
Hello @giuliacimi88! Please update DLC, I cannot reproduce that behavior with 2.1.10.3 😊

**Comment by giuliacimi88** [comment]
> Hello @giuliacimi88! Please update DLC, I cannot reproduce that behavior with 2.1.10.3 😊

Hi jeylau! Thanks for your reply. I am trying to reinstall DLC since the update has given me some problems. Once dowload the yaml file from http://www.mackenziemathislab.org/deeplabcut, opened anaconda prompt and typed conda env create -f DLC-CPU.yaml I got the following error:

ERROR conda.core.link:_execute(698): An error occurred while installing package 'defaults::qt-5.9.7-vc14h73c81de_0'.
Rolling back transaction: done

LinkError: post-link script failed for package defaults::qt-5.9.7-vc14h73c81de_0
location of failed script: C:\Giulia\Anaconda\envs\DLC-CPU\Scripts\.qt-post-link.bat
==> script messages <==
<None>
==> script output <==
stdout:         1 file(s) copied.

stderr: 'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.

return code: 1

()

Do you know what can it be?
Python 3.7.10

**Comment by giuliacimi88** [comment]
Hi jeylau! Thanks for your reply. I am trying to reinstall DLC since the update has given me some problems. Once dowload the yaml file from http://www.mackenziemathislab.org/deeplabcut, opened anaconda prompt and typed conda env create -f DLC-CPU.yaml I got the following error:

ERROR conda.core.link:_execute(698): An error occurred while installing package 'defaults::qt-5.9.7-vc14h73c81de_0'.
Rolling back transaction: done

LinkError: post-link script failed for package defaults::qt-5.9.7-vc14h73c81de_0
location of failed script: C:\Giulia\Anaconda\envs\DLC-CPU\Scripts.qt-post-link.bat
==> script messages <==

==> script output <==
stdout: 1 file(s) copied.

stderr: 'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.

return code: 1

()

Do you know what can it be?
before creating the env Python version is 3.7.10, after the env is created Python version is 3.8.5 even if DLC needs Python=3.7. I do not how to fix it.
Sorry if this is not the right place to ask this.

**Comment by MMathisLab** [comment]
@giuliacimi88 you can use your existing conda; just simple run `pip install deeplabcut==2.10.3`

**Comment by giuliacimi88** [comment]
MMathisLab, I tried and I got the following error:

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 4.2.0 requires pyqt5<5.13, which is not installed.
spyder 4.2.0 requires pyqtwebengine<5.13, which is not installed.
spyder 4.2.0 requires parso==0.7.0, but you have parso 0.7.1 which is incompatible.`

If I try to use DLC that is what happens:
`In [1]: import deeplabcut
C:\Giulia\Anaconda\envs\NEWDLC-CPU\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Giulia\Anaconda\envs\NEWDLC-CPU\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Giulia\Anaconda\envs\NEWDLC-CPU\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Giulia\Anaconda\envs\NEWDLC-CPU\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Giulia\Anaconda\envs\NEWDLC-CPU\lib\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Giulia\Anaconda\envs\NEWDLC-CPU\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])`

When I try to label the frames, I got the following error:

`TypeError                                 Traceback (most recent call last)
C:\Giulia\Anaconda\envs\NEWDLC-CPU\lib\site-packages\deeplabcut\gui\labeling_toolbox.py in browseDir(self, event)
    652         img_name = Path(self.img).name
    653         self.norm, self.colorIndex = self.image_panel.getColorIndices(
--> 654             self.img, self.bodyparts
    655         )
    656
C:\Giulia\Anaconda\envs\NEWDLC-CPU\lib\site-packages\deeplabcut\gui\labeling_toolbox.py in getColorIndices(self, img, bodyparts)
    193         im = cv2.imread(img)
    194         norm = mcolors.Normalize(vmin=0, vmax=np.max(im))
--> 195         ticks = np.linspace(0, np.max(im), len(bodyparts))[::-1]
    196         return norm, ticks
    197
<__array_function__ internals> in linspace(*args, **kwargs)
C:\Giulia\Anaconda\envs\NEWDLC-CPU\lib\site-packages\numpy\core\function_base.py in linspace(start, stop, num, endpoint, retstep, dtype, axis)
    126     # and make sure one can use variables that have an __array_interface__, gh-6634
    127     start = asanyarray(start) * 1.0
--> 128     stop  = asanyarray(stop)  * 1.0
    129
    130     dt = result_type(start, stop, float(num))
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'`



deeplabcut version:2.1.10.3
python version: 3.7.9

**Comment by MMathisLab** [comment]
this is fine (if you want the warning to go away, just run `pip install numpy==1.16.4` its just a warning:

```python
In [1]: import deeplabcut 
C:\Giulia\Anaconda\envs\NEWDLC-CPU\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_qint8 = np.dtype([("qint8", np.int8, 1)]) C:\Giulia\Anaconda\envs\NEWDLC-CPU\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_quint8 = np.dtype([("quint8", np.uint8, 1)]) C:\Giulia\Anaconda\envs\NEWDLC-CPU\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_qint16 = np.dtype([("qint16", np.int16, 1)]) C:\Giulia\Anaconda\envs\NEWDLC-CPU\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_quint16 = np.dtype([("quint16", np.uint16, 1)]) C:\Giulia\Anaconda\envs\NEWDLC-CPU\lib\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. _np_qint32 = np.dtype([("qint32", np.int32, 1)]) C:\Giulia\Anaconda\envs\NEWDLC-CPU\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'. np_resource = np.dtype([("resource", np.ubyte, 1)])
```

second seems you might have an error in config.yaml

**Comment by giuliacimi88** [comment]
I changed the paths in the config file, probably they were too long.
It still doesn't work tho. I have this error now:
`IndexError                               Traceback (most recent call last)
C:\Giulia\Anaconda\envs\NEWDLC-CPU\lib\site-packages\deeplabcut\gui\labeling_toolbox.py in browseDir(self, event)
    615         )
    616         self.relativeimagenames = [
--> 617             "labeled" + n.split("labeled")[1] for n in self.index
    618         ]  # [n.split(self.project_path+'/')[1] for n in self.index]
    619
C:\Giulia\Anaconda\envs\NEWDLC-CPU\lib\site-packages\deeplabcut\gui\labeling_toolbox.py in <listcomp>(.0)
    615         )
    616         self.relativeimagenames = [
--> 617             "labeled" + n.split("labeled")[1] for n in self.index
    618         ]  # [n.split(self.project_path+'/')[1] for n in self.index]
    619
IndexError: list index out of range`

Thanks a lot!

**Comment by MMathisLab** [comment]
can you post exactly what you post when you get this error?

**Comment by giuliacimi88** [comment]
Sure:
import and launch DLC
![1](https://user-images.githubusercontent.com/82583438/115228627-eb562100-a109-11eb-9416-9f2ac7da5b15.png)
load the project 
![2](https://user-images.githubusercontent.com/82583438/115228723-088aef80-a10a-11eb-98fc-4369edfa5554.png)
in label frames I click on label frames and open the folder with the frames extracted from the video
![4](https://user-images.githubusercontent.com/82583438/115228846-2eb08f80-a10a-11eb-915e-c7773a242371.png)
![5](https://user-images.githubusercontent.com/82583438/115228855-31ab8000-a10a-11eb-9a52-a912dc46bdd6.png)
Once I click on select folder it gives me the following error and does not load any frames
![6](https://user-images.githubusercontent.com/82583438/115228940-4be55e00-a10a-11eb-8bd0-da70f135b6a8.png)

**Comment by MMathisLab** [comment]
oh, you need to go into the folder, then click open, not just clicking on the folder icon.

**Comment by giuliacimi88** [comment]
I do, but the folder is empty, I mean it is not but it looks like it ...
![7](https://user-images.githubusercontent.com/82583438/115229559-1b51f400-a10b-11eb-8772-66c235d816dc.png)
![8](https://user-images.githubusercontent.com/82583438/115229566-1db44e00-a10b-11eb-9c25-64e66dc11292.png)

**Comment by MMathisLab** [comment]
awe then you need to be sure that when you open the terminal, you right click and say "open as admin"; then start conda env, then you can just run: python -m deeplabcut (no need to open ipython).

**Comment by giuliacimi88** [comment]
same problem. 
![9](https://user-images.githubusercontent.com/82583438/115230440-438e2280-a10c-11eb-81d2-150560c71aa5.png)
and the folder looks still empty

**Comment by MMathisLab** [comment]
Do you have admin/ root rights on this computer?

**Comment by giuliacimi88** [comment]
I would say so. Also, I have already labelled/extracted frames and worked on DLC without the need of opening the Anaconda Prompt as admin. :(

**Comment by MMathisLab** [comment]
^^ with this exact project and config.yaml? I am worried then there is still a typo in your config.yaml

**Comment by giuliacimi88** [comment]
Yes, when I posted the first problem, the one about having the same labels on different frames (see above) I could open the frames with the same project and config.yaml.
Here my config.yaml I cannot find the typo, I went through it so many times!
![config1](https://user-images.githubusercontent.com/82583438/115232190-586bb580-a10e-11eb-9282-9361b05092bc.png)
![config2](https://user-images.githubusercontent.com/82583438/115232199-5a357900-a10e-11eb-9230-1384d8c31181.png)
![config3](https://user-images.githubusercontent.com/82583438/115232210-5c97d300-a10e-11eb-82f4-83f2d7491c80.png)

**Comment by MMathisLab** [comment]
can you change: 

`skeleton: []` 

i.e, add the [ ] 
^ it is not blank by default

**Comment by giuliacimi88** [comment]
If I do it I get this:
```
ruamel.yaml.scanner.ScannerError: while scanning a simple key
  in "C:\Giulia\DeepLabCut\Labelling\SMBW\config.yaml", line 108, column 1
could not find expected ':'
  in "C:\Giulia\DeepLabCut\Labelling\SMBW\config.yaml", line 109, column 1
```

**Comment by giuliacimi88** [comment]
same error
```
Starting GUI...
Traceback (most recent call last):
  File "C:\Giulia\Anaconda\envs\NEWDLC-CPU\lib\site-packages\deeplabcut\gui\labeling_toolbox.py", line 617, in browseDir
    "labeled" + n.split("labeled")[1] for n in self.index
  File "C:\Giulia\Anaconda\envs\NEWDLC-CPU\lib\site-packages\deeplabcut\gui\labeling_toolbox.py", line 617, in <listcomp>
    "labeled" + n.split("labeled")[1] for n in self.index
IndexError: list index out of range
```

**Comment by MMathisLab** [comment]
hi @giuliacimi88 -- I'm not sure; can you load the project in your old env. and confirm it works.

**Comment by giuliacimi88** [comment]
It doesn't work anymore, same error. I also tried to made a new environment with DLC but I get this scary error:

```
ERROR conda.core.link:_execute(698): An error occurred while installing package 'defaults::qt-5.9.7-vc14h73c81de_0'.
Rolling back transaction: done
LinkError: post-link script failed for package defaults::qt-5.9.7-vc14h73c81de_0
location of failed script: C:\Giulia\Anaconda\envs\DLC-CPU\Scripts\.qt-post-link.bat
==> script messages <==
<None>
==> script output <==
stdout:         1 file(s) copied.
stderr: 'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.
return code: 1
()
```
Myabe I did something wrong with conda??

**Comment by MMathisLab** [comment]
I would delete the conda env, and start again: 

(myenv is your conda env name):

`conda remove --name myenv --all .`

**Comment by GiuliaCimi** [comment]
Thanks, there was something wrong with the chcp path. Now it seems to work.
