### ISSUE TITLE
Is it possible to redirect create_training_dataset to download pretrained datasets in alternate location?

### ISSUE THREAD

**Issue by rdauria** [DeepLabCut/DeepLabCut#1190]
**Operating system and DeepLabCut version**

CentOS  Linux release 7.9.2009, with an Anaconda Env, &  DeepLabCut 2.1.10.3

**Description of the problem**

We would like to install deeplabcut as a conda environment in a centralized location for several users on a shared cluster. However I noticed, when testing the environment with the provided testscript.py, that the function create_training_dataset wants to donwload the pretrained data set within the conda environment:

```$CONDA_ENV/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained```

Please place code inside this:

<details><summary>Code output</summary><p>

python3 testscript.py
[...]
CREATING TRAININGSET
Downloading a ImageNet-pretrained model from http://download.tensorflow.org/models/resnet_v1_50_2016_08_28.tar.gz....
Traceback (most recent call last):
  File "testscript.py", line 121, in <module>
    path_config_file, net_type=net_type, augmenter_type=augmenter_type
  File "/u/local/apps/anaconda3/2020.11/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 918, in create_training_dataset
    net_type, Path(dlcparent_path), num_shuffles
  File "/u/local/apps/anaconda3/2020.11/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/utils/auxfun_models.py", line 62, in Check4weights
    Downloadweights(modeltype, model_path)
  File "/u/local/apps/anaconda3/2020.11/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/utils/auxfun_models.py", line 88, in Downloadweights
    tar.extractall(path=target_dir)
  File "/u/local/apps/anaconda3/2020.11/envs/DLC-GPU/lib/python3.7/tarfile.py", line 2002, in extractall
    numeric_owner=numeric_owner)
  File "/u/local/apps/anaconda3/2020.11/envs/DLC-GPU/lib/python3.7/tarfile.py", line 2044, in extract
    numeric_owner=numeric_owner)
  File "/u/local/apps/anaconda3/2020.11/envs/DLC-GPU/lib/python3.7/tarfile.py", line 2114, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/u/local/apps/anaconda3/2020.11/envs/DLC-GPU/lib/python3.7/tarfile.py", line 2155, in makefile
    with bltn_open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: '/u/local/apps/anaconda3/2020.11/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt'

</p></details>

**Questions**

Is there any way these preretrained model can be downloaded in the user $HOME? 

Or should we have each user just create their own conda env (which would be wasteful)? 

Alternatively could you suggest how to go about and prepopulate for the users all the locations where files needs to be downloaded and installed centrally?

Thanks,

RD

**Comment by jeylau** [comment]
The default download location is hardcoded, so you can't change it. What you could do though is let it download to `models/pretrained`, move it to the centralized folder of your choice, and update `init_weights` in `dlc-models/./train/pose_cfg.yaml` to reflect this new location.

**Comment by rdauria** [comment]
Thanks for your prompt reply. Just so that our users won't get an error when running the centrally installed code (or that they won't exhaust the space in their $HOME directories by performing local installs), is there a way to prepopulate the models/pretrained? I understand that we (the administrators) might need to update the models from time to time but this would be  preferable (if done in bulk) than to answer many separate requests. What command should I issue to download as many as possible of the pretrained models?

**Comment by jeylau** [comment]
The following will give you all pretrained models currently supported by DeepLabCut:

```
from deeplabcut.utils import auxfun_models, auxiliaryfunctions


dlc_path = auxiliaryfunctions.get_deeplabcut_path()
networks = [
    "resnet_50",
    "resnet_101",
    "resnet_152",
    "mobilenet_v2_1.0",
    "mobilenet_v2_0.75",
    "mobilenet_v2_0.5",
    "mobilenet_v2_0.35",
    "efficientnet-b0",
    "efficientnet-b3",
    "efficientnet-b6",
]
for network in networks:
    auxfun_models.Check4weights(network, dlc_path, 1)
```

**Comment by rdauria** [comment]
When executing the code you sent I get:

```
    auxfun_models.Check4weights(network, dlc_path, 1)
  File "/u/local/apps/anaconda3/2020.11/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/utils/auxfun_models.py", line 22, in Check4weights
    / "pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt"
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

I am not sure what passes the "/" perhaps you have an idea before I look into the code? 

Thanks,

RD

**Comment by jeylau** [comment]
My mistake... You also need:
```
from pathlib import Path

dlc_path = Path(auxiliaryfunctions.get_deeplabcut_path())
```
That should work now 😊

**Comment by MMathisLab** [comment]
also for shared resources, I would use consider using our docker containers

**Comment by rdauria** [comment]
Thanks Jessy the command worked! 

Mackenzie, we would like to run your container but, for security reasons, we can only run singularity in userspace on a non writable filesystem, so we would still need to download the pretrained modeles somewhere else, I think.

After importing the container with:

```
singularity shell --userns --nv $H2_CONTAINER_LOC/deeplabcut.sif 
```

and trying to run testscript.py in the DeepLabCut examples/ directory I, for example, get the following error:

```
Singularity> python3 testscript.py 
DLC loaded in light mode; you cannot use the relabeling GUI!
DLC loaded in light mode; you cannot use the relabeling GUI!
Imported DLC!
CREATING PROJECT
Created "/u/local/downloads/deeplabcut/DeepLabCut/examples/TEST-Alex-2021-04-17/videos"
Created "/u/local/downloads/deeplabcut/DeepLabCut/examples/TEST-Alex-2021-04-17/labeled-data"
Created "/u/local/downloads/deeplabcut/DeepLabCut/examples/TEST-Alex-2021-04-17/training-datasets"
Created "/u/local/downloads/deeplabcut/DeepLabCut/examples/TEST-Alex-2021-04-17/dlc-models"
Copying the videos
/u/local/downloads/deeplabcut/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30/videos/reachingvideo1.avi
Generated "/u/local/downloads/deeplabcut/DeepLabCut/examples/TEST-Alex-2021-04-17/config.yaml"

A new project with name TEST-Alex-2021-04-17 is created at /u/local/downloads/deeplabcut/DeepLabCut/examples and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
EXTRACTING FRAMES
Traceback (most recent call last):
  File "testscript.py", line 75, in <module>
    deeplabcut.extract_frames(path_config_file, mode="automatic", userfeedback=False)
TypeError: extract_frames() got an unexpected keyword argument 'userfeedback'
```

besides in the container I don't seem to be able to use the GUI. If you have any idea how to get around these two issues please let me know.

Thanks,

RD

**Comment by MMathisLab** [comment]
Hey RD, could you `import deeplabcut` and tell me the version? `deeplabcut.__version__`?  (that's bizarre; test script is passing on the repo and `userfeedback` is a long-standing addition; there is nothing below that TypeError? (I am more worried it's a permissions issue that is not allowing for you to download video/open it)

**Comment by rdauria** [comment]
Hello Mackenzie,

The version is:

2.0.2

Here is the error I get when trying to run testscrit.py:

```
Singularity> python3
Python 3.6.3 (default, Oct  6 2017, 08:44:35) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import deeplabcut
DLC loaded in light mode; you cannot use the relabeling GUI!
DLC loaded in light mode; you cannot use the relabeling GUI!
>>> deeplabcut.__version__
'2.0.2'
>>>     
Singularity> python3 testscript.py 
DLC loaded in light mode; you cannot use the relabeling GUI!
DLC loaded in light mode; you cannot use the relabeling GUI!
Imported DLC!
CREATING PROJECT
Created "/u/local/downloads/deeplabcut/DeepLabCut/examples/TEST-Alex-2021-04-19/videos"
Created "/u/local/downloads/deeplabcut/DeepLabCut/examples/TEST-Alex-2021-04-19/labeled-data"
Created "/u/local/downloads/deeplabcut/DeepLabCut/examples/TEST-Alex-2021-04-19/training-datasets"
Created "/u/local/downloads/deeplabcut/DeepLabCut/examples/TEST-Alex-2021-04-19/dlc-models"
Copying the videos
/u/local/downloads/deeplabcut/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30/videos/reachingvideo1.avi
Generated "/u/local/downloads/deeplabcut/DeepLabCut/examples/TEST-Alex-2021-04-19/config.yaml"

A new project with name TEST-Alex-2021-04-19 is created at /u/local/downloads/deeplabcut/DeepLabCut/examples and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
EXTRACTING FRAMES
Traceback (most recent call last):
  File "testscript.py", line 75, in <module>
    deeplabcut.extract_frames(path_config_file, mode="automatic", userfeedback=False)
TypeError: extract_frames() got an unexpected keyword argument 'userfeedback'
Singularity> 
```

RD

**Comment by MMathisLab** [comment]
Oh! That’s about 1.5 years old. Can you upgrade, as the test script is meant to be used with very latest on GitHub. ‘Pip install deeplabcut==2.1.10.3’

**Comment by AlexEMG** [comment]
A small clarifying comment. You don't need to update DLC, if that is not ideal for your situation. But you should run the corresponding testscript for the relevant version. I.e. if you can check them here: https://github.com/DeepLabCut/DeepLabCut/releases

Specifically, e.g. for 2.0.1 you can find: 
https://github.com/DeepLabCut/DeepLabCut/blob/v2.0.1/examples/testscript.py

(note that 2.0.2 doesn't have a tag, sorry!)
