### ISSUE TITLE
Can not create h5 file when creating training dataset

### ISSUE THREAD

**Issue by EAST-J** [DeepLabCut/DeepLabCut#1192]
Hello, I use DeepLabCut[gui], after labeling my frames and  I tried to create training dataset, I get error like this:
  File "D:\pytables_hdf5\CMake-hdf5-1.10.5\hdf5-1.10.5\src\H5F.c", line 444, in H5Fcreate
    unable to create file
  File "D:\pytables_hdf5\CMake-hdf5-1.10.5\hdf5-1.10.5\src\H5Fint.c", line 1509, in H5F_open
    unable to open file: time = Fri Apr 16 21:22:38 2021
, name = 'D:\Deeplabcut_project\1\training-datasets\iteration-0\UnaugmentedDataSet_Test1四月16\CollectedData_TestDog.h5', tent_flags = 13
  File "D:\pytables_hdf5\CMake-hdf5-1.10.5\hdf5-1.10.5\src\H5FD.c", line 734, in H5FD_open
    open failed
  File "D:\pytables_hdf5\CMake-hdf5-1.10.5\hdf5-1.10.5\src\H5FDsec2.c", line 346, in H5FD_sec2_open
    unable to open file: name = 'D:\Deeplabcut_project\1\training-datasets\iteration-0\UnaugmentedDataSet_Test1四月16\CollectedData_TestDog.h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 302

End of HDF5 error back trace

Unable to open/create file 'D:\Deeplabcut_project\1\training-datasets\iteration-0\UnaugmentedDataSet_Test1四月16\CollectedData_TestDog.h5'

And when I tried to change my tables version like others, I get error:

ImportError: Missing optional dependency 'tables'.  Use pip or conda to install tables.
But, In conda list there is tables. I reinstalled it then fixed, but still can not create h5 file.
Could you please tell me how to fix this?

**Comment by jeylau** [comment]
Hello! I believe this may have something to do with these characters 四月 in your file name. Could you remove those and let us know?

**Comment by EAST-J** [comment]
> Hello! I believe this may have something to do with these characters 四月 in your file name. Could you remove those and let us know?

Yeah, I fix this by changing data into English, Thanks

**Comment by EAST-J** [comment]
> Hello! I believe this may have something to do with these characters 四月 in your file name. Could you remove those and let us know?

Yeah, I fix this by changing date to English. Thanks.
