### ISSUE TITLE
Corners not detected in 3D Camera Calibration 

### ISSUE THREAD

**Issue by evianapetropoulou** [DeepLabCut/DeepLabCut#1197]
**Your Operating system and DeepLabCut version**
OS: Windows 10 Professional 1803 
DeepLabCut: 2.1.10.2
Anaconda Env used: 2020.11 Version

**Describe the problem**
Hello,
I am having some trouble with the camera calibration needed for a 3D Project. The setup consists of 2 lateral cameras (one on the left and one on the right) and a mouse box. The videos I took can be viewed here :
Video 1: https://www.dropbox.com/s/z7xpwj2z03l7d2n/ch01_20210414104348_001.avi?dl=0
Video 2: https://www.dropbox.com/s/sorcrovgya0ay6z/ch02_20210414104348_001.avi?dl=0 

After taking the videos, I extracted the frames, chose the best ones among them and put them in the calibration_images file. 
However, when I run the command to calibrate the cameras, it doesn't find the corners of any of the images. 

This is the command I run : deeplabcut.calibrate_cameras(config_path3d, cbrow=3, cbcol=4, calibrate=False, alpha=0.9)
And the output is: 
Corners not found for the image camera-1-001.jpg
Corners not found for the image camera-2-001.jpg
Corners not found for the image camera-1-002.jpg
Corners not found for the image camera-2-002.jpg
...
Corners not found for the image camera-1-174.jpg
Corners not found for the image camera-2-174.jpg
Corners extracted! You may check for the extracted corners in the directory C:\Users\e.petropoulou\demo-eviana-2021-04-11-3d\corners and remove the pair of images where the corners are incorrectly detected. If all the corners are detected correctly with right order, then re-run the same function and use the flag ``calibrate=True``, to calbrate the camera.

The corners folder is empty, because no corners are found. I have tried changing the alpha parameter and increasing the contrast. Also, I thought that there may be a reflexion problem, but even when I paint on the reflexion (so that it's not spotted), the corners are still not detected and thus not extracted. 
Last but not least, I would like to let you know that I can not move the cameras from the box and the biggest chessboard size I can use is 5x5 (however, in the videos provided I am using a 5x4 chessboard). 

Any advice would be of great help, since I've been struggling with this step for some time now. 
Thank you in advance and have a nice day!

**Comment by evianapetropoulou** [comment]
I put cbrow=3 and cbcol=4 by mistake while writing this issue, excuse me. The correct form is cbrow=4 and cbcol=3. I still have the same problem though.

**Comment by MMathisLab** [comment]
from those videos, the checkerboard is not parallel enough to the camera to detect them with openCV (which is what is used in DLC). It assumes setero-conf, see the demo data here: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/Overviewof3D.md

**Comment by evianapetropoulou** [comment]
Hello, 

Thank you so much for the reply!
Of course I haven't forgotten about this issue, but I am still trying to find a solution concerning the camera configuration in the setup.
I will post a follow up comment once I figure it out.

**Comment by evianapetropoulou** [comment]
I will! Thank you!

**Comment by ZICHEN02023** [comment]
Do you solve the problem?I have met the similar problem with you,but I have a error about key
