### ISSUE TITLE
Minor issues with reading in .mp4 videos

### ISSUE THREAD

**Issue by mschart** [DeepLabCut/DeepLabCut#12]
Hi there,

Here are a couple minor issues you may want to address.

There's a small error when running Step2_AnalysisofResults.py:

```
~/DeepLabCut-master/Evaluation-Tools$ python3 Step2_AnalysisofResults.py
Traceback (most recent call last):
  File "Step2_AnalysisofResults.py", line 92, in <module>
    for trainingiterations,index in snapindices:
TypeError: 'int' object is not iterable
```

I've circumventing it by putting square brackets around snapindices in line 92:

`for trainingiterations,index in [snapindices]:`

How can I see if that error is big or small?

```
~/DeepLabCut-master/Evaluation-Tools$ python3 Step2_AnalysisofResults.py
Results for 950000 training iterations: 95 1 train error: 0.8272971490056671 test error: 2.499064498562305
```

l115 in AnalyzeVideos.py, maybe you also want to accept other video formats, say mp4?
`videos = np.sort([fn for fn in os.listdir(os.curdir) if (".mp4" in fn)])#was avi`

same thing for line 73 in MakingLabeledVideo.py

`videos = np.sort([fn for fn in os.listdir(os.curdir) if (".mp4" in fn)])#was .avi`

Maybe you may want to write somewhere a rough overview of processing time. In my case it took 24h for training the net (cropped image, 2 points), number of frames times 15 frames/second for predicting 2 point positions, number of frames times 4 frames/second for labelling the video with the predicted points. 

Anyway, those are just small comments, overall my example finger tracking worked flawlessly thanks to your great software. Many thanks for such transparent sharing!

**Comment by MMathisLab** [comment]
These (Step2_Analys... & video format issue) were all fixed in a commit early this week, so please pull the latest GitHub version! 

And happy to hear it works well for you, the test error sounds pretty low.

The training time is described in the paper, but we could perhaps maybe also add this in the readme! Evaluation time depends a lot on the framesize, but we could perhaps also add some information to the readme.

**Comment by AlexEMG** [comment]
Dear Michael,

please note that we updated the Analysis Code to make the comparison of human labels + DeepLabCut's labels as in the paper (This can also be helpful to get a feel for "how" good/bad the RMSEs that you get are). See:

https://github.com/AlexEMG/DeepLabCut/blob/master/Evaluation-Tools/Step2_AnalysisofResults.py

Alexander
