### ISSUE TITLE
Installation failed on Ubuntu 18.04

### ISSUE THREAD

**Issue by aleksejs-fomins** [DeepLabCut/DeepLabCut#120]
**Installation procedure followed**
1. conda create -n dlc_env python=3.6
2. source activate dlc_env
3. pip install deeplabcut
4. pip install https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04/wxPython-4.0.3-cp36-cp36m-linux_x86_64.whl
5. pip install --ignore-installed tensorflow==1.10

The last operation throws the following error:

`deeplabcut 2.0.0.dev5 has requirement wheel==0.31.1, but you'll have wheel 0.32.3 which is incompatible.`

Afterwards, my attempt to run python and import deeplabcut is greeted by

```
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import deeplabcut
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/dlc_env/lib/python3.6/site-packages/deeplabcut/__init__.py", line 25, in <module>
    from deeplabcut import generate_training_dataset
  File "/opt/anaconda3/envs/dlc_env/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/__init__.py", line 15, in <module>
    from deeplabcut.generate_training_dataset.auxfun_drag_label import *    
  File "/opt/anaconda3/envs/dlc_env/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/auxfun_drag_label.py", line 18, in <module>
    import wx
  File "/opt/anaconda3/envs/dlc_env/lib/python3.6/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/opt/anaconda3/envs/dlc_env/lib/python3.6/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: libpng12.so.0: cannot open shared object file: No such file or directory
```

**Comment by aleksejs-fomins** [comment]
Installing wxpython using the following link seems to have fixed the 2nd issue
`pip install https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/wxPython-4.0.3-cp36-cp36m-linux_x86_64.whl`

**Comment by MMathisLab** [comment]
Yes, we don’t support Ubuntu 18 at this point in time.

**Comment by aleksejs-fomins** [comment]
Good to know. I would have appreciated if this was explicitly stated on the website. You state that Ubuntu 16.04 is the reference you have used, but not explicitly that it is the only linux you support. I guess I'll have to reinstall the system...

**Comment by AlexEMG** [comment]
The wheel thing is probably not a problem. Does it work with the wxPython command for Ubuntu 18? (I know people that use DLC on Ubuntu 18)

**Comment by MMathisLab** [comment]
Fair enough, but as far I as remember, it is more difficult with CUDA/TF, and there are some Kernel issues. So, unless he uses the Docker, then he might have issues down the line... 

https://askubuntu.com/questions/1060797/problem-installing-tensorflow-gpu-in-ubuntu-18-04-1

https://medium.com/@taylordenouden/installing-tensorflow-gpu-on-ubuntu-18-04-89a142325138

https://medium.com/@Oysiyl/install-tensorflow-1-8-0-with-gpu-from-source-on-ubuntu-18-04-bionic-beaver-35cfa9df3600

**Comment by Houiin** [comment]
I used python3.7 when I met this problem. Then I chose to use python3.6 and install tensorflow by using `conda install tensorflow-gpu`. Then I solved the problem for no reason.(At least I can't explain how the problem was solved😂
