### ISSUE TITLE
dlc.label_frames(config_path) error

### ISSUE THREAD

**Issue by rshteyn** [DeepLabCut/DeepLabCut#1202]
Operating system and DeepLabCut version:
deeplabcut 2.0, p3.68, tf1.14 on Linux (ran through a virtual environment using NoMachine)

After I extracted my frames, I tried to label them with the following line of code, and got this error. I do have a labeled-data folder, which contains the .png files for each video-- so the extraction was completed successfully. The video titles do not contain spaces, they are named as follows: "FMS1_AcqD1". So I am not sure why I'm getting these messages -- it's even quitting my python environment after it runs.

<details><summary>In [7]: dlc.label_frames(config_path)
</summary><p>

(ipython:6498): Gtk-WARNING **: 17:27:24.458: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(ipython:6498): Gtk-WARNING **: 17:27:24.458: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(ipython:6498): Gtk-WARNING **: 17:27:24.504: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(ipython:6498): Gtk-WARNING **: 17:27:24.504: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(ipython:6498): Gtk-WARNING **: 17:27:24.573: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(ipython:6498): Gtk-WARNING **: 17:27:24.590: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(ipython:6498): Gtk-WARNING **: 17:27:24.606: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(ipython:6498): Gtk-WARNING **: 17:27:24.624: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(ipython:6498): Gtk-WARNING **: 17:27:24.642: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(ipython:6498): Gtk-WARNING **: 17:27:24.766: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(ipython:6498): Gtk-WARNING **: 17:27:27.820: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(ipython:6498): Gtk-WARNING **: 17:27:27.820: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(ipython:6498): Gtk-WARNING **: 17:27:27.832: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(ipython:6498): Gtk-WARNING **: 17:27:27.857: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(ipython:6498): Gtk-WARNING **: 17:27:27.944: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(ipython:6498): Gtk-WARNING **: 17:27:27.984: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(ipython:6498): Gtk-WARNING **: 17:27:27.993: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)

(ipython:6498): Gtk-WARNING **: 17:27:28.017: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/gsfs0/public/deeplabcut/2.0-p3.68/envs/tfgpu/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/labeling_toolbox.py in browseDir(self, event)
    464 
    465 # Reading the image name
--> 466         self.img = self.index[self.iter]
    467         img_name = Path(self.index[self.iter]).name
    468         self.norm,self.colorIndex = self.image_panel.getColorIndices(self.img,self.bodyparts)

IndexError: index 0 is out of bounds for axis 0 with size 0

(ipython:6498): Gtk-WARNING **: 17:27:31.752: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)
Segmentation fault (core dumped)

</p></details>

**Comment by AlexEMG** [comment]
Does the GUI otherwise work? -- looks like a wxPython problem.

**Comment by rshteyn** [comment]
The GUI for labeling frames does pop up but when I load the folder with labeled-data, it never finishes loading. I also don't see the column on the right hand side with the labeling info.

I decided to scrap the labeled-data and imported videos and start over. However, now I am running into issues with the add_new_videos function:

`dlc.add_new_videos ('/gsfs0/data/shteynr/FMS-shteynr-2021-04-22/config.yaml',['/gsfs0
    ...: /data/shteynr/Documents/FMS1-16 videos'], copy_videos=True) `

Am I not able to import an entire folder? I keep getting an error that I'm calling to a directory. There are quite a lot of videos for me to write out the entire list.

**Comment by rshteyn** [comment]
Although I just tried to import only one video and it says that the video file is corrupted. So bizarre because I successfully imported it when I created the project.

**Comment by MMathisLab** [comment]
deeplabcut 2.0 >> please upgrade via `pip install 'deeplabcut[gui]'` and be sure to use the latest conda file

**Comment by rshteyn** [comment]
I reuploaded all the videos to my documents again. They are no longer corrupted, but I am getting this new error

`/usr/public/deeplabcut/2.1-p3.7/anaconda3/lib/python3.7/site-packages/deeplabcut/create_project/new.py:175: UserWarning: No valid videos were found. The project was not created... Verify the video files and re-create the project.
  "No valid videos were found. The project was not created... "`

All my permissions are read/write, and I did install the GUI and try creating the new project from there. same problem. Weird part is that I successfully created a new project with the same video files last week, so I don't know what could have changed.

**Comment by rshteyn** [comment]
`Created "/gsfs0/data/shteynr/Videos/xx-xx-2021-04-27/videos"
Created "/gsfs0/data/shteynr/Videos/xx-xx-2021-04-27/labeled-data"
Created "/gsfs0/data/shteynr/Videos/xx-xx-2021-04-27/training-datasets"
Created "/gsfs0/data/shteynr/Videos/xx-xx-2021-04-27/dlc-models"
Copying the videos
/gsfs0/data/shteynr/Videos/xx-xx-2021-04-27/videos/FMS1_AcqD1.mp4
/usr/public/deeplabcut/2.1-p3.7/anaconda3/lib/python3.7/site-packages/deeplabcut/create_project/new.py:168: UserWarning: Cannot open the video file! Skipping to the next one...
  warnings.warn("Cannot open the video file! Skipping to the next one...")
/usr/public/deeplabcut/2.1-p3.7/anaconda3/lib/python3.7/site-packages/deeplabcut/create_project/new.py:175: UserWarning: No valid videos were found. The project was not created... Verify the video files and re-create the project.
  "No valid videos were found. The project was not created... "`

**Comment by rshteyn** [comment]
`Created "/gsfs0/data/shteynr/Videos/xx-xx-2021-04-27/videos"

Created "/gsfs0/data/shteynr/Videos/xx-xx-2021-04-27/labeled-data"

Created "/gsfs0/data/shteynr/Videos/xx-xx-2021-04-27/training-datasets"

Created "/gsfs0/data/shteynr/Videos/xx-xx-2021-04-27/dlc-models"

Copying the videos

/gsfs0/data/shteynr/Videos/xx-xx-2021-04-27/videos/FMS1_AcqD1.mp4
/usr/public/deeplabcut/2.1-p3.7/anaconda3/lib/python3.7/site-packages/deeplabcut/create_project/new.py:168: UserWarning: Cannot open the video file! Skipping to the next one...

  warnings.warn("Cannot open the video file! Skipping to the next one...")

/usr/public/deeplabcut/2.1-p3.7/anaconda3/lib/python3.7/site-packages/deeplabcut/create_project/new.py:175: UserWarning: No valid videos were found. The project was not created... Verify the video files and re-create the project.

  "No valid videos were found. The project was not created... "
`

**Comment by rshteyn** [comment]
`Created "/gsfs0/data/shteynr/Videos/xx-xx-2021-04-27/videos"
Created "/gsfs0/data/shteynr/Videos/xx-xx-2021-04-27/labeled-data"
Created "/gsfs0/data/shteynr/Videos/xx-xx-2021-04-27/training-datasets"
Created "/gsfs0/data/shteynr/Videos/xx-xx-2021-04-27/dlc-models"
Copying the videos
/gsfs0/data/shteynr/Videos/xx-xx-2021-04-27/videos/FMS1_AcqD1.mp4
/usr/public/deeplabcut/2.1-p3.7/anaconda3/lib/python3.7/site-packages/deeplabcut/create_project/new.py:168: UserWarning: Cannot open the video file! Skipping to the next one...
  warnings.warn("Cannot open the video file! Skipping to the next one...")
/usr/public/deeplabcut/2.1-p3.7/anaconda3/lib/python3.7/site-packages/deeplabcut/create_project/new.py:175: UserWarning: No valid videos were found. The project was not created... Verify the video files and re-create the project.
  "No valid videos were found. The project was not created... "
`
