### ISSUE TITLE
backward compatibility issue - analyze video files generate different naming (2.1.10.4 vs 2.1.10.2)

### ISSUE THREAD

**Issue by mfkeles** [DeepLabCut/DeepLabCut#1204]
**Describe the bug**
Analyzed files with 2.1.10.4 are not recognized with the previous versions (2.1.10.2). When the same config file is used, 2.1.10.2 is looking for "resnet_50" in the name whereas 2.1.10.4 is searching for "resnet50". Manually changing the file name from "resnet50" to "resnet_50" solves this issue. 
*****I encountered this issue after failing to extract outlier frames with 2.1.10.4. Extract outlier frames in this version leads to  `missing 1 required positional argument: 'gui_size'` error in `outlier _frame_extraction_toolbox.py`. I then tried to extract outlier frames with the prev version (2.1.10.2) and then got the error `no analyzed video`. 

**Desktop (please complete the following information about your system):**
 - OS: Windows10
 - DeepLabCut Version: 2.1.10.4 vs 2.1.10.2
 - DeepLabCut mode: single animal tracking

**To Reproduce**
Steps to reproduce the behavior, i.e.:
1. Analyze a video with 2.1.10.4
2. Try extracting outlier frames using the manual option. This will fail (see above)
3. Use 2.1.10.2 to extract outlier frames. This will lead to 'no analyzed video' error.
4. Modify the analyzed file name as indicated above. Issue is solved. 
5. Below is the expected output when attempting to use `deeplabcut.extract_outlier_frames(config_path,vid_path, shuffle=1,outlieralgorithm='manual')`

<details><summary>TRACEBACK</summary><p>

```python


---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-9-8715a3aedf65> in <module>
----> 1 deeplabcut.extract_outlier_frames(config_path,vid_path, shuffle=1,outlieralgorithm='manual')
      2 

C:\ProgramData\Anaconda3\envs\dlc1-4\lib\site-packages\deeplabcut\refine_training_dataset\outlier_frames.py in extract_outlier_frames(config, videos, videotype, shuffle, trainingsetindex, outlieralgorithm, comparisonbodyparts, epsilon, p_bound, ARdegree, MAdegree, alpha, extractionalgorithm, automatic, cluster_resizewidth, cluster_color, opencv, savelabeled, destfolder, modelprefix, track_method)
    213                     df,
    214                     savelabeled,
--> 215                     cfg.get("multianimalproject", False),
    216                 )
    217 

C:\ProgramData\Anaconda3\envs\dlc1-4\lib\site-packages\deeplabcut\gui\outlier_frame_extraction_toolbox.py in show(config, video, shuffle, Dataframe, savelabeled, multianimal)
    580     app = wx.App()
    581     frame = MainFrame(
--> 582         None, config, video, shuffle, Dataframe, savelabeled, multianimal
    583     ).Show()
    584     app.MainLoop()

C:\ProgramData\Anaconda3\envs\dlc1-4\lib\site-packages\deeplabcut\gui\outlier_frame_extraction_toolbox.py in __init__(self, parent, config, video, shuffle, Dataframe, savelabeled, multianimal)
    102         vSplitter = wx.SplitterWindow(topSplitter)
    103 
--> 104         self.image_panel = ImagePanel(vSplitter, self.gui_size)
    105         self.choice_panel = ScrollPanel(vSplitter)
    106 

TypeError: __init__() missing 1 required positional argument: 'gui_size'

```
</p></details>

**Additional context**
2.1.10.4 fails to extract outlier frames, when older versions (2.1.10.2) are used on the same analyzed video, 'no analyzed video' is printed. Changing the analysis file names fixes this issue.

**Comment by AlexEMG** [comment]
Thanks for raising this issue! This was indeed introduced in: https://github.com/DeepLabCut/DeepLabCut/pull/1195

But we rolled-back this ResNet_50 naming convention to version to pre-2.1.10*, when this change was introduced: https://github.com/DeepLabCut/DeepLabCut/releases/tag/v2.1.10

This name change was accidentally introduced when adding the EfficientNets in January and caused videos analyzed with ResNets to be reanalyzed as the `DLCsccorername` changed. This is a fix for backwards compatibility, but of course all new projects from January '21 - now suffer the same problem... 

One can of course write a script to re-name the output files (as you also point out) & or simply re-run DLC.

We are really sorry for the inconvenience!
