### ISSUE TITLE
cropimagesandlabels RuntimeError: OrderedDict mutated during iteration

### ISSUE THREAD

**Issue by alexcwsmith** [DeepLabCut/DeepLabCut#1205]
**Describe the bug**

Since updating to be current with this repo, dlc.cropimagesandlabels results in RuntimeError: OrderedDict mutated during iteration.

The config.yaml file is not updated appropriately with cropped videos / video_sets_original.

**Desktop (please complete the following information about your system):**
 - OS: Ubuntu 18.04
 - DeepLabCut Version: 2.1.10.4 (current with GitHub repo)
 - DeepLabCut mode: Single-animal tracking
 - No browser.

**To Reproduce**
Steps to reproduce the behavior, i.e.:
1. Label data.
2. dlc.cropimagesandlabels(path_config_file, numcrops=10, size=(800,400), userfeedback=False)

setting excludealreadycropped=True does not have any impact here, same error occurs.

<details><summary>TRACEBACK</summary><p>

```python

  File "<ipython-input-3-4f0b621448c4>", line 1, in <module>
    dlc.cropimagesandlabels(path_config_file, numcrops=10, size=(800,400), userfeedback=False, excludealreadycropped=True)

  File "/d1/studies/DeepLabCut_Forked/DeepLabCut/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 308, in cropimagesandlabels
    for video in videos:

  File "/home/smith/anaconda3/envs/ma-dlc/lib/python3.7/site-packages/ruamel/yaml/comments.py", line 822, in __iter__
    for x in ordereddict.__iter__(self):

RuntimeError: OrderedDict mutated during iteration

 ```
</p></details></summary>

**Expected behavior**
Images and labels should be cropped for all videos and config.yaml should be updated.

**Comment by arjunt19** [comment]
Hi, I'm getting the same error, how did you fix it?

**Comment by alexcwsmith** [comment]
It was fixed in https://github.com/DeepLabCut/DeepLabCut/commit/e4e1f0084ac544f64b2f9975e82c41ffe2fd7656, upgrade to the latest version via pip
