### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by ArH-Terra** [DeepLabCut/DeepLabCut#1207]
Dear all,
I just had DLC installed yesterday.
I just cannot use the labeling toolbox.
I enter:

> deeplabcut.label_frames(path_config_file)

and when I press the "load frames" button and selected the folder, the GUI just kept blank, these jumps out

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> D:\software\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\gui\labeling_toolbox.py in browseDir(self, event)
>     652         img_name = Path(self.img).name
>     653         self.norm, self.colorIndex = self.image_panel.getColorIndices(
> --> 654             self.img, self.bodyparts
>     655         )
>     656
> 
> D:\software\anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\gui\labeling_toolbox.py in getColorIndices(self, img, bodyparts)
>     196         im = cv2.imread(img)
>     197         norm = mcolors.Normalize(vmin=0, vmax=np.max(im))
> --> 198         ticks = np.linspace(0, np.max(im), len(bodyparts))[::-1]
>     199         return norm, ticks
>     200
> 
> <__array_function__ internals> in linspace(*args, **kwargs)
> 
> D:\software\anaconda3\envs\DLC-CPU\lib\site-packages\numpy\core\function_base.py in linspace(start, stop, num, endpoint, retstep, dtype, axis)
>     134     # and make sure one can use variables that have an __array_interface__, gh-6634
>     135     start = asanyarray(start) * 1.0
> --> 136     stop  = asanyarray(stop)  * 1.0
>     137
>     138     dt = result_type(start, stop, float(num))
> 
> TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

I am not that familiar with DLC or the system, can somebody teach me how to fix this? (kindly step by step)
I am using Windows 10, anaconda3, and installed DLC-CPU version just as the DLC webpage recommended.
Thanks!

**Comment by ArH-Terra** [comment]
Here is my configuration file. I think the bug should be on the configuration...
[config.yaml.txt](https://github.com/DeepLabCut/DeepLabCut/files/6399745/config.yaml.txt)

**Comment by MMathisLab** [comment]
HI, please drop ` - point` in skeleton; the skeleton must connect two points. 
```python
    # Plotting configuration
skeleton:
- point
```

**Comment by ArH-Terra** [comment]
Hi,

Thank you for this urgent reply!

I am so sorry that it is not working. 
I tried as you recommended, but got the same error.
I also tried to add another point, like 

> - point1
> - point2

but still not working...

Would you think of other issues?

Thanks,

**Comment by AlexEMG** [comment]
Sorry for the confusion. There are two ways in which you can define the skeleton:

Method 1:
```
skeleton:
- - point1
  - point2
```

Method 2:
```
skeleton: [["point1", "point2"]]
```

For Method 2, if you have more items you just expand the list (of pairs):
```
skeleton: [['Hand', 'Finger1'], ['Joystick1', 'Joystick2']]
```

**Comment by ArH-Terra** [comment]
Also when I load DLC in the ipython

> import deeplabcut

There are some warnings. I wonder if they are relevant.

> D:\software\anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint8 = np.dtype([("qint8", np.int8, 1)])
> D:\software\anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
> D:\software\anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint16 = np.dtype([("qint16", np.int16, 1)])
> D:\software\anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
> D:\software\anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint32 = np.dtype([("qint32", np.int32, 1)])
> D:\software\anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   np_resource = np.dtype([("resource", np.ubyte, 1)])

**Comment by ArH-Terra** [comment]
I somewhat make things work, by deleting the folder and rebuild the DLC project.
The method given above is certainly not the key, but thanks for the urgent reply anyway!
I am now thinking that there might be some restriction on the video name, like I named my video "trial_1_labeled.avi", and the "_labeled" seems to forbid me from doing anything else.
My great thanks to DLC developers.
