### ISSUE TITLE
Offset tracklets vs. raw video in refinement GUI

### ISSUE THREAD

**Issue by Idavr** [DeepLabCut/DeepLabCut#1216]
OS: Windows 10
DeepLabCut Version: 2.2rc1
Anaconda env

**Describe the problem**

I was able to successfully train a model on multiple videos and also created a labeled video that looked really good (I am using the GUI for this entire process so far), but when getting to the refine tracklets stage I first see the message in the terminal that data and video length does not match, which results in off-set tracklets in the GUI:

Screenshots

![image](https://user-images.githubusercontent.com/47774575/117105495-6eb87900-ad7e-11eb-85e1-194765277d3a.png)

From what I have understood the data from the tracklets is what will be used for further analysis (plotting trajectories, occupancy maps, etc.) instead of the labeled video (which is correct) so this is the reason for me digging into this. The identity of the animals is preserved and the labels are quite consistent in the labeled video as well, it is simply the off-set of the tracklets in the screenshot here I am worried about. Is this a systematic skew I can adjust in some way to get the accurate positional data matched to the correct time points?

Thank you for all your work on this and for helping out with questions like this.

**Comment by MMathisLab** [comment]
HI @ldavr "I first see the message in the terminal that data and video length does not match, which results in off-set tracklets in the GUI:" --> could you please triple check you load the correct video, otherwise this will occur, namely it should be the same raw video that you pass for video_analysis :).

**Comment by Idavr** [comment]
Hi @MMathisLab . Triple checked twice right now just to be sure, and it is the same raw video that I load with the pickle-file for the model chosen for analysis (ellipse).

**Comment by MMathisLab** [comment]
thanks for checking; can you confirm what these values are?, i.e. which pickle file you are loading (and then confirm you click "step 1" before you launch optional refinement? 

![Screen Shot 2021-05-05 at 2 46 23 PM](https://user-images.githubusercontent.com/28102185/117144206-f4095100-adb1-11eb-8cf0-62deffd58310.png)

**Comment by Idavr** [comment]
Absolutely. Here are the values:

![image](https://user-images.githubusercontent.com/47774575/117151438-5dd92900-adb9-11eb-9551-3302e7e81203.png)

And confirmed that Step 1: Create tracks was clicked before Refinement:

![image](https://user-images.githubusercontent.com/47774575/117151526-777a7080-adb9-11eb-9a08-87b44cc54433.png)

**Comment by MMathisLab** [comment]
Okay great, that looks correct ... 

just to confirm, as it's an older project; you first re-trained a new shuffle within 2.2rc1 (i.e. shuffle 2 I gather)?

and, sorry, just to be extra sure, you have these files for this (your) video?
![Screen Shot 2021-05-05 at 3 55 39 PM](https://user-images.githubusercontent.com/28102185/117152569-6e3dd380-adba-11eb-81dd-79582aa47108.png)

**Comment by Idavr** [comment]
It is very good that you are extra sure and are double confirming, these details are typical to be the reason for issues like this :) 

Correct, it was retrained for 60 000 iterations (shuffle 2, as you correctly gathered) using the GUI.

Indeed, these are all the files connected to this video:

![image](https://user-images.githubusercontent.com/47774575/117153501-5450c080-adbb-11eb-93c7-d6cddf4cb09a.png)

**Comment by jeylau** [comment]
@Idavr, if you create a labeled video from the *el.h5 file, do you observed the offset as well? Another question: do both animals disappear at the beginning or end of the video?

**Comment by Idavr** [comment]
@jeylau , if I try the Refine Tracklet step with the *el.h5 file I get this error message:

![image](https://user-images.githubusercontent.com/47774575/117162106-c8429700-adc2-11eb-9290-d139714628cb.png)

An to your second question: No they do not, the video starts playing with them present in the very first frame and the video stops with them also present. There is no frames where either of them disappear at any point in time.

**Comment by Idavr** [comment]
@MMathisLab and @jeylau Ah, my bad. Yes, I tried this as well before and tried again now and do not see the same offset. The video looks perfect and no error message in the terminal either.

**Comment by jeylau** [comment]
Sweet!! This has to be a bug specific to the refinement window then, I'll have a look 😊

**Comment by MMathisLab** [comment]
okay great; bug isolated - thanks @ldavr :) hope it looks nice ;)

**Comment by Idavr** [comment]
Awesome, thank you so much @jeylau and @MMathisLab ! Good to know it seems everything is then in order and I can move forward using the data as intended asap! Appreciate the time, and it does indeed look very nice ;)

**Comment by jeylau** [comment]
I cannot replicate the issue 😕 I propose to close the issue for now since your labeled video looks great, but feel free to reopen it if you face the problem again.

**Comment by Idavr** [comment]
Actually, I think I have found the reason for this but I am uncertain of why it has happened. The videos I tested this on are analyzed by DLC as if they were 50 fps recordings, but they are recorded at 30 fps. I do not understand why DLC reads out and analyzes it according to a 50 fps...? The later videos I just now ran with the terminal telling me "recorded with 30 fps" the tracklets are correct. Do you know why DLC would say that a video was recorded in 50 fps when it was not?

**Comment by Idavr** [comment]
I think I actually found the issue myself, as it seems to have been human error. The files had been compressed into the wrong fps, so the analysis was based on a different frame rate than the video itself actually was running at, which would explain the offset of the tracklets (analysis based) overlaid on the video itself. I am very sorry for getting you to go through all this work, but I do appreciate the assistance and double-checking that all the settings were correct!

**Comment by jeylau** [comment]
You're welcome! Glad we figured out what's wrong and to know you're happy with the results!
