### ISSUE TITLE
How to Deactivate user-feedback in "deeplabcut.extract_outlier_frames(config_path, videos)"

### ISSUE THREAD

**Issue by Andrianarivelo** [DeepLabCut/DeepLabCut#1217]
Hi everyone, 
Thanks for this community and amazing tool ! :)

Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: [Ubuntu 20.04]
DeepLabCut Version: [e.g. 2.2] (2.1.10)
Anaconda env used:

**Describe the problem**

I just wanted to ask how to deactivate the user-feedback in the function "deeplabcut.extract_outlier_frames(config_path, videos)". I just want the program to extract outlier frames without asking for my consent for each of my 68 videos.

Please place code inside this:

deeplabcut.extract_outlier_frames(config_path, videos)

[Method  jump  found  663  putative outlier frames.
Do you want to proceed with extracting  2  of those?
If this list is very large, perhaps consider changing the parameters (start, stop, p_bound, comparisonbodyparts) or use a different method.
yes/noyes
Frames from video 210122_f84_2021.03.23_000_locomotionTriggerSIAndMotor60sec_001-002_raw_behavior  already extracted (more will be added)!
Loading video...
Duration of video [s]:  150.0 , recorded @  80.0 fps!
Overall # of frames:  12000 with (cropped) frame dimensions: 
Kmeans-quantization based extracting of frames from 0.0  seconds to 150.0  seconds.
Extracting and downsampling... 663  frames from the video.
663it [00:14, 45.72it/s]
Kmeans clustering ... (this might take a while)
Let's select frames indices: [5051, 7408]
New video was added to the project! Use the function 'extract_frames' to select frames for labeling.
The outlier frames are extracted. They are stored in the subdirectory labeled-data\210122_f84_2021.03.23_000_locomotionTriggerSIAndMotor60sec_001-002_raw_behavior.
Once you extracted frames for all videos, use 'refine_labels' to manually correct the labels.
Method  jump  found  187  putative outlier frames.
Do you want to proceed with extracting  2  of those?
If this list is very large, perhaps consider changing the parameters (start, stop, p_bound, comparisonbodyparts) or use a different method.
yes/noyes
![user feedback](https://user-images.githubusercontent.com/70333713/117261741-cb846400-ae50-11eb-97c4-304952131583.png)
![user feedback](https://user-images.githubusercontent.com/70333713/117261805-db03ad00-ae50-11eb-968e-b150defe88c6.png)
]

</p></details>

**How to Reproduce the problem**

**Screenshots**

**Additional context**

**Comment by jeylau** [comment]
Hey! Pass `automatic=True` to the function. 😊

**Comment by Andrianarivelo** [comment]
Hey ! I will try that ! Thanks :D
