### ISSUE TITLE
Pythonw using python 2.7 instead of python 3.

### ISSUE THREAD

**Issue by baudyboy** [DeepLabCut/DeepLabCut#1218]
Hi, I have some issues trying to install deeplabcut on my macbook. I am new to using Anaconda environments and never used deeplabcut before or python.

**Operating system**  **DeepLabCut version**

OS: macOS Catalina version 10.15.7
DeepLabCut Version: not installed yet
Anaconda env used: anaconda 3.

**Description of the problem**

I have installed DLC-CPU.yaml in the Anaconda 3 environment following the tutorial detailed here https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/installation.md. I entered the environment and run pythonw to import deeplabcut. I got a message error: ImportError: No module named deeplabcut (see below)

**Terminal output with pythonw:**

>(base) stal-lt04:~ sbaudouin$ conda activate DLC-CPU
>(DLC-CPU) stal-lt04:~ sbaudouin$ pythonw

>WARNING: Python 2.7 is not recommended. 
>This version is included in macOS for compatibility with legacy software. 
>Future versions of macOS will not include Python 2.7. 
>Instead, it is recommended that you transition to using 'python3' from within >Terminal.

>Python 2.7.16 (default, Jun  5 2020, 22:59:21) 
>[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) >(-macos10.15-objc- on darwin
>Type "help", "copyright", "credits" or "license" for more information.
>>> import deeplabcut
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named deeplabcut
>>> 

I tried the following command to identify the path for pythonw:

>(base) stal-lt04:~ sbaudouin$ which pythonw
>/Users/sbaudouin/opt/anaconda3/bin/pythonw
>(base) stal-lt04:~ sbaudouin$ 

I assume that the path should be correct at it uses the anaconda 3 environment but somehow the system is using python 2.7 and not python 3.

I wanted to check which version of python would be triggered if I type python instead of pythonw in the DLC-CPU environment. I was also curious to see if the import/launch of deeplabcut would work and it does not (unsurprisingly). Here is what I got:

**Terminal output with python:**

>(base) stal-lt04:~ sbaudouin$ conda activate DLC-CPU
>(DLC-CPU) stal-lt04:~ sbaudouin$ python
>Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 15:59:12) 
>[Clang 11.0.1 ] on darwin
>Type "help", "copyright", "credits" or "license" for more information.
>>> import deeplabcut
>>> deeplabcut.launch_dlc()
This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.
(DLC-CPU) stal-lt04:~ sbaudouin$ 

I also tried the which python command and here is what I have:
>(base) stal-lt04:~ sbaudouin$ which python
>/Users/sbaudouin/opt/anaconda3/bin/python

</p></details>

I have tried uninstall/reinstall but the problem persists.

I believe that my issue is related to launching the wrong version of python when using pythonw command. As I understand, python 3 should be built in the anaconda 3 environment. I do not know how to address this problem further, so if you have some suggestions I would be very happy to read them.

Thanks in advance
Stéphane

**Comment by jeylau** [comment]
You ran `which python` outside of your conda environment; activate it first, and the command will correctly point to python 3.7.10. You do not need pythonw though, `python` or `ipython` alone is fine on Mac. Note that if you want to run a headless version of deeplabcut, the DLC-CPU-LITE environment is probably what you'll want 😊

**Comment by baudyboy** [comment]
Thanks for the very quick reply! Unfortunately using the DLC-CPU-LITE environment does not solve the issue.

I also checked and, in the conda environment, pythonw points to a different path than python, see the terminal output below. I find suspicious that pythonw does not point to the anaconda environment.

***Terminal output with python:***

>(base) stal-lt04:~ sbaudouin$ conda activate DLC-CPU
>(DLC-CPU) stal-lt04:~ sbaudouin$ which pythonw
>/usr/bin/pythonw
>(DLC-CPU) stal-lt04:~ sbaudouin$ which python
>/Users/sbaudouin/opt/anaconda3/envs/DLC-CPU/bin/python
>(DLC-CPU) stal-lt04:~ sbaudouin$ conda deactivate

I also check in the DLC-CPU-LITE environment and it is the same:

***Terminal output with python:***
>(base) stal-lt04:~ sbaudouin$ conda activate DLC-CPU-LITE
>(DLC-CPU-LITE) stal-lt04:~ sbaudouin$ which pythonw
>/usr/bin/pythonw
>(DLC-CPU-LITE) stal-lt04:~ sbaudouin$ which python
>/Users/sbaudouin/opt/anaconda3/envs/DLC-CPU-LITE/bin/python

If I try to load the GUI with pythonw the error message is:
>(DLC-CPU) stal-lt04:~ sbaudouin$ pythonw -m deeplabcut
>/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No >module named deeplabcut

If I try to run it with python the error message is (I know python should not be used when working with Mac but I still gave it a try):
>(DLC-CPU) stal-lt04:~ sbaudouin$ python -m deeplabcut
>Starting GUI...
>This program needs access to the screen. Please run with a
>Framework build of python, and only when you are logged in
>on the main display of your Mac.

Doing the same with DLC-CPU-LITE gives the exact same result. So I am a bit stuck

**Comment by jeylau** [comment]
There are several things you could try:
- deactivate then reactivate the environment
- try with pythonw3
- run `hash -r` to reset the cache

**Comment by baudyboy** [comment]
Thanks Jeylau for the feedback, unfortunately it keeps on not working. 

I activated/deactivated and also uninstalled/installed everything but nothing worked. 

I tried to run the test of the installation: https://www.youtube.com/watch?v=IOWtKn3l33s.
It worked with python for the import of DLC but it blocks at the same stage with the following error message:
>This program needs access to the screen. Please run with a
>Framework build of python, and only when you are logged in
>on the main display of your Mac.

With pythonw I also have the same message error as before:
>(DLC-CPU) stal-lt04:examples sbaudouin$ pythonw testscript.py
>Traceback (most recent call last):
> File "testscript.py", line 16, in <module>
>    import deeplabcut
>ImportError: No module named deeplabcut

Pythonw3 does not work for me, here is the output:
>(DLC-CPU) stal-lt04:examples sbaudouin$ pythonw3 testscript.py
>-bash: pythonw3: command not found

I did try hash -r several time in and out of the conda environment but it does not change anything.

I found a description of a similar problem in a stackoverflow: https://stackoverflow.com/questions/64589937/mac-pythonw-gui-on-catalina-os-anaconda-not-working-python3.

It does look very similar to my issue but I am a bit lost when it comes to implement the solution. I do not exactly how to implement the solution and at what stage. Do you think it is a potential solution? If so would you be able to provide a bit more guidance on how to implement the solution?

Thanks anyway for the support, I greatly appreciate.

**Comment by baudyboy** [comment]
I think I solved it, at least I have the GUI!

The way I solved it was the following: 
In short, use command
`conda install python.app`
in the DLC-CPU environment. 

To confirm it did the work I then use command `which pythonw` in the DLC-CPU environment. 
I got the expect terminal output:
>(DLC-CPU) stal-lt04:~ sbaudouin$ which pythonw
>/Users/sbaudouin/opt/anaconda3/envs/DLC-CPU/bin/pythonw

Note that I tried to run the test of the installation described in the youtube video but it failed. I do not know if I should be concerned.
But now I have the GUI and it looks promising.

**Comment by JeffreyWBrown** [comment]
@baudyboy I just wanted to thank you for starting this thread and for the solution you offered in your last post: I was having the exact same issue with getting DLC to work on my Mac and spent days trying to circumvent this problem. Like you, I wasn't able to get testscript.py to complete its running, but I'm happy to at least be able to access the GUI at this point and start testing it with my data. My thanks again, and good luck with whatever you may be using DLC for!

**Comment by backyardbiomech** [comment]
I can confirm this issue and the fix (also seen in the forums).
Even with a fully updated conda base, creating a new env on mac with the DLC-CPU.yaml no longer installs a new pythonw into the env. However, after creating the env:

1. activate the env with `conda activate DLC-CPU`
2. install pythonw with `conda install python.app`

Allows DLC to run. It might be necessary to add either `python.app` to the config file, or add a note to the installation docs.
