### ISSUE TITLE
Labeling GUI: If you try to zoom before loading an image, there is nothing to zoom (GUI will crash) 

### ISSUE THREAD

**Issue by aleksejs-fomins** [DeepLabCut/DeepLabCut#122]
Running Demo_yourowndata.ipynb with my own videos. When GUI is loaded, but before loading a video, clicking on the PAN or ZOOM buttons causes the error below. Clicking on PAN or ZOOM buttons after the video has loaded has no result at all.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/dlc/.conda/envs/dlc_env/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/labeling_toolbox.py in zoom(self, event)
    131     def zoom(self,event):
    132         self.statusbar.SetStatusText("Zoom")
--> 133         self.toolbar.zoom()
    134 
    135     def home(self,event):

AttributeError: 'MainFrame' object has no attribute 'toolbar'
```

**Comment by MMathisLab** [comment]
please update to the latest repo; you'll have to git clone it, and work from within the repo for now... and see this issue: https://github.com/AlexEMG/DeepLabCut/issues/115#issuecomment-439746813. If this is the labeling GUI, then I just triple checked, in my Jupyter Notebook, and I open the GUI, **load video**, Zoom, pan, and go home, and close it, and re-open it without issue...

**Comment by MMathisLab** [comment]
"When GUI is loaded, but before loading a video, clicking on the PAN or ZOOM buttons causes the error below."

and yes, of course the buttons do not work if there is no image to ZOOM on....
