### ISSUE TITLE
Feature request_Mark labeled video's folder

### ISSUE THREAD

**Issue by Andrianarivelo** [DeepLabCut/DeepLabCut#1221]
**Is your feature request related to a problem? Please describe.**
Hello, 
I'm afraid of this being taken as just a request of a lazy person...But I'm labeling usually between 50 to 260 videos, sometimes more. Once I label one video, I have to search for videos I didn't label yet. My only indication on which folder Isn't labeled yet is the date of modification so during the frame labeling process, I just sort folders by date of modification. This works well for initial frame labeling.

The problem is during the refining label process after video analysis. The machinelabels-iter0.h5 file is inside a folder named after the video,  after labeling, the folder's date of modification doesn't change so I have to check again inside the folders if the files where modified and this takes a very long time when you have to refine label on hundreds of videos or more...

Notice on the screenshots that the folder modification date doesn't actualize after labeling while the file inside does.

**Note also that this bug only happens during label refinement after videos analysis, the folders modification date is changing during initial frame labeling. This bug is specific to refine_labels.**

![which folder did I already labeled](https://user-images.githubusercontent.com/70333713/117431608-baf3ec80-af29-11eb-8eb7-0688aa17efd0.png)
![Oh this file Is already labeled](https://user-images.githubusercontent.com/70333713/117431678-ccd58f80-af29-11eb-9686-4271c423db6c.png)

**Describe the solution you'd like**
It would be really cool if the already labeled folder showed a green mark for instance saying you already labeled the file inside this folder. Or make the labeled file temporary masked so we could find easily the files awaiting labeling.
But correcting the bug so that already labeled folder actualize their modification date would be enough.

**Describe alternatives you've considered**
Take a screenshot of folder list then marking manually those I already labeled

**Additional context**

**Comment by AlexEMG** [comment]
Great suggestion!

**Comment by AlexEMG** [comment]
This will be done in the new GUI... watch out!
