### ISSUE TITLE
tracklet h5 rows truncated when no animals are present at start results in out of sync labeled video

### ISSUE THREAD

**Issue by felixhol** [DeepLabCut/DeepLabCut#1223]
Thanks so much for all the hard work that made DLC2.2rc1 possible - amazing!! Super excited to see the new features. 

**The bug**

I was testing some of the new features on a dataset that I worked on before using 2.2b8. In trying to compare the box and new ellipse tracker I noticed that the .h5 tracklet file gets truncated when animals are not present starting from frame 1. This was not the case before (2.2b8) when empty frames at the start of an experiment would have rows filled with NaNs. As a result, the create videos function creates videos where the labels are 'out of sync' with the actual video. 

**Desktop:**
 - OS: Ubuntu 18.04 GPU
 - DeepLabCut Version 2.2rc1
 - DeepLabCut mode multi animal

**To Reproduce**
Steps to reproduce the behavior, i.e.:
have a video that does not have animals present in the first n frames. Create tracklets (e.g. using ellipse tracker), and create labeled video. If animals are not present (or not detected) in the first 100 frames, the labels will be plotted 100 frames out of phase (too early) with the video. 

**Expected behavior**
pad dataframe with NaN to let row 0 be frame 1, or let video creator read at what frame plotting should start.

**Comment by jeylau** [comment]
Thanks for reporting the issue @felixhol! This will be corrected with #1225 😊

**Comment by felixhol** [comment]
Thanks a lot for the quick fix, @jeylau !!
