### ISSUE TITLE
Minor edit to docs - Clarify CUDA version required

### ISSUE THREAD

**Issue by JLC827** [DeepLabCut/DeepLabCut#1224]
Hi,

Would it be worth making a minor change to the [installation docs](https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/installation.md) to specify that the CUDA version installed should be 10.0, rather than just CUDA 10? This caused some trouble for me when trying to set up GPU support as I had CUDA version 10.2 installed. As GPU support is tricky enough to get working as it is I think it's best to clarify as much as possible. This would also be more in line with [the Tensorflow docs specifying CUDA version compatability](https://www.tensorflow.org/install/source#tested_build_configurations).

**Comment by AlexEMG** [comment]
Yes, maybe we should from the get-go emphasize that the table below matters (https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/installation.md#troubleshooting)

**Comment by MMathisLab** [comment]
Actually 10.1  works, and we will soon support TF2 (see blog)! But I will update thanks

https://github.com/DeepLabCut/DeepLabCut/commit/51017b3ad3f7dfa6ad72b124072bf35873a7a3fb
