### ISSUE TITLE
Error when trying to extract outlier frames, missing 'gui_size' argument

### ISSUE THREAD

**Issue by pamelaosuna** [DeepLabCut/DeepLabCut#1226]
Error when trying to extract outlier frames, missing 'gui_size' argument
-----
I got the following message while trying to extract outlier frames: "__init__() missing 1 required positional argument: 'gui_size".

System: Windows10
DeepLabCut Version: 2.2rc1
DeepLabCut mode: multi-animal tracking

To reproduce this error:

deeplabcut.extract_outlier_frames(config_path, [video_path], outlieralgorithm='manual', track_method = 'box')

<details><summary>TRACEBACK</summary><p>

```python

    102         vSplitter = wx.SplitterWindow(topSplitter)
    103
--> 104         self.image_panel = ImagePanel(vSplitter, self.gui_size)
    105         self.choice_panel = ScrollPanel(vSplitter)
    106

TypeError: __init__() missing 1 required positional argument: 'gui_size'

```
</p></details>

Expected behavior: The GUI should open and I could be able to correct the misdetections.

This problem is solved by changing the line 104 _from self.image_panel = ImagePanel(vSplitter, self.gui_size)_     to 
   _self.image_panel = ImagePanel(vSplitter, config, self.gui_size)_ in the file "deeplabcut/gui/outlier_frame_extraction_toolbox.py"

**Comment by MMathisLab** [comment]
PLease be aware, this is not the GUI that allows you to correct frames; `deeplabcut.extract_outlier_frames(config_path, ['videofile_path'])` is to extract frames, tpyically automatically, not manually. Then you launch the refine GUI with: `deeplabcut.refine_labels(config_path)` 

but I will check the manual outlier extraction GUI for maDLC purposes (we don't have this in the docs as an option, so I am not sure it is supported, but can be address: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/maDLC_UserGuide.md)
