### ISSUE TITLE
Q: importing DLC on macos: not found? (Pythonw)

### ISSUE THREAD

**Issue by JiHyunKu** [DeepLabCut/DeepLabCut#1227]
Thank you for your time looking at this. I attempted to look at some of the forums that had similar issues, and implemented in the terminal. But I seem to still have the issue. Thank you for your time and really appreciate your help!

**Describe the bug**
Hello! I am a Mac user trying to download DeepLabCut. I am trying to import DeepLabCut, but I cannot seem to import the program even though the program is downloaded. Here are some of the things I did to attempt debugging. 

1. The OS I was using was Big Sur. I saw on the document that Mojave was recommended. So I downgraded my OS to Mojave. 
2. I used environment the document provided. When I could not import DeepLabCut, I deleted the environment and redownloaded the environment. But still had the same issue.
3. Realized that python program needed to be in version 3.6.x, I created custom environment with python version 3.6.8 by conda create -n python368 python=3.6.8. Also, did pip install tensorflow==1.15.0, pip install wxpython==4.0.7.post2, and pip install deeplabcut. Everything went fine but when I tried to import DeepLabCut, I couldn't. 

Please provide the minimal required code to reproduce the error and the full output (please edit ONLY the section below that says `PLACE YOUR CODE HERE!!! `.

conda create -n python368 python=3.6.8
Conda activate python368
pip install tensorflow==1.15.0
pip install wxpython==4.0.7.post2
pip install deeplabcut
pythonw
import deeplabcut

**Desktop (please complete the following information about your system):**
 - OS: MacOS Mojave 10.14.6, 13-inch, 2017
 - DeepLabCut Version 2.1.10.4
 - Browser Safari

<details><summary>TRACEBACK</summary><p>

```python

^do not delete the above "<details><summary>TRACEBACK</summary><p>" or the ```python part!

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named deeplabcut

do not delete below this line, leave the blank line and the ```

```
</p></details>

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. (but please post the code output above, not images of code!)

**Additional context**

**Comment by MMathisLab** [comment]
@JiHyunKu I would recommend using the conda file we supply; I use it on my MacOS Catalina just fine!

**Comment by jeylau** [comment]
Is `Conda` with a capital C a typo? But I'd encourage you, like Mackenzie said, to use our conda environments with (for example): `conda env create -f DeepLabCut\conda-environments\DLC-CPU.yaml` and `conda activate DLC-CPU`

**Comment by JiHyunKu** [comment]
> @JiHyunKu I would recommend using the conda file we supply; I use it on my MacOS Catalina just fine! 

Hello! Thank you for your reply. I initially used the conda file that DeepLabCut provided, and I still had the same issue as stated above.

**Comment by JiHyunKu** [comment]
> Is `Conda` with a capital C a typo? But I'd encourage you, like Mackenzie said, to use our conda environments with (for example): `conda env create -f DeepLabCut\conda-environments\DLC-CPU.yaml` and `conda activate DLC-CPU`
> 
>  

Hello! Conda was autocorrected when I typed it here on GitHub. I used lowercase. I used the conda file provided and still got the same error.

**Comment by MMathisLab** [comment]
^ then i suspect your mac is set up "incorrectly;" if you run `ipython, import deeplabcut` then I bet it works. You should change the default such that it will use `pythonw`. You can check with `which python`

**Comment by JiHyunKu** [comment]
> ^ then i suspect your mac is set up "incorrectly;" if you run `ipython, import deeplabcut` then I bet it works. You should change the default such that it will use `pythonw`. You can check with `which python`

Ah I see! I will test this out! I will definitely update if this worked! Thank you

**Comment by JiHyunKu** [comment]
Thank you! It also turns out the framework was the issue. If I download the python.app, it seems to fix my issue.

`conda install python.app` inside the environment

**Comment by JiHyunKu** [comment]
Another question, how do I change the path for pythonw? When I do which pythonw, the path shows usr/bin/pythonw. But for python, the path is /opt/anaconda3/bin/python

**Comment by backyardbiomech** [comment]
Run all of those commands, including the conda install Python.app after activating DLC-CPU  env.
