### ISSUE TITLE
After label frames, h5 file is not created

### ISSUE THREAD

**Issue by kimminji2018** [DeepLabCut/DeepLabCut#1228]
terminal shows error,,

C:\Users\minji\DeepLabCut\test-minji-2021-05-08\labeled-data\secondimage\CollectedData_minji.h5  not found (perhaps not annotated). If training on cropped data, make sure to call `cropimagesandlabels` prior to creating the dataset.
Annotation data was not found by splitting video paths (from config['video_sets']). An alternative route is taken...
The following folders were found: ['C:\\Users\\minji\\DeepLabCut\\test-minji-2021-05-08\\labeled-data\\secondimage']
C:\Users\minji\DeepLabCut\test-minji-2021-05-08\labeled-data\secondimage\CollectedData_minji.h5  not found (perhaps not annotated)
No data was found!

**Comment by MMathisLab** [comment]
@kimminji2018 please fill out the template fully. It is impossible to know what happened otherwise :)

**Comment by jeylau** [comment]
Make sure to hit Save when you're done labeling 😊

**Comment by kimminji2018** [comment]
> 라벨 지정이 완료되면 저장을 누르세요. 😊
Thank you!!! I didn't save after labeling

**Comment by kimminji2018** [comment]
Thank you!!! I didn't save after labeling
