### ISSUE TITLE
Windows only: GUI adjust marker size result in crash

### ISSUE THREAD

**Issue by aleksejs-fomins** [DeepLabCut/DeepLabCut#123]
Clicking the "adjust marker size" tickbox and then moving the slider results in the error below. DeepLabCut version 2.0.0.dev4 downloaded via pip install.

/home/dlc/.conda/envs/dlc_env/lib/python3.6/site-packages/matplotlib/colors.py
TypeError: ufunc 'subtract' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')

**Comment by MMathisLab** [comment]
yes, please update to the latest repo, and see this issue: https://github.com/AlexEMG/DeepLabCut/issues/115#issuecomment-439746813

**Comment by MMathisLab** [comment]
pip install deeplabcut==2.0.0.dev7

**Comment by MMathisLab** [comment]
update: There will be no crash, but the functionally of the GUI is currently limited to NOT clicking adjust labels for Windows users. See issue: #129.
