### ISSUE TITLE
can't see the labels in multiple individual labeling toolbox

### ISSUE THREAD

**Issue by DuanWei-fudan** [DeepLabCut/DeepLabCut#1230]
When I label the multi-animals,I can't see the labels with color

**Comment by DuanWei-fudan** [comment]
I checked the version of deeplabcut ,it is 2.1.10.4, and I have already installed the deeplabcut[gui].

**Comment by jeylau** [comment]
Hey @DuanWei-fudan, can you give us a bit more background? Is any error being printed?

**Comment by DuanWei-fudan** [comment]
I am so sorry for that.I will pay attention next time.Anyway,thank you very much
