### ISSUE TITLE
the number of iterations did not exceed 200,000 in multiple animal project with maDLC

### ISSUE THREAD

**Issue by YukiAsano2501** [DeepLabCut/DeepLabCut#1232]
**Your Operating system and DeepLabCut version**
OS:Windows 10
DeepLabCut Version: deeplabcut.__version__ = 2.2rc1
Anaconda env used: used(DLC_GPU)

**Describe the problem**
I would like to train with maDLC but, the max iteration didn't exceed 200,000 times when I try to launch "deeplabcut.train_network( )" function with "maxiters=500000".  It occurred only when a multi-animal project, and there is no traceback. It seems to be working right. As a result, I realize that the training stopped when "iter = 200000". Is anybody know how to solve this problem?

Please place code inside this:

**Important Codes**
    multi_animal: bool = True
    print("\n----------------create new project-------------------\n")
    config_file_path = deeplabcut.create_new_project(project_name, experimenter, video_path,
                                                     working_directory=working_directory, copy_videos=copy_flag,
                                                     multianimal=multi_animal)

 [abbreviation]

    disp_iter = 100
    save_iter = 5000
    max_iter = 500000

    deeplabcut.train_network(config_file_path,
                             displayiters=disp_iter,
                             saveiters=save_iter,
                             maxiters=max_iter,
                             gputouse=0)

**How to Reproduce the problem**
1. Create a new project (multi animal is True)
2. train_network with maxiters >= 200000
3. Finally, the iteration does not exceed 200000 times.

Thank you!
P.S.
It's first time to submit the report for me. If anything wrong, please tell me!

**Comment by jeylau** [comment]
Hello! The default behavior with maDLC is to take the smallest input between your `maxiters` and 200k. https://github.com/DeepLabCut/DeepLabCut/blob/91a313b5fd260088ec13a611e60ddc6f120c2ff4/deeplabcut/pose_estimation_tensorflow/train_multianimal.py#L210-L212 Note that, as written in the docs https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/maDLC_UserGuide.md#train-the-network, training is much shorter than with single-animal projects (typically 20-100k at most).

**Comment by YukiAsano2501** [comment]
Thank you jeylau!
