### ISSUE TITLE
stitch_tracklets default animal names break create_labeled_video function

### ISSUE THREAD

**Issue by pavelbugneac** [DeepLabCut/DeepLabCut#1236]
Thanks for the amazing work first of all! The new maDLC is quite amazing, more accurate, more network choices. Fantastic work team! I did encounter one challenge when using it, hence this feature request.

**Is your feature request related to a problem? Please describe.**

In the beta version of maDLC, one could name the individuals in the config file as pleased. This would then be used as the individual names in the h5 file and would lead to no issues when creating a labelled video.

In the new version of maDLC, the stitch_tracklets method by default assigns ids as [ind1,ind2,...]. Then when trying to create a labelled video nothing is displayed as the individuals names in the h5 file and config files do not match and thus the list 'individuals' (which comes from individuals = auxfun_multianimal.IntersectionofIndividualsandOnesGivenbyUser(cfg,displayedindividuals)) becomes empty. Thus when slicing the dataframe from the h5 file, this also becomes empty and nothing is plotted on the frames.

**Describe the solution you'd like**
Ideally, by default the stitch_tracklets function should just take the individuals names from the config file. Not sure if this was implemented on purpose this way, but at least for me, it caused some confusion and would be nice if it can be avoided.
If necessary I can make a pull request to ease your workload.

**Describe alternatives you've considered**
Perhaps in the maDLC userguide you could emphasize that if custom names are used (instead of ind_i) then these should also be specified when stitching tracklets.

**Comment by jeylau** [comment]
Hi @pavelbugneac, thanks for the kind words!
When stitching tracklets programmatically, we wanted the procedure to be universal and work independently of a configuration file (hence the dummy animal names). This flexibility allows one, for example, to easily reconstruct a varying number of tracks. As you rightly observe though, you could use it as follows:
```
import deeplabcut

cfg = deeplabcut.utils.read_config('config_path')
deeplabcut.stitch_tracklets(..., animal_names=cfg['individuals'])
```
The above is the default when done via the GUI 😊
I hope that helps!

**Comment by pavelbugneac** [comment]
Thanks for the support @jeylau ! Indeed it helps.

**Comment by jeylau** [comment]
Hey @pavelbugneac, just a quick update: the high level function `deeplabcut.stitch_tracklets` will now receive `config_path` as its first argument, so the desired (and arguably most common) behavior will be the default programmatically too 😊

**Comment by pavelbugneac** [comment]
Thanks again @jeylau!

**Comment by felixhol** [comment]
many thanks for the ```animal_names=cfg['individuals']``` suggestion, super helpful @jeylau ! It works very well in projects where I do not have unique  body parts, yet in projects where I do, I have trouble implementing this suggestion.... Any idea how to adapt this for projects having varying numbers of identical animals in addition to unique body parts (single individual)?

**Comment by jeylau** [comment]
Hey @felixhol, you shouldn't have to worry about that scenario, as the 'unique' individual gets labeled 'single' anyway, consistently with our other functions. The suggestion above should work, otherwise please let me know as that'd be a 🐛. What is important is the number of animal tracks to reconstruct (omitting the single individual, which is not really 'stitched' per se as it is only one unambiguous data sequence), and the number of 'multi' animal names given.

**Comment by ghost** [comment]
Hi @jeylau, I think I am running into this problem as well. I am running v2.3.4 on Colab and each video has a varying number of individuals (ranging from 7-99) + a "single". When I run deeplabcut.analyze_videos(..., auto_track=True) and then deeplabcut.plot_trajectories() I get 99 trajectories (with names as in the config_file) + "single". However, when I specify n_tracks=38 (for example) the names become ind1, ind2, ..., ind38. This then breaks the deeplabcut.plot_trajectories() and deeplabcut.create_labeled_video() which produce the "single" trajectory exclusively. The only way I was able to go about it was to change the config_file to "ind1, ind2, ..., ind99" which outputs the 38 trajectories but now the "single" is blank. I also tried providing animal_names=cfg['individuals'] as suggested above but I think the functions no longer take this argument? Should I open a new issue or is there just something I am doing wrong? Many thanks in advance! And thanks to the whole team for such a great tool!!!
