### ISSUE TITLE
Issue creating and refining tracklets

### ISSUE THREAD

**Issue by rkos29** [DeepLabCut/DeepLabCut#1237]
Thank you for the 2.2rc1 release - it is amazing so far! 

**Your Operating system and DeepLabCut version**
Windows 10
DeepLabCut Version: 2.2rc1
Anaconda env DLC-GPU

**Describe the problem**

I previously trained maDLC 2.2b8 to track the behavior of one animal in an open field. With the upgrade, I labeled some more images and trained a new iteration. Using the GUI, when I try to refine tracklets with the ellipse or skeleton method, I get an error during stitching for the shape of passed values. When I use the box method, it works beautifully, but half way through the video all of the labels on the one mouse switch from being indiv1 to indiv2. This is potentially related to  #1215, although this post does not reference any value errors for the other tracking methods. Since multi-animal is now optimized for 2-14 animals, do you recommend switching to a single animal project? I really appreciate all the work that has gone into this release and your advice on this issue. 

<details>
<summary> Please place code inside this: </summary><p>
<br>
C:\Users\rog8777\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py:634: UserWarning: No optimal solution found. Employing black magic...
  warnings.warn("No optimal solution found. Employing black magic...")
---------------------------------------------------------------------------ValueError                                Traceback (most recent call last)
~\Anaconda3\envs\DLC-GPU\lib\site-packages\pandas\core\internals\managers.py in create_block_manager_from_blocks(blocks, axes)
   1661                 blocks = [
-> 1662                     make_block(values=blocks[0], placement=slice(0, len(axes[0])))
   1663                 ]

~\Anaconda3\envs\DLC-GPU\lib\site-packages\pandas\core\internals\blocks.py in make_block(values, placement, klass, ndim, dtype)
   2713
-> 2714     return klass(values, ndim=ndim, placement=placement)
   2715

~\Anaconda3\envs\DLC-GPU\lib\site-packages\pandas\core\internals\blocks.py in __init__(self, values, placement, ndim)
    129             raise ValueError(
--> 130                 f"Wrong number of items passed {len(self.values)}, "
    131                 f"placement implies {len(self.mgr_locs)}"

ValueError: Wrong number of items passed 39, placement implies 36 

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
~\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\refine_tracklets.py in create_tracks(self, event)
    316             self.datafile,
    317             n_tracks=self.ntracks.GetValue(),
--> 318             animal_names=self.cfg["individuals"],
    319         )
    320

~\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py in stitch_tracklets(pickle_file, n_tracks, min_length, split_tracklets, prestitch_residuals, weight_func, animal_names, output_name)
   1006     stitcher.build_graph(weight_func=weight_func)
   1007     stitcher.stitch()
-> 1008     stitcher.write_tracks(output_name, animal_names)
   1009     return stitcher

~\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py in write_tracks(self, output_name, animal_names)
    838
    839     def write_tracks(self, output_name="", animal_names=None):
--> 840         df = self.format_df(animal_names)
    841         if not output_name:
    842             output_name = self.filename.replace("pickle", "h5")

~\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py in format_df(self, animal_names)
    825         )
    826         inds = range(self._first_frame, self._last_frame + 1)
--> 827         df = pd.DataFrame(data, columns=columns, index=inds)
    828         if self.single is not None:
    829             columns = pd.MultiIndex.from_product(

~\Anaconda3\envs\DLC-GPU\lib\site-packages\pandas\core\frame.py in __init__(self, data, index, columns, dtype, copy)
    495                 mgr = init_dict({data.name: data}, index, columns, dtype=dtype)
    496             else:
--> 497                 mgr = init_ndarray(data, index, columns, dtype=dtype, copy=copy)
    498
    499         # For data is list-like, or Iterable (will consume into list)

~\Anaconda3\envs\DLC-GPU\lib\site-packages\pandas\core\internals\construction.py in init_ndarray(values, index, columns, dtype, copy)
    232         block_values = [values]
    233
--> 234     return create_block_manager_from_blocks(block_values, [columns, index])
    235
    236

~\Anaconda3\envs\DLC-GPU\lib\site-packages\pandas\core\internals\managers.py in create_block_manager_from_blocks(blocks, axes)
   1670         blocks = [getattr(b, "values", b) for b in blocks]
   1671         tot_items = sum(b.shape[0] for b in blocks)
-> 1672         raise construction_error(tot_items, blocks[0].shape[1:], axes, e)
   1673
   1674

ValueError: Shape of passed values is (9457, 39), indices imply (9457, 36)
</p></details>

**Comment by jeylau** [comment]
Hello @rkos29! Single animal track reconstruction now works well with #1219. The fix will be available soon in 2.2rc2😊

**Comment by rkos29** [comment]
Hi @jeylau, thanks so much that's awesome news!
