### ISSUE TITLE
Refine tracklets - batch processing option?

### ISSUE THREAD

**Issue by kylecnewton** [DeepLabCut/DeepLabCut#1238]
Hi, 

I am not sure if this is addressed somewhere in the tutorial and I missed it, but I have 1000s of videos to analyze and would like to have the option of batch processing selecting the video, tracklet data, launching the GUI and filtering tracks. In the refine tracklets tab, it is very tedious (and easy to make a mistake) when I have to manually scroll through all the files in a directory to select the proper files in each drop down menu. Even if the whole processs was automated where it cycles through each video and the associated tracklet data file and then the bx.h5 file to filter it would be soooooo helpful.

thanks - Kyle

**Comment by MMathisLab** [comment]
you should definitely then use the command line / write a simple script to run this. you can look at the testscripts to fully automate this, 

for example, you can make a file called run.py (even in text editor) and the inside:
```python
import deeplabcut
config_path = 'input your full data path'
video_folder = ' full path to folder'

print("Analyzing videos...")
deeplabcut.analyze_videos(config_path, [video_folder], "mp4", robust_nframes=True)
    print("Video analyzed.")

print("Convert detections to tracklets...")
deeplabcut.convert_detections2tracklets(
        config_path, [new_video_path], "mp4", track_method="ellipse"
    )
print("Tracklets created...")

# you should change this to loop over your assoc. pickle files:
pickle_file = os.path.join(
        os.path.dirname(basepath), "tests", "data", "trimouse_tracklets.pickle"
    )

deeplabcut.stitch_tracklets(
        pickle_file,
        n_tracks=3,
        animal_names=cfg["individuals"],
        output_name=os.path.splitext(new_video_path)[0] + scorer + "_el.h5",
    )
```
