### ISSUE TITLE
Juptyer kernel re-start: Cannot activate multiple GUI eventloops

### ISSUE THREAD

**Issue by aleksejs-fomins** [DeepLabCut/DeepLabCut#124]
Running the Demo_yourowndata.ipynb on deeplabcut version 2.0.0.dev4. If I close GUI during marking and reset the kernel of the notebook, running the gui again produces the following error 

```
ERROR:root:Cannot activate multiple GUI eventloops
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-6005a6684cbf> in <module>()
      1 get_ipython().magic('gui wx')
----> 2 deeplabcut.label_frames(path_config_file)

/home/dlc/.conda/envs/dlc_env/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py in label_frames(config)
     91     """
     92     startpath = os.getcwd()
---> 93     wd = Path(config).resolve().parents[0]
     94     os.chdir(str(wd))
     95 

/home/dlc/.conda/envs/dlc_env/lib/python3.6/pathlib.py in __new__(cls, *args, **kwargs)
    999         if cls is Path:
   1000             cls = WindowsPath if os.name == 'nt' else PosixPath
-> 1001         self = cls._from_parts(args, init=False)
   1002         if not self._flavour.is_supported:
   1003             raise NotImplementedError("cannot instantiate %r on your system"

/home/dlc/.conda/envs/dlc_env/lib/python3.6/pathlib.py in _from_parts(cls, args, init)
    654         # right flavour.
    655         self = object.__new__(cls)
--> 656         drv, root, parts = self._parse_args(args)
    657         self._drv = drv
    658         self._root = root

/home/dlc/.conda/envs/dlc_env/lib/python3.6/pathlib.py in _parse_args(cls, args)
    638                 parts += a._parts
    639             else:
--> 640                 a = os.fspath(a)
    641                 if isinstance(a, str):
    642                     # Force-cast str subclasses to str (issue #21127)

TypeError: expected str, bytes or os.PathLike object, not NoneType
```

If, prior to that, I delete the folder produced by create_new_project, and run whole notebook again, I still get the following error, but at least the GUI starts
`ERROR:root:Cannot activate multiple GUI eventloops`

**Comment by MMathisLab** [comment]
make sure you restart, 
![image](https://user-images.githubusercontent.com/28102185/48728061-e96a9980-ec01-11e8-9b71-f6270be15a36.png)

and then be sure your kernel is trusted (click on trusted), 

![image](https://user-images.githubusercontent.com/28102185/48728259-7c0b3880-ec02-11e8-8b59-4ee738cfc9d1.png)

if you have an Env, switch to it in this menu, i.e. click change kernel, and select your env:

![image](https://user-images.githubusercontent.com/28102185/48728200-4cf4c700-ec02-11e8-9538-dbb6e7e0255a.png)

then I don't see this error. (Also, sometimes the GUI pops up behind the Browser, so if it happens, just double check it truly not popping up)

**Comment by hummuscience** [comment]
@MMathisLab I followed your steps from above but the error still persists. Specially on the steps to relabel the frames.

The only thing that seems to help is rebooting the machine...
