### ISSUE TITLE
Unable to create conda environment

### ISSUE THREAD

**Issue by NeelimaValluru** [DeepLabCut/DeepLabCut#1245]
I'm attempting to create a virtual environment based on the DLC-GPU.yaml file provided. However, I'm getting an error that says the environment failed and ResolvePackageNotFound = cudnn.

**Comment by KonradDanielewski** [comment]
Please provide information on what OS you use.

I've only seen this error in case of MacOS which can't run it since even Macs with GPUs use AMD rather than Nvidia.

**Comment by NeelimaValluru** [comment]
I'm on a windows machine with an Nvidia GPU.

**Comment by KonradDanielewski** [comment]
OK, so follow up questions:

Did you install CUDA properly, and what version have you installed? What is your GPU?
Did you run terminal as administrator?

**Comment by NeelimaValluru** [comment]
I was able to get the installation working but now my GUI stops responding when I start training. I get an error that says my loss tensors has an NaN. I'm on an NVIDIA GeForce 3090 GPU. I'm running terminal as an administrator. I have CUDA 10.0.0.

**Comment by KonradDanielewski** [comment]
> I'm on an NVIDIA GeForce 3090 GPU 

That actually explains everything. When using 3000 series GPU you should use deeplabcut-core since they only work on tensorflow 2.X
