### ISSUE TITLE
Add 'allow_growth' features to analyze_videos

### ISSUE THREAD

**Issue by cyf203** [DeepLabCut/DeepLabCut#1246]
Hi, DLC group,

I saw we can choose to enable 'allow_growth' in the 'train_network' function with DLC but not in the analyzed_videos function. 

I wonder if that trivial to include this feature in the 'analyzed_videos' function in the 2.1 or later DLC version. So, it may prevent us from exhausted all GPU memory. 

We are sincerely looking forward to this feature. For now, we have to add some line outside this function to do that.

Thank you very much!

**Comment by cyf203** [comment]
Hi, DLC group,

I saw we can choose to enable 'allow_growth' in the 'train_network' function with DLC but not in the analyzed_videos function. 

I wonder if that trivial to include this feature in the 'analyzed_videos' function in the 2.1 or later DLC version. So, it may prevent us from exhausted all GPU memory. 

We are sincerely looking forward to this feature. For now, we have to add some line outside this function to do that.

Thank you very much!

**Comment by KonradDanielewski** [comment]
I think this shouldn't be that hard, it's probably just adding allow_growth in part of code that creates tensorflow session. But I think better solution is still to preallocate the amount you need rather then slowly allocate memory (just for speed reasons). Do you want to use the GPU for something else when you run inference?

**Comment by AlexEMG** [comment]
Usage:
`deeplabcut.analyze_videos(config_path, [new_video_path], allow_growth=True)`
