### ISSUE TITLE
No steps further than "create training dataset" displayed

### ISSUE THREAD

**Issue by EstherXSD** [DeepLabCut/DeepLabCut#1247]
OS: Ubuntu 18.04.1
DeepLabCut Version: 2.1.8.2
Anaconda env used: GPU

When I want to enter DeepLabCut GUI, i entered the instruction "source activate DLC2""python -m deeplabcut" in the terminal. Something strange happens, no steps further than "create training dataset" displayed. As the figure shows, I'm wondering what's wrong with the project. I didn't do any modificaitons to the initial code.
`Starting GUI...
Gtk-Message: 07:44:04.353: Failed to load module "canberra-gtk-module"

(__main__.py:969398): Gtk-WARNING **: 07:44:17.885: Error loading theme icon 'gtk-edit' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /usr/lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

(__main__.py:969398): Gtk-WARNING **: 07:44:17.914: Error loading theme icon 'gtk-edit' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /usr/lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end
Traceback (most recent call last):
  File "/home/komiyama/anaconda3/envs/DLC2/lib/python3.7/site-packages/deeplabcut/gui/create_new_project.py", line 330, in create_new_project
    page6 = Train_network(self.parent,self.gui_size,self.cfg)
  File "/home/komiyama/anaconda3/envs/DLC2/lib/python3.7/site-packages/deeplabcut/gui/train_network.py", line 89, in __init__
    display_iters = str(pose_cfg['display_iters'])
TypeError: 'NoneType' object is not subscriptable
`
![image](https://user-images.githubusercontent.com/66427267/118365556-d5843080-b5cf-11eb-8b1a-182c836c0c14.png)

**Comment by jeylau** [comment]
Hello @EstherXSD, please update DeepLabCut with pip install -U 'deeplabcut[gui]'; the GUI works fine :)

**Comment by EstherXSD** [comment]
Hi @jeylau , problems still exist after I have updated DeepLabCut with pip install -U 'deeplabcut[gui]'.

`Collecting deeplabcut[gui]
  Using cached deeplabcut-2.1.10.4-py3-none-any.whl (695 kB)
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (56.2.0)
Requirement already satisfied: filterpy in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (1.4.5)
Requirement already satisfied: ipython-genutils in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (0.2.0)
Requirement already satisfied: matplotlib==3.1.3 in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (3.1.3)
Requirement already satisfied: networkx in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (2.5.1)
Requirement already satisfied: tensorpack==0.9.8 in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (0.9.8)
Requirement already satisfied: statsmodels>=0.11 in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (0.12.2)
Requirement already satisfied: imgaug in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (0.4.0)
Requirement already satisfied: intel-openmp in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (2021.2.0)
Requirement already satisfied: ipython in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (7.23.1)
Requirement already satisfied: scikit-image>=0.17 in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (0.18.1)
Requirement already satisfied: opencv-python-headless~=3.4.9.33 in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (3.4.9.33)
Requirement already satisfied: pandas>=1.0.1 in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (1.2.4)
Requirement already satisfied: numpy~=1.17.3 in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (1.17.5)
Requirement already satisfied: numba==0.51.1 in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (0.51.1)
Requirement already satisfied: certifi in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (2020.12.5)
Requirement already satisfied: chardet in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (4.0.0)
Requirement already satisfied: patsy in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (0.5.1)
Requirement already satisfied: six in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (1.16.0)
Requirement already satisfied: moviepy<=1.0.1 in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (1.0.1)
Requirement already satisfied: wheel in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (0.36.2)
Requirement already satisfied: tables in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (3.6.1)
Requirement already satisfied: scikit-learn in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (0.24.2)
Requirement already satisfied: cython in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (0.29.23)
Requirement already satisfied: pyyaml in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (5.4.1)
Requirement already satisfied: scipy>=1.4 in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (1.6.3)
Requirement already satisfied: click in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (8.0.0)
Requirement already satisfied: ruamel.yaml>=0.15.0 in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (0.15.46)
Requirement already satisfied: tqdm in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (4.60.0)
Requirement already satisfied: bayesian-optimization in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (1.2.0)
Requirement already satisfied: python-dateutil in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (2.8.1)
Requirement already satisfied: h5py in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (3.2.1)
Requirement already satisfied: wxpython<4.1 in ./anaconda3/lib/python3.7/site-packages (from deeplabcut[gui]) (4.0.4)
Requirement already satisfied: cycler>=0.10 in ./anaconda3/lib/python3.7/site-packages (from matplotlib==3.1.3->deeplabcut[gui]) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./anaconda3/lib/python3.7/site-packages (from matplotlib==3.1.3->deeplabcut[gui]) (1.3.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./anaconda3/lib/python3.7/site-packages (from matplotlib==3.1.3->deeplabcut[gui]) (2.4.7)
Requirement already satisfied: llvmlite<0.35,>=0.34.0.dev0 in ./anaconda3/lib/python3.7/site-packages (from numba==0.51.1->deeplabcut[gui]) (0.34.0)
Requirement already satisfied: termcolor>=1.1 in ./anaconda3/lib/python3.7/site-packages (from tensorpack==0.9.8->deeplabcut[gui]) (1.1.0)
Requirement already satisfied: msgpack-numpy>=0.4.4.2 in ./anaconda3/lib/python3.7/site-packages (from tensorpack==0.9.8->deeplabcut[gui]) (0.4.7.1)
Requirement already satisfied: pyzmq>=16 in ./anaconda3/lib/python3.7/site-packages (from tensorpack==0.9.8->deeplabcut[gui]) (22.0.3)
Requirement already satisfied: tabulate>=0.7.7 in ./anaconda3/lib/python3.7/site-packages (from tensorpack==0.9.8->deeplabcut[gui]) (0.8.9)
Requirement already satisfied: psutil>=5 in ./anaconda3/lib/python3.7/site-packages (from tensorpack==0.9.8->deeplabcut[gui]) (5.8.0)
Requirement already satisfied: msgpack>=0.5.2 in ./anaconda3/lib/python3.7/site-packages (from tensorpack==0.9.8->deeplabcut[gui]) (1.0.2)
Requirement already satisfied: proglog<=1.0.0 in ./anaconda3/lib/python3.7/site-packages (from moviepy<=1.0.1->deeplabcut[gui]) (0.1.9)
Requirement already satisfied: imageio-ffmpeg>=0.2.0 in ./anaconda3/lib/python3.7/site-packages (from moviepy<=1.0.1->deeplabcut[gui]) (0.4.3)
Requirement already satisfied: decorator<5.0,>=4.0.2 in ./anaconda3/lib/python3.7/site-packages (from moviepy<=1.0.1->deeplabcut[gui]) (4.4.2)
Requirement already satisfied: requests<3.0,>=2.8.1 in ./anaconda3/lib/python3.7/site-packages (from moviepy<=1.0.1->deeplabcut[gui]) (2.25.1)
Requirement already satisfied: imageio<3.0,>=2.5 in ./anaconda3/lib/python3.7/site-packages (from moviepy<=1.0.1->deeplabcut[gui]) (2.9.0)
Requirement already satisfied: pillow in ./anaconda3/lib/python3.7/site-packages (from imageio<3.0,>=2.5->moviepy<=1.0.1->deeplabcut[gui]) (8.2.0)
Requirement already satisfied: pytz>=2017.3 in ./anaconda3/lib/python3.7/site-packages (from pandas>=1.0.1->deeplabcut[gui]) (2021.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./anaconda3/lib/python3.7/site-packages (from requests<3.0,>=2.8.1->moviepy<=1.0.1->deeplabcut[gui]) (1.26.4)
Requirement already satisfied: idna<3,>=2.5 in ./anaconda3/lib/python3.7/site-packages (from requests<3.0,>=2.8.1->moviepy<=1.0.1->deeplabcut[gui]) (2.10)
Requirement already satisfied: tifffile>=2019.7.26 in ./anaconda3/lib/python3.7/site-packages (from scikit-image>=0.17->deeplabcut[gui]) (2021.4.8)
Requirement already satisfied: PyWavelets>=1.1.1 in ./anaconda3/lib/python3.7/site-packages (from scikit-image>=0.17->deeplabcut[gui]) (1.1.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./anaconda3/lib/python3.7/site-packages (from scikit-learn->deeplabcut[gui]) (2.1.0)
Requirement already satisfied: joblib>=0.11 in ./anaconda3/lib/python3.7/site-packages (from scikit-learn->deeplabcut[gui]) (1.0.1)
Requirement already satisfied: cached-property in ./anaconda3/lib/python3.7/site-packages (from h5py->deeplabcut[gui]) (1.5.2)
Requirement already satisfied: Shapely in ./anaconda3/lib/python3.7/site-packages (from imgaug->deeplabcut[gui]) (1.7.1)
Requirement already satisfied: opencv-python in ./anaconda3/lib/python3.7/site-packages (from imgaug->deeplabcut[gui]) (4.5.2.52)
Requirement already satisfied: traitlets>=4.2 in ./anaconda3/lib/python3.7/site-packages (from ipython->deeplabcut[gui]) (5.0.5)
Requirement already satisfied: backcall in ./anaconda3/lib/python3.7/site-packages (from ipython->deeplabcut[gui]) (0.2.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in ./anaconda3/lib/python3.7/site-packages (from ipython->deeplabcut[gui]) (3.0.18)
Requirement already satisfied: pickleshare in ./anaconda3/lib/python3.7/site-packages (from ipython->deeplabcut[gui]) (0.7.5)
Requirement already satisfied: pexpect>4.3 in ./anaconda3/lib/python3.7/site-packages (from ipython->deeplabcut[gui]) (4.8.0)
Requirement already satisfied: matplotlib-inline in ./anaconda3/lib/python3.7/site-packages (from ipython->deeplabcut[gui]) (0.1.2)
Requirement already satisfied: jedi>=0.16 in ./anaconda3/lib/python3.7/site-packages (from ipython->deeplabcut[gui]) (0.18.0)
Requirement already satisfied: pygments in ./anaconda3/lib/python3.7/site-packages (from ipython->deeplabcut[gui]) (2.9.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in ./anaconda3/lib/python3.7/site-packages (from jedi>=0.16->ipython->deeplabcut[gui]) (0.8.2)
Requirement already satisfied: ptyprocess>=0.5 in ./anaconda3/lib/python3.7/site-packages (from pexpect>4.3->ipython->deeplabcut[gui]) (0.7.0)
Requirement already satisfied: wcwidth in ./anaconda3/lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->deeplabcut[gui]) (0.2.5)
Requirement already satisfied: numexpr>=2.6.2 in ./anaconda3/lib/python3.7/site-packages (from tables->deeplabcut[gui]) (2.7.3)
Installing collected packages: deeplabcut
Successfully installed deeplabcut-2.1.10.4
`
Then I entered the instruction "source activate DLC2""python -m deeplabcut" in the terminal.

`Starting GUI...
Gtk-Message: 02:06:29.511: Failed to load module "canberra-gtk-module"

(__main__.py:1002140): Gtk-WARNING **: 02:06:38.735: Error loading theme icon 'gtk-edit' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /usr/lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end

(__main__.py:1002140): Gtk-WARNING **: 02:06:38.763: Error loading theme icon 'gtk-edit' for stock: Unable to load image-loading module: /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /usr/lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end
Traceback (most recent call last):
  File "/home/komiyama/anaconda3/envs/DLC2/lib/python3.7/site-packages/deeplabcut/gui/create_new_project.py", line 330, in create_new_project
    page6 = Train_network(self.parent,self.gui_size,self.cfg)
  File "/home/komiyama/anaconda3/envs/DLC2/lib/python3.7/site-packages/deeplabcut/gui/train_network.py", line 89, in __init__
    display_iters = str(pose_cfg['display_iters'])
TypeError: 'NoneType' object is not subscriptable

** (__main__.py:1002140): CRITICAL **: 02:06:52.293: gail_notebook_real_remove_gtk: assertion 'obj' failed
`

**Comment by EstherXSD** [comment]
Updates:
Now the computer system seems to have some modifications. Here is the latest version:
OS: Ubuntu 20.04.2 LTS
DeepLabCut Version: 2.1.10.4
Anaconda env used: GPU

**Comment by EstherXSD** [comment]
Hi @jeylau , it seems that your suggestions work successfully ! Specifically, it is necessary to pip install after I have activated the environment (source activate DLC2).
