### ISSUE TITLE
CUDA 10.0 with Ubuntu 20.04

### ISSUE THREAD

**Issue by elmi-spektr** [DeepLabCut/DeepLabCut#1249]
Hi,

I am trying to get Deeplabcut 2.2rc1 to work with GPU on Ubuntu 20.04.2 LTS machine. From your installation guide it seems like I need to have CUDA version 10.0 and the problem seems to be that CUDA 10.0 toolkit is not supported for Ubuntu 20.04. See the page here: https://developer.nvidia.com/cuda-10.0-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu

My GPU is the following: GeForce GTX 1070

I have read that you have updated to 20.04 and are able to use CUDA 10.0 and I was wondering how you managed to do that. I used to be able to use my GPU before upgrading to my OS to 20.04.

**Comment by MMathisLab** [comment]
`wget http://developer.download.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.243_418.87.00_linux.run
sudo sh cuda_10.1.243_418.87.00_linux.run`

**Comment by elmi-spektr** [comment]
Thanks for the quick response, but I am unable to install this particular combination of CUDA/NVIDIA driver versions. I'm attaching the cuda and nvidia-installer logs for reference. Driver seems to keep failing to install, as you can see in the cuda-installer.log and the error inside nvidia-installer.log is not really very readable, at least not by me.. Seems like something goes wrong at:
     CONFTEST: is_export_symbol_gpl_refcount_dec_and_test (line 193)

This results in "nvidia kernel module was not created." (line 29241)

Perhaps there is another driver version that I can use?

[cuda-installer.log](https://github.com/DeepLabCut/DeepLabCut/files/6503172/cuda-installer.log)
[nvidia-installer.log](https://github.com/DeepLabCut/DeepLabCut/files/6503170/nvidia-installer.log)

**Comment by MMathisLab** [comment]
@elmi-spektr you should be able to just use the latest; here is how I install 18.04 or 20.04 LTS: https://github.com/DeepLabCut/Docker4DeepLabCut2.0/wiki/Installation-of-NVIDIA-driver-and-CUDA-10

Note, I recommend Dockers for ubuntu anyhow, and this then makes life much easier! ^ see Docker repo
