### ISSUE TITLE
Jupyter Kernel Restarting in maDLC (during training only) winOS

### ISSUE THREAD

**Issue by DuanWei-fudan** [DeepLabCut/DeepLabCut#1258]
windows 10
deeplabcut 2.2rc1
python 3.7.10 in Anaconda 3
 

When I used the Multi-Animal Projects with **jupyter notebook**, it can't start training normally.
I followed the steps in [https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/maDLC_UserGuide.md](url), it can work well until the _create_multianimaltraining_dataset_.But when I started the train, it shutted down.

The details of the problem :
**Kernel Restarting** 
The kernel appears to have died. It will reatart automatically.

I also tested the examples in [https://github.com/DeepLabCut/DeepLabCut/tree/master/examples](url) .
The testscript_multianimal.py can run until the training.

**Comment by KonradDanielewski** [comment]
Could you run the function through terminal to get the actual error and traceback that causes the kernel death? It might be a problem with cudnn/cuda, might be that there is OOM on your GPU which also causes kernel death in jupyter. Hard to say what is causing the issue without seeing an actual error.

**Comment by DuanWei-fudan** [comment]
Yes, I tried it. However it didn't work. I thought it is the unsuitable cudnn/cuda firstly.
But it  worked very well when I used the GPU to train network with deeplabcutcore.

**Comment by KonradDanielewski** [comment]
I'll try to reproduce this today if I'll have time but going through posts on stack some people report that it just doesn't work on jupyter but works either when run from terminal or from .py file... 

When you run it on jupyter does the memory get allocated? Is there anything printed or does it just go straight to kernel restart?

**Comment by KonradDanielewski** [comment]
So, I was able to reproduce this on my laptop with small RTX 2060 and it appears to just OOM without an error message. Interestingly same thing happens in terminal, ipython dies, no error message, goes back to environment. 

I changed the batchsize to 1 and it works so this is probably a solution for you if you do this on a small GPU like the one I tested this on. 

Not sure why there is no error printed. For context it dies after tensorflow device is created. Parameters and "Starting multi-animal training..." never get printed

**Comment by KonradDanielewski** [comment]
> But it worked very well when I used the GPU to train network with deeplabcutcore.

Do you use a 3000 series GPU?

**Comment by DuanWei-fudan** [comment]
Thank you for you trying. I changed the batchsize to 1. But it shut down again.

The terminal of juypter notebook printed like this:
_[I 15:28:41.603 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel ee3b4c0d-889b-4d75-b24b-45a25929b0dc restarted_

I searched the **ee3b4c0d-889b-4d75-b24b-45a25929b0dc**, it contained 

_"shell_port": 64954,
  "iopub_port": 64955,
  "stdin_port": 64956,
  "control_port": 64958,
  "hb_port": 64957,
  "ip": "127.0.0.1",
  "key": "4e7c4797-e0e734ad10ffd1f224f9c51b",
  "transport": "tcp",
  "signature_scheme": "hmac-sha256",
  "kernel_name": ""_

I can't understand what the mean is.

**Comment by DuanWei-fudan** [comment]
> > But it worked very well when I used the GPU to train network with deeplabcutcore.
> 
> Do you use a 3000 series GPU?

Yes. It is just in another environment.

**Comment by DuanWei-fudan** [comment]
I also trained the network with CPU(AMD Ryzen Threadripper 3960X 24-Core).
It worked normally. So It might be a problem with cudnn/cuda.
But I don't know how to solve it.

**Comment by KonradDanielewski** [comment]
Let's clarify. You use deeplabcut==2.2rc1 in your jupyter kernel with RTX 3000? Or do you use deeplabcutcore in jupyter with 3000 GPU?

If it's the former, it won't work and will die, since 2.2rc1 is still on tensorflow 1.

**Comment by DuanWei-fudan** [comment]
You worked well in RTX2060. So how about the detail information ,like the version of CUDA ,deeplabcut and TensorFlow?

**Comment by KonradDanielewski** [comment]
It's simply that deeplabcut 2.2 doesn't support tensorflow 2 for now. And without tensorflow 2 you cannot use 3000 series GPUs because of CUDA compatibility - Ampere architecture is supported from version 11.1 (incompatible with tensorflow 1.X). Simply updating those won't do much because of significant differences between TF 1.X and 2.X (the code of DLC has to be changed in order for this to work)

When reproducing I was using CUDA 10.0, tensorflow 1.15.5 on 2.2rc1

**Comment by DuanWei-fudan** [comment]
Great! I changed my CUDA from 11.2 to 10.0. It worked normally! I can start multi-animal training right now!
Thank you very much!

**Comment by DuanWei-fudan** [comment]
Well, there is another question.
We import deeplabcut to begin the analysis.
I think the first step will connect to GPU, so I add
_tf.__version__
tf.test.gpu_device_name()_

to test if I can use my GPU. It will print _'/device:GPU:0'_ after that. Maybe it cost just seconds.
After changed the version, the speed of is very slow. About minutes?
So just the lower version of CUDA owns a lower speed?

**Comment by KonradDanielewski** [comment]
As I said, lower CUDA version is not compatible (in a way that it cannot utilize new architecture) so even if it will run on the GPU it will not use it properly, i.e. will be slow.

Checking if the GPU is there is also happening when you call `deeplabcut.train_network`, printed just above the parameters when creating tensorflow device.

**Comment by DuanWei-fudan** [comment]
The train will stop in advance. If I set the max numbers of times to 50000, it will stop at about 17000. But the GPU is working.
I changed the batchsize from 1 to 2, it stopped more early.
I found when I call **deeplabcut.train_network**, the jupyter notebook printed a message:
_2021-06-04 17:54:20.457925: W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Internal: Invoking ptxas not supported on Windows
Relying on driver to perform ptx compilation. This message will be only logged once._

Maybe it is also the lower CUDA version? So how can I solve it?
The 11.x is not suitable to **2.2rc1**, and the 10.x is not suitable for the RTX3090.

**Comment by KonradDanielewski** [comment]
The solve is to either modify the code yourself to work with TF2 or wait for official move of the project to TF2.

If your project can be done without using maDLC, then use deeplabcutcore which is on TF2. No other way around it

EDIT: You can also try this solution https://github.com/DeepLabCut/DeepLabCut-core/issues/13#issuecomment-762845356
