### ISSUE TITLE
Problem building Pandas on Windows 7 64-bit (Installation >> perhaps use the conda env.)

### ISSUE THREAD

**Issue by rdabbi** [DeepLabCut/DeepLabCut#126]
**Your Operating system and DeepLabCut version**
Windows 7 64-bit, with an Anaconda Env, & DeepLabCut 2.x.

I am running the command
pip install deeplabcut and I am getting the following error.

  copying pandas\tests\tseries\data\dateoffset_0_15_2.pickle -> build\lib.win-amd64-3.7\pandas\tests\tseries\data
  UPDATING build\lib.win-amd64-3.7\pandas/_version.py
  set build\lib.win-amd64-3.7\pandas/_version.py to '0.20.3'
  running build_ext
  Traceback (most recent call last):
    File "c:\Users\jdabb803\Anaconda3\lib\site-packages\pkg_resources\__init__.p
y", line 354, in get_provider
      module = sys.modules[moduleOrReq]
  KeyError: 'numpy'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "c:\Users\jdabb803\Anaconda3\lib\site-packages\numpy\core\__init__.py",
 line 16, in <module>
      from . import multiarray
  ImportError: DLL load failed: The specified module could not be found.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\jdabb803\AppData\Local\Temp\pip-install-f8atwwvi\pandas\setup
.py", line 729, in <module>
      **setuptools_kwargs)
    File "c:\Users\jdabb803\Anaconda3\lib\site-packages\setuptools\__init__.py",
 line 140, in setup
      return distutils.core.setup(**attrs)
    File "c:\Users\jdabb803\Anaconda3\lib\distutils\core.py", line 148, in setup

      dist.run_commands()
    File "c:\Users\jdabb803\Anaconda3\lib\distutils\dist.py", line 966, in run_c
ommands
      self.run_command(cmd)
    File "c:\Users\jdabb803\Anaconda3\lib\distutils\dist.py", line 985, in run_c
ommand
      cmd_obj.run()
    File "c:\Users\jdabb803\Anaconda3\lib\site-packages\wheel\bdist_wheel.py", l
ine 202, in run
      self.run_command('build')
    File "c:\Users\jdabb803\Anaconda3\lib\distutils\cmd.py", line 313, in run_co
mmand
      self.distribution.run_command(command)
    File "c:\Users\jdabb803\Anaconda3\lib\distutils\dist.py", line 985, in run_c
ommand
      cmd_obj.run()
    File "c:\Users\jdabb803\Anaconda3\lib\distutils\command\build.py", line 135,
 in run
      self.run_command(cmd_name)
    File "c:\Users\jdabb803\Anaconda3\lib\distutils\cmd.py", line 313, in run_co
mmand
      self.distribution.run_command(command)
    File "c:\Users\jdabb803\Anaconda3\lib\distutils\dist.py", line 985, in run_c
ommand
      cmd_obj.run()
    File "c:\Users\jdabb803\Anaconda3\lib\site-packages\Cython\Distutils\old_bui
ld_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "c:\Users\jdabb803\Anaconda3\lib\distutils\command\build_ext.py", line
339, in run
      self.build_extensions()
    File "C:\Users\jdabb803\AppData\Local\Temp\pip-install-f8atwwvi\pandas\setup
.py", line 388, in build_extensions
      build_ext.build_extensions(self)
    File "C:\Users\jdabb803\AppData\Local\Temp\pip-install-f8atwwvi\pandas\setup
.py", line 156, in build_extensions
      numpy_incl = pkg_resources.resource_filename('numpy', 'core/include')
    File "c:\Users\jdabb803\Anaconda3\lib\site-packages\pkg_resources\__init__.p
y", line 1139, in resource_filename
      return get_provider(package_or_requirement).get_resource_filename(
    File "c:\Users\jdabb803\Anaconda3\lib\site-packages\pkg_resources\__init__.p
y", line 356, in get_provider
      __import__(moduleOrReq)
    File "c:\Users\jdabb803\Anaconda3\lib\site-packages\numpy\__init__.py", line
 142, in <module>
      from . import add_newdocs
    File "c:\Users\jdabb803\Anaconda3\lib\site-packages\numpy\add_newdocs.py", l
ine 13, in <module>
      from numpy.lib import add_newdoc
    File "c:\Users\jdabb803\Anaconda3\lib\site-packages\numpy\lib\__init__.py",
line 8, in <module>
      from .type_check import *
    File "c:\Users\jdabb803\Anaconda3\lib\site-packages\numpy\lib\type_check.py"
, line 11, in <module>
      import numpy.core.numeric as _nx
    File "c:\Users\jdabb803\Anaconda3\lib\site-packages\numpy\core\__init__.py",
 line 26, in <module>
      raise ImportError(msg)
  ImportError:
  Importing the multiarray numpy extension module failed.  Most
  likely you are trying to import a failed build of numpy.
  If you're working with a numpy git repo, try `git clean -xdf` (removes all
  files not under version control).  Otherwise reinstall numpy.

  Original error was: DLL load failed: The specified module could not be found.

  ----------------------------------------
  Failed building wheel for pandas
  Running setup.py clean for pandas
  Running setup.py bdist_wheel for easydict ... done
  Stored in directory: C:\Users\jdabb803\AppData\Local\pip\Cache\wheels\9a\88\ec
\085d92753646b0eda1b7df49c7afe51a6ecc496556d3012e2e
Successfully built moviepy easydict
Failed to build pandas
twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
Installing collected packages: numpy, imageio, moviepy, pandas, easydict, ipytho
n, intel-openmp, matplotlib, opencv-python, deeplabcut
  Found existing installation: numpy 1.15.1
    Uninstalling numpy-1.15.1:
      Successfully uninstalled numpy-1.15.1
  Found existing installation: imageio 2.4.1
Cannot uninstall 'imageio'. It is a distutils installed project and thus we cann
ot accurately determine which files belong to it which would lead to only a part
ial uninstall.
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

**Comment by MMathisLab** [comment]
You should post in pandas, https://github.com/pandas-dev/pandas, as this is a package not managed by us.... The error suggests git clean -xdf ... then try pandas and bumpy separately.  We also note that Windows 7 is not tested with deeplabcut (ie Windows 10 is tested).

**Comment by rdabbi** [comment]
I tried this with windows 10 and got the same error. 

I also executed conda install numpy and then re-executed pip install deeplabcut and got the following
    running build_ext
    cythoning pandas\_libs/lib.pyx to pandas\_libs\lib.c
    warning: pandas/_libs/src\util.pxd:6:33: Declarations should not be declared
 inline.
    warning: pandas/_libs/src\util.pxd:7:40: Declarations should not be declared
 inline.
    warning: pandas/_libs/src\util.pxd:9:32: Declarations should not be declared
 inline.
    warning: pandas/_libs/src\util.pxd:10:30: Declarations should not be declare
d inline.
    warning: pandas/_libs/src\util.pxd:11:32: Declarations should not be declare
d inline.
    warning: pandas/_libs/src\util.pxd:12:29: Declarations should not be declare
d inline.
    warning: pandas/_libs/src\util.pxd:13:31: Declarations should not be declare
d inline.
    warning: pandas/_libs/src\util.pxd:14:35: Declarations should not be declare
d inline.
    warning: pandas/_libs/src\util.pxd:15:36: Declarations should not be declare
d inline.
    warning: pandas/_libs/src\util.pxd:16:30: Declarations should not be declare
d inline.
    warning: pandas/_libs/src\util.pxd:17:30: Declarations should not be declare
d inline.
    warning: pandas/_libs/src\util.pxd:18:30: Declarations should not be declare
d inline.
    warning: pandas/_libs/src\util.pxd:19:23: Declarations should not be declare
d inline.
    warning: pandas/_libs/src\util.pxd:20:16: Declarations should not be declare
d inline.
    warning: pandas/_libs/src\util.pxd:21:32: Declarations should not be declare
d inline.
    warning: pandas/_libs/src\util.pxd:22:38: Declarations should not be declare
d inline.
    warning: pandas/_libs/src\util.pxd:25:34: Declarations should not be declare
d inline.
    warning: pandas/_libs/src\inference.pyx:909:23: Declarations should not be d
eclared inline.
    building 'pandas._libs.lib' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual
C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    ----------------------------------------
  Rolling back uninstall of pandas
Command "c:\Users\jdabb803\Anaconda3\python.exe -u -c "import setuptools, tokeni
ze;__file__='C:\\Users\\jdabb803\\AppData\\Local\\Temp\\pip-install-w6wf0wnr\\pa
ndas\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replac
e('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --recor
d C:\Users\jdabb803\AppData\Local\Temp\pip-record-hbfu6_gk\install-record.txt --
single-version-externally-managed --compile" failed with error code 1 in C:\User
s\jdabb803\AppData\Local\Temp\pip-install-w6wf0wnr\pandas\
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

**Comment by rdabbi** [comment]
As per your suggestion, I did a conda install pandas which sucessfilly installed 0.23 version
After that when I did pip install deeplabcut it tries to get 0.20 version of pandas from deeplabcut. This results in the same error as before

Thanks for your help.

PS: I am High School student doing neuroscience research on Zera Fish. So, please bear with me.

Riya

**Comment by AlexEMG** [comment]
Please just use the conda environment for Windows, which we put in https://github.com/AlexEMG/DeepLabCut/tree/master/conda-environments

```
cd conda-environments
conda env create -f dlc-windowsCPU.yaml 
```

Thanks to @imagejan

**Comment by AlexEMG** [comment]
Dear @rdabbi, did you test it this?

**Comment by AlexEMG** [comment]
Closing this, anyway a Pandas problem...
