### ISSUE TITLE
Conversion code fails - does not properly concatenates target folder paths

### ISSUE THREAD

**Issue by mfkeles** [DeepLabCut/DeepLabCut#1262]
I am converting my annotations from windows to unix style to be able add annotations to the project on my macbook pro. I run into an issue when using `deeplabcut.convertannotationdata_fromwindows2unixstyle`. However the function does not find the generate the correct list of folders to loop through the annotations and change the format. 

**Desktop (please complete the following information about your system):**
 - OS: MacOS Catalina
 - DeepLabCut Version: 2.1.10.4
 - DeepLabCut mode: single

**To Reproduce**
Steps to reproduce the behavior, i.e.:
run `deeplabcut.convertannotationdata_fromwindows2unixstyle(config_path,userfeedback=True, win2linux=True)`

<details><summary>TRACEBACK</summary><p>

```python

Do you want to convert the annotationdata in folder: /Users/mehmetkeles/Desktop/DLC_Project_Files/LiquidFoodDLC-Mehmet-2020-03-23/labeled-data/D:\DLC_Sleep\LiquidFood\20200304_Fly2_30FPS_LiquidFood\Fly2-03042020151948-0002 ?
yes/noyes
/Users/mehmetkeles/opt/anaconda3/envs/tDLC/lib/python3.7/site-packages/deeplabcut/utils/conversioncode.py:63: UserWarning: Could not find '/Users/mehmetkeles/Desktop/DLC_Project_Files/LiquidFoodDLC-Mehmet-2020-03-23/labeled-data/D:\DLC_Sleep\LiquidFood\20200304_Fly2_30FPS_LiquidFood\Fly2-03042020151948-0002/CollectedData_Mehmet.h5'. skipping
  warnings.warn(f"Could not find '{fn+'.h5'}'. skipping")




```
</p></details>

**Expected behavior**
the function grabs the config folder combines it with `/labeled data/` but does not split windows paths since os.path.split is run on MacOS. So instead of splitting `D:\DLC_Sleep\LiquidFood\fly2` to just `fly2` it leaves it as is and combines it with the config path + `/labeled_data/`. 

**Additional context**
I am sorry if I am missing something trivial here. I guess I maybe could run the function in windows then move the folder to macos but seemed a little counter intuitive.

**Comment by KonradDanielewski** [comment]
You have wrong path passed in the function: 

`Could not find '/Users/mehmetkeles/Desktop/DLC_Project_Files/LiquidFoodDLC-Mehmet-2020-03-23/labeled-data/D:\DLC_Sleep\LiquidFood\20200304_Fly2_30FPS_LiquidFood\Fly2-03042020151948-0002/CollectedData_Mehmet.h5'`

**Comment by mfkeles** [comment]
Hey @KonradDanielewski  thanks for the response!

Hmm, I actually just pass the config path to the function. So the folder path that it can't find is not the one I pass. Maybe I am missing something but it seems like the [function](https://github.com/DeepLabCut/DeepLabCut/blob/e2c80479212daea55ff0e39a900ef3678783a11b/deeplabcut/utils/conversioncode.py) only asks for the config path.

**Comment by mfkeles** [comment]
It matches my actual Mac path.

**Comment by jeylau** [comment]
Hey @mfkeles, thanks for reporting the bug. This specifically comes from here https://github.com/DeepLabCut/DeepLabCut/blob/156b899ee71fc927f0d595e4eaebf078292c4a5a/deeplabcut/utils/conversioncode.py#L43, where `Path().stem` fails to split a WindowsPath on Unix systems. I'll push a fix soon 😊

**Comment by MMathisLab** [comment]
Thanks! If anyone else has the inverse request i.e., labeled on windows but want to train, etc on linux, note that when you create a training dataset you simply can pass:
```python
windows2linux: bool.
    The annotation files contain path formatted according to your operating system. If you label on windows
    but train & evaluate on a unix system (e.g. ubuntu, colab, Mac) set this variable to True to convert the paths.
``
