### ISSUE TITLE
video_sets_orginal gets overwritten when cropping new videos while excluding already cropped videos

### ISSUE THREAD

**Issue by backyardbiomech** [DeepLabCut/DeepLabCut#1269]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). 
Please fill out the template completely, including the full "TRACEBACK" and input code that you ran to hit this error.

**Describe the bug**

After refining labels on an existing model, merging, and running `cropimagesandlabels` on the new labeled images with `excludealreadycropped=True`, the `video_sets_original` entries in `config` are overwritten to show **only** the newly cropped videos.

**Desktop (please complete the following information about your system):**
 - OS: Windows10, jupyter
 - DeepLabCut Version: 2.2rc1
 - DeepLabCut mode: maDLC
 - chrome

**To Reproduce**
Steps to reproduce the behavior, i.e.:
1. extract outliers on videos not already in maDLC model that was based on cropped images
2. merge
3. run: 
        ```
        dlc.cropimagesandlabels(config,
                       numcrops=10,
                       size=(256,256),
                       userfeedback=False,
                       cropdata=True,
                       excludealreadycropped=True,
                       updatevideoentries=True,
                       )
         ```

NOTE that this only occurs when `excludealreadycropped=True`. When `False`, all videos are recropped, and `video_sets_original` is as it should be.

**Expected behavior**
Newly refined videos should be cropped and appended to `video_sets_original` rather than replacing all entries in `video_sets_original`. This would allow for re-cropping to different sizes, or other manipulations to all existing videos.

**Comment by jeylau** [comment]
Hey @backyardbiomech, thanks for reporting that bug, I'll fix it! Meanwhile, are you certain `excludealreadycropped=False` does recrop all videos? It should normally ignore those from which no new (uncropped) frames where extracted 🤔

**Comment by backyardbiomech** [comment]
@jeylau , actually, I'm not sure. I thought it did with a test run previously, but I wasn't actually watching for that. I just happened to run it again, and it did not re-crop everything (I only realized this time because I wanted it to re-crop everything because I was trying a new crop size. I got it to re-crop by deleting the cropped folders and moving video_sets_original entries to video_sets). However, it was that combination of exclude and update that caused the problem.

@MMathisLab , I have not tried with `updatevideoentries=False`. It's training right now, so I don't want to mess with it, but I can test later if you need.
