### ISSUE TITLE
I don't know what to do

### ISSUE THREAD

**Issue by juholavonen** [DeepLabCut/DeepLabCut#1276]
MacOS 11.2.3
DeepLabCut Version: 2.2
Anaconda3

The problem is that I'm trying install DLC to mac MacBook. I got Anaconda installed and tested and thats work. Then I tried install DLC but I got stuck after "conda activate DLC-CPU" and "pythonw" and after that this message show up: 

(base) $ conda activate DLC-CPU
(DLC-CPU) $ pythonw

WARNING: Python 2.7 is not recommended. 
This version is included in macOS for compatibility with legacy software. 
Future versions of macOS will not include Python 2.7. 
Instead, it is recommended that you transition to using 'python3' from within Terminal.

Python 2.7.16 (default, Dec 21 2020, 23:00:36) 
[GCC Apple LLVM 12.0.0 (clang-1200.0.30.4) [+internal-os, ptrauth-isa=sign+stri on darwin
Type "help", "copyright", "credits" or "license" for more information.

But when I test my "python --version" --> Python 3.7.10

I'm new with python. Can someone help me?

**Comment by MMathisLab** [comment]
Hi @juholavonen welcome to the community! We ask that help-style questions please get posted on Image Forum (and searching there is a wealth of good info!) https://github.com/DeepLabCut/DeepLabCut#community-support-developers--help 

>  `python --version`

you will need to check `pythonw --version`

to note, you can re-configure your mac to use python3 as default (vs. 2.7, which indeed is not supported by deeplabcut). Posted without endorsement: https://dev.to/jqn/learn-to-setup-python-3-as-a-default-on-your-mac-1bd6

**Comment by backyardbiomech** [comment]
On some macs, pythonw is not properly installed when the env is created, so calling pythonw finds the next one on the PATH (at `/usr/bin/pythonw`), which is from the OS python installation.

As confirmed [in the forum](https://forum.image.sc/t/importerror-in-osx/52907/15), activating the env and installing pythonw fixes the problem:

```
conda activate DLC-CPU
conda install python.app
```
