### ISSUE TITLE
error running testscript.py (FileNotFound)

### ISSUE THREAD

**Issue by tachposa** [DeepLabCut/DeepLabCut#1277]
Please complete the following information about your system:

OS: MacOS Mojave
DeepLabCut Version: 2.2rc1
Anaconda env used: Anaconda3 w/ wxpython 4.0.7

**Describe the problem**

Hi! I followed every step to install and run testscript.py, but I have been having a lot of errors shown in testscript. This one says that the file is not found when looking for a video which might suggest an import error? Can anyone help me out with this?

Please place code inside this:

<details><summary>FileNotFoundError: File /Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/labeled-data/reachingvideo1short/machinelabels-iter0.h5 does not exist</summary><p>

(DLC-CPU) pondposa:examples pondposa$ pythonw testscript.py
/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Imported DLC!
On Windows/OSX tensorpack is not tested by default.
CREATING PROJECT
Created "/Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/videos"
Created "/Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/labeled-data"
Created "/Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/training-datasets"
Created "/Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/dlc-models"
Copying the videos
/Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/videos/reachingvideo1.avi
Generated "/Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/config.yaml"

A new project with name TEST-Alex-2021-05-26 is created at /Users/pondposa/Downloads/DeepLabCut/examples and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
EXTRACTING FRAMES
Config file read successfully.
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 8.53  seconds.
Extracting and downsampling... 256  frames from the video.
256it [00:02, 100.42it/s]
Kmeans clustering ... (this might take a while)
Frames were successfully extracted, for the videos of interest.

You can now label the frames using the function 'label_frames' (if you extracted enough frames for all videos).
CREATING-SOME LABELS FOR THE FRAMES
Plot labels...
Creating images with labels by Alex.
100%|███████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  2.01it/s]
If all the labels are ok, then use the function 'create_training_dataset' to create the training dataset!
CREATING TRAININGSET
The training dataset is successfully created. Use the function 'train_network' to start training. Happy training!
CHANGING training parameters to end quickly!
TRAIN
Selecting single-animal trainer
Config:
{'all_joints': [[0], [1], [2], [3]],
 'all_joints_names': ['bodypart1', 'bodypart2', 'bodypart3', 'objectA'],
 'alpha_r': 0.02,
 'batch_size': 1,
 'clahe': True,
 'claheratio': 0.1,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_TESTMay26/TEST_Alex80shuffle1.mat',
 'dataset_type': 'default',
 'decay_steps': 30000,
 'deterministic': False,
 'display_iters': 2,
 'edge': False,
 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]},
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'histeq': True,
 'histeqratio': 0.1,
 'init_weights': '/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'lr_init': 0.0005,
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_TESTMay26/Documentation_data-TEST_80shuffle1.pickle',
 'min_input_size': 64,
 'mirror': False,
 'multi_stage': False,
 'multi_step': [[0.001, 5]],
 'net_type': 'resnet_50',
 'num_joints': 4,
 'optimizer': 'sgd',
 'pairwise_huber_loss': False,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'pos_dist_thresh': 17,
 'project_path': '/Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26',
 'regularize': False,
 'rotation': 25,
 'rotratio': 0.4,
 'save_iters': 5,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'sharpen': False,
 'sharpenratio': 0.3,
 'shuffle': True,
 'snapshot_prefix': '/Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/dlc-models/iteration-0/TESTMay26-trainset80shuffle1/train/snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Starting with imgaug pose-dataset loader (=default).
Batch Size is 1
Initializing ResNet
Loading ImageNet-pretrained resnet_50
2021-05-26 11:31:14.682531: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2021-05-26 11:31:14.682796: I tensorflow/core/common_runtime/process_util.cc:71] Creating new thread pool with default inter op setting: 4. Tune using inter_op_parallelism_threads for best performance.
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': '/Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/dlc-models/iteration-0/TESTMay26-trainset80shuffle1/train/snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'sgd', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'default', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': False, 'pairwise_predict': False, 'all_joints': [[0], [1], [2], [3]], 'all_joints_names': ['bodypart1', 'bodypart2', 'bodypart3', 'objectA'], 'alpha_r': 0.02, 'clahe': True, 'claheratio': 0.1, 'cropratio': 0.4, 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_TESTMay26/TEST_Alex80shuffle1.mat', 'decay_steps': 30000, 'display_iters': 2, 'edge': False, 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]}, 'histeq': True, 'histeqratio': 0.1, 'init_weights': '/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt', 'lr_init': 0.0005, 'max_input_size': 1500, 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_TESTMay26/Documentation_data-TEST_80shuffle1.pickle', 'min_input_size': 64, 'multi_stage': False, 'multi_step': [[0.001, 5]], 'net_type': 'resnet_50', 'num_joints': 4, 'pos_dist_thresh': 17, 'project_path': '/Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26', 'rotation': 25, 'rotratio': 0.4, 'save_iters': 5, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'sharpen': False, 'sharpenratio': 0.3, 'covering': True, 'elastic_transform': True, 'motion_blur': True, 'motion_blur_params': {'k': 7, 'angle': (-90, 90)}}
Starting training....
iteration: 2 loss: 1.2973 lr: 0.001
iteration: 4 loss: 0.7604 lr: 0.001
2021-05-26 11:32:07.633706: W tensorflow/core/kernels/queue_base.cc:277] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
	 [[{{node fifo_queue_enqueue}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/train.py", line 91, in load_and_enqueue
    sess.run(enqueue_op, feed_dict=food)
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
	 [[node fifo_queue_enqueue (defined at /opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/train.py:77) ]]

Caused by op 'fifo_queue_enqueue', defined at:
  File "testscript.py", line 146, in <module>
    deeplabcut.train_network(path_config_file)
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/training.py", line 189, in train_network
    allow_growth=allow_growth,
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/train.py", line 176, in train
    batch, enqueue_op, placeholders = setup_preloading(batch_spec)
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/train.py", line 77, in setup_preloading
    enqueue_op = q.enqueue(placeholders_list)
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 345, in enqueue
    self._queue_ref, vals, name=scope)
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 4158, in queue_enqueue_v2
    timeout_ms=timeout_ms, name=name)
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

CancelledError (see above for traceback): Enqueue operation was cancelled
	 [[node fifo_queue_enqueue (defined at /opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/train.py:77) ]]

The network is now trained and ready to evaluate. Use the function 'evaluate_network' to evaluate the network.
EVALUATE
Config:
{'all_joints': [[0], [1], [2], [3]],
 'all_joints_names': ['bodypart1', 'bodypart2', 'bodypart3', 'objectA'],
 'batch_size': 1,
 'crop_pad': 0,
 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_TESTMay26/TEST_Alex80shuffle1.mat',
 'dataset_type': 'imgaug',
 'deterministic': False,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': '/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 1.0,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'mean_pixel': [123.68, 116.779, 103.939],
 'mirror': False,
 'net_type': 'resnet_50',
 'num_joints': 4,
 'optimizer': 'sgd',
 'pairwise_huber_loss': True,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'regularize': False,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': '/Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/dlc-models/iteration-0/TESTMay26-trainset80shuffle1/test/snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Running  DLC_resnet50_TESTMay26shuffle1_5  with # of trainingiterations: 5
Initializing ResNet
Analyzing data...
5it [00:16,  3.36s/it]
Done and results stored for snapshot:  snapshot-5
Results for 5  training iterations: 80 1 train error: 357.63 pixels. Test error: 320.37  pixels.
With pcutoff of 0.01  train error: 357.63 pixels. Test error: 320.37 pixels
Thereby, the errors are given by the average distances between the labels by DLC and the scorer.
Plotting...
100%|███████████████████████████████████████████████████████████████████████| 5/5 [00:02<00:00,  1.98it/s]
The network is evaluated and the results are stored in the subdirectory 'evaluation_results'.
If it generalizes well, choose the best model for prediction and update the config file with the appropriate index for the 'snapshotindex'.
Use the function 'analyze_video' to make predictions on new videos.
Otherwise consider retraining the network (see DeepLabCut workflow Fig 2)
CUT SHORT VIDEO AND ANALYZE (with dynamic cropping!)
/bin/sh: ffmpeg: command not found
Config:
{'all_joints': [[0], [1], [2], [3]],
 'all_joints_names': ['bodypart1', 'bodypart2', 'bodypart3', 'objectA'],
 'batch_size': 1,
 'crop_pad': 0,
 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_TESTMay26/TEST_Alex80shuffle1.mat',
 'dataset_type': 'imgaug',
 'deterministic': False,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': '/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 1.0,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'mean_pixel': [123.68, 116.779, 103.939],
 'mirror': False,
 'net_type': 'resnet_50',
 'num_joints': 4,
 'optimizer': 'sgd',
 'pairwise_huber_loss': True,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'regularize': False,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': '/Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/dlc-models/iteration-0/TESTMay26-trainset80shuffle1/test/snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Using snapshot-5 for model /Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/dlc-models/iteration-0/TESTMay26-trainset80shuffle1
Starting analysis in dynamic cropping mode with parameters: (True, 0.1, 5)
Switching batchsize to 1, num_outputs (per animal) to 1 and TFGPUinference to False (all these features are not supported in this mode).
Initializing ResNet
No video(s) were found. Please check your paths and/or 'video_type'.
analyze again...
Config:
{'all_joints': [[0], [1], [2], [3]],
 'all_joints_names': ['bodypart1', 'bodypart2', 'bodypart3', 'objectA'],
 'batch_size': 1,
 'crop_pad': 0,
 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_TESTMay26/TEST_Alex80shuffle1.mat',
 'dataset_type': 'imgaug',
 'deterministic': False,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': '/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 1.0,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'mean_pixel': [123.68, 116.779, 103.939],
 'mirror': False,
 'net_type': 'resnet_50',
 'num_joints': 4,
 'optimizer': 'sgd',
 'pairwise_huber_loss': True,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'regularize': False,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': '/Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/dlc-models/iteration-0/TESTMay26-trainset80shuffle1/test/snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Using snapshot-5 for model /Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/dlc-models/iteration-0/TESTMay26-trainset80shuffle1
Initializing ResNet
No video(s) were found. Please check your paths and/or 'video_type'.
CREATE VIDEO
No video(s) were found. Please check your paths and/or 'video_type'.
Making plots
No videos found. Make sure you passed a list of videos and that *videotype* is right.
EXTRACT OUTLIERS
No suitable videos found in ['/Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/videos/reachingvideo1short.avi']
No suitable videos found in ['/Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/videos/reachingvideo1short.avi']
RELABELING
Traceback (most recent call last):
  File "testscript.py", line 227, in <module>
    DF = pd.read_hdf(file, "df_with_missing")
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/pandas/io/pytables.py", line 397, in read_hdf
    raise FileNotFoundError(f"File {path_or_buf} does not exist")
FileNotFoundError: File /Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/labeled-data/reachingvideo1short/machinelabels-iter0.h5 does not exist
</p></details>

**How to Reproduce the problem**
1. clone repo
2. make DLC-CPU env
3. run testscript.py
4. (I also manually installed deeplabcut 2.2rc1 and wxPython 4.0.7 since these were not installed properly even after multiple tries.)

**Screenshots**

**Additional context**

**Comment by MMathisLab** [comment]
Hey @pondposaphiwat so the repo right now is quite ahead of the rc1; so to run the test script you should install the latest code. Here is how to do that: https://github.com/DeepLabCut/DeepLabCut/wiki/How-to-use-the-latest-GitHub-code

Also, the first warnings are numpy & tensorflow warning, but all will work; not an issue (if they annoy you, you can run `pip install numpy==1.16.4` and it goes away.

The missing file sometimes is a permissions issue (but I normally only see this on windows). Good thing is that if you are to the point in the script where you are at machine labels, everything is working in the install (just this file that gets written into the `test-alex-date` might not be able to write. You can also look at the test folder that is created and see if it's missing.

**Comment by tachposa** [comment]
I just followed the instructions to do that before running the test script (so everything has just been updated). Is there a way to check which files I should be looking out for in particular?

**Comment by MMathisLab** [comment]
`/Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/labeled-data/reachingvideo1short/machinelabels-iter0.h5` <-- is that file in the folder?

also, please check your ffmpeg installation (as we suggest on the forum: https://forum.image.sc/t/problem-in-dlc-installation-testscript-py/52038/7)

**Comment by tachposa** [comment]
No it isn't the file is not there (the folder /readingvideo1short is not made)
<img width="396" alt="Screen Shot 2564-05-26 at 12 52 15" src="https://user-images.githubusercontent.com/70335919/119722493-3a862480-be21-11eb-9a7e-5a61bbf5a8db.png">

**Comment by tachposa** [comment]
Is it possible for that the testscript throws these errors but the installed modules work properly?

**Comment by jonahpc** [comment]
To whom it may concern,

I have a few questions regarding the triangulation process.

1.) Do the cameras have to be oriented orthogonally? Is the
triangulated space all co-registered across multiple sessions, and if so,
what dictates this space? What does x, y, and z imply in this space?
2.) Can I use data from three cameras to find the best fit?

Best,
JPC

**Comment by MMathisLab** [comment]
@pondposaphiwat did you re-install ffpmeg in your conda env run `conda install -c conda-forge ffmpeg`

**Comment by tachposa** [comment]
I did. Now I am getting this error message instead...

`Using snapshot-5 for model /Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/dlc-models/iteration-0/TESTMay26-trainset80shuffle1
Initializing ResNet
Starting to analyze %  /Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/videos/reachingvideo1short.avi
/Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/videos  already exists!
The videos are analyzed. Now your research can truly start! 
 You can create labeled videos with 'create_labeled_video'
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
CREATE VIDEO
/Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/videos  already exists!
Starting to process video: /Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/videos/reachingvideo1short.avi
Loading /Users/pondposa/Downloads/DeepLabCut/examples/TEST-Alex-2021-05-26/videos/reachingvideo1short.avi and data.
Duration of video [s]: 1.0, recorded with 30.0 fps!
Overall # of frames: 30 with cropped frame dimensions: 832 747
Generating frames and creating video.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
`

**Comment by tachposa** [comment]
Have you seen this error before? What do you think the best solution is here?

**Comment by tachposa** [comment]
Hi! If you still see this can you give me some help please? I am only concerned because the issue has been closed.

**Comment by backyardbiomech** [comment]
That error is not common, and is not a deeplabcut issue. As one option, you might try restarting the computer, move the folder to your documents folder, and run the test again. Or, create a small project with your own videos, and run through the steps. However, the fact that the test script got as far as it did suggests that your deeplabcut installation is working.

**Comment by shahmili** [comment]
I am getting the same error as pondposaphiwat.  Looks like this may be an issue with Mac OS 10.13/14 and Python: https://bugs.python.org/issue33725

**Comment by tachposa** [comment]
Did you solve it? I don't really want to try updated my OS because I have an older Macbook :(
