### ISSUE TITLE
color scale reversed in labeling gui

### ISSUE THREAD

**Issue by jefromson** [DeepLabCut/DeepLabCut#1280]
**Describe the bug**
When labeling frames in the labeling gui I noticed the color scale on the right is reverse from the expected. The points labeled are correct with correct colors, so this issue doesn't cause problems down the line.

**Desktop (please complete the following information about your system):**
 - OS: Windows 10
 - DeepLabCut Version '2.1.10.4'
 - DeepLabCut mode - single animal tracking

**Expected behavior**
Reversed color scale to match labeled points

**Screenshots**
![image](https://user-images.githubusercontent.com/66144986/119852473-518a4c80-bedd-11eb-871d-85ab6b53edf1.png)

Thanks!

**Comment by MMathisLab** [comment]
Hi @jefromson in your conda env, can you run and report back on:

`deeplabcut.__version__` and `matplotlib.__version__`
