### ISSUE TITLE
rotation description in DownSampleVideo function is ambiguous

### ISSUE THREAD

**Issue by jefromson** [DeepLabCut/DeepLabCut#1285]
**Describe the bug**
When I query the function description of "DownSampleVideo" it describes "rotateccw" as "rotate clockwise if Yes"

**Desktop (please complete the following information about your system):**
    - OS: Ubuntu 20.04
    - DeepLabCut Version '2.1.10.4'
    - DeepLabCut mode - single animal tracking

**To Reproduce**
```
import deeplabcut
deeplabcut.DownSampleVideo?
```

**Expected behavior**
I would expect the parameter "rotateccw" to rotate counter-clockwise if Yes.

**Screenshots**
![image](https://user-images.githubusercontent.com/66144986/120020605-f2e5d100-bfb7-11eb-9b64-c08d7a131493.png)

Thanks!

**Comment by jeylau** [comment]
Good catch @jefromson! This looks like an omission to me, but @KonradDanielewski could perhaps confirm :)

**Comment by KonradDanielewski** [comment]
Yep, my bad, sorry. The parameter should be renamed to rotatecw. Made pull request for auxfun_videos.py and video_editing.py
