### ISSUE TITLE
Issue occuring when labeling frames

### ISSUE THREAD

**Issue by Gullen-Sw** [DeepLabCut/DeepLabCut#1286]
when I labeled frames, once I click next botton, I got an error messages such like below ones. How can I deal with this problem?

>>> deeplabcut.label_frames(config_path)
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\gui\labeling_toolbox.py", line 807, in nextImage
    keep_view=self.view_locked,
  File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\gui\labeling_toolbox.py", line 169, in drawplot
    im = cv2.imread(img)[..., ::-1]
TypeError: 'NoneType' object is not subscriptable

(ps. when I labeled using with GUI, colors which mean each bodyparts did not match which shown as samples. I don't know whether this matters, but I hope this info could be some cues..)

**Comment by jeylau** [comment]
What DLC version are you using? It looks like some frames were deleted from the labeled-data folder (and thus could not be read). If you open the CollectedData...csv file, do the image names in the left column match the frames in your folder?
For the color issue in the GUI, I believe this will be fixed in the next version https://github.com/DeepLabCut/DeepLabCut/pull/1282 😊

**Comment by Gullen-Sw** [comment]
I'm appreciate to recieve some solutions for my case. However, I think those do not work for me. 
I extracted 30 frames from video, and there are all of them in the labeled_data folder.  
Also, I could not find any csv files to refer or.. check some faults. (If csv files are biult when I extract frames from video, would u taught me the directory?)
I'm so sorry to say this, but, could you give me another option to solve this problem?

**Comment by jeylau** [comment]
When the labeling GUI opens, and you click on Load Frames, make sure to select the folder containing your images rather than an image. Let me know if that helps :)

**Comment by Gullen-Sw** [comment]
when I click Load Frames botton, there are no any image files, jsut empty. 
As far as now, when I just click the video_names folder and click open botton, the frames automatically load in my GUI screen.

**Comment by backyardbiomech** [comment]
When you extract frames, the program creates a folder inside `labeled-data`  with the same name as the video.
If you look in the file explorer, inside that video folder, you should see all of the frames you extracted as `.png` files. You should also see `CollectedData_dlt.h5` and `CollectedData_dlt.csv`. 

When you click Load Frames in the label frames GUI, you should see the video folder. If you open the video folder in that GUI, you will not see any files, but can just click the `Select Folder` button with nothing selected.

**Comment by Gullen-Sw** [comment]
Sorry to reply too late. 
To tell the result, I could not find and fix my problems despite you guys' advice, so I ran the same process on another desktop (the same env, modules) and I could succeed in the task easily. 
Hence, I doubt that maybe there are some problems with my anacondas, (or others) so I reset my env and try again, and I could do the same task easily again.
I can't conclude that all the anaconda's environment is trouble in this case, but in my case, it was. 
I pretty much appreciate all your help. Thx.

My enviroment 
python : 3.6.4
deeplabcut : 2.2rc2
Using IDLE : spyder
