### ISSUE TITLE
poor tracking results with 3080 GPU

### ISSUE THREAD

**Issue by haofanglee** [DeepLabCut/DeepLabCut#1287]
Dear deeplabcut team,

First of all thank you for making this great program!  I am encountering some difficulties getting accurate tracking of the shape of a mouse's eyelid. I would like to get some help here. 

My DLC environment: OS: Windows 10. GPU: NVIDIA Geforce RTX 3080   Cuda: 10.0 . & DLC-GPU environment file. Deeplabcut Version: 2.1.10.4

I extracted and hand-labeled 90 frames using kmeans method. Then I created the trainingset using RESNET-50 (didn't change other parameters in pose yaml config file). I can normally run all the steps in the program. However, the training results are very poor. The train and test errors are over 200. And based on the inference coordinates, all the 6 markers are located on the corner of the image, which is far- far away from my hand-labeled coordinates.

Description of my video: mice are head-fixed so the lighting and position of all the labels are pretty similar across frames. I thought tracking this type of videos should be relatively  easy compared to a freely moving animal. But the results seem to be far from accurate. I am thinking that I'm missing some important step, but I couldn't figure it out. 

I have attached an example image of the video, the training results summary, hand-labeled coordinates, result coordinates, plus the 2 config files down below. Please let me know if other info is needed. Thank you again!!

![manually labeled video](https://user-images.githubusercontent.com/18105990/120143517-d42f4680-c212-11eb-9ad0-a92b7ee0f01b.PNG)
![combined evaluation](https://user-images.githubusercontent.com/18105990/120143522-d7c2cd80-c212-11eb-862a-77e0aab9dec4.PNG)
![labeled coordinates](https://user-images.githubusercontent.com/18105990/120143533-dabdbe00-c212-11eb-91f3-54b2c3a56a11.PNG)
![results coordinate](https://user-images.githubusercontent.com/18105990/120143543-dd201800-c212-11eb-83b2-feeb088b27af.PNG)

[configfile.txt](https://github.com/DeepLabCut/DeepLabCut/files/6567928/configfile.txt)
[pose_cfgfile.txt](https://github.com/DeepLabCut/DeepLabCut/files/6567929/pose_cfgfile.txt)

**Comment by jeylau** [comment]
Hello @haofanglee, this is a behavior that a couple of users have been facing (see https://github.com/DeepLabCut/DeepLabCut/issues/1142). Your GPU is not supported by Tensorflow 1, so you must train using `deeplabcutcore` meanwhile. Full support for TF2 in DeepLabCut is at the top of our priority list, and will be available soon 😊

**Comment by haofanglee** [comment]
Thanks @jeylau ! I didn't realize that RTX 3 series is not compatible with the tensorflow 1.x~. I haven't used deeplabcutcore before. If I am running deeplabcutcore on windows, can I still follow the step as #1142 ? Thank you for the continuous effort on updating the program :)

**Comment by MMathisLab** [comment]
Note, you can use the same project, just in your DLC conda env run:
```python

pip uninstall tensorflow
pip install tensorflow==2.4
pip install deeplabcutcore

import deeplabcutcore as dlc
dlc.create_training_dataset(yourfullconfig.yaml path, shuffle = 2)
dlc.train_network(confg, shuffle=2)
``` 

* here, you can either delete shuffle 1, or just make a new one.

**Comment by haofanglee** [comment]
Thanks! Will give it a try.
