### ISSUE TITLE
Cannot reconstruct 1 animal track in refinement GUI

### ISSUE THREAD

**Issue by ana-ich** [DeepLabCut/DeepLabCut#1291]
You will have to update to rc2; 1 did not support single animal mode.

_Originally posted by @MMathisLab in https://github.com/DeepLabCut/DeepLabCut/issues/1288#issuecomment-851565226_

**Comment by ana-ich** [comment]
Actually I have the rc2 version. Here's a screenshot.
![image](https://user-images.githubusercontent.com/66062281/120223842-e927cc00-c24a-11eb-844f-0c1828d89665.png)

**Comment by jeylau** [comment]
@ana-ich, how can we help you?

**Comment by ana-ich** [comment]
Hello, I'm trying to use 2.2rc2 with single animal but when I refine tracklets  I see two individuals in the GUI. 
I mention this problem in #1288. I attached also some screenshots in the issue. I thought I have rc1 version but actually I have the rc2 version, which should support single animal mode.

**Comment by jeylau** [comment]
This was indeed something silly: the entry field in the GUI was not accepting a value of 1. This will be fixed thanks to #1298.
