### ISSUE TITLE
Installing DeepLabCut on Windows 10, can't run testscript.py

### ISSUE THREAD

**Issue by lhrhode** [DeepLabCut/DeepLabCut#1292]
OS: Windows 10
DeepLabCut Version: 2.2rc1
Anaconda env used: DLC-CPU

Hi, I'm using deeplabcut as part of a student project.

I have been trying to install deeplabcut on windows 10 (nvidia geforce RTX 2080) using either gpu or cpu, but I have been having issues trying to run the testscript.py file.
Initially, when I set up my conda environment using the DLC-CPU.yaml file, I tried running the testscript.py and had the known error found here: https://github.com/DeepLabCut/DeepLabCut/issues/1106 . 
It was resolved by following the conda install -c conda-forge ffmpeg advice. 
Then I got a new error similar to this one: https://github.com/DeepLabCut/DeepLabCut/issues/1265 . And so now I am stuck trying to upgrade the deeplabcut version from ‘2.1.10.4’ to ‘2.2rc1’. 
After upgrading to 2.2rc1 using pip install and trying to import deeplabcut, then I get what is shown in the screenshot below.
I've also tried running ./reinstall.sh file, but it didn't work for windows so I've also tried directly running the following:
pip uninstall deeplabcut 
python setup.py sdist bdist_wheel
pip install C:\Users\LabMi\Documents\GitHub\DeepLabCut\dist\deeplabcut-2.2rc1-py3-none-any.whl 
However, I get the same error with import deeplabcut

What can I do?
I’ve tried upgrading different ways, but I always get the same error.
Has someone been able to install deeplabcut on windows 10 and can show their steps for an updated clean walk through, with or without gpu?

![image](https://user-images.githubusercontent.com/71452451/120266584-3e2a0900-c270-11eb-85b9-dc6b9ea9ef84.png)

Thank you so much for any help.

**Comment by lhrhode** [comment]
Thank you so much for your quick response @jeylau !
I tried your suggestion, and got the output that I'll list at the end.
When I run import deeplabcut, unfortunately, I still get the same error as in the original post (OSError: [WinError 126] The specified module could not be found).
What other steps could I try?

Below is the output of running: conda env update -f DLC-CPU.yaml in my activated environment
(DLC-CPU) C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments>conda env update -f DLC-CPU.yaml
Collecting package metadata (repodata.json): done
Solving environment: done
Installing pip dependencies: / Ran pip subprocess with arguments:
['C:\\Users\\LabMi\\Anaconda3\\envs\\DLC-CPU\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\Users\\LabMi\\Documents\\GitHub\\DeepLabCut\\conda-environments\\condaenv.4kkmlclj.requirements.txt']
Pip subprocess output:
Requirement already satisfied: tensorflow==1.15.5 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from -r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (1.15.5)
Requirement already satisfied: deeplabcut[gui] in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from -r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (2.2rc2)
Requirement already satisfied: absl-py>=0.7.0 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorflow==1.15.5->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (0.12.0)
Requirement already satisfied: numpy<1.19.0,>=1.16.0 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorflow==1.15.5->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (1.17.5)
Requirement already satisfied: grpcio>=1.8.6 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorflow==1.15.5->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (1.38.0)
Requirement already satisfied: protobuf>=3.6.1 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorflow==1.15.5->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (3.17.1)
Requirement already satisfied: astor>=0.6.0 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorflow==1.15.5->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (0.8.1)
Requirement already satisfied: tensorflow-estimator==1.15.1 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorflow==1.15.5->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (1.15.1)
Requirement already satisfied: keras-preprocessing>=1.0.5 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorflow==1.15.5->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (1.1.2)
Requirement already satisfied: gast==0.2.2 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorflow==1.15.5->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (0.2.2)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorflow==1.15.5->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: wheel>=0.26 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorflow==1.15.5->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (0.36.2)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorflow==1.15.5->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (3.3.0)
Requirement already satisfied: keras-applications>=1.0.8 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorflow==1.15.5->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (1.0.8)
Requirement already satisfied: wrapt>=1.11.1 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorflow==1.15.5->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (1.12.1)
Requirement already satisfied: six>=1.10.0 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorflow==1.15.5->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: google-pasta>=0.1.6 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorflow==1.15.5->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (0.2.0)
Requirement already satisfied: tensorboard<1.16.0,>=1.15.0 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorflow==1.15.5->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (1.15.0)
Requirement already satisfied: h5py<=2.10.0 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorflow==1.15.5->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (2.10.0)
Requirement already satisfied: markdown>=2.6.8 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.5->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (3.3.4)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.5->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (49.6.0.post20210108)
Requirement already satisfied: werkzeug>=0.11.15 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.5->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: importlib-metadata in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from markdown>=2.6.8->tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.5->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (4.4.0)
Requirement already satisfied: numba==0.51.1 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.51.1)
Requirement already satisfied: opencv-python-headless~=3.4.9.33 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (3.4.9.33)
Requirement already satisfied: ipython-genutils in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.2.0)
Requirement already satisfied: chardet in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (4.0.0)
Requirement already satisfied: pyyaml in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (5.4.1)
Requirement already satisfied: certifi in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (2021.5.30)
Requirement already satisfied: pandas>=1.0.1 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (1.2.4)
Requirement already satisfied: python-dateutil in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (2.8.1)
Requirement already satisfied: tensorpack==0.9.8 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.9.8)
Requirement already satisfied: matplotlib==3.1.3 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (3.1.3)
Requirement already satisfied: scikit-learn in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.24.2)
Requirement already satisfied: statsmodels>=0.11 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.12.2)
Requirement already satisfied: ipython in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (7.24.0)
Requirement already satisfied: filterpy in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (1.4.5)
Requirement already satisfied: scikit-image>=0.17 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.18.1)
Requirement already satisfied: intel-openmp in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (2021.2.0)
Requirement already satisfied: cython in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.29.23)
Requirement already satisfied: ruamel.yaml>=0.15.0 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.17.7)
Requirement already satisfied: moviepy<=1.0.1 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (1.0.1)
Requirement already satisfied: scipy>=1.4 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (1.6.3)
Requirement already satisfied: imgaug in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.4.0)
Requirement already satisfied: tqdm in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (4.61.0)
Requirement already satisfied: Pillow>=7.1 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (8.2.0)
Requirement already satisfied: click in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (8.0.1)
Requirement already satisfied: patsy in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.5.1)
Requirement already satisfied: tables in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (3.6.1)
Requirement already satisfied: networkx in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (2.5.1)
Requirement already satisfied: wxpython<4.1 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (4.0.7.post2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from matplotlib==3.1.3->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from matplotlib==3.1.3->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from matplotlib==3.1.3->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.10.0)
Requirement already satisfied: llvmlite<0.35,>=0.34.0.dev0 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from numba==0.51.1->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.34.0)
Requirement already satisfied: pyzmq>=16 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorpack==0.9.8->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (22.1.0)
Requirement already satisfied: tabulate>=0.7.7 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorpack==0.9.8->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.8.9)
Requirement already satisfied: msgpack-numpy>=0.4.4.2 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorpack==0.9.8->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.4.7.1)
Requirement already satisfied: psutil>=5 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorpack==0.9.8->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (5.8.0)
Requirement already satisfied: msgpack>=0.5.2 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tensorpack==0.9.8->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (1.0.2)
Requirement already satisfied: requests<3.0,>=2.8.1 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from moviepy<=1.0.1->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (2.25.1)
Requirement already satisfied: imageio-ffmpeg>=0.2.0 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from moviepy<=1.0.1->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.4.4)
Requirement already satisfied: proglog<=1.0.0 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from moviepy<=1.0.1->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.1.9)
Requirement already satisfied: decorator<5.0,>=4.0.2 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from moviepy<=1.0.1->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (4.4.2)
Requirement already satisfied: imageio<3.0,>=2.5 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from moviepy<=1.0.1->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (2.9.0)
Requirement already satisfied: pytz>=2017.3 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from pandas>=1.0.1->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (2021.1)
Requirement already satisfied: idna<3,>=2.5 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from requests<3.0,>=2.8.1->moviepy<=1.0.1->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from requests<3.0,>=2.8.1->moviepy<=1.0.1->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (1.26.5)
Requirement already satisfied: ruamel.yaml.clib>=0.1.2 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from ruamel.yaml>=0.15.0->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.2.2)
Requirement already satisfied: tifffile>=2019.7.26 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from scikit-image>=0.17->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (2021.4.8)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from scikit-image>=0.17->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (1.1.1)
Requirement already satisfied: colorama in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from click->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.4.4)
Requirement already satisfied: opencv-python in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from imgaug->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (4.5.2.52)
Requirement already satisfied: Shapely in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from imgaug->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (1.7.1)
Requirement already satisfied: zipp>=0.5 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from importlib-metadata->markdown>=2.6.8->tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.5->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (3.4.1)
Requirement already satisfied: typing-extensions>=3.6.4 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from importlib-metadata->markdown>=2.6.8->tensorboard<1.16.0,>=1.15.0->tensorflow==1.15.5->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 1)) (3.7.4.3)
Requirement already satisfied: backcall in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from ipython->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.2.0)
Requirement already satisfied: matplotlib-inline in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from ipython->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.1.2)
Requirement already satisfied: traitlets>=4.2 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from ipython->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (5.0.5)
Requirement already satisfied: jedi>=0.16 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from ipython->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.18.0)
Requirement already satisfied: pygments in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from ipython->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (2.9.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from ipython->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (3.0.18)
Requirement already satisfied: pickleshare in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from ipython->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.7.5)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from jedi>=0.16->ipython->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.8.2)
Requirement already satisfied: wcwidth in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (0.2.5)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from scikit-learn->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (2.1.0)
Requirement already satisfied: joblib>=0.11 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from scikit-learn->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (1.0.1)
Requirement already satisfied: numexpr>=2.6.2 in c:\users\labmi\anaconda3\envs\dlc-cpu\lib\site-packages (from tables->deeplabcut[gui]->-r C:\Users\LabMi\Documents\GitHub\DeepLabCut\conda-environments\condaenv.4kkmlclj.requirements.txt (line 2)) (2.7.3)

done
#
# To activate this environment, use
#
#     $ conda activate DLC-CPU
#
# To deactivate an active environment, use
#
#     $ conda deactivate

**Comment by jeylau** [comment]
According to that post https://github.com/conda/conda/issues/9313 (among others), it looks like it is your conda installation that is faulty. Could you maybe try to make sure anaconda is up-to-date, and retry then in a fresh environment?

**Comment by AlexEMG** [comment]
also https://stackoverflow.com/questions/29904248/error-importing-polygon-from-shapely-geometry-polygon
