### ISSUE TITLE
some problems while running example file testscript.py

### ISSUE THREAD

**Issue by kimminji2018** [DeepLabCut/DeepLabCut#1293]
Imported DLC!
CREATING PROJECT
Created "/content/TEST-Alex-2021-06-01/videos"
Created "/content/TEST-Alex-2021-06-01/labeled-data"
Created "/content/TEST-Alex-2021-06-01/training-datasets"
Created "/content/TEST-Alex-2021-06-01/dlc-models"
Copying the videos
/usr/local/lib/python3.7/dist-packages/deeplabcut/create_project/new.py:175: UserWarning: No valid videos were found. The project was not created... Verify the video files and re-create the project.
  "No valid videos were found. The project was not created... "
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-8-73f8407947c8> in <module>()
     64     )
     65 
---> 66     cfg = deeplabcut.auxiliaryfunctions.read_config(path_config_file)
     67     cfg["numframes2pick"] = 5
     68     cfg["pcutoff"] = 0.01

/usr/local/lib/python3.7/dist-packages/deeplabcut/utils/auxiliaryfunctions.py in read_config(configname)
    186     else:
    187         raise FileNotFoundError(
--> 188             "Config file is not found. Please make sure that the file exists and/or that you passed the path of the config file correctly!"
    189         )
    190     return cfg

FileNotFoundError: Config file is not found. Please make sure that the file exists and/or that you passed the path of the config file correctly!

How can I solve this?

**Comment by jeylau** [comment]
Hi @kimminji2018, it looks like deeplabcut is installed globally rather than in a separate, virtual environment. What command did you use to execute the test script? The test folder is created in the wrong location ('/content') rather than in 'DeepLabCut/examples'.
