### ISSUE TITLE
create_training_model_comparison confused by training split 93%

### ISSUE THREAD

**Issue by jefromson** [DeepLabCut/DeepLabCut#1300]
**Describe the bug**
Using the deeplabcut gui, when I use the "create_training_model_comparison" function (screenshot a), it creates a training dataset with 93% training fraction (output 1, screenshot b). When I attempt to begin training the system is automatically looking for a folder labeled “trainingset95shuffle0” and not finding it because it is “trainingset93shuffle0” (output 2). If I attempt to use the “User Feedback” function (screenshot c) when creating the training dataset to force the training split to be 95% I get another error and the dataset is not created successfully(Output 3).

**Desktop (please complete the following information about your system):**
 - Ubuntu 20.04
 - DeepLabCut version 2.1.10.4
 - DeepLabCut single animal tracking

**To Reproduce**
1. Open the DeepLabCut GUI
2. On the "Create training dataset" page select the compare models option.
3. Create dataset
4. Train network
5. See errors:

<details><summary>TRACEBACK</summary><p>

Output 1:
```python
Annotation data converted to unix format...
You passed a split with the following fraction: 93%
The training dataset is successfully created. Use the function 'train_network' to start training. Happy training!
```

Output 2:
```
The training datafile  /home/John/Downloads/net_comparison_v1-JE-2021-06-02/dlc-models/iteration-0/net_comparison_v1Jun2-trainset95shuffle0/train/pose_cfg.yaml  is not present.
Probably, the training dataset for this specific shuffle index was not created.
Try with a different shuffle/trainingsetfraction or use function 'create_training_dataset' to create a new trainingdataset with this shuffle index.
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~/miniconda3/envs/dlc_gpu/lib/python3.7/site-packages/deeplabcut/gui/train_network.py in train_network(self, event)
    326             displayiters=displayiters,
    327             saveiters=saveiters,
--> 328             maxiters=maxiters,
    329         )
    330 

~/miniconda3/envs/dlc_gpu/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/training.py in train_network(config, shuffle, trainingsetindex, max_snapshots_to_keep, displayiters, saveiters, maxiters, allow_growth, gputouse, autotune, keepdeconvweights, modelprefix)
    191 
    192     except BaseException as e:
--> 193         raise e
    194     finally:
    195         os.chdir(str(start_path))

~/miniconda3/envs/dlc_gpu/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/training.py in train_network(config, shuffle, trainingsetindex, max_snapshots_to_keep, displayiters, saveiters, maxiters, allow_growth, gputouse, autotune, keepdeconvweights, modelprefix)
    162             os.environ["CUDA_VISIBLE_DEVICES"] = str(gputouse)
    163     try:
--> 164         cfg_dlc = auxiliaryfunctions.read_plainconfig(poseconfigfile)
    165         if "multi-animal" in cfg_dlc["dataset_type"]:
    166             from deeplabcut.pose_estimation_tensorflow.train_multianimal import train

~/miniconda3/envs/dlc_gpu/lib/python3.7/site-packages/deeplabcut/utils/auxiliaryfunctions.py in read_plainconfig(configname)
    261     if not os.path.exists(configname):
    262         raise FileNotFoundError(
--> 263             f"Config {configname} is not found. Please make sure that the file exists."
    264         )
    265     with open(configname) as file:

FileNotFoundError: Config /home/John/Downloads/net_comparison_v1-JE-2021-06-02/dlc-models/iteration-0/net_comparison_v1Jun2-trainset95shuffle0/train/pose_cfg.yaml is not found. Please make sure that the file exists.
```

Output 3:
```
It appears that the images were labeled on a Windows system, but you are currently trying to create a training set on a Unix system. 
 In this case the paths should be converted. Do you want to proceed with the conversion?
yes/noyes
Annotation data converted to unix format...
/home/John/Downloads/net_comparison_v1-JE-2021-06-02/training-datasets/iteration-0/UnaugmentedDataSet_net_comparison_v1Jun2  already exists!
It appears that the images were labeled on a Windows system, but you are currently trying to create a training set on a Unix system. 
 In this case the paths should be converted. Do you want to proceed with the conversion?
yes/noyes
Annotation data converted to unix format...
You passed a split with the following fraction: 93%
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/miniconda3/envs/dlc_gpu/lib/python3.7/site-packages/deeplabcut/gui/create_training_dataset.py in create_training_dataset(self, event)
    398                     userfeedback=userfeedback,
    399                     net_types=self.net_type,
--> 400                     augmenter_types=self.aug_type,
    401                 )
    402 

~/miniconda3/envs/dlc_gpu/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py in create_training_model_comparison(config, trainindex, num_shuffles, net_types, augmenter_types, userfeedback, windows2linux)
   1206                     augmenter_type=aug,
   1207                     userfeedback=userfeedback,
-> 1208                     windows2linux=windows2linux,
   1209                 )
   1210                 logger.info(log_info)

~/miniconda3/envs/dlc_gpu/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py in create_training_dataset(config, num_shuffles, Shuffles, windows2linux, userfeedback, trainIndices, testIndices, net_type, augmenter_type)
    967                         config,
    968                         shuffle=shuffle,
--> 969                         trainingsetindex=cfg["TrainingFraction"].index(trainFraction),
    970                     )
    971                     if trainposeconfigfile.is_file():

~/miniconda3/envs/dlc_gpu/lib/python3.7/_collections_abc.py in index(self, value, start, stop)
    918                 break
    919             i += 1
--> 920         raise ValueError
    921 
    922     def count(self, value):

ValueError: 
```

</p></details>

**Expected behavior**
1) When I create a training dataset using the compare_models function the train_network function should find the correct training set regardless of training fraction.
2) I am unsure the expected behavior of the "User feedback" parameter here but I was not expecting it to get hung up here.

**Screenshots**
a) ![image](https://user-images.githubusercontent.com/66144986/120487320-dcf35a00-c383-11eb-8ca6-4f4faa167fcb.png)

b) ![image](https://user-images.githubusercontent.com/66144986/120488460-cbf71880-c384-11eb-9077-1b8b7cdb6cd7.png)

c) ![image](https://user-images.githubusercontent.com/66144986/120487430-f72d3800-c383-11eb-945b-7b79bb5f1208.png)

**Additional context**

The data was labeled on a Windows 10 system and is being converted to Unix format.

Thanks!

**Comment by MMathisLab** [comment]
to confirm, you put `trainfraction: 93` in your config.yaml ?

**Comment by jefromson** [comment]
No I did not change that parameter in the config.yaml file.

![image](https://user-images.githubusercontent.com/66144986/120503006-ea631100-c390-11eb-9c19-e7be876c9f0e.png)

**Comment by MMathisLab** [comment]
> You passed a split with the following fraction: 91%

can you explain more what you are doing; in the first post you said you created the `model_comparision` with 93% training data; but it looks like you keep trying to recreate it several times. 
please then don't keep re-creating, this will cause a big mess; just simply change in the `config.yaml` to `93`, then run `train_network` (where you need to pick 1 shuffle to start with!)

**Comment by jefromson** [comment]
In these previous attempts, rather than recreating the project, I was deleting the contents of the "dlc-models" and "training-datasets" folders and just recreating the training set.

Working off the last iteration (all files suggest 93% training split but 91% resulted), I changed the config.yaml to reflect the "0.91" training split and it is successfully training.

Thank you for the assistance sorting this one out with this work-around. It seems like something odd is happening when the training_dataset is created which outputs a data split lower than intended.

Appreciate your time!
John

**Comment by AlexEMG** [comment]
Just to be clear, not a bug. I'm tempted to call it finite size effect.
