### ISSUE TITLE
Analyze_videos runs into video error partway into analysis

### ISSUE THREAD

**Issue by rshteyn** [DeepLabCut/DeepLabCut#1303]
I am using my university's linux cluster, accessed on my Mac, deeplabcut/2.0-p3.68-tf1.14

I created a pbs and py file to run analyze_videos through the cluster. The first few videos work fine, but after that there is an error that the file is not found, and the script stops running. But all of the videos are the same mp4 files, collected on the same camera/stored in the same folder, same everything.

Here is how a correct video analysis looks:
<details><summary>Starting to analyze %  FMS1_TestD1.mp4
Loading  FMS1_TestD1.mp4
Duration of video [s]:  2435.5 , recorded with  30.0 fps!
Overall # of frames:  73065  found with (before cropping) frame dimensions:  640 480
Starting to extract posture
Detected frames:  72990
Saving results in ....
Saving csv poses!</summary></p>

Here is how the error looks:
<details><summary>Starting to analyze %  FMS1_ExtD1.mp4
Loading  FMS1_ExtD1.mp4
Duration of video [s]:  1955.16 , recorded with  25.0 fps!
Overall # of frames:  48879  found with (before cropping) frame dimensions:  640 480
Starting to extract posture
[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m/gsfs0/public/deeplabcut/2.0-p3.68/envs/tfgpu/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py[0m in [0;36mAnalyzeVideo[0;34m(video, DLCscorer, trainFraction, cfg, dlc_cfg, sess, inputs, outputs, pdindex, save_as_csv, destfolder, get_nframesfrommetadata)[0m
[1;32m    322[0m         [0;31m# Attempt to load data...[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 323[0;31m         [0mpd[0m[0;34m.[0m[0mread_hdf[0m[0;34m([0m[0mdataname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    324[0m         [0mprint[0m[0;34m([0m[0;34m"Video already analyzed!"[0m[0;34m,[0m [0mdataname[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/gsfs0/public/deeplabcut/2.0-p3.68/envs/tfgpu/lib/python3.6/site-packages/pandas/io/pytables.py[0m in [0;36mread_hdf[0;34m(path_or_buf, key, mode, **kwargs)[0m
[1;32m    380[0m             raise FileNotFoundError(
[0;32m--> 381[0;31m                 [0;34m"File {path} does not exist"[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0mpath[0m[0;34m=[0m[0mpath_or_buf[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    382[0m             )

[0;31mFileNotFoundError[0m: File ./FMS1_ExtD1DeepCut_resnet50_FMSMay26shuffle1_1030000.h5 does not exist

During handling of the above exception, another exception occurred:

[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m/gsfs0/data/shteynr/analyzedlc1.py[0m in [0;36m<module>[0;34m()[0m
[1;32m      5[0m [0mconfig_path[0m[0;34m=[0m[0;34m'FMS-shteynr-2021-05-26/config.yaml'[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m [0;34m[0m[0m
[0;32m----> 7[0;31m [0mdlc[0m[0;34m.[0m[0manalyze_videos[0m[0;34m([0m[0mconfig_path[0m[0;34m,[0m [0;34m[[0m[0;34m'/gsfs0/data/shteynr/Videos/FMS1'[0m[0;34m][0m[0;34m,[0m [0mvideotype[0m[0;34m=[0m[0;34m'mp4'[0m[0;34m,[0m [0mgputouse[0m[0;34m=[0m[0;36m3[0m[0;34m,[0m [0msave_as_csv[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/gsfs0/public/deeplabcut/2.0-p3.68/envs/tfgpu/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py[0m in [0;36manalyze_videos[0;34m(config, videos, videotype, shuffle, trainingsetindex, gputouse, save_as_csv, destfolder, cropping, get_nframesfrommetadata)[0m
[1;32m    192[0m         [0;31m#looping over videos[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    193[0m         [0;32mfor[0m [0mvideo[0m [0;32min[0m [0mVideos[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 194[0;31m             [0mAnalyzeVideo[0m[0;34m([0m[0mvideo[0m[0;34m,[0m[0mDLCscorer[0m[0;34m,[0m[0mtrainFraction[0m[0;34m,[0m[0mcfg[0m[0;34m,[0m[0mdlc_cfg[0m[0;34m,[0m[0msess[0m[0;34m,[0m[0minputs[0m[0;34m,[0m [0moutputs[0m[0;34m,[0m[0mpdindex[0m[0;34m,[0m[0msave_as_csv[0m[0;34m,[0m [0mdestfolder[0m[0;34m,[0m[0mget_nframesfrommetadata[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    195[0m [0;34m[0m[0m
[1;32m    196[0m         [0mos[0m[0;34m.[0m[0mchdir[0m[0;34m([0m[0mstr[0m[0;34m([0m[0mstart_path[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/gsfs0/public/deeplabcut/2.0-p3.68/envs/tfgpu/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py[0m in [0;36mAnalyzeVideo[0;34m(video, DLCscorer, trainFraction, cfg, dlc_cfg, sess, inputs, outputs, pdindex, save_as_csv, destfolder, get_nframesfrommetadata)[0m
[1;32m    346[0m         [0mprint[0m[0;34m([0m[0;34m"Starting to extract posture"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    347[0m         [0;32mif[0m [0mint[0m[0;34m([0m[0mdlc_cfg[0m[0;34m[[0m[0;34m"batch_size"[0m[0;34m][0m[0;34m)[0m[0;34m>[0m[0;36m1[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 348[0;31m             [0mPredicteData[0m[0;34m,[0m[0mnframes[0m[0;34m=[0m[0mGetPoseF[0m[0;34m([0m[0mcfg[0m[0;34m,[0m[0mdlc_cfg[0m[0;34m,[0m [0msess[0m[0;34m,[0m [0minputs[0m[0;34m,[0m [0moutputs[0m[0;34m,[0m[0mcap[0m[0;34m,[0m[0mnframes[0m[0;34m,[0m[0mint[0m[0;34m([0m[0mdlc_cfg[0m[0;34m[[0m[0;34m"batch_size"[0m[0;34m][0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    349[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    350[0m             [0mPredicteData[0m[0;34m,[0m[0mnframes[0m[0;34m=[0m[0mGetPoseS[0m[0;34m([0m[0mcfg[0m[0;34m,[0m[0mdlc_cfg[0m[0;34m,[0m [0msess[0m[0;34m,[0m [0minputs[0m[0;34m,[0m [0moutputs[0m[0;34m,[0m[0mcap[0m[0;34m,[0m[0mnframes[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/gsfs0/public/deeplabcut/2.0-p3.68/envs/tfgpu/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py[0m in [0;36mGetPoseF[0;34m(cfg, dlc_cfg, sess, inputs, outputs, cap, nframes, batchsize)[0m
[1;32m    241[0m                 [0;32mif[0m [0mbatch_ind[0m[0;34m==[0m[0mbatchsize[0m[0;34m-[0m[0;36m1[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    242[0m                     [0mpose[0m [0;34m=[0m [0mpredict[0m[0;34m.[0m[0mgetposeNP[0m[0;34m([0m[0mframes[0m[0;34m,[0m [0mdlc_cfg[0m[0;34m,[0m [0msess[0m[0;34m,[0m [0minputs[0m[0;34m,[0m [0moutputs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 243[0;31m                     [0mPredicteData[0m[0;34m[[0m[0mbatch_num[0m[0;34m*[0m[0mbatchsize[0m[0;34m:[0m[0;34m([0m[0mbatch_num[0m[0;34m+[0m[0;36m1[0m[0;34m)[0m[0;34m*[0m[0mbatchsize[0m[0;34m,[0m [0;34m:[0m[0;34m][0m [0;34m=[0m [0mpose[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    244[0m                     [0mbatch_ind[0m [0;34m=[0m [0;36m0[0m[0;34m[0m[0;34m[0m[0m
[1;32m    245[0m                     [0mbatch_num[0m [0;34m+=[0m [0;36m1[0m[0;34m[0m[0;34m[0m[0m

[0;31mValueError[0m: could not broadcast input array from shape (8,18) into shape (7,18)</summary></p>

</p></details>

1. qsub the pbs file (see screenshot) -- it will call the python file

<img width="516" alt="pbs" src="https://user-images.githubusercontent.com/82400459/120701340-b9620980-c480-11eb-8530-660ee0666687.png">
<img width="630" alt="py" src="https://user-images.githubusercontent.com/82400459/120701338-b8c97300-c480-11eb-82d5-6ef34b6a6175.png">

**Comment by jeylau** [comment]
Could you fix the look of the traceback? It makes it very hard to troubleshoot.

**Comment by rshteyn** [comment]
Sorry, what do you mean by that? That is how the output looks like—with all of those symbols

**Comment by MMathisLab** [comment]
@rshteyn please fill out the template, we cannot help otherwise (DLC version, system, etc). The symbols are not normal, but seems you are using a very old DLC version, please update. 

It likely also means your video is corrupted; see issues: https://github.com/DeepLabCut/DeepLabCut/issues/1141 https://github.com/DeepLabCut/DeepLabCut/pull/1058
