### ISSUE TITLE
Creating Datasets without GUI

### ISSUE THREAD

**Issue by lkaesberg** [DeepLabCut/DeepLabCut#1306]
**Is your feature request related to a problem? Please describe.**
I wrote a Unity App which can produce images of 3d objects in different orientations and in front of different backgrounds. You can select keypoints on the object and the program produces a JSON file with all the keypoint locations. Now I am trying to create a script which converts this data to a training set to train DLC on this artificial data. But I ran into a problem creating the h5 file to start the training.

**Describe the solution you'd like**
A function which just takes an array of arrays of coordinates for each image and produces the labeled image data instead of using the GUI to place them manually.

**Comment by MMathisLab** [comment]
@lkaesberg the API for each function, without the GUI, is described in the wiki and the docs: https://github.com/DeepLabCut/DeepLabCut/wiki/DOCSTRINGS#create_training_dataset

You can look at how we create the H5 here: https://github.com/DeepLabCut/DeepLabCut/wiki/Using-labeled-data-in-DeepLabCut-that-was-annotated-elsewhere
