### ISSUE TITLE
Pythonw using an old version (2.7)

### ISSUE THREAD

**Issue by violakomedova** [DeepLabCut/DeepLabCut#1307]
**Your Operating system and DeepLabCut version**

Laptop: MacBook Air early 2015
OS: MacOS Big Sur
DeepLabCut Version: 2.2rc2

**Describe the problem**
    
Downloaded annaconda. We used the DLC.CPU.yaml file (downloaded off website).
We ran "conda env create -f DLC-CPU" this created the environment and downloaded deeplabcut successfully.
We activated this with "conda activate DLC-CPU". Then we tried to use "pythonw -m deeplabcut". An error message with "no module called deeplabcut". We tried "pythonw", but our python is using an older version of pythonw and "import deeplabcut" is not working.

Error message:
WARNING: Python 2.7 is not recommended. 
This version is included in macOS for compatibility with legacy software. 
Future versions of macOS will not include Python 2.7. 
Instead, it is recommended that you transition to using 'python3' from within Terminal.

Python 2.7.16 (default, May  8 2021, 11:48:02) 
[GCC Apple LLVM 12.0.5 (clang-1205.0.19.59.6) [+internal-os, ptrauth-isa=deploy on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>  

We have noticed DLC is not compatible with older versions of python. Is this the issue? We have tried to update both python and pythonw (checked this with "which python", unistalled and installed DLC-CPU again) and the newer version (pythonw 3.0.3) was working outside of the environment. However, once DLC-CPU is activated python reverts to the older version. Thank you in advance for your help!

Please place code inside this:

Last login: Fri Jun  4 14:22:59 on ttys000
(base) Vivi@Violas-Air ~ % conda activate DLC-CPU
(DLC-CPU) Vivi@Violas-Air ~ % pythonw -m deeplabcut
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named deeplabcut
(DLC-CPU) Vivi@Violas-Air ~ % 

Last login: Fri Jun  4 14:45:34 on ttys000
(base) Vivi@Violas-Air ~ % conda activate DLC-CPU
(DLC-CPU) Vivi@Violas-Air ~ % pythonw

WARNING: Python 2.7 is not recommended. 
This version is included in macOS for compatibility with legacy software. 
Future versions of macOS will not include Python 2.7. 
Instead, it is recommended that you transition to using 'python3' from within Terminal.

Python 2.7.16 (default, May  8 2021, 11:48:02) 
[GCC Apple LLVM 12.0.5 (clang-1205.0.19.59.6) [+internal-os, ptrauth-isa=deploy on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import deeplabcut
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named deeplabcut
>>>

**Comment by jeylau** [comment]
Duplicate of #1218 

In your deeplabcut environment, running `conda install python.app` fixes the issue. 😊

**Comment by violakomedova** [comment]
Thank you for such a quick reply! It fixed the issue and DLC is now working :)
