### ISSUE TITLE
ModuleNotFoundError: No module named 'kiwisolver'

### ISSUE THREAD

**Issue by kayihui** [DeepLabCut/DeepLabCut#1310]
About half a year ago, I have no problem importing deeplabcut. But today I got the following importing error. I tried uninstall and reinstall kiwisolver, but it doesn't work.

Thank you in advance for anything I can do.

MacOS 11.3.1

>>> import deeplabcut
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/__init__.py", line 38, in <module>
    from deeplabcut import generate_training_dataset
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/__init__.py", line 18, in <module>
    from deeplabcut.generate_training_dataset.labeling_toolbox import *
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/labeling_toolbox.py", line 21, in <module>
    import matplotlib.pyplot as plt
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/matplotlib/colorbar.py", line 34, in <module>
    import matplotlib.gridspec as gridspec
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/matplotlib/gridspec.py", line 25, in <module>
    import matplotlib._layoutbox as layoutbox
  File "/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/matplotlib/_layoutbox.py", line 19, in <module>
    import kiwisolver as kiwi
ModuleNotFoundError: No module named 'kiwisolver'

**Comment by jeylau** [comment]
Why is it that it suddenly fails today? Did you update matplotlib? Or deeplabcut?
According to this post https://github.com/nucleic/kiwi/issues/68#issuecomment-761707334, 
```
pip uninstall kiwisolver
pip install kiwisolver
```
should work.

**Comment by kayihui** [comment]
I have other programming projects, but in theory I didn't touch the DLC virtual environment for at least half a year. I did update my MacOS, and do other stuffs in between, but I don't know if that might affect the deeplabcut lib. Do you think it might be the matplotlib lib problem?

I have tired 
pip uninstall kiwisolver
pip install kiwisolver

But didn't work.

I tried to upgrade the deeplabcut too, but it took very long, and kind of frozen when installing some dependencies.

**Comment by jeylau** [comment]
You tried the commands within the environment, correct?
Could you share some more details about your attempt to upgrade DLC? What were the dependencies causing problems? deeplabcut should install fine with `pip install 'deeplabcut[gui]'==2.2rc2` 😊

**Comment by kayihui** [comment]
The new conda env I created is python 3.9

**Comment by jeylau** [comment]
Precisely, whereas we provide deeplabcut with python 3.7. Why don't you create your new environment off the conda configuration files we provide?

**Comment by kayihui** [comment]
For your info:

When I go back to the old env, and do the upgrade:

INFO: pip is looking at multiple versions of backcall to determine which version is compatible with other requirements. This could take a while.
  Using cached appnope-0.0.7.tar.gz (2.3 kB)
  WARNING: Generating metadata for package appnope produced metadata for project name unknown. Fix your #egg=appnope fragments.
WARNING: Discarding https://files.pythonhosted.org/packages/d5/c8/3a9da27436ab1f8fa2ad7bd6aeccd3d5dc69ab5090214d988d8f26db148b/appnope-0.0.7.tar.gz#sha256=41c495961091fe4014f651688bd669d7557743838417923867c8752fd54536b5 (from https://pypi.org/simple/appnope/). Requested unknown from https://files.pythonhosted.org/packages/d5/c8/3a9da27436ab1f8fa2ad7bd6aeccd3d5dc69ab5090214d988d8f26db148b/appnope-0.0.7.tar.gz#sha256=41c495961091fe4014f651688bd669d7557743838417923867c8752fd54536b5 (from ipython->deeplabcut) has inconsistent name: filename has 'appnope', but metadata has 'UNKNOWN'
  Using cached appnope-0.0.6.zip (3.1 kB)
  Using cached appnope-0.0.5.tar.gz (2.2 kB)
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/z3/kd8xzp1s4k9b9qkp_hh_gw840000gn/T/pip-install-vif_1mk2/appnope_22c183842def46ebb7003ca2460c3a58/setup.py'"'"'; __file__='"'"'/private/var/folders/z3/kd8xzp1s4k9b9qkp_hh_gw840000gn/T/pip-install-vif_1mk2/appnope_22c183842def46ebb7003ca2460c3a58/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/z3/kd8xzp1s4k9b9qkp_hh_gw840000gn/T/pip-pip-egg-info-5tudmidk
         cwd: /private/var/folders/z3/kd8xzp1s4k9b9qkp_hh_gw840000gn/T/pip-install-vif_1mk2/appnope_22c183842def46ebb7003ca2460c3a58/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/z3/kd8xzp1s4k9b9qkp_hh_gw840000gn/T/pip-install-vif_1mk2/appnope_22c183842def46ebb7003ca2460c3a58/setup.py", line 20
        exec line
             ^
    SyntaxError: Missing parentheses in call to 'exec'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/cc/15/54dd83c0f15452fa7c38f0f436e44bf58cc31fb376265fe0cde9d8b74706/appnope-0.0.5.tar.gz#sha256=1737b15b03576fee8e791012262db6a7d6e1ca4109175f19927376aa846daedd (from https://pypi.org/simple/appnope/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached appnope-0.0.4.tar.gz (2.2 kB)
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/z3/kd8xzp1s4k9b9qkp_hh_gw840000gn/T/pip-install-vif_1mk2/appnope_8f90305e594240148304d418c069dd1a/setup.py'"'"'; __file__='"'"'/private/var/folders/z3/kd8xzp1s4k9b9qkp_hh_gw840000gn/T/pip-install-vif_1mk2/appnope_8f90305e594240148304d418c069dd1a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/z3/kd8xzp1s4k9b9qkp_hh_gw840000gn/T/pip-pip-egg-info-f6k4weje
         cwd: /private/var/folders/z3/kd8xzp1s4k9b9qkp_hh_gw840000gn/T/pip-install-vif_1mk2/appnope_8f90305e594240148304d418c069dd1a/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/z3/kd8xzp1s4k9b9qkp_hh_gw840000gn/T/pip-install-vif_1mk2/appnope_8f90305e594240148304d418c069dd1a/setup.py", line 20
        exec line
             ^
    SyntaxError: Missing parentheses in call to 'exec'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/c5/fc/b07ec72940676b7a7fb41418980ab2ca0e5fee0f76970e506e822bee564c/appnope-0.0.4.tar.gz#sha256=13ed9cf4f2b1393ff0f2ea6a356d6195030d5b4bd56ef550e7f1f9e294f8e59d (from https://pypi.org/simple/appnope/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached appnope-0.0.3.tar.gz (2.1 kB)


....

Now stopped at:

INFO: pip is looking at multiple versions of ptyprocess to determine which version is compatible with other requirements. This could take a while.
  Using cached prompt_toolkit-3.0.17-py3-none-any.whl (367 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking

**Comment by kayihui** [comment]
I have been thinking, maybe I have messed my python some time ago...should I just use the time machine to go back to the time that works???

**Comment by jeylau** [comment]
Your environment likely contains packages other than deeplabcut; for example, this "appnope" package causing you trouble is not present in any of the environments I have.
Assuming you have downloaded the YAML files from DeepLabCut/conda-environments, you just need to run `conda env create -f DLC-CPU.yaml` and you should be set on the right track. ☺️

**Comment by kayihui** [comment]
It's finally working!!!

I outline the solution here, so that if other people have the same problem (conflict with some other lib or dependences), they can solve it quicker!

Please don't try to use time machine to move back to an earlier time...I wasted > 24 hrs frustrating with installing the MacOS.

Instead:
1. clean up the libraries in my python(s)
pip freeze | xargs pip uninstall -y

2. remove and reinstall anaconda

3. fix the pythonw (default is 2.x) to 3.x

4. install deeplabcut as in the documentation


Thank you!
