### ISSUE TITLE
Problems after Analysing a Video

### ISSUE THREAD

**Issue by DaBue93** [DeepLabCut/DeepLabCut#1316]
Hei,
[Windows 10, DeepLabCut Version '2.1.10.4', in Anaconda Env and GUI]

I have the following problem. 
I would like to analyse a mouse in the open field video using DLC-GUI and have started a multianimal project for this, because I have also labelled the open field (correct?).
Then I have successfully trained DLC with 10 videos of 20 frames each. All labels are displayed correctly in the GUI.
(200000 iterations, ellipse)

The analysis of the videos also seems to work, but in the output folder I only get the "meta.pickle" and "full.pickle" but no csv or .h5 output. What could be the reason for this? The csv/h5 files are only displayed after the refinement. 

Reproduction:
1) click on "Analyze Video" 
2) load config.yaml
3) load video file (.mpg)
output =  meta/full.pickle
4) Convert to tracklets
output = _el.pickle (used for refinement)
5) checking for csv in folder failed

**Screenshots**
![ANALYZING](https://user-images.githubusercontent.com/66160679/121531439-b0cc7e80-c9fe-11eb-94e7-f140a694fe2d.jpg)
![2](https://user-images.githubusercontent.com/66160679/121531436-b033e800-c9fe-11eb-9cd5-eabd3b9d17ba.jpg)
![3](https://user-images.githubusercontent.com/66160679/121531434-b033e800-c9fe-11eb-808c-ee87734418ce.jpg)
![4](https://user-images.githubusercontent.com/66160679/121531429-af02bb00-c9fe-11eb-96a0-c7d9c32d74de.jpg)

**Comment by jeylau** [comment]
Hey! The *el.pickle was correctly created and can be refined in the GUI as you can judge from the terminal output. You will get to inspect the tracks and save them to a h5 file. I'd encourage you to upgrade deeplabcut to version 2.2rc2 though: it makes that part of the analysis simpler (which you can read more about here https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/maDLC_UserGuide.md#optimized-animal-assembly--video-analysis).

**Comment by DaBue93** [comment]
Thank you so much! 

Is right to use multianimal project for single mouse tracking in open field? or should i use the single animal path?

**Comment by DaBue93** [comment]
This means to re-label all videos :/ okei. 
In the case of multi animal project. Is it enough if I label the open field only 2-3 times, since only the mouse moves and the box is fixed.

**Comment by jeylau** [comment]
Aw you're right, I don't think we have a function to convert from maDLC back to single animal project!
Even if the box is fixed, make sure to label it every time you see it in the frame.
