### ISSUE TITLE
PAF usage in multianimal video analysis

### ISSUE THREAD

**Issue by mynschen** [DeepLabCut/DeepLabCut#1317]
**Your Operating system and DeepLabCut version**

OS: Ubuntu 20.04
DeepLabCut Version: 2.2rc2

**Describe the problem**

I am wondering if part affinity fields (PAF) are extracted during video analysis for a multianimal project. 
From the biorxiv preprint (doi: https://doi.org/10.1101/2021.04.30.442096), I was convinced that PAF is applied to link body parts and to generate a robust proposal for animal assembly. However, in DeepLabCut/docs/maDLC_UserGuide.md it says "If the network has been trained to learn the animals' identities (i.e., you set identity=True in config.yaml before training) this information can be leveraged both during: (i) animal assembly, where body parts are grouped based on the animal they are predicted to belong to (affinity between pairs of keypoints is no longer considered in that case); and (ii) animal tracking, where identity only can be utilized in place of motion trackers to form tracklets." Therefore, I looked into the original code and in deeplabcut/pose_estimation_tensorflow/nnet/predict.py I noticed that the function extract_cnn_output(outputs_np, cfg) returns only scmap and locref but not paf.
From my testing experience with maDLC with identity as true, the identity prediction is more correct. However, the instances of physically unlikely assignment of bodyparts seems to increase as well (please refer to the screenshot below). In the screenshot, some distances between bodyparts assigned to the same individual seems extremely far away. I am wondering if this could be managed using information form PAF.
Thank you for your time reading and kind explanation. =)

**Screenshots**
![196267769_1503435890007747_8753553839741352068_n](https://user-images.githubusercontent.com/53803897/121562690-46422f80-ca4c-11eb-9a47-adfe281e8860.png)
![199022909_519112919208086_4635575227889512202_n](https://user-images.githubusercontent.com/53803897/121562696-47735c80-ca4c-11eb-9f7a-1d7fd34eae5d.png)

**Comment by jeylau** [comment]
The right `extract_cnn_output` is under nnet/predict_multianimal.py 😊  https://github.com/DeepLabCut/DeepLabCut/blob/6cf532326da08d9f3fbcaff12c738c5b7f06bc3b/deeplabcut/pose_estimation_tensorflow/nnet/predict_multianimal.py#L27
You're correct though, PAFs exclusively are used to assemble body parts into individuals _unless_ assembling and tracking with identity only is toggled; in that case, we rely on identity prediction at the keypoint level. Having in mind that accuracy is not perfect (~85–95%), this explains why some body parts may be wrongly assigned.
Have you tried to assemble individuals without identity, but to track them with it? This can only be done programmatically currently, but I think this would give you the best performance.

**Comment by AlexEMG** [comment]
What performance do you get on train/test with this? Can you post the output from evaluation?

**Comment by mynschen** [comment]
@jeylau Thanks for the advice. Will definitely try = )
@AlexEMG Thanks for the follow up. The evaluation is as below:
Shuffle 1 with 120000 iterations. The image above is generated from this network.
![image](https://user-images.githubusercontent.com/53803897/121701359-64b73200-cb03-11eb-8b68-73a38612f1b9.png)
Shuffle 2 with 200000 iterations.
![image](https://user-images.githubusercontent.com/53803897/121701518-903a1c80-cb03-11eb-975a-9dbe9b963cce.png)

**Comment by mynschen** [comment]
I am curious about the criteria for best PAF graph.
The current criteria is set as:
size_opt = np.argmax((1 - df.loc["miss", "mean"]) * df.loc["purity", "mean"])
(from deeplabcut/pose_estimation_tensorflow/lib/crossvalutils.py#L575)
I am wondering if the number of edges can be additionally considered as a basis for penalty on the score, such that a concise graph is prioritized to be selected as the best PAF graph. Something like the second term in Akaike or Bayesian information criterion for model selection.
Thank you!

**Comment by MMathisLab** [comment]
@mynschen the methods are fully outlined here: https://www.biorxiv.org/content/10.1101/2021.04.30.442096v1.full 

hope that helps!
