### ISSUE TITLE
while running in Colab - value error: unrecognized track method 

### ISSUE THREAD

**Issue by AkshayaVijayareka** [DeepLabCut/DeepLabCut#1319]
Hi,

I've been using DLC on google colab. I trained a new set today and trying to test it out. But I got the following error while doing that on the analyze video step.
Colab version : 2.1.10.4

Can you help me solve this issue ?

Please place code inside this:
<videofile_path = ['/content/drive/My Drive/DLC/videos'] 
deeplabcut.analyze_videos(path_config_file,videofile_path, videotype='avi')>

Output:
Analyzing all the videos in the directory...
Loading  /content/drive/My Drive/DLC/videos/Boson_Capture_4.avi and data.
No unfiltered data file found in /content/drive/My Drive/DLC/videos for video Boson_Capture_4 and scorer DLC_resnet50_New Training 2 Jun8shuffle1_200000.
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/deeplabcut/utils/plotting.py in plot_trajectories(config, videos, videotype, shuffle, trainingsetindex, filtered, displayedbodyparts, displayedindividuals, showfigures, destfolder, modelprefix, track_method, imagetype, resolution, linewidth)
    257             df, _, _, suffix = auxiliaryfunctions.load_analyzed_data(
--> 258                 videofolder, vname, DLCscorer, filtered, track_method
    259             )

4 frames
FileNotFoundError: No unfiltered data file found in /content/drive/My Drive/DLC/videos for video Boson_Capture_4 and scorer DLC_resnet50_New Training 2 Jun8shuffle1_200000.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/deeplabcut/utils/auxiliaryfunctions.py in load_detection_data(video, scorer, track_method)
    768         tracker = "el"
    769     else:
--> 770         raise ValueError(f"Unrecognized track_method={track_method}")
    771 
    772     filepath = os.path.splitext(video)[0] + scorer + f"_{tracker}.pickle"

ValueError: Unrecognized track_method=

**Comment by AkshayaVijayareka** [comment]
Hi , 
I added the tracker method but still the files are not saving after analyzing the video.

Codes used: 
deeplabcut.analyze_videos(path_config_file,videofile_path, videotype='avi')
deeplabcut.plot_trajectories(path_config_file,videofile_path,videotype=VideoType,track_method='skeleton')

Error:
No unfiltered data file found in /content/drive/My Drive/DLC/videos for video Boson_Capture_4 and scorer DLC_resnet50_New Training 2 Jun8shuffle1_200000 and skeleton tracker.

Why is there a sudden issue in saving the files?

**Comment by jeylau** [comment]
Hi! Please have a look at our docs https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/maDLC_UserGuide.md#---------------------decision--break-point-------------------- and preprint https://www.biorxiv.org/content/10.1101/2021.04.30.442096v1
With multi-animal projects, there are additional steps to carry out after a video analysis—which only gives you a *_full.pickle file. The body part detections should be assembled into animals and tracked with `deeplabcut.convert_detections2tracklets`, producing short animal trajectories that must be stitched together to form kinematically-consistent, full-length trajectories (`deeplabcut.stitch_tracklets`). 😊

**Comment by AkshayaVijayareka** [comment]
Hi,
This is a single animal project. The raw data (.h5 and .pickle files) are not storing after the analyze.video() step.
Can you help me solve this issue ?
