### ISSUE TITLE
ValueError: range() arg 3 must not be zero  (deeplabcut.label_frames)

### ISSUE THREAD

**Issue by flysy** [DeepLabCut/DeepLabCut#132]
**windows 10, Anaconda Env,  DeepLabCut version 2**

The following appears when I run the GUI to label the images. I can label 1 frame, but when I press 'next' nothing happens, and kernel stops working shortly after. 
Below is the error message in Junyper notebook: 

deeplabcut.label_frames(config_path)
Working on folder: c2
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
C:\Users\palom\Anaconda3\envs\DeepLabCut\lib\site-packages\deeplabcut\generate_training_dataset\labeling_toolbox.py in nextImage(self, event)
    326             im_axis = self.ax1f1.imshow(im,self.colormap)
    327             cbar = self.fig1.colorbar(im_axis, ax = self.ax1f1)
--> 328             cbar.set_ticks(range(12,np.max(im),int(np.floor(np.max(im)/len(self.bodyparts)))))
    329             cbar.set_ticklabels(self.bodyparts)
    330             img_name = Path(self.index[self.iter]).name # self.index[self.iter].split('/')[-1]

ValueError: range() arg 3 must not be zero

**Comment by MMathisLab** [comment]
Strange. Is the default color the same in the config file (ie hsv)? If you restart the kernel is this a repeatable error? If you hit the right arrow key to advance is there the same error? And, is the body part list formatted correctly? Ie does this work on the demo data in your hands? Also be sure you are up to date with the full 2.0.0 release (ie not a dev version).
