### ISSUE TITLE
Index Error in "inferenceutils.py" at GUI  "step2: convert to tracklets" 

### ISSUE THREAD

**Issue by linyangju1994** [DeepLabCut/DeepLabCut#1322]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Your Operating system and DeepLabCut version**

Windows 10
2.2rc2 (updated again from latest github master folder on June 11)
env: DLC-GPU (following installation instruction)

**Please complete the following information about your system:**

I started a multi-animal project (GUI)  training by tracking 10 individuals (5 red dots, 5 white dots; each were marked as 2 bodyparts, identity = false). After train network -> evalulate network -> analyze videos (step1: analyze videos), when I clicked "step2: convert to tracklets", I saw following index errors from terminal output. 

Could you help me have a look at it?

Thanks

**Please place code inside this:**

<details><summary>Code output</summary><p>

Config:
{'all_joints': [[0], [1], [2]],
 'all_joints_names': ['bodypart1', 'bodypart2', 'fooddot'],
 'batch_size': 1,
 'crop_pad': 0,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_test5Jun13\\test5_LJ95shuffle1.pickle',
 'dataset_type': 'multi-animal-imgaug',
 'deterministic': False,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'E:\\anaconda3\\envs\\DLC-GPU\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 1.0,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'mean_pixel': [123.68, 116.779, 103.939],
 'minconfidence': 0.01,
 'mirror': False,
 'multi_stage': False,
 'net_type': 'resnet_50',
 'nmsradius': 5.0,
 'num_idchannel': 0,
 'num_joints': 3,
 'num_limbs': 1,
 'optimizer': 'sgd',
 'pairwise_huber_loss': True,
 'pairwise_predict': False,
 'partaffinityfield_graph': [[0, 1]],
 'partaffinityfield_predict': True,
 'regularize': False,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'E:\\test5-LJ-2021-06-13\\dlc-models\\iteration-0\\test5Jun13-trainset95shuffle1\\test\\snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Using snapshot-200000 for model E:\test5-LJ-2021-06-13\dlc-models\iteration-0\test5Jun13-trainset95shuffle1
Processing...  E:\test5-LJ-2021-06-13\videos\10.mp4
E:\test5-LJ-2021-06-13\videos  already exists!
Analyzing E:\test5-LJ-2021-06-13\videos\10DLC_resnet50_test5Jun13shuffle1_200000.h5
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "E:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\analyze_videos.py", line 424, in convert2_tracklets
    identity_only=self.identity_toggle.GetStringSelection() == "Yes",
  File "E:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 1490, in convert_detections2tracklets
    ass.assemble()
  File "E:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\lib\inferenceutils.py", line 721, in assemble
    assemblies, unique = self._assemble(data_dict, i)
  File "E:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\lib\inferenceutils.py", line 642, in _assemble
    p = max(self.calc_link_probability(link), 0.001)
  File "E:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\lib\inferenceutils.py", line 327, in calc_link_probability
    sigma = self._kde.covariance[i, j]
IndexError: index 1 is out of bounds for axis 1 with size 1

</p></details>

**How to Reproduce the problem**

All parameters (except individual and bodyparts) were default in the GUI setting, the only difference I noticed between the GUI and tone config file is that the "select the network" default in GUI is "resnet+50“, but in the config file it is "dlcrnet_ms5". 

**Screenshots**
config
![image](https://user-images.githubusercontent.com/44795395/121915145-f049e200-cd00-11eb-8c29-ea99b193901d.png)

inference
![image](https://user-images.githubusercontent.com/44795395/121915316-196a7280-cd01-11eb-8955-55a08547e132.png)

GUI[analyze videos]
![image](https://user-images.githubusercontent.com/44795395/121917980-9e568b80-cd03-11eb-9a97-255dd2db9055.png)

Terminal output
![image](https://user-images.githubusercontent.com/44795395/121916120-dc52b000-cd01-11eb-9bb0-1084fafc8772.png)

**Additional context**

**Comment by jeylau** [comment]
Hi @linyangju1994! You could set `Calibrate animal assembly?` to False to ignore that step while I have a look at the issue :)

**Comment by linyangju1994** [comment]
Hi @jeylau 

Thanks for your quick reply. I set Calibrate animal assembly to false and it did proceed to generate the two more pickle files (XXX_assembilies.pickle, XXX_el.pickle). However, when I did the next step "Refine tracklets -> step1: Create tracks", I got following errors demonstrating "Tracklets are empty". 

I got the "video for checking detection" in "Analyze videos step" and it did show they captured those dot objects I labeled. 
When I compared it with my previous projects, I found there should be a third file XXX_el.h5 generated as well after "step2: convert to tracklets"

Could you help me look it to this issue?

Thanks 

**Here is the detailed output and screenshot:**
![image](https://user-images.githubusercontent.com/44795395/121973160-a2f26280-cd4a-11eb-863e-132cfdcb5168.png)
![image](https://user-images.githubusercontent.com/44795395/121973228-c74e3f00-cd4a-11eb-9657-ed991ca505ac.png)


Using snapshot-200000 for model E:\test5-LJ-2021-06-13\dlc-models\iteration-0\test5Jun13-trainset95shuffle1
Processing...  E:\test5-LJ-2021-06-13\videos\10.mp4
E:\test5-LJ-2021-06-13\videos  already exists!
Analyzing E:\test5-LJ-2021-06-13\videos\10DLC_resnet50_test5Jun13shuffle1_200000.h5
18067it [00:04, 3647.02it/s]
18067it [00:00, 2577587.35it/s]

The tracklets were created. Now you can 'refine_tracklets'.
Traceback (most recent call last):
  File "E:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\refine_tracklets.py", line 318, in create_tracks
    n_tracks=self.ntracks.GetValue(),
  File "E:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py", line 1042, in stitch_tracklets
    pickle_file, n_tracks, min_length, split_tracklets, prestitch_residuals
  File "E:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py", line 510, in from_pickle
    tracklets, n_tracks, min_length, split_tracklets, prestitch_residuals
  File "E:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py", line 542, in from_dict_of_dict
    tracklets, n_tracks, min_length, split_tracklets, prestitch_residuals
  File "E:\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py", line 469, in __init__
    raise IOError("Tracklets are empty.")
OSError: Tracklets are empty.

**Comment by jeylau** [comment]
Could you tell me if you face the same problem when using the box tracker?

**Comment by linyangju1994** [comment]
Yes, I tried all 3 methods but neither generated that .h5 file...

**Comment by jeylau** [comment]
So you are saying that the *_bx.pickle is empty too?

**Comment by linyangju1994** [comment]
Hi, just got a chance to try again, yes _bx.pickle and _sk.pickle also returned same error as ellipse: "OSError: Tracklets are empty."..

**Comment by linyangju1994** [comment]
Hi Alex (or deeplabcut team),

Do you need me to upload any files to help better understand this issue?

Thanks!

**Comment by linyangju1994** [comment]
Hi deeplabcut team,

I just tried to use 3 bodyparts (previously it was 2) to mark the dot I want to track, and I didn't see the previous empty tracklet error anymore.

Thanks!
