### ISSUE TITLE
Mobilenet is not supported by the Multi-animal project

### ISSUE THREAD

**Issue by nizheyi** [DeepLabCut/DeepLabCut#1324]
**Is your feature request related to a problem? Please describe.**
Dear all,
I'm trying to train a moblienet in multi-animal mode and export the model to deeplabcut-live. However, the following error raised when I was creating the training set:
"ValueError: Unsupported network mobilenet_v2_0.5"

In the generate_training_dataset/multiple-individuals_trainingsetmanipulation.py, I saw the comment: currently only Resnet supported for the muli-animal project. Is it possible to track multi-animal lively now? Thank you in advanced!

**Comment by jeylau** [comment]
Hi @nizheyi, the support for MobileNets will come very soon with #1323 😊

**Comment by nizheyi** [comment]
Looking forward to it！Thank you!
