### ISSUE TITLE
Multianimal Open Field Problem after updating to new DLC version.

### ISSUE THREAD

**Issue by DaBue93** [DeepLabCut/DeepLabCut#1325]
**Multianimal Problem after updating to new DLC version**

**My Operating system and DeepLabCut version**
Windows 10
DLC Version: 2.2rc2
used the DLC GUI

**The problem**

the following problem, I have filmed a mouse in the open field and wanted to analyze the video. The training for OF was done in Multianimal mode, because I want to track the animal and capture the corner points of the open field at the same time. 

During the analysis I found out that not only one mouse is detected, but automatically indiv.1 and indiv.2 are captured (color difference of the tracking points) although I have only one mouse in the openfield. 

The GUI also says "number of animals" = 2, probably because I am in multianimal mode. Can I still use the trained multianimal model, or does this no longer work?

**How to Reproduce the problem**
1. Create multi animal project
2. label mouse and open field (only one indiv.)
3. train model
4. analyse video (ellipse)
5. refine tracklets
6. --> got tracklets for 2 mice instead of 1 (see folowing pictures)

![multianimal1](https://user-images.githubusercontent.com/66160679/121997676-03b18780-cdab-11eb-8fa0-f2d6546fe1e2.jpg)
![multianimal2](https://user-images.githubusercontent.com/66160679/121997680-044a1e00-cdab-11eb-9327-6facd44fae20.jpg)

what do you suggest when it comes to analyzing Elevated Plus maze and open field videos. Is a single or multianimal project preferable?

Thanks for helping

**Comment by jeylau** [comment]
Hey @DaJe93, this bug was recently fixed with #1298. This will come with the next release candidate 😊. If you're impatient, you could have a look at `deeplabcut.stitch_tracklets` to achieve the same programmatically.
