### ISSUE TITLE
What should I do if I want to save in **.npy** format?    

### ISSUE THREAD

**Issue by shen8848** [DeepLabCut/DeepLabCut#1326]
What should I do if I want to save in **.npy** format?

**Comment by jeylau** [comment]
You could load your h5 file and write it to npy as follows:
```python
import numpy as np
import pandas as pd

df = pd.read_hdf('your_h5_data_file')
np.save('output_path', df.to_numpy())
```

**Comment by shen8848** [comment]
> You could load your h5 file and write it to npy as follows:
> 
> ```python
> import numpy as np
> import pandas as pd
> 
> df = pd.read_hdf('your_h5_data_file')
> np.save('output_path', df.to_numpy())
> ```

I can also use the same method to convert** csv to npy**, right?

**Comment by jeylau** [comment]
Correct 😊

**Comment by shen8848** [comment]
> Correct 😊

May I ask you a question. I want to mark the centroid of the mouse, and finally save it in npy format, but how do I save the centroid of the mouse in npy format? This is the teacher’s homework.

**Comment by AlexEMG** [comment]
Maybe this is not an ideal question for GitHub issues, if it is your homework ;)
But why don't you propose something and we can give you feedback... if it doesn't work.

Little hint: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mean.html

**Comment by shen8848** [comment]
哈哈哈，thank you

**Comment by MMathisLab** [comment]
Also just please know we have ample resources for questions, and GitHub should be left for bug reports / feature requests, etc :) 

See here for the very helpful forum: https://forum.image.sc/tag/deeplabcut
 And our helper code here: https://github.com/DeepLabCut/DLCutils
