### ISSUE TITLE
Triangulation and co-registered space

### ISSUE THREAD

**Issue by jonahpc** [DeepLabCut/DeepLabCut#1327]
**Your Operating system and DeepLabCut version**
Example: Anaconda Env & DeepLabCut2.0 
OS: Windows 10

**Describe the problem**
I have a few questions regarding the triangulation process. For starters, I am using 2 machine vision cameras that are facing a mouse that is strapped in place. The camera's are set at about 2 O'clock and 10 O'clock. The mouse's nose is always in the direction of 12 O'clock. My ultimate goal is that I want to triangulate my 2 videos and understand the space they live in. 

In particular, I'm having a problem with this set-up using the 'deeplabcut.calibrate_cameras' function, as they are not properly finding corners for my images, even though the grid is large in the field of view and is very crisp. 

Here are one pair of photos for my calibration photos. I have taken 200 pairs of this. The grid is on a pole which is rotated about the 2-camera's field of views.
![Front-114](https://user-images.githubusercontent.com/27032080/122088734-a7129480-cdcb-11eb-8a6c-7273d6307384.jpg)
![Side-114](https://user-images.githubusercontent.com/27032080/122088736-a7129480-cdcb-11eb-9fd9-35c45290f6e4.jpg)

In the past I have had this step (i.e., the calibrate_camera function) work, which then facilitates my next set of questions. I will be doing multiple imaging sessions, each will have very slight variations of camera positions. I would like to ensure that these sessions are coregistered, but there is large ambiguity about what space the DLC-3D lives in:

1.) Where is the origin placed? 
2.) What are the directions of the basis vectors and what determines them? 
3.) How can I ensure a coregistered space for imaging sessions that have  very slight differences in camera position?

**Comment by jonahpc** [comment]
Any updates?

**Comment by backyardbiomech** [comment]
Regarding the corner detection, you generally want to have a clean border around full outer squares. You have partial squares all around. Even a very thin border can help

![](https://docs.opencv.org/master/calib_result.jpg)

but I find that a border as thick as the squares themselves provides the cleanest output.  You also have to make sure you are inputing parameters correctly - i.e. how many rows and columns you declare. For your image it looks like 9 and 6. If rows=6 and cols=9 doesn't work, try rows=9 and cols=6. Sometimes what you call a row vs a column is nonsensical.

I believe DLC uses the [opencv camera calibration](https://docs.opencv.org/master/d9/d0c/group__calib3d.html) engine, which I have never used for 3D, so you would have to look there for placement and orientation of origin and axis, but most algorithms use either:

1. the center of the calibration point cloud in all frames,
2. the first frame digitized in the first camera
3. or the center of the first camera's sensor and its orientation (principal point). 
 
I'm pretty sure that opencv uses 3 based on a pinhole model. But none of those are very helpful for registering axes among different camera placements. The best strategy for what you want is to have a fixed or temporary registration object to provide axis origin and orientation. Build a physical object like:


![](https://i.stack.imgur.com/aHe4R.png)

You can setup the cameras, place the calibration object, and film a single frame of it (or leave it in view during the animal trials). If your filming volume is inside of a box, and one box corner is visible in both cameras, you can use that as your origin and box edges as axes. If you always place the object in the same global location and orientation, and digitize it for every camera set up, you can translate and rotate your DLC calculated animal coordinates to that global reference frame.

There are other DLC compatible systems that are more focussed on 3d. I've used anipose, and helped develop easyWand and Argus. If you need very precise 3D tracking, look at those options (and the DLC cheetah paper).

If you need [future help on usage strategies](https://github.com/DeepLabCut/DeepLabCut#community-support-developers--help), it's best to ask on the image.sc forum and save GitHub issues for bug reports. 

Also, the developers are busy with their own research programs and lives, but do their best to develop and support free software. Some of us are just experienced DLC users (with our own busy research programs and lives) who try to help other users. We enjoy helping, but please show patience when requesting help.
