### ISSUE TITLE
Running GUI after installation (python 2.7)

### ISSUE THREAD

**Issue by h1408** [DeepLabCut/DeepLabCut#1329]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Your Operating system and DeepLabCut version**

Using MacOS Catalina (10.15.7), with Anaconda environment DLC-CPU, and version 2.2rc2

**Describe the problem**

When I have activate the conda environment by typing 'conda activate DLC-CPU' and then go to the DeepLabCut folder on my desktop and try to run 'pythonw -m deeplabcut' I get an error. 

Please place code inside this:

<details><summary>Code output</summary><p>

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "deeplabcut/__init__.py", line 3
SyntaxError: Non-ASCII character '\xc2' in file deeplabcut/__init__.py on line 4, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

</p></details>

**How to Reproduce the problem**

1. Download DLC using the details in Step 2 from this link: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/installation.md
2. Activate the env using terminal
3.  navigate to where DeepLabCut is on your computer. type pythonw -m deeplabcut
4. Get the error mentioned above.

**Comment by MMathisLab** [comment]
python 2.7 is not supported (see in your error, it's being called: `"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7....`)

If you need to change you default python, see https://github.com/DeepLabCut/DeepLabCut/issues/1307 

hope that helps

**Comment by backyardbiomech** [comment]
Try this:
`conda activate DLC-CPU`
`conda install python.app`

Also note that once it’s installed, you don’t have to navigate to a folder. Just activate the env, and run `pythonw -m deeplabcut`

**Comment by h1408** [comment]
Awesome, that worked thank you very much for your help!
