### ISSUE TITLE
analyze_skeleton likelihoods

### ISSUE THREAD

**Issue by tzeriver** [DeepLabCut/DeepLabCut#1330]
I'm little confused about this line: https://github.com/DeepLabCut/DeepLabCut/blob/8c86c23425b74094f23dff626a81498cf1054063/deeplabcut/post_processing/analyze_skeleton.py#L156

If it's keeping the smallest of the two likelihoods, why does it only have bp2 inside?

**Comment by MMathisLab** [comment]
Hey @tzeriver - thanks for the question. For questions it would be awesome to use the forum, and leave github for bug reports /code not working (see community guideline here:  https://github.com/DeepLabCut/DeepLabCut#community-support-developers--help)

For this code, it was a contribution: "Written by Federico Claudi - https://github.com/FedeClaudi" so you'd have to ask @FedeClaudi for more details; I'll close this, feel free to follow up below or on the forum. <3

**Comment by FedeClaudi** [comment]
Hi, it looks like it should take the likelihoods of `bp1` and `bp2`, so it's a typo.

**Comment by tzeriver** [comment]
> Hey @tzeriver - thanks for the question. For questions it would be awesome to use the forum, and leave github for bug reports /code not working (see community guideline here: https://github.com/DeepLabCut/DeepLabCut#community-support-developers--help)
> 
> For this code, it was a contribution: "Written by Federico Claudi - https://github.com/FedeClaudi" so you'd have to ask @FedeClaudi for more details; I'll close this, feel free to follow up below or on the forum. <3

I thought it should be a quick fix, so I posted it here instead of the forum. I'll use the forum next time. Thanks!
