### ISSUE TITLE
Raw data not saving while running onColab

### ISSUE THREAD

**Issue by AkshayaVijayareka** [DeepLabCut/DeepLabCut#1331]
Hi,

I'm currently doing a single animal tracking using DLC.
I'm labelling the frames using the GUI and using google colab to train the network.
I trained the network yesterday with a new data set and when analyzing a new video, the raw data (.h5 and .pickle files) are not stored in the drive.
```
Code :
deeplabcut.analyze_videos(path_config_file,videofile_path, videotype='avi', shuffle=1,save_as_csv=True)
Output : 
49692it [09:27, 87.27it/s]                           The videos are analyzed. Now your research can truly start! 
 You can create labeled videos with 'create_labeled_video'
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
DLC_resnet50_DLCTraining Jun14shuffle1_200000
```
```
Code:
deeplabcut.plot_trajectories(path_config_file,videofile_path, videotype='avi')
Output:
Analyzing all the videos in the directory...
Loading  /content/drive/My Drive/DLC3/videos/B5.avi and data.
No unfiltered data file found in /content/drive/My Drive/DLC3/videos for video B5 and scorer DLC_resnet50_DLCTraining Jun14shuffle1_200000 and skeleton tracker.
No detection data found in /content/drive/My Drive/DLC3/videos for video B5, scorer DLC_resnet50_DLCTraining Jun14shuffle1_200000, and tracker skeleton
Make sure /content/drive/My Drive/DLC3/videos/B5.avi was previously analyzed, and that detections were successively converted to tracklets using "deeplabcut.convert_detections2tracklets()" and "deeplabcut.convert_raw_tracks_to_h5()".
Plots could not be created! Videos were not evaluated with the current scorer DLC_resnet50_DLCTraining Jun14shuffle1_200000.
```
Since its a single animal project and also in the old version 2.10.4 , why is this issue coming up?
How can I get the raw data ?

**Comment by MMathisLab** [comment]
Hey @AkshayaVijayareka - typically this happens if your drive is full ; but I am also concerned with your project folder name - does it have a space in it? `DLC_resnet50_DLCTraining Jun14shuffle1_200000` with the space is odd ...

**Comment by AkshayaVijayareka** [comment]
@MMathisLab  The drive has space. My project folder name is DLC3. 

DLC_resnet50_DLCTraining Jun14shuffle1_200000 is the .h5 file of the evaluation-result. 

Is there any other issue?

**Comment by MMathisLab** [comment]
>DLC3

That is the folder name your video is in, i'm asking what the DLC project folder is named; i.e. you input project name, experimenter name, and then it created a folder which you put on google colab, ie.. should look like: "openfield-mackenzie-2021-06-14" 

> DLC_resnet50_DLCTraining Jun14shuffle1_200000 is the .h5 file of the evaluation-result.

that's not evaluation result, that is the analyzed video result, which you said is NOT in the folder with the video, after you run analyze_videos, correct? Can you confirm after you run analyze_videos when you check the folder it is not there? (i..e, I can 100% confirm this works for me on colab :).

**Comment by AkshayaVijayareka** [comment]
The DLC folder name is DLCTraining-Akshaya-2021-06-11

Yes, after I run analyze_videos function the files are not saving in the folder.

**Comment by MMathisLab** [comment]
can you put the video in the video folder of the DLC project, just to be sure it's not a permission issue? then re-run analyze_videos, etc
