### ISSUE TITLE
Kmeans Extraction Error

### ISSUE THREAD

**Issue by neurologic** [DeepLabCut/DeepLabCut#1332]
Thank you as always for all of your help and guidance!
We are working on tracking a group of freely swimming Mormyrid fish to study electrocommunication and turn taking in animal communication behavior.

**OS and Deeplabcut version**
MacOS 10.15
Deeplabcut 2.1.10.4 (also tried 2.2rc2 bleeding edge install)
environment DLC_CPU

**Describe the problem**

We are running into an error when we use the kmeans extraction method (but not uniform). 

<details><summary>Code output</summary><p>

[A new project with name MO-lab-2021-06-16 is created at /Users/kperks/Desktop/temp and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
more networks are available soon for maDLC, but currenlty this uses DLC-ResNet50 only
Config file read successfully.
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 8.88  seconds.
Extracting and downsampling... 491  frames from the video.
491it [00:05, 85.89it/s]
Kmeans clustering ... (this might take a while)
Traceback (most recent call last):
  File "/Users/kperks/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/gui/extract_frames.py", line 241, in extract_frames
    slider_width=slider_width,
  File "/Users/kperks/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/frame_extraction.py", line 306, in extract_frames
    color=cluster_color,
  File "/Users/kperks/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/utils/frameselectiontools.py", line 392, in KmeansbasedFrameselectioncv2
    kmeans.fit(data)
  File "/Users/kperks/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py", line 1662, in fit
    order='C', accept_large_sparse=False)
  File "/Users/kperks/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/sklearn/base.py", line 421, in _validate_data
    X = check_array(X, **check_params)
  File "/Users/kperks/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/Users/kperks/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/sklearn/utils/validation.py", line 664, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/Users/kperks/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/sklearn/utils/validation.py", line 106, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
]

</p></details>

**How to Reproduce the problem**
1. from pythonw import deeplabcut and run deeplabcut.launch_dlc()
2. create new project with video (copy video to project directory checked)
3. extract frames using kmeans 

*However, if we use 'uniform' algorithm instead, the frames are successfully extracted*
So I am using the uniformly extracted frames for now to build a training set. 

**Additional context**
This (or something similar) has come up in the past and it seemed like using the bleeding edge version remedied it. But that is not working this time. Over the school year we have tried to get this going but were dealing with camera setup and animal issues. Sorry it has taken so long to hammer on the actual training of our network for this. But we are at that point now so would like to get this weird behavior figured out before getting too far into the training (in case we need to change versions or create new projects from scratch to fix it, etc).
The multianimal testscript does work, so it does not seem like a bug in the code. Could it be a compatibility issue with the video file? We recorded using Pylon software from a Basler AcA1300 usb camera. 

Here is the information from ffmpeg about the video file that is causing the error:

<details><summary>Code output</summary><p>

[ffmpeg version 4.2.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with clang version 9.0.1
  configuration: --prefix=/Users/kperks/opt/anaconda3/envs/DLC-CPU --cc=x86_64-apple-darwin13.4.0-clang --disable-doc --disable-openssl --enable-avresample --enable-gnutls --enable-gpl --enable-hardcoded-tables --enable-libfreetype --enable-libopenh264 --enable-libx264 --enable-pic --enable-pthreads --enable-shared --enable-static --enable-version3 --enable-zlib --enable-libmp3lame
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, avi, from 'Rachel_FirstTest_IR.avi':
  Duration: 00:00:08.88, start: 0.000000, bitrate: 578701 kb/s
    Stream #0:0: Video: rawvideo, pal8, 1280x1024, 581053 kb/s, 55.30 fps, 55.30 tbr, 55.30 tbn, 55.30 tbc
]

</p></details>

**Comment by AlexEMG** [comment]
Can you make sure that this video is non-corrupt? It appears that it is not loaded correctly.

**Comment by neurologic** [comment]
@AlexEMG it is not corrupt from the perspective of VLC media player (it plays). Is there another way to check other than ffmpeg -i? Thanks!

**Comment by jeylau** [comment]
@neurologic, you could try the following:
```python
from deeplabcut.utils.auxfun_videos import VideoReader

vid = VideoReader('path_to_your_video')
vid.check_integrity()
```
This produces a log of possible errors found in the video, and you'll get warned if it's not empty.

**Comment by neurologic** [comment]
Thanks!
That returned no warnings:
```
>>> from deeplabcut.utils.auxfun_videos import VideoReader
>>> vid = VideoReader('/Users/kperks/mnt/PerksLab_rstore/Videos_Gnathonemus/Rachel_FirstTest_IR.avi')
>>> vid.check_integrity()
>>> 
```

**Comment by backyardbiomech** [comment]
I would try re-encoding the video with ffmpeg into h264 or h265 and trying again. There are multiple levels of file corruption, some of which are difficult to detect without loading every frame into opencv, but re-encoding fixes them all!

See [this discussion](https://forum.image.sc/t/analyzing-new-videos-no-data/48313/3) for re-encoding ideas.

**Comment by neurologic** [comment]
Thank you! My student followed that discussion and tried this and said that the kmeans extraction now worked for them - but that the video now looked really poor quality. I want to double check their work to make sure it is not something obvious in the re-encoding options.

**Comment by neurologic** [comment]
This seems to have been the fix for this. Thank you!
