### ISSUE TITLE
offline enquiry

### ISSUE THREAD

**Issue by iyashdesh** [DeepLabCut/DeepLabCut#1339]
Hello,

Thank You for making this.

I just want to make sure, is there a 100% offline version available or not?

Thank You

**Comment by KonradDanielewski** [comment]
Offline as in without internet access or offline as offline in inference?

For the first the answer is yes, after installing all the necesarry stuff. 
For the second the answer is yes, that is actually the "default" use case, for online you have to use DeepLabCut-Live

**Comment by iyashdesh** [comment]
Thank You
