### ISSUE TITLE
error on Mac OS 11.4 (Big sur)

### ISSUE THREAD

**Issue by es1223** [DeepLabCut/DeepLabCut#1341]
Thank you for opening this issue. 
This is my first time to install Deeplabcut on my PC.

OS: MaxOS 11.4 Big sur
DeepLabCut Version: DeepLabCut2.2
Anaconda env used:anaconda3

**Describe the problem**

After I installed anaconda3 and Deeplabcut on my Mac mini, I typed `pythonw -m deeplabcut`on terminal window.
I got the error as below,

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "deeplabcut/__init__.py", line 3
SyntaxError: Non-ASCII character '\xc2' in file deeplabcut/__init__.py on line 4, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

I can't understand and resolve that error. Please teach me how to resolve it.

**Comment by jeylau** [comment]
The solution is given here https://github.com/DeepLabCut/DeepLabCut/issues/1329#issuecomment-861852532:
after you activate your environment, run `conda install python.app` and all is well. Otherwise, pythonw references an old python version, which causes the error.

**Comment by es1223** [comment]
Thank you for your kind reply! Now, I can start GUI.

I appreciate you
