### ISSUE TITLE
Deeplabcut not saving changes made during label_frames()

### ISSUE THREAD

**Issue by aridorschel** [DeepLabCut/DeepLabCut#1342]
Hi! I’ve manually extracted some frames for one of my videos. One of the files was truncated, so I deleted it. When trying to label the new frames I noticed that all my points were shifted, so I used the function “dropannotationfileentriesduetodeletedimages”, but the points are still wrong. When I dragged them into the correct position for a few frames, clicked save, quit, and then re-opened the labelling GUI, none of my changes were saved. I have no idea why this could be? :frowning:

Strangely I’ve found no post discussing a similar issue, I’ve searched for hours but nothing comes up…

I'm using Deeplabcut 2.0 on Windows 10 in an Anaconda environment. :)

**Comment by MMathisLab** [comment]
Hi @aridorschel please fill out the template completely (i.e., 2.0 is 2 years old; are you sure you are using that version?). Also note that if you start labeling then delete images in the folder, you will indeed mess up the indexing, and it wouldn't be able to fix this shift :(

**Comment by aridorschel** [comment]
Thank you for the fast response!! :) Sorry for being imprecise, the version I'm using is 2.1.10.2 !

What I did was:
- Manually extract additional frames
- saw that two frames were truncated and deleted them out of the folder
- ran deeplabcut.dropannotationfileentriesduetodeletedimages(config), which successfully changed the csv and h5 file
- opened the labeling gui with deeplabcut.label_frames()
- label a previously unlabelled frame
- clicked save, then quit
- re-open the same folder in the labeling gui -> here, for me, the changes i just made are now gone...

Is there anything else i can upload that would be any help at all?

Since i manually extracted 160 frames i'm trying to avoid re-doing it (so deleting this folder and the video path out of the config file, perhaps renaming the original video, adding it to the project again, extracting all the frames again manually, labelling them), but apart from being quite time-consuming i just don't understand what the issue could currently be that this would resolve ? :(

thank you so much for your support!!

**Comment by aridorschel** [comment]
update: i've noticed that there is a mismatch between number of frames in my folder (168) and the list of frames in the csv file (188), of which however 19 are repeated, for example img01091, 01813, 05522 etc. appear twice. Could this be a source of the issue, and how can this occur? I've uploaded the csv file for reference! 
[csvfile_repeatingelements.zip](https://github.com/DeepLabCut/DeepLabCut/files/6700451/csvfile_repeatingelements.zip)

**Comment by backyardbiomech** [comment]
Answered on the [forum](https://forum.image.sc/t/deeplabcut-does-not-save-changes-made-during-label-frames/54255/8) and on chat.
In the future, please avoid cross-posting - it makes it harder for future users to find answers.

**Comment by aridorschel** [comment]
Solved: the issue was that the slashes in my csv file were not consistent for some reason
