### ISSUE TITLE
Problems with refinement of single animal analysis after update to DLC 2.2rc2 

### ISSUE THREAD

**Issue by DaBue93** [DeepLabCut/DeepLabCut#1344]
**MY Operating system and DeepLabCut version**
Windows 10
DeepLabCut Version: 2.2rc2 (GUI)
Anaconda env used: Anaconda 3

**Describe the problem**
I have the following problem. After creating and training a single animal project with the latest DLC version, I find that there is no longer an option to refine tracklets in the GUI bar at the top (the button is missing). Did I enter something incorrectly when creating the project? 

I want to track a mouse in the Open Field and therefore used single animal, because with multi animal I get a tracking with gaps as output (due to incorrect stitching).

**How to Reproduce the problem**
1. Created single animal project in DLC 2.2rc2
2. labeled videos with point of interest
3. trained with 1030000 iterations
4. analyzed video
5. created labeled video
6. wanted to refine tracklets
7. --> no GUI-button for refinement of tracklets, 

**Screenshots**
![no refinement button](https://user-images.githubusercontent.com/66160679/123043054-0558fc00-d3f8-11eb-9992-bf9274427e74.jpg)

I also get an error when using python code in anaconda:
![anaconda error refinement](https://user-images.githubusercontent.com/66160679/123044059-7947d400-d3f9-11eb-8990-fd456d59dbe6.jpg)

If I understand it correctly, there should be no "individuals" in the header of the single analysis in the pickle file / CSV.

**Comment by backyardbiomech** [comment]
You should use single animal if you have a single animal. You should use single animal if you have multiple animals but can reliably tell them apart (e.g. black mouse and white mouse). You should really only use multi-animal if you have multiple animals in a video that you can't tell apart.

With single animal DLC, there is no refine tracklets step, so the tab doesn't show, and you can't call it on a single animal config file.
