### ISSUE TITLE
Training iterations taking too long

### ISSUE THREAD

**Issue by elolearnsDLC** [DeepLabCut/DeepLabCut#1345]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Your Operating system and DeepLabCut version**
OS: MacOS Big SUR
DeepLabCut Version: DeepLabCut 2.2rc1
Anaconda env used: Anaconda-Navigator

**Describe the problem**
I'm practicing with videos of my cat from my iphone8 (14.4.2 - not sure of the frame information)

Following the provided protocols, I have been able to begin training my network (wahoo), however, my first pass took over 4 days to reach 11,000 iterations when it's suggested to have a min of 50,000. I do think the loss leveled out a bit (not sure what that range of "plateau" is). **Ultimately, what are the various ways to speed this process up?** Should it be taking this long on my computer and therefore? If not do I need to switch to using something like google colaboratory or using a different server that can compute at a higher rate? 

Any help with this is greatly appreciated. 
Thank you!

**Comment by backyardbiomech** [comment]
If you didn't scale down your iphone video significantly, then your extracted images are very large. CPU training is 10-100x slower than GPU training. Combine those two factors, and your results are expected.

If you don't have access to a GPU, or just want to test things out, use the provide COLAB notebooks, and make Google's GPU's work for you (for free!).
