### ISSUE TITLE
How to retrain & it keeps displaying snapshot-# is not in all_model_checkpoint_paths.

### ISSUE THREAD

**Issue by timegate** [DeepLabCut/DeepLabCut#135]
**Your Operating system and DeepLabCut version**
Anaconda Env & DeepLabCut 2.0

**Describe the problem**
I cannot understand how to retrain. In https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#i-video-analysis-and-plotting-results, I found that I should fix init_weight, but I don't know how should I fix. I tried to change init_weights to 
C:\Users\user\Desktop\LinearChamber-KAIST-2018-11-19\dlc-models\iteration-0\LinearChamberNov19-trainset95shuffle1\train\snapshot-1000,
But it doesn't work and my kernel dead(I made snapshot-1000 folder and put all snapshot-1000 related 3 files-snapshot-1000.index, snapshot-1000.meta, snapshot-1000.data-00000-of-00001) .
I feel init_weights should be changed changed to some ~.ckpt file but I can't find any ~.ckpt file in the C:\Users\user\Desktop\LinearChamber-KAIST-2018-11-19\dlc-models\iteration-0\LinearChamberNov19-trainset95shuffle1\train folder.
Could you let me know how to retrain?

![image](https://user-images.githubusercontent.com/16134605/49134347-9cd03e00-f326-11e8-81b4-4ae4b7d748cf.png)

And I got this message again and again.. may I know where is all_model_checkpoint_paths please? I can't find the variable in any deeplabcut files..

**How to Reproduce the problem**
1. train to 1000 and snapshot of 1000 made in train folder
2. change init_weights in pose_cfg.yaml to C:\Users\user\Desktop\LinearChamber-KAIST-2018-11-19\dlc-models\iteration-0\LinearChamberNov19-trainset95shuffle1\train\snapshot-1000,make snapshot-1000 folder in train folder, put 3 snapshot files in it
4. train to 2000 and my kernel dead

**Comment by AlexEMG** [comment]
(this was based on some other error and fixed on slack)

For others, here is the documentation to start  from a specific snapshot:

https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md

By default, the pre-trained ResNet network is not provided in the DeepLabCut toolbox (as it has around 100MB). However, if not previously downloaded from the TensorFlow model weights, it will be downloaded and stored in a subdirectory pre-trained under the subdirectory models in Pose_Estimation_Tensorflow. At user specified iterations during training checkpoints are stored in the subdirectory train under the respective iteration directory. If the user wishes to restart the training at a specific checkpoint they can specify the full path of the checkpoint to the variable init_weights in the pose_cfg.yaml file under the train subdirectory (see Box 2).

**Comment by AlexEMG** [comment]
The yaml file wants colons: 

**init_weights:** C:\Users\user\Desktop\LinearChamber-KAIST-2018-11-19\dlc-models\iteration-0\LinearChamberNov19-trainset95shuffle1\train\snapshot-1000

Perhaps also try 

**init_weights:** C:\\Users\user\\Desktop\\LinearChamber-KAIST-2018-11-19\\dlc-models\\iteration-0\\LinearChamberNov19-trainset95shuffle1\\train\\snapshot-1000

(and post the whole output if it does not work please)

**Comment by timegate** [comment]
> The yaml file wants colons:
> 
> **init_weights:** C:\Users\user\Desktop\LinearChamber-KAIST-2018-11-19\dlc-models\iteration-0\LinearChamberNov19-trainset95shuffle1\train\snapshot-1000
> 
> Perhaps also try
> 
> **init_weights:** C:\Users\user\Desktop\LinearChamber-KAIST-2018-11-19\dlc-models\iteration-0\LinearChamberNov19-trainset95shuffle1\train\snapshot-1000
> 
> (and post the whole output if it does not work please)

![image](https://user-images.githubusercontent.com/16134605/49419045-78fa7580-f7c8-11e8-967b-744764c0aef9.png)

---If I don't have snapshot in train folder and only have snapshot in snapshot-1000 folder, kernel died.

![image](https://user-images.githubusercontent.com/16134605/49419429-1609de00-f7ca-11e8-9c29-42daf54d5120.png)


![image](https://user-images.githubusercontent.com/16134605/49419121-de4e6680-f7c8-11e8-9ea0-438c30841312.png)

![image](https://user-images.githubusercontent.com/16134605/49419481-5b2e1000-f7ca-11e8-83c9-af75b7ae8bd6.png)


--it I do have snapshot in train folder, starts with snapshot-100(not retraining).
![image](https://user-images.githubusercontent.com/16134605/49419404-0094b400-f7ca-11e8-9444-de599ff861e6.png)


![image](https://user-images.githubusercontent.com/16134605/49419260-65034380-f7c9-11e8-9315-86c016540cfe.png)

![image](https://user-images.githubusercontent.com/16134605/49419284-7d735e00-f7c9-11e8-8fd3-c7c965f2c4b1.png)

![image](https://user-images.githubusercontent.com/16134605/49419299-8bc17a00-f7c9-11e8-96b2-563565075b04.png)

For index error, I guess you can ignore it because I intentionally fixed max_iter by fixing multi_step.
Thanks for helping me.

**Comment by AlexEMG** [comment]
Good, so it works if you don't put the snapshots in a subfolder. Note that they are also not stored in a subfolder... (i.e. during standard training, so I don't know why you would do this).

________________________________

**Comment by timegate** [comment]
> Good, so it works if you don't put the snapshots in a subfolder. Note that they are also not stored in a subfolder... (i.e. during standard training, so I don't know why you would do this).
> […](#)
> ________________________________ From: altairlight <notifications@github.com> Sent: Monday, December 3, 2018 11:37:10 PM To: AlexEMG/DeepLabCut Cc: Mathis, Alexander Thomas; State change Subject: Re: [AlexEMG/DeepLabCut] How to retrain & it keeps displaying snapshot-# is not in all_model_checkpoint_paths. (#135) The yaml file wants colons: init_weights: C:\Users\user\Desktop\LinearChamber-KAIST-2018-11-19\dlc-models\iteration-0\LinearChamberNov19-trainset95shuffle1\train\snapshot-1000 Perhaps also try init_weights: C:\Users\user\Desktop\LinearChamber-KAIST-2018-11-19\dlc-models\iteration-0\LinearChamberNov19-trainset95shuffle1\train\snapshot-1000 (and post the whole output if it does not work please) [image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_16134605_49419045-2D78fa7580-2Df7c8-2D11e8-2D967b-2D744764c0aef9.png&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=11wEEDBv3Ke3n3b8dICjuQC5vgZ23dfGPax018VOZ2g&m=q7fhWot78qQlKmVYiwdqVGpqR3Im6REH4ezz5IQjLqs&s=pOcq3HopeLLroT_u_o9fEHvuMwanBxXIdQcMB62K73I&e=> [image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_16134605_49419121-2Dde4e6680-2Df7c8-2D11e8-2D9ea0-2D438c30841312.png&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=11wEEDBv3Ke3n3b8dICjuQC5vgZ23dfGPax018VOZ2g&m=q7fhWot78qQlKmVYiwdqVGpqR3Im6REH4ezz5IQjLqs&s=rNrbEYd1eq2bwr6s0d8evHy-fIDJyiRaaM9Dq7TDE4I&e=> [image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_16134605_49419260-2D65034380-2Df7c9-2D11e8-2D9315-2D86c016540cfe.png&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=11wEEDBv3Ke3n3b8dICjuQC5vgZ23dfGPax018VOZ2g&m=q7fhWot78qQlKmVYiwdqVGpqR3Im6REH4ezz5IQjLqs&s=jHVQmapy3Ghuk5hq9YIUHBRnU4s1nWjMAgkuLG3cg-A&e=> [image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_16134605_49419284-2D7d735e00-2Df7c9-2D11e8-2D8fd3-2Dc7c965f2c4b1.png&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=11wEEDBv3Ke3n3b8dICjuQC5vgZ23dfGPax018VOZ2g&m=q7fhWot78qQlKmVYiwdqVGpqR3Im6REH4ezz5IQjLqs&s=_rE5yggvETAWHndbUsfY-xOcOmz_2zNaFgCfs6hSZKk&e=> [image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_16134605_49419299-2D8bc17a00-2Df7c9-2D11e8-2D96b2-2D563565075b04.png&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=11wEEDBv3Ke3n3b8dICjuQC5vgZ23dfGPax018VOZ2g&m=q7fhWot78qQlKmVYiwdqVGpqR3Im6REH4ezz5IQjLqs&s=yqkn3-zTdQ2XdGosHtvUCsrSAt9t9FvmT1yERZIgmk8&e=> For index error, you can ignore it because I intentionally fixed max_iter by fixing multi_step — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_AlexEMG_DeepLabCut_issues_135-23issuecomment-2D443968395&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=11wEEDBv3Ke3n3b8dICjuQC5vgZ23dfGPax018VOZ2g&m=q7fhWot78qQlKmVYiwdqVGpqR3Im6REH4ezz5IQjLqs&s=GVEFSU5GazDaRyjGMzWUVmG670Ws1-0OEyQNCjVMSqc&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AT4mXqNmPceHmqzJEZvCXTCNWh-5FuHZ2Wks5u1fv2gaJpZM4Y2-5FBd&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=11wEEDBv3Ke3n3b8dICjuQC5vgZ23dfGPax018VOZ2g&m=q7fhWot78qQlKmVYiwdqVGpqR3Im6REH4ezz5IQjLqs&s=nuaI4STopu0oxXbo-QaRL9IYvWiO_rnZB8JzRa7sEXk&e=>.

It seems it does not start with snapshot-1000. I mean it starts from the beginning and it doesn't retrain. I can't say it retrains from snapshot-1000 because also loss function doesn't seems to be started from 1000th iteration(If it does, it should start from loss 0.02~ at least. but the loss starts from over 0.05 and even sometimes 0.1). 
![image](https://user-images.githubusercontent.com/16134605/49420730-39378c00-f7d0-11e8-8493-94158ecdcb76.png)
(Please take a look at these the images.. It's hard to say it is retraining from snpashot-1000. It seems to train from the beginning)

The reason I made subfolder is because I got this message on and on 
![image](https://user-images.githubusercontent.com/16134605/49420288-0e4c3880-f7ce-11e8-84e2-e4653fdcc9c0.png)

**Comment by timegate** [comment]
> It is 100% starting correctly. It saves at steps you specify, ie 100... it won’t add 1000+100, just like the pre-trained ResNet doesn’t say iteration 1M plus X... It only crashes because you edited multi-step.

Umm.. ok. Now I got it. Thank you so much.

**Comment by JXXCgit** [comment]
Hey, @AlexEMG 
i am using googleColab GPU to run DLC. The former iterations i have is 45000 and i want to increase the iterations to 200000 and do the retrainning. i am not really understand this 
In my original pose_cfg.yaml file, the  original is 'init_weights: /usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt', 
and i change it to 'init_weights: /content/drive/My Drive/shauyin/dlc-models/iteration-0/#203Nov28-trainset95shuffle1/train/snapshot-44500' , i don't know whether this change is correct? 
And if correct, another strange thing is , 
after i run 'deeplabcut.train_network(path_config_file, shuffle=1, displayiters=100,saveiters=500, maxiters=200000)' , 
then still it goes to 'Config:
{'all_joints': [[0], [1], [2], [3]],
 'all_joints_names': ['bodypart1', 'bodypart2', 'bodypart3', 'objectA'],
 'batch_size': 1,
 'bottomheight': 400,
 'crop': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_#203Nov28/#203_xiuxian95shuffle1.mat',
 'dataset_type': 'default',
 'deterministic': False,
 'display_iters': 1000,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': '/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt',
 'intermediate_supervision': False
'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_#203Nov28/Documentation_data-#203_95shuffle1.pickle',
 'min_input_size': 64,
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 4,
 'optimizer': 'sgd',
 'pos_dist_thresh': 17,
 'project_path': '/content/drive/My Drive/shauyin',
 'regularize': False,
 'rightwidth': 400,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': '/content/drive/My '
                    'Drive/shauyin/dlc-models/iteration-0/#203Nov28-trainset95shuffle1/train/snapshot',
 'stride': 8.0,
 'topheight': 400,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}

Switching batchsize to 1, as default/tensorpack/deterministic loaders do not support batches >1. Use imgaug loader.
Starting with standard pose-dataset loader.
Initializing ResNet
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/layers/python/layers/layers.py:1057: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/nnet/pose_net.py:62: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/nnet/pose_net.py:160: The name tf.losses.sigmoid_cross_entropy is deprecated. Please use tf.compat.v1.losses.sigmoid_cross_entropy instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/nn_impl.py:183: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/nnet/losses.py:38: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
Loading ImageNet-pretrained resnet_50
INFO:tensorflow:Restoring parameters from /usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt
Max_iters overwritten as 200000
Display_iters overwritten as 100
Save_iters overwritten as 500
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'weigh_only_present_joints': False, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': '/content/drive/My Drive/shauyin/dlc-models/iteration-0/#203Nov28-trainset95shuffle1/train/snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'sgd', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'mirror': False, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'default', 'deterministic': False, 'crop': True, 'cropratio': 0.4, 'minsize': 100, 'leftwidth': 400, 'rightwidth': 400, 'topheight': 400, 'bottomheight': 400, 'all_joints': [[0], [1], [2], [3]], 'all_joints_names': ['bodypart1', 'bodypart2', 'bodypart3', 'objectA'], 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_#203Nov28/#203_xiuxian95shuffle1.mat', 'display_iters': 1000, 'init_weights': '/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt', 'max_input_size': 1500, 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_#203Nov28/Documentation_data-#203_95shuffle1.pickle', 'min_input_size': 64, 'multi_step': [[0.005, 10000], [0.02, 430000], [0.002, 730000], [0.001, 1030000]], 'net_type': 'resnet_50', 'num_joints': 4, 'pos_dist_thresh': 17, 'project_path': '/content/drive/My Drive/shauyin', 'save_iters': 50000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'output_stride': 16, 'deconvolutionstride': 2}
Starting training....' 
it still go to '/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt' 
something wrong with my change in the pose_cfg.yaml file? 
Or the way of retrainning is not correct? 
Thank you for help. 
Best wishes. 
shauyin

**Comment by AlexEMG** [comment]
Dear Shauyin,

When you start training the code prints the pose_cfg file‘s content. So you probably changed it in a different shuffle/project?

Alexander

________________________________

**Comment by JXXCgit** [comment]
Hi, Dear Alexander@AlexEMG, 
Thank you for reply. 
I am not fully understand what you mean by 'changing it in different shuffle'. 
Do you mean that 
First, i change  '/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckp' in the original pose_cfg file to 'init_weights: /content/drive/My Drive/shauyin/dlc-models/iteration-0/#203Nov28-trainset95shuffle1/train/snapshot-44500'. 
Then i restart the initial step as '
from google.colab import drive
drive.mount('/content/drive')' ? 
or which step should i start after i change the pose_cfg file. 

I mean if i restart from the first step, it later still will produce ''/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt' in the pose_cfg file, then re-training is almost start from zero, rather than on the basis the the last check_point of the training. 
Can you please tell me from which step i should follow to make pose_cfg file after being edited  works? 
Cheers, 
Shauyin

**Comment by AlexEMG** [comment]
If you changed the init_weights and when you start training the changed path is not printed, then you changed the path in the wrong file.

This is why I said that you need to make sure you change the pose_cfg.yaml file of the model that you are training.

________________________________

**Comment by JXXCgit** [comment]
> If you changed the init_weights and when you start training the changed path is not printed, then you changed the path in the wrong file. This is why I said that you need to make sure you change the pose_cfg.yaml file of the model that you are training.
> […](#)
> ________________________________ From: Shauyin CHAN <notifications@github.com> Sent: Thursday, December 12, 2019 9:07:49 AM To: AlexEMG/DeepLabCut <DeepLabCut@noreply.github.com> Cc: Mathis, Alexander Thomas <amathis@fas.harvard.edu>; Mention <mention@noreply.github.com> Subject: Re: [AlexEMG/DeepLabCut] How to retrain & it keeps displaying snapshot-# is not in all_model_checkpoint_paths. (#135) Hi, Dear Alexander@AlexEMG, Thank you for reply. I am not fully understand what you mean by 'changing it in different shuffle'. Do you mean that First, i change '/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckp' in the original pose_cfg file to 'init_weights: /content/drive/My Drive/shauyin/dlc-models/iteration-0/#203Nov28-trainset95shuffle1/train/snapshot-44500'. Then i restart the initial step as ' from google.colab import drive drive.mount('/content/drive')' ? or which step should i start after i change the pose_cfg file. I mean if i restart from the first step, it later still will produce ''/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt' in the pose_cfg file, then re-training is almost start from zero, rather than on the basis the the last check_point of the training. Can you please tell me from which step i should follow to make pose_cfg file after being edited works? Cheers, Shauyin — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_AlexEMG_DeepLabCut_issues_135-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAE7CMXWVWSHBSO5ZFY4KQKTQYJATLA5CNFSM4GG36BO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGWYTCA-23issuecomment-2D565021064&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=11wEEDBv3Ke3n3b8dICjuQC5vgZ23dfGPax018VOZ2g&m=hR6XltSl9q87qIllNFKna_fUQwBMA6dW9KXFl5W3Nw4&s=v-v5tGkoBbOC0q0SSKheM1Zqn7aRhao2fXevaiX-i0M&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AE7CMXTGSTA4U7A73BIWWSTQYJATLANCNFSM4GG36BOQ&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=11wEEDBv3Ke3n3b8dICjuQC5vgZ23dfGPax018VOZ2g&m=hR6XltSl9q87qIllNFKna_fUQwBMA6dW9KXFl5W3Nw4&s=FHC60BHHH81_GFVfVgrx89R1sOnnoZC945swfOq7iVE&e=>.

Hey, @AlexEMG Dear Alexander, 
I might understand what you mean, since i finally found the directory ' /usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt' in the googledrive. If i understand correctly, does it mean that i put the pose_cfg file with the init_weights changed into this directory and then restart the training? 
If i understan correctly for that, then it comes to another question, i can find the directory ' /usr/local/lib/python3.6', but i can not further find the ' /usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt'. Can you please help me to figure out what the problem would be?
Thanks in advance, 
Shauyin

![Screenshot from 2019-12-12 16-32-24](https://user-images.githubusercontent.com/40397232/70725895-7ac11800-1cfd-11ea-808f-db95c01341c7.png)
