### ISSUE TITLE
Convert to tracklet with `Assemble with identity only` option cause IndexError

### ISSUE THREAD

**Issue by bobfromjapan** [DeepLabCut/DeepLabCut#1350]
**Describe the bug**

Dear DeepLabCut team,

This error is probably caused by making tracklet with the `Assemble with identity only` option enabled in multi-animal tracking with `uniquebodyparts`.

**Desktop (please complete the following information about your system):**
 - OS: Windows10, python3.7
 - DeepLabCut Version: 2.2rc2
 - DeepLabCut mode: multi-animal tracking(identity=True)
 - GPU TYPE: CPU only

**To Reproduce**
1. make multi-animal project with `identity=true` and having some `uniquebodyparts` in `config.yaml`.
2. extract, labeling frames and create training dataset, training and analyze video follow the GUI.
3. For the created pickle file, set `Assemble with identity only` to yes and run `Step2: Convert to Tracklets`.
4. See error:

<details><summary>TRACEBACK</summary><p>

```python

Processing...  C:\Users\Owner\2_mice-tester-2021-06-23\videos\xxxxxx.mov
C:\Users\Owner\2_mice-tester-2021-06-23\videos  already exists!
Analyzing C:\Users\Owner\2_mice-tester-2021-06-23\videos\xxxxxxDLC_dlcrnetms5_2_miceJun23shuffle1_40000.h5
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Owner\pyenvs\dlc37\lib\site-packages\deeplabcut\gui\analyze_videos.py", line 424, in convert2_tracklets
    identity_only=self.identity_toggle.GetStringSelection() == "Yes",
  File "C:\Users\Owner\pyenvs\dlc37\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 1490, in convert_detections2tracklets
    ass.assemble()
  File "C:\Users\Owner\pyenvs\dlc37\lib\site-packages\deeplabcut\pose_estimation_tensorflow\lib\inferenceutils.py", line 721, in assemble
    assemblies, unique = self._assemble(data_dict, i)
  File "C:\Users\Owner\pyenvs\dlc37\lib\site-packages\deeplabcut\pose_estimation_tensorflow\lib\inferenceutils.py", line 628, in _assemble
    ass.add_joint(joint)
  File "C:\Users\Owner\pyenvs\dlc37\lib\site-packages\deeplabcut\pose_estimation_tensorflow\lib\inferenceutils.py", line 165, in add_joint
    self.data[joint.label] = *joint.pos, joint.confidence, joint.group
IndexError: index 4 is out of bounds for axis 0 with size 4

```
</p></details>

**Expected behavior**
I think it is caused by trying to add even `uniquebodyparts` to the `Assembly` in the `identity only` condition.

The `Assembly` class that stores the joint is created on line 625 of `inferenceutils.py` with the size `n_multibodyparts`.

```python
ass = Assembly(self.n_multibodyparts)
```

Therefore, I think it should not do `add_joint` for `uniquebodyparts`.

**Screenshots**
If applicable, add screenshots to help explain your problem. (but please post the code output above, not images of code!)

**Additional context**
I have tried a simple trick to solve this problem.
That is to add `and joint.label < self.n_multibodyparts` to line 627 of inferenceutils.py:

```python
for _, group in groups:
    ass = Assembly(self.n_multibodyparts)
    for joint in sorted(group, key=lambda x: x.confidence, reverse=True):
        if joint.confidence >= self.pcutoff and joint.label < self.n_multibodyparts: # HERE!!
            ass.add_joint(joint)
    if len(ass):
        assemblies.append(ass)
        assembled.update(ass._idx)
```

Consider a joint with a label greater than `n_multibodyparts` to be `uniquebodyparts`, and do not do `ass.add_joint(joint)` under this condition.
This fix seems to work fine for me.
However, I'm not sure exactly what the correct `assemble with identity only` behavior is, so this refinement is just an idea!

Thank you in advance!

**Comment by jeylau** [comment]
Once again, thanks for the very detailed bug report @bobfromjapan! And your fix is spot on! So please, do not hesitate to PR your change and I'll review it! 😎

**Comment by bobfromjapan** [comment]
Thank you for your reply, @jeylau !

I'm glad my fix seems to help! I'll send a PR soon!
