### ISSUE TITLE
Training model with Pairwise loss raises KeyError accessing pairwise_targets object Batch

### ISSUE THREAD

**Issue by aiporre** [DeepLabCut/DeepLabCut#1352]
First at all, thank you very much for the incredible work!

**Describe the bug**
Batch variable is list and fails KeyError is rised at line `deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py  at  line 311, in train pairwise_targets = batch[Batch.pairwise_targets]`

**Desktop (please complete the following information about your system):**
 - OS: [e.g. Windows10, MacOS version, Linux version, etc.]
 - DeepLabCut Version [e.g. 22] (please check with ``import deeplabcut``, ``deeplabcut.__version__``)
 - DeepLabCut mode, i.e. single animal tracking, multi-animal tracking, 3D tracking.
 - GPU TYPE: (or CPU only)?

**To Reproduce**
Steps to reproduce the behavior, i.e.:

 1. training a model with single-animal. 
 2. Defined a skeleton on the `config.yaml`. I set the flags of in the `pose_cfg.yaml` like:

<details><summary>pose_cfg.yaml</summary><p>

```bash
pairwise_huber_loss: true
pairwise_predict: true
partaffinityfield_predict: true
```
</p></details>

 3. I have a KeyError:

<details><summary>TRACEBACK</summary><p>

```python
Traceback (most recent call last):
  File "main.py", line 886, in onTrainNetwork
    saveiters=pose_config['save_iters'])
  File "C:\Users\XYZ\Anaconda3\envs\xyz\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 193, in train_network
    raise e
  File "C:\Users\XYZ\Anaconda3\envs\xyz\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 189, in train_network
    allow_growth=allow_growth,
  File "C:\Users\XYZ\Anaconda3\envs\xyz\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py", line 178, in train
    losses = pose_net(cfg).train(batch)
  File "C:\Users\XYZ\Anaconda3\envs\xyz\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py", line 311, in train
    pairwise_targets = batch[Batch.pairwise_targets]
KeyError: <Batch.pairwise_targets: 5>
```
</p></details>

If I print Batch, I get a list:

<details><summary>My Print</summary><p>

```python 
> print(''+++++>>>>", list(Batch))
OUTS:
+++++>>>> [<Batch.inputs: 0>, <Batch.part_score_targets: 1>, <Batch.part_score_weights: 2>, <Batch.locref_targets: 3>, <Batch.locref_mask: 4>, <Batch.pairwise_targets: 5>, <Batch.pairwise_mask: 6>, <Batch.data_item: 7>]
> print("+++++>>>>", Batch)
OUTS:
+++++>>>> <enum 'Batch'>
```
</p></details>

**Expected behavior**
Maybe read the element create object attribute..

**Screenshots**
NA
**Additional context**
NA

**Comment by jeylau** [comment]
Hello @aiporre, this is expected if you try to train a single-animal project while messing with the config file so it resembles the multi-animal settings. The safe way to do it is to create a multi-animal project (defining only one individual), which sets in place important parts of the workflow (training and batch specs, notably) 😊

**Comment by aiporre** [comment]
Thanks for the quick reply! Alright I get it, sorry for the noise

**Comment by jeylau** [comment]
No worries, do not hesitate to ask! That part of the docs may be of interest https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/convert_maDLC.md
