### ISSUE TITLE
Reinstalling DeepLabCut - How to Uninstall?

### ISSUE THREAD

**Issue by Apathion** [DeepLabCut/DeepLabCut#1354]
It seems like I messed up my installation on a new computer. Now I want to clean it all up by uninstalling everything. 
Is there a straight-forward way besides just putting everything in the bin?

**Comment by jeylau** [comment]
Do not put anything into the trash. Worst case, just run `conda remove --name DLC-CPU --all` to delete the conda environment; note that this would force you to re-create one from one afterwards.
Another option is to use `conda env update --file DLC-CPU.yaml --prune`: this will set your conda environment to the state defined in the configuration file while removing superfluous dependencies.
Yet another one is to take a look at the history of your environment with `conda list --revisions` and restore it to a version anterior to when you think you messed it up with `conda install --rev REVNUM`.

**Comment by MMathisLab** [comment]
just to add, also you can run `pip uninstall packagename` for any python package.

**Comment by Apathion** [comment]
Thanks for the fast answer you two.
