### ISSUE TITLE
maDLC; how to force tracklets to be N number of animals if one disappears? 

### ISSUE THREAD

**Issue by rachelmill** [DeepLabCut/DeepLabCut#1357]
Hi,

**Your Operating system and DeepLabCut version**

Please complete the following information about your system:

OS: MacOS Catalina
DeepLabCut Version: 2.1.10.4
Anaconda env used: Anaconda-Navigator

**Describe the problem**

I trained the network using a video with 7 fish and included 10 individuals in the config file. After training, I had the network label a video with 8 fish and I am now at the refine tracklets stage. The beginning frames have fish 1-8, but as the video continues sometimes the fish labels for one of the fish will disappear and be replaced with labels from fish 9. I know that the lasso tool can be used to move incorrectly placed labels onto the correct fish, but is there a way to fix the labels on a fish when the correct labels are no longer on the frame and have been replaced by labels for a new individual?

Here are screenshots of two frames where F9 is added.

<img width="1145" alt="Screen Shot 2021-06-25 at 4 10 27 PM" src="https://user-images.githubusercontent.com/86495175/123480203-fe84e180-d5cf-11eb-9823-1c8588a796e1.png">
<img width="1056" alt="Screen Shot 2021-06-25 at 4 10 37 PM" src="https://user-images.githubusercontent.com/86495175/123480233-093f7680-d5d0-11eb-927d-cc4fe88ca08c.png">

Thank you!

**Comment by MMathisLab** [comment]
HI @rachelmill if the animal leaves are returns, unless you can visually ID the animal, there is no way for DLC to know it's the same - i.e., you might know there cannot be a new animal, but sadly DLC doesn't :D. Only in cases where identity is True (and you can label each animal the same way on each frame, is this possible. Otherwise, as you suggest post-hoc clean up is best. 

The only Q I have for @jeylau is if there is a way to force it to be 8, not go to 9 is indeed N-tracks is set to 8.

**Comment by rachelmill** [comment]
Thank you! I have a clarifying question about the post-hoc clean up. The labels for fish 4 have disappeared and labels for fish 9 have appeared. Is there a way to delete the labels for a fish 9 and add back labels for fish 4 (which are no longer shown on the frame) in the refine tracklets GUI?

**Comment by jeylau** [comment]
Hi @rachelmill, I'd encourage you to upgrade your deeplabcut installation with `pip install 'deeplabcut[gui]'==2.2rc2`; tracking has greatly improved since 2.1.10.4, and the reconstruction of animal tracklets notably.

**Comment by backyardbiomech** [comment]
Also, in the refine tracklets gui, can't you lasso the fish 9 tracks, set start and end flags for the frames where the points are on fish 9, and just click on fish 4 (label and line at the top)? It "switches" them, but it should be switching points from fish 9 with NaN from fish 4.

**Comment by MMathisLab** [comment]
To clarify @jeylau comment, if you upgrade, the behavior changes to be what you want!

**Comment by rachelmill** [comment]
Thank you!
