### ISSUE TITLE
ticking *adjust marker size box* interferes with *labeling* and *zoom*  in GUI

### ISSUE THREAD

**Issue by WernTanj** [DeepLabCut/DeepLabCut#136]
windows 7, dlc 2.0.1.

1) select frames to label
2) tick adjust marker size and change it
3) right click on bodypart to label  - not responsive

OR

1) select frames to label
2) right click on first bodypart to label 
3) tick adjust marker size and change it
4) zoom not responsive

**Comment by MMathisLab** [comment]
Duplicate of #129. Closing

**Comment by MMathisLab** [comment]
Yes, dotsize curretnly refers to the plotting for creating videos. But I could pass that to Guo too, good suggestion. I’ll make a note for a future release.
