### ISSUE TITLE
Unable to find video path for analyze videos method

### ISSUE THREAD

**Issue by NeelimaValluru** [DeepLabCut/DeepLabCut#1360]
OS: Windows 10
DeepLabCut Version: Deeplabcut core
Anaconda env used: DLCcore-GPU

I'm getting an error that says the path to my videos is not found while using the analyze_video method. I have checked my path repeatedly and I see that it is correct. 

VideoType = 'avi'
videofile_path = "C:/Users/neelima2/Downloads/54_G21A_EPM_11920.AVI"
deeplabcutcore.analyze_videos(path_config_file,videofile_path,save_as_csv=True, videotype=VideoType)

Error:
No video/s found. Please check your path!

**Comment by backyardbiomech** [comment]
Note that the video file path must be passed as a list, even if it's a single video (see example in the [user guide](https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/standardDeepLabCut_UserGuide.md)). In python, lists are surround by square brackets. 
On windows, you should also use backslashes and add an "r" before the quotes.

```python
VideoType = 'avi'
videofile_path = [r"C:\Users\neelima2\Downloads\54_G21A_EPM_11920.AVI"]
deeplabcutcore.analyze_videos(path_config_file,videofile_path,save_as_csv=True, videotype=VideoType)
```
