### ISSUE TITLE
multi animal tracking; questions on use

### ISSUE THREAD

**Issue by es1223** [DeepLabCut/DeepLabCut#1361]
Thank you for opening this issue!

My enviroments
OS: MaxOS 11.4 Big sur
DeepLabCut Version: DeepLabCut2.2
Anaconda env used:anaconda3
using google Colaboratory 

After I made analyzed video, I also did ....
deeplabcut.create_video_with_all_detections
deeplabcut.convert_detections2tracklets

These two were successfully done without any errors.
Then I did
 deeplabcut.convert_raw_tracks_to_h5(config_path, picklefile)
because I need h5 or csv file to analyze.

But I got an error as below,
===============================================================================
TypeError                                 Traceback (most recent call last)
<ipython-input-62-e9e55437385a> in <module>()
----> 1 deeplabcut.convert_raw_tracks_to_h5(path_config_file, picklefile)

1 frames
/usr/local/lib/python3.7/dist-packages/deeplabcut/refine_training_dataset/tracklets.py in load_tracklets_from_pickle(self, filename, auto_fill)
    229     def load_tracklets_from_pickle(self, filename, auto_fill=True):
    230         self.filename = filename
--> 231         with open(filename, "rb") as file:
    232             tracklets = pickle.load(file)
    233         self._load_tracklets(tracklets, auto_fill)

TypeError: expected str, bytes or os.PathLike object, not list
===============================================================================

Please teach me how I can get cvs file.

**Comment by jeylau** [comment]
The right function to call is `deeplabcut.stitch_tracklets(config_path, pickle_file)`, where `pickle_file` is the path to the file you obtained after `deeplabcut.convert_detections2tracklets`(which ends in _bx.pickle or _el.pickle). You'll then get a h5 data file, which you can convert to csv if needed with `analyze_videos_converth5_to_csv` 😊

**Comment by es1223** [comment]
Thank you for your kind help!
```
I did deeplabcut.stitch_tracklets(config_path, pickle_file), but I got an another error as below...
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-10fa361c282f> in <module>()
----> 1 deeplabcut.stitch_traclets(config_path, pickle_file)

AttributeError: module 'deeplabcut' has no attribute 'stitch_traclets'
```
What's the problem??

**Comment by backyardbiomech** [comment]
You are missing the k in `tracklets`

**Comment by es1223** [comment]
Thank you!
Again I got the same error.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-1b190077b461> in <module>()
----> 1 deeplabcut.stitch_tracklets(config_path, pickle_file)

AttributeError: module 'deeplabcut' has no attribute 'stitch_tracklets'

and another question is...
After I did deeplabcut.convert_detections2tracklets, I got _full.pickle, _meta.pickle and _sk.pickle.
I can't get _bx.pickle or _el.pickle. Is it an error?

**Comment by jeylau** [comment]
The _sk.pickle file isn't an error, I just assumed you had used the box or ellipse tracker; this is the correct file nonetheless.
As for the AttributeError, it must be because your DLC version isn't 2.2. Make sure you do by running pip install 'deeplabcut[gui]'==2.2rc2

**Comment by MMathisLab** [comment]
@es1223 in the future, please fill out the template with the **actual code version**; the template says how to check the version, then this would have saved time for Jessy and Brandon ;) <3

**Comment by es1223** [comment]
Thank you all!
