### ISSUE TITLE
Installation error for setup.py

### ISSUE THREAD

**Issue by obsee** [DeepLabCut/DeepLabCut#1365]
Ubuntu20.04 with Anaconda environment and DeepLabCut 2.2

OS: Ubuntu20.4 LTS
DeepLabCut Version: 2.2
Anaconda env used: DEEPLABCUT.yaml
Problem: 
Installing deeplabcut has no problem
but when I try to install deeplabcut[gui], error occurred.
Failed to build wxpython. is the main issue.
I searched google and doc a lot
But I can't solve this problem.
This was a fresh start from your instruction.

Please help me to set up

Please place code inside this:

<details><summary>Code output</summary><p>

[Please copy/paste the full terminal output of the error here!!!]

</p></details>

**How to Reproduce the problem**

**Screenshots**

**Additional context**

**Comment by MMathisLab** [comment]
https://github.com/DeepLabCut/Docker4DeepLabCut2.0/wiki/ubuntu-20.04-LTS-fresh-install-guide

**Comment by obsee** [comment]
I setup all things by following that guide.
But using ubuntu18.04 or 10.04, produce the same error.
I do not know why..

**Comment by obsee** [comment]
> https://github.com/DeepLabCut/Docker4DeepLabCut2.0/wiki/ubuntu-20.04-LTS-fresh-install-guide

please don't close this issue.
nothing has been sloved.

**Comment by MMathisLab** [comment]
@obsee please note, DLC is provide free, without warranty or guarantee; we cannot serve as a free help desk; I put the resources I can in the issue - I close it so others don't need to spend more time; you are welcome to post back, but this is not a DLC bug.

**Comment by obsee** [comment]
Okay. Dr. Mathis.
If I made you offended, I apologize.
But one thing I tried to do verify is that I did something wrong following
your guide, or there are some issues besides your guide.
Because your post was so confident that there is no problem installing
with any version of ubuntu, tensor flow... so on.
It is really grateful you share your DLD with the community for free.
I'll handle my issue.
Best

*이은이 드림*

*Lee, Eunee MD., Ph.D.*

*Translational Research Assistant Professor*
*Dep. of Anatomy, College of Medicine, Yonsei University*
*Visiting Research Fellow*
*Center for Synaptic Brain Dysfunction, Institute for Basic Science*
*중개연구조교수 해부학교실 연세대학교 의과대학*

*겸임 연구 위원 시냅스 뇌질환 연구단 기초과학연구원*

Tel: 02-2228-0913

ᐧ

2021년 7월 1일 (목) 오후 7:00, Mackenzie Mathis ***@***.***>님이 작성:

**Comment by zhenhuaFu** [comment]
Hey,I meet the same question.My OS is ubuntu 18.04.Maybe u can try.
I delete the old conda env and create a new conda env with python3.7. And conda install wxpython and then pip install deeplabcut[gui].This fixed the bug. PS:I didn't find wxpython with python 3.8.
