### ISSUE TITLE
text labels in frame optional and delete label and re-asign

### ISSUE THREAD

**Issue by WernTanj** [DeepLabCut/DeepLabCut#137]
windows 7 and 10, dlc 2.0.1

It would be great if the text label in the frame would be optional. The text often occludes bodyparts for labeling which makes it difficult to hit the correct spot. 

A bit more difficult to implement but still something to consider in the future would be the option to delete a label  and re-asign it e.g. while clicking through the labels while one bodypart is occluded it can happen that by accident you label a bodypart with the incorrect label name.

**Comment by MMathisLab** [comment]
You can also change the code as you like to hide the labels. 

Re your second point, that is why you can drag the label to a new location... you don’t delete it, you just move it. That would have the same end effect you are asking for.

**Comment by WernTanj** [comment]
re second point - if the bodypart is occluded should I drag the label to the upper corner as in Fiji dlc1? In addition, it is only possible to move the label before selecting a new label and not at a later stage which makes the whole working process inflexible.

**Comment by MMathisLab** [comment]
No, you can right-click and delete it. Yes, that is so one doesn’t accidentally drag an already placed mark. You only add a new point once the placed marker is set in place, then it’s locked. If not, we found it’s easy to mess these up inadvertently, which we felt was worse. You can always load your labels in the refinement GUI and move them around before training if needed...

**Comment by WernTanj** [comment]
ok. Do you mean I can right click the label and delete it? I understand, makes sense that the current solution is better than making it messier.

**Comment by MMathisLab** [comment]
Yes, please click on the Help button in the GUI, which explains these features (also shown in the preprint).
