### ISSUE TITLE
Error extracting frames. 

### ISSUE THREAD

**Issue by NeelimaValluru** [DeepLabCut/DeepLabCut#1370]
OS: Windows/ GeForce 3090 GPU
DeepLabCut Version: Deeplabcutcore
Anaconda env used: DLCcore-GPU

Please place code inside this:

Error:

mjpeg @ 000001ccb6948e00] dqt: 0 quant value
[mjpeg @ 000001ccb6948e00] dqt: 0 quant value
[mjpeg @ 000001ccb6948e00] dqt: 0 quant value
[mjpeg @ 000001ccb6948e00] dqt: 0 quant value
[mjpeg @ 000001ccb6948e00] dqt: 0 quant value

While extracting frames from my AVI video, I'm getting this error and a lot of frames are being skipped. I've tried converting this to an MP4 file and I'm getting the same error. How would I be able to fix this.

**Comment by MMathisLab** [comment]
dlccore is depreciated; please install the latest, `pip install 'deeplabcut[gui]'==2.2rc3 ` which supports TF2 and your GPU.

more info here: http://www.mackenziemathislab.org/deeplabcutblog

**Comment by NeelimaValluru** [comment]
I'm getting an error that says no module named tensorflow is available. Do I have to get tensorflow separately or is it installed with the DEEPLABCUT conda environment.

**Comment by NeelimaValluru** [comment]
I'm using the DEEPLABCUT conda environment and I originally got an error that there was no module named tensorflow while trying to import deeplabcut in ipython. So I installed tensorflow used "conda install tensorflow". Now im getting the following error: type object 'h5py.h5.H5PYConfig' has no attribute '__reduce_cython__'

**Comment by backyardbiomech** [comment]
tensorflow should have installed with deeplabcut, and I don't think you want the standard conda version.

Try:

```
conda uninstall tensorflow
```
Once that's done, and still in your env

```
pip install deeplabcut[gui]==2.2rc3
```

Notice on windows, at least on mine, you can't have the single quotes in the pip command. While that's running, you should see tensorflow download and install.

**Comment by NeelimaValluru** [comment]
I'm not getting an AttributeError: module 'brotli' has no attribute 'error'.

**Comment by backyardbiomech** [comment]
Your conda env is scrambled. I would remove the env

```
conda deactivate
conda env remove -n DEEPLABCUT
```

Then download the latest [installation file](http://www.mackenziemathislab.org/s/DEEPLABCUT.yaml) - it changed slightly about 2 hours ago.
On my windows computer, I had to edit the last line to remove the single quotes around `deeplabcut[gui]`

+ Assuming you already have a recent driver and CUDA installation, remake the env using that new file.
+ Activate the env
+ `conda list` and check if `cudnn` is listed. If not, run `conda install cudnn -c conda-forge`
+ the list should also show tensorflow

**Comment by NeelimaValluru** [comment]
Sorry for the incessant questions. But I'm getting the following error even while attempting to create a new environment

AttributeError: module 'brotli' has no attribute 'error'

failed

CondaEnvException: Pip failed

**Comment by AlexEMG** [comment]
https://stackoverflow.com/questions/61881121/anaconda-error-module-brotli-has-no-attribute-error

**Comment by backyardbiomech** [comment]
That's not a deeplabcut error. I think you have a problem with your base anaconda installation. You should do some more googling, but I did find [this](https://stackoverflow.com/questions/61881121/anaconda-error-module-brotli-has-no-attribute-error).

**Comment by NeelimaValluru** [comment]
I've tried the solutions suggested there. I've also deleted my deeplabcut directory, recloned it and tried to create the conda environment again with the YAML file. I'm still getting 
AttributeError: module 'brotli' has no attribute 'error' 
failed
CondaEnvException: Pip failed
while creating the conda environment. However, the environment still gets created, but it says deeplabcut is not found in the environment. 

Thank you everyone for all your help!

**Comment by MMathisLab** [comment]
@NeelimaValluru not sure what more to suggest, as it seems your python is broken; I would re-install anaconda perhaps, and then just grab the conda file from deeplabcut.org (not need to fully git clone, etc). Maybe this new video can also help: https://www.youtube.com/watch?v=LYYoVTdiRQ8 - I will close for now, since not a DLC issue, but please do come back to the issue and let me know how it goes!

**Comment by NeelimaValluru** [comment]
I redownloaded conda but my original error of dropping frames and 
mjpeg @ 000001ccb6948e00] dqt: 0 quant value
[mjpeg @ 000001ccb6948e00] dqt: 0 quant value
[mjpeg @ 000001ccb6948e00] dqt: 0 quant value
[mjpeg @ 000001ccb6948e00] dqt: 0 quant value
[mjpeg @ 000001ccb6948e00] dqt: 0 quant value
is still there. I'm using the newest dlc.

**Comment by backyardbiomech** [comment]
Glad to hear you got the installation working! But too bad that these errors returned. 

Those mjpeg errors indicate a problem with decoding your video. Deeplabcut uses `ffmpeg` to decode video streams, so I would search for an ffmpeg solution for your specific camera. 

You could try reencoding the videos with ffmpeg - my guess is that you'll get the same error. If you have any software from your cameras that can open the videos and save them out as a different format, try that.

You could also try posting your error and the specific camera model on the [forum](image.sc/tags/deeplabcut) to see if anyone else has run into and solved this issue.

But I'm very confident this is not a deeplabcut issue or bug.
