### ISSUE TITLE
IndexError: list index out of range; increasing_indices = np.argsort([int(m.split("-")[1]) for m in Snapshots]) 208 Snapshots = Snapshots[increasing_indices]

### ISSUE THREAD

**Issue by noraparisi** [DeepLabCut/DeepLabCut#1373]
**OS and DLC Versions**
OS: macOS Catalina
DeepLabCut version: 2.2b8
Anaconda env used: anaconda3, DLC-GPU

**Problem:**
I haven't had any issues analyzing videos using the default pcutoff of 0.6, but once I reduced the pcutoff in the config file, I got an index error in which the list index is out of range. Even after changing the pcutoff value back to 0.6, I keep getting the same error. I didn't change anything else in the config file or any other file, so I'm not sure how this issue arose at this point.

**Code:**
dlc.analyze_videos('/home/tuh18198/DLC/SLF-NP-2021-06-06/config.yaml',['/home/tuh18198/DLC/SLF-NP-2021-06-06/vid_2021-06-29_14-49-03MirrTop.avi'],save_as_csv=True)

**Output:**
IndexError                                Traceback (most recent call last)
<ipython-input-2-ba6d236bffee> in <module>()
----> 1 dlc.analyze_videos('/home/tuh18198/DLC/SLF-NP-2021-06-06/config.yaml',['/home/tuh18198/DLC/SLF-NP-2021-06-06/vid_2021-06-29_14-49-03MirrTop.avi'],save_as_csv=True)

~/.local/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py in analyze_videos(config, videos, videotype, shuffle, trainingsetindex, gputouse, save_as_csv, destfolder, batchsize, cropping, get_nframesfrommetadata, TFGPUinference, dynamic, modelprefix, c_engine, robust_nframes)
    205         snapshotindex = cfg["snapshotindex"]
    206 
--> 207     increasing_indices = np.argsort([int(m.split("-")[1]) for m in Snapshots])
    208     Snapshots = Snapshots[increasing_indices]
    209 

~/.local/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py in <listcomp>(.0)
    205         snapshotindex = cfg["snapshotindex"]
    206 
--> 207     increasing_indices = np.argsort([int(m.split("-")[1]) for m in Snapshots])
    208     Snapshots = Snapshots[increasing_indices]
    209 

IndexError: list index out of range

**How to Reproduce the problem**
1. Edit config file.
2. Change pcutoff to 0.5.
3. Analyze videos.

**Comment by AlexEMG** [comment]
This error suggests that there is no trained model available.

**Comment by MMathisLab** [comment]
This likely means you accidentally deleted a line in your config.yaml file (or edited it), relating to snapsnots...

**Comment by noraparisi** [comment]
This happened even after uploading a backup of the config file with the original pcutoff value... Is it possible there's an error in the packages and I should just update DeepLabCut? There couldn't have been an error in the config file I'm using because it worked to analyze videos previously.

**Comment by MMathisLab** [comment]
It is not a package error, I promise you it's either you moved your project, deleted your models, or wrongly edited config.yam (that being said, you are using a very old version (DeepLabCut version: 2.2b8), I would re-train your model with rc3; there are massive performance improvements, as we show here: http://www.mackenziemathislab.org/deeplabcutblog/2021/4/2/multi-animal-deeplabcut-the-full-22-release)
