### ISSUE TITLE
Accuracy of DLC

### ISSUE THREAD

**Issue by Adhithiyan03** [DeepLabCut/DeepLabCut#1377]
**My operating system is Windows 10 with Anaconda Env and Deeplabcut Version is 2.1.10**

**
I am S Thanikai Adhithiyan, an undergraduate currently interning under Dr Chandramouli Krishnan at the University of Michigan, Ann Arbor. We are working on Gait Analysis using Deeplabcut for generating different angles of the lower limb. We had used the pre-trained model given but the results are not accurate. 

The video generated is missing a lot of markers and getting high variations in the graph we are generating and the error is too high. I have trained with the ResNet_50 model. I have used only the code which is already available in the Deeplabcut package as I just want to learn and validate the model.
Is there any way to improve the pose estimation in giving better results? Could you suggest any better way to improve the estimation?
Similarly, for 3D we are unable to generate the pose-estimation properly.  

I have attached the graph generated along with the 2D and 3D Pose-Estimation video with this mail. I have also attached the graph which we are expecting to generate along with this mail.**

![Deeplabcut 2D](https://user-images.githubusercontent.com/83748642/124345002-a8c5c000-dbf3-11eb-85f0-3bc4a114a883.jpg)

https://user-images.githubusercontent.com/83748642/124345023-c09d4400-dbf3-11eb-9594-10bb85e3a900.mp4

![deeplabcut3D](https://user-images.githubusercontent.com/83748642/124345031-d579d780-dbf3-11eb-9081-b0a433335bab.jpg)

https://user-images.githubusercontent.com/83748642/124345125-79fc1980-dbf4-11eb-9d5b-44f0df328c6b.mp4

**Comment by MMathisLab** [comment]
@Adhithiyan03 please post user questions on the ImageForum here: https://forum.image.sc/tag/deeplabcut
