### ISSUE TITLE
Issue when executing DeepLabCut.label_frames

### ISSUE THREAD

**Issue by davidSafeloc** [DeepLabCut/DeepLabCut#138]
I constantly get this problem and i do not how to solve it.

_This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac._

I'm trying to run the program on my MAC and i get the following error.

I have been following the installation using ANACONDA but i am not able to overcome this problem.

**Comment by davidSafeloc** [comment]
Ok i have overcome this one but i have a new one when selecting  "Load Frames"

Python freezes and i get something like that

_Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9561dc90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x12f752cd8). One of the two will be used. Which one is undefined.

python[1647:53903] -[wxNSApplication _setup:]: unrecognized selector sent to instance 0x7f8ec541dfc0_

**Comment by MMathisLab** [comment]
unfortunately we do not use (support) MacOS, please see our installation guide https://github.com/AlexEMG/DeepLabCut/blob/master/docs/installation.md#first-technical-considerations; however, I know that you need to use pythonw (vs ipython to get wxPython support). https://stackoverflow.com/questions/43480073/anaconda-python-3-6-pythonw-and-python-supposed-to-be-equivalent However, you might need to do so outside of Anaconda.

**Comment by MMathisLab** [comment]
see also this comment: https://github.com/AlexEMG/DeepLabCut/issues/141#issuecomment-453208298
