### ISSUE TITLE
`line 3: 76717 Illegal instruction: 4` -->  2.2rc3 will not install on M1 Macs

### ISSUE THREAD

**Issue by backyardbiomech** [DeepLabCut/DeepLabCut#1380]
**Describe the bug**

Base on my own tests, and two reports on gitter, there is an anaconda conflict between packages on m1 Macs that prevents importing deeplabcut in pythonw. Tested on conda 4.10.1 and 4.10.3, installing python.app from default and conda-forge.

**Desktop (please complete the following information about your system):**
 - OS: macOS Big Sur 11.4
 - DeepLabCut Version 2.2rc3
 - GPU TYPE: M1 Mac ...so?

**To Reproduce**
Steps to reproduce the behavior, i.e.:
1. Download DEEPLABCUT.yaml
2. `conda env create -f DEEPLABCUT.yaml`
3. `condo activate DEEPLABCUT`
3.  `conda install python.app`
4.  pythonw -m deeplabcut
5.  see error below

<details><summary>TRACEBACK</summary><p>

```python

% pythonw -m deeplabcut
/Users/brandonjackson/opt/miniconda3/envs/dlc22rc3/bin/pythonw: line 3: 76717 Illegal instruction: 4  /Users/brandonjackson/opt/miniconda3/envs/dlc22rc3/python.app/Contents/MacOS/python "$@"

```
</p></details>

No deeplabcut GUI shows.  This same error occurs, and pythonw crashes in the terminal back to zsh, when trying to import deeplabcut in pythonw.

**Comment by backyardbiomech** [comment]
Definitely seems a tensor flow issue. I am trying to work through [these instructions](https://github.com/apple/tensorflow_macos/issues/153) to install apple's version of TF 2.5 for arm.

**Comment by backyardbiomech** [comment]
I've spent a few hours on this, and made some progress but can't quite get everything to work. For other's interested, here's what I've figure out.

Prior to dlc 2.2rc3, deeplabcut could install and run in anaconda using rosetta2.
deeplabcut 2.2rc3 requires tensorflow 2.5, but there isn't a rosetta2 emulator version available.

So, you can install miniforge to replace conda, which will then grab non emulated ARM versions of packages (it still uses conda commands) and the apple alpha release of tf 2.5 following [these instructions](https://developer.apple.com/metal/tensorflow-plugin/). But that version of tf won't be recognized by pip when installing deeplabcut and creates a dependency problem.

So I installed what I could of the dlc dependencies via miniforge conda, and the rest via pip.  This let me import deeplabcut in pythonw, but it only imported in light mode. 

I tried to run the test script, but got the very interesting error below. I've never seen a **Mangled stack trace** before.

<details><summary>installation lines I ran</summary>

```python
conda create -n appletf25python39 python=3.9
conda activate appletf25python39
conda install -c apple tensorflow-deps
python -m pip install tensorflow-macos
python -m pip install tensorflow-metal
conda install python.app filterpy ruamel.yaml imgaug numba scikit-image scikit-learn statsmodels tqdm moviepy jupyter nb_conda ffmpeg
python -m pip install tensorpack tf_slim tables
python -m pip install 'deeplabcut[gui]'==2.2rc3 --no-deps
python -m pip install opencv-python-headless # This fails, but opencv is already installed
```

</details>

<details><summary>testscript.py results</summary>

```python
pythonw testscript.py
Init Plugin
Init Graph Optimizer
Init Kernel
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Imported DLC!
On Windows/OSX tensorpack is not tested by default.
CREATING PROJECT
Created "/Users/brandonjackson/Downloads/DeepLabCut-master/examples/TEST-Alex-2021-07-05/videos"
Created "/Users/brandonjackson/Downloads/DeepLabCut-master/examples/TEST-Alex-2021-07-05/labeled-data"
Created "/Users/brandonjackson/Downloads/DeepLabCut-master/examples/TEST-Alex-2021-07-05/training-datasets"
Created "/Users/brandonjackson/Downloads/DeepLabCut-master/examples/TEST-Alex-2021-07-05/dlc-models"
Copying the videos
/Users/brandonjackson/Downloads/DeepLabCut-master/examples/TEST-Alex-2021-07-05/videos/reachingvideo1.avi
Generated "/Users/brandonjackson/Downloads/DeepLabCut-master/examples/TEST-Alex-2021-07-05/config.yaml"

A new project with name TEST-Alex-2021-07-05 is created at /Users/brandonjackson/Downloads/DeepLabCut-master/examples and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
EXTRACTING FRAMES
Config file read successfully.
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 8.53  seconds.
Extracting and downsampling... 256  frames from the video.
256it [00:01, 170.79it/s]
Kmeans clustering ... (this might take a while)
Frames were successfully extracted, for the videos of interest.

You can now label the frames using the function 'label_frames' (if you extracted enough frames for all videos).
CREATING-SOME LABELS FOR THE FRAMES
Plot labels...
Creating images with labels by Alex.
100%|██████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00,  7.68it/s]
If all the labels are ok, then use the function 'create_training_dataset' to create the training dataset!
CREATING TRAININGSET
Downloading a ImageNet-pretrained model from http://download.tensorflow.org/models/resnet_v1_50_2016_08_28.tar.gz....
The training dataset is successfully created. Use the function 'train_network' to start training. Happy training!
CHANGING training parameters to end quickly!
TRAIN
Selecting single-animal trainer
Config:
{'all_joints': [[0], [1], [2], [3]],
 'all_joints_names': ['bodypart1', 'bodypart2', 'bodypart3', 'objectA'],
 'alpha_r': 0.02,
 'batch_size': 1,
 'clahe': True,
 'claheratio': 0.1,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_TESTJul5/TEST_Alex80shuffle1.mat',
 'dataset_type': 'default',
 'decay_steps': 30000,
 'deterministic': False,
 'display_iters': 2,
 'edge': False,
 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]},
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'histeq': True,
 'histeqratio': 0.1,
 'init_weights': '/Users/brandonjackson/opt/miniforge3/envs/appletf25python39/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'lr_init': 0.0005,
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_TESTJul5/Documentation_data-TEST_80shuffle1.pickle',
 'min_input_size': 64,
 'mirror': False,
 'multi_stage': False,
 'multi_step': [[0.001, 5]],
 'net_type': 'resnet_50',
 'num_joints': 4,
 'optimizer': 'sgd',
 'pairwise_huber_loss': False,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'pos_dist_thresh': 17,
 'project_path': '/Users/brandonjackson/Downloads/DeepLabCut-master/examples/TEST-Alex-2021-07-05',
 'regularize': False,
 'rotation': 25,
 'rotratio': 0.4,
 'save_iters': 5,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'sharpen': False,
 'sharpenratio': 0.3,
 'shuffle': True,
 'snapshot_prefix': '/Users/brandonjackson/Downloads/DeepLabCut-master/examples/TEST-Alex-2021-07-05/dlc-models/iteration-0/TESTJul5-trainset80shuffle1/train/snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Batch Size is 1
/Users/brandonjackson/opt/miniforge3/envs/appletf25python39/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1692: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
Metal device set to: Apple M1
2021-07-05 13:18:20.912923: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2021-07-05 13:18:20.913124: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
Loading ImageNet-pretrained resnet_50
2021-07-05 13:18:21.113541: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2021-07-05 13:18:21.113565: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2021-07-05 13:18:21.281575: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2021-07-05 13:18:21.283187: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
2021-07-05 13:18:21.900535: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
2021-07-05 13:18:22.608691: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
2021-07-05 13:18:22.625624: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': '/Users/brandonjackson/Downloads/DeepLabCut-master/examples/TEST-Alex-2021-07-05/dlc-models/iteration-0/TESTJul5-trainset80shuffle1/train/snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'sgd', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'default', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': False, 'pairwise_predict': False, 'all_joints': [[0], [1], [2], [3]], 'all_joints_names': ['bodypart1', 'bodypart2', 'bodypart3', 'objectA'], 'alpha_r': 0.02, 'clahe': True, 'claheratio': 0.1, 'cropratio': 0.4, 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_TESTJul5/TEST_Alex80shuffle1.mat', 'decay_steps': 30000, 'display_iters': 2, 'edge': False, 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]}, 'histeq': True, 'histeqratio': 0.1, 'init_weights': '/Users/brandonjackson/opt/miniforge3/envs/appletf25python39/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt', 'lr_init': 0.0005, 'max_input_size': 1500, 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_TESTJul5/Documentation_data-TEST_80shuffle1.pickle', 'min_input_size': 64, 'multi_stage': False, 'multi_step': [[0.001, 5]], 'net_type': 'resnet_50', 'num_joints': 4, 'pos_dist_thresh': 17, 'project_path': '/Users/brandonjackson/Downloads/DeepLabCut-master/examples/TEST-Alex-2021-07-05', 'rotation': 25, 'rotratio': 0.4, 'save_iters': 5, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'sharpen': False, 'sharpenratio': 0.3, 'covering': True, 'elastic_transform': True, 'motion_blur': True, 'motion_blur_params': {'k': 7, 'angle': (-90, 90)}}
Starting training....
2021-07-05 13:18:22.883015: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
iteration: 2 loss: 1.2472 lr: 0.001
iteration: 4 loss: 0.6408 lr: 0.001
2021-07-05 13:18:28.568851: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.
2021-07-05 13:18:29.023321: W tensorflow/core/kernels/queue_base.cc:277] _0_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
*** Received signal 11 ***
*** BEGIN MANGLED STACK TRACE ***
/Users/brandonjackson/opt/miniforge3/envs/appletf25python39/bin/pythonw: line 3: 98855 Segmentation fault: 11  /Users/brandonjackson/opt/miniforge3/envs/appletf25python39/python.app/Contents/MacOS/python "$@"
(appletf25python39) brandonjackson@Staceys-MacBook-Pro examples % /Users/brandonjackson/opt/miniforge3/envs/appletf25python39/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

</details>

**Conclusions:**

Some of the dependencies just aren't updated to work on ARM natively (see `opencv-python-headless`), and/or this version of tensor flow isn't quite ready for deeplabcut, or I'm missing something obvious which could be very likely. 

For now, M1 Macs might be limited to dlc 2.2rc2 (or 2.1.10.4)

**Comment by MMathisLab** [comment]
Hey Brandon, super sorry - we will also look into this! to note, we did test rc3 with TF2.0 - 2.5, so if an older version works, that works for DLC!

**Comment by backyardbiomech** [comment]
Some of the opencv libraries have been updated for ARM, so I've made some progress.  Based on the following, I've gotten DLC training and video analysis to engage the M1 GPU.  However, there are a few problems:
1. DLC only imports in `lite` mode (no GUIs)
2. any function that engages the GPU triggers a segmentation fault when it finishes:

<details>

```
deeplabcut.evaluate_network(config)
Running  DLC_resnet50_TESTJul12shuffle1_5  with # of trainingiterations: 5
/Users/brandonjackson/opt/miniforge3/envs/tftest/lib/python3.9/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1692: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
Metal device set to: Apple M1
Analyzing data...
5it [00:01,  4.31it/s]
*** Received signal 11 ***
*** BEGIN MANGLED STACK TRACE ***
/Users/brandonjackson/opt/miniforge3/envs/tftest/bin/pythonw: line 3: 49309 Segmentation fault: 11  /Users/brandonjackson/opt/miniforge3/envs/tftest/python.app/Contents/MacOS/python "$@"
(tftest) brandonjackson@Staceys-MacBook-Pro examples % /Users/brandonjackson/opt/miniforge3/envs/tftest/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

</details>

Here's how I got this far:

1. Install homebrew, and once that's installed run `brew install ffmpeg`. For some reason, the ARM capable opencv packages only look for certain libraries in `opt/homebrew/...` I tried creating those directories and shortcuts to conda ffmpeg, but that didn't work. 
2. Install miniforge as described [here](https://github.com/apple/tensorflow_macos/issues/153). It was a little tricky to get the zsh path to see it rather than Miniconda, but there's lots of help online. Basically you have to make sure miniforge installs in the user's opt folder, then manually edit the .zshrc paths from miniconda to miniforge.
3. Once the "sanity checks" pass, don't follow the rest of those directions to install TensorFlow in an env because it clashes with DLC dependencies, rather:

```
conda create -n tftest python=3.9
conda activate tftest
conda install -c apple tensorflow-deps
python -m pip install tensorflow-macos
python -m pip install tensorflow-metal
conda install python.app filterpy ruamel.yaml imgaug numba scikit-image scikit-learn statsmodels tqdm moviepy jupyter nb_conda
python -m pip install tensorpack tf_slim tables
python -m pip install 'deeplabcut[gui]'==2.2rc3 --no-deps
python -m pip install opencv-python-headless
```

4. At that point, deeplabcut imports in pythonw.
5. Everything up until training works. Training produces snapshots (and uses the GPU), but the segmentation error crashes python when the GPU is being released. 
6. Evaluate network give the same error and does not produce any output 
7. Analyze videos works and uses the GPU, produces the h5 and pickle files, but the crashes with the seg fault.

## so what?

If you're desperate to run training and analysis on your M1, this can get you started, but you have to work around the crashes, and will need functioning GUI installation of an older DLC to run in a separate env.  Colab is still probably easier.

**Comment by outlace** [comment]
So will 2.2rc3 work without GPU on M1?
I just need access to the label frames GUI. I have access to a server with GPU to do actual training.
I'm also considering writing an imageJ/FIJI plugin or a Javascript GUI to embed in Jupyter notebook to label images

**Comment by MMathisLab** [comment]
@outlace it's a release candidate so we can work through these things - for the full release we will find a solution; now you can easily install 2.10.4 on an M1, which is the stable release. You are welcome of course to write your own GUI but do be warned for multi-animal things it's not the most trivial endeavor.

**Comment by outlace** [comment]
actually I see you all made a Dash app for labeling donated data, the DeepLabCut WebApp. Is there any reason that can't be made to handle personal data and embedded in a Jupyter/Colab notebook?

**Comment by outlace** [comment]
I got 2.2rc3 to install on M1 Macs (without GPU support, unfortunately)

2.2rc3 requires TensorFlow 2.5 which does not work on M1
even through Rosetta, you get an invalid instruction error.
However, according to here: https://github.com/tensorflow/tensorflow/issues/46044
if you compile TensorFlow from source through Rosetta it works.

You can get a pre-compiled wheel of TensorFlow 2.5 that will
work through Rosetta. All the following is done in a Rosetta Terminal.
1. Make sure you have miniconda or anaconda installed
2. `git clone https://github.com/DeepLabCut/DeepLabCut.git`
3. `cd DeepLabCut/conda-environments`
4. Edit DEEPLABCUT.yaml and change python version from 3.8 to 3.7
5. `conda env create -f DEEPLABCUT.yaml`
6. `conda activate deeplabcut`
7. Download the Rosetta pre-compiled TensorFlow 2.5 wheel from here:
https://drive.google.com/file/d/17pSwfoNuyf3YR8vCaVggHeI-pMQ3xL7l/view?usp=sharing
8. `pip install tensorflow-2.4.1-py3-none-any.whl`
 (if that doesn't work, you may first need to do `pip install wheel`)
 Now you should have TensorFlow 2.4 installed
9. `conda install python.app`
10. Run `pythonw -m deeplabcut`
The GUI should appear

**Comment by MMathisLab** [comment]
@outlace thanks! note any TF2 is possible; we unpinned it in the setup so 2.2 will be any TF2, and of course 3.7 is possible as well.

**Comment by MMathisLab** [comment]
@outlace note that python 3.8 is supported for TF2.5 on M1, but the step 4 is required due to the wheel you give in that link - @outlace could you point me to where you found the link to download the rosetta TF; seems to be a 2.4.1 file

Note the alternative option from [this blog](https://caffeinedev.medium.com/how-to-install-tensorflow-on-m1-mac-8e9b91d93706) is: 

- after activating DEEPLABCUT with `conda activate DEEPLABCUT`,
- run: `conda install -c apple tensorflow-deps`
- then: `pip install tensorflow-macos`
- then: `pip install tensorflow-metal` 
albeit, I did not have success with this path

**Comment by MMathisLab** [comment]
> actually I see you all made a Dash app for labeling donated data, the DeepLabCut WebApp. Is there any reason that can't be made to handle personal data and embedded in a Jupyter/Colab notebook?

correct; that is an active project, see our roadmap: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/roadmap.md

**Comment by MMathisLab** [comment]
See #1430 for resolution (as best we can until TF and Mac plays a little nicer ;)
