### ISSUE TITLE
invalid network type: dlcrnet_ms5

### ISSUE THREAD

**Issue by WeissShahaf** [DeepLabCut/DeepLabCut#1382]
after getting a clean install of DLC,
i can train with any network except dlcrnet.
if i choose it from the gui, i get:
invalid network type: dlcrnet_ms5

looks like it can't find it to download.

**Comment by jeylau** [comment]
Please fill out the issue template, this helps us a lot 😊

**Comment by WeissShahaf** [comment]
unfortunately,  
i uninstalled DLC, and now cannot install it back.
so you can close this issue
