### ISSUE TITLE
2.2rc3 not importing in colab notebook

### ISSUE THREAD

**Issue by neurologic** [DeepLabCut/DeepLabCut#1384]
**Desktop (please complete the following information about your system):**
 - OS: Mac OS 11.1 using Colab notebook in chrome (https://colab.research.google.com/github/AlexEMG/DeepLabCut/blob/master/examples/COLAB_YOURDATA_TrainNetwork_VideoAnalysis.ipynb).
 - DeepLabCut Version : 2.2rc3
 - DeepLabCut mode : multi-animal tracking.
 - GPU TYPE: colab

**To Reproduce**
Steps to reproduce the behavior, i.e.:
1. Start the colab notebook and run cells as directed (including restart runtime)
2. Specify deeplabcut==2.2rc3 (I assumed the deeplabcut[gui] version would not be correct since it needed to be 'light' mode, but I tried that anyway as well and it failed to even install).
3. get to the 'import deeplabcut step'
4. See error:

<details><summary>TRACEBACK</summary><p>

```python

^do not delete the ```python
 
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-cfa4f159dfc5> in <module>()
----> 1 import deeplabcut

4 frames
/usr/local/lib/python3.7/dist-packages/deeplabcut/utils/make_labeled_video.py in <module>()
     28 from matplotlib.animation import FFMpegWriter
     29 from matplotlib.collections import LineCollection
---> 30 from skimage.draw import disk, line_aa
     31 from skimage.util import img_as_ubyte
     32 from tqdm import trange

ImportError: cannot import name 'disk' from 'skimage.draw' (/usr/local/lib/python3.7/dist-packages/skimage/draw/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
--------------------------------------------------------------------------- 
 
do not delete below this line, leave the blank line and the ```

```
</p></details>

**Additional context**
I am trying to merge datasets and train the network using the colab notebook to keep project development rolling while I try to fix my local install on my Windows GPU machine. I seem to have broken my previously working GPU build when I was following instructions to upgrade to 2.2rc3... I am not even sure how to ask for help on that one yet. Working on it. Deleting and re-creating the DEEPLABCUT environment did not fix it. So something must have happened to programs outside the environment.  I think at this point I tried enough things that I need to completely uninstall CUDA, etc and 'start from scratch', which from googling seems like actually a hard thing to do. If you have any good resources to point me to for removing everything associated with the GPU set up in order to start from scratch let me know. Thanks!

**Comment by jeylau** [comment]
Please try `pip install scikit-image --upgrade`; your version is likely too old.

**Comment by neurologic** [comment]
That worked. Thank you!
