### ISSUE TITLE
deeplabcut.evaluate_network() error with dlcrnet_ms5

### ISSUE THREAD

**Issue by blogeman** [DeepLabCut/DeepLabCut#1386]
system: Windows 10
version: 2.2rc3

Hi All,

I'm testing out the new DLCRnet and have run into an issue when attempting to evaluate multiple models. I made multiple shuffles to compare different architectures and all models appear to have trained successfully. For all architectures I have saved multiple snapshots. After training with resnet_152 and efficentnet-b6 I am able to run deeplabcut.evaluate_network() with the config file containing the line "snapshotindex:  all" and successfully compare all snapshots. However, when I try this for the shuffle trained with DLCRnet it will successfully evaluate the first snapshot but then I get error shown below. 

Any ideas what might be tripping this?

To reproduce the error, train a model with dlcrnet_ms5 and save multiple snapshots. Then run deeplabcut.evaluate_network() with the config file containing the line "snapshotindex:  all"

Thanks

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-d8dddb11b5e5> in <module>
----> 1 deeplabcut.evaluate_network(config_path, Shuffles=[0], trainingsetindex=0, plotting=False, show_errors=True, rescale=False)

~\anaconda3\envs\DLC\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\evaluate.py in evaluate_network(config, Shuffles, trainingsetindex, plotting, show_errors, comparisonbodyparts, gputouse, rescale, modelprefix, c_engine)
    560
    561         # TODO: Make this code not so redundant!
--> 562         evaluate_multianimal_full(
    563             config=config,
    564             Shuffles=Shuffles,

~\anaconda3\envs\DLC\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\evaluate_multianimal.py in evaluate_multianimal_full(config, Shuffles, trainingsetindex, plotting, show_errors, comparisonbodyparts, gputouse, modelprefix, c_engine)
    543                         if not os.path.isfile(uncropped_data_path):
    544                             print("Selecting best skeleton...")
--> 545                             crossvalutils._rebuild_uncropped_in(evaluationfolder)
    546                             _ = crossvalutils.cross_validate_paf_graphs(
    547                                 config,

~\anaconda3\envs\DLC\lib\site-packages\deeplabcut\pose_estimation_tensorflow\lib\crossvalutils.py in _rebuild_uncropped_in(base_folder)
    261                     metadata = pickle.load(file)
    262                 params = _set_up_evaluation(data)
--> 263                 _rebuild_uncropped_data(
    264                     data, params, full_data_file.replace(".pickle", "_uncropped.pickle")
    265                 )

~\anaconda3\envs\DLC\lib\site-packages\deeplabcut\pose_estimation_tensorflow\lib\crossvalutils.py in _rebuild_uncropped_data(data, params, output_name)
    214                             sl1 = np.ix_(map_[ind1][0], map_[ind2][0])
    215                             sl2 = np.ix_(map_[ind1][1], map_[ind2][1])
--> 216                             mask = costs_pred[n]["m1"][sl2] > costs[n]["m1"][sl1]
    217                             if mask.any():
    218                                 inds_lin = (sl1[0] * n_individuals + sl1[1])[mask]

IndexError: index 3 is out of bounds for axis 0 with size 3
```

**Comment by blogeman** [comment]
Update:

I tried some troubleshooting. I first created a new training set. I then trained with the following settings to generate 2 snapshots with relatively little training.
`deeplabcut.train_network(config_path, shuffle=0, trainingsetindex=0, max_snapshots_to_keep=2, displayiters=10, saveiters=100, maxiters=200, allow_growth=False, autotune=False, keepdeconvweights=True)`
Evaluating these two snapshots worked just fine. I then ran the same line of code but with increased training.
`deeplabcut.train_network(config_path, shuffle=0, trainingsetindex=0, max_snapshots_to_keep=25, displayiters=10, saveiters=1000, maxiters=50000, allow_growth=False, autotune=False, keepdeconvweights=True)`
Trying to evaluate this triggers an error at the same step but now gives a slightly different IndexError.
`---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-4-ea6546e02c5c> in <module>
----> 1 deeplabcut.evaluate_network(config_path, Shuffles=[0], trainingsetindex=0, plotting=False, show_errors=True, comparisonbodyparts='all', rescale=False)

~\anaconda3\envs\DLC\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\evaluate.py in evaluate_network(config, Shuffles, trainingsetindex, plotting, show_errors, comparisonbodyparts, gputouse, rescale, modelprefix, c_engine)
    560
    561         # TODO: Make this code not so redundant!
--> 562         evaluate_multianimal_full(
    563             config=config,
    564             Shuffles=Shuffles,

~\anaconda3\envs\DLC\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\evaluate_multianimal.py in evaluate_multianimal_full(config, Shuffles, trainingsetindex, plotting, show_errors, comparisonbodyparts, gputouse, modelprefix, c_engine)
    543                         if not os.path.isfile(uncropped_data_path):
    544                             print("Selecting best skeleton...")
--> 545                             crossvalutils._rebuild_uncropped_in(evaluationfolder)
    546                             _ = crossvalutils.cross_validate_paf_graphs(
    547                                 config,

~\anaconda3\envs\DLC\lib\site-packages\deeplabcut\pose_estimation_tensorflow\lib\crossvalutils.py in _rebuild_uncropped_in(base_folder)
    261                     metadata = pickle.load(file)
    262                 params = _set_up_evaluation(data)
--> 263                 _rebuild_uncropped_data(
    264                     data, params, full_data_file.replace(".pickle", "_uncropped.pickle")
    265                 )

~\anaconda3\envs\DLC\lib\site-packages\deeplabcut\pose_estimation_tensorflow\lib\crossvalutils.py in _rebuild_uncropped_data(data, params, output_name)
    214                             sl1 = np.ix_(map_[ind1][0], map_[ind2][0])
    215                             sl2 = np.ix_(map_[ind1][1], map_[ind2][1])
--> 216                             mask = costs_pred[n]["m1"][sl2] > costs[n]["m1"][sl1]
    217                             if mask.any():
    218                                 inds_lin = (sl1[0] * n_individuals + sl1[1])[mask]

IndexError: index 6 is out of bounds for axis 1 with size 6
`

**Comment by arjunt19** [comment]
Hey, I've been getting the same error - did you find any fix?

**Comment by jeylau** [comment]
@blogeman, @arjunt19, I cannot reproduce the issue. Do you have datasets with unique body parts defined in the config.yaml file?

**Comment by blogeman** [comment]
I think I've found the source of the error, not totally sure yet though. The issue is not unique to dlcrnet_ms5. Key point seems to be that every time I evaluate for the very first time everything seems to be in order, but after the first time (created new trainningset, evaluation got interrupted, etc), it always throws an error. I noticed that the 'pose_cfg.yaml' in the test folder is updated during training. Specifically, at the very end of the file is appended text beginning with 'paf_best:' that is not present before the first evaluation is executed.

@arjunt19 Could you check your pose_cfg.yaml and see if this text is there? If so, try deleting it and the lines below. This lets the algorithm compute paf from scratch instead of looking for previously defined values. This hack seems to do the trick for me.

**Comment by AlexEMG** [comment]
Thanks for that detailed description @blogeman.  @jeylau -- can you reproduce that?

**Comment by arjunt19** [comment]
@blogeman Hey thanks for the help! However, those lines aren't present for me, all I see is "partaffinityfield_predict: true
scoremap_dir: test" at the end. The error came up in the same way for me - trying to evaluate the model past the first time results in the error.

**Comment by MMathisLab** [comment]
Hey @blogeman we haven't forgotten - and we believe it's fixed in this branch and is a top priority to merge: https://github.com/DeepLabCut/DeepLabCut/pull/1334 

you are welcome to test of course now; I believe it's stable (but no major promises just quite yet!)

**Comment by blogeman** [comment]
Thanks!!!
