### ISSUE TITLE
needed Hardware spec

### ISSUE THREAD

**Issue by Kim-Gangmin** [DeepLabCut/DeepLabCut#1387]
Hello! I am trying to set up experiment using DeepLabCut.
Your papers are very helpful in analyzing animal behavior.
I get information about spec of GPU, RAM and graphic card at paper. 
However, I don't know spec of CPU, SSD and etc. 
When I trained data set at my computer, it took too much time. 

The computer specs used are as follows:
device name: DESKTOP-68KTCDG
processor: Intel(R) Xeon(R) E-2234 CPU 3.60GHz
RAM: 128GB
Graphic card: GeForce GTX 1660 super

The video properties used are as follows:
video length: 00:20:09
frame width: 1920
frame height: 1080
data rate: 14034kbps
total bit rate: 14229kbps
frame rate: 23.69 frame/s

I want to know spec of CPU, SSD and etc. 
I hope you answer this question.
Thank you for reading this question.

**Comment by MMathisLab** [comment]
Hi @Kim-Gangmin please in the future fill out the template, and also please post on image forum for questions, as we aim to leave github for feature requests and bug reports, etc! Here is the forum: https://forum.image.sc/tag/deeplabcut
Here are our technical considerations: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/installation.md#technical-considerations

Note, the hard drive (SSD) and CPU is really independent, as it's not used much/ is up to you how much data storage you need, etc. We use standard Dell workstations, as discussed in the link above.

Re speed: Your images are very large (1920 by 1080), and indeed **by default we cap the images at 1500** in the `pose_cfg.yaml` file. Also please not videos are not used in training - ONLY the frames you label are used. I would suggest trying to crop them down if you can, as the GPU 1660 is quite small; and minimally, you need to change `pose_cfg.yaml` file to train properly. See **BOX 2** in the Nature Protocols paper and/or here: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/standardDeepLabCut_UserGuide.md#f-create-training-datasets
