### ISSUE TITLE
Spyder is running script but no action is happening 

### ISSUE THREAD

**Issue by LyleSmash** [DeepLabCut/DeepLabCut#1388]
I just downloaded and updated windows 10 anaconda and am using spyder 5.0.3 with python 3.8.8 to try and install deeplabcut. I downloaded deeplabcut.yaml directly from github link. 

I used command 

cd downloads

then

conda env create -f deeplabcut.yaml

The python kernel indicates it is running script but there is no visible activity after 10 minutes. Do you know of any known issues similar to this. 

I have already uninstalled and reinstalled as well as updating spyder directly through the terminal. 

Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: Windows 10
DeepLabCut Version: na
Anaconda env used: na

Please place code inside this:

<details><summary>conda env create -f deeplabcut.yaml</summary><p>

**Screenshots**

![image](https://user-images.githubusercontent.com/87035058/124645968-124b0600-de62-11eb-9716-c95decee270a.png)

**Comment by LyleSmash** [comment]
conda env create -f deeplabcut.yaml

Note: you may need to restart the kernel to use updated packages.
'conda' is not recognized as an internal or external command,
operable program or batch file.

**Comment by LyleSmash** [comment]
I have reinstalled and selected the PATH option and checked them manually in advanced settings. Time elapsed with zero error messages has been 45minutes

**Comment by backyardbiomech** [comment]
You are running that in an ipython console. If spyder has a terminal or command line option, use that. Otherwise, just use the anaconda command line, started as an admin (as described in the installation instructions).

**Comment by LyleSmash** [comment]
Ok thanks. I ran in anaconda command line  and this error was produced 

(base) C:\Users\Lyle Murphy>cd download
The system cannot find the path specified.

(base) C:\Users\Lyle Murphy>cd downloads

(base) C:\Users\Lyle Murphy\Downloads>conda env create -f deeplabcut.yaml

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Lyle Murphy\anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\Users\Lyle Murphy\anaconda3\lib\site-packages\conda_env\cli\main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Users\Lyle Murphy\anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 81, in execute
        spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
      File "C:\Users\Lyle Murphy\anaconda3\lib\site-packages\conda_env\specs\__init__.py", line 43, in detect
        if spec.can_handle():
      File "C:\Users\Lyle Murphy\anaconda3\lib\site-packages\conda_env\specs\yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "C:\Users\Lyle Murphy\anaconda3\lib\site-packages\conda_env\env.py", line 165, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "C:\Users\Lyle Murphy\anaconda3\lib\site-packages\conda_env\env.py", line 142, in from_yaml
        data = yaml_safe_load(yamlstr)
      File "C:\Users\Lyle Murphy\anaconda3\lib\site-packages\conda\common\serialize.py", line 67, in yaml_safe_load
        return yaml.safe_load(string, version="1.2")
      File "C:\Users\Lyle Murphy\anaconda3\lib\site-packages\ruamel_yaml\main.py", line 980, in safe_load
        return load(stream, SafeLoader, version)
      File "C:\Users\Lyle Murphy\anaconda3\lib\site-packages\ruamel_yaml\main.py", line 935, in load
        return loader._constructor.get_single_data()
      File "C:\Users\Lyle Murphy\anaconda3\lib\site-packages\ruamel_yaml\constructor.py", line 109, in get_single_data
        node = self.composer.get_single_node()
      File "C:\Users\Lyle Murphy\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 78, in get_single_node
        document = self.compose_document()
      File "C:\Users\Lyle Murphy\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 101, in compose_document
        node = self.compose_node(None, None)
      File "C:\Users\Lyle Murphy\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 138, in compose_node
        node = self.compose_mapping_node(anchor)
      File "C:\Users\Lyle Murphy\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 218, in compose_mapping_node
        item_value = self.compose_node(node, item_key)
      File "C:\Users\Lyle Murphy\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 136, in compose_node
        node = self.compose_sequence_node(anchor)
      File "C:\Users\Lyle Murphy\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 180, in compose_sequence_node
        node.value.append(self.compose_node(node, index))
      File "C:\Users\Lyle Murphy\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 138, in compose_node
        node = self.compose_mapping_node(anchor)
      File "C:\Users\Lyle Murphy\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 211, in compose_mapping_node
        while not self.parser.check_event(MappingEndEvent):
      File "C:\Users\Lyle Murphy\anaconda3\lib\site-packages\ruamel_yaml\parser.py", line 141, in check_event
        self.current_event = self.state()
      File "C:\Users\Lyle Murphy\anaconda3\lib\site-packages\ruamel_yaml\parser.py", line 577, in parse_block_mapping_key
        raise ParserError(
    ruamel_yaml.parser.ParserError: while parsing a block mapping
      in "<unicode string>", line 26, column 5:
          - pip:
            ^ (line: 26)
    expected <block end>, but found '<scalar>'
      in "<unicode string>", line 27, column 24:
            - 'deeplabcut[gui]'==2.2rc3
                               ^ (line: 27)

`$ C:\Users\Lyle Murphy\anaconda3\Scripts\conda-env-script.py create -f deeplabcut.yaml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\Lyle Murphy\anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\Lyle Murphy\anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\Users\Lyle Murphy\anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\Lyle Murphy\anaconda3\python.exe
               CONDA_ROOT=C:\Users\Lyle Murphy\anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\Lyle Murphy
                     PATH=C:\Users\Lyle Murphy\anaconda3;C:\Users\Lyle
                          Murphy\anaconda3\Library\mingw-w64\bin;C:\Users\Lyle
                          Murphy\anaconda3\Library\usr\bin;C:\Users\Lyle
                          Murphy\anaconda3\Library\bin;C:\Users\Lyle
                          Murphy\anaconda3\Scripts;C:\Users\Lyle
                          Murphy\anaconda3\bin;C:\Users\Lyle Murphy\anaconda3;C:\Users\Lyle
                          Murphy\anaconda3\Library\mingw-w64\bin;C:\Users\Lyle
                          Murphy\anaconda3\Library\usr\bin;C:\Users\Lyle
                          Murphy\anaconda3\Library\bin;C:\Users\Lyle
                          Murphy\anaconda3\Scripts;C:\Users\Lyle
                          Murphy\anaconda3\bin;C:\Users\Lyle
                          Murphy\anaconda3\condabin;C:\Program Files
                          (x86)\PerkinElmerInformatics\ChemOffice2018\ChemScript\Lib;C:\Program
                          Files (x86)\Intel\Intel(R) Management Engine
                          Components\iCLS;C:\Program Files\Intel\Intel(R) Management Engine Comp
                          onents\iCLS;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:
                          \WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C
                          :\Program Files\WireGuard;C:\Users\Lyle Murphy\anaconda3;C:\Users\Lyle
                          Murphy\anaconda3\Library\mingw-w64\bin;C:\Users\Lyle
                          Murphy\anaconda3\Library\usr\bin;C:\Users\Lyle
                          Murphy\anaconda3\Library\bin;C:\Users\Lyle
                          Murphy\anaconda3\Scripts;C:\Users\Lyle Murphy\AppData\Local\Microsoft\
                          WindowsApps;C:\Anaconda\Library\bin\conda.bat;C:\Anaconda\Scripts\cond
                          a.exe;C:\Anaconda\condabin\conda.bat;.
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
               PYTHONPATH=C:\Program Files
                          (x86)\PerkinElmerInformatics\ChemOffice2018\ChemScript\Lib
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\Lyle Murphy\anaconda3
            shell level : 1
       user config file : C:\Users\Lyle Murphy\.condarc
 populated config files : C:\Users\Lyle Murphy\.condarc
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\Lyle Murphy\anaconda3  (writable)
      conda av data dir : C:\Users\Lyle Murphy\anaconda3\etc\conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Lyle Murphy\anaconda3\pkgs
                          C:\Users\Lyle Murphy\.conda\pkgs
                          C:\Users\Lyle Murphy\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Lyle Murphy\anaconda3\envs
                          C:\Users\Lyle Murphy\.conda\envs
                          C:\Users\Lyle Murphy\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.8.8 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]:

**Comment by backyardbiomech** [comment]
Open the DEEPLABCUT.yaml file you downloaded in a text editor. Delete the single quotes around deeplabcut in the last line, save the file, and run the conda create command again.
You currently have:

```
- 'deeplabcut[gui]'==2.2rc3
```

Change that to:

```
- deeplabcut[gui]==2.2rc3
```

**Comment by LyleSmash** [comment]
Thanks you, this worked.
