### ISSUE TITLE
General Question about DLC using Google COLAB 

### ISSUE THREAD

**Issue by Apathion** [DeepLabCut/DeepLabCut#1396]
Hello everyone.
So I finally got my mac running DLC, but as expected, it is taking quite a lot of time to calculate.
Therefore I thought about an input by MMathisLab two weeks ago (https://github.com/DeepLabCut/DeepLabCut/issues/1343#issue-927612925), mentioning Google COLAB.
Well, because we have to work with confidential data, which isn't allowed to be stored anywhere outside of our research-computers, I wanted to ask, if there might be a way to use COLAB without copying the data onto google-servers. 
All I could find (as someone who's not well versed in IT-topics) sounds like I would have to copy our data, but maybe someone here knows a way to use the processing-power of COLAB while looking at data still only stored on my machine?

I whish you all a great weekend and thank you for all the help dring the last weeks!

**Comment by backyardbiomech** [comment]
Please close this issue here and post it to the [forum](image.sc/tags/deeplabcut) since it is a usage question rather than a problem with the deeplabcut software.
