### ISSUE TITLE
Impossible to use dlcrnet_ms5 for creating training dataset.

### ISSUE THREAD

**Issue by DorianBattivelli** [DeepLabCut/DeepLabCut#1399]
Hello, 

I'm using DLC 2.2rc3 on windows 10 for a ma project. 

I can't use the dlcrnet_ms5 network apparently, here the message collab returns: 

![Schermata 2021-07-10 alle 12 39 40](https://user-images.githubusercontent.com/66886884/125160219-0fab2200-e17c-11eb-818f-6e9a7ac1f2c2.png)

I manage to create a training dataset if instead I turn back to resnet network passing resnet_50 in my config file. Have you any idea why I can't use the new network? 

Thank you, 
Best,

**Comment by DorianBattivelli** [comment]
And here what I obtain when I specify the net_type in the command: 

![Schermata 2021-07-10 alle 15 52 28](https://user-images.githubusercontent.com/66886884/125165386-f4014500-e196-11eb-9de0-e5749a310c9e.png)

**Comment by backyardbiomech** [comment]
Please try running `deeplacut._version__` in that notebook to make sure you are using a kernel with 2.2rc3 installed.

**Comment by DorianBattivelli** [comment]
In the colab pipeline where should I run deeplacut._version__?
If I run it after pip install and tensorflow cells, it returns: 
![Schermata 2021-07-10 alle 17 52 15](https://user-images.githubusercontent.com/66886884/125168828-99241980-e1a7-11eb-911c-92dac9fba6e4.png)

**Comment by DorianBattivelli** [comment]
Here the version my colab notebook returns: 
![Schermata 2021-07-10 alle 17 56 04](https://user-images.githubusercontent.com/66886884/125168919-20718d00-e1a8-11eb-875a-4523db92de5b.png)

Is that the good version? How to know if I'm using a kernel?

**Comment by backyardbiomech** [comment]
I forgot the b in deeplabcut

**Comment by DorianBattivelli** [comment]
No prob, rather thank you a lot. 
Indeed the version was 2.1. I'm now trying to specify 2.2rc3 when loading DLC. 
I let you know if it works asap, 

Thanks!

**Comment by DorianBattivelli** [comment]
Well, when I precise import deeplabcut== 2.2rc3, the first cell loads all the dependencies (I think), but then I can't load the tensorflow anymore: 

![Schermata 2021-07-10 alle 19 09 09](https://user-images.githubusercontent.com/66886884/125171053-6df2f780-e1b2-11eb-9314-0ff8f0b0ac24.png)

**Comment by backyardbiomech** [comment]
I'm not sure why, but colab is grabbing the wrong version of `scikit-image` for 2.2rc3.

I just tested this on Colab and it worked for me. Your install frame should be

```
!pip install deeplabcut==2.2rc3 scikit-image==0.17.2

%reload_ext numpy
%reload_ext scipy
%reload_ext matplotlib
%reload_ext mpl_toolkits
```

Then, after restarting the runtime, do

```
import os
os.environ["DLClight"]="True"
import deeplabcut
deeplabcut.__version__
```

And you should be able to get rid of the `tensorflow_version 1.x` now, too.

**Comment by DorianBattivelli** [comment]
Perfect, thank you, indeed, now it works. 

My only doubt is about which network I'm effectively running during the training. 
Cause I see that resnet_50 appears:
![Schermata 2021-07-10 alle 21 56 03](https://user-images.githubusercontent.com/66886884/125175025-c386ce80-e1c9-11eb-943f-57df3525a0c3.png)

In my project folder on Drive, I have: 
In the config file: dlcrnet_ms5
In the pose file: resnet_50

Is that ok to run dlcrnet_ms5 for training? 
In any case, when I try to modify the pose file, colab returns an error when I start to launch the training. 

Thank you for the help, 
Best,
Dorian

**Comment by DorianBattivelli** [comment]
Curious fact: 

My videos have hight resolution (~2000x2000), so that usually I'm constrained to decrease batchsize to 2 even 1 for training to don't saturate de RAM. 

Now, it works with batchsize = 8. Does dlcrnet requires less RAM for analyze? so that  the fact it works with this batchsize could be an indication that I'm indeed running dlcrnet network for training?

**Comment by backyardbiomech** [comment]
With dlcrnet, in `pose_cfg.yaml` the network is still `resnet_50` but you should also see `multi_stage: true`. If you see that, then you're using dlcrnet.

Regarding the size, since you're using maDLC, you ran `deeplabcut.cropimagesandlabels` I hope. If you did, then the images used in training are whatever you cropped to (400x400 by default), and you can use larger batch sizes than without cropping.

And yes, you really should run the cropping function.

**Comment by DorianBattivelli** [comment]
Indeed, I see multistage = True, so it works :)

Curious fact - part 2: Before I needed to do both : cropping + reducing batchsize. Now it seems that only cropping is enough, so much better. 
Thank you very much!
