### ISSUE TITLE
Create training dataset Posixpath Error (full paths required)

### ISSUE THREAD

**Issue by justkittenaround** [DeepLabCut/DeepLabCut#140]
**Ubuntu 16.04.5 LTS, Spyder3, and DeepLabCut 2.0**

**Describe the problem**

- Using Deep lab cut, everything works until: "deeplabcut.create_training_dataset(config_path,num_shuffles=1)"

- I get the error:
deeplabcut.create_training_dataset(config_path,num_shuffles=1)
Traceback (most recent call last):

  File "<ipython-input-22-da345eae6dea>", line 1, in <module>
    deeplabcut.create_training_dataset(config_path,num_shuffles=1)

  File "/usr/local/lib/python3.5/dist-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 292, in create_training_dataset
    auxiliaryfunctions.attempttomakefolder(Path(os.path.join(project_path,str(trainingsetfolder))),recursive=True)

  File "/usr/local/lib/python3.5/dist-packages/deeplabcut/utils/auxiliaryfunctions.py", line 29, in attempttomakefolder
    if os.path.isdir(foldername):

  File "/usr/lib/python3.5/genericpath.py", line 42, in isdir
    st = os.stat(s)

TypeError: argument should be string, bytes or integer, not PosixPath

![dlcerror](https://user-images.githubusercontent.com/36868866/49538453-76b41c00-f899-11e8-8155-3a642b19b800.png)

I have also tried running:
"deeplabcut.create_training_dataset(config_path)"

**Comment by MMathisLab** [comment]
couple things: (1) it needs to be a full path -->`TypeError: argument should be string, bytes or integer, not PosixPath`

i.e. 
![screen shot 2018-12-05 at 10 39 04 pm](https://user-images.githubusercontent.com/28102185/49545695-9cafdf80-f8de-11e8-82b3-8f57e597be51.png)

needs to be `C:/home/user/etc/yourstuff`

next issue you will hit is that it needs to be Python **3.6** so you might want to create a new env and be sure to use: '=`conda create -m dlc2 python=3.6` as we suggest in the user docs. https://github.com/AlexEMG/DeepLabCut/blob/master/docs/installation.md#anaconda

**Comment by justkittenaround** [comment]
Thanks!
