### ISSUE TITLE
Image adjustments in labeling GUI to help the human labeler see low contrast body features

### ISSUE THREAD

**Issue by weertman** [DeepLabCut/DeepLabCut#1402]
**Is your feature request related to a problem? Please describe.**

I have noticed that images when opened in the GUI sometimes look different than when viewed in video. Often this is to the detriment of labeling. Features that are low contrast in videos sometimes become even lower contrast when opened in the GUI. Not sure if I am noticing this only because of how I am recording videos (openCV and pypylon) but it is annoying.

**Describe the solution you'd like**

A slider in the labeling GUI that changes image contrast. 

**Describe alternatives you've considered**

I think maybe also a sharpness slider could help as well. There are a number of image alterations that can be done to change how an image looks. I think the degrees of freedom for what best alteration for a particular problem image would help is difficult to predict. Having the option to do a few simple alterations on the fly to help with labeling could be useful and fun. 

**Additional context**

I wouldn't mind taking a shot at coding this but I am unfamiliar with wxPython and found the GUI code difficult to read. I actually have no idea where in the codebase this code would be inserted. I have found that sometimes using the zoom tool as a 'highlighter' can help me see the low contrast features, this is not a great solution as once you zoom the 'highlighting' effect disappears and you have to guess. We have been trying to train students to label images using deeplabcut and have found it difficult to teach low contrast body feature labeling. Often folks just do a poor guess even when if interrogated the body feature is visible. Unfortunately, data sometimes is just how it is no going back and making sure you record with an extra lamp in corner x. deeplabcut is actually able to handle labeling low contrast features, it often does worse on them but it still can handle it. If you can label them often so can the model.

**Comment by MMathisLab** [comment]
Hi @weertman I have never noticed this: "I have noticed that images when opened in the GUI sometimes look different than when viewed in video." could you share an image from the raw video and from the GUI-loaded version?

**Comment by weertman** [comment]
![comparing_video_to_GUI_01](https://user-images.githubusercontent.com/86493327/125671077-06e4d896-19ab-438d-9e59-c99c5ea82852.png)

Attached is an example of this. It is not a great example. Just using the windows clip tool on my computer changed what my eyes are seeing. In the GUI the blacks become a little blacker and the low contrast features become subtly more difficult to see. In the video, the tip of the octopuses mantle tip in this frame is easier for me to see than in the GUI. Please trust that there is a difference, any compression makes it more difficult to see. The worst difference is actually between cv2.imshow() during video recording and the deeplabcut GUI. 

![an_alteration_helps](https://user-images.githubusercontent.com/86493327/125672538-3df054fa-54ed-437f-bad5-0442f5e026ca.png)

Here is a example of how altering a low contrast image can help you see the low contrast features. Altering the gamma parameter helped this visualization. After reading about Gamma https://www.cambridgeincolour.com/tutorials/gamma-correction.htm I see that my issue might be a Gamma issue.

**Comment by MMathisLab** [comment]
hi @weertman the larger issue is that you should be able to see what you want to label in the original image, as this is the only input the network gets, i.e., while data augmentation changes image properties, it should be clear to you, by eye, to label. i.e., imagine the scenario where you change gamma in every image to label, do you save this gamma setting and train? This means the network would not work on your original video then... if we don't save, the network can't be asked to really do this - if it's hard for a primate visual system, it's really hard for a NN :D.

I can trust you it seems you can see small differences in the canvas of matplotlib vs. video viewer (but I don't think the raw pixel values are changing?; a simple test on my own data seems they are the same at least - you can test the intensity in photoshop or in python).

**Comment by weertman** [comment]
Ha! yes, I absolutely agree making sure that the data is clean is really important. The example above hurt my soul a little. I am not sure that is the point though of this post. I can still label these images without the transformations it just is more difficult. I am posting here because I just thought I had a neat idea for a feature.  Something to tweak the image to make it easier on the human would be nice so I do not have to get really close to the screen and squint so much. Helping the human labeler seems fine by me. 

Why cannot the network handle a low contrast feature if other features are still visible?  For sure, the gamma transformation cannot be put in the training set. But the gamma transformed picture was gotten from the pixel values of the original image. The NNs definitely perform much worse on the low contrast features, but I have still had some success with it.

I do not know what the GUI is doing under the hood when it is displaying the images. I would assume it is a faithful representation. I do not know where the code is in deeplabcut to read more into it.

**Comment by MMathisLab** [comment]
Hi @weertman I bring up the case example as it's quite relevant to the feature request; namely, we have to decide what happens to the image after adjustments. My long(er) history with DLC tells me that adjusting images then training on really low contrast images is not a good idea. In the backend remember it's transformed to RGB data if it's not already. 

If you want to hack the GUI the code is here: https://github.com/DeepLabCut/DeepLabCut/tree/master/deeplabcut/gui

But, I feel rather strongly that making adjustments in the GUI for ease of the human is in the long run going to lead people down a dark path (pun intended), as the tag line of DLC truly is "if you can see it, you can track it."

**Comment by weertman** [comment]
If you can do image adjustments to help you find a body feature that means the information to find the feature is within the raw pixel values. NNs seem to be able to handle distorted images E.g., image augmentations can help when training a network. of course more easily seen by eye features will be easier for a NN but do we really know that NNs are not capable of learning low contrast body parts? Especially when other adjacent body parts are clearly visible. The models seem to handle occluded parts well enough. 

Low contrast bad is clearly transmitted in your publications. Unfortunately, data often is just what it is. Tools to help when data is dirty and/or you are using a low-quality screen could make labeling more pleasant. If the adjustment must be manual on every image people will only do it if they think it would help.  

I do not agree that providing such a tool will lead humans down the dark path (ha! nice pun). I think reducing tool options along this line of thinking is wrong. Provide folks options, let us learn from our mistakes! Who knows maybe providing such tools can help folks come up with more easily described workflows for labeling blob-like objects (from personal experience, describing the method by which we label the edges of a soft-bodied organism is difficult. We have been trying to teach people and the error bars between humans are pretty astonishing). I do totally get not doing it along lines of it being a low priority. 

--------

I am happy to try hacking it! That GUI code base, to be honest, is pretty intimidating to someone not familiar with wxPython. I have wanted a goal-based reason to learn it for a while so this could be a good one. 

Is the ```labeling_toolbox.py``` a good place to start? Does ```def drawplot(self, img, img_name, itr, index, bodyparts, cmap, keep_view=False)``` initialize the image?

Thanks!

**Comment by MMathisLab** [comment]
You are welcome to disregard my advice as you like, and of course it's open source code, so please go ahead. 🤗 I was just offering my experience to you. Best of luck in your [research](https://experiment.com/projects/understanding-how-octopuses-use-scent-to-find-food), looks interesting. PS - star of DLC is appreciated!

**Comment by weertman** [comment]
starred!

**Comment by backyardbiomech** [comment]
This will be a feature in the new napari-based labelling GUI, I believe.

**Comment by weertman** [comment]
> This will be a feature in the new napari-based labelling GUI, I believe.

tell me more! 

edit: Hey this is pretty cool! nice thanks for the share

**Comment by jeylau** [comment]
@weertman, we've open-sourced a napari-based labeling GUI here https://github.com/DeepLabCut/napari-DeepLabCut. It's out there for alpha testing, but it is smoother and will allow you to adjust images. I'll close this issue, but feel free to raise issues in the other repo :)

**Comment by weertman** [comment]
Awesome! I will definitely check it out!
