### ISSUE TITLE
Unable to install DLC 2.1.10.4 with tensorflow 2.5.0 on windows

### ISSUE THREAD

**Issue by mikailweston** [DeepLabCut/DeepLabCut#1403]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). 
Please fill out the template completely, including the full "TRACEBACK" and input code that you ran to hit this error.

I downloaded the YAML file as per the latest install instructions and attempted to create environment

Please provide the minimal required code to reproduce the error and the full output (please edit ONLY the section below that says `PLACE YOUR CODE HERE!!! `.

**Desktop (please complete the following information about your system):**
 - OS: Windows10
 - DeepLabCut Version [e.g. 22] 2.1.10.4
 - DeepLabCut mode, i.e. single animal tracking, multi-animal tracking, 3D tracking.
 - GPU TYPE: Nvidia 1080Ti. CUDA 11.2 installed

**To Reproduce**
Steps to reproduce the behavior, i.e.:
1. Go to https://github.com/DeepLabCut/DeepLabCut/blob/master/conda-environments/DEEPLABCUT.yaml for latest environment file
2. attempt to install with: 
```
conda env create -f DEEPLABCUT.yaml
```

Tensorflow does not install with this command

3. Attempt to install tensorflow 2.5.0 with pip

4. See error:

<details><summary>TRACEBACK</summary><p>

```python

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
deeplabcut 2.1.10.4 requires numpy~=1.17.3, but you have numpy 1.19.5 which is incompatible.

```
</p></details>

**Expected behavior**
installation of deeplabcut automatically installs tensorflow

**Screenshots**
If applicable, add screenshots to help explain your problem. (but please post the code output above, not images of code!)

**Additional context**

**Comment by MMathisLab** [comment]
2.10.4 does not support TF2.5; right now you can (1) pull conda file from the blog link: http://www.mackenziemathislab.org/deeplabcutblog/ or once you activate the conda file, you need to run: `pip install deeplabcut[gui]==2.2rc3` - see here for the release note! https://github.com/DeepLabCut/DeepLabCut/releases/tag/v2.2rc3

**Comment by MMathisLab** [comment]
cool, thanks @mikailweston - we will also figure out how to deal with the quotes (as the are needed for mac and ubuntu it seems!)
