### ISSUE TITLE
Training network using Colab - Multi animal DLC

### ISSUE THREAD

**Issue by AkshayaVijayareka** [DeepLabCut/DeepLabCut#1404]
Hi all,

I'm trying to get multi animal DLC training set for tracking two mice in a terrarium.

I'm using google colab pro to train the network.

But the training is very slow and stops after 2500 iterations.

I've been following this page to to verify the process.
https://github.com/DeepLabCut/DeepLabCut/blob/master/examples/COLAB_maDLC_TrainNetwork_VideoAnalysis.ipynb

Is there any steps I'm missing ? 
Kindly help me troubleshoot this issue.
Thank you!

Command used:
deeplabcut.create_multianimaltraining_dataset(path_config_file)
deeplabcut.train_network(path_config_file, shuffle=1, displayiters=500, saveiters=3000, maxiters=3000)

**Comment by arjunt19** [comment]
Did you change the runtime type to GPU? Also, deeplabcut.train_network(path_config_file, shuffle=1, displayiters=500, saveiters=3000, maxiters=3000) - maxiters refers to the max number of iterations to train for, if you increase this it will train for more iterations.

**Comment by AkshayaVijayareka** [comment]
> Did you change the runtime type to GPU? Also, deeplabcut.train_network(path_config_file, shuffle=1, displayiters=500, saveiters=3000, maxiters=3000) - maxiters refers to the max number of iterations to train for, if you increase this it will train for more iterations.

Yes the runtime type was GPU. I reduced the maxiters because it was taking to long to process.

**Comment by MMathisLab** [comment]
@AkshayaVijayareka - I can confirm it runs very quickly for me on colab w/GPU; be sure you set max iters to at lest 50K; that should train in about 4-6 hours depending on your image size

**Comment by AkshayaVijayareka** [comment]
> @AkshayaVijayareka - I can confirm it runs very quickly for me on colab w/GPU; be sure you set max iters to at lest 50K; that should train in about 4-6 hours depending on your image size

Thank you! I'll change the max iters. My image size is 512 x 640. Would that affect the training time?

**Comment by MMathisLab** [comment]
well, strictly speaking yes any size affects training time, but that is a reasonable sized frame; maybe this video can help so you can be sure you have similar settings: https://www.youtube.com/watch?v=DRT-Cq2vdWs

**Comment by AkshayaVijayareka** [comment]
> well, strictly speaking yes any size affects training time, but that is a reasonable sized frame; maybe this video can help so you can be sure you have similar settings: https://www.youtube.com/watch?v=DRT-Cq2vdWs

Thank you so much for the clarification!
