### ISSUE TITLE
Interruption during analysis on Colab. 

### ISSUE THREAD

**Issue by DorianBattivelli** [DeepLabCut/DeepLabCut#1406]
Hello, 

I created a maProject, with DLC 2.2rc3 on Windows 10. 
I trained a model with dlcRnet_ms5 over 53k iterations. So far so good. 

I'm now facing issues during the analysis of the videos on Colab. Each video is 20 min long, 45 fps, ~3,5 gb. 
The analysis is interrupted in the middle of the process (~50/60%), so usually after ~2 or 3 hours. 
No message appears (GPU limitation usage or else). It just disconnects and stops there (and I have no warning message to ask me if I'm still there, if I'm a robot..)

At this point I would have 2 questions: 
- Is there a way to resume the analysis without restarting from scratch in order to don't loose what have already been analyzed? 
- What could I do to avoid such interruptions?  

Thank you, 
Best, 
Dorian

**Comment by MMathisLab** [comment]
hi @dorianbattivelli, colab times out if it's not being actively engaged; with a non-Pro account this is ~ every 8 hours; with a pro account (which is around 10 USD a month) you get 24 run times. There is no way to start from a mid-video point. You can chunk your videos to be shorter to likely not hit any interruptions, or use a pro account.

also please note we ask questions do the to user forum, you will get more community engagement there, as this is best for bug reports or feature requests.
