### ISSUE TITLE
Video path does not point to a file -- Extracting frames needs to point to an existing video

### ISSUE THREAD

**Issue by slahmed** [DeepLabCut/DeepLabCut#1407]
**Desktop (please complete the following information about your system):**

- Windows 10Pro 
- DeepLabCut-2.2rc3 through anaconda
- DeepLabCut mode: multi-animal tracking

**To Reproduce
Steps to reproduce the behavior, i.e.:**

- Created a new project and added new videos successfully 
- deeplabcut.extract_frames(config_path,mode='automatic',algo='kmeans',userfeedback=False,crop=True)

**Error code:**
```python
Config file read successfully.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-22-3dca5034b1c2> in <module>
----> 1 deeplabcut.extract_frames(config_path,mode='automatic',algo='kmeans',userfeedback=False,crop=True)

~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\generate_training_dataset\frame_extraction.py in extract_frames(config, mode, algo, crop, userfeedback, cluster_step, cluster_resizewidth, cluster_color, opencv, slider_width, config3d, extracted_cam)
    236
    237                 if opencv:
--> 238                     cap = VideoReader(video)
    239                     nframes = len(cap)
    240                 else:

~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\auxfun_videos.py in __init__(self, video_path)
     20     def __init__(self, video_path):
     21         if not os.path.isfile(video_path):
---> 22             raise ValueError(f'Video path "{video_path}" does not point to a file.')
     23         self.video_path = video_path
     24         self.video = cv2.VideoCapture(video_path)

ValueError: Video path "C:\Users\PhysiozooTest\NOR-SAhmed-2021-07-13\videos\STM_CS-9L_CS-9R_CS-9N_F.mp4" does not point to a file.
```

**Comment by MMathisLab** [comment]
can you post what your config.yaml file contains?

**Comment by AlexEMG** [comment]
Well, for extracting frames, the video `C:\Users\PhysiozooTest\NOR-SAhmed-2021-07-13\videos\STM_CS-9L_CS-9R_CS-9N_F.mp4` should be at that location; otherwise (in case you moved it), you can also change the path accordingly.

**Comment by slahmed** [comment]
Here is my config.yaml file:

    # Project definitions (do not edit)
Task: NOR
scorer: SAhmed
date: Jul13
multianimalproject: true
identity: false

    # Project path (change when moving around)
project_path: C:\Users\PhysiozooTest\Downloads\NOR-SAhmed-2021-07-13

    # Annotation data set configuration (and individual video cropping parameters)
video_sets:
  C:\Users\PhysiozooTest\NOR-SAhmed-2021-07-13\videos\STM_CS-9L_CS-9R_CS-9N_F.mp4:
    crop: 0, 1280, 0, 720
  C:\Users\PhysiozooTest\NOR-SAhmed-2021-07-13\videos\STM_CS-13B_CS-20B_CS-20R_F.mp4:
    crop: 0, 1280, 0, 720
  C:\Users\PhysiozooTest\NOR-SAhmed-2021-07-13\videos\STM_CS-13R_CS-13N_CS-13L_F.mp4:
    crop: 0, 1280, 0, 720
individuals:
- far
- middle
- near
uniquebodyparts:
- leftobj
- rightobj
- topleftcorner
- toprightcorner
multianimalbodyparts:
- snout
- tail
- middlebody
skeleton:
- - snout
  - tailbase
bodyparts: MULTI!
start: 0
stop: 1
numframes2pick: 20

    # Plotting configuration
skeleton_color: black
pcutoff: 0.6
dotsize: 12
alphavalue: 0.7
colormap: rainbow

    # Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 0
default_net_type: dlcrnet_ms5
default_augmenter: multi-animal-imgaug
snapshotindex: -1
batch_size: 8

    # Cropping Parameters (for analysis and outlier frame detection)
cropping: false
croppedtraining: false
    #if cropping is true for analysis, then set the values here:
x1: 0
x2: 640
y1: 277
y2: 624

    # Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 50
- 50
move2corner: true

**Comment by slahmed** [comment]
Ah I've noticed now that for some reason the video path in the config is different- thanks!
