### ISSUE TITLE
OpenCV error during camera calibration in 3Deeplabcut

### ISSUE THREAD

**Issue by DuanWei-fudan** [DeepLabCut/DeepLabCut#1408]
Windows 10 x64, with an Anaconda Env, & DeepLabCut 2.1.8.2
Four cameras

When I calibrated the cameras in the terminal, an error about OpenCV appeared:

Saving intrinsic camera calibration matrices for camera-1 as a pickle file in C:\Users\admin\Test-Mouse1-2021-07-14-3d\camera_matrix
Mean re-projection error for camera-1 images: 0.118 pixels
Saving intrinsic camera calibration matrices for camera-2 as a pickle file in C:\Users\admin\Test-Mouse1-2021-07-14-3d\camera_matrix
Mean re-projection error for camera-2 images: 0.193 pixels
Saving intrinsic camera calibration matrices for camera-3 as a pickle file in C:\Users\admin\Test-Mouse1-2021-07-14-3d\camera_matrix
Mean re-projection error for camera-3 images: 0.090 pixels
Saving intrinsic camera calibration matrices for camera-4 as a pickle file in C:\Users\admin\Test-Mouse1-2021-07-14-3d\camera_matrix
Mean re-projection error for camera-4 images: 0.229 pixels
Computing stereo calibration for
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Anaconda\envs\DLC-CPU\lib\site-packages\deeplabcut\pose_estimation_3d\camera_calibration.py", line 158, in calibrate_cameras
    retval, cameraMatrix1, distCoeffs1, cameraMatrix2, distCoeffs2, R, T, E, F = cv2.stereoCalibrate(objpoints[pair[0]],imgpoints[pair[0]],imgpoints[pair[1]],dist_pickle[pair[0]]['mtx'],dist_pickle[pair[0]]['dist'], dist_pickle[pair[1]]['mtx'], dist_pickle[pair[1]]['dist'],(h,  w),flags = cv2.CALIB_FIX_INTRINSIC)
cv2.error: OpenCV(3.4.15) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-xaf8b7hp\opencv\modules\calib3d\src\calibration.cpp:3129: error: (-2:Unspecified error) in function 'void __cdecl cv::collectCalibrationData(const class cv::_InputArray &,const class cv::_InputArray &,const class cv::_InputArray &,class cv::Mat &,class cv::Mat &,class cv::Mat *,class cv::Mat &)'
>  (expected: 'nimages == (int)imagePoints2.total()'), where
>     'nimages' is 54
> must be equal to
>     '(int)imagePoints2.total()' is 53

So just because of the 4 cameras ? The code don't support over 2 camaras?

**Comment by MMathisLab** [comment]
HI @DuanWei-fudan that is correct, only 4 is supported: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/Overviewof3D.md *but this will change in the future!

**Comment by DuanWei-fudan** [comment]
So if I have 4 cameras to record, and I did anlysis with DeepLabCut from four different views. Is there anything recommended to   reconstruction?  Anipose?
