### ISSUE TITLE
Kernel dies/restarts when starting GUI

### ISSUE THREAD

**Issue by byronrogers73** [DeepLabCut/DeepLabCut#141]
MacOS(HighSierra), Anancoda, DLC 2.0, Chrome

Working on my project in Jupyter on my iMac(intel Ci5, 12GB DDR3) . All was set up as before on my mac laptop that worked fine. When I ran the code 

%gui wx
deeplabcut.label_frames(path_config_file)

I go the following error on my bash command and the Kernel restarts.....

[I 21:22:27.188 NotebookApp] Starting buffering for 42e5c615-a2cb-4c21-a20a-8a3fabd66019:ddc91ee9c16b4f64a7fa05e9716ca05b
[W 21:22:39.161 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20181205211301 (::1) 1.96ms referer=http://localhost:8888/notebooks/anaconda3/envs/DLC/DLC-Biomechanics.ipynb
[I 21:22:39.787 NotebookApp] Adapting to protocol v5.1 for kernel 42e5c615-a2cb-4c21-a20a-8a3fabd66019
2018-12-05 21:23:47.102 python[2209:62292] -[TKApplication transformToForegroundApplication]: unrecognized selector sent to instance 0x7ff94491d180
2018-12-05 21:23:48.189 python[2209:62292] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[TKApplication transformToForegroundApplication]: unrecognized selector sent to instance 0x7ff94491d180'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff50dc559b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff780f7942 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff50e5c974 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff50d3cfe3 ___forwarding___ + 1443
	4   CoreFoundation                      0x00007fff50d3c9b8 _CF_forwarding_prep_0 + 120
	5   libwx_osx_cocoau_core-3.0.0.4.0.dylib 0x000000010c0e6b60 _ZN5wxApp9DoInitGuiEv + 272
	6   libwx_osx_cocoau_core-3.0.0.4.0.dylib 0x000000010c137e9e _ZN5wxApp9OnInitGuiEv + 30
	7   _core.cpython-36m-darwin.so         0x000000010b59b98d _ZN10sipwxPyApp9OnInitGuiEv + 93
	8   libwx_osx_cocoau_core-3.0.0.4.0.dylib 0x000000010c1cdd37 _ZN9wxAppBase10InitializeERiPPw + 135
	9   libwx_osx_cocoau_core-3.0.0.4.0.dylib 0x000000010c13720e _ZN5wxApp10InitializeERiPPw + 222
	10  libwx_baseu-3.0.0.4.0.dylib         0x000000010c8109d2 _Z12wxEntryStartRiPPw + 162
	11  _core.cpython-36m-darwin.so         0x000000010b59aefc _ZN7wxPyApp13_BootstrapAppEv + 460
	12  _core.cpython-36m-darwin.so         0x000000010b59ee14 _ZL26meth_wxPyApp__BootstrapAppP7_objectS0_ + 100
	13  python                              0x0000000108051078 _PyCFunction_FastCallDict + 200
	14  python                              0x000000010812822f call_function + 143
	15  python                              0x0000000108125f56 _PyEval_EvalFrameDefault + 47222
	16  python                              0x0000000108119519 _PyEval_EvalCodeWithName + 425
	17  python                              0x0000000108128e05 _PyFunction_FastCallDict + 373
	18  python                              0x0000000107fcfb90 _PyObject_FastCallDict + 320
	19  python                              0x0000000107ff7168 method_call + 136
	20  python                              0x0000000107fd71fe PyObject_Call + 62
	21  python                              0x0000000108078385 slot_tp_init + 117
	22  python                              0x000000010807c8d1 type_call + 241
	23  python                              0x0000000107fcfb01 _PyObject_FastCallDict + 177
	24  python                              0x0000000108128328 call_function + 392
	25  python                              0x0000000108125f56 _PyEval_EvalFrameDefault + 47222
	26  python                              0x0000000108119519 _PyEval_EvalCodeWithName + 425
	27  python                              0x000000010812869a fast_function + 362
	28  python                              0x000000010812828c call_function + 236
	29  python                              0x0000000108125f56 _PyEval_EvalFrameDefault + 47222
	30  python                              0x0000000108119519 _PyEval_EvalCodeWithName + 425
	31  python                              0x000000010812869a fast_function + 362
	32  python                              0x000000010812828c call_function + 236
	33  python                              0x0000000108125f56 _PyEval_EvalFrameDefault + 47222
	34  python                              0x0000000108119519 _PyEval_EvalCodeWithName + 425
	35  python                              0x0000000108113d39 builtin_exec + 345
	36  python                              0x0000000108051078 _PyCFunction_FastCallDict + 200
	37  python                              0x000000010812822f call_function + 143
	38  python                              0x0000000108125f56 _PyEval_EvalFrameDefault + 47222
	39  python                              0x0000000108119519 _PyEval_EvalCodeWithName + 425
	40  python                              0x000000010812869a fast_function + 362
	41  python                              0x000000010812828c call_function + 236
	42  python                              0x0000000108125f56 _PyEval_EvalFrameDefault + 47222
	43  python                              0x0000000108119519 _PyEval_EvalCodeWithName + 425
	44  python                              0x000000010812869a fast_function + 362
	45  python                              0x000000010812828c call_function + 236
	46  python                              0x0000000108126006 _PyEval_EvalFrameDefault + 47398
	47  python                              0x0000000108119519 _PyEval_EvalCodeWithName + 425
	48  python                              0x0000000108128e05 _PyFunction_FastCallDict + 373
	49  python                              0x0000000107fcfb90 _PyObject_FastCallDict + 320
	50  python                              0x0000000107ff7168 method_call + 136
	51  python                              0x0000000107fd71fe PyObject_Call + 62
	52  python                              0x000000010812614c _PyEval_EvalFrameDefault + 47724
	53  python                              0x0000000108119519 _PyEval_EvalCodeWithName + 425
	54  python                              0x000000010812869a fast_function + 362
	55  python                              0x000000010812828c call_function + 236
	56  python                              0x0000000108126006 _PyEval_EvalFrameDefault + 47398
	57  python                              0x000000010800d80e gen_send_ex + 142
	58  python                              0x000000010811598f builtin_next + 111
	59  python                              0x0000000108051078 _PyCFunction_FastCallDict + 200
	60  python                              0x000000010812822f call_function + 143
	61  python                              0x0000000108125f56 _PyEval_EvalFrameDefault + 47222
	62  python                              0x0000000108119519 _PyEval_EvalCodeWithName + 425
	63  python                              0x000000010812869a fast_function + 362
	64  python                              0x000000010812828c call_function + 236
	65  python                              0x0000000108125f56 _PyEval_EvalFrameDefault + 47222
	66  python                              0x000000010800d80e gen_send_ex + 142
	67  python                              0x000000010811598f builtin_next + 111
	68  python                              0x0000000108051078 _PyCFunction_FastCallDict + 200
	69  python                              0x000000010812822f call_function + 143
	70  python                              0x0000000108125f56 _PyEval_EvalFrameDefault + 47222
	71  python                              0x0000000108119519 _PyEval_EvalCodeWithName + 425
	72  python                              0x000000010812869a fast_function + 362
	73  python                              0x000000010812828c call_function + 236
	74  python                              0x0000000108125f56 _PyEval_EvalFrameDefault + 47222
	75  python                              0x000000010800d80e gen_send_ex + 142
	76  python                              0x000000010811598f builtin_next + 111
	77  python                              0x0000000108051078 _PyCFunction_FastCallDict + 200
	78  python                              0x000000010812822f call_function + 143
	79  python                              0x0000000108125f56 _PyEval_EvalFrameDefault + 47222
	80  python                              0x0000000108119519 _PyEval_EvalCodeWithName + 425
	81  python                              0x0000000108128e05 _PyFunction_FastCallDict + 373
	82  python                              0x0000000107fcfb90 _PyObject_FastCallDict + 320
	83  python                              0x0000000107ff7168 method_call + 136
	84  python                              0x0000000107fd71fe PyObject_Call + 62
	85  python                              0x000000010812614c _PyEval_EvalFrameDefault + 47724
	86  python                              0x000000010800d80e gen_send_ex + 142
	87  python                              0x00000001080510f2 _PyCFunction_FastCallDict + 322
	88  python                              0x000000010812822f call_function + 143
	89  python                              0x0000000108125f56 _PyEval_EvalFrameDefault + 47222
	90  python                              0x00000001081285ec fast_function + 188
	91  python                              0x000000010812828c call_function + 236
	92  python                              0x0000000108125f56 _PyEval_EvalFrameDefault + 47222
	93  python                              0x0000000108119519 _PyEval_EvalCodeWithName + 425
	94  python                              0x000000010801a5ad function_call + 125
	95  python                              0x0000000107fd71fe PyObject_Call + 62
	96  python                              0x000000010812614c _PyEval_EvalFrameDefault + 47724
	97  python                              0x0000000108119519 _PyEval_EvalCodeWithName + 425
	98  python                              0x0000000108128e05 _PyFunction_FastCallDict + 373
	99  python                              0x0000000107fcfb90 _PyObject_FastCallDict + 320
	100 python                              0x00000001081d7306 partial_call + 150
	101 python                              0x0000000107fcfb01 _PyObject_FastCallDict + 177
	102 python                              0x0000000108128328 call_function + 392
	103 python                              0x0000000108125f56 _PyEval_EvalFrameDefault + 47222
	104 python                              0x0000000108128d3f _PyFunction_FastCallDict + 175
	105 python                              0x0000000107fcfb90 _PyObject_FastCallDict + 320
	106 python                              0x0000000107ff7168 method_call + 136
	107 python                              0x0000000107fd71fe PyObject_Call + 62
	108 python                              0x000000010812614c _PyEval_EvalFrameDefault + 47724
	109 python                              0x00000001081285ec fast_function + 188
	110 python                              0x000000010812828c call_function + 236
	111 python                              0x0000000108125f56 _PyEval_EvalFrameDefault + 47222
	112 python                              0x00000001081285ec fast_function + 188
	113 python                              0x000000010812828c call_function + 236
	114 python                              0x0000000108125f56 _PyEval_EvalFrameDefault + 47222
	115 python                              0x00000001081285ec fast_function + 188
	116 python                              0x000000010812828c call_function + 236
	117 python                              0x0000000108125f56 _PyEval_EvalFrameDefault + 47222
	118 python                              0x00000001081285ec fast_function + 188
	119 python                              0x000000010812828c call_function + 236
	120 python                              0x0000000108125f56 _PyEval_EvalFrameDefault + 47222
	121 python                              0x00000001081285ec fast_function + 188
	122 python                              0x000000010812828c call_function + 236
	123 python                              0x0000000108125f56 _PyEval_EvalFrameDefault + 47222
	124 python                              0x0000000108119519 _PyEval_EvalCodeWithName + 425
	125 python                              0x000000010812869a fast_function + 362
	126 python                              0x000000010812828c call_function + 236
	127 python                              0x0000000108125f56 _PyEval_EvalFrameDefault + 47222
	128 python                              0x0000000108119519 _PyEval_EvalCodeWithName + 425
	129 python                              0x0000000108113d39 builtin_exec + 345
	130 python                              0x0000000108051078 _PyCFunction_FastCallDict + 200
	131 python                              0x000000010812822f call_function + 143
	132 python                              0x0000000108125f56 _PyEval_EvalFrameDefault + 47222
	133 python                              0x0000000108119519 _PyEval_EvalCodeWithName + 425
	134 python                              0x000000010812869a fast_function + 362
	135 python                              0x000000010812828c call_function + 236
	136 python                              0x0000000108125f56 _PyEval_EvalFrameDefault + 47222
	137 python                              0x0000000108119519 _PyEval_EvalCodeWithName + 425
	138 python                              0x000000010801a5ad function_call + 125
	139 python                              0x0000000107fd71fe PyObject_Call + 62
	140 python                              0x0000000108198b26 RunModule + 182
	141 python                              0x0000000108197cb4 Py_Main + 3076
	142 python                              0x0000000107fc7c19 main + 313
	143 libdyld.dylib                       0x00007fff78d0e015 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[I 21:23:50.920 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel 42e5c615-a2cb-4c21-a20a-8a3fabd66019 restarted.

**Comment by MMathisLab** [comment]
Yes, the GUIs do not work on MacOS unfortunately. Please see our installation guide that points out that only Ubuntu and Windows can be used.

**Comment by MMathisLab** [comment]
a note to say that we are working on getting it running on MacOS. One tip is if you install DeepLabCut in an Anaconda virtual environment, you may get an error when starting like this: 

> This program needs access to the screen. Please run with a Framework build of python, and only when you are logged in on the main display

if so, you need to use pythonw (vs. ipython or python). In the terminal start: 

```
pythonw
import deeplabcut
```

as of now, DLC fully works on MacOS, except for the GUIs; this is being addressed!
