### ISSUE TITLE
installation not successful

### ISSUE THREAD

**Issue by h1408** [DeepLabCut/DeepLabCut#1412]
OS: Windows 10 Education
DeepLabCut Version: 2.2rc3
Anaconda env used: Ancaonda for Windows

**Describe the problem**
Cannot use GUI after downloading per the instructions for Steps A-D at: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/installation.md

Please place code inside this:

<details><summary>Code output</summary><p>

(DEEPLABCUT) C:\Users\haniyyah\Documents\DeepLabCut>python -m deeplabcut
Traceback (most recent call last):
  File "C:\Users\haniyyah\.conda\envs\DEEPLABCUT\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\haniyyah\.conda\envs\DEEPLABCUT\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\haniyyah\.conda\envs\DEEPLABCUT\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\haniyyah\Documents\DeepLabCut\deeplabcut\__init__.py", line 14, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

</p></details>

**How to Reproduce the problem**
1. Go to 'https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/installation.md', Step 2. 
2. Under section titled 'CPU or GPU' follow steps A-D (in A, download using the git clone command)
3. open anaconda prompt, type 'activate DEEPLABCUT' 
4. cd to the folder called DeepLabCut
5. type 'python -m deeplabcut'

**Comment by MMathisLab** [comment]
seems your installation did not go as planned; I would delete the env and try to built it again; carefully check for any errors in the build. 

conda tips:

https://towardsdatascience.com/manage-your-python-virtual-environment-with-conda-a0d2934d5195

@h1408 you also might try `python3 -m deeplabcut` --- perhaps you have an other python2 installed as well...

**Comment by WeissShahaf** [comment]
i've had the same problem using ubuntu 18.04.
tensorflow and numpy seem to not get along, or wxpython won't install.
the non gui version does install correctly

**Comment by MMathisLab** [comment]
Here are guides to installing on ubuntu: https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html

**Comment by MMathisLab** [comment]
This also seems related to your other issue, ie. https://github.com/DeepLabCut/DeepLabCut/issues/1329 so, I suggest running `python3 -m deeplabcut` to be sure you are calling the correct python version.
