### ISSUE TITLE
No frames to label after extract frame

### ISSUE THREAD

**Issue by tyyin12** [DeepLabCut/DeepLabCut#1415]
OS: Windows 10
DeepLabCut Version: 2.2rc3
Anaconda env used: yes

I was trying to follow along with the project manager GUI tutorial on Youtube, but after the extract frame step, there are no frames to label in the folder. I re-followed the tutorial several times, but there are still no frames extracted. The video is 24 min long. Any help would be much appreciated. Thanks.

**How to Reproduce the problem**
1. open Anaconda Prompt
2. enter: activate DEEPLABCUT
3. enter: python -m deeplabcut
4. in the GUI, create a new project and extract frames with these attributes:
![image](https://user-images.githubusercontent.com/84589354/125755355-07b383d3-2f7a-4578-bb61-e5b93875d3c5.png)

5. no frames extracted to label

**Comment by MMathisLab** [comment]
does the terminal say anything? How does the project folder look, i.e. is there a folder created for that video name?

**Comment by tyyin12** [comment]
> does the terminal say anything? How does the project folder look, i.e. is there a folder created for that video name?

Here is what the terminal says:
![image](https://user-images.githubusercontent.com/84589354/125851693-a84d42f8-e89d-4942-b754-4ffffcdebb0c.png)

there is a folder created for that video name within the labeled-data folder, but when I click into it, no frames exist.

**Comment by backyardbiomech** [comment]
When you click into the folder after clicking `load frames` in the label frames GUI, you won't see anything, just click `Select Folder`. If you click into in the windows file explorer, you should see frames. Unless you don't see them there. If that's the case, post back.

**Comment by tyyin12** [comment]
Awesome! I see the frames now. There are, however, only 20 frames from the select folder. Is this because of the downsampling? If so, how does DeepLabCut determine which frame to use for the user to label and which frame to not use? Thanks!

**Comment by MMathisLab** [comment]
@Potato1214 I recommend reading the Nature Protocols paper - the extraction and labeling is crucial, and you set what to pick in the `config.yaml` file you must edit, and it should be for more than 1 video for a project in general. see here: https://rdcu.be/bHpHN
