### ISSUE TITLE
IndexError when adding unique body parts to existing labels

### ISSUE THREAD

**Issue by arjunt19** [DeepLabCut/DeepLabCut#1417]
Hi, I am trying to add a list of unique body parts to my config.yaml file and then add labels for them in my images. There are other labels already present (for multianimal individuals).

**Desktop (please complete the following information about your system):**
 - Google Colab
 - DeepLabCut Version: 2.2rc2
 - DeepLabCut mode: Multi-animal tracking
 - GPU TYPE: GPU Tesla T4

**To Reproduce**
Steps to reproduce the behavior, i.e.:
Define multianimal labels, label images, then add unique body parts and attempt to label - at this point deeplabcut.label_frames runs into an error.

**Expected behavior**
Ability to add unique body parts

**Screenshots**
[error message](https://pastebin.com/fgATxdYQ)

**Comment by MMathisLab** [comment]
Hi @arjunt19  This is not currently supported; so I don't think it's the expected behavior to not get an `NotImplementedError ` - it is a feature request we can consider, thanks!

**Comment by arjunt19** [comment]
Oh ok, thanks! Is there any way to change the labels file to manually change a multianimal individual's body parts to be unique parts instead? I just don't know how a csv with unique parts looks like, so I don't really know what to change it to even if I can. Thanks for any help!

**Comment by backyardbiomech** [comment]
Create a new maDLC project with one video and some unique body parts. That will create a csv for you to emulate.

**Comment by jeylau** [comment]
This is actually supported since #1273 (which is part of 2.2rc2). I've just tested it by adding `uniquebodyparts` to a multi-animal test project, and it correctly indicated me that a new individual ('single') and new body parts had been detected. I can then proceed to label them and save without errors.
Could you maybe show your config.yaml file? 😊
