### ISSUE TITLE
Error while running refine tracklets in the DLC GUI

### ISSUE THREAD

**Issue by AkshayaVijayareka** [DeepLabCut/DeepLabCut#1418]
I've was able to train the network for 50K iterations in Google Colab. I have trained the model for two animals and tracking four points.

Operating system and DeepLabCut version : Windows 10 ; Ananconda env ; DLC 2.2rc ; Google Colab pro for training dataset

Problem : Issue in refine tracklets step

Error : When feeding the tracklet information in the refine tracklet step I'm getting the following error while running step 1.

Index Error : Boolean index did not match indexed array along dimension 1; dimension is 4 but corresponding Boolean dimension is 12

**Comment by MMathisLab** [comment]
@AkshayaVijayareka please fill out the issue template that is requested; you can edit your post.

**Comment by MMathisLab** [comment]
likely related to https://github.com/DeepLabCut/DeepLabCut/issues/1429 and https://github.com/DeepLabCut/DeepLabCut/issues/1424 namely, training with the wrong version of deeplabcut; be sure you install the correct version in colab, i.e. use this for maDLC with rc3: https://github.com/DeepLabCut/DeepLabCut/blob/master/examples/COLAB_maDLC_TrainNetwork_VideoAnalysis.ipynb
