### ISSUE TITLE
Exporting inference model for use on android

### ISSUE THREAD

**Issue by chris-rogers-anki** [DeepLabCut/DeepLabCut#142]
Would it be possible to export the inference model for use on android/embedded?

**Comment by AlexEMG** [comment]
I'm afraid, I have never looked into this. But would be slow..

**Comment by MMathisLab** [comment]
this could be useful: https://www.tensorflow.org/lite/demo_android

**Comment by MMathisLab** [comment]
I vote to close this issue since there is no movement on it...

**Comment by MMathisLab** [comment]
(please re-open if work starts on it!)
