### ISSUE TITLE
cannot label frames

### ISSUE THREAD

**Issue by WeissShahaf** [DeepLabCut/DeepLabCut#1421]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Your Operating system and DeepLabCut version**

OS: WIN10 
DeepLabCut Version:2.2rc3
Anaconda env used:yes

**Describe the problem**
when trying to save labled frames. i get an error to do with panda tables
A clear and concise description of what the problem is.

Please place code inside this:

<details><summary>Code output</summary><p>

[Please copy/paste the full terminal output of the error here!!!]
Traceback (most recent call last):
  File "H:\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\labeling_toolbox.py", line 938, in saveDataSet
    self.dataFrame.to_hdf(
  File "H:\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\generic.py", line 2700, in to_hdf
    pytables.to_hdf(
  File "H:\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\io\pytables.py", line 311, in to_hdf
    with HDFStore(
  File "H:\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\io\pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "H:\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\compat\_optional.py", line 118, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'tables'.  Use pip or conda to install tables.

</p></details>

**How to Reproduce the problem**
1. Go to python -m deeplabcut
2. Click on 'label'
3. label a frames, save or quit

**Screenshots**

**Additional context**
had alot of trouble installing DLC. many depencencies where contradictory and had to manually install each one that was missing and then the next, and then the next.

in ubuntu. could not install deeplabcut[gui], as tensorflow needs numpy 1.19, and deeplabcut needs numpy 1.17

**Comment by MMathisLab** [comment]
> `ImportError: Missing optional dependency 'tables'. Use pip or conda to install tables.`

if you then install tables, it will work!; note this is a dependency of DLC, so seems your installation is not complete. I would recommend running the test script upon install: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/installation.md

ie here: https://www.youtube.com/watch?v=IOWtKn3l33s

**Comment by WeissShahaf** [comment]
i tried installing tables. it's already there:
Requirement already satisfied: tables in h:\anaconda3\envs\deeplabcut\lib\site-packages (3.6.1)
Requirement already satisfied: numpy>=1.9.3 in h:\anaconda3\envs\deeplabcut\lib\site-packages (from tables) (1.21.0)
Requirement already satisfied: numexpr>=2.6.2 in h:\anaconda3\envs\deeplabcut\lib\site-packages (from tables) (2.7.3)

**Comment by backyardbiomech** [comment]
See #1368. This problem is fixed with the latest yaml file.
