### ISSUE TITLE
KeyError when using convert_detections2tracklets

### ISSUE THREAD

**Issue by arjunt19** [DeepLabCut/DeepLabCut#1429]
Google Colab
DeepLabCut Version: 2.2rc2
Using Colab's Tesla T4 GPU
**Describe the problem**

I created a multianimal project with multianimal body parts and unique body parts. After creating dataset, training, evaluating, and analyzing, a KeyError occurs when convert_detections2tracklets is called after analysis. The videos created from create_video_with_all_detections() are really good, but I need the csv for data analysis.
Please place code inside this:

<details><summary>Code output</summary><p>

```
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/content/drive/MyDrive/ArestyProject/DLCAresty/deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py", line 730, in wrapped
    return i, self._assemble(self[i], i)
  File "/content/drive/MyDrive/ArestyProject/DLCAresty/deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py", line 639, in _assemble
    links = self.extract_best_links(bag, data_dict["costs"], trees)
  File "/content/drive/MyDrive/ArestyProject/DLCAresty/deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py", line 356, in extract_best_links
    lengths = costs[ind]["distance"]
KeyError: 3
"""

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-47-8652b4029fe7> in <module>()
----> 1 deeplabcut.convert_detections2tracklets(config=path_config_file, videos=['/content/drive/MyDrive/arestymedia/Ins-1_03012020_Trim.mp4'], videotype='.mp4',track_method='ellipse', overwrite=True)

6 frames
/content/drive/MyDrive/ArestyProject/DLCAresty/deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py in extract_best_links()
    354             if dets_s is None or dets_t is None:
    355                 continue
--> 356             lengths = costs[ind]["distance"]
    357             if np.isinf(lengths).all():
    358                 continue

KeyError: 3
```

</summary><p>

</p></details>
I think I screwed up the formatting, so here's a pastebin link : https://pastebin.com/iaHkWgKQ

This is the call to the function: `deeplabcut.convert_detections2tracklets(config=path_config_file, videos=['/content/drive/MyDrive/arestymedia/video.mp4'], videotype='.mp4',track_method='ellipse', overwrite=True)`

Thanks for any help!!

**Comment by arjunt19** [comment]
I though it could be due to the fact that I included unique body parts in the skeleton, but even when I removed them and created a new training set. However, an error still persists, yet this time it says:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/content/drive/MyDrive/ArestyProject/DLCAresty/deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py", line 730, in wrapped
    return i, self._assemble(self[i], i)
  File "/content/drive/MyDrive/ArestyProject/DLCAresty/deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py", line 652, in _assemble
    assemblies, assembled = self.build_assemblies(links)
  File "/content/drive/MyDrive/ArestyProject/DLCAresty/deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py", line 490, in build_assemblies
    success = assembly.add_link(link)
  File "/content/drive/MyDrive/ArestyProject/DLCAresty/deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py", line 195, in add_link
    self.add_joint(link.j1)
  File "/content/drive/MyDrive/ArestyProject/DLCAresty/deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py", line 165, in add_joint
    self.data[joint.label] = *joint.pos, joint.confidence, joint.group
IndexError: index 4 is out of bounds for axis 0 with size 4
"""

The above exception was the direct cause of the following exception:

IndexError                                Traceback (most recent call last)
<ipython-input-59-5cfad4d28065> in <module>()
----> 1 deeplabcut.convert_detections2tracklets(config=path_config_file,videos=['/content/drive/MyDrive/arestymedia/Copy of PrL-3_09072020.mp4'], videotype='.mp4',track_method='ellipse')

8 frames
/content/drive/MyDrive/ArestyProject/DLCAresty/deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py in add_joint()
    163         if joint.label in self._visible or joint.label is None:
    164             return False
--> 165         self.data[joint.label] = *joint.pos, joint.confidence, joint.group
    166         self._visible.add(joint.label)
    167         self._idx.add(joint.idx)

IndexError: index 4 is out of bounds for axis 0 with size 4

**Comment by MMathisLab** [comment]
@arjunt19 can you confirm you are using the latest maDLC colab? https://github.com/DeepLabCut/DeepLabCut/blob/master/examples/COLAB_maDLC_TrainNetwork_VideoAnalysis.ipynb

**Comment by arjunt19** [comment]
> @arjunt19 can you confirm you are using the latest maDLC colab? https://github.com/DeepLabCut/DeepLabCut/blob/master/examples/COLAB_maDLC_TrainNetwork_VideoAnalysis.ipynb

omg thank you!! after upgrading to 2.2rc3 it works. Thanks again for the help
