### ISSUE TITLE
DLC Windows 10 Install

### ISSUE THREAD

**Issue by jdabbi** [DeepLabCut/DeepLabCut#143]
I used the WindowsCPU YAML file provided. I have the following error. Can I ignore it or how do I fix it

mkl-random 1.0.1 requires cython, which is not installed.
jupyter-console 6.0.0 has requirement prompt_toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.15 which is incompatible.

Thanks in advance

**Comment by AlexEMG** [comment]
pip install cython

For the jupyter-console, just check it (probably fine), otherwise see e.g. here: https://github.com/jupyter/jupyter_console/issues/158

**Comment by AlexEMG** [comment]
Does it work?
