### ISSUE TITLE
Analyze_videos not analyzing all frames from the video

### ISSUE THREAD

**Issue by RobertoEnrique** [DeepLabCut/DeepLabCut#1433]
Problem: 

I am running the deeplabcut.analyze_videos function on multiple videos and for some reason it is not analyzing all frames. It extracted posture up to 63% in one example, and said that it detected 54558/86679 frames. 

Additional info: training this network took about 7 days (200,000 iterations). 

Any ideas what could be going wrong here?

Thanks,
-Roberto

**Comment by KonradDanielewski** [comment]
Probably video metadata corrupted. Can you try to run `analyze_videos` with `robust_nframes=True`?

**Comment by MMathisLab** [comment]
some helpful answers here too (and agree with @KonradDanielewski - video corruption)

https://github.com/DeepLabCut/DeepLabCut/issues/982#issuecomment-723480607 
https://github.com/DeepLabCut/DeepLabCut/issues/1004
https://github.com/DeepLabCut/DeepLabCut/issues/1052

Please also fill out the template in your original post.

> Additional info: training this network took about 7 days (200,000 iterations).

This means you are using a CPU, not a GPU; a GPU for 200K takes a few hours with rc2.3

**Comment by jeylau** [comment]
@RobertoEnrique, what version of deeplabcut are you using? We had addressed a similar behavior quite a while ago with https://github.com/DeepLabCut/DeepLabCut/pull/1058.
