### ISSUE TITLE
`ImportError: Missing optional dependency 'tables'.  Use pip or conda to install tables.` No data found after labelling frames

### ISSUE THREAD

**Issue by tyyin12** [DeepLabCut/DeepLabCut#1434]
OS: Windows 10
DeepLabCut Version: 2.2rc3
Anaconda env used: yes

After labeling and saving the frames, I proceeded to create a training dataset. However, the output from the terminal says: No data was found! I proceeded to click the check labels, and a message popped up saying: this will now plot the labeled frames after you have finished labeling.  Checking the terminal again, it produced the following result:
![image](https://user-images.githubusercontent.com/84589354/126888875-28fb2b23-4220-4736-819f-653451feeb85.png). I reloaded the video and relabeled the frames, making sure I saved every frame, yet the error occurred again. Any help would be appreciated. Thank you.

**Comment by MMathisLab** [comment]
@Potato1214 - did you visually check the frames?

**Comment by AlexEMG** [comment]
Perhaps randomly label some points in one folder, click save and share what is in the terminal? [I suspect that there will be some cannot save xyz?]. 

Also, note that the ```video_sets``` entry in the config file needs to have corresponding folders in the `labeled-data` folder (and all of the entries need to have labels).

**Comment by tyyin12** [comment]
I visually checked the frames from previous frames and they are all labeled. 
However, one thing I noticed is that when I label a frame and click save, on the bottom of the GUI it says file saved, but in the terminal it produces
![image](https://user-images.githubusercontent.com/84589354/127081701-c6ff199c-0cd4-4e57-8014-31a45465b13a.png)
I then quit deeplabcut and proceed to install tables with `pip install tables`, but it says requirement already satisfied.
![image](https://user-images.githubusercontent.com/84589354/127082061-a8696eb2-1cef-4a3b-b0e0-71e7243a841d.png)

**Comment by MMathisLab** [comment]
Fixed here: https://github.com/DeepLabCut/DeepLabCut/issues/1368

please use the latest yaml file.
