### ISSUE TITLE
mismatch between C/C++ and Windows locale (wxPython related error?)

### ISSUE THREAD

**Issue by clementpouget** [DeepLabCut/DeepLabCut#1436]
Hello,

**Your Operating system and DeepLabCut version**

OS: [Windows 10 Pro Version 10.0.19041 Build 19041]
DeepLabCut Version: [2.2rc3] 
Anaconda env used: yes, conda 4.10.3 (Python 3.8.10)

**Describe the problem**

I am trying to run DLC, but I get an error message every time a GUI window opens up. For example, when trying to use DLC completely with the GUI: 

<details><summary>Code output</summary><p>

(DEEPLABCUT) C:\Users\C4_admin>python -m deeplabcut
2021-07-26 12:36:27.647513: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-07-26 12:36:27.647656: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Starting GUI...
Traceback (most recent call last):
  File "C:\Users\C4_admin\anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\C4_admin\anaconda3\envs\DEEPLABCUT\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\C4_admin\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\__main__.py", line 22, in <module>
    deeplabcut.launch_dlc()
  File "C:\Users\C4_admin\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\launch_script.py", line 45, in launch_dlc
    frame = MainFrame().Show()
  File "C:\Users\C4_admin\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\launch_script.py", line 27, in __init__
    self.SetIcon(wx.Icon(logo))
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(LC_ALL, NULL), "C") == 0" failed at ..\..\src\common\intl.cpp(1579) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!
</p></details>

Or, when working through the command window, the same error pops when I get to the labeling step. I can open the labeling step GUI, click 'Load frames', but when I select the folder where my images are here's what comes up :

<details><summary>Code output</summary><p>
In [6]: deeplabcut.label_frames(config_path)
---------------------------------------------------------------------------
wxAssertionError                          Traceback (most recent call last)
~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\labeling_toolbox.py in browseDir(self, event)
    696                 self.canvas,
    697                 self.toolbar,
--> 698             ) = self.image_panel.drawplot(
    699                 self.img, img_name, self.iter, self.index, self.bodyparts, self.colormap
    700             )

~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\labeling_toolbox.py in drawplot(self, img, img_name, itr, index, bodyparts, cmap, keep_view)
    187             self.axes.set_ylim(ylim)
    188         if self.toolbar is None:
--> 189             self.toolbar = NavigationToolbar(self.canvas)
    190         return (self.figure, self.axes, self.canvas, self.toolbar)
    191

~\anaconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\backends\backend_wx.py in __init__(self, canvas)
   1375     def __init__(self, canvas):
   1376         wx.ToolBar.__init__(self, canvas.GetParent(), -1)
-> 1377         NavigationToolbar2.__init__(self, canvas)
   1378         self.canvas = canvas
   1379         self._idle = True

~\anaconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\backend_bases.py in __init__(self, canvas)
   2634         # This cursor will be set after the initial draw.
   2635         self._lastCursor = cursors.POINTER
-> 2636         self._init_toolbar()
   2637         self._idDrag = self.canvas.mpl_connect(
   2638             'motion_notify_event', self.mouse_move)

~\anaconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\backends\backend_wx.py in _init_toolbar(self)
   1402                 self.AddTool(
   1403                     -1,
-> 1404                     bitmap=_load_bitmap(image_file + ".png"),
   1405                     bmpDisabled=wx.NullBitmap,
   1406                     label=text, shortHelp=text, longHelp=tooltip_text,

~\anaconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\backends\backend_wx.py in _load_bitmap(filename)
   1241         raise IOError('Could not find bitmap file "%s"; dying' % bmpFilename)
   1242
-> 1243     bmp = wx.Bitmap(bmpFilename)
   1244     return bmp
   1245

wxAssertionError: C++ assertion "strcmp(setlocale(LC_ALL, NULL), "C") == 0" failed at ..\..\src\common\intl.cpp(1579) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!

</p></details>

**Additional context**
 I am guessing this is error is coming from wxpython. I believe the provided version with the conda env. was wspython 4.0.x, and I tried updating to 4.1.1, but the error codes stay the same. 
 I haven't the slightest idea how to fix this... Any ideas would be appreciated.

**Comment by clementpouget** [comment]
Sorry I forgot, but to reproduce the issue I just have to run :
"python -m deeplabcut"

**Comment by jeylau** [comment]
Hey @clementpouget, could you tell me if this answer works for you? https://github.com/DeepLabCut/DeepLabCut/issues/682#issuecomment-882325252

**Comment by clementpouget** [comment]
Yep, that fixed it !
I guess with more patience I could have found the answer by searching the closed issues... 
Thanks a bunch anyways ;)

**Comment by clementpouget** [comment]
Hey Jeylau,
the change allows me to open the GUI using "python -m deeplabcut". But this time, when I get to the image labelling step, I get the same error again: 

<details><summary>Code output</summary><p>
(DEEPLABCUT) C:\Users\C4_admin>python -m deeplabcut
2021-07-26 13:07:52.712752: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-07-26 13:07:52.712987: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Starting GUI...
Traceback (most recent call last):
  File "C:\Users\C4_admin\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\labeling_toolbox.py", line 698, in browseDir
    ) = self.image_panel.drawplot(
  File "C:\Users\C4_admin\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\labeling_toolbox.py", line 189, in drawplot
    self.toolbar = NavigationToolbar(self.canvas)
  File "C:\Users\C4_admin\anaconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\backends\backend_wx.py", line 1377, in __init__
    NavigationToolbar2.__init__(self, canvas)
  File "C:\Users\C4_admin\anaconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\backend_bases.py", line 2636, in __init__
    self._init_toolbar()
  File "C:\Users\C4_admin\anaconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\backends\backend_wx.py", line 1404, in _init_toolbar
    bitmap=_load_bitmap(image_file + ".png"),
  File "C:\Users\C4_admin\anaconda3\envs\DEEPLABCUT\lib\site-packages\matplotlib\backends\backend_wx.py", line 1243, in _load_bitmap
    bmp = wx.Bitmap(bmpFilename)
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!
</p></details>

**Comment by MMathisLab** [comment]
@clementpouget there is another issue in your top post:

> Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found

this means you have the wrong CUDA installed; https://deeplabcut.github.io/DeepLabCut/docs/installation.html#gpu-support

and wxPython >4.0.7post2 will cause this issue, so please downgrade: `pip install -U wxPython<4.1.0`

**Comment by clementpouget** [comment]
@MMathisLab I'm not even sure why this computer has any CUDA installed as it has no GPU, so it's a non problem. Thanks for noticing, though.

I decided to reset the computer to factory settings so as to set it up as a 'completely english' computer, since the problems with wxpython only seem to come up when other locales are used, and that worked for me. This is not as satisfying a fix as I would have hoped, but it works so I can't complain !

Thank you both for the help. I'll mark this as closed.
