### ISSUE TITLE
The tag v2.10.2 is v2.1.10.2, isn't it?

### ISSUE THREAD

**Issue by KikuchiMakoto** [DeepLabCut/DeepLabCut#1440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

The tag v2.10.2 is v2.1.10.2, isn't it?
That's all. Thank you.

### Operating System

any

### DeepLabCut version

any

### DeepLabCut mode

single animal

### Device type

any

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hey @KikuchiMakoto, you're correct, this must have been a typo 😅 @MMathisLab, I can delete it, right?

**Comment by MMathisLab** [comment]
sorry, where are you talking about? looks correct to me: https://github.com/DeepLabCut/DeepLabCut/tree/v2.1.10.2

**Comment by jeylau** [comment]
https://github.com/DeepLabCut/DeepLabCut/releases/tag/v2.10.2 :)

**Comment by MMathisLab** [comment]
awe, a duplicate/draft. deleted.

@jeylau can we not have the tag "bug" auto added? for example, this is not a bug; it's a documentation change.
