### ISSUE TITLE
evaluation code incompatible with newest feature of create_multianimal_dataset

### ISSUE THREAD

**Issue by yeshaokai** [DeepLabCut/DeepLabCut#1441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

create_multianimal_dataset now takes training indices and testing indices.  Therefore, training_indices + testing_indices could still be a subset of the CollectedData*.h5.

But according to this https://github.com/DeepLabCut/DeepLabCut/blob/master/deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py#L313

The evaluation iterates throughs all images in CollectedData*.h5.  Should be Data.Index.values[testindices] + Data.Index.values[trainingindices] instead.

### Operating System

Any

### DeepLabCut version

dlc version

### DeepLabCut mode

multi animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by AlexEMG** [comment]
That's not really a problem. Fair enough, if you happen to have tons of images in Data that are neither in the train/test set than re-indexing is advantageous. But for the typical (99.999% of the use cases) that's not the case. So I'd stick with the code as is.
