### ISSUE TITLE
Can new videos be included after having a trained network?

### ISSUE THREAD

**Issue by aXcELLcore** [DeepLabCut/DeepLabCut#1446]
Hello,
I created a project with multiple individuals and I have managed to have a likelihood of 0.9 and it has worked very well, but I wanted to add new videos so that the same network could mark them and these have presented problems.
My question is if despite having a retrained network, new videos can still be added and if this can be done, what would be the way?

What I have done is add the new videos to the project and later labeled the frames of each video, but I don't know how to retrain the network with these new videos or if it is no longer necessary to do so.

**Comment by backyardbiomech** [comment]
Usage issues should be posted on the [forum](image.sc/tags/deeplabcut). 

See the function `deeplabcut.merge_datasets` in the user guide. 

But you don't need to add videos to the project if you just want to analyze them.
