### ISSUE TITLE
no .h5 files created after labelling

### ISSUE THREAD

**Issue by Charlottewiltshire97** [DeepLabCut/DeepLabCut#1447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi DeepLabCut!
Firstly, thank you for taking the time to read this. 

I am trying to train a model on the new version of DLC (2.2rc3). Everything went well and I have labelled all my frames with no issues. However, I have tried create the training dataset (with GUI default choices) and I got an error, no .h5 file. I have checked within the labelled images folder and it has created a .csv with all the co-ordinates but no .h5! Why is this? How can I fix this! I can't train without it!

(I am using the most up to date version of deeplabcut (windows) with a GPU. I have trained multiple times on this laptop using my GPU with no issue)

Charlotte 

### Operating System

operating system: Windows 

### DeepLabCut version

dlc version: 2.2rc3

### DeepLabCut mode

multi animal

### Device type

gpu: NVIDA 

### Steps To Reproduce

1. activate DEEPLABCUT
2. ipython
3. import deeplabcut
4. deeplabcut.launch_dlc()
5. create training dataset (GUI)
6. error:  File C:\Users\cw266\Videos\gorilla_rotations-charlotte-2021-07-01\labeled-data\gorilla1\CollectedData_charlotte.h5 does not exist 
(have checked the folders, it does not exist for any video in the dataset)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
>  labelled images folder and it has created a .csv with all the co-ordinates 

very odd ... I have never heard of this; as typically the csv is made from the H5; there is a helper function; @jeylau although I don't know if it supports maDLC - Jessy could you check so we can help @Charlottewiltshire97 salvage her dataset? 
https://github.com/DeepLabCut/DeepLabCut/blob/dd55f2769de083eeab13f6c86f5a8066247db7cb/deeplabcut/utils/conversioncode.py#L89

But, in general, there were no terminal errors? nothing like a PyTables error while labeling?

**Comment by jeylau** [comment]
I was going to ask about pytables too; I suspect this is related to https://github.com/DeepLabCut/DeepLabCut/issues/1445#issuecomment-890032095.
@Charlottewiltshire97, could you please try the following and let us know?
```
conda uninstall pytables
pip install tables
```

The helper function Mackenzie mentioned can be used for multi-animal projects; note though that if there is indeed something wrong with pytables, you'd need to run the two lines above prior to using the function 😊

**Comment by Charlottewiltshire97** [comment]
Thank you for the quick response!
I tried with the "convertcsv2h5" code before uninstalling/installing but got an error regarding tables. 
So I followed your advice jeylau, uninstalled pytables and installed tables within the environment. 
However now when I try "import deeplabcut" I get the error:
"SystemError: <built-in method __contains__ of dict object at 0x000001534022B900> returned a result with an error set"
any ideas? 

(Thanks in advance!)
```
full error message: 
In [1]: import deeplabcut
2021-08-03 09:22:51.296375: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-08-03 09:22:51.299015: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-cfa4f159dfc5> in <module>
----> 1 import deeplabcut

~\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\__init__.py in <module>
     12
     13 # Suppress tensorflow warning messages
---> 14 import tensorflow as tf
     15
     16 tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)

~\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\__init__.py in <module>
     39 import sys as _sys
     40
---> 41 from tensorflow.python.tools import module_util as _module_util
     42 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader
     43

~\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\__init__.py in <module>
     38 # pylint: disable=wildcard-import,g-bad-import-order,g-import-not-at-top
     39
---> 40 from tensorflow.python.eager import context
     41 from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
     42

~\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\eager\context.py in <module>
     35 from tensorflow.python import pywrap_tfe
     36 from tensorflow.python import tf2
---> 37 from tensorflow.python.client import pywrap_tf_session
     38 from tensorflow.python.eager import executor
     39 from tensorflow.python.eager import monitoring

~\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\client\pywrap_tf_session.py in <module>
     21 # pylint: disable=invalid-import-order,g-bad-import-order, wildcard-import, unused-import
     22 from tensorflow.python import pywrap_tensorflow
---> 23 from tensorflow.python._pywrap_tf_session import *
     24 from tensorflow.python._pywrap_tf_session import _TF_SetTarget
     25 from tensorflow.python._pywrap_tf_session import _TF_SetConfig

ImportError: SystemError: <built-in method __contains__ of dict object at 0x000001534022B900> returned a result with an error set
```

**Comment by Charlottewiltshire97** [comment]
"But, in general, there were no terminal errors? nothing like a PyTables error while labeling?"
^ I did not notice any error messages but I have been having an issue where re-opening the file after I had closed it caused all the labels to be deleted, despite it being saved. It was as if opening it again caused it to re-write. The labels did not show up on the GUI and once I clicked save after re-opening, it deleted anything from the previous marking session.
For example: If I marked frame 1-10, saved and closed that file. I re-open it. The labels do not show for frame 1-10 on the GUI but the co-ordinates are in the .csv file. I then mark frames 11-25 and click save. The .csv will now only have co-ordinates for 11-25, and has deleted 1-10. 
I don't know if it is relevant but I thought I would mention. I never had this problem in this past, although I have updated from DLC-GPU to DEEPLABCUT, so maybe a bug with the new version?

**Comment by backyardbiomech** [comment]
When you load a folder in the label images GUI, it loads from the h5 not the csv. Without an h5 file, it assumes you have not labeled anything, so it creates an empty data frame. It then saves a new csv, overwriting the old one. So that all makes unfortunate sense if you don't have h5 files.

The newer error suggests a corrupted installation environment (you now have compatibility issues between tables and tensorflow). I would suggest installing the new 2.2 in a fresh environment. The tables error has been fixed during install, so that shouldn't come up again.

**Comment by Charlottewiltshire97** [comment]
I managed to fix this by loading the project into colab and running "convertcsv2h5". Thanks for the help!

**Comment by ellamcho** [comment]
Hello, I am experiencing a similar issue except I am not able to generate any csv at all (error says due to FileNotFoundError: [Errno 2] No such file or directory). Does anyone happen to have any insight on this?

**Comment by EnnyvanBeest** [comment]
Hi,
for me the same problem started after I did the "pip install upgrade deeplabcut" yesterday. I noticed no h5 files are saved anymore when I tried to run create_labeled_video, and the error message I got was:  
"Starting to process video: xx.mj2
Loading xx.mj2 and data. 
No unfiltered data file found in yy for video xx and scorer zz. "
The CSV file is saved as usual and the data in it looks good.

My colleague who ran the exact same code without doing the latest upgrade still gets the h5 files and can also create the labeled videos. 
I already tried: 
conda uninstall pytables
pip install tables
but still got no h5 files afterwards. 
Any idea what can cause this?

**Comment by jeylau** [comment]
@EnnyvanBeest, does video analysis return an error? Is this happening with single- or multi-animal projects?

**Comment by EnnyvanBeest** [comment]
Hi Jessy, Thanks for replying so fast. It’s a single animal project. The analysis itself does not give any error. I’m using a trained network. We’re running it as described here: https://github.com/sylviaschroeder/PupilDetection_DLC/wiki. I’ve never had this problem before. Since the last update (I upgraded yesterday) I get no h5 file for both and because of that I can’t run any of the deeplabcut functions that rely on the h5 file. Running it on his computer still works (and he hasn’t done the upgrade).

**Comment by fontaineg** [comment]
Hi, I'm having the same issue - when I save the annotated frame layer only a .csv and .tiff file are generated, no .h5. I tried 

conda uninstall pytables
pip install tables

but still got no h5 files afterwards. @EnnyvanBeest were you able to solve this issue in the end? 

deeplabcut.convertcsvtoh5(config_path) also does not seem to output anything. 

Operating System
Windows

DeepLabCut version
dlc version: 2.3.5

DeepLabCut mode
single animal

Device type
GPU: NVIDA

**Comment by EnnyvanBeest** [comment]
Hi @fontaineg,

It's a while ago but if my memory is correct, I eventually did a clean install of a later version after which it just worked again. I think sometimes there are some problems with back-compatibility, which may be fixed in later versions.

As an intermediate solution back then I did the following:
```
deeplabcut.analyze_videos(config_path,videos,save_as_csv=False)
for thisvideo in videos:
	thisvideo = Path(thisvideo)
	print(thisvideo)
	parent = os.path.dirname(thisvideo)
	print(parent)
	deeplabcut.analyze_videos_converth5_to_csv(parent, videotype=".mj2",listofvideos=False)
```

Hope that helps.
Enny

**Comment by kayjuen** [comment]
Same problem here with the h5 file with deeplabcut 3.0.0rc6. Unable to build skeleton after video analysis. File missing.

**Comment by MMathisLab** [comment]
@kayjuen yes; you need to reinstall the latest from git; you are using a release candidate so its updated very often; https://github.com/DeepLabCut/DeepLabCut/pull/2798 is the fix.

```
conda install -c conda-forge pytables==3.8.0
pip install "git+https://github.com/DeepLabCut/DeepLabCut.git@pytorch_dlc#egg=deeplabcut[gui,modelzoo,wandb]"
