### ISSUE TITLE
(Windows) checkcropping during extract_frames does not correctly display the area that will be cropped

### ISSUE THREAD

**Issue by t-preto** [DeepLabCut/DeepLabCut#145]
Windows 10, DLC 2 in Anaconda Env

When running deeplabcut.extract_frames with crop=True and checkcropping=True, the checkcropping window displays the area to be cropped incorrectly. The boundaries of the area shown are x1, x1+x2, y1, y1+y2, when the area actually cropped during extraction is the area between the two x and y values given in the config file.

**Comment by AlexEMG** [comment]
See: https://github.com/AlexEMG/DeepLabCut/pull/114/files

Should be fixed in latest commit.
