### ISSUE TITLE
Installation error in Conda's YAML file for DLC 2.2rc3 

### ISSUE THREAD

**Issue by peachiia** [DeepLabCut/DeepLabCut#1454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi, I just started learning to use DLC, and I want to run it on my own PC. I've used the YAML file from the [installation](https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/installation.md), which mention to [this](http://www.mackenziemathislab.org/s/DEEPLABCUT.yaml) file. However, during the installation, I got an error that said that there's something wrong with YAML's parser.

So, I've tried editing the YAML myself. 

from
```    
  - pip:
    - 'deeplabcut[gui]'==2.2rc3
```
    
to
```    
  - pip:
    - 'deeplabcut[gui]==2.2rc3'
```
    
And it seems to work just fine. 

However, I'm not sure that it happens only in my environment, or it did happen in other ones too. So, I want to mention it, and please suggest to me if there're other solutions (i.e. My using the wrong version of Conda or something else.)

### Operating System

Windows 10 with Anaconda 

### DeepLabCut version

2.2rc3

### DeepLabCut mode

single animal

### Device type

1x RTX 2070 Super

### Steps To Reproduce

Create CONDA Env using the file from http://www.mackenziemathislab.org/s/DEEPLABCUT.yaml

### Relevant log output

```shell
YAMLException: bad indentation of a sequence entry at line 28, column 24:
   - 'deeplabcut[gui]'==2.2rc3
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@peachiia please use the yaml on the repo, or re-download now; we just updated the code yesterday/today, so we are in the process of cleaning up a few links here and there ;). The conda on the website is now updated, thanks!

**Comment by peachiia** [comment]
@MMathisLab Oh, Thank you very much. : )
