### ISSUE TITLE
Corrupted files in cropped folders of labeled-data

### ISSUE THREAD

**Issue by rachelmill** [DeepLabCut/DeepLabCut#1459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi,

Somehow throughout the training and labeling process some files in the cropped folders within the labeled-data folder have been corrupted. Is there a way to either reencode the photos or to remove the frames from the project?

I found this similar error here: https://github.com/python-pillow/Pillow/issues/5141

Thank you!

### Operating System

operating system
MacOS Catalina

### DeepLabCut version

dlc version
2.2rc2

### DeepLabCut mode

multi animal

### Device type

gpu
Google Colab

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by AlexEMG** [comment]
Can you please post what kind of error/output you get and in what steps? Can you open the images?

**Comment by rachelmill** [comment]
After merging datasets and cropping images and labels, I get an error when running the create_multianimaltraining_dataset function. I am not able to open some of the images in each of the cropped folders in the labeled_data folder. Some of the images still open.
<img width="1222" alt="Screen Shot 2021-08-13 at 6 55 09 PM" src="https://user-images.githubusercontent.com/86495175/129425388-0b0ae0cd-7daa-47f0-8704-4925a1c51d29.png">
Thank you!

**Comment by backyardbiomech** [comment]
You can try to delete the images, then run `deeplabcut.dropannotationfileentriesduetodeletedimages` (see[ here](https://github.com/DeepLabCut/DeepLabCut/blob/bd6add9b41a9a616660ba86282ee1a33bd0e7776/deeplabcut/generate_training_dataset/trainingsetmanipulation.py#L160)) to update the labels.

Make a backup of your project first, though.

**Comment by jeylau** [comment]
Alternatively, you could update to deeplabcut 2.2 where images are no longer pre-cropped (a step that from now on happens in memory during training); this should get rid of the error 😄
