### ISSUE TITLE
installing DeepLabCut: build fail for pandas with Python3.7

### ISSUE THREAD

**Issue by MingdiZheng** [DeepLabCut/DeepLabCut#146]
Hi, 
when i am trying to install DeepLabCut on my Ubuntu System, it always says :Failed building wheel for pandas and error: command 'gcc' failed with exit status 1. I tried many approaches on the website, but they doesn't work. Could somebody hepl me?

Ubuntu 16.04 LTS, with an Anaconda Env,GPU 1080Ti

**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

**Describe the problem**

A clear and concise description of what the problem is.

**How to Reproduce the problem**

**Screenshots**

**Additional context**

**Comment by MingdiZheng** [comment]
also, it says: 
Command "/home/shenduxuexi/anaconda3/envs/DLC/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-r_pmu2cy/pandas/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-7524ubz7/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-r_pmu2cy/pandas/

is there something wrong with pandas?

**Comment by MingdiZheng** [comment]
> Seems you don’t have a compiler; ‘gcc’ can you run ‘ pip install pandas’ without errors?

hi! Thanks for your reply!!
If I input gcc -v, it will show the version of gcc. Like the picture shows:
![image](https://user-images.githubusercontent.com/42430483/49925630-7698c980-fef4-11e8-8b31-5f5d8f40505a.png)
Also, I can run 'pip install pandas' without errors, it shows:
![image](https://user-images.githubusercontent.com/42430483/49925691-a21bb400-fef4-11e8-89ce-ae34099d086f.png)

**Comment by MMathisLab** [comment]
Hmm... and your using python 3.6 ?

**Comment by MingdiZheng** [comment]
> Hmm... and your using python 3.6 ?

I am using python 3.7, does it work?

**Comment by MMathisLab** [comment]
No, you need to make an env with python=3.6 (See Installation Guide ☺️)

**Comment by MingdiZheng** [comment]
> No, you need to make an env with python=3.6 (See Installation Guide ☺️)

It worked!! Thanks a lot!!!!!!

**Comment by MMathisLab** [comment]
@AlexEMG - we should change the pandas in setup.py, as it seems if it's a newer pandas it (1) works fine, and (2) doesn't seem to have issues building with 3.7..

**Comment by outlace** [comment]
Does it work with Python 3.7 now? @MMathisLab
