### ISSUE TITLE
`AxisError: axis 2 is out of bounds for array of dimension 0`

### ISSUE THREAD

**Issue by owadhwa** [DeepLabCut/DeepLabCut#1460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have trained my neural network and have evaluated it on a single animal Drosophila video. However, when I use the "create video" option in the GUI, I get the following error: 

![WhatsApp Image 2021-08-15 at 10 51 36 PM](https://user-images.githubusercontent.com/56737677/129569699-6d9636e0-9863-47dc-9aa6-ad4a4849732a.jpeg)
![WhatsApp Image 2021-08-15 at 10 51 36 PM (1)](https://user-images.githubusercontent.com/56737677/129569770-158ee433-3a30-472e-809b-3942c5e83904.jpeg)

The labelled video file is also corrupted after this and I cannot run the "extract outlier frames" and "refine labels" part of the GUI.

I haven't run any of my own code and am using the GUI only. 

### Operating System

operating system Windows 10

### DeepLabCut version

dlc version 2.2

### DeepLabCut mode

single animal

### Device type

gpu RTX 3060

### Steps To Reproduce

1. In the DEEPLABCUT environment
2. Run python -m deeplabcut
3. Use the GUI to train and evaluate the network, analyse video (use a renset_50 to extract training dataset)
4. Go to the "create video" panel and click on "RUN" after choosing the video.
While training and testing, all the settings were the default settings in the GUI and the video was in mp4 format. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by KonradDanielewski** [comment]
Issue seems to be the same or similar to one posted on image.sc, as in it looks like video/video metadata corruption (last frames probably don't exist and are just empty indices). Try the soultion from here: https://forum.image.sc/t/numpy-axiserror-traceback/53022

**Comment by jeylau** [comment]
Hey @KonradDanielewski, I feel like your post https://forum.image.sc/t/analyzing-new-videos-no-data/48313/7 would be a very useful recipe in our cookbook. Would you like to add it? It's better than if I do. 😄

**Comment by KonradDanielewski** [comment]
Hi, @jeylau, should I add it as a new file in recipes? I can add addtional info about parameters etc.

**Comment by jeylau** [comment]
@KonradDanielewski, you could probably add it here https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/recipes/io.md, this would fit nicely 😊
