### ISSUE TITLE
module 'tensorflow.compat' has no attribute 'v1'

### ISSUE THREAD

**Issue by HasanMurad1** [DeepLabCut/DeepLabCut#1461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have created an environment called 'project', I opened it then imported deeplabcut but am getting this bug:

(project) C:\Users\hmurad>ipython
Python 3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import deeplabcut
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-cfa4f159dfc5> in <module>
----> 1 import deeplabcut

c:\users\hmurad\anaconda3\envs\project\lib\site-packages\deeplabcut\__init__.py in <module>
     14 import tensorflow as tf
     15
---> 16 tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)
     17 DEBUG = True and "DEBUG" in os.environ and os.environ["DEBUG"]
     18 from deeplabcut import DEBUG

AttributeError: module 'tensorflow.compat' has no attribute 'v1'

In [2]:    

### Operating System

operating system: Windows

### DeepLabCut version

dlc version - cant import DLC

### DeepLabCut mode

single animal

### Device type

CPU

### Steps To Reproduce

(project) C:\Users\hmurad>ipython
Python 3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import deeplabcut
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-cfa4f159dfc5> in <module>
----> 1 import deeplabcut

c:\users\hmurad\anaconda3\envs\project\lib\site-packages\deeplabcut\__init__.py in <module>
     14 import tensorflow as tf
     15
---> 16 tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)
     17 DEBUG = True and "DEBUG" in os.environ and os.environ["DEBUG"]
     18 from deeplabcut import DEBUG

AttributeError: module 'tensorflow.compat' has no attribute 'v1'

In [2]:    

### Relevant log output

```shell
(project) C:\Users\hmurad>ipython
Python 3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import deeplabcut
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-cfa4f159dfc5> in <module>
----> 1 import deeplabcut

c:\users\hmurad\anaconda3\envs\project\lib\site-packages\deeplabcut\__init__.py in <module>
     14 import tensorflow as tf
     15
---> 16 tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)
     17 DEBUG = True and "DEBUG" in os.environ and os.environ["DEBUG"]
     18 from deeplabcut import DEBUG

AttributeError: module 'tensorflow.compat' has no attribute 'v1'

In [2]:
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by backyardbiomech** [comment]
Please try reinstalling deeplabcut from a fresh download. You appear to have some conflict between the version of deeplabcut you installed and some of the dependencies.

**Comment by jeylau** [comment]
@HasanMurad1, as said above, install deeplabcut from the provided environment configuration files (see https://deeplabcut.github.io/DeepLabCut/docs/installation.html). You will automatically be set up with python 3.8 and all required dependencies.

**Comment by backyardbiomech** [comment]
Running `pip install deeplabcut==2.2 --upgrade` has worked for me on only 50% of my updates from a 2.2rc installation. 
Same with the `reinstall.sh` script in the repo.

When it doesn't work, it acts like it works, but then the same release candidate is installed, not the full 2.2. 
This can be fixed by installing a new env from the latest `DEEPLABCUT.yaml`, or running `pip install deeplabcut==2.2 -force-reinstall`, which will download and install updates to most or all dependencies.
