### ISSUE TITLE
Colab_TrainNetwork_VideoAnalysis.ipynb: Create labeled video 

### ISSUE THREAD

**Issue by imorozovuottawa** [DeepLabCut/DeepLabCut#1462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When I use the "create labeled video" option in the Colab_TrainNetwork_VideoAnalysis.ipynb, I get the following error:

![Colab_VideoAnalysis_error](https://user-images.githubusercontent.com/29438688/129602132-6021ab59-d0fc-4982-9c9a-a3fdc349f8d5.jpg)

### Operating System

operating system Windows 10

### DeepLabCut version

dlc version 2.2rc3

### DeepLabCut mode

single animal

### Device type

gpu  - Colab_TrainNetwork_VideoAnalysis.ipynb

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@imorozovuottawa for multi-animal projects, please use this colab notebook: https://github.com/DeepLabCut/DeepLabCut/blob/master/examples/COLAB_maDLC_TrainNetwork_VideoAnalysis.ipynb 

the keyerror suggests either this, or you are running an old project on a new version within colab. Hope that helps!

**Comment by imorozovuottawa** [comment]
it is single animal project.
Please open this issue and check colab notebook with dlc version 2.2rc3
