### ISSUE TITLE
Colab Google Drive error on train_network

### ISSUE THREAD

**Issue by simonecnascimento** [DeepLabCut/DeepLabCut#1467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am at the stage of training and on colab I can see clearly the iterations and losses.
However I asked to save every 500 iterations and despite the fact that is doesn't save all (it stopped saving on 2500), I only get the snapshot-XXX.index files, I do not get snapshot-XXXX.data-00000-of-00001 or the .meta files.
![Screenshot 2021-08-20 at 15 10 30](https://user-images.githubusercontent.com/54689806/130282428-6a1b78a1-df31-4412-acbe-b13d3fce98ce.png)

### Operating System

MacOS

### DeepLabCut version

dlc version

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Could you please specify what version of deeplabcut you're using?

**Comment by simonecnascimento** [comment]
Hey @jeylau thanks a lot for the reply. I actually realised that files were automatically disappearing (and placed into the drive trash) for lack of drive space (silly me!). I only have the Google Drive 15GB.
