### ISSUE TITLE
create_multianimaltraining_dataset not updated to 2.2.rc3 yet

### ISSUE THREAD

**Issue by AnFrBo** [DeepLabCut/DeepLabCut#1469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

create_multianimaltraining_dataset not updated to 2.2.rc3 yet. It is still the old one without the new parameters like e.g.  crop_sampling. I looked in the source code that is attached to https://github.com/DeepLabCut/DeepLabCut/releases and it is also the older version in there too.

### Operating System

Linux/Ubuntu 1.18

### DeepLabCut version

2.2rc3

### DeepLabCut mode

multi animal

### Device type

GPU: GeForce RTX 3090

### Steps To Reproduce

activate conda env, ipython, import deeplabcut, deeplabcut.create_multianimaltraining_dataset?, look for new parameter like crop_sampling (not there)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by AnFrBo** [comment]
![missingparameters](https://user-images.githubusercontent.com/39856231/130364912-0b91003f-4454-49ac-822b-f684af70d437.png)

attached a screenshot of the issue I described above. Thanks in advance for your support @jeylau

**Comment by jeylau** [comment]
Hey @AnFrBo, make sure you upgrade to deeplabcut 2.2, the latest stable release 😊 (rc3 was a prior release candidate)

**Comment by AnFrBo** [comment]
@jeylau I tested in on a Mac with CPU support and it worked! I am sure it will also work tomorrow on my linux workstation. Thanks a lot!:)

**Comment by MMathisLab** [comment]
super - I will close, but do come back if any issues arise!
