### ISSUE TITLE
OneDrive - Colab for analysis of videos after trained network

### ISSUE THREAD

**Issue by simonecnascimento** [DeepLabCut/DeepLabCut#1474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Anyone knows if Colab can be linked to OneDrive (which I have much more space)?
I have limited google drive space and I am running most of the code (ie analysing videos etc) on Google Colab (for the GPU). That way I could transfer all my raw videos to OneDrive and do the analysis there, linked to Colab. 

### Operating System

MacOS

### DeepLabCut version

2.2rc3

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
@simonecnascimento, I guess you'd be more successful asking your question over there https://forum.image.sc/tag/deeplabcut. We try to keep GitHub for code-related issues ☺️
