### ISSUE TITLE
version 2.2 stable whl  is NOT 2.2 stable

### ISSUE THREAD

**Issue by KikuchiMakoto** [DeepLabCut/DeepLabCut#1475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

check __version__ or deeplabcut-2.2-py3-none-any.whl\deeplabcut\version.py

### Operating System

any

### DeepLabCut version

2.2 stable

### DeepLabCut mode

single animal

### Device type

cpu headless

### Steps To Reproduce

just install from pip

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Sorry about that; you do indeed have 2.2, but the printed version only got corrected after the release 😑 (it is fixed here https://github.com/DeepLabCut/DeepLabCut/blob/master/deeplabcut/version.py)
