### ISSUE TITLE
Index is out of bonds

### ISSUE THREAD

**Issue by Charly77220** [DeepLabCut/DeepLabCut#1477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello,

I regularly use DeepLabCut, everything is fine and today, without having any modification since yesterday, this error message appears when I want to analyze the videos. I've been looking for it, but I can't find any solution or any idea of how it could be caused. 

Thanks for your help

![Capture](https://user-images.githubusercontent.com/53442625/130671370-1b9804e3-2fe2-4e6e-99fd-8b608c9c12b1.PNG)

### Operating System

operating system : Windows 10

### DeepLabCut version

dlc version : 2.1.8.2

### DeepLabCut mode

single animal

### Device type

gpu : Nvidia 2070

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
check your snapshot value in the config.yaml, and be sure there is a `shuffle=1` for snapshot X. And, I guess there must be something that changed - did you update DLC or such?

**Comment by AlexEMG** [comment]
I suppose this just means that you don't have a trained model in the dlc-model folder!

**Comment by Charly77220** [comment]
Thanks, it was a problem with the snapshot. I close this issue
