### ISSUE TITLE
How to activate DLC-GPU?

### ISSUE THREAD

**Issue by felipearrudamoura** [DeepLabCut/DeepLabCut#1483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

In the last versions of DLC, if you want to use GPU, you should chose GPU file on the conda-enviroments folder. However, in the new version, there only one file. So, during training, DLC is using only my CPU. In the other versions, I typed "activate DLC-GPU" and it worked.
Could you help me?

### Operating System

WIN 10

### DeepLabCut version

2.2.rc3

### DeepLabCut mode

multi animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by KonradDanielewski** [comment]
Please follow instructions listed here: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/installation.md#gpu-support

**Comment by Darkweiss** [comment]
I have also today tried to install deeplabcut on a new machine and the new env file did not install cudnn and cudatoolkit.

**Comment by felipearrudamoura** [comment]
I guys. I don't know why. I am doing exactly the instructions, DLC gui runs but using my CPU.

**Comment by KonradDanielewski** [comment]
> I have also today tried to install deeplabcut on a new machine and the new env file did not install cudnn and cudatoolkit.

As specified in instruction, you have to run `conda install -c conda-forge cudnn`
