### ISSUE TITLE
create_labeled_video() is not generating a labeled video in colab

### ISSUE THREAD

**Issue by rhgoo** [DeepLabCut/DeepLabCut#1484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I'm using Google Colab to create my training set to analyze, plot, and label videos but no labeled videos are loaded into my project folder. The analyze_videos() and plot_trajectories() commands work since I do see meta.pickle and .h5 files in my project 'videos' folder. However, running create_labeled_video() generates no labeled video files. Is there any way to fix this issue? I've tried running `from google.colab import drive` after I ran create_labeled_video() but nothing showed up.

My input:
`deeplabcut.create_labeled_video(path_config_file,videofile_path, videotype=VideoType)`

### Operating System

Windows 10
Google Chrome
Google Colab

### DeepLabCut version

dlc version: 2.2.0.1

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

1. Follow and run blocks of code provided on Colab for DeepLabCut

### Relevant log output
```
Output:
Analyzing all the videos in the directory...
/content/drive/My Drive/LEDpan2-richard-2021-08-26/videos  already exists!
/content/drive/My Drive/LEDpan2-richard-2021-08-26/videos  already exists!
Starting to process video: /content/drive/My Drive/LEDpan2-richard-2021-08-26/videos/B36_2LEDpan_filter-08052021115852-0000.avi
Starting to process video: /content/drive/My Drive/LEDpan2-richard-2021-08-26/videos/B36_2LEDpan_filter-08052021115844-0000.avi
Loading /content/drive/My Drive/LEDpan2-richard-2021-08-26/videos/B36_2LEDpan_filter-08052021115852-0000.avi and data.
Loading /content/drive/My Drive/LEDpan2-richard-2021-08-26/videos/B36_2LEDpan_filter-08052021115844-0000.avi and data.
Duration of video [s]: 3.0, recorded with 249.94 fps!
Overall # of frames: 750 with cropped frame dimensions: 668 462
Generating frames and creating video.
Duration of video [s]: 3.0, recorded with 249.94 fps!
Overall # of frames: 751 with cropped frame dimensions: 668 462
  0%|          | 0/750 [00:00<?, ?it/s]Generating frames and creating video.
100%|██████████| 750/750 [00:05<00:00, 126.87it/s]
/content/drive/My Drive/LEDpan2-richard-2021-08-26/videos  already exists!
 98%|█████████▊| 736/751 [00:05<00:00, 119.46it/s]Starting to process video: /content/drive/My Drive/LEDpan2-richard-2021-08-26/videos/B36_2LEDpan_filter-08052021115837-0000.avi
Loading /content/drive/My Drive/LEDpan2-richard-2021-08-26/videos/B36_2LEDpan_filter-08052021115837-0000.avi and data.
100%|██████████| 751/751 [00:06<00:00, 124.99it/s]
/content/drive/My Drive/LEDpan2-richard-2021-08-26/videos  already exists!
Starting to process video: /content/drive/My Drive/LEDpan2-richard-2021-08-26/videos/LEDpanTest1.avi
Loading /content/drive/My Drive/LEDpan2-richard-2021-08-26/videos/LEDpanTest1.avi and data.
Duration of video [s]: 3.0, recorded with 249.94 fps!
Overall # of frames: 751 with cropped frame dimensions: 668 462
Generating frames and creating video.
  0%|          | 0/751 [00:00<?, ?it/s]Duration of video [s]: 3.0, recorded with 249.94 fps!
Overall # of frames: 751 with cropped frame dimensions: 668 462
Generating frames and creating video.
100%|██████████| 751/751 [00:05<00:00, 125.33it/s]
100%|██████████| 751/751 [00:05<00:00, 126.47it/s]
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hello @rhgoo, do you have enough Drive storage? We've seen this happen when the Drive is full, and videos get thrown to trash immediately.

**Comment by rhgoo** [comment]
> Hello @rhgoo, do you have enough Drive storage? We've seen this happen when the Drive is full, and videos get thrown to trash immediately.

I’m using my university’s email so I have unlimited storage. I’m just confused as to what’s wrong because I didn’t have this issue until this project.

**Comment by MHRosenberg** [comment]
@rhgoo, my colleague was hitting the same problem with version 2.2. He ran the entire pipeline in the GUI on macOS (M1). We appear to have resolved the issue by lowering the pcutoff in the config.yaml file. I believe DLC may be assigning low confidence (called "likelihood" in the .csv file) to your points which aren't above the pcutoff and are therefore excluded from the labeled video. I hope that helps.

**Comment by jeylau** [comment]
Great point above by @MHRosenberg! I understood the problem as no video being created at all...

**Comment by rhgoo** [comment]
> @rhgoo, my colleague was hitting the same problem with version 2.2. He ran the entire pipeline in the GUI on macOS (M1). We appear to have resolved the issue by lowering the pcutoff in the config.yaml file. I believe DLC may be assigning low confidence (called "likelihood" in the .csv file) to your points which aren't above the pcutoff and are therefore excluded from the labeled video. I hope that helps.

Thanks for the suggestion! May I ask what pcutoff you changed yours to and which blocks of code you ran? I changed my pcutoff from 0.6 to 0.1 and reran all the code (including training a new dataset), but I still don't have any labeled videos.

**Comment by MHRosenberg** [comment]
> > @rhgoo, my colleague was hitting the same problem with version 2.2. He ran the entire pipeline in the GUI on macOS (M1). We appear to have resolved the issue by lowering the pcutoff in the config.yaml file. I believe DLC may be assigning low confidence (called "likelihood" in the .csv file) to your points which aren't above the pcutoff and are therefore excluded from the labeled video. I hope that helps.
> 
> Thanks for the suggestion! May I ask what pcutoff you changed yours to and which blocks of code you ran? I changed my pcutoff from 0.6 to 0.1 and reran all the code (including training a new dataset), but I still don't have any labeled videos.

We changed the config file and only reran the video generation step. I forget what pcutoff we used, maybe 0.01 or something crazy low. In our case, we were running a test of the pipeline rather than actually trying to generate interpretable data; I would not use our super low pcutoff beyond testing. 

Have you verified that your tracking is reasonable? Check the .csv results. Note the confidence values relative to your 0.1 cutoff and also maybe plot those x and y coordinates to see if they're sensible.

You could also check the alpha and dotsize params in the config. It's possible the points are there but they just aren't visible.

**Comment by MMathisLab** [comment]
how do the `plot_trajectories` plots look? these plots allow you to pick a good `pcutoff`

But, can you confirm wether NO video is saved at all, OR that a video is saved but you do not see the DLC labels?

**Comment by rhgoo** [comment]
> how do the `plot_trajectories` plots look? these plots allow you to pick a good `pcutoff`
> 
> But, can you confirm wether NO video is saved at all, OR that a video is saved but you do not see the DLC labels?

I'm using my university's Google Drive so I should have unlimited storage. I'm still relatively new to DLC so I don't have a strong understanding of interpreting the plots but I've posted a screenshot of the plot regarding pcutoff. When I run create_labeled_video() it doesn't seem to load anything at all. I tried searching for it in the DLC folders and my entire Drive (including trash) but no labeled video is found.
![image](https://user-images.githubusercontent.com/86977704/131936726-5fdfa20f-3b30-4df3-9593-410abf41f189.png)

**Comment by MMathisLab** [comment]
yeah okay this plot shows that the data is analyzed, you have mostly highly confident points (so the `pctuoff` in the config file should stay at `0.6`) - here, you look at the likelihood and set a good threshold, as the plot notes. 

So, this means that either colab isn't working, your drive is full OR you hit your daily upload limit in google drive. you can try locally, creating a video is not using a GPU anyhow. Namely, download the project, and run the command using the GUI interface.

**Comment by jeylau** [comment]
I propose to close this issue as I cannot replicate it in Colab, and as Mackenzie said above videos can easily be created locally. Doesn't look like it comes from us anyway 🙁
