### ISSUE TITLE
Can docker images be tagged instead of 'latest core'

### ISSUE THREAD

**Issue by lnguyen** [DeepLabCut/DeepLabCut#1493]
Is there a way we can tag the deeplabcut docker images to version? latest-core makes it hard to run things predictably on CI if newest version introduces breaking changes

**Comment by MMathisLab** [comment]
no stable release has backwards breaking changes; only beta or rc releases, which are tagged, note there is likely to be a change. 2.2 vs. 2.1x is the major division upwards (but even then, older, non beta/rc releases) are fully backwards compatible. What we do internally is when you name the image and subsequent container, you can name it to ID both GPU and pypi version. Hope that helps!

**Comment by lnguyen** [comment]
Hi! I guess I'm just afraid if things upgrade and change underlying code for me. I'm using Concourse CI to create pipelines to train my models with dlc but that will pull latest image then I run it through https://github.com/paninski-lab/deepgraphpose. that code rely on some underlying deeplabcut code. Might be a later problem when it breaks :)

**Comment by MMathisLab** [comment]
It relies on a lot of dlc code ;). But, I'm sorry, but I can't made edits to our workflow as it would require a massively growing set of docker images.
