### ISSUE TITLE
Unable to create labeled videos on CoLab and Locally

### ISSUE THREAD

**Issue by rhgoo** [DeepLabCut/DeepLabCut#1496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Google Colab wasn't generating any labeled videos (and still isn't), so I was suggested to make the labeled video locally after I trained a network on Colab. However, there were still no labeled videos being created. I found another post from early 2019 that had the same error output and they said something about changing "codec," but I don't know what that means.

Top log output is after I inputted the normal `create_labeled_video`() code
Bottom log output is adding `save_frames=True` as the last parameter of `create_labeled_video()`

### Operating System

Windows 10
Anaconda Prompt

### DeepLabCut version

2.2.0.1 for Colab

### DeepLabCut mode

single animal

### Device type

CPU

### Steps To Reproduce

1. Train network as you would on Colab
2. Download and extract the project folder
3. Change project path in config.yaml back from Google Drive to Windows
4. Open Anaconda and launch standard DLC
5. run `deeplabcut.create_labeled_video(config_path, [r'C:\Users\Richard\Documents\DeepLabCut\projects\50cmTest-richard
   ...: -2021-09-06\videos\50cm-08262021.avi'])`

### Relevant log output

```shell
2021-09-06 16:54:36.644950: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2021-09-06 16:54:36.645244: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
C:\Users\Richard\Documents\DeepLabCut\projects\50cmTest-richard-2021-09-06\videos  already exists!
Starting to process video: C:\Users\Richard\Documents\DeepLabCut\projects\50cmTest-richard-2021-09-06\videos\50cm-08262021.avi
Loading C:\Users\Richard\Documents\DeepLabCut\projects\50cmTest-richard-2021-09-06\videos\50cm-08262021.avi and data.
[mpeg4 @ 0000020dc9617080] timebase 500/124969 not supported by MPEG 4 standard, the maximum admitted value for the timebase denominator is 65535
Could not open codec 'mpeg4': Unspecified error
Duration of video [s]: 3.0, recorded with 249.94 fps!
Overall # of frames: 751 with cropped frame dimensions: 668 448
Generating frames and creating video.
100%|███████████████████████████████████████████████████████████████████████████████| 751/751 [00:01<00:00, 612.85it/s]

2021-09-06 16:56:17.244053: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2021-09-06 16:56:17.244315: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
C:\Users\Richard\Documents\DeepLabCut\projects\50cmTest-richard-2021-09-06\videos  already exists!
Starting to process video: C:\Users\Richard\Documents\DeepLabCut\projects\50cmTest-richard-2021-09-06\videos\50cm-08262021.avi
Loading C:\Users\Richard\Documents\DeepLabCut\projects\50cmTest-richard-2021-09-06\videos\50cm-08262021.avi and data.
Duration of video [s]: 3.0, recorded with 249.94 fps!
Overall # of frames: 751 with cropped frame dimensions: 668 448
Generating frames and creating video.
[WinError 2] The system cannot find the file specified
```

### Anything else?

I tried `deeplabcut.create_labeled_video(config_path, [r'C:\Users\Richard\Documents\DeepLabCut\projects\50cmTest-richard
   ...: -2021-09-06\videos\50cm-08262021.avi'], save_frames=True)` since that was a line of code I found in another post with the same error.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by KonradDanielewski** [comment]
Like in other issue, did you try specifing the codec?

**Comment by anmabu** [comment]
Did you copy the video to the "videos" folder of your project or did you just set a link? 
I get the same error when setting the path to the link but it works if a set the path to the original file. Have you tried this?

**Comment by rhgoo** [comment]
> Like in other issue, did you try specifing the codec?

I didn't know what codec was so I didn't change any files.

**Comment by rhgoo** [comment]
> Did you copy the video to the "videos" folder of your project or did you just set a link?
> I get the same error when setting the path to the link but it works if a set the path to the original file. Have you tried this?

My videos are copied into the project folder and the paths of the videos (when I type them in the command line) go to the 'videos' folder

**Comment by backyardbiomech** [comment]
For reference, the previous issue was #244 . 

We can develop a few hypotheses as to the source of the error:
1. something with your video
2. something with colab
3. something with deeplabcut
4. something with the ffmpeg installation

It's not a problem with deeplabcut specifically because nobody else is reporting this error, and I can't reproduce it. It's not a problem on colab (as I originally thought with some similar errors), or with a specific ffmpeg installation because you get this error with your local installation and colab. Therefore it must be something with your video format. Just as with the previous issue, the bug occurs with ffmpeg or opencv encoding, which are used by, but are not part of, the deeplabcut code. 

```
[mpeg4 @ 0000020dc9617080] timebase 500/124969 not supported by MPEG 4 standard, the maximum admitted value for the timebase denominator is 65535
Could not open codec 'mpeg4': Unspecified error
```

That part also suggests that ffmpeg cannot fully read your video. It *can* read it, otherwise analyzing videos wouldn't work, but there's some other problem with the read/write functions. 

```
Generating frames and creating video.
[WinError 2] The system cannot find the file specified
```

with save frames on suggests a file writing issue - either a permissions problem on the drive, or ffmpeg didn't actually save out individual frames.

I would suggest reencoding the videos. See [this discussion](https://forum.image.sc/t/analyzing-new-videos-no-data/48313/5) for re-encoding options.
