### ISSUE TITLE
maDLC only one animal gets labeled 

### ISSUE THREAD

**Issue by anmabu** [DeepLabCut/DeepLabCut#1498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Two mice, both labeled with multianimal bodyparts, each has an individual bodypart.
In the created video only the coordinates for the first mouse and the 2 individual bodyparts are shown. Also the coordinates jump between the mice and not stay on the first mouse.
Had a look a the .csv file from `refine tracklets`, same problem, only the coordinates for one mouse and the individual markers exist. 

### Operating System

Windows 10

### DeepLabCut version

2.2.0.1
- including #1495

### DeepLabCut mode

multi animal

### Device type

GPU 

### Steps To Reproduce

GUI. 
Two mice. Both have multianimal points, both have 1 inidiviual bodypart.
Creating trainingset, training network, analyzing network, refine tracklets, create video

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Did you perform intermediate visual checks? Specifically, we encourage users to use `deeplabcut.create_video_with_all_detections` to check detections independently of tracking performance. Are you happy with the images saved during model evaluation (when passing `deeplabcut.evaluate_network(..., plotting=True)`)?

**Comment by anmabu** [comment]
Yes, I did both of these and all detections and plotted maps look fine.

**Comment by MMathisLab** [comment]
@anmabu in your environment can you run: `pip install https://github.com/DeepLabCut/DeepLabCut/archive/master.zip` I believe there was one wrongly merged PR that might cause this....

**Comment by anmabu** [comment]
Thank you very much, that solved it!
