### ISSUE TITLE
draw skeleton during labelling

### ISSUE THREAD

**Issue by poborin** [DeepLabCut/DeepLabCut#1499]
**Is your feature request related to a problem? Please describe.**
I'm labelling a group of (max 8) people during the sports exercise. In many cases, limbs and other parts of the body are concealed by a piece of equipment or trainees. Given the body is symmetrical and has similar proportions across individuals there will be nice to have guidance during the labelling process. 

**Describe the solution you'd like**
Drawing a skeleton during the labelling process will give visual guidance on the body parts distance and positioning.

**Additional context**
This should also reduce an issue of accidental mislabeling as the skeleton will pronounce additional check criteria.

**Comment by MMathisLab** [comment]
@poborin there is a skeleton builder GUI actually already, if you wanted to hack that into the labeling GUI! check out `deeplabcut.SkeletonBuilder(config+path)`
