### ISSUE TITLE
demo training data

### ISSUE THREAD

**Issue by cchamber** [DeepLabCut/DeepLabCut#15]
When running the demo scripts I saw that some of the labelled images have labels in the wrong place.
img0-img43 are correct
Maybe this doesn't matter for running the scripts...wondering if this is normal
![img119](https://user-images.githubusercontent.com/8458570/41372128-5c240e62-6f1a-11e8-83b7-f526ddfe38b5.png)

**Comment by AlexEMG** [comment]
I cannot reproduce this error, but have a suspicion: If you run Step1_...  some additional frames will be extracted from the video and added to the folder /data-reaching/reachingvideo1. Naturally, these *new* frames will not have labels in the csv file that DeepLabCut ships with. If you then proceedto Step2 & 3 the labels will not be correctly linked to corresponding frames. Is that what you did?

Anyway, this is why in the [readme](https://github.com/AlexEMG/DeepLabCut/blob/master/README.md) we state: "If you want to run the code on our demo video, a mouse reaching video from Mathis et al., 2017, you will NOT run code from sections (0), (1), or (2) below, as we have created labels for this video already (and e.g. (0) will extract different frames that are thus not labeled)."

**Comment by cchamber** [comment]
Thanks for the quick reply, I see why you recommend skipping to step 3. 

A related question: when using new labelled data, is it ok to copy the data in a pandas data frame directly, like DataSingleUser in step 2?

**Comment by AlexEMG** [comment]
Yes, absolutely. It is open source code, so it should be easy to adjust to your specific needs. Feel free to enter your data wherever it is easiest!
