### ISSUE TITLE
create_training_dataset - FileNotFound error (DOWNLOADING ResNet Weights windows)

### ISSUE THREAD

**Issue by Bart-van-Alphen** [DeepLabCut/DeepLabCut#150]
I'm using this setup: Windows 10 with an Anaconda environment, Python, 3.6.2, DeepLabCut 2

The problem occurs when I try to create a training dataset using:
deeplabcut.create_training_dataset(config_path,num_shuffles=1)

I get this error message: see screenshot

![create training dataset error message](https://user-images.githubusercontent.com/45836197/50060232-fe7e0e00-0156-11e9-8f3d-89546b9c567e.png)

It seems to be looking for this non-existing directory 'D:\\Work\\DeepLabCut\\test_vids\\first_test_run\\PE_test-BvA-2018-12-13\\dlc-models\\iteration-0\\PE_testDec13-trainset95shuffle1\\train\\pose_cfg.yaml'

This folder is empty: D:\\Work\\DeepLabCut\\test_vids\\first_test_run\\PE_test-BvA-2018-12-13\\dlc-models\\

Instead, the pose_cfg.yaml file seems to be here: 'C:\Users\Bart\Anaconda3\envs\DLC\deeplabcut'

What would be the best solution here?

**Comment by AlexEMG** [comment]
I have never seen this error. This step creates lots of folders + files. Are the ResNet weights correctly downloaded, are the trainingset files created?

The default ```pose_cfg.yaml``` is stored in your deeplabcut installation folder so that makes sense.

**Comment by Bart-van-Alphen** [comment]
This path does not exist in windows: cd usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/

On my PC, it is: C:\Users\Bart\Anaconda3\envs\DLC\Lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained

And you're right, resnet is not there. 

How do I run sudo download.sh? 
I tried: sudo ./download.sh, but that gives a SyntaxError

**Comment by AlexEMG** [comment]
Ok, so that is indeed the error then. There are quite a few ways, but I think the best way is to install: git for windows and then it should work. https://gitforwindows.org/

**Comment by Bart-van-Alphen** [comment]
Updating this comment:
After downloading and installing git, running "deeplabcut.create_training_dataset(config_path,num_shuffles=1)" resulted in a successful download of resnet.

However, I get an FileNotFoundError because pose_cfg.yaml is not in the folder that DeepLabCut is looking:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Work\\DeepLabCut\\test_vids\\first_test_run\\PE_test-BvA-2018-12-13\\dlc-models\\iteration-0\\PE_testDec13-trainset95shuffle1\\train\\pose_cfg.yaml'

All the folders are there, but pose_cfg.yaml is not in the "train" folder...

**Comment by MMathisLab** [comment]
could you paste the screenshot or text output again now that it is downloaded? Also delete the iteration-0 model/training data folders first, then re-run the command `deeplabcut.create_training_dataset(config_path)`, or alternatively create a different shuffle, e.g. `deeplabcut.create_training_dataset(config_path,Shuffles=[2])`

**Comment by Bart-van-Alphen** [comment]
Ok, deleting the folders and using deeplabcut.create_training_dataset(config_path) did the trick

Thanks for the excellent feedback! Going to train the network now for the first time. Exciting :-)

**Comment by WrathUM** [comment]
Hi, I am not sure if the issue I am facing is the same as the one listed here and I would like to get some help with it.
I am working with Windows 10 computer and I am pretty sure I installed everything correctly. 
Firstly, even though I have excel spreadsheets in each of the labeled data folders with coordinate values stored in the spreadsheets, every time I run the check labels through GUI it returns that none of the videos were labeled. 


Additionally, I get the following error when I try to create a training data set in the GUI. I am not sure what to do about this as I am not the administrator account on this Lab PC. Do I need to ask my PI for access to the Admin user or is there a work around.

![image](https://user-images.githubusercontent.com/57931859/92187648-36d3ed00-ee0f-11ea-9b8c-c93533cd97c7.png)

**Comment by AlexEMG** [comment]
That just means that this folder has no labeled data.

You can also run: deeplabcut. comparevideolistsanddatafolders(config)
to check!
https://github.com/DeepLabCut/DeepLabCut/blob/master/deeplabcut/generate_training_dataset/trainingsetmanipulation.py#L33
