### ISSUE TITLE
DeepLabCut always shutting down when trying to refine

### ISSUE THREAD

**Issue by Apathion** [DeepLabCut/DeepLabCut#1504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello everyone.

So I tried many times in the past to refine my trackless, but DLC is always breaking down after a short amount of time.
I was actually hoping using a cloud-service could solve this problem (thinking it might be because of my weaker desktop) but now I realised that I would still need my local computer for the refinement anyways.
Well, today I actually wanted to create a new set of outliers to label before I put everything on the cloud, but then I had a problem with creating outliers (first time ever, so I might just have made some minor error there, so it doesn't matter that much to me for now. 
The important point is, that I once again tried to at least activate the "refine" GUI (thinking that after this DLC might realise that I did already analyze that video) and long story short:
DLC once again gave up on me just after me opening the refine-GUI.
I'm not sure if this is a bug, if my system is simply to weak or if I messed something up, but I wanted to mention it here in case there is something that could be done to make that GUI more stable (or maybe just letting me know what I did wrong).

### Operating System

operating system

MacOS high Sierra

### DeepLabCut version

cpu version

 DeepLabCut 2.2rc2

### DeepLabCut mode

multi animal

### Device type

Using the CPU-Env.
(Radeon Pro 560 4096 MB, 3.6 GHz Intel Core i7, 16 GB 2400 MHz DDR4)

### Steps To Reproduce

1. Starting GUI in CPU-Environment
2. Going on "Refine tracklets"
3. Choose the appropriate el.pickle file, as I did work with ellipse-analysis.
4. Number of animals: 3
5. Click on "create tracks"
6. Choosing the unaltered video-file that fits the pickle-file
7. Clicking on "refine tracklets"
8. After a few seconds the GUI already closes down 

### Relevant log output

```shell
(DLC-CPU) UniversitysiMac:~ psydev20$ pythonw -m deeplabcut
Starting GUI...
currently DLCRNet is only supported in multi-animal mode
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 505/505 [00:00<00:00, 930.69it/s]
Video duration and data length do not match. Continuing nonetheless...
[msmpeg4 @ 0x7fba0d5f3600] ignoring overflow at 27 0
[msmpeg4 @ 0x7fba0d5f3600] ignoring overflow at 27 0
[msmpeg4 @ 0x7fba0d5f3600] ignoring overflow at 27 0
[msmpeg4 @ 0x7fba0d5f3600] ignoring overflow at 27 0
[msmpeg4 @ 0x7fba0d5f3600] ac-tex damaged at 28 0
[msmpeg4 @ 0x7fba0d5f3600] 
error while decoding block: 28 x 0 (5)
[msmpeg4 @ 0x7fba0d5f3600] Error at MB: 28
/opt/anaconda3/envs/DLC-CPU/bin/pythonw: line 3:  2150 Segmentation fault: 11  /opt/anaconda3/envs/DLC-CPU/python.app/Contents/MacOS/python "$@"
```

### Anything else?

That's all that comes to mind right now.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by backyardbiomech** [comment]
I don't think it's the computer because I can run the GUI on a slightly older/weaker MacBook.

> Video duration and data length do not match. Continuing nonetheless...

Is a possible source of the problem. This suggests not all video frames were analyzed. That's usually because the video file is corrupted.

> [msmpeg4 @ 0x7fba0d5f3600] ac-tex damaged at 28 0
[msmpeg4 @ 0x7fba0d5f3600] 
error while decoding block: 28 x 0 (5)
[msmpeg4 @ 0x7fba0d5f3600] Error at MB: 28

That also suggests that the video file is corrupted. In other words, a corrupted video file doesn't complete analysis, and then crashes the refining GUI (because the full file can't be loaded). 

Re-encode your video with ffmpeg, and re-run it through analysis. 
See [here](https://forum.image.sc/t/analyzing-new-videos-no-data/48313/5) for re-encoding tips.
