### ISSUE TITLE
Input frames for training need to have same orientation as for video inference (error with input size and rotation)

### ISSUE THREAD

**Issue by Donnypickels** [DeepLabCut/DeepLabCut#151]
Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut2.0.0

Hi,

I'm now training a very short video, 207 frames for the 6th time with every time about 300.000+ iteration, but the tracking is still very off.

I've got no idea what I'm doing wrong.. This is how I train:
```
deeplabcut.train_network(path_config_file)

deeplabcut.evaluate_network(path_config_file)

deeplabcut.analyze_videos(path_config_file,videofile_path)

deeplabcut.extract_outlier_frames(path_config_file,['videofile_path'],outlieralgorithm='uncertain',p_bound=.5)

deeplabcut.refine_labels(path_config_file)

deeplabcut.merge_datasets(path_config_file)

deeplabcut.create_training_dataset(path_config_file)
```

Am I missing something maybe? I read that you can continue training  by using a snapshot as initial, but when you start a new training you don't want to continue an old one right? Or did I get that wrong?

I don't know if you need any more info, but let me know!

Thanks :)

**Comment by AlexEMG** [comment]
Maybe you do, maybe you don't. Could you perhaps describe the problem?

**Comment by Donnypickels** [comment]
Sorry I see that something went wrong editing my comment, its update now!

**Comment by Donnypickels** [comment]
So I do a training, it's not that good and I extract outlier frames.
I refine the labels (load the machinelabels.iterX.hX) and refine them.
Then I merge the dataset and create a new training.
Where should I load my old weights and where can I find those? Is it the initial weights in the pose_cfg.yaml? And if so, which would be the weights that I need to use?

**Comment by AlexEMG** [comment]
@Donnypickels , this is a basic use question. Please consult the user guide: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#f-create-training-dataset 
https://www.biorxiv.org/content/early/2018/11/24/476531
Related issues:
https://github.com/AlexEMG/DeepLabCut/issues/135

Note for refinement: 
- Merge the data sets and train again!
- The weights will (again) be initialized from ImageNet weights! (because w.l.o.g. e.g. #body parts could have changed).
- However, you can manually link the init_weights in pose_cfg.yaml to the snapshot from the previous iteration before starting to train (i.e. change the path in `init_weights`). For instance, change it to: /home/alex/test_dlc-Fritz-2018-12-13/dlc-models/iteration-0/test_dlcDec13-trainset95shuffle2/train/snapshot-5000

**Comment by MMathisLab** [comment]
It just restarts at 0 for every refinement iteration

**Comment by Donnypickels** [comment]
I get it that it starts at 0 iterations when you start training again, but the network should be "trained" right? 
I.e. it should get better at tracking a certain point?

After the 7 iterations with 500.000+ training iterations, with refinement in between, it still does not track correctly.. I've been trying to track fingers during a simple hand motion, but the markers are still pretty random placed around the image (or just in the corner).

**Comment by MMathisLab** [comment]
Hmm... sounds like the original labels might need fixed... this is hard to troubleshoot on GitHub, could you email me?

**Comment by Donnypickels** [comment]
Alright, just because I don't like treads that don't end in answers:

What actually was going wrong during my training:
I filmed with a phone and my videos had a rotation. (`exiftool vid.mp4` showed a rotation of 90)
This made that the extraction of frames went wrong (extracted frames rotated and scaled) and that the network was trained on a scaled image, causing the labeling of the video to fail because the video was not scaled.

Was easily fixed this by getting rid of the rotation.
(I had to desample the video with ffmpeg anyways, which got rid of the rotation as well.)

*And max input size needed adjusted, as the default is that >1000 is not used for training, as to not crash GPU. To note, this default was changed to 1500 in 2.0.3! So please update if you use large frames regularly.

**Comment by AlexEMG** [comment]
Btw, if one had rotational differences between labeled data and videos, then one can augment during training by rotations, e.g. like this: https://github.com/AlexEMG/DeepLabCut/pull/102
