### ISSUE TITLE
Syntax for Video Re-encoding (ffmpeg)

### ISSUE THREAD

**Issue by rhgoo** [DeepLabCut/DeepLabCut#1510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I don't understand what the syntax error is. I'm trying to re-encode some videos to see if that would resolve my previous issue of no labeled videos being created. I was like to [this post](https://forum.image.sc/t/analyzing-new-videos-no-data/48313/5) as a solution, but couldn't even run the code due to a syntax error.

provided code was `ffmpeg -i "path/to/input.mp4" -c:v libx264 -crf 23 -c:a copy "/path/to/output.mp4"`

### Operating System

Windows

### DeepLabCut version

2.2.0.1

### DeepLabCut mode

single animal

### Device type

CPU

### Steps To Reproduce

1. Open Anaconda Terminal
2. Activate Environment > ipython > import deeplabcut
3. ffmpeg - "C:\Users\Richard\Documents\DeepLabCut\data\30cmPilot.avi" -c:v libx264 -crf23 -c:a copy "C:\Users\Richard\Documents\DeepLabCut\projects\30cmPilot-richard-2021-09-16"

### Relevant log output

```shell
In [7]: ffmpeg - "C:\Users\Richard\Documents\DeepLabCut\data\30cmPilot.avi" -c:v libx264 -crf23 -c:a copy "C:\Users\Ric
   ...: hard\Documents\DeepLabCut\projects\30cmPilot-richard-2021-09-16"
  File "<ipython-input-7-9a5e79c79c7b>", line 1
    ffmpeg - "C:\Users\Richard\Documents\DeepLabCut\data\30cmPilot.avi" -c:v libx264 -crf23 -c:a copy "C:\Users\Richard\Documents\DeepLabCut\projects\30cmPilot-richard-2021-09-16"
                                                                                   ^
SyntaxError: invalid syntax
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by KonradDanielewski** [comment]
Your command is incorrect, the input is not flagged and you should always add file extension, for libx that would be `.mp4`. Also space after crf 
You have: 
`ffmpeg - "C:\Users\Richard\Documents\DeepLabCut\data\30cmPilot.avi" -c:v libx264 -crf23 -c:a copy "C:\Users\Richard\Documents\DeepLabCut\projects\30cmPilot-richard-2021-09-16"`

When you should have:
 `ffmpeg -i "C:\Users\Richard\Documents\DeepLabCut\data\30cmPilot.avi" -c:v libx264 -crf 23 -c:a copy "C:\Users\Richard\Documents\DeepLabCut\projects\30cmPilot-richard-2021-09-16.mp4"`

Also, I just noticed, run it in the terminal, not ipython

**Comment by AlexanderMath** [comment]
Your command works for me if I add the "-strict -2" parameter, I tried it in [this Google Colab](https://colab.research.google.com/drive/187_eVi-cORL9Om7pFl_dTOQpsEAWlqc_?usp=sharing). 

Did you install ffmpeg?

**Comment by rhgoo** [comment]
Oh, I didn't know I needed to install ffmpeg before re-encoding; where can I find the installation package? Thank you guys for the help!

**Comment by mfkeles** [comment]
`conda install -c conda-forge ffmpeg` should do the trick!

**Comment by rhgoo** [comment]
Thank you, everyone! I got this output so I assume it worked?
![image](https://user-images.githubusercontent.com/86977704/133826526-e44715fc-2275-41c2-9493-6a80d2cc6fee.png)
