### ISSUE TITLE
FileNotFoundError: It seems the model for shuffle 1 and trainFraction 0.95 does not exist. [colab]

### ISSUE THREAD

**Issue by hammadmadu** [DeepLabCut/DeepLabCut#1512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I'm using googlecolab to train and analyze video.
I trained a network. However, when I use analyze_video function I ran into the following issue:
FileNotFoundError: It seems the model for shuffle 1 and trainFraction 0.95 does not exist.
This is the code I am using
```python
print("Start Analyzing my video(s)!")
#EDIT OPTION: which video(s) do you want to analyze? You can pass a path or a folder:
# currently, if you run "as is" it assumes you have a video in the DLC project video folder!


deeplabcut.analyze_videos(path_config_file,videofile_path, videotype=VideoType)
```
![deeplabcut](https://user-images.githubusercontent.com/60319554/134301486-5e46446f-31e3-4dc4-9081-d651b0ee95d7.png)

### Operating System

operating system googlecolab

### DeepLabCut version

dlc version 2.2.0.2

### DeepLabCut mode

multi animal

### Device type

gpu : googlecolab

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by hammadmadu** [comment]
print(path_config_file)
print(videofile_path)

/content/drive/MyDrive/Test-Hammad-2021-09-16/config.yaml
/content/drive/MyDrive/Test-Hammad-2021-09-16/videos/ShrimpsVIdeo_Trim_Training.mp4

**Comment by MMathisLab** [comment]
@hammadmadu can you confirm the file name in the model folder? I can't see it in the screenshot.

**Comment by hammadmadu** [comment]
I solved it, path was incorrect.

**Comment by hammadmadu** [comment]
Thanks.

**Comment by MMathisLab** [comment]
no problem :)
