### ISSUE TITLE
Index Error during when converting  detections to tracklets

### ISSUE THREAD

**Issue by mk-mccann** [DeepLabCut/DeepLabCut#1514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

_Note: I am using the DLC GUI_

I trained a multi-animal network with two individuals and a number of unique body parts for corner and object detection. On the 'Analyze videos' tab of the GUI, I am able to run 'Step 1: Analyze Videos' and output labelled versions of those videos. The predictions look good on the output videos. When running 'Step 2: Convert to tracklets', I get an Index Error originating in `pose_estimation_tensorflow\lib\inferenceutils.py`

Maybe important to note is that I only have two multi-animal body parts per individual. This could be increased, but the individuals of interest are very small in each frame.

### Operating System

Windows 10

### DeepLabCut version

2.2.02

### DeepLabCut mode

multi animal

### Device type

NVIDIA GeForce GTX 1080

### Steps To Reproduce

1. DLC-GPU environment installed from the supplied DEEPLABCUT.yaml file.
2. Train and evaluate multi-animal network
3. Under analyze videos tab of GUI, run Step 2: Convert to Tracklets
4. See log:

### Relevant log output

```shell
Analyzing D:\dlc_vr_arena_twocrickets\ARPrey-Matt-2021-09-14\test-videos\08_10_2021_12_24_45_ARPrey_DG_210203_a_succ_camo_crickettexture_twocrickets_capturelight_sl75_led25DLC_dlcrnetms5_ARPreySep14shuffle1_100000.h5
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "C:\Users\mmccann\repos\DeepLabCut\deeplabcut\gui\analyze_videos.py", line 414, in convert2_tracklets
    deeplabcut.convert_detections2tracklets(
  File "C:\Users\mmccann\repos\DeepLabCut\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 1458, in convert_detections2tracklets
    ass.assemble()
  File "C:\Users\mmccann\repos\DeepLabCut\deeplabcut\pose_estimation_tensorflow\lib\inferenceutils.py", line 737, in assemble
    assemblies, unique = self._assemble(data_dict, i)
  File "C:\Users\mmccann\repos\DeepLabCut\deeplabcut\pose_estimation_tensorflow\lib\inferenceutils.py", line 654, in _assemble
    p = max(self.calc_link_probability(link), 0.001)
  File "C:\Users\mmccann\repos\DeepLabCut\deeplabcut\pose_estimation_tensorflow\lib\inferenceutils.py", line 329, in calc_link_probability
    sigma = self._kde.covariance[i, j]
IndexError: index 1 is out of bounds for axis 1 with size 1
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
First q, how does the full.mp4 video look? (and/or the maps, you can plot a few images from the GUI tab)?

> This could be increased, but the individuals of interest are very small in each frame.

could you give us a sense of how small? note, the default pixels to consider is 17; see Nature Protocols Box 2 (or here: https://images.squarespace-cdn.com/content/v1/57f6d51c9f74566f55ecf271/1570325287859-NHCTKWOFWPVWLH8B79PS/ke17ZwdGBToddI8pDm48kApwhYXjNb7J-ZG10ZuuPUJ7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z4YTzHvnKhyp6Da-NYroOW3ZGjoBKy3azqku80C789l0uRNgJXBmK_J7vOfsoUyYccR03UZyExumRKzyR7hPRvjPGikK2uEIM-3GOD5thTJoQ/Box2-01.png?format=1000w)
![Screen Shot 2021-09-22 at 4 21 11 PM](https://user-images.githubusercontent.com/28102185/134361607-c8ba45c2-19fb-4efd-bc96-ce16fa84650d.png)

**Comment by mk-mccann** [comment]
The full video looks good. 

The individuals are small, on the order of 12 pixels. I believe this is the error, as you pointed out above. I can see the maps overlapping for the small individuals (see images below - the mouse is not multi-animal being tracked here). 
![Overlapping maps](https://user-images.githubusercontent.com/9754965/134873148-009289cf-1e66-4176-81bf-57baf713825d.png)
![Non-overlapping maps](https://user-images.githubusercontent.com/9754965/134873188-cf41d5a9-5daf-41ba-b47c-c79f73a33600.png)

I'll drop the pos_dist_thresh to something small like 4 pixels or so, and see if that works.
