### ISSUE TITLE
kill zombies in Outlier_frames.py (clip.close, fixed)

### ISSUE THREAD

**Issue by timegate** [DeepLabCut/DeepLabCut#152]
**Your Operating system and DeepLabCut version**

Windows 10, Anaconda Env & DeepLabCut 2.0

**Problem and Solution**
When I execute below command with "videofile_path that have many videos",
deeplabcut.extract_outlier_frames(path_config_file,videofile_path, outlieralgorithm='jump', comparisonbodyparts=['Snout', 'TailBase'], epsilon=110, automatic=False)

It works well when it finds outlier frames from first video, but It puts error when it finds outliers from second video. 

And I found that It's caused by zombie "clip" objects, however it can be fixed easily by adding 
clip.close()
in 377 line(after the "for index in frames2pick: ~" statement) of outlier_frame.py.
(Please refer to https://github.com/Zulko/moviepy/issues/73, https://github.com/Zulko/moviepy/issues/164, https://stackoverflow.com/questions/43966523/getting-oserror-winerror-6-the-handle-is-invalid-in-videofileclip-function)

I don't know whether the problem is specified to windows... so please also check in other environments. 

I hope it will be fixed in future version! Thanks.

**Comment by AlexEMG** [comment]
Related to https://github.com/AlexEMG/DeepLabCut/pull/94 -- will be fixed in next push. See https://github.com/AlexEMG/DeepLabCut/commit/4d5d410cad05d6317d83f3873ca3e038589048b9
