### ISSUE TITLE
Documentation doesn't link to DLC-GPU.yaml

### ISSUE THREAD

**Issue by kamdh** [DeepLabCut/DeepLabCut#1525]
We have been having issues getting gpu to work. On this documentation page:
https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/installation.md
there is a reference to "DLC-GPU" but no link to a relevant yaml file.

There should be a link added to http://www.mackenziemathislab.org/s/DLC-GPU.yaml in this documentation. Better yet, the yaml files could be included in the repo.

Also, a general suggestion would be to work on adding written documentation rather than having much of it in youtube videos.

Thank you very much for all of your work!

**Comment by MMathisLab** [comment]
On both deeplabcut.org, if you download the conda file, it is DEEPLABCUT.yaml, and in the conda folder here: https://github.com/DeepLabCut/DeepLabCut/tree/master/conda-environments

@kamdh, I do not see any ref. to DLC-GPU on the page - can you elaborate?

Also, all the docs are here: https://deeplabcut.github.io/DeepLabCut/docs/README.html - there is no step that is only in a video (in total, there are >64 pages of docs and a full paper on how to use DeepLabCut: https://www.nature.com/articles/s41596-019-0176-0

**Comment by kamdh** [comment]
Thanks for your response! 
In https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/installation.md there is a reference under GPU support:
"THIRD: Follow the steps above to get the DLC-GPU conda file and install it!"
which made us think that we would need that config file. Perhaps it is not necessary?

Looking at the two files, there are some differences in the included packages, the DLC-GPU.yaml file includes tensorflow-gpu and the DEEPLABCUT.yaml file does not.

Thanks for the pointer to the various documentation. Despite poring over the site, we somehow could not find them all, but I am happy to report that our GPU computations are now working (using DLC-GPU.yaml)

**Comment by MMathisLab** [comment]
fixed: https://github.com/DeepLabCut/DeepLabCut/pull/1531

please note, the old file will not work with the latest code and tensorflow, I would follow the top part of the installation and use DEEPLABCUT.yaml ;)

**Comment by kamdh** [comment]
Realizing this is closed, but is it necessary to `pip install tensorflow-gpu cudnn` after using DEEPLABCUT.yaml?

**Comment by MMathisLab** [comment]
@kamdh no you don't need to run pip install tensorflow-gpu, that behavior was for TF versions 1, and changed, hence why we can put out only 1 conda file now, AND deeplabcut installs TF>2 now by default.
