### ISSUE TITLE
skimage resize for paf

### ISSUE THREAD

**Issue by yeshaokai** [DeepLabCut/DeepLabCut#1528]
**Is there an existing issue for this?**
No
**Bug description**
When number of channel for paf exceeds 512, opencv resize cannot hanlde it and raise an error
**Operating System**
Linux 18.06
**DeepLabCut version**
2.2.0.2
**DeepLabCut mode**
Multiple animal
**Device type**
GPU
**Steps To Reproduce**
Have number of joints more than 25 and use full graph

**Comment by jeylau** [comment]
@yeshaokai, that's fixed with #1529
