### ISSUE TITLE
deeplabcut.label_frames() does not exist when trying to do it on the Colab 

### ISSUE THREAD

**Issue by AlphaNiner1415** [DeepLabCut/DeepLabCut#1532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I'm trying to run deeplabcut on GoogleColab but when I try to run deeplabcut.label_frames() it comes up as an error of AttributeError: module 'deeplabcut' has no attribute 'label_frames'

### Operating System

MacOS/Google Colab

### DeepLabCut version

'2.2.0.2'

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by backyardbiomech** [comment]
Colab cannot load GUI functions. If you look at any of the example colab notebooks, they list at the top which actions you can do in Colab. 

Label with a local installation, then shift to colab.

**Comment by AlphaNiner1415** [comment]
> Colab cannot load GUI functions. If you look at any of the example colab notebooks, they list at the top which actions you can do in Colab.
> 
> Label with a local installation, then shift to colab.

Ahh so there is no way to label the video online right?

**Comment by MMathisLab** [comment]
currently, no, you need to install the GUI - typically it easily works to keep the project buiding and labeling local, then upload the folder to gdrive: https://www.youtube.com/playlist?list=PLjpMSEOb9vRFwwgIkLLN1NmJxFprkO_zi
