### ISSUE TITLE
train_network not starting first iteration

### ISSUE THREAD

**Issue by heejaeyunajang** [DeepLabCut/DeepLabCut#154]
**Your Operating system and DeepLabCut version**
Ubuntu 16.04 LTS, Anaconda 3, Python 3.6, DLC 2

**Describe the problem**

deeplabcut.train_network establishes connection with GPU but does not start training. It has been reported in issue #43 previously but no solution was suggested. 
I have recreated training set (which seems to have worked for the person who initially reported) but still does not work. Oddly, it works for training datasets that has been already trained before I had issues.

**Comment by jabrantley** [comment]
**UPDATE:** I apologize, I discovered that the model is training, but it seems that its going very slowly. I am still not certain if the GPU is being used by DLC correctly or not. Sorry for the confusion. 

**Your Operating system and DeepLabCut version**
Windows 10, Anaconda 3, Python 3.6, DLC 2.0.1, Tensorflow 1.12.0, GPU: GTX 1060

**Describe the problem**
I am also having the same issue. I tried relabeling the data twice and made sure that the parameters in config.yaml matched (num joints, joint names, etc.). The training gets stuck at "Starting training...."

To ensure that the GPU is engaged, I run these lines of code to first check the number of the GPU

```python 
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
```

and then to test a computation on the GPU.
```python
with tf.device('/gpu:0'):
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
    c = tf.matmul(a, b)

with tf.Session() as sess:
    print (sess.run(c))
```

Both work correctly and I see a spike in GPU activity when checking the activity in the task manager. The lines of code were taken from [here](https://stackoverflow.com/questions/38009682/how-to-tell-if-tensorflow-is-using-gpu-acceleration-from-inside-python-shell).

**Comment by MMathisLab** [comment]
Based on update: how large are your images, as a 1060 is a relatively small GPU so the computation will be slower... 

Original comments: 
This means you likely have already allocated the gpu memory to be used elsewhere, so it cannot start. Run “nvidia-smi” in the terminal and see if any processes are running and kill them first. 

Please see the demo guide, which describes this as well: https://github.com/AlexEMG/DeepLabCut/blob/master/examples/Docker_TrainNetwork_VideoAnalysis.ipynb

**Comment by MMathisLab** [comment]
“It has been reported in issue #43 previously but no solution was suggested.” 

this issue was fixed, as the user edited the pose_config.yaml inappropriately and then it would not start. If you didn’t edit the yaml incorrectly, it’s likely that you are trying to run multiple processes on your gpu- see above comment.
