### ISSUE TITLE
`ValueError: Data must of shape (nframes, nbodyparts, 3 or 4)`

### ISSUE THREAD

**Issue by filos93** [DeepLabCut/DeepLabCut#1541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

hey sorry to bother you, first of all thanks for the amazing software and all your work-help, secondly I am facing this issue: I cannot create tracks and the .h5 file after converting to tracklets. After converting to tracklets, I get all the right pickle files but when I hit "create tracks" on the gui or I try using the command line the terminal gives me an error telling me: "ValueError: Data must of shape (nframes, nbodyparts, 3 or 4)" (I've attached a screenshot below). I cannot go on, please help me. I was not able to find anything similar to my issue. Again, thanks for all your work.
![Screenshot (89)](https://user-images.githubusercontent.com/64312024/137468960-9454c0dd-9e42-4ad0-a917-5d999908d750.png)

### Operating System

windows 10

### DeepLabCut version

dlc version 2.2.0.2

### DeepLabCut mode

multi animal

### Device type

gpu GeForce GTX 1650 Ti

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@filos93 can you confirm your steps: 

(1) run analyze_videos
(2) deeplabcut.convert_detections2tracklets
(3) deeplabcut.stitch_tracklets --> note, if youf video has a different n of animals than what you trained with, you need to pass this n you expect to find. https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#decision-break-point

it is also helpful not to post an image, but the copy/paste for us. You can format like code by using three ` before and after your input

**Comment by filos93** [comment]
hey thanks for your quick response, yes I'm confirming the steps, I trained the network with two animals and also the test videos contain just two, I initially shortened the videos and downsampled by DLC video editor (don't know if this info can be of help), I used the skeleton tracking method and I hit the calibrate animal assembly tab for creating the tracklets, but again I have all the pickle files as the user guide indicates, I have just this issue with the .h5 file, have you any suggestions? thanks again for your kindness and time

**Comment by filos93** [comment]
hey I tried to use the box tracking method and it worked, I get the .h5 file and everything runs smoothly, according to you why it does not work with the skeleton tracking method? thanks again

**Comment by MMathisLab** [comment]
@filos93 -- the skeleton is by far the least robust, as it requires really clean data (we are considering dropping it entirely, but this is why we don't recommend it anywhere in the docs, GUI, paper, etc); as you likely saw in the paper Lauer et al 2021, we dropped it, as ellispse is always better than box even. I would stick to the ellipse tracker.
