### ISSUE TITLE
h5 files are not saved when running native or in a venv [only 3.9 python]

### ISSUE THREAD

**Issue by louisadamian** [DeepLabCut/DeepLabCut#1546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

when running deeplabcut on native system python 3.9 or in a python 3.9 venv analyze_videos() does not save an h5 file and no error is raised.

### Operating System

macOS 11.6 Big Sur 20G165

### DeepLabCut version

2.2.0.2

### DeepLabCut mode

single animal

### Device type

cpu

### Steps To Reproduce

1. in native macOS python3.9 or 3.10 install deeplabcut from pip
2. have a pretrained model, config.yaml, and video
3. run analyze_videos() on a single video

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by backyardbiomech** [comment]
That's probably because deeplabcut doesn't work with python 3.9. Follow the installation instructions and you'll get a conda env with python=3.8.

**Comment by louisadamian** [comment]
it specifically says on the the [how to install page](https://deeplabcut.github.io/DeepLabCut/docs/installation.html?#technical-considerations) that python 3.7, 3.8, and 3.9 are supported. Is that incorrect?

**Comment by backyardbiomech** [comment]
Ah, I was mentally confusing it with another package I'm working with that is limited to 3.7 and 3.8.  

All of my deeplabcut installations, which were all made with the conda env file, on both mac and windows, are built on python 3.8. Are you trying to avoid conda?

Also, what error is raised? Can you past the traceback?

**Comment by MMathisLab** [comment]
@LouieAdamian there are other packages that are failing now on 3.9 for mac currently, the section you ref is more advanced technical considerations, but if you use our recommended route of conda or docker, you will get 3.8.

can you put the actual log please?

"Bug description
when running deeplabcut on native system python 3.9 or in a python 3.9 venv analyze_videos() does not save an h5 file and now error is raised."

and, are you saying this is specific to 3.9, i.e. you tried with 3.8?

**Comment by louisadamian** [comment]
@backyardbiomech I am trying to avoid conda because I have been having issue with conda when packaging with pyinstaller.
@MMathisLab No python error is being raised. Is there a log file somewhere that could potenially have more information? Sorry I realize I said "now error is raised" originally. I meant to say "no error is raised".

**Comment by MMathisLab** [comment]
@LouieAdamian there are no logs (aside from meta.pickle file) for video analysis; only logs for training. 

> and, are you saying this is specific to 3.9, i.e. you tried with 3.8?

Maybe you missed my edit, but could you confirm? Note, macOS is passing on 3.9. 

Could you try the docker if you don't want to use conda? https://deeplabcut.github.io/DeepLabCut/docs/docker.html

**Comment by louisadamian** [comment]
@MMathisLab I haven't tried 3.8 because it's only getting security support now I wanted to be more current. The reason I don't want to use Conda or Docker is because we're trying to create an binary executable of the software and we've been having trouble with conda and pyinstaller. I don't know how building an executable with docker would would but I can take a look on Monday. I will also see if deeplabcut works with 3.8 in a venv.

**Comment by MMathisLab** [comment]
@LouieAdamian if that is the goal, perhaps you can talk to us about it, as to not duplicate efforts: admin@deeplabcut.org

**Comment by jeylau** [comment]
@LouieAdamian, could you retry the video analysis by passing `save_as_csv=True` to the function? If the csv file does get written, then the analysis has definitely run to the end and it may be something wrong with `pytables`.

**Comment by louisadamian** [comment]
@jeylau when I ran `analyze_videos()` with `save_as_csv=True` in python 3.9 I did get just the CSV file and not the h5 files. and it would appear I am only having this issue with python3.9 and not 3.8 to answer @MMathisLab 's previous question. I think I will just stick with 3.8 for now as TensorFlow does not support 3.10

**Comment by jeylau** [comment]
@LouieAdamian, that's great to hear, in that it indicates that analysis does run to the end. pytables must definitely be causing the problem; I think there are still no py3.9 wheels for it through pip, which is why we encourage using (mini)conda, as `conda install tables` works like a charm.
