### ISSUE TITLE
Help ensuring conda-forge package stays up to date?

### ISSUE THREAD

**Issue by hmaarrfk** [DeepLabCut/DeepLabCut#1549]
I'm here asking if any official developer would like to help keep a conda package (on conda-forge) maintained and updated.

In the last few years, I've found conda and conda-forge to be very useful at integrating software with cross-platform support.

One of the benefits of conda, is that it believes in a "compiled-first" approach to package management. That means that packages like `wxpython` are pre-built for users, and they don't have to struggle getting their system dependenices lined up for the lengthy compilation of wx.

The largest disadvantage for conda (and conda-forge) is that it is often not a "first-class" package for large packages like tensorflow and pytorch (which are backbones of the ML community). 

However, interoperability between channels (and conda-forge) has become a focus as of late and I see interoperability improving.

For what its worth, I'm now able to run deeplabcut on linux by running a command

```
conda create --name dlc deeplabcut wxpython
```

and have the GUI startup without any compilation.

I don't really want to get into the pip vs conda debate, but more just asking if there is interested in sharing the workload.

Best,

Mark

**Comment by MMathisLab** [comment]
hi @hmaarrfk I would not be thrilled actually if this was packaged on conda without us being involved / I also do not want to put this on conda; we are happy with pip (and have cross platform support), we supply an easy-to-use conda env for users, and dockers that support headless, jupyter, and the GUI. 🤗

so, re: https://github.com/conda-forge/staged-recipes/pull/16559 I vote no. 
The other steering counsel member, @AlexEMG can also chip in .https://deeplabcut.github.io/DeepLabCut/docs/Governance.html#steering-council

**Comment by hmaarrfk** [comment]
Hi @MMathisLab,

Thank you so much for chiming in so quickly.

I understand your reservations to wanting to selective about how the package is released and how is shared with others.
I also understand that you have to devote your time where it is more needed to achieve your goals.

The docker images, environments, other supporting documentation you have provided have enabled us to jump start our projects. And for that we are truly grateful. 

However, I do think there are some shortcoming that come with each of those different solution that I believe that conda packages help solve. 

One of the biggest challenges our team has faced is the discrepancy between package names in conda and on pypi. As you have mentionned, supporting the conda community is something that you have identified as useful evidenced by your work on conda environment. However, the pypi package depends on a package called `opencv-python-headless` (for one) that, to my knowledge. does not have a conda counterpart.

This causes pip and conda to clash when trying to integrate `deeplabcut` with other workflows.

An other great benefit of the conda-forge community has been its ability to move quickly on new platform like `osx-arm64` which was released last year by apple. Native tensorflow packages are availble for `osx-arm64` on conda-forge enabling this package to get installed on many new computers. Even if it is only used for the labeling workflow.

My goal in creating a conda package is to provide those that find conda useful with a path to easily integrate `deeplabcut` into their science.

My goal is not to fork your work.

Your help in maintaining the conda-forge package would be greatly appreciated, but is not necessary. 

As mentioned earlier, I do not think it is realistic to expect your help in maintaining every esoteric package management system and operating system.

However, if you would like to help, and have the bandwidth to do so, I would be glad to work with you on the conda packaging front especially in how it relates to the conda-forge channel.

For what it is worth, you can decide to help at any time. Conda-forge makes it very easy to suggest adding yourself as a maintainer even after a project (or "feedstock" as they call it) has been created.
