### ISSUE TITLE
Challenges with Running Labeled Example

### ISSUE THREAD

**Issue by jdabbi** [DeepLabCut/DeepLabCut#155]
**Your Operating system and DeepLabCut version**

**Windows 10, with an Anaconda Env, & DeepLabCut 2.x. I installed anaconda and created the environment using dlc-windowsCPU.yaml**

**I am running the Labeled Example Demo. I have installed ipykernels so that in the jupyter notebook I can change to the dlc-windowsCPU virtual environment. Without, it the "import deeplabcut" fails.** 

**After installing, ipykernels and switching in jupyter notebook to dlc-windowsCPU virtual environment, the "import deeplabcut" suceeds but on the command window I see the following error. How do I get rid of this error?**

ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x0000023F7CAE9400>)
Traceback (most recent call last):
  File "c:\Anaconda3\envs\dlc-windowsCPU\lib\site-packages\tornado\ioloop.py", line 758, in _run_callback
    ret = callback()
  File "c:\Anaconda3\envs\dlc-windowsCPU\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\Anaconda3\envs\dlc-windowsCPU\lib\site-packages\ipykernel\kernelbase.py", line 306, in advance_eventloop
    eventloop(self)
  File "c:\Anaconda3\envs\dlc-windowsCPU\lib\site-packages\ipykernel\eventloops.py", line 238, in loop_tk
    app.tk.createfilehandler(stream.getsockopt(zmq.FD), READABLE, notifier)
AttributeError: '_tkinter.tkapp' object has no attribute 'createfilehandler'

**Also, when I train the network, I get the following output but nothing more. I have let it run for an hour. I see the CPU being consumed and files being generated. When can I stop it. How do I stop it?**

C:\DeepLabCut\Downloads\DeepLabCut-master\examples\Reaching-Mackenzie-2018-08-30/config.yaml
Config:
{'all_joints': [[0], [1], [2], [3]],
 'all_joints_names': ['hand', 'Finger1', 'Finger2', 'Joystick'],
 'batch_size': 1,
 'bottomheight': 400,
 'crop': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_ReachingAug30\\Reaching_Mackenzie95shuffle1.mat',
 'dataset_type': 'default',
 'display_iters': 1000,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'c:\\Anaconda3\\envs\\dlc-windowsCPU\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1000,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_ReachingAug30\\Documentation_data-Reaching_95shuffle1.pickle',
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 4,
 'optimizer': 'sgd',
 'pos_dist_thresh': 17,
 'project_path': 'C:\\DeepLabCut\\Downloads\\DeepLabCut-master\\examples\\Reaching-Mackenzie-2018-08-30',
 'regularize': False,
 'rightwidth': 400,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'C:\\DeepLabCut\\Downloads\\DeepLabCut-master\\examples\\Reaching-Mackenzie-2018-08-30\\dlc-models\\iteration-0\\ReachingAug30-trainset95shuffle1\\train\\snapshot',
 'stride': 8.0,
 'topheight': 400,
 'use_gt_segm': False,
 'video': False,
 'video_batch': False,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
INFO:tensorflow:Restoring parameters from c:\Anaconda3\envs\dlc-windowsCPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt
Restoring parameters from c:\Anaconda3\envs\dlc-windowsCPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'weigh_only_present_joints': False, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': 'C:\\DeepLabCut\\Downloads\\DeepLabCut-master\\examples\\Reaching-Mackenzie-2018-08-30\\dlc-models\\iteration-0\\ReachingAug30-trainset95shuffle1\\train\\snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'sgd', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'mirror': False, 'crop_pad': 0, 'scoremap_dir': 'test', 'dataset_type': 'default', 'use_gt_segm': False, 'batch_size': 1, 'video': False, 'video_batch': False, 'crop': True, 'cropratio': 0.4, 'minsize': 100, 'leftwidth': 400, 'rightwidth': 400, 'topheight': 400, 'bottomheight': 400, 'all_joints': [[0], [1], [2], [3]], 'all_joints_names': ['hand', 'Finger1', 'Finger2', 'Joystick'], 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_ReachingAug30\\Reaching_Mackenzie95shuffle1.mat', 'display_iters': 1000, 'init_weights': 'c:\\Anaconda3\\envs\\dlc-windowsCPU\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt', 'max_input_size': 1000, 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_ReachingAug30\\Documentation_data-Reaching_95shuffle1.pickle', 'multi_step': [[0.005, 10000], [0.02, 430000], [0.002, 730000], [0.001, 1030000]], 'net_type': 'resnet_50', 'num_joints': 4, 'pos_dist_thresh': 17, 'project_path': 'C:\\DeepLabCut\\Downloads\\DeepLabCut-master\\examples\\Reaching-Mackenzie-2018-08-30', 'save_iters': 50000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25}
Starting training....

**Finally, when I evaluate the network, I get no output but the CPU is running and files are getting generated. However, there are no files in the evaluation-results folder. Is this correct?**

**Comment by jdabbi** [comment]
Please close this since some of these have been resolved.

**Comment by MMathisLab** [comment]
please don't open new issues if they are about the same thing, i.e. you closed this but opened #157 ...
