### ISSUE TITLE
 single point tracking in maDLC

### ISSUE THREAD

**Issue by felipearrudamoura** [DeepLabCut/DeepLabCut#1552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi, guys! I have a data collection with several animal, but I want to recognize a single point in each animal (e.g the head). Everything works well until start training. It suddenly closes everything. Does anyone had the same experience? In other versions of DLC I was able to label and train a single point in the animal, but this is the first time with the last version.

### Operating System

WIN 10

### DeepLabCut version

2.2.0.1

### DeepLabCut mode

multi animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@felipearrudamoura yes - multi-animal does not currently support single point tracking; it minimally needs two points per animal. So, currently you would need to add another point; the beauty of maDLC is that is learns to associate bodyparts together, which makes "pose/posture"; otherwise it's just tracking :). But, given a few others asked for this, it's on our TODO list :)

**Comment by felipearrudamoura** [comment]
Perfect, my friends! Thanks for the fast answer!


Prof. Dr. Felipe Arruda Moura
Laboratório de Biomecânica Aplicada - LBA
Centro de Educação Física e Esporte
Universidade Estadual de Londrina
-------------------------------------------------------------
Prof. PhD. Felipe Arruda Moura
Laboratory of Applied Biomechanics
State University of Londrina


Em ter., 19 de out. de 2021 às 07:44, Mackenzie Mathis <
***@***.***> escreveu:

**Comment by felipearrudamoura** [comment]
Thanks, Mackenzie. You are fantastic. How to proceed now? Just update de
DLC version?
Cheers,

Prof. Dr. Felipe Arruda Moura
Laboratório de Biomecânica Aplicada - LBA
Centro de Educação Física e Esporte
Universidade Estadual de Londrina
-------------------------------------------------------------
Prof. PhD. Felipe Arruda Moura
Laboratory of Applied Biomechanics
State University of Londrina


Em dom., 7 de nov. de 2021 às 14:15, Mackenzie Mathis <
***@***.***> escreveu:
