### ISSUE TITLE
The DLC Model Zoo `ipynb` specifies `TensorFlow1.x.x` - Should that be bumped up to `TensorFlow 2.x.x`?

### ISSUE THREAD

**Issue by jonmatthis** [DeepLabCut/DeepLabCut#1555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I know that full support for TF2 is fairly recent, so I was wondering if y'all had forgotten to update that `ipynb`, or if there is a reason to keep that Notebook tied to TF1

### Operating System

Google Colab

### DeepLabCut version

Whatever gets installed in that ipynb

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
The models are trained with TF1.13; so they will not run in TF at this point. In the near future though the zoo gets an upgrade, so stay tuned!
