### ISSUE TITLE
Multi-animal prediction using deeplabcut model_export

### ISSUE THREAD

**Issue by ArdeleanRichard** [DeepLabCut/DeepLabCut#1558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Exporting the model created and using it to predict seems to leave out coordinates.

### Operating System

Microsoft Windows 10 Home
Version: 10.0.19042 Build 19042

### DeepLabCut version

DLC version: 2.2.0.2

### DeepLabCut mode

multi animal

### Device type

CPU: AMD Ryzen 9 5900HX with Radeon Graphics, 3301 Mhz, 8 Core(s), 16 Logical Processor(s)
GPU: NVIDIA GeForce RTX 3080 Laptop

### Steps To Reproduce

1. Used the DLC-GUI to label the keypoints of 3 individuals, each with 3 body parts. 
2. Trained multiple models: dlcrnet_ms5, restnet50, efficientnet-b0 with the same results. 
3. Video analysis returns the expected and intended result. With markers showing 3 different individuals and 3 different body parts.

3b. Using the deeplabcut.export_model() to create a .pb model to be used for separate predictions.
   4. Running on a selected image will return an array of 3 arrays each with 3 elements.
Example: 
[414.4364  412.214     1.     ]
[411.30463 455.03662   1.     ]
[401.72665 456.98535   1.     ]
As far as I understand, 3 individuals, 3 body parts, 3 values (2 coordinates + 1 likelihood)  should return 3*3*3 = 27 values. But in these cases it returns only 9. These values are not the coordinates of the 3 body parts of 1 individual, nor are they the coordinates of 1 body part from 3 individuals. 
This can be seen in the following image:
![image](https://user-images.githubusercontent.com/37302327/138836870-0ac56f19-da83-402f-b84f-806fb613bc1a.png)

In the video created, all the coordinates (of 3 individuals and 3 body parts for each can be viewed):
![image](https://user-images.githubusercontent.com/37302327/138837618-b28f788c-9161-4e52-92a7-51f300939c93.png)

### Anything else?

Code for loading .pb model:

import tensorflow as tf
import cv2

def load_pb(path_to_pb):
    with tf.compat.v1.gfile.GFile(path_to_pb, "rb") as f:
        graph_def = tf.compat.v1.GraphDef()
        graph_def.ParseFromString(f.read())
    with tf.Graph().as_default() as graph:
        tf.import_graph_def(graph_def, name='')
        return graph

graph = load_pb(PATH_TO_PB_MODEL)

with tf.compat.v1.Session(graph=graph) as sess:
    input = graph.get_tensor_by_name('Placeholder:0')
    output = graph.get_tensor_by_name('concat_1:0')

    image = cv2.imread(IMAGE_PATH)
    test = sess.run(output, feed_dict={input: [image]})

The arrays shown in the reproduction steps are the 'output'.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Hi @ArdeleanRichard `model_export` only is supported for single animal mode for real-time DLC.

**Comment by MMathisLab** [comment]
I updated the docs, thanks for pointing out it was unclear! https://github.com/DeepLabCut/DeepLabCut/commit/ddbacd2db5f76fba8316d5cb32db6f76dbf3dcf2

**Comment by ana-ich** [comment]
Is it possible to have model_export for multi animal in the future?

**Comment by MMathisLab** [comment]
yes, but it will not be something we support in the near term, but it's on the longer horizon roadmap :)

**Comment by ana-ich** [comment]
I see, thanks!
