### ISSUE TITLE
deeplabcut.calibrate_cameras is throwing an error related to nimages

### ISSUE THREAD

**Issue by anmolbyte** [DeepLabCut/DeepLabCut#1559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I'm trying to run deeplabcut.calibrate cameras, but I'm getting an issue when I try to run it. The error states that nimages must be 350, when it is instead finding 175. I'm not sure where this error stemmed from, since I have 350 images in my calibration folder. How do I begin to solve this issue

![image](https://user-images.githubusercontent.com/63212389/138916489-1fa05830-5514-457b-9d29-ff8e7f0ad641.png)

### Operating System

Windows 10 

### DeepLabCut version

2.2.0.2

### DeepLabCut mode

3d

### Device type

1050TI

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by anmolbyte** [comment]
Love y'all by the way

**Comment by MMathisLab** [comment]
Hi @ajarang hard for me to debug this specific issue, as we don't hit this (and as you suggest, seems linked to images in the folder; is it possible 1 image is missing? You can also try downgrading openCV, just in case; I believe the latest I have tried is 4.3)

**Comment by anmolbyte** [comment]
Weird. We restarted the computer and it seems to work fine now. Thanks for your help!
