### ISSUE TITLE
Is safe that .png files are deleted after refine_labels?

### ISSUE THREAD

**Issue by timegate** [DeepLabCut/DeepLabCut#156]
**Your Operating system and DeepLabCut version**

Windows, Anaconda Env & Deeplabcut 2.0

**Describe the problem**

After refining with method 'jump' (+merge, train again),  I extracted outlier frames with method 'uncertain'.
So there were machine_labels, machine_labels-iter0.h5 file, and machine_labels-iter1.h5 in LinearChamber-KAIST-2018-11-19\labeled-data\20180906_Trial1.

But, I deleted all img~labeled.png by mistake and now I'm worry about the fact that my refining work with 'jump' can be removed in next merging step. is it safe? or should I do it once more?

Thanks in advance.

**How to Reproduce the problem**
1. extract_outlier_frames with method 'jump'
2. refine_labels
3. merge_datasets
4. create_training_dataset
5. create_labeled_video
6. extract_outlier_frames with method 'uncertain'
7. remove png files(frames) with method 'jump' by mistake

**Comment by MMathisLab** [comment]
Deleting images won’t effect the network, so it’s fine. Also, please post help questions here: https://forum.image.sc/tags/deeplabcut
