### ISSUE TITLE
GUI only get framework, without any word

### ISSUE THREAD

**Issue by Jason66661010** [DeepLabCut/DeepLabCut#1562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

![image](https://user-images.githubusercontent.com/47680845/139439354-e4a34a35-f0e9-417c-93fd-6e898106d1b3.png)

like this...

### Operating System

WIN10

### DeepLabCut version

2.2rc3、2.2rc2 the same problem 

### DeepLabCut mode

multi animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @Jason66661010, is that something you observe with deeplabcut 2.2.0.2 (the latest) too?

**Comment by Jason66661010** [comment]
> Hi @Jason66661010, is that something you observe with deeplabcut 2.2.0.2 (the latest) too?

yep，CMD get no error:

(deeplabcut) D:\>python -m deeplabcut
2021-10-30 16:45:53.248116: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Starting GUI...

but the GUI still have the same problem ……

**Comment by jeylau** [comment]
What version of wxpython do you run? Was it installed automatically upon creating the environment?

**Comment by Jason66661010** [comment]
wxPython                      4.0.7.post2

I first installed the deeplabcut ,then I installed deeplabcut[gui], wxPython was installed automatically.
Is the version of wxPython caused this problem? :(

**Comment by SamsonRuan** [comment]
I can  get framework with words,but can not load pictures which come from labeled-data dir?

**Comment by MMathisLab** [comment]
this is strange, and I cannot reproduce; what language is your computer in?

**Comment by Jason66661010** [comment]
> this is strange, and I cannot reproduce; what language is your computer in?

Chinese

I switched the wxPython from 4.0.5 to 4.1.1 , it's still get this problem. 
My tensorflow version is 2.2.0
deeplabcut[gui] version 2.2.0.2 for now

**Comment by MMathisLab** [comment]
4.1.1 isn't supported, so it must be `wxPython 4.0.7.post2`. I know users who's computers are in chinese and it works, so I am not sure... You can also use the new alpha GUI here to label, https://github.com/DeepLabCut/napari-DeepLabCut


[@SamsonRuan be sure you have admin permission; when you open the terminal you must right click and say open as admin on windows; but there are other issues that cover this]

**Comment by jeylau** [comment]
@Jason66661010, did downgrading to `wxPython==4.0.7.post2` solve your issue?

**Comment by Jason66661010** [comment]
> @Jason66661010, did downgrading to `wxPython==4.0.7.post2` solve your issue?

no ,I tried that way, unfortunately it's not working.
I update the version of my CUDA to 11.2 to support the tensorflow 2.7
Then I simply ran 'conda env create -f DEEPLABCUT.yaml' and it worked this time!
Thanks for your help! :)
