### ISSUE TITLE
HDF5 File not found

### ISSUE THREAD

**Issue by ayah26** [DeepLabCut/DeepLabCut#1564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

<img width="1523" alt="Screen Shot 2021-11-01 at 12 36 48 PM" src="https://user-images.githubusercontent.com/89812935/139722786-2eb6c5f9-41b8-43d9-a476-2d7d4f5fb3ba.png">

### Operating System

macOS Big Sur

### DeepLabCut version

2.2.0.2

### DeepLabCut mode

single animal

### Device type

gpu

### Anything else?

I am working in google colab

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by backyardbiomech** [comment]
Hi, @ayah26: It will be difficult to help without more information. It looks like you are on a mac, but running this in Google Colab. Correct? Is this one of the demo notebooks, or your own? What happened before this - what code did you run, and what were the specifics? For example, if you ran `train_network`, for how many iterations did you train and what did you set `maxiters` and `saveiters` to? If you look in your project folder > `dlc-models` > latest iterations > desc > train, do you see three files per snapshot? In `config.yaml`, what is `snapshotindex` set to?
