### ISSUE TITLE
version of tensorflow

### ISSUE THREAD

**Issue by Jason66661010** [DeepLabCut/DeepLabCut#1568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

which version of deeplabcut use the tensorflow which <=2.3.0?

when I use command “pip install deeplabcut==2.0.0” it installed tensorflow2.7.0 automatically… it is too new for me that my CUDA 10.2 is not compatible with that…

### Operating System

WIN10

### DeepLabCut version

deeplabcut2.0.0
deeplabcut2.2.0.2
…

### DeepLabCut mode

multi animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Hi @Jason66661010 we ask questions go to the forum: https://forum.image.sc/tag/deeplabcut 

But in short, you can use any version of tensorflow; so, while this is going to install the latest, you can simply run `pip uninstall tensorflow` and use a version that works with CUDA 10.2, i.e., see here: https://www.tensorflow.org/install/source#gpu i.e., pip install tensorflow==2.2.0`

I would recommend updating your cuda though, so you can leverage the latest tensorflow versions.
