### ISSUE TITLE
Users on windows are unable to save labels in a csv file created on a mac

### ISSUE THREAD

**Issue by davidmurray** [DeepLabCut/DeepLabCut#1569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Note: This might be related to issue #1550.

In my team, we are annotating a large set of images in a distributed manner. Some are on Windows and some are one macOS.

I started annotating the labels first and thus the annotation csv file was created on a mac.
The people on Windows are able to use DeepLabCut to annotate, but once they click 'Save' in the labeling gui, move to the next image and then come back to the recently annotated image, the annotations are missing. Only the picture is shown.

I suspect that this is due to the slash issue in the csv file. In fact, the data _is being saved_ to the csv file on Windows, but with slashes in a different direction:

```csv
labeled-data/wall_video1_camera1/img03713.png,,,,,,,,,,,,,448.88407527032723,128.84763095070912,,,,,,,498.7107850021065,63.92191826990586,737.275031596686,137.90703272012354
labeled-data/wall_video1_camera1/img03736.png,251.0871366381126,245.10995365819406,385.4682628844264,130.35753124561154,294.8742451902823,223.97134952956048,,,403.5870664232551,287.3871619154613,331.11185226793987,320.60496840331416,441.33457379581523,260.20895660721806,,,331.11185226793987,213.40204746524364,269.2059401769414,175.65454009268365,467.0028788091561,115.25852829658754,,
labeled-data/wall_video1_camera1/img03737.png,241.57386056303366,238.4435191309878,,,290.10178824921286,219.42581774045814,,,360.2705485522016,326.31841521136624,332.72767067626205,315.1701074996764,446.83387901944,262.7074829740774,,,339.285498741962,206.96594441562837,264.5262587929833,173.52102128055895,448.14544463258005,125.6488764009498,,
labeled-data/wall_video1_camera1/img03828.png,,,,,,,,,,,,,,,,,,,,,,,,
labeled-data\wall_video1_camera1\img00668.png,,,984.8986799606797,621.075127088892,,,,,,,,,,,,,1049.824392641483,482.16429995787104,1099.6511023732623,510.85240556101667,,,,
labeled-data\wall_video1_camera1\img00725.png,,,1086.0619997191407,396.09998314843415,,,1227.9883940366112,380.1384600868089,,,,,987.2423388149944,439.613710811563,,,1185.7154191826994,337.2138716472406,1192.9701728342889,384.1636305485501,1027.4235563968878,526.4051407884529,,
labeled-data\wall_video1_camera1\img01386.png,,,216.35942985535735,699.5899424238169,,,,,,,,,,,,,140.8644151102373,545.5801123437718,195.22082572672372,522.9316079202358,,,,
labeled-data\wall_video1_camera1\img01418.png,,,133.31491363572525,257.1891560174132,,,,,,,,,,,193.71092543182135,384.020780789215,180.12182277769972,190.75354304170764,219.3792304451622,199.81294481112207,84.99810419884841,384.020780789215,121.23571127650604,661.8424350512568
labeled-data\wall_video1_camera1\img01812.png,220.88913074006456,509.34250526611424,210.31982867574777,284.3673613256565,234.75959000498978,456.52123643882175,,,,,,,,,,,231.833871348454,394.1059050993912,173.31949821773782,394.1059050993912,230.8586317962754,200.03323421584923,356.66453402731514,83.00448795441696
labeled-
```

Is there a way to always write with the slashes in the same direction? Right now, this bug seems to be preventing us from annotating collaboratively, which is a bummer.

Thanks,
David

### Operating System

Windows 10 or macOS Catalina

### DeepLabCut version

2.2.0.2

### DeepLabCut mode

single animal

### Device type

CPU

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by backyardbiomech** [comment]
There's a [function](https://github.com/DeepLabCut/DeepLabCut/blob/3d74d33fc63e3d3fc6687fa4ecef3bdec3bf96de/deeplabcut/utils/conversioncode.py#L21) for that. 
If you want to label on a mac, run:
```
deeplabcut.convertannotationdata_fromwindows2unixstyle(config, userfeedback=True, win2linux=True)
```
It will ask you to approve which folder(s) to convert (that's the `userfeedback` flag).

To label on windows, change `win2linux` to `False`.

Then, before creating your training dataset, run it again, targeting whichever platform you train on.
