### ISSUE TITLE
Help with some issues when running the Samples

### ISSUE THREAD

**Issue by jdabbi** [DeepLabCut/DeepLabCut#157]
**Your Operating system and DeepLabCut version

Windows 10, with an Anaconda Env, & DeepLabCut 2.x. I installed anaconda and created the environment using dlc-windowsCPU.yaml

I am running the Labeled Example Demo. I have installed ipykernels so that in the jupyter notebook I can change to the dlc-windowsCPU virtual environment. Without, it the "import deeplabcut" fails.

After installing, ipykernels and switching in jupyter notebook to dlc-windowsCPU virtual environment, the "import deeplabcut" suceeds but on the command window I see the following error. How do I get rid of this error?**

ERROR:tornado.application:Exception in callback functools.partial(<function wrap..null_wrapper at 0x0000023F7CAE9400>)
Traceback (most recent call last):
File "c:\Anaconda3\envs\dlc-windowsCPU\lib\site-packages\tornado\ioloop.py", line 758, in _run_callback
ret = callback()
File "c:\Anaconda3\envs\dlc-windowsCPU\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
return fn(*args, **kwargs)
File "c:\Anaconda3\envs\dlc-windowsCPU\lib\site-packages\ipykernel\kernelbase.py", line 306, in advance_eventloop
eventloop(self)
File "c:\Anaconda3\envs\dlc-windowsCPU\lib\site-packages\ipykernel\eventloops.py", line 238, in loop_tk
app.tk.createfilehandler(stream.getsockopt(zmq.FD), READABLE, notifier)
AttributeError: '_tkinter.tkapp' object has no attribute 'createfilehandler'

**The pose_cfg file is in multiple directories. Which one do I edit? The one I edited got overwritten when I trained the model.**

**Comment by AlexEMG** [comment]
The pose_cfg file is in multiple directories. Which one do I edit? 

Please note the following:

**Default configuration: ** 
wherever DLC is installed there will be two files:

installationpath/deeplabcut/pose_cfg.yaml and installationpathdeeplabcut/pose_estimation_tensorflow/default_config.py
that specify the default values. These are mostly used **before** the configuration file for a particular model is created. [However, values that are not contained in ```pose_cfg.yaml``` will be taken from ```default_config.py```

You can look at those here (note this is not the relevant place on your system):
https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/pose_cfg.yaml and 
https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/pose_estimation_tensorflow/default_config.py


**Once the model has been crated:** 
then you can edit the corresponding ```pose_config.yaml```, i.e. in projectpath/dlc-models/iteration-x/namedatetrainsetxshufflex with the correct constants referring to the model that you want to train

**Comment by demondi** [comment]
I am still confused about the 'AttributeError' encountered. How did you solve it?
