### ISSUE TITLE
TypeError: analyze_videos() got an unexpected keyword argument 'video'

### ISSUE THREAD

**Issue by ehsainit** [DeepLabCut/DeepLabCut#1570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Analyzing a video using the following command `python3 dlc.py analyze-videos config.yaml videos/vid.mkv` results in the following type error:

`TypeError: analyze_videos() got an unexpected keyword argument 'video'`

I think it is just a typo in the name of a parameter **video** :

https://github.com/DeepLabCut/DeepLabCut/blob/0902886377a83dc9ff26a1ea074fff5e571f5838/deeplabcut/cli.py#L285

which is used here :

https://github.com/DeepLabCut/DeepLabCut/blob/0902886377a83dc9ff26a1ea074fff5e571f5838/deeplabcut/cli.py#L322

whereas this function expect **videos** plural:

https://github.com/DeepLabCut/DeepLabCut/blob/0902886377a83dc9ff26a1ea074fff5e571f5838/deeplabcut/pose_estimation_tensorflow/predict_videos.py#L44

### Operating System

Windows 10

### DeepLabCut version

2.2.0.2

### DeepLabCut mode

single animal

### Device type

does not matter

### Steps To Reproduce

See description 

### Relevant log output

```shell
Traceback (most recent call last):
  File "dlc/DeepLabCut/dlc.py", line 18, in <module>
    main()
  File "dlc/DeepLabCut/dlc.py", line 14, in main
    cli.main()
  File "anaconda3\envs\DEEPLABCUT\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "anaconda3\envs\DEEPLABCUT\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "anaconda3\envs\DEEPLABCUT\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File anaconda3\envs\DEEPLABCUT\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "anaconda3\envs\DEEPLABCUT\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "anaconda3\envs\DEEPLABCUT\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "dlc\DeepLabCut\deeplabcut\cli.py", line 321, in analyze_videos
    predict_videos.analyze_videos(*args, **kwargs)
TypeError: analyze_videos() got an unexpected keyword argument 'video'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Hey @ehsainit good catch! indeed likely just a typo; happy if you'd like to PR the change to https://github.com/DeepLabCut/DeepLabCut/blob/0902886377a83dc9ff26a1ea074fff5e571f5838/deeplabcut/cli.py#L285

**Comment by ehsainit** [comment]
Hey @MMathisLab  gladly ... just took a thorough look at the file ...  seems like it was repeated few times :

https://github.com/DeepLabCut/DeepLabCut/blob/0902886377a83dc9ff26a1ea074fff5e571f5838/deeplabcut/cli.py#L333
https://github.com/DeepLabCut/DeepLabCut/blob/0902886377a83dc9ff26a1ea074fff5e571f5838/deeplabcut/cli.py#L461

will include them in the pull request

cheers !
