### ISSUE TITLE
Possible typo in outlier_frames. compute_deviations()

### ISSUE THREAD

**Issue by quantumdot** [DeepLabCut/DeepLabCut#1574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I suspect a typo in `deeplabcut.refine_training_dataset.outlier_frames.compute_deviations()`:
https://github.com/DeepLabCut/DeepLabCut/blob/50489743b27b0a36747a1911a4cce1971dc0107c/deeplabcut/refine_training_dataset/outlier_frames.py#L491

Should this not read as:
```
(x < CIx[:, 0]) + (x > CIx[:, 1]) + (y < CIy[:, 0]) + (y > CIy[:, 1])
# This should be y, not x?  ---------^
```

### Operating System

Windows

### DeepLabCut version

dlc version

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by AlexEMG** [comment]
Yes, that's a typos. Feel free to make a PR.

**Comment by quantumdot** [comment]
sure, see #1582 for PR
