### ISSUE TITLE
ImportError: Missing optional dependency 'tables'.  Use pip or conda to install tables.

### ISSUE THREAD

**Issue by Jason66661010** [DeepLabCut/DeepLabCut#1575]
ImportError: Missing optional dependency 'tables'.  Use pip or conda to install tables.
I ran these commands:

conda uninstall pytables
pip install tables

but the error still there.
how to fix it?
(deeplabcut[gui] version is 2.2.0.2)

_Originally posted by @Jason66661010 in https://github.com/DeepLabCut/DeepLabCut/issues/1445#issuecomment-967780171_

**Comment by MMathisLab** [comment]
Closing as this is a redundant issue: (see 8 issues) https://github.com/DeepLabCut/DeepLabCut/search?q=ImportError%3A+Missing+optional+dependency+%27tables%27.&type=issues

**Comment by TinyAnts** [comment]
Hi,
In the latest version of DLC, tables are already installed and pytables are not even there in conda list. Still the same error (optional tables has to be installed) persists. Please help me out. Even complete reinstall of anaconda shows the same error!

**Comment by Jason66661010** [comment]
> Hi, In the latest version of DLC, tables are already installed and pytables are not even there in conda list. Still the same error (optional tables has to be installed) persists. Please help me out. Even complete reinstall of anaconda shows the same error!

Did you solve this problem yet?

**Comment by TinyAnts** [comment]
not yet, even reinstalled anaconda and completely started from scratch, still the error persists...

**Comment by MMathisLab** [comment]
Hi @TinyAnts and @Jason66661010 did you check out the other threads? This typically happens if you don't have admin permissions, so please check the threads above carefully. As you point out, it is installed with deeplabcut when you run pip install deeplabcut, so this is very operating system+user specific issue that there can't be more that we can do aside from pointing down the paths ;/.

**Comment by TinyAnts** [comment]
Yeah read every single thread, most of it is for older versions and it is related to pytables vs tables...the newer version does not have those issues. I installed everything from the yaml file based env creation though to avoid any issues. Still could not find a solution, is there a way to create csv to h5 file, I even tried the helper function in utils, it has its own bunch of errors. Do you recommend different OS or conda based installation or my own env with just pip install deeplabcut or it is due to gui (I used this)or non-gui version? Please let me know thanks in advance though...for your time.

**Comment by MMathisLab** [comment]
its the same issue though; i.e., if you don't open terminal by right click "as an admin" then this will happen, I assume you are using windows?

**Comment by TinyAnts** [comment]
Yeah actually opened via admin access and ran the sample demo jupyter book, still got the same error. But did not create env with admin access I guess (just std terminal intallation), now I am trying to install again and create env once again via yaml file with admin access. Let's see how it goes! thanks for the continual support!

**Comment by TinyAnts** [comment]
Did the admin access stuff, installed and ran everything from admin, still the same error though...

**Comment by TinyAnts** [comment]
Hi,
I finally fixed the error!
Solution - Avoid using the yaml file at this point. Manually install all the libraries needed by reading the yaml file and making sure versions are matching as well... But the team is very responsive and very helpful for the most part... a great library to play with...Thanks to the devs...

**Comment by MMathisLab** [comment]
Great!  BTW, I think the error might have been simple; in Jupyter when you open it, you need to be sure you select the correct env kernel: maybe DEEPLABCUT was not selected?

![Screen Shot 2021-11-23 at 9 19 24 PM](https://user-images.githubusercontent.com/28102185/143097726-f80fafdc-3a8a-455a-83d2-80bb6206b870.png)

PS - also you could also use COLAB for free, just so you can move forward (and trust me the code works 🤗), i.e. here you can upload your project folder to google drive, etc: https://github.com/DeepLabCut/DeepLabCut/tree/master/examples/COLAB

**Comment by TinyAnts** [comment]
Yeah, for sure thanks for the colab recommendations! definitely have to start using it more often. 

And also I always checked that I had the right kernel selected though...I tried on a different PC as well, just in case. Just a heads-up if someone comes up with the same error, maybe if they manually install the libraries it might solve the issues and also maybe the yaml file has to be checked or revamped I guess...But overall one of the coolest libraries to use though! thanks again...Soon I can imagine when we combine vision transformers in the pipeline for better temporal relations between the frames... Maybe I can start writing code sooner to compare performances... Keep up the good work!

About myself, I am a graduate machine learning engineer (TU Berlin dual masters) and veterinary medicine student (currently studying)  & working on animal behavior/protien expr/gene expr at the moment out of interest!  
LinkedIn - https://www.linkedin.com/in/nagaraj21/

**Comment by Jason66661010** [comment]
> Avoid using the yaml file at this point. Manually install all the libraries needed by reading the yaml file and making sure versions are matching as well...

could you offer me a list of all the packages please?  I tried your way but still got the same error. Maybe somewhere the version of  some packages are still incompatible...  Thanks a lot for your help!!!

**Comment by MMathisLab** [comment]
@Jason66661010 there is zero you need aside from running in the terminal `pip install 'deeplabcut[gui]'` the conda file is just if you are a conda user and want to use it. Nothing is installed from the conda file that affects deeplabcut.

**Comment by MMathisLab** [comment]
@TinyAnts check out; https://arxiv.org/abs/2103.12115

**Comment by TinyAnts** [comment]
> > Avoid using the yaml file at this point. Manually install all the libraries needed by reading the yaml file and making sure versions are matching as well...
> 
> could you offer me a list of all the packages, please? I tried your way but still got the same error. Maybe somewhere the version of some packages is still incompatible... Thanks a lot for your help!!!

Hi, I created a new env, with python 3.8, then filled with PyTorch with cuda 11.5 as it installs most of the basic libs in parallel even though we don't need PyTorch in the code, then installed TensorFlow GPU and look at conda list you might get the tables also preinstalled as well...so just hop on to the code and run the demo jupyter notebooks given by the devs of this repo...Hope this was helpful....

**Comment by TinyAnts** [comment]
> @TinyAnts check out; https://arxiv.org/abs/2103.12115

looks like you guys are already at work! and it also beats the R50 in most areas as well that is so cool...Will this be integrated in the DLC REPO soon? is there a public GitHub version of this implementation?

**Comment by Jason66661010** [comment]
> @Jason66661010 there is zero you need aside from running in the terminal `pip install 'deeplabcut[gui]'` the conda file is just if you are a conda user and want to use it. Nothing is installed from the conda file that affects deeplabcut.

I update the version of my CUDA to 11.2 to support the tensorflow 2.7
Then I simply ran 'conda env create -f DEEPLABCUT.yaml' and it worked this time!
Thanks for your help! :)

**Comment by juliencarponcy** [comment]
Hey,

Curiously I have the same issue. I've updated drivers and installed both through Conda, and manually as suggested above. it still gives me the same error:
I do activate my environments before testing.

CREATING-SOME LABELS FOR THE FRAMES Traceback (most recent call last): File "testscript.py", line 108, in <module> dataFrame.to_hdf( File "C:\Users\phar0732\.conda\envs\DEEPLABCUT2\lib\site-packages\pandas\core\generic.py", line 2703, in to_hdf pytables.to_hdf( File "C:\Users\phar0732\.conda\envs\DEEPLABCUT2\lib\site-packages\pandas\io\pytables.py", line 311, in to_hdf with HDFStore( File "C:\Users\phar0732\.conda\envs\DEEPLABCUT2\lib\site-packages\pandas\io\pytables.py", line 572, in __init__ tables = import_optional_dependency("tables") File "C:\Users\phar0732\.conda\envs\DEEPLABCUT2\lib\site-packages\pandas\compat\_optional.py", line 118, in import_optional_dependency raise ImportError(msg) from None ImportError: Missing optional dependency 'tables'. Use pip or conda to install tables.

I assume this will be dealt with using docker, but it is weird that that same thing occurs and it does not appear to be that common. Really wonder where this conflict between tables pytables and pandas arise from and how it is so random...

**Comment by suchyun1993** [comment]
Same issue, tried all the solutions mentioned in previous discussions. I even reset the whole computer and anaconda, still same issue. 

At first I used the same protocol that I always used, met this issue, and then tried everything, then gave up.
I don't know if changing to Ubuntu will solve this problem.

**Comment by juliencarponcy** [comment]
Hey @MMathisLab ,

It look like this compatibility issue between packages for some versions (that's why i assume it is) makes DLC unusable for a few of us. I manage to install and launch the GUI on serveral different windows computers. The test script failed always with that same mistake, and i thought i solved it... My bad. just spent two hours labelling frames for realizing after that the labels were not saved anywhere because of that pytables / tables bug/compatibility issue. 

Here is the list of the packages I have in this environment, I am very sorry I coud not get a better formatted output from the anaconda prompt:

packages in environment at C:\Users\phar0732\.conda\envs\DEEPLABCUT2:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Name                    Version                   Build  Channel                                                                                                                                                                                                                                                           absl-py                   1.0.0                    pypi_0    pypi
                                                                                                                                                                                                                                                            argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     argon2-cffi-bindings      21.2.0           py38h294d835_1    conda-forge                                                                                                                                                                                                                                                     astunparse                1.6.3                    pypi_0    pypi                                                                                                                                                                                                                                                            async_generator           1.10                       py_0    conda-forge                                                                                                                                                                                                                                                     attrs                     21.4.0             pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     backcall                  0.2.0              pyh9f0ad1d_0    conda-forge                                                                                                                                                                                                                                                     backports                 1.0                        py_2    conda-forge                                                                                                                                                                                                                                                     backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                 bleach                    4.1.0              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     ca-certificates           2021.10.8            h5b45459_0    conda-forge                                                                                                                                                                                                                                                     cachetools                4.2.4                    pypi_0    pypi                                                                                                                                                                                                                                                            certifi                   2021.10.8                pypi_0    pypi                                                                                                                                                                                                                                                            cffi                      1.15.0           py38hd8c33c5_0    conda-forge                                                                                                                                                                                                                                                     charset-normalizer        2.0.9                    pypi_0    pypi                                                                                                                                                                                                                                                            colorama                  0.4.4              pyh9f0ad1d_0    conda-forge                                                                                                                                                                                                                                                     cycler                    0.11.0                   pypi_0    pypi                                                                                                                                                                                                                                                            debugpy                   1.5.1            py38h885f38d_0    conda-forge                                                                                                                                                                                                                                                     decorator                 4.4.2                    pypi_0    pypi                                                                                                                                                                                                                                                            deeplabcut                2.2.0.3                  pypi_0    pypi                                                                                                                                                                                                                                                            defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     entrypoints               0.3             pyhd8ed1ab_1003    conda-forge                                                                                                                                                                                                                                                     ffmpeg                    4.3.1                ha925a31_0    conda-forge                                                                                                                                                                                                                                                     filterpy                  1.4.5                    pypi_0    pypi                                                                                                                                                                                                                                                            flatbuffers               2.0                      pypi_0    pypi                                                                                                                                                                                                                                                            flit-core                 3.6.0              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     fonttools                 4.28.5                   pypi_0    pypi                                                                                                                                                                                                                                                            gast                      0.4.0                    pypi_0    pypi                                                                                                                                                                                                                                                            google-auth               2.3.3                    pypi_0    pypi                                                                                                                                                                                                                                                            google-auth-oauthlib      0.4.6                    pypi_0    pypi                                                                                                                                                                                                                                                            google-pasta              0.2.0                    pypi_0    pypi                                                                                                                                                                                                                                                            grpcio                    1.43.0                   pypi_0    pypi                                                                                                                                                                                                                                                            h5py                      3.6.0                    pypi_0    pypi                                                                                                                                                                                                                                                            icu                       68.2                 h0e60522_0    conda-forge                                                                                                                                                                                                                                                     idna                      3.3                      pypi_0    pypi                                                                                                                                                                                                                                                            imageio                   2.13.5                   pypi_0    pypi                                                                                                                                                                                                                                                            imageio-ffmpeg            0.4.5                    pypi_0    pypi                                                                                                                                                                                                                                                            imgaug                    0.4.0                    pypi_0    pypi                                                                                                                                                                                                                                                            importlib-metadata        4.10.0           py38haa244fe_0    conda-forge                                                                                                                                                                                                                                                     importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     ipykernel                 6.5.1            py38h595d716_0    conda-forge                                                                                                                                                                                                                                                     ipython                   7.30.1           py38haa244fe_0    conda-forge                                                                                                                                                                                                                                                     ipython_genutils          0.2.0                      py_1    conda-forge                                                                                                                                                                                                                                                     ipywidgets                7.6.5              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     jedi                      0.18.1           py38haa244fe_0    conda-forge                                                                                                                                                                                                                                                     jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     joblib                    1.1.0                    pypi_0    pypi                                                                                                                                                                                                                                                            jpeg                      9d                   h8ffe710_0    conda-forge                                                                                                                                                                                                                                                     jsonschema                4.3.2              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     jupyter                   1.0.0            py38haa244fe_7    conda-forge                                                                                                                                                                                                                                                     jupyter_client            7.1.0              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     jupyter_console           6.4.0              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     jupyter_core              4.9.1            py38haa244fe_1    conda-forge                                                                                                                                                                                                                                                     jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge                                                                                                                                                                                                                                                     jupyterlab_widgets        1.0.2              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     keras                     2.7.0                    pypi_0    pypi                                                                                                                                                                                                                                                            keras-preprocessing       1.1.2                    pypi_0    pypi                                                                                                                                                                                                                                                            kiwisolver                1.3.2                    pypi_0    pypi                                                                                                                                                                                                                                                            libclang                  12.0.0                   pypi_0    pypi                                                                                                                                                                                                                                                            libpng                    1.6.37               h1d00b33_2    conda-forge                                                                                                                                                                                                                                                     libsodium                 1.0.18               h8d14728_1    conda-forge                                                                                                                                                                                                                                                     libzlib                   1.2.11            h8ffe710_1013    conda-forge                                                                                                                                                                                                                                                     llvmlite                  0.37.0                   pypi_0    pypi                                                                                                                                                                                                                                                            markdown                  3.3.6                    pypi_0    pypi                                                                                                                                                                                                                                                            markupsafe                2.0.1            py38h294d835_1    conda-forge                                                                                                                                                                                                                                                     matplotlib                3.5.1                    pypi_0    pypi                                                                                                                                                                                                                                                            matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     mistune                   0.8.4           py38h294d835_1005    conda-forge                                                                                                                                                                                                                                                   moviepy                   1.0.3                    pypi_0    pypi                                                                                                                                                                                                                                                            msgpack                   1.0.3                    pypi_0    pypi                                                                                                                                                                                                                                                            msgpack-numpy             0.4.7.1                  pypi_0    pypi                                                                                                                                                                                                                                                            nb_conda                  2.2.1            py38haa244fe_4    conda-forge                                                                                                                                                                                                                                                     nb_conda_kernels          2.3.1            py38haa244fe_1    conda-forge                                                                                                                                                                                                                                                     nbclient                  0.5.9              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     nbconvert                 6.3.0            py38haa244fe_1    conda-forge                                                                                                                                                                                                                                                     nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     networkx                  2.6.3                    pypi_0    pypi                                                                                                                                                                                                                                                            notebook                  6.4.6              pyha770c72_0    conda-forge                                                                                                                                                                                                                                                     numba                     0.54.1                   pypi_0    pypi                                                                                                                                                                                                                                                            numexpr                   2.8.1                    pypi_0    pypi                                                                                                                                                                                                                                                            numpy                     1.20.3                   pypi_0    pypi                                                                                                                                                                                                                                                            oauthlib                  3.1.1                    pypi_0    pypi                                                                                                                                                                                                                                                            opencv-python             4.5.5.62                 pypi_0    pypi                                                                                                                                                                                                                                                            opencv-python-headless    4.5.5.62                 pypi_0    pypi                                                                                                                                                                                                                                                            openssl                   1.1.1l               h8ffe710_0    conda-forge                                                                                                                                                                                                                                                     opt-einsum                3.3.0                    pypi_0    pypi                                                                                                                                                                                                                                                            packaging                 21.3               pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     pandas                    1.3.5                    pypi_0    pypi                                                                                                                                                                                                                                                            pandoc                    2.16.2               h8ffe710_0    conda-forge                                                                                                                                                                                                                                                     pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     parso                     0.8.3              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     patsy                     0.5.2                    pypi_0    pypi                                                                                                                                                                                                                                                            pickleshare               0.7.5                   py_1003    conda-forge                                                                                                                                                                                                                                                     pillow                    8.4.0                    pypi_0    pypi                                                                                                                                                                                                                                                            pip                       21.3.1             pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     proglog                   0.1.9                    pypi_0    pypi                                                                                                                                                                                                                                                            prometheus_client         0.12.0             pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     prompt-toolkit            3.0.24             pyha770c72_0    conda-forge                                                                                                                                                                                                                                                     prompt_toolkit            3.0.24               hd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     protobuf                  3.19.1                   pypi_0    pypi                                                                                                                                                                                                                                                            psutil                    5.9.0                    pypi_0    pypi                                                                                                                                                                                                                                                            pyasn1                    0.4.8                    pypi_0    pypi                                                                                                                                                                                                                                                            pyasn1-modules            0.2.8                    pypi_0    pypi                                                                                                                                                                                                                                                            pycparser                 2.21               pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     pygments                  2.10.0             pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     pyqt                      5.12.3           py38haa244fe_8    conda-forge                                                                                                                                                                                                                                                     pyqt-impl                 5.12.3           py38h885f38d_8    conda-forge                                                                                                                                                                                                                                                     pyqt5-sip                 4.19.18          py38h885f38d_8    conda-forge                                                                                                                                                                                                                                                     pyqtchart                 5.12             py38h885f38d_8    conda-forge                                                                                                                                                                                                                                                     pyqtwebengine             5.12.1           py38h885f38d_8    conda-forge                                                                                                                                                                                                                                                     pyrsistent                0.18.0           py38h294d835_0    conda-forge                                                                                                                                                                                                                                                     python                    3.8.12          h7840368_2_cpython    conda-forge                                                                                                                                                                                                                                                  python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     python_abi                3.8                      2_cp38    conda-forge                                                                                                                                                                                                                                                     pytz                      2021.3                   pypi_0    pypi                                                                                                                                                                                                                                                            pywavelets                1.2.0                    pypi_0    pypi                                                                                                                                                                                                                                                            pywin32                   303              py38h294d835_0    conda-forge                                                                                                                                                                                                                                                     pywinpty                  1.1.6            py38hd3f51b4_0    conda-forge                                                                                                                                                                                                                                                     pyyaml                    6.0                      pypi_0    pypi                                                                                                                                                                                                                                                            pyzmq                     22.3.0           py38h09162b1_1    conda-forge                                                                                                                                                                                                                                                     qt                        5.12.9               h5909a2a_4    conda-forge                                                                                                                                                                                                                                                     qtconsole                 5.2.2              pyhd8ed1ab_1    conda-forge                                                                                                                                                                                                                                                     qtconsole-base            5.2.2              pyhd8ed1ab_1    conda-forge                                                                                                                                                                                                                                                     qtpy                      2.0.0              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     requests                  2.26.0                   pypi_0    pypi                                                                                                                                                                                                                                                            requests-oauthlib         1.3.0                    pypi_0    pypi                                                                                                                                                                                                                                                            rsa                       4.8                      pypi_0    pypi                                                                                                                                                                                                                                                            ruamel-yaml               0.17.19                  pypi_0    pypi                                                                                                                                                                                                                                                            ruamel-yaml-clib          0.2.6                    pypi_0    pypi                                                                                                                                                                                                                                                            scikit-image              0.18.1                   pypi_0    pypi                                                                                                                                                                                                                                                            scikit-learn              1.0.2                    pypi_0    pypi                                                                                                                                                                                                                                                            scipy                     1.7.3                    pypi_0    pypi                                                                                                                                                                                                                                                            send2trash                1.8.0              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     setuptools                60.2.0           py38haa244fe_0    conda-forge                                                                                                                                                                                                                                                     shapely                   1.8.0                    pypi_0    pypi                                                                                                                                                                                                                                                            six                       1.16.0             pyh6c4a22f_0    conda-forge                                                                                                                                                                                                                                                     sqlite                    3.37.0               h8ffe710_0    conda-forge                                                                                                                                                                                                                                                     statsmodels               0.13.1                   pypi_0    pypi                                                                                                                                                                                                                                                            tables                    3.7.0                    pypi_0    pypi                                                                                                                                                                                                                                                            tabulate                  0.8.9                    pypi_0    pypi                                                                                                                                                                                                                                                            tensorboard               2.7.0                    pypi_0    pypi                                                                                                                                                                                                                                                            tensorboard-data-server   0.6.1                    pypi_0    pypi                                                                                                                                                                                                                                                            tensorboard-plugin-wit    1.8.0                    pypi_0    pypi                                                                                                                                                                                                                                                            tensorflow                2.7.0                    pypi_0    pypi                                                                                                                                                                                                                                                            tensorflow-estimator      2.7.0                    pypi_0    pypi                                                                                                                                                                                                                                                            tensorflow-io-gcs-filesystem 0.23.1                   pypi_0    pypi                                                                                                                                                                                                                                                         tensorpack                0.11                     pypi_0    pypi                                                                                                                                                                                                                                                            termcolor                 1.1.0                    pypi_0    pypi                                                                                                                                                                                                                                                            terminado                 0.12.1           py38haa244fe_1    conda-forge                                                                                                                                                                                                                                                     testpath                  0.5.0              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     tf-slim                   1.1.0                    pypi_0    pypi                                                                                                                                                                                                                                                            threadpoolctl             3.0.0                    pypi_0    pypi                                                                                                                                                                                                                                                            tifffile                  2021.11.2                pypi_0    pypi                                                                                                                                                                                                                                                            tornado                   6.1              py38h294d835_2    conda-forge                                                                                                                                                                                                                                                     tqdm                      4.62.3                   pypi_0    pypi                                                                                                                                                                                                                                                            traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     typing-extensions         4.0.1                    pypi_0    pypi                                                                                                                                                                                                                                                            ucrt                      10.0.20348.0         h57928b3_0    conda-forge                                                                                                                                                                                                                                                     urllib3                   1.26.7                   pypi_0    pypi                                                                                                                                                                                                                                                            vc                        14.2                 hb210afc_5    conda-forge                                                                                                                                                                                                                                                     vs2015_runtime            14.29.30037          h902a5da_5    conda-forge                                                                                                                                                                                                                                                     wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge                                                                                                                                                                                                                                                     webencodings              0.5.1                      py_1    conda-forge                                                                                                                                                                                                                                                     werkzeug                  2.0.2                    pypi_0    pypi                                                                                                                                                                                                                                                            wheel                     0.37.1             pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     widgetsnbextension        3.5.2            py38haa244fe_1    conda-forge                                                                                                                                                                                                                                                     winpty                    0.4.3                         4    conda-forge                                                                                                                                                                                                                                                     wrapt                     1.13.3                   pypi_0    pypi                                                                                                                                                                                                                                                            wxpython                  4.0.7.post2              pypi_0    pypi                                                                                                                                                                                                                                                            zeromq                    4.3.4                h0e60522_1    conda-forge                                                                                                                                                                                                                                                     zipp                      3.6.0              pyhd8ed1ab_0    conda-forge                                                                                                                                                                                                                                                     zlib                      1.2.11            h8ffe710_1013    conda-forge

**Comment by juliencarponcy** [comment]
Hi again, after much troubles trying a failing the same way on another server on ubuntu, a VM on Ubuntu... I think I finally got it.
I think the conflict arise from user with Python 3.8, as i solved it on my windows computer restarting an environment using
`conda create -n dlc -v python=3.7`
then doing
`pip install 'deeplabcut[gui]'`
I hope it could help @suchyun1993 and @TinyAnts

**Comment by suchyun1993** [comment]
> Hi again, after much troubles trying a failing the same way on another server on ubuntu, a VM on Ubuntu... I think I finally got it. I think the conflict arise from user with Python 3.8, as i solved it on my windows computer restarting an environment using `conda create -n dlc -v python=3.7` then doing `pip install 'deeplabcut[gui]'` I hope it could help @suchyun1993 and @TinyAnts

Hi @juliencarponcy thank you so much for your feedback. It's great that you finally worked out. However, unfortunately, I need to use multi-animal DLC and 30series NVIDIA GPU, so I had to use python 3.8. 
Today I tried again on a fresh Windows PC. I first tested using traditional method (latest yaml file), still same issue. Just a moment ago finally worked out on my PC by cloning a functional DLC environment (version 2.2.0.3) from another PC that I created before. And BOOM, it works, same computer, same anaconda, everything is the same. Never thought it could be so easy to fix...

I'm not good at coding but it seems the latest DLC (downloading packages from internet) has some issue with Windows PC. I did try on Ubuntu and it kind of worked without reporting 'tables' error. 

In case anyone will meet this issue without other solution in a short time, I uploaded my DLC environment file to the Google drive [https://drive.google.com/file/d/1-0h_koFcU3ZcBDUIHeUCOCFreXuU6AfF/view?usp=sharing](url) and you can using code `conda create -n [name] --clone [Path]` to clone.

**Comment by Liordemarcas** [comment]
Faced the same error, when running testscript on a new installation (switch to a new GPU - GeForce3060, CUDA 11.2).
Simple `pip install tables==3.6.1` **solved the problem**.  Seem like "tables" was updated last month in pip (https://pypi.org/project/tables/#history), maybe it has a connection.


Installed with the conda file in http://www.mackenziemathislab.org/deeplabcut (seem like the same file as in https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/installation.md#step-2-easy-install-please-use-our-supplied-anaconda-environments, but unable to download it from the link there for some reason). Then ran `conda install -c conda-forge cudnn` for the cudnn, & `pip install --upgrade deeplabcut` to make sure I use the latest version (no changes).

#My environment in the attached file
[my_DLC.txt](https://github.com/DeepLabCut/DeepLabCut/files/7888274/my_DLC.txt)

**Comment by MMathisLab** [comment]
@jeylau should we pin to 3.6.1 for the time meaning; I agree that it seems a new Tables issue
