### ISSUE TITLE
Auxiliary function to get pose_cfg.yaml

### ISSUE THREAD

**Issue by A-Telfer** [DeepLabCut/DeepLabCut#1579]
**Is your feature request related to a problem? Please describe.**
I have to frequently modify the pose_cfg.yaml and it's always struck me as odd that there isn't an auxiliary function for it.

Several places in the deeplabcut code access the pose_cfg.yaml, each time they reconstruct it. Why not modularize it and make it more available to users?

e.g. in [auxiliaryfunctions.py#L575-L580](https://github.com/DeepLabCut/DeepLabCut/blob/444da3da70b1f3bfaae39b0849e0aafcff1a9b7a/deeplabcut/utils/auxiliaryfunctions.py#L575-L580)
```python
os.path.join(
    cfg["project_path"],
    str(GetModelFolder(trainFraction, shuffle, cfg, modelprefix=modelprefix)),
    "train",
    "pose_cfg.yaml",
)
```

**Describe the solution you'd like**
A new function in `auxiliaryfunctions.py` to get the pose_cfg.yaml file (ideally with an intuitive name like get_pose_config)

**Describe alternatives you've considered**
I have a snippet that does it, but I always lose it and have to go searching again. The frequency where its useful to change the pose_cfg makes me think others would benefit as well (eg. finding optimal augmentation parameters, changing learning rates, etc) 

**Additional context**
Some places I've found mention of the `pose_cfg.yaml` file (some appear tidy, others less so):
- https://github.com/DeepLabCut/DeepLabCut/blob/444da3da70b1f3bfaae39b0849e0aafcff1a9b7a/deeplabcut/utils/auxiliaryfunctions.py#L575-L580
- https://github.com/DeepLabCut/DeepLabCut/blob/34eb7f6042322d1af98afb487dbfd13b617d276f/examples/testscript_mobilenets.py#L27-L39
-  **Just found this, good solution? However un-intuitive name/location.** https://github.com/DeepLabCut/DeepLabCut/blob/6c3df66e901874371d2339bbccd968a07230fc77/examples/testscript_deterministicwithResNet152.py#L114
- https://github.com/DeepLabCut/DeepLabCut/blob/d7db8d36fdb95ad69f8d91f0a7877034cc81699b/examples/testscript_multianimal.py#L101
- https://github.com/DeepLabCut/DeepLabCut/blob/34eb7f6042322d1af98afb487dbfd13b617d276f/deeplabcut/pose_estimation_tensorflow/training.py#L38
- https://github.com/DeepLabCut/DeepLabCut/blob/d7db8d36fdb95ad69f8d91f0a7877034cc81699b/examples/testscript_multianimal.py#L101

**Comment by A-Telfer** [comment]
Perhaps something like this in `auxiliaryfunctions.py`... 
```python 

def get_pose_config(config, shuffle=1, trainingsetindex=0, modelprefix="", split='train'):
    """Returns the path to the pose_cfg.yaml file
    
    Parameters
    ----------
    config : string
        Full path of the config.yaml file as a string.
    shuffle: int, optional
        Integer value specifying the shuffle index to select for training.
    trainingsetindex: int, optional
        Integer specifying which TrainingsetFraction to use. By default the first (note that TrainingFraction is a list in config.yaml).
    modelprefix: str, optional
        Instead of saving models in the project's dlc-models folder, provide your own path.
    split: {'train', 'test'} 
        Get the pose_cfg for the train or test split. 

    Returns
    -------
    string
        The path to the pose_cfg.yaml file.
    """
    cfg = auxiliaryfunctions.read_config(config)
    model_folder = auxiliaryfunctions.GetModelFolder(
        cfg["TrainingFraction"][trainingsetindex], 
        shuffle, 
        cfg, 
        modelprefix or cfg["project_path"]
    )
    return os.path.join(model_folder, split, "pose_cfg.yaml")
```

**Comment by jeylau** [comment]
Hey @A-Telfer, `deeplabcut.return_train_network_path` is definitely the right function. I agree with you though that it could be reused more consistently across the codebase, and its name made more explicit. @MMathisLab, any thoughts? ☺️

**Comment by A-Telfer** [comment]
That function is a hidden gem, I wish I knew about it sooner. It would be great if it were easier to find

**Comment by MMathisLab** [comment]
I guess the easiest why right now is https://deeplabcut.github.io/DeepLabCut/docs/HelperFunctions.html but I agree a proper API docs would be good to finally deploy ...
