### ISSUE TITLE
Import issue with headless and GUI usage on the same machine

### ISSUE THREAD

**Issue by illogicalspock** [DeepLabCut/DeepLabCut#1583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When trying to import deeplabcut in an ipython session while connected over ssh, if wxPython is installed in the environment (since the machine is also used with a GUI), an error related to matplotlib's backend switching comes up since it is trying to load wxAgg but cannot since it is headless. Docs seem to say to set environment variable DLClight=True to force headless, but \_\_init\_\_.py only checks if wxPython is installed through a ModuleNotFoundError, so if wxPython is installed it will still try to use wxAgg regardless of whether DLClight is set, causing an error. 

### Operating System

Ubuntu 20.04

### DeepLabCut version

2.2.0.2

### DeepLabCut mode

single animal

### Device type

CPU: AMD Ryzen Threadripper PRO 3975WX
GPU: nVidia Quadro RTX 5000

### Steps To Reproduce

1. Have deeplabcut and wxPython installed on Ubuntu
2. SSH into machine
3. Set DLClight using 'export DLClight=True'
4. Try 'import deeplabcut' in ipython

### Relevant log output

```shell
273         if (current_framework and required_framework
    274                 and current_framework != required_framework):
--> 275             raise ImportError(
    276                 "Cannot load backend {!r} which requires the {!r} interactive "
    277                 "framework, as {!r} is currently running".format(

ImportError: Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'headless' is currently running
```

### Anything else?

I was able to import after adding a check in \_\_init\_\_.py to see whether DLClight had been set before the try block for importing the graphical stuff

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
HI @arawayrj the behavior changed recently, such that you need to `pip install deeplabcut` for headless, and `pip install deeplabcut[gui]` for GUI, so I recommend just simply using two environments. 

Also, the Docker is likely useful for you: `pip install deeplabcut-docker' 

https://deeplabcut.github.io/DeepLabCut/docs/docker.html?highlight=docker
