### ISSUE TITLE
maDLC convert_detections2tracklets() kills kernel

### ISSUE THREAD

**Issue by connorjohnson1** [DeepLabCut/DeepLabCut#1587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

when going through the multianimal DLC pipeline i hit an issue with the convert_detections2tracklets function. I want to extract my H5 but my kernel dies and i can not get an output

### Operating System

Windows 10

### DeepLabCut version

2.2rc3

### DeepLabCut mode

multi animal

### Device type

gpu

### Relevant log output

```shell
Using snapshot-50000 for model D:\Users\multi_dlc\Desktop\project1\multi2-CJ-2021-11-18\dlc-models\iteration-0\multi2Nov18-trainset95shuffle1
Processing...  D:\Users\multi_dlc\Desktop\vid\behavCam1.avi
D:\Users\multi_dlc\Desktop\vid  already exists!
Analyzing D:\Users\multi_dlc\Desktop\vid\behavCam1DLC_dlcrnetms5_multi2Nov18shuffle1_50000.h5
1000it [00:01, 903.12it/s]
0it [00:00, ?it/s]
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
HI @connorjohnson1 could you please use the latest code and a fresh conda env to try again (I suspect issue will be resolved; the rc's are really just short term release candidates, and not fully pipeline ready, plus 2.2.0.3 is a much improved version too ;)

**Comment by connorjohnson1** [comment]
i did this and now I am getting a new error:

```
deeplabcut.convert_detections2tracklets(
    r'D:\Users\multi_dlc\Desktop\project1\multi2-CJ-2021-11-18\config.yaml',
    r'D:\Users\multi_dlc\Desktop\vid\behavCam1.avi',
    track_method="ellipse"
)
```

```
`Using snapshot-50000 for model D:\Users\multi_dlc\Desktop\project1\multi2-CJ-2021-11-18\dlc-models\iteration-0\multi2Nov18-trainset95shuffle1
Processing...  D:\Users\multi_dlc\Desktop\vid\behavCam1.avi
Analyzing D:\Users\multi_dlc\Desktop\vid\behavCam1DLC_dlcrnetms5_multi2Nov18shuffle1_50000.h5
0it [00:00, ?it/s]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
C:\Users\MULTI_~1\AppData\Local\Temp/ipykernel_61580/1868230418.py in <module>
----> 1 deeplabcut.convert_detections2tracklets(
      2     r'D:\Users\multi_dlc\Desktop\project1\multi2-CJ-2021-11-18\config.yaml',
      3     r'D:\Users\multi_dlc\Desktop\vid\behavCam1.avi',
      4     track_method="ellipse"
      5 )

D:\Users\multi_dlc\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py in convert_detections2tracklets(config, videos, videotype, shuffle, trainingsetindex, overwrite, destfolder, ignore_bodyparts, inferencecfg, modelprefix, track_method, greedy, calibrate, window_size, identity_only)
   1461                     )
   1462                     ass.calibrate(train_data_file)
-> 1463                 ass.assemble()
   1464                 ass.to_pickle(dataname.split(".h5")[0] + "_assemblies.pickle")
   1465 

D:\Users\multi_dlc\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\lib\inferenceutils.py in assemble(self, chunk_size, n_processes)
    751         if chunk_size == 0 or multiprocessing.get_start_method() == "spawn":
    752             for i, data_dict in enumerate(tqdm(self)):
--> 753                 assemblies, unique = self._assemble(data_dict, i)
    754                 if assemblies:
    755                     self.assemblies[i] = assemblies

D:\Users\multi_dlc\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\lib\inferenceutils.py in _assemble(self, data_dict, ind_frame)
    665                     trees.append(tree)
    666 
--> 667             links = self.extract_best_links(bag, data_dict["costs"], trees)
    668             if self._kde:
    669                 for link in links[::-1]:

D:\Users\multi_dlc\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\lib\inferenceutils.py in extract_best_links(self, joints_dict, costs, trees)
    352         links = []
    353         for ind in self.paf_inds:
--> 354             s, t = self.graph[ind]
    355             dets_s = joints_dict.get(s, None)
    356             dets_t = joints_dict.get(t, None)

IndexError: list index out of range` 
```

**Comment by MMathisLab** [comment]
@connorjohnson1 can you confirm this works?

deeplabcut.create_video_with_all_detections(config_path, ['/fullpath/project/videos/testVideo.mp4'], videotype='.mp4')

https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#decision-break-point

I imagine if you did not re-train with 2.2.0.3 yet, you don't have a good assembly, as this is a big change from rc3; I would recommend creating a new training set (simply increase shuffle number) and retrain as well.

**Comment by connorjohnson1** [comment]
I can confirm deeplabcut.create_video_with_all_detections(config_path, ['/fullpath/project/videos/testVideo.mp4'], videotype='.mp4') is functional and provides an output video, which looks quite good.

I reinstalled and created a new project using 2.2.0.3 and I am back to the original error, everything works up to convert_detections2tracklets() and then the kernel dies. 

```
Using snapshot-200000 for model D:\Users\multi_dlc\Desktop\project1\multi2-CJ-2021-11-18\dlc-models\iteration-0\multi2Nov18-trainset95shuffle1
Processing...  D:\Users\multi_dlc\Desktop\vid\behavCam1.avi
Analyzing D:\Users\multi_dlc\Desktop\vid\behavCam1DLC_dlcrnetms5_multi2Nov18shuffle1_200000.h5
1000it [00:01, 928.36it/s]
0it [00:00, ?it/s]
```

**Comment by jeylau** [comment]
Hi @connorjohnson1. When you say that the kernel dies, is it because you're using jupyter notebooks? Does the same happen when running it from the command line? I wonder if it is related to parallel processing on Windows (although it's normally automatically turned off). Could you confirm that `multiprocessing.get_start_method() == "spawn"` evaluates to True on your machine?

**Comment by connorjohnson1** [comment]
I can confirm ` multiprocessing.get_start_method() == "spawn"` is true. I apologize but I currently am only able to run these functions in jupyter notebook, could you provide some guidance on how to run in terminal?

Also if its any help, essentially I am just trying to get a csv or any filetype really that I can extract animal coordinates from. Based on the videos output by the create_video_with_all_detections() function, I believe the tracking is all there but I just need the coords.

**Comment by jeylau** [comment]
@connorjohnson1, I'm sorry for only getting back to you now. You could create a python file (say "script.py"), with the following code:
```python
import deeplabcut

deeplabcut.convert_detections2tracklets(
    r'D:\Users\multi_dlc\Desktop\project1\multi2-CJ-2021-11-18\config.yaml',
    r'D:\Users\multi_dlc\Desktop\vid\behavCam1.avi',
    track_method="ellipse"
)
```
and run `python script.py` from your terminal. If it works this way, we'll know it was something related to the jupyter environment 😃

**Comment by MMathisLab** [comment]
also see here on how to use the terminal for DLC: https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#get-started-in-the-terminal-or-project-gui

You can also use the GUI, just load your config.yaml and the rest should work!
