### ISSUE TITLE
Issues running create_labeled_video

### ISSUE THREAD

**Issue by luigimvargas** [DeepLabCut/DeepLabCut#159]
OS & Version: Windows, DLC 2.0

Having an issue with creating labeled video after successfully evaluating network and running 'analyze_videos'

**Here's the command line for successful run of analyze videos:**

>>> deeplabcut.analyze_videos(config_path,'d3stim-Luigim-2018-12-20/videos/137Mouse-5Hz.mp4',save_as_csv=True,videotype='.mp4')

Config:
{'all_joints': [[0], [1], [2]],
 'all_joints_names': ['Nose', 'rHand', 'lHand'],
 'batch_size': 4,
 'bottomheight': 400,
 'crop': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_d3stimDec20\\d3stim_Luigim95shuffle1.mat',
 'dataset_type': 'default',
 'display_iters': 1000,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'C:\\Users\\Luigim\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1000,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_d3stimDec20\\Documentation_data-d3stim_95shuffle1.pickle',
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 3,
 'optimizer': 'sgd',
 'pos_dist_thresh': 17,
 'project_path': 'C:\\Users\\Luigim\\Desktop\\DeepLabCut-master\\Projects\\d3stim-Luigim-2018-12-20',
 'regularize': False,
 'rightwidth': 400,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'C:\\Users\\Luigim\\Desktop\\DeepLabCut-master\\Projects\\d3stim-Luigim-2018-12-20\\dlc-models\\iteration-0\\d3stimDec20-trainset95shuffle1\\test\\snapshot',
 'stride': 8.0,
 'topheight': 400,
 'use_gt_segm': False,
 'video': False,
 'video_batch': False,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Using snapshot-1030000 for model C:\Users\Luigim\Desktop\DeepLabCut-master\Projects\d3stim-Luigim-2018-12-20\dlc-models\iteration-0\d3stimDec20-trainset95shuffle1
INFO:tensorflow:Restoring parameters from C:\Users\Luigim\Desktop\DeepLabCut-master\Projects\d3stim-Luigim-2018-12-20\dlc-models\iteration-0\d3stimDec20-trainset95shuffle1\train\snapshot-1030000
Restoring parameters from C:\Users\Luigim\Desktop\DeepLabCut-master\Projects\d3stim-Luigim-2018-12-20\dlc-models\iteration-0\d3stimDec20-trainset95shuffle1\train\snapshot-1030000
d3stim-Luigim-2018-12-20/videos/137Mouse-5Hz.mp4
Starting %  d3stim-Luigim-2018-12-20/videos/137Mouse-5Hz.mp4
Loading  d3stim-Luigim-2018-12-20/videos/137Mouse-5Hz.mp4
Duration of video [s]:  11.03 , recorded with  30.0 fps!
Overall # of frames:  331 without cropped frame dimensions:  1920 1080
Starting to extract posture
Cropping based on the x1 = 0 x2 = 1920 y1 = 400 y2 = 1080. You can adjust the cropping coordinates in the config.yaml file.
340it [00:49,  7.08it/s]                                                                                               Detected frames:  331
Saving results in d3stim-Luigim-2018-12-20\videos...
Saving csv poses!
The videos are analyzed. Now your research can truly start!
 You can create labeled videos with 'create_labeled_video'.
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract any outlier frames!

**Now, on my first attempt to create the video, I get the following error:**
>>>deeplabcut.create_labeled_video(config_path,['d3stim-Luigim-2018-12-20/videos/137Mouse-5Hz.mp4'])

Starting %  d3stim-Luigim-2018-12-20\videos ['d3stim-Luigim-2018-12-20/videos/137Mouse-5Hz.mp4']
Loading  d3stim-Luigim-2018-12-20/videos/137Mouse-5Hz.mp4 and data.
The video was not analyzed with this scorer: DeepCut_resnet50_d3stimDec20shuffle1_1030000
Other scorers were found, however: ['137Mouse-5HzDeepCut_resnet50_d3stimDec20shuffle1_1030000.h5']
Creating labeled video for: DeepCut_resnet50_d3stimDec20shuffle1_1030000  instead.
True 0 1920 400 1080
warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:901)
warning: d3stim-Luigim-2018-12-20/videos/137Mouse-5Hz.mp4 (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:902)
0
Fast video creation has currently not been implemented for cropped videos. Please use 'save_frames=True' to get the video.

**I removed the cropping option to see if it would help, but it did not. The above command seems to change my working directory to /videos, so following attempts just list the video files, and give me a different error:**

>>>deeplabcut.create_labeled_video(config_path,['137Mouse-5Hz.mp4'])
Starting %  . ['137Mouse-5Hz.mp4']
Loading  137Mouse-5Hz.mp4 and data.
The video was not analyzed with this scorer: DeepCut_resnet50_d3stimDec20shuffle1_1030000
No other scorers were found, please use the function 'analyze_videos' first.

I don't understand what cause this error; the outputs of analyze_videos seems to work as expected.

I would greatly appreciate some help troubleshooting this error.

**Comment by MMathisLab** [comment]
The error tells you what to do, namely add the variable save_frames=True ... deeplabcut.create_labeled_video(config_path,['d3stim-Luigim-2018-12-20/videos/137Mouse-5Hz.mp4'], save_frames=True,**videotype='.mp4'**) - that should work then. 

(also don't forget the videotype specifier, this is why no videos are found...)

**Comment by luigimvargas** [comment]
I am still getting an error when trying to run the updated command:

>>> deeplabcut.create_labeled_video(config_path,['d3stim-Luigim-2018-12-20/videos/137Mouse-5Hz.mp4'], save_frames=True,videotype='.mp4')
Starting %  d3stim-Luigim-2018-12-20\videos ['d3stim-Luigim-2018-12-20/videos/137Mouse-5Hz.mp4']
Loading  d3stim-Luigim-2018-12-20/videos/137Mouse-5Hz.mp4 and data.
The video was not analyzed with this scorer: DeepCut_resnet50_d3stimDec20shuffle1_1030000
Other scorers were found, however: ['137Mouse-5HzDeepCut_resnet50_d3stimDec20shuffle1_1030000.h5']
Creating labeled video for: DeepCut_resnet50_d3stimDec20shuffle1_1030000  instead.
True 0 1920 400 1080
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Luigim\AppData\Local\Programs\Python\Python36\lib\site-packages\deeplabcut\utils\make_labeled_video.py", line 260, in create_labeled_video
    auxiliaryfunctions.attempttomakefolder(tmpfolder)
  File "C:\Users\Luigim\AppData\Local\Programs\Python\Python36\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 41, in attempttomakefolder
    os.mkdir(foldername)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'd3stim-Luigim-2018-12-20\\videos\\temp-137Mouse

It looks like the error is in making a folder for the images, and I get this even when running the command in an administrator command prompt. I get a similar error when running this command on data from an uncropped video.

Also, I don't quite understand the error regarding the 'scorer'. Why do I keep getting that error message?

**Comment by MMathisLab** [comment]
Did the suggestion fix your error?
