### ISSUE TITLE
plotting3D.py does not support Multimode

### ISSUE THREAD

**Issue by x35yao** [DeepLabCut/DeepLabCut#1593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When using multimode, the index level for variable df_cam1 and df_cam2 are different from standard mode, which gives keyError when running plotting3D.py because one needs to specify the individual before bodyparts.

### Operating System

Ubuntu 18.04

### DeepLabCut version

dlc version 2.2

### DeepLabCut mode

multi animal

### Device type

gpu 1080Ti

### Steps To Reproduce

1. Create, train, evaluate a 2D multi-mode project
2. Calibrate cameras for 3D
3. run create_labeled_video_3d()

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
please include the relevant output error; it actually is supported, but hard to debug without more details

**Comment by x35yao** [comment]
---------------------------------------------------------
Hi,
Thank you for replying. The following is the error I got. I believe the reason that I am getting this error is that `df_cam1_view[scorer_cam1][bp]["likelihood"].values[k]` needs to have the index for the individual before indexing the bodyparts, which means it should be `df_cam1_view[scorer_cam1][individual][bp]["likelihood"].values[k]`. FYI, 'head' is just one of the body parts I defined.

```python
-------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3360             try:
-> 3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:

~/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

~/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'head'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-2-87ef0d0cbb9f> in <module>
----> 1 deeplabcut.create_labeled_video_3d('/home/luke/Desktop/project/make_tea/dlc/make_tea_3d-Luke-2021-11-22-3d/config.yaml', ['/home/luke/Desktop/project/make_tea/camera-main/videos/'],videofolder = '/home/luke/Desktop/project/make_tea/camera-main/videos/',view = [50,50], videotype = '.mp4',start=50, end=250)

~/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_3d/plotting3D.py in create_labeled_video_3d(config, path, videofolder, start, end, trailpoints, videotype, view, xlim, ylim, zlim, draw_skeleton)
    220             # Start plotting for every frame
    221             for k in tqdm(frames):
--> 222                 output_folder, num_frames = plot2D(
    223                     cfg_3d,
    224                     k,

~/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_3d/plotting3D.py in plot2D(cfg_3d, k, bodyparts2plot, vid_cam1, vid_cam2, bodyparts2connect, df_cam1_view, df_cam2_view, xyz_pts, pcutoff, markerSize, alphaValue, color, path_h5_file, file_name, skeleton_color, view, draw_skeleton, trailpoints, xlim, ylim, zlim)
    385         axes1.imshow(frame_cam1)
    386         axes2.imshow(frame_cam2)
--> 387         if (df_cam1_view[scorer_cam1][bp]["likelihood"].values[k]) > pcutoff and (
    388             df_cam2_view[scorer_cam2][bp]["likelihood"].values[k]
    389         ) > pcutoff:

~/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/pandas/core/frame.py in __getitem__(self, key)
   3455         if is_single_key:
   3456             if self.columns.nlevels > 1:
-> 3457                 return self._getitem_multilevel(key)
   3458             indexer = self.columns.get_loc(key)
   3459             if is_integer(indexer):

~/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/pandas/core/frame.py in _getitem_multilevel(self, key)
   3506     def _getitem_multilevel(self, key):
   3507         # self.columns is a MultiIndex
-> 3508         loc = self.columns.get_loc(key)
   3509         if isinstance(loc, (slice, np.ndarray)):
   3510             new_columns = self.columns[loc]

~/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/pandas/core/indexes/multi.py in get_loc(self, key, method)
   2920 
   2921         if not isinstance(key, tuple):
-> 2922             loc = self._get_level_indexer(key, level=0)
   2923             return _maybe_to_slice(loc)
   2924 

~/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/pandas/core/indexes/multi.py in _get_level_indexer(self, key, level, indexer)
   3202         else:
   3203 
-> 3204             idx = self._get_loc_single_level_index(level_index, key)
   3205 
   3206             if level > 0 or self._lexsort_depth == 0:

~/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/pandas/core/indexes/multi.py in _get_loc_single_level_index(self, level_index, key)
   2853             return -1
   2854         else:
-> 2855             return level_index.get_loc(key)
   2856 
   2857     def get_loc(self, key, method=None):

~/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:
-> 3363                 raise KeyError(key) from err
   3364 
   3365         if is_scalar(key) and isna(key) and not self.hasnans:

KeyError: 'head'
```

**Comment by MMathisLab** [comment]
Hi @x35yao great, thanks for the report! We will look into it!

**Comment by jeylau** [comment]
@x35yao, I'm looking at it! Just a side question: how many animals did you define in your multi-animal project?

**Comment by x35yao** [comment]
Hi @jeylau, I defined 2 individuals and several unique objects. I walked around it by:1. List the unique objects in the 3D project config. 2. Include the unique objects into the bodyparts2plot variable. 3. When looping the bodyparts, drop a level for the variable df_cam1_view.

**Comment by jeylau** [comment]
Thanks for the feedback! I ran into trouble earlier though, when running `deeplabcut.triangulate()` with data with 2 animals; it worked fine in your case?

**Comment by x35yao** [comment]
Yes, I think you need to give the number of instances in each video.

**Comment by x35yao** [comment]
Actually, it `deeplabcut.triangulate()` only works if I indicate there are 1 animal in the scene and stop working if there are 2 animals. I think it is because the variable `dataFrame_cam1_undistort` is defined different with `dataFrame_cam1`.

**Comment by jeylau** [comment]
@x35yao, I just wanted to let you know that we've recently improved the 3D code in #1690. The issue you raised is already fixed, but we're missing one last item before merging the PR 😃

**Comment by x35yao** [comment]
Cool. Thank you.

**Comment by x35yao** [comment]
Hi Alexander,

Thank you for the feedback. I have a quick question to ask and I will really appreciate it if you can take 1 minute to help.

In your recent paper "Multi-animal pose estimation and tracking with DeepLabCut", in Figure 1a, you show a case where you have 2 different animals(mouse and pups) and each animal has a different number of body parts. I am wondering if you trained 2 separate networks(1 for each kind of animal) or just 1 network for all the animals. If you used only 1 network, how did you define the config file so that each animal could have a different number of body parts?

Thank you in advance.
Best regards,
Luke


Xueyang Yao
PhD candidate, Systems Design Engineering
University of Waterloo, Canada


________________________________

**Comment by jeylau** [comment]
Pups (with 5 body parts each) were defined as individuals with multianimalbodyparts, whereas the keypoints of the parent mouse were defined in "uniquebodyparts".

**Comment by x35yao** [comment]
Thank you so much for the quick reply. If I understand it right, it only works in the case where only one kind of animal(pups in this case) has multiple instances so that other kinds of animals are treated as unique objects. If I want to treat other kinds of animals(parent mouse in this case) as individuals as well, I will need to train another network.
