### ISSUE TITLE
Cannot grabframe when extracting frames.

### ISSUE THREAD

**Issue by shiyangw** [DeepLabCut/DeepLabCut#160]
When I use 'deeplabcut.extract_frames(config_path,'manual')' to extract frames, I can load the video, but if I click the 'Grab a Frame' button, it shows that 

In [3]: deeplabcut.extract_frames(config_path,'manual')
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/deeplabcut/generate_training_dataset/frame_extraction_toolbox.py in browseDir(self, event)
    169                 self.cropping = True
    170                 self.basefolder = 'data-' + self.Task + '/'
--> 171                 MainFrame.CheckCropping(self)
    172             else:
    173                 self.cropping = False

/usr/local/lib/python3.6/dist-packages/deeplabcut/generate_training_dataset/frame_extraction_toolbox.py in CheckCropping(self)
     99         filename = self.filename
    100         time = self.start
--> 101         self.x1 = int(self.cfg['video_sets'][videosource]['crop'].split(',')[0])
    102         self.x2 = int(self.cfg['video_sets'][videosource]['crop'].split(',')[1])
    103         self.y1 = int(self.cfg['video_sets'][videosource]['crop'].split(',')[2])

KeyError: '/home/shiyang/workdic/nameproject-shiyang-2018-12-30/videos/test1.avi'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/deeplabcut/generate_training_dataset/frame_extraction_toolbox.py in grabFrame(self, event)
    211             img_name = str(output_path) +'/img'+str(self.currFrame).zfill(int(np.ceil(np.log10(self.numberFrames)))) + '.png'
    212             if self.cropping:
--> 213                 crop_img = frame[self.y1:self.y2, self.x1:self.x2]
    214                 cv2.imwrite(img_name, cv2.cvtColor(crop_img, cv2.COLOR_RGB2BGR))
    215             else:

AttributeError: 'MainFrame' object has no attribute 'y1'

Frames are selected.
You can now label the frames using the function 'label_frames'.

and no frame is grabbed. I'm using ubuntu 16.04 and python3.6, my videos are xxx.avi, could anyone tell me what's the problem? 
Thanks in advance.

**Comment by Melli811** [comment]
Has this issue been solved yet? We seem to have the same issue. Thanks!
