### ISSUE TITLE
Using calibration, intrinsic and extrinsic pickle files to triangulate manually labeled points from set of images

### ISSUE THREAD

**Issue by jonahpc** [DeepLabCut/DeepLabCut#1600]
Hey DLC Family!

There are times that I do not care about the time-dependency of the features, nor is it a feature that I want to train the network, but that I want to label once in both images and then triangulate into a 3d space.

For instance, let’s say I place a ruler in my two FOVs to use as a conversion for unit conversion in 3d space. Instead of leaving the ruler in the videos and having DLC label them/train DLC, I want to take one image with the ruler in both FOVs and then manually select 2 points that have known distances (because they are on the ruler).

Is there a way to take those 2 point's coordinates, each in it’s own camera view, and then use the camera calibration files to triangulate them? If so, how would I do that? Thanks a ton!

**Comment by AlexEMG** [comment]
You can do this with the following OpenCV function: https://github.com/DeepLabCut/DeepLabCut/blob/master/deeplabcut/pose_estimation_3d/triangulation.py#L376 (check out the surrounding code for loading the calibration files etc.)
