### ISSUE TITLE
running on GPU

### ISSUE THREAD

**Issue by shanikornha** [DeepLabCut/DeepLabCut#1601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When trying to run the training, I see that no GPU is activated. In addition, the training something stop after 20 iterations and is not proceedings. 

### Operating System

operating system: Windows 10
CUDA: v11.2
cuDNN: 8.1
Tensorflow: 2.7

### DeepLabCut version

dlc version: I couldn't run the code; I assume it is the newest

### DeepLabCut mode

single animal

### Device type

gpu 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 497.09       Driver Version: 497.09       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:03:00.0  On |                  N/A |
|  0%   50C    P8    17W / 170W |    754MiB / 12288MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1300    C+G   Insufficient Permissions        N/A      |
|    0   N/A  N/A      1328    C+G   ...y\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A      6560    C+G   ...ge\Application\msedge.exe    N/A      |
|    0   N/A  N/A      9332    C+G   C:\Windows\explorer.exe         N/A      |
|    0   N/A  N/A      9844    C+G   ...artMenuExperienceHost.exe    N/A      |
|    0   N/A  N/A     10780    C+G   ...5n1h2txyewy\SearchApp.exe    N/A      |
|    0   N/A  N/A     11380    C+G   ...me\Application\chrome.exe    N/A      |
|    0   N/A  N/A     12180    C+G   ...nputApp\TextInputHost.exe    N/A      |
+-----------------------------------------------------------------------------+

### Steps To Reproduce

1. Label and extract frames.
2. Create training dataset:
deeplabcut.create_training_dataset(config)
4. Change in the pose.cfg file the displayitters to 10 instead of 1000
4. Run and try to train the network
deeplabcut.train_network(config, gputouse=0)
or deeplabcut.train_network(config)
5. Observe the following on the screen.

### Relevant log output

```shell
Microsoft Windows [Version 10.0.19042.1348]
(c) Microsoft Corporation. All rights reserved.

C:\Users\kornha0000-adm>nvidia-smi
Wed Dec  8 11:26:22 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 497.09       Driver Version: 497.09       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:03:00.0  On |                  N/A |
|  0%   54C    P8    19W / 170W |    602MiB / 12288MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1300    C+G   Insufficient Permissions        N/A      |
|    0   N/A  N/A      1328    C+G   ...y\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A      6560    C+G   ...ge\Application\msedge.exe    N/A      |
|    0   N/A  N/A      9332    C+G   C:\Windows\explorer.exe         N/A      |
|    0   N/A  N/A      9844    C+G   ...artMenuExperienceHost.exe    N/A      |
|    0   N/A  N/A     10780    C+G   ...5n1h2txyewy\SearchApp.exe    N/A      |
|    0   N/A  N/A     11380    C+G   ...me\Application\chrome.exe    N/A      |
|    0   N/A  N/A     12180    C+G   ...nputApp\TextInputHost.exe    N/A      |
+-----------------------------------------------------------------------------+

C:\Users\kornha0000-adm>conda activate DEEPLABCUT

(DEEPLABCUT) C:\Users\kornha0000-adm>python
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import deeplabcut
>>> config = 'C:\Users\kornha0000-adm\Desktop\T1_Videos\Test_number_1-SL-2021-12-07\config.yaml'
  File "<stdin>", line 1
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
>>> config = r'C:\Users\kornha0000-adm\Desktop\T1_Videos\Test_number_1-SL-2021-12-07\config.yaml'
>>> deeplabcut.create_training_dataset(config)
The training dataset is successfully created. Use the function 'train_network' to start training. Happy training!
[(0.95, 1, (array([17, 35,  8,  3, 25, 24, 11, 13,  1, 22,  2, 28, 19, 36, 33, 18, 29,
       10,  5, 38, 14, 21,  0, 16,  7, 37, 34, 26,  4, 12, 32, 27,  9, 15,
       23,  6, 20]), array([31, 30])))]
>>> deeplabcut.train_network(config, gputouse=0)
Selecting single-animal trainer
Config:
{'all_joints': [[0], [1], [2], [3]],
 'all_joints_names': ['head', 'FLeft', 'FRight', 'bottom'],
 'alpha_r': 0.02,
 'apply_prob': 0.5,
 'batch_size': 1,
 'clahe': True,
 'claheratio': 0.1,
 'crop_pad': 0,
 'crop_sampling': 'hybrid',
 'crop_size': [400, 400],
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Test_number_1Dec7\\Test_number_1_SL95shuffle1.mat',
 'dataset_type': 'default',
 'decay_steps': 30000,
 'deterministic': False,
 'display_iters': 10,
 'edge': False,
 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]},
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'histeq': True,
 'histeqratio': 0.1,
 'init_weights': 'C:\\Users\\kornha0000-adm\\Anaconda3\\envs\\DEEPLABCUT\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'lr_init': 0.0005,
 'max_input_size': 1500,
 'max_shift': 0.4,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Test_number_1Dec7\\Documentation_data-Test_number_1_95shuffle1.pickle',
 'min_input_size': 64,
 'mirror': False,
 'multi_stage': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 4,
 'optimizer': 'sgd',
 'pairwise_huber_loss': False,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'pos_dist_thresh': 17,
 'pre_resize': [],
 'project_path': 'C:\\Users\\kornha0000-adm\\Desktop\\T1_Videos\\Test_number_1-SL-2021-12-07',
 'regularize': False,
 'rotation': 25,
 'rotratio': 0.4,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'sharpen': False,
 'sharpenratio': 0.3,
 'shuffle': True,
 'snapshot_prefix': 'C:\\Users\\kornha0000-adm\\Desktop\\T1_Videos\\Test_number_1-SL-2021-12-07\\dlc-models\\iteration-0\\Test_number_1Dec7-trainset95shuffle1\\train\\snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Batch Size is 1
C:\Users\kornha0000-adm\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
2021-12-08 11:42:54.946297: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-12-08 11:42:56.174711: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9613 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060, pci bus id: 0000:03:00.0, compute capability: 8.6
Loading ImageNet-pretrained resnet_50
2021-12-08 11:42:56.705312: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9613 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060, pci bus id: 0000:03:00.0, compute capability: 8.6
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': 'C:\\Users\\kornha0000-adm\\Desktop\\T1_Videos\\Test_number_1-SL-2021-12-07\\dlc-models\\iteration-0\\Test_number_1Dec7-trainset95shuffle1\\train\\snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'sgd', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'default', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': False, 'pairwise_predict': False, 'all_joints': [[0], [1], [2], [3]], 'all_joints_names': ['head', 'FLeft', 'FRight', 'bottom'], 'alpha_r': 0.02, 'apply_prob': 0.5, 'clahe': True, 'claheratio': 0.1, 'crop_sampling': 'hybrid', 'crop_size': [400, 400], 'cropratio': 0.4, 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Test_number_1Dec7\\Test_number_1_SL95shuffle1.mat', 'decay_steps': 30000, 'display_iters': 10, 'edge': False, 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]}, 'histeq': True, 'histeqratio': 0.1, 'init_weights': 'C:\\Users\\kornha0000-adm\\Anaconda3\\envs\\DEEPLABCUT\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt', 'lr_init': 0.0005, 'max_input_size': 1500, 'max_shift': 0.4, 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Test_number_1Dec7\\Documentation_data-Test_number_1_95shuffle1.pickle', 'min_input_size': 64, 'multi_stage': False, 'multi_step': [[0.005, 10000], [0.02, 430000], [0.002, 730000], [0.001, 1030000]], 'net_type': 'resnet_50', 'num_joints': 4, 'pos_dist_thresh': 17, 'pre_resize': [], 'project_path': 'C:\\Users\\kornha0000-adm\\Desktop\\T1_Videos\\Test_number_1-SL-2021-12-07', 'rotation': 25, 'rotratio': 0.4, 'save_iters': 50000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'sharpen': False, 'sharpenratio': 0.3, 'covering': True, 'elastic_transform': True, 'motion_blur': True, 'motion_blur_params': {'k': 7, 'angle': (-90, 90)}}
Starting training....
2021-12-08 11:43:04.552558: I tensorflow/stream_executor/cuda/cuda_dnn.cc:366] Loaded cuDNN version 8100
```

### Anything else?

I am struggling with this error for over a month. 
I have checked that CUDA 11.2 is compatible with cuDNN 8.1, and that the latest tensorflow (2.7) also matches all the above. 
I installed python 3.9.9 and visual studio 2019. 
Any help will be highly appreciated!!

Thanks a lot
Best,
Shani 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @shanikornha, what error are you referring to? The log you uploaded looks all fine. Do you mean the `Insufficient Permissions` in the `nvidia-smi` output?

**Comment by shanikornha** [comment]
Hi @jeylau ! thanks for the quick answer. 
There's no error.. that is part of the problem. I am running the training and nothing happens. Even if I change the displayitters to 10, which means that I need to see something happens, there is no movement. To maximum itters that it shows (when it is showing) is 20. 
I also check my GPU, and it is not active. 
I am not quite sure what is the problem...
I tired all sorts of codes and solution that I saw were suggested to others, but they don't seem to work for me. 
Also, is it good that I am setting the gputouse as 0?

**Comment by jeylau** [comment]
`gputouse=0` is the default settings, so you don't need to set it explicitly when you only have one device on your machine ☺️ Could I ask you though to run the test script with `python examples/testscript.py` and let me know if it runs fine?

**Comment by shanikornha** [comment]
> `gputouse=0` is the default settings, so you don't need to set it explicitly when you only have one device on your machine ☺️ Could I ask you though to run the test script with `python examples/testscript.py` and let me know if it runs fine?

Hi (: 
The testscript seems to run fine

(edit to truncate - full output is not required)
```
ALL DONE!!! - default cases are functional.
```

**Comment by shanikornha** [comment]
Now I tried to run again my code, and it again got stuck after interation 46, the code is below: 

```
Microsoft Windows [Version 10.0.19042.1348]
(c) Microsoft Corporation. All rights reserved.

C:\Users\kornha0000-adm>conda activate DEEPLABCUT

(DEEPLABCUT) C:\Users\kornha0000-adm>python
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import deeplabcut
>>> config = r'C:\Users\kornha0000-adm\Desktop\T1_Videos\Test_number_1-SL-2021-12-07\config.yaml'
>>> deeplabcut.create_training_dataset(config)
The training dataset is successfully created. Use the function 'train_network' to start training. Happy training!
[(0.95, 1, (array([35,  1, 38, 16,  5, 18, 13, 11, 19, 23, 24, 31, 37, 26, 15, 36, 21,
       30, 20, 28,  0, 27,  6,  4,  8,  2, 12,  7,  3,  9, 25, 32, 17, 29,
       14, 34, 33]), array([10, 22])))]
>>> deeplabcut.train_network(config)
Selecting single-animal trainer
Config:
{'all_joints': [[0], [1], [2], [3]],
 'all_joints_names': ['head', 'FLeft', 'FRight', 'bottom'],
 'alpha_r': 0.02,
 'apply_prob': 0.5,
 'batch_size': 1,
 'clahe': True,
 'claheratio': 0.1,
 'crop_pad': 0,
 'crop_sampling': 'hybrid',
 'crop_size': [400, 400],
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Test_number_1Dec7\\Test_number_1_SL95shuffle1.mat',
 'dataset_type': 'default',
 'decay_steps': 30000,
 'deterministic': False,
 'display_iters': 2,
 'edge': False,
 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]},
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'histeq': True,
 'histeqratio': 0.1,
 'init_weights': 'C:\\Users\\kornha0000-adm\\Anaconda3\\envs\\DEEPLABCUT\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'lr_init': 0.0005,
 'max_input_size': 1500,
 'max_shift': 0.4,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Test_number_1Dec7\\Documentation_data-Test_number_1_95shuffle1.pickle',
 'min_input_size': 64,
 'mirror': False,
 'multi_stage': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 4,
 'optimizer': 'sgd',
 'pairwise_huber_loss': False,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'pos_dist_thresh': 17,
 'pre_resize': [],
 'project_path': 'C:\\Users\\kornha0000-adm\\Desktop\\T1_Videos\\Test_number_1-SL-2021-12-07',
 'regularize': False,
 'rotation': 25,
 'rotratio': 0.4,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'sharpen': False,
 'sharpenratio': 0.3,
 'shuffle': True,
 'snapshot_prefix': 'C:\\Users\\kornha0000-adm\\Desktop\\T1_Videos\\Test_number_1-SL-2021-12-07\\dlc-models\\iteration-0\\Test_number_1Dec7-trainset95shuffle1\\train\\snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Batch Size is 1
C:\Users\kornha0000-adm\Anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
2021-12-08 15:03:46.027128: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-12-08 15:03:46.531005: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9613 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060, pci bus id: 0000:03:00.0, compute capability: 8.6
Loading ImageNet-pretrained resnet_50
2021-12-08 15:03:47.030570: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9613 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060, pci bus id: 0000:03:00.0, compute capability: 8.6
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': 'C:\\Users\\kornha0000-adm\\Desktop\\T1_Videos\\Test_number_1-SL-2021-12-07\\dlc-models\\iteration-0\\Test_number_1Dec7-trainset95shuffle1\\train\\snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'sgd', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'default', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': False, 'pairwise_predict': False, 'all_joints': [[0], [1], [2], [3]], 'all_joints_names': ['head', 'FLeft', 'FRight', 'bottom'], 'alpha_r': 0.02, 'apply_prob': 0.5, 'clahe': True, 'claheratio': 0.1, 'crop_sampling': 'hybrid', 'crop_size': [400, 400], 'cropratio': 0.4, 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Test_number_1Dec7\\Test_number_1_SL95shuffle1.mat', 'decay_steps': 30000, 'display_iters': 2, 'edge': False, 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]}, 'histeq': True, 'histeqratio': 0.1, 'init_weights': 'C:\\Users\\kornha0000-adm\\Anaconda3\\envs\\DEEPLABCUT\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt', 'lr_init': 0.0005, 'max_input_size': 1500, 'max_shift': 0.4, 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Test_number_1Dec7\\Documentation_data-Test_number_1_95shuffle1.pickle', 'min_input_size': 64, 'multi_stage': False, 'multi_step': [[0.005, 10000], [0.02, 430000], [0.002, 730000], [0.001, 1030000]], 'net_type': 'resnet_50', 'num_joints': 4, 'pos_dist_thresh': 17, 'pre_resize': [], 'project_path': 'C:\\Users\\kornha0000-adm\\Desktop\\T1_Videos\\Test_number_1-SL-2021-12-07', 'rotation': 25, 'rotratio': 0.4, 'save_iters': 50000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'sharpen': False, 'sharpenratio': 0.3, 'covering': True, 'elastic_transform': True, 'motion_blur': True, 'motion_blur_params': {'k': 7, 'angle': (-90, 90)}}
Starting training....
2021-12-08 15:03:53.655634: I tensorflow/stream_executor/cuda/cuda_dnn.cc:366] Loaded cuDNN version 8100
iteration: 2 loss: 0.9759 lr: 0.005
iteration: 4 loss: 0.1427 lr: 0.005
iteration: 6 loss: 0.0862 lr: 0.005
iteration: 8 loss: 0.0171 lr: 0.005
iteration: 10 loss: 0.0790 lr: 0.005
iteration: 12 loss: 0.1711 lr: 0.005
iteration: 14 loss: 0.0547 lr: 0.005
iteration: 16 loss: 0.0429 lr: 0.005
iteration: 18 loss: 0.0344 lr: 0.005
iteration: 20 loss: 0.0329 lr: 0.005
iteration: 22 loss: 0.0337 lr: 0.005
iteration: 24 loss: 0.0321 lr: 0.005
iteration: 26 loss: 0.0292 lr: 0.005
iteration: 28 loss: 0.0136 lr: 0.005
iteration: 30 loss: 0.0389 lr: 0.005
iteration: 32 loss: 0.0242 lr: 0.005
iteration: 34 loss: 0.0293 lr: 0.005
iteration: 36 loss: 0.0317 lr: 0.005
iteration: 38 loss: 0.0220 lr: 0.005
iteration: 40 loss: 0.0276 lr: 0.005
iteration: 42 loss: 0.0204 lr: 0.005
iteration: 44 loss: 0.0261 lr: 0.005
iteration: 46 loss: 0.0168 lr: 0.005
```

**Comment by backyardbiomech** [comment]
You mentioned python==3.9.9. 
How did you install deeplabcut? Was it with the conda environment file provided? I'm pretty sure (but I could be wrong) that python 3.9+ is not supported, and if you have built your own env you may have some dependency conflicts. And please confirm the version of deeplabcut you have installed. After importing deeplabcut, just run `deeplabcut.__version__`.

As far as your GPU, have you followed [these instructions](https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html#how-to-confirm-that-your-gpu-is-being-used-by-deeplabcut) to determine GPU usage during training? It is not the GPU "usage" percentage that first shows in Windows Task Manager.

**Comment by shanikornha** [comment]
Hi @backyardbiomech ! thanks a lot for the answer. 
1. The deeplabcut bersion I have is '2.2.0.3'; in the main installation page I see that python 3.7 (at least) is required.. so I guess that is OK. Or is it better to use another version of python? 
2. Regarding my GPU usage: I checked how it is recommmended (I didn't see this page before). 
I saw a temporary increase in my CUDA usage to max - but then it drops, and again stops at a very early iteration (now it is 16). 
3. Do you think it might be some kind of dependency conflict between CUDA and cuDNN or something else? 

Thanks a lot again! I appreciate the help and effort 
Shani

**Comment by MMathisLab** [comment]
@shanikornha - what happens after iteration 46? this looks like the classic case of windows pausing the terminal if you click on it. It seems to train fine. 

Note, it IS using your GPU:

` Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9613 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060, pci bus id: 0000:03:00.0, compute capability: 8.6` 

"To pause the output of a command, press Ctrl+S or the Pause key. To resume output, press any key. If you have enabled QuickEdit mode for your Command Prompt window, simply click in the window to pause command output. To resume output, right-click in the window."

https://superuser.com/questions/1145483/is-there-a-keyboard-shortcut-to-pause-the-output-of-a-cmd-window-while-its-runn/1145485

Be sure that "quick edit" is disabled - otherwise, if you click on the window it pauses the run.

**Comment by shanikornha** [comment]
@MMathisLab Thank you for the answer!!!!!
I think I solved the problem. It seems that I did not upload enough videos. Now I upload many more and it is running since yesterday. 
I do have another question though. I noticed that in the pose.cfg code there is no max_iters (the line is not there).
Does it mean that I need to stop it? (I did not put in the train_network line any max_iters). 

Below is the pose.cfg code. I did not delete any line from it. Can it be that in the new updated version the max_iters is not there?

`all_joints:
- - 0
- - 1
- - 2
- - 3
all_joints_names:
- head
- abdomen
- left_front
- right_front
alpha_r: 0.02
apply_prob: 0.5
batch_size: 1
clahe: true
claheratio: 0.1
crop_sampling: hybrid
crop_size:
- 400
- 400
cropratio: 0.4
dataset: training-datasets\iteration-0\UnaugmentedDataSet_Test_DLC_iphoneDec9\Test_DLC_iphone_SK95shuffle1.mat
dataset_type: default
decay_steps: 30000
display_iters: 2
edge: false
emboss:
  alpha:
  - 0.0
  - 1.0
  embossratio: 0.1
  strength:
  - 0.5
  - 1.5
global_scale: 0.8
histeq: true
histeqratio: 0.1
init_weights: C:\Users\kornha0000-adm\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
max_shift: 0.4
metadataset: training-datasets\iteration-0\UnaugmentedDataSet_Test_DLC_iphoneDec9\Documentation_data-Test_DLC_iphone_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: resnet_50
num_joints: 4
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
pre_resize: []
project_path: C:\Users\kornha0000-adm\Desktop\iphone test videos\Test_DLC_iphone-SK-2021-12-09
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
sharpen: false
sharpenratio: 0.3
`

**Comment by MMathisLab** [comment]
@shanikornha max_iters is not in the pose_cfg.yaml, but you pass it when you train:

`deeplabcut.train_network(config_path, shuffle=1, trainingsetindex=0, gputouse=None, max_snapshots_to_keep=5, autotune=False, displayiters=100, saveiters=15000, maxiters=30000, allow_growth=True)`

https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html#g-train-the-network

You can always stop training (control +C); and the snapshots are saved (you can see the dlc-models folder has them as it trains).

**Comment by LWitter** [comment]
> @MMathisLab Thank you for the answer!!!!! I think I solved the problem. It seems that I did not upload enough videos. Now I upload many more and it is running since yesterday.

Could you explain what you did here? We're running into exactly the same issue, but ours is stopping after ±5 iterations. only. Memory of the GPU is almost full (94%), but not being used (1.0% prob windows). How did you 'upload enough videos'?
