### ISSUE TITLE
H5 file in the labeled-data folder  -- migrating labeled-data

### ISSUE THREAD

**Issue by felipearrudamoura** [DeepLabCut/DeepLabCut#1602]
My point is not necessarily a problema. I would like to understand how the H5 file inside the "labeled-data" folder is structured. If we have labeled data in other platforms, it would be possible to migrate to deeplabcut without having to manually label again. Also, after analyzing the videos after having the network trained, it would be possible to choose some good frames to improve the labeling and retrain the network.
Is that possible?

**Comment by AlexEMG** [comment]
Yes this is possible. Check out: 
https://github.com/DeepLabCut/DeepLabCut/wiki/Using-labeled-data-in-DeepLabCut-that-was-annotated-elsewhere

**Comment by felipearrudamoura** [comment]
It worked!! Perfect!! Thanks!!

Prof. Dr. Felipe Arruda Moura
Laboratório de Biomecânica Aplicada - LBA
Centro de Educação Física e Esporte
Universidade Estadual de Londrina
-------------------------------------------------------------
Prof. PhD. Felipe Arruda Moura
Laboratory of Applied Biomechanics
State University of Londrina


Em qui., 9 de dez. de 2021 às 09:23, Alexander Mathis <
***@***.***> escreveu:
