### ISSUE TITLE
Issue when runing training on cluster 

### ISSUE THREAD

**Issue by DorianBattivelli** [DeepLabCut/DeepLabCut#1606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I faile to run the training on a cluster (via docker installation).
This installation works for multi-animal project (at least the analysis - never trained a MAmodel with this installation). 

- This time I'm working on a single animal model. 
- On the GUI, I start a new project and run all the steps until 'create training dataset'.
- Then I transfert all my project folder on my virtual machine (when the docker is installed)
- And when I run the command for the training, it returns:

<img width="1030" alt="Schermata 2021-12-09 alle 21 23 26" src="https://user-images.githubusercontent.com/66886884/145470373-e9df8cd6-4261-4d6c-bfe0-778e5c12f0ac.png">

And indeed, my "training-datasets" folder is empty. Is a file missing there? Why? 
FYI: I'm using resnet_50 network for training.

Thank you, 
Cheers,

### Operating System

The GUI part of the project was done on Windows 10.

### DeepLabCut version

2.2.0.3

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by DorianBattivelli** [comment]
It's me again, I think my problem comes from a format issue between Windows and Unix languages as mentioned here https://github.com/DeepLabCut/DeepLabCut/issues/1134#issuecomment-847413065

So I did the converion using deeplabcut.convertannotationdata_fromwindows2unixstyle.

But I still have an error for the .mat document missing, while this time, it is intop the folder:

<img width="1368" alt="Schermata 2021-12-11 alle 17 09 36" src="https://user-images.githubusercontent.com/66886884/145683485-4413dcb2-2dfc-4389-8e02-e40b1b1acfaf.png">


Do you know what is going wrong there?
Thank you very much, 

Cheers,

**Comment by jeylau** [comment]
Hello @DorianBattivelli, it is generally better to create the training datasets on the machine where the model will be trained, so move the labeled data to your virtual machine and run `deeplabcut.create_training_dataset` there. Note that this won't be necessary anymore in deeplabcut 2.2.1 thanks to #1584.
Also double check that the `project_path` in the config.yaml is up-to-date after moving the files: your config and training files seem to reside in /g/gross... whereas it's trying to load the data in a F:\\ disk (of your local Windows machine I suppose). I hope that helps!

**Comment by DorianBattivelli** [comment]
Hi @jeylau,

Thank you very much for the help! Indeed, I recreated all the project from scratch, directly on the machine where I run the training, and everything works fine now,

Thanks again, 

Cheers
