### ISSUE TITLE
Deeplabcut evaluate network

### ISSUE THREAD

**Issue by linkedList123** [DeepLabCut/DeepLabCut#1608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi all! I believe the alpha channels in the current DLC package might not be properly blended into the RGB channels (e.g. RGBA images aren't being converted into RGB, if required). Evaluating my network I've trained in DLC, the following error appears.

"ValueError: Cannot feed value of shape (1, 1796, 2412, 4) for Tensor Placeholder:0, which has shape (1, None, None, 3)"

Does anyone have code that can change the number of color channels considered? Thanks in advance!

### Operating System

MacOS

### DeepLabCut version

dlc version

### DeepLabCut mode

multi animal

### Device type

gpu

### Relevant log output

```shell
"ValueError: Cannot feed value of shape (1, 1796, 2412, 4) for Tensor Placeholder:0, which has shape (1, None, None, 3)"
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
hi @deplabcut (funny name choice ;). Are your evaluation images (i..e, the images you labeled) moved? if you search there error, there are two related issues, did you check those out? 

https://github.com/DeepLabCut/DeepLabCut/search?q=ValueError%3A+Cannot+feed+value+of+shape%22&type=issues

**Comment by linkedList123** [comment]
Hello @MMathisLab, thank you so much for this response. I did see the related issues, but didn't know how to implement the changes you mentioned (i.e. changing the number of color channels) since I'm using the GUI, and not the terminal.

Also, I don't believe the images I labeled were moved: they are still in the labeled-data folder. Within the labeled data folder, they are in a folder called [videoname-labeled].

Sorry, I'm new to this, and thank you so much!

**Comment by linkedList123** [comment]
Also, there are two separate subfolders folders in the labeled-data (video and video_labeled_data), so I don't believed anything was overwritten. 

I'm also using the latest version of DLC. I followed the youtube tutorial and only labeled two corners of the box I was looking at; could this be the problem?

**Comment by linkedList123** [comment]
I think it may be a color channel issue because when I click the "optional: plot 3 test maps" option, the images I get in the maps folder in the evaluation-results folder are tinted purple and green, which was not my original color. Also, these pictures are only those which I have labeled, not new pictures.

**Comment by backyardbiomech** [comment]
> Also, there are two separate subfolders folders in the labeled-data (video and video_labeled_data), so I don't believed anything was overwritten.

The folder with just the video name is the important one. The one with `labeled` is the result of running `check_labels`. You should inspect those images to make sure the markers are being placed where you want them. After inspection, you can actually delete those 'labeled' folders if you want (e.g. to save space).

>Also, I don't believe the images I labeled were moved: they are still in the labeled-data folder. Within the labeled data folder, they are in a folder called [videoname-labeled].

Not that folder. Make sure the images are in the folders just named for the video.

>I'm also using the latest version of DLC. 

If you are running this on your mac, activate your env, then:
```
pythonw
import deeplabcut
deeplabcut.__version__
```
It would be very helpful if you provide the actual version number. Or are you using colab to train and evaluate?

>I followed the youtube tutorial and only labeled two corners of the box I was looking at; could this be the problem?

Yes, if  you don't have any animal body parts labeled. What specifically do you have entered in config.yaml for bodyparts? If you don't have any animal body parts there, or have them but didn't label any, you should expect errors. 

>I am using multi animal mode but I'm only evaluating a single animal.

If you are new to deeplabcut, I would strongly advise against this until you have fully trained a single animal model for your scenario and determined that it is insufficient and the added features of the multi-animal tracking might be beneficial. However, using maDLC for single animal is about to get quite a bit smoother.

> (1, 1796, 2412, 4)

You also appear to have very large frames. Did you increase `max_input_size` to 2412 (or more) in `pose_cfg.yaml` in both test and train folders in dlc-models? With maDLC now doing autocropping for training, I don't think this should cause any problems, at least for training, but it might be worth changing it anyways.

**Comment by linkedList123** [comment]
@MMathisLab Thank you very much for this response. 

I confirmed that the subfolder of just the video name in the labeled-data folder has only the unlabeled pictures, as well as a data collected csv and h5 file. 

Also, it says the version I have for deeplabcut is 2.2.0.3. I am using my mac terminal, not colab.

The video I was using is called "Using maDLC/ DeepLabCut 2.2 with a *single animal*," and I have the same config.yaml (multianimal) file as in the video, and the bodyparts part is:

individuals:
- individual1
uniquebodyparts:
- cornerofbox1
- cornerofbox2
multianimalbodyparts:
- snout
- leftear
- rightear
- midbody
- tailbase
- tail
skeleton:
- - snout
  - leftear
- - snout
  - rightear
- - snout
  - midbody
- - snout
  - tailbase
- - midbody
  - tailbase
- - leftear
  - rightear
- - leftear
  - midbody
- - rightear
  - midbody
- - midbody
  - tail1
- - tailbase
  - tail1

Also, I didn't see a line called max_input_size in the pose_cfg.yaml for test. I have added a line called max_input_size: 2412 in this yaml file and increased the max_input_size to 2412 for the train folder pose_cfg.yaml file. Thanks for the help!

**Comment by backyardbiomech** [comment]
It's very doable to use maDLC with single animals (I have multiple projects run that way), but I wouldn't recommend it until you know that standard DLC isn't sufficient. 

>I followed the youtube tutorial and only labeled two corners of the box I was looking at; could this be the problem?

I read that to mean that you labeled only the two box corners, and **not** any of the multianimalbodyparts. Did you label all the body parts in all of the images?

**Comment by linkedList123** [comment]
@backyardbiomech I labeled all of the bodyparts for the single animal in each frame. However, sometimes the animal was blocking the corner of a box, so I didn't label that corner. Is this problematic? Or should I retrain/relabel the corner of a box over the mouse that's blocking it in all frames? Thanks

**Comment by backyardbiomech** [comment]
> I labeled all of the bodyparts for the single animal in each frame. 
Good. So that's not the problem.

> Or should I retrain/relabel the corner of a box over the mouse that's blocking it in all frames?
No. As a general rule, only label what you can see. 

> Also, I didn't see a line called max_input_size in the pose_cfg.yaml for test
I can't always remember what is in each without looking. Adding it shouldn't cause a problem, though. Did that fix the evaluation problem? @MMathisLab would know if this large size would still be a problem with the cropping in maDLC, but you might need to train anew now that you've changed it.

**Comment by linkedList123** [comment]
@backyardbiomech Haven't fixed the evaluation problem yet-- been stuck on this for a while. When I hit the "RUN: Evaluate network" button in the GUI, the terminal continues to say:


Activating extracting of PAFs
Network Evaluation underway...
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/Users/user/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/gui/evaluate_network.py", line 270, in evaluate_network
    deeplabcut.evaluate_network(
  File "/Users/user/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/core/evaluate.py", line 572, in evaluate_network
    evaluate_multianimal_full(
  File "/Users/user/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py", line 350, in evaluate_multianimal_full
    pred = predictma.predict_batched_peaks_and_costs(
  File "/Users/user/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/core/predict_multianimal.py", line 215, in predict_batched_peaks_and_costs
    scmaps, locrefs, *pafs, peaks = sess.run(
  File "/Users/user/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 970, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/Users/user/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1167, in _run
    raise ValueError(
ValueError: Cannot feed value of shape (1, 1796, 2412, 4) for Tensor Placeholder:0, which has shape (1, None, None, 3)

**Comment by linkedList123** [comment]
Also, is there a way to remove markers when labeling?

**Comment by linkedList123** [comment]
If it is indeed a color channel issue as mentioned in other posts, would there by anyway to change the shape of Tensor Placeholder:0?

**Comment by jeylau** [comment]
Hey @deplabcut, I think your issue should be solved with #1614. The alpha channel should now be correctly read and blended into RGB ☺️

**Comment by linkedList123** [comment]
@jeylau thanks for this response. How would I implement these new changes? Should I download everything and retrain everything, and then it will work? Thanks!

**Comment by jeylau** [comment]
I'd open the terminal, make sure your deeplabcut environment is activated, and run
`pip install git+https://github.com/DeepLabCut/DeepLabCut.git@fix_rgba`
This will reinstall deeplabcut with just the minor changes I brought to address your issue.

**Comment by linkedList123** [comment]
Thank you! And then relabel/retrain the model, correct?

**Comment by jeylau** [comment]
I do not think it is needed; you should be able to re-run `deeplabcut.evaluate_network` without errors this time.

**Comment by linkedList123** [comment]
@jeylau Hmm I put the pip install command into my terminal and I'm still getting the error when evaluating the network. Does it have anything to do with me using the GUI and not actually typing "deeplabcut.evaluate_network" into the terminal?

**Comment by linkedList123** [comment]
Is there any way to check that the update actually went through?

**Comment by linkedList123** [comment]
Quick bump on the above message?
