### ISSUE TITLE
Accessing calibration features to triangulate manually selected points in both camera views

### ISSUE THREAD

**Issue by jonahpc** [DeepLabCut/DeepLabCut#1609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

There are times that I do not care about the time-dependency of the features, nor is it a feature that i want to train the network, but that I want to label once in both images and then triangulate into a 3d space.

For instance, let’s say I place a ruler in my two FOVs to use as a conversion for unit conversion in 3d space. Instead of leaving the ruler in the videos and having DLC label them, I want to take one image with the ruler in both FOVs and then manually select 2 points that have known distances (because they are on the ruler).

Is there a way to take those 2 points, each in it’s own camera view, and then use the camera calibration files to triangulate them? If so, how would I do that? Thanks a ton!

### Operating System

Windows 10

### DeepLabCut version

dlc version 2.1

### DeepLabCut mode

single animal

### Device type

GForce RTX 2080

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by nisckhan13** [comment]
I'm also curious about this.

**Comment by backyardbiomech** [comment]
This is a repost of a closed issue #1600 . I would suggest posting on the forum to see if anyone else has written code for this.
