### ISSUE TITLE
specifying parameters for extract_outlier_frames

### ISSUE THREAD

**Issue by HaixinLiuNeuro** [DeepLabCut/DeepLabCut#161]
**Your Operating system and DeepLabCut version**

Windows 10, DLC 2.0

**Describe the problem**

After successfully training a model, analyzing a video, I would like to extract outlier frames as there are mislabeled frames by examining the created labelled video. 
When I ran 

deeplabcut.extract_outlier_frames(config_path,['video path'])

I got result:
Fitting state-space models with parameters 3 1
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<?, ?it/s]
Method  fitting  found  0  putative outlier frames.
Do you want to proceed with extracting  20  of those?

This is weird as there are frames quite off, shown by the plotting result
![image](https://user-images.githubusercontent.com/46263698/50599782-07701e80-0e7d-11e9-82ec-d0639d4f9906.png)

I saw there is a way to specify the parameters for extracting outlier:
extract_outlier_frames(config, videos, shuffle, trainingsetindex, outlieralgorithm, comparisonbodyparts, epsilon, p_bound, ARdegree, MAdegree, alpha, extractionalgorithm, automatic)
However, I'm not familiar with python and the instruction doc does not provide a example code. I was wondering how can I specify the parameters to get some outlier frames extracted.

Thank you!

Best,
Haixin

**Comment by MMathisLab** [comment]
If you type ``deeplabcut.extract_outlier_frames?`` you will get the full function description - this is true for all functions in deeplabcut, i.e. add the ``?``
please see the user guide: https://www.biorxiv.org/content/biorxiv/early/2018/11/24/476531.full.pdf

![image](https://user-images.githubusercontent.com/28102185/50602135-7a30c800-0e84-11e9-8676-c4be293397fc.png)

**Comment by HaixinLiuNeuro** [comment]
Thanks so much!
I should have googled how to get help function in python.

Yep. Now, I can get the outliers out. Thanks again

**Comment by AlexEMG** [comment]
Here are a few use examples (from the help):

 for extracting the frames with default settings
    >>>``` deeplabcut.extract_outlier_frames('/analysis/project/reaching-task/config.yaml',['/analysis/project/video/reachinvideo1.avi'])```
    --------
    for extracting the frames with kmeans
    >>> ```deeplabcut.extract_outlier_frames('/analysis/project/reaching-task/config.yaml',['/analysis/project/video/reachinvideo1.avi'],extractionalgorithm='kmeans')```
    --------
    for extracting the frames with kmeans and epsilon = 5 pixels.
    >>> ```deeplabcut.extract_outlier_frames('/analysis/project/reaching-task/config.yaml',['/analysis/project/video/reachinvideo1.avi'],epsilon = 5,extractionalgorithm='kmeans',outlieralgorithm='jump')```

In your case, outlieralgorith=uncertain will be best. See:     outlieralgorithm: 'fitting', 'jump', or 'uncertain', optional

String specifying the algorithm used to detect the outliers. Currently, deeplabcut supports three methods. 'Fitting' fits a Auto Regressive Integrated Moving Average model to the data and computes the distance to the estimated data. Larger distances than epsilon are then potentially identified as outliers. The methods 'jump' identifies larger jumps than 'epsilon' in any body part; and 'uncertain' looks for frames with confidence below p_bound. The default is set to "fitting".

**Comment by HaixinLiuNeuro** [comment]
Thanks
