### ISSUE TITLE
Project not created because videos were not found. Videos works fine on VLC

### ISSUE THREAD

**Issue by AymericFerreira** [DeepLabCut/DeepLabCut#1612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

In both GUI and CLI I can't create a project because videos are not found.
Videos are working and can be open and played normally in both VLC.
I tried to reimport again the videos without success, videos are in mp4 format.

### Operating System

Windows

### DeepLabCut version

python 3.8.12
deeplabcut : 2.2.0.3

### DeepLabCut mode

single animal

### Device type

cpu

### Steps To Reproduce

- I cloned the repository
- In anaconda prompt in administrator
- Moved to the conda-environnements folder
- conda env create -f DEEPLABCUT.yaml
- conda activate DEEPLABCUT
- Start gui via python -m deeplabcut
- Create new project, name the project, choose one or multiple videos, Press OK. Get the error

### Relevant log output

```shell
D:\DLC\fsafas2-mazr-2021-12-13\videos\17226.mp4

C:\Users\Marie\anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\create_project\new.py:188: UserWarning: Cannot open the video file! Skipping to the next one...

  warnings.warn("Cannot open the video file! Skipping to the next one...")

C:\Users\Marie\anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\create_project\new.py:194: UserWarning: No valid videos were found. The project was not created... Verify the video files and re-create the project.

  warnings.warn(

Traceback (most recent call last):

  File "C:\Users\Marie\anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\create_new_project.py", line 390, in create_new_project

    cfg = auxiliaryfunctions.read_config(self.cfg)

  File "C:\Users\Marie\anaconda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 188, in read_config

    raise FileNotFoundError(

FileNotFoundError: Config file is not found. Please make sure that the file exists and/or that you passed the path of the config file correctly!
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by KonradDanielewski** [comment]
Have you tried with other videos? And if so, have you tried with other extensions? If it works with other videos - the ones you tried to make project with are probably corrupted. If it works on other extensions it's most likely a codec problem and you should reinstall ffmpeg and opencv.

**Comment by jeylau** [comment]
@AymericFerreira, could you also please try by moving your video to the same disk "C:\\"? I wonder if the error has something to do with the path resolution here https://github.com/DeepLabCut/DeepLabCut/blob/a48f1f2adbc4112adf8a405f97605f18fe026944/deeplabcut/create_project/new.py#L181

**Comment by AymericFerreira** [comment]
> @AymericFerreira, could you also please try by moving your video to the same disk "C:\"? I wonder if the error has something to do with the path resolution here
> 
> https://github.com/DeepLabCut/DeepLabCut/blob/a48f1f2adbc4112adf8a405f97605f18fe026944/deeplabcut/create_project/new.py#L181

Thank you for your reply but it didn't help. 
It looks to be a problem of OpenCV so I suppose it could be close. However I didn't manage to solve the issue yet.

**Comment by MMathisLab** [comment]
easiest way forward would be to simply recode the video with ffmpeg, and then try again (sometimes openCV is picky)

**Comment by dianavw3** [comment]
> easiest way forward would be to simply recode the video with ffmpeg, and then try again (sometimes openCV is picky)

Hi, did this work? Because I have the same issue and nothing is changing when I recode the video...
