### ISSUE TITLE
`Failed to launch the DLC GUI. Used args: "-e DISPLAY=unix:1 ...`

### ISSUE THREAD

**Issue by crsleeth** [DeepLabCut/DeepLabCut#1618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Fresh install of Ubuntu, after Nvidia installs, deeplabcut-docker gui and deeplabcut_docker.sh fail to launch.

### Operating System

Ubuntu 20.04.3 virtualized

### DeepLabCut version

Docker, latest

### DeepLabCut mode

single animal

### Device type

Virtualized CPU, passed through GPU Tesla M40 24 GB

### Steps To Reproduce

1. Install Ubuntu 20.04.3 and apply updates
2. Install Nvidia driver (.run file), CUDA 11.5 (online), libcudnn8
3. Install Docker and pip
4. pip install deeplabcut-docker
5. deeplabcut-docker.sh results in error: FileNotFoundError
6. deeplabcut-docker gui results in error (on both X11 forwarding and local display): Failed to launch the DLC GUI

### Relevant log output

```shell
deeplabcut-docker.sh FileNotFoundError:

                    .--,       .--,
                    ( (  \.---./  ) )
                     '.__/o   o\__.'
                       `{=  ^  =}´
                         >  u  <
 ____________________.""`-------`"".______________________  
\   ___                   __         __   _____       __  /
/  / _ \ ___  ___  ___   / /  ___ _ / /  / ___/__ __ / /_ \
\ / // // -_)/ -_)/ _ \ / /__/ _ `// _ \/ /__ / // // __/ /
//____/ \__/ \__// .__//____/\_,_//_.__/\___/ \_,_/ \__/  \
\_________________________________________________________/
                       ___)( )(___ `-.___. 
                      (((__) (__)))      ~`

Welcome to DeepLabCut docker!

Traceback (most recent call last):
  File "./deeplabcut-docker", line 8, in <module>
    sys.exit(main())
  File "/home/ryan/.local/lib/python3.8/site-packages/deeplabcut_docker.py", line 71, in main
    pty.spawn(argv)
  File "/usr/lib/python3.8/pty.py", line 158, in spawn
    os.execlp(argv[0], *argv)
  File "/usr/lib/python3.8/os.py", line 551, in execlp
    execvp(file, args)
  File "/usr/lib/python3.8/os.py", line 568, in execvp
    _execvpe(file, args)
  File "/usr/lib/python3.8/os.py", line 610, in _execvpe
    raise last_exc
  File "/usr/lib/python3.8/os.py", line 601, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
Container stopped.

####################
deeplabcut-docker gui Failed to launch the DLC GUI error:

latest-gui: Pulling from deeplabcut/deeplabcut
Digest: sha256:3f08a9e7ee3b0d9ab9905cb13114363c70a012d656b5662b1dd888d9cbce43ad
Status: Image is up to date for deeplabcut/deeplabcut:latest-gui
docker.io/deeplabcut/deeplabcut:latest-gui
[2021-12-16T23:50:26-0500]: Configuring a local container for user ryan (1000) in group ryan (1000)
sha256:17f5031b8e2b36bb4188129fc3a5a875c6a2b35a51223c3d0a28ba15ab354a45
[2021-12-16T23:50:27-0500]: Build succeeded
[2021-12-16T23:50:27-0500]: Using Linux config
[2021-12-16T23:50:33-0500]: Failed to launch the DLC GUI. Used args: "-e DISPLAY=unix:1 -v /tmp/.X11-unix:/tmp/.X11-unix -v :/home/developer/.Xauthority -v /home/ryan/.local/bin:/app -w /app "
```

### Anything else?

1. Nvidia 470.82.01 driver: https://us.download.nvidia.com/tesla/470.82.01/NVIDIA-Linux-x86_64-470.82.01.run

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.29.05    Driver Version: 495.29.05    CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla M40 24GB      On   | 00000000:00:10.0 Off |                    0 |
| N/A   31C    P8    16W / 250W |      8MiB / 22945MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       759      G   /usr/lib/xorg/Xorg                  3MiB |
|    0   N/A  N/A      3214      G   /usr/lib/xorg/Xorg                  3MiB |
+-----------------------------------------------------------------------------+
```

2. CUDA 11.5 driver: https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=20.04&target_type=deb_network

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Hi thanks for the report; can you expand on what this means? 'Ubuntu 20.04.3 virtualized` can you confirm the bash terminal launches? in my hands on 20.04 and macOS it does launch, so I am wondering if this is about your installation. Note, you don't need CUDA installed outside of the docker.

**Comment by crsleeth** [comment]
Hi thanks for your reply. I'm running Ubuntu 20.04 virtualized on a hypervisor. Its just a minor note, it should not matter for software's sake. Ubuntu runs as expected, bash terminal, monitor control, etc. I also have SSH enabled and remote access via [shell.](url)

I can try it again without installing CUDA and just the Nvidia driver installed

![Screen Shot 2021-12-17 at 11 24 08 AM](https://user-images.githubusercontent.com/13802587/146576060-6148e1fe-dbf2-43a0-baf0-bad130391a2e.png)
.

**Comment by MMathisLab** [comment]
here is the workflow I recommend:  
https://deeplabcut.github.io/DeepLabCut/docs/docker.html

`pip install deeplabcut-docker`


then:

`deeplabcut-docker bash -v /home/ryan:/home/ryan`

and not within ./local/bin; first "cd" to a home folder.

I.e., can you not run as ./deeplabcut_docker.sh

**Comment by crsleeth** [comment]
Hello, `deeplabcut-docker bash -v /home/ryan:/home/ryan` works and so does `.local/bin/deeplabcut-docker bash -v /home/ryan:/home/ryan` but both `deeplabcut-docker gui bash -v /home/ryan:/home/ryan` and `.local/bin/deeplabcut-docker gui bash -v /home/ryan:/home/ryan` result in the same `Failed to launch the DLC GUI` error.

I'm wondering if the issue is that the monitor doesn't have GPU acceleration.

**Comment by crsleeth** [comment]
I wouldn't expect that to matter though since the Tesla card is recognized and used for compute--especially over X11 forwarding.

**Comment by MMathisLab** [comment]
Hi @crsleeth can you launch WITHOUT GUI to try please, as I posted above ;)

**Comment by MMathisLab** [comment]
okay, great that the Docker does launch, so it's just an X11 issue; for this: 

can you try running:

`echo $DISPLAY`

`xhost + $IP`

**Comment by crsleeth** [comment]
Could you help clarify if my goal is to use the GUI version if I need to use `pip install deeplabcut-docker` or `pip install "deeplabcut-docker[gui]"`?

When I use `pip install "deeplabcut-docker[gui]"` I get the following error around building wxpython: https://pastebin.com/rEGJaX3x

The outputs for your commands are: `:1` and `access control disabled, clients can connect from any host`

**Comment by stes** [comment]
Hello @crsleeth , `pip install deeplabcut-docker` is correct, there is no extra `gui` variant of the `deeplabcut-docker`  package ─ it is simply a helper script to pull and start the images.

The outputs you got look correct. Could you check whether the following sequence can be reproduced on your machine (assuming you previously installed the `deeplabcut-docker` package):

```
$ xhost + 
access control disabled, clients can connect from any host
$ deeplabcut-docker gui

Welcome to DeepLabCut docker!

latest-gui: Pulling from deeplabcut/deeplabcut
Digest: sha256:3f08a9e7ee3b0d9ab9905cb13114363c70a012d656b5662b1dd888d9cbce43ad
Status: Image is up to date for deeplabcut/deeplabcut:latest-gui
docker.io/deeplabcut/deeplabcut:latest-gui
[2021-12-18T02:04:27+0100]: Configuring a local container for user stes (1000) in group stes (1000)
sha256:266cf94a1abe1c4c25b750bb8ac1bd867527b3a8aef4d66f61a6262aedc34249
[2021-12-18T02:04:27+0100]: Build succeeded
[2021-12-18T02:04:27+0100]: Using Linux config
2021-12-18 01:04:28.201335: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Starting GUI...
```

If not, could you please provide the full error messages you get by running these commands?

**Comment by crsleeth** [comment]
This is the full error message: [pastebin.com/W7JYLKAr](https://pastebin.com/W7JYLKAr)

I also get an Ubuntu error when I run that command with `gnome-shell` so I think it may be incompatible with my virtualized setup.

To test this I installed Ubuntu on the bare metal instead of virtualized through Debian/Proxmox (with the Tesla M40 passed through) and am able to run DLC without issue like one would expect.

I'd be interested to know if any other users are using DLC with GPUs in virtualized server setups instead of just workstations. And if anyone is using Tesla cards vs. GTX/RTX cards.

**Comment by dradri** [comment]
Hello, The above suggestions did not work for me to be able to launch the gui. 


> (DLC) leboeufa@biolpc182:~$ echo $DISPLAY
> :1
> (DLC) leboeufa@biolpc182:~$ xhost + $IP
> access control disabled, clients can connect from any host
> (DLC) leboeufa@biolpc182:~$ deeplabcut-docker gui
> 
>                     .--,       .--,
>                     ( (  \.---./  ) )
>                      '.__/o   o\__.'
>                        `{=  ^  =}´
>                          >  u  <
>  ____________________.""`-------`"".______________________  
> \   ___                   __         __   _____       __  /
> /  / _ \ ___  ___  ___   / /  ___ _ / /  / ___/__ __ / /_ \
> \ / // // -_)/ -_)/ _ \ / /__/ _ `// _ \/ /__ / // // __/ /
> //____/ \__/ \__// .__//____/\_,_//_.__/\___/ \_,_/ \__/  \
> \_________________________________________________________/
>                        ___)( )(___ `-.___. 
>                       (((__) (__)))      ~`
> 
> Welcome to DeepLabCut docker!
> 
> latest-gui: Pulling from deeplabcut/deeplabcut
> Digest: sha256:3f08a9e7ee3b0d9ab9905cb13114363c70a012d656b5662b1dd888d9cbce43ad
> Status: Image is up to date for deeplabcut/deeplabcut:latest-gui
> docker.io/deeplabcut/deeplabcut:latest-gui
> [2022-02-21T14:30:56+0100]: Configuring a local container for user leboeufa (1003) in group dev (1006)
> sha256:661de5c97732abab7970b829a0e8020988aae59fedaa36112601231b49f1e10e
> [2022-02-21T14:30:56+0100]: Build succeeded
> [2022-02-21T14:30:56+0100]: Using Linux config
> 2022-02-21 13:30:57.571088: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
>     return _get_module_details(pkg_main_name, error)
>   File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
>     __import__(pkg_name)
>   File "/usr/local/lib/python3.8/dist-packages/deeplabcut/__init__.py", line 27, in <module>
>     from deeplabcut import generate_training_dataset
>   File "/usr/local/lib/python3.8/dist-packages/deeplabcut/generate_training_dataset/__init__.py", line 12, in <module>
>     from deeplabcut.generate_training_dataset.trainingsetmanipulation import *
>   File "/usr/local/lib/python3.8/dist-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 23, in <module>
>     from deeplabcut.pose_estimation_tensorflow import training
>   File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/__init__.py", line 12, in <module>
>     from deeplabcut.pose_estimation_tensorflow.datasets import *
>   File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/datasets/__init__.py", line 11, in <module>
>     from .pose_deterministic import DeterministicPoseDataset
>   File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/datasets/pose_deterministic.py", line 19, in <module>
>     from deeplabcut.utils.auxfun_videos import imread, imresize
>   File "/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/__init__.py", line 6, in <module>
>     from deeplabcut.utils.make_labeled_video import *
>   File "/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/make_labeled_video.py", line 26, in <module>
>     import matplotlib.pyplot as plt
>   File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 2500, in <module>
>     switch_backend(rcParams["backend"])
>   File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 285, in switch_backend
>     raise ImportError(
> ImportError: Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'headless' is currently running
> [2022-02-21T14:30:59+0100]: Failed to launch the DLC GUI. Used args: "-e DISPLAY=unix:1 -v /tmp/.X11-unix:/tmp/.X11-unix -v /run/user/1003/gdm/Xauthority:/home/developer/.Xauthority -v /home/leboeufa:/app -w /app "
> Container stopped.



When I ran the above recommendation, I succeed but no gui is launched:

> deeplabcut-docker bash -v /home/leboeufa:/home/leboeufa
> 
>                     .--,       .--,
>                     ( (  \.---./  ) )
>                      '.__/o   o\__.'
>                        `{=  ^  =}´
>                          >  u  <
>  ____________________.""`-------`"".______________________  
> \   ___                   __         __   _____       __  /
> /  / _ \ ___  ___  ___   / /  ___ _ / /  / ___/__ __ / /_ \
> \ / // // -_)/ -_)/ _ \ / /__/ _ `// _ \/ /__ / // // __/ /
> //____/ \__/ \__// .__//____/\_,_//_.__/\___/ \_,_/ \__/  \
> \_________________________________________________________/
>                        ___)( )(___ `-.___. 
>                       (((__) (__)))      ~`
> 
> Welcome to DeepLabCut docker!
> 
> latest-core: Pulling from deeplabcut/deeplabcut
> Digest: sha256:002606843336725b795d1cf48a376e4a455e0dcf6effc9003f1f5d1ebc3df19c
> Status: Image is up to date for deeplabcut/deeplabcut:latest-core
> docker.io/deeplabcut/deeplabcut:latest-core
> [2022-02-21T14:25:27+0100]: Configuring a local container for user leboeufa (1003) in group dev (1006)
> sha256:6a9cfc0efda317d162e5778bf85541e895f9b1b167a986ec1d047aa7b55b9bd3
> [2022-02-21T14:25:27+0100]: Build succeeded
>

**Comment by dradri** [comment]
Through the Jupyter notebook, the same problem:

> import deeplabcut

> 
> 2022-02-21 13:50:57.951524: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
> 
> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> /tmp/ipykernel_11/419757306.py in <module>
> ----> 1 import deeplabcut
> 
> /usr/local/lib/python3.8/dist-packages/deeplabcut/__init__.py in <module>
>      25 
>      26     mpl.use("WxAgg")
> ---> 27     from deeplabcut import generate_training_dataset
>      28     from deeplabcut import refine_training_dataset
>      29 
> 
> /usr/local/lib/python3.8/dist-packages/deeplabcut/generate_training_dataset/__init__.py in <module>
>      10 
>      11 from deeplabcut.generate_training_dataset.frame_extraction import *
> ---> 12 from deeplabcut.generate_training_dataset.trainingsetmanipulation import *
>      13 from deeplabcut.generate_training_dataset.multiple_individuals_trainingsetmanipulation import *
> 
> /usr/local/lib/python3.8/dist-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py in <module>
>      21 import yaml
>      22 
> ---> 23 from deeplabcut.pose_estimation_tensorflow import training
>      24 from deeplabcut.utils import (
>      25     auxiliaryfunctions,
> 
> /usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/__init__.py in <module>
>      10 
>      11 from deeplabcut.pose_estimation_tensorflow.config import *
> ---> 12 from deeplabcut.pose_estimation_tensorflow.datasets import *
>      13 from deeplabcut.pose_estimation_tensorflow.default_config import *
>      14 from deeplabcut.pose_estimation_tensorflow.core.evaluate import *
> 
> /usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/datasets/__init__.py in <module>
>       9 """
>      10 from .factory import PoseDatasetFactory
> ---> 11 from .pose_deterministic import DeterministicPoseDataset
>      12 from .pose_scalecrop import ScalecropPoseDataset
>      13 from .pose_imgaug import ImgaugPoseDataset
> 
> /usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/datasets/pose_deterministic.py in <module>
>      17 import os
>      18 import scipy.io as sio
> ---> 19 from deeplabcut.utils.auxfun_videos import imread, imresize
>      20 from .factory import PoseDatasetFactory
>      21 from .pose_base import BasePoseDataset
> 
> /usr/local/lib/python3.8/dist-packages/deeplabcut/utils/__init__.py in <module>
>       4 from deeplabcut.utils.conversioncode import *
>       5 from deeplabcut.utils.frameselectiontools import *
> ----> 6 from deeplabcut.utils.make_labeled_video import *
>       7 from deeplabcut.utils.plotting import *
>       8 from deeplabcut.utils.video_processor import *
> 
> /usr/local/lib/python3.8/dist-packages/deeplabcut/utils/make_labeled_video.py in <module>
>      24 
>      25 import matplotlib.colors as mcolors
> ---> 26 import matplotlib.pyplot as plt
>      27 import numpy as np
>      28 from matplotlib.animation import FFMpegWriter
> 
> /usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py in <module>
>    2498     dict.__setitem__(rcParams, "backend", rcsetup._auto_backend_sentinel)
>    2499 # Set up the backend.
> -> 2500 switch_backend(rcParams["backend"])
>    2501 
>    2502 # Just to be safe.  Interactive mode can be turned on without
> 
> /usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py in switch_backend(newbackend)
>     283         if (current_framework and required_framework
>     284                 and current_framework != required_framework):
> --> 285             raise ImportError(
>     286                 "Cannot load backend {!r} which requires the {!r} interactive "
>     287                 "framework, as {!r} is currently running".format(
> 
> ImportError: Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'headless' is currently running
>

**Comment by crsleeth** [comment]
@MMathisLab I experimented with setting up deeplabcut-docker gui on Ubuntu 20.04 with the goal of having multiple concurrent, simultaneous, graphically accelerated, remote sessions but was unsuccessful. Even with multiple graphically accelerated VNC sessions (confirmed by running [Unigine Heaven](https://benchmark.unigine.com/heaven) and possible by utilizing [VirtualGL](https://virtualgl.org/)) I would still get the `ImportError: Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'headless' is currently running` error.

Non graphically accelerated sessions also didn't work, obviously. I tested many including NoMachine, ThinLinc, and XRDP.

It seems that the way deeplabcut-docker gui is setup requires local console :0. This can be accessed remotely via some session software, but multiple concurrent sessions never worked.

So unless someone more technical than me can figure it out it seems the only way of splitting up a GPU's (in my case a Tesla M40 24 GB) resources for deeplabcut-docker gui is with GPU partitioning via a hypervisor like VMware + Nvidia GRID or Windows Server Hyper-V + RemoteFX/GPU-P then creating multiple virtual machines each with their own slice of the GPU so that they can each present a localhost :0 console for deeplabcut-docker gui.

**Comment by crsleeth** [comment]
I tried deeplabcut-docker gui on Windows via Docker Desktop and got the same error:

```
2022-03-04 08:09:05.762353: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/__init__.py", line 27, in <module>
    from deeplabcut import generate_training_dataset
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/generate_training_dataset/__init__.py", line 12, in <module>
    from deeplabcut.generate_training_dataset.trainingsetmanipulation import *
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 23, in <module>
    from deeplabcut.pose_estimation_tensorflow import training
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/__init__.py", line 12, in <module>
    from deeplabcut.pose_estimation_tensorflow.datasets import *
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/datasets/__init__.py", line 11, in <module>
    from .pose_deterministic import DeterministicPoseDataset
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/datasets/pose_deterministic.py", line 19, in <module>
    from deeplabcut.utils.auxfun_videos import imread, imresize
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/__init__.py", line 6, in <module>
    from deeplabcut.utils.make_labeled_video import *
  File "/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/make_labeled_video.py", line 26, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 2500, in <module>
    switch_backend(rcParams["backend"])
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 285, in switch_backend
    raise ImportError(
ImportError: Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'headless' is currently running
```
