### ISSUE TITLE
Undistortion error during triangulation

### ISSUE THREAD

**Issue by guatomallin** [DeepLabCut/DeepLabCut#1624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Undistortion fails after 2D analysis of videos during triangulation steps. 

### Operating System

Windows 10 

### DeepLabCut version

2.0.7

### DeepLabCut mode

3d

### Device type

gpu

### Relevant log output

```shell
Undistorting...
0it [00:00, ?it/s]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
c:\users\lab\.conda\envs\dlc-windowsgpu\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2521             try:
-> 2522                 return self._engine.get_loc(key)
   2523             except KeyError:

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'DeepCut_resnet50_r&d_cam3_2DJul19shuffle1_200000'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-4-37f1dc5997b0> in <module>()
----> 1 deeplabcut.triangulate(r'C:\Users\lab\CP_DLC_working_directory\RD_2CAM-CP-2021-12-26-3d\config.yaml',r"C:\Users\lab\Desktop\Video Processing\new videos",videotype=".mp4", filterpredictions=True)

c:\users\lab\.conda\envs\dlc-windowsgpu\lib\site-packages\deeplabcut\pose_estimation_3d\triangulation.py in triangulate(config, video_path, videotype, filterpredictions, filtertype, gputouse, destfolder, save_as_csv)
    136             #undistort points for this pair
    137             print("Undistorting...")
--> 138             dataFrame_camera1_undistort,dataFrame_camera2_undistort,stereomatrix,path_stereo_file = undistort_points(config,dataname,str(cam_names[0]+'-'+cam_names[1]),destfolder)
    139             if len(dataFrame_camera1_undistort) != len(dataFrame_camera2_undistort):
    140                 raise Exception("The number of frames do not match in the two videos. Please make sure that your videos have same number of frames and then retry!")

c:\users\lab\.conda\envs\dlc-windowsgpu\lib\site-packages\deeplabcut\pose_estimation_3d\triangulation.py in undistort_points(config, dataframe, camera_pair, destfolder)
    268
    269             # Undistorting the points from cam2 camera
--> 270             points_cam2 = np.array([dataframe_cam2[scorer_cam2][bp]['x'].values[:],dataframe_cam2[scorer_cam2][bp]['y'].values[:]])
    271             points_cam2 = points_cam2.T
    272             points_cam2 = np.expand_dims(points_cam2, axis=1)

c:\users\lab\.conda\envs\dlc-windowsgpu\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   2135             return self._getitem_frame(key)
   2136         elif is_mi_columns:
-> 2137             return self._getitem_multilevel(key)
   2138         else:
   2139             return self._getitem_column(key)

c:\users\lab\.conda\envs\dlc-windowsgpu\lib\site-packages\pandas\core\frame.py in _getitem_multilevel(self, key)
   2179
   2180     def _getitem_multilevel(self, key):
-> 2181         loc = self.columns.get_loc(key)
   2182         if isinstance(loc, (slice, Series, np.ndarray, Index)):
   2183             new_columns = self.columns[loc]

c:\users\lab\.conda\envs\dlc-windowsgpu\lib\site-packages\pandas\core\indexes\multi.py in get_loc(self, key, method)
   2069
   2070         if not isinstance(key, tuple):
-> 2071             loc = self._get_level_indexer(key, level=0)
   2072             return _maybe_to_slice(loc)
   2073

c:\users\lab\.conda\envs\dlc-windowsgpu\lib\site-packages\pandas\core\indexes\multi.py in _get_level_indexer(self, key, level, indexer)
   2359         else:
   2360
-> 2361             loc = level_index.get_loc(key)
   2362             if isinstance(loc, slice):
   2363                 return loc

c:\users\lab\.conda\envs\dlc-windowsgpu\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2522                 return self._engine.get_loc(key)
   2523             except KeyError:
-> 2524                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2525
   2526         indexer = self.get_indexer([key], method=method, tolerance=tolerance)

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'DeepCut_resnet50_r&d_cam3_2DJul19shuffle1_200000'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
`KeyError: 'DeepCut_resnet50_r&d_cam3_2DJul19shuffle1_200000'` <-- did you see why this error occurs? You are also using a very, very old version, I suggest upgrading!

**Comment by guatomallin** [comment]
Hello! 

This is the first time I am using the triangulation method for 3d DLC. I actually have no idea why that is happening. I've checked that the two videos have the same number of matched frames as well.

**Comment by MMathisLab** [comment]
I believe older versions didn't support special characters in the name, as we have to parse this; i.e. "'DeepCut_resnet50_r&d_cam3_2DJul19shuffle1_200000'" --> can you try upgrading, i.e. in your environment run `pip install 'deeplabcut[gui]' ? (as 2.0.7 is > 2 years old :).

**Comment by guatomallin** [comment]
Hello, 

I've tried upgrading deeplabcut and installing the deeplabcut[gui] version in my cloned environment without success. I received the following error. Thanks a ton for your help!

  Building wheel for psutil (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\lab\.conda\envs\dlc-windowsgpu\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\lab\\AppData\\Local\\Temp\\pip-install-v6uxk3s1\\psutil_552469b4ef9b4e7b95479d8d1c9b370e\\setup.py'"'"'; __file__='"'"'C:\\Users\\lab\\AppData\\Local\\Temp\\pip-install-v6uxk3s1\\psutil_552469b4ef9b4e7b95479d8d1c9b370e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\krublab\AppData\Local\Temp\pip-wheel-84hu3i1h'
       cwd: C:\Users\lab\AppData\Local\Temp\pip-install-v6uxk3s1\psutil_552469b4ef9b4e7b95479d8d1c9b370e\
  Complete output (46 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\psutil
  copying psutil\_common.py -> build\lib.win-amd64-3.6\psutil
  copying psutil\_compat.py -> build\lib.win-amd64-3.6\psutil
  copying psutil\_psaix.py -> build\lib.win-amd64-3.6\psutil
  copying psutil\_psbsd.py -> build\lib.win-amd64-3.6\psutil
  copying psutil\_pslinux.py -> build\lib.win-amd64-3.6\psutil
  copying psutil\_psosx.py -> build\lib.win-amd64-3.6\psutil
  copying psutil\_psposix.py -> build\lib.win-amd64-3.6\psutil
  copying psutil\_pssunos.py -> build\lib.win-amd64-3.6\psutil
  copying psutil\_pswindows.py -> build\lib.win-amd64-3.6\psutil
  copying psutil\__init__.py -> build\lib.win-amd64-3.6\psutil
  creating build\lib.win-amd64-3.6\psutil\tests
  copying psutil\tests\runner.py -> build\lib.win-amd64-3.6\psutil\tests
  copying psutil\tests\test_aix.py -> build\lib.win-amd64-3.6\psutil\tests
  copying psutil\tests\test_bsd.py -> build\lib.win-amd64-3.6\psutil\tests
  copying psutil\tests\test_connections.py -> build\lib.win-amd64-3.6\psutil\tests
  copying psutil\tests\test_contracts.py -> build\lib.win-amd64-3.6\psutil\tests
  copying psutil\tests\test_linux.py -> build\lib.win-amd64-3.6\psutil\tests
  copying psutil\tests\test_memleaks.py -> build\lib.win-amd64-3.6\psutil\tests
  copying psutil\tests\test_misc.py -> build\lib.win-amd64-3.6\psutil\tests
  copying psutil\tests\test_osx.py -> build\lib.win-amd64-3.6\psutil\tests
  copying psutil\tests\test_posix.py -> build\lib.win-amd64-3.6\psutil\tests
  copying psutil\tests\test_process.py -> build\lib.win-amd64-3.6\psutil\tests
  copying psutil\tests\test_sunos.py -> build\lib.win-amd64-3.6\psutil\tests
  copying psutil\tests\test_system.py -> build\lib.win-amd64-3.6\psutil\tests
  copying psutil\tests\test_testutils.py -> build\lib.win-amd64-3.6\psutil\tests
  copying psutil\tests\test_unicode.py -> build\lib.win-amd64-3.6\psutil\tests
  copying psutil\tests\test_windows.py -> build\lib.win-amd64-3.6\psutil\tests
  copying psutil\tests\__init__.py -> build\lib.win-amd64-3.6\psutil\tests
  copying psutil\tests\__main__.py -> build\lib.win-amd64-3.6\psutil\tests
  running build_ext
  building 'psutil._psutil_windows' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\psutil
  creating build\temp.win-amd64-3.6\Release\psutil\arch
  creating build\temp.win-amd64-3.6\Release\psutil\arch\windows
  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=590 -DPSUTIL_WINDOWS=1 -D_WIN32_WINNT=0x01000 -D_AVAIL_WINVER_=0x01000 -D_CRT_SECURE_NO_WARNINGS -DPSAPI_VERSION=1 -Ic:\users\lab\.conda\envs\dlc-windowsgpu\include -Ic:\users\lab\.conda\envs\dlc-windowsgpu\include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include" /Tcpsutil/_psutil_common.c /Fobuild\temp.win-amd64-3.6\Release\psutil/_psutil_common.obj
  _psutil_common.c
  c:\users\krublab\.conda\envs\dlc-windowsgpu\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
  error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.30.30705\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for psutil

**Comment by guatomallin** [comment]
I should say that I tried upgrading to the latest version DLC and 'deeplabcut[gui]'==2.2.0.3. . I used your suggested command without specifying the version of dlc[gui] with success, though I was unable to start it in the terminal.

**Comment by aristotelis-economides** [comment]
Hey @guatomallin, have you managed to install the most recent version of DeepLabCut and reproduce the undistortion error?

**Comment by guatomallin** [comment]
Hello, 

Sorry for the long delay. We ordered two new and up-to-date computers and made a fresh install of the 2.2.0.3 by cloning. The 3D are working well fine!

**Comment by guatomallin** [comment]
Hello again, 

I spoke too soon. I am analyzing new videos with this fresh install and I want to generate labeled videos. Here is the error I received. This is not a multi animal project. Though I should mention that I am using the up-to-date dlc with old projects. Will report back if I figure it out. 

KeyError                                  Traceback (most recent call last)
Input In [5], in <cell line: 1>()
----> 1 deeplabcut.create_labeled_video(r'D:\project_deeplabcut\r&d_cam2_2D-CP-2021-09-14\config.yaml',[r'D:\project_deeplabcut\r&d_cam2_2D-CP-2021-09-14\videos\undistorted_singleedit_14_behavior_shape4_cam2_11090_blind_122421.mp4.avi'])

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\make_labeled_video.py:472, in create_labeled_video(config, videos, videotype, shuffle, trainingsetindex, filtered, fastmode, save_frames, keypoints_only, Frames2plot, displayedbodyparts, displayedindividuals, codec, outputframerate, destfolder, draw_skeleton, trailpoints, displaycropped, color_by, modelprefix, track_method)
    469     fastmode = False  # otherwise one cannot save frames
    470     keypoints_only = False
--> 472 bodyparts = auxiliaryfunctions.IntersectionofBodyPartsandOnesGivenbyUser(
    473     cfg, displayedbodyparts
    474 )
    475 individuals = auxfun_multianimal.IntersectionofIndividualsandOnesGivenbyUser(
    476     cfg, displayedindividuals
    477 )
    478 if draw_skeleton:

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py:511, in IntersectionofBodyPartsandOnesGivenbyUser(cfg, comparisonbodyparts)
    509 """ Returns all body parts when comparisonbodyparts=='all', otherwise all bpts that are in the intersection of comparisonbodyparts and the actual bodyparts """
    510 # if "MULTI!" in allbpts:
--> 511 if cfg["multianimalproject"]:
    512     allbpts = cfg["multianimalbodyparts"] + cfg["uniquebodyparts"]
    513 else:

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\ruamel\yaml\comments.py:927, in CommentedMap.__getitem__(self, key)
    924 def __getitem__(self, key):
    925     # type: (Any) -> Any
    926     try:
--> 927         return ordereddict.__getitem__(self, key)
    928     except KeyError:
    929         for merged in getattr(self, merge_attrib, []):

KeyError: 'multianimalproject'


Thank you

**Comment by jeylau** [comment]
Hello @guatomallin, I'll close the issue as #1690 will be live very soon with the next DeepLabCut release ☺️
