### ISSUE TITLE
`ValueError: Unrecognized track_method=`

### ISSUE THREAD

**Issue by linyangju1994** [DeepLabCut/DeepLabCut#1626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi DLC team, 

I am using the GUI DLC (single animal model) to track a single fly and its interaction with a food dot (So I label the fly and the food with one dot respectively).  The training went smoothly and the evaluation result is OK.

When I try to use the analyze videos to first analyze the video I used  to train, the processing step itself seems normal (processed a 10min video for ~3min till 100%) and no error is reported, but there is no any output file is generated after analyzing.  So it will show "no unfiltered data file found" and further errors  if I clicked "yes" for downstream options like "want to plot the trajectory" in the "analyze videos" step.  I did blindly did a searching to see whether the output file is somewhere else but not found. 

I found a previous comment that re-encoding the video may help if there is frame corrupted (I did see some sign since when deeplabcut was automatically picking 100 frames to label, only 98 were exported and they said 1 frame cannot be found), so I re-encoding the video by "ffmpeg -i "flyvideo.mp4" -c:v libx264 -crf 23 -c:a copy "flyvideo2.mp4"", but it didn't help. 

Could you help me look through this?

Thanks and happy new year. 

### Operating System

Windows 10

### DeepLabCut version

>>> import deeplabcut
>>> deeplabcut.__version__
'2.2.0.3'

### DeepLabCut mode

single animal

### Device type

RTX 2080 Ti

### Steps To Reproduce

On the GUI "analyze videos"

select the video I used for training (either original or re-encoded)

specify the video type: mp4 and clicked yes for "save csv", "want plots to pop up" and "want to plot the trajectory" (if I don't click yes for them, there won't be error but still no output file is generated")

### Relevant log output

```shell
Use the function 'analyze_video' to make predictions on new videos.
Otherwise, consider adding more labeled-data and retraining the network (see DeepLabCut workflow Fig 2, Nath 2019)
Config:
{'all_joints': [[0], [1]],
 'all_joints_names': ['bodypart1', 'food'],
 'batch_size': 1,
 'crop_pad': 0,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_flytrack2Dec28\\flytrack2_LJ95shuffle1.mat',
 'dataset_type': 'imgaug',
 'deterministic': False,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'E:\\anaconda3\\envs\\deeplabcut\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 1.0,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'mean_pixel': [123.68, 116.779, 103.939],
 'mirror': False,
 'net_type': 'resnet_50',
 'num_joints': 2,
 'optimizer': 'sgd',
 'pairwise_huber_loss': True,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'regularize': False,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'E:\\flytrack2-LJ-2021-12-28\\dlc-models\\iteration-0\\flytrack2Dec28-trainset95shuffle1\\test\\snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Using snapshot-1030000 for model E:\flytrack2-LJ-2021-12-28\dlc-models\iteration-0\flytrack2Dec28-trainset95shuffle1
2021-12-29 08:39:03.338611: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8962 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5
Starting to analyze %  E:\flytrack2-LJ-2021-12-28\videos\flyvideo.mp4
Loading  E:\flytrack2-LJ-2021-12-28\videos\flyvideo.mp4
Duration of video [s]:  600.0 , recorded with  29.97 fps!
Overall # of frames:  17982  found with (before cropping) frame dimensions:  416 416
Starting to extract posture
18079it [01:35, 188.44it/s]
The videos are analyzed. Now your research can truly start!
 You can create labeled videos with 'create_labeled_video'
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.

Loading  E:\flytrack2-LJ-2021-12-28\videos\flyvideo2.mp4 and data.
No unfiltered data file found in E:\flytrack2-LJ-2021-12-28\videos for video flyvideo2 and scorer DLC_resnet50_flytrack2Dec28shuffle1_1030000.
Traceback (most recent call last):
  File "E:\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\utils\plotting.py", line 257, in plot_trajectories
    df, _, _, suffix = auxiliaryfunctions.load_analyzed_data(
  File "E:\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 768, in load_analyzed_data
    filepath, scorer, suffix = find_analyzed_data(
  File "E:\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 754, in find_analyzed_data
    raise FileNotFoundError(msg)
FileNotFoundError: No unfiltered data file found in E:\flytrack2-LJ-2021-12-28\videos for video flyvideo2 and scorer DLC_resnet50_flytrack2Dec28shuffle1_1030000.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\gui\analyze_videos.py", line 529, in analyze_videos
    deeplabcut.plot_trajectories(
  File "E:\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\utils\plotting.py", line 291, in plot_trajectories
    _ = auxiliaryfunctions.load_detection_data(
  File "E:\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 785, in load_detection_data
    raise ValueError(f"Unrecognized track_method={track_method}")
ValueError: Unrecognized track_method=
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
`The videos are analyzed.`

did you check the folder and see the h5 there? 

Then, if looks like you want to use the filtered data to create a video, but it's not filtered...
...
`FileNotFoundError: No unfiltered data file found in E:\flytrack2-LJ-2021-12-28\videos for video flyvideo2 and scorer DLC_resnet50_flytrack2Dec28shuffle1_1030000.`

check your config.yaml; what is set in track_method? if single animal project, should be "None"

`ValueError: Unrecognized track_method=`

**Comment by linyangju1994** [comment]
> 

Hi DLC team,

In addition to the original video, there is "no any file" newly generated in the video folder after "the video is analyzed", either filtered/unfiltered or any output. that is the most strange part...

There is no track_method commended in the default config.yaml. I added one line track_method: None but the error is still there.

Thanks

**Comment by linyangju1994** [comment]
Hi DLC team,

I analyzed another video and everything worked smoothly. It looks like it is just because the original video is corrupted. 

Thanks
