### ISSUE TITLE
Empty tracklet for a single-animal single-point tracking using maDLC

### ISSUE THREAD

**Issue by linyangju1994** [DeepLabCut/DeepLabCut#1627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Dear DLC team,

I have a different issue following #1626 for single point  tracking. 

I also used maDLC to track a single animal (fly) and its interaction with food. Since v2.2.0.3  starts to support single point tracking, I also just labeled fly as "individual 1" with only 1 body part and the food dot as a stable object. 

After analyzing the video (tracker method: box), I first checked the video generated for detection before building tracklet. It did a perfect job which can stably track the fly dot and food dot (fly and food are always present in the video). However, after "convert to tracklets" and "create tracks", I saw following error saying that "tracklets are empty". 

I have seen this error before when I was analyzing other videos which have multiple animals with multiple bodyparts, but that seems only happen when there are no (or very few) animals present in the video. 

I am just wondering if there is any change of parameter may help this single-point tracking to build the tracklet and get the (x,y) csv file. 

Thanks and happy new year.  

### Operating System

Windows 10

### DeepLabCut version

2.2.0.3

### DeepLabCut mode

multi animal

### Device type

RTX 2080Ti

### Steps To Reproduce

In analyze video (GUI), I selected the video I used for training to analyze, and specify the videotype and tracker method (box), "No" for "calibrate animal assembly and identity only". 

The inference_config is default:
boundingboxslack: 0
iou_threshold: 0.6
max_age: 1
method: m1
min_hits: 1
minimalnumberofconnections: 1
pafthreshold: 0.1
pcutoff: 0.1
topktoretain: 2
variant: 0
withid: false

In "refine tracklets", the specified shuffle and trainingset index is default as "1" and "0" respectively.  

### Relevant log output

```shell
Starting to analyze %  E:\flytrack-LJ-2021-12-27\videos\flyvideo.mp4
Loading  E:\flytrack-LJ-2021-12-27\videos\flyvideo.mp4
Duration of video [s]:  600.0 , recorded with  29.97 fps!
Overall # of frames:  17982  found with (before cropping) frame dimensions:  416 416
Starting to extract posture from the video(s) with batchsize: 32
17985it [01:44, 172.59it/s]
Video Analyzed. Saving results in E:\flytrack-LJ-2021-12-27\videos...
The videos are analyzed. Time to assemble animals and track 'em...
 Call 'create_video_with_all_detections' to check multi-animal detection quality before tracking.
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
Using snapshot-200000 for model E:\flytrack-LJ-2021-12-27\dlc-models\iteration-0\flytrackDec27-trainset95shuffle1
Processing...  E:\flytrack-LJ-2021-12-27\videos\flyvideo.mp4
Analyzing E:\flytrack-LJ-2021-12-27\videos\flyvideoDLC_dlcrnetms5_flytrackDec27shuffle1_200000.h5
17982it [00:01, 16617.81it/s]
0it [00:00, ?it/s]E:\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\pose_estimation_tensorflow\lib\trackingutils.py:78: RuntimeWarning: invalid value encountered in double_scalars
  r = w / float(h)
17982it [00:05, 3199.98it/s]
The tracklets were created (i.e., under the hood deeplabcut.convert_detections2tracklets was run). Now you can 'refine_tracklets' in the GUI, or run 'deeplabcut.stitch_tracklets'.
Processing...  E:\flytrack-LJ-2021-12-27\videos\flyvideo.mp4
Traceback (most recent call last):
  File "E:\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\gui\refine_tracklets.py", line 317, in create_tracks
    deeplabcut.stitch_tracklets(
  File "E:\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py", line 1093, in stitch_tracklets
    stitcher = TrackletStitcher.from_pickle(
  File "E:\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py", line 515, in from_pickle
    class_ = cls.from_dict_of_dict(
  File "E:\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py", line 547, in from_dict_of_dict
    class_ = cls(
  File "E:\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py", line 475, in __init__
    raise IOError("Tracklets are empty.")
OSError: Tracklets are empty.
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
You will need to build from gituhub for the latest updates to this code, as it's not in pypi yet: https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html#how-to-use-the-latest-updates-directly-from-github

and, you can just pass `auto_track=True`, or use the new GUI update that is one-click running for single animal tracking, which is in the github code if you install as above!

also, if you only have a single animal this `topktoretain: 2` should be set to `1`

**Comment by linyangju1994** [comment]
Hi DLC team,

I actually followed [this](https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/installation.md) to created a new env after downloading the latest version from github, I checked the version in the new environment which is 2.2.0.3.

I did first try single animal tracking first but saw issue #1626 (the GUI for single-animal tracking is one-clicking), then see whether multi-animal model will work. 
I changed the topktoretain to 1 and it can successfully generate tracklet, in the meantime I found an interesting "bug" (I am not sure if this is a bug): I selected "ellipse" as tracker method in both analyze videos and refine tracklets page, but the output .h5 file is "XXX_bx" after clicking "create tracks", I manually change that to "_el" then clicking filter tracks can give me the csv file I want.

**Comment by MMathisLab** [comment]
>> I selected "ellipse" as tracker method in both analyze videos and refine tracklets page, but the output .h5 file is "XXX_bx" after clicking "create tracks", I manually change that to "_el" then clicking filter tracks can give me the csv file I want.

Intended; the ellipse tracker does not work for single animals, the box tracker is the only option - so it smartly ignores if the user inputs something else. 

Glad the setting to 1 fixed it for you
