### ISSUE TITLE
ubuntu 18.04: issue with wxPython build

### ISSUE THREAD

**Issue by Houiin** [DeepLabCut/DeepLabCut#163]
**Your Operating system and DeepLabCut version**
 Ubuntu 18.04.1 LTS, with an Anaconda3 Env, & DeepLabCut2.x  ,GTX1050 Mobile
Install tensorflow-gpu by using 'conda install tensorflow-gpu'

**Describe the problem**
When I try to import deeplabcut in ipython, it fails and I get the error message below. It seems that there are some problems with wxPyhton? And Ubuntu 16.04 LTS is not work well in my computer. Should I return to Ubuntu 16.04LTS?
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-52d2df9c7fa5> in <module>()
----> 1 import deeplabcut

/home/houiin/anaconda3/envs/deeplabcut-py36/lib/python3.6/site-packages/deeplabcut/__init__.py in <module>()
     23 else:
     24     mpl.use('TkAgg')
---> 25     from deeplabcut import generate_training_dataset
     26     from deeplabcut import refine_training_dataset
     27 

/home/houiin/anaconda3/envs/deeplabcut-py36/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/__init__.py in <module>()
     13     pass
     14 else:
---> 15     from deeplabcut.generate_training_dataset.auxfun_drag_label import *
     16     from deeplabcut.generate_training_dataset.frameselectiontools import *
     17     from deeplabcut.generate_training_dataset.labeling_toolbox import *

/home/houiin/anaconda3/envs/deeplabcut-py36/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/auxfun_drag_label.py in <module>()
     16 
     17 import numpy as np
---> 18 import wx
     19 
     20 

/home/houiin/anaconda3/envs/deeplabcut-py36/lib/python3.6/site-packages/wx/__init__.py in <module>()
     15 # Import all items from the core wxPython module so they appear in the wx
     16 # package namespace.
---> 17 from wx.core import *
     18 
     19 

/home/houiin/anaconda3/envs/deeplabcut-py36/lib/python3.6/site-packages/wx/core.py in <module>()
     10 """
     11 
---> 12 from ._core import *
     13 
     14 #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

ImportError: libpng12.so.0: cannot open shared object file: No such file or directory
```
**How to Reproduce the problem**
1. Run ipython
2. import deeplabcut

**Screenshots**
![image](https://user-images.githubusercontent.com/30932544/50696984-e4f82400-107b-11e9-9849-765a6b018735.png)

**Additional context**
Where can I get libpng12.so? And where should I put it?
Thank you!!!

**Comment by AlexEMG** [comment]
I have not tried it on Ubuntu 18 yet. Perhaps just install libpng with apt-get. https://ubuntu.pkgs.org/18.04/ubuntu-main-amd64/libpng-dev_1.6.34-1_amd64.deb.html

You could export "DLClight"=True (then wxpython is not used and GUIs are inactivated).

**Comment by MMathisLab** [comment]
If you followed the installation guide, then the wxPython is specific to 16.04: i.e. see the link...

Linux: ``pip install https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04/wxPython-4.0.3-cp36-cp36m-linux_x86_64.whl``

you'll need to grab wxPython for 18.04 ... https://wxpython.org/pages/downloads/

Other users have reported issues with Ubuntu 18 though, as TensorFlow is not supported... see https://github.com/AlexEMG/DeepLabCut/issues/120, https://github.com/AlexEMG/DeepLabCut/issues/51

**Comment by AlexEMG** [comment]
I think TensorFlow is now supported, i.e. see: https://www.tensorflow.org/install/
states: Ubuntu 16.04 or later

Same with wxPython (I believe)

**Comment by Houiin** [comment]
Thank you for your reply and help.👍❤❤❤

The problem has been solved. I will close this issue.

 I reinstalled libpng-dev and install wxPython for Ubuntu18.04. It should be noted that `wxPython-4.0.3-cp37-cp37m` not support this platform. So I use wxPython-4.0.3-cp36-cp36m and it works !

**Comment by simranvirdi** [comment]
solution:

wget http://se.archive.ubuntu.com/ubuntu/pool/main/libp/libpn/libpng12-0_1.2.54-1ubuntu1_amd64.deb
sudo dpkg -i libpng12-0_1.2.54-1ubuntu1_amd64.deb


reference: https://gist.github.com/AbstractGeek/e5c7ecf60f1d8f63b32ed527a785523c

**Comment by pfelramos** [comment]
https://anaconda.org/anaconda/wxpython 

Just another way of installing wxPython for Ubuntu 18.04 which include all needed packages. I had the same error and this solved the problem.

Linux cmd: conda install -c anaconda wxpython
