### ISSUE TITLE
question about multi-animal tracking ID problem

### ISSUE THREAD

**Issue by Jason66661010** [DeepLabCut/DeepLabCut#1631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I get the video datasets about two mice which looks the same with each other(One can distinguish them only by the order they emerged in the first ten seconds in video).
In the labeling stage, I make sure that I  labeled  the individuals correctly.
But when I create labeled videos with test datasets, the key points look fine but the ID shifted. 

Is there anything I can do to improve the performance?(Two mice can not be marked in the real life.)

### Operating System

WIN10

### DeepLabCut version

dlc 2.2.0

### DeepLabCut mode

multi animal

### Device type

gpu 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
hi @Jason66661010 we ask you please post questions on the user forum: 
https://deeplabcut.github.io/DeepLabCut/docs/intro.html#community-support-developers-help

if you label consistently, then you should train with identity=True and DLC will learn the ID. See Laure et al: https://www.biorxiv.org/content/10.1101/2021.04.30.442096v1
