### ISSUE TITLE
Colab : not recognizing labeled images after upload

### ISSUE THREAD

**Issue by tomwilson41986** [DeepLabCut/DeepLabCut#1639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have labeled images locally on my laptop via the GUI and have then migrated to Colab to train the dataset and create the model.

However after upload to Google Drive and starting to train dataset the model is not recognising the labelled images.

All images have been labelled and the Collected Data CSV and Collected Data h5 files are existing in the source folder.

### Operating System

operating system

### DeepLabCut version

dlc version 2.2.0.5

### DeepLabCut mode

single animal

### Device type

gpu

### Relevant log output

```shell
/content/drive/MyDrive/walk2-tom-2022-01-17/labeled-data/Lot 145 - Camacho (GB)  Woolstone (GB) B.F. (IRE)walk 0-59/CollectedData_tom.h5  not found (perhaps not annotated)
/content/drive/MyDrive/walk2-tom-2022-01-17/labeled-data/Lot 143 - Dutch Art (GB)  Winds of Time (IRE) B.F. (GB)walk 60-69/CollectedData_tom.h5  not found (perhaps not annotated)
/content/drive/MyDrive/walk2-tom-2022-01-17/labeled-data/Lot 143 - Muhaarar (GB)  Patience Alexander (IRE) B.C. (IRE) walk OR68/CollectedData_tom.h5  not found (perhaps not annotated)
/content/drive/MyDrive/walk2-tom-2022-01-17/labeled-data/Lot 142 - Kingman (GB)  Whirly Bird (GB) B.C. (GB)walk 70-79/CollectedData_tom.h5  not found (perhaps not annotated)
/content/drive/MyDrive/walk2-tom-2022-01-17/labeled-data/Lot 144 - Adaay (IRE)  Winifred Jo (GB) B.C. (GB) walk 70-79/CollectedData_tom.h5  not found (perhaps not annotated)
/content/drive/MyDrive/walk2-tom-2022-01-17/labeled-data/Lot 143 - Dutch Art (GB)  Winds of Time (IRE) B.F. (GB) walk 50-59/CollectedData_tom.h5  not found (perhaps not annotated)
/content/drive/MyDrive/walk2-tom-2022-01-17/labeled-data/Lot 142 - Holy Roman Emperor (IRE)  Passionforfashion (IRE) B.F. (IRE) walk OR76/CollectedData_tom.h5  not found (perhaps not annotated)
```

### Anything else?

![image](https://user-images.githubusercontent.com/95654146/149781427-4d93d950-9721-4ac9-bd2c-fb0dcd01b78e.png)
![image](https://user-images.githubusercontent.com/95654146/149781599-27951ab1-2a82-449b-8d6f-6641ae234ed0.png)
![image](https://user-images.githubusercontent.com/95654146/149781844-fef67581-7b6c-4318-b521-b90eebfde08c.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by KonradDanielewski** [comment]
It might be just Colab being lazy in syncing with Google Drive. You can try to use this to remount the drive - should sync them and allow you to move on.
```
from google.colab import drive
drive.flush_and_unmount()
```
Also, if you annotated data on a windows add `windows2linux=True` as a parameter in `create_training_dataset`.

**Comment by MMathisLab** [comment]
(I am also nervous with the "." in filename  .... )

**Comment by tomwilson41986** [comment]
Thanks Konrad. Same error i'm afraid.
![image](https://user-images.githubusercontent.com/95654146/149828239-cad5721b-93a3-49e6-b32a-c905c5594c54.png)

**Comment by tomwilson41986** [comment]
> (I am also nervous with the "." in filename .... )

Thanks. Could you explain a bit more please?

**Comment by KonradDanielewski** [comment]
Hmm, you use the lateset dlc so also windows2linux is not necessary I think - sorry didn't notice this change in the code before. 
As a rule of thumb I'd avoid using white spaces and dots in paths and filenames. Any split that is based on either of those can result in an error.

**Comment by MMathisLab** [comment]
>> As a rule of thumb I'd avoid using white spaces and dots in paths and filenames. Any split that is based on either of those can result in an error.

^exactly this, as we have to parse file names ... :( any chance you can rename folders? It just required to edit names of the folder within `labeled-data` in `config.yaml` the path as well. / you can save a copy of the project, just in case!

**Comment by tomwilson41986** [comment]
Thanks both for the feedback! I will try amending the filenames.
