### ISSUE TITLE
Unable to color body parts by individual during evaluation of multi-animal project

### ISSUE THREAD

**Issue by kchen01** [DeepLabCut/DeepLabCut#1640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

In the maDLC documentation, it states: "setting plotting to True plots all the testing and training frames with the manual and predicted labels; these will be colored by body part type by default. They can alternatively be colored by individual by passing plotting=individual."

However, this feature is not in the code. In the screenshot below, one can see that there is no option for setting its value to "individual, only True or False.

<img width="1055" alt="Screen Shot 2022-01-17 at 5 26 56 PM" src="https://user-images.githubusercontent.com/52056529/149847489-b1b39511-cae8-4af5-908c-6a57b3eb3911.png">
 

### Operating System

macOS

### DeepLabCut version

2.2.0.2

### DeepLabCut mode

multi animal

### Device type

Radeon pro 555 2 gb

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @kchen01, this feature is new in DLC 2.2.0.3 https://github.com/DeepLabCut/DeepLabCut/releases/tag/v2.2.0.3. You could run `pip install -U deeplabcut` to get the latest pypi version ☺️
