### ISSUE TITLE
Missing labeled data

### ISSUE THREAD

**Issue by owadhwa** [DeepLabCut/DeepLabCut#1642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have labelled my frames and I have saved the labels, but the folder with the labels doesn't seem to have the labeled data. The .h5 file is missing and there is no labeled data. 
I have got the CSV file in the folder with the coordinates labeled perfectly. I can thus also not train the neural network. 

I have tried multiple things - pip uninstall tables followed by pip install tables; conda uninstall pytables followed by conda install tables. However, I cannot seem to overcome this error. 

I also thought of separately converting the CSV file to the .h5 file using tables myself, but the same import error in tables persists in the DLC ipython terminal. 

I would be highly obliged if you could help me overcome this error. 

### Operating System

Windows 11

### DeepLabCut version

dlc version 2.2.0.5

### DeepLabCut mode

single animal

### Device type

gpu RTX 3060

### Steps To Reproduce

1. In the environment DEEPLABCUT
2. In the config file:
   # Project definitions (do not edit)
Task: FlyPoseEstimationPart3
scorer: OmikaWadhwa
date: Jan14
multianimalproject: false
identity:

    # Project path (change when moving around)
project_path: C:\Users\Omika\Documents\DeepLabCut\FlyPoseEstimation-OmikaWadhwa-2022-01-14

    # Annotation data set configuration (and individual video cropping parameters)
video_sets:
  ? C:\Users\Omika\Documents\DeepLabCut\FlyPoseEstimationPart3-OmikaWadhwa-2022-01-14\videos\medium_size_arena_camera_at_top_no_zoom.mp4
  : crop: 0, 1280, 0, 720
bodyparts:
- head
- abdomen
- tail
start: 0
stop: 1
numframes2pick: 20

    # Plotting configuration
skeleton:
- - head
  - abdomen
- - abdomen
  - tail
skeleton_color: black
pcutoff: 0.6
dotsize: 12
alphavalue: 0.7
colormap: rainbow

    # Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 0
default_net_type: resnet_50
default_augmenter: default
snapshotindex: -1
batch_size: 8

    # Cropping Parameters (for analysis and outlier frame detection)
cropping: false
    #if cropping is true for analysis, then set the values here:
x1: 0
x2: 640
y1: 277
y2: 624

    # Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 50
- 50
move2corner: true

3. Extract the frames from the video
4. Label the frames and save the labels
5. Check the labels
6. Create the training dataset

### Relevant log output

```shell
(DEEPLABCUT) C:\Users\Omika>python -m deeplabcut
Starting GUI...
Traceback (most recent call last):
  File "C:\Users\Omika\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\labeling_toolbox.py", line 945, in saveDataSet
    self.dataFrame.to_hdf(
  File "C:\Users\Omika\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\generic.py", line 2703, in to_hdf
    pytables.to_hdf(
  File "C:\Users\Omika\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\io\pytables.py", line 311, in to_hdf
    with HDFStore(
  File "C:\Users\Omika\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\io\pytables.py", line 572, in __init__
    tables = import_optional_dependency("tables")
  File "C:\Users\Omika\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\compat\_optional.py", line 118, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'tables'.  Use pip or conda to install tables.
You can now check the labels, using 'check_labels' before proceeding. Then, you can use the function 'create_training_dataset' to create the training dataset.
Creating images with labels by OmikaWadhwa.
Attention: C:\Users\Omika\Documents\DeepLabCut\FlyPoseEstimation-OmikaWadhwa-2022-01-14\labeled-data\medium_size_arena_camera_at_top_no_zoom does not appear to have labeled data!
If all the labels are ok, then use the function 'create_training_dataset' to create the training dataset!
C:\Users\Omika\Documents\DeepLabCut\FlyPoseEstimation-OmikaWadhwa-2022-01-14\labeled-data\medium_size_arena_camera_at_top_no_zoom\CollectedData_OmikaWadhwa.h5  not found (perhaps not annotated).
Annotation data was not found by splitting video paths (from config['video_sets']). An alternative route is taken...
The following folders were found: ['C:\\Users\\Omika\\Documents\\DeepLabCut\\FlyPoseEstimation-OmikaWadhwa-2022-01-14\\labeled-data\\medium_size_arena_camera_at_top_no_zoom']
C:\Users\Omika\Documents\DeepLabCut\FlyPoseEstimation-OmikaWadhwa-2022-01-14\labeled-data\medium_size_arena_camera_at_top_no_zoom\CollectedData_OmikaWadhwa.h5  not found (perhaps not annotated)
No data was found!
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
@om-git216, I normally get it to work with this command `conda install -c conda-forge pytables` (the conda-forge channel may make the difference here). I hope this helps!

**Comment by owadhwa** [comment]
Thanks, I tried this, but the error still persists.

**Comment by jeylau** [comment]
Do you restart the console after installation? Do you confirm that `tables` is present when running `conda list`?

**Comment by owadhwa** [comment]
Hi, I did restart the console after installation. Pytables version 3.6.1 is present in the conda list (not "tables" in particular).

**Comment by jeylau** [comment]
I'm puzzled. Could you perhaps try `conda install hdf5` as well?

**Comment by jeylau** [comment]
We've had a user reporting that `pip install tables==3.6.1` did help https://github.com/DeepLabCut/DeepLabCut/issues/1575#issuecomment-1015275590.
I wonder if there may be tables vs pytables conflicts; I remarked that in all my (working) environments, it is tables rather than pytables that is installed.

**Comment by owadhwa** [comment]
Hi, this worked. Thanks!
