### ISSUE TITLE
Create video for checking detection differed from refining tracklets

### ISSUE THREAD

**Issue by advmsbrdn16** [DeepLabCut/DeepLabCut#1649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi

I am working on pose estimation on Marmosets using ma-DLC. I have an issue where plotted points on refining tracklets are way too different compare to the create video for checking detection. Major plotted points' swap between male and female marmosets were occurred along the refining tracklets. Some even mixed wrongly for the body parts but created video for checking detection was fine. How can I fixed them without refining them one by one throughout frames in tracklets? This is my config.yaml and inference_config.yaml. Please help.

### Operating System

Windows 10

### DeepLabCut version

2.2rc3

### DeepLabCut mode

multi animal

### Device type

GeForce GTX 1060

### Relevant log output

```shell
CONFIG.YAML

# Project definitions (do not edit)
Task: '00001'
scorer: adam
date: Jan5
multianimalproject: true
identity: false

    # Project path (change when moving around)
project_path: C:\Users\adam\00001-adam-2022-01-05

    # Annotation data set configuration (and individual video cropping parameters)
video_sets:
  C:\Users\adam\00001-adam-2022-01-05\videos\00001.mp4:
    crop: 657, 1261, 11, 1079
individuals:
- male
- female
uniquebodyparts:
- testis
multianimalbodyparts:
- rightear
- forehead
- leftear
- chin
- chest
- tail1
- tail2
- tail3
- tail4
- tail5
skeleton:
- - rightear
  - forehead
- - forehead
  - leftear
- - chin
  - chest
- - tail2
  - tail3
- - chest
  - tail1
- - tail4
  - tail5
- - tail1
  - tail2
- - forehead
  - chin
- - tail3
  - tail4
bodyparts: MULTI!
start: 0
stop: 1
numframes2pick: 20

    # Plotting configuration
skeleton_color: yellow
pcutoff: 0.6
dotsize: 12
alphavalue: 0.7
colormap: rainbow

    # Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 0
default_net_type: resnet_50
default_augmenter: multi-animal-imgaug
snapshotindex: -1
batch_size: 4

    # Cropping Parameters (for analysis and outlier frame detection)
cropping: false
    #if cropping is true for analysis, then set the values here:
x1: 0
x2: 640
y1: 277
y2: 624

    # Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 50
- 50
move2corner: true


INFERENCES CONFIG.YAML

boundingboxslack: 0
iou_threshold: 0.6
max_age: 1
method: m1
min_hits: 1
minimalnumberofconnections: 5
pafthreshold: 0.1
pcutoff: 0.1
topktoretain: 2
variant: 0
withid: false
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by backyardbiomech** [comment]
First thing: Definitely update DLC to `2.2.0.6`.
The version you are using (`2.2rc3`) is deprecated, and many major improvements have been made in track formation after pose estimation since.
I also suggest that instead of simply upgrading, you create a new env and install from scratch.

**Comment by advmsbrdn16** [comment]
thanks for the info. But still major swaps were occurred along the result. I still need to swap them manually using refine tracklets. Is it normal for other user also?

**Comment by jeylau** [comment]
@advmsbrdn16, this is very dataset-specific. What `track_method` are you using? Also, if you haven't already, have a look here https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#optimized-animal-assembly-video-analysis. This § may be relevant in your case:

> Animal assembly and tracking quality can be assessed via deeplabcut.utils.make_labeled_video.create_video_from_pickled_tracks. This function provides an additional diagnostic tool before moving on to refining tracklets.
> 
> If animal assemblies do not look pretty, an alternative to the outlier search described above is to pass the _assemblies.pickle to find_outliers_in_raw_data in place of the _full.pickle. This will focus the outlier search on unusual assemblies (i.e., animal skeletons that were oddly reconstructed). This may be a bit more sensitive with crowded scenes or frames where animals interact closely. Note though that at that stage it is likely preferable anyway to carry on with the remaining steps, and extract outliers from the final h5 file as was customary in single animal projects.
