### ISSUE TITLE
[need suggestion] should use the existing model or train from the default, when retrain after refine/correct the outlier frames?

### ISSUE THREAD

**Issue by HaixinLiuNeuro** [DeepLabCut/DeepLabCut#165]
**Your Operating system and DeepLabCut version**

Windows 10, DLC 2.0

**Describe the problem**
After training a model, I used the outlier extraction to correct mislabeled frames. I would to improve the model. I was wondering what is the recommended method:
(1) using the trained model and continue training with merged training dataset
(2) start a new training with the merged dataset

I could miss the right method, if it is already in the biorxiv paper. 

Thank you very much!

**How to Reproduce the problem**

**Screenshots**

**Additional context**

**Comment by MMathisLab** [comment]
Hello, we would prefer that questions get posted here: https://forum.image.sc/tags/deeplabcut and code/bug reports on GitHub. 

(if your original labels have errors, then re-train from scratch, if not, you can re-load your network easily in the  pose_config.yaml file, see here: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/images/Box2.png)

**Comment by HaixinLiuNeuro** [comment]
I see. Thanks.
