### ISSUE TITLE
Non-tracked NaN points in maDLC saved with likelihood of 1.0

### ISSUE THREAD

**Issue by backyardbiomech** [DeepLabCut/DeepLabCut#1650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Single animal tracking in maDLC. 

If (part of) the animal starts offscreen, or ends up offscreen, the model, appropriately, cannot create tracks for invisible bodyparts for those frames. The saved coordinates are `nan, nan`. However, the saved likelihood is `1.00000`. 

Other than just being inaccurate, this creates problems in two realms:
1. Applying splines or other filtering regimes post-DLC where weights are based on likelihood thresholds.
2. Importing data to other workflows, especially 3d reconstruction in Anipose (my case), which uses a simple likelihood threshold for including data in calculations. Anipose will triangulate a point in a frame based on the lowest likelihood among the cameras. One camera with nans and 1.0 and another camera with points and 0.99 likelihood leads to problematic 3d reconstructions.

Simply setting the default likelihood to 0.0, or setting to 0 the likelihood for any rows of nans per bodypart, would fix it.

I have not checked to see if this is true in single animal DLC (it shouldn't be though since the nans will only show, I believe, when tracklets can't be formed or stitched for certain frames), or with more than 1 animal in maDLC.

### Operating System

Windows 10

### DeepLabCut version

2.2.0.3

### DeepLabCut mode

multi animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @backyardbiomech, thanks for reporting the bug! In your experience, is this occurring only strictly if at the beginning/end of a video?

**Comment by MMathisLab** [comment]
I think this was actually changed by 2.2.0.6; do you mind checking just to be sure? thanks @backyardbiomech !
