### ISSUE TITLE
Error when refining tracklets

### ISSUE THREAD

**Issue by CorinneAKelly** [DeepLabCut/DeepLabCut#1655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When trying to refine tracklets in the GUI, the drag tool isn't allowing the body parts to be moved. The checkbox for "drag" just unchecks itself.

### Operating System

Windows 10

### DeepLabCut version

dlc version 2.2.0.5

### DeepLabCut mode

multi animal

### Device type

NVIDIA 2070 Super

### Steps To Reproduce

1. In refine tracklets GUI, click "drag"
2. Attempt to move body part
3. Drag becomes deselected and error appears in command window

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\ckelly\Anaconda3\envs\dlc\lib\site-packages\matplotlib\cbook\__init__.py", line 287, in process
    func(*args, **kwargs)
  File "C:\Users\ckelly\Anaconda3\envs\dlc\lib\site-packages\matplotlib\widgets.py", line 1086, in <lambda>
    return self._observers.connect('clicked', lambda text: func(text))
  File "C:\Users\ckelly\Anaconda3\envs\dlc\lib\site-packages\deeplabcut\gui\tracklet_toolbox.py", line 299, in toggle_draggable_points
    self.scat.set_offsets([])
  File "C:\Users\ckelly\Anaconda3\envs\dlc\lib\site-packages\matplotlib\collections.py", line 566, in set_offsets
    (np.asarray(self.convert_xunits(offsets[:, 0]), 'float'),
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
_
```

### Anything else?

I am doing this while looking at tracks with identity colored instead of body parts (the individual parts are great, but occasionally are on the wrong animal).

Python 3.8.12
cudatoolkit 11.2.2
cudnn 8.1.0.77
tensorflow 2.5.0

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by CalvinLloyd117** [comment]
I am also experiencing this exact issue. Hopefully this is fixed soon.

**Comment by jeylau** [comment]
@CorinneAKelly @CalvinLloyd117, what's your current matplotlib version? I can only reproduce the error with matplotlib==3.5.1 (3.5.0 and under all work fine for me). If you're in that situation, `pip install matplotlib==3.5.0` should work (and I'll pin it in the requirements.txt). Let me know if that helps. 😊

**Comment by CalvinLloyd117** [comment]
For me, `pip install matplotlib==3.5.0` did fix the issue.
