### ISSUE TITLE
'numframes2pick' is actually N - 1

### ISSUE THREAD

**Issue by lauritk** [DeepLabCut/DeepLabCut#166]
Hi,
the 'numframes2pick' picks only N - 1 frames. 120 results in 119 frames.

**Comment by MMathisLab** [comment]
It depends on the method you pick to find the frames, actually. as k-means doesn't always give the # you select (due to how the clusters break down) but this doesn't affect performance. You can always grab more frames (or through them out before opening the labeling GUI).

**Comment by AlexEMG** [comment]
Without cropping the method indeed often resulted in N-1 frames, I fixed this and it will be in the next push. I also expanded the docs and allowed user feedback allowing to select frames only for specific videos.

**Comment by lauritk** [comment]
Great! I didn't use cropping so it seems to be the case.
