### ISSUE TITLE
UNIMPLEMENTED: DNN library is not found.

### ISSUE THREAD

**Issue by tomwilson41986** [DeepLabCut/DeepLabCut#1667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

This morning i started getting an issue with my Colab notebook, after having it working for days.

I have the following dependencies installed:

!pip install deeplabcut
!pip install opencv-python-headless==4.4.0.46

Everything works up until training the dataset. Then i receive a DNN library not found error.

Starting training....
---------------------------------------------------------------------------
UnimplementedError                        Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py](https://localhost:8080/#) in _do_call(self, fn, *args)
   1376     try:
-> 1377       return fn(*args)
   1378     except errors.OpError as e:

9 frames
UnimplementedError: 2 root error(s) found.
  (0) UNIMPLEMENTED: DNN library is not found.
	 [[{{node resnet_v1_50/conv1/Conv2D}}]]
	 [[huber_loss/assert_broadcastable/AssertGuard/pivot_f/_15/_556]]
  (1) UNIMPLEMENTED: DNN library is not found.
	 [[{{node resnet_v1_50/conv1/Conv2D}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

UnimplementedError                        Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py](https://localhost:8080/#) in _do_call(self, fn, *args)
   1394                     '\nsession_config.graph_options.rewrite_options.'
   1395                     'disable_meta_optimizer = True')
-> 1396       raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
   1397 
   1398   def _extend_graph(self):

UnimplementedError: Graph execution error:

### Operating System

operating system

### DeepLabCut version

dlc version 2.2.0.6

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

Here is the colab notebook:

https://colab.research.google.com/drive/1YbTE3snFNIjQ3l2J1NQ2C4O8ER7tWxf-?usp=sharing

### Anything else?

Thanks for your support !

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by stickzh** [comment]
I independently got the same problem

**Comment by aristotelis-economides** [comment]
Hey, can you try `pip install tensorflow==2.7` and removing the `%tensorflow_version 1.x` ?

**Comment by tomwilson41986** [comment]
Thanks. I tried that and got a different error.
![image](https://user-images.githubusercontent.com/95654146/152557543-98cf21a1-8f28-4c65-9998-e226e252f8dd.png)

**Comment by MMathisLab** [comment]
if cuDNN is failing, this is a COLAB issue; has happened in the past too: https://stackoverflow.com/questions/53414185/google-colab-error-failed-to-get-convolution-algorithm-this-is-probably-becaus 

so, unfortuantely we cannot fix colab :(

**Comment by stickzh** [comment]
Thanks Mackenzie, any suggestions on how to get colab to correct their problems?

**Comment by aristotelis-economides** [comment]
you could open an issue in their gihub repo, here's the closed issue for the last time it happened: https://github.com/googlecolab/colabtools/issues/384#issuecomment-451001849

**Comment by stickzh** [comment]
So, of course by Monday the problem did not exist anymore. I am able to run again.
This does reinforce my feeling though that colab is a very useful development tool but one needs a dedicated environment under careful version control in order to be sure to have reproducible results in production quality. 
Thanks everyone for your help
Will try throwing raw chicken over left shoulder next time as a first debugging step :-)

**Comment by aristotelis-economides** [comment]
Awesome to hear it's working again :grinning: :rocket: . 


Definitely having a dedicated environment is crucial for reproducibility! :) 

[Using a conda environment](https://deeplabcut.github.io/DeepLabCut/docs/installation.html#conda-the-installation-process-is-as-easy-as-this-figure) would be the easier and hassle-free way to do have reproducibility at least on the python module versions level. [Docker](https://deeplabcut.github.io/DeepLabCut/docs/docker.html) would be the bullet-proof way (ensuring also OS libraries compatibility), even though a bit more involved to setup and work with.

**Comment by stickzh** [comment]
I of course spoke too quickly,
I ran 200,000 iterations overnight. Had to restart the runtime (due to external reasons)
Now again the same problem.
This colab implementation is really annoying
:-(

I appreciate this is not a deeplabcut problem, but I imagine most people use the colab implementations 


David Stickland
+33-675350267
***@***.***

**Comment by jonpedros** [comment]
Are you running the create data set cell every time you restart the runtime? I was and it was giving me that same error. You only need to run it once and ignore it when setting up the runtime in the future.
