### ISSUE TITLE
extracting frames for new videos added to a projects extracts new frames for every video

### ISSUE THREAD

**Issue by louisadamian** [DeepLabCut/DeepLabCut#1668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

If videos are added to an existing project using `add_new_videos` and then `extract_frames` is run new frames are extracted  for every video instead of just the newly added videos.

### Operating System

Windows 10

### DeepLabCut version

2.2.0.6

### DeepLabCut mode

single animal

### Device type

Nvidia Titan RTX

### Steps To Reproduce

with an existing deeplabcut project run 'add_new_videos' to that project then run 'extract frames' on that project.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
You can pass `userfeedback=True` and manually indicate what videos you want to skip. Admittedly, this is not convenient if you have a lot of them, which reminds me of this proposal here for `userfeedback='auto'` #1283. @MMathisLab, maybe something to add in?

**Comment by louisadamian** [comment]
@jeylau I wrote #1660, which automatically extracts frames when running `add_new_videos`. Let me know what you think, I think this is the right behavior.

**Comment by louisadamian** [comment]
Also setting `userfeedback=True` and manually saying `no` for all old videos does not really make sense if you have a large training dataset it certainly becomes annoying after 20 videos.

**Comment by jeylau** [comment]
I agree with you!

**Comment by jeylau** [comment]
Closing, as it was fixed with #1660. Thanks again @louisadamian ☺️
