### ISSUE TITLE
DeepLabCut installed without GUI

### ISSUE THREAD

**Issue by AnnabelPerry** [DeepLabCut/DeepLabCut#1669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I installed DeepLabCut according to the recommended steps (see "Steps to Reproduce"), but it appears to have installed without GUI support. I get the following errors when I import DLC in an ipython session and attempt to label frames:
Commands:
```
ipython  

import deeplabcut  
```

Error:
```
2022-02-03 12:32:05.248671: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-02-03 12:32:05.248699: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
/home/blackmonlab/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/statsmodels/compat/pandas.py:65: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import Int64Index as NumericIndex
```

Commands:
```
path_config = '/home/blackmonlab/SurfaceAnnotated-annabel-2022-01-24/config.yaml'  

deeplabcut.label_frames(path_config)
```

Error:
```
AttributeError                            Traceback (most recent call last)
Input In [3], in 
----> 1 deeplabcut.label_frames(path_config)

AttributeError: module 'deeplabcut' has no attribute 'label_frames'
```

### Operating System

operating system
Distributor ID: Ubuntu
Description: Ubuntu 18.04.6 LTS
Release: 18.04
Codename: bionic
270.2 GB RAM

### DeepLabCut version

dlc version
2.2.0.6

### DeepLabCut mode

single animal

### Device type

gpu
01:00.0 VGA compatible controller: NVIDIA Corporation Device 1e04 (rev a1)

### Steps To Reproduce

```
git clone https://github.com/DeepLabCut/DeepLabCut.git

cd /home/blackmonlab/DeepLabCut/conda-environments

conda env create -f DEEPLABCUT.yaml

conda activate DEEPLABCUT

ipython

import deeplabcut

deeplabcut.create_new_project('SurfaceAnnotated','annabel',['/home/blackmonlab/Documents/Annabel/NeuralNetworkProject/DLCSurfaceAnnotated/videos/Surface 1 41486.mp4','/home/blackmonlab/Documents/Annabel/NeuralNetworkProject/DLCSurfaceAnnotated/videos/Surface 2 45209.mp4','/home/blackmonlab/Documents/Annabel/NeuralNetworkProject/DLCSurfaceAnnotated/videos/Surface 3 03428.mp4'])
```

Add body parts to config.yaml

### Anything else?

I attempted to downgrade tensorflow from 2.8.0 to 2.5.0, but got the following error when I did so (and the original problem was not solved by the downgrade):
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
black 22.1.0 requires typing-extensions>=3.10.0.0; python_version < "3.10", but you have typing-extensions 3.7.4.3 which is incompatible.

```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by AnnabelPerry** [comment]
I also tried installing tensorflow with gpu via ```pip install tensorflow-gpu==2.5.0``` but am still encountering the same error

**Comment by jeylau** [comment]
Hi @AnnabelPerry, once in your environment, do you see wxpython in the list given by `conda list`? If not, could you please execute the following command `pip install 'deeplabcut[gui]'` and let us know?
(side question: are you using python 3.8?)

**Comment by AnnabelPerry** [comment]
Thanks for the rapid response - I found ```wxpython                  4.0.7.post2``` when I ran ```conda list```. Since writing this post, I have tried running ```pip install 'deeplabcut[gui]'```. It did not fix the issue.
Also, I searched ```/lib/x86_64-linux-gnu``` for any version of ```libcudart.so```, but found none. I am trying to re-install CUDA via the following steps:
```
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin 

sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600 

wget <https://developer.download.nvidia.com/compute/cuda/11.0.3/local_installers/cuda-repo-ubuntu2004-11-0-local_11.0.3-450.51.06-1_amd64.deb> 

sudo dpkg -i cuda-repo-ubuntu2004-11-0-local_11.0.3-450.51.06-1_amd64.deb 

sudo apt-key add /var/cuda-repo-ubuntu2004-11-0-local/7fa2af80.pub 

sudo apt-get update 

sudo apt-get install cuda
```
... but encountered the following error after the last line of the above code:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cuda : Depends: cuda-11-0 (>= 11.0.3) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
... and am now chasing a cuda/nvidia dependency chain. I'm worried about accidentally messing up my graphics drivers in chasing this dependency chain, so any help is greatly appreciated. Also, I don't think cuda is simply not present on my desktop, because when I run ```nvcc --version```, I get this:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
```

**Comment by MMathisLab** [comment]
you will need CUDA 11+

**Comment by AnnabelPerry** [comment]
Thanks, I installed CUDA 11 but am still running into the same issue. I installed cuda using this command:
```
sudo aptitude install cuda
```
```aptitude``` gave me several install options to resolve dependency conflicts in the attempted installation. The first two options would involve not installing cuda 11, so I pressed ```n``` to reject each option until I got this option:
```
The following actions will resolve these dependencies:
   Upgrade the following packages:                                                                                     
1)     nvidia-settings [440.33.01-0ubuntu1 (, now) -> 470.57.01-0ubuntu0.18.04.1 (bionic-security, bionic-updates)]



Accept this solution? [Y/n/q/?] Y
```
... which I accepted. Now, when I enter an ```ipython``` session in the ```DEEPLABCUT``` conda environment and enter ```import deeplabcut```, I get the following message:
```
2022-02-07 21:01:26.190300: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
```
As you can see, cuda 11 appears successfully installed, but I am still getting the GUI error. I also get the same error as before when I run ```deeplabcut.label_frames()```. I've even tried rerunning ```pip install 'deeplabcut[gui]'```, but just get "Requirement already satisfied" messages when I do so.

**Comment by MMathisLab** [comment]
@AnnabelPerry -- are you sure it is installed for ipython, i.e. if you do:
```
python
import deeplabcut 
```
what do you get?

**Comment by MMathisLab** [comment]
and relatedly, if you run `pip3 install 'deeplabcut[gui]' ` then import, via ipython or python, can you tell me what you get?

**Comment by MMathisLab** [comment]
you can also try running `unset DLClight` -- nature.com/articles/s41596-019-0176-0

**Comment by AnnabelPerry** [comment]
Thank you - I ran all three suggestions and am still encountering the ```DLC loaded in light mode``` warning

**Comment by jeylau** [comment]
@AnnabelPerry, could you show us the output of `which python` (making sure your environment is activated)?
Could you also try:
```
python
import wx
```
and tell us if that gives you an error?

**Comment by AnnabelPerry** [comment]
Thanks for the rapid response! Output of ```which python``` is the following:
```
/home/blackmonlab/anaconda3/envs/DEEPLABCUT/bin/python
```

The suggested command...
```
python
import wx
```
... DOES give an error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/blackmonlab/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/home/blackmonlab/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: /home/blackmonlab/anaconda3/envs/DEEPLABCUT/bin/../lib/libgio-2.0.so.0: undefined symbol: g_unix_get_passwd_entry
```

**Comment by AnnabelPerry** [comment]
Update: I ran into some ```wxpython``` issues on this same computer when attempting to install a program called SimBA a little over a month ago. Installing SimBA with the ```--no-deps``` flag fixed had fixed that issue, so I just now decided to try wiping DLC from the computer and re-dowloading as follows:
```
conda deactivate

conda env remove -n DEEPLABCUT 

sudo rm -r /home/blackmonlab/DeepLabCut/

git clone https://github.com/DeepLabCut/DeepLabCut.git  

cd /home/blackmonlab/DeepLabCut/conda-environments  

conda env create -f DEEPLABCUT.yaml  

conda activate DEEPLABCUT 

pip install 'deeplabcut[gui]' --no-deps
```
... this did not work. However, the ```pip install 'deeplabcut[gui]' --no-deps``` gave the following message:
```
Requirement already satisfied: deeplabcut[gui] in /home/blackmonlab/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages (2.2.0.6)
```
... which I thought is interesting given that ```which python``` indicates that python is being sourced from the ```/home/blackmonlab/anaconda3/envs/DEEPLABCUT/bin/python``` directory rather than the ```/home/blackmonlab/anaconda3/envs/DEEPLABCUT/lib/python3.8``` directory. Could this prohibit the DeepLabCut GUI features from being accessed from within Python?

I also tried installing ```wxpython``` as follows:
```
conda install -c anaconda wxpython
```
... but got the following errors:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                      

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:
  - wxpython -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:
  - feature:/linux-64::__glibc==2.27=0
  - feature:|@/linux-64::__glibc==2.27=0
  - wxpython -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.27

```
So, I tried downgrading python to 3.6 via ```conda install python=3.6 ``` (since DLC was originally written in 3.6.x), but got this error followed by several screens-worth of package conflicts.
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                       -                               -                                                                                           |  

UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (pip):

  - python=3.6 -> pip

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```
I also simply tried opening python version 3.6 using the ```python3.6``` command in the Linux terminal and running ```import wx```, but got the following error:
```

Traceback (most recent call last):
  File "", line 1, in 
ModuleNotFoundError: No module named 'wx'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 62, in apport_excepthook
    if not enabled():
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 24, in enabled
    import re
  File "/home/blackmonlab/anaconda3/envs/DEEPLABCUT/lib/python3.8/re.py", line 125, in 
    import sre_compile
  File "/home/blackmonlab/anaconda3/envs/DEEPLABCUT/lib/python3.8/sre_compile.py", line 17, in 
    assert _sre.MAGIC == MAGIC, "SRE module mismatch"
AssertionError: SRE module mismatch

Original exception was:
Traceback (most recent call last):
  File "", line 1, in 
ModuleNotFoundError: No module named 'wx'
```

**Comment by MMathisLab** [comment]
Hi @AnnabelPerry best practice would to not create the env and then again run pip install DLC, i.e. I would not recommend this:
```
conda activate DEEPLABCUT 

pip install 'deeplabcut[gui]' --no-deps
```
- 3.6 is not supported, only 3.8 onwards. 
- wxPython must be a very specific version right now, so don't just install the latest. I would recommend you follow this exactly: 
- for ubuntu, there is a specific formula you might follow if issues: https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html#installation-on-ubuntu-20-04-lts

**Comment by AnnabelPerry** [comment]
Sorry to bother y'all again, but even when following the formula described [here](https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html#installation-on-ubuntu-20-04-lts), I cannot get DeepLabCut to install.

First off, I switched desktop computers because I noticed the installation steps required a ```reboot``` and, since the original desktop I was working on is a shared lab desktop, I couldn't reboot it without messing up other peoples' projects. The new desktop has similar device specifications to those mentioned for the previous system.

I got through the following steps...
```
sudo apt install gcc 


wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin 

sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600 

wget https://developer.download.nvidia.com/compute/cuda/11.3.1/local_installers/cuda-repo-ubuntu2004-11-3-local_11.3.1-465.19.01-1_amd64.deb 

sudo dpkg -i cuda-repo-ubuntu2004-11-3-local_11.3.1-465.19.01-1_amd64.deb 

sudo apt-key add /var/cuda-repo-ubuntu2004-11-3-local/7fa2af80.pub 

sudo apt-get update 
```
...before encountering the following error on the ```sudo apt-get -y install cuda``` command:
```
Errors were encountered while processing:
 nvidia-dkms-465
 cuda-drivers-465
 cuda-drivers
 nvidia-driver-465
 cuda-runtime-11-3
 cuda-demo-suite-11-3
 cuda-11-3
 cuda
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
I tried to see if I could get through the next few steps...
```
sudo add-apt-repository ppa:graphics-drivers/ppa 

sudo apt update 
```
... but encountered an error on ```sudo ubuntu-drivers autoinstall```:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nvidia-driver-510 : Depends: libnvidia-gl-510 (= 510.47.03-0ubuntu0.20.04.1) but it is not going to be installed
   Depends: nvidia-kernel-source-510 (= 510.47.03-0ubuntu0.20.04.1) but it is not going to be installed
   Depends: libnvidia-extra-510 (= 510.47.03-0ubuntu0.20.04.1) but it is not going to be installed
   Depends: libnvidia-decode-510 (= 510.47.03-0ubuntu0.20.04.1) but it is not going to be installed
   Depends: libnvidia-encode-510 (= 510.47.03-0ubuntu0.20.04.1) but it is not going to be installed
   Depends: xserver-xorg-video-nvidia-510 (= 510.47.03-0ubuntu0.20.04.1) but it is not going to be installed
   Depends: libnvidia-cfg1-510 (= 510.47.03-0ubuntu0.20.04.1) but it is not going to be installed
   Depends: libnvidia-fbc1-510 (= 510.47.03-0ubuntu0.20.04.1) but it is not going to be installed
   Recommends: libnvidia-compute-510:i386 (= 510.47.03-0ubuntu0.20.04.1)
   Recommends: libnvidia-decode-510:i386 (= 510.47.03-0ubuntu0.20.04.1)
   Recommends: libnvidia-encode-510:i386 (= 510.47.03-0ubuntu0.20.04.1)
   Recommends: libnvidia-fbc1-510:i386 (= 510.47.03-0ubuntu0.20.04.1)
   Recommends: libnvidia-gl-510:i386 (= 510.47.03-0ubuntu0.20.04.1)
E: Unable to correct problems, you have held broken packages.
```

**Comment by dradri** [comment]
FYI I am having a near identical issue. However I install it, it loads in light mode. Now finally I have no errors installing (followed the recipe for ubuntu 20.04 w GPU)
but finding this thread, i also tried 'import wx' and got a different error

>>> import wx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leboeufa/.local/lib/python3.8/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/home/leboeufa/.local/lib/python3.8/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: /home/leboeufa/anaconda3/envs/DEEPLABCUT/bin/../lib/libgio-2.0.so.0: undefined symbol: g_uri_join

I've also tried the docker approach and still no luck

**Comment by MMathisLab** [comment]
@AnnabelPerry you will need to uninstall CUDA first: `E: Unable to correct problems, you have held broken packages.`
