### ISSUE TITLE
Colab Freezes at Collecting statsmodels>=0.11   Using cached statsmodels-0.13.2.tar.gz (17.9 MB)

### ISSUE THREAD

**Issue by tomwilson41986** [DeepLabCut/DeepLabCut#1679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Myself and other users are experiencing an issue with Colab this morning.

When installing dependencies, Colab is crashing on the step

Collecting statsmodels>=0.11
Using cached statsmodels-0.13.2.tar.gz (17.9 MB)

We are trying to install:
!pip install deeplabcut
!pip install opencv-python-headless==4.5.1.48
!pip install --upgrade tables
!pip install tensorflow==2.7

Describe the expected behavior
Dependencies usually install within 2-3 mins. Now it is freezing for over 1 hour.

What web browser you are using
Chrome

### Operating System

operating system

### DeepLabCut version

dlc version

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

https://colab.research.google.com/drive/1YbTE3snFNIjQ3l2J1NQ2C4O8ER7tWxf-?usp=sharing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
There is indeed something wrong with their latest release specifically. I got it to work simply by adding `!pip install statsmodels==0.13.1` before the line `!pip install deeplabcut`. Don't hesitate to report the issue on their repo though. ☺️
