### ISSUE TITLE
Intel OpenVINO backend

### ISSUE THREAD

**Issue by dkurt** [DeepLabCut/DeepLabCut#1682]
Hi! I'm working on [OpenVINO](https://github.com/openvinotoolkit/openvino) backend for DeepLabCut for better efficiency. Currently, I validate integration on https://github.com/DeepLabCut/DeepLabCut/blob/master/examples/testscript_pretrained_models.py. However, I cannot check the accuracy because this sample runs human body estimation model on `reachingvideo1` which is a mouse video. May I ask to share the link to "human dancing" video from http://www.mackenziemathislab.org/dlc-modelzoo or can I run a different network on mouse video?

![image](https://user-images.githubusercontent.com/25801568/153449842-85d07eee-f7cb-4579-a9a4-d269ba48859f.png)

WIP branch: https://github.com/dkurt/DeepLabCut/tree/openvino

**Comment by MMathisLab** [comment]
hi @dkurt cool! And looking forward to PR https://github.com/dkurt/DeepLabCut/pull/1/files; I don't have the human video permission to share, but you can use DLC-live if you want; it pulls a dog model with a dog video. https://github.com/DeepLabCut/DeepLabCut-live

**Comment by dkurt** [comment]
Thanks, @MMathisLab! Will open a pull request as soon as possible. Maybe I can just record myself dancing :smile:

**Comment by dkurt** [comment]
Hi, @MMathisLab! Opened a PR: https://github.com/DeepLabCut/DeepLabCut/pull/1686. Looking forward for any feedback.

**Comment by MMathisLab** [comment]
yes, sorry we are just very busy and enhancements need to take a secondary priority, please be patient with us :D
