### ISSUE TITLE
Providing images instead of videos

### ISSUE THREAD

**Issue by ashwin-miriyala** [DeepLabCut/DeepLabCut#1685]
**Is your feature request related to a problem? Please describe.**
My setup involves recording behaviour via a camera that captures and saves each frame as  a numpy array.  The process of converting the numpy arrays into images and then into videos is quite confusing, as it's tough to decide which video format to save in.

**Describe the solution you'd like**

I was wondering if DLC could allow for setting the path to an image folder instead, and then use the raw uncompressed images (e.g. tiff) or even the numpy arrays to run the pose estimation on.  

**Describe alternatives you've considered**
As of now I'm using cv2.VideoWriter in python to write the .tiff images into .avi using 'MPEG' as the fourcc.  These are the videos I'm using to do pose estimation in DLC.

**Comment by backyardbiomech** [comment]
You can process images with the time lapse function. See comments in #401

**Comment by ashwin-miriyala** [comment]
Thanks for the quick reply!

  If I understand this correctly, I should:
First, train a dataset using a video(s), and evaluate the trained network
Next, apply that training dataset to a folder of images using deeplabcut.analyze_time_lapse_frames

Is that correct?

**Comment by MMathisLab** [comment]
training is done on images, typically extracted from videos, I would recommend the Nature Protocols paper to get started!

**Comment by ashwin-miriyala** [comment]
Hi, I wasn't clear with the request, sorry about that.  What I meant was, when creating a new project (deeplabcut.create_new_project), I would like to point to a folder that contains a sequence of images (in either .tiff format or .numpy format), instead of a video.  

This saves the effort of converting a sequence of images into a video format, which will anyways be used to extract back into individual images.  Further, most video formats require a certain amount of compression that decreases image quality.

From what I understand, deeplabcut.analyze_time_lapse_frames is for analyzing a sequence of images AFTER having already created a training dataset.  This isn't what I wanted.  

Thanks again for all the effort with this!
