### ISSUE TITLE
Hardware accelleration and easy installation on ANY GPU (AMD, Intel, Nvidia) via Tensorflow-DirectML

### ISSUE THREAD

**Issue by Seyij** [DeepLabCut/DeepLabCut#1687]
Installation for GPU hardware accelleation can be complicated and only works on Nvidia graphics cards. There is a method I used that made installation of deeplabcut with GPU hardware incredibly easy and consistant across devices (even those with only integrated GPUs). I could create a conda environment fully set up for GPU-deeplabcut work in 3 lines that worked on multiple tested computers. This was when Tensorflow-DirectML was in pre-release, where originally there were issues but I contacted the developers of Tensorflow-DirectML, where they thankfully added support for the version of Deeplabcut that was available a that time. 

After coming back to working with Deeplabcut after various updates, there are now compatibility issues with the method. I believe I and many others would benefit is this method was made to work again and added to the installation documentation.  Here I will briefly describe the instructions I followed and what no longer works.

### Easy GPU accelleration installation on Windows PCs for ANY GPU:

If you are on Windows 10/11 and have a DirectX 12 compatible GPU from ANY vendor (AMD, Intel, or Nvidia), you can benefit from the dramatic speed increase of using a GPU for inference, but with much simpler installation than with standard tensorflow-GPU. This method uses [Tensorflow-directml](https://github.com/microsoft/tensorflow-directml) which uses DirectX instead of Cuda for ML inference. 

To check the DirectX version of your installed GPU, type in __*dxdiag*__ into windows search and select the run command. In system information the bottom item of the list shows your DirectX version. In addition to this ensure your GPU drivers are up-to-date. Updating drivers by any official means (Nvidia Geforce experience, AMD radeon software, direct from the vendor website) is fine.

The following instructions are using conda and pip for environment management, executing within the Anaconda prompt program that was installed along with Anaconda python. The # lines are not to be typed, they are for guidance.

```dos
# the latest version of python compatible with tensorflow-directml is 3.7
# the environment name dlc_dml can be any name
conda create -n dlc_dml python=3.7
# activate so any next steps are within this environment
conda activate dlc_directml

pip install tensorflow-directml
pip install "deeplabcut[gui]"
```
---
After going through some deeplabcut examples, this no longer works. I think the main incompatibility problem is that the latest version of tensorflow-directml is based on tensorflow 1.15, whereas as Deeplabcut is on tensorflow 2. Because of this, training new networks does not work. I also was unable to get GPU inferencing to work. Pip noted a large dependency issue being numpy and tensorboard versions, as deeplabcut required newer versions than numpy.

Thanks very much for your time and development work, if you have any more questions about what I have written feel free to ask.

**Comment by dkurt** [comment]
Hi! Is you're interested in Intel HW optimizations, we have a proposal: https://github.com/DeepLabCut/DeepLabCut/pull/1686

**Comment by MMathisLab** [comment]
Hey @Seyij thanks for this! Indeed we moved to TF2, but also support still running TF1 as well; it might be a "simple" fix in this way. If you want to document what the errors you face, I can try to help guide ways!

**Comment by Seyij** [comment]
> Hi! Is you're interested in Intel HW optimizations, we have a proposal: #1686
Thank you for this, I'm not familiar with this, so I'll have a look.

> Hey @Seyij thanks for this! Indeed we moved to TF2, but also support still running TF1 as well; it might be a "simple" fix in this way. If you want to document what the errors you face, I can try to help guide ways!
Sure thing, I'll try the method again and work through a standard Deeplabcut example. I'll post specific details here of my findings.

**Comment by Seyij** [comment]
Hello, I'll try and summarise some of my findings from trying to get it to work here.

**Summary**

A key part of getting tensorflow-directml to work is just to get it to recognise the GPU. Tested on older versions of tensorflow via:
```python
import tensorflow as tf
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
```
To get this to work, I changed the order of installation so that tensorflow-directml dependencies supersede the deeplabcut one. This allowed my integrated and dedicated GPU to be recognised.

Unfortunately when I tried to import deeplabcut I got an extremely large error traceback that ended in ModuleNotFoundError: No module named 'numpy.typing'. I assume this is because tensorflow-directml 1.15.5needs a version of numpy that doesn't have numpy.typing. I'll do more tests to see this can be solved with a numpy version that works with both deeplabcut and tensorflow 1.15.5. Below I have the error report, any advice will be appreciated!

---

```python
In [1]: import deeplabcut as dlc
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-7dc21562c90f> in <module>
----> 1 import deeplabcut as dlc

~\anaconda3\envs\dlc_dml2\lib\site-packages\deeplabcut\__init__.py in <module>
     44
     45
---> 46 from deeplabcut.create_project import (
     47     create_new_project,
     48     create_new_project_3d,

~\anaconda3\envs\dlc_dml2\lib\site-packages\deeplabcut\create_project\__init__.py in <module>
      1 from deeplabcut.create_project.add import add_new_videos
----> 2 from deeplabcut.create_project.demo_data import load_demo_data
      3 from deeplabcut.create_project.modelzoo import (
      4     create_pretrained_human_project,
      5     create_pretrained_project,

~\anaconda3\envs\dlc_dml2\lib\site-packages\deeplabcut\create_project\demo_data.py in <module>
     13
     14 import deeplabcut
---> 15 from deeplabcut.utils import auxiliaryfunctions
     16
     17

~\anaconda3\envs\dlc_dml2\lib\site-packages\deeplabcut\utils\__init__.py in <module>
----> 1 from deeplabcut.utils.auxfun_multianimal import *
      2 from deeplabcut.utils.auxfun_videos import *
      3 from deeplabcut.utils.auxiliaryfunctions import *
      4 from deeplabcut.utils.conversioncode import *
      5 from deeplabcut.utils.frameselectiontools import *

~\anaconda3\envs\dlc_dml2\lib\site-packages\deeplabcut\utils\auxfun_multianimal.py in <module>
     19
     20 from deeplabcut.utils import auxiliaryfunctions, conversioncode
---> 21 from deeplabcut.generate_training_dataset import trainingsetmanipulation
     22
     23

~\anaconda3\envs\dlc_dml2\lib\site-packages\deeplabcut\generate_training_dataset\__init__.py in <module>
     10
     11 from deeplabcut.generate_training_dataset.frame_extraction import *
---> 12 from deeplabcut.generate_training_dataset.trainingsetmanipulation import *
     13 from deeplabcut.generate_training_dataset.multiple_individuals_trainingsetmanipulation import *

~\anaconda3\envs\dlc_dml2\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py in <module>
     22 import yaml
     23
---> 24 from deeplabcut.pose_estimation_tensorflow import training
     25 from deeplabcut.utils import (
     26     auxiliaryfunctions,

~\anaconda3\envs\dlc_dml2\lib\site-packages\deeplabcut\pose_estimation_tensorflow\__init__.py in <module>
     10
     11 from deeplabcut.pose_estimation_tensorflow.config import *
---> 12 from deeplabcut.pose_estimation_tensorflow.datasets import *
     13 from deeplabcut.pose_estimation_tensorflow.default_config import *
     14 from deeplabcut.pose_estimation_tensorflow.core.evaluate import *

~\anaconda3\envs\dlc_dml2\lib\site-packages\deeplabcut\pose_estimation_tensorflow\datasets\__init__.py in <module>
     11 from .pose_deterministic import DeterministicPoseDataset
     12 from .pose_scalecrop import ScalecropPoseDataset
---> 13 from .pose_imgaug import ImgaugPoseDataset
     14 from .pose_tensorpack import TensorpackPoseDataset
     15 from .pose_multianimal_imgaug import MAImgaugPoseDataset

~\anaconda3\envs\dlc_dml2\lib\site-packages\deeplabcut\pose_estimation_tensorflow\datasets\pose_imgaug.py in <module>
     20 import pickle
     21
---> 22 import imgaug.augmenters as iaa
     23 import numpy as np
     24 import scipy.io as sio

~\anaconda3\envs\dlc_dml2\lib\site-packages\imgaug\__init__.py in <module>
      5 # classes/functions, hence always place the other imports below this so that
      6 # the deprecated stuff gets overwritten as much as possible
----> 7 from imgaug.imgaug import *  # pylint: disable=redefined-builtin
      8
      9 import imgaug.augmentables as augmentables

~\anaconda3\envs\dlc_dml2\lib\site-packages\imgaug\imgaug.py in <module>
     17 import numpy as np
     18 import cv2
---> 19 import imageio
     20 import six
     21 import six.moves as sm

~\anaconda3\envs\dlc_dml2\lib\site-packages\imageio\__init__.py in <module>
     20
     21 # Load some bits from core
---> 22 from .core import FormatManager, RETURN_BYTES
     23
     24 # Instantiate the old format manager

~\anaconda3\envs\dlc_dml2\lib\site-packages\imageio\core\__init__.py in <module>
     14 from .fetching import get_remote_file, InternetNotAllowedError, NeedDownloadError
     15 from .request import Request, read_n_bytes, RETURN_BYTES
---> 16 from .format import Format, FormatManager

~\anaconda3\envs\dlc_dml2\lib\site-packages\imageio\core\format.py in <module>
     38 from . import Array, asarray
     39 from .request import ImageMode, Request
---> 40 from ..config import known_plugins, known_extensions, PluginConfig, FileExtension
     41 from ..config.plugins import _original_order
     42 from .imopen import imopen, _get_config

~\anaconda3\envs\dlc_dml2\lib\site-packages\imageio\config\__init__.py in <module>
      5     video_extensions,
      6 )
----> 7 from .plugins import known_plugins, PluginConfig
      8
      9 __all__ = [

~\anaconda3\envs\dlc_dml2\lib\site-packages\imageio\config\plugins.py in <module>
      2 import importlib
      3
----> 4 from ..core.legacy_plugin_wrapper import LegacyPlugin
      5
      6

~\anaconda3\envs\dlc_dml2\lib\site-packages\imageio\core\legacy_plugin_wrapper.py in <module>
      4
      5 from .request import IOMode, Request, InitializationError
----> 6 from .v3_plugin_api import PluginV3, ImageProperties
      7
      8

~\anaconda3\envs\dlc_dml2\lib\site-packages\imageio\core\v3_plugin_api.py in <module>
      1 from . import Request
----> 2 from numpy.typing import ArrayLike
      3 import numpy as np
      4 from typing import Optional, Dict, Any, Tuple, Union, List
      5 from dataclasses import dataclass

ModuleNotFoundError: No module named 'numpy.typing'
```

**Some details of other tests**

I set up an environment as follows:
```shell
conda create -n dlc_dml python=3.7
conda activate dlc_dml
pip install tensorflow-directml
pip install "deeplabcut[gui]"
```
And this causes incopatible tensorflow versions to be installed as pip says deeeplabcut needs tensorflow >2, but the tensorflow and tensorflow-directml need to be the same version.
```shell
##This is a subset of package details, as a output from conda list
tensorflow                2.8.0                    pypi_0    pypi
tensorflow-directml       1.15.5                   pypi_0    pypi
tensorflow-estimator      1.15.1                   pypi_0    pypi
```
After this I installed tensorflow 1.15.5 and received this informative error:
```shell
pip install tensorflow==1.15.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imageio 2.16.0 requires numpy>=1.20.0, but you have numpy 1.18.5 which is incompatible.
deeplabcut 2.2.0.6 requires tensorflow>=2.0, but you have tensorflow 1.15.5 which is incompatible.
Successfully installed numpy-1.18.5 tensorboard-1.15.0 tensorflow-1.15.5
```
After this the GPU still was not recognised. I conducted a variety of other tests that I can report on if the details and error reports will be helpful.

**Comment by bobfromjapan** [comment]
Hello, @Seyij!

I also tried deeplabcut with tensorflow-directml about a year ago and I reported it in [image.sc](http://image.sc/) forum. 
That report is bit old version, but it may be helpful for you!
https://forum.image.sc/t/fyi-deeplabcut-worked-on-radeon-gpu-rtx3080-using-tensorflow-directml/47700

On my most recent experience, I could run deeplabcut on tensorflow-directml at 2021/6, and that specifications like below:

OS: Windows 10
CPU: Ryzen5 5600X
GPU: Radeon 6900XT
python ver: 3.7
dlc ver: 2.2rc2
tf-dML ver: tensorflow_directml-1.15.5.dev210429

requirements.txt

```
absl-py==0.12.0
astor==0.8.1
backcall==0.2.0
cached-property==1.5.2
certifi==2021.5.30
chardet==4.0.0
click==8.0.1
colorama==0.4.4
cycler==0.10.0
Cython==0.29.23
decorator==5.0.9
deeplabcut==2.2rc2
filterpy==1.4.5
gast==0.2.2
google-pasta==0.2.0
grpcio==1.38.0
h5py==2.10.0
idna==2.10
imageio==2.9.0
imageio-ffmpeg==0.4.4
imgaug==0.4.0
importlib-metadata==4.5.0
intel-openmp==2021.2.0
ipykernel==5.5.5
ipython==7.24.1
ipython-genutils==0.2.0
jedi==0.18.0
joblib==1.0.1
jupyter-client==6.1.12
jupyter-core==4.7.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
kiwisolver==1.3.1
llvmlite==0.34.0
Markdown==3.3.4
matplotlib==3.1.3
matplotlib-inline==0.1.2
moviepy==1.0.1
msgpack==1.0.2
msgpack-numpy==0.4.7.1
networkx==2.5.1
numba==0.51.1
numexpr==2.7.3
numpy==1.17.5
opencv-python==4.5.2.54
opencv-python-headless==4.5.2.54
opt-einsum==3.3.0
pandas==1.2.4
parso==0.8.2
patsy==0.5.1
pickleshare==0.7.5
Pillow==8.2.0
proglog==0.1.9
prompt-toolkit==3.0.18
protobuf==3.17.3
psutil==5.8.0
Pygments==2.9.0
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2021.1
PyWavelets==1.1.1
pywin32==301
PyYAML==5.4.1
pyzmq==22.1.0
requests==2.25.1
ruamel.yaml==0.17.7
ruamel.yaml.clib==0.2.2
scikit-image==0.18.1
scikit-learn==0.24.2
scipy==1.6.3
Shapely==1.7.1
six==1.16.0
statsmodels==0.12.2
tables==3.6.1
tabulate==0.8.9
tensorboard==1.15.0
tensorflow-directml==1.15.5.dev210429
tensorflow-estimator==1.15.1
tensorpack==0.11
termcolor==1.1.0
threadpoolctl==2.1.0
tifffile==2021.6.6
tornado==6.1
tqdm==4.61.0
traitlets==5.0.5
typing-extensions==3.10.0.0
urllib3==1.26.5
wcwidth==0.2.5
Werkzeug==2.0.1
wrapt==1.12.1
wxPython==4.0.7.post2
zipp==3.4.1

```

**Comment by Seyij** [comment]
Hi @bobfromjapan Thanks very much for this, exactly what I need! This should help me figure out the rest!

**Comment by Seyij** [comment]
Hello! I found an instruction set that works, tested on a few deeplabcut models and GPU acceleration is working great!

```shell
conda create --name dlc_dml python=3.7
conda activate dlc_dml
#specific version just in case something changes later
pip install deeplabcut[gui]==2.2.0.6
pip install tensorflow-directml==1.15.5
pip install pip install imageio==2.9.0
```
Since now there is a set of version numbers this should not break unless pip itself has a significant change in the future. 
I have a pip requirements file that has the resultant configuration. I also have a conda environment file but I was unable to upload that to this issue comment.
[tf_dml_pip.txt](https://github.com/DeepLabCut/DeepLabCut/files/8196775/tf_dml_pip.txt)

Thanks all for your help so far!
In terms of making this useful for other people, would providing the command line install instructions as above be more helpful, or providing a conda environment, or both?

**Comment by MMathisLab** [comment]
Hey @Seyij want to write a cookbook/docs update entry for this? Would be awesome!

(1) edit this to add new info on hardware, i.e. if you have X, then you just need to do Y" 👍  https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/recipes/TechHardware.md

(2) If you want to also add a section here, on a "how to": https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/recipes/installTips.md

**Comment by Seyij** [comment]
Yes thanks I'd be happy to do that!
