### ISSUE TITLE
Create new single animal project using image files, not video

### ISSUE THREAD

**Issue by ashwin-miriyala** [DeepLabCut/DeepLabCut#1688]
**Is your feature request related to a problem? Please describe.**

I am acquiring a sequence of images as numpy arrays and then converting them into .tiff format to preserve the image quality.  When creating a new project in deeplabcut, It's frustrating that I have to encode these images into video format first, when deeplabcut extracts frames from the video anyway.  This reduces the quality of the original frame data.  

**Describe the solution you'd like**
I do not have a trained dataset yet, so having the original higher quality image data to label with would be very helpful.  

When creating a new project, I would like to provide a folder with a sequence of images (eg tiff or numpy arrays) that were acquired during behaviour, instead of providing a video.  This way there's no loss of image quality while converting the images into a video format. 

**Describe alternatives you've considered**
I could first compile the frames into a video (e.g. using python cv2.VideoWriter).  Then, I could use this video to extract frames (deeplabcut.extract_frames).  Using the frame numbers from this  extract step, I could replace these frames with the original frames (changing the name to have "img%5d.png" ).  This way I could have the original uncompressed images to label.  

**Additional context**
Beyond this, it would be very useful to create the training dataset and train the network using the original images.

**Comment by MMathisLab** [comment]
You don't' have to put then into a video format first, you simply need to adhere to our project management structure: https://github.com/DeepLabCut/DeepLabCut/wiki/Using-labeled-data-in-DeepLabCut-that-was-annotated-elsewhere

Namely, just put the images in the folder that match the dummy config.yaml video_set paths.
