### ISSUE TITLE
cuDNN failed to initialize

### ISSUE THREAD

**Issue by tomwilson41986** [DeepLabCut/DeepLabCut#1689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Colab is crashing due to a cuDNN error. This is the second time this has happened in a week.

Believe it is likely a tensorflow issue, but posting here in case anyone can help. 

UnknownError: 2 root error(s) found.
(0) UNKNOWN: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
[[{{node resnet_v1_50/conv1/Conv2D}}]]
[[Sigmoid/_545]]
(1) UNKNOWN: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
[[{{node resnet_v1_50/conv1/Conv2D}}]]
0 successful operations.
0 derived errors ignored.

![image](https://user-images.githubusercontent.com/95654146/154283603-fb473f54-36c7-46c7-a526-6f4f5b89cdf2.png)

### Operating System

operating system

### DeepLabCut version

2.2.06

### DeepLabCut mode

single animal

### Device type

gpu

### Anything else?

Notebook - https://colab.research.google.com/drive/1YbTE3snFNIjQ3l2J1NQ2C4O8ER7tWxf-?usp=sharing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by SauBuen** [comment]
This issue is related to  [#10505](https://github.com/tensorflow/models/issues/10505)

**Comment by MMathisLab** [comment]
yes, unfortunately we can't control colab ;( ... so please post there as well! thank you!!
