### ISSUE TITLE
`init_weights` not working

### ISSUE THREAD

**Issue by ghost** [DeepLabCut/DeepLabCut#169]
**Your Operating system and DeepLabCut version**

OS: Arch Linux
Venv: Python 3.6 venv
DeepLabCut: 2.0.2

**Describe the bug**
Setting the parameter `init_weights` to ".../dlc-models/iteration-0/projectname/train/snapshot-2800" does not actually change initial weights

**To Reproduce**
1. set `init_weights` to a checkpoint
2. run `train_network`

**Expected behavior**
I expect to see the `train_network` function begin at "iteration 2800", not "iteration 1". Loss should also be much less than the value expected at the first iteration (~1.4 for me).

**Comment by MMathisLab** [comment]
As we explained in several other issues, it does not start counting at the snapshot, it starts again at 0. Just as the first weights are also not “0”, it’s already trained on imagenet.

**Comment by AlexEMG** [comment]
If you don't want to overwrite it, then just make a copy of the snapshot in question before you start. Keep in mind that the loss can only be compared if enough samples were taken into account. However, the loading works for me.

**Comment by ghost** [comment]
Thank you for clarifying.

**Comment by UnicodeAlt255** [comment]
Thank you for clarifying.
