### ISSUE TITLE
Unsupported network of type dlcrnet_ms5

### ISSUE THREAD

**Issue by DuanWei-fudan** [DeepLabCut/DeepLabCut#1692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I can't train my network with the dlcrnet_ms5.

### Operating System

operating system: windows 10

### DeepLabCut version

dlc version: '2.2.0.6'

### DeepLabCut mode

multi animal

### Device type

GPU

### Steps To Reproduce

I want to  train my network with the dlcrnet_ms5.
_deeplabcut.create_multianimaltraining_dataset(config_path, net_type='dlcrnet_ms5')_
But the config still was the resnet_50, so I artifically changed the types in 'config.yaml' and 'pose_cfg.yaml'.
After starting my training
_deeplabcut.train_network(config_path,shuffle=1,gputouse=0,displayiters=10, saveiters=1000, maxiters=600000, allow_growth=True)_
It reported :
**Unsupportrd network of type dlcrnet_ms5**

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by DuanWei-fudan** [comment]
And when I search the help documentaion with help(deeplabcut.create_multianimaltraining_dataset)
It shows the type of network was supported:
**net_type: string
        Type of networks. Currently resnet_50, resnet_101, and resnet_152, efficientnet-b0, efficientnet-b1, efficientnet-b2, efficientnet-b3,
        efficientnet-b4, efficientnet-b5, and efficientnet-b6 as well as dlcrnet_ms5 are supported (not the MobileNets!).**

**Comment by MMathisLab** [comment]
If you pass DLCRNet to create the dataset, yes the pose-cfg config file will still say resnet-50, - so this is as expected (but I agree annoying cc @jeylau as discussed in internal meetings; we should consider changing :)

**Comment by DuanWei-fudan** [comment]
So it still works with DLCRNet? Just ignore it and continue my training?

**Comment by jeylau** [comment]
@DuanWei-fudan, you should normally see `multi_stage=True` in your config. ☺️

**Comment by JianzhiZhang1** [comment]
hei, Have you solved this problem?I encountered the same problem.
![image](https://user-images.githubusercontent.com/103829351/167052672-5e1a05d6-6164-40ef-b059-1a18173df6c9.png)

**Comment by DuanWei-fudan** [comment]
Sorry for that. I can't use the _dlcrnet_ms5_ right now.The DLC still loads the _ImageNet-pretrained resnet_50_.
![image](https://user-images.githubusercontent.com/75257822/211964669-e19a2ff5-b564-4376-9282-9a5ce15d585f.png)

**Comment by DuanWei-fudan** [comment]
@jeylau 
 Amazing work for tracing mutil-animals!
I believe it will be widely used!

**Comment by MMathisLab** [comment]
> Sorry for that. I can't use the _dlcrnet_ms5_ right now.The DLC still loads the _ImageNet-pretrained resnet_50_. ![image](https://user-images.githubusercontent.com/75257822/211964669-e19a2ff5-b564-4376-9282-9a5ce15d585f.png)

It SHOULD load the resnet_50; this is pretrained on ImageNet, and we modify it to build DLCRNet (DLC-resnet), so it says "multi-satege = true" in the pose_cfg.yaml file for model. So you are 100% using DLCRNet
