### ISSUE TITLE
UserGuide seems to have conflicting recommendations

### ISSUE THREAD

**Issue by poja** [DeepLabCut/DeepLabCut#1696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

The `UseOverviewGuide` seems to have two recommendations regarding: "I have single animal videos, but I want to use" [DLC 2.2 features]. Also one of the recommendation has a typo (`False`) :)
So maybe there should be a more consistent way of deciding if to use `multianimal`?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@poja the typo is wrong, thank you, we will fix it! But, the other aspect is correct: if you want to use mutli-animal network features, such as PAFs, you need to set `multianimal: True`; then just label 1 individual.
