### ISSUE TITLE
AttributeError: module 'deeplabcut' has no attribute 'label_frames'

### ISSUE THREAD

**Issue by bertugilk** [DeepLabCut/DeepLabCut#1697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

AttributeError: module 'deeplabcut' has no attribute 'label_frames'  

![Ekran Alıntısı](https://user-images.githubusercontent.com/48621020/154999840-149fce85-e474-4627-b406-3bd4caae3bc1.JPG)

Command doesn't work in google colab so I can't labeled data.

I am using the codes in the link below.

https://github.com/ryanloney/dog-pose-estimation/blob/main/DLC_TrainNetwork_VideoAnalysis.ipynb

### Operating System

Windows 10

### DeepLabCut version

2.2.0.6

### DeepLabCut mode

single animal

### Device type

gpu

### Relevant log output

```shell
AttributeError                            Traceback (most recent call last)
<ipython-input-12-a20ca1232f3e> in <module>()
      1 get_ipython().magic('gui wx')
----> 2 deeplabcut.label_frames(path_config_file)

AttributeError: module 'deeplabcut' has no attribute 'label_frames'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @bertugilk, you cannot use the GUI in Colab (as it is sort of a remote machine without display hosted by Google); you need to label data locally first (as warned in the notebook cell), then upload your project to your Drive to train/evaluate your network and analyze your videos.

**Comment by metincanisik** [comment]
For anyone having a similar issue running in the Jupyter notebook, it is solved for me after installing the related gui library with  pip install -U wxPython

**Comment by 2751abc** [comment]
<img width="462" alt="image" src="https://user-images.githubusercontent.com/97718220/163384250-e6a832f8-686d-468c-89e3-61011ab6a759.png">

I have the same question and I am already install wxpython,
<img width="449" alt="image" src="https://user-images.githubusercontent.com/97718220/163384522-3949c7af-4656-4915-b89a-b905987494c7.png">


when i run the 'dlc.label_frames(config_path)',the python prompt window can not show ,the dlc gui .
and i have already run

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/97718220/163384636-b26f7202-e04d-4492-9a4d-b715d9fcfa33.png">


this programe before
