### ISSUE TITLE
Installation Problem - Illegal Instruction (TensorFlow and CPU mismatch)

### ISSUE THREAD

**Issue by AnnetGeorge** [DeepLabCut/DeepLabCut#170]
**Your Operating system and DeepLabCut version**
Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut2.x 

**Describe the problem**

I recently installed deeplabcut for use with the CPU using the instructions on the installation guide (created an environment for Python 3.6, installed deeplabcut, wxPython and tensorflow) All these tools were correctly installed as when I try to install them again, I receive a message saying the requirement is already satisfied.
However when I open ipython in the environment and type import deeplabcut, I get the following error message. 

"Illegal instruction (core dumped)"

**How to Reproduce the problem**
1. Run ipython in the virtual environment
2. import deeplabcut

**Comment by MMathisLab** [comment]
Which version of python, and tensorflow? How do you know they where correctly installed? I can’t reproduce the error with these instructions. Can you import and package? Import numpy for example?

**Comment by AlexEMG** [comment]
This is most likely a TensorFlow problem, try to narrow it down by importing only specific packages. See e.g. https://github.com/tensorflow/tensorflow/issues/17411

Check in particular if AVX is supported by your CPU, see https://github.com/tensorflow/tensorflow/issues/17411#issuecomment-426521095
