### ISSUE TITLE
`Getlistofvideos` returns `[]` when given a directory as a string

### ISSUE THREAD

**Issue by sneakers-the-rat** [DeepLabCut/DeepLabCut#1703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

If a `'string'` rather than a `['string']` in a list is passed to `auxiliaryfunctions.Getlistofvideos`, it isn't coerced before the check for being a directory, so it checks if each character in the string is a directory instead:

https://github.com/DeepLabCut/DeepLabCut/blob/63e65bcce1a5ff15adf324465392320f8174f5c7/deeplabcut/utils/auxiliaryfunctions.py#L326

and since that check fails, and so will the `os.path.isfile` that follows, an empty list is returned silently. 

Additionally, the `videotype` is applied inconsistently, and needs to be supplied even when it is unnecessary: eg. if someone supplies a list of `.mp4` videos, they need to provide the extension even though it isn't used, which complicates the functions that wrap it.

The function also changes the working directory unnecessarily, which is causing some unexpected behavior when some folks in my lab use it.

The simplest way I think of fixing without changing behavior would be to 
* coerce to list if string
* make optional videotype, but require if given a directory,
* if given directory, get list of videos first,
* otherwise do all filtering in same step at end of function

Will submit a PR in a second. 

### Operating System

Should be crossplatform? but i'm on a mac

### DeepLabCut version

pulled latest version of `main`, which is `63e65bc` at the moment

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

```python
>>> import os
>>> [os.path.isdir(i) for i in '/home/user/video_dir']
[True,
 False,
 False,
 ...]
```

### Relevant log output

```shell
(remotely debugging some problems my labmates are having, so i don't have stdout)
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by sneakers-the-rat** [comment]
PR here: https://github.com/DeepLabCut/DeepLabCut/pull/1704 feel free to edit however <3

**Comment by jeylau** [comment]
#1704 has now been merged! 😃
