### ISSUE TITLE
Videos with identical names trying to use same symlink path in videos folder

### ISSUE THREAD

**Issue by m-col** [DeepLabCut/DeepLabCut#1705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello,

I have added a number of videos to my project using `create_new_project` and subsequently `add_new_videos`. Many of my videos use the same name, as the data organisation is largely done at the folder name level, rather than file names. While my config.yaml contains the full paths to all of the videos as expected, the symlinks in the `videos/` folder seem to have overwritten each other so I am only left with 1 for each unique name pointing to the last video added using that name.

Is this a problem? What purpose do these symlinks have, as they seem to be redundant with the paths in config.yaml?

### Operating System

Ubuntu

### DeepLabCut version

2.2.0.3

### DeepLabCut mode

single animal

### Device type

nvidia gpu

### Anything else?

There are no errors, so everything does _appear_ to work as expected. However it could be a hidden problem, such as only extracting frames from only a subset of the videos that I expect them to be extracted from (I don't think I'd notice this easily as my videos all look very similar).

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Yes, that would be an issue, as we expect videos to have unique names throughout the code.

**Comment by m-col** [comment]
Might there be a workaround for this that wouldn't involve renaming all of my past videos? Such as creating symlinks with an incrementing suffix when an existing symlink exists with a given file name?
