### ISSUE TITLE
Analyze Videos: Python Error "File dialog failed with error code 3003"

### ISSUE THREAD

**Issue by tarafoley** [DeepLabCut/DeepLabCut#1707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

After updating my DLC version this week to the newest v2.2, I get an error when trying to select more than 2,500 videos (~2.2 million frames). It says "File dialog failed with error code 3003". Before the update, I would occasionally have this error when selecting videos, but it could easily be fixed with a DLC restart. 

### Operating System

Windows 11

### DeepLabCut version

Changed from v2.2.0.1 (where the projects were trained) to v2.2.0.2

### DeepLabCut mode

single animal

### Device type

NVIDIA GeForce RTX 3060 (Game Ready Driver)

### Steps To Reproduce

1.) Enter the DLC environment
2.) Open Python then the DLC GUI
3.) Open a project which has been trained on about 400 frames
4.) Click the Analyze Videos tab and attempt to add >2,500 videos (or ~2.2 million frames)
5.) Popup window appears saying "Python Error: File dialog failed with error code 3003."

### Relevant log output

```shell
I'm sorry I can't figure out how to get the logs output, but nothing appears in the python terminal window.
```

### Anything else?

I have to analyze tens of thousands of videos for each project so being able to add these videos in larger batches would help me greatly. Thank you for your time and assistance.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@tarafoley could could pass just the folder, not all the videos; then anything in the folder that does not have a corresponding DLC output would be analyzed. If this is over many folders, I would suggest you run this as a bash script such as this: https://github.com/DeepLabCut/DLCutils/blob/master/SCALE_YOUR_ANALYSIS/scale_analysis_oversubfolders.py
Otherwise, sorry, this is not something we can debug.
