### ISSUE TITLE
3D analysis failing at triangulate, likely calibration errors (check_undistorted weird). But corners correctly detected.

### ISSUE THREAD

**Issue by juliencarponcy** [DeepLabCut/DeepLabCut#1709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

The code is failing at the triangulate level, after sucessfully analyzing both 2D vids.

I nevertheless think that the problem is in the calibration. Corners are detected fine and I curated the folder to leave only the images where the corneres are detected from both angles. Detection looks fine, but check_undistortion gives very weird outputs.
I have one camera on the side, and one in front-down to the mice. You can see the other objectives on the example corner image below.

![image](https://user-images.githubusercontent.com/41296546/156042085-bb293d33-c9af-4697-8826-b2c1bae98774.png)

I have this weird outputs of the check undistortion.

![image](https://user-images.githubusercontent.com/41296546/156042201-94979386-120d-4f46-a581-2a04f767a434.png)

I run on the notebook the following lines:

```
config_path3d = deeplabcut.create_new_project_3d('2cam_Rig2','julien',num_cameras = 2)
deeplabcut.calibrate_cameras(config_path3d, cbrow=4, cbcol=6, calibrate=False, alpha=0.9)
```
then
```
deeplabcut.calibrate_cameras(config_path3d, cbrow=4, cbcol=6, calibrate=True, alpha=0.9)
```
This gave the dodgy outputs (No ref present in the docs, might be good to add what is expected after this stage)
```
deeplabcut.check_undistortion(config_path3d, cbrow=4, cbcol=6)
```
```
video_path = '/home/MRC.OX.AC.UK/phar0732/ettin/Data/head-fixed/videos/3D_unscored'
deeplabcut.triangulate(config_path3d, video_path, videotype='mp4', filterpredictions=False)
```

and I got the resulting error message (inserted below in dedicated section)

### Operating System

Ubuntu 20.04 LTS

### DeepLabCut version

dlc version 2.2.0.6

### DeepLabCut mode

3d

### Device type

Nvidia RTX 3090

### Steps To Reproduce

All 3 configs in the .zip file:
[ConfigsDLC.zip](https://github.com/DeepLabCut/DeepLabCut/files/8155988/ConfigsDLC.zip)

Folder screenshot:
![image](https://user-images.githubusercontent.com/41296546/156044962-04e7a1d2-f42e-41ad-8601-59e338635d58.png)

1. With the supplied conda environment,
2. on a notebook
3. I have previously extracted frames with ffmpeg and only selected the ones with full checkckerboard on both cams
4. did the calibrate cameras without calibration, 
5. checked and curated the resulting corners files
6. run again with calibration True
7. executed Triangulate, 
8. Failed with below error message after sucessfully analyzing both 2D vids.

### Relevant log output

```shell
List of pairs: [['/home/MRC.OX.AC.UK/phar0732/ettin/Data/head-fixed/videos/3D_unscored/JC282LS_2021-11-18_11-41-13.000_Rig_1_camera-1.mp4', '/home/MRC.OX.AC.UK/phar0732/ettin/Data/head-fixed/videos/3D_unscored/JC282LS_2021-11-18_11-41-13.000_Rig_1_camera-2.mp4']]
Analyzing video /home/MRC.OX.AC.UK/phar0732/ettin/Data/head-fixed/videos/3D_unscored/JC282LS_2021-11-18_11-41-13.000_Rig_1_camera-1.mp4 using config_file_camera-1
Using snapshot-1200000 for model /home/MRC.OX.AC.UK/phar0732/ettin/Models/down-julien-2022-02-23/dlc-models/iteration-0/downFeb23-trainset95shuffle1

2022-02-28 18:21:37.266604: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3090 computeCapability: 8.6
coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 23.70GiB deviceMemoryBandwidth: 871.81GiB/s
2022-02-28 18:21:37.267686: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 1 with properties: 
pciBusID: 0000:81:00.0 name: NVIDIA GeForce RTX 3090 computeCapability: 8.6
coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 23.70GiB deviceMemoryBandwidth: 871.81GiB/s
2022-02-28 18:21:37.270469: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0, 1
2022-02-28 18:21:37.270553: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-02-28 18:21:37.270559: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 1 
2022-02-28 18:21:37.270563: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N N 
2022-02-28 18:21:37.270566: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 1:   N N 
2022-02-28 18:21:37.272459: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 21481 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:01:00.0, compute capability: 8.6)
2022-02-28 18:21:37.273674: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 22312 MB memory) -> physical GPU (device: 1, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:81:00.0, compute capability: 8.6)

Starting to analyze %  /home/MRC.OX.AC.UK/phar0732/ettin/Data/head-fixed/videos/3D_unscored/JC282LS_2021-11-18_11-41-13.000_Rig_1_camera-1.mp4
The videos are analyzed. Now your research can truly start! 
 You can create labeled videos with 'create_labeled_video'
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
/home/MRC.OX.AC.UK/phar0732/ettin/Data/head-fixed/videos/3D_unscored JC282LS_2021-11-18_11-41-13.000_Rig_1_camera-1 DLC_resnet50_downFeb23shuffle1_1200000
Analyzing video /home/MRC.OX.AC.UK/phar0732/ettin/Data/head-fixed/videos/3D_unscored/JC282LS_2021-11-18_11-41-13.000_Rig_1_camera-2.mp4 using config_file_camera-2
Using snapshot-1030000 for model /home/MRC.OX.AC.UK/phar0732/ettin/Models/side_2_hands-julien-2022-01-05/dlc-models/iteration-1/side_2_handsJan5-trainset95shuffle1

2022-02-28 18:21:40.720525: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3090 computeCapability: 8.6
coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 23.70GiB deviceMemoryBandwidth: 871.81GiB/s
2022-02-28 18:21:40.721540: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 1 with properties: 
pciBusID: 0000:81:00.0 name: NVIDIA GeForce RTX 3090 computeCapability: 8.6
coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 23.70GiB deviceMemoryBandwidth: 871.81GiB/s
2022-02-28 18:21:40.724212: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0, 1
2022-02-28 18:21:40.724265: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-02-28 18:21:40.724270: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 1 
2022-02-28 18:21:40.724274: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N N 
2022-02-28 18:21:40.724277: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 1:   N N 
2022-02-28 18:21:40.726074: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 21481 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:01:00.0, compute capability: 8.6)
2022-02-28 18:21:40.727195: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 22312 MB memory) -> physical GPU (device: 1, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:81:00.0, compute capability: 8.6)

Starting to analyze %  /home/MRC.OX.AC.UK/phar0732/ettin/Data/head-fixed/videos/3D_unscored/JC282LS_2021-11-18_11-41-13.000_Rig_1_camera-2.mp4
The videos are analyzed. Now your research can truly start! 
 You can create labeled videos with 'create_labeled_video'
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
/home/MRC.OX.AC.UK/phar0732/ettin/Data/head-fixed/videos/3D_unscored JC282LS_2021-11-18_11-41-13.000_Rig_1_camera-2 DLC_resnet50_side_2_handsJan5shuffle1_1030000
Undistorting...

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/tmp/ipykernel_2980235/1195822122.py in <module>
      1 video_path = '/home/MRC.OX.AC.UK/phar0732/ettin/Data/head-fixed/videos/3D_unscored'
----> 2 deeplabcut.triangulate(config_path3d, video_path, videotype='mp4', filterpredictions=False)

~/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_3d/triangulation.py in triangulate(config, video_path, videotype, filterpredictions, filtertype, gputouse, destfolder, save_as_csv)
    300                 stereomatrix,
    301                 path_stereo_file,
--> 302             ) = undistort_points(
    303                 config, dataname, str(cam_names[0] + "-" + cam_names[1])
    304             )

~/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_3d/triangulation.py in undistort_points(config, dataframe, camera_pair)
    451     if True:
    452         # Create an empty dataFrame to store the undistorted 2d coordinates and likelihood
--> 453         dataframe_cam1 = pd.read_hdf(dataframe[0])
    454         dataframe_cam2 = pd.read_hdf(dataframe[1])
    455         scorer_cam1 = dataframe_cam1.columns.get_level_values(0)[0]

IndexError: list index out of range
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
alpha=0.9 needs to be validated; you should run without calibrate=True until you get results that look appropriate. That being said, our 3D supports cameras in stereo mode, i.e. on the same plane, next to each other; yours appear not to be in a configuration we support. The user guide explains this and other suggestions if the conditions are not met: https://deeplabcut.github.io/DeepLabCut/docs/Overviewof3D.html?highlight=3d

and in the DEMO the camera angles are, I think, clear: https://github.com/DeepLabCut/DeepLabCut/blob/a70c9b7cab8cbad6a5014e4b07d9e35deead729c/examples/JUPYTER/Demo_3D_DeepLabCut.ipynb

**Comment by juliencarponcy** [comment]
Hello, 

I did run with calibrate = False on the first pass. And I checked that everything was correctly detected in corners and removed frames.

Regarding "_our 3D supports cameras in stereo mode, i.e. on the same plane, next to each other; yours appear not to be in a configuration we support_"

Checking the docs section, I can't find anything mentioning that clearly. Perhaps it would be good to add that clearly and bold at the beggining of the 3D section so other people don't make the same mistake and realize afterward that their camera placement will not be compatible with 3D DLC.

Between the 3 external options you describe Acinoset, Anipose and DLCconverterDLT, which one would you recomment as the simplest and most straightforward for my use case? Anipose look like a good fit. 

Any plans in a near to medium-term future to integrate cameras which are not in the same plan?

Thanks very much.

Julien

**Comment by MMathisLab** [comment]
hi Julien, sure I agree it could be more clear in the docs, but it is there, and I edited further (https://github.com/DeepLabCut/DeepLabCut/pull/1717): https://deeplabcut.github.io/DeepLabCut/docs/Overviewof3D.html?highlight=stereo

deeplabcut.calibrate_cameras(config_path3d, cbrow=8, cbcol=6, calibrate=True, alpha=0.9)

This computes the intrinsic and extrinsic parameters for each camera. A re-projection error is also computed using the intrinsic and extrinsic parameters which provide an estimate of how good the parameters are. The transformation between the two cameras are estimated and the **cameras are stereo calibrated**. Furthermore, the above function brings both the camera image plane to the same plane by computing the stereo rectification. These parameters are stored as a pickle file named as stereo_params.pickle under the directory camera_matrix.

But, I added the term higher up, and link to the code (which is where you could change this, if desired): https://github.com/DeepLabCut/DeepLabCut/pull/1717

**Comment by DukeMacrocat** [comment]
Hello, i have a problem with the 3D deeplabcut. on the calibration part i get errors although i follow the process guided  from {https://github.com/DeepLabCut/DeepLabCut/blob/a70c9b7cab8cbad6a5014e4b07d9e35deead729c/examples/JUPYTER/Demo_3D_DeepLabCut.ipynb} 

![2020](https://user-images.githubusercontent.com/106013071/199666782-51decf02-27ce-4a3c-b1f5-b2075fd67ae2.png)

Thank you.
