### ISSUE TITLE
how to calculate Mean Average Precision in our code

### ISSUE THREAD

**Issue by Jason66661010** [DeepLabCut/DeepLabCut#1710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I want to calculate the **Mean Average Precision** and **Multi-Object Tracking Accuracy** to see whether the model performs well in my own dataset.

I have read the paper "Multi-animal pose estimation and tracking with DeepLabCut" and in the paper you use mAP and MOTA to evaluate the performance, but I didn't find the code or command to calculate in our project(deeplabcutv2.2rc3)

thanks for your help! :)

### Operating System

WIN10

### DeepLabCut version

v2.2rc3

### DeepLabCut mode

multi animal

### Device type

GPU

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hello @Jason66661010! The code to evaluate MOTA isn't part of the public-facing API; it requires human-annotated videos to evaluate how well animals are tracked, which is a very rare use-case. However, mAP is automatically calculated after network evaluation.
https://github.com/DeepLabCut/DeepLabCut/blob/ac547cbcdd4f5109b711875b481c1ac86222987c/deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py#L558
You will need to update DLC though, as it was only formally added after RC3.
You could call `cross_validate_paf_graphs()` separately too: the only thing you need is to pass your project config, the inference config found under dlc-models/test/inf_config.yaml, and the _full and _meta.pickle that are in the evaluation-results folder. Multiple graphs of increasing size will be evaluated, and mAP for each one will be written to a _map.pickle file. If you'd like lower level access, it is just a bit more complicated: have a look at these two functions https://github.com/DeepLabCut/DeepLabCut/blob/ac547cbcdd4f5109b711875b481c1ac86222987c/deeplabcut/pose_estimation_tensorflow/lib/crossvalutils.py#L254
https://github.com/DeepLabCut/DeepLabCut/blob/ac547cbcdd4f5109b711875b481c1ac86222987c/deeplabcut/pose_estimation_tensorflow/lib/inferenceutils.py#L955
The latter is to convert your annotated data (typically the CollectedData.h5 in training-datasets) into assemblies, which are then passed to `evaluate_assembly`. I hope this helps ☺️

**Comment by Jason66661010** [comment]
Hi @jeylau !
Thanks for your reply! I really appreciate your advice and help, however, I still have some questions to trouble you.

For mAP, I just updated my DLC to 2.2.0.6. After the network evaluation, I found out this result in the _map.pickle file:
![Snipaste_2022-03-01_22-09-04](https://user-images.githubusercontent.com/47680845/156320731-fb95b085-25ac-4c9c-9d35-b8d89d42e8bd.jpg)
![image](https://user-images.githubusercontent.com/47680845/156321549-3e54bdec-f219-4239-95fd-df681e514231.png)

1. I had each rat marked with 8 points, so there are 28 limbs totally. I just want to know whether the ten limbs in the first line in the first image are components of the best skeleton.

2. Also I wander the specific meaning of numbers for each limb in the second image.

For MOTA, can you share the code which calculate the MOTA in the paper so that I can learn the strategy more specifically?

Thank you again for your precious time and your help!😀

**Comment by MMathisLab** [comment]
@Jason66661010, to the second part of your question, the code for reproducing main parts of the pending paper is here (the paper is not published yet): https://github.com/DeepLabCut/maDLC_NatureMethods2022

**Comment by Jason66661010** [comment]
Still, I want to ask the meaning of the numbers in the first line when calculating the mAP(during the model evaluation).
 
![image](https://user-images.githubusercontent.com/47680845/156953886-09757f4a-feff-4035-8df9-65daa6fd0fd3.png)
Just like the result from my own dataset(using 8 points to label rats and obtain 28 limbs)
![image](https://user-images.githubusercontent.com/47680845/156954124-a20c7848-7e36-46a2-b86d-53715b05a12d.png)

Thanks for your help!!

**Comment by jeylau** [comment]
Hey @Jason66661010, as mentioned above, these are the sizes of the multiple graphs (i.e., skeletons) that are evaluated. By default, we evaluate 10 that are increasingly large (redundant); the last one being the fully connected graph (in your case for example, 8 keypoints give 28 possible undirected edges). I hope that helps!

**Comment by Jason66661010** [comment]
Hi @jeylau , I can't thank you more for your precious help! 
Have a nice day! 😀

**Comment by Jason66661010** [comment]
hello, I want to calculate the oks mAP of each output video.  I use "parse_ground_truth_data_file(h5_file)"function to convert my annotated data ( CollectedData.h5) into assemblies. However, the result is like this:
![image](https://user-images.githubusercontent.com/47680845/163919732-a5432324-c769-4d14-9b5d-b35e50b72dbf.png)

Also, after the conversion, what should I send into the evaluate_assembly() function?
