### ISSUE TITLE
Analyze_videos() function doesn't work properly - Human model

### ISSUE THREAD

**Issue by gokcergun** [DeepLabCut/DeepLabCut#1718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I want to make inference using your pre-trained human model. 
I've created the project using dlc.create_pretrained_project() functions. 
Then, I've run dlc.analyze_videos() function to make inference on .mp4 videos. 
 The function runs without an error message, but it doesn't analyze all frames and at the end it doesn't create .h5 file. 
I tried it also videos with .avi extention. The result is the same. 
Please see attached image. 
<img width="943" alt="analyze_videos_bug" src="https://user-images.githubusercontent.com/7740778/157459810-52a374e2-0db0-40d8-b4b8-71eea2649535.PNG">

dlc.create_pretrained_project() function creates a single-animal project. I converted it to a multi-animal project by changing the config file. The output of analyze_videos() function is same for both  single-animal and multi-animal projects.   

### Operating System

Windows 10

### DeepLabCut version

DeepLabCut verion: '2.2.0.6'

### DeepLabCut mode

single animal

### Device type

GPU - Quadro P5000

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by gokcergun** [comment]
I think the problem was that the frame size of the videos (4000x2800). 
I've resized the frames (1400x980) and created another video from those frames. Then it works fine with single-animal project. 
Multi-animal project also analyze videos but it creates a single animal output.

**Comment by MMathisLab** [comment]
our human model is only trained for single human detection, but glad it's fixed!
