### ISSUE TITLE
Low-Res Labeled Video, cannot extract_outlier, no frames to 'refine_labels'

### ISSUE THREAD

**Issue by rhgoo** [DeepLabCut/DeepLabCut#1721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

1. After analyzing a video, I created a labeled video to visualize my network but it outputted a very low-res/choppy video (see attached screenshot)
![Screenshot 2022-03-11 112640](https://user-images.githubusercontent.com/86977704/157907645-de57e115-5aa0-41e1-a9ab-d879b905044e.png)
Code ran: `deeplabcut.create_labeled_video(config_path, [r'C:\Users\SB11FLPC008\Documents\DeepLabCut\projects\Nov222021-richard-2021-11-22\videos\ChR5_2secstim_prog3-02162022123733-0000.avi'], videotype='.mp4', filtered=True,save_frames=True)`

2. Ran `deeplabcut.refine_labels(config_path)`, successfully opened the GUI, clicked "Load Labels" but there were no frames to refine. All folders within "labeled-data" appeared empty even though there were extracted frames, a .h5, and and a .csv file

### Operating System

Windows 10

### DeepLabCut version

2.2.03

### DeepLabCut mode

single animal

### Device type

GPU: NVIDIA GeForce RTX 3070
CPU: Intel(R) Xeon(R) W-2223 CPU @ 3.60GHz

### Steps To Reproduce

1. create_labeled_video()
`deeplabcut.create_labeled_video(config_path, [r'C:\Users\SB11FLPC008\Documents\DeepLabCut\projects\Nov2220
    ...: 21-richard-2021-11-22\videos\ChR5_2secstim_prog3-02162022123733-0000.avi'], videotype='.mp4', filtered=Tru
    ...: e,save_frames=True)'
2. refine_labels()
'deeplabcut.refine_labels(config_path)'

### Relevant log output

```shell
Labeled Video
Starting to process video: C:\Users\SB11FLPC008\Documents\DeepLabCut\projects\Nov222021-richard-2021-11-22\videos\ChR5_2secstim_prog3-02162022123733-0000.avi
Loading C:\Users\SB11FLPC008\Documents\DeepLabCut\projects\Nov222021-richard-2021-11-22\videos\ChR5_2secstim_prog3-02162022123733-0000.avi and data.
Duration of video [s]: 4.0, recorded with 249.94 fps!
Overall # of frames: 1000 with cropped frame dimensions: 480 346
Generating frames and creating video.
100%|██████████████████████████████████████████████████████████████████████████| 1000/1000 [03:57<00:00,  4.21it/s]
Labeled video C:\Users\SB11FLPC008\Documents\DeepLabCut\projects\Nov222021-richard-2021-11-22\videos\ChR5_2secstim_prog3-02162022123733-0000DLC_resnet50_Nov222021Nov22shuffle1_500000_filtered_labeled.mp4 successfully created.


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
HI @rhgoo - DLC doesn't change the video resolution at all actually; so you might consider checking the video, it might be corrupted. 

But, your steps are incorrect:

(1) `deeplabcut.create_labeled_video(config_path, [r'C:\Users\SB11FLPC008\Documents\DeepLabCut\projects\Nov222021-richard-2021-11-22\videos\ChR5_2secstim_prog3-02162022123733-0000.avi'], videotype='.mp4', filtered=True,save_frames=True)` <, here, you pass a .avi file, then say it's a .mp4; 

(2) you need to extract outliers BEFORE you refine... please see the workflow both in nature protocols paper, and here: https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html#j-optional-active-learning-network-refinement-extract-outlier-frames
