### ISSUE TITLE
train_network() -`FileNotFoundError: No such file: '....png'`

### ISSUE THREAD

**Issue by Duarte-Rodrigues** [DeepLabCut/DeepLabCut#1723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When running the function - `deeplabcut.train_network(path_config_file, shuffle=1, displayiters=100,saveiters=5000, maxiters=100000,allow_growth=True, max_snapshots_to_keep=5)` - the pose_cfg.yml file is loaded correctly, as well as, the training parameters and model. The iterations start smoothly, however at a certain random point, for no apparent reason the following error appears:

...

> iteration: 8600 loss: 0.0076 lr: 0.005
> iteration: 8700 loss: 0.0071 lr: 0.005
> iteration: 8800 loss: 0.0070 lr: 0.005
> iteration: 8900 loss: 0.0072 lr: 0.005
> Exception in thread Thread-3:
> Traceback (most recent call last):
>   File "D:\_users\Duarte\envs\DEEPLABCUT\lib\threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "D:\_users\Duarte\envs\DEEPLABCUT\lib\threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "D:\_users\Duarte\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 81, in load_and_enqueue
>     batch_np = dataset.next_batch()
>   File "D:\_users\Duarte\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\datasets\pose_imgaug.py", line 370, in next_batch
>     ) = self.get_batch()
>   File "D:\_users\Duarte\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\datasets\pose_imgaug.py", line 303, in get_batch
>     image = imread(
>   File "D:\_users\Duarte\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\auxfun_videos.py", line 359, in imread
>     image = io.imread(image_path)
>   File "D:\_users\Duarte\envs\DEEPLABCUT\lib\site-packages\skimage\io\_io.py", line 48, in imread
>     img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
>   File "D:\_users\Duarte\envs\DEEPLABCUT\lib\site-packages\skimage\io\manage_plugins.py", line 207, in call_plugin
>     return func(*args, **kwargs)
>   File "D:\_users\Duarte\envs\DEEPLABCUT\lib\site-packages\skimage\io\_plugins\imageio_plugin.py", line 10, in imread
>     return np.asarray(imageio_imread(*args, **kwargs))
>   File "D:\_users\Duarte\envs\DEEPLABCUT\lib\site-packages\imageio\__init__.py", line 86, in imread
>     return imread_v2(uri, format=format, **kwargs)
>   File "D:\_users\Duarte\envs\DEEPLABCUT\lib\site-packages\imageio\v2.py", line 159, in imread
>     with imopen(uri, "ri", plugin=format) as file:
>   File "D:\_users\Duarte\envs\DEEPLABCUT\lib\site-packages\imageio\core\imopen.py", line 162, in imopen
>     request = Request(uri, io_mode, format_hint=format_hint)
>   File "D:\_users\Duarte\envs\DEEPLABCUT\lib\site-packages\imageio\core\request.py", line 248, in __init__
>     self._parse_uri(uri)
>   File "D:\_users\Duarte\envs\DEEPLABCUT\lib\site-packages\imageio\core\request.py", line 388, in _parse_uri
>     raise FileNotFoundError("No such file: '%s'" % fn)
> FileNotFoundError: No such file: '\\files0\data\duteixei\My Documents\Duarte\3rd_withDS-Duarte-2022-03-11\labeled-data\HC_7_L_syncdownsampled\img2044.png'

### Operating System

Edition	Windows 10 Education
Version	21H2
Installed on	‎01-‎Mar-‎22
OS build	19044.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0

### DeepLabCut version

'2.2.0.6'

### DeepLabCut mode

single animal

### Device type

NVIDIA GeForce RTX 2060

### Steps To Reproduce

1. Use the GUI to create a new project with a video previously downsampled and ready to go
2. Label the frames and create the training set
3. Use a .ipynb to initalize the variables with the correct paths created 
4. And then run the above mentioned line - `deeplabcut.train_network(path_config_file, shuffle=1, displayiters=100,saveiters=5000, maxiters=100000,allow_growth=True, max_snapshots_to_keep=5)`

The error must appear after a few minutes of training
The notebook cell does not stop running and, after the error, if I stop it, the kernel of the notebook has to be restarted.

### Anything else?

The files with the information regarding the coordinates of the labeled images and the images themselves are in the correct directory.
I am using the conda installation, with VS code.
The image that it says is missing is not always the same. The iteration it breaks is not always the same. I could never get past the 18000 iteration, but I was aiming for 100000's.

Thank you for all the help you can give me.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Hi @Duarte-Rodrigues this means the img that is written into the training dataset is moved or deleted, i.e., it cannot be found. Please check to be sure that image is in the intended folder. If you think it's there, are you sure you not loosing access to another drive? i.e., are you running DLC on the D drive, or another one?

**Comment by Duarte-Rodrigues** [comment]
The DLC conda env is in the D:\ drive. I was running the example codes in another drive (K:\) and the project/training data I want to access is also there. But it is strange, since the first thousands of iterations can run smoothly, but all of the sudden, something happens and the image cannot be retrieved anymore! It is strange to lose access to the drive midway training, but it is a possible explanation.

The problem is, even if I want to run it as admin, I have to have the project on the C:\, but that is not very good because of the available space.

**Comment by aristotelis-economides** [comment]
Hello, thanks for the information. Can you try running your model on the same drive as your conda environment and let us know if the problem persists?

**Comment by jeylau** [comment]
Hello @Duarte-Rodrigues, is your problem solved?

**Comment by Duarte-Rodrigues** [comment]
Hello
As suspected, when running the model in a network drive, as I was doing, sometimes the connectivity is not very stable, and so, during the long training epochs, sometimes the connection breaks and the DLC loses access to the video frames.

My solution was to run the .ipynb files in the D:\ drive, because it is the local drive with more space. An important note is that the admin privileges are absolutely necessary to allow the creation of symbolic links, for it not to occupy all the memory of my D:\ disk. From my tests, it is also a second layer of assurance that the training doesn't fail midway.

After this, the rest of the functions ran smoothly.
Thank you for the help.

**Comment by jeylau** [comment]
Awesome to hear! 😃
