### ISSUE TITLE
Training in Colab

### ISSUE THREAD

**Issue by alexasoares** [DeepLabCut/DeepLabCut#1725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have created a project using the GUI. When I switch to Colab to train, there are no errors but it gets stuck on training. I run deeplabcut.train_network, it loads the config and overwrites max_iters/display_iters/save_iters, it says "Starting training..." and then nothing happens. The cell appears to be running, but nothing else shows up.

### Operating System

Windows 10 Home

### DeepLabCut version

2.2.0.6

### DeepLabCut mode

single animal

### Device type

Colab Pro GPU

### Steps To Reproduce

In Google Colab:

`!pip install deeplabcut
%reload_ext numpy
%reload_ext scipy
%reload_ext matplotlib
%reload_ext mpl_toolkits

!pip install --upgrade scikit-image
!pip3 install pickle5

import deeplabcut
import pickle5 as pickle

from google.colab import drive
drive.mount('/content/drive')

ProjectFolderName = 'TST-AS-2022-03-03'
VideoType = 'mp4'
videofile_path = ['/content/drive/My Drive/DLC/'+ProjectFolderName+'/videos/']
videofile_path
path_config_file = '/content/drive/My Drive/DLC/'+ProjectFolderName+'/config.yaml'
path_config_file

shuffle = 1
deeplabcut.create_training_dataset(path_config_file, net_type='resnet_50', Shuffles=[shuffle], augmenter_type='imgaug', windows2linux=True)

deeplabcut.train_network(path_config_file, shuffle=shuffle, displayiters=10,saveiters=50, maxiters=500000, allow_growth=True)`

### Relevant log output

```shell
Config:
{'all_joints': [[0], [1], [2]],
 'all_joints_names': ['tip', 'mid', 'butt'],
 'alpha_r': 0.02,
 'apply_prob': 0.5,
 'batch_size': 1,
 'clahe': True,
 'claheratio': 0.1,
 'crop_pad': 0,
 'crop_sampling': 'hybrid',
 'crop_size': [400, 400],
 'cropratio': 0.4,
 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_TSTMar3/TST_AS95shuffle1.mat',
 'dataset_type': 'imgaug',
 'decay_steps': 30000,
 'deterministic': False,
 'display_iters': 1000,
 'edge': False,
 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]},
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'histeq': True,
 'histeqratio': 0.1,
 'init_weights': '/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'lr_init': 0.0005,
 'max_input_size': 1500,
 'max_shift': 0.4,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_TSTMar3/Documentation_data-TST_95shuffle1.pickle',
 'min_input_size': 64,
 'mirror': False,
 'multi_stage': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 3,
 'optimizer': 'sgd',
 'pairwise_huber_loss': False,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'pos_dist_thresh': 17,
 'pre_resize': [],
 'project_path': '/content/drive/My Drive/DLC/TST-AS-2022-03-03',
 'regularize': False,
 'rotation': 25,
 'rotratio': 0.4,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'sharpen': False,
 'sharpenratio': 0.3,
 'shuffle': True,
 'snapshot_prefix': '/content/drive/My '
                    'Drive/DLC/TST-AS-2022-03-03/dlc-models/iteration-0/TSTMar3-trainset95shuffle1/train/snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Selecting single-animal trainer
Batch Size is 1
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
/usr/local/lib/python3.7/dist-packages/tf_slim/layers/layers.py:684: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  outputs = layer.apply(inputs, training=is_training)
Loading ImageNet-pretrained resnet_50
Max_iters overwritten as 500000
Display_iters overwritten as 10
Save_iters overwritten as 50
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': '/content/drive/My Drive/DLC/TST-AS-2022-03-03/dlc-models/iteration-0/TSTMar3-trainset95shuffle1/train/snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'sgd', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'imgaug', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': False, 'pairwise_predict': False, 'all_joints': [[0], [1], [2]], 'all_joints_names': ['tip', 'mid', 'butt'], 'alpha_r': 0.02, 'apply_prob': 0.5, 'clahe': True, 'claheratio': 0.1, 'crop_sampling': 'hybrid', 'crop_size': [400, 400], 'cropratio': 0.4, 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_TSTMar3/TST_AS95shuffle1.mat', 'decay_steps': 30000, 'display_iters': 1000, 'edge': False, 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]}, 'histeq': True, 'histeqratio': 0.1, 'init_weights': '/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt', 'lr_init': 0.0005, 'max_input_size': 1500, 'max_shift': 0.4, 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_TSTMar3/Documentation_data-TST_95shuffle1.pickle', 'min_input_size': 64, 'multi_stage': False, 'multi_step': [[0.005, 10000], [0.02, 430000], [0.002, 730000], [0.001, 1030000]], 'net_type': 'resnet_50', 'num_joints': 3, 'pos_dist_thresh': 17, 'pre_resize': [], 'project_path': '/content/drive/My Drive/DLC/TST-AS-2022-03-03', 'rotation': 25, 'rotratio': 0.4, 'save_iters': 50000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'sharpen': False, 'sharpenratio': 0.3, 'covering': True, 'elastic_transform': True, 'motion_blur': True, 'motion_blur_params': {'k': 7, 'angle': (-90, 90)}}
Starting training....
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
are you connected to a GPU runtime? Otherwise, CPU just takes much longer

**Comment by alexasoares** [comment]
Sorry I should've clarified - my computer just has a CPU but I'm using a GPU runtime in Colab. I've done it this way before with 2.2rc3 and training was much faster.

**Comment by MMathisLab** [comment]
the 2.2.0.x versions are actually much faster; but I meant in colab, can you show me a screenshot of how you connect to a GPU?

**Comment by kaylago** [comment]
I am having a similar issue! Screenshots of how I've been connecting to the Colab GPU are attached

![ConnectedtoGPU](https://user-images.githubusercontent.com/36450185/159259263-784ab152-7334-490c-9e29-57b24a28b174.png)
![ConnecttoColabGPU](https://user-images.githubusercontent.com/36450185/159259267-bd2385d1-d94a-4f0b-a5d9-1de0eec59258.png)

**Comment by MMathisLab** [comment]
ah, then sounds like a colab issue :( - I'll look into, but unfortunately we cannot control Colab

**Comment by alexasoares** [comment]
I'm using a Python 3 GPU
![image](https://user-images.githubusercontent.com/65625662/159372995-2a2ba6ab-fc65-41c4-937f-62c9994a61b0.png)

**Comment by alexasoares** [comment]
I also tried training on my CPU using the GUI, and the same thing is happening. I started training 10 hours ago and it's still not showing any progress.

`C:\WINDOWS\system32>conda activate DEEPLABCUT

(DEEPLABCUT) C:\WINDOWS\system32>python -m deeplabcut
2022-03-21 22:04:14.349798: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-03-21 22:04:14.352047: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Starting GUI...
The training dataset is successfully created. Use the function 'train_network' to start training. Happy training!
Selecting single-animal trainer
Config:
{'all_joints': [[0], [1], [2]],
 'all_joints_names': ['tip', 'mid', 'butt'],
 'alpha_r': 0.02,
 'apply_prob': 0.5,
 'batch_size': 1,
 'clahe': True,
 'claheratio': 0.1,
 'crop_pad': 0,
 'crop_sampling': 'hybrid',
 'crop_size': [400, 400],
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_TSTMar3\\TST_AS95shuffle1.mat',
 'dataset_type': 'imgaug',
 'decay_steps': 30000,
 'deterministic': False,
 'display_iters': 1000,
 'edge': False,
 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]},
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'histeq': True,
 'histeqratio': 0.1,
 'init_weights': 'C:\\Users\\alexa\\anaconda3\\envs\\DEEPLABCUT\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'lr_init': 0.0005,
 'max_input_size': 1500,
 'max_shift': 0.4,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_TSTMar3\\Documentation_data-TST_95shuffle1.pickle',
 'min_input_size': 64,
 'mirror': False,
 'multi_stage': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 3,
 'optimizer': 'sgd',
 'pairwise_huber_loss': False,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'pos_dist_thresh': 17,
 'pre_resize': [],
 'project_path': 'G:\\My Drive\\DLC\\TST-AS-2022-03-03',
 'regularize': False,
 'rotation': 25,
 'rotratio': 0.4,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'sharpen': False,
 'sharpenratio': 0.3,
 'shuffle': True,
 'snapshot_prefix': 'G:\\My '
                    'Drive\\DLC\\TST-AS-2022-03-03\\dlc-models\\iteration-0\\TSTMar3-trainset95shuffle1\\train\\snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Batch Size is 1
C:\Users\alexa\anaconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
C:\Users\alexa\anaconda3\envs\DEEPLABCUT\lib\site-packages\tf_slim\layers\layers.py:684: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  outputs = layer.apply(inputs, training=is_training)
2022-03-21 22:09:43.741189: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2022-03-21 22:09:43.742144: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-03-21 22:09:43.754861: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-41DSQLT
2022-03-21 22:09:43.755186: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-41DSQLT
2022-03-21 22:09:43.778610: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Loading ImageNet-pretrained resnet_50
Max_iters overwritten as 500000
Display_iters overwritten as 10
Save_iters overwritten as 50
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': 'G:\\My Drive\\DLC\\TST-AS-2022-03-03\\dlc-models\\iteration-0\\TSTMar3-trainset95shuffle1\\train\\snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'sgd', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'crop_pad': 0, 'scoremap_dir': 'test', 'batch_size': 1, 'dataset_type': 'imgaug', 'deterministic': False, 'mirror': False, 'pairwise_huber_loss': False, 'weigh_only_present_joints': False, 'partaffinityfield_predict': False, 'pairwise_predict': False, 'all_joints': [[0], [1], [2]], 'all_joints_names': ['tip', 'mid', 'butt'], 'alpha_r': 0.02, 'apply_prob': 0.5, 'clahe': True, 'claheratio': 0.1, 'crop_sampling': 'hybrid', 'crop_size': [400, 400], 'cropratio': 0.4, 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_TSTMar3\\TST_AS95shuffle1.mat', 'decay_steps': 30000, 'display_iters': 1000, 'edge': False, 'emboss': {'alpha': [0.0, 1.0], 'embossratio': 0.1, 'strength': [0.5, 1.5]}, 'histeq': True, 'histeqratio': 0.1, 'init_weights': 'C:\\Users\\alexa\\anaconda3\\envs\\DEEPLABCUT\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt', 'lr_init': 0.0005, 'max_input_size': 1500, 'max_shift': 0.4, 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_TSTMar3\\Documentation_data-TST_95shuffle1.pickle', 'min_input_size': 64, 'multi_stage': False, 'multi_step': [[0.005, 10000], [0.02, 430000], [0.002, 730000], [0.001, 1030000]], 'net_type': 'resnet_50', 'num_joints': 3, 'pos_dist_thresh': 17, 'pre_resize': [], 'project_path': 'G:\\My Drive\\DLC\\TST-AS-2022-03-03', 'rotation': 25, 'rotratio': 0.4, 'save_iters': 50000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25, 'sharpen': False, 'sharpenratio': 0.3, 'covering': True, 'elastic_transform': True, 'motion_blur': True, 'motion_blur_params': {'k': 7, 'angle': (-90, 90)}}
Starting training....`

**Comment by MMathisLab** [comment]
@alexasoares  your running DLC on C: and data is on G; idk windows well enough to know is this is part of the issue, but certainly TF isn't installed correctly for GPU or CPU:

```
2022-03-21 22:09:43.754861: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-41DSQLT
2022-03-21 22:09:43.755186: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-41DSQLT
2022-03-21 22:09:43.778610: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
```

**Comment by alexasoares** [comment]
Do you know how to fix TF? I installed DLC using the conda environment, I thought TF was included with that?

**Comment by backyardbiomech** [comment]
Try `conda install cudnn` in your env.

**Comment by kaylago** [comment]
I have a similar issue with running training on my CPU, and conda install cudnn did not fix it. I also tried to install cuda toolkit, and that did not solve the issue either.

![Screenshot 2022-03-22 211343](https://user-images.githubusercontent.com/36450185/159602434-992a2637-c2c7-4c73-9496-0ba9bdd66a23.png)

I've been looking into using google cloud or my university's cluster to run the training as well, but any suggestions to get it going on the CPU or colab would be great! Colab is still freezing at 'Starting training' just like the CPU

**Comment by kaylago** [comment]
I got Colab to work!!! After digging through various resources I figures out that my images were too big - I decreased the global scale in the pose_cfg file and so far everything is running on colab. @alexasoares you should try this and see if it fixes your issue

**Comment by Guillermo-Hidalgo-Gadea** [comment]
Thank you @kaylago! 
I am wondering by how much you decreased `global_scale`?

I was having the same issue on my local dlc environment with GPU RTX 3090 (see https://github.com/DeepLabCut/DeepLabCut/issues/1672#issuecomment-1076387656) and changing `max_input_size` to 2000 in the `pose_cfg.yaml` file did the trick for me without running out of memory (yet...?). 

Seems like the problem was related to https://github.com/DeepLabCut/DeepLabCut/issues/1620#issuecomment-1017935156 after all.

**Comment by jeylau** [comment]
I've pushed a fix! If we detect that images are too large, we'll interrupt training and raise an error inviting users to edit the config. This should clarify what is truly happening. 😌

**Comment by alexasoares** [comment]
I think I had the opposite problem - my images were too small, so I increased global_scale and it worked! Thanks @kaylago!!

**Comment by kaylago** [comment]
@Guillermo-Hidalgo-Gadea I dropped global_scale to 0.4 (so half) just to see if it would run, and because I had pretty big images anyways
