### ISSUE TITLE
Parallel progress bars for `make_labeled_video`

### ISSUE THREAD

**Issue by sneakers-the-rat** [DeepLabCut/DeepLabCut#1726]
**Is your feature request related to a problem? Please describe.**

I'm sitting here with the lab computer just in my peripheral vision and my labmate is analyzing some videos and the progress bar is flickering badly and it is distracting me. I think it would be nice to have progress bars for multiple processes display all at once instead of overlapping

**Describe the solution you'd like**

Unless there's something I'm missing, it would take
* setting a `Lock` for tqdm when the pool is initialized here https://github.com/DeepLabCut/DeepLabCut/blob/4a653bb9203691fa81a024bf6d3d9c6ad0660d72/deeplabcut/utils/make_labeled_video.py#L517
* identifying the process ID (or set as `0` when not run from `multiprocessing.Pool`) in the inner method that calls the progress bar
* setting that as the `position`

Here's a MWE:

```python
import multiprocessing as mp
import os
from time import sleep
import random
from tqdm.auto import tqdm, trange


def regular_pbar(idk):
    speed = random.random()*0.1
    for i in trange(100, leave=False):
        sleep(speed)

def parallel_pbar(whatevs):
    speed = random.random()*0.1
    proc = mp.current_process()
    id = proc._identity[0]-1

    for i in trange(100, 
        position=id,
        desc=f"Process {id:02d}",
        leave=False):
        sleep(speed)


if __name__ == "__main__":
    
    print('-'*20)
    print('parallel pbars')
    with mp.Pool(
            16, 
            initializer=tqdm.set_lock,
            initargs=(mp.Lock(),)) as pool:
        pool.map(parallel_pbar, range(16))

    print("\x1b[2J") 
    print('-'*20)
    print('regular pbars')
    with mp.Pool(16) as pool:
        pool.map(regular_pbar, range(16))

```

and here's how that looks:

![tqdm_paralell](https://user-images.githubusercontent.com/12961499/158442638-3f7e4b7d-2504-4680-822d-0ca33ba4bcae.gif)

**Comment by AlexEMG** [comment]
Sorry for the flickering @sneakers-the-rat!

**Comment by hmaarrfk** [comment]
In consider a solution for this problem, I would like to ask that a provision be made for not including a progress bar at all.

In many environments, the user may wish to use jupyter notebooks (which don't play well with the terminal based tqdm), a different environment where the terminal tqdm doesn't really work well. `trange` is convenient when working on your own, but I find it pretty tedious when it comes to integration time.

Finally, if you ever wish to present the users with a progress bar in the GUI (wx or Qt), you'll have to develope an other solution.

I've been playing around with solution to a similar problem in my own work. We pass a `tqdm-like` object constructor for the inner functions to call to report their progress. That said, it doesn't work well in this "pool" scenerio. Mainly it assumes that there is only one thread controlling the bar progress. Not infinitely many.
When the user doesn't want a progress bar, the argument `tqdm=None` is specified. We typically choose to have `tqdm=None` be the default.

```python
# Pseudocode
# Do not import tqdm
# from tqdm import tqdm
def tqdm_none(*_, **__):
    return _[0]

def my_super_long_function(list_to_analyse, *, tqdm=None):
    if tqdm is None:
        tqdm= tqdm_none
    for item in tqdm(list_to_analyse):
        # Do useful work
        pass

# Without progress bar
my_super_long_function(list(range(10)))
# With progress bar
from tqdm.notebook import tqdm as tqdm_i_really_want
my_super_long_function(list(range(10)), tqdm=tqdm_i_really_want)
```

**Comment by hmaarrfk** [comment]
on the other hand @sneakers-the-rat the progress bar you made is rather awesome

**Comment by sneakers-the-rat** [comment]
agreed not having pbars should be possible for downstream use. another strategy that doesn't involve needing to make a dummy iterator/the user needing to import tqdm in their script and pass it might be to have it be specified with a bool and then do something like this

```python
from tqdm import tqdm
from typing import Iterable

def some_function(iterate_me:Iterable, tqdm:bool = False):
    if tqdm:
        iterator = tqdm(iterate_me)
    else:
        iterator = iter(iterate_me)
        
    for item in iterator:
        # do stuff
        
        
        
```

**Comment by AlexEMG** [comment]
Fair enough, maybe good to be able to turn this off. Let's make an option and PR?

**Comment by MMathisLab** [comment]
closed due to being stale
