### ISSUE TITLE
Empty tracklets created during multi-animal training

### ISSUE THREAD

**Issue by charithaomprakash** [DeepLabCut/DeepLabCut#1727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I trained my network to detect two mice in my experiment but when I analyze videos it creates empty tracklets for videos recorded on two days of the experiment (it works for videos from all the other days). I followed what was suggested in previous posts, ie. save the videos using a video editor in a different format (used premier pro and ffmpeg to do this), and checked the integrity of the video and it created an empty log file. I also checked the assemblies pickle file and it is empty. I am unsure what the problem is and it would be wonderful to get some help regarding this issue. 

If required, I can share a google drive link with the video in question, integrity check log files and the pickle files.

### Operating System

Ubuntu 20.04

### DeepLabCut version

dlc version 2.2

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

deeplabcut GUI
1. select videos 
2. Analyze videos

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Hi @charithaomprakash glad to hear its working on all others; is there something very different about how these videos look?

**Comment by charithaomprakash** [comment]
No, unfortunately they look the same as the other videos; which is why I am unsure what is happening here. I tried tracking using single animal DLC and it works and tracks one mouse and creates videos and the csv but I would like to track both the mice in the video using maDLC

**Comment by jeylau** [comment]
@charithaomprakash, could you tell me what specific version of DLC you're using?

**Comment by charithaomprakash** [comment]
Hi, the specific version is 2.2.0.2

**Comment by charithaomprakash** [comment]
Hi, I also updated to the latest version of maDLC (2.2.0.6) and I still have an empty pickle file.

**Comment by jeylau** [comment]
@charithaomprakash, have you tried to use `deeplabcut.utils.make_labeled_video.create_video_with_all_detections` to check whether network predictions look good for that particular video?

**Comment by jeylau** [comment]
I'll close due to inactivity, but please feel free to reopen the issue if we can help you further ☺️
