### ISSUE TITLE
tiny feature request for evaluation matrix

### ISSUE THREAD

**Issue by WeissShahaf** [DeepLabCut/DeepLabCut#1728]
please add network type as a column in the evaluation matrix .csv file

**Is your feature request related to a problem? Please describe.**
no problem per say, but would help alot.

**Describe the solution you'd like**
net_type and string of network used

**Describe alternatives you've considered**
tried memorizing which iteration was which network. or manually going through each pose.cfg file to see which network it used

**Additional context**

**Comment by MMathisLab** [comment]
Hi @WeissShahaf there is a way to mark the shuffles, with a `modelprefix` although mostly used by our dev team; I will leave @AlexEMG explain it ;)

**Comment by WeissShahaf** [comment]
@MMathisLab thanks. that would mark the output files right? but still not in the eval matrix?

**Comment by jeylau** [comment]
`modelprefix` allows you to nest the dlc-models and evaluation-results folders within a parent directory whose name you choose. In other words, you can have multiple networks with e.g. varying training/evaluation params live under the same project, and it suffices to pass `modelprefix="name_parent_folder"` to tell DeepLabCut which one you want to train/evaluate. This is unambiguous, and guarantees that evaluation results files only contain data from that network type.
