### ISSUE TITLE
Issue on installing DeepLabCut on macOS Mojave

### ISSUE THREAD

**Issue by jpalma-espinosa** [DeepLabCut/DeepLabCut#173]
**Your Operating system and DeepLabCut version**
macOS Mojave v 10.14.2
python 3.7.1 installed with brew

**If applicable, please also complete the following information:**
Chrome Versión 71.0.3578.98 (Build official) (64 bits)
 
**Describe the bug**
I can't install DLC by using pip3.  
I installed hdf5 (brew install hdf5) and tables (pip install tables)
However, while installing, throws the following

```
Collecting tables==3.4.3 (from deeplabcut)
  Using cached https://files.pythonhosted.org/packages/98/bb/0192955689d2e5972e2714300433eff57e5bef4147248cb15c7b6f04ae9e/tables-3.4.3.tar.gz
    Complete output from command python setup.py egg_info:
    * Using Python 3.7.1 (default, Nov  6 2018, 18:46:03)
    * USE_PKGCONFIG: True
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/l2/0d6wkyh96n3d_s05ml6jy70w0000gn/T/pip-install-0dl49_pv/tables/setup.py", line 597, in <module>
        hdf5_version = get_hdf5_version(hdf5_header)
      File "/private/var/folders/l2/0d6wkyh96n3d_s05ml6jy70w0000gn/T/pip-install-0dl49_pv/tables/setup.py", line 350, in get_hdf5_version
        major_version = int(re.split("\s*", line)[2])
    ValueError: invalid literal for int() with base 10: 'd'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/l2/0d6wkyh96n3d_s05ml6jy70w0000gn/T/pip-install-0dl49_pv/tables/
```

**To Reproduce**
just do `pip3 install deeplabcut
`
**Expected behavior**
to get DLC installed :P

**Additional context**
No anaconda environment. Also, I tried installing on virtualenv.
Before I installed DLC, I upgraded setuptools by doing ` #pip install -U setuptools`

**Comment by jpalma-espinosa** [comment]
UPDATE: solved by downgrading to python 3.6

**Comment by MMathisLab** [comment]
actually, @jpalma-espinosa could I ask you to write a "how to install DLC on MacOS?"

**Comment by jpalma-espinosa** [comment]
@MMathisLab sorry, I was on holiday break.
SURE!!! I will start tonight!

**Comment by MMathisLab** [comment]
Oh no problem - I released a MacOS yaml file now ;) https://github.com/AlexEMG/DeepLabCut/tree/master/conda-environments

**Comment by jpalma-espinosa** [comment]
oh, im sorry. Anyway, i'll keep watching and using this package
