### ISSUE TITLE
Doubts in methodology of the use of deeplabcut 3d

### ISSUE THREAD

**Issue by Alberto100591** [DeepLabCut/DeepLabCut#1734]
Good afternoon, I am interested in using deeplabcut 3d, but I have some doubts. (I am new using deeplabcut)

1.- I am working on a Mac and the CAMCONTROL software only works on Windows 10, will you have any other option for Mac?

2.- Should I have the two videos individually processed in 2D and then apply the 3D methodology?

Thanks for the help

**Comment by aristotelis-economides** [comment]
> 2.- Should I have the two videos individually processed in 2D and then apply the 3D methodology?

Your videos do not need to be processed already, but you need to have 2D projects setup and models trained for your 2D videos. Then when you call `deeplabcut.triangulate()` they will be processed automatically.  See the [3D documentation, Step 4](https://deeplabcut.github.io/DeepLabCut/docs/Overviewof3D.html#triangulation-take-your-2d-to-3d) for more details.

Also, check out the [Nature Protocols Paper](https://www.nature.com/articles/s41596-019-0176-0).
