### ISSUE TITLE
Issues with Lasso Identity swap on Ubuntu DLC

### ISSUE THREAD

**Issue by eunkyuhodu** [DeepLabCut/DeepLabCut#1736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am using the Lasso function to swap identities between two animals.

I used the flag function to mark the start and the beginning of the time series.
Toggled Lasso, lassoed the tracklets I want to swap identities.

But when I click on the identity on the top of the Refine Tracklet GUI, this error appears:

AttributeError: can't set attribute. 

How would I solve this error? THhanks. 

### Operating System

Ubuntu 20.04.3 LTS 
Release 20.04

### DeepLabCut version

DLC 2.2.0.6

### DeepLabCut mode

multi animal

### Device type

NVIDIA-SMI 470.42.01
GeForce 3070

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by aristotelis-economides** [comment]
Hello, can you give us more information on how you are running DeepLabCut? Is it from a dedicated conda environment? It might be a matplotlib version issue. Also, can you send us the full error log, it makes things easier

**Comment by eunkyuhodu** [comment]
Hi I actually solved this problem by updating matplotlib.

Thanks!

Eunkyu
