### ISSUE TITLE
TypeError when using Refine Outliers

### ISSUE THREAD

**Issue by austin2118ace** [DeepLabCut/DeepLabCut#1743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I exctracted ~50 frames manually using the Extract Outliers GUI. When I clicked Launch GUI and attempted to load the machinelabels h5 file I get the traceback shown below. I completed a clean install of both the code, and the environment neither of which rectified the issue. I also double checked that the config file pointed to the correct video and the labels are also in the correct place. I saw this error on other time on our GPU compute cluster but a fresh install fixed it there. The same DLC installation was used to extract the labels as we tried to use to refine them. 

### Operating System

Windows 10

### DeepLabCut version

dlc version: 2.2.0.6

### DeepLabCut mode

single animal

### Device type

CPU

### Steps To Reproduce

1. Successfully Extract Outlier Frames
2. Launch the Outlier Labeling GUI using LAUNCH GUI
3. Select the machinelabels-iter0.h5 file in the appropriate labeled-data folder for our video
4. Get the stack trace below and the program locks up

### Relevant log output

```shell
`Traceback (most recent call last):
  File "C:\Users\dewanlab.PSY-PDB-C474-B\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\refinement.py", line 395, in browseDir
    self.Dataframe.sort_index(inplace=True)
  File "C:\Users\dewanlab.PSY-PDB-C474-B\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\dewanlab.PSY-PDB-C474-B\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\frame.py", line 6449, in sort_index
    return super().sort_index(
  File "C:\Users\dewanlab.PSY-PDB-C474-B\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\generic.py", line 4693, in sort_index
    indexer = get_indexer_indexer(
  File "C:\Users\dewanlab.PSY-PDB-C474-B\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\sorting.py", line 93, in get_indexer_indexer
    indexer = nargsort(
  File "C:\Users\dewanlab.PSY-PDB-C474-B\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\sorting.py", line 411, in nargsort
    indexer = non_nan_idx[non_nans.argsort(kind=kind)]
TypeError: '<' not supported between instances of 'str' and 'tuple'`
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by KonradDanielewski** [comment]
As far as I can follow the code it seems to never change strings into tuples at all, when using the merging via gui after tracklet refinement. Though I have a hard time following the gui code so I might be missing something.

A workaround I found is that you can just open machinelabels with refine_labels, move one of the labels so a change is detected and just save and quit. This will automatically merge datasets and it does work as intended spliting string and making a tuple. 

edit: so I did this in tracklet_toolbox.py and now it works. Also in `guarantee_multiindex_rows` function `[0]` was removed
![image](https://user-images.githubusercontent.com/54865575/160579104-14bb322e-abae-4589-aa07-aaae2f74343f.png)

**Comment by austin2118ace** [comment]
This error was occurring before merging the dataset. I was unable to refine the tracklets at all. I tried opening another machine labels file from a different project and it opened fine. When I loaded the other projects h5 file with pandas, all the file paths were converted to tuples. When I open the file I have trouble with, only index 0 was converted to a tuple, leaving us with the sorting error.

My understanding of the code was that gurantee_multiindex_rows takes any file system path xxx/yyy/z.z and converts paths a tuple form when the h5 file is saved/created so the paths robust across multiple operating systems. For some reason on my H5 file it only converted index 0 and not the other 49 frames.

**Comment by backyardbiomech** [comment]
For clarification, you are extracting outliers and trying to refine them on the same computer, in the same conda env, correct? 
I'm wondering if this is another tables issue. Can you get the version of tables in your env from `conda list`?

**Comment by austin2118ace** [comment]
I extracted outliers (~50 frames) and then immediately clicked the Launch GUI button, when attempting to load the H5 file that was created we get the stack trace above. It was done back to back all in the same environment. We even nuked the environment, deleted the cached packages, deleted the DLC code, and reinstalled everything just to make sure. I'm not in the lab at the moment, but later today I will edit this comment with the tables version. 

I manually ran through the H5 and gurantee_multindex_rows code in a local python environment to see if I could replicate the problem on some other machinelearning.h5 files from older projects. The code functioned properly on the other test files. It is specifically this one machinelearning.h5 file from our current project that wont open. For some reason on our current project, only the first frame's path was converted to a tuple and frames 1-49 still have the windows xxx/yyy/zzz path (I saw this when loading the H5 file manually with pandas). When it attempts to run **df.sort(inplace=True)** index 0 is a tuple and indices 1-49 are still strings which aren't comparable.


Edit: since we're stuck on this project anyways, I am going to attempt to reextract all the frames today and see if the issue persists. There was nothing about the extraction process that we did that was out of order or weird, but it would verify if this was some weird one time issue or a code issue.

Edit 2: Tables version is 3.6.1. Re-extracted all the frames and the same problem exists: index 0 has the tuple file path and the rest of the indexes are windows formatted

**Comment by austin2118ace** [comment]
Small update, I manually fixed my broken h5 file. I opened the file with pandas in python and exported all the indexes to a list, I then manually converted all the paths to the proper tuple format and rewrote the indexes to the h5 file. It now opens without any trouble in the refinement GUI. This is a good one-time fix so we can continue refinement and training, but I don't know what initially caused the problem. 

Edit: Guess I spoke too soon. The H5 file I "repaired" opened and allowed us to do all of the refinement, but when we clicked save it gave us a new error we haven't seen before. All of our manual adjustments were for sure inside of the image, so not sure why its thrown an error. I've attached the broken and my "repaired" h5 files.

`Checking labels if they are outside the image
Traceback (most recent call last):
  File "D:\DeepLabCut\deeplabcut\gui\refinement.py", line 725, in saveDataSet
    self.Dataframe = MainFrame.check_labels(self)
  File "D:\DeepLabCut\deeplabcut\gui\refinement.py", line 706, in check_labels
    self.Dataframe.loc[i, (self.scorer, bp, "x")] > width
  File "C:\Users\dewanlab.PSY-PDB-C474-B\Anaconda2\envs\DEEPLABCUT\lib\site-packages\pandas\core\generic.py", line 1534, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
`
[H5 Files.zip](https://github.com/DeepLabCut/DeepLabCut/files/8374761/H5.Files.zip)

**Comment by KonradDanielewski** [comment]
I just noticed (for some reason my brain skipped over it) my error happened with tracklets, yours with regular refinement. Anyway, reason seems to be the same. When you remove `[0]` from `guarantee_multiindex_rows` doesn't it solve your issue? Cause it seems it's only not converting that's an issue. Manually changing the file is a no-no here, cause something also happens when you load it and try to save it - EDIT: meaning I think it's trying to create another tuple and breakes it completely

**Comment by austin2118ace** [comment]
> 

I haven't tried removing the `[0]` from `guarantee_multiindex_rows` Wouldn't that break the entire function though since its relying on `path = index[0]` to create the splits? Or should `path = index` work just fine? I will attempt to do this later today. I will have to extract all the frames _again_ since the conversion code will not work on an h5 file that has index 0 already converted to a tuple

**Comment by KonradDanielewski** [comment]
Since index isn't a python list but a pandas object when you choose `[0]` it will only split the first one, but when it's just `index` it will split all indices. I don't quite follow why the `[0]` is there, maybe there are differences between OS'es?

**Comment by austin2118ace** [comment]
Removing the `[0]` index does not resolve the problem. It actually seems to cause an error when loading the config file.
It seems that it passes some other DataFrame to `gurantee_multiindex_rows` before anything is done.

However, I think I may have finally discovered the issue. When your initial frame is extracted, there is no H5 file created. So we go to line 397, this creates the first index for our first frame and writes it to the H5 file, however, it is not converted to a tuple yet. When frame 2 is extracted, we enter the main if statement, it loads the h5 file, and then converts everything in it to a tuple (e.g. only frame one) and then concats the other frames we have extracted and saves them to the h5 file with string paths. 

I have added the following line and it seems to be working now! It will convert all new paths to tuples before they are written to the H5 file. Refinement works as expected now, I can open the machine file, edit the labels, and save them and it generates the appropriate CollectedData file. Both lines seem to be needed. Trying to run the function with just `gurantee_multiindex_rows` on **DataCombined** runs into the issue where some of the data may be tuples already and some of it isn't and the function will throw an error.



![image](https://user-images.githubusercontent.com/3708103/161315240-f4820047-9cc2-4091-9863-3cc876bbeed2.png)

![image](https://user-images.githubusercontent.com/3708103/161317555-b0b15466-4dd6-42b5-83df-278e72515683.png)

Instead of using a conversion function for new paths, why are new paths not written as tuples by default? Using the conversion is necessary for backward compatibility with old files, but new paths can just be saved as tuples going forward. Yes?


Error from removing `[0]`
```
AttributeError: Can only use .str accessor with string values!
Traceback (most recent call last):
  File "C:\DeepLabCut\deeplabcut\gui\extract_outlier_frames.py", line 190, in extract_outlier_frames
    deeplabcut.extract_outlier_frames(
  File "C:\DeepLabCut\deeplabcut\refine_training_dataset\outlier_frames.py", line 358, in extract_outlier_frames
    outlier_frame_extraction_toolbox.show(
  File "C:\DeepLabCut\deeplabcut\gui\outlier_frame_extraction_toolbox.py", line 584, in show
    frame = MainFrame(
  File "C:\DeepLabCut\deeplabcut\gui\outlier_frame_extraction_toolbox.py", line 232, in __init__
    conversioncode.guarantee_multiindex_rows(self.Dataframe)
  File "C:\DeepLabCut\deeplabcut\utils\conversioncode.py", line 233, in guarantee_multiindex_rows
    splits = tuple(df.index.str.split(sep))
  File "C:\Users\Austin-PC\anaconda3\envs\deeplabcut\lib\site-packages\pandas\core\accessor.py", line 181, in __get__
    accessor_obj = self._accessor(obj)
  File "C:\Users\Austin-PC\anaconda3\envs\deeplabcut\lib\site-packages\pandas\core\strings\accessor.py", line 168, in __init__
    self._inferred_dtype = self._validate(data)
  File "C:\Users\Austin-PC\anaconda3\envs\deeplabcut\lib\site-packages\pandas\core\strings\accessor.py", line 225, in _validate
    raise AttributeError("Can only use .str accessor with string values!")
AttributeError: Can only use .str accessor with string values!
```

**Comment by KonradDanielewski** [comment]
Ye, I done some more testing and also found that it was leading to further errors down the line. I'll try out your solution when I have time

**Comment by KonradDanielewski** [comment]
Ye, I done some more testing and also found that it was leading to further errors down the line. I'll try out your solution when I have time

**Comment by GozuNaz** [comment]
Hey,
wanted to join the disscusion. I have the same/similiar issue after refining tracklets when I try to merge data.

```
Frames from video CTRL_KO_3  already extracted (more will be added)!
C:\Users\Tomek\anaconda3\envs\dlc\lib\site-packages\deeplabcut\gui\tracklet_toolbox.py:708: FutureWarning: inplace is deprecated and will be removed in a future version.
  df.columns.set_levels(
A training dataset file is already found for this video. The refined machine labels are merged to this data!
Traceback (most recent call last):
  File "C:\Users\Tomek\anaconda3\envs\dlc\lib\site-packages\deeplabcut\gui\refine_tracklets.py", line 268, in export_data
    self.viz.export_to_training_data()
  File "C:\Users\Tomek\anaconda3\envs\dlc\lib\site-packages\deeplabcut\gui\tracklet_toolbox.py", line 723, in export_to_training_data
    df_joint.sort_index(inplace=True)
  File "C:\Users\Tomek\anaconda3\envs\dlc\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Tomek\anaconda3\envs\dlc\lib\site-packages\pandas\core\frame.py", line 6447, in sort_index
    return super().sort_index(
  File "C:\Users\Tomek\anaconda3\envs\dlc\lib\site-packages\pandas\core\generic.py", line 4685, in sort_index
    indexer = get_indexer_indexer(
  File "C:\Users\Tomek\anaconda3\envs\dlc\lib\site-packages\pandas\core\sorting.py", line 94, in get_indexer_indexer
    indexer = nargsort(
  File "C:\Users\Tomek\anaconda3\envs\dlc\lib\site-packages\pandas\core\sorting.py", line 417, in nargsort
    indexer = non_nan_idx[non_nans.argsort(kind=kind)]
TypeError: '<' not supported between instances of 'tuple' and 'str'

```

**Comment by austin2118ace** [comment]
@KonradDanielewski had a chance to look over my fix?

**Comment by jeylau** [comment]
@austin2118ace @KonradDanielewski I'll test and push a fix later today. I'll get back to you once done 😃.
