### ISSUE TITLE
feature request: make video editor tab available outside of projects

### ISSUE THREAD

**Issue by WeissShahaf** [DeepLabCut/DeepLabCut#1748]
**Is your feature request related to a problem? Please describe.**
Ex. I'm always frustrated when [i need to downsample or shorten a video, i have to first load a project, though the two things are not necessarily connected]

**Describe the solution you'd like**
make the video editor tab always visible.

**Describe alternatives you've considered**
using ffmpeg directly in commandline, or using special softwares like Handbrake to downsample / shorten videos. 

**Additional context**

**Comment by MMathisLab** [comment]
Hey @WeissShahaf you mean in the GUI? Otherwise, you can run without loading any project:
```
deeplabcut.DownSampleVideo(
                    video,
                    width=-1,
                    height=self.height.GetValue(),
                    rotatecw=self.rotate_val,
                    angle=self.vangle.GetValue(),
                )
```
```
deeplabcut.ShortenVideo(
                    video,
                    start,
                    stop,
                )
```
```
 deeplabcut.CropVideo(
                  video, 
                  useGUI=True
               )
```

**Comment by WeissShahaf** [comment]
thanks,
i'll use those instead of the GUI
