### ISSUE TITLE
snapshot file saving during training (with >255 character long paths in windows)

### ISSUE THREAD

**Issue by guyts** [DeepLabCut/DeepLabCut#175]
Windows 10, Anaconda 3, DLC 2.0.3, DLC-windowsCPU env

I followed the installation instructions for CPU environment and started running the [demo for CPU](https://github.com/AlexEMG/DeepLabCut/blob/master/examples/Demo_labeledexample_MouseReaching.ipynb).

The first couple of steps seem to work fine (`deeplabcut.load_demo_data(path_config_file)` and `deeplabcut.check_labels(path_config_file)`), but a bit into the training phase (`deeplabcut.train_network(path_config_file, shuffle=1)`) I'm getting the following error: 

```
Failed to create a NewWriteableFile: D:\[...]\DeepLabCut\examples\Reaching-Mackenzie-2018-08-30\dlc-models\iteration-0\ReachingAug30-trainset95shuffle1\train\snapshot-100.data-00000-of-00001.tempstate15672210206235734816 : The system cannot find the path specified.
; No such process
```

I tried to look up the snapshot file in the directory but couldn't find one.
Do you know how to handle this issue?

**Comment by AlexEMG** [comment]
Interesting - never had seen this. [The path itself looks fine, so this should work] - however, some googling suggests that your path is too long, i.e. check out https://github.com/una-dinosauria/human-motion-prediction/issues/10

Try to run it in a shallower folder and let me know if it works then?
