### ISSUE TITLE
Concurrency in multi-animal estimation

### ISSUE THREAD

**Issue by sneakers-the-rat** [DeepLabCut/DeepLabCut#1750]
**Is your feature request related to a problem? Please describe.**

Since the prediction loop runs synchronously, it only uses the GPU ~half of the time-ish. circled part is the CPU-based pose extraction routine (and the green column to its right is the time spent loading frames into memory)

<img width="1427" alt="Screen Shot 2022-04-01 at 5 27 02 PM" src="https://user-images.githubusercontent.com/12961499/161358260-5267ad89-9108-4327-b32d-ec2aff105ced.png">

that's sorta slower than it needs to be.

**Describe the solution you'd like**

Run the three parts of the inference loop (loading frames, prediction, and the cpu-based stuff) concurrently.

To do that: 
* `predict_batched_peaks_and_costs` needs to be split into two functions, one to run the session, and one to do the CPU part: https://github.com/DeepLabCut/DeepLabCut/blob/686cf5e86f155e95bb494d6243b1e66059266a4e/deeplabcut/pose_estimation_tensorflow/core/predict_multianimal.py#L205
* frame loading and cpu analysis need to be put into separate processes. Here's one totally naive and hacky way of doing that with Processs and Queue. Note that I haven't tested this at all because of tensorflow problems that i absolutely don't have the patience for right now:

(see full example here: https://github.com/sneakers-the-rat/DeepLabCut/commit/9d0cf498ea1ff81e8739748507152dd7af844999 )

```python

def batch_reader(cap, cfg, batch_size:int, queue:mp.Queue):
    counter = 0
    strwidth=64
    while cap.video.isOpened():
        # avoid loading the whole movie into memory without explicit locking
        if queue.qsize() > 2:
            continue
        # get another batch and put it in the queue!
        batch = []
        inds = []
        for i in range(batch_size):
            frame = cap.read_frame(crop=cfg["cropping"])
            if frame is None:
                break
            frame = img_as_ubyte(frame)
            if frame.shape[-1] == 4:
                frame = rgba2rgb(frame)
            batch.append(frame)
            inds.append(counter)
            counter += 1
        batch = np.stack(batch)
        queue.put((batch, inds))

def batch_extractor(in_q, out_q):
    for data in iter(in_q, 'END'):
        pose_cfg, scmaps, locrefs, pafs, peaks = data
        # the CPU part
        out_q.put(predict.extract_peaks_and_costs(pose_cfg, scmaps, locrefs, pafs, peaks))
```

So then `GetPoseandCostsF` can look like this:

```python
def GetPoseandCostsF():
    # ... the stuff before the loop...
    # make queues for concurrent processing
    frame_q = mp.Queue()
    extract_q_put = mp.Queue()
    extract_q_get = mp.Queue()
    # process to extract frames in batches
    frame_proc = mp.Process(target=batch_reader, args=(cap, cfg, batchsize, frame_q))
    frame_proc.start()
    extractor_proc = mp.Process(target=batch_extractor, args=(extract_q_put, extract_q_get))
    extractor_proc.start()

    while cap.video.isOpened():

        frames, inds = frame_q.get()
        scmaps, locrefs, pafs, peaks = predict.predict_only(frames, sess, inputs, outputs)
        extract_q_put.put((dlc_cfg, scmaps, locrefs, pafs, peaks))
        try:
            D = extract_q_get.get_nowait()
            for ind, data in zip(inds, D):
                db["frame" + str(ind).zfill(strwidth)] = data

                pbar.update(1)
        except Empty:
            pass
        # the rest of the function
```

so that while the GPU is processing the frames, the video reader can get loading the next round of frames and the CPU part can be analyzing the last batch. It seems like tensorflow would probably have some means of feeding data to a continuously running session as well, but i don't know enough about TF to sketch that.

**Describe alternatives you've considered**

well i mean this is just a sketch, there are definitely cleaner ways of doing this. this is made sorta needlessly tricky because it looks like there's a lot of duplicated code (eg `GetPoseandCostsF` vs. `GetPoseandCostsS` which could be simplified by just separating the batch iteration logic from the main loop ), so if y'all are interested in parallel inference i would probably do some cleanup first to make it easier to write and test (like i get it, i'm dealing with some of my own code like this atm, much easier to clean up other ppls code than your own lol)

**Additional context**

~ gotta go fast ~

**Comment by MMathisLab** [comment]
closed due to being stale  -- pytorch version out by Q3 this year so will be redone anyhow :D
