### ISSUE TITLE
multi-animal 3D triangulation

### ISSUE THREAD

**Issue by yunacu** [DeepLabCut/DeepLabCut#1752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Dear DLC team, 
I am trying to use maDLC for 3D pose estimation. My DLC version is 2.2.0.6. When I run 
`deeplabcut.triangulate(config_path, video_path, filterpredictions=False, videotype='.mp4',save_as_csv=True)`
It analyzes my videos correctly, however the files (including the .h5 file) have an unsual prefix **_el** example: `camera-1-pochuanDLC_dlcrnetms5_camera1Mar31shuffle1_200000_el.h5`
I deleted that prefix so that the tirangulation function could find it, however now I get the following error: 

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [10], in <module>
----> 1 deeplabcut.triangulate(config_path, video_path, filterpredictions=False, videotype='.mp4',save_as_csv=True)

File ~/.dlc-env/lib/python3.8/site-packages/deeplabcut/pose_estimation_3d/triangulation.py:302, in triangulate(config, video_path, videotype, filterpredictions, filtertype, gputouse, destfolder, save_as_csv)
  293 if run_triangulate:
  294     #        if len(dataname)>0:
  295     # undistort points for this pair
  296     print("Undistorting...")
  297     (
  298         dataFrame_camera1_undistort,
  299         dataFrame_camera2_undistort,
  300         stereomatrix,
  301         path_stereo_file,
--> 302     ) = undistort_points(
  303         config, dataname, str(cam_names[0] + "-" + cam_names[1])
  304     )
  305     if len(dataFrame_camera1_undistort) != len(dataFrame_camera2_undistort):
  306         import warnings

File ~/.dlc-env/lib/python3.8/site-packages/deeplabcut/pose_estimation_3d/triangulation.py:453, in undistort_points(config, dataframe, camera_pair)
  438 """
  439 path_undistort = destfolder
  440 filename_cam1 = Path(dataframe[0]).stem
 (...)
  449 else:
  450 """
  451 if True:
  452     # Create an empty dataFrame to store the undistorted 2d coordinates and likelihood
--> 453     dataframe_cam1 = pd.read_hdf(dataframe[0])
  454     dataframe_cam2 = pd.read_hdf(dataframe[1])
  455     scorer_cam1 = dataframe_cam1.columns.get_level_values(0)[0]

IndexError: list index out of range 
```
Which I think originates in the multianimal indexing, I am not sure how I could change it since I am not very experienced in how the .h5 file is being read. Any help would be greatly appreciated! I cannot find a lot of info on multianimal 3d tracking. Thank you

### Operating System

Ubuntu 20.04

### DeepLabCut version

2.2.0.6

### DeepLabCut mode

multi animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Hi @yunacu 3D maDLC support will come out later this week actually, stay tuned!

**Comment by yunacu** [comment]
> Hi @yunacu 3D maDLC support will come out later this week actually, stay tuned!

Thanks a lot! Looking forward to it :)
