### ISSUE TITLE
colab notebook needs https instead of git for authentication error

### ISSUE THREAD

**Issue by cxrodgers** [DeepLabCut/DeepLabCut#1753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am running the colab notebook Colab_DEMO_mouse_openfield.ipynb. 
https://colab.research.google.com/github/DeepLabCut/DeepLabCut/blob/master/examples/COLAB/COLAB_DEMO_mouse_openfield.ipynb

This is linked from this page:
https://github.com/DeepLabCut/DeepLabCut/blob/master/examples/README.md

The first cell attempts to clone `git://github.com/DeepLabCut/DeepLabCut.git`. This results in an authentication error because github no longer accepts this authentication method. Replacing `git://` with `https://` t make it `https://github.com/DeepLabCut/DeepLabCut.git` seems to work for me.

### Operating System

Linux

### DeepLabCut version

in browser

### DeepLabCut mode

single animal

### Device type

google colab

### Steps To Reproduce

Go to https://colab.research.google.com/github/DeepLabCut/DeepLabCut/blob/master/examples/COLAB/COLAB_DEMO_mouse_openfield.ipynb and click first cell

### Relevant log output

```shell
Cloning into 'cloned-DLC-repo'...
warning: --local is ignored
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
[Errno 2] No such file or directory: 'cloned-DLC-repo'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Hey @cxrodgers that's true, behavior changed last week or so - happy to edit, thanks!
