### ISSUE TITLE
some of the affinity models was not used during the tracklet stitching stage?

### ISSUE THREAD

**Issue by Jason66661010** [DeepLabCut/DeepLabCut#1754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

In the paper(Multi-animal pose estimation and tracking with DeepLabCut)I found that four **affinity models** was used during the tracklet stitching stage(Motion affinity, Spatial proximity, Shape similarity, Dynamic similarity).

But in the code, some of the methods are never called:
in stitch.py, motion_affinity_with() ,shape_dissimilarity_with(), dynamic_similarity_with()...

I want to know whether our code use the affinity models mentioned above. 

### Operating System

operating system
WIN10

### DeepLabCut version

dlc version
2.2.0.5

### DeepLabCut mode

multi animal

### Device type

gpu 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
4 models are tested, not used all need to be/should be used at once, so this is something you can call in the code if you'd like!

**Comment by jeylau** [comment]
If you want to use a different affinity model, you can specify your custom weight function in `deeplabcut.stitch_tracklets`.
It should only accept two `Tracklets` as inputs and output a scalar value that is the cost incurred by stitching them together (the lower, the more probable it is that the tracklets belong to the same track).
For example:
```python
def my_custom_func(tracklet1, tracklet2):
    return tracklet1.motion_affinity_with(tracklet2)

# A combination of affinity models is also possible
def my_custom_func2(tracklet1, tracklet2):
    return (0.2 * tracklet1.dynamic_dissimilarity_with(tracklet2)
            + 0.8 * tracklet1.shape_dissimilarity_with(tracklet2))

deeplabcut.stitch_tracklets(..., weight_func=my_custom_func)
```
I hope this helps! (We should add this somewhere @intergalactic-mammoth 😌)
