### ISSUE TITLE
Error building docker image

### ISSUE THREAD

**Issue by AdrianChe** [DeepLabCut/DeepLabCut#176]
Ubuntu 16.04 LTS, with an Anaconda 2018.12, & DeepLabCut (the newest on I guess)

Hi,
I could really use some help to find the reason for this error. I'm trying to create the Docker environment for deeplabcut.

Thanks,

ebfmlab@ebfmlab-desktop:~/Docker4DeepLabCut2.0$ docker image build -t dlc_username/dlcdocker .
Sending build context to Docker daemon 534kB
Step 1/12 : FROM python:3
---> 7c5fd2af3815
Step 2/12 : RUN pip install imageio
---> Running in e072bb04427e
Collecting imageio
Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f5825859860>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/imageio/
Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f58258596d8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/imageio/
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f5825859588>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/imageio/
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f58258591d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/imageio/
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f58240f62e8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/imageio/
Could not find a version that satisfies the requirement imageio (from versions: )
No matching distribution found for imageio
The command '/bin/sh -c pip install imageio' returned a non-zero code: 1

**Comment by MMathisLab** [comment]
seems to be a network connection error; this can happen if the Docker doesn't have access to the internet.

**Comment by MMathisLab** [comment]
also, another user had the same error, and it was his network. He contacted IT to make sure he had permission to use Dockers, and their solution was: ``mkdir /etc/resolv.conf.d/tail then sudo subl /etc/resolv.conf.d/tail and input: nameserver 10.1.XX.XX``

**Comment by MMathisLab** [comment]
I will close and move comments to the Docker issue, thanks!

**Comment by AdrianChe** [comment]
Thank you very much for your response, it was helpfull.
