### ISSUE TITLE
UnboundLocalError: local variable 'putativecam2name' referenced before assignment

### ISSUE THREAD

**Issue by Alberto100591** [DeepLabCut/DeepLabCut#1766]
Hi my name is Alberto, right now I'm working with 3D Deeplabcut, I'm already at the stage of converting my videos from 2D to 3D, however when I use the command 

deeplabcut.triangulate(config_path,video_path, videotype='mp4')

 I get flag 

UnboundLocalError: local variable 'putativecam2name' referenced before assignment

**Describe the solution you'd like**
I am new to Deeplabcut and I don't know how to solve this error, to generate my 3D video
From what I can understand of the error, possibly the solution is in the format of the folder paths,
**Describe alternatives you've considered**
I've been checking the forums, but many of them work on windows and linux, and at the moment I'm working on mac

At this time I already followed the instructions to carry out the process in
(https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/Overviewof3D.md)

Another possible error is in the name of the cameras. but I'm not sure about that, I leave my config file to ask if you can give me any suggestions

<img width="678" alt="Captura de Pantalla 2022-04-08 a la(s) 12 07 34" src="https://user-images.githubusercontent.com/68699532/162489305-01b8bb64-739f-4db9-8477-d84a9979843e.png">

**Additional context**

<img width="1378" alt="Captura de Pantalla 2022-04-08 a la(s) 11 59 44" src="https://user-images.githubusercontent.com/68699532/162488151-2ee5af27-8f8e-4844-b0d8-739d8a626d45.png">

**Comment by MMathisLab** [comment]
please fill out the template fully, then we can assist you.

**Comment by Alberto100591** [comment]
> please fill out the template fully, then we can assist you.
hello complete the information you request, I hope you can help me

**Comment by MMathisLab** [comment]
the skeleton is incorrectly formatted,it must be like:
```
-- part1
 - part2
 ```

 and be sure your videos have the identical names as the camera names you used.
