### ISSUE TITLE
Error in: find_outliers_in_raw_data

### ISSUE THREAD

**Issue by auesro** [DeepLabCut/DeepLabCut#1775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Running `find_outliers_in_raw_data` in Google Colab provided notebook for maDLC (https://github.com/DeepLabCut/DeepLabCut/blob/master/examples/COLAB/COLAB_maDLC_TrainNetwork_VideoAnalysis.ipynb) as recommended here (https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#decision-point) results in a ValueError (see log output) for some videos while others (I have tested 19 different videos) run without issue and extract outlier frames.

No idea whats going on.

### Operating System

Google Colab

### DeepLabCut version

2.2.0.6

### DeepLabCut mode

multi animal

### Device type

gpu in Google Colab

### Steps To Reproduce

deeplabcut.find_outliers_in_raw_data(path_config_file,pickle_file='/content/drive/Shareddrives/Computational_Neuro_IP-AER/Test_maDLC_multi_2/singleanimal-IsabelP-2022-03-24/videos/8-2-2021_Chloroquine_5DLC_dlcrnetms5_singleanimalMar24shuffle1_100000_full.pickle',video_file='/content/drive/Shareddrives/Computational_Neuro_IP-AER/Test_maDLC_multi_2/singleanimal-IsabelP-2022-03-24/videos/8-2-2021_Chloroquine_5.mp4',pcutoff=0.5)

### Relevant log output

```shell
---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-6-7be94f9a6ed7> in <module>()
----> 1 deeplabcut.find_outliers_in_raw_data(path_config_file,pickle_file='/content/drive/Shareddrives/Computational_Neuro_IP-AER/Test_maDLC_multi_2/singleanimal-IsabelP-2022-03-24/videos/8-2-2021_Chloroquine_5DLC_dlcrnetms5_singleanimalMar24shuffle1_100000_full.pickle',video_file='/content/drive/Shareddrives/Computational_Neuro_IP-AER/Test_maDLC_multi_2/singleanimal-IsabelP-2022-03-24/videos/8-2-2021_Chloroquine_5.mp4',pcutoff=0.5)

2 frames

/usr/local/lib/python3.7/dist-packages/numpy/lib/index_tricks.py in __getitem__(self, key)
    411                 objs[k] = objs[k].astype(final_dtype)
    412 
--> 413         res = self.concatenate(tuple(objs), axis=axis)
    414 
    415         if matrix:

<__array_function__ internals> in concatenate(*args, **kwargs)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by auesro** [comment]
More info: I have tested the same in a local installation of deeplabcut, same error.

**Comment by jeylau** [comment]
Hi @auesro, would you be willing to share the _full.pickle file that causes the issue? I cannot reproduce it on my side 😕
I also see that your project is called singleanimal..., is this a setting where you use maDLC with a single animal only?

**Comment by auesro** [comment]
Hi @jeylau , sure, more than willing to share the full picke and the video itself with you. How do you prefer to go about it? Can I send you a google drive link over email?
Yes, we are using the maDLC with single animal videos in order to take advantage of more advanced video handling (robust frames etc).

Thanks!

A

**Comment by jeylau** [comment]
@auesro, I think I have just fixed it 😄 If you want to try it, you could install the patch as follows: `pip install git+https://github.com/DeepLabCut/DeepLabCut.git@fix_outlier_data`. If you still run into the error, a google drive link over email is great!

**Comment by auesro** [comment]
It works!
Just tested it on COLAB and it is currently `Extracting and downsampling... 37896  frames from the video.`. That was quick Jessy, awesome!!
If you still need/want the videos/pickles, just pass an email address!
