### ISSUE TITLE
Error Creating Training Dataset (TypeError)

### ISSUE THREAD

**Issue by cdj5044** [DeepLabCut/DeepLabCut#1778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I believe I am having an issue that was previously addressed (#1636, #1647), related to moving projects with labeled frames to another computer. I have a project with about 400 labeled frames that I moved on to a computer with the GPU I want to use for training. When I attempt to create the training dataset, I get a 'TypeError'. Below is the full output. I also get an error when trying to view the labeled frames ('Label Frames' function), which is posted below as well. 

I've transferred projects between these same computers before and everything ran fine, so I'm not sure what is different.

### Operating System

Microsoft Windows 10 Pro

### DeepLabCut version

DLC 2.2.0.1

### DeepLabCut mode

single animal

### Device type

NVIDIA Quadro P2000

### Steps To Reproduce

1. On original computer- I ran 'Label frames' in GUI and labeled about 400 frames total
2. The project was transferred to another computer (noted above) and the link was updated in the config file
3. On the second computer- I ran: conda activate DLC-GPU
4. In GUI: I ran 'Create training dataset' or 'Label frames'
5. Relevant errors for either are copied below

### Relevant log output

```shell
(base) PS C:\Users\SNRC_Z42> conda activate DLC-GPU
(DLC-GPU) PS C:\Users\SNRC_Z42> python -m deeplabcut
Starting GUI...

1. Create training dataset:
C:\Users\SNRC_Z42\Desktop\DLC-Projects\ALII Study\ALII_TM_Front-CDJ-2022-02-02\training-datasets\iteration-0\UnaugmentedDataSet_ALII_TM_FrontFeb2  already exists!
Traceback (most recent call last):
  File "C:\Users\SNRC_Z42\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\create_training_dataset.py", line 385, in create_training_dataset
    augmenter_type=self.aug_choice.GetValue(),
  File "C:\Users\SNRC_Z42\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 1018, in create_training_dataset
    Data, trainIndices, nbodyparts, project_path
  File "C:\Users\SNRC_Z42\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 793, in format_training_data
    img_shape = _read_image_shape_fast(os.path.join(project_path, filename))
  File "C:\Users\SNRC_Z42\anaconda3\envs\DLC-GPU\lib\ntpath.py", line 115, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Users\SNRC_Z42\anaconda3\envs\DLC-GPU\lib\genericpath.py", line 153, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'tuple'

2. Label frames:
Traceback (most recent call last):
  File "C:\Users\SNRC_Z42\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\generate_training_dataset\labeling_toolbox.py", line 637, in browseDir
    self.newimages = list(set(self.relativeimagenames) - set(old_imgs))
TypeError: unhashable type: 'numpy.ndarray'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
hi @cdj5044 can you please update to the latest, vs. 2.2.0.1, the current release is 2.2.1

and be aware, you are over writing your data, I would already create a new shuffle #:


C:\Users\SNRC_Z42\Desktop\DLC-Projects\ALII Study\ALII_TM_Front-CDJ-2022-02-02\training-datasets\iteration-0\UnaugmentedDataSet_ALII_TM_FrontFeb2  already exists!

**Comment by cdj5044** [comment]
Hi @MMathisLab - Ah, I'm sorry- I thought I had the latest version installed based on the install documentation page. I updated it and the error was resolved. 

Thank you!

**Comment by sherryxinyuean** [comment]
Hi, I am encountering same issues when creating training dataset. 

**- TypeError: join() argument must be str or bytes, not 'tuple'**

To reproduce, I transferred previously labeled data (Windows) to GPU that has DeepLabCut docker version. DLC version is 2.2.2.

Thank you
