### ISSUE TITLE
Multi-animal project - no output data to csv when animal body is occluded

### ISSUE THREAD

**Issue by JianzhiZhang1** [DeepLabCut/DeepLabCut#1785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

hi, Deeplabcut!
When the video of 2 mice is analyzed, there will be no data in the corresponding occluded or otherwise invisible body parts in the output CSV file. Curiously, most of the limbs were occluded during previous single-animal analysis, but there would still be corresponding csv data.
I think it may be related to this issue #1732

**Comment by MMathisLab** [comment]
@JianzhiZhang1 there is a lot going on here 🤗-- you are also using the transformer code in the middle, lots of errors throughout the output log. :) Can you please make a clean workflow we can can follow what you did? in general, occlusions are not tracked unless you taught the model to guess. I would suggest doing (1) analyze_video only --> create video in the GUI and see how that goes first?

**Comment by JianzhiZhang1** [comment]
Thank you for spending your valuable time on this pile of code. I'm very sorry!

**Comment by JianzhiZhang1** [comment]
@MMathisLabThank you for spending your valuable time on this pile of code. I'm very sorry!

1. I might just want the network to predict the invisible points and their raw data. The main concern is that there is no data output for the body parts of the animals I need. like this: 
![image](https://user-images.githubusercontent.com/103829351/164884485-3f08d081-c294-4d49-ba73-5699744fdce6.png)

2. Here are my related files:
[related files.zip](https://github.com/DeepLabCut/DeepLabCut/files/8546449/related.files.zip)

3. Here is my code: 


(base) PS C:\Users\Administrator> conda activate DLC-221
(DLC-221) PS C:\Users\Administrator> python -m deeplabcut
C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\statsmodels\compat\pandas.py:65: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import Int64Index as NumericIndex
Starting GUI...

DLC network loading and video analysis starting ...
Using snapshot-50000 for model E:\FreeSocialTest\FSoT-01-2022-04-21\dlc-models\iteration-0\FSoTApr21-trainset95shuffle1
C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\tf_slim\layers\layers.py:684: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  outputs = layer.apply(inputs, training=is_training)

Activating extracting of PAFs
2022-04-23 15:05:03.895853: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-23 15:05:04.274162: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9622 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060, pci bus id: 0000:01:00.0, compute capability: 8.6

Starting to analyze %  E:\FreeSocialTest\FSoT-01-2022-04-21\videos\1.wmv
Loading  E:\FreeSocialTest\FSoT-01-2022-04-21\videos\1.wmv
Duration of video [s]:  60.07 , recorded with  30.3 fps!
Overall # of frames:  1820  found with (before cropping) frame dimensions:  1072 1024
Starting to extract posture from the video(s) with batchsize: 8
  0%|                                                                                         | 0/1820 [00:00<?, ?it/s]2022-04-23 15:05:06.350403: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8201
100%|██████████████████████████████████████████████████████████████████████████████| 1820/1820 [01:59<00:00, 15.27it/s]
Video Analyzed. Saving results in E:\FreeSocialTest\FSoT-01-2022-04-21\videos...
Using snapshot-50000 for model E:\FreeSocialTest\FSoT-01-2022-04-21\dlc-models\iteration-0\FSoTApr21-trainset95shuffle1
Processing...  E:\FreeSocialTest\FSoT-01-2022-04-21\videos\1.wmv
Analyzing E:\FreeSocialTest\FSoT-01-2022-04-21\videos\1DLC_resnet50_FSoTApr21shuffle1_50000.h5
1800it [00:06, 257.60it/s]
1800it [00:05, 335.37it/s]
The tracklets were created (i.e., under the hood deeplabcut.convert_detections2tracklets was run). Now you can 'refine_tracklets' in the GUI, or run 'deeplabcut.stitch_tracklets'.
Processing...  E:\FreeSocialTest\FSoT-01-2022-04-21\videos\1.wmv
100%|████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 3508.20it/s]
The videos are analyzed. Time to assemble animals and track 'em...
 Call 'create_video_with_all_detections' to check multi-animal detection quality before tracking.
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
Creating labeled video for  1
100%|██████████████████████████████████████████████████████████████████████████████| 1820/1820 [00:21<00:00, 83.09it/s]
Filtering with median model E:\FreeSocialTest\FSoT-01-2022-04-21\videos\1.wmv
Saving filtered csv poses!
All H5 files were converted to CSV.
Loading  E:\FreeSocialTest\FSoT-01-2022-04-21\videos\1.wmv and data.
Plots created! Please check the directory "plot-poses" within the video directory


Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\deeplabcut\gui\create_videos.py", line 248, in build_skeleton
    skeleton.SkeletonBuilder(self.config)
  File "C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\deeplabcut\utils\skeleton.py", line 56, in __init__
    row, col = self.pick_labeled_frame()
  File "C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\deeplabcut\utils\skeleton.py", line 108, in pick_labeled_frame
    row, col = kept.pop()
ValueError: too many values to unpack (expected 2)


Creating a video with the Default tracker method!
C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\statsmodels\compat\pandas.py:65: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import Int64Index as NumericIndex
Starting to process video: E:\FreeSocialTest\FSoT-01-2022-04-21\videos\1.wmv
Loading E:\FreeSocialTest\FSoT-01-2022-04-21\videos\1.wmv and data.
Duration of video [s]: 60.06, recorded with 30.3 fps!
Overall # of frames: 1820 with cropped frame dimensions: 1072 1024
Generating frames and creating video.
100%|██████████████████████████████████████████████████████████████████████████████| 1800/1800 [00:21<00:00, 84.01it/s]
Loading  E:\FreeSocialTest\FSoT-01-2022-04-21\videos\1.wmv and data.
Plots created! Please check the directory "plot-poses" within the video directory

What am I overlook? Looking forward to your guidance! @

**Comment by JianzhiZhang1** [comment]
@MMathisLab

**Comment by jeylau** [comment]
Hey @JianzhiZhang1, like @MMathisLab above, I'd encourage you to use analyze_videos only in the first place, and I'd add that you could then run `deeplabcut.create_video_with_all_detections` to visualize the raw detections. This way, you'll be able to gauge whether the network has been trained well prior to animal assembly and tracking. Also, you should find a xxx_map.pickle nested within the evaluation-results folder; it contains some evaluation metrics.
Could you open it as follows and tell us what the output looks like?:
```python
from deeplabcut import auxiliaryfunctions

table = auxiliaryfunctions.read_pickle('path_to_your_map_pickle')[0]
print(table)
```

**Comment by JianzhiZhang1** [comment]
hey@jeylau, I try to run this step: deeplabcut.create_video_with_all_detections. And the a xxx_map.pickle files was not  generated. What am I not considering? ![image](https://user-images.githubusercontent.com/103829351/166417576-39316a83-1bf5-4d88-bd25-06075950b804.png)
![image](https://user-images.githubusercontent.com/103829351/166417953-03361e62-6647-4c5d-a58b-95e2c3f844df.png)
[config_files.zip](https://github.com/DeepLabCut/DeepLabCut/files/8608920/config_files.zip)

**Comment by jeylau** [comment]
You can inspect the _full.mp4 video: this is the one with all the detections. The _map.pickle though is found in the project/evaluation-results subfolder; it is automatically written upon completion of your network evaluation.

**Comment by JianzhiZhang1** [comment]
@jeylau hey,  I'm sorry to have disturbed you, I ran the code you gave me above.
```
from deeplabcut import auxiliaryfunctions

table = auxiliaryfunctions.read_pickle('path_to_your_map_pickle')[0]
print(table)
```
The result after I ran it was:
![image](https://user-images.githubusercontent.com/103829351/166854159-8b49ff08-95d6-40ee-93b2-3260cb3ee767.png)

Is there anything I can know here?

thanks

**Comment by JianzhiZhang1** [comment]
oh，I would like to ask you a question: do I need to change resnet50 to dlcrnet_ms50, when I train multi-animal project?
![image](https://user-images.githubusercontent.com/103829351/166855803-c838eeb9-f99d-4919-9dab-86c7ef2f0f15.png)
In the last training session, I used resnet 50.

**Comment by jeylau** [comment]
Evaluation metrics look good to me. Note that If you want DeepLabCut to predict occluded points, you'll have to label the occluded keypoints in your training images. There is a nice forum post covering this very issue https://forum.image.sc/t/how-does-deeplabcut-deal-with-bodyparts-that-are-most-of-the-time-occluded/30985.

**Comment by jeylau** [comment]
I'll close the issue but feel free to reopen it if something remains unclear ☺️
