### ISSUE TITLE
Is IPython really a dependency?

### ISSUE THREAD

**Issue by hmaarrfk** [DeepLabCut/DeepLabCut#1790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

It seems that ipython gets installed along with DeepLabCut.

Do you really need it? Searching through the repo, I don't see a need for it. Maybe it is a convenience?

As somebody who maintains packages, may I suggest removing the dependency?

https://github.com/DeepLabCut/DeepLabCut/blob/master/setup.py#L28

### Operating System

Linux

### DeepLabCut version

master 2.2.0.6

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
agree it could be dropped; when we started it was for life sci were many were new to python, but agree this has changed. Feel free to make PR if you'd like; it could be moved to conda yml file, which has the other "convenience installs", like nb_conda, etc.

**Comment by ArAbolghasemi** [comment]
I am experiencing issues when creating a new conda environment on a Windows with latest conda version, using the `DEEPLABCUT.yml` file that seems to be related to the `nb_conda ` dep.

This is the issue after conda install `nb_conda`>
```shell
==> script messages <==
Enabling nb_conda_kernels...
CONDA_PREFIX: C:\Users\SNeurobiology\Anaconda3\envs\deeplabcut
Status: enabled

==> script output <==
stdout:
stderr: 'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.
```


So, I would also advise for removing `nb_conda `as a requirement if it is not a strict one.
