### ISSUE TITLE
unpin scikit-image requirement

### ISSUE THREAD

**Issue by hmaarrfk** [DeepLabCut/DeepLabCut#1791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I know that scikit-image had some issues with releases 0.18.X and as such a few people had to pin their upper bound.

May I suggest unpinning scikit-image? 

As a core developer of scikit-image, I think it is appropriate to do so (I've been using deeplabcut+scikit-image 0.19 on conda-forge for a while now)
It should work without any problems.

XREF for the likely issue that has since been fixed that caused lots of headaches in scikit-image.
https://github.com/scikit-image/scikit-image/issues/3906

### Operating System

All

### DeepLabCut version

master 2.2.0.6

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
hey @hmaarrfk thanks for the tip on this; indeed we had not checked with >0.19 yet- happy to unpin. If you'd like to make PR, please do!
