### ISSUE TITLE
Sort videos during inference

### ISSUE THREAD

**Issue by hmaarrfk** [DeepLabCut/DeepLabCut#1792]
**Is your feature request related to a problem? Please describe.**
When I try to run inference of a folder of videos, they get analyzed in a random order. This is because it seems that they get shuffled during the collection/discovery step.

However, when you look at your folder, the results start to appear in a random order. I would like to look down my folder list in my file explorer and see the videos get analyzed in some kind of order.

**Describe the solution you'd like**
I would like a call to `videos.sort()` to sort the list of videos found so they get 

**Describe alternatives you've considered**

Patching deeplabcut myself, I would rather collobarate and submit the patch to you to help other users.

Attached is one non-invasive suggestion. You could patch `get_list_of_videos` but I feel like that might get used in training, where yo uwould want the videos to be sorted.
[0001-Ensure-videos-are-sorted-during-inference-steps-to-h.txt](https://github.com/DeepLabCut/DeepLabCut/files/8544366/0001-Ensure-videos-are-sorted-during-inference-steps-to-h.txt)

**Comment by jeylau** [comment]
That's indeed the relevant line: https://github.com/DeepLabCut/DeepLabCut/blob/aa0b43cc89db15790b01844ed9a958d70bef6dfc/deeplabcut/utils/auxiliaryfunctions.py#L360
@AlexEMG is shuffling still beneficial?

**Comment by AlexEMG** [comment]
Yes, I think this is beneficial, as one can run multiple workers/models on a list of videos. Then through randomness, they will chip away at different videos. 

I propose to make a flag, for turning shuffling off?

**Comment by hmaarrfk** [comment]
thank you
