### ISSUE TITLE
How to Load a training snapshot

### ISSUE THREAD

**Issue by byronrogers73** [DeepLabCut/DeepLabCut#180]
As found here (but closed ticket) - https://github.com/AlexEMG/DeepLabCut/issues/70

So I am clear, the change in "init_weights:" value in pose_cfg.yaml (that file found in .../dlc-models/iteration-0/-trainset95shuffle1/train/...)

Should go from /usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt

to (as example)

.../dlc-models/iteration-0/-trainset95shuffle1/train/snapshot-80000.meta

?

**Comment by MMathisLab** [comment]
No, you add the path **without** the ending; as it loads multiple files, so you just point it to a snapshot: 

i.e.  ``init_weights: /fullpathtothisfolder/ProjectFolder/dlc-models/iteration-0/train/snapshot-20000``

Here is an updated graphic for important **pose_config.yaml** file settings:

![image](https://user-images.githubusercontent.com/28102185/51443998-8e1b5d00-1cbf-11e9-8614-be3b2745e4a5.png)
