### ISSUE TITLE
Joint Selection

### ISSUE THREAD

**Issue by diegosancarmen** [DeepLabCut/DeepLabCut#1808]
**Is your feature request related to a problem? Please describe.**
With the work I'm doing I need to track mouse paws & tail (sample image attached below).  As you can see, when I first used DLC I labeled paws, ankles, legs, tail base and mid-tail.  

**Describe the solution you'd like**
In a Python script I would like to select the joint landmarks (e.g., "left_ankle, left_paw, etc.") and be able to track and calculate around those joints only.  Is that possible with DLC?

**Additional context**
This feature would be used to calculate several things:
- the Euclidean distance from the ankle to the tail base
- the change of angle formed by the paw and the leg
- the horizontal and vertical velocity of the paw
- and I'm sure more things once I find a program which offers such a feature!

![img3278_individual](https://user-images.githubusercontent.com/101142209/165417265-1cd42749-b795-4e19-bc88-7daf057a1b24.png)

**Comment by jeylau** [comment]
Hello @diegosancarmen, it looks like `deeplabcut.analyzeskeleton()` will be useful! Have a look here too https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html?highlight=skeleton#extract-skeleton-features, it details how you could define segments or "bones" whose lengths and orientations can automatically be calculated by DeepLabCut. I hope this helps!

**Comment by MMathisLab** [comment]
you can also use `DLC2Kinematics` https://github.com/AdaptiveMotorControlLab/DLC2Kinematics

**Comment by diegosancarmen** [comment]
Hello!

Is there a way to plot the trajectories of specific body parts, versus all body parts?  I am using the Google Colab for training and analyzing.  This is DLC 2.2.1.

When I use `deeplabcut.create_labeled_videos` using the arguments `(path_config_file,videofile_path, videotype=VideoType, draw_skeleton= True)`, the skeleton does not show.  This is the skeleton (and the body parts) as listed in the config.yaml file.

```

https://user-images.githubusercontent.com/101142209/168158495-a7ceef78-1a73-4cdd-a239-5f7415a15713.mp4


individuals:
- individual1
uniquebodyparts:
- leftofrod
- rightofrod
multianimalbodyparts:
- leftpaw
- leftankle
- leftleg
- rightpaw
- rightankle
- rightleg
- tailbase
- tail
bodyparts: MULTI!

    # Fraction of video to start/stop when extracting frames for labeling/refinement
start: 0
stop: 1
numframes2pick: 20

    # Plotting configuration
skeleton: [
  [leftpaw, leftankle], 
  [leftpaw, leftleg], 
  [leftpaw, tailbase], 
  [rightpaw, rightankle], 
  [rightpaw, rightleg], 
  [rightpaw, tailbase], 
  [tailbase, tail]
  ]
skeleton_color: white
pcutoff: 0.9
dotsize: 4
alphavalue: 0.7
colormap: rainbow

```

As seen in the screenshots below the forearms are also being detected; what outlier algorithm argument would be best to pass for this?

![Screenshot (5)](https://user-images.githubusercontent.com/101142209/168158967-20c5e983-bb30-42ad-9c88-c8f16f042c44.png)
![Screenshot (6)](https://user-images.githubusercontent.com/101142209/168158971-541a2a9e-b243-46ce-ad1c-8c7380d8d76d.png)
