### ISSUE TITLE
OpenBLAS: Segmentation fault when extracting frames using k-means

### ISSUE THREAD

**Issue by charithaomprakash** [DeepLabCut/DeepLabCut#1809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi there,

I am trying to extract frames from two videos in a new DLC project and I did what was suggested in the post with the same issue (#1651) (installing DLC using the conda file that is provided by you). Unfortunately this doesn't seem to solve the issue for me. I still get a segmentation fault and it is never on the same frame either. 

### Operating System

operating system: Ubuntu 20.04.3

### DeepLabCut version

dlc version: 2.2.1

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

1. In the deeplabcut environment, ipython
2. import deeplabcut
3. create a new multianimal project
4. deeplabcut.extract_frames(config, mode='automatic', algo='kmeans', userfeedback=False)

### Relevant log output

```shell
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
***Recieved signal 11***
**BEGIN MANGLED STACK TRACE***
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @charithaomprakash, it seems to be an error related to scipy and scikit-learn, documented here https://github.com/scikit-learn/scikit-learn/issues/20539. I read through it, there is no definite solution, but you could maybe try to uninstall both packages with `pip uninstall scipy scikit-learn` and reinstall them via conda `conda install scipy scikit-learn`. Another possible option would be to instruct scikit-learn to use fewer threads with `export OPENBLAS_NUM_THREADS=64` for example (if it doesn't work, you could try it with 1, but that looks suboptimal then as you lose parallelism). Let me know if that helped :)

**Comment by charithaomprakash** [comment]
Hi @jeylau uninstalling it via pip and reinstalling it using conda seems to do the trick. I will close the issue. Thank you!

**Comment by jeylau** [comment]
Great to hear! Thanks for reporting back. ☺️
