### ISSUE TITLE
Playing the Labeled video - black frames displayed

### ISSUE THREAD

**Issue by guyts** [DeepLabCut/DeepLabCut#181]
Windows 10, Anaconda3, Latest DLC version (cpu env), ffmpeg 4.1

After analyzing videos I am trying to generate labeled video output (single video file at the moment). 

`deeplabcut.create_labeled_video(path_config_file, ['D:\\dlc-blinking\\an3_vid2\\videos\\an3_vid2_150fps.mp4'], save_frames=True)`

A folder with all the labeled frames is created, and I can access the folder and all individual images (~15k frame).
The code seems to work fine, and doesn't give any errors:

```
Starting %  D:\dlc-blinking\an3_vid2\videos ['D:\\dlc-blinking\\an3_vid2\\videos\\an3_vid2_150fps.mp4']
Loading  D:\dlc-blinking\an3_vid2\videos\an3_vid2_150fps.mp4 and data.
True 180 320 40 180
15166
Duration of video [s]:  101.11 , recorded with  150.0 fps!
Overall # of frames:  15166 with cropped frame dimensions:  140 140
Generating frames
100%|██████████| 15166/15166 [40:29<00:00,  6.09it/s] 
All labeled frames were created, now generating video...
A clear and concise description of what the problem is.
```

However, when I try and open the video file, all I'm seeing is black, and although the duration mentioned is right (~1.5mins), the video plays only black screen and ends after less than a second.

I've installed latest version of ffmpeg before running.
The video is cropped (set in config.yaml) and frames are saved.

Any ideas for what might be the cause?

**Comment by MMathisLab** [comment]
Try opening the video in something more universal, like VLC  https://www.videolan.org/vlc/download-windows.html

i.e. "Windows Media Player does not support the playback of the .mp4 file format. You can play back .mp4 media files in Windows Media Player when you install DirectShow-compatible MPEG-4 decoder packs." https://support.microsoft.com/en-us/help/316992/file-types-supported-by-windows-media-player

**Comment by guyts** [comment]
Thank you - resolved!
