### ISSUE TITLE
DeepLabCut is "Loud"

### ISSUE THREAD

**Issue by hmaarrfk** [DeepLabCut/DeepLabCut#1815]
**Is your feature request related to a problem? Please describe.**
I find that DeepLabCut is rather "Loud" in terms of output when one uses it to analyze many videos. Alot of output is generated on `stdout`, which sometimes isn't piped to the user (i.e. if the GUI is used, the output is going to a terminal, so the user isn't really aware of what is going on) and generally speaking, the amount of verbosity increases the likeliness of a user simply disabling outputs all together.

I find a few different locations where print statements can be avoided:
1. During the top level import. This typically communicates to the end user that different features of DLC are enabled/disabled.
2. During analysis to report progress.
3. During analysis to report that no files were found.
4. During analysis through the use of a "standard" `tqdm` object.

**Describe the solution you'd like**
I think a few improvements have been made to python since DLC started that can be used to improve on the present state.

1. Lazy importing (Python 3.7+) may be used to avoid importing GUI/Pytorch features until the user requests them. If the user requests it and the dependencies are not available, and error is likely better than a warning?
2. `quiet` or `verbose` flags may be used here. I typically chose to only allow the user to provide these as keyword only arguments.
3. `quiet`, `verbose` flags may be used. It may also be better to error here?
4. A `quiet` or `verbose` flag may be used. I would prefer the usage of a `tqdm` "constructor", so users may pass in `tqdm.notebook` or similar to get application specific progress bars. 

Personally, I think the use of `print` statements should not be used within the "library" portion, but more at the "application" level. However, I understand that they are convenient for debugging and rapid development.

I also think the print statements are useful to debug long running training sessions.
I think other libraries use the [logging](https://docs.python.org/3/howto/logging.html) but I don't have much experience with this.

**Describe alternatives you've considered**
There isn't much one can do to remove `internal` print statement other than direct patching (or monkey patching). I would prefer to avoid these solutions.

**Additional context**
I'm happy to submit patches to start addressing the different points (as different Pull Requests). Though I'm not sure this is something you want to work on at all.

**Comment by CBroz1** [comment]
I would request a migration to `logging` in order to allow the user to dial in DeepLabCut verbosity. This might include an environment variable like `DEEPLABCUT_LOGLEVEL` that could optionally be set to 'warn', 'info', etc.

I personally call DLC from another application, and the stdout becomes hard to scan with large training paramset dicts, for example, being sent to stdout. 

I would be happy to contribute one or more PRs to this effect
