### ISSUE TITLE
Error when loading the library due to qt5 incompatability

### ISSUE THREAD

**Issue by guyts** [DeepLabCut/DeepLabCut#182]
Win10, latest DLC, CPU environment, running on Spyder

I installed seaborn on the dlc-windowsCPU environment to get some analyses done, which was fine, but when trying to run the code again and import the dlc library, I got the following error:

`ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'qt5' is currently running`

I've uninstalled seaborn from the environment, but the error remains, and couldn't find an easy fix on stackoverflow. I've also made sure tk was installed [qt v5.9.7; tk v8.6.8]

Is there a solution to this problem?

**Comment by guyts** [comment]
Tried recreating the environment but got a different set of errors.
I'm trying to reinstall anaconda and hopefully that'll solve it.
I'll update

**Comment by MMathisLab** [comment]
No offense, but deleting Anaconda likely won't change anything, I would think it is better to just clean up the env folder, and freshly create an environment. but it's up to you...

**Comment by guyts** [comment]
Point Taken. However, I installed a new environment but it didn't solve the issue and actually created different errors, and I decided to reset everything.

**Comment by guyts** [comment]
Reinstallation of everything resolved the issue.
For reference however, I think installing libraries that use Qt over Tk might cause problems loading dlc properly.
