### ISSUE TITLE
Refine Tracklets Error: [IndexError: index 0 is out of bounds for axis 0 with size 0]

### ISSUE THREAD

**Issue by JianzhiZhang1** [DeepLabCut/DeepLabCut#1825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

hey, I'm so sorry when operating DLC with an error again. 
My operation steps: 

1. 2s video analysis
![image](https://user-images.githubusercontent.com/103829351/167348539-e9380149-0628-4b78-bcb2-53eec2b3c9d7.png)

2. Create predicted video
![image](https://user-images.githubusercontent.com/103829351/167348614-29a78eb8-8422-4725-bb1e-34e22c15bc18.png)

3. Results
![image](https://user-images.githubusercontent.com/103829351/167348729-8bafae19-898b-4ad7-af08-8d73374fd765.png)

4.Refine Tracklets
move, delete bodyparts of the animal, then click the 'save' button. Unfortunately, an error was reported.
![image](https://user-images.githubusercontent.com/103829351/167349127-deaa3d18-aa1e-4bd4-a069-ffe9e495c260.png)

`Processing...  E:\FreeSocialTest\FSoT-01-2022-04-21\videos\2s.mp4
100%|████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\matplotlib\cbook\__init__.py", line 287, in process
    func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\matplotlib\widgets.py", line 227, in <lambda>
    return self._observers.connect('clicked', lambda event: func(event))
  File "C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\deeplabcut\gui\tracklet_toolbox.py", line 637, in save
    self.save_coords()
  File "C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\deeplabcut\gui\tracklet_toolbox.py", line 343, in save_coords
    nrow = np.flatnonzero(inds == ind)[0]
IndexError: index 0 is out of bounds for axis 0 with size 0`

Is there a step I've missed? can you give a hand?  Thank you most sincerely. 

### Operating System

windows 10

### DeepLabCut version

dlc version: 2.2.1

### DeepLabCut mode

multi animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by JianzhiZhang1** [comment]
hey!excues me, I noticed that if I clicked the [Rfine Tracklets] ‘’save‘’ button multiple times in quick succession, the error code prompt would appear.

**Comment by jeylau** [comment]
@JianzhiZhang1, your video has 2 frames only?

**Comment by JianzhiZhang1** [comment]
@jeylau Not really, my video has 2 seconds.

**Comment by jeylau** [comment]
@JianzhiZhang1, the error should now be fixed! You could try it out with:
`pip install --upgrade --no-deps --force-reinstall git+https://github.com/DeepLabCut/DeepLabCut.git@fix_save_tracklets`
