### ISSUE TITLE
ValueError: Could not find a backend to open `C:\Users\hugues.lamothe\Documents\DeepLabCut\examples\TEST-Alex-2022-05-09\labeled-data\reachingvideo1\CollectedData_Alex.csv`` with iomode `ri`.

### ISSUE THREAD

**Issue by Hugues1273** [DeepLabCut/DeepLabCut#1827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Dear all,

I installed deeplabcut and I m trying to use it through a GPU.
I installed deeplabcut using git clone https://github.com/DeepLabCut/DeepLabCut.git

Now I try to test deeplabcut using testscript.py in the example folder following the https://www.youtube.com/watch?v=IOWtKn3l33s instruction. Note that I installed CUDA, cuDNN, NVIDIA with appropriate and compatible versions closely following the guideline instruction.

launching testscript.py I get the following error message and I failed to fix it:

> (DEEPLABCUT) C:\Users\hugues.lamothe\Documents\DeepLabCut\examples>python testscript.py
> C:\Users\hugues.lamothe\Anaconda3\envs\DEEPLABCUT\lib\site-packages\statsmodels\compat\pandas.py:65: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
>   from pandas import Int64Index as NumericIndex
> C:\Users\hugues.lamothe\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\__init__.py:78: UserWarning:
>         As PyTorch is not installed, unsupervised identity learning will not be available.
>         Please run `pip install torch`, or ignore this warning.
> 
>   warnings.warn(
> Imported DLC!
> On Windows/OSX tensorpack is not tested by default.
> CREATING PROJECT
> Project "C:\Users\hugues.lamothe\Documents\DeepLabCut\examples\TEST-Alex-2022-05-09" already exists!
> EXTRACTING FRAMES
> Config file read successfully.
> Extracting frames based on kmeans ...
> Kmeans-quantization based extracting of frames from 0.0  seconds to 8.53  seconds.
> Extracting and downsampling... 256  frames from the video.
> 256it [00:02, 113.22it/s]
> Kmeans clustering ... (this might take a while)
> Frames were successfully extracted, for the videos listed in the config.yaml file.
> 
> You can now label the frames using the function 'label_frames' (Note, you should label frames extracted from diverse videos (and many videos; we do not recommend training on single videos!)).
> CREATING-SOME LABELS FOR THE FRAMES
> Plot labels...
> Creating images with labels by Alex.
> Traceback (most recent call last):
**>   File "testscript.py", line 122, in <module>
>     deeplabcut.check_labels(path_config_file)**
>   File "C:\Users\hugues.lamothe\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 345, in check_labels
>     visualization.make_labeled_images_from_dataframe(
>   File "C:\Users\hugues.lamothe\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\visualization.py", line 307, in make_labeled_images_from_dataframe
>     h, w = ic[0].shape[:2]
>   File "C:\Users\hugues.lamothe\Anaconda3\envs\DEEPLABCUT\lib\site-packages\skimage\io\collection.py", line 294, in __getitem__
>     self.data[idx] = self.load_func(self.files[n], **kwargs)
>   File "C:\Users\hugues.lamothe\Anaconda3\envs\DEEPLABCUT\lib\site-packages\skimage\io\_plugins\imageio_plugin.py", line 10, in imread
>     return np.asarray(imageio_imread(*args, **kwargs))
>   File "C:\Users\hugues.lamothe\Anaconda3\envs\DEEPLABCUT\lib\site-packages\imageio\__init__.py", line 96, in imread
>     return imread_v2(uri, format=format, **kwargs)
>   File "C:\Users\hugues.lamothe\Anaconda3\envs\DEEPLABCUT\lib\site-packages\imageio\v2.py", line 200, in imread
>     with imopen(uri, "ri", **imopen_args) as file:
>   File "C:\Users\hugues.lamothe\Anaconda3\envs\DEEPLABCUT\lib\site-packages\imageio\core\imopen.py", line 302, in imopen
>     raise err_type(err_msg)
**> ValueError: Could not find a backend to open `C:\Users\hugues.lamothe\Documents\DeepLabCut\examples\TEST-Alex-2022-05-09\labeled-data\reachingvideo1\CollectedData_Alex.csv`` with iomode `ri`.**

Would some know how to fix this problem, I found no solution on internet (I thought it was because of the creation of a labeled "XXXX.csv" in the csv file rather than only .jpg labels but it seems not to be that. I checked directly in the testscript.py script how ot fix it but, once again I failed.

Thank you so so much for your help!

Hugues

### Operating System

windows

### DeepLabCut version

dlc version 2.2.1

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hello @Hugues1273, could you try running the testscript_multianimal.py too?
I haven't seen this error before (which indicates that a CSV file is trying to be read as an image 🤨). I would add though that these tests all pass on the 3 OS they are automatically tested on at GitHub, so I'd be inclined to think that your DLC installation is fine nonetheless.

**Comment by Hugues1273** [comment]
der jeylau,
thank you for your help,
I directly tried with my own data and it worked, therefore I did not try again with testscript.py

Thank you again

Hugues
