### ISSUE TITLE
create_training_dataset read-only file system error with docker on cluster

### ISSUE THREAD

**Issue by nmtimme** [DeepLabCut/DeepLabCut#1828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I'm attempting to run deeplabcut on a university cluster (Indiana University: Carbonate) using the deeplabcut docker (lastest-gui tag) via singularity (our university's preferred way to use dockers). I have been able to get to the create_training_dataset step (import deeplabcut, create new project, extract frames, label frames, all fine). However, when I run create_training_dataset, I get the following error:

OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt'

I spoke with my university IT staff and they agree that it seems like deeplabcut is trying to write to this python3.8 directory for which I do not have write permission. They suggested finding a way to bindmount this requested directory to another directory where I do have write permissions. However, we are unsure how to do this and I thought someone in the deeplabcut community might have an idea of how to address this problem. I previously had to bindmount a directory with write permissions when I open the deeplabcut docker in singularity to resolve some other write permission errors, but I'm unsure how to do this in this case. Perhaps this is a problem with singularity or how singularity handles the docker? I'd greatly appreciate any advice you can provide. Thanks for your time!

### Operating System

Red Hat Enterprise Linux 7

### DeepLabCut version

2.2.0.2

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

Using singularity, in the latest-gui docker, run...
ipython
import deeplabcut
deeplabcut.create_training_dataset(ConfigPath, augmenter_type='imgaug')

### Relevant log output

```shell
Downloading a ImageNet-pretrained model from http://download.tensorflow.org/models/resnet_v1_50_2016_08_28.tar.gz....
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-4-128412801f55> in <module>
----> 1 deeplabcut.create_training_dataset(ConfigPath, augmenter_type='imgaug')

/usr/local/lib/python3.8/dist-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py in create_training_dataset(config, num_shuffles, Shuffles, windows2linux, userfeedback, trainIndices, testIndices, net_type, augmenter_type)
    798         dlcparent_path = auxiliaryfunctions.get_deeplabcut_path()
    799         defaultconfigfile = os.path.join(dlcparent_path, "pose_cfg.yaml")
--> 800         model_path, num_shuffles = auxfun_models.Check4weights(
    801             net_type, Path(dlcparent_path), num_shuffles
    802         )

/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/auxfun_models.py in Check4weights(modeltype, parent_path, num_shuffles)
     63         else:
     64             if not model_path.is_file():
---> 65                 Downloadweights(modeltype, model_path)
     66 
     67     return str(model_path), num_shuffles

/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/auxfun_models.py in Downloadweights(modeltype, model_path)
     89         response = urllib.request.urlopen(url)
     90         with tarfile.open(fileobj=BytesIO(response.read()), mode="r:gz") as tar:
---> 91             tar.extractall(path=target_dir)
     92     except KeyError:
     93         print("Model does not exist: ", modeltype)

/usr/lib/python3.8/tarfile.py in extractall(self, path, members, numeric_owner)
   2026                 tarinfo.mode = 0o700
   2027             # Do not set_attrs directories, as we will do that further down
-> 2028             self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),
   2029                          numeric_owner=numeric_owner)
   2030 

/usr/lib/python3.8/tarfile.py in extract(self, member, path, set_attrs, numeric_owner)
   2067 
   2068         try:
-> 2069             self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
   2070                                  set_attrs=set_attrs,
   2071                                  numeric_owner=numeric_owner)

/usr/lib/python3.8/tarfile.py in _extract_member(self, tarinfo, targetpath, set_attrs, numeric_owner)
   2139 
   2140         if tarinfo.isreg():
-> 2141             self.makefile(tarinfo, targetpath)
   2142         elif tarinfo.isdir():
   2143             self.makedir(tarinfo, targetpath)

/usr/lib/python3.8/tarfile.py in makefile(self, tarinfo, targetpath)
   2180         source.seek(tarinfo.offset_data)
   2181         bufsize = self.copybufsize
-> 2182         with bltn_open(targetpath, "wb") as target:
   2183             if tarinfo.sparse is not None:
   2184                 for offset, size in tarinfo.sparse:

OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@nmtimme - see here to make the container writable: https://deeplabcut.github.io/DeepLabCut/docs/docker.html

i.e., you need to"

```
deeplabcut-docker bash -v /home/mackenzie/DEEPLABCUT:/home/mackenzie/DEEPLABCUT

(which will mount the full directory into the container in read/write mode)

If read-only access is enough, deeplabcut-docker bash -v /home/mackenzie/DEEPLABCUT:/home/mackenzie/DEEPLABCUT:ro
```

**Comment by nmtimme** [comment]
Hi @MMathisLab !

Thanks for that feedback. However, I have a few more questions about that command. First, I tried to use the deeplabcut-docker tool, but it is not working on my system. I can use pip install to install it to a new conda environment, but then all deeplabcut commands are not recognized. I suspect this is because we don't have docker and instead use singularity to manage containers, if that's the right way to say it. So, I'm trying to take the command you provide for deeplabcut-docker for binding directories and adapt it to singularity. 

So, in the command deeplabcut-docker bash -v /home/mackenzie/DEEPLABCUT:/home/mackenzie/DEEPLABCUT, I'm thinking these are paths that should be adapted to my system. Is that correct? Or is /home/mackenzie/DEEPLABCUT a directory within the container, so I need to bind my local directory to it, via something like localDir:/home/mackenzie/DEEPLABCUT? I'd appreciate any information you can provide. Thanks!

~Nick

**Comment by nmtimme** [comment]
@MMathisLab , I'm wondering if you or anyone else has made progress on this issue. If not, would you mind reopening it since it has not been solved. I would appreciate more information about the directories that need to be bound. Thanks!

**Comment by luiztauffer** [comment]
I think the proposed solution is really suboptimal, because it requires you to have the contents of `dlc_instalation_path/pose_estimation_tensorflow/models/pretrained` in the host machine, otherwise the necessary file `pretrained_model_urls.yaml` can be overwritten by an empty directory in the host.
A better approach, as suggested in https://github.com/DeepLabCut/DeepLabCut/issues/1843 , would be to allow for users to select the path where to save the models, which would also need to be available in the GUI. But that Issue was closed as well?
