### ISSUE TITLE
Skeleton Builder Issue

### ISSUE THREAD

**Issue by diegosancarmen** [DeepLabCut/DeepLabCut#1831]
Hello!

Is there a way to plot the trajectories of specific body parts, versus all body parts?  I am using the Google Colab for training and analyzing.  This is DLC 2.2.1.

When I use `deeplabcut.create_labeled_videos` using the arguments `(path_config_file,videofile_path, videotype=VideoType, draw_skeleton= True)`, the skeleton does not show.  This is the skeleton (and the body parts) as listed in the config.yaml file.

```

https://user-images.githubusercontent.com/101142209/168158495-a7ceef78-1a73-4cdd-a239-5f7415a15713.mp4


individuals:
- individual1
uniquebodyparts:
- leftofrod
- rightofrod
multianimalbodyparts:
- leftpaw
- leftankle
- leftleg
- rightpaw
- rightankle
- rightleg
- tailbase
- tail
bodyparts: MULTI!

    # Fraction of video to start/stop when extracting frames for labeling/refinement
start: 0
stop: 1
numframes2pick: 20

    # Plotting configuration
skeleton: [
  [leftpaw, leftankle], 
  [leftpaw, leftleg], 
  [leftpaw, tailbase], 
  [rightpaw, rightankle], 
  [rightpaw, rightleg], 
  [rightpaw, tailbase], 
  [tailbase, tail]
  ]
skeleton_color: white
pcutoff: 0.9
dotsize: 4
alphavalue: 0.7
colormap: rainbow

```

I get this error when I run `deeplabcut.SkeletonBuilder(path_config_file)` referenced in the [DLC Documentation](https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html):
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-49-4c5fd9cfd290>](https://localhost:8080/#) in <module>()
----> 1 deeplabcut.SkeletonBuilder(path_config_file)

AttributeError: module 'deeplabcut' has no attribute 'SkeletonBuilder'

```
As seen in the screenshots below the forearms are also being detected; what outlier algorithm argument would be best to pass for this?

![Screenshot (5)](https://user-images.githubusercontent.com/101142209/168158967-20c5e983-bb30-42ad-9c88-c8f16f042c44.png)
![Screenshot (6)](https://user-images.githubusercontent.com/101142209/168158971-541a2a9e-b243-46ce-ad1c-8c7380d8d76d.png)

**Comment by MMathisLab** [comment]
@diegosancarmen hey - so the GUI cannot be in Colab, it would have to be out of colab. 

>> get this error when I run deeplabcut.SkeletonBuilder(path_config_file) referenced in the [DLC Documentation](https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html):

>>---------------------------------------------------------------------------
>>AttributeError                            Traceback (most recent call last)
[<ipython-input-49-4c5fd9cfd290>](https://localhost:8080/#) in <module>()
----> 1 deeplabcut.SkeletonBuilder(path_config_file)

>>AttributeError: module 'deeplabcut' has no attribute 'SkeletonBuilder'

You can see the API docs: https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html#id9

and you can pass:
```
displayedbodyparts: list[str] or str, optional, default=”all”
This selects the body parts that are plotted in the video. If all, then all body parts from config.yaml are used. If a list of strings that are a subset of the full list. E.g. [‘hand’,’Joystick’] for the demo Reaching-Mackenzie-2018-08-30/config.yaml to select only these body parts.
```
I would also format the skeleton in your config.yaml file like this, as you don't include the ' 
```
# Plotting configuration
skeleton: [['snout', 'leftear'], ['snout', 'rightear'], ['leftear', 'tailbase'], ['leftear', 'rightear'], ['rightear','tailbase']]

```

**Comment by diegosancarmen** [comment]
Thank you for your help!  I really appreciate your quick response times.
