### ISSUE TITLE
Can't create video by filtered file.[No filtered data file found in......]

### ISSUE THREAD

**Issue by JianzhiZhang1** [DeepLabCut/DeepLabCut#1832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When I analyze my video well，these files were generated.and
![image](https://user-images.githubusercontent.com/103829351/168410734-4f51b4db-114b-4624-8405-95245e388464.png)
Then I performed the refinetracklets step, refining the tracking points in the video. clicke save and filter track.
![image](https://user-images.githubusercontent.com/103829351/168410812-c9cd9af7-6ff7-4955-b39c-8d984f1ca58f.png)
 
next,create video with [use filtered predictions]
![image](https://user-images.githubusercontent.com/103829351/168410856-63386db5-e557-41fa-9e46-50c1703382ab.png)

Unfortunately, I got the error message.
![image](https://user-images.githubusercontent.com/103829351/168410896-648ea286-54a2-4027-ba3a-5f20949e84a8.png)

But the filtered file is already there.
![image](https://user-images.githubusercontent.com/103829351/168410916-fdd27e1c-d37e-4517-b477-9cc80aa30a7c.png)

could you help me! Any help would be greatly appreciated!

### Operating System

operating system：windows 10

### DeepLabCut version

dlc version：2.2.1

### DeepLabCut mode

multi animal

### Device type

gpu

### Relevant log output

```shell
(base) PS C:\Users\Administrator> conda activate DLC-221
(DLC-221) PS C:\Users\Administrator> python -m deeplabcut
C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\statsmodels\compat\pandas.py:65: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import Int64Index as NumericIndex


Starting GUI...
DLC network loading and video analysis starting ...
Using snapshot-500000 for model E:\social-02-2021-10-24\dlc-models\iteration-0\socialOct24-trainset95shuffle1
C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\tf_slim\layers\layers.py:684: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  outputs = layer.apply(inputs, training=is_training)


Activating extracting of PAFs
2022-05-14 12:07:31.849114: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-05-14 12:07:32.230363: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9622 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060, pci bus id: 0000:01:00.0, compute capability: 8.6
No video(s) were found. Please check your paths and/or 'video_type'.
No video(s) were found. Please check your paths and/or 'videotype'.
All H5 files were converted to CSV.
No videos found. Make sure you passed a list of videos and that *videotype* is right.


DLC network loading and video analysis starting ...
Using snapshot-500000 for model E:\social-02-2021-10-24\dlc-models\iteration-0\socialOct24-trainset95shuffle1
C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\tf_slim\layers\layers.py:684: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  outputs = layer.apply(inputs, training=is_training)
Activating extracting of PAFs
2022-05-14 12:08:32.412507: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9622 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060, pci bus id: 0000:01:00.0, compute capability: 8.6


Starting to analyze %  E:\FreeSocialTest\FSoT-01-2022-04-21\videos\2s.mp4
Loading  E:\FreeSocialTest\FSoT-01-2022-04-21\videos\2s.mp4
Duration of video [s]:  2.0 , recorded with  30.0 fps!
Overall # of frames:  60  found with (before cropping) frame dimensions:  1072 1024
Starting to extract posture from the video(s) with batchsize: 8
  0%|                                                                                           | 0/60 [00:00<?, ?it/s]2022-05-14 12:08:34.474719: I tensorflow/stream_executor/cuda/cuda_dnn.cc:368] Loaded cuDNN version 8201
100%|██████████████████████████████████████████████████████████████████████████████████| 60/60 [01:27<00:00,  1.45s/it]
Video Analyzed. Saving results in E:\FreeSocialTest\FSoT-01-2022-04-21\videos...
Using snapshot-500000 for model E:\social-02-2021-10-24\dlc-models\iteration-0\socialOct24-trainset95shuffle1

Processing...  E:\FreeSocialTest\FSoT-01-2022-04-21\videos\2s.mp4
Analyzing E:\FreeSocialTest\FSoT-01-2022-04-21\videos\2sDLC_dlcrnetms5_socialOct24shuffle1_500000.h5
C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\deeplabcut\pose_estimation_tensorflow\lib\inferenceutils.py:256: UserWarning: The network was not trained with identity; setting `identity_only` to False.
  warnings.warn(
C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\deeplabcut\pose_estimation_tensorflow\lib\inferenceutils.py:309: UserWarning: The assembler could not be robustly calibrated. Continuing without it...
  warnings.warn(
60it [00:00, 99.44it/s]
60it [00:00, 6038.73it/s]
The tracklets were created (i.e., under the hood deeplabcut.convert_detections2tracklets was run). Now you can 'refine_tracklets' in the GUI, or run 'deeplabcut.stitch_tracklets'.
Processing...  E:\FreeSocialTest\FSoT-01-2022-04-21\videos\2s.mp4
100%|████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]



C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py:674: UserWarning: No optimal solution found. Employing black magic...
  warnings.warn("No optimal solution found. Employing black magic...")
The videos are analyzed. Time to assemble animals and track 'em...
 Call 'create_video_with_all_detections' to check multi-animal detection quality before tracking.
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
Creating labeled video for  2s
100%|██████████████████████████████████████████████████████████████████████████████████| 60/60 [00:04<00:00, 12.53it/s]
Filtering with median model E:\FreeSocialTest\FSoT-01-2022-04-21\videos\2s.mp4
Saving filtered csv poses!
Found output file for scorer: DLC_dlcrnetms5_socialOct24shuffle1_500000_el
Converting E:\FreeSocialTest\FSoT-01-2022-04-21\videos\2sDLC_dlcrnetms5_socialOct24shuffle1_500000_el.h5...
Found output file for scorer: DLC_dlcrnetms5_socialOct24shuffle1_500000_el_filtered
Converting E:\FreeSocialTest\FSoT-01-2022-04-21\videos\2sDLC_dlcrnetms5_socialOct24shuffle1_500000_el_filtered.h5...
All H5 files were converted to CSV.


Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\deeplabcut\gui\refine_tracklets.py", line 317, in refine_tracklets
    dest = str(Path(self.video).parents[0])
  File "C:\ProgramData\Anaconda3\envs\DLC-221\lib\pathlib.py", line 621, in __getitem__
    raise IndexError(idx)
IndexError: 0
Processing...  E:\FreeSocialTest\FSoT-01-2022-04-21\videos\2s.mp4
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\deeplabcut\refine_training_dataset\stitch.py:674: UserWarning: No optimal solution found. Employing black magic...
  warnings.warn("No optimal solution found. Employing black magic...")
DLC network loading and video analysis starting ...
Using snapshot-500000 for model E:\social-02-2021-10-24\dlc-models\iteration-0\socialOct24-trainset95shuffle1
C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\tf_slim\layers\layers.py:684: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  outputs = layer.apply(inputs, training=is_training)
Activating extracting of PAFs
2022-05-14 12:15:45.867871: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9622 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060, pci bus id: 0000:01:00.0, compute capability: 8.6
Starting to analyze %  E:\social-02-2021-10-24\videos\2s_M1M22123.mp4
Loading  E:\social-02-2021-10-24\videos\2s_M1M22123.mp4
Duration of video [s]:  2.0 , recorded with  30.0 fps!
Overall # of frames:  60  found with (before cropping) frame dimensions:  1020 1024
Starting to extract posture from the video(s) with batchsize: 8
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 60/60 [00:08<00:00,  7.43it/s]
Video Analyzed. Saving results in E:\social-02-2021-10-24\videos...
Using snapshot-500000 for model E:\social-02-2021-10-24\dlc-models\iteration-0\socialOct24-trainset95shuffle1
Processing...  E:\social-02-2021-10-24\videos\2s_M1M22123.mp4
Analyzing E:\social-02-2021-10-24\videos\2s_M1M22123DLC_dlcrnetms5_socialOct24shuffle1_500000.h5
C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\deeplabcut\pose_estimation_tensorflow\lib\inferenceutils.py:256: UserWarning: The network was not trained with identity; setting `identity_only` to False.
  warnings.warn(
C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\deeplabcut\pose_estimation_tensorflow\lib\inferenceutils.py:309: UserWarning: The assembler 

could not be robustly calibrated. Continuing without it...
  warnings.warn(
60it [00:00, 235.90it/s]
60it [00:00, 3759.91it/s]
The tracklets were created (i.e., under the hood deeplabcut.convert_detections2tracklets was run). Now you can 'refine_tracklets' in the GUI, or run 'deeplabcut.stitch_tracklets'.
Processing...  E:\social-02-2021-10-24\videos\2s_M1M22123.mp4
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<?, ?it/s]
The videos are analyzed. Time to assemble animals and track 'em...
 Call 'create_video_with_all_detections' to check multi-animal detection quality before tracking.
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
Creating labeled video for  2s_M1M22123
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 60/60 [00:00<00:00, 93.70it/s]
Found output file for scorer: DLC_dlcrnetms5_socialOct24shuffle1_500000_el
Converting E:\social-02-2021-10-24\videos\2s_M1M22123DLC_dlcrnetms5_socialOct24shuffle1_500000_el.h5...
All H5 files were converted to CSV.


Loading  E:\social-02-2021-10-24\videos\2s_M1M22123.mp4 and data.
Plots created! Please check the directory "plot-poses" within the video directory
Processing...  E:\social-02-2021-10-24\videos\2s_M1M22123.mp4
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<?, ?it/s]
Filtering with median model E:\social-02-2021-10-24\videos\2s_M1M22123.mp4
Saving filtered csv poses!


Creating a video with the Default tracker method!
C:\ProgramData\Anaconda3\envs\DLC-221\lib\site-packages\statsmodels\compat\pandas.py:65: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import Int64Index as NumericIndex
Starting to process video: E:\social-02-2021-10-24\videos\2s_M1M22123.mp4
Loading E:\social-02-2021-10-24\videos\2s_M1M22123.mp4 and data.
No filtered data file found in E:\social-02-2021-10-24\videos for video 2s_M1M22123 and scorer DLC_dlcrnetms5_socialOct24shuffle1_500000 and ellipse tracker.
Loading  E:\social-02-2021-10-24\videos\2s_M1M22123.mp4 and data.
No filtered data file found in E:\social-02-2021-10-24\videos for video 2s_M1M22123 and scorer DLC_dlcrnetms5_socialOct24shuffle1_500000 and ellipse tracker.
Call "deeplabcut.stitch_tracklets()" prior to plotting the trajectories.
Plots could not be created! Videos were not evaluated with the current scorer DLC_dlcrnetms5_socialOct24shuffle1_500000.
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by JianzhiZhang1** [comment]
hey!  @MMathisLab @jeylau The environment I installed the DLC-2.2.1 is listed below, could you help me (base) PS 'C:\Users\Administrator> conda activate DLC-221
(DLC-221) PS C:\Users\Administrator> conda list
packages in environment at C:\ProgramData\Anaconda3\envs\DLC-221:
Name                                              Version                                                                 Build  C           hannel
absl-py                                               1.0.0                                                                  pypi_0               pypi
asttokens                                            2.0.5                                                                  pypi_0               pypi
astunparse                                         1.6.3                                                                  pypi_0               pypi
backcall                                              0.2.0                                                                  pypi_0                pypi
bzip2                                                  1.0.8                                                                  h8ffe710_4          conda-forge
ca-certificates                                    2021.10.8                                                          h5b45459_0         conda-forge
cachetools                                         5.0.0                                                                  pypi_0                   pypi
certifi                                                 2021.10.8                                                           pypi_0                   pypi
charset-normalizer                            2.0.12                                                                 pypi_0                  pypi
colorama                                           0.4.4                                                                   pypi_0                   pypi
cudatoolkit                                        11.6.0                                                                 hc0ea762_10         conda-forge
cudnn                                                8.2.1.32                                                               h754d62a_0        conda-forge
cycler                                                 0.11.0                                                                 pypi_0               pypi
decorator                                           4.4.2                                                                  pypi_0               pypi
deeplabcut                                         2.2.1                                                                  pypi_0               pypi
executing                                           0.8.3                                                                  pypi_0               pypi
filterpy                                               1.4.5                                                                   pypi_0               pypi
flatbuffers                                          2.0                                                                      pypi_0               pypi
fonttools                                            4.31.2                                                                 pypi_0               pypi
gast                                                    0.5.3                                                                   pypi_0               pypi
google-auth                                       2.6.2                                                                   pypi_0               pypi
google-auth-oauthlib                        0.4.6                                                                   pypi_0               pypi
google-pasta                                      0.2.0                                                                  pypi_0               pypi
grpcio                                                 1.44.0                                                                 pypi_0               pypi
h5py                                                    3.6.0                                                                  pypi_0               pypi
idna                                                     3.3                                                                     pypi_0               pypi
imageio                                               2.16.1                                                                 pypi_0               pypi
imageio-ffmpeg                                  0.4.5                                                                   pypi_0               pypi
imgaug                                                0.4.0                                                                   pypi_0               pypi
importlib-metadata                             4.11.3                                                                 pypi_0               pypi
ipython                                                 8.2.0                                                                  pypi_0               pypi
jedi                                                        0.18.1                                                               pypi_0               pypi
joblib                                                    1.1.0                                                                  pypi_0              pypi
keras                                                     2.8.0                                                                  pypi_0               pypi
keras-preprocessing                             1.1.2                                                                  pypi_0               pypi
kiwisolver                                              1.4.2                                                                  pypi_0               pypi
libclang                                                 13.0.0                                                                pypi_0               pypi
libffi                                                       3.4.2                                                                  h8ffe710_5       conda-forge
libzlib                                                      1.2.11                                                              h8ffe710_1014    conda-forge
llvmlite                                                   0.38.0                                                                pypi_0               pypi
markdown                                              3.3.6                                                                 pypi_0               pypi
matplotlib                                              3.5.1                                                                  pypi_0               pypi
matplotlib-inline                                    0.1.3                                                                 pypi_0               pypi
moviepy                                                 1.0.3                                                                  pypi_0               pypi
msgpack                                                1.0.3                                                                  pypi_0               pypi
msgpack-numpy                                    0.4.7.1                                                               pypi_0               pypi
networkx                                                 2.7.1                                                                 pypi_0               pypi
numba                                                     0.55.1                                                               pypi_0               pypi
numexpr                                                  2.8.1                                                                 pypi_0               pypi
numpy                                                     1.21.5                                                               pypi_0               pypi
oauthlib                                                   3.2.0                                                                 pypi_0               pypi
opencv-python                                        4.5.5.64                                                             pypi_0               pypi
openssl                                                     3.0.2                                                                h8ffe710_1       conda-forge
opt-einsum                                               3.3.0                                                                 pypi_0               pypi
packaging                                                 21.3                                                                   pypi_0               pypi
pandas                                                      1.4.2                                                                  pypi_0               pypi
parso                                                         0.8.3                                                                  pypi_0               pypi
patsy                                                         0.5.2                                                                  pypi_0               pypi
pickleshare                                                0.7.5                                                                  pypi_0               pypi
pillow                                                        9.1.0                                                                  pypi_0               pypi
pip                                                            22.0.4                                                                pyhd8ed1ab_0    conda-forge
proglog                                                    0.1.9                                                                  pypi_0               pypi
prompt-toolkit                                         3.0.29                                                                 pypi_0               pypi
protobuf                                                   3.20.0                                                                 pypi_0               pypi
psutil                                                         5.9.0                                                                  pypi_0               pypi
pure-eval                                                  0.2.2                                                                  pypi_0               pypi
pyasn1                                                      0.4.8                                                                  pypi_0               pypi
pyasn1-modules                                       0.2.8                                                                  pypi_0               pypi
pygments                                                  2.11.2                                                                 pypi_0               pypi
pyparsing                                                  3.0.7                                                                  pypi_0               pypi
python                                                      3.8.13                                                               hcf16a7b_0_cpython    conda-forge
python-dateutil                                         2.8.2                                                                  pypi_0               pypi
python_abi                                                3.8                                                                    2_cp38               conda-forge
pytz                                                           2022.1                                                                 pypi_0               pypi
pywavelets                                                1.3.0                                                                  pypi_0               pypi
pyyaml                                                      6.0                                                                    pypi_0               pypi
pyzmq                                                       22.3.0                                                                 pypi_0                pypi
requests                                                    2.27.1                                                                 pypi_0               pypi
requests-oauthlib                                     1.3.1                                                                  pypi_0               pypi
rsa                                                             4.8                                                                    pypi_0               pypi
ruamel-yaml                                             0.17.21                                                              pypi_0              pypi
ruamel-yaml-clib                                      0.2.6                                                                  pypi_0               pypi
scikit-image                                              0.18.1                                                                 pypi_0               pypi
scikit-learn                                                1.0.2                                                                  pypi_0               pypi
scipy                                                          1.8.0                                                                 pypi_0               pypi
setuptools                                                 62.0.0                                                               py38haa244fe_0    conda-forge
shapely                                                      1.8.1.post1                                                       pypi_0               pypi
six                                                              1.16.0                                                                 pypi_0               pypi
sqlite                                                          3.37.1                                                             h8ffe710_0               conda-forge
stack-data                                                  0.2.0                                                                  pypi_0               pypi
statsmodels                                              0.13.1                                                                 pypi_0               pypi
tables                                                        3.6.1                                                                  pypi_0                pypi
tabulate                                                    0.8.9                                                                  pypi_0                pypi
tensorboard                                             2.8.0                                                                 pypi_0                 pypi
tensorboard-data-server                          0.6.1                                                                  pypi_0               pypi
tensorboard-plugin-wit                            1.8.1                                                                  pypi_0               pypi
tensorflow                                                 2.8.0                                                                  pypi_0               pypi
tensorflow-io-gcs-filesystem                    0.24.0                                                                 pypi_0               pypi
tensorpack                                                0.11                                                                   pypi_0               pypi
termcolor                                                  1.1.0                                                                  pypi_0               pypi
tf-estimator-nightly                                  2.8.0.dev2021122109                                        pypi_0               pypi
tf-slim                                                       1.1.0                                                                    pypi_0               pypi
threadpoolctl                                            3.1.0                                                                   pypi_0               pypi
tifffile                                                        2022.3.25                                                           pypi_0               pypi
tk                                                              8.6.12                                                                h8ffe710_0    conda-forge
torch                                                         1.11.0                                                               pypi_0               pypi
tqdm                                                         4.64.0                                                               pypi_0               pypi
traitlets                                                      5.1.1                                                                 pypi_0               pypi
typing-extensions                                     4.1.1                                                                 pypi_0               pypi
ucrt                                                            10.0.20348.0                                                     h57928b3_0    conda-forge
urllib3                                                        1.26.9                                                               pypi_0               pypi
vc                                                               14.2                                                                  hb210afc_6               conda-forge
vs2015_runtime                                         14.29.30037                                                    h902a5da_6    conda-forge
wcwidth                                                     0.2.5                                                                 pypi_0               pypi
werkzeug                                                   2.1.1                                                                 pypi_0               pypi
wheel                                                         0.37.1                                                              pyhd8ed1ab_0    conda-forge
wrapt                                                         1.14.0                                                               pypi_0               pypi
wxpython                                                  4.0.7.post2                                                       pypi_0               pypi
xz                                                               5.2.5                                                               h62dcd97_1    conda-forge
zipp                                                            3.8.0                                                              pypi_0               pypi'

**Comment by jeylau** [comment]
Hi @JianzhiZhang1, thanks for opening the issue. I could reproduce the error you described and found the tiny bug; it's now corrected with #1835. If you want to check it, you could install it with `pip install git+https://github.com/DeepLabCut/DeepLabCut.git@fix1832` 😊

**Comment by benlansdell** [comment]
I had this issue, and the change you made in #1835 fixes things. Thank you!

**Comment by JianzhiZhang1** [comment]
@jeylau Thank you very much from the bottom of my heart, I have also followed your guidance to solve the problem.
