### ISSUE TITLE
Web-based GUI for labeling

### ISSUE THREAD

**Issue by kvuong2711** [DeepLabCut/DeepLabCut#1833]
I see that DeepLabCut has a web-based GUI for labeling here (https://contrib.deeplabcut.org/#). Is there a plan to release the source code for this? My simple goal is to deploy a web-based GUI for labeling, e.g., hosting a web-based GUI so that the annotators don't have to install anything (just need to go to the website and annotate). Is there a simple way to make this work? Thank you!

**Comment by MMathisLab** [comment]
hi @kvuong2711 we are releasing a napari based annotator (see here:https://github.com/DeepLabCut/napari-DLCLabelingAlpha and here: https://github.com/DeepLabCut/napari-deeplabcut), which is much more commonly used. For our model zoo project we hope people will contribute data, so therefore we don't plan to release the source code, but we will release an update that allows one to upload their data to annotate and grab model weights.
