### ISSUE TITLE
Add option for swapping RGB with BGR when training model

### ISSUE THREAD

**Issue by glopesdev** [DeepLabCut/DeepLabCut#1834]
DLC models seem to assume images are encoded in the RGB color space. However, a common source of video frames for inference is OpenCV capture, which unfortunately encodes frames in the BGR color space. A network trained in RGB which is then used for live inference using BGR will suffer from significant pose estimation errors when the dataset of interest contains highly saturated color patches.

DLC itself uses OpenCV to analyze videos, and the current workaround is to swap BGR back to RGB for each frame before running model inference. This is unfortunate, since the computational cost of swapping color channels can be significant, especially when working with high-resolution images or live inference.

It would be interesting to have an option for training DLC models directly in the BGR color space, which would hopefully eliminate the need for the color swap step during inference.

The main concern of doing this would be compatibility with models which currently assume RGB. This could be solved by creating a new option in the `config.yaml` file (and `pose_cfg.yaml`) to indicate the color space used for inference, with RGB as default.

Other considerations:
  * RGB might be the assumed color space for resnet, mobilenet, etc, and swapping color space in the DLC training set might have unforeseen impacts when relying on natural features. If this is the case, would there be performance advantages of moving the color conversion step to the GPU?

Current workarounds:
  * Manually flip color space of labeled images before training.

See also:
https://github.com/bonsai-rx/deeplabcut/issues/6

**Comment by AlexEMG** [comment]
Indeed, I think the major issue is that imagine pertained models are RGB, so this option is not advised (unless one works on grayscale data). So let's close this.
