### ISSUE TITLE
convertcsv2h5 issue

### ISSUE THREAD

**Issue by xirechen** [DeepLabCut/DeepLabCut#1838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I'm trying to combine labeled data from 2 scorers so I need to change the information in the h5 file. I did it by using the function convertcsv2h5, but it turns out to have bug when in `data.columns = data.columns.set_levels([scorer], level='scorer')` where the error looks like `ValueError: On level 0, code max (2) >= length of level (1). NOTE: this index is in an inconsistent state
`
I've noticed that in the csv file, there's no inputs from B1 to C3, and I thought it to be the problem. When I added scorer name to the file, it works for this line, but the h5 file structure actually changed so that deeplabcut can not read it. The h5 keys before looks like `<KeysViewHDF5 ['axis0_label0', 'axis0_label1', 'axis0_label2', 'axis0_level0', 'axis0_level1', 'axis0_level2', 'axis1_label0', 'axis1_label1', 'axis1_label2', 'axis1_level0', 'axis1_level1', 'axis1_level2', 'block0_items_label0', 'block0_items_label1', 'block0_items_label2', 'block0_items_level0', 'block0_items_level1', 'block0_items_level2', 'block0_values']>` while after the change, it looks like `<KeysViewHDF5 ['axis0_label0', 'axis0_label1', 'axis0_label2', 'axis0_level0', 'axis0_level1', 'axis0_level2', 'axis1', 'block0_items_label0', 'block0_items_label1', 'block0_items_label2', 'block0_items_level0', 'block0_items_level1', 'block0_items_level2', 'block0_values', 'block1_items_label0', 'block1_items_label1', 'block1_items_label2', 'block1_items_level0', 'block1_items_level1', 'block1_items_level2', 'block1_values']>`

If simply comment out the set_level function, the h5 file structure will also be changes, which can also be noticed from the csv file, 'unnamed' will be inserted into B1-C3.

### Operating System

Windows

### DeepLabCut version

2.2.0.6

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hello @xirechen, I think your issue was fixed in 2.2.1 with https://github.com/DeepLabCut/DeepLabCut/pull/1769. Could you update deeplabcut with `pip install -U deeplabcut` and let me know?

**Comment by jeylau** [comment]
@xirechen, did the above address your issue?

**Comment by xirechen** [comment]
> @xirechen, did the above address your issue?

yes it has been solved! Thx!
