### ISSUE TITLE
KeyError: 'No object named df_with_missing in the file' #19

### ISSUE THREAD

**Issue by diegosancarmen** [DeepLabCut/DeepLabCut#1839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When I try to start the DLC2Kinematics on both Google Colab and my Anaconda Environment, after running:
```
df, bodyparts, scorer = dlc2kinematics.load_data(h5_path)
```
I get:
```
KeyError: 'No object named df_with_missing in the file'
```

### Operating System

This occurs on both the Google Colab notebook and the Anaconda DEEPLABCUT environment.

### DeepLabCut version

```
In [5]: dlc2kinematics.__version__
Out[5]: '0.0.3'
```

### DeepLabCut mode

single animal

### Device type

N/A

### Steps To Reproduce

```
pip install dlc2kinematics
import dlc2kinematics
h5_path = "/content/sample_TrimDLC_resnet50_sampleApr11shuffle1_20000_el (1).h5"
df, bodyparts, scorer = dlc2kinematics.load_data(h5_path)
```

### Relevant log output

```shell
KeyError                                  Traceback (most recent call last)
<ipython-input-8-fe3b9b5b8035> in <module>()
      1 h5_path = "/content/sample_TrimDLC_resnet50_sampleApr11shuffle1_20000_el (1).h5"
----> 2 df, bodyparts, scorer = dlc2kinematics.load_data("sample_TrimDLC_resnet50_sampleApr11shuffle1_20000_el (1).h5")

2 frames
/usr/local/lib/python3.7/dist-packages/pandas/io/pytables.py in select(self, key, where, start, stop, columns, iterator, chunksize, auto_close)
    848         group = self.get_node(key)
    849         if group is None:
--> 850             raise KeyError(f"No object named {key} in the file")
    851 
    852         # create the storer and axes

KeyError: 'No object named df_with_missing in the file'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hello @diegosancarmen, thanks for reporting this bug. While I push a fix, would you mind closing it here and opening it at https://github.com/AdaptiveMotorControlLab/DLC2Kinematics rather. This makes tracking easier :)

**Comment by jeylau** [comment]
Hello @diegosancarmen, thanks for reporting this bug. While I push a fix, would you mind closing it here and opening it at https://github.com/AdaptiveMotorControlLab/DLC2Kinematics rather. This makes tracking easier :)

**Comment by diegosancarmen** [comment]
Hello Jessy,

I posted this issue at [the other site](https://github.com/AdaptiveMotorControlLab/DLC2Kinematics/issues/19) three days ago, and was awaiting help because I could not proceed with the project.  Seeing as that tickets posted on the DLC github site are seen and answered on a faster timeline, I wanted to address the issue here as well.

**Comment by jeylau** [comment]
I don't know how I missed it 😖Please excuse me!
If you check the source code though, you can see that all that function does by default is:
```python
df = pd.read_hdf(filename, "df_with_missing")
bodyparts = df.columns.get_level_values("bodyparts").unique().to_list()
scorer = df.columns.get_level_values(0)[0]
```
If you replace the first line simply with `df = pd.read_hdf(filename)` and run those in your notebook or your script, it will work ☺️

**Comment by diegosancarmen** [comment]
I had tried that in the past, and it didn't work.  
```
    df = pd.read_hdf(filename)
    bodyparts = df.columns.get_level_values("bodyparts").unique().to_list()
    scorer = df.columns.get_level_values(0)[0]
```

I tried it again just now and the results are the same.  I started a new notebook and changed the `preprocess.py` file before importing DLC2K and it still gives the same error :/

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-6-c8eee90f89d0>](https://localhost:8080/#) in <module>()
----> 1 df, bodyparts, scorer = dlc2kinematics.load_data(path_h5)

2 frames
[/usr/local/lib/python3.7/dist-packages/dlc2kinematics/preprocess.py](https://localhost:8080/#) in load_data(filename, smooth, filter_window, order)
     41 
     42     """
---> 43     df = pd.read_hdf(filename)
     44     bodyparts = df.columns.get_level_values("bodyparts").unique().to_list()
     45     scorer = df.columns.get_level_values(0)[0]

[/usr/local/lib/python3.7/dist-packages/pandas/io/pytables.py](https://localhost:8080/#) in read_hdf(path_or_buf, key, mode, errors, where, start, stop, columns, iterator, chunksize, **kwargs)
    461             iterator=iterator,
    462             chunksize=chunksize,
--> 463             auto_close=auto_close,
    464         )
    465     except (ValueError, TypeError, KeyError):

[/usr/local/lib/python3.7/dist-packages/pandas/io/pytables.py](https://localhost:8080/#) in select(self, key, where, start, stop, columns, iterator, chunksize, auto_close)
    848         group = self.get_node(key)
    849         if group is None:
--> 850             raise KeyError(f"No object named {key} in the file")
    851 
    852         # create the storer and axes

KeyError: 'No object named df_with_missing in the file'
```
I used `deeplabcut.analyze_videos_converth5_to_csv("<video_path>, videotype='mp4')` to see if the h5 file had an error of sorts.  The CSV is attached.  It doesn't appear abnormal to me; I've been able to plot the data and manipulate it without errors previously.  However, I'm still learning DLC so perhaps I'm missing something?

[sample_TrimDLC_resnet50_sampleApr11shuffle1_20000_el.csv](https://github.com/DeepLabCut/DeepLabCut/files/8733002/sample_TrimDLC_resnet50_sampleApr11shuffle1_20000_el.csv)

**Comment by jeylau** [comment]
You shouldn't edit the package files, but in your script or notebook, call the 3 lines above rather than the function load_data.

**Comment by jeylau** [comment]
Closing here as discussion continues at https://github.com/AdaptiveMotorControlLab/DLC2Kinematics/issues/19.

**Comment by Obi-1-Kanobi** [comment]
Hello, I am a undergraduate student at Queen's University. I am working on the dlc2kinematics and I am currently having difficulty with the install, specifically with the h5 file. I am getting an error with the data frame. Are there any prereqs I should have doe to load the data frames before pulling for the h5 file? Any assistance would be greatly appreciated. 
![Screenshot 2022-06-01 142555](https://user-images.githubusercontent.com/106699354/171476418-e92ec3f0-fdb8-4df1-ba48-52354b8451a1.png)

**Comment by diegosancarmen** [comment]
You're in python; you need to exit and use `pip install dlc2kinematics` in the conda environment.  Here's what my terminal looks like:

```
(DEEPLABCUT) C:\Users\[username]\anaconda3\envs\DEEPLABCUT>python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 05:59:45) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> pip install dlc2kinematics
  File "<stdin>", line 1
    pip install dlc2kinematics
        ^
SyntaxError: invalid syntax
>>> !pip install dlc2kinematics
  File "<stdin>", line 1
    !pip install dlc2kinematics
    ^
SyntaxError: invalid syntax
>>> exit()

(DEEPLABCUT) C:\Users\[username]\anaconda3\envs\DEEPLABCUT>pip install dlc2kinematics
...

```

After that, depending on whether you are using Windows or Mac, call `ipython` or `pythonw` to begin running your script.
Check out these links to the relevant [docs](https://deeplabcut.github.io/DeepLabCut/docs/UseOverviewGuide.html?highlight=ipython) and [video tutorial](https://www.youtube.com/watch?v=7xwOhUcIGio).  The video tutorial from the DLC lab is for creating a project, but the essence of using ipython to run your script is the same.
