### ISSUE TITLE
How to evaluate video without training?

### ISSUE THREAD

**Issue by FSet89** [DeepLabCut/DeepLabCut#184]
I installed Deeplabcut 2.0 on Ubuntu 16.04 using Docker as described [here](https://github.com/MMathisLab/Docker4DeepLabCut2.0). I would like to evlauate a video using the pretrained Resnet, without creating a new dataset and performing the training. I'm not sure how to do it. Should I create a new project? The demo assumes that I have a labeled dataset, is it necessary if I just want to perform evaluation?

**Comment by AlexEMG** [comment]
The pretrained ResNet will be good for object recognition (it is pretrained on [imagenet](http://www.image-net.org/)); it won't perform any pose estimation... you could (briefly) try to train with the labeled dataset from the demos. 

(If you just want to test the install you can run https://github.com/AlexEMG/DeepLabCut/blob/master/examples/testscript.py -- this takes ~8min on CPU and 1:30min on GPU)

**Comment by MMathisLab** [comment]
These demos do not assume you have your OWN data, you can run DeepLabCut on our data, here: https://github.com/AlexEMG/DeepLabCut/blob/master/examples/Demo_labeledexample_Openfield.ipynb
https://github.com/AlexEMG/DeepLabCut/blob/master/examples/Demo_labeledexample_MouseReaching.ipynb
