### ISSUE TITLE
Running Testscript : ValueError: Video path does not point to a file

### ISSUE THREAD

**Issue by Rabsev** [DeepLabCut/DeepLabCut#1840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am using the GPU version of DLC with the correct CUDA packages. I have then gone to run ipython testscript.py and I get a value error as seen in below. 

### Operating System

Windows 10

### DeepLabCut version

dlc version 2.2.1 

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

1. Conda activate DEEPLABCUT
2. (DeeplabCut) cd Desktop\DEEPLABCUT\examples
3. ipython testscript.py
4. See Error

### Relevant log output

```shell
(DEEPLABCUT) C:\Users\fs17974\OneDrive - University of Bristol\Desktop\DEEPLABCUT\examples>ipython testscript.py
C:\Users\fs17974\Anaconda3\envs\DEEPLABCUT\lib\site-packages\statsmodels\compat\pandas.py:65: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import Int64Index as NumericIndex
C:\Users\fs17974\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\__init__.py:78: UserWarning:
        As PyTorch is not installed, unsupervised identity learning will not be available.
        Please run `pip install torch`, or ignore this warning.

  warnings.warn(
Imported DLC!
On Windows/OSX tensorpack is not tested by default.
CREATING PROJECT
Project "C:\Users\fs17974\OneDrive - University of Bristol\Desktop\DEEPLABCUT\examples\TEST-Alex-2022-05-19" already exists!
EXTRACTING FRAMES
Config file read successfully.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~\OneDrive - University of Bristol\Desktop\DEEPLABCUT\examples\testscript.py:80, in <module>
     77 deeplabcut.auxiliaryfunctions.write_config(path_config_file, cfg)
     79 print("EXTRACTING FRAMES")
---> 80 deeplabcut.extract_frames(path_config_file, mode="automatic", userfeedback=False)
     82 print("CREATING-SOME LABELS FOR THE FRAMES")
     83 frames = os.listdir(os.path.join(cfg["project_path"], "labeled-data", videoname))

File ~\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\generate_training_dataset\frame_extraction.py:246, in extract_frames(config, mode, algo, crop, userfeedback, cluster_step, cluster_resizewidth, cluster_color, opencv, slider_width, config3d, extracted_cam, videos_list)
    236 if (
    237     askuser == "y"
    238     or askuser == "yes"
   (...)
    242     or askuser == "ouais"
    243 ):  # multilanguage support :)
    245     if opencv:
--> 246         cap = VideoReader(video)
    247         nframes = len(cap)
    248     else:
    249         # Moviepy:

File ~\Anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\utils\auxfun_videos.py:31, in VideoReader.__init__(self, video_path)
     29 def __init__(self, video_path):
     30     if not os.path.isfile(video_path):
---> 31         raise ValueError(f'Video path "{video_path}" does not point to a file.')
     32     self.video_path = video_path
     33     self.video = cv2.VideoCapture(video_path)

ValueError: Video path "C:\Users\fs17974\OneDrive - University of Bristol\Desktop\DEEPLABCUT\DeepLabCut\examples\TEST-Alex-2022-05-19\videos\reachingvideo1.avi" does not point to a file.
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
It said in the traceback that the project "C:\Users\fs17974\OneDrive - University of Bristol\Desktop\DEEPLABCUT\examples\TEST-Alex-2022-05-19" already existed. Have you tried to delete it before re-running the testscript? The video from "examples/Reaching-Mackenzie-2018-08-30" should normally be automatically be copied over.

**Comment by Rabsev** [comment]
Thanks for your help! I deleted the file and now there are two other value errors: 

```bash

C:\Users\fs17974\Anaconda3\envs\DeeplabCut\lib\site-packages\statsmodels\compat\pandas.py:65: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import Int64Index as NumericIndex
C:\Users\fs17974\Anaconda3\envs\DeeplabCut\lib\site-packages\deeplabcut\__init__.py:78: UserWarning:
        As PyTorch is not installed, unsupervised identity learning will not be available.
        Please run `pip install torch`, or ignore this warning.

  warnings.warn(
Imported DLC!
On Windows/OSX tensorpack is not tested by default.
CREATING PROJECT
Project "C:\Users\fs17974\OneDrive - University of Bristol\Desktop\DEEPLABCUT\examples\TEST-Alex-2022-05-25" already exists!
EXTRACTING FRAMES
Config file read successfully.
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 8.53  seconds.
Extracting and downsampling... 256  frames from the video.
256it [00:01, 171.41it/s]
Kmeans clustering ... (this might take a while)
Frames were successfully extracted, for the videos listed in the config.yaml file.

You can now label the frames using the function 'label_frames' (Note, you should label frames extracted from diverse videos (and many videos; we do not recommend training on single videos!)).
CREATING-SOME LABELS FOR THE FRAMES
Plot labels...
Creating images with labels by Alex.
---------------------------------------------------------------------------
**ValueError**                                Traceback (most recent call last)
File ~\OneDrive - University of Bristol\Desktop\DEEPLABCUT\examples\testscript.py:122, in <module>
    108 dataFrame.to_hdf(
    109     os.path.join(
    110         cfg["project_path"],
   (...)
    117     mode="w",
    118 )
    120 print("Plot labels...")
--> 122 deeplabcut.check_labels(path_config_file)
    124 print("CREATING TRAININGSET")
    125 deeplabcut.create_training_dataset(
    126     path_config_file, net_type=NET, augmenter_type=augmenter_type
    127 )

File ~\Anaconda3\envs\DeeplabCut\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py:345, in check_labels(config, Labels, scale, dpi, draw_skeleton, visualizeindividuals)
    342     else:  # for single animal projects
    343         color_by = "bodypart"
--> 345     visualization.make_labeled_images_from_dataframe(
    346         DataCombined,
    347         cfg,
    348         folder,
    349         scale,
    350         dpi=dpi,
    351         keypoint=Labels[0],
    352         draw_skeleton=draw_skeleton,
    353         color_by=color_by,
    354     )
    355 except FileNotFoundError:
    356     print("Attention:", folder, "does not appear to have labeled data!")

File ~\Anaconda3\envs\DeeplabCut\lib\site-packages\deeplabcut\utils\visualization.py:307, in make_labeled_images_from_dataframe(df, cfg, destfolder, scale, dpi, keypoint, draw_skeleton, color_by)
    304 attempttomakefolder(tmpfolder)
    305 ic = io.imread_collection(images_list)
--> 307 h, w = ic[0].shape[:2]
    308 all_same_shape = True
    309 for array in ic[1:]:

File ~\Anaconda3\envs\DeeplabCut\lib\site-packages\skimage\io\collection.py:294, in ImageCollection.__getitem__(self, n)
    292                 raise
    293     else:
--> 294         self.data[idx] = self.load_func(self.files[n], **kwargs)
    295     self._cached = n
    297 return self.data[idx]

File ~\Anaconda3\envs\DeeplabCut\lib\site-packages\skimage\io\_plugins\imageio_plugin.py:10, in imread(*args, **kwargs)
      8 @wraps(imageio_imread)
      9 def imread(*args, **kwargs):
---> 10     return np.asarray(imageio_imread(*args, **kwargs))

File ~\Anaconda3\envs\DeeplabCut\lib\site-packages\imageio\__init__.py:97, in imread(uri, format, **kwargs)
     68 """imread(uri, format=None, **kwargs)
     69
     70 Reads an image from the specified file. Returns a numpy array, which
   (...)
     86     to see what arguments are available for a particular format.
     87 """
     89 warnings.warn(
     90     "Starting with ImageIO v3 the behavior of this function will switch to that of"
     91     " iio.v3.imread. To keep the current behavior (and make this warning dissapear)"
   (...)
     94     stacklevel=2,
     95 )
---> 97 return imread_v2(uri, format=format, **kwargs)

File ~\Anaconda3\envs\DeeplabCut\lib\site-packages\imageio\v2.py:200, in imread(uri, format, **kwargs)
    197 imopen_args = decypher_format_arg(format)
    198 imopen_args["legacy_mode"] = True
--> 200 with imopen(uri, "ri", **imopen_args) as file:
    201     return file.read(index=0, **kwargs)

File ~\Anaconda3\envs\DeeplabCut\lib\site-packages\imageio\core\imopen.py:303, in imopen(uri, io_mode, plugin, extension, format_hint, legacy_mode, **kwargs)
    297         err_msg += (
    298             "\nBased on the extension, the following plugins might add capable backends:\n"
    299             f"{install_candidates}"
    300         )
    302 request.finish()
--> 303 raise err_type(err_msg)

**ValueError**: Could not find a backend to open `C:\Users\fs17974\OneDrive - University of Bristol\Desktop\DEEPLABCUT\examples\TEST-Alex-2022-05-25\labeled-data\reachingvideo1\CollectedData_Alex.csv`` with iomode `ri`.



```

**Comment by jeylau** [comment]
Could you tell me what versions of scikit-image and imageio are installed in your environment?

**Comment by Rabsev** [comment]
Hello, I tried to check what version they are but I get something like this = 
(DeepLabCut) C:\Users\fs17974>print(skimage.__version__)
Unable to initialize device PRN

but then if I try to pip install them then it tells me what version (excuse my ignorance I am very new to all of this!) = 

(DeepLabCut) C:\Users\fs17974>pip install scikit-image
Requirement already satisfied: scikit-image in c:\users\fs17974\anaconda3\envs\deeplabcut\lib\site-packages (0.18.1)
Requirement already satisfied: networkx>=2.0 in c:\users\fs17974\anaconda3\envs\deeplabcut\lib\site-packages (from scikit-image) (2.8.1)
Requirement already satisfied: imageio>=2.3.0 in c:\users\fs17974\anaconda3\envs\deeplabcut\lib\site-packages (from scikit-image) (2.19.2)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\fs17974\anaconda3\envs\deeplabcut\lib\site-packages (from scikit-image) (1.3.0)
Requirement already satisfied: matplotlib!=3.0.0,>=2.0.0 in c:\users\fs17974\anaconda3\envs\deeplabcut\lib\site-packages (from scikit-image) (3.5.2)
Requirement already satisfied: tifffile>=2019.7.26 in c:\users\fs17974\anaconda3\envs\deeplabcut\lib\site-packages (from scikit-image) (2022.5.4)
Requirement already satisfied: scipy>=1.0.1 in c:\users\fs17974\anaconda3\envs\deeplabcut\lib\site-packages (from scikit-image) (1.8.1)
Requirement already satisfied: numpy>=1.16.5 in c:\users\fs17974\anaconda3\envs\deeplabcut\lib\site-packages (from scikit-image) (1.21.6)
Requirement already satisfied: pillow!=7.1.0,!=7.1.1,>=4.3.0 in c:\users\fs17974\anaconda3\envs\deeplabcut\lib\site-packages (from scikit-image) (9.1.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\fs17974\anaconda3\envs\deeplabcut\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image) (4.33.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\fs17974\anaconda3\envs\deeplabcut\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image) (2.8.2)
Requirement already satisfied: cycler>=0.10 in c:\users\fs17974\anaconda3\envs\deeplabcut\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\fs17974\anaconda3\envs\deeplabcut\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image) (1.4.2)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\fs17974\anaconda3\envs\deeplabcut\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image) (3.0.9)
Requirement already satisfied: packaging>=20.0 in c:\users\fs17974\anaconda3\envs\deeplabcut\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image) (21.3)
Requirement already satisfied: six>=1.5 in c:\users\fs17974\anaconda3\envs\deeplabcut\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.0.0,>=2.0.0->scikit-image) (1.16.0)

**Comment by jeylau** [comment]
No problem ☺️ You could achieve the same using `conda list`: it prints all the packages currently installed in your environment. I see that we're using the same versions, so I do not know what may be causing the error. Another user had the same error #1827, and on Windows too coincidentally. I would not worry about it very much though: our automatic tests on GitHub all pass (on all major platforms), and, as that user had reported, you could safely use DeepLabCut.

**Comment by MMathisLab** [comment]
@jeylau I got the same error message today when testing the new napari plugin...
```python
err_msg = 'Could not find a backend to open `/Users/mwmathis/Documents/Birds-Daniel-2021-04-27/labeled-data/montblanc/CollectedData_Daniel.csv`' with iomode `ri`.'` this is when I clicked okay on the default image loader; 
```
unrelated perhaps, but worth noting ... 
<img width="735" alt="Screen Shot 2022-06-03 at 12 42 05 AM" src="https://user-images.githubusercontent.com/28102185/171750704-bfcd6e7d-b223-4f31-818f-2c02b0a178bc.png">

**Comment by Usuy-Leon** [comment]
hey same problem here ! also on windows !
Could not find a backend to open `C:\Users\.....\DeepLabCut\examples\TEST-Alex-2022-10-28\labeled-data\reachingvideo1\CollectedData_Alex.csv`` with iomode `ri`.
:(
