### ISSUE TITLE
Cannot dlopen some GPU libraries - GPU Failure

### ISSUE THREAD

**Issue by lrfreeman** [DeepLabCut/DeepLabCut#1842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have been getting a consistent error that some GPU libraries can't open and thus my machine switches from trying to use GPU to CPU. I have not had it working before on this machine. Though I have installed DLC GPU on two other machines. I have tried:
- wiping the computer and starting with the most up to date drivers and CUDA, didn't work same error
- I have tried specific CUDA versions 11.7, 11.6, 11.4, 11,2, didn't work same error
- I have tried deleting the conda environment and re-creating that
- I have tried rolling back driver version, didn't work

There are consistent errors during conda env creation:

![Enviroment errors](https://user-images.githubusercontent.com/22481774/169550201-baf97a55-bb20-44ca-8bbf-1279ed7579b8.PNG)

GPU Error:

![error](https://user-images.githubusercontent.com/22481774/169550992-42524582-2a97-44f2-a13a-5881dac4d44b.PNG)

### Operating System

![system](https://user-images.githubusercontent.com/22481774/169549471-366005a3-ba55-487d-99b9-af142795b02e.PNG)

![driver](https://user-images.githubusercontent.com/22481774/169550375-9ddbb543-7909-4d48-80c8-60ad79f7bb5b.PNG)

### DeepLabCut version

dlc version: 2.2.1

### DeepLabCut mode

single animal

### Device type

gpu

![smi](https://user-images.githubusercontent.com/22481774/169550352-50e68610-37e7-4b3c-8a1c-aa3d65d3937e.PNG)

### Steps To Reproduce

1. Start with a fresh machine, Windows 10
2. Install Driver 512.77 for my model of GPU, install CUDA 11.2 
3. Download Repo
4. Create conda environment
5. Start conda environment and run test script
6. Failed to load GPU Libraries

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by lrfreeman** [comment]
Solved, by one of two things:
- Downloading windows C++ redistributable
- And running: conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0 in the DEEPLABCUT conda environment

**Comment by Temp2Spec** [comment]
Hey @3man1992 
Thank you very much for raising this and posting a solution. I am experiencing the exact same issue (same error messages and inability to use the GPU for training. 
I have conda 11.7 
Can ask what you mean by 'Downloading windows C++ redistributable' ?
How do you know what cuDNN is included in the DLC files?

Assuming that I have the same cuDNN, will running: conda install -c conda-forge cudatoolkit=11.7 cudnn=8.1.0 in the DEEPLABCUT conda environment be enough?

Thank you in advance. 
A
