### ISSUE TITLE
Controlling save location of pretrained network

### ISSUE THREAD

**Issue by nmtimme** [DeepLabCut/DeepLabCut#1843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Following up on issue #1828 , is there a way to control where the pretrained network is saved during training data set creation? I have been unable to resolve that issue (#1828) using the solution suggested. My main writable directory on the cluster is bound and the container version of the software can created directories in analysis steps before creation of the training data set. Perhaps the directory structures on a cluster were (understandably) not anticipated when designing the container? Thanks!

~Nick

### Operating System

Red Hat Enterprise Linux 7

### DeepLabCut version

2.2.0.2

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

Using singularity, in the latest-gui docker, run...
ipython
import deeplabcut
deeplabcut.create_training_dataset(ConfigPath, augmenter_type='imgaug')

### Relevant log output

```shell
Downloading a ImageNet-pretrained model from http://download.tensorflow.org/models/resnet_v1_50_2016_08_28.tar.gz....
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-4-128412801f55> in <module>
----> 1 deeplabcut.create_training_dataset(ConfigPath, augmenter_type='imgaug')

/usr/local/lib/python3.8/dist-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py in create_training_dataset(config, num_shuffles, Shuffles, windows2linux, userfeedback, trainIndices, testIndices, net_type, augmenter_type)
    798         dlcparent_path = auxiliaryfunctions.get_deeplabcut_path()
    799         defaultconfigfile = os.path.join(dlcparent_path, "pose_cfg.yaml")
--> 800         model_path, num_shuffles = auxfun_models.Check4weights(
    801             net_type, Path(dlcparent_path), num_shuffles
    802         )

/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/auxfun_models.py in Check4weights(modeltype, parent_path, num_shuffles)
     63         else:
     64             if not model_path.is_file():
---> 65                 Downloadweights(modeltype, model_path)
     66 
     67     return str(model_path), num_shuffles

/usr/local/lib/python3.8/dist-packages/deeplabcut/utils/auxfun_models.py in Downloadweights(modeltype, model_path)
     89         response = urllib.request.urlopen(url)
     90         with tarfile.open(fileobj=BytesIO(response.read()), mode="r:gz") as tar:
---> 91             tar.extractall(path=target_dir)
     92     except KeyError:
     93         print("Model does not exist: ", modeltype)

/usr/lib/python3.8/tarfile.py in extractall(self, path, members, numeric_owner)
   2026                 tarinfo.mode = 0o700
   2027             # Do not set_attrs directories, as we will do that further down
-> 2028             self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),
   2029                          numeric_owner=numeric_owner)
   2030 

/usr/lib/python3.8/tarfile.py in extract(self, member, path, set_attrs, numeric_owner)
   2067 
   2068         try:
-> 2069             self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
   2070                                  set_attrs=set_attrs,
   2071                                  numeric_owner=numeric_owner)

/usr/lib/python3.8/tarfile.py in _extract_member(self, tarinfo, targetpath, set_attrs, numeric_owner)
   2139 
   2140         if tarinfo.isreg():
-> 2141             self.makefile(tarinfo, targetpath)
   2142         elif tarinfo.isdir():
   2143             self.makedir(tarinfo, targetpath)

/usr/lib/python3.8/tarfile.py in makefile(self, tarinfo, targetpath)
   2180         source.seek(tarinfo.offset_data)
   2181         bufsize = self.copybufsize
-> 2182         with bltn_open(targetpath, "wb") as target:
   2183             if tarinfo.sparse is not None:
   2184                 for offset, size in tarinfo.sparse:

OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @nmtimme, I thought this was doable, but I appear to be wrong. While you could call `auxfun_models.Downloadweights` and specify `model_path` yourself prior to creating the training dataset, `Check4weights` would still attempt to download the pretrained weights to the default location, causing the OSError 😕

**Comment by rahulporuri** [comment]
@jeylau are you already looking into this issue? If not, I can take a crack at it over this weekend.

I'm interested in this issue because it helps understand the larger design of DeepLabCut - it is an application and not straightforward to use as a library within another application.

**Comment by jeylau** [comment]
Hey @rahulporuri, I haven't had the time to. But I'd be very happy if you contributed this feature! A naive solution is to add an optional root path to `Check4weights`, so users could specify where they want weights to be saved, but you'll probably find something more elegant. Looking forward to reviewing your code ☺️

**Comment by jennyfothergill** [comment]
Could this issue be reopened? On shared HPC systems it would be really useful for users to be able to provide a path where they can save their model.
