### ISSUE TITLE
QOL feature: Better way to detect overlapping keypoints in refinement GUI

### ISSUE THREAD

**Issue by hummuscience** [DeepLabCut/DeepLabCut#1846]
**Is your feature request related to a problem? Please describe.**
In some cases (see image below), the machine labels in images that were extracted as outliers overlap so well that it is hard to detect that it is overlapping. Only one of those labels is correct. This is particularly hard when the colours happen to be so close to each other. This happened a few times and probably just confuses the model when training.

![Screenshot 2022-05-25 at 10 49 32](https://user-images.githubusercontent.com/4943380/170222930-ff56106a-cbb6-4110-9035-8dcb7f5116c5.png)

**Describe the solution you'd like**
I am not yet sure what is the best way to deal with it or make them better visible... Maybe a colour change when they overlap, or something similar?

**Comment by jeylau** [comment]
Hello @Cumol, that's a great suggestion! We're getting closer to releasing a napari plugin for DLC annotations, which I believe will nicely address this particular scenario: machine labels will belong to a different layer, making it easy to set differentially opacity/masking/coloring.

**Comment by jeylau** [comment]
If you want to give it a try, the napari-deeplabcut plugin is now available [here](https://github.com/DeepLabCut/napari-deeplabcut). I'll close this issue, but feel free to provide us with feedback or what we could do to make the plugin better. 😃
