### ISSUE TITLE
Update to Documentation?

### ISSUE THREAD

**Issue by diegosancarmen** [DeepLabCut/DeepLabCut#1849]
**Is your feature request related to a problem? Please describe.**
In the [DLC documentation](https://deeplabcut.github.io/DeepLabCut/docs/recipes/post.html) on post-DLC data processing the example code uses 
```
diff = (bpt1 - bpt2).reshape((len(df), -1, 2))
```
... but the current hdf5 format for a bodypart is `x-coordinate, y-coordinate, likelihood`.  So wouldn't the correct reshape dimensions be `(len(df), -1, 3)` ?

**Comment by jeylau** [comment]
Hello @diegosancarmen. The recipe was originally meant to describe an additional tool to validate annotated images (so when h5 files only contain 2D coordinates. You're right though that for final model outputs one would need `(len(df), -1, 3)`.
We could either edit the recipe by adding:
```
bpt1 = df.xs('head', level='bodyparts', axis=1).to_numpy()[..., :2]
bpt2 = df.xs('tail', level='bodyparts', axis=1).to_numpy()[..., :2]
```
or having the following clause:
```
try:
    diff = (bpt1 - bpt2).reshape((len(df), -1, 2))
except ValueError:
    diff = (bpt1 - bpt2).reshape((len(df), -1, 3))

Would you maybe like to submit a pull request? 😃

**Comment by diegosancarmen** [comment]
@jeylau I'm not very familiar with GitHub yet, so I don't know how to create a pull request.  Could you submit one for me?  

I like the second option you wrote:
```
try:
    diff = (bpt1 - bpt2).reshape((len(df), -1, 2))
except ValueError:
    diff = (bpt1 - bpt2).reshape((len(df), -1, 3))
```

**Comment by jeylau** [comment]
Sure! I do believe though that it's much better if you author it and get all the credit for it! 😃
You could fork DeepLabCut by clicking at the top right of the page; this will add a copy of the DeepLabCut code base in the list of your repositories. There you could directly edit the docs/recipes/post.md file and commit the change. You will then be shown a banner asking whether you want to contribute these changes to our repo, and you're all good!

**Comment by diegosancarmen** [comment]
Done!  Thanks a lot for walking me through it =)

Quick question: what do you recommend as the minimum number of training iterations?  I've been cutting off at 20K due to Google Colab limitations but it doesn't seem to suffice.

**Comment by jeylau** [comment]
Great, I can indeed see the changes. Make sure now that you open a Pull Request so I can merge them into our code 😃
As for the # of iterations, it's hard to tell as it really is specific to one's dataset (roughly though, I'd maybe say 200k+ for single-animal projects as they are trained with batch size 1, and 60k+ for multi-animal, but again, these are very very rough estimates). You typically want to see the loss converge and stabilize, which indicates that your model isn't learning anymore. A neat thing to do too is to save model weights every 5–10k iterations for example, and evaluate your network over all of them to pick the best snapshot.
