### ISSUE TITLE
Exception in SkeletonBuilder

### ISSUE THREAD

**Issue by poja** [DeepLabCut/DeepLabCut#1850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When pressing "Build Skeleton" in the "Create videos" tab of the GUI, I get the following exception:

```
File d:\deeplabcut\deeplabcut\deeplabcut\gui\create_videos.py:248, in Create_Labeled_Videos.build_skeleton(self, event)
    247 def build_skeleton(self, event):
--> 248     skeleton.SkeletonBuilder(self.config)

File d:\deeplabcut\deeplabcut\deeplabcut\utils\skeleton.py:56, in SkeletonBuilder.__init__(self, config_path)
     50 if os.path.isdir(folder) and not any(
     51     folder.endswith(s) for s in ("cropped", "labeled")
     52 ):
     53     self.df = pd.read_hdf(
     54         os.path.join(folder, f'CollectedData_{self.cfg["scorer"]}.h5')
     55     )
---> 56     row, col = self.pick_labeled_frame()
     57     if "individuals" in self.df.columns.names:
     58         self.df = self.df.xs(col, axis=1, level="individuals")

File d:\deeplabcut\deeplabcut\deeplabcut\utils\skeleton.py:110, in SkeletonBuilder.pick_labeled_frame(self)
    108 kept = mask.stack().index.to_list()
    109 np.random.shuffle(kept)
--> 110 row, col = kept.pop()
    111 return row, col

ValueError: too many values to unpack (expected 2)
```

It seems that `kept.pop()` returns a 4-value tuple, instead of the expected 2 values. A deeper inspection shows that my dataframe's index is made of tuples that look like this: 
`('labeled-data',
 'VIDEO1',
 'img1191.png')`
while the code seems to expect a single string value for the dataframe index (`row` is passed later to `self.df.loc`)

### Operating System

windows

### DeepLabCut version

v2.2.1

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

1. Train and evaluate a model
2. Go to "Create videos" tab
3. Press "Build skeleton"

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Good catch @poja, thanks! I've just pushed a fix #1851.
