### ISSUE TITLE
No CSV file created during deeplabcut.analyze_videos()

### ISSUE THREAD

**Issue by diegosancarmen** [DeepLabCut/DeepLabCut#1852]
When I run 
```
deeplabcut.analyze_videos(path_config_file,videofile_path, videotype=VideoType, save_as_csv = True)
```
... after analysis an h5 file is created but there is no CSV file.  

I've been working with both the h5 and the CSV using 
```
deeplabcut.analyze_videos_converth5_to_csv()
```
but wanted to bring this up for fixing, as it was difficult for me to find the aforementioned function previously and I didn't know how to work with h5 files.

**Comment by jeylau** [comment]
Thanks for reporting this bug @diegosancarmen; I've pushed a fix!
