### ISSUE TITLE
'zsh: illegal hardware instruction ipython'

### ISSUE THREAD

**Issue by EllBirk** [DeepLabCut/DeepLabCut#1855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

After downloading deeplabcut (I believe correctly) I cannot open the GUI once in the correct environment. This is the code and error I receive:

(base) elliot@Elliots-iMac ~ % conda activate DEEPLABCUT_M1
(DEEPLABCUT_M1) elliot@Elliots-iMac ~ % pythonw -m deeplabcut
/Users/elliot/opt/anaconda3/envs/DEEPLABCUT_M1/bin/pythonw: line 3:  3628 Illegal instruction: 4  /Users/elliot/opt/anaconda3/envs/DEEPLABCUT_M1/python.app/Contents/MacOS/python "$@"

I notice similar issues have existed and were resolved by using 'conda install python.app' e.g. in #1329 however this does not seem to help in my case. Any advice would be great - thanks!

### Operating System

MacOS BigSur 11.6

### DeepLabCut version

2.2

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

(base) elliot@Elliots-iMac ~ % conda activate DEEPLABCUT_M1
(DEEPLABCUT_M1) elliot@Elliots-iMac ~ % pythonw -m deeplabcut
/Users/elliot/opt/anaconda3/envs/DEEPLABCUT_M1/bin/pythonw: line 3:  3628 Illegal instruction: 4  /Users/elliot/opt/anaconda3/envs/DEEPLABCUT_M1/python.app/Contents/MacOS/python "$@"

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hello @EllBirk!
If you try to call:
```
ipython

import deeplabcut
```
does DeepLabCut import fine?

**Comment by EllBirk** [comment]
Hi! Thanks for getting back to me. Unfortunately not, this is the error I recieve: 

(base) elliot@Elliots-iMac ~ % conda activate DEEPLABCUT_M1
(DEEPLABCUT_M1) elliot@Elliots-iMac ~ % ipython
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:57:50) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.33.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import deeplabcut
zsh: illegal hardware instruction  ipython

**Comment by jeylau** [comment]
Your iMac does come with the new M1 chip, correct?

**Comment by EllBirk** [comment]
Yes that is correct.

**Comment by hailsong** [comment]
I have same issue with M1 mac and conda environment. I'll check it tomorrow in my window environment, with same conda settings.

**Comment by KonKob** [comment]
I have the same problem as EllBirk described. My Macbook has the new M2. Is it maybe related to tensor flow?

**Comment by KonKob** [comment]
Well, for me, the problem was, that I didn't install the Tensorflow Version using the Rosetta Wheel Download as described below. 

https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html
DeepLabCut M1 chip installation environment instructions

**Comment by JuanWang814** [comment]
> 
Thanks for pointing this out! After wasting hours I found M1 chip installation is different...they should make this more conspicuous.


> Well, for me, the problem was, that I didn't install the Tensorflow Version using the Rosetta Wheel Download as described below.
> 
> https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html DeepLabCut M1 chip installation environment instructions
