### ISSUE TITLE
Add charuco board to camera calibration for 3D

### ISSUE THREAD

**Issue by backyardbiomech** [DeepLabCut/DeepLabCut#1856]
One of the more common issues with DLC-3D is the "stereo" camera configuration and proper checkerboard filming needed for 3D reconstruction (e.g. #1847 ). For example, if one camera is rotated (or the checkerboard is rotated too much during filming), opencv may be unable to determine which part of the checkerboard is the common origin in both cameras. 

Based on my understanding, [charuco board calibration](https://docs.opencv.org/3.4/da/d13/tutorial_aruco_calibration.html) should help. Opencv can use the unique aruco blocks within the checkerboard to confirm that it is identifying corresponding parts of the checkerboard, and can even use incomplete checkerboard views if it is moved off screen. The former would be helpful now, and the latter will be most helpful when >2 cameras are possible (because it can be very difficult to get 3 cameras to see a full board). 

I may try to add this later this summer after I add it to Argus for camera intrinsic calibration; I just wanted to get this on the roadmap and see if anyone else wanted to tackle it since it will take me a while to get to it.

**Comment by backyardbiomech** [comment]
As a quick update, I'm procrastinating from other work by working on this. So let me know before tackling it and I'll share my branch. I currently have the board detection working, and am just trying to get the stereo calibration part working.

**Comment by MMathisLab** [comment]
agree is should go on the roadmap!
