### ISSUE TITLE
`Script file xxx\pip-script.py is not present`

### ISSUE THREAD

**Issue by guang20180608** [DeepLabCut/DeepLabCut#1858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

after 'conda env create -f DEEPLABCUT.yaml', there is not 'deeplabcut' model in my 'DEEPLABCUT' env, and when i do 'pip install deeplabcut', it not work.

### Operating System

windows

### DeepLabCut version

dlc version

### DeepLabCut mode

single animal

### Device type

cpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Could you be more explicit? Or show us a screenshot of the error reported in the console?

**Comment by guang20180608** [comment]
thank you, this is my screenshot.
![1](https://user-images.githubusercontent.com/68522028/171579660-fa83d250-5a1c-4666-9be1-18a727d5fc0c.png)
![2](https://user-images.githubusercontent.com/68522028/171579700-3f739bc2-7965-4a7f-8dd8-e07633e2e542.png)

**Comment by MMathisLab** [comment]
hi @guang20180608 you need to have anaconda installed; here it looks like pip is not installed. Can you be sure you follow these steps and open the anaconda prompt terminal:

https://deeplabcut.github.io/DeepLabCut/docs/installation.html

Note, you do *not* need to pip install deeplabcut within the conda env, it is already there if you follow the guide above!

**Comment by guang20180608** [comment]
Thank you for your reply, I can sure that it is based on the tutorial, and did in  anaconda prompt terminal. Then I try to do it in Ubuntu, but I I encountered the same problem. the pip is installed, but 'deeplabcut[gui]'in DEEPLABCUUT.yaml  is not can be installed, so i try to install deeplabcut. I don't think it's a problem with my computer or procedures. Thank you again for your reply,If you're sure there's no problem, I'll try again.
![image](https://user-images.githubusercontent.com/68522028/171683306-eb92999a-a1ea-4295-8cd8-44cc7a1ca14d.png)

**Comment by MMathisLab** [comment]
Yes, but it seems you don't have pip installed properly first; Your error message says that pip cannot be verified and it is being blocked by your university (tsinghua). See your screenshot. Can you try to upgrade pip only first? 

`pip install --upgrade pip`

and if that does not work, as I guess it will not based on your error that says: " `Script file xxx\pip-script.py is not present`

please try to fix pip, then re-try the conda file!

https://www.geeksforgeeks.org/how-to-install-pip-on-windows/#:~:text=Download%20and%20Install%20pip%3A&text=Download%20the%20get%2Dpip.py,where%20the%20above%20file%20exists.&text=and%20wait%20through%20the%20installation,now%20installed%20on%20your%20system.

Also, you are installing deeplabcut outside the conda environment there... you get the error message but then move on to install deeplabcut (without the GUI as well?)
