### ISSUE TITLE
Empty plots-poses after analysing video

### ISSUE THREAD

**Issue by yangyuke001** [DeepLabCut/DeepLabCut#1863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

 I’ve trained and evaluated my model and it all works fine up to this stage, but when I try to plot the trajectories under the tab Analyse videos, the outputs are four empty graphs. I’ve attached one of the graphs here
![plot-likelihood_filtered](https://user-images.githubusercontent.com/27425366/172090842-912b05fb-5201-435a-82f1-dcb753c3ee55.png)
:
Also, in my case the issue is not the p-value cut off. Setting it as low as possible does not repopulate the plots. And the p-values for the frames are pretty much all >.9 for my csv files.

### Operating System

os:windows 10

### DeepLabCut version

dlc version:2.2.1

### DeepLabCut mode

single animal

### Device type

gpu:3080

### Steps To Reproduce

I folllowed the instroduction step by step:
Interactive Project Manager GUI[https://deeplabcut.github.io/DeepLabCut/docs/PROJECT_GUI.html](url)

### Relevant log output

```shell
Using snapshot-20000 for model C:\DeepLabCut0601\hand-yyk-2022-06-01\dlc-models\iteration-0\handJun1-trainset95shuffle1
C:\Users\Citydo\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1692: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
2022-06-06 11:49:41.513739: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3080 Laptop GPU computeCapability: 8.6
coreClock: 1.71GHz coreCount: 48 deviceMemorySize: 16.00GiB deviceMemoryBandwidth: 417.29GiB/s
2022-06-06 11:49:41.514293: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2022-06-06 11:49:41.514518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:      
2022-06-06 11:49:41.514719: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0
2022-06-06 11:49:41.515002: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N
2022-06-06 11:49:41.515462: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 13620 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3080 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6)
Starting to analyze %  C:\DeepLabCut0601\hand-yyk-2022-06-01\videos\1.avi
Loading  C:\DeepLabCut0601\hand-yyk-2022-06-01\videos\1.avi
Duration of video [s]:  25.0 , recorded with  20.0 fps!
Overall # of frames:  500  found with (before cropping) frame dimensions:  1280 720
Starting to extract posture
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [00:15<00:00, 31.91it/s] 
Saving results in C:\DeepLabCut0601\hand-yyk-2022-06-01\videos...
Saving csv poses!
The videos are analyzed. Now your research can truly start! 
 You can create labeled videos with 'create_labeled_video'
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
Filtering with median model C:\DeepLabCut0601\hand-yyk-2022-06-01\videos\1.avi
Saving filtered csv poses!
Loading  C:\DeepLabCut0601\hand-yyk-2022-06-01\videos\1.avi and data.
Plots created! Please check the directory "plot-poses" within the video directory
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@yangyuke001 can you tell us what your output CSV has in it?

**Comment by yangyuke001** [comment]
@MMathisLab 
Thank you for your response!
 Yes ,here is the output:
[0DLC_dlcrnetms5_handJun1shuffle1_20000.csv](https://github.com/DeepLabCut/DeepLabCut/files/8866070/0DLC_dlcrnetms5_handJun1shuffle1_20000.csv)

**Comment by yangyuke001** [comment]
@MMathisLab 
Hi,I have found this qusetion  [there](https://forum.image.sc/t/empty-plots-after-analysing-video/62266).
Unfortunatly,it did not work.

**Comment by yangyuke001** [comment]
@jeylau @MMathisLab 
Hi,

I can get the plots to output fine with a jupyter notebook ,
so I think maybe  it's a GUI perspective bug?

**Comment by grahamfindlay** [comment]
@yangyuke001 I also get empty plots in `plot-poses/` when using the GUI (DLC v2.2.1), but I got correct plots when running `plot_trajectories` without the GUI (from jupyter, interpreter, or script). Try running something like the following script from within your DLC project folder:

```
import pathlib
import deeplabcut

project_path = pathlib.Path(__file__).parent.resolve()
config_path = str(project_path / "config.yaml")
print(f"config_path: {config_path}")
print(f"DeepLabCut version: {deeplabcut.__version__}")

videos_path = project_path / "videos"
videos = list(str(v) for v in videos_path.glob("*.mp4")) # Change to suit your project/data
print(f"Videos to analyze: \n {videos}")

deeplabcut.plot_trajectories(config_path, videos)
```

**Comment by yangyuke001** [comment]
@grahamfindlay 
Thank you very much.
I can get the plots  results from the ipython, but still not work in GUI.
