### ISSUE TITLE
3d deeplabcut does not give out csv file，and does not generate 3D coordinates

### ISSUE THREAD

**Issue by Drjinchaos** [DeepLabCut/DeepLabCut#1864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

The code is executed without error, but the CSV file is not generated and the 3D coordinates are not output。There are marked points on the picture, but there is no skeleton and no 3D coordinates

![image](https://user-images.githubusercontent.com/97204137/172353772-6eca8a26-a043-4a4b-90c5-9b245dbabb2e.png)
![image](https://user-images.githubusercontent.com/97204137/172354150-eebc3a68-9344-408c-8568-9df76cc83e8c.png)
![image](https://user-images.githubusercontent.com/97204137/172354217-60786bf3-bf97-4030-b8ec-4e3bf34c2b28.png)
![image](https://user-images.githubusercontent.com/97204137/172354269-394d359f-60ac-43aa-bdac-f246b8743103.png)

### Operating System

Win10

### DeepLabCut version

dlc version2.2.0.6

### DeepLabCut mode

3d

### Device type

cpu

### Steps To Reproduce

No errors displayed，there is no 3D coordinate generation。

### Relevant log output

```shell
no
```

### Anything else?

no

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by backyardbiomech** [comment]
Can you post frames of your two camera views?

**Comment by Drjinchaos** [comment]
> Can you post frames of your two camera views?

![image](https://user-images.githubusercontent.com/97204137/172406295-32a1830c-161b-4338-b6ae-f6480db59784.png)
I only marked two points for testing, and I only trained the model 15000 times。

**Comment by Drjinchaos** [comment]
> Can you post frames of your two camera views?

By the way, when I calibrate the camera, is there a position requirement between the position of the chessboard and the position of my test object?

**Comment by MMathisLab** [comment]
can you check the video folder and see if there is an H5 file? the 3D plot (far right), you might need to adjust; it's also not really advisable for single point in 3D; hard to verify - but I see the chin point marked on the 2 videos, so I think the H5 is there and this is just a matter of adjusting x, y, z lim: 

https://deeplabcut.github.io/DeepLabCut/docs/Overviewof3D.html#visualize-your-3d-deeplabcut-videos

**Comment by backyardbiomech** [comment]
The chessboard should be moved through and beyond the volume occupied by the parts you are tracking (calibrate, don't extrapolate). My guess regarding the plot is that your axis limits are not encompassing the triangulated xyz coordinates - try removing those from the call to see if anything gets plotted. Also make sure that your "skeleton" between the two points is formatted correctly in the 3d config file. 

As for the csv, that's odd.  Delete the h5 and try running it again. Windows has some very odd file creation problems from python sometimes.

**Comment by Drjinchaos** [comment]
> can you check the video folder and see if there is an H5 file? the 3D plot (far right), you might need to adjust; it's also not really advisable for single point in 3D; hard to verify - but I see the chin point marked on the 2 videos, so I think the H5 is there and this is just a matter of adjusting x, y, z lim:
> 
> https://deeplabcut.github.io/DeepLabCut/docs/Overviewof3D.html#visualize-your-3d-deeplabcut-videos

You're right，the H5 file was indeed generated in video folder. I set the XYZ axis through checkerboard_3d.png.Therefore, it may be that the same marker point is not detected in the two camera angles. Thank you .

**Comment by Drjinchaos** [comment]
> 
I set the XYZ axis through checkerboard_3d.png.
![image](https://user-images.githubusercontent.com/97204137/172500631-18753773-a061-456c-9b8d-ab9aea4ff03b.png)
This is the setting I made in the 3Dconfig file, and I set the value of pcutoff very small, but there is still no skeleton and 3D coordinate generation
![image](https://user-images.githubusercontent.com/97204137/172500682-2dac2981-1a6e-4b44-9889-48e86006a3c0.png)

**Comment by Drjinchaos** [comment]
> 

Does the beyond the volume  mean that the distance from the chessboard to the camera is longer than the distance from the part I track to the camera?

**Comment by MMathisLab** [comment]
sorry if I was unclear, you will NOT get anything in the 3D plot because you only have 1 point -- the min. is 2, as it needs the skeleton. You can plot elsewhere though, as you have the H5 :) hope that helps!

**Comment by backyardbiomech** [comment]
1. By "beyond" I meant to get images of the calibration board closer, further, left, right, above, and below your tracked points in 3D space (at least in the shared view of both cameras). You have to think about calibrating the full **volume**, but also calibrating towards the edges of each camera to help account for lens distortion.
2. Try leaving the limits empty first (or set like `xlim=[None, None]`) so that they are set automatically. 
3. The skeleton is also formatted incorrectly. It should be:

```yaml
skeleton:
-- up1
 - do2
 ```

4. And add points as @MMathisLab said.

**Comment by Drjinchaos** [comment]
> 1. By "beyond" I meant to get images of the calibration board closer, further, left, right, above, and below your tracked points in 3D space (at least in the shared view of both cameras). You have to think about calibrating the full **volume**, but also calibrating towards the edges of each camera to help account for lens distortion.
> 2. Try leaving the limits empty first (or set like `xlim=[None, None]`) so that they are set automatically.
> 3. The skeleton is also formatted incorrectly. It should be:
> 
> ```yaml
> skeleton:
> -- up1
>  - do2
> ```
> 
> 4. And add points as @MMathisLab said.

thank you very much

**Comment by Drjinchaos** [comment]
> sorry if I was unclear, you will NOT get anything in the 3D plot because you only have 1 point -- the min. is 2, as it needs the skeleton. You can plot elsewhere though, as you have the H5 :) hope that helps!

thank you

**Comment by Drjinchaos** [comment]
> 1. By "beyond" I meant to get images of the calibration board closer, further, left, right, above, and below your tracked points in 3D space (at least in the shared view of both cameras). You have to think about calibrating the full **volume**, but also calibrating towards the edges of each camera to help account for lens distortion.
> 2. Try leaving the limits empty first (or set like `xlim=[None, None]`) so that they are set automatically.
> 3. The skeleton is also formatted incorrectly. It should be:
> 
> ```yaml
> skeleton:
> -- up1
>  - do2
> ```
> 
> 4. And add points as @MMathisLab said.

thank you very much, I'll try it again

**Comment by Drjinchaos** [comment]
> 1. By "beyond" I meant to get images of the calibration board closer, further, left, right, above, and below your tracked points in 3D space (at least in the shared view of both cameras). You have to think about calibrating the full **volume**, but also calibrating towards the edges of each camera to help account for lens distortion.
> 2. Try leaving the limits empty first (or set like `xlim=[None, None]`) so that they are set automatically.
> 3. The skeleton is also formatted incorrectly. It should be:
> 
> ```yaml
> skeleton:
> -- up1
>  - do2
> ```
> 
> 4. And add points as @MMathisLab said.

I train the model in project 1 (the first angle of view taken by the camera), then I copy the trained model（for example the snapshot-10000) to project 2 (the second angle of view taken by the camera), and mark the video. Is this right?

**Comment by Drjinchaos** [comment]
> sorry if I was unclear, you will NOT get anything in the 3D plot because you only have 1 point -- the min. is 2, as it needs the skeleton. You can plot elsewhere though, as you have the H5 :) hope that helps!

I train the model in project 1 (the first angle of view taken by the camera), then I copy the trained model（for example the snapshot-10000) to project 2 (the second angle of view taken by the camera), and mark the video. Is this right?
