### ISSUE TITLE
Changing the name of body parts after labeling and training

### ISSUE THREAD

**Issue by Dvirbs** [DeepLabCut/DeepLabCut#1865]
Hi

I am working in 2D project. I am finish labeling all the body parts and training the network.
I have 2D DLC network that are ready to analayze vidoes.
I want to know if there is any way that I can change the name of the body part now after finish tagging and training the network?

Best,
Dvir

**Comment by jeylau** [comment]
Hi @Dvirbs, that's probably doable, although I would recommend against it: doing so requires editing multiple config files, as well as some metadata stored in pickle files, which is quite brittle. Could I ask why you'd like to do so?

**Comment by Dvirbs** [comment]
First, thank you for the fast replay!

The 2D project has 35 body parts that I tagged.
When I want to start work with the anazlyze data (csv file) I saw that the names is too long and not comfortable to work with so i want to change the names to work with the csv more easily.

**Comment by jeylau** [comment]
Perhaps a simple alternative is to define somewhere in your Python script a dictionary mapping old to new names, and then utilize pandas to edit and overwrite the data file. You could do something like the following (note that we'll load the h5 file, as parsing is simpler):
```
import pandas as pd

dict_ = {
    'bpt1_old': 'bpt1_new',
    'bpt2_old': 'bpt2_new',
}
df = pd.read_hdf(my_h5_file)
df.rename(dict_, axis=1, inplace=True)
df.to_csv('new_csv_file_name')
```

**Comment by Dvirbs** [comment]
It may be batter.
Thank you very much Jessy !

Best,
Dvir
