### ISSUE TITLE
Is it possible for DeepLabCut to detect more than one animal, if the network was trained on only just one ?

### ISSUE THREAD

**Issue by ehsainit** [DeepLabCut/DeepLabCut#187]

**Comment by AlexEMG** [comment]
Yes, see Fig 4 in https://www.nature.com/articles/s41593-018-0209-y >> just get all the local maxima of scmap.

**Comment by ehsainit** [comment]
Thanks for the answer. so that means i should adapt the predict.py for that, or can i provide it as an input option in the inference ?

**Comment by ehsainit** [comment]
Great Job on the Software Package and Thanks for the help

**Comment by ehsainit** [comment]
Hi again,
I tried to play around with the code.i was able to extract the scmaps and save them. In the last respond from you guys, it was pointed out that this function is where the thing is happening:
```
def extract_cnn_output(outputs_np, cfg):
    ''' extract locref + scmap from network '''
    scmap = outputs_np[0]
    scmap = np.squeeze(scmap)
    locref = None
    if cfg.location_refinement:
        locref = np.squeeze(outputs_np[1])
        shape = locref.shape
        locref = np.reshape(locref, (shape[0], shape[1], -1, 2))
        locref *= cfg.locref_stdev
    return scmap, locref
```

I dont see how this could be adapted for more than one animal (here the output is extracted and returned).

i would be greatful if you could elaborate more on this issue , Thanks!

**Comment by AlexEMG** [comment]
We are actively working on another version that will incorporate this.
