### ISSUE TITLE
Statsmodels 0.13.2?

### ISSUE THREAD

**Issue by hmaarrfk** [DeepLabCut/DeepLabCut#1870]
I noticed that statsmodels 0.13.2 is disallowed during the installation of deeplabcut.

Was this due to installation woes reported in 
- https://github.com/statsmodels/statsmodels/issues/8279
- https://github.com/DeepLabCut/DeepLabCut/issues/1679

or was there a runtime requirement change?

Thank you for your help.

**Comment by jeylau** [comment]
Hello @hmaarrfk, you're correct, this was because of the issue in Colab. I've just tried to install the latest statsmodels version, and encountered no problems though. The pin could maybe be lifted @MMathisLab? 🤔
