### ISSUE TITLE
Realtime detection from webcam

### ISSUE THREAD

**Issue by KennyTC** [DeepLabCut/DeepLabCut#1872]
**Is your feature request related to a problem? Please describe.**
Is it possible to use deeplabcut to detect realtime from a webcam ?

**Describe the solution you'd like**
I would like to use deeplabcut to detect from output of my webcam in realtime.

**Comment by MMathisLab** [comment]
Please see readme where there is a link to dlclive.deeplabcut.org which is another repo as it has another license.
