### ISSUE TITLE
GUI feature suggestions

### ISSUE THREAD

**Issue by diegosancarmen** [DeepLabCut/DeepLabCut#1875]
Hello DLC Lab!

When I use the DLC GUI to add new videos to an already existing project, if I accidentally click on the wrong video I'm not able to remove it from the list of videos to add.  I think it would be really helpful to have the ability to remove videos before uploading, like in a checkbox format.

Also, when I want to extract frames from this new video to add to the project, the program runs through an extraction of the entire folder of videos, including the ones that have already been extracted from and labeled on.  In my opinion it would be better if the GUI had an option to "extract from all" or "extract from new videos" etc.  Otherwise I have to exit GUI and use ipython to extract frames from the single new video added.

**Comment by MMathisLab** [comment]
hello, please put under the open issue for GUI dev: https://github.com/DeepLabCut/DeepLabCut/issues/1588
