### ISSUE TITLE
Can DLC do this？and with what functions？

### ISSUE THREAD

**Issue by mengxinglvhappy** [DeepLabCut/DeepLabCut#1876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I want to use DLC to identify key points in the image. I wanted to create the training dataset using my own images rather than extracting frames from all the videos.And I want to create labeled image that are different from the ones I used to do the training dataset .Can I use DLC to do this and how to do.

### Operating System

WINDOWS 10

### DeepLabCut version

v2.2.1

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by mengxinglvhappy** [comment]
Do I need to make images into videos?

**Comment by MMathisLab** [comment]
you can use the napari GUI https://github.com/DeepLabCut/napari-deeplabcut. You just need to create a DLC project first. Also see: https://github.com/DeepLabCut/DeepLabCut/wiki/Using-labeled-data-in-DeepLabCut-that-was-annotated-elsewhere
