### ISSUE TITLE
deeplabcut.train_network unable to open table file

### ISSUE THREAD

**Issue by StoCS** [DeepLabCut/DeepLabCut#188]
![screenshot from 2019-01-26 17-12-39](https://user-images.githubusercontent.com/46301576/51788478-75171e00-218f-11e9-99a1-6841145c120a.png)

Ubuntu 18.04 LTS, with an Anaconda Env, & DeepLabCut

I'm trying to test deeplabcut and when applying the following command: deeplabcut.train_network() a problem arises which is "unable to open table file"
more information are in the attached picture

Thanks.
![screenshot from 2019-01-26 17-11-21](https://user-images.githubusercontent.com/46301576/51789400-90872680-2199-11e9-9b8e-af2f009efc13.png)

**Comment by MMathisLab** [comment]
I haven’t seen this before...Seems it was training, so what was the solution/issue, just in case it arises for others thanks!
