### ISSUE TITLE
#1835 not merged?

### ISSUE THREAD

**Issue by diegosancarmen** [DeepLabCut/DeepLabCut#1883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I got the same problem as #1832 but saw that @jeylau fixed it with #1835.

I'm using the Google Colab ipynb notebook, which runs `!pip install deeplabcut` to load DLC.  Apparently the version uploaded doesn't reflect the fix in #1835.  I changed the file manually (I'm not familiar with how to do it in the terminal 😬 so I did it the old-fashioned way).  

### Operating System

Google Colab

### DeepLabCut version

2.2.1

### DeepLabCut mode

single animal

### Device type

Colab Pro

### Steps To Reproduce

In `/usr/local/lib/python3.7/dist-packages/deeplabcut/utils/auxiliaryfunctions.py`
starting line 724:
```    
candidates = []
    for file in grab_files_in_folder(folder, "h5"):
        stem = Path(file).stem
```

So I changed it to
```
    candidates = []
    for file in grab_files_in_folder(folder, "h5"):
        stem = Path(file).stem.replace("_filtered", "")
```

### Anything else?

[Colab Notebook](https://colab.research.google.com/github/DeepLabCut/DeepLabCut/blob/master/examples/COLAB/COLAB_YOURDATA_TrainNetwork_VideoAnalysis.ipynb)
[GitHub File](https://github.com/DeepLabCut/DeepLabCut/blob/master/examples/COLAB/COLAB_YOURDATA_TrainNetwork_VideoAnalysis.ipynb)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
hi @diegosancarmen the pypi of deeplabcut is not updated; you would need to install from the repo, i.e. run:

`!pip install git+https://github.com/DeepLabCut/DeepLabCut.git`

**Comment by diegosancarmen** [comment]
Thank you so much for clarifying @MMathisLab ! I apologize for being ignorant about github and pypi; I really appreciate your help :)
