### ISSUE TITLE
3D coordinates are not generated, CSV file is empty

### ISSUE THREAD

**Issue by Drjinchaos** [DeepLabCut/DeepLabCut#1884]

**Comment by Drjinchaos** [comment]
I use two industrial cameras. Do I need image processing when taking photos?

**Comment by Drjinchaos** [comment]
![image](https://user-images.githubusercontent.com/97204137/174288320-75272245-60c6-483d-9358-8f8a916d1461.png)
this is “stereo_params.pickle”

**Comment by jeylau** [comment]
Please fill in the issue template.

**Comment by jeylau** [comment]
@Drjinchaos, could you share some more details with us? We're otherwise unable to help you.

**Comment by Drjinchaos** [comment]
> Please fill in the issue template.

Thank you,The problem has been solved

**Comment by Scottydoesntkno** [comment]
How did you fix the issue?
