### ISSUE TITLE
Trouble with Cropping for Analysis 

### ISSUE THREAD

**Issue by diegosancarmen** [DeepLabCut/DeepLabCut#1885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

After using the cropping parameter in dlc.analyze_videos, the labels are appearing on the upper left corner of the video instead of on the animal.
Original (no cropping parameter)
![Screenshot (18)](https://user-images.githubusercontent.com/101142209/174462089-7bd7a268-78c3-4d59-b863-55ce171f36c4.png) 
With cropping parameter
![Screenshot (17)](https://user-images.githubusercontent.com/101142209/174462088-024bb1a5-9b68-407d-a6ce-c6dbabd6637a.png)

### Operating System

Google Colab

### DeepLabCut version

2.2.1

### DeepLabCut mode

single animal

### Device type

Colab Pro

### Steps To Reproduce

`deeplabcut.analyze_videos(path_config_file, "/content/drive/MyDrive/DeepLabCut/Trial9B-JDC-2022-05-23/videos/FILE1077_D194_A2_aMSH.mp4", videotype=VideoType, save_as_csv = False, cropping= [700,1250, 300, 900 ])`

### Relevant log output

```shell
N/A
```

### Anything else?

- I obtained the coordinates by using the parameter `cropped = 'GUI'` during `deeplabcut.extract_frames()`.  
  - `[x1, x2, y1, y2] = [700, 1250, 300, 900 ]`
- The frame dimensions are 1920 x 1080.

![Figure_1](https://user-images.githubusercontent.com/101142209/174462139-78c6179e-d118-4240-9fa3-fbca664fee6d.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Did you pass `displaycropped=True` to `create_labeled_video`?

**Comment by diegosancarmen** [comment]
Thank you @jeylau!  That worked perfectly =)
