### ISSUE TITLE
Unable to Label Frames following new install of DLC

### ISSUE THREAD

**Issue by seesesyd** [DeepLabCut/DeepLabCut#1887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I recently installed DLC to a new lab computer, I ran the test script as recommended and the output was that the default cases are functional. When I tried to extract frames, I ran into the issue described in #1809, after uninstalling scripy and scikit-learn and reinstalling with conda, which allowed the frames to be extracted but the warning 

> UserWarning: MiniBatchKMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can prevent it by setting batch_size >= 8192 or by setting the environment variable OMP_NUM_THREADS=1

appeared. I continued on to label the frames and got this error: 

> TypeError: Item at index 0 has type 'int' but a sequence of bytes or strings is expected

and was unable to label any frames. Several lines of highlighted code were also output and are attached below. I see that there is another solution mentioned in #1809 and #1877 that describes specifying the number of threads, would that be useful in this circumstance? If so, what is the exact code I should input?

### Operating System

Windows 10

### DeepLabCut version

2.2.1.1

### DeepLabCut mode

multi animal

### Device type

Quadro RTX 5000 
GPU

### Steps To Reproduce

1. In the deeplabcut environment, ipython
2. import deeplabcut
3. load existing project
4. label frames
5. load frames
6. select video folder

### Relevant log output

```shell
TypeError                                 Traceback (most recent call last)
File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\multiple_individuals_labeling_toolbox.py:972, in MainFrame.browseDir(self, event)
    958     self.image_panel.addcolorbar(
    959         self.img,
    960         self.image_axis,
   (...)
    963         self.colormap,
    964     )
    965 else:
    966     (
    967         self.choiceBox,
    968         self.individualrdb,
    969         self.rdb,
    970         self.change_marker_size,
    971         self.checkBox,
--> 972     ) = self.choice_panel.addRadioButtons(
    973         self.multibodyparts, self.individual_names, self.file, self.markerSize
    974     )
    975     self.image_panel.addcolorbar(
    976         self.img, self.image_axis, self.iter, self.multibodyparts, self.colormap
    977     )
    978 self.individualrdb.Bind(wx.EVT_RADIOBOX, self.select_individual)

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\multiple_individuals_labeling_toolbox.py:257, in ScrollPanel.addRadioButtons(self, bodyparts, individual_names, fileIndex, markersize)
    255 self.change_marker.Enable(False)
    256 names = [k for k in individual_names]
--> 257 self.individualradiobox = wx.RadioBox(
    258     self,
    259     label="Select an individual",
    260     majorDimension=3,
    261     style=wx.RA_SPECIFY_COLS,
    262     choices=names,
    263 )
    265 self.checkBox = wx.CheckBox(self, id=wx.ID_ANY, label="Adjust marker size")
    266 self.choiceBox.Add(self.change_marker, 0, wx.ALL, 5)

TypeError: Item at index 0 has type 'int' but a sequence of bytes or strings is expected
```

### Anything else?

This error appears and no frames are shown in the DLC user interface, but labels described in the config file and the folder selected appear in the user interface:
![Screenshot 2022-06-22 132315](https://user-images.githubusercontent.com/69919418/175109351-b6a52097-c194-4e48-8d5d-b4ba906b4aab.png)
 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
hi @seesesyd we are currently moving fully to the napari-gui for labeling so this will be low priority (since it's very vesion dependent on wxpython, which we are dropping. If you want to use the new GUI it is now very easy! Check out: https://github.com/DeepLabCut/napari-deeplabcut 
 
in short, just run in your conda env: `pip install napari-deeplabcut` and have napari installed.
