### ISSUE TITLE
Incorrect marker types on plots generated during network evaluation

### ISSUE THREAD

**Issue by grahamfindlay** [DeepLabCut/DeepLabCut#1888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

[Section H of the DLC user guide](https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html#h-evaluate-the-trained-network) says: "Note that by default the human labels are plotted as plus (‘+’), DeepLabCut’s predictions either as ‘.’ (for confident predictions with likelihood > p-cutoff) and ’x’ for (likelihood <= pcutoff)." 

But it seems that both my labels and DLC's predictions are plotted as ('+'). 
![Example image](https://user-images.githubusercontent.com/4753005/175133560-f4e9c110-e2d5-4dad-930b-c8902f92642a.png)

### Operating System

Ubunutu 20.04.4 LTS

### DeepLabCut version

2.2.1

### DeepLabCut mode

single animal

### Device type

GPU: NVidia Tesla V100 32GB GPU
CPU: 224-core Intel Xeon Platinum 8276M (Skylake, x86_64).

### Steps To Reproduce

Environment: [dlc_env.yaml](https://github.com/DeepLabCut/DeepLabCut/files/8961236/dlc_env.txt)
Config: [config.yaml](https://github.com/DeepLabCut/DeepLabCut/files/8961238/config.txt)
Run: `deeplabcut.evaluate_network(config_path, plotting=True)`

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Hi @grahamfindlay this is some weird issue that pops up every few years with matplotlib changing the behavior. You can roll back to an older version, or hack the check annotations: https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html#e-check-annotated-frames

**Comment by grahamfindlay** [comment]
@MMathisLab Would you consider leaving this issue open until fixed (e.g. specifying a working `matplotlib` version in the requirements, or updating the docs, or checking  `matplotlib` version in `check_labels`)? I understand that this might be a super low priority issue and it may not be worth the time to fix, but when closed it requires other people who encounter it to have to correct search terms to find it, whereas if open and labeled `wontfix` or similar, people can still find it (and the solution, and avoid opening a duplicate, which I apparently did) by browsing. Whereas browsing closed issues is often infeasible because of the sheer quantity and the fact that they are mixed with mostly solved issues.
