### ISSUE TITLE
"Invalid NAL unit size"/"Partial file" errors during multiple DLC steps

### ISSUE THREAD

**Issue by grahamfindlay** [DeepLabCut/DeepLabCut#1891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When running several DLC steps, including `analyze_videos()` or `create_labeled_video()`, I receive variations of the following error messages, often repeated many times:

```
Starting to extract posture
 99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 171468/173285 [27:19<00:16, 107.78it/s][h264 @ 0x564c0ea705c0] Invalid NAL unit size (7657 > 1005).
[h264 @ 0x564c0ea705c0] Error splitting the input into NAL units.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x564c0d950b80] stream 0, offset 0x4bc925e0: partial file
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 173200/173285 [27:24<00:00, 108.36it/s][mov,mp4,m4a,3gp,3g2,mj2 @ 0x564c0d950b80] stream 0, offset 0x4bc940b3: partial file
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x564c0d950b80] stream 0, offset 0x4bc95aee: partial file
```

It looks to me like `ffmpeg` is probably the source. I searched the docs/issues and found suggestions that re-installing `ffmpeg` may be necessary for some users on Windows. I am using Linux, but tried reinstalling `ffmpeg` anyways. It had no effect. 

So far it _seems_ as if each step is still completing without practical consequences, but of course I can't be sure... 

My colleague said: "I looked up the error message.  The page I found points to trying to use a media codec inside of a media container that doesn't support it. ffmpeg is usually smart enough to pick a reasonable codec for a given container on its own, so I'm guessing that's why it's working even with the error. I have another theory though: Is there an audio track with these video files? [If not], Then it's possible the codec it's rejecting is the audio codec, which (given the message about a 'partial file') may just be a stub with no usable audio content."

Indeed, these files are mp4 containers with H264 codecs, and no audio track. They are generated by [e3vision](https://white-matter.com/products/e3vision/) cameras. 

### Operating System

Ubunutu 20.04.4 LTS

### DeepLabCut version

2.2.1

### DeepLabCut mode

single animal

### Device type

GPU: NVidia Tesla V100 32GB GPU
CPU: 224-core Intel Xeon Platinum 8276M (Skylake, x86_64).

### Steps To Reproduce

Environment: [dlc_env.yaml](https://github.com/DeepLabCut/DeepLabCut/files/8961236/dlc_env.txt)
Config: [config.yaml](https://github.com/DeepLabCut/DeepLabCut/files/8961238/config.txt)
Run: deeplabcut.analyze_videos()

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
hi @grahamfindlay i use the e3vision cameras and don't see this error actually.... (also running on ubuntu 20.04 LTS); maybe ry installing ffmpeg via conda (vs pip?) - I will close since not a DLC specific thing, but please let me know what you find!  :)

**Comment by grahamfindlay** [comment]
Thanks, unfortunately neither re-installing ffmpeg with conda nor pip helps :/
