### ISSUE TITLE
I can not import deeplabcut in colab.

### ISSUE THREAD

**Issue by Banboo-glich** [DeepLabCut/DeepLabCut#1894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I can not import deeplabcut in colab.

### Operating System

operating system

### DeepLabCut version

COLAB_maDLC_TrainNetwork_VideoAnalysis.ipynb

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

![20220630-072814](https://user-images.githubusercontent.com/65880626/176557332-145f8a41-15ef-44dd-a115-fbbcaa5691fa.jpg)
'

### Relevant log output

```shell
AttributeError: module 'matplotlib.cbook' has no attribute '_make_class_factory
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
You need to simply click the RESTART RUNTIME button before import to be sure DLC is installed first.
