### ISSUE TITLE
`load_demo_data` - Expand functionality? Raise exception?

### ISSUE THREAD

**Issue by CBroz1** [DeepLabCut/DeepLabCut#1896]
**Is your feature request related to a problem? Please describe.**
I'm interested in passing a minimal dataset to a colleague similar to the demo datasets, who will make adjustments and either continue training or analyze videos. I was experimenting with `load_demo_data` as a way for them to quickly add absolute paths, and possibly regenerate `training-datasets`.

**Describe the solution you'd like**
1. Expanded the use of `load_demo_data` to allow additional datasets, particularly `transform_data` [here](https://github.com/DeepLabCut/DeepLabCut/blob/master/deeplabcut/create_project/demo_data.py#L54-L60) to permit a list of relative path videos, expanded with the config root directory. 
2. Or, change [this print statement](https://github.com/DeepLabCut/DeepLabCut/blob/master/deeplabcut/create_project/demo_data.py#L60) to `raise Exception`. At present, the next line raises an ambiguous error for unofficial datasets:

```python
UnboundLocalError: local variable 'video_file' referenced before assignment
```

Let me know if you're interested in a PR

**Describe alternatives you've considered**
1. Asking recipients to manually edit config files with destination absolute paths.
2. Writing my own script to pass to the colleague with similar config-editing functionality.

**Comment by backyardbiomech** [comment]
I could be wrong, but I believe all you have to have your colleague do is change the project path in config.yaml to their local path (assuming you pass the full project folder). All dlc functions work from that project path. 

The one exception is when you create a training dataset, that must be performed on the computer on which training will occur.  So, if they want to continue refining the model, they should run `merge_datasets` to advance the iteration, and create a new training dataset.  Before training, the would add their local path to the last best snapshot as `init_weights` in `pose_cfg.yaml`. In other words, other than editing the project path, they would do nothing differently than if they started the projectyon their computer.

**Comment by CBroz1** [comment]
Thanks for the advice! I'm working on [some functions](https://github.com/CBroz1/workflow-deeplabcut/blob/dev/workflow_deeplabcut/load_demo_data.py#L24) that would replace paths in `cfg` files - still under development, willing to PR.

For now, I understand manual path editing to be the intended course, but I'll leave the issue open in case the print statement I mentioned should be considered a bug. If not, we can close.

**Comment by jeylau** [comment]
Hi @CBroz1, there is already a function allowing you to programmatically edit a function: it is `deeplabcut.utils.edit_config()`, and accepts a path to a config and a dictionary of edits you want to make. For example:
```python
edit_config('path_to_train_pose_cfg.yaml', {'init_weights': 'updated_path_to_weights'})
```
To add to what @backyardbiomech said, your colleague won't even need to update the `project_path` as this is automatically done by DeepLabCut.
I'll close the issue, but feel free to reopen it if you need more guidance on contributing new functions. ☺️

**Comment by CBroz1** [comment]
I wasn't aware - Thanks for the pointer @jeylau !
