### ISSUE TITLE
Possible Bug: Multiprocessing with DLC.analyze_videos() returning video "videos are analyzed" before completion.

### ISSUE THREAD

**Issue by LucaH285** [DeepLabCut/DeepLabCut#1897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have a ton of videos to analyze, so I decided to multiprocess the analyze_videos() class on google colab to make things faster. I notice that its very hit or miss, sometimes it works phenomenally well and sometimes it "crashes". The crash reports no error, but simply returns the end statement after analysis is completed, namely: "The videos are analyzed. Now your research can truly start! 
 You can create labeled videos with 'create_labeled_video' ...". This always happens at the 10s mark. My multiprocess class is shown below: 

```
class setDaemonFalse(multiprocessing.Process):
  def _get_daemon(self):
    return(False)

  def _set_daemon(self, value):
    pass
  daemon = property(_get_daemon, _set_daemon)

class useMyPool(multiprocessing.pool.Pool):
  Process = setDaemonFalse

def AnalyzeVids(Vids):
  result = DLC.analyze_videos(config_paths[0], Vids, save_as_csv=True)
  return(result)

def callPool(ProcessNodes):
  pool = useMyPool(ProcessNodes)

  result = pool.map(AnalyzeVids, ExternalVideos)

  pool.close()
  pool.join()
  return(result)

if __name__ == "__main__":
  callPool(4)
```

I typically only send 3-4 videos to be analyzed in parallel on colab (Pro+) since I know how intensive these runs are. I wonder if there is an internal lock when using multiprocessing with DLC? It only ever happens with analyze_videos() though, I use this without any issue with the network trains and the label class.  

And PS, love the software, I've been using it for a few years now and its fantastic!!

### Operating System

Windows 10, but running in Colab so some unix/linux OS. 

### DeepLabCut version

dlc version 2.2.1

### DeepLabCut mode

single animal

### Device type

gpu google colab

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @LucaH285, video analysis is GPU-heavy, I'm not sure tensorflow and multiprocessing would play well together. Multiprocessing's behavior is also OS-specific, which makes matters worse. Instead of writing custom queues or pools, it's perhaps simpler to rather increase `batch_size` in the config.yaml to accelerate inference.

**Comment by LucaH285** [comment]
Hello @jeylau thanks for the tip, I'll try that out! One other solution I came up with (given that our analysis strictly concerns itself with positional tracking) was downsizing the videos from their recorded 1080p resolution to 360p, really sped everything up without messing with the fidelity of data gathering. I imagine this approach would not work with something like fine motor movements in grabbing behaviour, so I'll try the batch size in the future, thanks again!!
