### ISSUE TITLE
Scrolling through labels when labeling

### ISSUE THREAD

**Issue by rojasgabriel** [DeepLabCut/DeepLabCut#1898]
There are times where I would like to edit some labels or skip through the list because some are occluded. Although there isn't an issue per se with having the click on the label that you want to do something with from the sidebar, I think it would be useful if you could scroll through them with the mouse wheel (or with the keyboard arrows). This would make the process a bit faster since it would reduce travel time with the cursor and make for a more cohesive experience in my opinion.

**Comment by backyardbiomech** [comment]
Try the [napari labeler plugin](https://github.com/DeepLabCut/napari-deeplabcut).  It doesn't fit in with the main GUI (yet), but the user experience during lots of labeling is so much improved.

**Comment by rojasgabriel** [comment]
i'll try it out, thanks!
