### ISSUE TITLE
'cuModuleGetFunction(&function, module, kernel_name)' failed with 'CUDA_ERROR_INVALID_HANDLE'

### ISSUE THREAD

**Issue by hejiaonju** [DeepLabCut/DeepLabCut#1899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I encountered the titled error when starting the training from the GUI. I don't have a clue how to solve the problem. I confirmed that GPU is recognized by tensorflow-gpu. CUDA version is 11.2, and cuDNN version 8.2, tensorflow-gpu version is 2.6.0. 

### Operating System

Windows 10

### DeepLabCut version

deeplabcut 2.2.1.1

### DeepLabCut mode

single animal

### Device type

gpu

### Relevant log output

```shell
InternalError: 2 root error(s) found.
  (0) Internal: 'cuModuleGetFunction(&function, module, kernel_name)' failed with 'CUDA_ERROR_INVALID_HANDLE'
         [[node resnet_v1_50/block1/unit_3/bottleneck_v1/add (defined at D:\Anaconda\envs\git2\lib\site-packages\tf_slim\nets\resnet_v1.py:128) ]]
         [[sigmoid_cross_entropy_loss/value/_549]]
  (1) Internal: 'cuModuleGetFunction(&function, module, kernel_name)' failed with 'CUDA_ERROR_INVALID_HANDLE'
         [[node resnet_v1_50/block1/unit_3/bottleneck_v1/add (defined at D:\Anaconda\envs\git2\lib\site-packages\tf_slim\nets\resnet_v1.py:128) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node resnet_v1_50/block1/unit_3/bottleneck_v1/add:
 resnet_v1_50/block1/unit_3/bottleneck_v1/conv3/BatchNorm/FusedBatchNormV3 (defined at D:\Anaconda\envs\git2\lib\site-packages\tf_slim\layers\layers.py:684)
 resnet_v1_50/block1/unit_3/bottleneck_v1/shortcut/MaxPool (defined at D:\Anaconda\envs\git2\lib\site-packages\tf_slim\layers\layers.py:2446)

Input Source operations connected to node resnet_v1_50/block1/unit_3/bottleneck_v1/add:
 resnet_v1_50/block1/unit_3/bottleneck_v1/conv3/BatchNorm/FusedBatchNormV3 (defined at D:\Anaconda\envs\git2\lib\site-packages\tf_slim\layers\layers.py:684)
 resnet_v1_50/block1/unit_3/bottleneck_v1/shortcut/MaxPool (defined at D:\Anaconda\envs\git2\lib\site-packages\tf_slim\layers\layers.py:2446)

Original stack trace for 'resnet_v1_50/block1/unit_3/bottleneck_v1/add':
  File "D:\Anaconda\envs\git2\Scripts\ipython-script.py", line 10, in <module>
    sys.exit(start_ipython())
  File "D:\Anaconda\envs\git2\lib\site-packages\IPython\__init__.py", line 124, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "D:\Anaconda\envs\git2\lib\site-packages\traitlets\config\application.py", line 976, in launch_instance
    app.start()
  File "D:\Anaconda\envs\git2\lib\site-packages\IPython\terminal\ipapp.py", line 318, in start
    self.shell.mainloop()
  File "D:\Anaconda\envs\git2\lib\site-packages\IPython\terminal\interactiveshell.py", line 680, in mainloop
    self.interact()
  File "D:\Anaconda\envs\git2\lib\site-packages\IPython\terminal\interactiveshell.py", line 673, in interact
    self.run_cell(code, store_history=True)
  File "D:\Anaconda\envs\git2\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_cell
    result = self._run_cell(
  File "D:\Anaconda\envs\git2\lib\site-packages\IPython\core\interactiveshell.py", line 2936, in _run_cell
    return runner(coro)
  File "D:\Anaconda\envs\git2\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "D:\Anaconda\envs\git2\lib\site-packages\IPython\core\interactiveshell.py", line 3135, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "D:\Anaconda\envs\git2\lib\site-packages\IPython\core\interactiveshell.py", line 3338, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "D:\Anaconda\envs\git2\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-1ced4355ffc5>", line 1, in <cell line: 1>
    deeplabcut.launch_dlc()
  File "D:\Anaconda\envs\git2\lib\site-packages\deeplabcut\gui\launch_script.py", line 50, in launch_dlc
    app.MainLoop()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\wx\core.py", line 2167, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "D:\Anaconda\envs\git2\lib\site-packages\deeplabcut\gui\label_frames.py", line 232, in label_frames
    label_frames(self.config)
  File "D:\Anaconda\envs\git2\lib\site-packages\deeplabcut\gui\label_frames.py", line 101, in label_frames
    labeling_toolbox.show(config, config3d, sourceCam, imtypes, jump_unlabeled)
  File "D:\Anaconda\envs\git2\lib\site-packages\deeplabcut\gui\labeling_toolbox.py", line 971, in show
    app.MainLoop()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\wx\core.py", line 2167, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "D:\Anaconda\envs\git2\lib\site-packages\deeplabcut\gui\train_network.py", line 315, in train_network
    deeplabcut.train_network(
  File "D:\Anaconda\envs\git2\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 207, in train_network
    train(
  File "D:\Anaconda\envs\git2\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 170, in train
    losses = PoseNetFactory.create(cfg).train(batch)
  File "D:\Anaconda\envs\git2\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnets\base.py", line 22, in train
    heads = self.get_net(batch[Batch.inputs])
  File "D:\Anaconda\envs\git2\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnets\resnet.py", line 66, in get_net
    net, end_points = self.extract_features(inputs)
  File "D:\Anaconda\envs\git2\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnets\resnet.py", line 39, in extract_features
    net, end_points = net_fun(
  File "D:\Anaconda\envs\git2\lib\site-packages\tf_slim\nets\resnet_v1.py", line 270, in resnet_v1_50
    return resnet_v1(
  File "D:\Anaconda\envs\git2\lib\site-packages\tf_slim\nets\resnet_v1.py", line 212, in resnet_v1
    net = resnet_utils.stack_blocks_dense(net, blocks, output_stride)
  File "D:\Anaconda\envs\git2\lib\site-packages\tf_slim\ops\arg_scope.py", line 184, in func_with_args
    return func(*args, **current_args)
  File "D:\Anaconda\envs\git2\lib\site-packages\tf_slim\nets\resnet_utils.py", line 219, in stack_blocks_dense
    net = block.unit_fn(net, rate=1, **unit)
  File "D:\Anaconda\envs\git2\lib\site-packages\tf_slim\ops\arg_scope.py", line 184, in func_with_args
    return func(*args, **current_args)
  File "D:\Anaconda\envs\git2\lib\site-packages\tf_slim\nets\resnet_v1.py", line 128, in bottleneck
    output = nn_ops.relu(shortcut + residual)
  File "D:\Anaconda\envs\git2\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1367, in binary_op_wrapper
    return func(x, y, name=name)
  File "D:\Anaconda\envs\git2\lib\site-packages\tensorflow\python\util\dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "D:\Anaconda\envs\git2\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1700, in _add_dispatch
    return gen_math_ops.add_v2(x, y, name=name)
  File "D:\Anaconda\envs\git2\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 463, in add_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "D:\Anaconda\envs\git2\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "D:\Anaconda\envs\git2\lib\site-packages\tensorflow\python\framework\ops.py", line 3561, in _create_op_internal
    ret = Operation(
  File "D:\Anaconda\envs\git2\lib\site-packages\tensorflow\python\framework\ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)
```

### Anything else?

This is the list of packages installed under conda environment.

(git2) C:\Users\Administrator>conda list
# packages in environment at D:\Anaconda\envs\git2:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu    defaults
abseil-cpp                20210324.2           h0e60522_0    conda-forge
absl-py                   0.15.0                   pypi_0    pypi
aiohttp                   3.8.1            py38h294d835_1    conda-forge
aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py38h294d835_2    conda-forge
astor                     0.8.1              pyh9f0ad1d_0    conda-forge
asttokens                 2.0.5              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
blas                      1.0                         mkl    defaults
bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
blinker                   1.4                        py_1    conda-forge
brotlipy                  0.7.0           py38h294d835_1004    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.6.15            h5b45459_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                4.2.4              pyhd8ed1ab_0    conda-forge
certifi                   2022.6.15        py38haa244fe_0    conda-forge
cffi                      1.15.1           py38hd8c33c5_0    conda-forge
charset-normalizer        2.1.0              pyhd8ed1ab_0    conda-forge
clang                     5.0                      pypi_0    pypi
click                     8.1.3            py38haa244fe_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
cryptography              37.0.4           py38hb7941b4_0    conda-forge
cudatoolkit               11.3.1              h280eb24_10    conda-forge
cudnn                     8.2.1.32             h754d62a_0    conda-forge
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.6.0            py38h885f38d_0    conda-forge
decorator                 4.4.2                    pypi_0    pypi
deeplabcut                2.2.1.1                  pypi_0    pypi
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 0.8.3              pyhd8ed1ab_0    conda-forge
ffmpeg                    4.3.1                ha925a31_0    conda-forge
filterpy                  1.4.5                    pypi_0    pypi
flatbuffers               2.0.6                h0e60522_0    conda-forge
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
fonttools                 4.34.4                   pypi_0    pypi
freetype                  2.10.4               h546665d_1    conda-forge
frozenlist                1.3.0            py38h294d835_1    conda-forge
future                    0.18.2           py38haa244fe_5    conda-forge
gast                      0.4.0              pyh9f0ad1d_0    conda-forge
giflib                    5.2.1                h8d14728_2    conda-forge
google-auth               1.35.0             pyh6c4a22f_0    conda-forge
google-auth-oauthlib      0.4.6              pyhd8ed1ab_0    conda-forge
google-pasta              0.2.0              pyh8c360ce_0    conda-forge
grpcio                    1.46.3           py38he5377a8_0    conda-forge
h5py                      3.7.0           nompi_py38hc790250_100    conda-forge
hdf5                      1.12.1          nompi_h2a0e4a3_104    conda-forge
icu                       68.2                 h0e60522_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
imageio                   2.19.3                   pypi_0    pypi
imageio-ffmpeg            0.4.7                    pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
importlib-metadata        4.11.4           py38haa244fe_0    conda-forge
importlib_resources       5.8.0              pyhd8ed1ab_0    conda-forge
intel-openmp              2022.1.0          h57928b3_3787    conda-forge
ipykernel                 6.15.0             pyh025b116_0    conda-forge
ipython                   8.4.0            py38haa244fe_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.7.1              pyhd8ed1ab_0    conda-forge
jedi                      0.18.1           py38haa244fe_1    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9e                   h8ffe710_2    conda-forge
jsonschema                4.6.2              pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0            py38haa244fe_7    conda-forge
jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.10.0           py38haa244fe_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.1.1              pyhd8ed1ab_0    conda-forge
keras                     2.6.0                    pypi_0    pypi
keras-preprocessing       1.1.2              pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.3                    pypi_0    pypi
krb5                      1.19.3               h1176d77_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libblas                   3.9.0              12_win64_mkl    conda-forge
libcblas                  3.9.0              12_win64_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libcurl                   7.83.1               h789b8ee_0    conda-forge
libdeflate                1.12                 h8ffe710_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
liblapack                 3.9.0              12_win64_mkl    conda-forge
libpng                    1.6.37               h1d00b33_3    conda-forge
libprotobuf               3.17.2               h7755175_1    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libssh2                   1.10.0               h680486a_2    conda-forge
libtiff                   4.4.0                h2ed3b44_1    conda-forge
libuv                     1.43.0               h8ffe710_0    conda-forge
libwebp                   1.2.2                h57928b3_0    conda-forge
libwebp-base              1.2.2                h8ffe710_1    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libzlib                   1.2.12               h8ffe710_1    conda-forge
llvmlite                  0.38.1                   pypi_0    pypi
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markdown                  3.3.7              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.1            py38h294d835_1    conda-forge
matplotlib                3.5.2                    pypi_0    pypi
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py38h294d835_1005    conda-forge
mkl                       2021.4.0           h0e2418a_729    conda-forge
mkl-service               2.4.0            py38h4f8af0f_0    conda-forge
moviepy                   1.0.3                    pypi_0    pypi
msgpack                   1.0.4                    pypi_0    pypi
msgpack-numpy             0.4.8                    pypi_0    pypi
msys2-conda-epoch         20160418                      1    conda-forge
multidict                 6.0.2            py38h294d835_1    conda-forge
nb_conda                  2.2.1                     win_6    conda-forge
nb_conda_kernels          2.3.1            py38haa244fe_1    conda-forge
nbclient                  0.6.6              pyhd8ed1ab_0    conda-forge
nbconvert                 6.5.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            6.5.0              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          6.5.0              pyhd8ed1ab_0    conda-forge
nbformat                  5.4.0              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
networkx                  2.8.4                    pypi_0    pypi
ninja                     1.11.0               h2d74725_0    conda-forge
notebook                  6.4.12             pyha770c72_0    conda-forge
numba                     0.55.2                   pypi_0    pypi
numexpr                   2.8.3                    pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
oauthlib                  3.2.0              pyhd8ed1ab_0    conda-forge
opencv-python             4.6.0.66                 pypi_0    pypi
opencv-python-headless    4.6.0.66                 pypi_0    pypi
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1q               h8ffe710_0    conda-forge
opt_einsum                3.3.0              pyhd8ed1ab_1    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.3                    pypi_0    pypi
pandoc                    2.18                 h57928b3_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pathlib2                  2.3.7.post1      py38haa244fe_1    conda-forge
patsy                     0.5.2                    pypi_0    pypi
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0            py38hd8e0db4_0    conda-forge
pip                       22.1.2             pyhd8ed1ab_0    conda-forge
proglog                   0.1.10                   pypi_0    pypi
prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.30             pyha770c72_0    conda-forge
prompt_toolkit            3.0.30               hd8ed1ab_0    conda-forge
protobuf                  3.17.2           py38h885f38d_0    conda-forge
psutil                    5.9.1            py38h294d835_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
pyjwt                     2.4.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pypubsub                  4.0.3                      py_0    conda-forge
pyqt                      5.12.3           py38h7ae7562_4    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.18.1           py38h294d835_1    conda-forge
pysocks                   1.7.1            py38haa244fe_5    conda-forge
python                    3.8.13          h9a09f29_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.15.3             pyhd8ed1ab_0    conda-forge
python-flatbuffers        1.12               pyhd8ed1ab_1    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.10.2          cpu_py38h907fbb5_0    defaults
pytz                      2022.1                   pypi_0    pypi
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pywavelets                1.3.0                    pypi_0    pypi
pywin32                   303              py38h294d835_0    conda-forge
pywinpty                  2.0.6            py38hd3f51b4_0    conda-forge
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     23.2.0           py38h09162b1_0    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
qtconsole                 5.3.1              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.3.1              pyha770c72_0    conda-forge
qtpy                      2.1.0              pyhd8ed1ab_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.1              pyhd8ed1ab_0    conda-forge
rsa                       4.8                pyhd8ed1ab_0    conda-forge
ruamel-yaml               0.17.21                  pypi_0    pypi
ruamel-yaml-clib          0.2.6                    pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.1.1                    pypi_0    pypi
scipy                     1.8.1            py38h9bf8e03_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                63.1.0           py38haa244fe_0    conda-forge
shapely                   1.8.2                    pypi_0    pypi
six                       1.15.0                   pypi_0    pypi
snappy                    1.1.9                h82413e6_1    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
sqlite                    3.39.0               h8ffe710_0    conda-forge
stack_data                0.3.0              pyhd8ed1ab_0    conda-forge
statsmodels               0.13.1                   pypi_0    pypi
tables                    3.7.0                    pypi_0    pypi
tabulate                  0.8.10                   pypi_0    pypi
tbb                       2021.5.0             h2d74725_1    conda-forge
tensorboard               2.6.0              pyhd8ed1ab_1    conda-forge
tensorboard-data-server   0.6.0            py38haa244fe_2    conda-forge
tensorboard-plugin-wit    1.8.1              pyhd8ed1ab_0    conda-forge
tensorflow                2.6.0           gpu_py38hc0e8100_0    defaults
tensorflow-base           2.6.0           gpu_py38hb3da07e_0    defaults
tensorflow-estimator      2.6.0              pyh7b7c402_0    defaults
tensorflow-gpu            2.6.0                    pypi_0    pypi
tensorpack                0.11                     pypi_0    pypi
termcolor                 1.1.0              pyhd8ed1ab_3    conda-forge
terminado                 0.15.0           py38haa244fe_0    conda-forge
tf-slim                   1.1.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2022.5.4                 pypi_0    pypi
tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
tornado                   6.2              py38h294d835_0    conda-forge
tqdm                      4.64.0                   pypi_0    pypi
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.3.0                hd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
urllib3                   1.26.10            pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  2.1.2              pyhd8ed1ab_1    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
widgetsnbextension        3.6.1              pyha770c72_0    conda-forge
win_inet_pton             1.1.0            py38haa244fe_4    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.12.1                   pypi_0    pypi
wxpython                  4.1.1            py38heb73c8a_7    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yarl                      1.7.2            py38h294d835_2    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h8ffe710_1    conda-forge
zstd                      1.5.2                h6255e5f_2    conda-forge

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Something may be wrong with your tensorflow installation. I've just checked my conda environment, and I only have tensorflow 2.6.0, but no tensorflow-gpu. Could you retry after running `pip uninstall tensorflow-gpu` (or `conda uninstall tensorflow-gpu`)?

**Comment by hejiaonju** [comment]
I tried to uninstall tensorflow-gpu, then when I run the following:
tf.config.list_physical_devices("GPU"), and it shows empty []
Only when I have tensorflow-gpu installed, then it returns [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')].
It seems that tensorflow-gpu is required to recognize GPU.

**Comment by MMathisLab** [comment]
did you try the tips here? https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html?highlight=windows%20gpu#how-to-confirm-that-your-gpu-is-being-used-by-deeplabcut
