### ISSUE TITLE
Running demo "name 'clip' is not defined" (Problem when scorer is not correctly specified during MakingLabeledVideo.py)

### ISSUE THREAD

**Issue by arnitkun** [DeepLabCut/DeepLabCut#19]
I am trying to run the demo. But after running `MakeLabeledVideo.py` i get the following error:
```
Traceback (most recent call last):
  File "MakingLabeledVideo.py", line 92, in <module>
    ny, nx = clip.size  # dimensions of frame (height, width)
NameError: name 'clip' is not defined
```
I have followed step (3) to (8)to run the code on demo video.

Ubuntu 16,  CUDA 8 , CUDNN 5, python 3.5
I think it is an issue with moviepy but i am not sure.

**Comment by AlexEMG** [comment]
Dear Anitkrun,

Thanks for using our toolbox! In the demo code there are no demo videos (linked), so I think this error just means that the video could not be loaded. Same message should have been given in "AnalyzeVideos.py", maybe we should make that clearer. You can of course just put a video in /videos and then run it. Perhaps I do this in the next update. Thanks for pointing this out. 

Perhaps, (if you have a video and it was analyzed), then you need to make sure that you set the parameters for the scorer, i.e. the name:

scorer = 'DeepCut' + "_resnet" + str(resnet) + "_" + Task + str(
    date) + 'shuffle' + str(shuffle) + '_' + str(trainingsiterations)

in myconfig_analysis.py so that poses are loaded. 

Best,
Alexander

**Comment by arnitkun** [comment]
Actually it did, and I created a video folder in the correct place and copied the supplied video of the mouse.

The above stuff happened after that. I think the parameters are set in myconfig_analysis.py . But I will double check to be sure as I don't have access to the GPU machine all the time.

Running MakeLabeledVideo.py tells me i haven't run AnalyzeVideo.py even after running analyzeVideo.py

**Comment by AlexEMG** [comment]
Well, I cannot reproduce your error. I suppose the problem is still to make sure that the scorer name is correct for loading the Dataframe = pd.read_hdf(dataname)  (line 90). Does the corresponding dataname = video.split('.')[0] + scorer + '.h5'  file exist in your videos folder?

**Comment by MMathisLab** [comment]
I only can reproduce the error if there is a video in the folder that hasn't been analyzed (with Step1) first: 

        $  /Evaluation-Tools$ python3 MakingLabeledVideo.py

       Loading  rigVideo_mouse-Dingo_day-30_attempt-1_camera-2_part-0_doe-20180609_rig-1.avi and data.
           Data was not analyzed (run AnalysisVideos.py first).
           Traceback (most recent call last):
           File "MakingLabeledVideo.py", line 95, in <module>
           ny, nx = clip.size  # dimensions of frame (height, width)
           NameError: name 'clip' is not defined

**Comment by arnitkun** [comment]
upon running AnalyzeVideo.py it says video already analyzed. Still I removed the video and checked it again. No success. I am missing something.

**Comment by MMathisLab** [comment]
It does seem it’s not loading the video... Could you check if the MakingLabeledVideo_fast.py works on your data? 

And, as Alex suggested,  can you double check that the scorer name is correct for loading the Dataframe = pd.read_hdf(dataname) (line 90). Does the corresponding dataname = video.split('.')[0] + scorer + '.h5' file exist in your videos folder?

**Comment by arnitkun** [comment]
Apparently there is something wrong with the server here, the download sometimes skips files(??). I have started afresh to find that 'Results' folder, like 'videos/'  is missing. I think perhaps it's generated later, but that didn't happen. So I'll have to get around that before I  can run "fast.py", which to my surprise was not in the previous build. 

I'll let you know as soon as possible.

EDIT: After a fresh rebuild..

running `MakeLabeledVideo.py`
```
Starting  ../videos/ ['reachingvideo1.avi']
Loading  reachingvideo1.avi and data.
Data was not analyzed (run AnalysisVideos.py first).
Traceback (most recent call last):
  File "MakingLabeledVideo.py", line 95, in <module>
    ny, nx = clip.size  # dimensions of frame (height, width)
NameError: name 'clip' is not defined

```
 > I think it is an issue with moviepy but i am not sure.

I stand by my previous logic. 

On running `MakeLabeledVideo_Fast.py`..

```
Starting  ../videos/ ['reachingvideo1.avi']
Loading  reachingvideo1.avi and data.
Data was not analyzed (run AnalysisVideos.py first).
Traceback (most recent call last):
  File "MakingLabeledVideo_fast.py", line 94, in <module>
    ny = clip.height()
AttributeError: 'VideoFileClip' object has no attribute 'height'
```
Never dealt with skvideo issues so no idea.

EDIT 2: 

Contents of `./videos/` 

```
root@EBCRobo:~/DeepLabCut/videos# ls
reachingvideo1.avi
reachingvideo1DeepCut_resnet50_reachingJan30shuffle1_100000.h5
reachingvideo1DeepCut_resnet50_reachingJan30shuffle1_100000includingmetadata.pickle
tempreachingvideo1
```
I think the scorer name is right in myconfig.py :
`scorer = 'Mackenzie'`

**Comment by AlexEMG** [comment]
Thanks for showing all the output. Could you share your myconfig_analysis.py?

The crucial parameters in this configuration file will be:

scorer = 'Mackenzie'
Task = 'reaching'
date = 'Jan30'
resnet = 50
shuffle = 1

**trainingsiterations = 100000  # type the number listed in .pickle file**
pcutoff = 0.1  # likelihood cutoff for body part in image
deleteindividualframes = False

Did you set _trainingiterations_ to the number of "trainingiterations" of the scorer?  In the next update I will make sure this is automatically done... [currently it needs to be set manually, and if the Dataframe is not found then it will spit out these errors. I'll try to make it more transparent in the future.

**Comment by arnitkun** [comment]
myconfig_analysis.py 

```
# Filename and path to behavioral video (for labeling)
videofolder = '../videos/'
cropping = False
videotype='.avi' #type of videos to analyze 

#Note: under the hood there is moviepy, which can handle many types of videos:
#See: https://zulko.github.io/moviepy/_modules/moviepy/video/io/VideoFileClip.html

# If you have stacks of tiffs (instead of videos) you can use "AnalyzeABunchofPictures.py"

# ROI dimensions / bounding box (only used if cropping == True)
# x1,y1 indicates the top left corner and
# x2,y2 is the lower right corner of the croped region.

x1 = 0
x2 = 640
y1 = 277
y2 = 624

#########################################################################################
# Analysis Network parameters (so that the right networks is loaded for analysis)
#########################################################################################
scorer = 'Mackenzie'
Task = 'reaching'
date = 'Jan30'
trainingsFraction = 0.95  # Fraction of labeled images used for training
resnet = 50
snapshotindex = -1
shuffle = 1

storedata_as_csv=False #if true then the time series of poses will (also) be saved as csv. 
# Note the data is always saved in hdf - format which is an efficient format that easily allows to load the full pandas multiarray at a later stage

#########################################################################################    1,1           Top
## For plotting (MakingLabeledVideo.py)
#########################################################################################
trainingsiterations = 100000  # type the number listed in the h5 file containing the pose estimation data. The video will be generated
#based on the labels for this network state.
pcutoff = 0.1  # likelihood cutoff for body part in image

# delete individual (labeled) frames after making video? (note there could be many...)
deleteindividualframes = False
alphavalue=.1 # "strength/transparency level of makers" in individual frames (Vary from 0 to 1. / not working in "MakingLabeledVideo_fast.py")
dotsize = 5
colormap='cool' #hsv'


```                
I didn't update training iterations, thanks for pointing out.  Running   MakeLabeledVideo_fast.py throws some error, but MakeLabeledVideo.py now runs and generates a video, though it wasn't labelled. I might have messed up the directories. Will do a retry and let you know.  




EDIT : on the page "Evaluation Tools instructions" Link : [https://github.com/AlexEMG/DeepLabCut/wiki/Evaluation-Tools---instructions](url) :-

> NOTE: if you are using the Docker container, and did not change the FFMEG binding, this will fail (i.e. it will label frames, but not make the video); you can either run outside the docker, or bind the download file correctly                                                       

But there is `reachingVideoLabelled.xxx` being generated.

**Comment by AlexEMG** [comment]
Good to see, that it is now loaded correctly. Perhaps make the dots bigger/ less transparent if you don't see it on your videos:
**alphavalue=.1
dotsize = 5**
As I said, I will push an updated version that tells the user, which scorers have been found. 

Great to hear that video creation worked in the container!

**Comment by arnitkun** [comment]
Yes, the dot size was too dim/transparent.

It worked. Thank you for the help. You guys are great. Now I can proceed on my task.

Thanks again.

**Comment by cathy-liu23** [comment]
Hello! I'm having a similar issue with MakingLabeledVideo.py.
**Description of the Error**
After running "CUDA_VISIBLE_DEVICES=0 python3 AnalyzeVideos.py" everything seems to be fine. In the videos folder, a .h5, .csv and .pickle file are all generated. But while running "python3 MakingLabeledVideo.py" the error below occurs. It seems as though the scorer cannot be found. At first I kept the scorer the same as the one in the myconfig.py file. Since that also caused the same error, I changed the scorer to "DeepCut_resnet50_fish0817Aug17shuffle1_550000" which is the scorer listed in the error and follows the format of the scorer indicated in the discussion above, but the same error is still generated. Any clues as to what is wrong would be appreciated! Thank you so much for the help!

**Here is the error that I receive in Terminal:**
(deeplabcut) [jli819@biocomputesrg Analysis-tools]$ python3 MakingLabeledVideo.py
Starting  ../videos/ ['fishvideo3.avi']
Folder already exists!
Loading  fishvideo3.avi and data.
Duration of video [s]:  28.57 , recorded with  7.0 fps!
Overall # of frames:  200 with cropped frame dimensions:  [1296, 972]
Generating frames
100%|█████████████████████████████████████| 200/200 [00:00<00:00, 273244.56it/s]
Generating video
The video was not analyzed with this scorer: DeepCut_resnet50_fish0817Aug17shuffle1_550000
No other scorers were found, please run AnalysisVideos.py first.
