### ISSUE TITLE
Error when extracting frames (uniform with start > 0)

### ISSUE THREAD

**Issue by guyts** [DeepLabCut/DeepLabCut#190]
Win10, DLC 2.0.4, GPU environment

After setting up the project and the config file, I run the following code to extract frames:

`deeplabcut.extract_frames(path_config_file,'automatic','uniform',crop=True, checkcropping=True)`

I get the following dialogue:

```
Config file read successfully.
Do you want to extract (perhaps additional) frames for video: D:\dlc-blinking\xxx\eyes_only-Guy-gpu-2019-01-29\videos\animal_3_video_2_150fps_correct.mp4 ?

yes/no

```

To which I respond with `yes`. However, I then get an error:

```
  File "C:\Users\xxx\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\generate_training_dataset\frame_extraction.py", line 168, in extract_frames
    ax.imshow(image)

UnboundLocalError: local variable 'image' referenced before assignment
```

I can attach my config file if necessary to debug. I couldn't figure out the cause, but this worked just fine on the CPU env.

**Comment by guyts** [comment]
To update on this - I created a new project (using CPU this time), where I had to extract frames from scratch.
I set up the config file and the project, and got a similar error:
`UnboundLocalError: local variable 'image' referenced before assignment`

I'm attaching here the config file from this latest case, perhaps something is wrong there?
[config-text.txt](https://github.com/AlexEMG/DeepLabCut/files/2823458/config-text.txt)

**Comment by AlexEMG** [comment]
Thanks for giving me all the details. Ok, I could now recreate the error. For the time being you can fix it by running instead:

```deeplabcut.extract_frames(cfg,algo='uniform',opencv=False)```

(the opencv version will be fixed in the next release).
