### ISSUE TITLE
`get_list_of_videos` errors when passed filepaths and `videotype=None`

### ISSUE THREAD

**Issue by CBroz1** [DeepLabCut/DeepLabCut#1900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I'm setting up a [script to call `analyze_videos`](https://github.com/datajoint/element-deeplabcut/blob/main/element_deeplabcut/readers/dlc_reader.py#L152). For end-user clarity, I set all parameters to defaults, including `videotype`. In doing so `get_list_of_videos` gets a list of filepaths with an an explicit `videotype=None`

### Operating System

OSX

### DeepLabCut version

2.2.1.1

### DeepLabCut mode

single animal

### Device type

Intel Core i7

### Steps To Reproduce

```python
from deeplabcut.pose_estimation_tensorflow import analyze_videos
analyze_videos('my/config.yaml','my/videos/vid.mp4',videotype=None)
```

### Anything else?

Based on the `analyze_videos` docstring, I would expect it to look for supported extensions when `videotype` is None, even when `videos` is not a directory.
>    videotype: str, optional, default=""
>        Checks for the extension of the video in case the input to the video is a
>        directory. Only videos with this extension are analyzed. If left unspecified,
>        videos with common extensions ('avi', 'mp4', 'mov', 'mpeg', 'mkv') are kept.
        
Suggestions
1. Move [this conditional](https://github.com/DeepLabCut/DeepLabCut/blob/master/deeplabcut/utils/auxiliaryfunctions.py#L349-L350) outside the parent if clause, to call `auxfun_videos.SUPPORTED_VIDEOS` even when input is not a directory.
2. Modify to above docstring to restrict the unspecified behavior to only when `videos` is a directory.

Happy to submit a PR if desired

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @CBroz1. I'm confused about what the bug is. When passing a path (or a list of them) pointing to videos, `videotype` is irrelevant as what videos should be analyzed is unambiguous; note also that the default is the empty string `videotype=""` (I suspect `None` would trigger a TypeError here https://github.com/DeepLabCut/DeepLabCut/blob/10ef6ef2a728afd134e6e32af12df06040eebc01/deeplabcut/utils/auxiliaryfunctions.py#L370).

**Comment by CBroz1** [comment]
Ah! My mistake - I was overlooking the distinction between empty string and None. Thanks for the clarification
