### ISSUE TITLE
extract_outlier_frames should not move videos

### ISSUE THREAD

**Issue by johnmbarrett** [DeepLabCut/DeepLabCut#1901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

On file systems where symlinking is not possible, extract_outlier_frames moves the video. In create_new_project, I can stop this happening by setting copy_videos to True, but extract_outlier_frames has no such option.

### Operating System

Windows 10

### DeepLabCut version

DLC 2.2.1.1

### DeepLabCut mode

single animal

### Device type

NVIDIA GeForce GT 730

### Steps To Reproduce

1) Download the attached [script](https://github.com/DeepLabCut/DeepLabCut/files/9098869/test.txt) and [video](https://github.com/DeepLabCut/DeepLabCut/files/9098858/test.zip) to a file system where it is not possible to create symlinks (in my case this happens to be a network drive)
2) Unzip the video
3) Rename test.txt to test.py
4) Change the paths on lines 8-9 of test.py to point to where you keep your DLC projects and where you downloaded the video in step 1
5) Run test.py
6) At the first prompt (line 13), change both the numframes2pick and the TrainingFraction in config.yaml to 1
7) Label the frames
8) [Optional, but it will go a lot faster if you do] At the second prompt (line 21), in the DLC model's pose_cfg.yaml file, change the display_iters and save_iters both to 1 and multi_step to:
```
- - 0.005
  - 1
```
9) Wait for the script to finish running
10) Navigate to the folder where you unzipped the video to in step 2

Expected behaviour: test.avi is still there

Actual behaviour: it has been moved inside the DLC project folder

### Anything else?

I believe this to have been introduced in #1272. As mentioned up top, this is fixable when creating a project by passing copy_videos=True, but not with extract_outlier_frames. More generally, I'm not sure moving videos is the best default option, as it is liable to lead to user confusion and may interfere with other scripts/programs that expect the videos to be in whatever folder they came from. In my opinion, the safer default would be to symlink if possible, otherwise copy, cutting only if the user specifies copy_videos=False and symlinking is impossible.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hello @johnmbarrett, I agree with you. It didn't occur to me at the time I addressed #1272, but moving files around does not seem like a desirable default behavior. Would you like to submit a PR?

**Comment by MMathisLab** [comment]
@jeylau can you submit the PR, thanks! good to have this fixed in upcoming release :)
