### ISSUE TITLE
Triangulation –> converting your 2D to 3D

### ISSUE THREAD

**Issue by Elaheh-Motamedi** [DeepLabCut/DeepLabCut#1902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi,
When I run 
deeplabcut.triangulate(config_path3d,video_path,filterpredictions=True)
I get : IndexError: list index out of range

### Operating System

operating system Linux 20

### DeepLabCut version

dlc version2.2.1.1

### DeepLabCut mode

3d

### Device type

cpu

### Steps To Reproduce

1- Conda activate DEEPLABCUT
2- ipython
3- import DEEPLABCUT
4-deeplabcut.create_new_project_3d
5-deeplabcut.calibrate_cameras(config_path3d, cbrow=8, cbcol=6, calibrate=False, alpha=0.9)
6-deeplabcut.calibrate_cameras(config_path3d, cbrow=8, cbcol=6, calibrate=True, alpha=0.9)
7-deeplabcut.check_undistortion(config_path3d, cbrow=8, cbcol=6)
8-video_path = '/home/arms/test3-Ela-2022-07-13-3d/videos'
9-config_path3d= '/home/arms/test3-Ela-2022-07-13-3d/config.yaml'
10-deeplabcut.triangulate(config_path3d,video_path,filterpredictions=True)
11see errro:
![IMG_2404](https://user-images.githubusercontent.com/101594016/178787506-7ce7d54e-ba6e-4b15-be7f-825b986130f5.jpg)

in my videos folder I have:
![Screenshot from 2022-07-13 12-40-48](https://user-images.githubusercontent.com/101594016/178787336-060b0059-658f-4807-b62f-0e2ec50f6639.png)

### Anything else?

I have another question regarding to output of deeplabcut.check_undistortion(config_path3d, cbrow=8, cbcol=6)
I want to be sure the calibration is done correctly or not.
![left-02_undistort](https://user-images.githubusercontent.com/101594016/178787940-a863dadd-ad74-4b12-8be4-fb29f527cb5c.jpg)

Thank you.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Could you retry with `deeplabcut.triangulate(config_path3d, video_path, videotype='avi', filterpredictions=True)` and let me know if this changes anything?

**Comment by Elaheh-Motamedi** [comment]
Thank you for your reply.
No, I got the same error as well.
![2e](https://user-images.githubusercontent.com/101594016/179020138-f0c263b3-7076-478c-af35-57e00d05d6e7.jpg)

**Comment by backyardbiomech** [comment]
That undistortion image is not good - unless you are using a panoramic camera. The board might be too small in the image, so it found a local minima that allowed it to undistort the board at the cost of dramatically warping the rest of the image. You should see something that looks like the original, but bent just a little bit so that all the lines in the board are straight.

**Comment by Elaheh-Motamedi** [comment]
Thank you for your reply.
I did calibration one more time with bigger board-the paper size is A3 . My camera is ZED 2 and it is not panoramic. I set the alpha 3 and the the undistortion images are better (the bent is less) 

![undistorted_points](https://user-images.githubusercontent.com/101594016/179293478-6495ed30-4338-4568-afba-0233ca354d06.png)

but I got the error regarding to undistorting.
![thumbnail_image_50406401](https://user-images.githubusercontent.com/101594016/179293649-27b54271-310d-4cde-83f8-39295654c9ba.jpg)

**Comment by backyardbiomech** [comment]
1. Try setting alpha to 1. That will get rid of the panoramic effect where the image repeats as it wraps, and will leave some of the black residual on the edges - i.e., you will see all of the original pixels on the edges.
2.  You set cbrow=8 and cbcol=6 (8 rows, 6 columns). i.e. you need to hold the board vertically (in "portrait" mode, not "landscape"), that probably explains the poor undistortion in your original post, and the better output in the last post.
3. That last index error means it's not finding the data files output for the videos you are passing, which is odd given that it sees that they are analyzed. Can you try running with filtering (`deeplabcut.triangulate(config,..., filterpredictions=True)`). There may be a missing `dataname.append` call in the code without filtering (below line [Line 311](https://github.com/DeepLabCut/DeepLabCut/blob/10ef6ef2a728afd134e6e32af12df06040eebc01/deeplabcut/pose_estimation_3d/triangulation.py#L311)). That's one for @jeylau to confirm.

**Comment by Elaheh-Motamedi** [comment]
I did with alpha=1 but the pictures have the panoramic effect in undistortion folder:
![left-06_undistort](https://user-images.githubusercontent.com/101594016/179312518-2d02d87d-4aac-48e9-b7f4-17b09e5215f2.jpg)




but when I set the alpha =0 ,the pictures does not have the panormaic effects;
![left-06_undistort](https://user-images.githubusercontent.com/101594016/179311867-22edfe6f-7b23-4e81-9b9f-a98953557c4a.jpg)

I consider alpha=1 and filterpredictions=True, also I got pictures in portrait again, now the results:



![IMG_2453](https://user-images.githubusercontent.com/101594016/179312390-e8488330-d9c5-4464-be5e-9eb68bb566b6.jpg)



This is my folder where my videos are 

![IMG_2455](https://user-images.githubusercontent.com/101594016/179313374-5e5ef6f1-12fa-43ca-b37e-ca6beea596fd.jpg)


In alpha =0 and alpha =1 , the error is the same.

**Comment by MMathisLab** [comment]
did you rename your cameras in the 3d config.yaml file?

**Comment by Elaheh-Motamedi** [comment]
Hello,
Yes, in my config file , the name of cameras are left and right and the video files are output-left.avi and output-right.avi. 
and the name of pictures for calibration are left-01.jpg, right-01, etc.

**Comment by MMathisLab** [comment]
>> the name of cameras are left and right 

it would need to be: 

```
camera_names:
- output-left
- output-right
```
can you confirm?

**Comment by MMathisLab** [comment]
can you paste here the video_path ? the error is suggesting it's not in [ ]

**Comment by MMathisLab** [comment]
as at the top you use linux, and now you use Windows, and there are some clear path issues going on here :)

**Comment by Elaheh-Motamedi** [comment]
I tried many times in windows and linux. For example in last photo , I used this video path:
video_path= '/Users/msiam/video3d'
deeplabcut.triangulate(config_path3d, video_path, videotype='avi', filterpredictions=True)

I did not use this format for addressing video_path: deeplabcut.triangulate(config,[['/data/project1/videos/video1-camera-1.avi','/data/project1/videos/video1-camera-2.avi'],['/data/project1/videos/video2-camera-1.avi','/data/project1/videos/video2-camera-2.avi']]) 
Should I use []?


I tried both linux and windows but I got the same error in both of them. When I used windows I modified the address  in config files , ...
Thank you for your time.

**Comment by MMathisLab** [comment]
I think I am not understanding the issue fully; in the very last image you post, you have the 3D file... output-3D.h5; that is the expected output of DLC-3D; your first issue had the path differently, so hard to track down what is happening on the other computer that isn't work. But, the data is there... is there something wrong with the .h5?

**Comment by Elaheh-Motamedi** [comment]
Yes, you are right. As the error on Linux and windows was the same and I shared here both results but on both of them I had changed the path correctly. The problem is that when I used deeplabcut.triangulate , I got the error : IndexError: list index out of range, as you see, while I got h5 too. 
My problem is with the coordination of output_DLC_3D.h5  , 
<img width="1440" alt="3dDLC" src="https://user-images.githubusercontent.com/101594016/183461923-db8859e4-9712-48be-860d-dcb67cc678ca.png">


In pixel position for body part "ch" , I have the good accuracy and the right trend, but when I get 3d xyz coordination the trend is not right, also both y and z are negative. I don't know this problem is related to the Index error that I received in deeplabcut.triangulate or related to my camera calibration.

**Comment by MMathisLab** [comment]
the coordinates are arbitrary; you can plot then edit as you like; but given you are getting the 3D, I don't see the issue // the issue is saying ti does not find more video pairs, but you seem to have only 1 pair and it runs :D

**Comment by Elaheh-Motamedi** [comment]
Thank you so much for your reply.
How can I found the origin and axis direction in 3D? I need them for translation and rotation to another origin.

**Comment by MMathisLab** [comment]
easiest way is to look at pixel values in images and map them to real-space; the 3D is arbitrary sizing.
