### ISSUE TITLE
What does "train error with pcut off" mean?

### ISSUE THREAD

**Issue by Banboo-glich** [DeepLabCut/DeepLabCut#1903]
Please forgive me for a rudimentary question. 

With DLC Dcoument I have learned that p-cutoff is "confident predictions with likelihood". 

Here, "train error with p-cutoff" means how often the training data did not reach the pcutoff. I think "test with pcut off" in the same way.

At what train(or test) error with p-cutoff value can the model be used? Please tell me the reference value.

And why doesn't DeepLabCut use mAP metrics?

Best regards!

**Comment by jeylau** [comment]
Hello @Banboo-glich, DeepLabCut reports mAP for the multi-animal scenarios.
As for train/test error with pcutoff, it is rather to be understood as train and test RMSE between GT and predictions whose confidence values are above pcutoff. I hope that helps!
