### ISSUE TITLE
Recognition of uploaded individual images from a trained model or from a model in modlezoo

### ISSUE THREAD

**Issue by lBWtt** [DeepLabCut/DeepLabCut#1909]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I cannot analyze a single image(not videos)

**Describe the solution you'd like**
I would like to add this new feature by modifying the code(But I don't know how to do it)

**Describe alternatives you've considered**
Not available at the moment

**Additional context**

Whether or not to modify this function:
def GetPoseandCostsF(
    cfg, dlc_cfg, sess, inputs, outputs, cap, nframes, batchsize, shelf_path,
):

I would be glad if you could help me!

**Comment by jeylau** [comment]
For multi-animal DLC, I had drafted code in this PR #1758; specifically, take a look at the function `_eval_single_image`. https://github.com/DeepLabCut/DeepLabCut/blob/6ffd4441c6564e2513f1ca1ab1ed6d5085024546/deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py#L532-L557
It is functional, you can pass in the path of an image, together with the pose_cfg.yaml that you find under dlc-models/...test, and you'll get the raw detections.
For single-animal projects, you can readily use `analyze_time_lapse_frames` https://github.com/DeepLabCut/DeepLabCut/blob/10ef6ef2a728afd134e6e32af12df06040eebc01/deeplabcut/pose_estimation_tensorflow/predict_videos.py#L1230
I hope that helps!

**Comment by AlexEMG** [comment]
Indeed, these options exist.

**Comment by lBWtt** [comment]
> _eval_single_image



> For multi-animal DLC, I had drafted code in this PR #1758; specifically, take a look at the function `_eval_single_image`.
> 
> https://github.com/DeepLabCut/DeepLabCut/blob/6ffd4441c6564e2513f1ca1ab1ed6d5085024546/deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py#L532-L557
> 
> 
> It is functional, you can pass in the path of an image, together with the pose_cfg.yaml that you find under dlc-models/...test, and you'll get the raw detections.
> For single-animal projects, you can readily use `analyze_time_lapse_frames`
> https://github.com/DeepLabCut/DeepLabCut/blob/10ef6ef2a728afd134e6e32af12df06040eebc01/deeplabcut/pose_estimation_tensorflow/predict_videos.py#L1230
> 
> 
> I hope that helps!

Thanks for the suggestion, I ran the def analyze_time_lapse_frames function and returned an .h5 file and pickle file. It doesn't look like it will generate images directly.

**Comment by lBWtt** [comment]
> For multi-animal DLC, I had drafted code in this PR #1758; specifically, take a look at the function `_eval_single_image`.
> 
> https://github.com/DeepLabCut/DeepLabCut/blob/6ffd4441c6564e2513f1ca1ab1ed6d5085024546/deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py#L532-L557
> 
> 
> It is functional, you can pass in the path of an image, together with the pose_cfg.yaml that you find under dlc-models/...test, and you'll get the raw detections.
> For single-animal projects, you can readily use `analyze_time_lapse_frames`
> https://github.com/DeepLabCut/DeepLabCut/blob/10ef6ef2a728afd134e6e32af12df06040eebc01/deeplabcut/pose_estimation_tensorflow/predict_videos.py#L1230
> 
> 
> I hope that helps!


* About the _eval_single_image function, this error occurs when it runs, and I don't know why.

deeplabcut\pose_estimation_tensorflow\core\predict.py", line 38, in setup_pose_prediction
    tf.float32, shape=[cfg["batch_size"], None, None, 3]
TypeError: string indices must be integers

**Comment by jeylau** [comment]
Is batch_size a float in the pose_config.yaml file? Does int(cfg['batch_size']) help?

**Comment by lBWtt** [comment]
> Is batch_size a float in the pose_config.yaml file? Does int(cfg['batch_size']) help?

I successfully ran the **analyze_time_lapse_frames** function to generate the .h5 file and the .pickle file

But what I want is to generate a predicted image (More visual)

How should I do it?  thank you!
