### ISSUE TITLE
Error when using GUI in upgrade. (ConstructorError: could not determine a constructor for the tag '!!python/tuple')

### ISSUE THREAD

**Issue by byronrogers73** [DeepLabCut/DeepLabCut#191]
Anaconda Env, Deeplab Cut 2.0.4

I had previously extracted the frames under 2.0.3 on my PC. Upgraded in the meantime to 2.0.4 and ran the code, etc. The kernel died after the error below.

%gui wx
path_config_file = 'C:\\Users\\byron\\Anaconda3\\envs\\DLC\\ThoroughbredDLC-Byron-2019-01-24\\config.yaml'
deeplabcut.label_frames(path_config_file)
---------------------------------------------------------------------------
ConstructorError                          Traceback (most recent call last)
C:\Users\byron\Anaconda3\envs\DLC\lib\site-packages\ruamel\yaml\constructor.py in construct_undefined(self, node)
   1292             yield data
-> 1293             self.construct_mapping(node, data)
   1294         except:

C:\Users\byron\Anaconda3\envs\DLC\lib\site-packages\ruamel\yaml\constructor.py in construct_mapping(self, node, maptyp, deep)
   1103                 "expected a mapping node, but found %s" % node.id,
-> 1104                 node.start_mark)
   1105         merge_map = self.flatten_mapping(node)

ConstructorError: expected a mapping node, but found sequence
  in "C:\Users\byron\Anaconda3\envs\DLC\ThoroughbredDLC-Byron-2019-01-24\config.yaml", line 12, column 15

During handling of the above exception, another exception occurred:

ConstructorError                          Traceback (most recent call last)
C:\Users\byron\Anaconda3\envs\DLC\lib\site-packages\deeplabcut\generate_training_dataset\labeling_toolbox.py in browseDir(self, event)
    368 
    369 # Reading config file and its variables
--> 370         self.cfg = auxiliaryfunctions.read_config(self.config_file)
    371         self.scorer = self.cfg['scorer']
    372         self.bodyparts = self.cfg['bodyparts']

C:\Users\byron\Anaconda3\envs\DLC\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py in read_config(configname)
     72     path = Path(configname)
     73     with open(path, 'r') as f:
---> 74         cfg = ruamelFile.load(f)
     75     return(cfg)
     76 

C:\Users\byron\Anaconda3\envs\DLC\lib\site-packages\ruamel\yaml\main.py in load(self, stream)
    229         constructor, parser = self.get_constructor_parser(stream)
    230         try:
--> 231             return constructor.get_single_data()
    232         finally:
    233             parser.dispose()

C:\Users\byron\Anaconda3\envs\DLC\lib\site-packages\ruamel\yaml\constructor.py in get_single_data(self)
     90         node = self.composer.get_single_node()
     91         if node is not None:
---> 92             return self.construct_document(node)
     93         return None
     94 

C:\Users\byron\Anaconda3\envs\DLC\lib\site-packages\ruamel\yaml\constructor.py in construct_document(self, node)
    100             self.state_generators = []
    101             for generator in state_generators:
--> 102                 for dummy in generator:
    103                     pass
    104         self.constructed_objects = {}

C:\Users\byron\Anaconda3\envs\DLC\lib\site-packages\ruamel\yaml\constructor.py in construct_undefined(self, node)
   1297                 "could not determine a constructor for the tag %r" %
   1298                 utf8(node.tag),
-> 1299                 node.start_mark)
   1300 
   1301     def construct_yaml_timestamp(self, node, values=None):

ConstructorError: could not determine a constructor for the tag '!!python/tuple'
  in "C:\Users\byron\Anaconda3\envs\DLC\ThoroughbredDLC-Byron-2019-01-24\config.yaml", line 12, column 15
------

The Python terminal had the following.

[I 21:43:02.087 NotebookApp] Saving file at /DLC.ipynb
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x0000020C02CC92F0>)
Traceback (most recent call last):
  File "C:\Users\byron\Anaconda3\envs\DLC\lib\site-packages\tornado\ioloop.py", line 758, in _run_callback
    ret = callback()
  File "C:\Users\byron\Anaconda3\envs\DLC\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\byron\Anaconda3\envs\DLC\lib\site-packages\ipykernel\kernelbase.py", line 306, in advance_eventloop
    eventloop(self)
  File "C:\Users\byron\Anaconda3\envs\DLC\lib\site-packages\ipykernel\eventloops.py", line 238, in loop_tk
    app.tk.createfilehandler(stream.getsockopt(zmq.FD), READABLE, notifier)
AttributeError: '_tkinter.tkapp' object has no attribute 'createfilehandler'
[I 21:45:02.097 NotebookApp] Saving file at /DLC.ipynb
[I 21:47:02.499 NotebookApp] Saving file at /DLC.ipynb
[I 21:49:02.463 NotebookApp] Saving file at /DLC.ipynb
[I 21:50:32.932 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel 8758a1a1-6419-40e9-b9d0-ec2899eddb2e restarted

**Comment by AlexEMG** [comment]
Sorry for that error, we will post a fix, but for now just delete "'!!python/tuple'" inside the config.yaml file. ( also see https://forum.image.sc/t/colab-constructorerror-could-not-determine-a-constructor-for-the-tag-python-tuple/22535)
