### ISSUE TITLE
Error using Google Colab to create training set

### ISSUE THREAD

**Issue by kevinle628** [DeepLabCut/DeepLabCut#1912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am trying to create a training set for DLC in Google Colab using the template provided. I keep getting an error every time I run the code and am unsure how to fix it. Some say that the template uses a depreciated version of DLC and I may need to update it but I have no idea how to do so. Any advice would be appreciated! Thank you all!

`/content/drive/My Drive/Angled_Project-Kevin-2022-06-21/training-datasets/iteration-0/UnaugmentedDataSet_Angled ProjectJun21  already exists!
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-1ea74fe54287> in <module>()
      2 #Then, run this cell. There are many more functions you can set here, including which network to use.
      3 #check the docstring for full options you can do!
----> 4 deeplabcut.create_training_dataset(path_config_file, net_type='resnet_50', Shuffles=[SHUF], augmenter_type='imgaug')

3 frames
/usr/local/lib/python3.7/dist-packages/deeplabcutcore/generate_training_dataset/trainingsetmanipulation.py in create_training_dataset(config, num_shuffles, Shuffles, windows2linux, userfeedback, trainIndexes, testIndexes, net_type, augmenter_type)
    692             # Saving data file (convert to training file for deeper cut (*.mat))
    693             ################################################################################
--> 694             data, MatlabData = format_training_data(Data, trainIndexes, nbodyparts, project_path)
    695             sio.savemat(os.path.join(project_path,datafilename), {'dataset': MatlabData})
    696 

/usr/local/lib/python3.7/dist-packages/deeplabcutcore/generate_training_dataset/trainingsetmanipulation.py in format_training_data(df, train_inds, nbodyparts, project_path)
    548         filename = df.index[i]
    549         data['image'] = filename
--> 550         img_shape = _read_image_shape_fast(os.path.join(project_path, filename))
    551         try:
    552             data['size'] = img_shape[2], img_shape[0], img_shape[1]

/usr/lib/python3.7/posixpath.py in join(a, *p)
     92                 path += sep + b
     93     except (TypeError, AttributeError, BytesWarning):
---> 94         genericpath._check_arg_types('join', a, *p)
     95         raise
     96     return path

/usr/lib/python3.7/genericpath.py in _check_arg_types(funcname, *args)
    151         else:
    152             raise TypeError('%s() argument must be str or bytes, not %r' %
--> 153                             (funcname, s.__class__.__name__)) from None
    154     if hasstr and hasbytes:
    155         raise TypeError("Can't mix strings and bytes in path components") from None

TypeError: join() argument must be str or bytes, not 'tuple'`

### Operating System

Google Colab on a Windows 7 Computer

### DeepLabCut version

2+

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
In Colab, run `!pip install -U deeplabcut` to update deeplabcut. Version 2+ isn't very helpful, but I suppose it should work after updating the package.

**Comment by kevinle628** [comment]
I upgraded to 2.2.1.1 but I still get the same error

**Comment by jeylau** [comment]
Do you also get the error when trying to create the training set on your machine?

**Comment by kevinle628** [comment]
I was able to create a training set on my CPU computer (however python crashes with training hence the switch to Google Colab).

**Comment by jeylau** [comment]
All right, good to know! Note that you could create the training dataset locally, and easily move it to Colab afterwards. Since some months now we've made data paths platform-agnostic, so there is no need for windows-to-linux conversion.

**Comment by kevinle628** [comment]
Oh so I can create the training dataset on my computer then transfer to the drive?

**Comment by kevinle628** [comment]
Okay I created and imported the training set to the google drive but when I begin training I get an error with the config key. Not sure what this is and it doesn't seem to be an issue on any DLC forums.

`Error under config key: emboss
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-030fef213175> in <module>()
      3 #more info and there are more things you can set: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/functionDetails.md#g-train-the-network
      4 
----> 5 deeplabcut.train_network(path_config_file, shuffle=SHUF, displayiters=10,saveiters=50)
      6 
      7 #this will run until you stop it (CTRL+C), or hit "STOP" icon, or when it hits the end (default, 1.03M iterations).

5 frames
/usr/local/lib/python3.7/dist-packages/deeplabcutcore/pose_estimation_tensorflow/training.py in train_network(config, shuffle, trainingsetindex, max_snapshots_to_keep, displayiters, saveiters, maxiters, allow_growth, gputouse, autotune, keepdeconvweights)
    132         train(str(poseconfigfile),displayiters,saveiters,maxiters,max_to_keep=max_snapshots_to_keep,keepdeconvweights=keepdeconvweights,allow_growth=allow_growth) #pass on path and file name for pose_cfg.yaml!
    133     except BaseException as e:
--> 134         raise e
    135     finally:
    136         os.chdir(str(start_path))

/usr/local/lib/python3.7/dist-packages/deeplabcutcore/pose_estimation_tensorflow/training.py in train_network(config, shuffle, trainingsetindex, max_snapshots_to_keep, displayiters, saveiters, maxiters, allow_growth, gputouse, autotune, keepdeconvweights)
    130             os.environ['CUDA_VISIBLE_DEVICES'] = str(gputouse)
    131     try:
--> 132         train(str(poseconfigfile),displayiters,saveiters,maxiters,max_to_keep=max_snapshots_to_keep,keepdeconvweights=keepdeconvweights,allow_growth=allow_growth) #pass on path and file name for pose_cfg.yaml!
    133     except BaseException as e:
    134         raise e

/usr/local/lib/python3.7/dist-packages/deeplabcutcore/pose_estimation_tensorflow/train.py in train(config_yaml, displayiters, saveiters, maxiters, max_to_keep, keepdeconvweights, allow_growth)
    111     setup_logging()
    112 
--> 113     cfg = load_config(config_yaml)
    114     if cfg.dataset_type=='default' or cfg.dataset_type=='tensorpack' or cfg.dataset_type=='deterministic':
    115         print("Switching batchsize to 1, as default/tensorpack/deterministic loaders do not support batches >1. Use imgaug loader.")

/usr/local/lib/python3.7/dist-packages/deeplabcutcore/pose_estimation_tensorflow/config.py in load_config(filename)
     54 
     55 def load_config(filename = "pose_cfg.yaml"):
---> 56     return cfg_from_file(filename)
     57 
     58 if __name__ == "__main__":

/usr/local/lib/python3.7/dist-packages/deeplabcutcore/pose_estimation_tensorflow/config.py in cfg_from_file(filename)
     47     yaml_cfg['snapshot_prefix']=trainpath+'snapshot'
     48     #the default is: "./snapshot"
---> 49     _merge_a_into_b(yaml_cfg, cfg)
     50 
     51     logging.info("Config:\n"+pprint.pformat(cfg))

/usr/local/lib/python3.7/dist-packages/deeplabcutcore/pose_estimation_tensorflow/config.py in _merge_a_into_b(a, b)
     30         if type(v) is edict:
     31             try:
---> 32                 _merge_a_into_b(a[k], b[k])
     33             except:
     34                 print('Error under config key: {}'.format(k))

KeyError: 'emboss'`

**Comment by jeylau** [comment]
Please use deeplabcut instead of deeplabcutcore; the package has not been touched for more than a year, as DeepLabCut now fully supports tensorflow 2.

**Comment by kevinle628** [comment]
Awesome! I was able to create a dataset in colab after switching to deeplabcut from deeplabcut core. However, I'm still having issues with training as I am getting errors that I am unsure if they stem from the poseconfig file with weights or not.

`Loading ImageNet-pretrained resnet_50
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-030fef213175> in <module>()
      3 #more info and there are more things you can set: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/functionDetails.md#g-train-the-network
      4 
----> 5 deeplabcut.train_network(path_config_file, shuffle=SHUF, displayiters=10,saveiters=50)
      6 
      7 #this will run until you stop it (CTRL+C), or hit "STOP" icon, or when it hits the end (default, 1.03M iterations).

3 frames
/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/training.py in train_network(config, shuffle, trainingsetindex, max_snapshots_to_keep, displayiters, saveiters, maxiters, allow_growth, gputouse, autotune, keepdeconvweights, modelprefix)
    216 
    217     except BaseException as e:
--> 218         raise e
    219     finally:
    220         os.chdir(str(start_path))

/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/training.py in train_network(config, shuffle, trainingsetindex, max_snapshots_to_keep, displayiters, saveiters, maxiters, allow_growth, gputouse, autotune, keepdeconvweights, modelprefix)
    212                 max_to_keep=max_snapshots_to_keep,
    213                 keepdeconvweights=keepdeconvweights,
--> 214                 allow_growth=allow_growth,
    215             )  # pass on path and file name for pose_cfg.yaml!
    216 

/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/core/train.py in train(config_yaml, displayiters, saveiters, maxiters, max_to_keep, keepdeconvweights, allow_growth)
    231 
    232     # Restore variables from disk.
--> 233     restorer.restore(sess, cfg["init_weights"])
    234     if maxiters is None:
    235         max_iter = int(cfg["multi_step"][-1][1])

/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/saver.py in restore(self, sess, save_path)
   1391     if not checkpoint_management.checkpoint_exists_internal(checkpoint_prefix):
   1392       raise ValueError("The passed save_path is not a valid checkpoint: " +
-> 1393                        checkpoint_prefix)
   1394 
   1395     logging.info("Restoring parameters from %s", checkpoint_prefix)

ValueError: The passed save_path is not a valid checkpoint: /usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt`

**Comment by jeylau** [comment]
The error indicates that the pretrained model weights were not found (the file likely didn't persist on Colab). You could verify this programmatically and re-download them with the following command:
```python
from deeplabcut.utils.auxfun_models import Downloadweights

Downloadweights('resnet_50', '/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt')
```

**Comment by kevinle628** [comment]
Hm i tried to run the download weights but it says there is an str object with no parents though I am unsure where the str is located in the code.

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-ce1fc44181d6> in <module>()
      4 
      5 from deeplabcut.utils.auxfun_models import Downloadweights
----> 6 Downloadweights('resnet_50', '/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt')
      7 
      8 deeplabcut.train_network(path_config_file, shuffle=SHUF, displayiters=10,saveiters=50)

/usr/local/lib/python3.7/dist-packages/deeplabcut/utils/auxfun_models.py in Downloadweights(modeltype, model_path)
     64     from io import BytesIO
     65 
---> 66     target_dir = model_path.parents[0]
     67     neturls = auxiliaryfunctions.read_plainconfig(
     68         target_dir / "pretrained_model_urls.yaml"

AttributeError: 'str' object has no attribute 'parents'`

**Comment by jeylau** [comment]
Aw I'm sorry, my mistake... Instead of a string, the path should be:
```python
from pathlib import Path

path = Path('/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt')
Downloadweights('resnet_50', path)
```

**Comment by kevinle628** [comment]
Awesome it worked perfectly!
