### ISSUE TITLE
Network evaluation bug -- ValueError

### ISSUE THREAD

**Issue by sunqy31** [DeepLabCut/DeepLabCut#1916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi, 

I had trained my multianimal network successfully, but when I evaluate it on GUI, it showed ：“ ValueError : Shape of passed value is (40, 10), indices imply (40, 15)".  I started to learn Deeplabcut a few days ago. I had trained a single-animal model without this bug. So I wonder whether it was due to the multianimal mode.  

By the way, there is another bothering question. Could I continue to work with the network, if training process was accidentally killed? Actually, I had trained a previous model but it stopped at iteration 75000 out of unknown reason. I tried to reload the project and go evaluation, but got the same "ValueError" bug. I thought that was caused by the training interruption, so I copied the files and did trained again. This time training completed, but the error was still there.   

I'm fledgling in deeplabcut and I used mostly default settings. 

Many thanks！

### Operating System

Windows 10

### DeepLabCut version

deeplabcut 2.2.1.1 GUI

### DeepLabCut mode

multi animal

### Device type

GPU NVIDIA Quadro P1000

### Steps To Reproduce

1. launch DeepLabCut GUI
2. everything samed ok till training completed 
3. run: evaluate network
4. boom!

### Relevant log output

```shell
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\evaluate_network.py:270, in Evaluate_network.evaluate_network(self, event)
    268 if len(self.bodyparts) == 0:
    269     self.bodyparts = "all"
--> 270 deeplabcut.evaluate_network(
    271     self.config,
    272     Shuffles=Shuffles,
    273     #trainingsetindex=trainingsetindex,
    274     plotting=plotting,
    275     show_errors=True,
    276     comparisonbodyparts=self.bodyparts,
    277 )

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\evaluate.py:601, in evaluate_network(config, Shuffles, trainingsetindex, plotting, show_errors, comparisonbodyparts, gputouse, rescale, modelprefix)
    598     from .evaluate_multianimal import evaluate_multianimal_full
    600     # TODO: Make this code not so redundant!
--> 601     evaluate_multianimal_full(
    602         config=config,
    603         Shuffles=Shuffles,
    604         trainingsetindex=trainingsetindex,
    605         plotting=plotting,
    606         comparisonbodyparts=comparisonbodyparts,
    607         gputouse=gputouse,
    608         modelprefix=modelprefix,
    609     )
    610 else:
    611     from deeplabcut.utils.auxfun_videos import imread, imresize

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\evaluate_multianimal.py:448, in evaluate_multianimal_full(config, Shuffles, trainingsetindex, plotting, show_errors, comparisonbodyparts, gputouse, modelprefix)
    445 sess.close()  # closes the current tf session
    447 # Compute all distance statistics
--> 448 df_dist = pd.DataFrame(dist, columns=df.index)
    449 df_conf = pd.DataFrame(conf, columns=df.index)
    450 df_joint = pd.concat(
    451     [df_dist, df_conf],
    452     keys=["rmse", "conf"],
    453     names=["metrics"],
    454     axis=1,
    455 )

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\frame.py:694, in DataFrame.__init__(self, data, index, columns, dtype, copy)
    684         mgr = dict_to_mgr(
    685             # error: Item "ndarray" of "Union[ndarray, Series, Index]" has no
    686             # attribute "name"
   (...)
    691             typ=manager,
    692         )
    693     else:
--> 694         mgr = ndarray_to_mgr(
    695             data,
    696             index,
    697             columns,
    698             dtype=dtype,
    699             copy=copy,
    700             typ=manager,
    701         )
    703 # For data is list-like, or Iterable (will consume into list)
    704 elif is_list_like(data):

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\internals\construction.py:351, in ndarray_to_mgr(values, index, columns, dtype, copy, typ)
    346 # _prep_ndarray ensures that values.ndim == 2 at this point
    347 index, columns = _get_axes(
    348     values.shape[0], values.shape[1], index=index, columns=columns
    349 )
--> 351 _check_values_indices_shape_match(values, index, columns)
    353 if typ == "array":
    355     if issubclass(values.dtype.type, str):

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\internals\construction.py:422, in _check_values_indices_shape_match(values, index, columns)
    420 passed = values.shape
    421 implied = (len(index), len(columns))
--> 422 raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")

ValueError: Shape of passed values is (40, 10), indices imply (40, 15)
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @sunqy31, how many animals and body parts are defined in the config.yaml? The issue looks similar to #1451: have you changed the number of individuals defined in the config, after labeling?
As for your 2nd question, there should be no problem continuing to use your latest snapshot (even if training got interrupted): DeepLabCut will always pick this one by default. Note that you could also resume training from that point on by editing the variable `init_weights` in the dlc-models/.../train/pose_cfg.yaml and specifying the location of the latest snapshot. I hope this helps.

**Comment by sunqy31** [comment]
Thanks! I just went through that previous issue, very similar indeed (and maybe much simpler).
The default setting of number of individuals is 3, but I only have 2. So I deleted the line "individual 3" in config.yaml before labelling. I checked my "CpllectedData.csv" file and found that columns of individual 3 still remains there. I believe this is the cause (and have nothing to do with training interruption. haha). So, can I just erase those extra columns then go to evaluation?

**Comment by MMathisLab** [comment]
Hi @sunqy31 awe, so if there are three, then unfortuantely that is what it was trained with too, in the Collecteddata.h5 file. If you put back ind 3 into config, this might be fine... it would still only compute metrics for animals shown...

**Comment by anacastropsico** [comment]
> Oi@sunqy31, quantos animais e partes do corpo são definidos no config.yaml? O problema é semelhante ao [nº 1451](https://github.com/DeepLabCut/DeepLabCut/issues/1451) : você alterou o número de indivíduos definido na configuração após a rotulagem? Quanto à sua 2ª pergunta, não deve haver problema em continuar usando seu instantâneo mais recente (mesmo se o treinamento for interrompido): o DeepLabCut sempre escolherá este por padrão. Observe que você também pode retomar o treinamento a partir desse ponto editando a variável `init_weights`em dlc-models/.../train/pose_cfg.yaml e especificando o local do instantâneo mais recente. Eu espero que isso ajude.
___________
@jeylau 
I'm trying to start from a specific short. with the init_weights command line, but it always completely restarts. I'm using Colab google.

init_weights: /content/drive/My Drive/Teste_DLC/new_projet/dlc-models/iteration-0/new_projetOct24-trainset95shuffle1/train/snapshot-220000

my file pose:

all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
all_joints_names:
- fucinho
- orelha1
- orelha2
- pescoco
- tronco1
- tronco2
- centro
- tronco3
- tronco4
- calda
- Ob1
- Ob2
alpha_r: 0.02
apply_prob: 0.5
batch_size: 1
contrast:
  clahe: true
  claheratio: 0.1
  histeq: true
  histeqratio: 0.1
convolution:
  edge: false
  emboss:
    alpha:
    - 0.0
    - 1.0
    strength:
    - 0.5
    - 1.5
  embossratio: 0.1
  sharpen: false
  sharpenratio: 0.3
cropratio: 0.4
dataset: training-datasets/iteration-0/UnaugmentedDataSet_APNov2/AP_AP95shuffle1.mat
dataset_type: imgaug
decay_steps: 30000
display_iters: 1000
global_scale: 0.8
init_weights: /content/drive/My Drive/Teste_DLC/AP/dlc-models/iteration-0/APNov2-trainset95shuffle1/train/snapshot-220000
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
metadataset: training-datasets/iteration-0/UnaugmentedDataSet_APNov2/Documentation_data-AP_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: resnet_50
num_joints: 12
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
project_path: /content/drive/My Drive/Teste_DLC/AP
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
