### ISSUE TITLE
Data augmentation with new frames from unseen videos

### ISSUE THREAD

**Issue by WernTanj** [DeepLabCut/DeepLabCut#192]
We would like to improve network performance by adding new frames from unseen videos. Do you think the following steps are the way to go?

1) 'deeplabcut.add_new_videos()' 
2) 'deeplabcut.extract_frames()' : change the config.yaml such that only new added videos are used for frame extraction i.e. comment out already seen videos.
3) 'deeplabcut.label_frames()'
4) train with best snapshot

**Comment by MMathisLab** [comment]
No, I would run analyze videos, then extract outlier frames, then merge datasets and create a new training set. The bioarxiv user-guide explains these steps for active refinement in full. Please check those out. 

https://camo.githubusercontent.com/f949958888e3aea07c9fb0b1ae793e9b38ac198b/68747470733a2f2f737461746963312e73717561726573706163652e636f6d2f7374617469632f3537663664353163396637343536366635356563663237312f742f3563336534373435346661353161343230666138656364662f313534373538353336373233342f666c6f776669672e706e673f666f726d61743d37353077

**Comment by WernTanj** [comment]
We analyzed the new videos already and the prediction is very bad - in almost every frame some labels get assigned to the background (which has different lighting and camera angle... I was surprised that the network did not generalize). Do you
Still recommend using the ‘extract_outlier frames()’ over adding new labeled frames?

Sent from my iPhone

On 31 Jan 2019, at 15:44, Mathis Lab <notifications@github.com<mailto:notifications@github.com>> wrote:


No, I would run analyze videos, then extract outlier frames, then merge datasets and create a new training set. The bioarxiv user-guide explains these steps for active refinement in full. Please check those out.

**Comment by AlexEMG** [comment]
_Still recommend using the ‘extract_outlier frames()’ over adding new labeled frames?_

Either way is fine, whatever is more convenient for you to label...
