### ISSUE TITLE
DeepLabCut GUI won't show output

### ISSUE THREAD

**Issue by Sofi306** [DeepLabCut/DeepLabCut#1923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I'm using DLC GUI to track human movement. 

I encountered 2 issues:
1. Output can't be displayed. An error that has to do with a mismatch between C/C++ and Windows locale shows up (see Relevant log output).
2. There is a warning regarding using GPU.

I'd be happy to get some assistance in the matter.
Thanks!

### Operating System

Windows

### DeepLabCut version

version 2.2.1.1

### DeepLabCut mode

single animal

### Device type

GPU

### Steps To Reproduce

1. Create a project using GUI.
2. Extract frames - default.
3. Label Data -> Label Frames -> worked as expected.
4. Label Data ->Check Labels! -> shows locale error.
5. Anytime an output is requested the locale error shows again. For example in Evaluate->Optional: Plot 3 test maps, or Create videos->Bluid skeleton.

### Relevant log output

```shell
return wx.Bitmap(str(cbook._get_data_path('images', filename)))
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(LC_ALL, NULL), "C") == 0" failed at ..\..\src\common\intl.cpp(1579) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!
```

### Anything else?

There is an error when starting the GUI regarding the GPU use:

2022-07-26 19:49:59.225377: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-07-26 19:49:59.233256: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by backyardbiomech** [comment]
Duplicate of #1436.

**Comment by sofiakup** [comment]
I tried to install it inside the DLC environment:

`pip install -U wxPython==4.0.7.post2`

as suggested in the following comment:
https://github.com/DeepLabCut/DeepLabCut/issues/682#issuecomment-627307639

but I keep getting this error:

`    return wx.Bitmap(str(cbook._get_data_path('images', filename)))
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(LC_ALL, NULL), "C") == 0" failed at ..\..\src\common\intl.cpp(1579) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!`

**Comment by sofiakup** [comment]
Please note that I'm using Anaconda and Windows.
The output when I install `pip install -U wxPython==4.0.7.post2:`

`pip install -U wxPython==4.0.7.post2
Requirement already satisfied: wxPython==4.0.7.post2 in c:\users\sofi\anaconda3\envs\deeplabcut\lib\site-packages (4.0.7.post2)
Requirement already satisfied: numpy in c:\users\sofi\anaconda3\envs\deeplabcut\lib\site-packages (from wxPython==4.0.7.post2) (1.22.4)
Requirement already satisfied: six in c:\users\sofi\anaconda3\envs\deeplabcut\lib\site-packages (from wxPython==4.0.7.post2) (1.16.0)
Requirement already satisfied: pillow in c:\users\sofi\anaconda3\envs\deeplabcut\lib\site-packages (from wxPython==4.0.7.post2) (9.2.0)
(DEEPLABCUT) PS C:\BioMech Code>`

Is there anything else I can do to solve this?

**Comment by sofiakup** [comment]
In addition, note that in https://github.com/DeepLabCut/DeepLabCut/issues/1436#issuecomment-886667869 the user decided to reset his PC to factory settings and reinstall as a 'completely english' computer.

My PC is in English and I can't reset it at the moment.

**Comment by MMathisLab** [comment]
please now try running `pip install --upgrade --force-reinstall 'deeplabcut[gui]'==2.3rc1` in your env and/or docker
