### ISSUE TITLE
Labeled data and config file exapmle

### ISSUE THREAD

**Issue by Michael-Amar-95** [DeepLabCut/DeepLabCut#1926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi everyone, I started to use DLC with the google colab tool (DeepLabCut 2+ Toolbox | Colab for TensorFlow 2+)  in the last days and I see that I have alot of problems durring this experience. 
First, I am notice that there is no example for the correct way to create the directory in the colab. I am not sure witch directory I nedd to create and what they need to contain. 
for now, this is what I made:
* I have a folder named videos that contain all the videos I want to train
* Config file - I am not sure if it correct

I saw that I need to label the video but I dont understand in what form it should be (I need to label the frames?).

![image](https://user-images.githubusercontent.com/87607021/182480373-efe60257-048b-4b4a-9914-72afc8ece210.png)

### Operating System

 operating system - Google colab

### DeepLabCut version

dlc version - https://github.com/DeepLabCut/DeepLabCut-core.git@tf2.2alpha

### DeepLabCut mode

multi animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hello! You do not need to create configuration files or folders yourself: they are automatically created by deeplabcut upon calling `deeplabcut.create_new_project(...)`. Note also that you won't be able to use our labeling GUI in Colab, so I'd encourage you to start locally on your machine (following this [guide](https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html) or this [one](https://www.nature.com/articles/s41596-019-0176-0)). When you get to the model training stage, you can then copy your project folder to your Google Drive and use Colab then. Last thing, deeplabcut-core is no longer supported, and you should simply be using deeplabcut, it has now been compatible with tensorflow 2 for quite some time ☺️
