### ISSUE TITLE
How can I examine the effectiveness of our trained model?

### ISSUE THREAD

**Issue by NTUMEDREX** [DeepLabCut/DeepLabCut#1929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I’ve trained my model for six times, and I add 2 videos, labeled 20 frames each.
I have added 12 videos in total, and I expect the test error may decrease to some extent however it increases instead.
I think the reason is that the more video I loaded the more different the photo may be so the test error may increase.
So I am wondering how can I prove that I am training a better model through adding more videos and training more times?

### Operating System

Linux

### DeepLabCut version

2.2.1.1

### DeepLabCut mode

multi animal

### Device type

Geforce 3070

### Steps To Reproduce

I’ve trained my model for six times, and I add 2 videos, labeled 20 frames each.
I have added 12 videos in total, and I expect the 'test error' may decrease  however it increases instead.
I think the reason is that the more video I loaded the more different the photo may be so the test error may increase.
So I am wondering how can I prove that I am training a better model through adding more videos and training more times?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
I responded on Image Forum: https://forum.image.sc/t/how-can-i-examine-the-effectiveness-of-our-trained-model/70272/3

Please don't double post Questions :) the forum is best.
