### ISSUE TITLE
TypeError: SplitterWindow.SplitVertically(): argument 'sashPosition' has unexpected type 'float'

### ISSUE THREAD

**Issue by ghost** [DeepLabCut/DeepLabCut#1930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I get this error when I run `label_frames()` and when I try to label frames from the GUI app.

I solved (?) it by deleting `* 0.8` and `* 0.83` from

https://github.com/DeepLabCut/DeepLabCut/blob/f162ec5110075bc66063dcb8feb33fb0348d7a02/deeplabcut/gui/labeling_toolbox.py#L273-L280

but given that `wx.SplitterWindow.SplitVertically()`  (and `SplitHorizontally()` too) only accepts `sashPosition` as `int`, ([link](https://docs.wxpython.org/wx.SplitterWindow.html#wx.SplitterWindow.SplitVertically)) why would such an obvious error happen?

### Operating System

Debian GNU/Linux bookworm/sid x86_64 5.18.0-3-amd64

### DeepLabCut version

2.2.1.1

### DeepLabCut mode

single animal

### Device type

NVIDIA GeForce RTX 3060 Mobile / Max-Q

### Steps To Reproduce

1.
```
git clone https://github.com/DeepLabCut/DeepLabCut.git
cd DeepLabCut
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
pip install .["gui"]
```
2.
```
python3
>>> import deeplabcut as dlc
# Create project, extract frames etc.
>>> dlc.label_frames(config)
```
3. Get error.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/user/caf/venv/lib/python3.10/site-packages/deeplabcut/gui/label_frames.py", line 232, in label_frames
    label_frames(self.config)
  File "/home/user/caf/venv/lib/python3.10/site-packages/deeplabcut/gui/label_frames.py", line 101, in label_frames
    labeling_toolbox.show(config, config3d, sourceCam, imtypes, jump_unlabeled)
  File "/home/user/caf/venv/lib/python3.10/site-packages/deeplabcut/gui/labeling_toolbox.py", line 970, in show
    frame = MainFrame(None, config, imtypes, config3d, sourceCam, jump_unlabeled).Show()
  File "/home/user/caf/venv/lib/python3.10/site-packages/deeplabcut/gui/labeling_toolbox.py", line 273, in __init__
    vSplitter.SplitVertically(
TypeError: SplitterWindow.SplitVertically(): argument 'sashPosition' has unexpected type 'float'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
@cagriozkurt, what you did is correct. Either remove the `* 0.8` (as `self.gui_size` is already a tuple of int), or cast the size to int, e.g.: `int(self.gui_size[0] * 0.8)

**Comment by rojasgabriel** [comment]
is this fix already implemented in main? i was encountering it myself just now when running the refine outliers function

**Comment by jeylau** [comment]
@rojasgabriel, yes! The GUI has been rebuilt with another framework, so this error is gone 🙂

**Comment by rojasgabriel** [comment]
oh i see, i was just running an old version. thank you!
