### ISSUE TITLE
Google Colab No Longer Supports TensorFlow 1.x

### ISSUE THREAD

**Issue by drweatherill** [DeepLabCut/DeepLabCut#1931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Running the following line of code within the second code box within the DLC Jupyter Notebook on Google Colab:

%tensorflow_version 1.x

...throws the following error:

---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

[<ipython-input-8-419240ad4a53>](https://localhost:8080/#) in <module>()
      1 # Use TensorFlow 1.x:
----> 2 get_ipython().magic('tensorflow_version 1.x')

2 frames

[/usr/local/lib/python3.7/dist-packages/google/colab/_tensorflow_magics.py](https://localhost:8080/#) in _tensorflow_version(line)
     39 
     40              Your notebook should be updated to use Tensorflow 2.
---> 41              See the guide at https://www.tensorflow.org/guide/migrate#migrate-from-tensorflow-1x-to-tensorflow-2."""
     42                        ))
     43 

ValueError: Tensorflow 1 is unsupported in Colab.

Your notebook should be updated to use Tensorflow 2.
See the guide at https://www.tensorflow.org/guide/migrate#migrate-from-tensorflow-1x-to-tensorflow-2.

### Operating System

macOS Monterey v12.5

### DeepLabCut version

DLC version 2.2.1.1

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

1. Navigate to https://colab.research.google.com/github/DeepLabCut/DeepLabCut/blob/master/examples/COLAB/COLAB_YOURDATA_TrainNetwork_VideoAnalysis.ipynb#scrollTo=o4orkg9QTHKK
2. First, go to "Runtime" ->"change runtime type"->select "Python3", and then select "GPU"
3. Run the first line of code: !pip install deeplabcut
4. (Be sure to click "RESTART RUNTIME" is it is displayed above above before moving on !)
5. Run the second line of code: %tensorflow_version 1.x
6. View the error report in the output

### Relevant log output

```shell
---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-1-419240ad4a53> in <module>()
      1 # Use TensorFlow 1.x:
----> 2 get_ipython().magic('tensorflow_version 1.x')

2 frames

/usr/local/lib/python3.7/dist-packages/google/colab/_tensorflow_magics.py in _tensorflow_version(line)
     39 
     40              Your notebook should be updated to use Tensorflow 2.
---> 41              See the guide at https://www.tensorflow.org/guide/migrate#migrate-from-tensorflow-1x-to-tensorflow-2."""
     42                        ))
     43 

ValueError: Tensorflow 1 is unsupported in Colab.

Your notebook should be updated to use Tensorflow 2.
See the guide at https://www.tensorflow.org/guide/migrate#migrate-from-tensorflow-1x-to-tensorflow-2.
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by drweatherill** [comment]
Update:
Using !pip install tensorflow==1.15.2 instead of %tensorflow_version 1.x seems to be a good temporary work around. However, Google Colab now seems to run substantially slower.

**Comment by jeylau** [comment]
You can also drop this line from the notebook and let it use tensorflow 2, which is fully supported by DeepLabCut ☺️

**Comment by drweatherill** [comment]
Thanks jeylau,

I skipped this line of code as per your suggestion, and it is humming along at its normal speed now.
