### ISSUE TITLE
train from scratch

### ISSUE THREAD

**Issue by yangyuke001** [DeepLabCut/DeepLabCut#1932]
Hi everyone,

Thank you for your awesome work!

I am wondering if there is possible to train from scratch using the defult networks, such as resnet50.

And how to set it ？

Best Regards！

**Comment by MMathisLab** [comment]
yes, please see the extensive docs here, which guides you through how to train a model: https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html

**Comment by yangyuke001** [comment]
@MMathisLab Sorry, my previous expression was not very accurate. I would like to say whether I can train directly from scratch without using the ImageNet pre-training model.

**Comment by mshooter** [comment]
Hi @yangyuke001, 
were you able to do this?

**Comment by yangyuke001** [comment]
@mshooter noops
