### ISSUE TITLE
Issues installing GUI on Mac - fresh install

### ISSUE THREAD

**Issue by tremblay-s** [DeepLabCut/DeepLabCut#1940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

How to install the latest DLC (08/2022) on a Mac such that the GUI works fine, the pyhtonw path is correct, and you don't get the "This program needs access to the screen" error. 

1-Install Anaconda 3
2-Create a Conda environement using Python 3.8 (3.9 not supported yet by DLC)
conda create --name DLC  python=3.8 
conda activate DLC
3- Confirm right version is installed
python --version    
4-Install Deeplabcut with gui within the environment.
pip install 'deeplabcut[gui]'  
5-The path to pythonw is wrong, so the GUI won't start. Correct using:
conda install python.app  (within your conda DLC environment, may need sudo rights)
6-Confirm it is seeing pythonw from within the environment path (not within usr/bin)
which pythonw  
7-Run the GUI using pythonw
pythonw -m deeplabcut

The GUI should open.

You're welcome ;)

### Operating System

operating system: macOS Big Sur
iMac 2017 27in

### DeepLabCut version

dlc version: 2.2.1.1

### DeepLabCut mode

single animal

### Device type

CPU : iMac 2017

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@tremblay-s we suggest using the DEEPLABCUT_M1 cona env, then it all works :) 

see: https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html#deeplabcut-m1-chip-installation-environment-instructions

(and DLC is supported on python 3.7 through 3.10)

and for completeness: https://github.com/DeepLabCut/DeepLabCut/search?q=conda+install+python.app&type=issues

**Comment by tremblay-s** [comment]
Thanks,

My iMac 2017 doesn't have a M1 chip. Do you recommend mac users without M1 chips to also install the M1 version of the environment ?

(and the non-M1 DLC install failed with Python 3.9, but worked with 3.8)
