### ISSUE TITLE
v2.2.1.1: 3D scorer name is written incorrectly into the resulting 3D.h5 file

### ISSUE THREAD

**Issue by MMathisLab** [DeepLabCut/DeepLabCut#1941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Historically, the H5 file that results after running `deeplabcut.triangulation` would write the 3D scorer name in the file. This is the correct behavior. 

Currently, it puts a 2D scorer name into the H5, which is suboptimal -- this does not tell us about the 3d project info, and how would one decide which scorer to pull anyhow? One can have different DLC models for each camera, or use the same, etc. 

Here is an example: top is correct (dlc VERSION 2.0.7) and bottom (version 2.2.1.1):
![image (4)](https://user-images.githubusercontent.com/28102185/184148966-c3f0d06b-4b7f-48b3-9b90-5107cfa69bd9.png)

### Operating System

OS indepent (but ubuntu)

### DeepLabCut version

dlc version 2.0.7 vs 2.2.1.1

### DeepLabCut mode

3d

### Device type

N/A

### Steps To Reproduce

Run `deeplabcut.triangulation` in version 2.0.7 and version 2.2.1.1

### Anything else?

issues around here likely...

https://github.com/DeepLabCut/DeepLabCut/blob/8ddb7abde7ee065289149cd24b6cdd33b3605f07/deeplabcut/pose_estimation_3d/triangulation.py#L233

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by stes** [comment]
#1943 contains a proposal related to this for easier debugging of the triangulation.py methods.

**Comment by MMathisLab** [comment]
fixed with the latest PRs, or more is needed?

**Comment by stes** [comment]
No this is not fixed with the PR.
