### ISSUE TITLE
couldn't integrate the GPU to my training (windows 11)

### ISSUE THREAD

**Issue by onny112** [DeepLabCut/DeepLabCut#1947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello,
I am having Error code 193 while running the training
I tried to reinstall everything and install alone the file and it didn't work
when ever I try diffrent version he ask for a file that only exist on windows 10 not 11

### Operating System

windows 11

### DeepLabCut version

dlc version  2.2.1.1

### DeepLabCut mode

single animal

### Device type

gtx 1060

### Relevant log output

```shell
Starting training....
2022-08-13 12:58:33.458304: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8500
Could not load library cudnn_cnn_infer64_8.dll. Error code 193
```

### Anything else?

it's my second time using neural network and I learn a lot from your work, thank you in advance

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by josemgmz** [comment]
Same problem on a RTX 3080, in Windows 10

**Comment by jeylau** [comment]
What versions of cudnn and cudatoolkit are printed out when you run `conda list`?

**Comment by MMathisLab** [comment]
Hello, did you check the docs here? https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html?highlight=windows%20gpu#how-to-confirm-that-your-gpu-is-being-used-by-deeplabcut
