### ISSUE TITLE
Requirement for labeled mouse data.

### ISSUE THREAD

**Issue by tiger990111** [DeepLabCut/DeepLabCut#1948]
Dear, I want to take a fast test on my mouse videos for pose estimation, without pre work on labeling data and train network from scretch. Would you please release your whole labeled mouse datas or your pretrained network? I will appreciate it for your help!

**Comment by MMathisLab** [comment]
The data is all released here: https://zenodo.org/record/4008504#.YvjPYexBxqs and many more here: https://benchmark.deeplabcut.org/datasets.html
