### ISSUE TITLE
DeepCutLab on cells

### ISSUE THREAD

**Issue by Ciro1990** [DeepLabCut/DeepLabCut#1950]
Hello there,

first of all thanks for such an amazing (and opensource) work! I was wondering if this tracking tool also works on cells and if somebody actually tested it on them already.

Thanks a lot!
Ciro

**Comment by jeylau** [comment]
It does; they used DeepLabCut for cancer cell detection in [this paper](https://www.science.org/doi/pdf/10.1126/sciadv.abe3348). You could also approach it as a "multi-individual" DeepLabCut project, if you're interested in cell tracking and computation of displacement and other related kinematic metrics.

**Comment by Ciro1990** [comment]
Hi and thanks for the answer. I am actually interested in cell tracking especially because other tracking methods unfortunately give a high rate of error. May I ask what do you mean by "multi-individual" DeepLabCut project? Thanks!

**Comment by jeylau** [comment]
I meant to approach the tracking of multiple cells as one would track multiple individuals with DeepLabCut; i.e., create a multi-animal project, defining n number of cells in the configuration file, and following the flow described [here](https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html).
