### ISSUE TITLE
Request for pretrained model of mouse

### ISSUE THREAD

**Issue by tiger990111** [DeepLabCut/DeepLabCut#1955]
Dear,
  Thanks for your great Job! I am now doing the research of the behavior of mouse. Could you please release the pose estimation modal of mouse which is already trained on your whole dataset? It will be very helpful to me.

**Comment by AlexEMG** [comment]
Thanks for your interest, you can find pertained models on the model zoo: http://www.mackenziemathislab.org/dlc-modelzoo
