### ISSUE TITLE
Very high loss when resuming training from snapshot, or training new iteration from snapshot

### ISSUE THREAD

**Issue by ShovelJockey** [DeepLabCut/DeepLabCut#1957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

While generally I find DLC to work very well, sometimes when restarting training from a snapshot or training a new iteration from a snapshot I get an erroneously high learning loss (over 1000 in some cases). These snapshots had evaluated well, and during previous training had normal plateaued rates of loss hence being chosen as the point to train the next iteration from.

I had considered that this could be a problem with correctly displaying information rather than a reflection of the true learning loss value but the model snapshots created during the training with very high loss evaluate very poorly, sometimes not producing any predictions above the pcutoff of 0.6.

Restarting training can fix this problem but sometimes not, continuing to produce quite different but always much to high learning loss. In this case I have chosen the 2nd best performing snapshot and trained from that point without issue.

This issue does not seem to have prevented the training of well performing models generally and I have had no errors during my use of DLC otherwise.

### Operating System

win 10 x64

### DeepLabCut version

dlc version 2.2.1.1

### DeepLabCut mode

single animal

### Device type

colab gpu/3080

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
this is actually expected/observed behavior, but the loss drops rapidly down - sorry for the slow reply!
