### ISSUE TITLE
unsupported pickle protocol error in COLAB_maDLC_TrainNetwork_VideoAnalysis.ipynb

### ISSUE THREAD

**Issue by hakuupi** [DeepLabCut/DeepLabCut#1959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

The multi animal colab notebook fails to run on the training step. It returns a ValueError: unsupported pickle protocol: 5. 

### Operating System

macOS Catalina 10.15.2 

### DeepLabCut version

dlc version 2.2.1.1

### DeepLabCut mode

multi animal

### Device type

gpu, google colab

### Steps To Reproduce

Run COLAB_maDLC_TrainNetwork_VideoAnalysis.ipynb

### Relevant log output

```shell
>>deeplabcut.train_network(path_config_file, shuffle=shuffle, displayiters=100,saveiters=500, maxiters=5000, allow_growth=True)

[/usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/datasets/pose_multianimal_imgaug.py](https://localhost:8080/#) in load_dataset(self)
     52         with open(os.path.join(self.cfg["project_path"], file_name), "rb") as f:
     53             # Pickle the 'data' dictionary using the highest protocol available.
---> 54             pickledata = pickle.load(f)
     55 
     56         self.raw_data = pickledata

ValueError: unsupported pickle protocol: 5
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
indeed a lot of changes happening on colab this week we can't control, but thanks for pointing it out! 

here is the solution: https://github.com/DeepLabCut/DLCutils/issues/19
