### ISSUE TITLE
ERROR: Failed building wheel for wxpython while Installing DeepLabCut GUI

### ISSUE THREAD

**Issue by rishavgoel95** [DeepLabCut/DeepLabCut#1975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am trying to install DeepLabCut GUI but facing this error each time "ERROR: Failed building wheel for wxpython"

The attached pdf contains the codes of errors from python
[Issues.pdf](https://github.com/DeepLabCut/DeepLabCut/files/9465479/Issues.pdf)

### Operating System

Windows 10

### DeepLabCut version

 DLC 2.2.2

### DeepLabCut mode

single animal

### Device type

CPU - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz 1.38 GHz
GPU - Intel Iris Xe Graphics

### Anything else?

I am going in circles trying to fix the error

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
I would use our conda file, vs installing deeplabcut into your (base) env. please see here: https://deeplabcut.github.io/DeepLabCut/docs/installation.html#conda-the-installation-process-is-as-easy-as-this-figure
