### ISSUE TITLE
Check wrong files for existing pretrained models for mobilenet and efficientnet networks

### ISSUE THREAD

**Issue by thperret** [DeepLabCut/DeepLabCut#1976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When `deeplabcut.utils.auxfun_models.check_for_weights` function is called (e.g. from `create_training_dataset`) with efficientnet or mobilenet model types, the check for existing model is done against a files that is not provided by upstream pretrained model which results in the model being re-downloaded every time.
The easy fix is to check against `*.ckpt.meta` or `*.ckpt.index` files defined in `deeplabcut.utils.auxfun_models.MODELTYPE_FILEPATH_MAP` for efficientnet and mobilenet networks.

### Operating System

Debian 11

### DeepLabCut version

2.2.2

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

with standard installation, run:
```python
$ from pathlib import Path
$ import deeplabcut
$ from deeplabcut.utils import auxfun_models
$ for model in auxfun_models.MODELTYPE_FILEPATH_MAP:
...    auxfun_models.check_for_weights(
...        model, Path(deeplabcut.utils.auxiliaryfunctions.get_deeplabcut_path()), 1
...    )
$ # this will download all available pretrained models
$ # rerun the previous command and it will re-download all mobilenet and efficientnet models whereas they already are available

### Relevant log output

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Good catch @thperret, thanks! I'll fix it.
