### ISSUE TITLE
KeyError: 'No object named h5_store in the file'

### ISSUE THREAD

**Issue by Stakwhy** [DeepLabCut/DeepLabCut#1978]
Question:
I read the HDF file appear wrong

Seek help:
How to solve the error of success is to use df. Resample data sorting?

code:
import pandas as pd
import os

pd.set_option('expand_frame_repr', False)  # 当列太多时显示完整

# =====将数据存入hdf文件
# 批量读取文件名称
file_list = []
# 存储csv文件的文件夹路径
file_location = r'C:\Users\Administrator\Desktop\python\coin_quant_class_2022\data\class6\BITFINEX\EOSUSD'

for root, dirs, files in os.walk(file_location):
    for filename in files:
        if filename.endswith('.csv'):
            file_path = os.path.join(root, filename)
            file_path = os.path.abspath(file_path)
            file_list.append([filename, file_path])

# 创建hdf文件
h5_store = pd.HDFStore(
    r'C:\Users\Administrator\Desktop\python\coin_quant_class_2022\data\class6\BITFINEX\eos_1min_data_来源HSD保存数据.h5',
    mode='w',
    key='h5_store'
)

# 批量导入并且存储数据
for filename, file_path in sorted(file_list):
    # BITFINEX_EOSUSD_20170701_1T.csv
    date = filename.split('_')[2]
    print(date, filename, file_path)
    df = pd.read_csv(file_path, encoding='gbk', skiprows=1, parse_dates=['candle_begin_time'])

    # 存储数据到hdf
    h5_store['eos_' + date] = df.iloc[:100]

# 关闭hdf文件
h5_store.close()

# =====读取hdf数据
# 创建hdf文件
h5_store = pd.HDFStore(
    r'C:\Users\Administrator\Desktop\python\coin_quant_class_2022\data\class6\BITFINEX\eos_1min_data_来源HSD保存数据.h5',
    mode='r',
    key='h5_store'
)

**The following generation output when there is a problem**
# === 从hdf中读取1分钟数据
hdf_hdf_path = r'C:\Users\Administrator\Desktop\python\coin_quant_class_2022\data\class6\BITFINEX\eos_1min_data_来源HSD保存数据.h5'

df = pd.read_hdf(hdf_hdf_path, key='h5_store', mode='r')

# === 1min k线数据转换为5min k线数据
rule_type = '5T'
period_df = df.resample(rule=rule_type, on='candle_begin_time', base=0, label='left', closed='left').agg(
    {
        'open': 'first',
        'high': 'max',
        'low': 'min',
        'close': 'last',
        'volume': 'sum',
    }
)

output：

KeyError: 'No object named h5_store in the file'

**Comment by jeylau** [comment]
Hey @Stakwhy, I don't really understand what you're trying to do, but in DeepLabCut, h5 data files can simply be opened as follows:
```python
import pandas

df = pd.read_hdf('path_to_h5_file')
```
There is no need to specify a particular store key, as there is only one and this will be the one read by default.
