### ISSUE TITLE
Labels on labeled video placed from cropped coordinates

### ISSUE THREAD

**Issue by jonpedros** [DeepLabCut/DeepLabCut#1979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello everyone,

I'm having an issue with the create_labeled_video function. Currently, I've been analyzing novel videos by setting cropping coordinates for each file separately. I do this because I labeled frames cropped around the eye and now pupil border detection performance is perfect this way (but quite finicky when using the whole frame or even with dynamic cropping).

However, when creating the labeled videos, the labels are placed according to the cropped frames label coordinates, as you can see here. 

![vlcsnap-2022-09-10-09h38m51s478](https://user-images.githubusercontent.com/85462635/189463319-f14d4c76-2f11-4daf-8ce3-5da3a275c47d.png)

Here is a frame from a labeled video created with `displaycropped=True`

![vlcsnap-2022-09-10-09h38m55s898](https://user-images.githubusercontent.com/85462635/189463340-63bc031a-895a-4327-ab13-9afd7a389e9d.png)

The issue doesn't happen with no cropping or dynamic cropping.

I found [this](https://forum.image.sc/t/madlc-video-analysis-with-cropping-wrong-labeling/43671) discussion on image.sc, in which the user solved the exact same problem by using `cropping=False` on the config.yaml file. I checked this boolean is false for my file, so that shouldn't be an issue. 

Lastly, I noticed that, when using `save_frames=True`, the created frame_temp folder has all the files with the correct label placing, although I haven't been able to check the finished video for this mode because the file is not written (but with no error output) and only a few frames remain in the temporary folder.

### Operating System

Windows 10 (Native)

### DeepLabCut version

DLC 2.2.2

### DeepLabCut mode

single animal

### Device type

NVIDIA GeForce RTX 2600 SUPER

### Steps To Reproduce

1 - Use network trained from cropped frames
2 - Analyze novel video with cropping parameters
3 - Create labeled video

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Since individual frames are stored temporarily, I assume you've passed `save_frames=True`; does the problem remain if it's left to `False` (so that the fast video creation mode is used)?

**Comment by jonpedros** [comment]
I actually hadn't gone to the end yet with `save_frames=True` video creation. I tried now, but although video creation takes reasonable time, the generated video is blank, and the temp_frames folder has only two frames (but they show the label at the right spot).  This also happens with `fast_mode=True` . I'll post the terminal outputs I get when doing video analysis and when creating labeled videos.

When analyzing:

```
deeplabcut.pose_estimation_tensorflow.predict_videos.analyze_videos('C:\\Users\\systemses\\Downloads\\pupillome
   ...: try\\dlc-project\\pupillometry-Joao-2022-09-08\\config.yaml', ^M
   ...: ['C:\\Users\\systemses\\Downloads\\pupillometry\\dlc-project\\analyzed-videos\\M2-6-video-2022-09-07_11-10-24.a
   ...: vi'],   ^M
   ...: gputouse=0, ^M
   ...: save_as_csv=True, ^M
   ...: destfolder='C:\\Users\\systemses\\Downloads\\pupillometry\\dlc-project',  ^M
   ...: cropping=[186, 257, 126, 183],  ^M
   ...: robust_nframes=True, ^M
   ...: allow_growth=False, ^M
   ...: use_shelve=False)
Overwriting cropping parameters: [186, 257, 126, 183]
These are used for all videos, but won't be save to the cfg file.
Using snapshot-500000 for model C:\Users\systemses\Downloads\pupillometry\dlc-project\pupillometry-Joao-2022-09-08\dlc-models\iteration-0\pupillometrySep8-trainset95shuffle1
C:\Users\systemses\anaconda3\envs\deeplabcut\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
2022-09-12 16:45:01.646925: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-12 16:45:02.413894: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 6007 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2060 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5
2022-09-12 16:45:02.447742: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
Starting to analyze %  C:\Users\systemses\Downloads\pupillometry\dlc-project\analyzed-videos\M2-6-video-2022-09-07_11-10-24.avi
Loading  C:\Users\systemses\Downloads\pupillometry\dlc-project\analyzed-videos\M2-6-video-2022-09-07_11-10-24.avi
Duration of video [s]:  1246.43 , recorded with  30.0 fps!
Overall # of frames:  37393  found with (before cropping) frame dimensions:  480 348
Starting to extract posture
Cropping based on the x1 = 186 x2 = 257 y1 = 126 y2 = 183. You can adjust the cropping coordinates in the config.yaml file.
  0%|                                                                                        | 0/37393 [00:00<?, ?it/s]2022-09-12 16:45:04.749850: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8100
2022-09-12 16:45:05.881263: E tensorflow/core/platform/windows/subprocess.cc:287] Call to CreateProcess failed. Error code: 2, command: '"ptxas.exe" "--version"'
2022-09-12 16:45:05.882222: E tensorflow/core/platform/windows/subprocess.cc:287] Call to CreateProcess failed. Error code: 2, command: '"ptxas.exe" "--version"'
2022-09-12 16:45:05.882835: W tensorflow/stream_executor/gpu/asm_compiler.cc:80] Couldn't get ptxas version string: INTERNAL: Couldn't invoke ptxas.exe --version
2022-09-12 16:45:05.885997: E tensorflow/core/platform/windows/subprocess.cc:287] Call to CreateProcess failed. Error code: 2, command: '"ptxas.exe" "C:\Users\SYSTEM~1\AppData\Local\Temp\/tempfile-DESKTOP-8ETBCR1-4b90-3532-5e87612fc9c9e" "-o" "C:\Users\SYSTEM~1\AppData\Local\Temp\/tempfile-DESKTOP-8ETBCR1-4b90-3532-5e87612fca443" "-arch=sm_75" "--warn-on-spills"'
2022-09-12 16:45:05.886438: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] INTERNAL: Failed to launch ptxas
Relying on driver to perform ptx compilation.
Modify $PATH to customize ptxas location.
This message will be only logged once.
100%|██████████████████████████████████████████████████████████████████████████▊| 37300/37393 [01:35<00:00, 389.70it/s]
Saving results in C:\Users\systemses\Downloads\pupillometry\dlc-project...
Saving csv poses!
The videos are analyzed. Now your research can truly start!
 You can create labeled videos with 'create_labeled_video'
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
Out[4]: 'DLC_resnet50_pupillometrySep8shuffle1_500000'
```
When creating labeled videos:

```
In [7]: deeplabcut.utils.make_labeled_video.create_labeled_video('C:\\Users\\systemses\\Downloads\\pupillometry\\dlc-pr
   ...: oject\\pupillometry-Joao-2022-09-08\\config.yaml', ^M
   ...: ['C:\\Users\\systemses\\Downloads\\pupillometry\\dlc-project\\analyzed-videos\\M2-6-video-2022-09-07_11-10-24.a
   ...: vi'], ^M
   ...: filtered=True, ^M
   ...: fastmode=False, ^M
   ...: save_frames=True, ^M
   ...: displayedbodyparts='all',^M
   ...: displaycropped=False, ^M
   ...: codec='mp4v', ^M
   ...: draw_skeleton=False,^M
   ...: Frames2plot=[0,800],^M
   ...: color_by='bodypart')
Loading DLC 2.2.2...
Starting to process video: C:\Users\systemses\Downloads\pupillometry\dlc-project\analyzed-videos\M2-6-video-2022-09-07_11-10-24.avi
Loading C:\Users\systemses\Downloads\pupillometry\dlc-project\analyzed-videos\M2-6-video-2022-09-07_11-10-24.avi and data.
Duration of video [s]: 1246.43, recorded with 30.0 fps!
Overall # of frames: 37393 with cropped frame dimensions: 480 348
Generating frames and creating video.
100%|██████████████████████████████████████████████████████████████████████████| 37393/37393 [00:07<00:00, 4885.15it/s]
Labeled video C:\Users\systemses\Downloads\pupillometry\dlc-project\analyzed-videos\M2-6-video-2022-09-07_11-10-24DLC_resnet50_pupillometrySep8shuffle1_500000_filtered_labeled.mp4 successfully created.
```

**Comment by jonpedros** [comment]
An update about this:
I tried to create the video with `save_frames=True` and without specifying frames with `Frames2plot`.
The video actually has the labels on the right place. So, in short:

- bug does not happen with `save_frames=True`
- `save_frames=True` video creation does not work when `Frames2plot` is specified (and with no error output).

**Comment by jeylau** [comment]
Thanks for letting us know @jonpedros! I couldn't replicate what you described with `Frames2plot` though. I'll close the issue since you got the labeled video working, but feel free to reopen it if you need some more help.
