### ISSUE TITLE
Dynamic crop inference for videos 

### ISSUE THREAD

**Issue by peterperch** [DeepLabCut/DeepLabCut#198]
Win10, Anconda Env, DeepLabCut 2.0.4.1, CPU

Feature request: speed improvement when analyzing videos with CPU (and GPU)

Solution1: 
Select FPS when analyzing video (e.g. recorded with 120 FPS, but only 60 FPS needed)

cap = cv2.VideoCapture()
cap.set(cv2.cv.CV_CAP_PROP_FPS, 60)

Solution2: 
Create roi around animal when analyzing video (detection of points in first frame) and looking for matches within the roi instead of entire cropped frame. The roi in next frame is expected to be near the last detected points.
(E.g. mouse in one half of the arena cannot jump to the other half within one frame; therefore the video has to be analyzed only in a fraction of the frame.

Cheers ;)

**Comment by AlexEMG** [comment]
That's useful for some cases (and e.g. indeed what I do for the trail-tracking data). However, many users have full-frame data, so it only covers a subset of use cases. Anyway we planned to include such a function at some point called e.g. ```deeplabcut.analyze_new_videos_dynamiccrop(...)```

Feel free to write it.

**Comment by peterperch** [comment]
Thanks’ for the fast reply! I will look into it.
Otherwise the program works really good!

**Comment by AlexEMG** [comment]
I'll reopen this for now, if someone wants to contribute....

**Comment by MMathisLab** [comment]
Will be in the next release (2.1)

**Comment by AlexEMG** [comment]
Here is how you use it:

```deeplabcut.analyze_videos(path_config_file,[video],save_as_csv=True, dynamic=(True,.1,30))```

Thereby, the triple denotes (state,detectiontreshold,margin). If the state is true, then dynamic cropping will be performed. That means that if an object is detected (i.e. any body part > detectiontreshold), then object boundaries are computed according to the smallest/largest x position and smallest/largest y position of all body parts. This  window is expanded by the margin and from then on only the posture within this crop is analyzed (until the object is lost, i.e. <detectiontreshold). The current position is utilized for updating the crop window, for the next frame (this is why the margin is important and should be set large enough given the movement of the animal).

Even **on CPU the gains are large**. I.e. on the test video for the openfield given that the mouse is small in relation to the frame, the inference speed goes from ~1.5FPS to around 15FPS on a desktop.... 

See deeplabcut/pose_estimation_tensorflow/predict_videos.py#L35

**Comment by PolarBean** [comment]
is there anyway to use this mode with GPU?

**Comment by MMathisLab** [comment]
@PolarBean yes, it uses the gpu by default if you have it set up to use a gpu normally.

**Comment by PolarBean** [comment]
when i run dynamic cropping it returns: "Starting analysis in dynamic cropping mode with parameters: (True, 0.1, 30)
Switching batchsize to 1, num_outputs (per animal) to 1 and TFGPUinference to False (all these features are not supported in this mode)."

**Comment by MMathisLab** [comment]
Yep, doesn’t mean it’s not using the gpu, just the TFGPu isn’t used. 

if you check the docstring each variable is explained. `Deeplabcut.analyze_videos?`

You can also see you gpu being used by checking `nvida-smi` in another terminal. And the FPS will be a big clue. You can check out papers for several test across platforms and GPUs.

**Comment by PolarBean** [comment]
ah i understand now, thank you

**Comment by PolarBean** [comment]
do you think it would be possible to introduce larger batchsizes for dynamic cropping, if you think this is worthwhile Id be happy to try and implement. I understand the limitation is that each dynamically cropped image has a different resolution and therefore batchwise analysis doesnt make sense however if you were to force all cropped images to be the size of the largest image in the batch then i don't see why not. 

all the best from Australia :)

**Comment by MMathisLab** [comment]
> however if you were to force all cropped images to be the size of the largest image in the batch then i don't see why not.

The issue will be that would end up being just the size of the frame, as the way it works now is if a key point is not found in the cropped area first, then it runs inference over the whole frame to double check for the key point (i.e. the "standard" way). 

So, it would require some thought about how you'd want to implement the batch size, but I think it's a reasonable idea, thanks!

**Comment by PolarBean** [comment]
Interesting points, I suppose possible to save the idx of frames where a key point is not found and analyse those frames last but I will think about this more. 
Thank you :)
