### ISSUE TITLE
wxpython gui interface not working on Ubuntu 

### ISSUE THREAD

**Issue by SmoothOperator00EC** [DeepLabCut/DeepLabCut#1980]
**Is your feature request related to a problem? Please describe.**
Currently the DLC GUI in Ubuntu 22.00 doesn't work for me .I had proble with wxPython toolkit and I tried to build a wheel specific for my Ubuntu version but still doens't work and from what i see , i'm not the only one.
**Describe the solution you'd like**
it'd be great if you change the software you use to create the gui for DeepLabCut. If you are already working on it , which software you'll  use and when you will release DLC with the updated GUI sw  ?

**Comment by MMathisLab** [comment]
the new gui is here: https://github.com/DeepLabCut/napari-deeplabcut. 

this will be the deafult in DLC within the month. happy for contributions.
