### ISSUE TITLE
NumPy 1.23 dropped `numpy.asscalar`

### ISSUE THREAD

**Issue by mfansler** [DeepLabCut/DeepLabCut#1981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Conda environment created with `numpy>=1.23` will fail with exception:

```python
AttributeError: module 'numpy' has no attribute 'asscalar'
```

Reported in [this StackOverflow question](https://stackoverflow.com/q/73679514/570918).

### Operating System

Not my system, but StackOverflow report shows Windows. However, this is platform-agnostic issue.

### DeepLabCut version

2.2.2

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

1. Follow Install instructions.
2. Check that `numpy >= 1.23` is installed.
3. Run example (`python testscript.py`)

### Anything else?

NumPy has had `numpy.asscalar()` deprecated since v1.16 and finally removed in v1.23 (see [Release Notes](https://numpy.org/doc/stable/release/1.23.0-notes.html?highlight=asscalar#expired-deprecations)).

Quick fix is to set upper bound in YAML environment definitions (`numpy <1.23`). Better would be to follow [NumPy guidance](https://numpy.org/doc/1.22/reference/generated/numpy.asscalar.html) and replace `numpy.asscalar()` calls with `numpy.ndarray.item()`.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Thanks @mfansler for reporting the issue! It will be fixed with #1982 ☺️

**Comment by mfansler** [comment]
@jeylau Thanks for such a prompt update! 🤩
