### ISSUE TITLE
Issue with installation: Python 3.8 + wxPython

### ISSUE THREAD

**Issue by hyr2** [DeepLabCut/DeepLabCut#1985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Her e is the error on the terminal popping up for wxpython installation compatibility:

![image](https://user-images.githubusercontent.com/51006894/189760530-e46b9444-f35a-4b4b-8654-1ec1814aaa1a.png)

### Operating System

operating system: Linux x64 Fedora 36

### DeepLabCut version

dlc version: 2.35

### DeepLabCut mode

single animal

### Device type

gpu: AMD R9 280
CPU: Intel i7 11th gen

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@hyr2 yes, 3.8 will no longer, work, but there is a new GUI :) #1984 which does not rely on wxPython. Please check it out and report any issues you have: https://github.com/DeepLabCut/DeepLabCut/pull/1984

**Comment by MMathisLab** [comment]
please now try running `pip install --upgrade --force-reinstall 'deeplabcut[gui]'==2.3rc1` in your env and/or docker. I will close, but please do post back!
