### ISSUE TITLE
question about video selection and config(multianimalproject )

### ISSUE THREAD

**Issue by lBWtt** [DeepLabCut/DeepLabCut#1987]
hello I have some questions 

1 Do I still need to select "multianimalproject"   if there are multiple animals in the video but I only label one which is the most obvious
?

2 When do you need to select “multianimalproject”

3 Can a video be multiple different animals cut together? 
    Or is it that a video can only one animal one shot to the end(So that I have to load a new video for individual diversity)

**Comment by MMathisLab** [comment]
hi @lBWtt we ask user questions be placed on Image Forum and leave github to code issues; but please see docs where all your questions are answered; specifically using the GUI will be easiest as it's very clear when to select these steps. https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html
