### ISSUE TITLE
Unsupported marker

### ISSUE THREAD

**Issue by sherryxinyuean** [DeepLabCut/DeepLabCut#1988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Terminal log shows unsupported marker when running **analyze_videos**. While the output analysis was still successfully produced, I am wondering if those warnings should be taken care of. Thank you!

### Operating System

Windows 10

### DeepLabCut version

dlc version 2.2.2

### DeepLabCut mode

single animal

### Device type

CPU

### Steps To Reproduce

In DEEPLABCUT environment, ipython, I ran the command like this:

> dlc.analyze_videos('Z:\...\...\config.yaml',['Z:\......\video1.mj2','Z:\......\video1.mj2'],save_as_csv=True)

Note that my video is in .mj2 video type.

### Relevant log output

```shell
Overall # of frames:  42061  found with (before cropping) frame dimensions:  1756 788
Starting to extract posture
 83%|███████████████████████████████████████████████████████████▋            | 34860/42061 [6:56:41<1:25:52,  1.40it/s][jpeg2000 @ 0000017cfeb61840] unsupported marker 0x6A70 at pos 0x4
[jpeg2000 @ 0000017cfeb61840] unsupported marker 0x842A at pos 0x3269
[jpeg2000 @ 0000017cfeb61840] unsupported marker 0xD607 at pos 0x6C18
[jpeg2000 @ 0000017cfeb61840] unsupported marker 0x6BAD at pos 0x14196
[jpeg2000 @ 0000017cfeb61840] unsupported marker 0x53B2 at pos 0x1F3F7
[jpeg2000 @ 0000017cfeb61840] unsupported marker 0x1E96 at pos 0x20F53
[jpeg2000 @ 0000017cfeb61840] unsupported marker 0xAF15 at pos 0x25CB7
[jpeg2000 @ 0000017cfeb61840] unsupported marker 0xF037 at pos 0x2CB06
[jpeg2000 @ 0000017cfeb61840] unsupported marker 0xB24F at pos 0x32EFC
[jpeg2000 @ 0000017cfeb61840] unsupported marker 0xCE01 at pos 0x3674B
[jpeg2000 @ 0000017cfeb61840] unsupported marker 0x6083 at pos 0x41E54
[jpeg2000 @ 0000017cfeb61840] unsupported marker 0x84B3 at pos 0x51C9F
[jpeg2000 @ 0000017cfeb61840] unsupported marker 0x4AD9 at pos 0x52603
[jpeg2000 @ 0000017cfeb61840] unsupported marker 0x65B7 at pos 0x58575
[jpeg2000 @ 0000017cfeb61840] unsupported marker 0xE821 at pos 0x58A89
[jpeg2000 @ 0000017cfeb61840] unsupported marker 0x0961 at pos 0x5CD83
[jpeg2000 @ 0000017cfeb61840] unsupported marker 0xD000 at pos 0x624C8
100%|█████████████████████████████████████████████████████████████████████████▉| 42000/42061 [8:22:56<00:43,  1.39it/s]
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by sherryxinyuean** [comment]
To add on this, I have not seen similar output when I analyze the same videos in .avi, so I am concerned.

**Comment by jeylau** [comment]
Hi @sherr-an, I found only very limited info online about this warning, but it looks like some frames could not be decoded properly. After video analysis, you could use `deeplabcut.create_video_with_all_detections` and verify that no frames are missing. Another thing to try is to convert your videos to `.avi`. I wouldn't worry very much about it if only few frames give you that output. Note that you could ask on the [forum](https://forum.image.sc/tag/deeplabcut): it's preferable for that type of questions, and you may find a user experienced with this video format ☺️
