### ISSUE TITLE
Track plants with variable keypoints

### ISSUE THREAD

**Issue by LjIA26** [DeepLabCut/DeepLabCut#1989]
**Is your feature request related to a problem? Please describe.**
I was wondering if the method was suitable for plants with long leaves, since they have unknown number of keypoints. 

**Describe the solution you'd like**
Variable number of keypoints.

**Comment by jeylau** [comment]
The number of keypoints in an image may vary, but I suppose you could define in the config.yaml file the largest set of keypoints that is relevant to your analysis. Then when labeling images, only mark keypoints that are visible and you can reliably identify.

**Comment by LjIA26** [comment]
Thank you for your answer. The skeleton itself would change if the plants had more leaves.  I have a rough upper bound of what it would be but I also want to track how they curve.

**Comment by MMathisLab** [comment]
^ @LjIA26 the skeleton is just used for visualization (or if using maDLC for training individual poses - but I would suggest you use normal single animal DLC for this); so that could be computed based on the plants leaves later on.
