### ISSUE TITLE
libstdc++.so.6: version `GLIBCXX_3.4.29' not found

### ISSUE THREAD

**Issue by dengweiyang** [DeepLabCut/DeepLabCut#1990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I was trying to install deeplabcut on the Linux system but always run into this error. 

ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/usr/anaconda3/envs/DLC-GPU/lib/python3.7/site-packages/scipy/spatial/ckdtree.cpython-37m-x86_64-linux-gnu.so)

I tried upgrading and downgrading different modules but could not solve this issue or bring up other issues cause the modules' not supported. I tried everything people suggested online about similar issue but still could not fix this. Anyone has any insight on this problem? Thank you so much.

### Operating System

operating system: Linux

### DeepLabCut version

dlc version: lastest

### DeepLabCut mode

single animal

### Device type

gpu: NVIDIA-SMI 440.33.01 

### Steps To Reproduce

ipython
import deeplabcut

ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/usr/anaconda3/envs/DLC-GPU/lib/python3.7/site-packages/scipy/spatial/ckdtree.cpython-37m-x86_64-linux-gnu.so)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@dengweiyang can you give more details; which build of linux? Can you try upgrading scipy, since that seems the root of the issue? `envs/DLC-GPU/lib/python3.7/site-packages/scipy/` to do so, in the env run `pip install --upgrade scipy`

**Comment by dengweiyang** [comment]
> 

I tried that before and it gave the same error message.
The linux build is LXPanel 0.9.3, Desktop panel for LXDE project

**Comment by MMathisLab** [comment]
Hi @dengweiyang we only support ubuntu, so hard for us to debug; if you can update OS, or use docker, that is recommended: https://deeplabcut.github.io/DeepLabCut/docs/docker.html?highlight=docker
