### ISSUE TITLE
Analyse videos not working on Go Pro video

### ISSUE THREAD

**Issue by Emily961** [DeepLabCut/DeepLabCut#1996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When I try to analyse a new video and it comes from my GoPro 9 (copied from the camera into the correct folder) the programme goes through the analyse step and then displays "no filtered file found" and no plots etc. This does not happen with other videos from my android phone in the exact same folders. I have tried adding them to the project and that works so its not that they can't be found, I have even used footage from it in labelling, so I am not sure why it doesn't work for analysis? The videos are not long (29 seconds- 23.98 fps) as I am just testing it at the moment, they are .mp4 files, and I am using the GUI as I am new to computer coding

### Operating System

Windows 10 Pro, 32GB RAM, 8GPU

### DeepLabCut version

dlc version 2.2.1.1

### DeepLabCut mode

single animal

### Device type

gpu

### Relevant log output

```shell
Duration of video [s]:  29.45 , recorded with  23.98 fps!
Overall # of frames:  706  found with (before cropping) frame dimensions:  1080 1920
Starting to extract posture
 99%|███████████████████████████████████████████████████████████████████████████████▎| 700/706 [06:59<00:03,  1.67it/s]
The videos are analyzed. Now your research can truly start!
 You can create labeled videos with 'create_labeled_video'
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
Filtering with median model C:\Users\emily\Desktop\Deeplab\Horse_blinking-Emily-2022-08-06\videos\GX010040.MP4
No unfiltered data file found in C:\Users\emily\Desktop\Deeplab\Horse_blinking-Emily-2022-08-06\videos for video GX010040 and scorer DLC_resnet50_Horse_blinkingAug6shuffle1_240000.
Loading  C:\Users\emily\Desktop\Deeplab\Horse_blinking-Emily-2022-08-06\videos\GX010040.MP4 and data.
No filtered data file found in C:\Users\emily\Desktop\Deeplab\Horse_blinking-Emily-2022-08-06\videos for video GX010040 and scorer DLC_resnet50_Horse_blinkingAug6shuffle1_240000.
Traceback (most recent call last):
  File "C:\Users\emily\anaconda3\envs\dlc_dml3\lib\site-packages\deeplabcut\utils\plotting.py", line 288, in plot_trajectories
    videofolder, vname, DLCscorer, filtered, track_method
  File "C:\Users\emily\anaconda3\envs\dlc_dml3\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 769, in load_analyzed_data
    folder, videoname, scorer, filtered, track_method
  File "C:\Users\emily\anaconda3\envs\dlc_dml3\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 754, in find_analyzed_data
    raise FileNotFoundError(msg)
FileNotFoundError: No filtered data file found in C:\Users\emily\Desktop\Deeplab\Horse_blinking-Emily-2022-08-06\videos for video GX010040 and scorer DLC_resnet50_Horse_blinkingAug6shuffle1_240000.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\emily\anaconda3\envs\dlc_dml3\lib\site-packages\deeplabcut\gui\analyze_videos.py", line 570, in analyze_videos
    showfigures=showfig,
  File "C:\Users\emily\anaconda3\envs\dlc_dml3\lib\site-packages\deeplabcut\utils\plotting.py", line 322, in plot_trajectories
    video, DLCscorer, track_method
  File "C:\Users\emily\anaconda3\envs\dlc_dml3\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 785, in load_detection_data
    raise ValueError(f"Unrecognized track_method={track_method}")
ValueError: Unrecognized track_method=
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @Emily961, I realized I could replicate this issue on some 'recent' GoPro videos only (not older ones). I haven't found an explanation so far, but I'll keep looking at it!

**Comment by Emily961** [comment]
> Hi @Emily961, I realized I could replicate this issue on some 'recent' GoPro videos only (not older ones). I haven't found an explanation so far, but I'll keep looking at it!

Thank you! I need to collect my data with a GoPro so that would be great! I'm not sure if its the recording type as Windows media player doesn't recognise the files either, have to use VLC
