### ISSUE TITLE
extract_outlier_frames does not read individual names from config file

### ISSUE THREAD

**Issue by felixhol** [DeepLabCut/DeepLabCut#1997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When running extract outlier frames to create machine labelled data (to be manually refined) for the next training iterations, it seems that the individual names in the machinelabels-iter0.h5 (and corresponding csv) do not correspond to the individual names defined in the config.yaml file. Instead, the individuals are named (default) ind1 through indN.  Unfortunately the individuals in my original labelled set of iteration 0 are called m1 ... mN. After refining the labels this results in a CollectedData file with additional individual names. 

When creating the training set this leads to the creation of additional individual names, and hence too many individuals when evaluating the network causing evaluate_network to crash. 

Renaming the individuals in the data that was added in iteration1 using: `df.rename(level=1, columns={"ind1": "m1", "ind2": "m2", "ind3": "m3", "ind4": "m4", "ind5": "m5"})` for all added videos solves this issue.

Perhaps the machinelabels could be genrated using the individual names from the config. 

### Operating System

operating system: Ubuntu 20.04

### DeepLabCut version

dlc version: 2.2.2

### DeepLabCut mode

multi animal

### Device type

gpu Titan RTX

### Anything else?

Thanks :)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
I remember this as an old issue; could you check version again, just to be sure?

**Comment by felixhol** [comment]
I'm on 2.2.2 or is this something that may have changed after the latest release?

**Comment by MMathisLab** [comment]
@jeylau can you look into it tomorrow more? Maybe the fix was rolled back :) thanks @felixhol for the report! will update soon

**Comment by jeylau** [comment]
Hello @felixhol, this should no longer be the case with more recent versions of DLC, as the animal names from the config.yaml are used when writing the h5 file after stitching https://github.com/DeepLabCut/DeepLabCut/blob/834523524d6c44a8c8418a93dcc2a15a8ed6bfce/deeplabcut/refine_training_dataset/stitch.py#L1208.
Only when analyzing videos with a # of animals different from what is defined in the config file do we default to naming them ind1, ind2, etc.
I'll close the issue but feel free to reopen it if you still encounter the bug.
