### ISSUE TITLE
modules need __init__.py files

### ISSUE THREAD

**Issue by sneakers-the-rat** [DeepLabCut/DeepLabCut#2]
Howdy -  the imports within the package (eg. from myconfig import ... ) fail because there are no `__init__.py` files in any of the directories. Simple fix, I'll PR if you don't get to it first <3

**Comment by MMathisLab** [comment]
Not sure I understand the issue actually, works fine for us (and others) without it! :) 
perhaps you can also try from myconfig import *

**Comment by sneakers-the-rat** [comment]
just rounding out testing the model -- this issue is pretty extensive: all within-package imports are path dependent (ie. cwd and relative paths are appended to sys.path at the top of every file) instead of being organized as modules. many imports are also misspecified - eg. in Step1 of the evaluation functions attempts to `from config import load_config`, but it should be `from pose.config import load_config` after renaming pose-tensorflow to pose and adding `__init__.py`. that's another issue in a few places: pose-tensorflow also appears to have been renamed from pose at some point, and since hyphens are not allowed in module imports, nothing is able to use anything within pose-tensorflow except by using the working directory.

**Comment by AlexEMG** [comment]
Dear @sneakers-the-rat , you are right. Making it modular is quite extensive. For simplicity we had avoided that. However, this is something to think about! Thanks for your commitment, looking forward to your PR!
