### ISSUE TITLE
KeyError: 'cropping'

### ISSUE THREAD

**Issue by Charlottewiltshire97** [DeepLabCut/DeepLabCut#2001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi DLC!
I am trying to analyze my videos but I am getting an error: "KeyError: 'cropping'", this is regardless of the video I try to analyze and regardless of if I mark "create video for checking detections" as yes or no. How can I fix this? What have I done wrong! 

Thank you in advance for your help. 

Best wishes, 
Charlotte + the Wild Minds Lab  

### Operating System

Windows 

### DeepLabCut version

dlc version 2.2.2 (latest)

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

1. run DLC environment and open GUI
2. Load config file 
3. analyze videos tab
4. select 1 video, specify video type, and to make CSV of results
5. click 'Analyze Videos'
6. KeyError: 'cropping' regardless of what video I try to analyze 

### Relevant log output

```shell
DLC network loading and video analysis starting ...
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~\Anaconda3\envs\'DEEPLABCUT6'\lib\site-packages\deeplabcut\gui\analyze_videos.py:487, in Analyze_videos.analyze_videos(self, event)
    484     else:
    485         _filter = True
--> 487 if self.cfg["cropping"] == "True":
    488     crop = self.cfg["x1"], self.cfg["x2"], self.cfg["y1"], self.cfg["y2"]
    489 else:

File ~\Anaconda3\envs\'DEEPLABCUT6'\lib\site-packages\ruamel\yaml\comments.py:927, in CommentedMap.__getitem__(self, key)
    924 def __getitem__(self, key):
    925     # type: (Any) -> Any
    926     try:
--> 927         return ordereddict.__getitem__(self, key)
    928     except KeyError:
    929         for merged in getattr(self, merge_attrib, []):

KeyError: 'cropping'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Hey @Charlottewiltshire97 no worries, here to help -- can you tell me what is under cropping in the config.yaml file for you?

**Comment by AlexEMG** [comment]
The key doesn't seem to exist, we should just load default load False @jeylau

**Comment by jeylau** [comment]
@Charlottewiltshire97, add `cropping: false` in the config.yaml and it will work.

**Comment by MMathisLab** [comment]
yes, the config.yaml should have at the very bottom, by default `cropping: false`

**Comment by Charlottewiltshire97** [comment]
Thank you so much!
