### ISSUE TITLE
resnet-101 not found

### ISSUE THREAD

**Issue by sebo361** [DeepLabCut/DeepLabCut#201]
Ubuntu 16.04 DLC= 2.0.4.1 with virtualenv python3

Hi guys! After using the pretrained MPII model I wanted to use the ImageNet pretrained resnet 101 again. After downloading them via `download.sh` and declaring 101 in `config.yaml` I got following error when running `deeplabcut.create_new_dataset(config)`:

```
In [20]: deeplabcut.create_training_dataset(config)
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-20-ade4483e7b7f> in <module>()
----> 1 deeplabcut.create_training_dataset(config)

/home/sebo/DLC/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py in create_training_dataset(config, num_shuffles, Shuffles, windows2linux)
   1012         """
   1013         start = os.getcwd()
-> 1014         os.chdir(str(Path(resnet_path).parents[0]))
   1015         print("Downloading the pretrained model (ResNets)....")
   1016         subprocess.call("download.sh", shell=True)

FileNotFoundError: [Errno 2] No such file or directory: '/home/sebo/DLC/lib/python3.6/site-packages/deeplabcut/Pose_Estimation_Tensorflow/models/pretrained'
```

I checked `trainingsetmanipulation.py` and `Pose_Estimation_Tensorflow` needs to be written in lowercase letters in line [1004](https://github.com/AlexEMG/DeepLabCut/blob/0197cf53abadedb2a2a37496bc2486fe723ccc23/deeplabcut/generate_training_dataset/trainingsetmanipulation.py#L1004). After reinstalling deeplabcut, it found and loaded resnet-101 :)

**Comment by AlexEMG** [comment]
Oh, thanks! Yes that should be fixed, updated the code & will be released in next version!

**Comment by MMathisLab** [comment]
I guess we know everyone is using ResNet-50 now ;)

**Comment by sebo361** [comment]
Hahaa true!
