### ISSUE TITLE
missing file in DLC 2.3rc1

### ISSUE THREAD

**Issue by WeissShahaf** [DeepLabCut/DeepLabCut#2013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

error about missing file. it is indeed not there.

### Operating System

operating system: WIN 10

### DeepLabCut version

dlc version: 2.3rc1

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

pip3 install --upgrade --force-reinstall "deeplabcut[gui]"==2.3rc1 --user  #(some modules would not install without the --user)

(DEEPLABCUT) C:\WINDOWS\system32>python -m deeplabcut
Loading DLC 2.3rc1...
Starting GUI...
Traceback (most recent call last):
  File "C:\Users\superuser\.conda\envs\DEEPLABCUT\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\superuser\.conda\envs\DEEPLABCUT\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\superuser\AppData\Roaming\Python\Python38\site-packages\deeplabcut\__main__.py", line 22, in <module>
    launch_dlc()
  File "C:\Users\superuser\AppData\Roaming\Python\Python38\site-packages\deeplabcut\gui\launch_script.py", line 35, in launch_dlc
    with open(stylefile, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\superuser\\AppData\\Roaming\\Python\\Python38\\site-packages\\deeplabcut\\gui\\style.qss'

### Anything else?

errors during install, overcome by manually installing dependencies:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pytest 7.1.3 requires pluggy<2.0,>=0.12, which is not installed.

pip install pluggy<2.0
pip install pytest==7.1.3

uninstalling and reinstalling DLC also didnt help

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by oliriley** [comment]
I am encountering the same issue. I tried getting around it by running `pip install --upgrade --force-reinstall "deeplabcut[gui]"==2.3rc1` within brand-new Anaconda environments created via Navigator for Python 3.8.13, 3.9.13, and 3.10.6 but to no avail.

**Comment by kthcwd** [comment]
I am getting this error too after the issue has been closed...

**Comment by jeylau** [comment]
@kthcwd, how did you install DeepLabCut?

**Comment by kthcwd** [comment]
Hi @jeylau - I installed using the conda route, so downloaded the yawl file and followed the instructions (conda env create -f DEEPLABCUT.yaml). Then followed the interactive gui page (https://deeplabcut.github.io/DeepLabCut/docs/PROJECT_GUI.html) and ran this code: pip install --upgrade --force-reinstall 'deeplabcut[gui]'==2.3rc1 - which didn't fully work but then worked when I added in --user (pip install --user --upgrade --force-reinstall 'deeplabcut[gui]'==2.3rc1). Then I get the error above about the style.qss when I try to run the gui

**Comment by jeylau** [comment]
That's because the fix will be live with our next pypi release. If you can't wait, rather install deeplabcut this way: `pip install git+https://github.com/DeepLabCut/DeepLabCut.git`; this will pull the most recent code changes.

**Comment by kthcwd** [comment]
OK - great - thank you!
