### ISSUE TITLE
DLC 2.2.2 GUI: Labeling data, copying labels from one frame to the next

### ISSUE THREAD

**Issue by MSchellenberger** [DeepLabCut/DeepLabCut#2018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When labeling frames, pressing ctrl + c seems to copy the labels of the current frame if you use it the first time. So far so good. However, afterwards ctrl +c will always paste the labels copied from the first use of ctrl+c. Additionally, ctrl+v does not seem to do anything.
Thank you for your help!

![221018_issue_DLC_labeling_frames_ctrl+c_use_1](https://user-images.githubusercontent.com/97124047/196453311-5292b6f7-aebf-4731-9a2a-31ca8742be73.png)
![221018_issue_DLC_labeling_frames_ctrl+c_use_2](https://user-images.githubusercontent.com/97124047/196453325-f632e3ee-f1dd-4592-b1d4-e21d40427bde.png)

### Operating System

Windows 11

### DeepLabCut version

DLC 2.2.2

### DeepLabCut mode

single animal

### Device type

CPU: 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz   3.30 GHz
GPU: none used

### Steps To Reproduce

1. I saw the issue on multiple environments, here I used the one in the attached file
[221018_issue_DLC_labeling_frames_ctrl+c_env.txt](https://github.com/DeepLabCut/DeepLabCut/files/9811372/221018_issue_DLC_labeling_frames_ctrl%2Bc_env.txt)

2. Open GUI
3. Load any project
4. Head to label frames
5. Label frames
6. Load frames
7. ctrl +c
8. This is the step where the bug shows: move to the next frame, then click ctrl + c again.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hey @MSchellenberger, I'll close this issue, as this is supported in the new napari-based labeling GUI. Feel free to reopen one at https://github.com/DeepLabCut/napari-deeplabcut if you encounter some bug!
