### ISSUE TITLE
Visualizing 3D DLC videos on Google Colab

### ISSUE THREAD

**Issue by Aziz965** [DeepLabCut/DeepLabCut#2019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am running a 3D DLC project using two cameras on Google Colab.

I managed to run all steps successfully, and I already have the final triangulation output for my tracked videos. The issue I'm facing is with the: deeplabcut.create_labeled_video_3d

I keep getting this error message: IndexError: list index out of range

I found several posts where others got a similar message and I tried the solutions given but that did not help. These included adding the videotype, making sure that the path is correct ['path of folder with videos and 3d.h5 files'], and properly connecting the skeleton  

I found a post where the author suggested typing in this code when trying to create 3d labelled videos on Colab:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

However, that did not help with my issue.

Here is the command and the error message
![Error message](https://user-images.githubusercontent.com/116289297/196988650-e308e621-19bd-4656-83bd-dc17a3137037.png)

This is the 3D config file
![3D-Config-file](https://user-images.githubusercontent.com/116289297/196982861-03f3ab01-aa6c-4049-a122-6fb2db65966c.png)

the config file for camera-1
![config cam1](https://user-images.githubusercontent.com/116289297/196984781-0c4e8e18-df23-427d-a941-4b2a42c33dfa.PNG)

the config file for camera-2
![config cam2](https://user-images.githubusercontent.com/116289297/196984867-eb20ce7a-58b5-4c0b-8fa9-ac1519ddad49.PNG)

I hope this covers everything needed

Thanks in advance

### Operating System

Colab

### DeepLabCut version

dlc version: 2.2.3

### DeepLabCut mode

3d

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
from your error do I understand that is works outside of colab? could you try passing none for the folder? 
https://deeplabcut.github.io/DeepLabCut/docs/Overviewof3D.html

**Comment by Aziz965** [comment]
> from your error do I understand that is works outside of colab? could you try passing none for the folder? https://deeplabcut.github.io/DeepLabCut/docs/Overviewof3D.html


I just tried running the code on windows and I got the same error message. I also tried passing none for the folder, but it didn't help

<img width="940" alt="create labeled video 3d" src="https://user-images.githubusercontent.com/116289297/197236478-1e930ca3-cf0a-4eb6-86f5-3cb586813364.png">

**Comment by Aziz965** [comment]
I managed to get it to work by starting new 2D projects from scratch and making sure that the names of the body parts exactly matched.

Initially, the first time I created the projects and adjusted the config files, I capitalized the first letter on one of the body parts in the 'camera1-2d-project' but not in the 'camera2-2d-project'. Later, when I started the 3D project, I found that error and fixed it, but I guess that the mismatch still remained in background files, which led to the IndexError.

**Comment by Aziz965** [comment]
Just to add to my last comment, there is actually a way to get the create_labeled_videos_3d command to work even if there was initially a mismatch in the names of the body parts. initially I thought that renaming the body parts in the config file would solve the issue, but that did not help.

 Instead, the way to do it is to modify the names of the body parts in the pose_cfg.yaml for both projects, and ensuring that they match. this seems to have solved it for me and I was able to visualize the data.
