### ISSUE TITLE
Analyze videos CSV files short on frame numbers 

### ISSUE THREAD

**Issue by Charlottewiltshire97** [DeepLabCut/DeepLabCut#2023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi DeepLabCut!

I am having an issue when analyzing videos. The csv files created have less frames than the videos do. For example, a video has 325 frames but the csv stops at 185 frames. When creating a video to check detections, DLC appears to track all the way to the end. Is there a reason I am not seeing these numbers on the csv? I would like to add this is not for every video and that deleting the files and re-running did not fix it. 

Thank you in advance for your help and as always I want to apologise in advance if it is my own naivety causing the problem!

Best wishes, 
Charlotte & the Wild Minds lab 

### Operating System

windows 

### DeepLabCut version

2.2

### DeepLabCut mode

multi animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hello @Charlottewiltshire97, could you tell us exactly what version of DeepLabCut you are using? (run `python -c 'import deeplabcut;print(deeplabcut.__version__)'` in your terminal.)

**Comment by Charlottewiltshire97** [comment]
Hey @jeylau, I am using 2.2.2. Thank you for such a swift response!

**Comment by oliriley** [comment]
Is it possible it's an issue within the files? 

I had something similar happening when analyzing some .avi files, it turned out their framenumber indexes had gotten corrupted & needed to be repaired.

**Comment by Charlottewiltshire97** [comment]
Hi @oliriley. I have just tried redownloading the video completely and it still cut off at the exact same place. Interestingly, if I run the same video through an older model it also cuts short (121 frames instead of the 185 frames my most recent model cuts it at). Again, I ran this twice to be sure and the video appears to have detections right until the end.

**Comment by Charlottewiltshire97** [comment]
I should probably add this is an entirely novel video to the model, so it doesn't have any interaction with the model prior to me trying to analyze it

**Comment by MMathisLab** [comment]
seems the H5 file is correct length? ie., if you can create labeled video (which uses H5), so this seems some CSV issue 

(side note, much better to use the H5 files, better data standard quality, and we really do not recommend using CSV)

**Comment by Charlottewiltshire97** [comment]
Hi Mackenzie!
Thank you for pointing this out to us. We opened up the .h5 file and it stops at the same length as the .csv, however the 'create labelled video' is showing detections to the end of the video. Any ideas?

**Comment by jeylau** [comment]
Closing as clarified by @AlexEMG via email.

=> The video created with `deeplabcut.create_video_with_all_detections` may look different from the final output as it includes all detections (false positives too, e.g.) prior to assembly and tracking.
