### ISSUE TITLE
ERROR: Cannot install deeplabcut and deeplabcut==2.1.8 because these package versions have conflicting dependencies

### ISSUE THREAD

**Issue by ZHU883000** [DeepLabCut/DeepLabCut#2024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

The conflict is caused by:
    deeplabcut 2.1.8 depends on numpy==1.16.4
    matplotlib 3.0.3 depends on numpy>=1.10.0
    h5py 2.7.0 depends on numpy>=1.7
    opencv-python 3.4.18.65 depends on numpy>=1.17.3; python_version >= "3.8"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

### Operating System

Ubuntu16

### DeepLabCut version

dlc version 2.1.8,maybe

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

after "pip  install deeplabcut"

### Relevant log output

```shell
no
```

### Anything else?

no

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@ZHU883000 please update to the latest; run `pip install --upgrade --force-reinstall 'deeplabcut[gui]'`
