### ISSUE TITLE
GUI | OPT: Extract outliers| manual | multiple videos | unable to extract frames from next video

### ISSUE THREAD

**Issue by KareemShalabi** [DeepLabCut/DeepLabCut#2027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

During manual extraction of outliers ,If for some reason you select multiple videos to analyse, EXTRACT FRAMES GUI only loads the first video file of the list.  the only way to load the next video is to load the whole project again selecting only one video at time.

### Operating System

operating system: Windows 10 x64

### DeepLabCut version

dlc version: 2.2.3

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
hi @KareemShalabi do you want to try the latest GUI? if so, please see: https://deeplabcut.github.io/DeepLabCut/docs/PROJECT_GUI.html

`pip install --upgrade --force-reinstall 'deeplabcut[gui]'==2.3rc1`

**Comment by jeylau** [comment]
Hello @KareemShalabi, is this still happening with the new GUI?

**Comment by KareemShalabi** [comment]
No it doesn't happen with the new GUI. You can close this thread. Thank you All.
