### ISSUE TITLE
Missing file error when training network on CPU

### ISSUE THREAD

**Issue by guyts** [DeepLabCut/DeepLabCut#203]
DLC 2.0.4, Win10, CPU, Anaconda (3.6)

Used to work alright before upgrading to 2.0.4.
I'm running train_network with the config file, but getting an error that the pose_cfg is not in its directory.

I've double checked multiple times, and the pose_cfg file is in right place.
I removed the folder and ran create_training_dataset again. The pose_cfg file was again created (in the right location), but I get the same error (below).

For clarification, I'm at the correct parent directory when running the code, and all previous functions in the process worked.

`FileNotFoundError: [Errno 2] No such file or directory: 'dlc-blinking\\blinking-lr-2019-02-06\\dlc-models\\iteration-0\\blinkingFeb6-trainset95shuffle1\\train\\pose_cfg.yaml'`

Any idea how to fix?

**Comment by MMathisLab** [comment]
Please update to 2.0.4.1 and re-create the training. There was a potential error if you created the project in 2.0.3 then used 2.0.4 but that is resolved in the latest update.

**Comment by guyts** [comment]
Ok I've done that, but am getting the same error exactly:

I've verified DLC version:
`print(deeplabcut.__version__):  2.0.4.1`

To clarify - before recreating the dataset, I deleted the files in iteration-0 folder both under dlc-models and under training-datasets, and then reran create_traininig_dataset.

**Comment by MMathisLab** [comment]
Can you post your pose_config.yaml file that is inside the training folder?

**Comment by guyts** [comment]
Attached.
[pose_cfg-txt.txt](https://github.com/AlexEMG/DeepLabCut/files/2841769/pose_cfg-txt.txt)

**Comment by guyts** [comment]
To update, in the meantime I've set up a new project on 2.0.4.1 from the get go, and it works alright.

**Comment by MMathisLab** [comment]
good to hear; if you've already labeled data you should be able to just move the images/CollectedData files to the new project. I'm still unclear of what happened, but since resolved I'll close the issue.
