### ISSUE TITLE
Analyzing videos: Having to select how many individuals are in each video 

### ISSUE THREAD

**Issue by Charlottewiltshire97** [DeepLabCut/DeepLabCut#2031]
Hey DeepLabCut!

In this thread I wanted to discuss "Analyze videos" tab ->  "Number of Animals". Whilst I am sure selecting the number of animals may help DeepLabCut detect the individuals, it makes our research slower. Below I will discuss why and I would love your input on how we can streamline the process.

**Is your feature request related to a problem? Please describe.**
With our dataset on wild apes, the number of individuals changes with every video. This means I have to sit and manually watch the videos to decide how many are in that particular clip, then reset GUI when this number changes, meaning I cannot just leave DLC to run 'analyze videos' on 100 videos like I used to be able to. This is slowing down our research. 

**Describe the solution you'd like**
I am guessing telling DLC how many individuals it is expecting allows for better tracking, but is there a way to not have to do this? In an ideal world, the same level of tracking proficiency without having to state the number of individuals would be great! In a realistic world, having the option to just run through 100+ videos at one time would be awesome.

Thank you for taking the time to consider this and I will look forward to your solutions!

Best wishes, 
Charlotte & The Wild Minds Lab

**Comment by MMathisLab** [comment]
bump @AlexEMG
