### ISSUE TITLE
3D DeepLabCut

### ISSUE THREAD

**Issue by dukezacks** [DeepLabCut/DeepLabCut#2032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello, i have a problem with the 3D deeplabcut. on the calibration part i get errors although i follow the process guided from {https://github.com/DeepLabCut/DeepLabCut/blob/a70c9b7cab8cbad6a5014e4b07d9e35deead729c/examples/JUPYTER/Demo_3D_DeepLabCut.ipynb}

i am using the same data that has been suggested to download from {https://data.caltech.edu/records/20164}
Thank you.
![2020](https://user-images.githubusercontent.com/106013071/199672297-8615eee4-e2a6-4d2d-9fa9-c628e4b7788e.png)

### Operating System

operating system: Linux Ubuntu 20.04 lts

### DeepLabCut version

dlc version : 2.3rc1  

### DeepLabCut mode

3d

### Device type

gpu: 3060ti

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@DukeMacrocat could you give more details; do you have an image of your checkerboard you can share?

**Comment by dukezacks** [comment]
@MMathisLab 

[calib_example (1).zip](https://github.com/DeepLabCut/DeepLabCut/files/9947545/calib_example.1.zip)

Thank you for the reply. This are my checkerboard i am using although i remove the ones that the corners were not recognized still i get same errors.

**Comment by dukezacks** [comment]
solved Thank you
