### ISSUE TITLE
MovieS2_Perturbation_noLaser_compressed.avi is missing 

### ISSUE THREAD

**Issue by DonnieKim411** [DeepLabCut/DeepLabCut#204]
`MovieS2_Perturbation_noLaser_compressed.avi` is missing from `examples/Reaching-Mackenzie-2018-08-30/videos` 

Mind if u can share the video? I am trying to follow the demo from examples...

Cheers,

**Comment by MMathisLab** [comment]
fixed! https://github.com/AlexEMG/DeepLabCut/commit/f26a65c5e51a779b67621e11af31f01f95e90e1b
