### ISSUE TITLE
Installation, missing linking to libiconv?

### ISSUE THREAD

**Issue by zyzhang1992** [DeepLabCut/DeepLabCut#2041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am installing with pip install "deeplabcut[gui, tf]" but ran into the error, 

 ```
/tmp/pip-install-1s2wnff1/wxpython_fcf72eaf8ef04fbba04081bb22b4cd98/build/wxbld/gtk3/lib/libwx_baseu-3.0.so: undefined reference to `libiconv'
    /tmp/pip-install-1s2wnff1/wxpython_fcf72eaf8ef04fbba04081bb22b4cd98/build/wxbld/gtk3/lib/libwx_baseu-3.0.so: undefined reference to `libiconv_close'
    /tmp/pip-install-1s2wnff1/wxpython_fcf72eaf8ef04fbba04081bb22b4cd98/build/wxbld/gtk3/lib/libwx_baseu-3.0.so: undefined reference to `libiconv_open'
```

I do have libiconv installed in the conda environment. Looks like the link path may not be correct, 

 `   g++ -o wxrc wxrc_wxrc.o    -L/tmp/pip-install-1s2wnff1/wxpython_fcf72eaf8ef04fbba04081bb22b4cd98/build/wxbld/gtk3/lib  -pthread   -L/home/groups/ruthm/zyzhang/sw/sherlock2/anaconda-envs/DEEPLABCUT/lib    -lwx_baseu_xml-3.0  -lwx_baseu-3.0     -lwxregexu-3.0 -lwxexpat-3.0 -pthread   -L/home/groups/ruthm/zyzhang/sw/sherlock2/anaconda-envs/DEEPLABCUT/lib  -Wl,--version-script,/tmp/pip-install-1s2wnff1/wxpython_fcf72eaf8ef04fbba04081bb22b4cd98/build/wxbld/gtk3/version-script -lz -ldl -lm  -lz -ldl -lm `

Could you please advise what I should do to fix this? 

### Operating System

operating system: CentOS 7

### DeepLabCut version

dlc version: 

### DeepLabCut mode

multi animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
It is apparently trying to build wxpython, which indicates that it is not installing deeplabcut's latest version. Rather try with `pip install --upgrade --force-reinstall "deeplabcut[gui,tf]"==2.3rc2` and let us know if that works 😊.

**Comment by zyzhang1992** [comment]
Thanks @jeylau That seemed to work and the installation finished without error. However, it did break the python/conda environment somehow. When I do conda list or conda search, I got the following errors, 

`Error processing line 1 of /home/groups/ruthm/zyzhang/sw/sherlock2/anaconda/Anaconda3-2022.05/lib/python3.9/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/home/groups/ruthm/zyzhang/sw/sherlock2/anaconda/Anaconda3-2022.05/lib/python3.9/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
Traceback (most recent call last):
  File "/home/groups/ruthm/zyzhang/sw/sherlock2/anaconda/Anaconda3-2022.05/lib/python3.9/site-packages/conda/models/version.py", line 11, in <module>
    from tlz.functoolz import excepts
ModuleNotFoundError: No module named 'tlz.functoolz'

During handling of the above exception, another exception occurred:` 

Any idea about how to fix that?

**Comment by jeylau** [comment]
That's odd, but according to [this](https://github.com/conda/conda/issues/9876), it may be a matplotlib-related issue. You could try `pip uninstall matplotlib` followed by `pip install --no-cache matplotlib` to reinstall it.
