### ISSUE TITLE
DLC 2.3rc2 - Labeling frames: No option to quit without saving

### ISSUE THREAD

**Issue by MSchellenberger** [DeepLabCut/DeepLabCut#2042]
When labeling frames in the beautiful new GUI, I think it would be nice to have the option to not to save the results. However, Napari does not allow closing the window if the data is not saved.
It would hence be nice if there was an option to close the Napari window without saving after kindly being reminded that the data should be saved.

**Comment by jeylau** [comment]
Good point @MSchellenberger! While I implement it, a trick is to delete the Points layer; you'll then be allowed to close the GUI normally.

**Comment by backyardbiomech** [comment]
@jeylau This trick isn't working. I'm running the main branch pulled and installed today (Jan 20) on windows. The folder I open has both machine labels and collected data files. The only way to close that window is to terminate the terminal which closes the full GUI. 
No error is printed.
Task manager can't even close it.
