### ISSUE TITLE
ValueError: len() should return >= 0

### ISSUE THREAD

**Issue by GeneRuan** [DeepLabCut/DeepLabCut#2048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

![Image 11-11-22 at 12 24 PM](https://user-images.githubusercontent.com/114833740/201782766-8173652a-2cd0-437e-825c-491a0ec6f690.jpg)

I receive this error when trying to use multi-animal analysis; in the DeepLabCut GUI, I try to extract frames and it fails to do so, even though the paths to the files exist. 

### Operating System

macOS Monterey, version 12.5.1

### DeepLabCut version

dlc version 2.2
GUI v2.2.3

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

1. Open the DLC GUI. Create a new file for a multi-animal project using these two images to start. (These two are supposed to be pre-annotated data.)
![img40179_individual](https://user-images.githubusercontent.com/114833740/201784581-e314abe4-d9e9-4e08-ac31-8e2577f6c29b.png)
![img27527_individual](https://user-images.githubusercontent.com/114833740/201784591-41b9832e-b7cb-48fc-8ea7-c3515b3bcde7.png)
2. Edit config file for multi-animal, using 1-100 individuals, and the hen annotations here.
<img width="1019" alt="DLC_ErrorPage1" src="https://user-images.githubusercontent.com/114833740/201784780-cbe5c8de-652c-4459-bf1a-9d875185d54e.png">
<img width="1019" alt="DLC_ErrorPage2" src="https://user-images.githubusercontent.com/114833740/201784796-d4995f25-8e79-47b4-bbc3-35e1fe6bce88.png">
<img width="1019" alt="DLC_ErrorPage3" src="https://user-images.githubusercontent.com/114833740/201784804-a9100ce5-f88a-4692-b167-2ae197454a0f.png">
3. Move to "Extract Frames" tab, and keep everything default.
4. Run. See Error.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
It looks like something is wrong with the video's metadata. Could you please try the following:
```python
import cv2

vid = cv2.VideoCapture("path_to_your_video_file")
print(vid.get(cv2.CAP_PROP_FRAME_COUNT))
```
What number of frames are you getting?

**Comment by MMathisLab** [comment]
I think the issue is the GUI to extract frames from video expects a **video**, but you uploaded 2 images? can you clarify?

**Comment by jeylau** [comment]
@MMathisLab, good catch, I overlooked that.

@GeneRuan, in order to extract frames, you need to have a video file, rather than images already.
If you really want to get started with these two frames only, you could follow this [post](https://forum.image.sc/t/skip-extract-frames-labeling-images-without-a-video/40912/2?u=jeylau) (though it's hacky and I would only recommend starting from a video).
