### ISSUE TITLE
Movidius

### ISSUE THREAD

**Issue by DemetrisS** [DeepLabCut/DeepLabCut#205]
Not sure if this is the appropriate place to ask  - this is not a feature request nor an issue but a a generic question that I wasn't able to address elsewhere...

Ubuntu 16.04, Anaconda, Ver 2

I have been using DLC and works great for me.

I just wanted to ask if, once a network has been trained, whether it would be possible to port it to a movidius stick? Has anyone tried?

Many thanks,
DS

**Comment by AlexEMG** [comment]
I think this is possible, but unfortunately not something we will work towards. It would be a great addition. As such TensorFlow models can be ported to Intel's movidius stick (see https://www.movidius.com/news/introducing-tensorflow-support-for-neural-compute-stick)

P.S.: this is also related to (for Android porting): https://github.com/AlexEMG/DeepLabCut/issues/142

**Comment by DemetrisS** [comment]
Hi Alex 

Many thanks for getting back - if i make any progress ill post back here.

Best, 
Demetris

**Comment by OptogeneticsandNeuralEngineeringCore** [comment]
DemetrisS, Please email me at neuralengineering@ucdenver.edu. I'd like to collaborate on this. I will have one overnight-ed to me so I can play with it this weekend (it's a long weekend here in the States).

**Comment by iceriverg** [comment]
Hi, DemetrisS, 

I have been also burned some models into Movidius, such as image recognition and face recognition. It would be great to try some more with animal. 

Have you made any progress? it would be better to develop an model in tensorfolw, then just convert it. But not sure how deeplabcut's model based on. Do you have any clue?

/River

> Hi Alex
> 
> Many thanks for getting back - if i make any progress ill post back here.
> 
> Best,
> Demetris
