### ISSUE TITLE
missing widget single animal analysis

### ISSUE THREAD

**Issue by guiwitz** [DeepLabCut/DeepLabCut#2052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When running a basic single animal analysis with the latest version of DLC (main branch), the workflow steps via the GUI work without problem until the "Analyze videos" tab. There when using defaults and clicking on the ```Analyze Videos``` button the error ```AttributeError: 'AnalyzeVideos' object has no attribute 'create_detections_video_checkbox'``` comes up. From looking at the code, it looks like the widget [```create_detections_video_checkbox```](https://github.com/DeepLabCut/DeepLabCut/blob/f7170311e68b4ad9ae15bc10894226f927573b45/deeplabcut/gui/tabs/analyze_videos.py#L171) is created in the call to [```_generate_layout_multianimal```](https://github.com/DeepLabCut/DeepLabCut/blob/f7170311e68b4ad9ae15bc10894226f927573b45/deeplabcut/gui/tabs/analyze_videos.py#L133) which obviously only happens for multi-animal experiments. I'm not familiar enough with DLC to know whether that option should also be available for single animal experiments and therefore the widget be created somewhere else, or if that call should only happen for multi-animal experiments.

### Operating System

Mac M1

### DeepLabCut version

2.3rc2

### DeepLabCut mode

single animal

### Device type

Mac M1 GPU

### Steps To Reproduce

Simply install the latest version on main and run a default analysis with the example mouse data.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by cagriozkurt** [comment]
Same here, a workaround is moving `create_detections_video_checkbox` (lines 171-173) under `_generate_layout_other_options()`.
