### ISSUE TITLE
TypeError when trying to refine_labels after Google Colab

### ISSUE THREAD

**Issue by juliabandura** [DeepLabCut/DeepLabCut#2058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have trained a network, analyzed a large set of new videos, and I'm now trying to refine_labels to retrain on some of the worse-labeled parts of my videos. I extracted outlier frames in Google Colab - however, as I need the GUI, I have downloaded my whole folder to my local machine to do the refine_labels. However, when I open the project and go to the refine_labels tab, despite having .h5 and .csv files in each folder, the frames do not show up and I get a traceback error in the console as detailed in the log. As well, if I try to go to the next image, I get:
`IndexError: list index out of range`

Let me know if there's any more information needed to try to solve this.

Thank you!

### Operating System

Ubuntu 18.04

### DeepLabCut version

dlc version 

### DeepLabCut mode

single animal

### Device type

CPU

### Relevant log output

```shell
Traceback (most recent call last):
  File "/media/julia/Data/Julia/anaconda3/envs/DLC/lib/python3.7/site-packages/deeplabcut/gui/refinement.py", line 404, in browseDir
    self.img = os.path.join(self.project_path, self.index[self.iter])
  File "/media/julia/Data/Julia/anaconda3/envs/DLC/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/media/julia/Data/Julia/anaconda3/envs/DLC/lib/python3.7/genericpath.py", line 153, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'tuple'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hello! Make sure you use `pip install deeplabcut>=2.2.1`, this is a bug that we fixed 12 months ago.

**Comment by juliabandura** [comment]
> Hello! Make sure you use `pip install deeplabcut>=2.2.1`, this is a bug that we fixed 12 months ago.

This worked! Thank you so much :)
