### ISSUE TITLE
delete accidentally placed label

### ISSUE THREAD

**Issue by mschart** [DeepLabCut/DeepLabCut#206]
Hi there,

I'm using the GUI for labeling and I sometimes had the problem to place a point too quickly, hence I'd like to delete it (as that point is not seen in the given frame). Now I need to restart or keep that error in there and hope for the best. The option to delete an accidentally picked point would be nice.

Cheers

**Comment by AlexEMG** [comment]
Hey!

The newest version >2.0.4 can do that (pip install deeplabcut==2.0.4.1). You need to use the middle mouse key. The new GUI also allows intermediate saving, moving all points at any point, going back and forth ... It is really convenient - let me know how it works for you!

Cheers,
Alexander

P.S. now one can also add (missed) labels at any later point: https://github.com/AlexEMG/DeepLabCut/issues/147
P.P.S: before 2.0.4 the solution for deleting was to use the refinement GUI (and adjust the original labels). This method could not add points though, now adding, removing & changing are supported.

**Comment by qsimeon** [comment]
what's the equivalent of "middle mouse button" on a macbook though?

**Comment by catubc** [comment]
I am also looking for the same.

**Comment by backyardbiomech** [comment]
Look for bettertouchtool (https://folivora.ai/buy). It's very affordable and does much more, and does allows middle click with trackpad or magic mouse
.

**Comment by MMathisLab** [comment]
@catubc @qsimeon - in a near release it will also have a hot key: i.e the "delete" button.... now that I have to work from home on my macbook, I also am annoyed by this ;).

**Comment by catubc** [comment]
Hey guys, I think there's some mac settings for doing this, here's a youtube video:

https://www.youtube.com/watch?v=VIr9R1P2wys
