### ISSUE TITLE
extract matching frames  does not look for videos_list

### ISSUE THREAD

**Issue by felixtrinoma** [DeepLabCut/DeepLabCut#2061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi, 

When extracting matching frames with extract_frames, it works only if videos are stored in the "videos" directory of the project. 

It looks for neither the paths mentioned in the config file nor the paths in the videos_list. 

### Operating System

Windows 10 professional version 22H2

### DeepLabCut version

dlc version 2.2.1.1

### DeepLabCut mode

3d

### Device type

gpu

### Steps To Reproduce

1. Store videos from cam1 and cam2 in a serapate folder
2. Manually add video file paths in the config file and create the corresponding folders in "labeled-data" in the project
3. Extract frames from cam1 only (easiest way is to write path to videos_list)
4. Extract frames from cam2 using "match" mode. 

This step 4 will work only if cam2 video file is in "videos" folder in the project. Writing cam2 video file path in videos_list at step 4 does not work. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by felixtrinoma** [comment]
Hi, any news ? 

Thanks, 
Félix

**Comment by jeylau** [comment]
Hi @felixtrinoma, sorry for the delay. I'll be looking at it now!

**Comment by felixtrinoma** [comment]
Hi, I see you have fixed the bug. Thank you very much ! Waiting for the merge now.

**Comment by jeylau** [comment]
Note that if you don't want to wait, you could pull the changes using: `pip install git+https://github.com/DeepLabCut/DeepLabCut.git@fix_extract_matched` 😌
