### ISSUE TITLE
value error: the passed save_path is not a valid checkpoint 

### ISSUE THREAD

**Issue by sarahy191** [DeepLabCut/DeepLabCut#2062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

when training i get this error and not sure how to change it as it is not in the config file 

### Operating System

mac

### DeepLabCut version

dlc version2

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

ValueError: The passed save_path is not a valid checkpoint: /Users/sarahy/Desktop/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@sarahy191 can you fill out the steps to reproduce; is this at train time, etc.

**Comment by jeylau** [comment]
Somehow the model is not found, perhaps because its download did not complete during the creation of the training dataset. Recreating the training dataset (either through the GUI or `deeplabcut.create_training_dataset(...)` would fix this issue.
