### ISSUE TITLE
Can not create training dataset - FileNotFoundError: [Errno 2] (path length on windows...)

### ISSUE THREAD

**Issue by jennymsmith94** [DeepLabCut/DeepLabCut#207]
**Windows 10 Pro with an Anaconda Env and DeepLabCut 2.0.4**

After labeling frames, I am unable to create the training dataset and the following error is output.
FileNotFoundError: [Errno 2] No such file or directory:

Upon entering the following command:
**deeplabcut.create_training_dataset(path_config_file,num_shuffles=1)**

This is the output I receive from python:

  **File "<ipython-input-3-89ffde556bf7>", line 1, in <module>
    deeplabcut.create_training_dataset(path_config_file,num_shuffles=1)

  File "C:\Users\PfeifferLab\Anaconda3\envs\deeplabEnv\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 1079, in create_training_dataset
    auxiliaryfunctions.SaveMetadata(os.path.join(project_path,metadatafilename),data, trainIndexes, testIndexes, trainFraction)

  File "C:\Users\PfeifferLab\Anaconda3\envs\deeplabEnv\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 165, in SaveMetadata
    with open(metadatafilename, 'wb') as f:

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\PfeifferLab\\Anaconda3\\envs\\deeplabEnv\\Lib\\site-packages\\deeplabcut\\KcConditional-HCandSI-DC-Lilyana-2019-02-11\\training-datasets\\iteration-0\\UnaugmentedDataSet_KcConditional-HCandSI-DCFeb11\\Documentation_data-KcConditional-HCandSI-DC_95shuffle1.pickle'**

Any help would be greatly appreciated!

**Comment by MMathisLab** [comment]
It is likely related to this: #196 - Also I wouldn't recommend making your projects inside the site-packages; I would move this folder to somewhere like Documents. You can just change the ``project_path`` inside the ``config_file`` after you move it.

**Comment by jennymsmith94** [comment]
Great, thank you! This fixed the problem.

**Comment by AlexEMG** [comment]
This path-length issue on windows is quite funny. and not something one would expect...
