### ISSUE TITLE
error in create training dataset

### ISSUE THREAD

**Issue by mdciri** [DeepLabCut/DeepLabCut#2072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am using the GUI to do training a tracking task and after I have labeled the data, the next step is to create a training dataset, but I got this error:

```
python -m deeplabcut
Loading DLC 2.3rc3...
Starting GUI...
Traceback (most recent call last):
  File "C:\Users\Marco.VPP\Miniconda3\envs\dlc\lib\site-packages\deeplabcut\gui\tabs\create_training_dataset.py", line 88, in create_training_dataset
    deeplabcut.create_multianimaltraining_dataset(
  File "C:\Users\Marco.VPP\Miniconda3\envs\dlc\lib\site-packages\deeplabcut\generate_training_dataset\multiple_individuals_trainingsetmanipulation.py", line 203, in create_multianimaltraining_dataset
    Data = merge_annotateddatasets(cfg, full_training_path)
  File "C:\Users\Marco.VPP\Miniconda3\envs\dlc\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 479, in merge_annotateddatasets
    conversioncode.guarantee_multiindex_rows(data)
  File "C:\Users\Marco.VPP\Miniconda3\envs\dlc\lib\site-packages\deeplabcut\utils\conversioncode.py", line 247, in guarantee_multiindex_rows
    df.index = df.index.set_levels(df.index.levels[1].astype(str), level=1)
  File "C:\Users\Marco.VPP\Miniconda3\envs\dlc\lib\site-packages\pandas\core\indexes\frozen.py", line 73, in __getitem__
    return super().__getitem__(n)
IndexError: list index out of range
```

I think that somehow the dataframe read from the .h5 file is not multiindex. 
How should I fix this?

PS: my "individuals" are not all present in all frames, and sometimes one or more of their "bodyparts" are not present because of occlusion. May this be a problem?

thanks in advance.

### Operating System

windows

### DeepLabCut version

dlc version 2.3rc3

### DeepLabCut mode

multi animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by tsizemo2** [comment]
I'm using an identical DLC setup and a similar machine, and am experiencing an identical error. @mdciri  did you find a way of resolving this since last week?

**Comment by yvonne-chen-0813** [comment]
I have the same question in DLC2.2rc3.  I did the same thing using DLC2.2rc2, but there is no such error.

**Comment by tsizemo2** [comment]
> I have the same question in DLC2.2rc3.  I did the same thing using DLC2.2rc2, but there is no such error.

Rolling back it is 👍

**Comment by mdciri** [comment]
No @tsizemo2, I haven't found the bug. I am waiting for @jeylau support. I will try too to use DLC2.2rc2.

**Comment by tsizemo2** [comment]
> No @tsizemo2, I haven't found the bug. I am waiting for @jeylau support. I will try too to use DLC2.2rc2.

Yes yes, apologies for any confusion re. my reply. My previous comment was merely me voicing what the temporary/quick solution might be for myself (& perhaps you as well).

**Comment by jeylau** [comment]
I think this bug has been solved very recently with https://github.com/DeepLabCut/napari-deeplabcut/commit/23463dedc0bbd58be052b51ea48bb1d8140719bf. On Windows, glob paths sometimes contained a mixture of forward and backward slashes, causing problems when writing the annotated data.
Make sure you `pip install napari-deeplabcut>=0.0.9`.

A simple way to get your current data file fixed is to open the CSV file in Excel or Google Sheets, and manually add the 2 missing columns (as in this image https://github.com/DeepLabCut/napari-deeplabcut/issues/30#issue-1301728053): one with `labeled-data` and the other with the corresponding video folder names.
You can then open that file in pandas and convert it to h5:
```python
import pandas as pd

df = pd.read_csv(path_to_file, header=[0, 1, 2, 3], index_col=[0, 1, 2])
df.to_hdf(path_to_file.replace('.csv', '.h5'), key='data')
```

**Comment by mano2991** [comment]
@jeylau followed your instruction still the same error pops up. my csv file looks like this. there wasn't any blank cells in my csv files. 

```
import pandas as pd
df = pd.read_csv("C:/Users/hp/Desktop/Lader-Test_mice-2022-12-23/labeled-data/One_side/CollectedData_Test_mice.csv",header=[0, 1, 2, 3], index_col=[0, 1, 2])
df.to_hdf("C:/Users/hp/Desktop/Lader-Test_mice-2022-12-23/labeled-data/One_side/CollectedData_Test_mice".replace('.csv','.h5'),key='data')
```

![image](https://user-images.githubusercontent.com/13638496/209345658-11f20c90-a1b3-4709-ab36-0a00629fa008.png)

**Comment by ablot** [comment]
FYI I had the issue again. I'm not sure exactly what were the step to generate it. It for sure stems from the fact that I train and do analysis on linux-based cluster while the manual labelling is done on a windows computer. Some going back and forth between the OS messes the file paths.
It was a bit annoying to figure out where things go wrong, so I just fix the bad files. If it helps, here is the function that seemed to work:

```python
from pathlib import Path
import yaml
import shutil
import pandas as pd


def fix_bad_path_handling(config_file, user):
    """Fix dirty file path generated by DLC-GUI

    Mixing OS induces bugs with filepaths that are not easily parsed. Try to fix bad
    csv and h5 generated by the manual labeling step with napari.

    Issue is there:
    https://github.com/DeepLabCut/napari-deeplabcut/issues/30#issue-1301728053

    Fix is described here
    https://github.com/DeepLabCut/DeepLabCut/issues/2072

    Args:
        config_file (str): path to the config.yml file
        user (str): Name of the user who did the labeling. 
    """

    with open(config_file, "r") as fhandle:
        config = yaml.safe_load(fhandle)
    root = Path(config["project_path"])
    assert root.is_dir()

    videos = [Path(k).stem for k in config["video_sets"]]

    labeled = root / "labeled-data"
    for subfolder in labeled.glob("*"):
        if not subfolder.is_dir():
            continue
        if subfolder.name in videos:
            labels = subfolder / f"CollectedData_{user}.h5"
            if not labels.exists():
                continue
            df = pd.read_hdf(labels)
            if df.index.nlevels != 1:
                continue
            print(f"{subfolder.name} needs fixing")
            shutil.copy(labels, labels.with_suffix(".h5.backup"))
            shutil.copy(labels.with_suffix(".csv"), labels.with_suffix(".csv.backup"))
            fixed = pd.concat({subfolder.name: df}, names=[])
            fixed = pd.concat({"labeled-data": fixed}, names=[])
            fixed.to_hdf(labels.with_suffix(".h5"), key="data", mode="w")
            fixed.to_csv(labels.with_suffix(".csv"))
```

**Comment by jeylau** [comment]
@mano2991, your file is still missing the 2 columns that need to be added: 'labeled-data' in the first column, and the name of your image folder in the second (as in the left image https://github.com/DeepLabCut/napari-deeplabcut/issues/30#issue-1301728053). Then it will work fine. You could also use @ablot's helper function, looks very convenient! 😌
