### ISSUE TITLE
NVIDIA GPU not Engaged During Training in DLC Docker GUI

### ISSUE THREAD

**Issue by samcentanni** [DeepLabCut/DeepLabCut#2079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Using DLC in the docker GUI on Ubuntu 18.04. It is not engaging the GPU when we run training. In the same conda environment if i run ipython and import tensorflow and check the status of the GPU with tf.test.is_gpu_available() i get “TRUE”

However in the deeplabcut docker gui it is not engaging the GPU during training.

### Operating System

Linux Ubuntu 18.04

### DeepLabCut version

dlc version DOCKER

### DeepLabCut mode

single animal

### Device type

±----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03 Driver Version: 460.32.03 CUDA Version: 11.2 |
|-------------------------------±---------------------±---------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
| | | MIG M. |
|===============================+======================+======================|
| 0 Quadro RTX 6000 Off | 00000000:73:00.0 On | Off |
| 33% 27C P8 18W / 260W | 451MiB / 24211MiB | 0% Default |
| | | N/A |
±------------------------------±---------------------±---------------------+

### Steps To Reproduce

**Environment (DLCenv):** 

channels:
  - conda-forge
  - anaconda
  - bioconda
  - defaults
dependencies:
  - cudatoolkit==11.2.2=he111cf0_8
  - cudnn==8.1.0.77=h90431f1_0
  - python=3.8
  - scipy
  - pandas
  - numpy
  - scikit-image
  - spyder
  - opencv
  - seaborn
  - scikit-learn
  - wxpython==4.0.7.post2=py38hac52f33_3

**Conda activate DLCenv**
**deeplabcut-docker gui**

### Relevant log output

```shell
**Output:** 
latest-gui: Pulling from deeplabcut/deeplabcut
Digest: sha256:3f08a9e7ee3b0d9ab9905cb13114363c70a012d656b5662b1dd888d9cbce43ad
Status: Image is up to date for deeplabcut/deeplabcut:latest-gui
docker.io/deeplabcut/deeplabcut:latest-gui
[2022-12-08T17:18:01-0500]: Configuring a local container for user samuel (1000) in group samuel (1000)
sha256:7d250a8b03b049a7c0967fa4e1a197b85dd489b5c02ad171920808a492210af6
[2022-12-08T17:18:01-0500]: Build succeeded
[2022-12-08T17:18:01-0500]: Using Linux config
2022-12-08 22:18:02.200688: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Starting GUI...

(__main__.py:1): dbind-WARNING **: 22:18:04.761: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-wyN00DEHVk: Connection refused
Gtk-Message: 22:18:04.798: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:18:04.799: Failed to load module "canberra-gtk-module"
```

### Anything else?

Extracting frames, labeling, training initiate just fine, GPU is just not engaged

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Hi @samcentanni the error is addressed in other issues: https://github.com/DeepLabCut/DeepLabCut/issues/1012
