### ISSUE TITLE
warning: Could not load matplotlib icon: can't use "pyimage352" as iconphoto: not a photo image

### ISSUE THREAD

**Issue by salvador-blanco** [DeepLabCut/DeepLabCut#208]
3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0]
Deep labcut 2.0.4
Ubuntu 16.04.5 LTS

I get the error when running on the MouseReaching example
deeplabcut.evaluate_network(path_config_file,plotting=True)

```
Restoring parameters from /home/chava/HDD/DLC2/examples/Reaching-Mackenzie-2018-08-30/dlc-models/iteration-0/ReachingAug30-trainset95shuffle1/train/snapshot-6900
0it [00:00, ?it/s]

Analyzing data...

19it [00:01, 13.26it/s]
Could not load matplotlib icon: can't use "pyimage343" as iconphoto: not a photo image

Done and results stored for snapshot:  snapshot-6900
Results for 6900  training iterations: 95 1 train error: 2.56 pixels. Test error: 7.17  pixels.
With pcutoff of 0.4  train error: 2.56 pixels. Test error: 7.17 pixels
Thereby, the errors are given by the average distances between the labels by DLC and the scorer.
Plotting...

Could not load matplotlib icon: can't use "pyimage352" as iconphoto: not a photo image
Could not load matplotlib icon: can't use "pyimage361" as iconphoto: not a photo image
Could not load matplotlib icon: can't use "pyimage370" as iconphoto: not a photo image
Could not load matplotlib icon: can't use "pyimage379" as iconphoto: not a photo image
```

I would appreciate your help

**Comment by AlexEMG** [comment]
This is just a warning/annoying error message. Please look at the notebook that we fully run for you, so you can see the typical outputs. It depends on your configuration, as we note in the notebook. 

https://github.com/AlexEMG/DeepLabCut/blob/master/examples/Demo_labeledexample_MouseReaching.ipynb
![image](https://user-images.githubusercontent.com/28102185/52727380-16b9b000-2f83-11e9-8f82-cef8fd6aa09d.png)
