### ISSUE TITLE
merge data report error in extracting outlier frames 

### ISSUE THREAD

**Issue by yvonne-chen-0813** [DeepLabCut/DeepLabCut#2080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have already extracted frames and labeled them in the labeling GUI.
But when I click the 'Merge data' button, there is a TypeError.

I have checked the issues and found that the code in 2.2rc3 seems to be the latest version.
Current answers are not suitable for me.

Thank you!

### Operating System

Windows 11

### DeepLabCut version

GUI 2.2rc3

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

1. click 'Merge data'
2. 
WARNING: QStatusBar::insertPermanentWidget: Index out of range (0), appending widget
Traceback (most recent call last):
  File "C:\Users\yifan\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\tabs\extract_outlier_frames.py", line 150, in merge_dataset
    msg.setWindowIcon([QtWidgets.QMessageBox.Warning])
TypeError: 'PySide6.QtWidgets.QWidget.setWindowIcon' called with wrong argument types:
  PySide6.QtWidgets.QWidget.setWindowIcon(list)
Supported signatures:
  PySide6.QtWidgets.QWidget.setWindowIcon(Union[PySide6.QtGui.QIcon, PySide6.QtGui.QPixmap])

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Thanks @yvonne-chen-0813 for reporting the bug! It will be fixed in the next release ☺️.

**Comment by yvonne-chen-0813** [comment]
Thank you!!
