### ISSUE TITLE
Windows native Tensorflow support is only upto 2.10.0

### ISSUE THREAD

**Issue by NirvikNU** [DeepLabCut/DeepLabCut#2081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Following the steps to install DEEPLABCUT using the provided conda environment file (DEEPLABCUT.yaml) in the latest version in Windows results in CPU mode only for training. This happens even though the correct version of CUDA (11.2) is pre-installed along with the correct NVIDIA graphics driver.

We found that this problem may be due to the fact that [tensorflow doesn't support native Windows from version > 2.10.0](https://www.tensorflow.org/install/pip#windows-native_1). We fixed the issue by forcing a new CUDNN and compatible tensorflow install after creating the DEEPLABCUT conda environment using the provided yaml file:

```conda env create -f DEEPLABCUT.yaml
conda activate DEEPLABCUT
conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0
pip uninstall tensorflow
pip uninstall tensorflow-intel
pip install tensorflow==2.10.0
pip install tensorflow-intel==2.10.0 
```

### Operating System

Windows 10

### DeepLabCut version

2.2.3

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Thanks for pointing this out @NirvikNU!

@MMathisLab, @AlexEMG, should we pin to tf>=2,<=2.10?

**Comment by MMathisLab** [comment]
yes, let's pin it! ft<2.11 is a good pin (over 2 isn't formally required)

**Comment by NirvikNU** [comment]
Hi, I retried the installation with the latest supplied environment after the fix was implemented. But it seems like the issue still remains. Additionally, I still need to manually install cudnn and cudatoolkit using conda-forge.

**Comment by MMathisLab** [comment]
the latest conda will not have the fix; @AlexEMG will push a new pypi version, otherwise to use changes in the repo you need to install from git - see docs
