### ISSUE TITLE
Deeplabcut 3D calibration problem

### ISSUE THREAD

**Issue by weirh0326** [DeepLabCut/DeepLabCut#2083]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Bug description

Hello.
 After I finish deleting any bad pairs from the corner and calibration_images files, when I start deeplabcut.calibrate_cameras, it have following error (I have 27 pairs images). How to solve this problem?:

deeplabcut.calibrate_cameras(‘Z:\Anaysis Codes for Data (MATLAB, DLC, etc)\DeepLabCut\Ran\Cam01-b-2021-01-20-3d\config.yaml’, cbrow=6, cbcol=8, calibrate=False, alpha=0.4)
error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-wbmte9m7\opencv\modules\calib3d\src\calibration.cpp:3336: error: (-2:Unspecified error) in function ‘void __cdecl cv::collectCalibrationData(const class cv::_InputArray &,const class cv::_InputArray &,const class cv::_InputArray &,int,class cv::Mat &,class cv::Mat &,class cv::Mat *,class cv::Mat &)’

(expected: ‘nimages == (int)imagePoints2.total()’), where
‘nimages’ is 54
must be equal to
‘(int)imagePoints2.total()’ is 27

### Operating System

operating system: Windows 

### DeepLabCut version

dlc version 2.1

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

In [5]: deeplabcut.calibrate_cameras('Z:\Current-Members\Ran\Cam01-WalkingMonkey-2022-12-06-3d\config.yaml', cbrow=6, c
   ...: bcol=9, calibrate=True, alpha=0.9)
Saving intrinsic camera calibration matrices for Cam0 as a pickle file in Z:\Current-Members\Ran\Cam01-WalkingMonkey-2022-12-06-3d\camera_matrix
Mean re-projection error for Cam0 images: 0.026 pixels
Saving intrinsic camera calibration matrices for Cam1 as a pickle file in Z:\Current-Members\Ran\Cam01-WalkingMonkey-2022-12-06-3d\camera_matrix
Mean re-projection error for Cam1 images: 0.026 pixels
Computing stereo calibration for

### Relevant log output

```shell
error                                     Traceback (most recent call last)
<ipython-input-5-1fdfc0affe4d> in <module>
----> 1 deeplabcut.calibrate_cameras('Z:\Current-Members\Ran\Cam01-WalkingMonkey-2022-12-06-3d\config.yaml', cbrow=6, cbcol=9, calibrate=True, alpha=0.9)

c:\users\walkway\appdata\local\continuum\anaconda3\envs\anipose\lib\site-packages\deeplabcut\pose_estimation_3d\camera_calibration.py in calibrate_cameras(config, cbrow, cbcol, calibrate, alpha)
    218                 dist_pickle[pair[1]]["dist"],
    219                 (h, w),
--> 220                 flags=cv2.CALIB_FIX_INTRINSIC,
    221             )
    222

error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-k3ngdfuh\opencv\modules\calib3d\src\calibration.cpp:3336: error: (-2:Unspecified error) in function 'void __cdecl cv::collectCalibrationData(const class cv::_InputArray &,const class cv::_InputArray &,const class cv::_InputArray &,int,class cv::Mat &,class cv::Mat &,class cv::Mat *,class cv::Mat &)'
>  (expected: 'nimages == (int)imagePoints2.total()'), where
>     'nimages' is 98
> must be equal to
>     '(int)imagePoints2.total()' is 49
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
stale issue
