### ISSUE TITLE
PAF maps generation in Deeplabcut 2.3rc3

### ISSUE THREAD

**Issue by Hizafa-Nadeem** [DeepLabCut/DeepLabCut#2084]
**Is your feature request related to a problem? Please describe.**
I would like to know if Deeplabcut==2.3rc3 provides the features of generation on PAF maps, score maps and locrefs?

**Describe the solution you'd like**
I would like to have same features of deeplabcut2.2 in deeplabcut 2.3rc3.

**Describe alternatives you've considered**

**Additional context**

**Comment by jeylau** [comment]
Hi! Yes, DLC2.3 will be backward-compatible with DLC2.2, model training has not changed (and you can still visualize PAFs, heatmaps and locref fields with `deeplabcut.extract_save_all_maps`).

**Comment by Hizafa-Nadeem** [comment]
Hello,

I would like to generate PAF maps using the GUI. DeepLabCut 2.3rc3 gui
doesn't show any button for generating maps.

Kindly, guide me in this regard.

Thank you,
Hizafa Nadeem
