### ISSUE TITLE
Error at train_network()

### ISSUE THREAD

**Issue by wmau** [DeepLabCut/DeepLabCut#209]
**Your Operating system and DeepLabCut version**
Windows 7, conda virtual environment imported into PyCharm IDE, DeepLabCut v2.0.4.1.

**Describe the problem**
Running train_network(path_config_file) gives me the following error message after "Starting training..." prints:

> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py", line 1322, in _do_call
>     return fn(*args)
>   File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py", line 1307, in _run_fn
>     options, feed_dict, fetch_list, target_list, run_metadata)
>   File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py", line 1409, in _call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
> 	 [[Node: resnet_v1_50/block4/unit_2/bottleneck_v1/conv1/weights/read/_1219 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_938_resnet_v1_50/block4/unit_2/bottleneck_v1/conv1/weights/read", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
> 	 [[Node: pose/part_pred/block4/stack/_1347 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1430_pose/part_pred/block4/stack", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\IPython\core\interactiveshell.py", line 2847, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-4-d17f40cf0f8b>", line 1, in <module>
>     dlc.train_network(path_config_file)
>   File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 81, in train_network
>     raise e
>   File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 79, in train_network
>     train(str(poseconfigfile),displayiters,saveiters,maxiters,max_to_keep=max_snapshots_to_keep) #pass on path and file name for pose_cfg.yaml!
>   File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py", line 142, in train
>     feed_dict={learning_rate: current_lr})
>   File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
>     run_metadata_ptr)
>   File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py", line 1135, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py", line 1316, in _do_run
>     run_metadata)
>   File "C:\ProgramData\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py", line 1335, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
> 	 [[Node: resnet_v1_50/block4/unit_2/bottleneck_v1/conv1/weights/read/_1219 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_938_resnet_v1_50/block4/unit_2/bottleneck_v1/conv1/weights/read", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
> 	 [[Node: pose/part_pred/block4/stack/_1347 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1430_pose/part_pred/block4/stack", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
> 

**How to Reproduce the problem**
Run train_network(path_config_file).

**Screenshots**
N/A

**Additional context**
GPU: NVIDIA Quadro 410, 4095 MB RAM
CUDA v9.0
cuDNN v7.3

**Comment by MMathisLab** [comment]
First, can you import ``tensorflow as tf`` and test if you can start a session? 

#### Which version of TF do I have installed?
``tf.__version__``

#### can I start a TF session?
``sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))``

Second, your GPU is also unlikely to be sufficient to use, unless your frames are **very** small memory (the Quadro 410: https://www.nvidia.com/content/PDF/data-sheet/nv-quadro-410-lr.pdf) This is why we recommend a card with at least 8 GB of memory. 

I would install the conda env for CPU ...

**Comment by wmau** [comment]
I think I am able to connect to my GPU. See below. 

> import tensorflow as tf
> tf.__version__
> Out[10]: '1.8.0'
> 
> sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
> Device mapping:
> /job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: Quadro 410, pci bus id: 0000:01:00.0, compute capability: 3.0

Hm what constitutes as small in memory? Frames are 304x236 pixels, ~18 MB per video. I'd like to see if I can get the GPU version running first then try CPU if that fails.

**Comment by MMathisLab** [comment]
okay, that is good that you can start a session, so TF is installed properly, etc and it's bound to the GPU. 

So, then I'm guessing the frames are just way too large for what is needed. 

The file size of the frame is not what makes the network; think how the ResNet has ~1M parameters, and each pixel makes the network larger (that is why larger frames = slower to train, slower to analyze). So, for that size, I think you would need something like a 1060 ~i.e. 6 GB of memory, and the Quadro 410 has 512 MB ... also it seems the Quadro has no CUDA compatible cores... so I don't think it will work... https://technical.city/en/video/GeForce-GTX-1050-Ti-vs-Quadro-410
![image](https://user-images.githubusercontent.com/28102185/52817727-b7d36400-3072-11e9-8143-91a05358a25a.png)

**Comment by wmau** [comment]
Weird, the CUDA website lists the Quadro 410 as a compatible GPU: https://developer.nvidia.com/cuda-gpus

I think you're right about the memory issue though: https://github.com/aymericdamien/TensorFlow-Examples/issues/38

Worth a shot, I guess I'll try the CPU env now. Thanks, closing the issue!
