### ISSUE TITLE
efficiently masking the videos

### ISSUE THREAD

**Issue by ludovicbellier** [DeepLabCut/DeepLabCut#2094]
Hi team DLC,

I have a particular use case for which I'm currently developing some code, and would like to get your input about 1) whether you have insights on how to best get this done, and 2) whether you would be interested in getting this as a feature (in such case I would create a PR).

Here's the use case: I have a set of videos in which I want to track one animal, but there is a second animal in part of the FOV, contained within a specific area, who can't move much and for which I'm not interested in getting pose estimates. I've tried to analyze one of these videos with a model trained on single-animal videos (hoping it would generalize like in Mathis et al., 2018, Fig. 4b), but it seemed like there could only be one instance of each body part label per frame (so sometimes the left back paw label was placed onto the animal I want to ignore, thus "stealing" the label from the animal of interest). I bypassed this issue by applying a mask on the video before frame extraction, effectively hiding the FOV area containing the second animal (and in which the animal of interest can't physically go). Hope this makes sense so far!

Now, here's the feature idea: instead of rewriting all videos to get the corresponding masked version, I was thinking we could do the same as cropping, i.e., in the config.yaml file, below each video we could have the option to put "mask: <some params>" to apply a mask on the video in an online way. The mask could either be a path to an image file of the exact same dimensions than the cropped frames, or even (messier but more "online") parameters for drawing shapes in the FOV (e.g., "circle", center_x, center_y, radius). And there would be relevant flags for all functions (extract_frames obviously, but also analyze_videos and create_labeled_videos).

And that's it, basically it's about adding a built-in masking feature alongside the existing cropping feature, so that we don't have to do this step beforehand loosing time and disk space doing so. I don't know if such use cases where masking is needed occur often though, hence this issue to get your insights on it first. Also, if you have suggestions on better ways to handle this use case than using masks, I'm looking forward to reading them!

Thank you,
Ludovic

**Comment by MMathisLab** [comment]
> I've tried to analyze one of these videos with a model trained on single-animal videos (hoping it would generalize like in Mathis et al., 2018, Fig. 4b), but it seemed like there could only be one instance of each body part label per frame (so sometimes the left back paw label was placed onto the animal I want to ignore, thus "stealing" the label from the animal of interest). 

You need to set `num_outputs` > 1 if you just want to get the points across animals, otherwise indeed it only takes the top-one hit.


> instead of rewriting all videos to get the corresponding masked version, I was thinking we could do the same as cropping, i.e., in the config.yaml file

Actually this exists :) you just set the cropping bounds and the model only looks in that area of the video. Ideally all your videos are the same size for ease, but otherwise you can just loop over writing the config cropping coordinates per video:

defaults:
```python
    cfg_file["cropping"] = False
    cfg_file["x1"] = 0
    cfg_file["x2"] = 640
    cfg_file["y1"] = 277
    cfg_file["y2"] = 624


edits = { 'cropping': True, x1: 500, etc ... 
}
deeplabcut.auxiliaryfunctions.edit_config(config_path, edits)
```

**Comment by ludovicbellier** [comment]
Thanks @MMathisLab for your prompt reply!

> You need to set `num_outputs` > 1 if you just want to get the points across animals, otherwise indeed it only takes the top-one hit.

Fantastic, I'll go ahead and try that, thank you!

> Actually this exists :) you just set the cropping bounds and the model only looks in that area of the video. Ideally all your videos are the same size for ease, but otherwise you can just loop over writing the config cropping coordinates per video

Oh I should have been clearer about describing my intended mask, sorry about that: the FOV area I want the model to ignore is not rectangular (it's an ellipse), nor is it occupying an entire edge (it's close to the corner of the arena, but the animal of interest can still go around). So a more sophisticated cropping would work (basically, the negative of my intended mask), but I don't think the current rectangular implementation would.

**Comment by jeylau** [comment]
Hi @ludovicbellier, how did you end up implementing your solution? One way that came to my mind is akin to how `napari` defines shapes for their Shape layer: `cropping` could be defined by some coordinates and a shape type; e.g., `(x1, y1, x2, y2), shape_type: "rectangle"`, or `(center, major_axis, minor_axis, angle), shape_type: "ellipse"). This would be backward compatible, the default being `.get(shape_type, "rectangle")` and expecting the traditional list of 4 corners, while allowing to flexibly define other shapes.

**Comment by ludovicbellier** [comment]
Hi @jeylau, thanks a lot for your reply, and sorry for my delayed response!

I started by interactively finding the ellipse parameters (x_center, y_center, width, height, angle) that best fitted the area to mask, then by plotting this ellipse in black on all frames, resulting in a masked video that I used as input of DLC. Then I improved the tedious manual first step by implementing an automatic fit based on OpenCV's Canny edge detection, findContours and fitEllipse; but in the end, to stay on topic here, I still create a new video.

Defining shapes by shape type and relevant coordinates sounds like a great idea! Using napari or cv2 would work fine, and indeed allow backward compatibility. However in my use case, I would need to do a negative cropping (i.e., keep everything _but_ the ellipse), so it would mean adding an argument to define whether we want a positive/regular or negative cropping, and it would be complicated to add multiple masks (e.g., two ellipses). Instead, do you think adding a `masking` option in config.yaml all while ensuring backward compatibility (e.g., nothing breaks if `masking` isn't provided) could work? With this strategy we could add several shapes.

Thanks a lot for looking into this, and I'll make sure to reply faster next time =)
Best,
Ludovic

**Comment by jeylau** [comment]
No worries at all! Thanks a lot for sharing. I guess we could just add yet another key to the `crop` dictionary that specifies whether we want the mask or its inverse (e.g., `inv: True`). If you feel like implementing and contributing this feature, let me know, I could provide you with some guidance 😊

**Comment by ludovicbellier** [comment]
Got it, thanks @jeylau! With this `crop` strategy, would I still be able to crop my videos though?
In my use case, I need to crop the video, and mask an elliptic area. I guess we could have a list of cropping shapes, like:
`crop: [[120, 1120, 40, 1040, 'rectangle', 'keep'], [280, 300, 80, 60, 45, 'ellipse', 'mask']]` and make it so that `crop: 120, 1120, 40, 1040` is interpreted as `[120, 1120, 40, 1040, 'rectangle', 'keep']` to make it backward compatible.

Using another `masking:` option in config.yaml would replace the need of `'keep'/'mask'` (or `inv: True/False`), and thus won't change the `crop:` option (so it's more like adding a new feature than extending an existing one). What option do you prefer?

Regardless of the option chosen I'll be happy to implement and contribute it!
