### ISSUE TITLE
IndexError running "Step1_EvaluateModelonDataset.py" (Installation specific python3 vs python call)

### ISSUE THREAD

**Issue by sot-iris** [DeepLabCut/DeepLabCut#21]
Hello,
When trying to run above script (Step1_EvaluateModelonDataset.py), having "Ctrl + C" from the ../../../train.py script after x iterations, I run into the following error:

Traceback (most recent call last):
  File "Step1_EvaluateModelonDataset.py", line 72, in <module>
    cfg['init_weights'] = os.path.join(modelfolder,'train',Snapshots[snapIndex])
IndexError: index -1 is out of bounds for axis 0 with size 0

I have reproduced this on both Ubuntu 16.04 LTS and Windows 10 - any ideas?
Thank you!
Sotiris

**Comment by sot-iris** [comment]
correction: the above is an Ubuntu issue, when I try running the above script on windows 10 I get: 
FileNotFoundError: [WinError 2] The system cannot find the file specified

Sorry about this, guys!

**Comment by sot-iris** [comment]
rectified, on windows 10, by changing python3 --> python

subprocess.call(['python3','EvaluateNetwork.py',str(snapIndex),str(shuffleIndex),str(trainFractionIndex)])

**Comment by cathy-liu23** [comment]
I'm having the same issue on Ubuntu 16.04 LTS. Did you find a solution to this issue?
I changed 'python3' to 'python' (in hope that it would also solve the issue on Ubuntu), but it didn't work for me.

**Comment by MMathisLab** [comment]
Could also be related issue #26 - i.e. just no snapshots found (just for future users checking issues :)

**Comment by AlexEMG** [comment]
We did solve this problem in the latest push. Indeed if your python3 is installed such that you call it by "python" then the previous script did not call the analysis script correctly. We have now fixed this.
