### ISSUE TITLE
Unable to evaluate network  or analyze new videos (HDFStore requires PyTables)

### ISSUE THREAD

**Issue by lilyanax** [DeepLabCut/DeepLabCut#210]
I am using Windows 10 with an Anaconda Env and  DeepLabCut version 2.0

I have successfully trained the network but have been unable to utilize the deeplabcut.evaluate_network or deeplabcut.analyze_videos function due to an error with PyTables

**How to Reproduce the problem**
1. deeplabcut.evaluate_network(path_config_file,Shuffles=1, plotting=True)
ImportError: HDFStore requires PyTables, "DLL load failed: The specified procedure could not be found." problem importing

2.deeplabcut.analyze_videos(path_config_file,['\\?\C:/Users/PfeifferLab/Documents/DeepLabCut-master/DeepLabCut-master/KcConditional-HCandSI-DC-Lilyana-2019-02-11/videos/DC7.mp4'],shuffle=1, trainingsetindex=0, save_as_csv=True)

Using snapshot-200000 for model C:\Users\PfeifferLab\Documents\DeepLabCut-master\DeepLabCut-master\KcConditional-HCandSI-DC-Lilyana-2019-02-11\dlc-models\iteration-0\KcConditional-HCandSI-DCFeb11-trainset95shuffle1
INFO:tensorflow:Restoring parameters from C:\Users\PfeifferLab\Documents\DeepLabCut-master\DeepLabCut-master\KcConditional-HCandSI-DC-Lilyana-2019-02-11\dlc-models\iteration-0\KcConditional-HCandSI-DCFeb11-trainset95shuffle1\train\snapshot-200000
INFO:tensorflow:Restoring parameters from C:\Users\PfeifferLab\Documents\DeepLabCut-master\DeepLabCut-master\KcConditional-HCandSI-DC-Lilyana-2019-02-11\dlc-models\iteration-0\KcConditional-HCandSI-DCFeb11-trainset95shuffle1\train\snapshot-200000
The videos are analyzed. Now your research can truly start! 
 You can create labeled videos with 'create_labeled_video'.
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract any outlier frames!

Although the data was generated initially for the 3 videos I used for training, every time I try this for new videos, no analysis is generated. When modifying  the video location sometimes it will go through the analysis but at the end when it goes to save the file it outputs "ImportError: HDFStore requires PyTables"(see below)

deeplabcut.analyze_videos(path_config_file, [r'D:\\Lilyana\videos\DC7.mp4'], shuffle=1, trainingsetindex=0,videotype='.mp4')
Using snapshot-200000 for model C:\Users\PfeifferLab\Documents\DeepLabCut-master\DeepLabCut-master\KcConditional-HCandSI-DC-Lilyana-2019-02-11\dlc-models\iteration-0\KcConditional-HCandSI-DCFeb11-trainset95shuffle1
INFO:tensorflow:Restoring parameters from C:\Users\PfeifferLab\Documents\DeepLabCut-master\DeepLabCut-master\KcConditional-HCandSI-DC-Lilyana-2019-02-11\dlc-models\iteration-0\KcConditional-HCandSI-DCFeb11-trainset95shuffle1\train\snapshot-200000
INFO:tensorflow:Restoring parameters from C:\Users\PfeifferLab\Documents\DeepLabCut-master\DeepLabCut-master\KcConditional-HCandSI-DC-Lilyana-2019-02-11\dlc-models\iteration-0\KcConditional-HCandSI-DCFeb11-trainset95shuffle1\train\snapshot-200000
Starting to analyze %  D:\\Lilyana\videos\DC7.mp4
Loading  D:\\Lilyana\videos\DC7.mp4
Duration of video [s]:  10805.0 , recorded with  25.0 fps!
Overall # of frames:  270125  found with (before cropping) frame dimensions:  720 480
Starting to extract posture
Cropping based on the x1 = 40 x2 = 560 y1 = 120 y2 = 480. You can adjust the cropping coordinates in the config.yaml file.
272801it [1:21:46, 55.03it/s]                            Detected frames:  270125

Saving results in D:\Lilyana\videos...
Traceback (most recent call last):

  File "<ipython-input-6-36a613a58c70>", line 1, in <module>
    deeplabcut.analyze_videos(path_config_file, [r'D:\\Lilyana\videos\DC7.mp4'], shuffle=1, trainingsetindex=0,videotype='.mp4')

  File "C:\Users\PfeifferLab\Anaconda3\envs\deeplabEnv\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 153, in analyze_videos
    AnalyzeVideo(video,DLCscorer,trainFraction,cfg,dlc_cfg,sess,inputs, outputs,pdindex,save_as_csv, destfolder)

  File "C:\Users\PfeifferLab\Anaconda3\envs\deeplabEnv\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 310, in AnalyzeVideo
    auxiliaryfunctions.SaveData(PredicteData[:nframes,:], metadata, dataname, pdindex, range(nframes),save_as_csv)

  File "C:\Users\PfeifferLab\Anaconda3\envs\deeplabEnv\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 150, in SaveData
    DataMachine.to_hdf(dataname, 'df_with_missing', format='table', mode='w')

  File "C:\Users\PfeifferLab\Anaconda3\envs\deeplabEnv\lib\site-packages\pandas\core\generic.py", line 1471, in to_hdf
    return pytables.to_hdf(path_or_buf, key, self, **kwargs)

  File "C:\Users\PfeifferLab\Anaconda3\envs\deeplabEnv\lib\site-packages\pandas\io\pytables.py", line 280, in to_hdf
    complib=complib) as store:

  File "C:\Users\PfeifferLab\Anaconda3\envs\deeplabEnv\lib\site-packages\pandas\io\pytables.py", line 448, in __init__
    'importing'.format(ex=str(ex)))

ImportError: HDFStore requires PyTables, "DLL load failed: The specified procedure could not be found." problem importing

After looking at other issues posted here I tried reinstalling Pytables and changing the version but I am still getting the error.

**Comment by MMathisLab** [comment]
*please also post the version of DLC (i.e. 2.0.4.1 is the latest)

I would use the supplied conda environment. Using this no one has had this issue that we know if.

Here is one solution: 
https://github.com/AlexEMG/DeepLabCut/issues/108

**Comment by lilyanax** [comment]
Using DLC 2.0.4.1

**Comment by lilyanax** [comment]
I have tried the above solution but it still doesn't work, I will try using the supplied conda environment.

**Comment by MMathisLab** [comment]
@lilyanax - okay great; hopefully that solves it! let me know so I can close the issue ;)

**Comment by lilyanax** [comment]
I reinstalled using the supplied conda environment but still receive the same error when analyzing videos.
"ImportError: HDFStore requires PyTables, "DLL load failed: The specified procedure could not be found." problem importing"
