### ISSUE TITLE
Requesting safer import of `tensorflow`

### ISSUE THREAD

**Issue by CodyCBakerPhD** [DeepLabCut/DeepLabCut#2104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Partially related to https://github.com/DeepLabCut/DeepLabCut/issues/2102 but this would be present on all OS

Also somewhat related to https://github.com/DeepLabCut/DLC2NWB/issues/17, where a safe upstream import attempt is used (which resolves the issue)

Latest release of `deeplabcut` removes `tensorflow` as a minimal dependency: https://github.com/DeepLabCut/DeepLabCut/blob/main/setup.py#L58

yet the outer import of the package attempts to import it as if it were a non-optional requirement: https://github.com/DeepLabCut/DeepLabCut/blob/main/deeplabcut/__init__.py#L16

### Operating System

Linux, Windows, MacOS

### DeepLabCut version

2.3.0

### DeepLabCut mode

single animal

### Device type

N/A - just importing package

### Steps To Reproduce

conda create -n test_dlc_import python={3.7-3.10}
conda activate test_dlc_import
pip install deeplabcut
python -c "import deeplabcut"

### Relevant log output

```shell
Caught in downstream CI: https://github.com/catalystneuro/neuroconv/actions/runs/3769847940/jobs/6409325021
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by CodyCBakerPhD** [comment]
Minimal suggested solution: if `tensorflow` is truly optional now, wrap https://github.com/DeepLabCut/DeepLabCut/blob/main/deeplabcut/__init__.py#L16 and associated lines in a `try/except` block for a simple 'lazy import' like in https://github.com/DeepLabCut/DLC2NWB/blob/main/dlc2nwb/utils.py#L17

**Comment by MMathisLab** [comment]
Hi @CodyCBakerPhD it's not an optional import, but the version is now important due to changes in TF for operating systems; namely, they stop supporting windows natively after 2.10; thus, we are using it as a flag now, and in 2023 we will drop TF in favor of pytorch.

edit to add: we did update our docs to be clear that using DLC requires TF (and torch since 2.2), thus the bare-minimum pip install is `deeplabcut[tf]`; we are sorry this is backwards breaking and should have put a depreciation warning on it... apologies for that!

**Comment by CodyCBakerPhD** [comment]
@MMathisLab No worries - I can definitely appreciate the difficulty of dealing with that complication... we're currently trying to extend support of [NeuroConv](https://github.com/catalystneuro/neuroconv) to Python 3.11 and this is coming up again there as well

My main request now is actually on the sister project dlc2nwb. I'd appreciate one of two pathways

(a) https://github.com/DeepLabCut/DLC2NWB/issues/17 requesting fresh release of dlc2nwb that includes the safer requirement/import of deeplabcut currently on that main dev branch

or, preferably

(b) I've also suggested an ever safer way to retrieve the upstream version, when installed, without triggering an import at all: https://github.com/DeepLabCut/DLC2NWB/pull/18 (would need to be accepted and also released)

**Comment by jeylau** [comment]
Hi @CodyCBakerPhD, I'll check the PRs @DLC2NWB and give you some feedback by tomorrow!

**Comment by CodyCBakerPhD** [comment]
Thanks all
