### ISSUE TITLE
Manual extraction from previously analyzed videos broken

### ISSUE THREAD

**Issue by hummuscience** [DeepLabCut/DeepLabCut#2107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Upgraded to the most recent DLC release (2.3) and tried to recreate what I used to do in previous versions.

1) Analyze video
2) Open GUI and click on extract outlier frames, choose video and choose "manual" as option
3) Click on "Extract frames":
- Expected: Frame extraction GUI opens up with the video, a slider, and the points overlayed on top
- Reality: A warning (see below) and an empty napari window
`WARNING: QStatusBar::insertPermanentWidget: Index out of range (0), appending widget`
-> Decided to load the video and .h5 file of the analysis instead.
4) Video and points are overlayed.
-> realized that the points and video are one frame off (I have a flash in the video where no points are detected, which is the correct behavior and in the opened video the "lack of detections" was constantly one frame off).
5) Go to chosen frames and click "extract frame"
- Expectation: Images are stored in labelled_data along with a machine-labels file
- Reality: only extracted images without machine-labels stored in labelled_data
- > This requires me to manually label the 50 manually extracted images. Normally no problem, but this model has 60 points to track (expanded monkey face from the Model Zoo). And I guess this is also not the intended behavior.

### Operating System

macOS Monterey

### DeepLabCut version

2.3

### DeepLabCut mode

single animal

### Device type

gpu

### Anything else?

It is possible that this has something to do with the project being created with an older version of DLC (should be around May 2022). 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
hi @Cumol unfortunately not all functions in the brand new GUI are backwards compatible; we had a 4 month beta release to catch such things, but alas it will take take, given it;s a few new re-write of the code. We will put in the que, but in the meantime you might consider staying with the last pre-pyside GUI release for older projects.

**Comment by hummuscience** [comment]
Thanks for the response. I assume 2.2.3 is the last stable release before the napari GUI? (https://github.com/DeepLabCut/DeepLabCut/releases/tag/v2.2.3)

**Comment by jeylau** [comment]
@Cumol, I've fixed the 2 bugs you described at https://github.com/DeepLabCut/napari-deeplabcut. If you `pip install git+https://github.com/DeepLabCut/napari-deeplabcut.git` to get the latest GUI code, outlier frame extraction should now work as expected.

**Comment by hummuscience** [comment]
Thanks for updating it. I tried to repeat the process with the following errors:
1) In the refine outliers tab, I chose a video, choose "manual" as method, and clicked on "extract frames"
Expected: GUI opens with chosen video and .h5 file ready for manual extraction
What happened: Empty napari GUI opened (so it has to be done manually in this case, no big issue).

2) I tried to use the open-file dialogue and got the following error. This could be due to the project being an older one. I wonder if this a backward compatibility issue but solvable by using this: https://deeplabcut.github.io/DeepLabCut/docs/convert_maDLC.html
```
Traceback (most recent call last):
  File "/Users/abdelhaym/.conda/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/napari/_qt/qt_viewer.py", line 735, in _open_files_dialog
    filenames, _ = dlg.getOpenFileNames(
AttributeError: PySide6.QtWidgets.QFileDialog.getOpenFileNames(): unsupported keyword 'directory'
```
3) Loading in the video and the .h5 file manually works fine without errors!
Note: maybe a general note. Extracting frames from large videos manually is quite sluggish (talking about 1hour videos with 60fps). I realized this might be a general problem with how Napari handles large videos. I just know the opening the same video with Fiji/ImageJ using "Virtual stacks" leads to quite easy and fast scrolling through the video (https://imagej.nih.gov/ij/docs/guide/146-8.html)

**Comment by jeylau** [comment]
Thanks for the feedback @Cumol! The window will open with the video and the annotations after #2114 is merged in. The AttributeError is a bug from napari caused by PySide6; I suppose it will be fixed with their next release. I'd recommend loading files by dropping them onto the canvas though. Virtual stacks look interesting, I'll look at it closely, thanks for the pointer ☺️
