### ISSUE TITLE
About the SuperAnimal-Quadruped

### ISSUE THREAD

**Issue by Kazusaisjustice** [DeepLabCut/DeepLabCut#2108]
Excuse me, I expect to use a dog pretrained model first, but in your ModelZoo, you mentioned user should use the SuperAnimal-Quadruped model instead. Exactly, I have no idea on how to use this new model. Can you give me a direction? Or is there any direction written somewhere? Thank you very much!

**Comment by MMathisLab** [comment]
hi @Kazusaisjustice -- firstly just want to say that nothing in this code base is guaranteed and esp the model zoo is not stable yet, so just be aware :); the dog and cat model were depreciated in Nov 2022, and the new models are just up! 

You can see one way to use the `superanimal_quadruped` model in the colab notebook: https://colab.research.google.com/github/DeepLabCut/DeepLabCut/blob/master/examples/COLAB/COLAB_DLC_ModelZoo.ipynb

![Screen Shot 2023-01-08 at 1 17 30 PM](https://user-images.githubusercontent.com/28102185/211195660-c5be316c-b9c0-4899-baa9-5ff154135e14.png)


To note, there are two ways to use the models now; one is in an open PR but not yet merged (docs note this will be in 2.3+). Docs: https://deeplabcut.github.io/DeepLabCut/docs/ModelZoo.html

main page: http://www.mackenziemathislab.org/dlc-modelzoo/

and if you use the models, please cite Ye et al. 2022, thanks! Happy hacking.

**Comment by Kazusaisjustice** [comment]
Thank for your guidance！I have tried this model successfully under your help! In addition, I expect to train my own labeled videos dataset based on this pretrained model. Is it possible? Waiting for your reply, thanks!

**Comment by MMathisLab** [comment]
hi @Kazusaisjustice it's not possible to train with your own data; we encourage others to share data (can be confidentially) to make the model better for everyone :D

**Comment by Kazusaisjustice** [comment]
Well, I got it. Thanks for your reply!
