### ISSUE TITLE
Need video stream support

### ISSUE THREAD

**Issue by SUGE2016** [DeepLabCut/DeepLabCut#211]
Is it possible to support real-time detection of video streams? If we add such support, what changes need to be made? Thank you!

**Comment by AlexEMG** [comment]
DeepLabCut is pretty fast - see [On the inference speed and video-compression robustness of DeepLabCut](https://www.biorxiv.org/content/early/2018/10/30/457242.full.pdf). Thus, for reasonable frame rates real-time detection is supported. All you need to do is just directly pass the frames to DLC.

**Comment by SUGE2016** [comment]
@AlexEMG ,thanks, We are trying, and will comment results here

**Comment by MMathisLab** [comment]
@SUGE2016 - geat, I will close for now, but please feel free to comment, etc.
