### ISSUE TITLE
GPU seems not to be well used in video analyzing

### ISSUE THREAD

**Issue by AthiemoneZero** [DeepLabCut/DeepLabCut#2111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I used deeplabcut-gui to analyze my video, and it is very nice.
But I find it is really slow to analyze and create video although I used GPU.

Most recently call back in analyzing video:

Loading DLC 2.3.0...
Starting GUI...
Traceback (most recent call last):
  File "C:\Users\dell\anaconda3\envs\DLC\lib\site-packages\deeplabcut\gui\tabs\analyze_vid
eos.py", line 344, in analyze_videos
    self.logger.debug(f"Selected body parts for plot_trajectories: {bdpts}")
AttributeError: 'AnalyzeVideos' object has no attribute 'logger'. Did you mean: 'lower'?  
C:\Users\dell\anaconda3\envs\DLC\lib\site-packages\tensorflow\python\keras\engine\base_lay
er_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future ve
rsion. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
2023-01-04 17:41:54.555600: I tensorflow/core/platform/cpu_feature_guard.cc:193] This Tens
orFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the fol
lowing CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags
.
2023-01-04 17:41:55.088937: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Creat
ed device /job:localhost/replica:0/task:0/device:GPU:0 with 13611 MB memory:  -> device: 0
, name: NVIDIA RTX A4000, pci bus id: 0000:65:00.0, compute capability: 8.6
2023-01-04 17:41:55.130727: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354
] MLIR V1 optimization pass is not enabled
  0%|                                                          | 0/52798 [00:00<?, ?it/s]2
023-01-04 17:41:57.850565: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN
 version 8100
2023-01-04 17:41:59.629295: I tensorflow/stream_executor/cuda/cuda_blas.cc:1614] TensorFlo
at-32 will be used for the matrix multiplication. This will only be logged once.
 73%|█████████████████████████████████▋            | 38624/52798 [45:52<17:00, 13.88it/s]

### Operating System

windows 10

### DeepLabCut version

deeplabcut                    2.3.0   
tensorflow                    2.10.0
tensorflow-estimator          2.10.0
tensorflow-gpu                2.10.1
tensorflow-io-gcs-filesystem  0.29.0
tensorpack                    0.11

### DeepLabCut mode

single animal

### Device type

NVIDA A4000

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by KonradDanielewski** [comment]
Depends on the resolution of your video. A4000 is basically a 3070 with more memory, it's not that fast (actually it's a little slower even cause it doesn't clock as high)

**Comment by MMathisLab** [comment]
seems it's also not fully utilizing using your GPU; did you check this in the docs? https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html#how-to-confirm-that-your-gpu-is-being-used-by-deeplabcut

```
2023-01-04 17:41:54.555600: I tensorflow/core/platform/cpu_feature_guard.cc:193] This Tens
orFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the fol
lowing CPU instructions in performance-critical operations: AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags
.
```
