### ISSUE TITLE
"The videos are analyzed." even though they are not.

### ISSUE THREAD

**Issue by hummuscience** [DeepLabCut/DeepLabCut#2117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

(I believe this has been a longer standing bug, I just didn't figure out what is causing it)

In my pipeline, I am analyzing two different videos (`video1 `and `video2 `from the same experimental session with two different models (`model1 `and `model2`) but outputting the results into the same folder (`folderX`).

For that I am using the `destfolder=` option in `analyze_videos`. These analyses sometimes run in parallel or in series (with different sbatch jobs). When they run **in series**, `video1 `is analyzed and results are placed into `folderX`. Then DLC tries to analyze `video2` and looks first into `folderX` (which is `destfolder`) and sees some `*.pickle` and `*.h5` files (from `video1`, which has a different name and is analyzed with a `model1`) and **declares that `video2` is already analyzed.**

### Operating System

Linux RedHat. Running over slurm on RTX A6000

### DeepLabCut version

2.2.1

### DeepLabCut mode

single animal

### Device type

gpu RTX A6000

### Steps To Reproduce

Here is an example of such a folder where it fails and the output of running `video2` with `model2`.

`video1`: cam35_2023-01-06-13-24-16.avi
`video2`: cam34_2023-01-06-13-24-16.avi
`model1`: DLC_resnet50_monkey-faceMay2shuffle1_1425000
`model2`: DLC_resnet50_monkey-handMay10shuffle1_1000000

```shell
├── cam34_2023-01-06-13-24-16.avi
├── cam35_2023-01-06-13-24-16.avi
├── test_recordings-Cosmos-20230106-LeafForaging-001.dlc
│   ├── cam35_2023-01-06-13-24-16DLC_resnet50_monkey-faceMay2shuffle1_1425000.csv
│   ├── cam35_2023-01-06-13-24-16DLC_resnet50_monkey-faceMay2shuffle1_1425000.h5
│   ├── cam35_2023-01-06-13-24-16DLC_resnet50_monkey-faceMay2shuffle1_1425000_labeled.mp4
│   ├── cam35_2023-01-06-13-24-16DLC_resnet50_monkey-faceMay2shuffle1_1425000_meta.pickl
```

### Relevant log output

When I run the analysis of `video2` with `model2` I get the following output

```python
Using snapshot-1000000 for model /mnt/hpc_slurm/departmentN5/dlc-models/monkey-hand-ZeroNoiseLab-2022-05-10/dlc-models/iteration-1/monkey-handMay10-trainset95shuffle1
Starting to analyze %  /mnt/hpc_slurm//projects/MWzeronoise/test_recordings/Cosmos/20230106/LeafForaging/001/cam34_2023-01-06-13-24-16.avi
Loading  /mnt/hpc_slurm//projects/MWzeronoise/test_recordings/Cosmos/20230106/LeafForaging/001/cam34_2023-01-06-13-24-16.avi
The videos are analyzed. Now your research can truly start! 
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by hummuscience** [comment]
Closing this temporarily since it might be an error with a corrupt (or empty) video file.

**Comment by hummuscience** [comment]
This turned out to be an issue with a video file being empty (file created but not copied). 

I am not sure if it is worth it to add some  `path.stat().st_size == 0` and `path.exists()` from `pathlib` as a check before to catch that type of error since I could image that others are copying videos around (in our case from a tape file system archive to a computing node).

@jeylau

**Comment by rahim-hashim** [comment]
Following up here, were you using the full macaque model to capture key points for your labeled monkey-hand videos? If so, how well did the model perform on your dataset?

**Comment by hummuscience** [comment]
@rahim-hashim no, I am capturing hand and face videos and analyzing both. Trained my own hands model. I don't know how well it will work for you (I could imagine that it will perform poorly in another condition), but if you are interested, I could share it

**Comment by rahim-hashim** [comment]
That would be great, I'd love to try it out and see how well it generalizes to new monkeys/video acquisitions. Feel free to message me privately!
