### ISSUE TITLE
deeplabcut.label_frames: labels from last frame remain in the GUI when loading a frames from a new folder

### ISSUE THREAD

**Issue by WernTanj** [DeepLabCut/DeepLabCut#212]
Centos 7.6, DLC 2.0.4.1

1) Save labels from first frame folder
2) Select new folder with frames to label
3) The previous GUI with the labels of the last frame remains and the new GUI with the new frame to label is overlaid - see screenshot

![screenshot_20190215_135324](https://user-images.githubusercontent.com/44802531/52858290-00018d80-312a-11e9-88f2-95ac1f7a105f.png)

4) Closing the GUI entirely and run `deeplabcut.label_frames` again refreshes the GUI

**Comment by ghost** [comment]
going back and forth with previous and next without closing also refreshes the GUI

**Comment by MMathisLab** [comment]
Thanks for pointing it out! Will be fixed in next release; see @juplabs suggestion in the meantime :)

**Comment by AlexEMG** [comment]
Fixed in DLC 2.0.5.
