### ISSUE TITLE
Combination of quick and loop in GUI

### ISSUE THREAD

**Issue by hummuscience** [DeepLabCut/DeepLabCut#2121]
**Is your feature request related to a problem? Please describe.**
I often want to re-label a certain bodypart (where I have noticed that the model is creating "jitters" because of imprecise labelling). I thought an easy way to do this is to use the "quick" option in the labelling and then go through the the images with the arrows. But "quick" currently automatically jumps to the next bodypart after clicking (as described) and often restarts from the top of the list of bodyparts (even though the limb I want to label is chosen from the dropdown). The latter is a general issue (and maybe should be a bugreport) since there are often bodyparts that are not visible in the current image that is labelled. 

**Describe the solution you'd like**
Combine the "quick" option and the "loop" option. 

1) Choose limb from drop-down menu
2) Clicking on a position in the image places a new point at the position (and removes the previous point).

**Describe alternatives you've considered**
Having a complete "manual"/"single" mode. Choose a limb from the dropdown and then just move images using the arrows, *not* changing the bodypart chosen.

**Comment by MMathisLab** [comment]
thanks! can we move this to the deeplabcut-napari gui repo? https://github.com/DeepLabCut/napari-deeplabcut

**Comment by jeylau** [comment]
Hi @Cumol, I've just added this functionality to the plugin with https://github.com/DeepLabCut/napari-deeplabcut/pull/53!
