### ISSUE TITLE
Cant add a new body part after training

### ISSUE THREAD

**Issue by OmerBarkai** [DeepLabCut/DeepLabCut#2125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

After labeling and training I decided to add another body part label to my analysis. 

According to the Neth et al. 2019 paper - 
"Occasionally, the user might want to label additional body parts. In such a case, the user needs to append the new labels to the bodyparts list in the config.yaml file. Thereafter, the user can call the function label_frames and will be asked if he or she wants to display only the new labels or all labels before loading the frames. Saving the labels after all the images are labeled will append the new labels to the existing labeled dataset."

I added the newly desired body part to the config.yaml file. However, when pressing 'Label frames' in the Label frames tab napari opens but  I am never asked if I want to display only the new or all the labels. The new body part does not appear in the key point selection list. 

Maybe I am missing something in the process? any other way to add a new body part label to my videos?  

### Operating System

Windows

### DeepLabCut version

DLC 2.3

### DeepLabCut mode

single animal

### Device type

GPU

### Anything else?

Really enjoying working with DLC! Thank you so much for the support! 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Thanks @OmerBarkai for reporting this bug; I'm looking at it. What I see is that we infer the list of body parts from the header of the h5 data file (which is independent of the config.yaml, hence why added/deleted body parts are not reflected). I'll push a fix soon!

**Comment by OmerBarkai** [comment]
Great! Thank you so much for taking care of this and your friendly support!

Omer

**Comment by msarvestani** [comment]
Hi all. I'm still experiencing this issue (have updated DLC and widget.py etc reflect this update). The new body parts are in the config file, which I load using the GUI. The new labels show up under bodyparts when I load the config file via the GUI. But they are not reflected in the dropdown menu in the Napari labeling GUI when I try to label frames.

DLC GUI 2.3.5, Windows10, Single animal DLC, GPU

**Comment by kwhitlow92** [comment]
My group is also experiencing this issue with DLC on windows 10, single animal on a CPU run through the GUI

**Comment by katjaReinhard** [comment]
Hi, I'm also experiencing the same problem on Ubuntu and recently installed DLC. Are there any solutions? I've tried adding the new labels directly to the h5 file but couldn't figure out how to do that for a string array. would appreciate any (workaround) solution before relabeling 100s of frames!

**Comment by ghost** [comment]
Hello, I am also experiencing the same issue with the gui. The only work around was to use DLC directly through the terminal, then the new labels come up but it is inefficient and does not allow to open another folder. My new issue is that I trained the network on a new video with the new labels, but it did not include the previous labels and only labeled the new ones. Can someone help me with this please?

**Comment by bainro** [comment]
I am still experiencing the problem too :( windows 10 python 3.10

**Comment by katjaReinhard** [comment]
I found a way around it that works for me, although I still hope it'll be solved soon so I don't need to do this little hack:

1. load your project as always
2. go to label frames and select your video to open napari
3. sometimes even step 2 doesn't work for me (it opens napari, but without the video) -> open folder -> select your "labeled-data" folder of interest
4. now what seems to happen is that even though you started DLC with the correct config file, it reads the body parts saved in the h5 file in your labeled-data folder -> drag the correct config.yaml file onto napari -> a pop up appears where you can choose whether to show all or only new labels -> happy labeling

The annoying thing is that you need to close all files in napari before loading the next folder (at least for me it seems necessary) and drag again the correct config.yaml file for each video folder. sometimes I need to reload napari. but it does work, it saves the new bodyparts correctly and it allows you to use the GUI.

Edit: this is on linux, there seems to be some issues when trying this on windows.

**Comment by tom221085** [comment]
Apparently, this only works if you don't run dlc as administrator.

**Comment by X4ndri** [comment]
thanks @katjaReinhard your solution helped. If for some reason that doesn't work for those on windows, I was doing a different workaround, where I would open the labelled .csv file, add three columns associated with new new body part (x, y, likelihood), save, then run the dlc [`convertcsv2h5`](https://github.com/DeepLabCut/DeepLabCut/blob/main/deeplabcut/utils/conversioncode.py#L30C5-L30C18) function to generate a .h5 labelled dataset from the newly edited csv file. But this will need to be done to each previously labelled dataset.

**Comment by mikeumo** [comment]
Not sure if the issue is resolved but I am getting the same error (the new body parts do not show up for addition) in DLC3.0.0rc8 in Windows and Mac. Solution in Windows and Mac: After opening the Napari window through Label Frames command in DLC, open the desired folder with partially labelled frames, then re-read the config.yaml through Napari's OWN File>Open File command (Ctrl-/ Command-O). Say Yes/No in the dialog. The new body parts should now show up in Keypoint selection drop-down list  and color scheme and can be added to the frames. Don't forget to highlight the CollectedData layer. 

Mike
