### ISSUE TITLE
'EasyDict' object has no attribute 'project_path'

### ISSUE THREAD

**Issue by byronrogers73** [DeepLabCut/DeepLabCut#213]
**Your Operating system and DeepLabCut version**

DLC = 2.0.4.1
Using GoogleColab

**Describe the problem**

When running training model - deeplabcut.train_network(path_config_file, shuffle=1, displayiters=50,saveiters=250)

Error below....

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-18-b91fd233f3b9> in <module>()
      1 
----> 2 deeplabcut.train_network(path_config_file, shuffle=1, displayiters=50,saveiters=250)
      3 
      4 #this will run until you stop it (CTRL+C), or hit "STOP" icon, or when it hits the end (default, 1.03M iterations).
      5 #Whichever you chose, you will see what looks like an error message, but it's not an error - don't worry....

/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/training.py in train_network(config, shuffle, trainingsetindex, gputouse, max_snapshots_to_keep, autotune, displayiters, saveiters, maxiters)
     79           train(str(poseconfigfile),displayiters,saveiters,maxiters,max_to_keep=max_snapshots_to_keep) #pass on path and file name for pose_cfg.yaml!
     80       except BaseException as e:
---> 81           raise e
     82       finally:
     83           os.chdir(str(start_path))

/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/training.py in train_network(config, shuffle, trainingsetindex, gputouse, max_snapshots_to_keep, autotune, displayiters, saveiters, maxiters)
     77         os.environ['CUDA_VISIBLE_DEVICES'] = str(gputouse)
     78       try:
---> 79           train(str(poseconfigfile),displayiters,saveiters,maxiters,max_to_keep=max_snapshots_to_keep) #pass on path and file name for pose_cfg.yaml!
     80       except BaseException as e:
     81           raise e

/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/train.py in train(config_yaml, displayiters, saveiters, maxiters, max_to_keep)
     84     cfg['batch_size']=1 #in case this was edited for analysis.
     85 
---> 86     dataset = create_dataset(cfg)
     87     batch_spec = get_batch_spec(cfg)
     88     batch, enqueue_op, placeholders = setup_preloading(batch_spec)

/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/dataset/factory.py in create(cfg)
      7 
      8 def create(cfg):
----> 9     data = PoseDataset(cfg)
     10     return data

/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/dataset/pose_dataset.py in __init__(self, cfg)
     69     def __init__(self, cfg):
     70         self.cfg = cfg
---> 71         self.data = self.load_dataset()
     72         self.num_images = len(self.data)
     73         if self.cfg.mirror:

/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/dataset/pose_dataset.py in load_dataset(self)
     78     def load_dataset(self):
     79         cfg = self.cfg
---> 80         file_name = os.path.join(self.cfg.project_path,cfg.dataset)
     81         # Load Matlab file dataset annotation
     82         mlab = sio.loadmat(file_name)

AttributeError: 'EasyDict' object has no attribute 'project_path'

**Comment by MMathisLab** [comment]
I can try later too, but can you try to add this to the notebook, after you install dlc (ie you can place in the same cell where Pillow is re-installed) “pip install easydict==1.7” 

And/or double check you changed the `project_path` in your config.yaml file to be on you google drive dlc project path!

**Comment by byronrogers73** [comment]
Requirement already satisfied: Pillow==4.0.0 in /usr/local/lib/python3.6/dist-packages (4.0.0)
Requirement already satisfied: olefile in /usr/local/lib/python3.6/dist-packages (from Pillow==4.0.0) (0.46)
Requirement already satisfied: easydict==1.7 in /usr/local/lib/python3.6/dist-packages (1.7)

Still get the same error....

**Comment by MMathisLab** [comment]
Okay just got to my computer, and the version that is in the current repo everything works for me. Open from here:

![image](https://user-images.githubusercontent.com/28102185/52919477-e189c680-32d0-11e9-89a2-07801698012c.png)


https://github.com/AlexEMG/DeepLabCut/tree/master/examples#demo-2-set-up-deeplabcut-on-your-own-data

![image](https://user-images.githubusercontent.com/28102185/52919512-2281db00-32d1-11e9-8bc8-c46fc3e16bf6.png)

**Comment by MMathisLab** [comment]
Be sure your project path is correct!

```
     # Project path (change when moving around)
      project_path: /content/drive/My Drive/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30``
```

**Comment by byronrogers73** [comment]
It was correct. It was an error in the pose_cfg.yaml file in the DLC-models subdirectory. It had an incorrect project path....Once I got that sorted out I got the following......

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/losses/losses_impl.py:209: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/losses/losses_impl.py:209: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/train.py", line 51, in load_and_enqueue
    batch_np = dataset.next_batch()
  File "/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/dataset/pose_dataset.py", line 188, in next_batch
    return self.make_batch(data_item, scale, mirror)
  File "/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/dataset/pose_dataset.py", line 215, in make_batch
    image = imread(os.path.join(self.cfg.project_path,im_file), mode='RGB')
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/scipy/misc/pilutil.py", line 164, in imread
    im = Image.open(name)
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2312, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/DLC/ThoroughbredDLC-Byron-2019-01-24/labeled-data\\Anjaal\\img063.png'

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /content/drive/My Drive/DLC/ThoroughbredDLC-Byron-2019-01-24/snapshots/snapshot-850000
Restoring parameters from /content/drive/My Drive/DLC/ThoroughbredDLC-Byron-2019-01-24/snapshots/snapshot-850000
Display_iters overwritten as 10
Save_iters overwritten as 500
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'weigh_only_present_joints': False, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': '/content/drive/My Drive/DLC/ThoroughbredDLC-Byron-2019-01-24/dlc-models/iteration-0/ThoroughbredDLCJan24-trainset95shuffle1/train/snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'sgd', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'mirror': False, 'crop_pad': 0, 'scoremap_dir': 'test', 'dataset_type': 'default', 'use_gt_segm': False, 'batch_size': 1, 'video': False, 'video_batch': False, 'crop': True, 'cropratio': 0.4, 'minsize': 100, 'leftwidth': 400, 'rightwidth': 400, 'topheight': 400, 'bottomheight': 400, 'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15], [16], [17], [18], [19], [20], [21], [22]], 'all_joints_names': ['nose', 'eye', 'wither', 'midshoulder', 'shoulder', 'elbow', 'girth', 'nearforeknee', 'nearforefetlock', 'nearforefoot', 'offforeknee', 'offforefetlock', 'offforefoot', 'hip', 'topoftail', 'ischium', 'stifle', 'nearhock', 'hearhindfetlock', 'nearhindfoot', 'offhock', 'offhindfetlock', 'offhindfoot'], 'dataset': '/content/drive/My Drive/DLC/ThoroughbredDLC-Byron-2019-01-24/training-datasets/iteration-0/UnaugmentedDataSet_ThoroughbredDLCJan24/ThoroughbredDLC_Byron95shuffle1.mat', 'display_iters': 10, 'init_weights': '/content/drive/My Drive/DLC/ThoroughbredDLC-Byron-2019-01-24/snapshots/snapshot-850000', 'max_input_size': 1500, 'metadataset': '/content/drive/My Drive/DLC/ThoroughbredDLC-Byron-2019-01-24/training-datasets/iteration-0/UnaugmentedDataSet_ThoroughbredDLCJan24/Documentation_data-ThoroughbredDLC_95shuffle1.pickle', 'multi_step': [[0.005, 10000], [0.02, 430000], [0.002, 730000], [0.001, 1030000]], 'net_type': 'resnet_50', 'num_joints': 23, 'pos_dist_thresh': 17, 'project_path': '/content/drive/My Drive/DLC/ThoroughbredDLC-Byron-2019-01-24', 'save_iters': 500, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25}
Starting training....

HOWEVER.....it has sat on "Starting training" for the past 30 minutes and despite displayiters being "10" and saveiters being "500" its not displayed nor saved....
<img width="962" alt="screen shot 2019-02-17 at 5 07 23 pm" src="https://user-images.githubusercontent.com/6619599/52920265-a8edeb00-32d8-11e9-961b-bd2383030fbf.png">

**Comment by MMathisLab** [comment]
You must create the training_set inside of Colab to have the conversion happen; I.e. you labeled on Windows but Colab is Unix:

``"FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/DLC/ThoroughbredDLC-Byron-2019-01-24/labeled-data\Anjaal\img063.png'"``

![image](https://user-images.githubusercontent.com/28102185/52920397-cc656580-32d9-11e9-9111-eda1fe71690e.png)

**Comment by MMathisLab** [comment]
then it will ask you:

![image](https://user-images.githubusercontent.com/28102185/52920420-03d41200-32da-11e9-8e08-362d21afe528.png)

and you say yes :) 

Be sure to delete any older folder set for the iteration (inside dlc-models) first, otherwise this step won't work (see above)!
