### ISSUE TITLE
Missing animals in tracklet gui 

### ISSUE THREAD

**Issue by rikebuck** [DeepLabCut/DeepLabCut#2130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello, 
I am using multianimal DLC and having trouble going from the analyzed videos to the tracks. 
In particular, although when I run deeplabcut.analyze_videos(config_path, ['/fullpath/project/videos/'], videotype='.mp4', auto_track=True)
The output video I get ([vidname]_dlcrnetms5_shuffle1_50000_full.mp4) looks pretty good and is tracking all the animals in frame throughout the entirety of the video. However when I analyze the tracklets, often not all the animals are tracked, including in tracks in which the animals are found in the _full.mp4 movie (This is true even though p_cutoff in inference_cfg.yaml is lower than than p_cutoff in config.yaml):

Further I notice that when tracking individual animals, the tracklets will swap animalID without any obvious interference or obscuration of animals: 

Please advise? My assumption is that params in the refine_tracklets and inference_cfg.yaml need to be optimized? (perhaps cross-validated?);

     - The github version on the inference_cfg.yaml says certain params should be cross-validated

     - How does one go about using this?  
                - I saw that the function deeplabcut.evaluate_multianimal_crossvalidate() no longer exists, so I am not sure the best next step.  
               - I have tried playing around a little with the inference_cfg.yaml params manually via the refine_tracklets gui but didn’t see huge differences; I am not sure if I am changing the wrong params; if this the wrong way to go about changing params or something else

     - Do you have a process for going about optimizing the params?

     - Could there be other issues leading to this problem not related to cross validation/ or changing specific params? 
     
Thank you!

animals detected in _full.mp4 not found in refine_tracklet: 

<img width="787" alt="fullmp4_frame909" src="https://user-images.githubusercontent.com/20208871/214184917-2488b1ba-cc9c-4d45-911a-b6c739331ec1.png">
<img width="1117" alt="tracklet_frame909" src="https://user-images.githubusercontent.com/20208871/214184919-7ecf1400-6362-45ee-b48c-13a4a6805ffc.png">

consecutive frames swapping animal ID: 

<img width="617" alt="frame_i2" src="https://user-images.githubusercontent.com/20208871/214183361-f5c7a48b-c021-4dce-aaca-72491c5941dd.png">
<img width="619" alt="frame_i1" src="https://user-images.githubusercontent.com/20208871/214183363-0ebf43f9-d465-47bd-b38c-ad9710da4b6a.png">

### Operating System

linux

### DeepLabCut version

v2.3

### DeepLabCut mode

multi animal

### Device type

gpu

### Anything else?

inference_cfg:
https://github.com/DeepLabCut/DeepLabCut/blob/main/deeplabcut/inference_cfg.yaml 

cross validation: 
https://github.com/DeepLabCut/DeepLabCut/issues/758

refine_tracklets_gui settings:
<img width="291" alt="refine_tracklet_gui_settings" src="https://user-images.githubusercontent.com/20208871/214186178-c85e78b0-9d3a-48b9-8edc-6da8b7fe3056.png">

example changed inference_cfg:
<img width="372" alt="tested_inference_cfg_params" src="https://user-images.githubusercontent.com/20208871/214186180-147893e6-3005-4e75-8448-5fb2c27473f2.png">

default inference_cfg:
<img width="475" alt="default_inference_cfg_params" src="https://user-images.githubusercontent.com/20208871/214186181-86788df4-8b8e-49e5-94f2-c0ff455f2138.png">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @rikebuck, have you tried using the `box` tracker when calling `convert_detections2tracklets`? It may me more robust than `ellipse` if animals are very deformable. You could also lower `iou_threshold` to 0.1 to have tracking even less sensitive to frame-by-frame changes in body shapes
