### ISSUE TITLE
Tracking one body part in multiple animals

### ISSUE THREAD

**Issue by ellisjt** [DeepLabCut/DeepLabCut#2137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I'm working on a project where I want to track the center of three moving cells. One of the animals is distinguishable, and the other two are the same. I'm running into issues, especially with evaluation, because I think DLC is expecting two or more body parts.

### Operating System

Windows 10

### DeepLabCut version

2.3.0

### DeepLabCut mode

single animal

### Device type

CPU

### Relevant log output

```shell
Running  DLC_dlcrnetms5_1did_2paramJan30shuffle1_1900  with # of trainingiterations: 1900
C:\Users\Ellis\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
Activating extracting of PAFs
Network Evaluation underway...
0it [00:00, ?it/s]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[9], line 1
----> 1 deeplabcut.evaluate_network(path_config_file, plotting=True)

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\evaluate.py:604, in evaluate_network(config, Shuffles, trainingsetindex, plotting, show_errors, comparisonbodyparts, gputouse, rescale, modelprefix)
    601     from .evaluate_multianimal import evaluate_multianimal_full
    603     # TODO: Make this code not so redundant!
--> 604     evaluate_multianimal_full(
    605         config=config,
    606         Shuffles=Shuffles,
    607         trainingsetindex=trainingsetindex,
    608         plotting=plotting,
    609         comparisonbodyparts=comparisonbodyparts,
    610         gputouse=gputouse,
    611         modelprefix=modelprefix,
    612     )
    613 else:
    614     from deeplabcut.utils.auxfun_videos import imread, imresize

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\evaluate_multianimal.py:423, in evaluate_multianimal_full(config, Shuffles, trainingsetindex, plotting, show_errors, comparisonbodyparts, gputouse, modelprefix)
    418         conf[sl] = probs_pred[n_joint][
    419             neighbors[found]
    420         ].squeeze()
    422 if plotting == "bodypart":
--> 423     temp_xy = GT.unstack("bodyparts")[joints].values
    424     gt = temp_xy.reshape(
    425         (-1, 2, temp_xy.shape[1])
    426     ).T.swapaxes(1, 2)
    427     h, w, _ = np.shape(frame)

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\frame.py:3813, in DataFrame.__getitem__(self, key)
   3811     if is_iterator(key):
   3812         key = list(key)
-> 3813     indexer = self.columns._get_indexer_strict(key, "columns")[1]
   3815 # take() does not accept boolean indexers
   3816 if getattr(indexer, "dtype", None) == bool:

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\indexes\base.py:6070, in Index._get_indexer_strict(self, key, axis_name)
   6067 else:
   6068     keyarr, indexer, new_indexer = self._reindex_non_unique(keyarr)
-> 6070 self._raise_if_missing(keyarr, indexer, axis_name)
   6072 keyarr = self.take(indexer)
   6073 if isinstance(key, Index):
   6074     # GH 42790 - Preserve name from an Index

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\pandas\core\indexes\base.py:6133, in Index._raise_if_missing(self, key, indexer, axis_name)
   6130     raise KeyError(f"None of [{key}] are in the [{axis_name}]")
   6132 not_found = list(ensure_index(key)[missing_mask.nonzero()[0]].unique())
-> 6133 raise KeyError(f"{not_found} not in index")

KeyError: "['bodypart2'] not in index"
```

### Anything else?

Here's the config file:

>     # Project definitions (do not edit)
> Task: 1did_2param
> scorer: Christine
> date: Jan30
> multianimalproject: true
> identity: false
> 
>     # Project path (change when moving around)
> project_path: /Users/Ellis/Desktop/1did_2param-Christine-2023-01-30
> 
>     # Annotation data set configuration (and individual video cropping parameters)
> video_sets:
>   C:\Users\Ellis\Desktop\1did_2param-Christine-2023-01-30\videos\1did_2param_0to5s.mp4:
>     crop: 0, 800, 0, 600
> individuals:
> - did1
> - param1
> - param2
> uniquebodyparts: []
> multianimalbodyparts:
> - center
> 
>     # Fraction of video to start/stop when extracting frames for labeling/refinement
> start: 0
> stop: 1
> numframes2pick: 20
> 
>     # Plotting configuration
> skeleton:
> - center
> skeleton_color: black
> pcutoff: 0.6
> dotsize: 12
> alphavalue: 0.7
> colormap: rainbow
> 
>     # Training,Evaluation and Analysis configuration
> TrainingFraction:
> - 0.95
> iteration: 0
> default_net_type: dlcrnet_ms5
> default_augmenter: multi-animal-imgaug
> default_track_method: ellipse
> snapshotindex: -1
> batch_size: 8
> 
>     # Cropping Parameters (for analysis and outlier frame detection)
> cropping: false
>     #if cropping is true for analysis, then set the values here:
> x1: 0
> x2: 640
> y1: 277
> y2: 624
> 
>     # Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
> corner2move2:
> - 50
> - 50
> move2corner: true

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Correct; we do not support single-point multi-animal tracking (discussed in other issues!), you must use at least 2 points, and we recommend more, as this is geared towards pose estimation, not single-key point tracking :D
