### ISSUE TITLE
Error on new install `Collecting scikit-learn>=1.0`

### ISSUE THREAD

**Issue by byronrogers73** [DeepLabCut/DeepLabCut#2138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Using Mac installed with Ventura 13.1...

cloned the git and ran conda env create -f DEEPLABCUT.yaml

Everything seemed to be installed correctly and then all the dependecies installed correctly right up to when it gets to scikit-learn....any ideas as to why and a solution are appreciated.

Collecting scikit-learn>=1.0
  Using cached scikit-learn-1.2.1.tar.gz (7.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [101 lines of output]
      Ignoring numpy: markers 'python_version == "3.10" and platform_system == "Windows" and platform_python_implementation != "PyPy"' don't match your environment
      Collecting setuptools<60.0
        Using cached setuptools-59.8.0-py3-none-any.whl (952 kB)
      Collecting wheel
        Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
      Collecting Cython>=0.29.24
        Using cached Cython-0.29.33-py2.py3-none-any.whl (987 kB)
      Collecting oldest-supported-numpy
        Using cached oldest_supported_numpy-2022.11.19-py3-none-any.whl (4.9 kB)
      Collecting scipy>=1.3.2
        Using cached scipy-1.10.0.tar.gz (42.4 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Preparing metadata (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [67 lines of output]
            The Meson build system
            Version: 1.0.0
            Source dir: /private/var/folders/7j/lz56t_j55j32201sw4psr0w40000gn/T/pip-install-nvc8iw7j/scipy_20bfbdb4701844a7aead83a8d72db228
            Build dir: /private/var/folders/7j/lz56t_j55j32201sw4psr0w40000gn/T/pip-install-nvc8iw7j/scipy_20bfbdb4701844a7aead83a8d72db228/.mesonpy-r5x6ofdy/build
            Build type: native build
            Project name: SciPy
            Project version: 1.10.0
            C compiler for the host machine: cc (clang 14.0.0 "Apple clang version 14.0.0 (clang-1400.0.29.202)")
            C linker for the host machine: cc ld64 820.1
            C++ compiler for the host machine: c++ (clang 14.0.0 "Apple clang version 14.0.0 (clang-1400.0.29.202)")
            C++ linker for the host machine: c++ ld64 820.1
            Host machine cpu family: x86_64
            Host machine cpu: x86_64
            Compiler for C supports arguments -Wno-unused-but-set-variable: YES
            Compiler for C supports arguments -Wno-unused-function: YES
            Compiler for C supports arguments -Wno-conversion: YES
            Compiler for C supports arguments -Wno-misleading-indentation: YES
            Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
            Library m found: YES
      
            ../../meson.build:63:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['ifx'], ['g95']]
            The following exception(s) were encountered:
            Running `gfortran --version` gave "[Errno 2] No such file or directory: 'gfortran'"
            Running `gfortran -V` gave "[Errno 2] No such file or directory: 'gfortran'"
            Running `flang --version` gave "[Errno 2] No such file or directory: 'flang'"
            Running `flang -V` gave "[Errno 2] No such file or directory: 'flang'"
            Running `nvfortran --version` gave "[Errno 2] No such file or directory: 'nvfortran'"
            Running `nvfortran -V` gave "[Errno 2] No such file or directory: 'nvfortran'"
            Running `pgfortran --version` gave "[Errno 2] No such file or directory: 'pgfortran'"
            Running `pgfortran -V` gave "[Errno 2] No such file or directory: 'pgfortran'"
            Running `ifort --version` gave "[Errno 2] No such file or directory: 'ifort'"
            Running `ifort -V` gave "[Errno 2] No such file or directory: 'ifort'"
            Running `ifx --version` gave "[Errno 2] No such file or directory: 'ifx'"
            Running `ifx -V` gave "[Errno 2] No such file or directory: 'ifx'"
            Running `g95 --version` gave "[Errno 2] No such file or directory: 'g95'"
            Running `g95 -V` gave "[Errno 2] No such file or directory: 'g95'"
      
            A full log can be found at /private/var/folders/7j/lz56t_j55j32201sw4psr0w40000gn/T/pip-install-nvc8iw7j/scipy_20bfbdb4701844a7aead83a8d72db228/.mesonpy-r5x6ofdy/build/meson-logs/meson-log.txt
            + meson setup --prefix=/Users/byronrogers/opt/anaconda3/envs/DEEPLABCUT /private/var/folders/7j/lz56t_j55j32201sw4psr0w40000gn/T/pip-install-nvc8iw7j/scipy_20bfbdb4701844a7aead83a8d72db228 /private/var/folders/7j/lz56t_j55j32201sw4psr0w40000gn/T/pip-install-nvc8iw7j/scipy_20bfbdb4701844a7aead83a8d72db228/.mesonpy-r5x6ofdy/build --native-file=/private/var/folders/7j/lz56t_j55j32201sw4psr0w40000gn/T/pip-install-nvc8iw7j/scipy_20bfbdb4701844a7aead83a8d72db228/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
            Traceback (most recent call last):
              File "/Users/byronrogers/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                main()
              File "/Users/byronrogers/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
              File "/Users/byronrogers/opt/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
                whl_basename = backend.build_wheel(metadata_directory, config_settings)
              File "/private/var/folders/7j/lz56t_j55j32201sw4psr0w40000gn/T/pip-build-env-17ahsi_r/overlay/lib/pypy3.8/site-packages/mesonpy/__init__.py", line 1060, in build_wheel
                with _project(config_settings) as project:
              File "/Users/byronrogers/opt/anaconda3/envs/DEEPLABCUT/lib/pypy3.8/contextlib.py", line 113, in __enter__
                return next(self.gen)
              File "/private/var/folders/7j/lz56t_j55j32201sw4psr0w40000gn/T/pip-build-env-17ahsi_r/overlay/lib/pypy3.8/site-packages/mesonpy/__init__.py", line 975, in _project
                with Project.with_temp_working_dir(
              File "/Users/byronrogers/opt/anaconda3/envs/DEEPLABCUT/lib/pypy3.8/contextlib.py", line 113, in __enter__
                return next(self.gen)
              File "/private/var/folders/7j/lz56t_j55j32201sw4psr0w40000gn/T/pip-build-env-17ahsi_r/overlay/lib/pypy3.8/site-packages/mesonpy/__init__.py", line 750, in with_temp_working_dir
                yield cls(source_dir, tmpdir, build_dir, meson_args)
              File "/private/var/folders/7j/lz56t_j55j32201sw4psr0w40000gn/T/pip-build-env-17ahsi_r/overlay/lib/pypy3.8/site-packages/mesonpy/__init__.py", line 632, in __init__
                self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
              File "/private/var/folders/7j/lz56t_j55j32201sw4psr0w40000gn/T/pip-build-env-17ahsi_r/overlay/lib/pypy3.8/site-packages/mesonpy/__init__.py", line 680, in _configure
                self._meson('setup', *setup_args)
              File "/private/var/folders/7j/lz56t_j55j32201sw4psr0w40000gn/T/pip-build-env-17ahsi_r/overlay/lib/pypy3.8/site-packages/mesonpy/__init__.py", line 657, in _meson
                return self._proc('meson', *args)
              File "/private/var/folders/7j/lz56t_j55j32201sw4psr0w40000gn/T/pip-build-env-17ahsi_r/overlay/lib/pypy3.8/site-packages/mesonpy/__init__.py", line 652, in _proc
                subprocess.check_call(list(args), env=self._env)
              File "/Users/byronrogers/opt/anaconda3/envs/DEEPLABCUT/lib/pypy3.8/subprocess.py", line 364, in check_call
                raise CalledProcessError(retcode, cmd)
            subprocess.CalledProcessError: Command '['meson', 'setup', '--prefix=/Users/byronrogers/opt/anaconda3/envs/DEEPLABCUT', '/private/var/folders/7j/lz56t_j55j32201sw4psr0w40000gn/T/pip-install-nvc8iw7j/scipy_20bfbdb4701844a7aead83a8d72db228', '/private/var/folders/7j/lz56t_j55j32201sw4psr0w40000gn/T/pip-install-nvc8iw7j/scipy_20bfbdb4701844a7aead83a8d72db228/.mesonpy-r5x6ofdy/build', '--native-file=/private/var/folders/7j/lz56t_j55j32201sw4psr0w40000gn/T/pip-install-nvc8iw7j/scipy_20bfbdb4701844a7aead83a8d72db228/.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2']' returned non-zero exit status 1.
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

### Operating System

Mac OS using Ventura 13.1

### DeepLabCut version

dlc version

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
I would run without using cached versions (in general is this why conda env are not ideal and docker is best :). You can run: `pip install --upgrade --force-reinstall 'deeplabcut[gui,tf,modelzoo]'` and see if that fixs the issue (otherwise, I don't have 13.1 installed on a mac to test locally)
