### ISSUE TITLE
Completing docs for pretrained MPII resnet-101

### ISSUE THREAD

**Issue by sebo361** [DeepLabCut/DeepLabCut#214]
Hi guys,

the `functionDetails.md` docs says that only `curl -L -O https://datasets.d2.mpi-inf.mpg.de/deepercut-models-tensorflow/mpii-single-resnet-101.data-00000-of-00001` needs to be downloaded but actually also `.meta` and `.index` is needed:

```
curl -L -O https://datasets.d2.mpi-inf.mpg.de/deepercut-models-tensorflow/mpii-single-resnet-101.meta
curl -L -O https://datasets.d2.mpi-inf.mpg.de/deepercut-models-tensorflow/mpii-single-resnet-101.index
```

Without them I could not start training.

**Comment by MMathisLab** [comment]
thanks, Sebo! Good point. I'll add them to the docs for the next update!

**Comment by MMathisLab** [comment]
(I will close now, as it's updated in a branch that will be merged soon!)
