### ISSUE TITLE
DLC Training with PAF loss

### ISSUE THREAD

**Issue by williamhoole** [DeepLabCut/DeepLabCut#2141]
Is it possible to use the pairwise_huber_loss without having to use Multianimal training ?

If so how is this possible ?

**Comment by williamhoole** [comment]
I have a datasst with only one class but would like to use the pairwise_huber_loss to increase the accuracy of the predictions

**Comment by MMathisLab** [comment]
hi @williamhoole we ask that questions go to the ImageForum, please see: https://github.com/DeepLabCut/DeepLabCut#be-part-of-the-dlc-community

You can use only single animal data, but set multianimal true and it will use the PAF
