### ISSUE TITLE
Issue to launch DLC 2.2.3 GUI on MacOS

### ISSUE THREAD

**Issue by witeal** [DeepLabCut/DeepLabCut#2143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi everyone,

I am new to DLC and I am using a MacBook Pro (Beginning of 2015 version) and the 12.6.3 version of MacOS Monterey

I followed all the instructions given to install DeepLabCut 2.3.0 (the latest version of DLC I assume) and managed to install the environment DLC, I couldn't launch the newest version of DLC so I tried to install the 2.2.3 version that seems to work better with MacOS but still I have an error stating that the program doesn't have access to my screen...

Does anyone know how to solve that on Mac ?

I tried to follow the instruction given in other discussions, to deinstall and reinstall since two days and it still doesn’t work. I would be grateful for any help.

Thanks a lot.

### Operating System

MacOS Monterey - 12.6.3 version 

### DeepLabCut version

dlc version 2.2.3 (same problem with the 2.3.0)

### DeepLabCut mode

single animal

### Device type

GPU I assume (I have a Intel Iris Graphics 6100 integrated GPU on my MacBook Pro)

### Steps To Reproduce

MacBook-Pro-de-myname:~ myname$ conda activate DEEPLABCUT
(DEEPLABCUT) MacBook-Pro-de-myname:~ myname$ python -m deeplabcut

### Relevant log output

```shell
2023-02-03 10:06:43.901878: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Loading DLC 2.2.3...
Starting GUI...
This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
You need to launch DLC using pythonw rather than python: `pythonw -m deeplabcut`. If you get an error that pythonw is not found (or if it linked to the wrong python version), run `conda install python.app` to be safe. (see e.g. https://github.com/DeepLabCut/DeepLabCut/issues/1218#issuecomment-853280085)
