### ISSUE TITLE
videos cut and pasted rather than copied when symlink fails on windows

### ISSUE THREAD

**Issue by backyardbiomech** [DeepLabCut/DeepLabCut#2145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I called `add_videos` on the command line without setting `copy_videos`.
Symlink creation failed, but instead of stopping, or copying the videos, the videos were cut and pasted (moved) per the printed output.

My concern is not the symlink failure (actually I meant to copy_videos anyway).

This behavior is dangerous - unexpectedly moving video files disrupts file organization designed to maintain experimental integrity. 

Is there a way to catch the windows error regarding symlink failure, and copy the videos instead?

### Operating System

Windows 10

### DeepLabCut version

dlc version = 2.3.0

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

1. called `dlc.add_new_videos(config, vids)` on existing project (`vids` is a list of two videos)
2. got error below

### Relevant log output

```shell
Attempting to create a symbolic link of the video ...
Symlink creation impossible (exFat architecture?): cutting/pasting the video instead.
C:\Users\original\path\to\project\videos\videoname.mov moved to C:\Users\projects\thisAnimal\dlcproject-DLC-2021-10-07\videos\videoname.mov
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
i agree; @jeylau can this be revised? 

>> copy the videos instead

**Comment by jeylau** [comment]
Although this had changed with https://github.com/DeepLabCut/DeepLabCut/issues/1234, I agree too. We probably need another flag to disambiguate 'copy' vs 'move' fallback.

**Comment by nataliekoh** [comment]
I am seeing this issue too; following thread.
