### ISSUE TITLE
DeepLabCu: "Drag image(s) here to open" window box not showing any images after dragging

### ISSUE THREAD

**Issue by Oolev** [DeepLabCut/DeepLabCut#2149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

On Ubuntu 20.04.5, after extracting the video frames and moving to the next step: "Label frames", a new empty window shows up without the frames asking to manually drag them from the labeled-data folder. However, nothing shows up after I drag the images (screenshot attached). They are 30 i total.

Usually on Windows OS, the frames window is automatically populated with the frames, so I wonder how to solve this issue.

![Screenshot from 2023-02-07 18-31-59](https://user-images.githubusercontent.com/19272590/217214303-e86a5283-7cee-42f2-a777-b6557797e73b.png)

### Operating System

Ubuntu 20.04.5

### DeepLabCut version

DLC 2.3.0

### DeepLabCut mode

multi animal

### Device type

Nvidia GeForce 940Mx

### Steps To Reproduce

conda create --name dlctrial python=3.10
conda activate dlctrial
pip install deeplabcut[gui,tf]
python -m deeplabcut

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by natsukium** [comment]
It might be a problem of napari used internally.
I tried running the napari container image (https://github.com/orgs/napari/packages) in my WSL environment, but even this bare napari cannot open any images. Even the provided sample image cannot be opened.
I could not find the napari==0.4.17rc8 image installed with dlc==2.3.0, but I ran it with the released version, 0.4.17.
The command I used is as follows.
```bash
docker run --rm -v /tmp/.X11-unix:/tmp/.X11-unix -v /mnt/wslg:/mnt/wslg -e DISPLAY=$DISPLAY -e WAYLAND_DISPLAY=$WAYLAND_DISPLAY -e XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR -e PULSE_SURVER=$PULSE_SURVER ghcr.io/napari/napari:0.4.17
```
It seems that no such problem is reported in the repo of napari itself, and I will look into this a little more, as I may have missed something.

**Comment by jeylau** [comment]
Hi @natsukium, do images also fail to load when opened via the File menu? Or is it only related to drag/dropping folders?

**Comment by Oolev** [comment]
Yes @natsukium , I had problems with napari. I installed it via pip:
`python -m pip install "napari[all]"`
And it worked.

**Comment by natsukium** [comment]
It fails in both cases.

**Comment by natsukium** [comment]
@jiruhameru, Do you mean that it worked correctly after reinstalling napari[all]?
Hmmm, it still doesn't work in my environment.

**Comment by jeylau** [comment]
@natsukium, can you try by uninstalling `pyside6` and installing `pyqt6==6.5.0` rather?

**Comment by natsukium** [comment]
@jeylau thank you for your suggestion.
It works fine in the container created with dlc==2.3.3. (Containerfile is [here](https://github.com/natsukium/selfhosted/blob/93213720a15c132c224a83f744eb83fa84b2f6db/services/deeplabcut/deeplabcut/Containerfile))
It may be due to a change in dependencies. I will check it later.

**Comment by jeylau** [comment]
Great to hear! And thanks for sharing the Dockerfile.

**Comment by natsukium** [comment]
It looks like we can close this issue.
