### ISSUE TITLE
Bug in Track Refinement GUI causes DLC to crash

### ISSUE THREAD

**Issue by VAmoroso13** [DeepLabCut/DeepLabCut#2152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When in the [track refinement GUI] you attempt to fast-forward the speed you are met with DeepLabCut crashing and the following error in the terminal:

> QCoreApplication::exec: The event loop is already running
QObject::startTimer: Timers can only be used with threads started with QThread
.....
QObject::startTimer: Timers can only be used with threads started with QThread
Assertion fctx->async_lock failed at libavcodec/pthread_frame.c:173

I mentioned this to Konrad Danielewski, who I beleive commented on it in a different pull-request: [Here](https://github.com/DeepLabCut/DeepLabCut/pull/2126#issuecomment-1406421346)

### Operating System

Windows 11

### DeepLabCut version

v2.3.0

### DeepLabCut mode

multi animal

### Device type

RTX4080
i5-12600K

### Steps To Reproduce

1. Open DLC's [Track Refinment GUI]
2. Attempt to speed-up the frames/tick by using [Alt]-[Forward]
3. Crash

### Relevant log output

```shell
QCoreApplication::exec: The event loop is already running
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
QObject::startTimer: Timers can only be used with threads started with QThread
Assertion fctx->async_lock failed at libavcodec/pthread_frame.c:173
```

### Anything else?

The lack of this features makes the fixing of occasional identity swaps in a highly interacting species over hours of video very difficult if not impossible given the sluggishness of the GUI in general. 

Thank you for any help in this matter

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by VAmoroso13** [comment]
I hate to be a bother, but is there a confirmation and ETA on this issue? With many long videos in a highly interacting species, it's near impossible to correct for label swaps with the way it is currently. 

Thank you!

**Comment by jeylau** [comment]
Hey @VAmoroso13, I have just opened a PR to fix the GUI crashes you described. Sorry about the delay!

**Comment by VAmoroso13** [comment]
Hi Jessy, 
First of all, thank you for addressing this problem. Very much respect your work and efforts; So, my gratitude is enormous. 

While I have you, can I ask you a basic question?

If I have a network that has been trained with identified individuals (identity=true) in config.yaml, what is the optimal or right setting for [withid] in inference_cfg.yaml when running on two animals that are in the same species but not in the direct training set of videos? Also, the number of individuals changed from 3 to 2. 

Thank you for everything and have a wonderful day, Vince

**Comment by jeylau** [comment]
It's a whole team behind it, but you're very welcome! ☺️

I could see the case you describe work in only one very specific scenario: the two other animals in your test videos share the same specific visual features than those you annotated, and the third one is very different. In those conditions, considering that your model has been trained to predict 2 scores per body part (i.e., the likelihood that this keypoint belongs to either animal 1 or animal 2), and assuming that ID prediction is very accurate, you could get the poses of animal 1 & 2 and infer the pose of the 3rd one as the remaining keypoints. This seems quite unlikely though, so I'd set `withid` to False, `topktoretain` to 3, and run video analysis with the default parameters.

**Comment by VAmoroso13** [comment]
Of course and thanks for the advice. 

Just to clarify; the model was trained on 3 individuals and I'm now identifying pairs. I infer that it's still best to set [withid] to False which was my confusion and [topktoretain] to 2?

**Comment by jeylau** [comment]
Sorry for the confusion: `topktoretain` to 2 is right. I just checked for `withid` and it isn't used anymore actually. So checking whether it works is simple, you can pass `identity_only=True` to `deeplabcut.analyze_videos`.
