### ISSUE TITLE
A stranger loss pleateu druing the training of maDeeplabcut

### ISSUE THREAD

**Issue by DuanWei-fudan** [DeepLabCut/DeepLabCut#2155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When I trained the network, an amazing increase of the loss value occured.
![image](https://user-images.githubusercontent.com/75257822/218414630-e0ea2607-ea1f-49e5-9838-fc02df4774e8.png)
![image](https://user-images.githubusercontent.com/75257822/218414576-85df8116-3ed4-4ce8-b163-7c044c435bfa.png)

### Operating System

Win10

### DeepLabCut version

dlc version：'2.3.0'

### DeepLabCut mode

multi animal

### Device type

gpu，batchsize=8
_deeplabcut.train_network(config_path,shuffle=1,gputouse=0,displayiters=100,saveiters=10000, maxiters=100000, allow_growth=True)_

### Anything else?

How can I improve the compute capability?Maybe just one-third?
(6.2/16GB------>16/16GB)
![image](https://user-images.githubusercontent.com/75257822/218415064-d09a794b-b373-4905-8eed-b2095c49698a.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
tell you tell us a bit more about if this always happens? Could be a GPU issue....

**Comment by DuanWei-fudan** [comment]
Actually it happened just that day!But a the new question happend: the _evaluate_network_ is very very slow.
![image](https://user-images.githubusercontent.com/75257822/220496682-1f24b9b1-0a8c-45e0-ba50-f4855cfc2be5.png)

**Comment by AlexEMG** [comment]
I'd think there is some wrongly labeled image in the batch and whenever that is in the queue you get a huge loss (or something related). Maybe the image is corrupted and the output cannot even be predicted or so. 

Did the evaluation run in the end?
