### ISSUE TITLE
Unable to start using Docker container (invalid device #)

### ISSUE THREAD

**Issue by Idavr** [DeepLabCut/DeepLabCut#216]
**Your Operating system and DeepLabCut version**

Ubuntu 16.04 LTS, with DeepLabCut2.0

**Describe the problem**

I am trying to install DeepLabCut, following your instructions on https://github.com/MMathisLab/Docker4DeepLabCut2.0. I am very new to using this kind of program, and just using the terminal is still a learning process, but the instructions are quite straight-forward. However, the problem I mostly seem to run into is regarding the nvidia docker when trying to start the docker container from the image using 

GPU=1 bash ./dlc-docker run -d -p 2351:8888 -e USER_HOME=$HOME/DeepLabCut --name containername dlc_username/dlcdocker

The screenshot below shows the result of that command.

![screenshot from 2019-02-19 13-38-40](https://user-images.githubusercontent.com/47774575/53015594-b7104880-344b-11e9-8b50-56d1f9349a9f.png)

The error message is:

1 nvidia-docker run -v /home/poop:/home/poop -p 47133:22 -p 2351:8888 -e USER_GROUPS=sudo -e USER=poop -e USER_ID=1000 -e USER_ENCRYPTED_PASSWORD=aa5V9MSdgw5ec -e USER_HOME=/home/poop -e GPU=1 -e DISPLAY=:0 -d -e USER_HOME=/home/poop/DeepLabCut --name containername dlc_username/dlcdocker
nvidia-docker | 2019/02/19 13:34:40 Error: invalid device: 1

From what I've gathered, this suggests some kind of incompatibility, am I correct? I have been unable to find any solution to this, so any insight would be greatly appreciated!

**Comment by MMathisLab** [comment]
Could you please post docker questions on the Docker repo or the forum please. 

Do you have two GPUs?
As the instructions say, check GPU # with nvidia-Smi 

Also you’re binding HOME  to DeepLabCut, so hopefully you have a folder called that. Looks like you don’t ... see your error, “poop” seems to be your folder.
