### ISSUE TITLE
SciPy version update (1.10) breaks Colab (fixed) 

### ISSUE THREAD

**Issue by yanavdsande** [DeepLabCut/DeepLabCut#2166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi, just a heads up. Running the google colab MADLC example breaks with dependency issues due to the latest SciPy update from this week. Manually reverting to SciPy 1.7.0 fixed this for me, but note that you also have adjust scikit-image (0.19 works). Maybe an easy fix is to set a range of versions in the requirement file? Cheers and thank you for the great work!! 

### Operating System

Google Colab

### DeepLabCut version

dlc version 2.3.0

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

Run the google colab MA script in Colab

### Relevant log output

```shell
N.A.
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
thanks @yanavdsande for the heads up! Very useful ! @jeylau can we test a fix?

**Comment by jeylau** [comment]
@yanavdsande, what is the error you're running into? The notebook seems to work fine, but that's maybe because COLAB now comes with scipy 1.10.1 🤔

**Comment by yanavdsande** [comment]
@jeylau  Hi! It has been a while, but I remember there were problems with different functions that could not be accessed such as the read_config() function and the signal.tools(), when running the train_network().  I looked back in my version history and found this output when I ran the train_network() cell:
<img width="963" alt="image" src="https://user-images.githubusercontent.com/58653502/228904011-b1e53541-7ea6-460c-be9e-993a407d19dc.png">

If you would load in the function as such: 
from deeplabcut.utils import auxiliaryfunctions
f = auxiliaryfunctions.read_config() 
It would also give the same error as in the screenshot: 
	Error
		AttributeError
		---------------------------------------------------------------------------
		AttributeError                            Traceback (most recent call last)
		<ipython-input-16-13d4ba472440> in <module>
		      1 from deeplabcut.utils import auxiliaryfunctions
		----> 2 f = auxiliaryfunctions.read_config()
		
		AttributeError: module 'deeplabcut.utils.auxiliaryfunctions' has no attribute 'read_config

Accessing the function this way: 
from deeplabcut.utils.auxiliaryfunctions import read_config 
would work, but if I adjusted it in the code it still gave me a read_config does not exist error. 

Maybe the upgrade to scipy 10.1 fixed it, let's hope so! Hope this message does grant you some more information. Let me know if you need more. 

All the best, 
Yana

**Comment by jeylau** [comment]
Thanks a lot for the extra information, @yanavdsande! It does run without problem now, so I'll close this issue.
