### ISSUE TITLE
qtpy.QtBindingsNotFoundError: No Qt bindings could be found

### ISSUE THREAD

**Issue by jain-brain** [DeepLabCut/DeepLabCut#2167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

While trying to import deeplabcut, I am receiving this error but can't resolve it. Here is the associated traceback error:
`Loading DLC 2.3.0...
Traceback (most recent call last):
  File "/home/shubham/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/qtpy/__init__.py", line 253, in <module>
    from PySide6.QtCore import __version__ as QT_VERSION  # analysis:ignore
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/shubham/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/PySide6/Qt/lib/libQt6Core.so.6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shubham/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/__init__.py", line 25, in <module>
    from deeplabcut.gui.tracklet_toolbox import refine_tracklets
  File "/home/shubham/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/gui/__init__.py", line 15, in <module>
    import qtpy  # Necessary unused import to properly store the env variable
  File "/home/shubham/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/qtpy/__init__.py", line 259, in <module>
    raise QtBindingsNotFoundError()
qtpy.QtBindingsNotFoundError: No Qt bindings could be found
`

### Operating System

Ubuntu 18.04

### DeepLabCut version

dlc version

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by natsukium** [comment]
Hi, @jain-brain
It seems this error is caused by the lack of the glibc shared library(libc.so.6) on Ubuntu.
Try installing `libc6` with the command `sudo apt install libc6`.
Alternatively, I believe this is the actual solution here. Ubuntu 18.04 does not officially support glibc 2.28 or higher, so you have to install glibc 2.28 manually like [this answer](https://stackoverflow.com/questions/72513993/how-to-install-glibc-2-29-or-higher-in-ubuntu-18-04).
It is a bit of a challenge, so you may consider upgrading to Ubuntu 20.04 or higher if possible otherwise, consider installing deeplabcut==2.2.3.

**Comment by pderdeyn** [comment]
I did some research on this issue as well and was advised against manually installing glibc 2.28. If you make a mistake it's easy to cause damage to your OS
https://stackoverflow.com/a/62390881
Perhaps it is better to say there is no longer DLC support for ubuntu 18.04 then to risk folks taking this path?

**Comment by timsainb** [comment]
I get this error when using 2.3 but not 2.2.3, when installing without the GUI. 

Is it possible that the no gui version is for some reason trying to load QT?

**Comment by jeylau** [comment]
I have seen this error on other machines, but not on mine with a fresh install today, and just understood why; @timsainb pointed me in the right direction in #2178.
It is only with the new qtpy release from 2 days ago that the `qtpy.QtBindingsNotFoundError` inherits from `ImportError` (https://github.com/spyder-ide/qtpy/commit/2f04efabdbbe115ec6b020e74f08b2776dea3b93) and is thus properly handled by deeplabcut [here](https://github.com/DeepLabCut/DeepLabCut/blob/cd5b685043b6c2253899e35f9fb92096c178f5c5/deeplabcut/__init__.py#L32).
If you do not use the GUI, you could simply uninstall qtpy (or funnily enough update it with `pip install qtpy==2.3.1`), and deeplabcut will load just fine. If you do need the GUI though, try reinstall PySide6 with `pip install pyside6<6.3.2`.
