### ISSUE TITLE
Unable to generate analysed video

### ISSUE THREAD

**Issue by sanchitkalra** [DeepLabCut/DeepLabCut#2172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi.

I have been trying to generate analysed videos with DeepLabCut using trained models I’ve received from my Lab. I’m trying to process one video at a time. The video gets processed and plot-poses, pickle, and h5 files are created. The csv is generated when I try to run the script manually but not for some reason when I run the script through a process spawned by NodeJS.

Python Code:
```
import os
os.environ["DLClight"]="True"

import deeplabcut
import argparse

import argparse
parser = argparse.ArgumentParser(description='MobileNet 5 marker models')
parser.add_argument('dir', type=str, help='absolute path for the directory for this analysis. must end with a /')
parser.add_argument('video', type=str, help='name of the video file. tested only with mp4, supply that.')
parser.add_argument('dirpath', type=str, help='name of the dir path to the config file')
args = parser.parse_args()
print(args.__dict__)

videofile_path = [args.dir  + args.video]
videofile = args.dir 
path_config_file = args.dirpath +'/config.yaml'

print('NEW project_path: ' + args.dir)
print('NEW path_config_file: ' + path_config_file)
print('NEW videofile_path: ' + videofile_path[0])

if __name__ == "__main__":
    deeplabcut.analyze_videos(path_config_file,videofile_path, videotype='mp4')

    deeplabcut.plot_trajectories(path_config_file,videofile_path, videotype='mp4')

    deeplabcut.create_labeled_video(path_config_file,videofile_path, videotype='mp4')

    deeplabcut.analyze_videos_converth5_to_csv(videofile,'.mp4')
```

NodeJS code:
```
const model = spawn('python', [
      `models/model.py`, // refers to the above python code
      `uploads/${fileDir}/`, // dir where the video is supposed to be located
      `${fileName}`, // the name of the video file
      `${modelDir}` // the dir where the model's config file is present
    ])
```
Things I’ve tried:

I thought it could be an issue with the file name containing - but removing that did no change, the video was still not generated.
I tried putting the code and the model in a separate folder to test and remove arguments and statically provided values via variables. The frames are again analysed successfully but no video is rendered or csv file is generated. Code below.
Another thing that happens always after the video is analysed, I get the following error:
```
Starting to process video: videos/v.mp4
Loading videos/v.mp4 and data.
[Errno 2] No such file or directory: 'videos'
Traceback (most recent call last):
  File "/path/to/models/model.py", line 32, in <module>
    deeplabcut.analyze_videos_converth5_to_csv(videofile,'.mp4')
  File "/Users/mk/Downloads/DeepLabCut/deeplabcut/utils/conversioncode.py", line 130, in analyze_videos_converth5_to_csv
    h5_files = list(
  File "/Users/mk/Downloads/DeepLabCut/deeplabcut/utils/auxiliaryfunctions.py", line 436, in grab_files_in_folder
    for file in os.listdir(folder):
FileNotFoundError: [Errno 2] No such file or directory: 'v.mp4'
```
in this case, v.mp4 is the video it just analysed and is trying to analyse again and failing with this error.

Code for the second case of what I tried
```
import os
os.environ["DLClight"]="True"

import deeplabcut
# import argparse

# import argparse
# parser = argparse.ArgumentParser(description='MobileNet 5 marker models')
# parser.add_argument('dir', type=str, help='absolute path for the directory for this analysis. must end with a /')
# parser.add_argument('video', type=str, help='name of the video file. tested only with mp4, supply that.')
# parser.add_argument('dirpath', type=str, help='name of the dir path to the config file')
# args = parser.parse_args()
# print(args.__dict__)

videofile_path = ['videos/' + 'v.mp4']
videofile = 'v.mp4'
path_config_file = 'config.yaml'

# print('NEW project_path: ' + args.dir)
print('NEW path_config_file: ' + path_config_file)
print('NEW videofile_path: ' + videofile_path[0])

if __name__ == "__main__":
    deeplabcut.analyze_videos(path_config_file,videofile_path, videotype='mp4')

    deeplabcut.plot_trajectories(path_config_file,videofile_path, videotype='mp4')

    deeplabcut.create_labeled_video(path_config_file,videofile_path, videotype='mp4')

    deeplabcut.analyze_videos_converth5_to_csv(videofile,'.mp4')
```

### Operating System

macOS 13.0 (22A380)

### DeepLabCut version

2.3.0

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hello @sanchitkalra, your video path is relative; have you tried to pass in the absolute paths to your videos? `v.mp4` alone is not enough to locate the file.

**Comment by sanchitkalra** [comment]
Hello @jeylau, the video file path is `videos/v.mp4` and the script is present in this directory. I think DeepLabCut is able to locate the file because the plot-poses dir, the pickle and the h5 files are being created in the `videos` folder. It appears something else is probably going wrong for the csv and video to not be rendered.

**Comment by jeylau** [comment]
It cannot find the video folder though: `[Errno 2] No such file or directory: 'videos'`. Just specify the full path to the video folder (regardless of where your script is placed), and it should normally work fine ☺️

**Comment by sanchitkalra** [comment]
It did work. It did render the video this time but still no CSV. Interestingly, it told me `All H5 files were converted to CSV.` even though there is no CSV present in the directory. Also, could you shed some light as to why relative paths were causing issues?

**Comment by jeylau** [comment]
Use the following: `deeplabcut.analyze_videos(..., save_as_csv=True)`, so you won't have to convert the files later on. 
`analyze_videos_converth5_to_csv` must be given the absolute path to a folder rather than a video file, that's probably why it did not work.

**Comment by sanchitkalra** [comment]
I did supply the absolute path to the videos folder but still no CSV was generated. Although `deeplabcut.analyze_videos(..., save_as_csv=True)` does the same job and works for me.

Thank you for your help!
