### ISSUE TITLE
Runtime Error: Cannot compile QRC on Windows 10

### ISSUE THREAD

**Issue by Nike-Nay** [DeepLabCut/DeepLabCut#2173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello,
I have installed the DEEPLABCUT and have been able to create new projects, load videos and extract frames and label them. However, if I attempt to open an existing project, when I attempt to label the frames, I get the following error:
RuntimeError: Cannot compile QRC. Unexpected qtpy API name: PySide6

I found the same issue occurred to someone in November 2022 and I attempted the fixes on that forum, which included installing the newest version of napari-deeplabcut (pip install -U napari-deeplabcut or pip install git+https://github.com/DeepLabCut/napari-deeplabcut.git). However, these were not successful. 

Update: The issue has now started to happen everytime I try to label a project (new or existing)

### Operating System

Microsoft Windows 10 Home

### DeepLabCut version

dlc version: 2.3.1

### DeepLabCut mode

single animal

### Device type

Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz

### Steps To Reproduce

1.activate DEEPLABCUT
2. ipython
3. import deeplabcut
4. path_config_file = 'path to config file.yaml'
5. deeplabcut.label_frames(path_config_file)

### Relevant log output

```shell
In [7]: deeplabcut.label_frames(path_config_file)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[7], line 1
----> 1 deeplabcut.label_frames(path_config_file)

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\tabs\label_frames.py:19, in label_frames(config_path)
     18 def label_frames(config_path):
---> 19     _ = launch_napari(config_path)

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\widgets.py:38, in launch_napari(files)
     37 def launch_napari(files=None):
---> 38     viewer = napari.Viewer()
     39     # Automatically activate the napari-deeplabcut plugin
     40     for action in viewer.window.plugins_menu.actions():

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\viewer.py:61, in Viewer.__init__(self, title, ndisplay, order, axis_labels, show)
     57 # having this import here makes all of Qt imported lazily, upon
     58 # instantiating the first Viewer.
     59 from .window import Window
---> 61 self._window = Window(self, show=show)
     62 self._instances.add(self)

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\_qt\qt_main_window.py:414, in Window.__init__(self, viewer, show)
    412 def __init__(self, viewer: 'Viewer', *, show: bool = True):
    413     # create QApplication if it doesn't already exist
--> 414     get_app()
    416     # Dictionary holding dock widgets
    417     self._dock_widgets: Dict[
    418         str, QtViewerDockWidget
    419     ] = WeakValueDictionary()

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\_qt\qt_event_loop.py:195, in get_app(app_name, app_version, icon, org_name, org_domain, app_id, ipy_interactive)
    191     app.aboutToQuit.connect(wait_for_workers_to_quit)
    193     # this will register all of our resources (icons) with Qt, so that they
    194     # can be used in qss files and elsewhere.
--> 195     _register_napari_resources()
    197 _app_ref = app  # prevent garbage collection
    199 # Add the dispatcher attribute to the application to be able to dispatch
    200 # notifications coming from threads

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\_qt\qt_resources\_icons.py:438, in _register_napari_resources(persist, force_rebuild)
    436     _clear_resources = getattr(mod, "qCleanupResources")
    437 else:
--> 438     resources = _compile_napari_resources(save_path=persist and save_path)
    439     exec(resources, globals())
    440     _clear_resources = globals()["qCleanupResources"]

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\_qt\qt_resources\_icons.py:375, in _compile_napari_resources(save_path)
    367 svgs = generate_colorized_svgs(
    368     svg_paths=ICONS.values(),
    369     colors=[(k, 'icon') for k in _themes],
    370     opacities=(0.5, 1),
    371     theme_override={'warning': 'warning', 'logo_silhouette': 'background'},
    372 )
    374 with _temporary_qrc_file(svgs, prefix='themes') as qrc:
--> 375     output = compile_qrc(qrc)
    376     if save_path:
    377         try:

File ~\anaconda3\envs\DEEPLABCUT\lib\site-packages\napari\_qt\qt_resources\_icons.py:283, in compile_qrc(qrc)
    281     return _compile_qrc_pyside2(qrc).replace(b'PySide2', b'qtpy')
    282 else:
--> 283     raise RuntimeError(
    284         f"Cannot compile QRC. Unexpected qtpy API name: {qtpy.API_NAME}"
    285     )

RuntimeError: Cannot compile QRC. Unexpected qtpy API name: PySide6
```

### Anything else?

The forum which had the same issue as me was closed but this was the link:
https://github.com/DeepLabCut/DeepLabCut/issues/2035

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
hi @Nike-Nay can you install the latest, 2.3.2 - should be fixed!

**Comment by Nike-Nay** [comment]
Heya, thanks for the response @MMathisLab . However, I am getting the same error even now that I have installed the latest 2.3.2.
![Screenshot (47)](https://user-images.githubusercontent.com/127593957/226407217-b615e8aa-3bf3-4440-b873-bf84623f5f4f.png)
![Screenshot (48)](https://user-images.githubusercontent.com/127593957/226407224-27e4591e-0ac5-4c0d-b0ae-56de543941fb.png)

**Comment by jeylau** [comment]
@Nike-Nay, what are the versions of `napari`, `napari-deeplabcut`, and `PySide6` that are installed?

**Comment by Nike-Nay** [comment]
PySide6 is 6.3.1
napari is 0.4.17rc8
napari-deeplabcut is 0.1.1
![Screenshot (49)](https://user-images.githubusercontent.com/127593957/230066200-03278baa-51cb-49d2-975d-e2c4732328a0.png)

**Comment by jeylau** [comment]
@Nike-Nay, could you let me know if the error still occurs after you pull napari's latest full release: `pip install -U napari` (should be v0.4.17)?

**Comment by Nike-Nay** [comment]
Yep this finally worked! Thank you very much for the help!
