### ISSUE TITLE
qtpy issue with headless ubuntu on 2.3+

### ISSUE THREAD

**Issue by timsainb** [DeepLabCut/DeepLabCut#2178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

The new version of DLC tries to import qtpy

https://github.com/DeepLabCut/DeepLabCut/blob/main/deeplabcut/gui/__init__.py#L15

On a headless server, since there is no QT, an error is raised during import:

```
    256     QT6 = PYSIDE6 = True
    258 except ImportError:
--> 259     raise QtBindingsNotFoundError()
    260 else:
    261     os.environ[QT_API] = API
```

### Operating System

Ubuntu 22.04

### DeepLabCut version

2.3.3

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by timsainb** [comment]
It turns out this issue is an interaction with jupyter and deeplabcut 2.3 

To reproduce the issue on my machine (a headless ubuntu node). 

```
[create conda environment[
pip3 install deeplabcut[tf]
python3 -c "import deeplabcut"
> No error
pip3 install jupyter
python3 -c "import deeplabcut"
> Error
```

When jupyter is not installed everything works fine.

**Comment by jeylau** [comment]
Hello @timsainb! I just tried on headless Ubuntu 20.04 with a fresh installation: `pip install deeplabcut[tf]` and `pip install jupyter`, and all works fine on my side. Although `jupyter` did install qtpy (which is definitely undesirable), if deeplabcut has truly been installed gui-less, qtpy raises a `qtpy.QtBindingsNotFoundError`, which is caught at this [line](https://github.com/DeepLabCut/DeepLabCut/blob/cd5b685043b6c2253899e35f9fb92096c178f5c5/deeplabcut/__init__.py#L32), and deeplabcut continues in light mode.

How did you create your conda environment? Mine was simply with `conda create -n dlctest python=3.9`.
