### ISSUE TITLE
keyboard shortcuts for labeling gui

### ISSUE THREAD

**Issue by alberto-bortoni** [DeepLabCut/DeepLabCut#218]
it takes time to switch between zoom and pan. 
also once either of those tools are selected, moving a marker is a little glitchy. 
sure it is a small pointless request, but labeling takes long time and it is crucial. =)

if implemented, it would be best if they are one handed keyboard (right or left handed) so that the other hand does not leave the mouse

**Comment by MMathisLab** [comment]
> also once either of those tools are selected, moving a marker is a little glitchy.

Could you specifiy your operating system? I don't see any glitches so would be good to document them; perhaps take a screen capture so we can see? 

(just as an aside, there are hotkeys to advance (left and right arrows), and the bodyparts auto-advane to the next once placed). Ideally frames are cropped such that you do not need to zoom on each image, if possible :)

**Comment by AlexEMG** [comment]
Feel free to make a PR about this (the GUIs will be updated soon, so perhaps wait a few days). Some hotkeys do exist (for advancing frames etc.)

**Comment by ghost** [comment]
I've been using this [GUI for deeplabcut](https://gitlab.com/d_/dlc-gui), it has a lot of keybindings implemented.

**Comment by MMathisLab** [comment]
Maybe let’s make a list of hotkey requests here? 

- disable zoom with hotkey so you don’t have to click “off” to move labels, etc 

- skip a body part, ie be able to skip down in the body part list

**Comment by sebo361** [comment]
Hi @MMathisLab, yeaa skipping a label (as body part is occluded) with DOWN arrow would be awesome :)

**Comment by alesantuz** [comment]
Not a hotkey request, but I noticed that if I label only some body parts, then go to the next frame and come back to the original, the selected label is always the first, independently on whether it has been already placed or not. Maybe restart from the first non-placed label?

**Comment by alesantuz** [comment]
Not a hotkey request, but I noticed that if I label only some body parts, then go to the next frame and come back to the original, the selected label is always the first, independently on whether it has been already placed or not. Maybe restart from the first non-placed label?

Concerning hotkeys, I would add two items to the list:

- Disable zoom with hotkey so you don’t have to click “off” to move labels, etc

- Skip a body part, ie be able to skip down in the body part list

- _Enable/disable pan_

- _Next/previous frame_

Note on the zoom one: would it be possible to zoom in/out with Ctrl+mouse wheel?

**Comment by MMathisLab** [comment]
- next/previous are hot keys (the left and right arrows on the keyboard). 
- middle/wheel is allocated to deleting a point 
- @jbonaiuto implemented the auto-zoom off, but this caused errors in MacOS so we currently removed it from 2.0.6, but if someone wants to troubleshoot this on Mac, that would be great! https://github.com/AlexEMG/DeepLabCut/commit/f6744e53558e22efe593c1bcbdb6bc6b61a1f65e

**Comment by MMathisLab** [comment]
Hey @alberto-bortoni the latest PR/push #293 has your request in it!
