### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by SaeedF36** [DeepLabCut/DeepLabCut#2182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have managed to install DLC on my machine with no error or warninng following the instructions. However, using GUI, it does not create the labelled files.
Also, using terminal, when I run _label_frames_ command, the napari window pops up with no video and the software becomes busy (turning cursor) with the following warning in terminal:
_WARNING: Cannot open file '/Users/sf574/src/napari_deeplabcut/assets/unlock.svg', because: No such file or directory_

Thanks

### Operating System

macOS Monterry 12.6.3
MacBook Pro (14-inch, 2021)

### DeepLabCut version

DLC 2.3.2

### DeepLabCut mode

single animal

### Device type

Apple M1 Pro

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by AurelieP23** [comment]
Hi, 

I got the same error message when running the Extract Outlier Frames function, although both images and labels loaded into the napari viewer. 

I am using DLC 2.3.2 in Windows 10.

**Comment by dmkobylkov** [comment]
Hi,
I have the same issue, I can train the network, but I cannot analyze videos with this network. The issue with opening the videeo I have solved by installing a different version of matplotlib,
I am using DLC 2.3.2 in Windows 11.

**Comment by omnesan** [comment]
Hi! 
I ran into a similar issue when saving labeled frames with the GUI. I was able to find a temporary fix by accessing the napari_deeplabcut files. In **_widgets.py**, try changing line 218, 'selected=True' to **False**. I hope this helps!

Also, the warning is for a picture in the napari window that doesn't have the correct path. You can fix the path in _widgets.py.
Otherwise, the warning can safely be ignored!

I am using DLC 2.3.1 in Windows 11

**Comment by jeylau** [comment]
Icon paths are now fixed with https://github.com/DeepLabCut/napari-deeplabcut/commit/6749c01a84c5de6038e6c3dba77edcd9abdcbf85, thanks @omnesan for helping me troubleshoot.
I would not recommend changing `selected` though, as this has the effect of saving all layers (which is problematic when videos or other layers were added to napari).

**Comment by omnesan** [comment]
Thanks for the fast patch @jeylau !
To reiterate for other users and to make sure I have this right:

When saving labeled frames, you can save them all by selecting **Save Selected Layer(s)** as they're selected by default in the napari window.

However, by the same logic, if you select **Save All Layers** it's going to attempt saving all layers including the other images/videos that you are labeling over. Therefore, crashing napari and the gui as the image was not intended to be saved.

Is this correct?

**Comment by SaeedF36** [comment]
> Icon paths are now fixed with [DeepLabCut/napari-deeplabcut@6749c01](https://github.com/DeepLabCut/napari-deeplabcut/commit/6749c01a84c5de6038e6c3dba77edcd9abdcbf85), thanks @omnesan for helping me troubleshoot. I would not recommend changing `selected` though, as this has the effect of saving all layers (which is problematic when videos or other layers were added to napari).

Thank you for your help. I have still the problem that DLC crashes with a black screen of napari when I try to refine the labels.

**Comment by jeylau** [comment]
@omnesan, that's right!

@SaeedF36, are you getting an error in the terminal when this happens?

**Comment by SaeedF36** [comment]
No output on terminal. Like a normal execution.

**Comment by lindsayveazey** [comment]
Hi, I wanted to add that I am also getting the error
WARNING: Cannot open file `'..../src/napari_deeplabcut/assets/unlock.svg', because: No such file or directory` when I try to run `deeplabcut.label_frames(path_config)`. Has this fix been merged to the main branch?

**Comment by jeylau** [comment]
@lindsayveazey, yes, it has been merged into the main branch of `napari-deeplabcut`. It just a warning though, so you can safely ignore it.

@SaeedF36, could you describe exactly the steps you're taking so I can try to reproduce the crash?

**Comment by SaeedF36** [comment]
1. Open DLC with GUI on my machine
2. Create the project
3. Label the snapshots
4. Train the network on COLAB
5. Copy the Project on my machine
6. Call DLC on terminal (without GUI)
7. Open the project
8. Try to label frames
(6-8 are in the screenshot)

If I call DLC with GUI in the second round, it works fine but I cannot refine the machine-labelled frames.

<img width="1164" alt="Screenshot 2023-04-06 at 09 24 30" src="https://user-images.githubusercontent.com/111056358/230362739-d23f455f-5cf9-420f-ad7d-9311864fbc47.png">

**Comment by SaeedF36** [comment]
1. Open DLC with GUI on my machine
2. Create the project
3. Label the snapshots
4. Train the network on COLAB
5. Copy the Project on my machine
6. Call DLC on terminal (without GUI)
7. Open the project
8. Try to label frames
(6-8 are in the screenshot)

If I call DLC with GUI in the second round, it works fine but I cannot refine the machine-labelled frames.

<img width="1164" alt="Screenshot 2023-04-06 at 09 24 30" src="https://user-images.githubusercontent.com/111056358/230363950-26728c62-73e3-40dc-80ba-bcfdfe403a37.png">

**Comment by SaeedF36** [comment]
Is there any update for this issue?

**Comment by vchiang001** [comment]
I am getting a similar error on DLC 2.3.8 when I try to reopen folders I previously labelled (whenever a h5 file is already created). 
![image](https://github.com/DeepLabCut/DeepLabCut/assets/72048480/fd61633e-88d9-42e9-9b7d-04bb7a598d00)
