### ISSUE TITLE
filtered predictions not created in analyze_videos (GUI)

### ISSUE THREAD

**Issue by guillemlopez** [DeepLabCut/DeepLabCut#2184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello ! When I analyze the videos with the GUI (and having checked the box filter predictions), I don't get the h5 and csv files for the filtered predictions. I get no errors but the filter files are not created.

Then of course, I can't create videos with the filtered files.

Thank you in advance !
Guillem

### Operating System

windows 11

### DeepLabCut version

dlc version 2.3.2

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by KonradDanielewski** [comment]
Should be fixed with #2126 . Basically because the analysis was forwarded to a separate thread it was trying to run `filterpredictions` before the video has been analyzed.
