### ISSUE TITLE
How to convert deeplabcut’s ckpt model to ONNX or TFLITE, so that it can run on a mobile device(use flutter).

### ISSUE THREAD

**Issue by lBWtt** [DeepLabCut/DeepLabCut#2185]
I tried the code that I could find, but none of them could convert.

Can I change the format of the model produced by deeplabcut, maybe to .pb?

**Additional context**
![image](https://user-images.githubusercontent.com/105534764/228118555-472cf73b-4c10-4bea-9bbf-9387139052b5.png)

**Comment by MMathisLab** [comment]
please use the template for issues. I assume you have tried model_export?

**Comment by jeylau** [comment]
I'll close, as the answer was given by Mackenzie. `deeplabcut.export_model` internally calls `tf_to_pb` https://github.com/DeepLabCut/DeepLabCut/blob/7c1c8719426439a57fea8c07b37afee222d83fc7/deeplabcut/pose_estimation_tensorflow/export.py#L371, giving you a tar archive with a .pb model. Let us know if this didn't help.
