### ISSUE TITLE
Cannot create labelled video

### ISSUE THREAD

**Issue by SGasperoni** [DeepLabCut/DeepLabCut#2186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi, I am getting this issue when trying to create a labelled video. This happens both for filtered and unfiltered data, although the corresponding files do exist in the correct directory.
I tried with both google colab, from my computer (both from GUI and terminal) always the same error.

![image](https://user-images.githubusercontent.com/129159855/228177154-73805558-4e28-4817-a1ad-2ab49fdf05fb.png)

### Operating System

Windows 11

### DeepLabCut version

DLC 2.3.3

### DeepLabCut mode

multi animal

### Device type

google colab gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Is the project folder name correct? CSDS-Seren s -2023-03-17 does not look like a path typically produced automatically by DeepLabCut?

**Comment by SGasperoni** [comment]
Yes I doubled checked and the project folder name is the right one. (it's just weird because I misclicked when I first created the project name and then just never changed it).

**Comment by jeylau** [comment]
Great! Could you perhaps share a screenshot of the data files that were produced after video analysis? What code was run in the cells above in your notebooks? This may help me troubleshoot ☺️

**Comment by SGasperoni** [comment]
These are all the files that were created in that folder:

analyzeDLC_resnet50_CSDSMar17shuffle1_50000_assemblies.pickle
analyzeDLC_resnet50_CSDSMar17shuffle1_50000_el_filtered.csv
analyzeDLC_resnet50_CSDSMar17shuffle1_50000_el.h5
analyzeDLC_resnet50_CSDSMar17shuffle1_50000_el.pickle
analyzeDLC_resnet50_CSDSMar17shuffle1_50000_full.pickle
analyzeDLC_resnet50_CSDSMar17shuffle1_50000_meta.pickle
analyzeDLC_resnet50_CSDSMar17shuffle1_50000filtered.h5

Here is the code run in the cells above:
![image](https://user-images.githubusercontent.com/129159855/228524890-72a6e8c8-a651-4325-8b06-d8c5821d64a1.png)
![image](https://user-images.githubusercontent.com/129159855/228525826-8fdce840-33ce-4c26-b738-508718a11158.png)
![image](https://user-images.githubusercontent.com/129159855/228525169-d55a3b5a-7506-4408-bb58-3c359c22a396.png)

**Comment by ssy5425** [comment]
Try version 2.2.3

**Comment by jeylau** [comment]
@Sere-98, try passing `track_method='ellipse'` to `create_labeled_video`. I think this is the argument you're missing, which by default is empty.

**Comment by SGasperoni** [comment]
@jeylau Actually I used that 
![image](https://user-images.githubusercontent.com/129159855/228562654-805b6553-6d20-4563-b42e-ad6c6e94ada7.png)
Here track_method=tracktype, where tracktype was defined as ellipse in the cell above:
![image](https://user-images.githubusercontent.com/129159855/228562894-bead9ad1-a19f-49de-a5dd-6b66bd96a29d.png)

**Comment by jeylau** [comment]
Yes, but it should be passed to "create_labeled_video" too.
Otherwise DLC looks for analyzeDLC_resnet50_CSDSMar17shuffle1_50000.h5 rather than analyzeDLC_resnet50_CSDSMar17shuffle1_50000_el.h5

**Comment by SGasperoni** [comment]
@jeylau Now it works, thank you!! ☺️☺️☺️

**Comment by jeylau** [comment]
Awesome!😊
