### ISSUE TITLE
IndexError when trying to run DLC 2.3.3 Model Zoo 

### ISSUE THREAD

**Issue by KimSilvaA** [DeepLabCut/DeepLabCut#2193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello,

I've been hoping to use the Model Zoo for our video analysis but couldn't get it to run. I tried using the Model Zoo in the non-GUI version but have the same issue when I use the GUI. My video is 22 seconds long and the resolution is 1600 x 1200. Thanks in advance. 

### Operating System

Windows 11 

### DeepLabCut version

2.3.3 GUI 

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

1. Start the GUI
2. Click Model Zoo
3. Choose Video and select superanimal_topviewmouse
4. Hit Run 

### Relevant log output

```shell
(base) C:\Windows\System32>conda activate dlc_gpu

(dlc_gpu) C:\Windows\System32>python -m deeplabcut
Loading DLC 2.3.3...
Starting GUI...
Traceback (most recent call last):
  File "C:\Users\Kellendonk_Analysis\anaconda3\envs\dlc_gpu\lib\site-packages\deeplabcut\gui\tabs\modelzoo.py", line 112, in run_video_adaptation
    deeplabcut.video_inference_superanimal(
  File "C:\Users\Kellendonk_Analysis\anaconda3\envs\dlc_gpu\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_supermodel.py", line 95, in video_inference_superanimal
    adapter.before_adapt_inference(make_video=False)
  File "C:\Users\Kellendonk_Analysis\anaconda3\envs\dlc_gpu\lib\site-packages\deeplabcut\modelzoo\api\spatiotemporal_adapt.py", line 111, in before_adapt_inference
    self.init_weights, _ = superanimal_inference.video_inference(
  File "C:\Users\Kellendonk_Analysis\anaconda3\envs\dlc_gpu\lib\site-packages\deeplabcut\modelzoo\api\superanimal_inference.py", line 313, in video_inference
    init_weights = os.path.abspath(snapshots[0]).replace(".index", "")
IndexError: list index out of range
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
can you give us more information; what model are you trying to use? can you give us the full traceback for what you tried in the terminal as well? thanks cc @yeshaokai

**Comment by aloksneurobot1** [comment]
I have a similar issue. I found that  "C:\Users\user\anaconda3\envs\DEEPLABCUT\Lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\superanimal_topviewmouse_weights" is empty without the weights. 
I installed DLC 2.2.3, windows 10, nvidia 3070 and tried to run superanimal_topviewmouse through Modelzoo tab in the GUI.

**Comment by jeylau** [comment]
Can other model weights be downloaded on your machines (e.g., ResNet 101 when creating a `full_human` pretrained project)? I wonder whether it could be due to a permission issue.

**Comment by MMathisLab** [comment]
If you don't open the terminal "as an admin" in Windows it will not allow downloads and will be empty.

**Comment by KimSilvaA** [comment]
> can you give us more information; what model are you trying to use? can you give us the full traceback for what you tried in the terminal as well? thanks cc @yeshaokai

Thank you for getting back. I'm trying to use the model superanimal_topviewmouse. I believe I included the full traceback but please let me know if you need more information. I also opened the terminal as an admin.

**Comment by yeshaokai** [comment]
@mightbeamouse 
Can I have you put some print in the code block ?https://github.com/DeepLabCut/DeepLabCut/blob/main/deeplabcut/modelzoo/api/superanimal_inference.py#L297

Before you run the code again, delete the weight folder and 
print(weight_folder)
one line above " download_huggingface_model(superanimal_name, weight_folder)"

So we know if it ever tries to download the weight and whether the weight is downloaded into the correct folder.

**Comment by KimSilvaA** [comment]
I deleted the weight folder and ran the code. This is what I got now. 

<img width="671" alt="Screenshot 2023-04-03 141304" src="https://user-images.githubusercontent.com/124469197/229580514-5f204837-6612-4b82-bc6e-ba72cb3acd70.png">

**Comment by yeshaokai** [comment]
Sorry I meant deleting the weight_folder from your PC. Because once the folder was created, it won't try downloading it again. Can you put back 
 weight_folder = str(
        Path(dlc_root_path)
        / "pose_estimation_tensorflow"
        / "models"
        / "pretrained"
        / (superanimal_name + "_weights")
    )

And do

   if superanimal_name in MODELOPTIONS:
        if not os.path.exists(weight_folder):
            print(weight_folder) 
            download_huggingface_model(superanimal_name, weight_folder)

**Comment by KimSilvaA** [comment]
Sorry I misunderstood. I put that part of the script back and printed weight_folder. Now I got this:

(dlc_gpu) C:\Users\Kellendonk_Analysis\anaconda3\envs\dlc_gpu\Lib\site-packages\deeplabcut\modelzoo\api>python -m deeplabcut
Loading DLC 2.3.3...
Starting GUI...
Downloading (…)n-0_shuffle-1.tar.gz: 100%|██████████████████████████████████████████| 235M/235M [00:07<00:00, 30.5MB/s]
Traceback (most recent call last):
  File "C:\Users\Kellendonk_Analysis\anaconda3\envs\dlc_gpu\lib\site-packages\deeplabcut\gui\tabs\modelzoo.py", line 112, in run_video_adaptation
    deeplabcut.video_inference_superanimal(
  File "C:\Users\Kellendonk_Analysis\anaconda3\envs\dlc_gpu\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_supermodel.py", line 95, in video_inference_superanimal
    adapter.before_adapt_inference(make_video=False)
  File "C:\Users\Kellendonk_Analysis\anaconda3\envs\dlc_gpu\lib\site-packages\deeplabcut\modelzoo\api\spatiotemporal_adapt.py", line 111, in before_adapt_inference
    self.init_weights, _ = superanimal_inference.video_inference(
  File "C:\Users\Kellendonk_Analysis\anaconda3\envs\dlc_gpu\lib\site-packages\deeplabcut\modelzoo\api\superanimal_inference.py", line 300, in video_inference
    download_huggingface_model(superanimal_name, weight_folder)
  File "C:\Users\Kellendonk_Analysis\anaconda3\envs\dlc_gpu\lib\site-packages\dlclibrary\dlcmodelzoo\modelzoo_download.py", line 67, in download_huggingface_model
    hf_hub_download(repo_id, targzfn, cache_dir=str(target_dir))
  File "C:\Users\Kellendonk_Analysis\anaconda3\envs\dlc_gpu\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Kellendonk_Analysis\anaconda3\envs\dlc_gpu\lib\site-packages\huggingface_hub\file_download.py", line 1337, in hf_hub_download
    _create_symlink(blob_path, pointer_path, new_blob=True)
  File "C:\Users\Kellendonk_Analysis\anaconda3\envs\dlc_gpu\lib\site-packages\huggingface_hub\file_download.py", line 873, in _create_symlink
    _support_symlinks = are_symlinks_supported(os.path.dirname(os.path.commonpath([abs_src, abs_dst])))
  File "C:\Users\Kellendonk_Analysis\anaconda3\envs\dlc_gpu\lib\ntpath.py", line 763, in commonpath
    raise ValueError("Paths don't have the same drive")
ValueError: Paths don't have the same drive

**Comment by yeshaokai** [comment]
I see. I think this was the true error. This error is saying that it cannot create symbolic link between two drives, a very Windows specific error. 

Can you go to 

File "C:\Users\Kellendonk_Analysis\anaconda3\envs\dlc_gpu\lib\site-packages\huggingface_hub\file_download.py", line 873, in _create_symlink
_support_symlinks = are_symlinks_supported(os.path.dirname(os.path.commonpath([abs_src, abs_dst])))

and print abs_src and abs_dst before it throws this error? I want to understand why the huggingface library wants to create a symbolic link for downloading the weight file. Make sure you remove the folder again.

**Comment by kruettner** [comment]
I did observe the same error message as described by mightbeamouse and similar to aloksneurobot1 finding  "C:\Users\user\anaconda3\envs\DEEPLABCUT\Lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\superanimal_topviewmouse_weights" to be empty.  I tried to circumvent it, by manually downloading the DLC_ma_supertopview5k_resnet_50_iteration-0_shuffle-1.tar.gz file and placing it into the folder- without success. I also tried to extract the file and manually navigate to the snapshot and did not work either. Finally, i tested to generate a new project with the superanimal_topviewmouse mouse with the same result (see error below). Any help on this issue would be very welcome.

![DLCerror](https://user-images.githubusercontent.com/103006047/230387354-02cfd74c-bbf3-47b5-8005-2a97c4639a51.png)

**Comment by yeshaokai** [comment]
@kruettner It seems to me the issue was caused by huggingface_hub library and for some reason we couldn't reproduce the issue in our windows machine.  But I do agree downloading the weights manually should be a temporary solution to fix it. So instead of putting the tar file in the weight folder (which was empty in your case), can you unzip it and make sure those snapshot files are in the weight folder? Once the weight folder is created (and being empty), the huggingface_hub won't try to download weights again and then you can put the snapshots in the weight folder.

**Comment by kruettner** [comment]
> @kruettner It seems to me the issue was caused by huggingface_hub library and for some reason we couldn't reproduce the issue in our windows machine. But I do agree downloading the weights manually should be a temporary solution to fix it. So instead of putting the tar file in the weight folder (which was empty in your case), can you unzip it and make sure those snapshot files are in the weight folder? Once the weight folder is created (and being empty), the huggingface_hub won't try to download weights again and then you can put the snapshots in the weight folder.

I tested this already earlier. However, even when adjusting the path to the weighs in the pose_cfg.yaml it will result in an IndexError.

<img width="667" alt="image" src="https://user-images.githubusercontent.com/103006047/230629418-9c1b2f7b-3002-4e4b-bfd5-86ed03915bf6.png">

**Comment by yeshaokai** [comment]
After you unzip the weights from the tar, what is the current path of the snapshot files?

Note setting "init_weights" in pose_cfg wouldn't prevent this indexerror.

The code is expecting snapshot files under 
Your_DLC_ROOT/deeplabcut/pose_estimation_tensorflow/models/pretrained/superanimal_name_weights/

**Comment by kruettner** [comment]
Thanks, indeed the tar file has been unzipped to the wrong folder. After moving the snapshot to the correct folder everything seems to work.

**Comment by KimSilvaA** [comment]
> I see. I think this was the true error. This error is saying that it cannot create symbolic link between two drives, a very Windows specific error.
> 
> Can you go to
> 
> File "C:\Users\Kellendonk_Analysis\anaconda3\envs\dlc_gpu\lib\site-packages\huggingface_hub\file_download.py", line 873, in _create_symlink _support_symlinks = are_symlinks_supported(os.path.dirname(os.path.commonpath([abs_src, abs_dst])))
> 
> and print abs_src and abs_dst before it throws this error? I want to understand why the huggingface library wants to create a symbolic link for downloading the weight file. Make sure you remove the folder again.

Hello again,
I tried printing abs_src and abs_dst but I don't think I see them in the terminal. 

<img width="1423" alt="Screenshot 2023-04-10 123610" src="https://user-images.githubusercontent.com/124469197/230935328-4ad130c9-75a5-4b83-b995-533a6926e646.png">

**Comment by yeshaokai** [comment]
@mightbeamouse 

As a temporary solution, do you mind if you also manually download the model file: 
https://huggingface.co/mwmathis/DeepLabCutModelZoo-SuperAnimal-TopViewMouse/blob/main/DLC_ma_supertopview5k_resnet_50_iteration-0_shuffle-1.tar.gz

and unzip it and copy everything into the folder that was empty?

**Comment by KimSilvaA** [comment]
> @mightbeamouse
> 
> As a temporary solution, do you mind if you also manually download the model file: https://huggingface.co/mwmathis/DeepLabCutModelZoo-SuperAnimal-TopViewMouse/blob/main/DLC_ma_supertopview5k_resnet_50_iteration-0_shuffle-1.tar.gz
> 
> and unzip it and copy everything into the folder that was empty?

It works! Thank you so much for your help.

**Comment by yeshaokai** [comment]
@mightbeamouse Thanks! Let us know if there are failure modes for the model. White objects in the background or unusual resolutions can be problems. We will keep improving the models with more data.

**Comment by MalNeuro** [comment]
I had the same problem - it's caused by lines 1209-1215 in huggingface_hub.file_download

    if os.name == "nt" and len(os.path.abspath(lock_path)) > 255:
        lock_path = "\\\\?\\" + os.path.abspath(lock_path)

    if os.name == "nt" and len(os.path.abspath(blob_path)) > 255:
        blob_path = "\\\\?\\" + os.path.abspath(blob_path)

the whole string - including the added symbols before the drive letter - gets passed to create_relative_symlink() (line 1255),
hence the ValueError thrown by os.commonpath(). Editing file_download.py directly to add  

    blob_path=blob_path.strip("\\\\?\\")

before calling create_relative_symlink()  solves the problem and has not caused any other errors (so far...)

**Comment by AlexEMG** [comment]
We will fix this! 

Btw, the overall issue is also discussed here https://github.com/DeepLabCut/DeepLabCut/issues/196

**Comment by plant1987** [comment]
Hi there! 
@yeshaokai @MMathisLab 
I get the same problems when use the superanimal. I followed the steps describled above to manunlly download the .gz file and unzip it and put all the files to the MY_DLC_ROOT/deeplabcut/pose_estimation_tensorflow/models/pretrained/


I found there is no folder named 'superanimal_topviewmouse_weights'.

And then, I manually create this new 'superanimal_topviewmouse_weights' folder and put all the unzip files in it.  However, the same error still occur

![屏幕截图 2024-04-05 170015](https://github.com/DeepLabCut/DeepLabCut/assets/71976453/4ca39663-a905-4fad-8db4-b5a6cb9d2738)

![屏幕截图 2024-04-05 170057](https://github.com/DeepLabCut/DeepLabCut/assets/71976453/7da49987-e17d-42b2-a572-806a81535af0)

![屏幕截图 2024-04-05 170117](https://github.com/DeepLabCut/DeepLabCut/assets/71976453/ee579271-f33d-4d6e-a7f9-76163b292f50)
