### ISSUE TITLE
Use the latest github code in Google Colab

### ISSUE THREAD

**Issue by SGasperoni** [DeepLabCut/DeepLabCut#2195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi,
Is there any way to use the latest Github code in Google Colab?
I've found the website where it is explained how to do so from the terminal, but couldn't find how to do it from google colab, and everything I tried does not seem to work.

Alternatively, is it possible to import the training dataset created locally to google colab? When i do that, and start the training it gives me the error: 
"FileNotFoundError: Config file is not found. Please make sure that the file exists and/or that you passed the path of the config file correctly!"

### Operating System

windows 11

### DeepLabCut version

2.3.2

### DeepLabCut mode

multi animal

### Device type

google colab gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @Sere-98, install deeplabcut like in the superanimal COLAB example: `!pip install "deeplabcut[tf,modelzoo] @ git+https://github.com/DeepLabCut/DeepLabCut@main"`, this will fetch the current code from github. As for the training dataset, make sure you move the whole project folder (config.yaml, labeled-data, and training-datasets) to COLAB, and it works.

**Comment by SGasperoni** [comment]
@jeylau Thank you so much!!
