### ISSUE TITLE
How to analyze pose estimation result with PCA?

### ISSUE THREAD

**Issue by tctco** [DeepLabCut/DeepLabCut#2196]
In this paper https://doi.org/10.1038/s41592-022-01443-0 the authors mentioned a trick using PCA to capture some egocentrically aligned poses. Is this feature implemented in DLC? Could you please give me some guidance on how to do that?

Thanks in advance!

**Comment by jeylau** [comment]
Hi @tctco, take a look at a this demo notebook in our DLC2Kinematics repo https://github.com/AdaptiveMotorControlLab/DLC2Kinematics/blob/master/DEMO.ipynb. Cells 15 and 19 show how you could use `dlc2kinematics.compute_pca` or `dlc2kinematics.plot_3d_pca_reconstruction` to reduce the dimensionality of the data and optionally project it back in the original space so you could visualize what the poses are (as we did in the paper). The only step required prior to that is for you to align the poses, which typically requires you to define (at least) the long axis of the body, and rotate poses individually so, e.g., they all point up. I can provide you with more guidance if you let me know what your data/animals look like 😊

**Comment by tctco** [comment]
Hi @jeylau, Thanks for your elaboration! In your paper, it seems that you can encode the 'motion' (instead of only the postures) of the animal in a short time period with PCA and reconstruct this 'motion'. I'm wondering how I can achieve this, too :)
