### ISSUE TITLE
macOS Monterey 12.2.1 error: label_frames() unable to find /src/napari_deeplabcut/assets/unlock.svg

### ISSUE THREAD

**Issue by lindsayveazey** [DeepLabCut/DeepLabCut#2197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When I try to run `deeplabcut.label_frames(path_config)`

I get the following error- which was previously marked as resolved, but is still happening for me:

`WARNING: Cannot open file '..../src/napari_deeplabcut/assets/unlock.svg', because: No such file or directory`

### Operating System

macOS Monterey 12.2.1

### DeepLabCut version

DLC 2.3.3

### DeepLabCut mode

single animal

### Device type

Unsure...

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
It's a warning (so don't worry about it), and has been fixed with https://github.com/DeepLabCut/napari-deeplabcut/commit/6749c01a84c5de6038e6c3dba77edcd9abdcbf85. The fix will be live when I release napari-deeplabcut 0.1.2 😊
