### ISSUE TITLE
3mice demo zip no longer exists

### ISSUE THREAD

**Issue by iyzg** [DeepLabCut/DeepLabCut#2200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

The [original data](http://deeplabcut.rowland.harvard.edu/datasets/demo-me-2021-07-14.zip) that contains the data for the demo no longer exists. I was also unable to track it down anywhere online, and the closest thing I could find was [this dataset.](https://zenodo.org/record/5851157#.YeHC23vMJhE)

### Operating System

macOS Ventura, error was in Google Colab

### DeepLabCut version

dlc version 2.3.3

### DeepLabCut mode

multi animal

### Device type

Google Colab CPU

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hello @iyzg, the 3mice dataset can now be found on Zenodo at https://zenodo.org/record/5851157. I'll update the Colab notebook. 😊

**Comment by MMathisLab** [comment]
@iyzg data is now here: https://zenodo.org/record/7883589#.ZE_JDOxBz0o

@jeylau notebook updating now!
