### ISSUE TITLE
FileNotFound Error with create_training_dataset and Documentation_data- folder

### ISSUE THREAD

**Issue by swarupsamip** [DeepLabCut/DeepLabCut#2201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

After labeling, create_training_dataset outputs an error(screenshots below) with the Documentation_data- folder and a pickle file. I don't actually see the folder or file when searching for it in file manager or terminal. Still have this issue even after updating to dlc 2.3.3. Config file seems correct, but I've attached as many relevant screenshots below for any help. Please let me know if I can clarify in any way. Thank you.

### Operating System

Ubuntu 22.04 jammy

### DeepLabCut version

dlc version 2.3.0 and 2.3.3

### DeepLabCut mode

single animal

### Device type

NVIDIA GeForce RTX 3090/AMD Ryzen 9 5950X

### Steps To Reproduce

ipython output
![error](https://user-images.githubusercontent.com/83462789/230982642-20533249-f040-4ff4-b81e-6e1f31d061e7.png)
config file
![config](https://user-images.githubusercontent.com/83462789/230983331-022331b8-e5aa-4e64-860f-c99d58afac1c.png)
as far as I could go with the path specified in the error
![path](https://user-images.githubusercontent.com/83462789/230982997-e568ff80-c942-423d-97cc-c62dd4ce4f6c.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @swarupsamip, `Task` looks wrong to me; judging from your project path, it should be `PeriphDreadss_dlc`. Those variables do not typically require edits: `task` is defined when first creating the project, and `project_path` is automatically updated even is the project is moved around.

**Comment by swarupsamip** [comment]
That was it! I don't know how that happened, but it seems to be working fine now. Thank you!
