### ISSUE TITLE
deeplabcut.create_training_dataset hangs in COLAB

### ISSUE THREAD

**Issue by inmetal2002** [DeepLabCut/DeepLabCut#2204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Using one of the examples from /examples/COLAB/COLAB_YOURDATA_TrainNetwork_VideoAnalysis.ipynb, COLAB hangs when running deeplabcut.create_training_dataset

### Operating System

COLAB

### DeepLabCut version

2.3.3

### DeepLabCut mode

single animal

### Device type

COLAB GPU TESLA T4

### Steps To Reproduce

Run /examples/COLAB/COLAB_YOURDATA_TrainNetwork_VideoAnalysis.ipynb with relevant uploaded file structure and labelled data.

Hangs on deeplabcut.create_training_dataset(path_config_file, net_type='resnet_50', augmenter_type='imgaug')

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by inmetal2002** [comment]
I don't know whether this is relevant or not or has to do with file pointers, but when I stop cell that hangs in COLAB, it always pops out at the same line number 2984 in the Image.py module in the PIL library

[/usr/local/lib/python3.9/dist-packages/PIL/Image.py]  in open(fp, mode, formats)

-> 2984     prefix = fp.read(16)

**Comment by inmetal2002** [comment]
After a bit more digging, this is where it hangs in COLAB

create_training_dataset()>format_training_data()>read_image_shape_fast()>open()

**Comment by jeylau** [comment]
Hi @inmetal2002, I could not reproduce this behavior. Does `deeplabcut. create_training_dataset ` run locally? If it does, then you only need to upload the content of the `training-datasets` folder to Colab.

**Comment by inmetal2002** [comment]
Many thanks for checking it out. Yes creating training data set can be run
locally....for resnet_50. But I run into memory issues with my lower end
GPU when I look into creating training set with resnet_101 etc....hence
colab.

I suspect there is a path issue going on somewhere from exporting the
original labelled data from windows into colab and then creating training
data set from there.

For example, I can create training data set locally on windows and start
training for resnet_50. I can then export whole project, adjust the paths,
and continue training on colab. No problem at all.

But if I do an initial export of a project with labelled data, adjust the
paths again, and attempt to create training data set in colab, it hangs.

**Comment by jeylau** [comment]
Thanks for the clarification! By "exporting the original labelled data", do you mean uploading your project to the Drive? Or are you manipulating the data in some way beforehand? Typically, you annotate your data locally, and then upload your project into the Cloud. DeepLabCut will automatically update the relevant paths (e.g., the project path; others, like the image paths, are relevant to this very project path, and are OS-agnostic, so they should not cause any problem anyway).

**Comment by inmetal2002** [comment]
Thanks again. Just uploading to Drive, no manipulation

**Comment by MMathisLab** [comment]
>> I suspect there is a path issue going on somewhere from exporting the
original labelled data from windows into colab and then creating training
data set from there.

>> But if I do an initial export of a project with labelled data, adjust the
paths again, and attempt to create training data set in colab, it hangs.

You shouldn't have to adjust any paths; the only path that would be needed to be updated is the `project_path` in the config.yaml file, but this has been handled automatically for some years now

**Comment by MMathisLab** [comment]
I can confirm this is working for me, so I will close!
