### ISSUE TITLE
Can't create plot video

### ISSUE THREAD

**Issue by tokioshima** [DeepLabCut/DeepLabCut#2207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello!
I a beginner on DLC, I have the 2.3.3 version and I work with the GUI.
When I try to create video after the “analyze video” part, at the bottom of the GUI I have this message : “Plots could not be created for C:/Users/Manip2/Desktop/oui-non-2023-04-17/videos/2207 jessy 4.mp4. Videos were not evaluated with the current scorer DLC_resnet50_ouiApr17shuffle1_10.” only when I check the box "Plot trajectories". 
When I don't check this box I have this message : "Failed to create videos from C:/Users/Manip2/Desktop/oui-non-2023-04-17/videos/2207 jessy 4.mp4"
Any idea to help me?

### Operating System

Windows 10 Pro

### DeepLabCut version

2.3.3

### DeepLabCut mode

single animal

### Device type

cpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Can you confirm that h5 data files were written in your videos folder after video analysis? They should end in `DLC_resnet50_ouiApr17shuffle1_10.h5`.

**Comment by tokioshima** [comment]
Yes it is! but his name end by " 1DLC_resnet50_ouiApr17shuffle1_10.h5"

**Comment by jeylau** [comment]
Is it maybe because you've analyzed a video called `2207 jessy 1.mp4`? Otherwise, for the video file you mentioned, the h5 file should have been created by DeepLabCut with the name `2207 jessy 4DLC_resnet50_ouiApr17shuffle1_10.h5`.

**Comment by tokioshima** [comment]
I try to start over "analyze video" and "create video" with my video named "2207 jessy 1" and the same error message appear at bottom of the GUI :(

**Comment by Temp2Spec** [comment]
I have the exact same problem (Win 11, GPU, DLC 2.3.2). Labelled and trained with no problem at all. 

I trained my net on April 17th as well. Just to make sure there is nothing wrong with that date (for whatever reason), I changed the date on config, file names and everything else to Apr18 and the same problem appears. 

Have you had any ideas??

**Comment by jeylau** [comment]
I tried to reproduce this behavior (on macOS though) but could not. Even spaces in the file name are handled fine. I did spot one small 🐛 preventing the creation of the plots, but video analysis alone runs fine.
@Temp2Spec, what fails exactly? Both cases like described above by @tokioshima?

**Comment by Temp2Spec** [comment]
Thank you! Yeah, exactly the same problems. Both when plots clicked and unclicked. I checked the names, the length of the paths etc, Does the video name ending on a number have to do with it? Mine are just numbers?

**Comment by jeylau** [comment]
@Temp2Spec, I don't think so, as I tried it with the names above too and had no problem with it. I'll try again on a Windows machine in a moment, and get back to you.

**Comment by tokioshima** [comment]
@jeylau I fix the attributeError you have share previously but now my dlc can't extract frames. After dlc have read the config files succesfully, there is a traceback error appear but I can't read it due to a loading bar in front of it.
I tried to reinstall it by deleting the dlc environment in anaconda but it's the same result. help plz

**Comment by jeylau** [comment]
@tokioshima, can you share an error you may be getting? It's hard for me to help you otherwise.

**Comment by Temp2Spec** [comment]
@jeylau I'm sending this to let you know that I have just updated DLC to 2.3.3 and now it analysed the videos. :) Still not sure what the bug was though. 
Thank you for your time and effort!
A

**Comment by tokioshima** [comment]
ok @jeylau I retry with another project this morning and the "extract frames" part work, that's the main thing.

So with this project, I try to analyze video to see, with the fix you share yesterday, if it's work.
Unfortunately it didn't work but here is what it showed me:
![new bug](https://user-images.githubusercontent.com/130998972/233340423-694363fb-e00e-4aa3-ba90-716f8ab6c79d.PNG)

Maybe I didn't fix the attribute error well so I post you a picture of my analyze_videos.py with the part I modified in highlighted :
![image de analyze videos](https://user-images.githubusercontent.com/130998972/233340864-eadc9bde-01ff-43f7-a5f0-d0d9e9f85873.PNG)

Thank you in advance for your help!

**Comment by jeylau** [comment]
@tokioshima, the indentation is wrong. You have `if`, `try`, `except` and the `else` all at the same level, whereas the `try/except` block should be one tab to the right.

**Comment by tokioshima** [comment]
ok my bad!
So I try to start over with another new project and when I get to the "create videos" step, the same error message appears at the bottom of the GUI unfortunately :/

**Comment by jeylau** [comment]
The error is not very readable in the status bar; is it also written in the terminal you used to launch the GUI?

**Comment by tokioshima** [comment]
I put you GUI and terminal screenshot in my message
![terminal error](https://user-images.githubusercontent.com/130998972/233366459-4f112ec8-79c4-4528-b410-f7bf6cd6c6e4.PNG)


![GUI error](https://user-images.githubusercontent.com/130998972/233366467-c562ce1f-31bc-4ea1-9ba7-7761548a2fbc.PNG)

Hope that will help you!

**Comment by jeylau** [comment]
Could you also show me what h5 data files were created in the `videos` folder after running video analysis?

**Comment by tokioshima** [comment]
This is what I have after running video analysis in the videos folder : 

![h5 files error](https://user-images.githubusercontent.com/130998972/233379623-423bb4ba-b67d-4fe4-a453-5cb620484bbf.PNG)

**Comment by jeylau** [comment]
if you untick `use filtered data` in the GUI, does it run then?

**Comment by tokioshima** [comment]
oh it worked, a video has been created but it still doesn't contain any marking on it :/
There is also a folder named "plot-poses" which contains blank graphs ("hist", "plot", "plot-likelihood", "trajectory")
Do you have any idea why it does this?

![hist error](https://user-images.githubusercontent.com/130998972/233382344-9ad26631-10c1-451d-8c3d-c53810d51847.PNG)

![plot error](https://user-images.githubusercontent.com/130998972/233382365-7e92692a-5b1d-4bca-871f-80afe84f7dc1.PNG)

![plot-likelihood error](https://user-images.githubusercontent.com/130998972/233382387-759dd07b-3254-420a-9345-c4994fe8a466.PNG)

![trajectory error](https://user-images.githubusercontent.com/130998972/233382400-087832cf-9190-40f8-959f-eea3931c2af4.PNG)

**Comment by jeylau** [comment]
Judging from the file names, it looks like you trained for 1000 iterations only, which is way too short, and may explained why your network is not picking anything meaningful. Importantly, and before analyzing/creating labeled videos, are you satisfied with the performance of your network (the train/test error that is printed after your network is evaluated)? Have you looked at the detections on the test set (which you get in the GUI by ticking `plot predictions`)? Is there any reason you're using mobilenets instead of the default network? 
Start again slowly from network evaluation, make sure you're happy with the way it performs before you can continue and confidently analyze your videos. This section specifically of the docs is quite relevant (https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html#h-evaluate-the-trained-network).

I hope this helps!

**Comment by tokioshima** [comment]
Thanks you for all your advice and for your time!!

Have a good day!! :)

**Comment by VistiStenmo** [comment]
Hi. 

I have the "Failed to create videos from C:/Users/" problem, in the exact same environment as Temp2Spec. I tried to update to 2.3.3, which seemed to resolve the problem, but it didn't work for me. I tried to update to 2.3.4, but the same problem prevails. It won't let me create videos. 

Do you have any advice?

**Comment by VistiStenmo** [comment]
I have found that the problem is dependent on the Filtered Data option. If i do not use unfiltered data, the videos are created. If i do use it, it fails to create the videos.

**Comment by ziminguo** [comment]
> Can you confirm that h5 data files were written in your videos folder after video analysis? They should end in `DLC_resnet50_ouiApr17shuffle1_10.h5`.

Hi! I got the same issue and may I please ask where can I check that the h5 data files exists? Thank you!
