### ISSUE TITLE
Cannot use latest github code in local machine.

### ISSUE THREAD

**Issue by SGasperoni** [DeepLabCut/DeepLabCut#2209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi,
I opened an issue some weeks ago about not being able to use the latest Github code on Google Colab (which was solved #2195). I have now a workstation with GPU, so I'm trying to analyse my videos there. The problem is that I cannot seem to import the latest version (following the tutorial here https://github.com/DeepLabCut/DeepLabCut/wiki/How-to-use-the-latest-GitHub-code ).
I.e., when I run deeplabcut.__file__ the init.py that is used is the one from the conda environment and not from path../DeepLabCut/deeplabcut/__init__.py.
![image](https://user-images.githubusercontent.com/129159855/232847831-46773bab-053d-4e7c-aeb7-02ac4b063b48.png)
 In fact, I keep having the problem I had at the beginning where animal identities were randomly assigned (which was then solved, and worked importing the latest code from github in colab (#2192 )).

### Operating System

Windows 11

### DeepLabCut version

2.3.2

### DeepLabCut mode

multi animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
@Sere-98, open the terminal, activate your conda environment, `cd` into the DeepLabCut folder that you cloned, but instead of immediately calling `ipython`, call instead:
`pip install -e .`
The dot is important and indicates that you want the local directory (i.e., DeepLabCut) to be installed in your environment. Let me know if that helps 😃

**Comment by SGasperoni** [comment]
@jeylau It works, thank you so much for your quick reply! 😃😃😃

**Comment by jeylau** [comment]
Awesome!
