### ISSUE TITLE
minimum image size (current default is 100 pixels)

### ISSUE THREAD

**Issue by lgend** [DeepLabCut/DeepLabCut#222]
I'm using a desktop with Ubuntu 16.04 LTS, anaconda env, deeplabcut 2.05, and an nvidia TITAN xp gpu
 
**Describe the bug**
For 2 days I couldn't figure out what was causing deeplabcut to get stuck in training (specifically train_network just gets stuck before any training occurs and does not print any useful error info). I was able to use it a few days ago on a slightly different test case. I tried all the solutions from previous issues with similar problem (making sure GPU doesn't have any other running processes, making sure the Config.yaml file is correct, etc...). Finally I realized that the only thing I changed since it worked on the previous test case was the image size - previously it was 384 x 384, but now I went down to 94x94. I zoomed my images back to 384x384, started a new project, relabeled the training frames, and now the training runs again just fine.   

**To Reproduce**
Just follow the "Demo_yourowndata.ipynb" notebook from the provided examples, with a dataset where your images are small (94x94 in my case). 

**Expected behavior**
When you go through the first few steps and run "train_network" it will get stuck. It won't report any errors. It will just be stuck. If you run "nvidia-smi" you will see the process properly sitting on the GPU but no training will occur. 

I think there needs to be some documentation about minimum image size required for training. Additionally there should be some error thrown by train_network, it shouldn't just get stuck without any useful feedback!

**Comment by AlexEMG** [comment]
Currently the minimum size is set to nx x ny < 100**2, see https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/pose_estimation_tensorflow/dataset/pose_dataset.py#L194

You can change that number there. But I would not train with much smaller images than lets say 64 x 64. I think I will make this a parameter in the next version. Notice that due to automatic rescaling your 94x94 would probably go above 100 from time to time (depending on the settings).

**Comment by MMathisLab** [comment]
(so while it may have run very slowly until it hit an image that was scaled above 100, it was likely actually running beforehand too). I will close the issue now, but we can add this as a parameter in the next version.

**Comment by lgend** [comment]
Got it. Thanks for explaining that. It would definitely be helpful to have minimum image size as a parameter in the next version!

**Comment by AlexEMG** [comment]
Ok, going forward (starting with 2.0.5.1) there is a variable ```min_input_size``` that sets this. Currently it is set to 64 pixels. (I would not make it much smaller)
