### ISSUE TITLE
FileNotFoundError: Config file not found when training model in DeepLabCut

### ISSUE THREAD

**Issue by Nike-Nay** [DeepLabCut/DeepLabCut#2229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am able to create a project, extract frames, label frames without any issues. However, once I attempt to check the labels using _deeplabcut.check_labels(path_config_file, visualizeindividuals = True/False)_, I get a **'FileNotFoundError: Config file is not found. Please make sure that the file exists and/or that you passed the path of the config file correctly!'**

If I skip this step and attempt to train the model by using _deeplabcut.create_training_dataset(path_config_file, augmenter_type='imgaug')_, I get the same error. 

I am able to create the training set through the GUI. However, once I attempt to start training the network, it does not start and the GUI becomes unresponsiveness. I assume this is linked to the initial error which I described above.

The first two screenshots are in relation to the FileNotFoundError. The second two screenshots are the log ouput of when I attempt to train the network through the GUI and it becomes unresponsive.
![Screenshot (60)](https://user-images.githubusercontent.com/127593957/235969417-b8759452-5654-45d4-a338-36194d025c59.png)
![Screenshot (61)](https://user-images.githubusercontent.com/127593957/235969419-15ee9edf-d277-4eb3-9d0b-1e799147d35b.png)
![Screenshot (62)](https://user-images.githubusercontent.com/127593957/235969891-4d416688-6f0d-4248-a783-6afb276da619.png)
![Screenshot (63)](https://user-images.githubusercontent.com/127593957/235969899-ddd6aad7-ea88-46e7-a68e-c6cc627262ca.png)

### Operating System

Windows 10

### DeepLabCut version

2.3.4

### DeepLabCut mode

single animal

### Device type

CPU - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
There is a typo in the config path: the extension should be `yaml` and not `ymal`. On Windows, you can hold SHIFT and right-click on your file > Copy as path (see https://github.com/DeepLabCut/DeepLabCut/blob/main/docs/installation.md#step-2-please-use-our-supplied-conda-environment), so you're guaranteed to get the right path 😊
