### ISSUE TITLE
Add manual mode for outlier extraction

### ISSUE THREAD

**Issue by DonnieKim411** [DeepLabCut/DeepLabCut#223]
**Your Operating system and DeepLabCut version**
==> Ubuntu 18.04 and DLC2.0.5 (but I use docker which installs Ubuntu16.04 with DLC2.0.5). I don't use conda (the whole purpose of using Docker image)

**Is your feature request related to a problem? Please describe.**
The way I am using DLC is the following. Suppose I have video1. With video1, I extracted frames, trained, and created a labeled video. Now I have a video2 that needs to be labeled (and similar to video1). I do not wanna label these all over again by hand, so what I did was using `add_new_videos`, i added video2 to my config, analyze using the trained network (from video1), create a labeled video, and watch how it performed. Since it is a domain transfer, the labeled video is less accurate/reliable compared to video1. Some are well labeled, some are bad. On those bad ones, I would like to _manually_ select those frames if I can via `extract_outlier_frames`. Unfortunately, the current settings do not allow the manual extraction.

**Describe the solution you'd like**
Add a manual mode. I think we can reuse the GUI toolbox for `refine_labels` but allows the user to scan the entirety of the video. On the frames that the user considers as an _outlier_,  the user can either move the markers or delete the markers, then save those corrected labels.

**Describe alternatives you've considered**
Can't think of a better way for manual mode

**Additional context**
Described above

**Comment by oliriley** [comment]
The most recent update, 2.0.5, does in fact include this option. Use

deeplabcut.extract_outlier_frames(‘config_path’, ['videofile_path’], outlieralgorithm='manual')

as described in the [function details documentation](https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#j-refinement-extract-outlier-frames). This allows you to scan through the labeled video(s) and select individual frames or chunks of frames to adjust :)

**Comment by DonnieKim411** [comment]
Sweet thank you! I will close this issue then :+1:

**Comment by MMathisLab** [comment]
Ps - to analyze a new video you DO NOT have to add new video to the config file to analyze the video :)

**Comment by DonnieKim411** [comment]
Hmm it is a separate question but along with `manual` mode of the outlier algorithm. With `cropping` set to `True` in `config.yaml`, when I extracted with `non-manual` mode, it used `cropping` coordinates. However, when I did with `manual` mode, it does not use it. I also changed `crop` for the video that I am extracting the outliers from, but even that modification does not crop the frames in the manual mode extraction.

Any suggestion?

**Comment by MMathisLab** [comment]
Crop =True in the config yaml is only for inference (analyze_video). The coordinates below each video are the cropping for frame extraction. One cannot crop the outlier frames, you’d have to crop before running inference on the video. The coorindates would not match otherwise when the h5 is written.
