### ISSUE TITLE
No labeled video produced after running superanimal_topviewmouse from ModelZoo 

### ISSUE THREAD

**Issue by Bhuvanesh1234** [DeepLabCut/DeepLabCut#2235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi

After watching this https://www.youtube.com/watch?v=zT0qCA3YJOI example video of ModelZoo . I tried the superanimal topviewmouse model on the sample video in the repository DeepLabCut/examples/openfield-Pranav-2018-10-30)/videos/. I ran into two issues . The first issue was resolved by this thread https://github.com/DeepLabCut/DeepLabCut/issues/2193 . After the iterations were completed there was a h5 file and a pickle file generated in the video folder but no labeled video was produced 

### Operating System

Windows 10

### DeepLabCut version

2.3.3 GUI

### DeepLabCut mode

single animal

### Device type

cpu

### Steps To Reproduce

1. Start the GUI
2. Click Model Zoo
3. Choose Video and select superanimal_topviewmouse
4. Hit Run

### Relevant log output

```shell
(base) C:\WINDOWS\system32>activate DEEPLABCUT

(DEEPLABCUT) C:\WINDOWS\system32>python -m deeplabcut
2023-05-06 20:40:04.142943: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-05-06 20:40:04.147525: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Loading DLC 2.3.3...
Starting GUI...
C:\Users\Lenovo\miniconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
2023-05-06 20:41:47.338313: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2023-05-06 20:41:47.345830: W tensorflow/stream_executor/cuda/cuda_driver.cc:263] failed call to cuInit: UNKNOWN ERROR (303)
2023-05-06 20:41:47.434137: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-H6FNR0J
2023-05-06 20:41:47.446360: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-H6FNR0J
2023-05-06 20:41:47.454416: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-06 20:41:47.549853: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
100%|████████████████████████████████████████████████████████████████████████████| 2330/2330 [1:35:35<00:00,  2.46s/it]
C:\Users\Lenovo\miniconda3\envs\DEEPLABCUT\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
```

### Anything else?

![dlc_files](https://user-images.githubusercontent.com/46322655/236637874-b37831c4-1fee-4a9d-a16b-f6b344480f1c.PNG)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by yeshaokai** [comment]
@Bhuvanesh1234 Can you show us the code snippet of the way you call our modelzoo api ? Especially the path of your videos. I suspect that the path you gave was wrong or not matching the actual path of the video.

**Comment by MMathisLab** [comment]
@yeshaokai they used the GUI, so we should check this; I suspect it's a permission issue. 


@Bhuvanesh1234 when open terminal did you "right click to open terminal as admin?" otherwise DLC doesn't have access to files.

**Comment by yeshaokai** [comment]
@Bhuvanesh1234 What happen if you set the video_adapt = False and try again? The fact that you have .h5 and meta.pickle in the folder tells me you are one step away from generating the video.  Otherwise, If you had video_adapt = True, can I have you add a print (self.video_path) above
https://github.com/DeepLabCut/DeepLabCut/blob/main/deeplabcut/modelzoo/api/spatiotemporal_adapt.py#LL202C19-L202C29 ?
So we can know what happens to your video path.  Sorry that I don't have a windows-machine in hand. I will borrow one if possible.

**Comment by Bhuvanesh1234** [comment]
@MMathisLab Yes I did run deeplabcut gui with an administrator command prompt but no labeled video was generated only the .h5 and .pickle file were created. @yeshaokai Do you want me to add print(self.video_path) on line 199 before calling the function deeplabcut.create_labeled_video in the file https://github.com/DeepLabCut/DeepLabCut/blob/main/deeplabcut/modelzoo/api/spatiotemporal_adapt.py#LL202C19-L202C29.
Maybe the issue is caused by how file paths are specified in Windows and Linux . Also how can I use the function deeplabcut.create_labeled_video to create the labeled video using the config file supertopview.yaml , and the .mp4, .h5 and .pickle files

**Comment by yeshaokai** [comment]
@Bhuvanesh1234 Yes. Can you print it? 
I think that using the GUI again by specifying video_adapt = False should be equivalent to calling create_labeled_video without hacking that api with supertopview.yaml. Can you give that a try?

**Comment by Bhuvanesh1234** [comment]
@yeshaokai Even after adding the line print(self.video_path) before calling the function deeplabcut.create_labeled_video I get the same log as before , nothing is printed after 100% completion . Also isn't video_adapt equal to False by default in the file  predict_supermodel.py

**Comment by n-poulsen** [comment]
Hi @Bhuvanesh1234! Did you reinstall DeepLabCut with the added `print` statement before call the method again (you need to run `pip install -e .` from the DeepLabCut folder for the changes to take effect).

And could try using the CLI to see if the issue is with the GUI? Simply run:

```python
import deeplabcut

video_file = "path_to_the_video"
deeplabcut.video_inference_superanimal(
    [video_file],
    "superanimal_topviewmouse",
    videotype=".mp4",
    video_adapt=True,
    scale_list=[],
)
```
