### ISSUE TITLE
Why is DontUseNativeDialog specified in project creation

### ISSUE THREAD

**Issue by hmaarrfk** [DeepLabCut/DeepLabCut#2245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Why is DontUseNativeDialog specified in https://github.com/DeepLabCut/DeepLabCut/blob/c2469aba67a9f732a678ba1e47cdf7171b8b0a49/deeplabcut/gui/tabs/create_project.py#L112

It seems like we would want to use native dialogs if we can? It seems to have been added in the latest big update to PySide6
https://github.com/DeepLabCut/DeepLabCut/commit/993a64021762c3b5e2c639ba942f445f66c25a2f

I understand there are still some challenges with PySide6 so maybe i'm missing something

### Operating System

linux + conda-forge

### DeepLabCut version

2.3.4

### DeepLabCut mode

single animal

### Device type

cpu

### Steps To Reproduce

Create a new project
Add videos

Notice that the native dialog isn't use on linux

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @hmaarrfk, this was needed originally because I could not get the dialog window to open on my Mac consistently (and when it did open, it was horribly slow); I have just tried the native dialog again though, and it is no longer a problem, so this will be included in the coming GUI improvements.

**Comment by hmaarrfk** [comment]
Thats super interesting. I don't use macs so I don't see that side of the issues, but I'm very sympathetic to these kind of integration challenges.....
