### ISSUE TITLE
Issue while using the extract_frames function

### ISSUE THREAD

**Issue by Aks0121** [DeepLabCut/DeepLabCut#225]
**Your Operating system and DeepLabCut version**

macOS High Sierra, dlc-macOS-CPU, DeepLabCut 2

**Describe the problem**

When attempting to run the extract_frames function, the following error is returned: 
TypeError: expected str, bytes or os.PathLike object, not NoneType

The entire process:
![screen shot 2019-02-28 at 3 29 02 pm](https://user-images.githubusercontent.com/48101630/53596403-a5c2ec80-3b6d-11e9-8273-bd6c477b95d6.png)

**How to Reproduce the problem**
1. Attempt to apply the extract_frames function
2. See error

**Screenshots**
![screen shot 2019-02-28 at 3 29 02 pm](https://user-images.githubusercontent.com/48101630/53596482-d9057b80-3b6d-11e9-83fd-2b950fce8a7f.png)

**Additional context**
N/A

**Comment by MMathisLab** [comment]
You misspelled “uniform” ;)

**Comment by Aks0121** [comment]
Omg my god :/

Thank you.

**Comment by ZGeeM** [comment]
Hi, I am kinda having the same issue at this step, have you fixed it after correcting the typo? Thanks!

**Comment by Aks0121** [comment]
Hi, unfortunately we moved on to a different project and so did no fully try out DeepLabCut.
