### ISSUE TITLE
Using Pre-Annotated Data in a Different Format Than Usual

### ISSUE THREAD

**Issue by GeneRuan** [DeepLabCut/DeepLabCut#2251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I'm trying to use older data supplied to me by my research group, but due to the way it is formatted, I'm finding trouble with porting it over without being told that there are no labels for any of the given images.

I don't want to relabel all of these images, as that would take far too much time. Is it possible to use this data directly?

This is what a folder of this data looks like:
<img width="643" alt="image_data" src="https://github.com/DeepLabCut/DeepLabCut/assets/114833740/a9a2f355-cd03-44e2-a136-cf43a86ad949">

This is what the labeled images folder looks like:
<img width="787" alt="labeled_images" src="https://github.com/DeepLabCut/DeepLabCut/assets/114833740/435d2079-0dbe-4767-bdfc-6a119f947bb1">

### Operating System

macOS Monterey, Version 12.5.1
MacBook Pro

### DeepLabCut version

2.2.3

### DeepLabCut mode

multi animal

### Device type

Apple M1 Pro

### Steps To Reproduce

For this example, I'm using [this folder of labeled data](https://github.com/DeepLabCut/DeepLabCut/files/11501864/ch1_0727_1200.zip), and [this folder of labeled images](https://github.com/DeepLabCut/DeepLabCut/files/11501866/ch1_0727_1200_labeled.zip), as seen above. This is one folder out of many, but I'm simply trying one before scaling it upward for the rest. These instructions are based on the GUI.

1. Open DeepLabCut. Create a new multi-animal dataset using the images in the first folder. Use the scorer variable "CZ", as that is the scorer variable of these folders, and it is easier to keep this scorer variable than change the others to match.
2. Open the config file, and add body parts, skeleton, and individuals as follows.
```
uniquebodyparts: []
multianimalbodyparts:
- beak
- comb
- blade
- hackle1
- hackle2
- hackle3
- spine1
- spine2
- spine3
- spine4
- tail1
- tail2
- tail3
bodyparts: MULTI!

skeleton:
- - beak
  - comb
- - comb
  - blade
- - blade
  - hackle1
- - hackle1
  - hackle2
- - hackle2
  - hackle3
- - hackle3
  - spine1
- - spine1
  - spine2
- - spine2
  - spine3
- - spine3
  - spine4
- - spine4
  - tail1
- - tail1
  - tail2
- - tail2
  - tail3

individuals:
- individual1
- individual2
- individual3
- individual4
- individual5
- individual6
- individual7
- individual8
- individual9
- individual10
- individual11
- individual12
- individual13
- individual14
- individual15
- individual16
- individual17
- individual18
- individual19
- individual20
- individual21
- individual22
- individual23
- individual24
- individual25
- individual26
- individual27
- individual28
- individual29
- individual30
- individual31
- individual32
- individual33
- individual34
- individual35
- individual36
- individual37
- individual38
- individual39
- individual40
- individual41
- individual42
- individual43
- individual44
- individual45
- individual46
- individual47
- individual48
- individual49
- individual50
- individual51
- individual52
- individual53
- individual54
- individual55
- individual56
- individual57
- individual58
- individual59
- individual60
- individual61
- individual62
- individual63
- individual64
- individual65
- individual66
- individual67
- individual68
- individual69
- individual70
- individual71
- individual72
- individual73
- individual74
- individual75
- individual76
- individual77
- individual78
- individual79
- individual80
- individual81
- individual82
- individual83
- individual84
- individual85
- individual86
- individual87
- individual88
- individual89
- individual90
- individual91
- individual92
- individual93
- individual94
- individual95
- individual96
- individual97
- individual98
- individual99
- individual100
```
3. Open the folder for the new project, and replace the contents of the labeled data folder with the two folders above for download.
4. Reopen DLC with GUI and load the existing file, the one you just altered with the new data.
5. Skip "Extract Frames", continue to "Label Data". Click "Check Labels!". Get error.

### Relevant log output

```shell
Creating images with labels by CZ.
Attention: /Users/generuan/Desktop/PreAnnotatedDataTest/PreAnnotate-CZ-2023-05-16/labeled-data/img19075 does not appear to have labeled data!
Attention: /Users/generuan/Desktop/PreAnnotatedDataTest/PreAnnotate-CZ-2023-05-16/labeled-data/img28389 does not appear to have labeled data!
Attention: /Users/generuan/Desktop/PreAnnotatedDataTest/PreAnnotate-CZ-2023-05-16/labeled-data/img33546 does not appear to have labeled data!
If all the labels are ok, then use the function 'create_training_dataset' to create the training dataset!
```

### Anything else?

I cannot continue directly to creating a training dataset afterwards: any attempts to do so are met with the fact that DLC is not reading any training data, and thus creating a data set takes far too little time as would be reasonable. 

I don't know exactly where this specific dataset came from, but it's likely that it came from external methods (I believe it is Label Studio), and thus it may not originate from DeepLabCut. Any tips to help would be appreciated. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
hi @GeneRuan thanks for the post - please do note that we ask github say for code issues, and we and others are happy to assist on ImageForum. See here for all the community resources. https://github.com/DeepLabCut/DeepLabCut#get-assistance--be-part-of-the-dlc-community 

That being said, what you post was clearly labeled in DeepLabCut - that is the project folder. I recommend checking out the nature protocols paper and docs for multi-animal DLC (https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html). You can just edit the "project_path" in the config.yaml to your machine/location of the folder. Then you can easily launch the DLC GUI to interact with the project, or the terminal directly.
