### ISSUE TITLE
Does the need for fewer key points in model zoo affect the training effect?

### ISSUE THREAD

**Issue by lBWtt** [DeepLabCut/DeepLabCut#2252]
I use the superanimal_quadruped model in zoo, but I don't need all the points, just a few of them. Will the training be worse with just a few points than with all 39 points? If not, do I need to keep the key points I need in config.yaml (and with the same names as in the model?) .

**Comment by MMathisLab** [comment]
Hi @lBWtt right now we have not released the code to fine-tune superanimal models with less (or more) keypoints. We will do so with the paper (under revision). If you try to fine-tune naively you will have catastrophic forgetting, and it's not a simple solution -- see the paper here: http://www.mackenziemathislab.org/dlc-modelzoo/

So I suggest if you use the modelzoo superanimal models just "ignore" in your downstream analysis -- if you don't need them all, great!
