### ISSUE TITLE
Refining labels DLC 2.3.3+ in napari 0.4.17

### ISSUE THREAD

**Issue by JoeBrague1** [DeepLabCut/DeepLabCut#2259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Training a c57bl6 mouse in an openfield. 

When refining labels I open automatically labeled outliers in the same folder as manually labeled files (Containing machine labels and collected data) in napari 0.4.17. 

I moved/added labels to the machine labels layer and then saved*,**,*** I then repeated this process on the collected data. 

* When saving I tried clicking on the machine layer and pressing Ctrl+S and then did the same for the collected data. Outcome-I received the prompted response in napari that the data was saved successfully. I closed the program and opened it again and the data was not saved (both the machine and collected data layers reverted back to the old settings.)

** Alternatively, I went to file - save layer as and saved this way, also alternating between selected machine and collected data layers. Outcome-I received the prompted response in napari that the data was saved successfully. I closed the program and opened it again and the data was not saved. (both the machine and collected data layers reverted back to the old settings.)

***Finally, I tried file - save all layers. Outcome-DLC crashed.

I am getting a WARNING message when opening napari and i'm not sure if this is the problem or not. I've seen that its just a warning and "not to worry about it" https://github.com/DeepLabCut/DeepLabCut/issues/2197

### Operating System

Windows 11 64bit

### DeepLabCut version

DLC 2.3.3

### DeepLabCut mode

single animal

### Device type

Geforce 2080

### Relevant log output

```shell
WARNING: Cannot open file 'C:/tools/DeepLabCut/src/napari_deeplabcut/assets/unlock.svg', because: The system cannot find the path specified.
```

### Anything else?

Thanks for your support! 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
thanks @JoeBrague1 for the bug report; I can confirm I also have issues if I extract outliers that can from a training dataset video (sort of an edge case, but we should handle it!) on the radar for a fix ASAP! cc @jeylau

**Comment by JoeBrague1** [comment]
Many thanks @MMathisLab!

**Comment by jeylau** [comment]
@JoeBrague1, when refining labels, you only need to edit the machinelabels layer and save this one (as it will automatically merge your refined annotations in the CollectedData file). I just tested it with napari-deeplabcut==0.1.2 and confirm that after saving the refined machine labels, and reloading the CollectedData.h5, points are in the right place.

**Comment by JoeBrague1** [comment]
Hi @jeylau and @MMathisLab After a fresh install and update of DLC, it seems to be working now! I'm honestly not sure why the layers weren't saving before but I have checked the collected data after saving the machine label layer and they were added to the collected data. Merging the data sets works as well. Thanks for the follow-up @jeylau

**Comment by jeylau** [comment]
Awesome, thanks for letting us know @JoeBrague1!
