### ISSUE TITLE
pythonw is required to use DLC on MacOS

### ISSUE THREAD

**Issue by Aks0121** [DeepLabCut/DeepLabCut#226]
**Your Operating system and DeepLabCut version**

macOS High Sierra, dlc-macOS-CPU, DeepLabCut 2

**Describe the problem**

After using the label_frames command, I am given the following message: "SystemExit: This program needs access to the screen. Please run with a Framework build of python, and only when you are logged in on the main display of your Mac.," with IPython quitting. I'm running IPython 7.3.0.  Thank you. 

**How to Reproduce the problem**

Invoke label_frames command. 

**Screenshots**

![screen shot 2019-02-28 at 6 05 59 pm](https://user-images.githubusercontent.com/48101630/53605178-a915a280-3b84-11e9-861e-2fe9aaa580f1.png)

**Additional context**
N/A

**Comment by MMathisLab** [comment]
Yes, as we describe, and the error states, you need to use a framework build of python, which is pythonw in Mac. So when you start terminal you type “pythonw”

**Comment by MMathisLab** [comment]
also, it would be great if before you open code issues you (1) search (top left corner), as this was discussed on another issue already: https://github.com/AlexEMG/DeepLabCut/issues/141#issuecomment-453208298 and is in the user-guide: https://github.com/AlexEMG/DeepLabCut/blob/857cb1f38abfc3f467b6a8e53ae54365e05fcff2/docs/UseOverviewGuide.md#option-2-using-terminal-start-python

and/or if you have questions (vs a code bug report), please post them here, as many more people will see them and help answer them: https://forum.image.sc/tags/deeplabcut ;)

**Comment by Aks0121** [comment]
Got it. Thank you.
