### ISSUE TITLE
Plot trajectories Usage Error

### ISSUE THREAD

**Issue by AlecHuang3** [DeepLabCut/DeepLabCut#2260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I'm currently using an edited version of the Demo code and am trying to get plot_trajectories to function. However, I get a usage error warning and the code seems like it is not running. I'm not sure if it is an issue with matplotlib but there are no popups or output.

### Operating System

Windows 10

### DeepLabCut version

DLC 2.3.3
Tensorflow 2.10.0
cudnn 8.2.1
cuda 11.8

### DeepLabCut mode

single animal

### Device type

NVIDIA 3090 RTX

### Steps To Reproduce

Input:
```
%matplotlib notebook #for making interactive plots.
deeplabcut.plot_trajectories(path_config_file,videofile_path)
```
videofile_path is a folder with the original .mp4 files, .h5 files, and labelled .mp4 files

Output:
`UsageError: unrecognized arguments: #for making interactive plots.`

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
You can just remove the #and related text; see you error message which notes the comment can't be executed as is, the # comment should be one line down (or removed)
