### ISSUE TITLE
More CUDA versions for running DLC on HPC Cluster

### ISSUE THREAD

**Issue by bagnall-lab** [DeepLabCut/DeepLabCut#2261]
**Is your feature request related to a problem? Please describe.**
I have been trying to get DeepLabCut running on our university cluster (via docker) for over 6 weeks and kept running into issues. Eventually figured out the problem was the base image that the deeplabcut:latest-core image pulls from. Using GPU on our cluster requires CUDA 11.6 due to the drivers that are installed. The base image on deeplabcut:latest-core pulls from CUDA 11.4. Via [this forum post](https://forum.image.sc/t/deeplabcut-docker-tensorflow-gpu-problem/70044/7) , I saw that a docker image from base CUDA 11.7 was created and then found pull request #1936 for adding more CUDA versions to Dockerhub. 

**Describe the solution you'd like**
I know the pull request already exists, and I'm inexperienced with github etiquette so I apologize if that means this post is redundant, but I would like to reiterate the need for more CUDA versions (specifically for my cluster, CUDA 11.6) of the deeplabcut docker image. Is there any sort of timeline on when that part of the pull request would be implemented? 

**Describe alternatives you've considered**
I tried to run the original deeplabcut:latest-core docker image on my HPC cluster but couldn't engage GPU due to mismatch between CUDA and the nvidia drivers on the cluster GPUs. I then tried to update the base image to CUDA 11.6 myself but instantly ran into dependency version errors that I struggled to resolve due to inexperience. The lab's other option is to build our own dedicated computer to run Deeplabcut, and we are pursuing that, but being able to use the cluster would be incredibly helpful for our workflow. 

**Additional context**
Given I just found out what Docker was about 6 weeks ago, I don't have the experience that I need to build my own image from scratch, or even to update the deeplabcut:latest-core image to my desired CUDA version. That's why I am making this feature request. Thanks so much for reading and let me know if you have any questions! -Alaina

**Comment by MMathisLab** [comment]
New Docker images with 2.3.5 are slated for this week cc @maryapp ♥️👍
