### ISSUE TITLE
PySide6.QtCore

### ISSUE THREAD

**Issue by KnSun99** [DeepLabCut/DeepLabCut#2262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

In the spyder editor，run 'deeplabcut.label_frames(config_path)'

The following error occurs:

  File H:\Anaconda\envs\DEEPLABCUT\lib\site-packages\vispy\app\backends\_qt.py:62 in _check_imports
    raise RuntimeError("Refusing to import %s because %s is already "

RuntimeError: Refusing to import PyQt5 because PySide6.QtCore is already imported.

How do we fix this, thank you!

### Operating System

Win11

### DeepLabCut version

dlc 2.3.5

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
can you launch the gui from the terminal? i.e, ipython
```
ipython
import deeplabcut
python -m deeplabcut
```

**Comment by KnSun99** [comment]
Yes.

Use 'Anaconda Prompt',  can be opened.

**Comment by KonradDanielewski** [comment]
It's a spyder related issue of running Qt application from it. Check: https://github.com/spyder-ide/spyder/wiki/How-to-run-PyQt-applications-within-Spyder

**Comment by KnSun99** [comment]
Ok, thanks for your reply
