### ISSUE TITLE
issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by lishuaifu** [DeepLabCut/DeepLabCut#2263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

issubclass() arg 1 must be a class
![image](https://github.com/DeepLabCut/DeepLabCut/assets/61181011/24cb6d81-c6bf-4750-8024-757c3c184c25)

### Operating System

windows10

### DeepLabCut version

dlc-2.3.5

### DeepLabCut mode

single animal

### Device type

cpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @lishuaifu.

This seems to be an issue with Pydantic. Could you try to upgrade your `pydantic` version to `1.10.8`, as suggested in [this issue](https://github.com/pydantic/pydantic/issues/545#issuecomment-1573776471)?

**Comment by lishuaifu** [comment]
thank you
