### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by lishuaifu** [DeepLabCut/DeepLabCut#2265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

raise RuntimeError("Invalid Qt API %r, valid values are: %r, %r" %
TypeError: not all arguments converted during string formatting
![image](https://github.com/DeepLabCut/DeepLabCut/assets/61181011/7795d08f-dc15-4e2b-9c4f-bb850efe5fce)

### Operating System

windows10

### DeepLabCut version

2.3.5

### DeepLabCut mode

single animal

### Device type

cpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
we don't recommend using an IDE for DLC; we recommend the terminal or GUI; here you can see Qt is trying to be used, yet we use pyside6. Hope that helps!
