### ISSUE TITLE
Plot poses folder is empty after analyzing videos in GUI

### ISSUE THREAD

**Issue by madeleon365** [DeepLabCut/DeepLabCut#2266]
Hello!

I am having issues with trying to get the GUI to produce plot poses for my videos. My plot poses folder is completely empty and I am not sure why. In an attempt to resolve this, I followed the advice of @grahamfindlay and receive this error once I run everything.
```
project_path = pathlib.Path(__file__).parent.resolve()
config_path = str(project_path / "config.yaml")
print(f"config_path: {config_path}")
print(f"DeepLabCut version: {deeplabcut.__version__}")

videos_path = project_path / "videos"
videos = list(str(v) for v in videos_path.glob("*.mp4")) # Change to suit your project/data
print(f"Videos to analyze: \n {videos}")

deeplabcut.plot_trajectories(config_path, videos)
```

_Originally posted by @grahamfindlay in https://github.com/DeepLabCut/DeepLabCut/issues/1863#issuecomment-1163471526_
            
![plot_traj](https://user-images.githubusercontent.com/119619020/243404150-f2b86ae5-87cf-4b2c-bc62-02e7554761d9.png)

In my videos folder I have the csv files, H5 files, filtered csv files, and  PICKLE files for all of my videos. Would I have to reanalyze all of the videos again in the terminal to get the plots?  Thank you in advance!

**Comment by MMathisLab** [comment]
Hi @madeleon365 please edit your post to use our required template so we can better assist you, thanks!
