### ISSUE TITLE
Deeplabcut is not using GPU on mac M1 Studio 24 core GPU

### ISSUE THREAD

**Issue by Anuroop-Katukam** [DeepLabCut/DeepLabCut#2267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have tried installing the way you recommended on the website with Miniconda3, but still deeplabcut uses CPU as primary device to train the models.

### Operating System

Mac OS 13.4

### DeepLabCut version

dlc version : 2.3.5

### DeepLabCut mode

single animal

### Device type

24 Core GPU 

### Steps To Reproduce

1. Install Deeplabcut using Miniconda on Mac
2. create any project and label few frames.
3. Train the model and observe for GPU usage on Activity Monitor
4. Observation : Training never uses GPU

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @Anuroop-Katukam,

As described in issue #2240, it can be quite tricky to train models on Apple computers, and the way to go is really to train on an NVIDIA GPU. Make sure that you have both `tensorflow-macos` and `tensorflow-metal` installed, and the GPU should be engaged by TensorFlow.

Also check out [this forum post](https://forum.image.sc/t/updated-thread-on-gpu-use-on-apple-silicon-m1-m2/77419) describing the "optimal setups" found by a user on their MacBook.
