### ISSUE TITLE
cropping GUI in Jupyter not working

### ISSUE THREAD

**Issue by ghost** [DeepLabCut/DeepLabCut#227]
In the newest version of deeplabcut 2.0.5, I execute the command deeplabcut.extract_frames(path_config,crop=True) in Jupyter Notebook and am able to get the GUI and highlight the desired cropping window. However, closing the window does not allow the function to continue running. The last line shown is my answer to the prompt to extract frames for the video and it won't allow me to execute any other commands, I'm guessing because it's still waiting for me to "finish" cropping in the GUI. The same lines of code seem to work just fine when doing it through ipython in Anaconda.

**Comment by DonnieKim411** [comment]
As far as I have tested out the package (both version 2.0.4.1 and 2.0.5), GUI based functions/methods are not supported via Jupyter Notebook. If GUI is required (i.e. `extract_frames` or `label_frames`), you should do it on command line like IPython.

**Comment by MMathisLab** [comment]
They work for us in Jupyter... I’ll check into the cropping frames bit though. 

@skwakpk (assuming you are using Windows or Ubuntu; as you must use ``Pythonw`` for MacOS, so that is correct that on MacOS it is not supported... )

**Comment by ghost** [comment]
Yes I am using Windows! GUIs for labeling and extracting frames seem to work just fine through Jupyter, aside from the fact that everyone once in a while the GUI will crash, though I'm assuming that's a separate issue.

**Comment by MMathisLab** [comment]
We are working on a fix for the state of ``deeplabcut.extract_frames(path_config,crop=True)`` in Jupyter Notebook ;)
