### ISSUE TITLE
Setting crop=True in deeplabcut.extract_frames doesn't rases the proper GUI to crop the frames

### ISSUE THREAD

**Issue by Echo-JM-Zhang** [DeepLabCut/DeepLabCut#2276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Use of argument crop=True in deeplabcut.extract_frames ineither  jupyter notebook or directly type in terminal doesn't raises the proper GUI to crop the frames. It directly started to extract frames

### Operating System

Windows 11

### DeepLabCut version

Deeplabcut 2.3.4

### DeepLabCut mode

single animal

### Device type

cpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @Echo-JM-Zhang, you can simply pass `crop=”GUI”`, as mentioned in the [API docs for the method](https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html#id1):

> If `True`, video frames are cropped according to the corresponding coordinates stored in the project configuration file. Alternatively, if cropping coordinates are not known yet, `crop=”GUI”` triggers a user interface where the cropping area can be manually drawn and saved.
