### ISSUE TITLE
module 'deeplabcut' has no attribute 'label_frames'

### ISSUE THREAD

**Issue by ghost** [DeepLabCut/DeepLabCut#2277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I’m using anaconda3 on Jupyter notebook to doing pose estimation.
However, when I try to use label_frame function, I’m always returned “AttributeError: module ‘deeplabcut’ has no attribute 'label_frames” . Is there anyone who tell me what is wrong?
Any help would be much appreciated.

*I've already installed wxPython.
<img width="1076" alt="スクリーンショット 2023-06-19 11 14 52" src="https://github.com/DeepLabCut/DeepLabCut/assets/137019815/79e500de-1242-4610-878e-7ee2b544081f">

### Operating System

operating system

### DeepLabCut version

dlc version:2.3.5

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @Masa-chiefs, was deeplabcut installed with GUI enabled; i.e., with `pip install deeplabcut[gui]`?
Also note that we no longer use wxpython, but PySide6, which, if not found in the environment, launches deeplabcut only in light mode, without the GUI-associated functions.
