### ISSUE TITLE
Labelling and detecting multiple animals with similar features

### ISSUE THREAD

**Issue by deltaray224** [DeepLabCut/DeepLabCut#228]
Hi

Great package!

Is there a way to train using videos having multiple animals but mark similar features with the same markers?

So say what I'd like to do is mark the noses of the animals present there, but this number can vary from 0-n. Currently during training, it allows me to mark the nose only once, even if there are multiple animals (and noses) present in that frame. Is there a way I can basically mark all the noses (varying from 0 to n) that are there, and not just one?

Also the same would apply during detection- where I'd like to detect then the noses, but the number can vary from 0-m.

Cheers!
Saikat

**Comment by AlexEMG** [comment]
See https://github.com/AlexEMG/DeepLabCut/issues/50 and https://github.com/AlexEMG/DeepLabCut/issues/125

The GUI does not allow you to label multiple noses (unless you would give them different names, which would make little sense unless they consistently are in different areas). Anyway, we are working on a variant that can do this (both for labeling, training and inference). Stay tuned!

**Comment by JXXCgit** [comment]
> See #50 and #125
> 
> The GUI does not allow you to label multiple noses (unless you would give them different names, which would make little sense unless they consistently are in different areas). Anyway, we are working on a variant that can do this (both for labeling, training and inference). Stay tuned!

Hi, Dear Alexander @AlexEMG , 
I wonder if i gave different label for different bodyparts in different animals, 
for instance, 
animal A: bodypart 1
bodypart 2
bodypart 3
bodypart 4
animal B: body1
body2
body3
body4
and then label them in the same video meanwhile,
so what the result would be later when we do the training and video analysis: does it mean the data of these two animals will be in the same file and same plot? 
And another strange question to ask is:
i delete one label in the config.yaml, and the numframes2pick: 20
and then after extracting video and label video, i found the number of frame to label is more than 20. what the problems would be?
And another question: i can not really understand what is this in config.yaml: 
# Plotting configuration
skeleton:
- - bodypart1
  - bodypart2
- - objectA
  - bodypart3

if i delete one label, how this would arranged? 
Thank you for answer, 
Greetings, 
Shauyin

**Comment by AlexEMG** [comment]
Starting with https://github.com/DeepLabCut/DeepLabCut/tree/v2.2b5 there is (finally) very strong multi-animal support built in! Please let us know how it goes.
