### ISSUE TITLE
Click "crop" icon in GUI but no response

### ISSUE THREAD

**Issue by Echo-JM-Zhang** [DeepLabCut/DeepLabCut#2283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I try to crop my video by setting crop='GUI', and the GUI pumps up. However, when finished choosing area and click 'crop', there is no change/no response. I check the config.yaml file and there is no update of cropping parameters.

### Operating System

operating system: windows11

### DeepLabCut version

dlc versionL 2.3.5

### DeepLabCut mode

single animal

### Device type

gpu: RTX3080

### Steps To Reproduce

1. In DEEPLABCUT environment
2. run `deeplabcut.extract_frames(config_path, mode='automatic', algo='kmeans', userfeedback=False, crop='GUI')`
3. The GUI pumps up, but clicking 'crop' icon gives no response

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @Echo-JM-Zhang, thank you for reporting this issue. It will be fixed by pull request #2288.

**Comment by MMathisLab** [comment]
merged! please update your conda env by running `pip install git+https://github.com/DeepLabCut/DeepLabCut.git`
