### ISSUE TITLE
Muti animal mode in the deeplabcut vs 2.3.5 could not tracking a video of 2 mice.

### ISSUE THREAD

**Issue by cfsilvia** [DeepLabCut/DeepLabCut#2284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi
I am trying to tracking  a movie with two mice (which are very different). Attached one example frame.
![img0542](https://github.com/DeepLabCut/DeepLabCut/assets/131141474/4b628d6e-98f8-44e0-abef-d5bd255dfd4a)

I am using the deeplabcut gui version 2.3.5.
Each mice were labeled. We labeled around 45 frames.  According to the message sent by the gui, the training step finished 
successfully**. But the analyze video is stacked and not csv and video are getting.**

I saw that other issue with the same problem because all the labels were not included thus we repeated the label step by marking all the mice parts. 

Anyway the issue is not working. 
Note: If you  work with only one mice the deeplabcut is working

Can you help me to solve this issue.
Thanks
Silvia Chuartzman Phd
Weizmann Institute of Science 

### Operating System

operating system
windows 10

### DeepLabCut version

dlc version
2.3.5

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

1-Run GUI
2-Train network
3-Evaluate network
4- analyze video- here is stacked no csv with annotation go out

![DeepError](https://github.com/DeepLabCut/DeepLabCut/assets/131141474/bc8ae843-aba5-401c-aeb1-c67cf09c5eaa)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
seems the frame has one mouse in it? 

Note, unless the mice look identical, you should not use maDLC without setting id=true; see out user-guide: https://deeplabcut.github.io/DeepLabCut/docs/UseOverviewGuide.html#what-scenario-do-you-have

**Comment by cfsilvia** [comment]
The other mouse is a pup. Is it very different from the black mouse.

**Comment by MMathisLab** [comment]
Right, so then its a special case for deeplabcut; if you have 1 adult mouse and multiple pups, see user docs:

https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#configure-the-project

>> Uniquebodyparts: are points that you want to track, but that appear only once within each frame, i.e. they are “unique”. Typically these are things like unique objects, landmarks, tools, etc. They can also be animals, e.g. in the case where one German shepherd is attending to many sheep the sheep bodyparts would be multianimalbodyparts, the shepherd parts would be uniquebodyparts and the individuals would be the list of sheep (e.g. Polly, Molly, Dolly, …).

**Comment by cfsilvia** [comment]
Thanks for your reply. But the pup isn't stay in one place during the movie.
It also disappears from the frames.
What do you suggest to do?

Silvia

**Comment by MMathisLab** [comment]
The pup can move, and the adult, the point is how you labeled your data; you would need to share your config.yaml file for me to be more helpful :)

**Comment by cfsilvia** [comment]
Thanks again!!!!


Silvia G. Chuartzman
________________________________

**Comment by cfsilvia** [comment]
Hi
I am still cannot running the deeplabcut for 2 animals. The same issue as before.
I saw you closed my issue, but it doesn't work when I try with 2 animals (I tried also with a black and white mice) .
The gui is stacked in analyze video-.
An error status bar appears.

I attached again the config file as you asked for me.
I am working with GPU Quadro RTX 4000. Is this card enough?

Thanks
Silvia

**Comment by MMathisLab** [comment]
As I mentioned, I think you likely labeled the data incorrectly for your setting, hence why I asked that if you want my help further I'd need to see your config.yaml file.
