### ISSUE TITLE
Cannot generate .h5 file

### ISSUE THREAD

**Issue by thetalker101** [DeepLabCut/DeepLabCut#2297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When working on a multi-animal project, I would run into errors at every step, which inevitably result in the program failing to generate a .h5 file. I tried rerunning the data set creation in different shuffles as well as the following steps, but nothing would fix it. I also deleted everything but the labeled data, and that didn't fix it either. I have only 2 ideas why it isn't working. The first is that the labeled data is the issue. Whether that's because I'm using data from an .avi that acted weird alongside some normal .mp4 files or whether some random bug happened that messed the whole workflow up, I don't know. The second may be that my version (2.2.3) is not able to handle multi-animal models, so it just won't complete. I've tried a lot of tweaking with the settings, but nothing seems to fix it.

The reason I am using an older version is because I tried to use the newer version (2.3.3), but that seemed to be more dysfunctional than 2.2.3 and I had work to do instead of trying to get the new version working.

### Operating System

Windows

### DeepLabCut version

2.2.3

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

Not sure how to replicate as I've redone every step apart from labeling as that would be the longest to fix.

### Relevant log output

```shell
I receive this after evaluating the network:
Traceback (most recent call last):
  File "C:\Users\anaconda3\lib\site-packages\deeplabcut\gui\evaluate_network.py", line 266, in evaluate_network
    deeplabcut.extract_save_all_maps(self.config, shuffle=shuffle)
  File "C:\Users\anaconda3\lib\site-packages\deeplabcut\pose_estimation_tensorflow\visualizemaps.py", line 487, in extract_save_all_maps
    fig1, _ = visualize_scoremaps(image, map_)
  File "C:\Users\anaconda3\lib\site-packages\deeplabcut\pose_estimation_tensorflow\visualizemaps.py", line 297, in visualize_scoremaps
    fig, ax = form_figure(nx, ny)
  File "C:\Users\anaconda3\lib\site-packages\deeplabcut\pose_estimation_tensorflow\visualizemaps.py", line 286, in form_figure
    fig, ax = plt.subplots(frameon=False)
  File "C:\Users\anaconda3\lib\site-packages\matplotlib\pyplot.py", line 1474, in subplots
    fig = figure(**fig_kw)
  File "C:\Users\anaconda3\lib\site-packages\matplotlib\_api\deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\anaconda3\lib\site-packages\matplotlib\pyplot.py", line 813, in figure
    manager = new_figure_manager(
  File "C:\Users\anaconda3\lib\site-packages\matplotlib\pyplot.py", line 383, in new_figure_manager
    return _get_backend_mod().new_figure_manager(*args, **kwargs)
  File "C:\Users\anaconda3\lib\site-packages\matplotlib\backend_bases.py", line 3570, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "C:\Users\anaconda3\lib\site-packages\matplotlib\backend_bases.py", line 3575, in new_figure_manager_given_figure
    return cls.FigureCanvas.new_manager(figure, num)
  File "C:\Users\anaconda3\lib\site-packages\matplotlib\backend_bases.py", line 1738, in new_manager
    return cls.manager_class.create_with_canvas(cls, figure, num)
  File "C:\Users\anaconda3\lib\site-packages\matplotlib\backends\backend_wx.py", line 1008, in create_with_canvas
    frame = FigureFrameWx(num, figure, canvas_class=canvas_class)
  File "C:\Users\anaconda3\lib\site-packages\matplotlib\backends\backend_wx.py", line 928, in __init__
    manager = FigureManagerWx(self.canvas, num, self)
  File "C:\Users\anaconda3\lib\site-packages\matplotlib\backends\backend_wx.py", line 1002, in __init__
    super().__init__(canvas, num)
  File "C:\Users\anaconda3\lib\site-packages\matplotlib\backend_bases.py", line 2828, in __init__
    self.toolbar = self._toolbar2_class(self.canvas)
  File "C:\Users\anaconda3\lib\site-packages\matplotlib\backends\backend_wx.py", line 1089, in __init__
    bitmap=self._icon(f"{image_file}.png"),
  File "C:\Users\anaconda3\lib\site-packages\matplotlib\backends\backend_wx.py", line 1132, in _icon
    return wx.Bitmap.FromBufferRGBA(
RuntimeError: Failed to gain raw access to bitmap data.

I would receive this after trying to analyze a video:
Traceback (most recent call last):
  File "C:\Users\anaconda3\lib\site-packages\deeplabcut\gui\analyze_videos.py", line 497, in analyze_videos
    scorername = deeplabcut.analyze_videos(
  File "C:\Users\anaconda3\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 634, in analyze_videos
    convert_detections2tracklets(
  File "C:\Users\anaconda3\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 1809, in convert_detections2tracklets
    ass.calibrate(train_data_file)
  File "C:\Users\anaconda3\lib\site-packages\deeplabcut\pose_estimation_tensorflow\lib\inferenceutils.py", line 298, in calibrate
    dists = np.vstack([pdist(data, "sqeuclidean") for data in xy])
  File "<__array_function__ internals>", line 180, in vstack
  File "C:\Users\anaconda3\lib\site-packages\numpy\core\shape_base.py", line 282, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate

This is the group of errors I receive after training:
Traceback (most recent call last):
  File "C:\Users\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1378, in _do_call
    return fn(*args)
  File "C:\Users\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1361, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "C:\Users\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1454, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[{{node fifo_queue_enqueue}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\anaconda3\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 83, in load_and_enqueue
    sess.run(enqueue_op, feed_dict=food)
  File "C:\Users\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 968, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "C:\Users\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1191, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "C:\Users\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1371, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "C:\Users\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1397, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.CancelledError: Graph execution error:

Detected at node 'fifo_queue_enqueue' defined at (most recent call last):
    File "C:\Users\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\Users\anaconda3\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "C:\Users\anaconda3\lib\site-packages\deeplabcut\__main__.py", line 22, in <module>
      deeplabcut.launch_dlc()
    File "C:\Users\anaconda3\lib\site-packages\deeplabcut\gui\launch_script.py", line 50, in launch_dlc
      app.MainLoop()
    File "C:\Users\anaconda3\lib\site-packages\wx\core.py", line 2262, in MainLoop
      rv = wx.PyApp.MainLoop(self)
    File "C:\Users\anaconda3\lib\site-packages\deeplabcut\gui\train_network.py", line 315, in train_network
      deeplabcut.train_network(
    File "C:\Users\anaconda3\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 197, in train_network
      train(
    File "C:\Users\anaconda3\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train_multianimal.py", line 66, in train
      batch, enqueue_op, placeholders = setup_preloading(batch_spec)
    File "C:\Users\anaconda3\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 69, in setup_preloading
      enqueue_op = q.enqueue(placeholders_list)
Node: 'fifo_queue_enqueue'
Enqueue operation was cancelled
         [[{{node fifo_queue_enqueue}}]]

Original stack trace for 'fifo_queue_enqueue':
  File "C:\Users\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\anaconda3\lib\site-packages\deeplabcut\__main__.py", line 22, in <module>
    deeplabcut.launch_dlc()
  File "C:\Users\anaconda3\lib\site-packages\deeplabcut\gui\launch_script.py", line 50, in launch_dlc
    app.MainLoop()
  File "C:\Users\anaconda3\lib\site-packages\wx\core.py", line 2262, in MainLoop
    rv = wx.PyApp.MainLoop(self)
  File "C:\Users\anaconda3\lib\site-packages\deeplabcut\gui\train_network.py", line 315, in train_network
    deeplabcut.train_network(
  File "C:\Users\anaconda3\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 197, in train_network
    train(
  File "C:\Users\anaconda3\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train_multianimal.py", line 66, in train
    batch, enqueue_op, placeholders = setup_preloading(batch_spec)
  File "C:\Users\anaconda3\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\train.py", line 69, in setup_preloading
    enqueue_op = q.enqueue(placeholders_list)
  File "C:\Users\anaconda3\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 346, in enqueue
    return gen_data_flow_ops.queue_enqueue_v2(
  File "C:\Users\anaconda3\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 4062, in queue_enqueue_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "C:\Users\anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 797, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "C:\Users\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3800, in _create_op_internal
    ret = Operation(
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @thetalker101, it seems to me that there might be an issue with wxPython: the first error indicates that an image cannot be loaded. Which version are you using (you can see the wxPython version in the output of `conda list`)?

One solution would be to try an upgrade the package, which you can do in your conda environment using `pip install --upgrade wxPython`. You could also upgrade `DeepLabCut` to the latest version (using the command `pip install --upgrade deeplabcut`), which does not use `wxPython` and might solve your issue (no need to relabel the entire dataset - you can just use it as-is with the newest version of DeepLabCut, and simply re-train and evaluate your model). This might also fix your issue.

Finally, it's possible that the image cannot be loaded if the video or an image is corrupted.

Can you create the training dataset without errors? If you can't, could you please log the error you get when creating the training dataset?

**Comment by thetalker101** [comment]
Thank you for the response. I upgraded wxpython and reran the whole thing after creating the training dataset, but only now a new error appeared regarding the wxpython version, but only that error occurred on evaluate network. I do not believe there are any issues with the videos I'm using, so that is not likely it. Finally, there are no errors with creating the training dataset. However, the only other options are to recreate the entire project and dataset with the chance of repeating failure, or I can try and run the latest stable build of DLC. Please wait for my response.

**Comment by thetalker101** [comment]
After upgrading from 2.2.3 to 2.3.5, I found that the "tracklets are empty" error is still going on. This implies at some point I broke something and now I have to redo it completely. Thanks for the assistance as I believe this is a user error instead of a code based one.

**Comment by thetalker101** [comment]
After further work it seems this issue is beyond random error, so I will go over the full steps I made to have this tracklets issue. I created a new project in DLC 2.3.5. I used an .mp4 video for extracting and labeling frames. I took said frames and labeled them using the napari application and having it add points to the collected data section and finally saving. I used resnet 50 and imgaug for the dataset. I trained the network to only 10k iterations as a test. I evaluated the network without checking test maps. I analyzed the videos with multiple settings all resulting in the "tracklets are empty" error. This time around I had no errors except for this last one and I believe somewhere I made a simple mistake that was not noticed because I have not worked with multi-animal models so far.

**Comment by n-poulsen** [comment]
An error indicating that tracklets are empty usually indicates that the model you trained is not performing well enough, as you can read about in [this issue](https://github.com/DeepLabCut/DeepLabCut/issues/1854) or in the documentation [here](https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#decision-point) or in [this forum post](https://forum.image.sc/t/tracklets-are-empty-or-no-video-s-were-found-please-check-your-paths/59225/5)

Most importantly, the first thing you should do is described [here](https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#attention):
> Pose estimation and tracking should be thought of as separate steps. If you do not have good pose estimation evaluation metrics at this point, stop, check original labels, add more data, etc –> don’t move forward with this model. If you think you have a good model, please test the “raw” pose estimation performance on a video to validate performance:
```python
scorername = deeplabcut.analyze_videos(
    config_path, ['/fullpath/project/videos/testVideo.mp4'], videotype='.mp4'
)
deeplabcut.create_video_with_all_detections(
    config_path, ['/fullpath/project/videos/testVideo.mp4'], videotype='.mp4'
)
```
> Please note that you do not get the .h5/csv file you might be used to getting (this comes after tracking). You will get a pickle file that is used in create_video_with_all_detections. Another sanity check may be to examine the distributions of edge affinity costs using deeplabcut.utils.plot_edge_affinity_distributions. Easily separable distributions indicate that the model has learned strong links to group keypoints into distinct individuals — likely a necessary feature for the assembly stage (note that the amount of overlap will also depend on the amount of interactions between your animals in the daset).

If your trained model is performing well enough, you probably need to modify the `inference_cfg` file to select parameters better suited to your problem.

**Comment by thetalker101** [comment]
Hmmm, so this issue is happening because I'm not using enough examples or my labeled data is not consistent enough? Well alright, I'll see what I can do to improve the dataset.

**Comment by thetalker101** [comment]
I completely redid the data set and included more slides (total ~1170 with ~200 per camera angle) and made sure every label was accurate to the animal. I trained it using resnet101 and trained 100k iterations. However it still returned this issue. Any recommendations? I'm at a total loss.

**Comment by n-poulsen** [comment]
Did you look at results using `deeplabcut.create_video_with_all_detections`, and did those results look good? How about the training/test errors?

Could you also share your project `config.yaml` file, as well as the tracking  `inference_cfg.yaml` (which sets parameters for tracking)?

**Comment by thetalker101** [comment]
I made a video using that command and it looked alright. Not perfect but working. I guess that means something may be wrong with the gui based commands because that's how I've been working on all of my projects. I don't know how to check my training/test errors.
Here are my yaml files:
[config.txt](https://github.com/DeepLabCut/DeepLabCut/files/12075652/config.txt)
[inference_cfg.txt](https://github.com/DeepLabCut/DeepLabCut/files/12075657/inference_cfg.txt)

**Comment by n-poulsen** [comment]
To check your training/test error, you can check out the documentation [here](https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#evaluate-the-trained-network) (check out the do). Basically, all you need to do is run
```python
deeplabcut.evaluate_network(config_path)
```

This will create results files in an `evaluation-results` folder in your project. You can check out the `CombinedEvaluation-results.csv` file to look at how different snapshots are progressing (and if the loss is going down).

It's particularly important to note that (as indicated in the documentation linked above):
> In multi-animal projects, model evaluation is crucial as this is when the data-driven selection of the optimal skeleton is carried out. 

And this important [message](https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#attention):
> Pose estimation and tracking should be thought of as separate steps. If you do not have good pose estimation evaluation metrics at this point, stop, check original labels, add more data, etc –> don’t move forward with this model. If you think you have a good model, please test the “raw” pose estimation performance on a video to validate performance:

Also note, as mentioned in the [training documentation](https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#train-the-network), that:
> We recommend you look closely at the loss to not overfit on your data. The bonus, training time is much less!!!
So make sure your model is not overfitting the training data.

If the model is not assembling your different individuals well, the tracker will not be able to track them. So my first recommendation would be to evaluate your model, look at the results, and maybe try to tweak your training parameters (number of iterations/save iterations) to get the best performing model you can. Once the model has good performance on single images, then you can look at tracking individuals.

**Comment by thetalker101** [comment]
The results are as follows. I don't know what exactly overfitting will look like in this data. Also it seems to me that there is an issue with using the gui as it did not return any errors when I evaluated the network. When I did so in the gui it would come back with a bitmap error even though it fully ran.

Results for 100000 training iterations, training fraction of 95, and shuffle 1:
Train error: 2.93 pixels. Test error: 14.45 pixels. (full video size is 720X528)
With pcutoff of 0.6:
Train error: 2.93 pixels. Test error: 12.35 pixels.
##########################################
Average Euclidean distance to GT per individual (in pixels; test-only)
individuals
bear1    15.477709
bear2     9.577364
bear3    11.225948
Average Euclidean distance to GT per bodypart (in pixels; test-only)
bodyparts
Asleep            NaN
Awake       15.526700
Away        14.135301
Drinking          NaN
Eating            NaN
Resting      7.724308

**Comment by jeylau** [comment]
Hey @thetalker101, what do your body parts correspond to? Those look like action labels to me.

**Comment by thetalker101** [comment]
They correspond to animal activities. Whether the bears I am analyzing are sleeping or awake or doing other activities. I placed these labels to the back of the bear to keep it relatively square on the animal.

**Comment by jeylau** [comment]
I'm afraid this is beyond what DeepLabCut can offer. DeepLabCut learns to predict anatomical landmarks, but not actions, based on the visual information contained within your images; I guess that'd work if your bears changed colors as they sleep 😄. The traditional way to do the sort of analysis you described though is to annotate keypoints consistently to estimate your bears' poses, and subsequently use those to recognize actions. This paper from our group is a good introduction to the topic https://www.cell.com/neuron/pdf/S0896-6273(20)30717-0.pdf ☺️

**Comment by thetalker101** [comment]
Well that's the funny part of using machine learning, it can do a lot more than you originally thought. I've had great success with using location estimation in EPM tests. I would track where the animal is and change the marker as it transitioned to the closed or open arm. It had extremely high accuracy, which told me the proposed method of analysis via pose estimation was not set in stone.
Are you referring to pose estimation as the only way to achieve high accuracy? I tried using location markers on kangaroo mice jumping in videos to tell whether they were on the ground or not. I was not able to beat the existing lab classification of random forest using pose estimation from DLC.
Your lab promotes pose estimation, but there are circumstances that pose estimation can be curtailed for a simpler marker. I can send some of my videos as proof of this if you would like.

**Comment by jeylau** [comment]
Certainly, but the problem you described above with your bears is different. To simply locate an animal in space, I agree that pose estimation is unnecessary; this could be solved using a single marker only and looking at its coordinates though, making it simpler to annotate. Same for jumping animals. As for the bears, unless they systematically take different actions in very distinct (and different-looking) locations in the scene, I do not see how the model could distinguish awake from resting based on a minuscule patch of pixels in a single frame: that looks to me like a very different problem from determining an animal's spatial location.

**Comment by thetalker101** [comment]
I am testing this idea so far, maybe it will work, maybe not. However, I opened this issue because the gui is not working for me. It has been useful to run some of the commands without the gui to see that it has been working. It would help if I could get an explanation why the gui commands are not working for this single project when other have.

**Comment by jeylau** [comment]
`wxpython` was notoriously difficult to install properly, hence why we moved away from it in more recent versions. I'd stick to DeepLabCut 2.3.5, but understand that it is natural that animal tracking fails since in your case there are no poses to estimate and track. If you're happy with your trained model after evaluation, just run inference on your videos without the tracklets part, all detections should be found in a *.pickle file in your videos folder. Please let us know how accurate your action classification ends up being, your approach definitely does sound novel.

**Comment by thetalker101** [comment]
I will be considering the random forest calibration as needed, but for right now I just need the project to work. Also, I used the command `analyze_videos` but it still has the empty tracklets error and I need the .csv files for my project, but they aren't generating. I checked and it doesn't work in the new or old version of DLC

**Comment by n-poulsen** [comment]
The `.h5` files are not generating because with your setup, the animals cannot be tracked (you can see more details in the [Multi-animal pose estimation](https://www.nature.com/articles/s41592-022-01443-0) publication). This is why the tracklets are empty. This is not an issue with the code itself, as behavior analysis is not what it was designed to do. It worked in the single animal setup as no tracking was needed.

As @jeylau mentioned above, you can just run inference on your videos without tracking the animals, and all detections should be found in a `*.pickle` file in your videos folder. This file contains all detections in a dictionary.

**Comment by thetalker101** [comment]
Just as a clarifying question, is there still a way to generate .csv files with my current method?

**Comment by n-poulsen** [comment]
Someone seems to have desired the same data as you, and wrote a python script to transform the pickle file output by the model to a csv file: here is a [link to that conversation](https://forum.image.sc/t/using-the-full-pickle-file/44403/4) and a [link to the script](https://github.com/rasdani/bachelor-thesis/blob/main/get_detections.py).

You'll need to modify the script to use your keypoint names (the "meta_columns") and path to your full file (the "MP-TestDLC_resnet50_PoCNov1shuffle1_50000_full.pickle" string).

**Comment by thetalker101** [comment]
I seem to not know where this convertdetectiondict2listoflist function and it won't let me run the script.

**Comment by jeylau** [comment]
@thetalker101, give a look at the function `find_outliers_in_raw_detections` rather https://github.com/DeepLabCut/DeepLabCut/blob/3b06cd8f4f7f8e0420220bb70078ea7c944932b1/deeplabcut/refine_training_dataset/outlier_frames.py#L123
Give it the data contained in the _full.pickle, which you open for example with:
```python
import pandas as pd

data = pd.read_pickle('path_to_full_pickle')
_, dets = find_outliers_in_raw_detections(data)
```
The function returns `dets`, which is a dictionary whose keys are individual frame names and values are detections + confidence, ordered as defined in your config.yaml file.
Then just use `numpy.argmax` to get the index of the point of highest likelihood, and in turn infer what action that was.

**Comment by thetalker101** [comment]
It seems that I should consider another approach. A myriad of issues are appearing trying to make this script work. I will reconsider the method to see if I can get something that will allow me to detect single animals and analyze them from written data.
