### ISSUE TITLE
Installation gets stuck at "Installing pip dependencies"

### ISSUE THREAD

**Issue by tsievert** [DeepLabCut/DeepLabCut#2298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

The installation of DLC via `conda env create -f DEEPLABCUT.yaml` seems to freeze after a while.
The last printed message is `Installing pip dependencies: ` and the progress indicator is spinning.

I force quit the first attempt after about 22h of no progress and the second attempt is already running now for 2h.

### Operating System

Windows 11

### DeepLabCut version

2.3.5

### DeepLabCut mode

single animal

### Device type

GeForce RTX 4070 Ti
Driver Version: 536.40

### Steps To Reproduce

1. Install latest driver
2. Install CUDA
3. `nvidia-smi`
4. `NVIDIA-SMI 536.40      Driver Version: 536.40       CUDA Version: 12.2`
5. git clone 
6. navigate to folder
7. ` (base) PS C:\Program Files\DeepLabCut\DeepLabCut\conda-environments> conda env create -f DEEPLABCUT.yaml`
8. 
```
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 23.5.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.5.0



Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: \ C:\Users\ULiege\anaconda3\envs\DEEPLABCUT\lib\site-packages\nb_conda_kernels\install.py:8: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import iter_entry_points
Enabling nb_conda_kernels...
CONDA_PREFIX: C:\Users\ULiege\anaconda3\envs\DEEPLABCUT
Status: enabled

- Config option `kernel_spec_manager_class` not recognized by `EnableNBExtensionApp`.
Enabling notebook extension nb_conda/main...
      - Validating: ok
Enabling tree extension nb_conda/tree...
      - Validating: ok
Config option `kernel_spec_manager_class` not recognized by `EnableServerExtensionApp`.
Enabling: nb_conda
- Writing config: C:\Users\ULiege\anaconda3\envs\DEEPLABCUT\etc\jupyter
    - Validating...
      nb_conda 2.2.1 ok

done
Installing pip dependencies: |
```
9. Nothing is happening even after 22h of waiting

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by tsievert** [comment]
I updated `conda` manually to 23.5.0, but nothing changed.

**Comment by tsievert** [comment]
I managed to find a work around by running `pip install 'deeplabcut[gui,tf]'`.
I then followed that up with `conda env update -f DEEPLABCUT.yaml` and it seemed to have worked.
Although, contrary to what is mentioned in the documentation, cudnn was not installed (see https://github.com/DeepLabCut/DeepLabCut/issues/2183#issuecomment-1575645671)

**Comment by n-poulsen** [comment]
`cudnn` has been added to the dependencies by pull request #2299

**Comment by wi11iamk** [comment]
Hello, @tsievert. I am experiencing this exact problem and have reproduced the error with identical hardware and drivers. I see your solution, but could you clarify the exact steps taken? After you terminated the process at `Installing pip dependencies:`, did you `conda activate DEEPLABCUT` and then `pip install 'deeplabcut[gui,tf]'` and install from the env or did you `pip install` from base and then `conda env update -f DEEPLABCUT.yaml`? I only ask because I see that the DEEPLABCUT env is created in spite of the process hanging at the dependency install. This question may be naive, but it is what it is. Thanks very much for your help.

**Comment by tsievert** [comment]
Hey @wi11iamk , I'm pretty certain I first ran `conda activate DEEPLABCUT` before `pip install`.
Good luck

**Comment by wi11iamk** [comment]
@tsievert , thanks very much. It worked a charm. Have a great Friday.
