### ISSUE TITLE
Bare except

### ISSUE THREAD

**Issue by jakirkham** [DeepLabCut/DeepLabCut#23]
In the process of debugging an issue, found a [bare `except`]( https://github.com/triccelli/DeepLabCut/blob/97ab76651736e514154fd72564dbf17e2ef6905d/Evaluation-Tools/AnalyzeVideos.py#L126 ). Generally these are not good as they can capture errors like `KeyboardInterrupt` or `ResourceError`, which it is likely not intended to capture. Instead would be better if a specific exception type were added here.

**Comment by jakirkham** [comment]
Guessing this should be `FileNotFoundError`, correct?

**Comment by AlexEMG** [comment]
Correct (but really not a problem in this case). I made a much nicer version last week [that automatically looks which scorer was used] and plan to upload it once I find time. Hard to imagine that this is the reason for #22 though.

**Comment by jakirkham** [comment]
Would disagree about it not being a problem. In fact, it's a [known anti-pattern]( https://docs.quantifiedcode.com/python-anti-patterns/correctness/no_exception_type_specified.html ).

Indeed. This is unrelated to #22. Different issue that was not filed as it was solved offline.

**Comment by AlexEMG** [comment]
Certainly bad practice. Will fix it in the next update.

**Comment by AlexEMG** [comment]
Fixed the bare excepts. Please let me know if you find other anti-patterns.
