### ISSUE TITLE
Issue when setting copy_videos = false

### ISSUE THREAD

**Issue by zaloch** [DeepLabCut/DeepLabCut#230]
**Windows 10 Deep Lab Cut Version 2.0**

Windows 10, Anaconda Env, DeeplabCut 2.0

**If applicable, please also complete the following information:**
 - Browser Firefox
 - Version 65.0.1 64 bit

**Describe the bug**
Hi, this is a simple bug. Perhaps it's only related to my system, but when I set copy_videos under deeplabcut.create_new_project I get an OSError: symbolic link privilege not held. None of the other commands work as config.yaml isn't created. _This is not an issue when setting copy_videos = True (everything else works fine when set to True)._ 

**To Reproduce**
Set Config_path to False.

**Expected behavior**
Symbolic path to videos would be created, config.yaml would be created under working_directory.

**Screenshots**

<img width="693" alt="dlc bug" src="https://user-images.githubusercontent.com/40471641/53758231-77a21d00-3e8b-11e9-9dd9-8cf93e25f908.PNG">

**Additional context**
Using python 3.6.8

**Comment by oliriley** [comment]
IIRC @AlexEMG indicated in discussion of another issue that this has to do with permissions on the specific files. That makes me think that some things to test would be:

1. What permissions are set for the files themselves, and for the folder they're in? Does setting looser permissions solve anything? 
2. Does the issue persist if you run the command prompt as administrator?

**Comment by dehmelt** [comment]
**Issue reproduced:**
Was able to reproduce @zaloch's issue using the same overall configuration (Win10, Anaconda, DLC 2.0, Python 3.6.8, either 1 or 3 .avi files).

**Confirmed workaround:**
Just like @oliriley suggested, running Anaconda Prompt _as administrator_ solved the issue on my system. Setting `copyvideos=False`, links were created as expected.

**Comment by MMathisLab** [comment]
Yes, running as an admin is unfortunately required for Windows users (for several steps). https://github.com/AlexEMG/DeepLabCut/wiki/Troubleshooting-Tips
"Open command prompt with administrative rights. Use `Run as administrator' while opening the command prompt."

I will close, but feel free to comment further here if needed.
