### ISSUE TITLE
Training pauses in middle and have to press enter to continue

### ISSUE THREAD

**Issue by tianboqi** [DeepLabCut/DeepLabCut#2300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

The training sporadically pauses (both CPU and GPU usage drops), but nothing freezes. When I press ENTER the training resumes, and immediately the console pops up the update like 'iteration: 31000 loss: 0.1208 lr: 0.002'. 

### Operating System

Win10

### DeepLabCut version

DLC 2.3.5

### DeepLabCut mode

single animal

### Device type

This issue happened both under CPU and under GPU

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @tianboqi, if you leave the execution alone (don't hit enter), does it eventually start printing iterations again? Or does it never update anymore?

**Comment by MMathisLab** [comment]
Thai is a windows console setting and a known issue -- if you click on the terminal it pauses. https://github.com/microsoft/terminal/issues/2678 

There are older DeepLabCut issues reporting this I believe. You can disable this in windows though!
