### ISSUE TITLE
Fail installation deeplabcut

### ISSUE THREAD

**Issue by minh132** [DeepLabCut/DeepLabCut#2304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I install deeplabcut with conda in ubuntu. When I import deeplabcut, I have this error :
```
conda activate DEEPLABCUT
(DEEPLABCUT) iwanna@iwanna:~/Documents/DeepLabCut/conda-environments$ ipython
Python 3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:06:00) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.2 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import deeplabcut
2023-07-08 22:59:47.747632: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-08 22:59:47.874065: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
Loading DLC 2.3.5...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
```

### Operating System

Ubuntu

### DeepLabCut version

dlc version 2.3.5

### DeepLabCut mode

single animal

### Device type

GPU NVIDIA

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @minh132, the "`tensorflow/cuda_blas`" messages you see might not actually be errors (as mentioned [here](https://discuss.tensorflow.org/t/trying-to-setup-first-time-unable-to-register-cublas-factory-already-been-registered/12946)). Could you just check that tensorflow has access to your GPU by running:
```python
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))
```

If a list containing your GPU is printed, then you should be able to safely ignore the warning (but check that the GPU is being used when training).

Then, the `DLC loaded in light mode` message indicates that the GUI for `DeepLabCut` was not installed. Did you install DeepLabCut using the supplied conda environment (`conda env create -f DEEPLABCUT.yaml`), and intend to use the GUI?

If so, did you get any error messages when installing DeepLabCut?

**Comment by n-poulsen** [comment]
Closing as stale
