### ISSUE TITLE
Extract outlier frames manual method Error. Extracts frame to incorrect directory

### ISSUE THREAD

**Issue by saxonberry** [DeepLabCut/DeepLabCut#2306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Using the napari  GUI I  try to manually extract frames from a novel video and the following error comes up: 

```
File “C:\Users\uqsberr2\Anaconda3\envs\DEEPLABCUT\lib\site-packages\napari_deeplabcut\_widgets.py”, line 281, in _extr _write_image(frame, str(output_path))
.
.
.
FileNotFoundError: The directory `"C:\Users\uqsberr2\Desktop\labeled-data\mouse10`" does not exist.
```

**Info that could be useful.** 

The video file is NOT located in  the “videos” folder found in the deeplabcut project folder. Both the video file and all its analysed h5/pickle data are saved together in a folder on the desktop. 

I use the deeplabcut GUI to open the Napari GUI for manual extraction.  The Napari GUI opens fine with the video and all its predicted labels, I am able to navigate it without issue too, however when I try to extract a frame with the "extract frame" button the error comes up.
The error occurs in the method `"_extract_single_frame"` from _widgets.py. 

My understanding is that it uses the root path from the metadata in the image layer to save the extracted frame.
Aka: `"C:\Users\uqsberr2\Desktop\labeled-data\mouse10"`. 

I’ve located where the metadata for the image layer is created and its in napari_deeplabcut, _reader.py, read_video(). I’m not sure why, but it uses the file path of the video to create the root path instead of the project path specified in the config file. Specifically the root directory for the image layer is the parent directory the video is found in, with “labeled-data” appended to the end of it.

I've also put the novel video (mouse10) and it's analysed files into the videos folder found in the project folder and tried manually extracting it from there. The save directory is correct but no mouse10 folder exists in labeled_data  for it to save the extracted frames. 

In addition, I tried the API function to extract the outlier frames: 
```python
deeplabcut.extract_outlier_frames(
    config_path,
    videos=video_paths,
    destfolder=output_path,
    videotype='mp4',
    outlieralgorithm='manual',
    savelabeled=True,
    track_method='ellipse',
    copy_videos=True,
)
```

In this case the Napari GUI opens and then immediately closes itself. 

### Operating System

operating system: Window

### DeepLabCut version

dlc version:  DLC 2.3.5

### DeepLabCut mode

multi animal

### Device type

gpu:  NVIDIA RTX A4000

### Steps To Reproduce

1. In the deeplabcut enviroment open the deeplab cut GUI
2. Navigate to the tab “Extract outlier frames (*)” 
3. Select a video that the model has not been trained on. My video and it's h5/pickle files are located in a folder on the desktop.
4. Select the following parameters: Tracking method ellipse, shuffle 1, algorithm manual, video type mp4 .
5. Open the napari GUI with the “extract frames” button
6.  extract a frame with the "“extract frame” button 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @saxonberry, this issue is known and documented in issue #2279.
