### ISSUE TITLE
Issue with corner extraction for 3d camera calibration

### ISSUE THREAD

**Issue by vasudha-kulkarni** [DeepLabCut/DeepLabCut#2310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi,

We are trying to calibrate two cameras positioned at roughly 90 degrees to one another using the command 'deeplabcut.calibrate_cameras(...)'. We tried with checkerboards of two sizes - 7x13 and 8x7 with square side of length 6 cm. Some example images and videos from the recordings can be found at this link - https://drive.google.com/drive/folders/1aj2tYeMxAWD9pA4fskSUU_M_pFFxOlpC?usp=sharing.

Out of 700 pairs of images (for 7x13 board), it only extracted corners from 5 pairs of images, and for the 8x7 board, out of 1500 pairs of images, it only extracted corners for 9 frames form the front camera and not a single frame from the top camera. It didn't change when we varied the contrast or color. We also tried changing the number of rows and columns, but no corners were extracted. The output reads as follows - 
> Corners not found for the image cam_15_001.jpg
> Corners not found for the image cam_15_002.jpg
> Corners not found for the image cam_15_003.jpg
> ...
> Corners not found for the image cam_15_1000.jpg
> Corners not found for the image cam_15_1001.jpg
> Corners not found for the image cam_15_1002.jpg
> Corners extracted! You may check for the extracted corners in the directory C:\Users\PS_22_2\Desktop\VK2023\Camera_calibration\cam14_cam15\behavsync_trial03-VK-2023-06-30-3d\corners and remove the pair of images where the corners are incorrectly detected. If all the corners are detected correctly with right order, then re-run the same function and use the flag ``calibrate=True``, to calbrate the camera.

Do you have any suggestions for what changes we can make to make this work?

Thank you so much for your help!

### Operating System

Windows 11

### DeepLabCut version

DLC 2.3.5

### DeepLabCut mode

3d

### Device type

GPU - NVIDIA RTX A2000

### Steps To Reproduce

1. conda activate DEEPLABCUT
2. import deeplabcut
3. config_path3d = create_new_project_3d("behavsync", "VK", num_cameras=2)
4. deeplabcut.calibrate_cameras(config_path3d, cbrow=8, cbcol=7, calibrate=False, alpha=1)

### Relevant log output

```shell
Corners not found for the image cam_15_001.jpg
Corners not found for the image cam_15_002.jpg
Corners not found for the image cam_15_003.jpg
...
Corners not found for the image cam_15_1000.jpg
Corners not found for the image cam_15_1001.jpg
Corners not found for the image cam_15_1002.jpg
Corners extracted! You may check for the extracted corners in the directory C:\Users\PS_22_2\Desktop\VK2023\Camera_calibration\cam14_cam15\behavsync_trial03-VK-2023-06-30-3d\corners and remove the pair of images where the corners are incorrectly detected. If all the corners are detected correctly with right order, then re-run the same function and use the flag ``calibrate=True``, to calbrate the camera.
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Be sure the images are < 90 degrees -- our setup requires stereo configuration of the cameras at this time. see here: https://deeplabcut.github.io/DeepLabCut/docs/Overviewof3D.html
