### ISSUE TITLE
Extract Outlier Frames extremely slow

### ISSUE THREAD

**Issue by hpay** [DeepLabCut/DeepLabCut#2311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Expect: Extract Outlier Frames should be reasonably fast, since we are only extracting single 10 frames per video and we've already analyzed the videos
Reality: Extract Outlier Frames  (using "jump" setting) processes each video slower than real time. It runs without error and correctly extracts 10 frames but surely there is a way to do this faster? Three overnight steps in our pipeline is a lot (1. train model, 2. analyze videos, AND 3. extract outliers)

### Operating System

operating system: Windows 11

### DeepLabCut version

dlc version: 2.3.5

### DeepLabCut mode

single animal

### Device type

gpu: NVIDIA Quadro M4000

### Steps To Reproduce

[In anaconda prompt]
conda activate deeplabcut
python -m deeplabcut

[In GUI]:

1. load config.yaml for an existing trained model. Set numframes2pick = 10
[config.txt](https://github.com/DeepLabCut/DeepLabCut/files/12051025/config.txt)
2. Analyze Videos (select 11 .mp4 videos, most ~500 Mb large and 1 hour long, either 540x540 or 1080x1080 pixels
(^this step takes a long time, approx real time, but this is expected. Runs overnight)
3. Extract Outlier Frames using "jump method". Runs extremely slowly, why? Note: It seems to be using CPU not GPU here, not sure that is expected

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @hpay!

To extract outlier frames using the `outlieralgorithm='jump'` and `extractionalgorithm="kmeans"`,  the detections for all frames where a bodypart has "jumped" more the epsilon pixels from the last frame are clustered using the k-means algorithm. Doing so on long videos (where a large number of frames need to be clustered) can be very slow.

To speed up the process, you can:
- try to run with `extractionalgorithm="uniform"`, which will sample `numframes2pick` frames from the outliers (and is quicker than clustering)
- extract frames from shorter versions of your videos

I would simply create a few short clips and extract frames from there. You can do so using DeepLabCut by running:
```
deeplabcut.ShortenVideo(
    "path/to/your/video.mp4",
    start="00:00:01",
    stop="00:00:06",
    outsuffix="short_1second_to_6seconds",
)
```

Also note that it's expected that it's not running on a GPU, as it's simply using the files output when you ran `analyze_videos`. 

Working on speeding up the clustering algorithm for long videos is not currently planned. If you want more information about extracting outlier frames, the documentation is available [here](https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html#m-optional-active-learning-network-refinement-extract-outlier-frames).
