### ISSUE TITLE
gputouse has no effect anymore

### ISSUE THREAD

**Issue by ludovicbellier** [DeepLabCut/DeepLabCut#2312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When specifying gputouse (at least) in predict_videos.analyze_videos(), it has no effect and it's always GPU 0 that gets used (see image below).

![image](https://github.com/DeepLabCut/DeepLabCut/assets/28165157/f17b880e-d5d5-4054-94e9-c53705670c81)

Now, I found [this](https://github.com/pytorch/pytorch/issues/9158) online, while led me to try hardcoding the CUDA_VISIBLE_DEVICES environment variable before relevant imports (tensorflow, most likely), and in this case the specified GPU is effectively used.

![image](https://github.com/DeepLabCut/DeepLabCut/assets/28165157/7897d8a3-7b7e-4247-b34f-60d638c31537)

Same exact code (.py script) used both times, trying to get CPU 2 engaged.
Also, I used to have CUDA 11.8 installed, as well as previous versions of NVIDIA drivers and of DLC, and it used to work fine.
Lastly, I have CUDA_MODULE_LOADING=LAZY in my environment variables.

### Operating System

Ubuntu 22.04

### DeepLabCut version

DLC 2.3.5

### DeepLabCut mode

single animal

### Device type

NVIDIA RTX A4500
NVIDIA drivers 535.54.03
CUDA 12.2

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @ludovicbellier, thanks for reporting the issue! We'll start working on a fix.

**Comment by ludovicbellier** [comment]
Fantastic, thanks a lot @n-poulsen!
