### ISSUE TITLE
Multiple animals failed training, and training a single animal could not detect multiple animals

### ISSUE THREAD

**Issue by niuyixing** [DeepLabCut/DeepLabCut#2316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

[
![1eb315e45e23b951df6eab153632354](https://github.com/DeepLabCut/DeepLabCut/assets/29516566/b4ef6f31-3f15-4060-a0f4-1419e099a446)
![8dd4fa9ae4f424fa260f8ad44df345b](https://github.com/DeepLabCut/DeepLabCut/assets/29516566/d1a8308f-12f9-4c58-8a9c-0ad2e682f9dc)
](url)

### Operating System

windows anaconda

### DeepLabCut version

dlc version 2.3.5

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by niuyixing** [comment]
Multiple animals fail to train, and an error is reported when saving all of them

**Comment by n-poulsen** [comment]
Hi @niuyixing, I need more information to be able to help you. What did you run exactly (which options did you select in the GUI, which part fails etc.) and could you provide the error logs that were obtained?

Thanks!

**Comment by n-poulsen** [comment]
Closing as stale
