### ISSUE TITLE
extracting outliers, automatic adding to config file failed

### ISSUE THREAD

**Issue by ghost** [DeepLabCut/DeepLabCut#232]
When extracting outlier frames, I got the following message: 

> AUTOMATIC ADDING OF VIDEO TO CONFIG FILE FAILED! You need to do this manually for including it in the config.yaml file!

I'm not sure exactly what I'm supposed to be adding into the config file and where in the config file in order to manually correct the outlier frames. Is there an example of this somewhere?

**Comment by oliriley** [comment]
I am not sure why this warning shows up, but I have seen it before and it ***seems*** to be mostly a reminder to people who are adding a new video to an existing project. You can see what videos the project currently knows to look for by looking at "_video_sets_" in your config.yaml. If this is a video you have labeled and trained on previously, and you are just adding **more** frames, you should be fine. If it is new, I *think* that if you want for the **train_network** function to recognize that labeled data, you need to use
> deeplabcut.add_new_videos("Full path of config.yaml",["full path of video "], copy_videos=True/False)

As far as I'm aware the outlier frames *do get extracted* even if you did not add the video to the project ahead of time, so you do not need to re-run the extract_outlier_frames function. You can double-check this by going into the project folder, looking in "_labeled-data_", and seeing if there is a "_machine labels_" file with the same iteration number as you're currently using. I think this is called "_iter_" in the config file (it will be 0 when you start).

**Comment by AlexEMG** [comment]
Videos that contain training data should be added to the list of videosets so that they are included in the training set. This is what this step is supposed to do. 

If you need to add it manually add it and keep the same style (tabs etc. as for other entries), e.g. 
```
video_sets:
  /home/alex/Desktop/BasiliskL.avi:
    crop: 0, 320, 0, 120
  /home/alex/Desktop/BasiliskL13.avi:
    crop: 0, 320, 0, 120
```

@skwakpk This never happened for me, do you have any insight why? I.e. did you not have permissions?/ was the path correct?

**Comment by oliriley** [comment]
@AlexEMG that same warning has shown up a lot when I extract outliers on my lab's setup (Windows 10), it has just never had a negative impact, for both videos we are analyzing separately and for videos which had previously been added to the training set.
