### ISSUE TITLE
failed installation on win10 with yaml file

### ISSUE THREAD

**Issue by Fusenheizi** [DeepLabCut/DeepLabCut#2324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When creating the environment using a YAML file, an error occurred. At first, I didn't think it was a big issue, but as I proceeded with the tutorial, I noticed some problems: there was no presence of Jupyter, and there was no GUI interface. After removing the environment and attempting to recreate Deeplabcut with administrator privileges, the same error persisted.

### Operating System

operating system

### DeepLabCut version

dlc version

### DeepLabCut mode

single animal

### Device type

gpu

### Relevant log output

```shell
D:\Anaconda\envs\DEEPLABCUT\Scripts\jupyter-nbextension.exe"' is not recognized as an internal or external command,
operable program or batch file.
'"D:\Anaconda\envs\DEEPLABCUT\Scripts\jupyter-serverextension.exe"' is not recognized as an internal or external command,
operable program or batch file.

done
ERROR conda.core.link:_execute (952): An error occurred while installing package 'conda-forge::nb_conda-2.2.1-win_6'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::nb_conda-2.2.1-win_6
location of failed script: D:\Anaconda\envs\DEEPLABCUT\Scripts\.nb_conda-post-link.bat
==> script messages <==
'"D:\Anaconda\envs\DEEPLABCUT\Scripts\jupyter-nbextension.exe"' is not recognized as an internal or external command,
operable program or batch file.
'"D:\Anaconda\envs\DEEPLABCUT\Scripts\jupyter-serverextension.exe"' is not recognized as an internal or external command,
operable program or batch file.

==> script output <==
stdout:
stderr:
return code: 1

()
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
this is a repeated issue: https://github.com/DeepLabCut/DeepLabCut/issues/2322
