### ISSUE TITLE
Updating the DLC version on NeSI framework, 

### ISSUE THREAD

**Issue by ReetKaur15** [DeepLabCut/DeepLabCut#2326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

1. I am using the .yml file provided by the developers which has a clear instruction to install deeplabcut gui. Installation goes through without any issues but attempting to launch the gui via python -m deeplabcut triggers the message DeepLabCut will load in light mode...  (without the gui). 

2. Second error comes after that and related zeroMQ libray and GLIBC incompatibility 

Strangely, I have downloaded the upstream docker container as a singularity image and that itself has the issue with the GUI. Given this is the image provided by DeepLabCut developers and independent of the operating system we have, looks like there is a fundamental issue with version 2.3.* on Linux.

Please look into this and give suggestions.

Thanks and Regards

### Operating System

Linux

### DeepLabCut version

2.3.5

### DeepLabCut mode

single animal

### Device type

GPU (NeSI)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
we don't support GUI natively in the docker, that is for headless computing- `pip install deeplabcut[gui]`, which is in the yaml file you ref. would allow local use of the GUI.

Also note we only support NVIDIA GPUs with CUDA.
