### ISSUE TITLE
error in GUI 'save all layers'

### ISSUE THREAD

**Issue by Fusenheizi** [DeepLabCut/DeepLabCut#2327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When I execute the 'label frames' step in the GUI, an error is displayed when I choose 'Save All Layers'.

### Operating System

operating system

### DeepLabCut version

latest

### DeepLabCut mode

single animal

### Device type

GPU

### Steps To Reproduce

1. Select the 'labeled-data' folder. 
2. Label each frame. 
3. choose ‘save all layers'.

### Relevant log output

```shell
Traceback (most recent call last):
  File "E:\anaconda3\envs\deeplabcut\lib\site-packages\napari\_qt\menus\file_menu.py", line 82, in <lambda>
    'slot': lambda: window._qt_viewer._save_layers_dialog(
  File "E:\anaconda3\envs\deeplabcut\lib\site-packages\napari\_qt\qt_viewer.py", line 617, in _save_layers_dialog
    filename, selected_filter = dlg.getSaveFileName(
AttributeError: PySide6.QtWidgets.QFileDialog.getSaveFileName(): unsupported keyword 'directory'
```

### Anything else?
name    version
-----------------
napari   0.4.17
PySide6   6.3.1

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by Harry-WXH** [comment]
Got the same issue

**Comment by jeylau** [comment]
Hello! The `save all layers` should not be used (as it attempts to save not only your annotations but also the images, which is not defined and thus causes an error); simply select the Points layer, and hit Ctrl+S or `File > Save Selected Layer(s)...`. You can read some usage doc [here](https://github.com/DeepLabCut/napari-deeplabcut#save-layers). Note that with the new release of the napari-deeplabcut plugin coming soon, the option to save all layers will be removed.
