### ISSUE TITLE
launch UI fail because of qt version

### ISSUE THREAD

**Issue by rdengqlink** [DeepLabCut/DeepLabCut#2329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

hello,
I followed the instruction to install DLC, when launch by python -m deeplabcut, it tells qt plugin incompatible:

> Loading DLC 2.3.5...
> Starting GUI...
> qt.core.plugin.loader: In C:/Users/Administrator/anaconda3/envs/DEEPLABCUT/Library/plugins/platforms/qdirect2d.dll:
>   Plugin uses incompatible Qt library (5.15.0) [release]
> qt.core.plugin.loader: In C:/Users/Administrator/anaconda3/envs/DEEPLABCUT/Library/plugins/platforms/qminimal.dll:
>   Plugin uses incompatible Qt library (5.15.0) [release]
> qt.core.plugin.loader: In C:/Users/Administrator/anaconda3/envs/DEEPLABCUT/Library/plugins/platforms/qoffscreen.dll:
>   Plugin uses incompatible Qt library (5.15.0) [release]
> qt.core.plugin.loader: In C:/Users/Administrator/anaconda3/envs/DEEPLABCUT/Library/plugins/platforms/qwebgl.dll:
>   Plugin uses incompatible Qt library (5.15.0) [release]
> qt.core.plugin.loader: In C:/Users/Administrator/anaconda3/envs/DEEPLABCUT/Library/plugins/platforms/qwindows.dll:
>   Plugin uses incompatible Qt library (5.15.0) [release]
> qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

I think this is because now we are using pyside6, and napari --info might also tells this by:

> (DEEPLABCUT) C:\Users\Administrator>napari --info
> WARNING: pyqt5 already imported, cannot switch to pyqt6
> WARNING:vispy:pyqt5 already imported, cannot switch to pyqt6
> napari: 0.4.17
> Platform: Windows-10-10.0.19045-SP0
> Python: 3.8.17 (default, Jul  5 2023, 20:35:33) [MSC v.1916 64 bit (AMD64)]
> Qt: 5.15.2
> PyQt5: 5.15.7
> NumPy: 1.24.4
> SciPy: 1.10.1
> Dask: 2023.5.0
> VisPy: 0.11.0
> magicgui: 0.7.2
> superqt: unknown
> in-n-out: 0.1.8
> app-model: 0.2.0
> npe2: 0.7.2
> 
> OpenGL:
>   -   File "C:\Users\Administrator\anaconda3\envs\DEEPLABCUT\lib\site-packages\vispy\app\backends\_pyside6.py", line 32, in <module>
>   -     from PySide6 import QtTest
> 
> Screens:
> 
> Plugins:
>   - napari: 0.4.17 (77 contributions)
>   - napari-console: 0.0.8 (0 contributions)
>   - napari-deeplabcut: 0.1.2 (16 contributions)
>   - napari-svg: 0.1.10 (2 contributions)

So I removed qt5 and reinstall PyQt6 by:
```
conda remove qt
conda remove pyqt
pip install sip   (under env)
pip install PyQt6 (under env)
pip install PyQt6-toolspip (under env)
```

Now napari --info shows:

> napari: 0.4.17
> Platform: Windows-10-10.0.19045-SP0
> Python: 3.8.17 (default, Jul  5 2023, 20:44:21) [MSC v.1916 64 bit (AMD64)]
> Qt: 6.4.2
> PyQt6:
> NumPy: 1.24.4
> SciPy: 1.10.1
> Dask: 2023.5.0
> VisPy: 0.11.0
> magicgui: 0.7.2
> superqt: unknown
> in-n-out: 0.1.8
> app-model: 0.2.0
> npe2: 0.7.2
> 
> OpenGL:
>   -   File "C:\Users\Administrator\anaconda3\envs\DEEPLABCUT\lib\site-packages\vispy\app\backends\_pyside6.py", line 32, in <module>
>   -     from PySide6 import QtTest
> 
> Screens:
> 
> Plugins:
>   - napari: 0.4.17 (77 contributions)
>   - napari-console: 0.0.8 (0 contributions)
>   - napari-deeplabcut: 0.1.2 (16 contributions)
>   - napari-svg: 0.1.10 (2 contributions)

Seems Ok? but when I execute python -m deeplabcut, it still reports:

> (DEEPLABCUT) C:\Users\Administrator>python -m deeplabcut
> 2023-07-26 03:24:19.703811: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
> 2023-07-26 03:24:19.703915: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
> Loading DLC 2.3.5...
> Starting GUI...
> qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

So Could you tell me where I got wrong with this? Thanks!!

### Operating System

Windows 10 with out GPU for now

### DeepLabCut version

2.3.5

### DeepLabCut mode

single animal

### Device type

not for now

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
The PySide6 version looks incorrect, as it should be `<6.3.2`. You also should not install `PyQt6` (as it is likely to conflict with pyside). I'd try to uninstall all GUI frameworks (pyside, pyqt and qtpy), and reinstall only the needed one via `pip install deeplabcut[gui]`. I hope this helps!
