### ISSUE TITLE
ALL gpus seem to be allocated when running analyze_videos

### ISSUE THREAD

**Issue by DonnieKim411** [DeepLabCut/DeepLabCut#233]
**Your Operating system and DeepLabCut version**
Ubuntu18.04 with DLC 2.0.5. But running on Docker (https://github.com/eqs/DeepLabCut-Docker/blob/master/docker/Dockerfile) which installs Ubuntu 16.04 with cuda9.0.

I have two GPUs installed. 1080ti on GPU0 and 1080 on GPU1
 
**Describe the bug**
when running `analyze_videos` with `gputouse` to be 0, it should only utilize GPU0, but it seems like somehow allocate _all_ available GPUs to analyze. And annoyingly it does not seem to improve the speed either.

**To Reproduce**
1. After training done, run `dlc.analyze_videos(config_path, [video_path], gputouse=0, destfolder=dest_dir).
2. run nvidia-smi on your cmd and watch how memory is being allocated.
3. Both GPU somehow occupy all memory 

**Expected behavior**
Only 1 GPU should be used

**Screenshots**
![nvidia-smi](https://user-images.githubusercontent.com/23262857/53841463-77288580-3f62-11e9-9229-dafd92aa336f.png)

**Additional context**
None

**Comment by AlexEMG** [comment]
I have never seen this (especially not in the docker container...) I suspect you didn't close a previous session?

**Comment by DonnieKim411** [comment]
I am certain I wasn't using GPUs  before opening up IPython. It is puzzling to me as well. I can share my docker image (it is almost identical to this guy: https://github.com/eqs/DeepLabCut-Docker ).

If i recall correctly, when I trained the model, it used only 1 GPU... but for some reason when I do `analyze_videos` it takes up both mysteriously. Have you tried this on a machine with multiple GPU?

**Comment by MMathisLab** [comment]
Can you confirm in our Docker container, as that one is quite different actually. And yes, tested on systems with 2 or more GPUs, and it has never happened with our standard container ... ( maybe post a Q on his GitHub, as perhaps eqs changed this step in his version, idk)

**Comment by DonnieKim411** [comment]
OK i will open a ticket there and see. In the meantime, do u remember how many iterations u get when analyze? I know it is GPU dependent, but I saw drastic performance decrease when I analyze bigger images (say 1000 by 1000)... like it goes 15~20 iters/sec while for some smaller images, it can go at 120 or so iters/sec.

**Comment by MMathisLab** [comment]
Yes, please see the preprint on speed: https://www.biorxiv.org/content/early/2018/10/30/457242

**Comment by MMathisLab** [comment]
any updates on this?

**Comment by AlexEMG** [comment]
We set the environment variable for picking the GPU in here: https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/pose_estimation_tensorflow/predict_videos.py#L143

The gpu number should thus always be overwritten, and only one in use: os.environ['CUDA_VISIBLE_DEVICES'] = str(gputouse)
