### ISSUE TITLE
fail to install on M1 Mac - failed to build `wxPython`

### ISSUE THREAD

**Issue by BenjaminSchaar** [DeepLabCut/DeepLabCut#2330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Does anyone have the same issue that the installation of the newest version of deeplabcut always crashes with wxpython?
<img width="1324" alt="Screenshot 2023-07-26 at 16 27 48" src="https://github.com/DeepLabCut/DeepLabCut/assets/122351773/1ac71d42-2e60-4f2d-b225-9e659bdd52fd">

### Operating System

operating system: macOS ventura 13

### DeepLabCut version

dlc version

### DeepLabCut mode

single animal

### Device type

gpu - M1

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @BenjaminSchaar, which commands exactly do you use to install `DeepLabCut`?

**Comment by BenjaminSchaar** [comment]
so first thing I made sure that I have the newest anaconda version for arm64. 

I tried the pulling it from github and installing the DEEPLABCUT_M1.yaml environment 
- pulled from git hub and navigated to folder with cd
-conda env create -f DEEPLABCUT_M1.yaml

I tried the pip install 'deeplabcut[gui,tf]'

I tried already with miniconda3 and anaconda.

I also made sure that i have tensorflow.

This wxpyhton error is the furthest I was with the installation.

With the docker version of deeplabcut i have the error that the amd64 is not correct for arm64 
- deeplabcut-docker

'M1 docker preview and keycloak 'image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8)'

**Comment by n-poulsen** [comment]
The commande `pip install "deeplabcut[gui,tf]"` will not work on an M1 mac, as tensorflow should not be installed in that way. The current installation has issues with the latest Jupyter Notebook release (see issue #2322), and we're in the process of fixing that.

However, you should not be having issues with `wxPython` as it does not need to be installed. Could you try and install DeepLabCut in the following way (and if it doesn't work, copy-past the logs here instead of sending a screenshot; it makes it much easier to debug)?

```bash
conda create -n deeplabcut_apple_mchip python=3.9
conda activate dlctest
pip install "notebook<7.0.0" "tensorflow-macos<2.13.0" "tensorflow-metal" 
pip install "deeplabcut[gui]"
```

This process worked for me on an M2 mac, and there should be no difference on an M1 chip.

**Comment by BenjaminSchaar** [comment]
after this following error comes up:

```
"Collecting tables>=3.7.0 (from deeplabcut[gui])
  Using cached tables-3.8.0.tar.gz (8.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      <string>:19: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      ld: library not found for -lhdf5
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      cpuinfo failed, assuming no CPU features: 'flags'
      * Using Python 3.9.17 (main, Jul  5 2023, 15:35:09)
      * Found cython 3.0.0
      * USE_PKGCONFIG: False
      * Found conda env: ``/Users/benjaminschaar/anaconda3/envs/deeplabcut_apple_mchip``
      .. ERROR:: Could not find a local HDF5 installation.
         You may need to explicitly state where your local HDF5 headers and
         library can be found by setting the ``HDF5_DIR`` environment
         variable or by using the ``--hdf5`` command-line option.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip."
```

I did: "brew install hdf5" -> still same error after retrying it

**Comment by BenjaminSchaar** [comment]
solved the previous error by setting the hdf5 environment variable to installation path for hdf5: 
"export HDF5_DIR=/opt/homebrew/opt/hdf5"

Now I have following error:

    Cython.Compiler.Errors.CompileError: tables/utilsextension.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by BenjaminSchaar** [comment]
(deeplabcut) benjaminschaar@eduroam-078-104-028-244 ~ % echo $HDF5_DIR

/opt/homebrew/opt/hdf5

The dir is correct but error remains

**Comment by jeylau** [comment]
Hi @BenjaminSchaar! Could you try to uninstall `tables` with `pip uninstall tables`, and reinstall it rather via conda: `conda install pytables`. I always have more success this way, as it comes bundled with all the right libraries, at the right location.

**Comment by BenjaminSchaar** [comment]
ok installed hdf5 via this: https://ports.macports.org/port/hdf5/

new error message is relatet to cython:

"   Cython.Compiler.Errors.CompileError: tables/utilsextension.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip."

@jeylau  thanks for your input also tried what you said , the error still there

**Comment by BenjaminSchaar** [comment]
my mac seems to be a mess sorry and thanks for all the help!

**Comment by jeylau** [comment]
Have you maybe tried to start with a new, fresh installation using the `DEEPLABCUT_M1.yaml` environment file?

**Comment by BenjaminSchaar** [comment]
@jeylau 
this is the error via "conda env create -f DEEPLABCUT_M1.yaml"

"      Cython.Compiler.Errors.CompileError: tables/utilsextension.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

failed"

-> seem to be similar error as when i try installing it via @n-poulsen suggested way

**Comment by jeylau** [comment]
Maybe try this one: `pip install git+https://github.com/PyTables/PyTables.git@v3.7.0` (https://github.com/PyTables/PyTables/issues/968#issuecomment-1304436034). It looks like something can go wrong with the .c files, and this command has apparently helped some people install it properly.

**Comment by BenjaminSchaar** [comment]
ok i managed to run the installation in my environment via pip install "deeplabcut[gui]"

but when i put in "python -m deeplabcut" following error appears:

"Loading DLC 2.3.5...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Traceback (most recent call last):
  File "/Users/benjaminschaar/anaconda3/envs/deeplabcut/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/benjaminschaar/anaconda3/envs/deeplabcut/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/benjaminschaar/anaconda3/envs/deeplabcut/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/benjaminschaar/anaconda3/envs/deeplabcut/lib/python3.9/site-packages/deeplabcut/__init__.py", line 37, in <module>
    from deeplabcut.create_project import (
  File "/Users/benjaminschaar/anaconda3/envs/deeplabcut/lib/python3.9/site-packages/deeplabcut/create_project/__init__.py", line 12, in <module>
    from deeplabcut.create_project.demo_data import load_demo_data
  File "/Users/benjaminschaar/anaconda3/envs/deeplabcut/lib/python3.9/site-packages/deeplabcut/create_project/demo_data.py", line 16, in <module>
    from deeplabcut.utils import auxiliaryfunctions
  File "/Users/benjaminschaar/anaconda3/envs/deeplabcut/lib/python3.9/site-packages/deeplabcut/utils/__init__.py", line 11, in <module>
    from deeplabcut.utils.auxfun_multianimal import *
  File "/Users/benjaminschaar/anaconda3/envs/deeplabcut/lib/python3.9/site-packages/deeplabcut/utils/auxfun_multianimal.py", line 34, in <module>
    from deeplabcut.utils import auxiliaryfunctions, conversioncode
  File "/Users/benjaminschaar/anaconda3/envs/deeplabcut/lib/python3.9/site-packages/deeplabcut/utils/auxiliaryfunctions.py", line 31, in <module>
    from deeplabcut.pose_estimation_tensorflow.lib.trackingutils import TRACK_METHODS
  File "/Users/benjaminschaar/anaconda3/envs/deeplabcut/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/lib/trackingutils.py", line 20, in <module>
    from numba import jit
  File "/Users/benjaminschaar/anaconda3/envs/deeplabcut/lib/python3.9/site-packages/numba/__init__.py", line 55, in <module>
    _ensure_critical_deps()
  File "/Users/benjaminschaar/anaconda3/envs/deeplabcut/lib/python3.9/site-packages/numba/__init__.py", line 42, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.24 or less")
ImportError: Numba needs NumPy 1.24 or less"

weird thing is that my mac doesnt know the "pythonw -m deeplabcut" command

**Comment by BenjaminSchaar** [comment]
solveds! just had to fix some more dependencys manually

**Comment by BenjaminSchaar** [comment]
thanks for all the help I lost track of what I did elsewhise I would put it in a protocoll and paste:
In the end it worked in this environment:
"conda create -n deeplabcut_apple_mchip python=3.9
conda activate dlctest
pip install "notebook<7.0.0" "tensorflow-macos<2.13.0" "tensorflow-metal" 
pip install "deeplabcut[gui]"

put with additional bug fixing one after another

**Comment by jeylau** [comment]
Great to hear! We may need to pin numpy in the `setup.py` file then, if recent versions conflict with `numba`.

**Comment by jeylau** [comment]
> thanks for all the help I lost track of what I did elsewhise I would put it in a protocoll and paste: In the end it worked in this environment: "conda create -n deeplabcut_apple_mchip python=3.9 conda activate dlctest pip install "notebook<7.0.0" "tensorflow-macos<2.13.0" "tensorflow-metal" pip install "deeplabcut[gui]"
> 
> put with additional bug fixing one after another

Wait, this does not look right. If you create an environment called `deeplabcut_apple_mchip`, why do you activate it with `dlctest`?

**Comment by BenjaminSchaar** [comment]
I just copied from the comment from @n-poulsen but of course i activated the proper environment in reality.

I just meant that it worked in this manually created environment instead via the .yaml file

**Comment by BenjaminSchaar** [comment]
Last thing: I really appreciate your work and the 11/10 support thanks a lot!

**Comment by jeylau** [comment]
Thank you very much for the kind words!

**Comment by DaveGold35** [comment]
> thanks for all the help I lost track of what I did elsewhere I would put it in a protocoll and paste: In the end it worked in this environment: "conda create -n deeplabcut_apple_mchip python=3.9 conda activate dlctest pip install "notebook<7.0.0" "tensorflow-macos<2.13.0" "tensorflow-metal" pip install "deeplabcut[gui]"
> 
> put with additional bug fixing one after another

@BenjaminSchaar I was running into the same issues you were having about the HDF5 lib and tried the solution commands you posted and had no progress w the issue, could you reply the dependencies you fixed?

**Comment by outlace** [comment]
I'm having similar issues on my Macbook Air M1. Issue after issue. Fixed HDF5 issue, now getting an error: `ERROR: Could not build wheels for tables, vispy which use PEP 517 and cannot be installed directly`

EDIT: I finally got it installed and the GUI opens, but the are conflicts remaining. To install, I had to upgrade numpy to 1.24 because Numba required that but then: 
`tensorflow-macos 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.24.0 which is incompatible.`
So I don't know if that will cause a crash with tensorflow when I try to run the model (havent tried yet).

**Comment by BenjaminSchaar** [comment]
@DaveGold35 

> > thanks for all the help I lost track of what I did elsewhere I would put it in a protocoll and paste: In the end it worked in this environment: "conda create -n deeplabcut_apple_mchip python=3.9 conda activate dlctest pip install "notebook<7.0.0" "tensorflow-macos<2.13.0" "tensorflow-metal" pip install "deeplabcut[gui]"
> > put with additional bug fixing one after another
> 
> @BenjaminSchaar I was running into the same issues you were having about the HDF5 lib and tried the solution commands you posted and had no progress w the issue, could you reply the dependencies you fixed?

I went trough it error by error but I could send you my working DLC environment if that would help?

**Comment by DaveGold35** [comment]
@BenjaminSchaar  That would be super helpful!  Any chance I could get your email to correspond with you? idrk how to send private comments on this/ make a private forum for this kind of sharing

**Comment by alexgdyer** [comment]
@BenjaminSchaar Any update on how to resolve this issue? I am encountering the same batch of problems.

**Comment by BenjaminSchaar** [comment]
Ye as said I went error  by error message tonsolve this conflicts took me a week super annoying. I can export my env and send

**Comment by alexgdyer** [comment]
That would be so helpful if you could send it!

**Comment by alexgdyer** [comment]
@BenjaminSchaar Would email be the best to receive the environment? Feel free to send it to agdyer@college.harvard.edu
Thanks again!

**Comment by BenjaminSchaar** [comment]
This is the environment.yaml export of my currently working mac m1 environment:

name: deeplabcut
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=openblas
  - blosc=1.21.3=h313beb8_0
  - bzip2=1.0.8=h620ffc9_4
  - c-ares=1.19.1=hb547adb_0
  - c-blosc2=2.8.0=h313beb8_0
  - ca-certificates=2023.05.30=hca03da5_0
  - hdf5=1.12.1=h05c076b_3
  - krb5=1.20.1=h69eda48_0
  - libcurl=8.1.1=h3e2b118_1
  - libcxx=14.0.6=h848a8c0_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=12_3_0_hd922786_1
  - libgfortran5=12.3.0=ha3a6a3e_1
  - libnghttp2=1.52.0=h62f6fdd_1
  - libopenblas=0.3.21=h269037a_0
  - libssh2=1.10.0=h02f6b3c_2
  - llvm-openmp=16.0.6=h1c12783_0
  - lz4-c=1.9.4=h313beb8_0
  - lzo=2.10=h1a28f6b_2
  - ncurses=6.4=h313beb8_0
  - numexpr=2.8.4=py39h79ee842_1
  - openssl=3.0.9=h1a28f6b_0
  - pip=23.2.1=py39hca03da5_0
  - pytables=3.8.0=py39he239255_2
  - python=3.9.17=hb885b13_0
  - readline=8.2=h1a28f6b_0
  - setuptools=68.0.0=py39hca03da5_0
  - sqlite=3.41.2=h80987f9_0
  - tk=8.6.12=hb8d0fd4_0
  - wheel=0.38.4=py39hca03da5_0
  - xz=5.4.2=h80987f9_0
  - zlib=1.2.13=h5a0b063_0
  - zlib-ng=2.0.7=h80987f9_0
  - zstd=1.5.5=hd90d995_0
  - pip:
      - absl-py==1.4.0
      - alabaster==0.7.13
      - anyio==3.7.1
      - app-model==0.2.0
      - appdirs==1.4.4
      - appnope==0.1.3
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - astunparse==1.6.3
      - attrs==23.1.0
      - babel==2.12.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - blosc2==2.0.0
      - build==0.10.0
      - cachetools==5.3.1
      - cachey==0.2.1
      - certifi==2023.7.22
      - cffi==1.15.1
      - charset-normalizer==3.2.0
      - click==8.1.6
      - cloudpickle==2.2.1
      - comm==0.1.3
      - contourpy==1.1.0
      - cycler==0.11.0
      - cython==3.0.0
      - dask==2023.7.1
      - dask-image==2023.3.0
      - debugpy==1.6.7
      - decorator==5.1.1
      - deeplabcut==2.3.5
      - defusedxml==0.7.1
      - dlclibrary==0.0.3
      - docstring-parser==0.15
      - docutils==0.17.1
      - exceptiongroup==1.1.2
      - executing==1.2.0
      - fastjsonschema==2.18.0
      - filelock==3.12.2
      - filterpy==1.4.5
      - flatbuffers==23.5.26
      - fonttools==4.41.1
      - fqdn==1.5.1
      - freetype-py==2.4.0
      - fsspec==2023.6.0
      - gast==0.4.0
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.56.2
      - h5py==3.9.0
      - heapdict==1.0.1
      - hsluv==5.0.3
      - huggingface-hub==0.16.4
      - idna==3.4
      - imageio==2.31.1
      - imageio-ffmpeg==0.4.8
      - imagesize==1.4.1
      - imgaug==0.4.0
      - importlib-metadata==6.8.0
      - importlib-resources==6.0.0
      - in-n-out==0.1.8
      - ipykernel==6.25.0
      - ipython==8.14.0
      - ipython-genutils==0.2.0
      - isoduration==20.11.0
      - jax==0.4.13
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.3.1
      - jsonpointer==2.4
      - jsonschema==4.18.4
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.3.0
      - jupyter-core==5.3.1
      - jupyter-events==0.6.3
      - jupyter-server==2.7.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - keras==2.12.0
      - kiwisolver==1.4.4
      - lazy-loader==0.3
      - libclang==16.0.6
      - llvmlite==0.40.1
      - locket==1.0.0
      - magicgui==0.7.2
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mistune==3.0.1
      - ml-dtypes==0.2.0
      - msgpack==1.0.5
      - msgpack-numpy==0.4.8
      - mypy-extensions==1.0.0
      - napari==0.4.18
      - napari-console==0.0.8
      - napari-deeplabcut==0.2.0
      - napari-plugin-engine==0.2.0
      - napari-svg==0.1.10
      - natsort==8.4.0
      - nbclassic==1.0.0
      - nbclient==0.8.0
      - nbconvert==7.7.3
      - nbformat==5.9.1
      - ndindex==1.7
      - nest-asyncio==1.5.6
      - networkx==3.1
      - notebook==6.5.4
      - notebook-shim==0.2.3
      - npe2==0.7.2
      - numba==0.57.1
      - numpy==1.25.1
      - numpydoc==1.5.0
      - oauthlib==3.2.2
      - opencv-python==4.8.0.74
      - opencv-python-headless==4.8.0.74
      - opt-einsum==3.3.0
      - overrides==7.3.1
      - packaging==23.1
      - pandas==2.0.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - partd==1.4.0
      - patsy==0.5.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.0
      - pims==0.6.1
      - pint==0.22
      - platformdirs==3.9.1
      - pooch==1.7.0
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - protobuf==4.23.4
      - psutil==5.9.5
      - psygnal==0.9.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pydantic==1.10.12
      - pygments==2.15.1
      - pyopengl==3.1.7
      - pyparsing==3.0.9
      - pyproject-hooks==1.0.0
      - pyside6==6.3.1
      - pyside6-addons==6.3.1
      - pyside6-essentials==6.3.1
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - pyzmq==25.1.0
      - qdarkstyle==3.1
      - qtconsole==5.4.3
      - qtpy==2.3.1
      - referencing==0.30.0
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.4.2
      - rpds-py==0.9.2
      - rsa==4.9
      - ruamel-yaml==0.17.32
      - ruamel-yaml-clib==0.2.7
      - scikit-image==0.21.0
      - scikit-learn==1.3.0
      - scipy==1.11.1
      - send2trash==1.8.2
      - shapely==2.0.1
      - shiboken6==6.3.1
      - six==1.16.0
      - slicerator==1.1.0
      - sniffio==1.3.0
      - snowballstemmer==2.2.0
      - soupsieve==2.4.1
      - sphinx==4.5.0
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - stack-data==0.6.2
      - statsmodels==0.14.0
      - superqt==0.4.1
      - tabulate==0.9.0
      - tensorboard==2.12.3
      - tensorboard-data-server==0.7.1
      - tensorflow-estimator==2.12.0
      - tensorflow-macos==2.12.0
      - tensorflow-metal==1.0.1
      - tensorpack==0.11
      - termcolor==2.3.0
      - terminado==0.17.1
      - tf-slim==1.1.0
      - threadpoolctl==3.2.0
      - tifffile==2023.7.18
      - tinycss2==1.2.1
      - tomli==2.0.1
      - tomli-w==1.0.0
      - toolz==0.12.0
      - torch==1.12.0
      - tornado==6.3.2
      - tqdm==4.65.0
      - traitlets==5.9.0
      - typer==0.9.0
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - uri-template==1.3.0
      - urllib3==1.26.16
      - vispy==0.12.2
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.1
      - werkzeug==2.3.6
      - wrapt==1.14.1
      - zipp==3.16.2
