### ISSUE TITLE
.label_frames() for second camera to show epipolar lines for labeling for 3d project not working

### ISSUE THREAD

**Issue by patrickdwyer33** [DeepLabCut/DeepLabCut#2332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

https://deeplabcut.github.io/DeepLabCut/docs/HelperFunctions.html
Here it says I can call label_frames with an additional parameter specifying the path of the 3d config file. I try to do so and I get "TypeError: label_frames() got an unexpected keyword argument 'config3d'".

Given I have already labeled the first camera, the gui should pop up and allow me to label the second camera while showing epipolar lines from the labels of the first camera. Is this functionality no longer supported? 

### Operating System

Mac 13.4.1

### DeepLabCut version

dlc version 2.3.5

### DeepLabCut mode

3d

### Device type

cpu

### Steps To Reproduce

1. Set up a 3d project.
2. extract first camera's frames
3. extract (by matching) second camera's frames (I'll note that this does not produce any observable changes in the second camera's "labeled-data" folder)
4. label first camera's frames
5. label second camera's frames

### Relevant log output

```shell
TypeError: label_frames() got an unexpected keyword argument 'config3d'
```

### Anything else?

I searched through the repository and did not find an instance of .label_frames() that seemed to be able to handle the additional parameter, nor did I see any implementation of these epipolar lines, but I could be wrong about that.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@jeylau can you look into this please - maybe not ported to napari gui yet?

**Comment by MMathisLab** [comment]
@jeylau can you complete this issue, thanks.
