### ISSUE TITLE
Deeplabcut docker assumes linux/amd64 when trying to install on Raspberry-pi4

### ISSUE THREAD

**Issue by pra-navM** [DeepLabCut/DeepLabCut#2335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I was trying to install Deeplabcut on Raspberry-pi4 which has a processor with arm64 architecture.
I get an error- "The requested images platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested"

How can I install Deeplabcut on Raspberry-pi? Deeplabcut docker images all seem to be built for "linux/amd64"

I tried using Anaconda as well but I get an error with Anaconda on both Ubuntu and Raspian OSes where Anaconda exits with a core dump on installation 
"line 354 Illegal instruction (core dumped) "$CONDA_EXEC" constructor --prefix "$PREFIX" --extract-conda-pkgs"

Appreciate your help, thank you!

### Operating System

Problem seen on both OSes
1. Ubuntu Desktop 22.04.2 LTS (64 bit)
2. Raspberry PI OS 64bit

### DeepLabCut version

dlc version
Error during installation itself!

### DeepLabCut mode

single animal

### Device type

Raspberry PI-4 (arm64 processor)

### Steps To Reproduce

1. install docker
2. Run "sudo deeplabcut-docker gui"
3. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @pra-navM! I think the easiest way to install DeepLabCut on a Raspberry Pi would be through Conda. But as you mentioned (and is documented [here](https://github.com/conda/conda/issues/11141)), it seems that Conda isn't working for Raspberry Pi, and I'm not sure there's much of a workaround.

This might be a painful workaround, but maybe could you try installing DeepLabCut using [miniforge](https://github.com/conda-forge/miniforge), which they mention in the Conda issue as working with Raspberry Pi.

I don't know what you plan on training models on a Raspberry Pi, but I wouldn't recommend that (I'm not sure it has enough compute for that). Even running inference might be a stretch, but I think that's more reasonable.

**Comment by MMathisLab** [comment]
I would use autopilot if you are trying to deploy DeepLabCut on a pi, as in Kane et al 2020 elife. 

Indeed our Docker is not for real-time dlc.
