### ISSUE TITLE
Issue with selecting folder for creating a project and cannot access folder

### ISSUE THREAD

**Issue by kyro7793** [DeepLabCut/DeepLabCut#234]
**Your Operating system and DeepLabCut version**
Windows 10 with Anaconda environment. 

**Describe the problem**
When I look to create the folder of the project, it won't let me select where to create it in whcih automatically places it in System32. Also, it won't let me access the folder to change the config file to match my experiment parameters. Thank you.

**Comment by MMathisLab** [comment]
In the terminal, use “cd” to navigate to where you want to create the project. Also, you can pass the variable “working_directory= yourfullpath” to determine the location. For any function you can type “?” For more information, ie, deeplabcut.create_new_project?
