### ISSUE TITLE
labeling gui hangs indefinitely (not responding)

### ISSUE THREAD

**Issue by sbgbash** [DeepLabCut/DeepLabCut#2340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have successfully extracted the frames I want to label but whenever I enter: 
`deeplabcut.label_frames(path_config)`
The napari GUI launches but hangs and will not do anything else. I eventually have to open task monitor and kill the porocess. 

At first I thought i might be a memory issue and perhaps my labeled data was too large. But i get the same error even when I work from a DLC project that is known to work (like horse-10)

### Operating System

Ventura 13.4.1

### DeepLabCut version

dlc version 2.3.5

### DeepLabCut mode

single animal

### Device type

I have a macos M1. I installed using the recommended steps:
- Using miniconda i created a DLC_M1 env as instructed 

### Relevant log output

```shell
>>> deeplabcut.label_frames('/Users/sbg/Documents/hai/horse10/config.yaml')
>>> Terminated: 15
/Users/sbg/miniconda3/envs/DLC_M1/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by sbgbash** [comment]
@fixed issue with memory swap config

**Comment by Wenlve-Zhou** [comment]
I'm experiencing the same problem, could you please tell me exactly how you solved it, thanks!

**Comment by sbgbash** [comment]
I ended up launching via `python -m deeplabcut` this launched the gui and i was able to label no problem. For some reason if i launched python and then tried to enter `deeplabcut.label_frames(config_path)` napari would load, hang and i would have to force quit with: `Terminated: 15`

try `python -m deeplabcut` make sure `which python` points to your miniconda3/env/dlc_m1/bin you should be good to go. Let me know how it goes.

**Comment by Tetra-quark** [comment]
I get the same error when trying to launch the labeling GUI from the terminal or a script. Works fine if I launch the full GUI with `python -m deeplabcut`.
