### ISSUE TITLE
Low GPU usage and slow analysis/training

### ISSUE THREAD

**Issue by rapacotta** [DeepLabCut/DeepLabCut#2343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi! I have been trying to analyze some videos with DLC but noticed that the analysis was going very slowly. I then checked the GPU usage with `nvidia-smi`, showing me that roughly 6000 MiB were used out of 24000 MiB, as you can see below.

![nvidia-smi6000](https://github.com/DeepLabCut/DeepLabCut/assets/71755868/b47b2be8-1e83-436f-abe8-0826c3323885)

I already had this while training the model. I think it might be an issue due to my CUDA versions installed. Before installing DLC I installed the CUDA version 12.2, and when I tried to train it, it showed me the following error where DLC asked for a bunch of dll files from CUDA v11.x. Not being able to solve this issue in another way, I also installed CUDA v11.8

![dlc error training](https://github.com/DeepLabCut/DeepLabCut/assets/71755868/990c25f8-5869-49ad-ae44-a8931d050714)

Then I saw that the GPU usage during the training was pretty low and also crashed around 26000 iterations, so I uninstalled CUDA v12.2 and then tried to retrain the model but then DLC asked me for a DLL file from CUDA v12.2 (I don't have a picture of that error but the file asked was cublasLt64_12.dll). So I then reinstalled CUDA v12.0 to get the same file again. 

Does any of this makes sense? Can anyone explain the low GPU use?

Thanks!

### Operating System

operating system windows 10

### DeepLabCut version

dlc version 2.3.5

### DeepLabCut mode

multi animal

### Device type

gpu rtx 4090

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @rapacotta, low GPU memory usage does not indicate an incorrect installation (if the GPU is being used your installation should be correct). To increase GPU usage, increase the batch size in the configuration files (you can increase the batch size up to a given point, but will get an OOM error if you increase it too much as happened [here](https://github.com/DeepLabCut/DeepLabCut/issues/2318)).

Some more information is given [here](https://github.com/DeepLabCut/DeepLabCut/issues/2292#issuecomment-1610831355).

**Comment by vitorniskier** [comment]
Hey!

I've tried increasing batch size, eta dimished but GPU usage still at 0% on colab demo notebook. 

I'm trying to do a benchmark on GPU consumption so that we at the laboratory I'm working at can determine what GPU to acquire. 

Anyone know how to work around this?

**Comment by vitorniskier** [comment]
Found a solution: https://forum.image.sc/t/deeplabcut-not-using-gpu/30088
