### ISSUE TITLE
AttributeError: 'PySide6.QtGui.QAction' object has no attribute 'menu'

### ISSUE THREAD

**Issue by mrek235** [DeepLabCut/DeepLabCut#2344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello, I am trying to use DeepLabCut and while trying to label the frames I come across such a problem and I couldn't find a solution. I am running DeepLabCut on a small-ish GPU cluster with Ubuntu 20.04. I installed it through the instructions on the github page using pip. I also tried to upgrade nepari, but it didn't change the result. Is there a known solution to this problem?

All help is much appreciated.

### Operating System

Ubuntu 20.04

### DeepLabCut version

2.3.5

### DeepLabCut mode

single animal

### Device type

RTX Quadro 5000 GPUs

### Steps To Reproduce

1- Create a conda environment
2- Follow the installation steps using pip

### Relevant log output

```shell
File "/home/gk_gpu7920/.local/lib/python3.8/site-packages/deeplabcut/gui/tabs/label_frames.py", line 55, in label_frames
    _ = launch_napari(folder)
  File "/home/gk_gpu7920/.local/lib/python3.8/site-packages/deeplabcut/gui/widgets.py", line 38, in launch_napari
    viewer = napari.Viewer()
  File "/home/gk_gpu7920/.local/lib/python3.8/site-packages/napari/viewer.py", line 67, in __init__
    self._window = Window(self, show=show)
  File "/home/gk_gpu7920/.local/lib/python3.8/site-packages/napari/_qt/qt_main_window.py", line 564, in __init__
    self._add_menus()
  File "/home/gk_gpu7920/.local/lib/python3.8/site-packages/napari/_qt/qt_main_window.py", line 718, in _add_menus
    self.file_menu = menus.FileMenu(self)
  File "/home/gk_gpu7920/.local/lib/python3.8/site-packages/napari/_qt/menus/file_menu.py", line 149, in __init__
    self._rebuild_samples_menu()
  File "/home/gk_gpu7920/.local/lib/python3.8/site-packages/napari/_qt/menus/file_menu.py", line 211, in _rebuild_samples_menu
    menu = self.open_sample_menu.addMenu(
AttributeError: 'PySide6.QtGui.QAction' object has no attribute 'menu'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by mrek235** [comment]
I ran  " pip install pyside2" and it works now.

**Comment by mrek235** [comment]
Okay, found something interesting: Deeplabcut gui uses Pyside6, Napari needs Pyside2 and I couldn't yet find a solution to make them work at the same time. I can run napari standalone, but not from Deeplabcut GUI

**Comment by jeylau** [comment]
@mrek235, run `pip install -U napari-deeplabcut`. This will pull the latest version of our plugin, which works with the most recent napari release and pyside6 without problems.

**Comment by mrek235** [comment]
Thank you for your kind suggestion! I tried it, and for whatever the reason it doesn't seem to work in our system, I tried the installation steps on my Windows laptop it worked fine. However in our Gpu Rack with Ubuntu 20.04, it doesn't seem to work. I recreated environments again but still get the same PySide6.QtGui.QAction has no attribute 'menu' error.

**Comment by kephale** [comment]
Howdy! 

I ran into a similar error when creating a fresh napari environment without DLC. I believe this is an upstream issue in napari because it looks like `QAction.menu` has been deprecated (https://forums.ankiweb.net/t/add-on-issues-with-anki-2-1-50-beta/15631).
