### ISSUE TITLE
DeepLabCut headless commands not working

### ISSUE THREAD

**Issue by aaroncherian** [DeepLabCut/DeepLabCut#2345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hey there - I'm pretty new to using DLC so apologies if I am missing something obvious - but I trained a model using the DeepLabCut GUI, and now I am trying to use headless mode to do work with that same model. However, I'm having trouble getting some commands to work.

For example, the `extract_frames` command does not appear to do anything. I'm using this script:

![image](https://github.com/DeepLabCut/DeepLabCut/assets/17153275/89cb7d64-d7a4-4bab-8184-11082729e5e9)

And in the terminal all I see is this result:

![image](https://github.com/DeepLabCut/DeepLabCut/assets/17153275/3ff9290e-52e6-4f64-8d59-f869081903f2)

I see that an icon for the napari viewer briefly appears in my taskbar, and then disappears.

The same happens if I try `deeplabcut.refine_labels(config_path)`.

I am also unsure of the function of extracting labels vs. refining them. Is there an option in the GUI for refining labels? Because I was only able to see a tab for `extract outlier frames`. 

![image](https://github.com/DeepLabCut/DeepLabCut/assets/17153275/8864979a-6191-43f5-8f2b-807529ad00d1)

And to reiterate, I have been able to get the GUI working successfully and train a model on there - it's the headless commands that are giving me some trouble currently. Thanks!

### Operating System

Windows 10

### DeepLabCut version

deeplabcut 2.3.5

### DeepLabCut mode

single animal

### Device type

NVIDIA GeForce RTX 3090

### Steps To Reproduce

1. Create a python 3.8 environment in Anaconda
2. Install deeplabcut into environment
3. Use the scripts screenshotted above to try the headless commands

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @aaroncherian, how are you running the scripts exactly (which commands in the anaconda shell)?

**Comment by aaroncherian** [comment]
Hey there - 

![image](https://github.com/DeepLabCut/DeepLabCut/assets/17153275/120e5422-7581-4043-a59d-00cb505e3f61)

Not sure if this answers your question - but I'm using VSCode with the script above.

**Comment by MMathisLab** [comment]
Mode 'manual' requires a gui so does not work in headless environment. I'd recommend using automatic (which is kmeans).


@jeylau can you check why no refine labels tab shows up for him in main gui?

**Comment by jeylau** [comment]
@aaroncherian, in the `Extract outlier frames` tab, there are buttons on the right, the `Labeling GUI` one allows you to launch the GUI for refinement after outlier frames were extracted. As Mackenzie noted though, the `manual` mode won't work in DLC headless; note that the right function is `deeplabcut.extract_outlier_frames` and that the default algorithm is `jump`, where a frame is marked as outlier if keypoints are displaced in excess of a certain amount between this frame and the previous one.

**Comment by aaroncherian** [comment]
Hey there, thanks for the response! I think I need a bit of help understanding how to properly use the GUI here.

When I use the 'Extract frames` button, should I be expecting anything to pop up or to see any response? When I press it, I see this in the command prompt, but nothing else happens:

![image](https://github.com/DeepLabCut/DeepLabCut/assets/17153275/f6742753-d30c-4c50-8ef3-4edc424c0a01)

If I then opening the labelling GUI, it looks like this:

![image](https://github.com/DeepLabCut/DeepLabCut/assets/17153275/30a9fecb-ed87-4f9c-8962-5a4320379265)

There's no frames in there that I can see to refine. This is also the tooltip that appears in the GUI on the bottom left:

![image](https://github.com/DeepLabCut/DeepLabCut/assets/17153275/5b2b04cd-feb1-4684-8dcd-00e48001956b)

Apologies if I'm missing something obvious, but I could use help understanding what the proper procedure here should be!

**Comment by MMathisLab** [comment]
No worries! Let me write down what should happen, and I will look into it :D

**Step 1:** 
run extract frames (see button on the right):
**Step 2:**
then, once done, click "Labeling GUI"
![Screen Shot 2023-08-18 at 6 15 47 PM](https://github.com/DeepLabCut/DeepLabCut/assets/28102185/d42fb38c-294b-44fc-8094-48c9b27b6399)

Then the napari gui pops up, **and you go File > open folder > and open the new folder that is in labeled_data** with the new videos extracted frames (and you will see machine-labeled.h5 file ). Then you can see points on images, drag them around, delete occluded points, etc, and save!


Then once you refine all the folders, you click "merge datasets" and this creates a new iteration in your dlc project folder.

**Comment by aaroncherian** [comment]
Hey there, thanks very much! I was able to get it working and successfully refine the model. I appreciate the help a lot.
