### ISSUE TITLE
Can not generate .h5 file after running " deeplabcut.analyze_videos() "

### ISSUE THREAD

**Issue by Ruoqi277** [DeepLabCut/DeepLabCut#2347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hey,

I have labelled the frame from Deeplabcut 2.3.5, after that I upload the entirely folder to my colab.
When I run deeplabcut.analyze_videos() on colab to analyse the video , it shows " The videos are analyzed. Now your research can truly start! You can create labeled videos with 'create_labeled_video'"

But I found there is no .h5 file in the video folder ( There is only the video .mp4 file )

I tried the solution from #1637
But it doesn't work.

Best,
Ruoqi

### Operating System

operating system: window10

### DeepLabCut version

dlc version 2.3.5

### DeepLabCut mode

single animal

### Device type

gpu gpu

### Relevant log output

```shell
Using snapshot-72500 for model /content/drive/MyDrive/Colab Deeplabcut/test2-ruoqi-2023-08-04/dlc-models/iteration-0/test2Aug4-trainset95shuffle1
/usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
Analyzing all the videos in the directory...
Starting to analyze %  /content/drive/MyDrive/Colab Deeplabcut/f1test-cai-2023-08-07/videos/f3.mp4
Loading  /content/drive/MyDrive/Colab Deeplabcut/f1test-cai-2023-08-07/videos/f3.mp4
Starting to analyze %  /content/drive/MyDrive/Colab Deeplabcut/f1test-cai-2023-08-07/videos/f1.mp4
Loading  /content/drive/MyDrive/Colab Deeplabcut/f1test-cai-2023-08-07/videos/f1.mp4
Starting to analyze %  /content/drive/MyDrive/Colab Deeplabcut/f1test-cai-2023-08-07/videos/f2.mp4
Loading  /content/drive/MyDrive/Colab Deeplabcut/f1test-cai-2023-08-07/videos/f2.mp4
The videos are analyzed. Now your research can truly start! 
 You can create labeled videos with 'create_labeled_video'
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
DLC_resnet50_test2Aug4shuffle1_72500
```

### Anything else?

I tried to install tables==3.7.0 and restart runtime 
And also rename the video

It doesn't work.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @Ruoqi277, I see that you're running DeepLabCut in Google Colab. How exactly are you calling the `deeplabcut.analyze_videos` method (with which parameters)?

I tried to replicate your issue on Google Colab in one of my own projects, but was not able to (the files were created and output correctly). Did you refresh the files using the button in the Colab GUI to see if the files were written properly?
![colab_refresh](https://github.com/DeepLabCut/DeepLabCut/assets/45132115/41054428-f6e1-418c-affd-020c6e15ce0b)

And if you run `create_labeled_video`, does it actually crash saying the videos were not analyzed?

**Comment by Ruoqi277** [comment]
> Hi @Ruoqi277, I see that you're running DeepLabCut in Google Colab. How exactly are you calling the `deeplabcut.analyze_videos` method (with which parameters)?
> 
> I tried to replicate your issue on Google Colab in one of my own projects, but was not able to (the files were created and output correctly). Did you refresh the files using the button in the Colab GUI to see if the files were written properly? ![colab_refresh](https://user-images.githubusercontent.com/45132115/259694949-41054428-f6e1-418c-affd-020c6e15ce0b.png)
> 
> And if you run `create_labeled_video`, does it actually crash saying the videos were not analyzed?

Thank you for your reply!
Actually, I modified some parameters( default_augmenter: ) in the config file, and it works!

I'm not very clear about why it works, but I'm happy 👍
