### ISSUE TITLE
deeplabcut.analyze_videos returns the model name not an array of inference results 

### ISSUE THREAD

**Issue by Stanley-Michael** [DeepLabCut/DeepLabCut#2348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

in pose_estimation_tensorflow > predict_videos.py 

Analyze_videos on line 268: states that it returns a pandas array of inference results but just returns the name of the model.

line 697: return DLCscorer  # note: this is either DLCscorer or DLCscorerlegacy depending on what was used!

### Operating System

Linux

### DeepLabCut version

dlc version

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

See deeplabcut.analyze_videos

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @Stanley-Michael, thanks for spotting this! We'll fix the documentation. To load the data frame containing the predictions, you can use the scorer returned by `analyze_videos` and then `auxiliaryfunctions.load_analyzed_data` method.
