### ISSUE TITLE
How to improve multi animal tracking?

### ISSUE THREAD

**Issue by lxspedeza** [DeepLabCut/DeepLabCut#2349]
**Is your feature request related to a problem? Please describe.**
Dear Community,

I'm fairly new to DLC and I'm trying to analyze 3 identical mice in their home cage. I collected various video types (taken in dark/light conditions, different resolutions etc) and trained the model on more than 300 labelled frames. Identity tracking is set to False. After training, the pose estimation is going fairly well, the predictions are amazing!! However when the frames are put together, the tracking of animals is not consistent. From one frame to the next Mus1's bodyparts just move from one part of the video to another. I tried fixing these switches manually, but in my 10 minute video there's so many switches, it takes a lot of time.

What parameters can I change to try to finetune the tracking of the bodyparts across frame? 

Thank you!

**Describe the solution you'd like**
I'd like the programe to compare the position of bodyparts in the previous frames and if it's very far away, realize that it's probably not right and switch identities until the difference between bodyparts in frame 1 and frame 2 is the smallest. 

**Describe alternatives you've considered**
Alternatively, are there any other tools that I could use for better tracking?

**Additional context**
I'm using DLC 2.3.5

**Comment by MMathisLab** [comment]
lots of points of the parameters to change in the main docs https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#optimized-animal-assembly-video-analysis and for discussions we kindly ask you check out these resources: https://github.com/DeepLabCut/DeepLabCut#get-assistance--be-part-of-the-dlc-community
