### ISSUE TITLE
error using deeplabcut.convert2_maDLC

### ISSUE THREAD

**Issue by WeissShahaf** [DeepLabCut/DeepLabCut#2350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

trying to use deeplabcut.convert2_maDLC, i get an error
File ~\.conda\envs\DLC\lib\site-packages\deeplabcut\utils\auxfun_multianimal.py:65, in extractindividualsandbodyparts(cfg)
     64 def extractindividualsandbodyparts(cfg):
---> 65     individuals = cfg["individuals"].copy()

it doesn't matter if i use forindividual or not as input.
also trying on different computers

### Operating System

operating system
win 10

### DeepLabCut version

dlc version
2.3.5

### DeepLabCut mode

single animal

### Device type

gpu A4000 / A6000 / RTX 8000

### Steps To Reproduce

    ...: deeplabcut.convert2_maDLC(config,userfeedback=False,forceindividual='Lizzy')

### Relevant log output

```shell
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[21], line 1
----> 1 deeplabcut.convert2_maDLC(config,userfeedback=False,forceindividual='Lizzy')

File ~\.conda\envs\DLC\lib\site-packages\deeplabcut\utils\auxfun_multianimal.py:277, in convert2_maDLC(config, userfeedback, forceindividual)
    274 video_names = [trainingsetmanipulation._robust_path_split(i)[1] for i in videos]
    275 folders = [Path(config).parent / "labeled-data" / Path(i) for i in video_names]
--> 277 individuals, uniquebodyparts, multianimalbodyparts = extractindividualsandbodyparts(
    278     cfg
    279 )
    281 if forceindividual is None:
    282     if len(individuals) == 0:

File ~\.conda\envs\DLC\lib\site-packages\deeplabcut\utils\auxfun_multianimal.py:65, in extractindividualsandbodyparts(cfg)
     64 def extractindividualsandbodyparts(cfg):
---> 65     individuals = cfg["individuals"].copy()
     66     if len(cfg["uniquebodyparts"]) > 0:
     67         individuals.append("single")

File ~\.conda\envs\DLC\lib\site-packages\ruamel\yaml\comments.py:842, in CommentedMap.__getitem__(self, key)
    840 def __getitem__(self, key: Any) -> Any:
    841     try:
--> 842         return ordereddict.__getitem__(self, key)
    843     except KeyError:
    844         for merged in getattr(self, merge_attrib, []):

KeyError: 'individuals'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
@WeissShahaf, do you confirm that you have a field `individuals` in your config.yaml file?

**Comment by WeissShahaf** [comment]
i did not.
now its saying:


In [11]: deeplabcut.convert2_maDLC(config)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[11], line 1
----> 1 deeplabcut.convert2_maDLC(config)

File ~\Anaconda3\envs\DLC\lib\site-packages\deeplabcut\utils\auxfun_multianimal.py:277, in convert2_maDLC(config, userfeedback, forceindividual)
    274 video_names = [trainingsetmanipulation._robust_path_split(i)[1] for i in videos]
    275 folders = [Path(config).parent / "labeled-data" / Path(i) for i in video_names]
--> 277 individuals, uniquebodyparts, multianimalbodyparts = extractindividualsandbodyparts(
    278     cfg
    279 )
    281 if forceindividual is None:
    282     if len(individuals) == 0:

File ~\Anaconda3\envs\DLC\lib\site-packages\deeplabcut\utils\auxfun_multianimal.py:65, in extractindividualsandbodyparts(cfg)
     64 def extractindividualsandbodyparts(cfg):
---> 65     individuals = cfg["individuals"].copy()
     66     if len(cfg["uniquebodyparts"]) > 0:
     67         individuals.append("single")

AttributeError: 'NoneType' object has no attribute 'copy'

In [12]:

**Comment by n-poulsen** [comment]
From the documentation [here](https://github.com/DeepLabCut/DeepLabCut/blob/main/docs/convert_maDLC.md), I believe you need to add the `individuals` value as such (it can be something else than `mouse1`, but you need to have a name there):

```
individuals:
- mouse1
```

Does this work for you?

**Comment by WeissShahaf** [comment]
here is my config.yaml:

    # Project definitions (do not edit)
Task: homecage
scorer: FSB
date: Mar30
multianimalproject: false
identity: False


    # Project path (change when moving around)
project_path: E:\homecage-FSB-2022-03-30

    # Annotation data set configuration (and individual video cropping parameters)
video_sets:
  /storage/laur/Data_3/BaierFelix/Pi_2/Pi_2_31_03_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_3/Pi_3_31_03_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_4/Pi_4_31_03_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_5/Pi_5_31_03_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_6/Pi_6_31_03_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_1/Pi_1_01_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_4/Pi_4_05_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_1/Pi_1_05_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_3/Pi_3_07_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_2/Pi_2_04_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_5/Pi_5_05_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_6/Pi_6_05_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_3/Pi_3_13_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_6/Pi_6_13_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_2/Pi_2_13_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_4/Pi_4_13_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_1/Pi_1_13_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_5/Pi_5_13_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_1/Pi_1_16_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_4/Pi_4_16_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_3/Pi_3_16_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_2/Pi_2_16_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_6/Pi_6_16_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_5/Pi_5_16_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_4/Pi_4_10_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_2/Pi_2_10_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_5/Pi_5_10_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_6/Pi_6_10_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_1/Pi_1_10_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_3/Pi_3_10_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_2/Pi_2_20_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_4/Pi_4_20_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_3/Pi_3_20_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_5/Pi_5_20_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_4/Pi_4_24_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_4/Pi_4_23_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_2/Pi_2_24_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_2/Pi_2_23_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_2/Pi_2_26_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_4/Pi_4_26_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_1/Pi_1_25_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_6/Pi_6_26_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_2/Pi_2_30_04_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_2/Pi_2_12_05_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_2/Pi_2_27_05_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_4/Pi_4_07_05_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /storage/laur/Data_3/BaierFelix/Pi_4/Pi_4_30_05_2022__06_30.mp4:
    crop: 0, 1640, 0, 1232
  /gpfs/laur/data/baierf/terra2/dlc/dlc1/terra2_2023_06_13__07_00.mp4:
    crop: 0, 1640, 0, 1232
  F:\DLC_proj\homecage-FSB-2022-03-30\videos\terra4_2023_07_30__07_00_720.mp4:
    crop: 0, 958, 0, 720
    
individuals:
- Lizzy
uniquebodyparts:



multianimalbodyparts:bodyparts:
- frontleft
- frontright
- backleft
- backright
- water
- food
- stone
- bark
- hutfront
- huttop
- nose
- headleft
- neck
- headright
- spine
- hip
- midtail
- tailtip

    # Fraction of video to start/stop when extracting frames for labeling/refinement

    # Fraction of video to start/stop when extracting frames for labeling/refinement

    # Fraction of video to start/stop when extracting frames for labeling/refinement

    # Fraction of video to start/stop when extracting frames for labeling/refinement

    # Fraction of video to start/stop when extracting frames for labeling/refinement

    # Fraction of video to start/stop when extracting frames for labeling/refinement

    # Fraction of video to start/stop when extracting frames for labeling/refinement

    # Fraction of video to start/stop when extracting frames for labeling/refinement

    # Fraction of video to start/stop when extracting frames for labeling/refinement

    # Fraction of video to start/stop when extracting frames for labeling/refinement

    # Fraction of video to start/stop when extracting frames for labeling/refinement

    # Fraction of video to start/stop when extracting frames for labeling/refinement

    # Fraction of video to start/stop when extracting frames for labeling/refinement

    # Fraction of video to start/stop when extracting frames for labeling/refinement

    # Fraction of video to start/stop when extracting frames for labeling/refinement

    # Fraction of video to start/stop when extracting frames for labeling/refinement

    # Fraction of video to start/stop when extracting frames for labeling/refinement

    # Fraction of video to start/stop when extracting frames for labeling/refinement

    # Fraction of video to start/stop when extracting frames for labeling/refinement

    # Fraction of video to start/stop when extracting frames for labeling/refinement

    # Fraction of video to start/stop when extracting frames for labeling/refinement

    # Fraction of video to start/stop when extracting frames for labeling/refinement
start: 0
stop: 1
numframes2pick: 30

    # Plotting configuration
skeleton: [[nose, headright], [nose, headleft], [headright, neck], [headleft, neck],
  [headright, hip], [headleft, hip]]
skeleton_color: white
pcutoff: 0.4
dotsize: 10
alphavalue: 0.25
colormap: turbo

    # Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.9
iteration: 12
default_net_type: resnet_50
default_augmenter: default
snapshotindex: -1
batch_size: 16

    # Cropping Parameters (for analysis and outlier frame detection)
cropping: false
    #if cropping is true for analysis, then set the values here:
x1: 0
x2: 640
y1: 277
y2: 624

    # Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 0
- 0
move2corner: true

**Comment by WeissShahaf** [comment]
after filling in the missing fields.
i get the following error:
[config.yaml.txt](https://github.com/DeepLabCut/DeepLabCut/files/12313011/config.yaml.txt)

```
In [26]: deeplabcut.convert2_maDLC(config)
Do you want to convert the annotation file in folder: E:\homecage-FSB-2022-03-30\labeled-data\Pi_2_31_03_2022__06_30 ?
yes/noy
This is a single animal data set, converting to multi... E:\homecage-FSB-2022-03-30\labeled-data\Pi_2_31_03_2022__06_30
C:\Users\weisss\Anaconda3\envs\DLC\lib\site-packages\deeplabcut\utils\auxfun_multianimal.py:316: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array(
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~\Anaconda3\envs\DLC\lib\site-packages\pandas\core\arrays\categorical.py:441, in Categorical.__init__(self, values, categories, ordered, dtype, fastpath, copy)
    440 try:
--> 441     codes, categories = factorize(values, sort=True)
    442 except TypeError as err:
File ~\Anaconda3\envs\DLC\lib\site-packages\pandas\core\algorithms.py:822, in factorize(values, sort, na_sentinel, use_na_sentinel, size_hint)
    820             values = np.where(null_mask, na_value, values)
--> 822     codes, uniques = factorize_array(
    823         values,
    824         na_sentinel=na_sentinel_arg,
    825         size_hint=size_hint,
    826     )
    828 if sort and len(uniques) > 0:
File ~\Anaconda3\envs\DLC\lib\site-packages\pandas\core\algorithms.py:578, in factorize_array(values, na_sentinel, size_hint, na_value, mask)
    577 table = hash_klass(size_hint or len(values))
--> 578 uniques, codes = table.factorize(
    579     values,
    580     na_sentinel=na_sentinel,
    581     na_value=na_value,
    582     mask=mask,
    583     ignore_na=ignore_na,
    584 )
    586 # re-cast e.g. i8->dt64/td64, uint8->bool
File pandas\_libs\hashtable_class_helper.pxi:5943, in pandas._libs.hashtable.PyObjectHashTable.factorize()
File pandas\_libs\hashtable_class_helper.pxi:5857, in pandas._libs.hashtable.PyObjectHashTable._unique()
TypeError: unhashable type: 'CommentedSeq'
During handling of the above exception, another exception occurred:
TypeError                                 Traceback (most recent call last)
Cell In[26], line 1
----> 1 deeplabcut.convert2_maDLC(config)
File ~\Anaconda3\envs\DLC\lib\site-packages\deeplabcut\utils\auxfun_multianimal.py:315, in convert2_maDLC(config, userfeedback, forceindividual)
    313 # -> adding (single,bpt) for uniquebodyparts
    314 for j, bpt in enumerate(uniquebodyparts):
--> 315     index = pd.MultiIndex.from_arrays(
    316         np.array(
    317             [2 * [cfg["scorer"]], 2 * ["single"], 2 * [bpt], ["x", "y"]]
    318         ),
    319         names=["scorer", "individuals", "bodyparts", "coords"],
    320     )
    322     if bpt in Data[cfg["scorer"]].keys():
    323         frame = pd.DataFrame(
    324             Data[cfg["scorer"]][bpt].values, columns=index, index=imindex
    325         )
File ~\Anaconda3\envs\DLC\lib\site-packages\pandas\core\indexes\multi.py:489, in MultiIndex.from_arrays(cls, arrays, sortorder, names)
    486     if len(arrays[i]) != len(arrays[i - 1]):
    487         raise ValueError("all arrays must be same length")
--> 489 codes, levels = factorize_from_iterables(arrays)
    490 if names is lib.no_default:
    491     names = [getattr(arr, "name", None) for arr in arrays]
File ~\Anaconda3\envs\DLC\lib\site-packages\pandas\core\arrays\categorical.py:3007, in factorize_from_iterables(iterables)
   3003 if len(iterables) == 0:
   3004     # For consistency, it should return two empty lists.
   3005     return [], []
-> 3007 codes, categories = zip(*(factorize_from_iterable(it) for it in iterables))
   3008 return list(codes), list(categories)
File ~\Anaconda3\envs\DLC\lib\site-packages\pandas\core\arrays\categorical.py:3007, in <genexpr>(.0)
   3003 if len(iterables) == 0:
   3004     # For consistency, it should return two empty lists.
   3005     return [], []
-> 3007 codes, categories = zip(*(factorize_from_iterable(it) for it in iterables))
   3008 return list(codes), list(categories)
File ~\Anaconda3\envs\DLC\lib\site-packages\pandas\core\arrays\categorical.py:2980, in factorize_from_iterable(values)
   2975     codes = values.codes
   2976 else:
   2977     # The value of ordered is irrelevant since we don't use cat as such,
   2978     # but only the resulting categories, the order of which is independent
   2979     # from ordered. Set ordered to False as default. See GH #15457
-> 2980     cat = Categorical(values, ordered=False)
   2981     categories = cat.categories
   2982     codes = cat.codes
File ~\Anaconda3\envs\DLC\lib\site-packages\pandas\core\arrays\categorical.py:443, in Categorical.__init__(self, values, categories, ordered, dtype, fastpath, copy)
    441     codes, categories = factorize(values, sort=True)
    442 except TypeError as err:
--> 443     codes, categories = factorize(values, sort=False)
    444     if dtype.ordered:
    445         # raise, as we don't have a sortable data structure and so
    446         # the user should give us one by specifying categories
    447         raise TypeError(
    448             "'values' is not ordered, please "
    449             "explicitly specify the categories order "
    450             "by passing in a categories argument."
    451         ) from err
File ~\Anaconda3\envs\DLC\lib\site-packages\pandas\core\algorithms.py:822, in factorize(values, sort, na_sentinel, use_na_sentinel, size_hint)
    819             # Don't modify (potentially user-provided) array
    820             values = np.where(null_mask, na_value, values)
--> 822     codes, uniques = factorize_array(
    823         values,
    824         na_sentinel=na_sentinel_arg,
    825         size_hint=size_hint,
    826     )
    828 if sort and len(uniques) > 0:
    829     if na_sentinel is None:
    830         # TODO: Can remove when na_sentinel=na_sentinel as in TODO above
File ~\Anaconda3\envs\DLC\lib\site-packages\pandas\core\algorithms.py:578, in factorize_array(values, na_sentinel, size_hint, na_value, mask)
    575 hash_klass, values = _get_hashtable_algo(values)
    577 table = hash_klass(size_hint or len(values))
--> 578 uniques, codes = table.factorize(
    579     values,
    580     na_sentinel=na_sentinel,
    581     na_value=na_value,
    582     mask=mask,
    583     ignore_na=ignore_na,
    584 )
    586 # re-cast e.g. i8->dt64/td64, uint8->bool
    587 uniques = _reconstruct_data(uniques, original.dtype, original)
File pandas\_libs\hashtable_class_helper.pxi:5943, in pandas._libs.hashtable.PyObjectHashTable.factorize()
File pandas\_libs\hashtable_class_helper.pxi:5857, in pandas._libs.hashtable.PyObjectHashTable._unique()
TypeError: unhashable type: 'CommentedSeq'
```

**Comment by n-poulsen** [comment]
Try with
```
uniquebodyparts: []
```

Instead of 
```
uniquebodyparts:
- []
```

**Comment by WeissShahaf** [comment]
yes! that worked. though i don't see any change in the config or anything else.
and the default model still says resnet_50

**Comment by n-poulsen** [comment]
That's normal, it's the format of the labeled data that was changed (in your labeled-data folder, as explained in the [docs](https://github.com/DeepLabCut/DeepLabCut/blob/main/docs/convert_maDLC.md)). If you want you can update your config file to have `default_net_type: dlcrnet_ms5`.
