### ISSUE TITLE
Error when trying to Create training dataset

### ISSUE THREAD

**Issue by yrleftbrain** [DeepLabCut/DeepLabCut#2361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

All video frames are labeled. When I click “Create Training Dataset”, I get the following:

### Operating System

Windows

### DeepLabCut version

DLC 2.3.5 GUI

### DeepLabCut mode

single animal

### Device type

GPU NVIDIA GeForce RTX3060

### Steps To Reproduce

In deeplabcut environment. Loaded config file with all labeled frames. Clicked create train dataset --> error

### Relevant log output

```shell
Traceback (most recent call last):
File “C:\Users\Labpc\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\gui\tabs\create_training_dataset.py”, line 105, in create_training_dataset
deeplabcut.create_training_dataset(
File “C:\Users\Labpc\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py”, line 913, in create_training_dataset
model_path, num_shuffles = auxfun_models.check_for_weights(
File “C:\Users\Labpc\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\utils\auxfun_models.py”, line 70, in check_for_weights
download_weights(modeltype, model_path)
File “C:\Users\Labpc\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\utils\auxfun_models.py”, line 94, in download_weights
response = urllib.request.urlopen(url)
File “C:\Users\Labpc\anaconda3\envs\deeplabcut\lib\urllib\request.py”, line 222, in urlopen
return opener.open(url, data, timeout)
File “C:\Users\Labpc\anaconda3\envs\deeplabcut\lib\urllib\request.py”, line 531, in open
response = meth(req, response)
File “C:\Users\Labpc\anaconda3\envs\deeplabcut\lib\urllib\request.py”, line 640, in http_response
response = self.parent.error(
File “C:\Users\Labpc\anaconda3\envs\deeplabcut\lib\urllib\request.py”, line 569, in error
return self._call_chain(*args)
File “C:\Users\Labpc\anaconda3\envs\deeplabcut\lib\urllib\request.py”, line 502, in _call_chain
result = func(*args)
File “C:\Users\Labpc\anaconda3\envs\deeplabcut\lib\urllib\request.py”, line 649, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

### Anything else?

Other information that may be relevant: my python environments are on a separate drive than the deeplabcut project folders. They are both local drives but separate

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @yrleftbrain, which network architecture did you select for your training dataset? Was it `resnet_50`?

**Comment by yrleftbrain** [comment]
> 
Yes. resnet_50. I only get the issue with resnet

**Comment by yrleftbrain** [comment]
Attached is my pretrained model urls YAML file in C:\Users\Labpc\anaconda3\envs\dlc\Lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained . 
[pretrained_model_urls.docx](https://github.com/DeepLabCut/DeepLabCut/files/12449358/pretrained_model_urls.docx)

The URLs are fine and download when done directly, but the error persists. Seems like a particularly odd problem given mobilenet works fine. I even tried uninstalling and reinstalling dlc in different ways... i didn't have this issue with older versions of DLC (i don't remember which)/

**Comment by n-poulsen** [comment]
This is quite weird... I wasn't able to replicate your issue, and the pre-trained weights for the ResNet50 were downloaded correctly. The only thing I can think of would be the program not having the correct permissions to the folder, but from the error I'm not sure that's the issue.

 If you can download the model using the URL, could you simply do that and then place them in the correct folder (save them as `DeepLabCut/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt`). If they are already downloaded, the program won't try to download them again and you shouldn't have any issues running the code.

Let me know if that works for you

**Comment by yrleftbrain** [comment]
C:\Users\Labpc\DeepLabCut\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt

This is the extracted ckpt file from the tar.gz file. the GUI still tries to download it again and thus throws an error. How do i bypass this?

**Comment by yrleftbrain** [comment]
OK. I got it to work. The issue arose because of some proxy i did not know about (hospital-affiliated lab so many restrictions). For some reason ullib did not have permissions. I moved the downloaded file into the correct folder which was actually my conda environment, not the above path. Thanks for helping sort this out.

**Comment by yrleftbrain** [comment]
I can close this now.
