### ISSUE TITLE
Unable to generate .h5 files after labelling 

### ISSUE THREAD

**Issue by fontaineg** [DeepLabCut/DeepLabCut#2365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi, I have newly installed deeplabcut. I am able to create a new project and label frames using the terminal successfully, but I am unable to save labelled frames as .h5 files. 

When I try to save the "CollectedData" layer nothing happens and no new files are generated. When I save both the "Labels" and "CollectedData" files, a .csv and .tif file are generated but no .h5. Which means I can't progress to the training network step ("no annotated frames available").

I tried doing a clean install of DLC but the same issue persists. I have also tried converting the .csv file to a .h5 file using the command line but it still says I have no annotated frames available. No error messages show up in the terminal. 
 
Please let me know if you know a way to get around this!

### Operating System

operating system

### DeepLabCut version

dlc version 2.3.5

### DeepLabCut mode

single animal

### Device type

gpu - nvida driver 536.23 and cuda 11.3

### Steps To Reproduce

1. Create new project
2. Add bodyparts to .yaml file
3. Label frames in napari
4. Save "CollectedData" layer in napari - nothing happens
5. Save "CollectedData" and "Labels" layers in napari - only .csv and .tif file produced 
6. Try to create new training dataset - no annotated frames available 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @fontaineg, could you see an error printed in the terminal? Did you install deeplabcut with the provided conda environment files or differently? One culprit I can think of is a faulty installation of `pytables` (which could be fixed with `conda install pytables`), but I'm really just guessing.

**Comment by MMathisLab** [comment]
Stale issue.
