### ISSUE TITLE
Attribute Error when Running TestScript.py

### ISSUE THREAD

**Issue by Nike-Nay** [DeepLabCut/DeepLabCut#2369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I installed DeepLabCut onto my system and copied the github repo into my folder so I can use the testscript to make sure it was running correctly. 

However, when I run the testscript.py, after creating the training datatset, on line 140, I get the following 
AttributeError: module 'deeplabcut.utils.auxiliaryfunctions' has no attribute 'get_training_set_folder'

I am not sure if this is an issue with the auxiliary functions or a specific issue on my setup. Just for reference, I have not edited the testscript, I am using it as is from the repo.
![Screenshot (104)](https://github.com/DeepLabCut/DeepLabCut/assets/127593957/d2d138a0-f321-43ec-a554-c06a143ed11c)

### Operating System

Microsoft Windows 10 Home

### DeepLabCut version

dlc version: 2.2.1

### DeepLabCut mode

single animal

### Device type

Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz

### Steps To Reproduce

1. activate DEEPLABCUT
2. cd DeepLabCut/examples
3. python testscript.py

### Relevant log output

```shell
(base) C:\Users\asus\Desktop\Work\dlc>activate DEEPLABCUT

(DEEPLABCUT) C:\Users\asus\Desktop\Work\dlc>cd DeepLabCut\examples

(DEEPLABCUT) C:\Users\asus\Desktop\Work\dlc\DeepLabCut\examples>python testscript.py
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Imported DLC!
On Windows/OSX tensorpack is not tested by default.
CREATING PROJECT
Created "C:\Users\asus\Desktop\Work\dlc\DeepLabCut\examples\TEST-Alex-2023-09-05\videos"
Created "C:\Users\asus\Desktop\Work\dlc\DeepLabCut\examples\TEST-Alex-2023-09-05\labeled-data"
Created "C:\Users\asus\Desktop\Work\dlc\DeepLabCut\examples\TEST-Alex-2023-09-05\training-datasets"
Created "C:\Users\asus\Desktop\Work\dlc\DeepLabCut\examples\TEST-Alex-2023-09-05\dlc-models"
Copying the videos
C:\Users\asus\Desktop\Work\dlc\DeepLabCut\examples\TEST-Alex-2023-09-05\videos\reachingvideo1.avi
Generated "C:\Users\asus\Desktop\Work\dlc\DeepLabCut\examples\TEST-Alex-2023-09-05\config.yaml"

A new project with name TEST-Alex-2023-09-05 is created at C:\Users\asus\Desktop\Work\dlc\DeepLabCut\examples and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
EXTRACTING FRAMES
Config file read successfully.
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 8.53  seconds.
Extracting and downsampling... 256  frames from the video.
256it [00:01, 133.49it/s]
Kmeans clustering ... (this might take a while)
C:\Users\asus\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1043: UserWarning: MiniBatchKMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can prevent it by setting batch_size >= 3072 or by setting the environment variable OMP_NUM_THREADS=1
  warnings.warn(
Frames were successfully extracted, for the videos listed in the config.yaml file.

You can now label the frames using the function 'label_frames' (Note, you should label frames extracted from diverse videos (and many videos; we do not recommend training on single videos!)).
CREATING-SOME LABELS FOR THE FRAMES
Plot labels...
Creating images with labels by Alex.
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  3.70it/s]
If all the labels are ok, then use the function 'create_training_dataset' to create the training dataset!
CREATING TRAININGSET
Downloading a ImageNet-pretrained model from https://storage.googleapis.com/mobilenet_v2/checkpoints/mobilenet_v2_0.35_224.tgz....
The training dataset is successfully created. Use the function 'train_network' to start training. Happy training!
Traceback (most recent call last):
  File "C:\Users\asus\Desktop\Work\dlc\DeepLabCut\examples\testscript.py", line 140, in <module>
    trainingsetfolder = auxiliaryfunctions.get_training_set_folder(cfg)
AttributeError: module 'deeplabcut.utils.auxiliaryfunctions' has no attribute 'get_training_set_folder'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by Tetra-quark** [comment]
I would recommend updating your DLC version. The `get_training_set_folder` function was renamed last year.

**Comment by Nike-Nay** [comment]
Thanks for the quick response, I appreciate the help. I updated to the newest version (2.3.5) and managed to overcome that error but now run into a new error when attempting to evaluate the network:
TypeError: evaluate_network() got an unexpected keyword argument 'per_keypoint_evaluation'
![Screenshot (107)](https://github.com/DeepLabCut/DeepLabCut/assets/127593957/730a250a-8f3c-4342-bf40-be6e5835811b)
![Screenshot (108)](https://github.com/DeepLabCut/DeepLabCut/assets/127593957/2fd912b7-3989-4b12-b6e1-efcceae2ec20)
![Screenshot (109)](https://github.com/DeepLabCut/DeepLabCut/assets/127593957/a4abdf8b-8fc7-4469-919b-a247047de14b)
![Screenshot (110)](https://github.com/DeepLabCut/DeepLabCut/assets/127593957/edc80b7f-b4c0-47c9-a0f6-3e21c4c1d76c)
![Screenshot (111)](https://github.com/DeepLabCut/DeepLabCut/assets/127593957/96a2bf15-c5d0-44ef-a7cb-3895efb904a8)

**Comment by n-poulsen** [comment]
This issue is a duplicate of #2367
