### ISSUE TITLE
Plotting (via matplotlib) ACROSS animals with deeplabcut.plot_trajectories

### ISSUE THREAD

**Issue by JHartig** [DeepLabCut/DeepLabCut#2370]
I was wondering whether someone came up with some simple lines of code in order to get the plots which results from the deeplabcut.plot_trajectories function ACROSS multiple animals i.e. csv coordinate-time series outputs.

I guess that most people using DLC on e.g. mice would want plots not only cumulative accross 1 trial, but rather also have plots accross multiple animals.

Anyone got an idea for some more or less generic code? (Of course specific markers might be selected as well)

**Comment by MMathisLab** [comment]
Hi @JHartig can you clarify a bit? You mean instead of plots for each individual you'd like one mega plot with them all?
