### ISSUE TITLE
wx._core.wxAssertionError: (wxPython 4.2.1) bug

### ISSUE THREAD

**Issue by waynecwliu** [DeepLabCut/DeepLabCut#2371]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Bug description

Hello everyone,

I've been trying to create a user interface using WxPython. The program worked fine when I was using older versions of WxPython (WxPython 2.8) and Python (Python 2.6). However, when I attempted to upgrade to WxPython 4.2.1 and Python 3.11.5, the program stopped working.

After running it, I encountered an error code:
```
wx._core.wxAssertionError: C++ assertion "CheckSizerFlags(!((flags) & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL | wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL)))" failed at ..\..\src\common\sizer.cpp(2294) in wxBoxSizer::DoInsert(): wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL | wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL will be ignored in this sizer: wxEXPAND overrides alignment flags in box sizers
```
I would appreciate any suggestions or assistance you can provide.

**Comment by n-poulsen** [comment]
Hi @waynecwliu,

The newer versions of DeepLabCut do not use `wxpython` (PySide6 is used for the new GUI). So one easy way to use Python 3.11 would be to upgrade to the newest version of DeepLabCut.

If you're set on continuing to use the old GUI, I would think that Python 3.11 is not an issue. However, `wxpython` is pinned at version `<4.1`(as can be seen in the [setup file](https://github.com/DeepLabCut/DeepLabCut/blob/v2.2.3/setup.py)), so it will not be compatible with version `4.2.1`.
