### ISSUE TITLE
Ipython version issue when upgrading deeplabcut (don't use sudo ;)

### ISSUE THREAD

**Issue by mschart** [DeepLabCut/DeepLabCut#238]
hi there,

I just tried to upgrade deeplabcut using pip and got some ipython version issue. When downgrading ipython to 5.8.0 the issue remains:

```
(DLC) mic@mic-unige:~$ ipython --version
5.8.0
(DLC) mic@mic-unige:~$ sudo pip install deeplabcut -U
...
Collecting ipython~=6.0.0 (from deeplabcut)
  Could not find a version that satisfies the requirement ipython~=6.0.0 (from deeplabcut) (from versions: 0.10, 0.10.1, 0.10.2, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.13.2, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 4.0.0b1, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.1.0rc1, 4.1.0rc2, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.2.1, 5.0.0b1, 5.0.0b2, 5.0.0b3, 5.0.0b4, 5.0.0rc1, 5.0.0, 5.1.0, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.4.0, 5.4.1, 5.5.0, 5.6.0, 5.7.0, 5.8.0)
No matching distribution found for ipython~=6.0.0 (from deeplabcut)
```
Any advice is greatly appreciated.

Cheers,

Michael

**Comment by MMathisLab** [comment]
Hi there! 
if you try, without sudo, ``pip install deeplabcut==2.0.5`` do you still get the same error?

**Comment by AlexEMG** [comment]
Do you have python 2.7? -- for 3.x ipython is at 7.2 now or so... https://ipython.readthedocs.io/en/stable/install/install.html

**Comment by mschart** [comment]
Hi Alex,
no, that worked. 
`Successfully installed deeplabcut-2.0.5 ipython-6.0.0 prompt-toolkit-1.0.15 six-1.11.0`

**Comment by mschart** [comment]
The sudo caused the issue. 
Many thanks for your swift help!
