### ISSUE TITLE
Issue with launching GUI //installation on in Mac M2 chip

### ISSUE THREAD

**Issue by smsadegh** [DeepLabCut/DeepLabCut#2383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi, I installed DeepLabCut on a Mac Studio running on M2 chip . When in the terminal I run, 

**(DEEPLABCUT_M1) au539580@d54911 DeepLabCut % pythonw -m deeplabcut**

I get the below messages:

**Loading DLC 2.3.5...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
You installed DLC lite, thus GUI's cannot be used. If you need GUI support please: pip install 'deeplabcut[gui]''**

The version of the python I am using is 3.9.18. Also, I activated the environment and run **conda install python.app**, but still GUI doesn't appear.

If needed, I can send you the conda list, but for your information the package **wxpython** has been installed.

Thank you for your time,

Sadegh

### Operating System

MacOS, Ventura (13.5.2)

### DeepLabCut version

2.3.5

### DeepLabCut mode

single animal

### Device type

Apple M2 Max with 12‑core CPU, 38‑core GPU, 16‑core Neural Engine

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
wxpython has been outdated for at least 1 year, so please UNINSTALL it in the conda env and be sure to install napari-deeplabcut (I will show you how to get the latest, since it will be updated this week):

terminal:
```
conda activate DEEPLABCUT_M1
pip uninstall wxPython 
pip install git+https://github.com/DeepLabCut/napari-deeplabcut.git
```

pythonw is not needed, it should be python now (docs were recently updated, so that might have been missed :)

then:
```
python -m deeplabcut
```

Updated docs are here: 

https://deeplabcut.github.io/DeepLabCut/docs/installation.html

<img width="781" alt="Screen Shot 2023-09-17 at 11 29 57 AM" src="https://github.com/DeepLabCut/DeepLabCut/assets/28102185/60cdad90-3db4-45a4-ad3f-c6cd0b439d61">

Hope that solves your issue!

**Comment by smsadegh** [comment]
Thank you for your fast reply. I followed the above instruction and still got the same message. So, I installed deeplabcut from scratch (the package wxPython is removed). Below are the steps I took:

1. (base) au539580@d54911 ~ % _git clone https://github.com/DeepLabCut/DeepLabCut.git_
2. (base) au539580@d54911 ~ % _cd /Users/au539580/DeepLabCut/conda-environments_
3. (base) au539580@d54911 ~ % _conda env create -f DEEPLABCUT_M1.yaml_          
4. (base) au539580@d54911 ~ % _cd /Users/au539580/DeepLabCut_
5. (base) au539580@d54911 DeepLabCut % _conda activate DEEPLABCUT_M1_ 
6. DEEPLABCUT_M1) au539580@d54911 DeepLabCut % _pip install git+https://github.com/DeepLabCut/napari-deeplabcut.git_
7. (DEEPLABCUT_M1) au539580@d54911 DeepLabCut % _python3 -m deeplabcut_    

Following step 7) I get this message:

**Loading DLC 2.3.5...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
You installed DLC lite, thus GUI's cannot be used. If you need GUI support please: pip install 'deeplabcut[gui]''**

I get the same message after running _pip install 'deeplabcut[gui]'_

**Comment by MMathisLab** [comment]
Very strange! Can you confirm you're running locally, not on a server, and using miniconda3?

**Comment by smsadegh** [comment]
I am running on a local computer, and although I have anaconda installed too, but I think I am using miniconda 3 for deeplabcut (Please, see the screenshot) 

<img width="458" alt="Screenshot 2023-09-17 at 17 09 07" src="https://github.com/DeepLabCut/DeepLabCut/assets/56232965/1e9fcf74-cb63-40fa-9007-be9f2b3f494b">

**Comment by MMathisLab** [comment]
okay, thanks! I have no idea; I can confirm I can load the env on my M1 and M2 computers without issue :(.... if you pass in python 


```
pip3 install --no-cache-dir --upgrade deeplabcut[gui]
ENV DLClight=False

```

does this fix it?! last hope...

**Comment by smsadegh** [comment]
Sorry, do you mean in the terminal I run:

_pip3 install --no-cache-dir --upgrade deeplabcut[gui] 
ENV DLClight=False_

or run 

_python3 -m pip3 install --no-cache-dir --upgrade deeplabcut[gui] 
ENV DLClight=False_

**Comment by MMathisLab** [comment]
Sorry, to clarify, first line within Python/ipython, second within terminal

**Comment by MMathisLab** [comment]
did this work?  @smsadegh

**Comment by smsadegh** [comment]
Unfortunately, it didn't solve the problem. My own take is the problem
comes during creating the environment (*conda env create -f
DEEPLABCUT_M1.yaml*); specifically when it installs pip dependencies. I
tried updating and installing dependency packages separately in the
deeplabcut environment, but still the problem remains. I didn't want to
bother you with too many details.  But for your information, I attach part
of the copy of the text appearing during the installation.

**Comment by smsadegh** [comment]
Just wanted to update that the problem is now solved. What I had to do is **first to turn on Rosetta with the terminal app** (picture attached). Then follow your instruction.

1. (base) au539580@d54911 ~ % git clone https://github.com/DeepLabCut/DeepLabCut.git
2. (base) au539580@d54911 ~ % cd /Users/au539580/DeepLabCut/conda-environments
3. (base) au539580@d54911 ~ % conda env create -f DEEPLABCUT_M1.yaml
4. (base) au539580@d54911 ~ % conda activate DEEPLABCUT_M1
5. (DEEPLABCUT_M1) au539580@d54911 ~ % pip install git+https://github.com/DeepLabCut/napari-deeplabcut.git
6. (DEEPLABCUT_M1) au539580@d54911 ~ % python3 -m deeplabcut


<img width="399" alt="Screenshot 2023-10-06 at 16 21 17" src="https://github.com/DeepLabCut/DeepLabCut/assets/56232965/3bd55493-5890-4dec-8445-9eb0d5b7c077">

**Comment by MMathisLab** [comment]
Thanks so much!

**Comment by laurahgdrn** [comment]
I had the same problem on my M1 and was struggling with it for days - so thanks a lot for your tips! However, now that I finally got the GUI running to label the frames, I would like to use the "full_macaque" model, but I can only find "super animal_quadruped" (which basically takes forever). Was full_macaque depreciated or did I make a mistake while installing?

**Comment by MMathisLab** [comment]
The macaque model is still available in Colab - see demo notebooks - or locally, but we only support superanimal models in the gui. 

Can you tell me a bit more about "it takes forever" as it should be marginally slower because we adapt the model on the fly to your video, which is higher performance...

**Comment by laurahgdrn** [comment]
Thank you for your quick response, I was too quick with complaining! I actually was able to use the full_macaque model through the terminal and I am currently creating a pertained project using this code: 

deeplabcut.create_pretrained_project(
    project_name,
    experimenter,
    [video_path],
    model= "full_macaque",
    working_directory= r"/Users/hagedorn/Documents/TrackingProject",
    copy_videos= True,
    videotype= ".mp4",
    analyzevideo= True,
    filtered= True,
    createlabeledvideo= True,
    trainFraction= None
)

Currently it's at 82% after 1 hour and 23 mins of the first video. I have 4 videos of 30 mins to 1 hour, so it is actually quite slow. Is there a way to speed up the process? Or am I doing something wrong? I already preprocessed and compressed the video files. 

Duration of video [s]:  1620.57 , recorded with  30.0 fps!
Overall # of frames:  48617  found with (before cropping) frame dimensions:  900 500
Starting to extract posture
 82%|████████████████████████████▌      | 39680/48617 [1:23:50<19:29,  7.64it/

**Comment by MMathisLab** [comment]
Are you using an NVIDIA gpu? Apple is much, much slower for sure ...

**Comment by laurahgdrn** [comment]
Not I cannot, but then know why. I'll try to further compress the videos in order to speedup the process or I just need some patience. :) But thanks a lot for your quick help!
