### ISSUE TITLE
deeplabcut.create_labeled_video() extracting specific frames feature

### ISSUE THREAD

**Issue by ghost** [DeepLabCut/DeepLabCut#239]
HI,
Just a suggestions to have the capacity to extract only few selected frames or range of frames in the deeplabcut.create_labeled_video()  when extract frames is True.

**Comment by AlexEMG** [comment]
I see - I suppose this is for the case create_labeled_video(...,save_frames=True)? Would you like to pass the index, or have start and stop? [perhaps send a PR?]

**Comment by ghost** [comment]
yes passing an index would be nice

**Comment by AlexEMG** [comment]
Starting in DLC 2.0.5.1 you can pass, e.g.
```deeplabcut.create_labeled_video(path_config_file,[videopath],save_frames=True,Frames2plot=[0,1,2,33])```

**Comment by juplab** [comment]
Great! thanks for the quick implementation, works great
