### ISSUE TITLE
In DLC GUI, i can't change the default path when i create a new project

### ISSUE THREAD

**Issue by HaiYandada** [DeepLabCut/DeepLabCut#2391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When i create a new project, after writing the project name and experimenter, the program will complete the whole path.However, the default base path is "Desktop", and when i want to change the base path, it never worked. 

There is a concrete example: After finishing the blanks, it automatically generated the whole path as shown in the picture: "C:users\福娃\Desktop\First-Teresa-2023-09-20", and I changed it to a totally English path:"F:\First-Teresa-2023-09-20", and then i clicked the "create" button and the new project was created. However the config path was still the default "Desktop"!! 

<img width="961" alt="Snipaste_2023-09-20_11-10-27" src="https://github.com/DeepLabCut/DeepLabCut/assets/92616350/14e2c2ae-a0cd-40a4-9e7f-dfd7f7f8e0f0">
<img width="961" alt="Snipaste_2023-09-20_11-13-13" src="https://github.com/DeepLabCut/DeepLabCut/assets/92616350/aef676a2-f17f-44ae-8b40-7983de111fb6">
<img width="1201" alt="Snipaste_2023-09-20_11-13-42" src="https://github.com/DeepLabCut/DeepLabCut/assets/92616350/0e069b01-ae9c-4720-b45e-8950a360b47f">

### Operating System

operating system: win10

### DeepLabCut version

dlc version:2.3.5

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @HaiYandada! How did you edit the path: by editing the text within the input field, or by clicking on `Location` and selecting the desired directory?
