### ISSUE TITLE
Long Video Doesn't Fully Analyse

### ISSUE THREAD

**Issue by mikster36** [DeepLabCut/DeepLabCut#2397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Tried analysing a longer video than usual, ~7 hours at 1296x972 px. When finished analysing, it said the video was analysed; however, it immediately said 'killed', which I usually see after killing the python GPU process, so I don't think the full video was analysed. Additionally, the associated *_full.pickle file was significantly smaller than the same file for a shorter, 1h video (121 mb vs 600 mb). I suspect that this may be an issue with the video being corrupt?

### Operating System

Ubuntu 18.04.6 LTS

### DeepLabCut version

deeplabcut==2.2.3

### DeepLabCut mode

multi animal

### Device type

NVIDIA RTX2070

### Steps To Reproduce

deeplabcut.analyze_videos(config_path, [video_path], auto_track=False, robust_nframes=True, shuffle=4)

### Relevant log output

```shell
N/A
```

### Anything else?

unfortunately I lost the terminal output as my computer crashed while making this post; however, i will update with log output once I reproduce the error

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
> I suspect that this may be an issue with the video being corrupt?

This is likely; can you recode and test a smaller chunk?

**Comment by mikster36** [comment]
Yeah, the one hour video i mentioned is just a 1 hour chunk from the 7 hour one; I used deeplabcut's video editor to shorten the video. I am also trying to analyze the video using robust_nframes=True, so I can provide an update if that seems to be the solution.

**Comment by mikster36** [comment]
Update: after trying to analyse using robust_nframes=True, it still failed. The output suggests it failed at around 50%. I also ran it this time using allow_growth=True - not sure if this would have any impact.

 50%|█████████████████████████████████████████████████████████████████████▋                                                                      | 367440/738573 [7:55:38<8:56:44, 11.52it/s]
Killed

**Comment by MMathisLab** [comment]
@mikster36 how big are your video frames and how big is your GPU? 738,573 is a LOT of frames; and given the slow inference I worry you are filling up your GPU. You can monitor usage with `htop` and/or `nvidia-smi`

**Comment by mikster36** [comment]
Each frame is 1296x972 px, GPU has 8 GB of memory. When utilising the GPU with different deeplabcut methods, python usually accesses about 7.2 GB memory (that's what nvidia-smi displays). Would you suggest downsampling? 
Also, the video is recorded at 30 fps.

**Comment by MMathisLab** [comment]
Right, so the gpu isn't big enough to hold this - maDLC reasons across frames. You might consider using Google Colab where you could use a V100

**Comment by mikster36** [comment]
Ah, okay. Thanks for your help!
