### ISSUE TITLE
What are necessary files to share trained DLC models?

### ISSUE THREAD

**Issue by etterguillaume** [DeepLabCut/DeepLabCut#241]
**Your Operating system and DeepLabCut version**
Google Colab

**Describe the problem**
I have trained successfully DLC models on Google Colab, and was able to perform some inference on new videos in the same environment. Now, I would like to 'export' this trained model in a small compressed file that I could keep on the cloud and download on Google Colab whenever I would like to process new videos (Google Colab being very convenient, but I guess the general question concerns sharing models in general)
Since I would like to make the model as light as possible, I tried to avoid including the original training videos and the checkpoint files that are not used. However, when I try to run deeplabcut.analyze_videos(path_config_file,VideoFilePath) it seems to go through the analysis procedure seamlessly...

_Using snapshot-41000 for model /content/DLC_trained_model/dlc-models/iteration-0/Open fieldFeb1-trainset95shuffle1
INFO:tensorflow:Restoring parameters from /content/DLC_trained_model/dlc-models/iteration-0/Open fieldFeb1-trainset95shuffle1/train/snapshot-41000
INFO:tensorflow:Restoring parameters from /content/DLC_trained_model/dlc-models/iteration-0/Open fieldFeb1-trainset95shuffle1/train/snapshot-41000
The videos are analyzed. Now your research can truly start! 
 You can create labeled videos with 'create_labeled_video'.
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract any outlier frames!_

...however there is not progress bar and no videos are created. 
Now I know this is a lot of fiddling around so I did not expect it to work right away, but I was wondering:
- What files are still necessary when running inference?
- Namely, would I still need the training videos?
- Do I need all checkpoints to be present or only the one being used?
- Why is there no error message being issued?

In my previous training experiments that were successful, my trained models were inside the DeepLabCut git cloned folder: should my trained datasets always be inside the DeepLabCut folder?

I am sure many are interested in sharing trained models easily (after all at the end of the day the training phase should be only a small portion of the real work...)

Thanks again for all your support and take care!

**Comment by AlexEMG** [comment]
Short answer: Ideally just share the complete project folders -- you can of course delete snapshots that you don't need. The rest I would rather keep.  


What files are still necessary when running inference?
A snapshot (+ the file structure)

Namely, would I still need the training videos?
No. The videos are not important (neither are the training data themselves, but I would keep those around)

Do I need all checkpoints to be present or only the one being used?

No, you can keep any single one (or the last one etc.). Just make sure you keep all 3 files (i.e. snapshot-somenumber.index, snapshot-somenumber.meta, snapshot-somenumber.data-00000-of-00001)

Why is there no error message being issued?

There would be an error message, when there is an error.... "The videos are analyzed. Now your research can truly start!" suggests that: either the videos were already analyzed or they are not found (thus they were already analyzed). Perhaps check that you give the correct path?

**Comment by etterguillaume** [comment]
VideoFilePath was pointing to the right video (single video). Converting it to a list (with a single element) solved the problem:
VideoFilePath = [VideoFilePath]
I will experiment more with subtracting checkpoints/videos/ to make the model lighter before sharing. Thanks for your response too, take care.
