### ISSUE TITLE
Docker gui failed to start

### ISSUE THREAD

**Issue by AthiemoneZero** [DeepLabCut/DeepLabCut#2410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I try to use docker to run DLC according to installation tips. But I got such a bug as described below. 

### Operating System

ubuntus 22.04 in WSL2

### DeepLabCut version

deeplabcut-gui-latest image in docker

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

1. open terminal in WSL2;
2. `pip install deeplabcut-docker` before execute next command
3. enter `deeplabcut-docker gui`

### Relevant log output

```shell
`(base) ephys3@ZhouLab-Ephy3:~$ deeplabcut-docker gui

                    .--,       .--,
                    ( (  \.---./  ) )
                     '.__/o   o\__.'
                       `{=  ^  =}´
                         >  u  <
 ____________________.""`-------`"".______________________
\   ___                   __         __   _____       __  /
/  / _ \ ___  ___  ___   / /  ___ _ / /  / ___/__ __ / /_ \
\ / // // -_)/ -_)/ _ \ / /__/ _ `// _ \/ /__ / // // __/ /
//____/ \__/ \__// .__//____/\_,_//_.__/\___/ \_,_/ \__/  \
\_________________________________________________________/
                       ___)( )(___ `-.___.
                      (((__) (__)))      ~`

Welcome to DeepLabCut docker!

run-detectors: unable to find an interpreter for /usr/bin/docker-credential-desktop.exe
latest-gui: Pulling from deeplabcut/deeplabcut
Digest: sha256:3f08a9e7ee3b0d9ab9905cb13114363c70a012d656b5662b1dd888d9cbce43ad
Status: Image is up to date for deeplabcut/deeplabcut:latest-gui
docker.io/deeplabcut/deeplabcut:latest-gui
[2023-10-10T09:11:48+0800]: Configuring a local container for user ephys3 (1000) in group ephys3 (1000)
sha256:53d51ab7b9809cd0e01df9a679b298637b09d757b571878584ed9d63a601fcfb
[2023-10-10T09:11:49+0800]: Build succeeded
[2023-10-10T09:11:49+0800]: Using Linux config
docker: invalid spec: :/home/developer/.Xauthority: empty section between colons.
See 'docker run --help'.
[2023-10-10T09:11:49+0800]: Failed to launch the DLC GUI. Used args: "-e DISPLAY=unix:0 -v /tmp/.X11-unix:/tmp/.X11-unix -v :/home/developer/.Xauthority -v /home/ephys3:/app -w /app "
Container stopped.`
```

### Anything else?

To be noticed, `/bin/bash` (simple terminal mode with docker)  can work normally, although I found some problems with my GPU utility here :(

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by AthiemoneZero** [comment]
today with `deeplabcut-docker bash -v /home/mackenzie/DEEPLABCUT:/home/mackenzie/DEEPLABCUT`
it ran out of this:
`
                    .--,       .--,
                    ( (  \.---./  ) )
                     '.__/o   o\__.'
                       `{=  ^  =}´
                         >  u  <
 ____________________.""`-------`"".______________________
\   ___                   __         __   _____       __  /
/  / _ \ ___  ___  ___   / /  ___ _ / /  / ___/__ __ / /_ \
\ / // // -_)/ -_)/ _ \ / /__/ _ `// _ \/ /__ / // // __/ /
//____/ \__/ \__// .__//____/\_,_//_.__/\___/ \_,_/ \__/  \
\_________________________________________________________/
                       ___)( )(___ `-.___.
                      (((__) (__)))      ~`

Welcome to DeepLabCut docker!

run-detectors: unable to find an interpreter for /usr/bin/docker-credential-desktop.exe
Error response from daemon: Get "https://registry-1.docker.io/v2/": writing response to registry-1.docker.io:443: connecting to 127.0.0.1:7890: dial tcp 127.0.0.1:7890: connectex: No connection could be made because the target machine actively refused it.
Container stopped.`
Is this be due to my incorrect configuration of Docker?

**Comment by n-poulsen** [comment]
Hi @AthiemoneZero, I was able to replicate your issue from my side and am looking into it

**Comment by n-poulsen** [comment]
Hi @AthiemoneZero, GUI support was [dropped in 2.3.5+ due to too many numerous issues supporting them](https://deeplabcut.github.io/DeepLabCut/docs/docker.html#notes-and-troubleshooting). So to use the GUI, you'll have to install it directly in your operating system.
