### ISSUE TITLE
Error when trying to triangulate videos

### ISSUE THREAD

**Issue by Scottydoesntkno** [DeepLabCut/DeepLabCut#2415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I've received the error when trying "UnboundLocalError: local variable 'putativecam2name' referenced before assignment
".

### Operating System

macOS Sonoma

### DeepLabCut version

2.3.7

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

1. Check that config path = project_path
2. Double checking yaml final to ensure that it's correct
3. Ensuring that all paths are correct.
4. I've read other post and tried the solutions
![C592346A-F99B-429D-9018-242C6EE3CD67](https://github.com/DeepLabCut/DeepLabCut/assets/89419286/ecff7778-6f92-4396-a348-b964cd5fa0d3)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @Scottydoesntkno, it seems the problem might come from the name of your chosen video names. Would you be able to specify the names of the videos you're trying to analyze (just the name is enough, not the full path)?

If you can't share the video filenames, try renaming your videos. I see your camera names are `camera-1-` and `camera-2-`, so check if it works if you name the paired videos `camera-1-video1` and `camera-2-video1`

**Comment by Scottydoesntkno** [comment]
Ok I had the video files as ust camera-1- and camera-2- but I changed it to what you recommended.

I now receive this error "KeyError: 'trainingsetindex_camera-1-'"

**Comment by Scottydoesntkno** [comment]
OK, I got past this error by updating the yaml, and it produces a new error when it's trying to analyze the files: ModuleNotFoundError: spec not found for the module 'deeplabcut.pose_estimation_tensorflow.default_config'

Thank you again in advance!

**Comment by Scottydoesntkno** [comment]
You can close this error but I have a new one but Ill post it.

 It was due to the incorrect TF being installed, and I'm using a Mac M1. I followed this response: 

https://github.com/DeepLabCut/DeepLabCut/issues/2342#issuecomment-1668287031
