### ISSUE TITLE
bug report on the #239

### ISSUE THREAD

**Issue by ghost** [DeepLabCut/DeepLabCut#242]
Starting in DLC 2.0.5.1 you can pass, e.g.
deeplabcut.create_labeled_video(path_config_file,[videopath],save_frames=True,Frames2plot=[0,1,2,33])

The behavior of the current function is to overlay the bodayparts from the Frames2plot= index on the first frame of the video. For example :

deeplabcut.create_labeled_video(path_config_file,[videopath],save_frames=True,Frames2plot=[2500]) would out put the bodyparts from frame 2500 onto the video frame 1 instead of the video frame 2500

**Comment by AlexEMG** [comment]
Not elegantly fixed, but done. Thanks for raising this, the code should be switched to openCV
