### ISSUE TITLE
Label videos using DLC in Colab

### ISSUE THREAD

**Issue by neuropil** [DeepLabCut/DeepLabCut#2420]
Is there a way to label videos using the DLC framework in Colab?

**Comment by seesaw1992** [comment]
I think Colab doesn't offer the graphic interface for labeling. But if you may use other light weight labeling software to get the marks' coordination and transform them to csv and process in DLC colab version.

**Comment by neuropil** [comment]
That is an excellent suggestion!! Could you please direct me to the resource to demonstrate the structure I would need to input to Colab tutorial (i.e., output from my labeling process)? Thank you!

**Comment by n-poulsen** [comment]
Hi @neuropil, as mentioned you cannot label with DLC in Google Colab. However, you can label locally (on any Mac, Windows or Linux computer) and then train your model on Google Colab (simply upload your labeled project folder to Colab when you're done labelling). That will by far be the easiest way to do things.

Once you've labeled your data, you can use this [demo notebook](https://github.com/DeepLabCut/DeepLabCut/blob/main/examples/COLAB/COLAB_YOURDATA_TrainNetwork_VideoAnalysis.ipynb) to train a model and analyze videos.

**Comment by seesaw1992** [comment]
> That is an excellent suggestion!! Could you please direct me to the resource to demonstrate the structure I would need to input to Colab tutorial (i.e., output from my labeling process)? Thank you!

I think this link will help. https://forum.image.sc/t/how-to-generate-h5-files-from-pre-collected-data/61936
