### ISSUE TITLE
Direct linear transformation and scaling of marker coordinates within the DLC workflow

### ISSUE THREAD

**Issue by MSchellenberger** [DeepLabCut/DeepLabCut#2425]
**Overview**
When analyzing behavioral experiments in animal models, marker coordinates extracted through DLC often have to be transformed to account for the placement of the behavioral context and scaled to convert coordinates from px values to cm values. Hence, an optional transformation and scaling function within DLC would increase the usefulness for many users.

**Solution**
In most of those cases, the behavioral context has corners. These can be used to do a simple linear transformation and afterwards scaling by labeling at least three of the corners and thus generating an origin, as well as two basis vectors.
In behavioral contexts without corners, an object with those constant reference markers can easily be placed somewhere in the field of view of the camera.

**Application details**
Ideally those constant reference markers would be tracked with DLC to ensure that movement of the context between recordings does not affect the outcome. In this case, the marker names of the origin and basis vectors could be specified in the config file and the mean coordinate of high-likelihood datapoints could be used to generate an origin and basis vectors for the linear transformation.

Alternatively, defining the coordinates of the origin and basis vectors manually once per recording session would be sufficient in most cases. There, it would make sense to have the coordinates of origin and basis vectors as inputs, and to include a coordinate picker within the napari GUI.

In both cases, horizontal and vertical scaling factors should be specified in the config file.

Importantly, this is meant to be an optional feature of the video analysis step to increase versatility whilst keeping DLC user-friendly.

**Additional information**
Since this is a functionality that I personally use a lot, I wrote a [simple tool](https://github.com/Defense-Circuits-Lab/Transform_DLC) for it. Nonetheless, I think many people would benefit from getting transformed and scaled data out of DLC, which is why I would like to see it included in DLC itself.

Beyond that, I personally would even like to see additional preprocessing steps like video undistortion, filtering, interpolation, and smoothing in DLC as optional steps in the video analysis, since this would simplify the workflow of many users.

**Comment by MMathisLab** [comment]
hi @MSchellenberger thanks for the input. 

I agree using a ref. point can be very useful, and indeed people can define fiduciary keypoints to do this easily in their workflows. And indeed I have seen a # of papers that do this. You can also extract skeletons, which changes the ref frame with the in-built function `dlc.analyzeskeleton`. https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html#extract-skeleton-features

Re: " filtering, interpolation, and smoothing in DLC as optional steps in the video analysis "
>> this is in DLC already. You can see the function `dlc.filter_predictions`. https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html#j-filter-pose-data-data-recommended

I would also point you to several other tools that work with DLC data to do other things, i.e. 
 - DLCUtils, which has some helper functions from users, feel free to PR your tool in there: https://github.com/DeepLabCut/DLCutils
 - DLC2Kinematics, which is a package do do lots of useful transforms on the data: https://github.com/AdaptiveMotorControlLab/DLC2Kinematics
 
Adding more code to DLC is a huge decision, as it's a lot of time (and money) to maintain such features. Hence we we stick to our core functionality, and work intraoperatively with other tools to help then get their full analysis pipeline! Hope this helps!

**Comment by MSchellenberger** [comment]
Hi @MMathisLab thank you for the quick feedback!
I agree that it is always a big step to change the core software and that this has to be done with care. Hence, I understand that you don´t want to include this functionality and I would love to write a PR for DLCutils. To do this, it would be awesome if I could get some PR-mentorship from your team!
