### ISSUE TITLE
M2 Mac crash while training: `recursive_mutex lock failed`

### ISSUE THREAD

**Issue by smsadegh** [DeepLabCut/DeepLabCut#2427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Dear Mathis lab, in the process of training network I get the following error:

**libc++abi: terminating due to uncaught exception of type std::__1::system_error: recursive_mutex lock failed: Invalid argument
zsh: trace trap  python3 -m deeplabcut**

This appears to be related to locking a recursive mutex by a thread, repeatedly. If this exceeds an unspecified maximum number **std::system_error**  is issued (_https://en.cppreference.com/w/cpp/thread/recursive_mutex/lock_)

The error message could happen at any iteration number, but it mainly occurs between 20,000-50,000 (in an unlucky moment, it did happen at  iteration 98,000). In one occasion, it managed to complete a full training (100,000 iteration).

I was wondering if you could suggest a solution for this.

For your information, I noticed that even with 50,000 iteration, the trained network does a decent job in analysing videos. Also, although I use a Mac, the speed of iteration is not that slow (on 180 labeled images, 1,000 iterations take about 21 minutes). Here, I use miniforge 3.   

### Operating System

operating system: MacOS, Ventura (13.6)

### DeepLabCut version

dlc version: 2.3.7

### DeepLabCut mode

single animal

### Device type

Apple M2 Max with 12‑core CPU, 38‑core GPU, 16‑core Neural Engine

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @smsadegh, could you please provide the package versions you're using (the output of `pip list`)?

**Comment by smsadegh** [comment]
Please see the attached.
[dlc_package list.txt](https://github.com/DeepLabCut/DeepLabCut/files/13179005/dlc_package.list.txt)

**Comment by n-poulsen** [comment]
My best guess would be that it's because your tensorflow-metal and tensorflow versions aren't compatible. You have:
```bash
tensorflow-estimator          2.12.0
tensorflow-macos              2.12.0
tensorflow-metadata           1.14.0
tensorflow-metal              1.1.0
```

While from the [tensorflow-metal package](https://pypi.org/project/tensorflow-metal/), we can see that:
```bash

tensorflow	tensorflow-metal	MacOs	features
v2.5		v0.1.2			12.0+	Pluggable device
v2.6		v0.2.0			12.0+	Variable seq. length RNN
v2.7		v0.3.0			12.0+	Custom op support
v2.8		v0.4.0			12.0+	RNN perf. improvements
v2.9		v0.5.0			12.1+	Distributed training
v2.10		v0.6.0			12.1+	
v2.11		v0.7.0			12.1+	
v2.12		v0.8.0			12.1+	
v2.13		v1.0.0			12.1+	FP16 and BF16 support
v2.14		v1.1.0			12.1+	
```

DeepLabCut is only compatible with `tensorflow<2.13` on Apple M computers. If you run
```bash
pip install --upgrade tensorflow-macos==2.12.0 tensorflow-metal==0.8.0
```
does that solve your issue? And I'm curious, does it have any impact on training speed?

**Comment by smsadegh** [comment]
Thanks. Tonight, I will run it, and see if it is solved.

**Comment by smsadegh** [comment]
Unfortunately, the crash happened again (at iteration 33800) with the same error message. Nonetheless, thank you for helping me in this issue.

Regards,
Sadegh
