### ISSUE TITLE
wxPython dependency and subsequent issue on Linux OS (suppress wx on clusters)

### ISSUE THREAD

**Issue by isabellow** [DeepLabCut/DeepLabCut#243]
**Your Operating system and DeepLabCut version**

CentOS 7.x, Python 3.6.1 in cluster environment, and DeepLabCut2.x

**Is your feature request related to a problem? Please describe.**
I'm trying to train and analyze the DLC network on our university cluster, but am running into issues with wxPython. I had trouble installing wxPython, but was able to get it to install using:
`$ pip3 install --user -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/centos-7 wxPython`

This seemed to work, however I get the following error when I try to import in python 3.6:
```
>>> import wx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/users/ilow/.local/lib/python3.6/site-packages/wx/__init__.py", line 17, in 
<module> from wx.core import *
  File "/home/users/ilow/.local/lib/python3.6/site-packages/wx/core.py", line 12, in <module> 
from ._core import *
ImportError: libgtk-3.so.0: cannot open shared object file: No such file or directory
```

**Describe the solution you'd like**
 Is there a way to remove the wxPython dependency from the DLC import? I don't think that I'll need to use any of the GUI functions on the cluster (I've already built my training set and plan to evaluate the network on my personal computer, which has wxPython installed). Judging from the number of other issues related to installing wxPython on Linux, it seems like this could save people a lot of trouble, especially if they plan to analyze and train on a Linux with a GPU, but will use all GUI functions on a Mac or Windows OS.

**Describe alternatives you've considered**
I've tried operating within a "gtk+/3.22.18" module, but have found that wxPython still requires a module for sending desktop notifications, which is not currently installed on our cluster:
```
$ ml system gtk+/3.22.18
$ ml python/3.6.1
$ python3
>>> import wx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/users/ilow/.local/lib/python3.6/site-packages/wx/__init__.py", line 17, in <module> from wx.core import *
  File "/home/users/ilow/.local/lib/python3.6/site-packages/wx/core.py", line 12, in <module> from ._core import *
ImportError: libnotify.so.4: cannot open shared object file: No such file or directory
```

 I'm working with the cluster admin, but am not sure how much they will be able to do. Ultimately it feels a bit silly to jump through all these hoops just to import a package that I probably won't be using on this system.

Any assistance or advice would be greatly appreciated! Thank you!

**Comment by AlexEMG** [comment]
Yes, this is worked out. Obviously it doesn't make sense to install wx on servers etc. 

See: https://github.com/AlexEMG/DeepLabCut/issues/185
and page 7 in here https://www.biorxiv.org/content/biorxiv/early/2018/11/24/476531.full.pdf
