### ISSUE TITLE
Initial investigation - results differ between operating systems (Windows vs Ubuntu 20.04, WSL)

### ISSUE THREAD

**Issue by rahulporuri** [DeepLabCut/DeepLabCut#2430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Based on our initial investigation, it appears that the results generated by DeepLabCut on Windows 11 differ from the results generated on Ubuntu 20.04 (WSL). The results aren't substantially different but the difference is big enough that they effect further processing of pose estimates.

We're still investigating this but we wanted to open an issue to gather information on whether this is expected/known.

### Operating System

Windows 11 and Ubuntu 20.04 (WSL)

### DeepLabCut version

DeepLabCut 2.2.3 and DeepLabCut 2.3.7

### DeepLabCut mode

single animal

### Device type

gpu and cpu (gpu on windows and cpu on ubuntu 20.04 WSL)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by AlexEMG** [comment]
Thanks for raising this, we're looking forward to your report!

**Comment by sot-iris** [comment]
Hi both, I too have noticed this behaviour with single animal DLC-live. 

You can replicate this using Github Actions with a testing pipeline: extracting the coordinates from a given frame and asserting they're the same on: `[macos-latest-xlarge, ubuntu-latest, windows-latest]`

My guess is the models behave slightly differently given change in cpu/gpu architecture. As OP says, the difference is subtle but there's a difference nonetheless. Not an issue for my use case but just posting for visibility
