### ISSUE TITLE
Check benchmark submissions for completeness

### ISSUE THREAD

**Issue by stes** [DeepLabCut/DeepLabCut#2433]
**Is your feature request related to a problem? Please describe.**

The deeplabcut benchmark scripts currently do not check if a submission is complete, e.g. if predictions for all test images are returned, as noted by @n-poulsen .

**Describe the solution you'd like**

A good solution would be to add a few lines to [this part](https://github.com/DeepLabCut/DeepLabCut/blob/25f8c5026a03168358360e70c98039a7d7ed1b32/deeplabcut/benchmark/base.py#L91) of the evaluation code, sth along the lines of

```python
predictions = self.get_predictions(name)
self._validate_predictions(name)
...

def _validate_predictions(self, predictions):
  # check if predictions contains too many images not contained in the ground truth
  # check if predictions contains not all images in the ground truth
  # (other potential tests)
  pass
```

**Comment by MMathisLab** [comment]
@n-poulsen is this completed?
