### ISSUE TITLE
Calculate the oks and mAP

### ISSUE THREAD

**Issue by Shawn880629** [DeepLabCut/DeepLabCut#2435]
Hello, I am a graduate student currently researching dolphin skeletons and need to compare my work with other research papers. However, DeepLabCut only provides RMSE values for reference. I would like to know if there are other methods to obtain additional accuracy metrics, such as mAP and OKS values.

**Comment by AlexEMG** [comment]
DLC also computes mAP for multi-animal projects. Please, check out the multi animal DLC guide & see Lauer et al. Nature Methods. 

E.g. check the code here: 
https://github.com/DeepLabCut/DeepLabCut/blob/3ba648f38abf60b440e56d8dc4bcb062bd0a04af/deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py#L664

**Comment by AlexEMG** [comment]
https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#evaluate-the-trained-network
