### ISSUE TITLE
Unexpected behaviour while using 'tensorpack' augmentation method in GUI

### ISSUE THREAD

**Issue by nastya236** [DeepLabCut/DeepLabCut#2437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

On Window while running GUI with `tensorpack` augmentation method:

Operating System: Windows (exact version not specified)
Python Version: (not specified, please provide this if relevant)

<img width="659" alt="Capture" src="https://github.com/DeepLabCut/DeepLabCut/assets/41966024/b5426254-773f-4c71-beb4-06af9849045c">

Environment:
Python Version: 3.9.18

### Operating System

Windows 10

### DeepLabCut version

2.3.7 

### DeepLabCut mode

single animal

### Device type

CPU

### Steps To Reproduce

1. Open GUI
2. change augs method to `tensorpack`

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by AlexEMG** [comment]
Yeah, quick fix is use imgaug ;)

**Comment by nastya236** [comment]
Yep, created the issue just to be aware of the possible problem with Windows)
