### ISSUE TITLE
create labelled video: could not open codec 'mpeg4' 

### ISSUE THREAD

**Issue by heejaeyunajang** [DeepLabCut/DeepLabCut#244]
**Your Operating system and DeepLabCut version**
Ubuntu 16.04, DLC v2 

**Describe the problem**

create_labeled_video runs but does not generate a video. 
I had no trouble using this in the past when I compressed the videos locally using ffmpeg, but since I started compressing on the cluster, I get this issue. Every other step of Deeplabcut runs smoothly. 

[mpeg4 @ 0x564094fbbd80] timebase 1000/99923 not supported by MPEG 4 standard, the maximum admitted value for the timebase denominator is 65535
Could not open codec 'mpeg4': Unspecified error

**Comment by MMathisLab** [comment]
maybe ffmpeg is not installed on your cluster?

**Comment by heejaeyunajang** [comment]
It is. I suspect it's something about how the video is compressed. I'm compressing using ffmpeg and when I do this locally, all steps of DLC work fine. When I compress on the cluster, using the exact same ffmpeg options, DLC outputs the above error. Videos look fine whichever way I compress though.

**Comment by MMathisLab** [comment]
Hm, I'm not sure then (as our code doesn't contain this step), so I'm not sure how I can help out more... I'll close the issue, but if you find a solution perhaps post back here! To note, I would try using a compression codec that is supported by openCV. You can also run ``deeplabcut.create_labeled_video(cfp, video, save_frames=True)`` to make a video that uses a different backend. It is slower but better quality videos.

**Comment by heejaeyunajang** [comment]
If I specify the codec, it works.. I don't know why since by default the codec is mp4v.. but it works!

**Comment by cdj5044** [comment]
@heejaeyunajang 

I am actually having the same issue. I'm using Handbrake to compress the vids and then getting the same error when trying to create videos.

Would you mind posting an example of what you mean by specifying the codec? I use the GUI to run DLC, as I'm not super proficient with python, so it would be really helpful for me. Thank you so much, if you are able to.
