### ISSUE TITLE
Error in deeplabcut.create_training_dataset

### ISSUE THREAD

**Issue by CrazyGeG** [DeepLabCut/DeepLabCut#2441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I  used dataset labelled somewhere else, and create a csv file and used deeplabcut.convertcsv2h5('path_to_config.yaml', scorer= 'experimenter') to convert to h5, However when i run deeplabcut.create_training_dataset('path_to_config.yaml', net_type = 'resnet_50') it gives me following error:

temp = df.iloc[i].values.reshape(-1, 2)
  File "/home/an/miniconda3/envs/dlc38/lib/python3.8/site-packages/numpy/lib/index_tricks.py", line 419, in __getitem__
    res = self.concatenate(tuple(objs), axis=axis)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 17 and the array at index 1 has size 7 

My config file is:
video_sets:
  /mnt/Data_6_1/an/videos/ANTAA01STIM PILO.mp4:
    crop: 0, 1920, 0, 1080
bodyparts:
- nose
- ear_r
- ear_l
- neck
- jaw
- elbow-r
- elbow-l
- e-r
- e-l
- back
- tail
- k-r
- foot-r
- k-l
- t-r
- foot-l
- t-l
    # Fraction of video to start/stop when extracting frames for labeling/refinement
start: 0
stop: 1
numframes2pick: 20

    # Plotting configuration
skeleton: [['nose', 'ear-r'], ['nose', 'ear_l'],['ear_r', 'neck'],['ear_l', 'neck'],['jaw', 'neck'], ['neck', 'elbow-r'],
['neck', 'back'],['neck', 'elbow-l'],['elbow-r','e-r'],['elbow-l','e-l'],['back','tail'],['tail','k-r'],['tail','k-l'],
['k-r','foot-r'],['k-l','foot-l'],['foot-r','t-r'],['foot-l','t-l']]
skeleton_color: black
pcutoff: 0.6
dotsize: 12
alphavalue: 0.7
colormap: rainbow

### Operating System

LINUX

### DeepLabCut version

dlc version 2.3.8

### DeepLabCut mode

single animal

### Device type

gpu nvidia geforce

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by CrazyGeG** [comment]
I have checked labels and there is no error. Then I tried to create the training dataset and it gives the same error
>>> deeplabcut.check_labels('/mnt/Data_6_1/an/DeepLabCut/mouse_tracking-An-2023-11-09/config.yaml')
Creating images with labels by An.
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 726/726 [02:53<00:00,  4.19it/s]
If all the labels are ok, then use the function 'create_training_dataset' to create the training dataset!
>>> deeplabcut.create_training_dataset('/mnt/Data_6_1/an/DeepLabCut/mouse_tracking-An-2023-11-09/config.yaml',net_type = 'resnet_50')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/Data_6_1/an/DeepLabCut/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 1002, in create_training_dataset
    # Saving data file (convert to training file for deeper cut (*.mat))
  File "/mnt/Data_6_1/an/DeepLabCut/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 695, in format_training_data
    temp = df.iloc[i].values.reshape(-1, 2)
  File "/home/an/miniconda3/envs/dlc38/lib/python3.8/site-packages/numpy/lib/index_tricks.py", line 419, in __getitem__
    res = self.concatenate(tuple(objs), axis=axis)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 17 and the array at index 1 has size 7

**Comment by CrazyGeG** [comment]
I have solved this problem, and create training dataset is working

**Comment by Timeviewerzero** [comment]
> I have solved this problem, and create training dataset is working

I encountered the same problem. How did you solve this problem？
