### ISSUE TITLE
Mismatch between labeled video and csv created using analyze videos tab.

### ISSUE THREAD

**Issue by kamu7656** [DeepLabCut/DeepLabCut#2442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I’m tracking two animals and they are labeled the entire time in the video that was created using "create video with all detections" but the csv shows long stretches with no labels for either animal. I have not checked the .h5 file that was created, but the track refinement gui also has missing stretches of label so I assume that it matches the csv. This video has only been analyzed one time and the csv and labeled video were create using the analyze videos tab at the same time. 

This issue has been raised in the forum also: https://forum.image.sc/t/multi-animal-deeplabcut-video-labelled-not-matching-with-csv/85630

### Operating System

Linux/Ubuntu

### DeepLabCut version

2.3.7

### DeepLabCut mode

single animal

### Device type

gpu 

### Steps To Reproduce

conda activate DLC 
python3 -m deeplabcut
labeled many frames
created training dataset
created network (resnet and b0 both give same error)
analyze videos with "create video with all detections", "save result(s) as csv" checked

### Anything else?

![image](https://github.com/DeepLabCut/DeepLabCut/assets/60203249/c5f1660c-4778-4cf8-ba8b-649734703b01)

image on left shows frame in the track refinement gui without labels. image on right shows same frame from the labeled video that was created

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @kamu7656! Just to be sure I understand correctly, the video where the detections don't match with the output CSV file (the one uploaded to the Google Drive; I'm assuming you posted on the forum as well) is the one created with `create_video_with_all_detections`?

The reason this does not match the output in the `_el.csv` is that this file contains the keypoints after tracking. So if you create the video using `create_labeled_video`, it should match the contents of the file.

To view the detections as labeled in `create_video_with_all_detections`, you need to view the contents of the `_full.pickle` file. However, in that case the mice are not tracked (from one frame to another, your individuals might switch).

If there are long stretches of time where the tracking doesn't output the position of each individual, I would look into relaxing the tracking parameters: you can find those in your `dlc-models` folder (in `iteration-{i}/{your-model-name}/test/inference_cfg.yaml`). If you look at [Figure 3](https://www.nature.com/articles/s41592-022-01443-0#Fig3) in the publication, you can see that by increasing the `max_age` parameter (and maybe play around a bit/lower with the `iou_threshold`), you might get better tracking results. You can also check the [DeepLabCut documentation on tracking](https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#if-auto-track-false).

From looking at your video, it still seems that the detections can be a bit jittery when the mice are close to one another, so labeling a few more images when the mice are interacting should lead to better pose, better tracking and hence fewer times when no "tracked" detections occur (e.g., you can see at 2:32 that one of the mice has almost no keypoints detected - this shouldn't happen if you want better tracking).

**Comment by kamu7656** [comment]
Thanks! I'll try out those other parameters for tracking.

But I may also just try and write something that does some initial tracking
myself. Is there a simple way to turn that pickle file into a csv? I was
looking into the savemultianimalsfull function and was hitting an error
when trying to turn the dictionary into a csv. If there isn't a simple way
I can just go in and reformat the dict myself.

Also we've labeled thousands of frames across the lab from different videos
and we still have jitter in the labels. That video only has labels from a
particular experiment so there's far fewer frames but it seems to do better
than the more general network we've tried. Do you typically find that
that's the case? Are there settings that are better depending on whether
the frames are from different cameras/experiments or just from one specific
set up?

Thank you again for you help,
Kathleen

**Comment by n-poulsen** [comment]
You need to write a bit of custom code to do so (and the best way to go is to start from the `assemblies` file, as that is the file where keypoints are already grouped by "individual"). I'm sure there are already posts on our [forum](https://forum.image.sc/tag/deeplabcut) where people have discussed this.

When it comes to jitter in the videos, I would take a look at your labeled data (with the "check labels" button in the "label frames" tab of the GUI, or with `deeplabcut.check_labels(...)` in python, see our [docs](https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#check-annotated-frames) for more information). It's really important that your bodyparts are labeled consistently and without errors, as even just a few mistakes can lead to the model performing worse.

However, if your "more general" is tasked to make predictions on a "wider range" of setups (different cameras, lighting conditions, angles at which the animals are filmed), then it's a more difficult task for the model to learn and that might lead to performance that's a bit worse. The more homogeneous your data, the easier it is for the model to make predictions. But training on a wider range will make your model more robust and have it generalize better to new videos.

I'll close this issue, as it isn't really related to a problem in the code, but you can check the [forum](https://forum.image.sc/tag/deeplabcut) for more general discussions on the performance of DeepLabCut models!

**Comment by kamu7656** [comment]
Thank you so much!
