### ISSUE TITLE
Inconsistent requirements on TF

### ISSUE THREAD

**Issue by adrianloy** [DeepLabCut/DeepLabCut#2448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

The requirements of the package are not defined consistently. `requirements.txt` notes for tensorflow `
tensorflow>=2.0,<2.13.0` but setup.py notes for flavor `tf`: `"tensorflow>=2.0,<=2.10"`. Is it possible to run this package with tensorflow 2.12? I somehow think so but due to the definition of `setup.py` the following fails: `pip install deeplabcut[tf]==2.3.8 tensorflow==2.12`.

Additionally, the pytorch dependency does not allow torch==1.12.1 but it is probably just a mistake in the requirements definition `==1.12` and I assume if  1.12.0 is supported, 1.12.1 would probably also work.

### Operating System

Ubuntu 20.04

### DeepLabCut version

2.3.8

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

`pip install deeplabcut[tf]==2.3.8 tensorflow==2.12`

### Relevant log output

```shell
The conflict is caused by:
    The user requested tensorflow==2.12
    deeplabcut[tf] 2.3.8 depends on tensorflow<=2.10 and >=2.0; extra == "tf"
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by KonradDanielewski** [comment]
For Windows latest tensorflow version is `2.10.0` since this is the last supported one for this OS. Linux and MacOS can use `2.12.0` but both `2.10.0` should also work.

**Comment by adrianloy** [comment]
I see. Would you agree that `setup.py` should then be updated? Currently it is not possible to do `pip install deeplabcut[tf]==2.3.8 tensorflow==2.12` due to dependency conflict, even though as you said it should be possible to do this on Linux and MacOS.

**Comment by n-poulsen** [comment]
Hi @adrianloy!

As @KonradDanielewski said, we pin `tensorflow` to 2.10 when installing with DeepLabCut, as it is the [last version to support Windows Native GPUs](https://discuss.tensorflow.org/t/2-10-last-version-to-support-native-windows-gpu/12404).

This is also why `tensorflow` is an "extra" for the package: different versions of `tensorflow` work with DeepLabCut, and you can install `2.12` separately to DeepLabCut, if you use Linux or OS X. Additionally, the `apple_mchips` extra allows to install `tensorflow` for computers running Apple Silicon.

You can easily use `DeepLabCut` with `tensorflow` `2.12.0` on Linux by installing without the `tf` extra:

```bash
pip install deeplabcut==2.3.8 tensorflow==2.12
```

On Apple Silicon computers, you can install `DeepLabCut` with `tensorflow` by using

```bash
pip install deeplabcut==2.3.8 "tensorflow-macos<2.13.0" "tensorflow-metal"
```

or simply 

```bash
pip install "deeplabcut[apple_mchips]"
```

Let me know if this answers your question!

**Comment by adrianloy** [comment]
Thanks for the replies. Installing without the flavor to be able to still install it in a single step helped me.
