### ISSUE TITLE
Is there any chance of modifying the core code to improve the experimental results, also I see that your resnet network is downloaded directly from the web

### ISSUE THREAD

**Issue by learnbwt** [DeepLabCut/DeepLabCut#2450]
Is there any chance of modifying the core code to improve the experimental results, also I see that your resnet network is downloaded directly from the web

**Comment by KonradDanielewski** [comment]
Hi,

Could you be more specific about what you mean by improving experimental results? Yes the backbones are pretrained and downloaded as such

**Comment by n-poulsen** [comment]
Hi @learnbwt, yes you can modify the code yourself if you want to change how anything works (and re-install it), but I'm not sure what you mean by improving results. 

The ResNet backbone is downloaded from Tensorflow, and is pre-trained on a large dataset (this allows DeepLabCut models to work well on small datasets via transfer learning, which you can read about in the accompanying [publication](https://www.nature.com/articles/s41593-018-0209-y)).
