### ISSUE TITLE
Labels shifted in video and data file

### ISSUE THREAD

**Issue by tom221085** [DeepLabCut/DeepLabCut#2452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello!
I am using deeplabcut with the GUI for a multiple animal project with three mice. The evaluation results after training look really good.
However, when I analyze videos it seems as if the labels are shifted and, thus, move out of the field of view when the animals move too far north. In the data files, the labels are also shifted and there are no entries when the animals move north as well.

Here is a screenshot from an analyzed video:
![Shifted Tracklets DLC](https://github.com/DeepLabCut/DeepLabCut/assets/11939642/8d2dfc62-51cf-4fb5-8d97-a5a334ef9891)

I tried to see if there is a similar issue but I found only #1184 which doesn't seem to really give a solution for my specific problem.

I would really appreciate if someone could help me with that because except for the shift the tracking looks really good.

Thank you,
Thomas

### Operating System

Here's a screenshot that shows the system I am working at.
![Operating System](https://github.com/DeepLabCut/DeepLabCut/assets/11939642/a7efb6b0-b664-43bb-ba5f-97fa7a9df25b)

### DeepLabCut version

2.3.3

### DeepLabCut mode

multi animal

### Device type

NVIDIA Gforce RTX 3090

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by KonradDanielewski** [comment]
In your config at the bottom you probably have cropping set to True for analysis.

**Comment by tom221085** [comment]
That definitely helped, Thank you!
Do I have to retrain again now?

**Comment by KonradDanielewski** [comment]
No, this cropping is applied during analysis and evaluation. You can just reanalyze your videos.

**Comment by tom221085** [comment]
Thank you! That helped!
