### ISSUE TITLE
Napari Crashes on Startup During Label_Frames

### ISSUE THREAD

**Issue by klgrove** [DeepLabCut/DeepLabCut#2453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I'm trying to train a new network. I got the program to extract the frames, but when I input the label frames command, it brings up Napari then freezes and crashes. It does not return an error in the iPython terminal, just exits iPython. 

### Operating System

Windows 10 Enterprise

### DeepLabCut version

2.3.8

### DeepLabCut mode

multi animal

### Device type

GPU 0- Intel (r) UHD Graphics
GPU 1- AMD Radeon RX 6500

### Steps To Reproduce

conda activate tfdml_plugin
import deeplabcut
config_path = r"C:\Users\klgrove\Desktop\LatToeSpread-Kristi-2023-11-17\config.yaml"
deeplabcut.label_frames(config_path)

### Relevant log output

```shell
(tfdml_plugin) PS C:\WINDOWS\system32> ipython
Python 3.9.18 (main, Sep 11 2023, 14:09:26) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.17.2 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import deeplabcut
2023-11-21 14:44:16.519200: I tensorflow/c/logging.cc:34] Successfully opened dynamic library C:\Users\klgrove\AppData\Local\anaconda3\envs\tfdml_plugin\lib\site-packages\tensorflow-plugins/directml/directml.d6f03b303ac3c4f2eeb8ca631688c9757b361310.dll
2023-11-21 14:44:16.520345: I tensorflow/c/logging.cc:34] Successfully opened dynamic library dxgi.dll
2023-11-21 14:44:16.525755: I tensorflow/c/logging.cc:34] Successfully opened dynamic library d3d12.dll
2023-11-21 14:44:17.907528: I tensorflow/c/logging.cc:34] DirectML device enumeration: found 2 compatible adapters.
Loading DLC 2.3.8...

In [2]: config_path = r"C:\Users\klgrove\Desktop\LatToeSpread-Kristi-2023-11-17\config.yaml"

In [3]: deeplabcut.label_frames(config_path)
Installed qt6 event loop hook.

In [4]:
(tfdml_plugin) PS C:\WINDOWS\system32>
```

### Anything else?

Napari loads but then won't do anything, then windows tells me it isn't responding, Napari and the ipython session both crash. Similar to issues #400 and #682 but I'm not getting any error at all, it just crashes. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by klgrove** [comment]
UPDATE: when I run the project in the deeplabcut GUI using python -m deeplabcut, it opens Napari and allows me to label the frames. It only crashes when I run it manually through anaconda using deeplabcut.label_frames(config.path). BUT the GUI won't extract the frames. I ask it to extract the frames from the new videos I added, and it says it did, but it didn't. The new video frames and associated folders only show up when I use the deeplabcut.extract_frames command, not when I use the GUI extract frames command. It appears I have to extract the frames using the manual commands, and then open the GUI to label them.

**Comment by KonradDanielewski** [comment]
Try running it from Anaconda Prompt, not Powershell. When running extraction from the GUI, is there any error printed in the terminal?

**Comment by aaroncherian** [comment]
Hi there - I'm having this same problem, was there a solution figured out for this? This is the script I'm running in VSCode:

![image](https://github.com/DeepLabCut/DeepLabCut/assets/17153275/6728b09a-5685-4ca4-b6b5-d191d28e369d)

The napari GUI briefly pops up, and then crashes. There's no error in the terminal:

![image](https://github.com/DeepLabCut/DeepLabCut/assets/17153275/f487dd7a-435e-432f-8c26-c2bf049b82a9)

This error happens for any command to bring up the napari GUI using headless commands (label frames, extract outlier frames with manual mode turned on, and refine labels). However, it works fine, as mentioned by the original poster, when launching the GUI using `python -m deeplabcut`.

**Comment by MMathisLab** [comment]
Strange! We will check again 👍

**Comment by rory-bedford** [comment]
Are there any updates on this? I've spent a good while trying to get label_frames to open from within a python script, that I'm calling elsewhere. I'm also getting this issue of the napari window opening and closing immediately. I'm sure it's something to do with QT event hooks, but can't figure it out.

**Comment by rojasgabriel** [comment]
also interested in knowing if this got fixed

**Comment by n-poulsen** [comment]
@rojasgabriel are you running the commands in a `conda prompt` or `powershell`?

**Comment by rojasgabriel** [comment]
@n-poulsen my case is a little different. I'm calling the function within a CLI running inside `bash`. here's what I had to do to make it work properly:

```
from deeplabcut.gui.widgets import launch_napari
import napari
launch_napari([labeled_data_folder, configpath])
napari.run()
```

i think the issue with just calling the `label_frames` function directly in my case is that it doesn't start an application loop and immediately exits out from the CLI instead of leaving the application open until I explicitly close it
