### ISSUE TITLE
fail in install of cpu version

### ISSUE THREAD

**Issue by yokosyw** [DeepLabCut/DeepLabCut#2458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Graphics card：intel(R) UHD Graphics 630
install process：
install Anaconda Navigator，update it；
download DeepLabCut-main zip from https://github.com/DeepLabCut/DeepLabCut.git    and Extract the files
cut and paste the  DeepLabCut-main in C disc；
open Anaconda Navigator
import `"C：\DeepLabCut-main\conda-environments\DEEPLABCUT.yaml”` as new enviroment
open with ipython under DEEPLABCUT
input the first command：`import deeplabcut`
it showed that：`ModuleNotFoundError: No module named 'deeplabcut'`
input the second Command： `deeplabcut.launch_dlc()`
it showed ：`NameError: name 'deeplabcut' is not defined`

so which step is wrong？

### Operating System

operating system

### DeepLabCut version

cpu version

### DeepLabCut mode

single animal

### Device type

DESKTOP-38VGD59
Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz   3.10 GHz
Graphics card：intel(R) UHD Graphics 630

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @yokosyw!

When you created the environment with the anaconda navigator, were any errors printed? And which commands exaclty did you run to start `ipython` with the `DEEPLABCUT`environment?

**Comment by yokosyw** [comment]
> Hi @yokosyw!
> 
> When you created the environment with the anaconda navigator, were any errors printed? And which commands exaclty did you run to start `ipython` with the `DEEPLABCUT`environment?

created with deeplabcut environment generate 248 package under the enviroment and I use “open with ipython”
then "import deeplabcut"

**Comment by MMathisLab** [comment]
I would suggest following our guide, which is different than what you describe.  Please see: https://deeplabcut.github.io/DeepLabCut/docs/installation.html
