### ISSUE TITLE
Allowing multiple cropping coords for analysis

### ISSUE THREAD

**Issue by DonnieKim411** [DeepLabCut/DeepLabCut#246]
**Your Operating system and DeepLabCut version**
Linux 18.04 with 2.0.5. with Docker image

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

**Is your feature request related to a problem? Please describe.**

Instead of using for only 1 cropping coords universally when feeding in multiple videos, I would like to have different cropping coords just like under `crop`

**Describe the solution you'd like**

Since we already have a functionality that allows user to determine the cropping area when obtaining frames, we can use that particular function to crop the coords of videos to be inferred. Then the videos to be inferred are listed under cropping with coords to be cropped as the following fashion:

videos_to_be_inferred:
    /path/to/video_to_be_inferred1:
    cropping: True
    cropping_coords: 100,200,300,400
    /path/to/video_to_be_inferred2:
    cropping: False
    cropping_coords: 0,400,0,500 (or None if preferred) 

**Describe alternatives you've considered**

If `config.yaml` becomes too cluttered due to a long list of videos to be inferred, we can generate a separate yaml file like `inferring_config.yaml`  and use the same logic as above?

**Additional context**

None

**Comment by AmandineCornil** [comment]
Dear all,
I will be happy with this enhancement too ! For the moment, I plan to use a loop with the deeplabcut.analyze_videos() function and an update of the config.yaml for each video but it's  maybe not the faster way to do.
Thanks :-)

**Comment by AlexEMG** [comment]
@AmandineCornil's solution is fine, although perhaps annoying as one needs to read & write to config file for each video. 

I just changed DLC so one can also crop by passing it directly to analyze_video:
```deeplabcut.analyze_videos(path_config_file,[video],cropping=[0,50,0,50])```

Notice if nothing is passed, then the information is read from the config.yaml file as previously.

Hope that is useful? Now released: Version released: https://pypi.org/project/deeplabcut/2.0.6.3/

**Comment by AmandineCornil** [comment]
@AlexEMG yes it's better than read/write the config.yaml, thanks :-)
In the future, a GUI (like the one used for manual labeling) where it's possible to load the first frame of a movie and then to crop it (with automatic update of the config.yaml) will be a perfect solution ;-)
Thanks guys !
