### ISSUE TITLE
Allow not refining all outlier frames

### ISSUE THREAD

**Issue by roaldarbol** [DeepLabCut/DeepLabCut#2460]
**Is your feature request related to a problem? Please describe.**
I have been refining frames in a multi-animal project with a large number of animals and bodyparts in each frame. However, in this case "Extract frames" extracted roughly 40 frames which takes a loooong time to re-label. Currently, you can't label only some of them as you get the following error when trying to merge:

https://github.com/DeepLabCut/DeepLabCut/blob/0f657cde513dad207c68e9bb16eab8d5c351fde5/deeplabcut/refine_training_dataset/outlier_frames.py#L1147-L1148

**Describe the solution you'd like**
I see a few potential ways to get around this. 
1. When merging, only choose the frames that have manually been re-labelled. (Basically, instead of checking whether all frames have been re-labelled, check if _any_ have been, and then merge those.
2. Allow users to delete frames within the napari GUI (I'm not super familiar with the napari possibilities, but I'd assume it can be done).

**Describe alternatives you've considered**
Labelling all frames, but that is eating away a full day of work. Or manually choosing which frames - but I also want the goodies of an algorithm telling me which frames needs refinement the most. :-)

**Additional context**
As an aside, this is a silent error as it show up in the bottom bar without alerting the user that nothing was merged - maybe a pop-up would be better. Not a biggie though.

**Comment by MMathisLab** [comment]
Hi @roaldarbol you can set the # of frames to relabel by just changing the # in the config.yaml file. You can also extract them, then delete ones that are redundant to you before you open the folder in napari! We don't want to merge only the edited ones and people might accidentally not save, or something else, and then not realize they are merging too few frames... so we leave this up to user to check the folders first! Hope that explains the changes you can make and our rationale :)

**Comment by roaldarbol** [comment]
Hi @MMathisLab! Thanks for the quick response.
I get your point about not merging - I think that does make sense.

I can't find the place in the config.yaml where I could set this - I can find `numframes2pick`, but that seems to only affect initial frame extraction, not extraction for refinement (at least from the GUI). In my case it was set to 20, but for refinement I had 39 extracted. After a bit of digging, it seems it should indeed use `numframes2pick`.
https://github.com/DeepLabCut/DeepLabCut/blob/0f657cde513dad207c68e9bb16eab8d5c351fde5/deeplabcut/refine_training_dataset/outlier_frames.py#L685-L701
I tried to figure out if there's a bug preventing it from using `numframes2pick`, both from the GUI functions, the normal extract_frames function and the various functions in refine_labels, but couldn't find anything obvious. 

(As an aside, maybe the `config.yaml` should have a page of its own in the docs? Ref #2421)

But it sounds like this is mostly a UI/UX feature request, as the functionality should be in place. I think it would make sense to be able to set the number of frames to extract from the GUI directly - and worth considering whether there should be a parameter in config.yaml specifically for refinement extractions?

(Just to check on my personal case, is there nothing to do but label the remaining half or start over if I have already started re-labelling?)

**Comment by jeylau** [comment]
Hi @roaldarbol, I checked the code, and `numframes2pick` is passed to `KmeansbasedFrameselectioncv2` https://github.com/DeepLabCut/DeepLabCut/blob/0f657cde513dad207c68e9bb16eab8d5c351fde5/deeplabcut/refine_training_dataset/outlier_frames.py#L759C58-L767, so I am confused about what may have caused more frames to be extracted than defined in the config.
Was `Do you want to proceed with extracting 20 of those?` printed in the terminal when you ran the command? A list of 20 indices should also have been shown after `Let's select frames indices:, [...]`. Is that correct?

**Comment by roaldarbol** [comment]
Hi @jeylau! I can check later in the week - I was using the GUI, but something may have have appeared in the terminal; however, it must have continued without taking needing me to confirm anything in the terminal.
