### ISSUE TITLE
Updated docs/Overviewof3D.md ?

### ISSUE THREAD

**Issue by bainro** [DeepLabCut/DeepLabCut#2462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello, I am trying to make DLC-3D work, but the configuration file seems to have changed in the 1.5 years that the documentation was last updated. Are there other, more updated resources for setting up a 3D project? Especially interested in using the superanimal models, instead of having to train my own from scratch. Cheers!

### Operating System

Windows

### DeepLabCut version

2.3.7

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

https://github.com/DeepLabCut/DeepLabCut/blob/main/docs/Overviewof3D.md

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
hi @bainro the 3D docs are still relevant :) and we have not worked in SuperAnimal models to this. That being said, we do expect some nice new additions to the 3D code in 2024, so stay tuned!
