### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by LingZHouXin** [DeepLabCut/DeepLabCut#2469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

by using the DEEPLABCUT GUI ， I tried to use the SuperAnimal-TopViewMouse analysis.  It gives me an Index error. 

### Operating System

win11

### DeepLabCut version

DLC 2.3.8

### DeepLabCut mode

single animal

### Device type

 i9-13900kf
 rtx4090

### Steps To Reproduce

in the Conda Environment
run GUI by using: “ python -m deeplabcut"
in GUI, attempt to run Model Zoo
Add mp4 video
Click Run

### Relevant log output

```shell
(DLC) PS D:\model\DeepLabCut-main> python -m deeplabcut
Loading DLC 2.3.8...
Starting GUI...
Traceback (most recent call last):
  File "D:\model\DeepLabCut-main\deeplabcut\gui\utils.py", line 22, in run
    self.func()
  File "D:\model\DeepLabCut-main\deeplabcut\pose_estimation_tensorflow\predict_supermodel.py", line 98, in video_inference_superanimal
    adapter.before_adapt_inference(
  File "D:\model\DeepLabCut-main\deeplabcut\modelzoo\api\spatiotemporal_adapt.py", line 114, in before_adapt_inference
    self.init_weights, datafiles = superanimal_inference.video_inference(
  File "D:\model\DeepLabCut-main\deeplabcut\modelzoo\api\superanimal_inference.py", line 314, in video_inference
    init_weights = os.path.abspath(snapshots[0]).replace(".index", "")
IndexError: list index out of range
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
HI @LingZHouXin you just happen to catch us at a bad time 🤩 - we were updating the model weights yesterday! Can you try again after running `pip install --upgrade dlclibrary` in your conda env then re-launching the GUI? 

cc @jeylau

**Comment by LingZHouXin** [comment]
appreciate for your assistance @jeylau @MMathisLab.

 I've tried to re-launching the GUI , but there hasn't been any improvement.
```python
(DLC) PS D:\model\DeepLabCut-main> pip install --upgrade dlclibrary
Requirement already satisfied: dlclibrary in d:\anaconda3\envs\dlc\lib\site-packages (0.0.5)
Requirement already satisfied: huggingface-hub in d:\anaconda3\envs\dlc\lib\site-packages (from dlclibrary) (0.19.4)
Requirement already satisfied: ruamel.yaml>=0.15.0 in d:\anaconda3\envs\dlc\lib\site-packages (from dlclibrary) (0.18.5)
Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in d:\anaconda3\envs\dlc\lib\site-packages (from ruamel.yaml>=0.15.0->dlclibrary) (0.2.8)
Requirement already satisfied: filelock in d:\anaconda3\envs\dlc\lib\site-packages (from huggingface-hub->dlclibrary) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in d:\anaconda3\envs\dlc\lib\site-packages (from huggingface-hub->dlclibrary) (2023.12.2)
Requirement already satisfied: requests in d:\anaconda3\envs\dlc\lib\site-packages (from huggingface-hub->dlclibrary) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in d:\anaconda3\envs\dlc\lib\site-packages (from huggingface-hub->dlclibrary) (4.66.1)
Requirement already satisfied: pyyaml>=5.1 in d:\anaconda3\envs\dlc\lib\site-packages (from huggingface-hub->dlclibrary) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in d:\anaconda3\envs\dlc\lib\site-packages (from huggingface-hub->dlclibrary) (4.9.0)
Requirement already satisfied: packaging>=20.9 in d:\anaconda3\envs\dlc\lib\site-packages (from huggingface-hub->dlclibrary) (23.2)
Requirement already satisfied: colorama in d:\anaconda3\envs\dlc\lib\site-packages (from tqdm>=4.42.1->huggingface-hub->dlclibrary) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\anaconda3\envs\dlc\lib\site-packages (from requests->huggingface-hub->dlclibrary) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda3\envs\dlc\lib\site-packages (from requests->huggingface-hub->dlclibrary) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda3\envs\dlc\lib\site-packages (from requests->huggingface-hub->dlclibrary) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda3\envs\dlc\lib\site-packages (from requests->huggingface-hub->dlclibrary) (2023.11.17)
(DLC) PS D:\model\DeepLabCut-main> python -m deeplabcut
Loading DLC 2.3.8...
Starting GUI...
Traceback (most recent call last):
  File "D:\model\DeepLabCut-main\deeplabcut\gui\utils.py", line 22, in run
    self.func()
  File "D:\model\DeepLabCut-main\deeplabcut\pose_estimation_tensorflow\predict_supermodel.py", line 102, in video_inference_superanimal
    adapter.before_adapt_inference(make_video=False)
  File "D:\model\DeepLabCut-main\deeplabcut\modelzoo\api\spatiotemporal_adapt.py", line 114, in before_adapt_inference
    self.init_weights, datafiles = superanimal_inference.video_inference(
  File "D:\model\DeepLabCut-main\deeplabcut\modelzoo\api\superanimal_inference.py", line 314, in video_inference
    init_weights = os.path.abspath(snapshots[0]).replace(".index", "")
IndexError: list index out of range
```

Wishing smooth updates to your model weights!

**Comment by MMathisLab** [comment]
just to confirm, you updated the packages?

**Comment by MMathisLab** [comment]
okay great, thanks and sorry for the trouble! @jeylau can you check -- cc @AlexEMG!

**Comment by bainro** [comment]
I fixed it by unzipping, renaming, and moving the downloaded weights file. This is also affecting the colab superanimal notebook.

**Comment by LingZHouXin** [comment]
@bainro Could you please share the specific steps for the operation? thanks

**Comment by LingZHouXin** [comment]
ok，as said by @bainro clearing the weights folder 
#2193 @yeshaokai 'Your_DLC_ROOT/deeplabcut/pose_estimation_tensorflow/models/pretrained/superanimal_name_weights/'
and reloading. the bug have solved

and I have just reinstalling different version of Torch(torch1.12.0+cu116)
I'm able to use GPU to run the video.

**Comment by MiceOnDrugs** [comment]
@LingZHouXin Hello! Could you explain what you mean by clearing the weights folder and reloading (I'm very new to DLC and python)? I've been encountering the same issue while trying to use the SuperAnimal-TopViewMouse. I tried removing the files from the weights folder "superanimal_topviewmouse_weights". Thank you!

**Comment by bainro** [comment]
I don't think this should be closed. You have to manually unzip, rename, and move the weights folders. That was the first solution I found. But the true culprit seems to be this yaml file with commit names in it, which seem to be incorrect, so the tarfiles are never properly updated when downloading the weights the first time. I edited the commit line for the superanimal model I wanted to use and everything worked well. Everytime I have fixed this (1 linux, 1 windows, and 1 google colab running linux), it has been caused by that final commit folder not being found even though there was one downloaded. It was just named wrong, hence why the original solution I mentioned earlier worked. Hope that helps!

**Comment by MiceOnDrugs** [comment]
@bainro Thank you! Would you mind specifying which yaml file this is? None of my weights folders were ever zipped, so I don't know what's going on there.

**Comment by MMathisLab** [comment]
agree, we will reopen!

**Comment by Rastamous3** [comment]
Hello, I initially resolved this issue by unpacking, renaming, etc. as detailed in #2480. I am now experiencing the same issue as #2224 - index errors when running deeplabcut.create_pretrained_project and requesting a superanimal model. I believe these issues are related but am no expert. Any further suggestions? shall I wait for #2485 PR approval?
