### ISSUE TITLE
Which camera do I use when filming

### ISSUE THREAD

**Issue by ssdebbi** [DeepLabCut/DeepLabCut#247]
**Your Operating system and DeepLabCut version**
 Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

**Describe the problem**
I am about to embark on a new project using DeepLab cuts to video tape the behavior of infants in real time. Which camera is recommended for color images. Does anyone have any experience with this? or recommendations?

**Comment by AlexEMG** [comment]
There is a section in here: https://www.biorxiv.org/content/early/2018/11/24/476531.full.pdf

**Comment by Niinamk** [comment]
Hi ssdebbi - I wonder where have you gotten to with this...? We are thinking about doing this too, and would be great to learn more from what you have done.
