### ISSUE TITLE
IndexError: index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by klgrove** [DeepLabCut/DeepLabCut#2470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I had a working program. I added new videos to it, extracted outlier frames, corrected labels, retrained the network, and merged the data. Now every time I try to analyze a video, I get this error: 

IndexError: index -1 is out of bounds for axis 0 with size 0

I tried changing the snapshot index to 'all' but it returned the same error. 

### Operating System

Windows 10 Enterprise

### DeepLabCut version

dlc version 2.3.8

### DeepLabCut mode

multi animal

### Device type

Intel (R) UHD Graphics 770
AMD Radeon RX 6500

### Steps To Reproduce

conda activate tfdml_plugin
ipython
import deeplabcut
config_path=r"C:\Users\klgrove\Desktop\LatToeSpread-Kristi-2023-11-17\config.yaml"
deeplabcut.analyze_videos(config_path,[r"C:\Users\klgrove\Desktop\LatToeSpread-Kristi-2023-11-17\videos\30 Sec Vid Run 7.mp4"],videotype='.mp4', auto_track=True)

### Relevant log output

```shell
deeplabcut.analyze_videos(config_path,[r"C:\Users\klgrove\Desktop\LatToeSpread-Kristi-2023-11-17\videos\30 Sec Vid Run 7.mp4"],videotype='.mp4', auto_track=True)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[5], line 1
----> 1 deeplabcut.analyze_videos(config_path,[r"C:\Users\klgrove\Desktop\LatToeSpread-Kristi-2023-11-17\videos\30 Sec Vid Run 7.mp4"],videotype='.mp4', auto_track=True)

File ~\AppData\Local\anaconda3\envs\tfdml_plugin\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py:542, in analyze_videos(config, videos, videotype, shuffle, trainingsetindex, gputouse, save_as_csv, in_random_order, destfolder, batchsize, cropping, TFGPUinference, dynamic, modelprefix, robust_nframes, allow_growth, use_shelve, auto_track, n_tracks, calibrate, identity_only, use_openvino)
    539 increasing_indices = np.argsort([int(m.split("-")[1]) for m in Snapshots])
    540 Snapshots = Snapshots[increasing_indices]
--> 542 print("Using %s" % Snapshots[snapshotindex], "for model", modelfolder)
    544 ##################################################
    545 # Load and setup CNN part detector
    546 ##################################################
    547
    548 # Check if data already was generated:
    549 dlc_cfg["init_weights"] = os.path.join(
    550     modelfolder, "train", Snapshots[snapshotindex]
    551 )

IndexError: index -1 is out of bounds for axis 0 with size 0
```

### Anything else?

I first encountered this error in the GUI, but thought maybe I could fix it by running the code manually. I was wrong. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by klgrove** [comment]
I think I may have misunderstood the order in which to train/merge to refine the network. I retrained the network after merging, following the order from #989, and my program is working again. Thank you all so much for your continued support!!!

**Comment by josh-oloro** [comment]
I am getting the same error when trying to analyze new videos with previously trained weights.
