### ISSUE TITLE
Model Zoo: IndexError: list index out of range

### ISSUE THREAD

**Issue by Rastamous3** [DeepLabCut/DeepLabCut#2480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi there,

I am trying to analyse a short video with the Model Zoo superanimal_topviewmouse supermodel but am met with the following error. I am aware this issue has been detailed in previous posts, although these have been marked "Closed" despite multiple users expressing dissatisfaction with the nature of the solutions offered. The proposed solutions also lack clarity in their methods challenging novice python/DeepLabCut users such as myself, hence why I am making a new post. 

Should I manually unzip, rename, and move the weights folders as suggested in #2193? 

Other posts (#2469) suggest I edit the commit line for the superanimal_topviewmouse supermodel, although i'm unsure exactly how to do this.

Or should I wait for the huggingface_hub.file_download to be updated with this bug fixed? or attempt to edit it myself?

Any clarification / guidance on how to achieve a robust solution would be greatly appreciated.

Excuse my noobness, thank you all for your efforts! :) 

@AlexEMG @Bainro @yeshaokai @MMathisLab 

### Operating System

Windows 11

### DeepLabCut version

 DLC 2.3.8

### DeepLabCut mode

single animal

### Device type

RTX080 GPU

### Steps To Reproduce

1. Launch DeepLabCut CONDA Env
2. Launch GUI
3. Model Zoo
4. Add video 
5. Run

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\wendy\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\utils.py", line 22, in run
    self.func()
  File "C:\Users\wendy\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_supermodel.py", line 102, in video_inference_superanimal
    adapter.before_adapt_inference(make_video=False)
  File "C:\Users\wendy\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\modelzoo\api\spatiotemporal_adapt.py", line 114, in before_adapt_inference
    self.init_weights, datafiles = superanimal_inference.video_inference(
  File "C:\Users\wendy\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\modelzoo\api\superanimal_inference.py", line 314, in video_inference
    init_weights = os.path.abspath(snapshots[0]).replace(".index", "")
IndexError: list index out of range
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by bainro** [comment]
The short term hack is unpacking, renaming, etc. Ideally the dlclibrary
gets a PR to fix...

**Comment by MMathisLab** [comment]
Hi both, this is something that only seems to affect Windows users, and we cannot reproduce it, so hard to propose a real fix -- but if you have suggestions, please do make a PR!

**Comment by bainro** [comment]
It looks like the update to dlclibrary 3 wks ago might have fixed it. I had
it on 3 linux machines and 1 windows. 1 of the linux machines was google
colab, but I just tried it and it worked.

-Rob

**Comment by yeshaokai** [comment]
@bainro Thanks for the confirmation! 

@Rastamous3 Can you give a try by upgrading the dlclibrary?
