### ISSUE TITLE
deeplabcut.create_training_dataset superanimal_name issue

### ISSUE THREAD

**Issue by stef1029** [DeepLabCut/DeepLabCut#2481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am trying to replicate the transfer learning step mentioned in [this example page](https://deeplabcut.github.io/DeepLabCut/docs/ModelZoo.html). When my code runs, however, I receive the error `TypeError: create_training_dataset() got an unexpected keyword argument 'superanimal_name'`.

### Operating System

Windows 11

### DeepLabCut version

dlc version 2.3.6

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

Deeplabcut installed in conda environment, python 3.7.13, running on linux machine.
The code I am running is as follows:
```python
config = r'/cephfs2/srogers/New analysis pipeline/training_videos/DLC_Project_231212_193535_wtjx285-2a_raw_MP-SRC-2024-01-09/config.yaml'

import deeplabcut
import os

superanimal_name = "superanimal_topviewmouse"


# Create Training dataset
print("Creating Training Dataset")
deeplabcut.create_training_dataset(config,  
                                   net_type='resnet_50', 
                                   augmenter_type='imgaug', 
                                   windows2linux = True,
                                   superanimal_name = superanimal_name)
print("Training Dataset created")


# train
print("Training network")
deeplabcut.train_network(config, 
                         gputouse=os.environ.get("CUDA_VISIBLE_DEVICES"), 
                         maxiters=800000,
                         superanimal_name = superanimal_name,
                         superanimal_transfer_learning = True)
print("Network Trained")
```

### Relevant log output

```shell
Loading DLC 2.3.6...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Creating Training Dataset
Traceback (most recent call last):
  File "deeplabcut_training.py", line 16, in <module>
    superanimal_name = superanimal_name)
TypeError: create_training_dataset() got an unexpected keyword argument 'superanimal_name'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
hi @stef1029 can you update to 2.3.8 ?

**Comment by yeshaokai** [comment]
Transfer learning is introduced in 2.3.8. Let me know if upgrading solves it.

**Comment by stef1029** [comment]
Thanks very much, that seems to have fixed that issue. I believe it was because my environment was set to have python 3.7 so the newest deeplabcut version hadn't installed.
