### ISSUE TITLE
pose_cfg.yaml not created/found when creating HRNet pretrained project

### ISSUE THREAD

**Issue by Rastamous3** [DeepLabCut/DeepLabCut#2488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

[Edit] I am now under the impression that HRNet-w32 architecture is only compatible for DLC3.0+ Pytorch code which is yet be released.

Hello,

I am trying to create a pretrained project with the (HRNet-W32) superanimal_topviewmouse_hrnetw32 model but the pose_cfg.yaml is not created/found. I am able to create a pretrained project with the ResNet-50 Model (superanimal_topviewmouse_dlcrnet) without any errors. I thought I would opt for HRNet-W32 Model for better handling of complex poses and fine movements, is there a way to fix this error? or should I stick with the ResNet-50 Model?

Thank you again for all your efforts DLC team and contributors!

### Operating System

Windows 11

### DeepLabCut version

DLC 2.3.8

### DeepLabCut mode

single animal

### Device type

RTX4080 GPU

### Steps To Reproduce

deeplabcut.create_pretrained_project(
    "projectname",
    "experimenter",
    [r"path_for_the_videos"],
    model= "superanimal_topviewmouse_hrnetw32",
    working_directory= r"project_directory",
    copy_videos= True,
    videotype= ".mp4",
    analyzevideo= True,
    filtered= True,
    createlabeledvideo= True,
    trainFraction= None
)

### Relevant log output

```shell
FileNotFoundError: Config C:\Users\user\project file\dlc-models\iteration-0\SuperAnimal Model Trained HRNETJan18-trainset95shuffle1\train\pose_cfg.yaml is not found. Please make sure that the file exists.
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by juneleung** [comment]
same issue I faced.
I want to run with pytorch supermodel `superanimal_quadruped_hrnetw32`, pose_cfg.yaml not be downloaded when I run with `deeplabcut.create_pretrained_project`, error with:
`train/pose_cfg.yaml is not found. Please make sure that the file exists.`. 

Have you solved this issue? Thanks!
