### ISSUE TITLE
GUI Issue: Editing the config.yaml file

### ISSUE THREAD

**Issue by Timokleia** [DeepLabCut/DeepLabCut#2489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Encountered an issue in the DeepLabCut **GUI** where adding additional connections to the skeleton is not functioning as expected.

Also you cannot delete entries in the skeleton. 

### Operating System

operating system: macOS Monterey version 12.5 - chip Apple M1

### DeepLabCut version

dlc version: 2.3.8

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

Opened DeepLabCut GUI and loaded a project.
Click on editing the config.yaml file and then navigate to skeleton connections.
Attempted to add new connections to the skeleton by control and right-clicking and selecting 'insert new connection'.

The action only generates a single parameter input as in body part section, without offering a dropdown list where the user can input two bodyparts. 

<img width="706" alt="Screenshot 2024-01-18 at 11 38 40" src="https://github.com/DeepLabCut/DeepLabCut/assets/86098649/ca5eeee2-35c5-43b4-b140-489dc5f48a44">
<img width="340" alt="Screenshot 2024-01-18 at 11 39 01" src="https://github.com/DeepLabCut/DeepLabCut/assets/86098649/092aaf19-7252-4b3b-8106-3cc835bbd8fa">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
bump please

**Comment by meriem-hcini** [comment]
Hello, was this ever resolved or is there a work around? Currently running into this issue as well.
