### ISSUE TITLE
gputouse issue in deeplabcut.analyse_videos()

### ISSUE THREAD

**Issue by stef1029** [DeepLabCut/DeepLabCut#2490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When running the following function and parameters, I receive the following error. 
```python

deeplabcut.analyze_videos(config = config,
                          videos = [VideoDir], 
                          videotype='.avi', 
                          save_as_csv=True, 
                          gputouse=os.environ.get("CUDA_VISIBLE_DEVICES"))
```

error:
```
Traceback (most recent call last):
  File "deeplabcut_analyse.py", line 28, in <module>
    deeplabcut.analyze_videos(config = config,
  File "/lmb/home/srogers/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py", line 484, in analyze_videos
    auxfun_models.set_visible_devices(gputouse)
  File "/lmb/home/srogers/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/deeplabcut/utils/auxfun_models.py", line 164, in set_visible_devices
    if gputouse >= n_devices:
TypeError: '>=' not supported between instances of 'str' and 'int'
```

I have tried printing the result of os.environ.get("CUDA_VISIBLE_DEVICES") and receive a result that looks like indices of the gpus available, and it is responsive to me changing the number of gpus available. 
I have also tried downgrading deeplabcut to 2.3.7 and 2.3.6 to see if it was a recent issue, but still get the same issue.

### Operating System

Windows 11

### DeepLabCut version

2.3.8

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

With deeplabcut 2.3.8, python 3.8.16

```python
import deeplabcut
import os

config = r'~/project/config.yaml'
VideoDir = os.path.join(os.path.split(config)[0], "videos")

# Train new videos (Check if previous training already has coordinates)
deeplabcut.analyze_videos(config = config,
                          videos = [VideoDir], 
                          videotype='.avi', 
                          save_as_csv=True, 
                          gputouse=os.environ.get("CUDA_VISIBLE_DEVICES"))
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @stef1029, `gputouse` is expecting an integer; please try with `gputouse=int(os.environ.get("CUDA_VISIBLE_DEVICES"), "0")`. I hope that helps!

**Comment by stef1029** [comment]
Hi @jeylau , thanks for the response. I think the issue is that I've been offering the function a list of gpu's that are available to it assuming it would split the work across them. Does the function make use of multiple gpu's at all or is one its maximum? It does work with that advice with one gpu available though so can continue, but wonder if it could be made faster?

**Comment by KonradDanielewski** [comment]
@stef1029 you can run it in a way where each GPU analyzes a different video. I haven't tried doing it this way, but maybe you can check out this [stackoverflow post](https://stackoverflow.com/questions/53422761/distributing-jobs-evenly-across-multiple-gpus-with-multiprocessing-pool)

**Comment by stef1029** [comment]
@KonradDanielewski Thanks for the advice, that makes sense, I'll try that out.
