### ISSUE TITLE
Changing Unique Body Parts After Start of Labeling

### ISSUE THREAD

**Issue by tom221085** [DeepLabCut/DeepLabCut#2501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I started labeling and training but then decided to change and add the unique body parts. Unfortunately, it doesn't change it in my already labeled data. Is there a solution for this?
I found a closed issue about this (#2125) but it seems there hasn't been a solution for it yet.

Thanks,
Thomas

### Operating System

Windows 10

### DeepLabCut version

dlc version 2.3.8

### DeepLabCut mode

multi animal

### Device type

NVIDIA GeForce RTX 3090

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by KonradDanielewski** [comment]
After loading the data you want to label, you can drag&drop the config. This should update the bodyparts

**Comment by tom221085** [comment]
Thank you! Where do I drag&drop the config to?

**Comment by KonradDanielewski** [comment]
Onto the canvas of napari. On Windows drag&drop doesn't work if the terminal was run as administrator (it's a Windows issue that pertains to all software run on Windows - you can't drag&drop onto a window that has administrative privileges)

**Comment by tom221085** [comment]
Alright, that seems to work now. Thank you!
