### ISSUE TITLE
Superanimal inference stuck on "Create device"

### ISSUE THREAD

**Issue by hummuscience** [DeepLabCut/DeepLabCut#2503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Running superanimal inference (mouse) on a video using two different conda environments and GPUs leads to the process initiating (Device created etc.) but then keeps looking over this part. 

Testscript_cli.py runs without an error. Inference and training of normal DLC models run without issues.

### Operating System

RHEL 8

### DeepLabCut version

DLC Version = 2.3.8 (also tried from inside  freshly pulled git repo)
DLClibrary = `pip install -e . `inside from pulled git repo

### DeepLabCut mode

single animal

### Device type

gpu

### Relevant log output

![Screenshot 2024-01-30 at 17 45 19](https://github.com/DeepLabCut/DeepLabCut/assets/4943380/cd0ae44b-4944-4d35-80ae-7f913cc87530)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by hummuscience** [comment]
Funnily, when setting up a new project with create_pretrained_project, the inference with superanimal_topviewmouse suddenly works.

Edit: I think I know what's happening. This bug is only affecting `video_inference_superanimal` as this function is not called when one creates a pretrained project.

**Comment by yeshaokai** [comment]
@hummuscience 
Hi! Thanks for using SuperAnimal models. I want to clarify that create_pretrained_project is meant for user-contributed models and SuperAnimal models are separated from them. In the design, Inferencing SuperAnimal models does not require to do create_pretrained_project.

You can also do transfer learning and fine-tuning with SuperAnimal models. More details are https://github.com/DeepLabCut/DeepLabCut/blob/main/docs/ModelZoo.md
