### ISSUE TITLE
Failed to Install DLC GUI

### ISSUE THREAD

**Issue by TttRANN** [DeepLabCut/DeepLabCut#2511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I failed to install the GUI, but i was able to install the light version. i tried to downgrade python to 3.8 but it did not help. I used the conda env create -f DEEPLABCUT_M1.yaml command to set up dependencies.

### Operating System

operating system MACOS SONOMA 14.2.1 (23C71)

### DeepLabCut version

dlc version 2.2.3

### DeepLabCut mode

single animal

### Device type

cpu M1 Pro

### Relevant log output

```shell
Finished command: build_py (3m30.939s)
      Finished command: build (7m41.531s)
      Command '"/Users/miniconda3/envs/DEEPLABCUT_M1/bin/python3.9" -u build.py build' failed with exit code 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wxpython
  Running setup.py clean for wxpython
Failed to build wxpython
ERROR: Could not build wheels for wxpython, which is required to install pyproject.toml-based projects
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @TttRANN, `wxpython` is no longer used in DeepLabCut, and python 3.8 is no longer supported with DeepLabCut. I would make sure you have up-to-date code.

Could you try installing DeepLabCut using `pip` with one of the following commands (these are specific to install DeepLabCut on macOS)? I think option 1 is by far the easiest and best way to do this.

Let me know if this hasn't fixed yout installation issue.

## Option 1

Directly using the [DEEPLABCUT_M1.yaml](https://github.com/DeepLabCut/DeepLabCut/blob/main/conda-environments/DEEPLABCUT_M1.yaml) file:

```bash
conda env create -f DEEPLABCUT_M1.yaml
conda activate DEEPLABCUT_M1
python -m deeplabcut
```

If you get an error message saying `CondaValueError: prefix already exists: /Users/.../miniconda/envs/DEEPLABCUT_M1`, then the environement was already created once and you need to "delete" it to create a new one:
```bash
conda remove -n DEEPLABCUT_M1 --all
```

## Option 2

Manually create the environment and install the packages:
```bash
conda create -n DEEPLABCUT_M1 python=3.10
conda activate DEEPLABCUT_M1
conda install -c conda-forge "notebook<7.0.0" nb_conda jupyter ipython ffmpeg pytables
pip install "deeplabcut[gui,apple_mchips]"
```
