### ISSUE TITLE
No prediction plots when evaluating network

### ISSUE THREAD

**Issue by tom221085** [DeepLabCut/DeepLabCut#2515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I trained my network and when I try to evaluate it creates the folder for the prediction but the folder is empty without plots. It plots the test maps. This issue occurred recently after retraining and copying the videos into the video folder. Before that I never had problems.

Is there a way to solve this?

Thank you,
Thomas

### Operating System

Windows 10

### DeepLabCut version

2.3.8

### DeepLabCut mode

multi animal

### Device type

NVIDIA GeForce RTX 3090

### Relevant log output

```shell
(deeplabcut) C:\WINDOWS\system32>python -m deeplabcut
Loading DLC 2.3.8...
Starting GUI...
267it [00:00, 775.36it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 253/253 [00:00<00:00, 1419.02it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 1578.08it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 267/267 [00:00<00:00, 2798.03it/s]
267it [00:00, 634.57it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 253/253 [00:00<00:00, 1425.99it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 2300.05it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 267/267 [00:00<00:00, 2768.96it/s]
267it [00:00, 521.99it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 253/253 [00:00<00:00, 1378.95it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 1325.99it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 267/267 [00:00<00:00, 2743.60it/s]
267it [00:00, 291.48it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 253/253 [00:00<00:00, 1445.03it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 2342.25it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 267/267 [00:00<00:00, 2792.99it/s]
267it [00:00, 392.51it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 253/253 [00:00<00:00, 1473.19it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 1263.62it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 267/267 [00:00<00:00, 2870.27it/s]
267it [00:00, 342.25it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 253/253 [00:00<00:00, 1416.76it/s]
100%|█████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 968.49it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 267/267 [00:00<00:00, 2660.04it/s]
267it [00:01, 213.11it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 253/253 [00:00<00:00, 1414.28it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 1290.07it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 267/267 [00:00<00:00, 2809.02it/s]
267it [00:00, 280.02it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 253/253 [00:00<00:00, 1419.47it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 1125.66it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 267/267 [00:00<00:00, 2805.76it/s]
267it [00:01, 176.18it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 253/253 [00:00<00:00, 1427.47it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 1378.28it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 267/267 [00:00<00:00, 2724.22it/s]
267it [00:01, 234.47it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 253/253 [00:00<00:00, 1452.46it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 1465.70it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 267/267 [00:00<00:00, 2825.44it/s]
C:\ProgramData\Anaconda3\envs\deeplabcut\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
3it [00:02,  1.49it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:39<00:00, 13.16s/it]
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by CherryMiya** [comment]
I encountered a similar problem. When I tried to label ten animals with two dots on each animal, the evaluation network did not respond, the analysis video got stuck, and the interface displayed incomplete errors. I don't know how to locate and solve this problem? If there is any progress, thank you for your help.

**Comment by n-poulsen** [comment]
Are you using the DeepLabCut GUI or Python CLI? And did you select `Plot predictions` (in the GUI) or call `evaluate_network` with `plotting=True` (in the CLI)?

**Comment by tom221085** [comment]
I am using the GUI and select Plot predictions. Apparently, this problem occurs when I trained the network with the same amount of training steps before. If I delete this first training then it plots everything. That said I found a solution but you need to delete the previous training results.

**Comment by n-poulsen** [comment]
Happy you found the issue!

Indeed, DeepLabCut does not expect you to train the same shuffle multiple times - so if evaluation results are already present for a given snapshot (identified by the shuffle + number of iterations), evaluation will not be run again and results will not be plot. As you said, the solution would be to remove the evaluation results.

Ideally instead of training the same shuffle a second time, you would create a new shuffle, modify the parameters as you wish, and train + evaluate using this new shuffle. This would also allow you to compare results between different training runs/parameters.

@CherryMiya does this solve your issue as well? If not, could you please share the errors that are displayed?

**Comment by tom221085** [comment]
Understood! Thank you!

**Comment by CherryMiya** [comment]
> Happy you found the issue!
> 
> Indeed, DeepLabCut does not expect you to train the same shuffle multiple times - so if evaluation results are already present for a given snapshot (identified by the shuffle + number of iterations), evaluation will not be run again and results will not be plot. As you said, the solution would be to remove the evaluation results.
> 
> Ideally instead of training the same shuffle a second time, you would create a new shuffle, modify the parameters as you wish, and train + evaluate using this new shuffle. This would also allow you to compare results between different training runs/parameters.
> 
> @CherryMiya does this solve your issue as well? If not, could you please share the errors that are displayed?
Yes, thanks very much. Then, I encountered a new problem and have raised a separate question with errors listed. Thank you for your attention.
