### ISSUE TITLE
 Tracklets are empty

### ISSUE THREAD

**Issue by CherryMiya** [DeepLabCut/DeepLabCut#2516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When I track animals, the training network proceeds normally, but when analyzing the video, it shows Tracklets are emptye empty

### Operating System

WIN11

### DeepLabCut version

dlc version
2.3.8

### DeepLabCut mode

multi animals

### Device type

NVIDIA GeForce RTX 4090

### Steps To Reproduce

1.  import deeplabcut
2. path_config_file
3. videofile_path 
4. deeplabcut.analyze_videos(path_config_file,videofile_path, videotype='.mp4', save_as_csv=True)
5. error

**Comment by CherryMiya** [comment]
<img width="603" alt="image" src="https://github.com/DeepLabCut/DeepLabCut/assets/69582732/63583689-69dc-4182-91dc-b1369002e19e">
<img width="583" alt="image" src="https://github.com/DeepLabCut/DeepLabCut/assets/69582732/69eb8359-41fb-4208-8cc0-f2ded670952b">
no H5 file create

**Comment by CherryMiya** [comment]
config.yaml
    # Project definitions (do not edit)
Task: tenfish
scorer: m1
date: Jan28
multianimalproject: true
identity: true

    # Project path (change when moving around)
project_path: C:/Users/Administrator/Desktop/fish

    # Annotation data set configuration (and individual video cropping parameters)
video_sets:
  C:\Users\31668\Desktop\tenfish-m1-2024-01-28\videos\WeChat_20240126221132_1.mp4:
    crop: 0, 400, 0, 400
individuals:
- individual1
- individual2
- individual3
- individual4
- individual5
- individual6
- individual7
- individual8
- individual9
- individual10
uniquebodyparts: []
multianimalbodyparts:
- bodypart1
- bodypart2
bodyparts: MULTI!

    # Fraction of video to start/stop when extracting frames for labeling/refinement
start: 0
stop: 1
numframes2pick: 20

    # Plotting configuration
skeleton: 
- bodypart1
- bodypart2
skeleton_color: black
pcutoff: 0.6
dotsize: 5
alphavalue: 0.7
colormap: rainbow

    # Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 0
default_net_type: dlcrnet_ms5
default_augmenter: multi-animal-imgaug
default_track_method: ellipse
snapshotindex: -1
batch_size: 1

    # Cropping Parameters (for analysis and outlier frame detection)
cropping: false
    #if cropping is true for analysis, then set the values here:
x1: 0
x2: 640
y1: 277
y2: 624

    # Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 50
- 50
move2corner: true

**Comment by CherryMiya** [comment]
<img width="454" alt="image" src="https://github.com/DeepLabCut/DeepLabCut/assets/69582732/8b92452f-00f7-4a36-bb94-78e99d7b5372">
our data

**Comment by n-poulsen** [comment]
Hi @CherryMiya! Usually the `Tracklets are empty` comes when a model isn't performing well enough, so no individuals can be tracked. In this case your evaluation results look really good, so I think your model is well trained.

Can you run `deeplabcut.create_video_with_all_detections(...)`, after having ran `analyze_videos(..., auto_track=False)` as described [here](https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#evaluate-the-trained-network), at the decision point:
> ATTENTION! Pose estimation and tracking should be thought of as separate steps. If you do not have good pose estimation evaluation metrics at this point, stop, check original labels, add more data, etc –> don’t move forward with this model. If you think you have a good model, please test the “raw” pose estimation performance on a video to validate performance:
```python
scorername = deeplabcut.analyze_videos(config_path,['/fullpath/project/videos/testVideo.mp4'], videotype='.mp4', auto_track=False)
deeplabcut.create_video_with_all_detections(config_path, ['/fullpath/project/videos/testVideo.mp4'], videotype='.mp4')
```

This is just to check how your model is performing (if most individuals get detected, etc.). If your model seems good, you can try working with tracking parameters (as described [here](https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#if-auto-track-false)).

**Comment by CherryMiya** [comment]
> Hi @CherryMiya! Usually the `Tracklets are empty` comes when a model isn't performing well enough, so no individuals can be tracked. In this case your evaluation results look really good, so I think your model is well trained.
> 
> Can you run `deeplabcut.create_video_with_all_detections(...)`, after having ran `analyze_videos(..., auto_track=False)` as described [here](https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#evaluate-the-trained-network), at the decision point:
> 
> > ATTENTION! Pose estimation and tracking should be thought of as separate steps. If you do not have good pose estimation evaluation metrics at this point, stop, check original labels, add more data, etc –> don’t move forward with this model. If you think you have a good model, please test the “raw” pose estimation performance on a video to validate performance:
> 
> ```python
> scorername = deeplabcut.analyze_videos(config_path,['/fullpath/project/videos/testVideo.mp4'], videotype='.mp4', auto_track=False)
> deeplabcut.create_video_with_all_detections(config_path, ['/fullpath/project/videos/testVideo.mp4'], videotype='.mp4')
> ```
> 
> This is just to check how your model is performing (if most individuals get detected, etc.). If your model seems good, you can try working with tracking parameters (as described [here](https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#if-auto-track-false)).

Thanks for your help. I can run  analyze_videos and create_video_with_all_detections like above. Then I got an analysis video with estimated pose points for ten fish, and the result looks good. Then I begin to test the tracking as bellow.
![屏幕截图 2024-02-19 110610](https://github.com/DeepLabCut/DeepLabCut/assets/69582732/f787f872-6ce4-4139-a9be-c6b679963542)
![屏幕截图 2024-02-19 110434](https://github.com/DeepLabCut/DeepLabCut/assets/69582732/f629d009-97b6-47e8-ac4e-6e848e32769f)
![屏幕截图 2024-02-19 104011](https://github.com/DeepLabCut/DeepLabCut/assets/69582732/1424de58-ed54-4de9-bfd8-2f06afe4bddf)
From the pickle file obtained from the folder, it appears that the size of the el.piclke file is only 1kb, which is not quite normal. My test video is only 10 seconds, is this caused by the test video being too short? Or should I do it to get the trajectory? Thank you again for your help.

**Comment by CherryMiya** [comment]
I tried to analyze the longer video, but got similar results. My file configuration is as follows.

![1](https://github.com/DeepLabCut/DeepLabCut/assets/69582732/703eff09-5e1d-462b-87f4-b154e789129e)

![2](https://github.com/DeepLabCut/DeepLabCut/assets/69582732/05850fa4-5186-472c-98fa-d43e4cd0c684)

**Comment by CherryMiya** [comment]
When I evaluate this model, although the evaluation results show no issues, a warning will appear, and I am not sure if this will affect subsequent tracking? Thank you for your help.
![屏幕截图 2024-02-18 185359](https://github.com/DeepLabCut/DeepLabCut/assets/69582732/9a66156b-0f9c-4ae5-b3c9-54ff59ada4ad)

**Comment by n-poulsen** [comment]
Could you try chaning your `inference_cfg.yaml` to:

```yaml
# Tracking:
#p/m pixels in width and height for increasing bounding boxes.
boundingboxslack : 0
# Intersection over Union (IoU) threshold for linking two bounding boxes
iou_threshold: 0.1
# maximum duration of a lost tracklet before it's considered a "new animal" (in frames)
max_age: 10
# minimum number of consecutive frames before a detection is tracked
min_hits: 2

minimalnumberofconnections: 1
pafthreshold: 0.1
pcutoff: 0.1
topktoretain: 10
variant: 0
withid: false
```

and see if that works? As explained [here](https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#if-auto-track-false), the values you selected won't be able to track individuals (your IOU threshold needs to be between 0 and 1 - the higher it is, the more strict).

**Comment by CherryMiya** [comment]
Thanks for your help. I have sovled my problem.
