### ISSUE TITLE
Can't find displayiters/saveiters/maxiters in `config.yaml` file

### ISSUE THREAD

**Issue by aaroncherian** [DeepLabCut/DeepLabCut#2518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

![image](https://github.com/DeepLabCut/DeepLabCut/assets/17153275/57367146-b58f-4bd9-beeb-68c14ee93e4b)

So in the `train_network` function, it states in the docstrings that the displayiters, saveiters, and maxiters inputs are all set in the 'pose_config.yaml' file. However, I'm not seeing immediately where that is set in my project config file (attached for reference). 

[config_txt.txt](https://github.com/DeepLabCut/DeepLabCut/files/14241289/config_txt.txt)

Additionally, it specifies in the instructions that there's a `pose_config.yaml` file. Is a different yaml than the `config.yaml` file in my project folder? If so, where would I find this file?

### Operating System

Windows 10 

### DeepLabCut version

DLC 2.3.8

### DeepLabCut mode

single animal

### Device type

NVIDIA GeForce 2090

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @aaroncherian!

The file where the `displayiters`, `saveiters`, and `maxiters` values are stored is the `pose_cfg.yaml` (which is not the project config, `config.yaml`).

The project configuration file (stored in `C:\PathToYourProject\config.yaml`) stores information about the entire project.

The `pose_cfg.yaml` file is created when you create a training dataset for your project (see the [guide](https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html#f-create-training-dataset-s)). This file configures how your model will be trained (you have 1 `pose_cfg.yaml` file for each shuffle that you create). It's stored in `C:\\PathToYourProject\\dlc-models\\exampleFeb12-trainset95shuffle1\\train`, where "exampleFeb12-trainset95shuffle1" would be the name for shuffle 1. That's the file that you want to edit to change these parameters.

**Comment by aaroncherian** [comment]
Ah gotcha, thank you!
