### ISSUE TITLE
Cannot label frames

### ISSUE THREAD

**Issue by ysmgrr** [DeepLabCut/DeepLabCut#2519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have an issue that has been reported before (#2362) but I could not solve it with the suggestions provided.
I am using the GUI version for a project. I can create the project, modify the config file and extract the frames. But when I click to label them, I get the following message:
![dlc1](https://github.com/DeepLabCut/DeepLabCut/assets/148891237/b609e483-672d-4b57-a855-f75e85867f5a)
Napari still opens and allows me to label the frames, storing .csv and .h5 files on the labeled-data project folder. If I reopen the folder in napari, I can see the previous labels I have addressed to each frame. However, I cannot use the check labels function since the same error appears and cannot do any of the following steps afterwards. Cleaning the environment and git cloning the repo again does not fix the error.

### Operating System

Windows 10

### DeepLabCut version

2.3.9

### DeepLabCut mode

single animal

### Device type

NVIDIA GeForce RTX 2070 SUPER

### Steps To Reproduce

1.Using Conda Environment
2. Load in Deeplabcut gui "deeplabcut.launch_dlc()"
3. Load Project - from .yaml in project folder
4. Go to label frames tab
5. select any folder that contains extracted frames
6. error messages come up

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Strange! thats a new one :) Could you try `pip install --upgrade napari-deeplabcut` in your env?

**Comment by ysmgrr** [comment]
Hi Dr. Mathis, thank you for the reply. 
Yes, everything goes well:
![dlc3](https://github.com/DeepLabCut/DeepLabCut/assets/148891237/10cca494-178f-48ac-90ef-a6993f07bed9)

But again, once I am in the "Label Frames" section, I get this: 
![dlc4](https://github.com/DeepLabCut/DeepLabCut/assets/148891237/6b555d44-5a13-46b0-8236-9d49368f7396)

Do you think it could be related to the conda version? They use a very old version in the office (4.3.0), and this is the only thing I can think of that is causing the issue.

**Comment by MMathisLab** [comment]
Could you try this:

Launch env

Then don't import ipython, just type 'python -m deeplabcut' - let see if indeed it's somehow related to Python/conda :)

**Comment by ysmgrr** [comment]
I tried, but I got the same issue. Alternatively, I uninstalled my previous anaconda version and installed miniforge in place, followed the instructions of DLC installation and again get the same warning. :(

**Comment by diegogallo96** [comment]
I have a similar issue. When I use deeplabcut.label_frames(config), it opens Napari, but I get an error in the Anaconda Prompt and Napari crashes. 

DLC:  2.3.9
conda: 24.3.0
python: 3.8.18
napari: 0.4.18

Error code:

In [4]: deeplabcut.label_frames(config_path)
Installed qt6 event loop hook.
WARNING: DirectWrite: CreateFontFaceFromHDC() failed (Indica un error en un archivo de entrada, como un archivo de fuentes.) for QFontDef(Family="MS Sans Serif", pointsize=12, pixelsize=16, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("MS Sans Serif", lfWidth=0, lfHeight=-16) dpi=120.

Any ideas?

**Comment by n-poulsen** [comment]
@ysmgrr Could you print the output of `pip list`, and `napari-info`?

@diegogallo96 Could you try to re-create your `deeplabcut` conda environment with python 3.9 or 3.10 instead of 3.8 and try in that new environment? We only support `python>=3.9`.

**Comment by n-poulsen** [comment]
Closing as stale
