### ISSUE TITLE
Recommended frame rate

### ISSUE THREAD

**Issue by Aks0121** [DeepLabCut/DeepLabCut#252]
**Your Operating system and DeepLabCut version**

macOS High Sierra, with an Anaconda Env, & DeepLabCut 2

**Describe the problem**

Hello,

Is there a recommended frame rate for video recording that would work well with the software? 

Thank you. 

**How to Reproduce the problem**

**Screenshots**

**Additional context**

**Comment by MMathisLab** [comment]
Hi Aks, if you have questions, would you mind posting here, on the help forum? thanks! We try to leave this space for code issues. :) https://forum.image.sc/tags/deeplabcut

(but, in short, as long as you can see what you want to track in each frame, then anything is fine)

**Comment by Aks0121** [comment]
My bad, got it. 

Thank you!
