### ISSUE TITLE
Can't train my network on another computer

### ISSUE THREAD

**Issue by tokioshima** [DeepLabCut/DeepLabCut#2522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hey!

I start to setup up video analysis with DLC on my laptop for few iterations and it's work perfectly. But when I try to reinstall the same setup on another computer, when I train my network I have this error message : 

![Screenshot 2024-02-18 112159](https://github.com/DeepLabCut/DeepLabCut/assets/130998972/522a0185-3132-4c26-aa32-1df4a9591a50)

Here you can see the terminal : 

![Screenshot 2024-02-18 112251](https://github.com/DeepLabCut/DeepLabCut/assets/130998972/8284ca81-0c85-458b-8561-2ddb893a4c81)
![Screenshot 2024-02-18 112306](https://github.com/DeepLabCut/DeepLabCut/assets/130998972/15bf4c1c-461c-4d41-9806-b0ff2066384d)

I see that the error message refers to mathlab things and indeed on this computer there are mathlab analyses being performed. Maybe it's due to that, but I'd like your opinion.
Thank you in advance, have a nice day

### Operating System

Windows 11

### DeepLabCut version

2.3.9

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
there is no error message ?

**Comment by tokioshima** [comment]
not at all. Just the traceback message at the bottom of DLC windows

**Comment by jeylau** [comment]
@tokioshima, we can read in the status bar of the GUI that some files were not found. I'd make sure the paths in the config.yaml are correct (it looks like there are inconsistencies for example between `snapshot prefix` and `project_path`). Have you moved the whole project folder to your other machine or only a part of it?

**Comment by n-poulsen** [comment]
Closing as stale
