### ISSUE TITLE
FileNotFoundError when evaluating network

### ISSUE THREAD

**Issue by tom221085** [DeepLabCut/DeepLabCut#2537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am training a new project with 2 animals using the GUI. When I try to evaluate the network with plot predictions checked I am getting a FileNotFoundError. I am guessing that something is wrong with the paths but I can't figure it out. My previous project evaluates normally.
I found a similar issue #2505 but couldn't see a solution for it.

### Operating System

Windows 10

### DeepLabCut version

3.3.8

### DeepLabCut mode

single animal

### Device type

NVIDIA GeForce RTX 3090

### Relevant log output

```shell
Config:
{'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11]],
 'all_joints_names': ['snout',
                      'head',
                      'right ear',
                      'left ear',
                      'back 1',
                      'back 2',
                      'back 3',
                      'tail base',
                      'tail 1',
                      'tail 2',
                      'tail 3',
                      'tail tip'],
 'batch_size': 1,
 'crop_pad': 0,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_1 Chamber 2 '
            'mice assay in tubeMar8\\1 Chamber 2 mice assay in '
            'tube_Thomas95shuffle3.pickle',
 'dataset_type': 'multi-animal-imgaug',
 'deterministic': False,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'C:\\ProgramData\\Anaconda3\\envs\\deeplabcut\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 1.0,
 'locref_smooth': False,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'mean_pixel': [123.68, 116.779, 103.939],
 'minconfidence': 0.01,
 'mirror': False,
 'multi_stage': False,
 'net_type': 'resnet_50',
 'nmsradius': 5.0,
 'num_idchannel': 2,
 'num_joints': 12,
 'num_limbs': 66,
 'optimizer': 'sgd',
 'pairwise_huber_loss': True,
 'pairwise_predict': False,
 'partaffinityfield_graph': [[0, 1],
                             [0, 2],
                             [0, 3],
                             [0, 4],
                             [0, 5],
                             [0, 6],
                             [0, 7],
                             [0, 8],
                             [0, 9],
                             [0, 10],
                             [0, 11],
                             [1, 2],
                             [1, 3],
                             [1, 4],
                             [1, 5],
                             [1, 6],
                             [1, 7],
                             [1, 8],
                             [1, 9],
                             [1, 10],
                             [1, 11],
                             [2, 3],
                             [2, 4],
                             [2, 5],
                             [2, 6],
                             [2, 7],
                             [2, 8],
                             [2, 9],
                             [2, 10],
                             [2, 11],
                             [3, 4],
                             [3, 5],
                             [3, 6],
                             [3, 7],
                             [3, 8],
                             [3, 9],
                             [3, 10],
                             [3, 11],
                             [4, 5],
                             [4, 6],
                             [4, 7],
                             [4, 8],
                             [4, 9],
                             [4, 10],
                             [4, 11],
                             [5, 6],
                             [5, 7],
                             [5, 8],
                             [5, 9],
                             [5, 10],
                             [5, 11],
                             [6, 7],
                             [6, 8],
                             [6, 9],
                             [6, 10],
                             [6, 11],
                             [7, 8],
                             [7, 9],
                             [7, 10],
                             [7, 11],
                             [8, 9],
                             [8, 10],
                             [8, 11],
                             [9, 10],
                             [9, 11],
                             [10, 11]],
 'partaffinityfield_predict': True,
 'regularize': False,
 'scoremap_dir': 'test',
 'shuffle': True,
 'sigma': 1,
 'snapshot_prefix': 'C:\\Users\\mooney_lab\\Desktop\\1 Chamber 2 mice assay in '
                    'tube-Thomas-2024-03-08\\dlc-models\\iteration-0\\1 '
                    'Chamber 2 mice assay in '
                    'tubeMar8-trainset95shuffle3\\test\\snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
C:\ProgramData\Anaconda3\envs\deeplabcut\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
2024-03-12 10:54:56.546872: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21670 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:17:00.0, compute capability: 8.6
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\gui\tabs\evaluate_network.py", line 181, in evaluate_network
    deeplabcut.evaluate_network(
  File "C:\ProgramData\Anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\evaluate.py", line 659, in evaluate_network
    evaluate_multianimal_full(
  File "C:\ProgramData\Anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\pose_estimation_tensorflow\core\evaluate_multianimal.py", line 446, in evaluate_multianimal_full
    visualization.save_labeled_frame(
  File "C:\ProgramData\Anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\utils\visualization.py", line 203, in save_labeled_frame
    fig.savefig(full_path)
  File "C:\ProgramData\Anaconda3\envs\deeplabcut\lib\site-packages\matplotlib\figure.py", line 3343, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\deeplabcut\lib\site-packages\matplotlib\backends\backend_qtagg.py", line 75, in print_figure
    super().print_figure(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\deeplabcut\lib\site-packages\matplotlib\backend_bases.py", line 2366, in print_figure
    result = print_method(
  File "C:\ProgramData\Anaconda3\envs\deeplabcut\lib\site-packages\matplotlib\backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "C:\ProgramData\Anaconda3\envs\deeplabcut\lib\site-packages\matplotlib\backends\backend_agg.py", line 509, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "C:\ProgramData\Anaconda3\envs\deeplabcut\lib\site-packages\matplotlib\backends\backend_agg.py", line 458, in _print_pil
    mpl.image.imsave(
  File "C:\ProgramData\Anaconda3\envs\deeplabcut\lib\site-packages\matplotlib\image.py", line 1689, in imsave
    image.save(fname, **pil_kwargs)
  File "C:\ProgramData\Anaconda3\envs\deeplabcut\lib\site-packages\PIL\Image.py", line 2429, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '\\\\?\\C:/Users/mooney_lab/Desktop/1 Chamber 2 mice assay in tube-Thomas-2024-03-08\\evaluation-results\\iteration-0\\1 Chamber 2 mice assay in tubeMar8-trainset95shuffle3\\LabeledImages_DLC_resnet50_1 Chamber 2 mice assay in tubeMar8shuffle3_500_snapshot-500\\Training-TP180_220211_0-img011.png'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
It looks like a path issue; was the project moved? 

`'\\\\?\\C:/Users/mooney_lab/Desktop/1 Chamber 2 mice assay in tube-Thomas-2024-03-08\\evaluation-results\\iteration-0\\1 Chamber 2 mice assay in tubeMar8-trainset95shuffle3\\LabeledImages_DLC_resnet50_1 Chamber 2 mice assay in tubeMar8shuffle3_500_snapshot-500\\Training-TP180_220211_0-img011.png'` as I guess this does not exist as such. 

Check the project path, and also it seems you are usnig it in mulit-animal mode, not single animal mode, just fyi! :)

**Comment by tom221085** [comment]
Should I use it in single animal mode if I have 2 animals interacting with each other?

I checked the project path and it seems as if it's in the right place. I attached a capture of the config.yaml file:

![Capture](https://github.com/DeepLabCut/DeepLabCut/assets/11939642/2ef8458f-ab21-441f-8a6a-ccb6fa1e4d89)

The path there seems to be correct. Do I have to change it somewhere else? Could it be that my project name is too long?

**Comment by n-poulsen** [comment]
@tom221085 I think the issue might come from the fact "/" and "\\" are mixed in your project path. Could you try updating your `project_path` to:

```yaml
project_path: C:\Users\mooney_lab\Desktop\1 Chamber 2 mice assay in tube-Thomas-2024-03-08
```

**Comment by tom221085** [comment]
@n-poulsen Thank you for that suggestion. I changed the project path in the config.yaml file as you suggested. When I run evaluate network it changes it back from "\" to "/" and I still get the same error message.

**Comment by n-poulsen** [comment]
@tom221085 did you update the configuration file with the DeepLabCut GUI?

**Comment by tom221085** [comment]
I tried both. Changing it in the config.yaml directly and in the DeepLabCut GUI. It still changes it back and gives me the error.

**Comment by n-poulsen** [comment]
@tom221085 Could you try running the following code snippet and let me know what's printed? You can run this in an `ipython` shell. 

```python
import os
from pathlib import Path

config = r"C:\Users\mooney_lab\Desktop\1 Chamber 2 mice assay in tube-Thomas-2024-03-08"
curr_dir = os.path.dirname(config)
print(curr_dir)
print(Path(config))
print(Path(config).parent)
```

**Comment by MMathisLab** [comment]
as a side comment, you should NOT have spaces in the DLC project name please, i.e.  "1 Chamber 2 mice assay in tube" minimally you need to add _ or - :) otherwise this is not very robust and can be read as new files at the breaks

**Comment by nicolej113** [comment]
I am also having the exact same issue. It occurred when I accidentally synced my computer to onedrive and had to revert my project file back to the local computer. However, I cannot undo the problem, everytime I interact with the GUI in 'evaluate network' the project path changes from \ to /.

**Comment by n-poulsen** [comment]
@nicolej113 that could be the source of the error! Since then, have you removed the project from OneDrive or is it still there?

@tom221085 are you or have you also used OneDrive?

**Comment by nicolej113** [comment]
> @nicolej113 that could be the source of the error! Since then, have you removed the project from OneDrive or is it still there?
> 
> @tom221085 are you or have you also used OneDrive?

I just retrained the model on my local computer files. Changing the config files to my local computer got very complicated and DLC stopped working.

**Comment by n-poulsen** [comment]
@nicolej113 could you explain what you mean by "DLC stopped working"? Do you get an error message, does something crash?

**Comment by tom221085** [comment]
> @tom221085 Could you try running the following code snippet and let me know what's printed? You can run this in an `ipython` shell.
> 
> ```python
> import os
> from pathlib import Path
> 
> config = r"C:\Users\mooney_lab\Desktop\1 Chamber 2 mice assay in tube-Thomas-2024-03-08"
> curr_dir = os.path.dirname(config)
> print(curr_dir)
> print(Path(config))
> print(Path(config).parent)
> ```

I ran it and got the following output:
C:\Users\mooney_lab\Desktop
C:\Users\mooney_lab\Desktop\1 Chamber 2 mice assay in tube-Thomas-2024-03-08
C:\Users\mooney_lab\Desktop

**Comment by tom221085** [comment]
> @nicolej113 that could be the source of the error! Since then, have you removed the project from OneDrive or is it still there?
> 
> @tom221085 are you or have you also used OneDrive?

No, I haven't used OneDrive. I only moved the folder within my local computer.

**Comment by n-poulsen** [comment]
@tom221085 If you fix the project path in your project's `config.yaml` and then run:

```python
from deeplabcut.utils import auxiliaryfunctions
cfg = auxiliaryfunctions.read_config(
  r"C:\Users\mooney_lab\Desktop\1 Chamber 2 mice assay in tube-Thomas-2024-03-08"
)
```

Does that incorrectly change the project path in the `config` again?

**Comment by tom221085** [comment]
When I run that code I am getting the following error message:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_18336\3595720360.py in <module>
----> 1 from deeplabcut.utils import auxiliaryfunctions
      2 cfg = auxiliaryfunctions.read_config(
      3   r"C:\Users\mooney_lab\Desktop\1 Chamber 2 mice assay in tube-Thomas-2024-03-08"
      4 )

ModuleNotFoundError: No module named 'deeplabcut'

**Comment by RolfSkyberg** [comment]
Hi all, I have been following this thread as I am having the same issue (i.e. when the evaluation result png files are being saved the pathing is all messed up). I think @n-poulsen is correct in that the issue has to  do with '\' being replaced by '/' in the config file pathing. I also have tried manually altering the config file in the gui and in the config file directly but when loading the config file in the gui, the '/' get switched back to '\'.  I can't figure out where/why this seems to be happening though.

> @tom221085 If you fix the project path in your project's `config.yaml` and then run:
> 
> ```python
> from deeplabcut.utils import auxiliaryfunctions
> cfg = auxiliaryfunctions.read_config(
>   r"C:\Users\mooney_lab\Desktop\1 Chamber 2 mice assay in tube-Thomas-2024-03-08"
> )
> ```
> 
> Does that incorrectly change the project path in the `config` again?

@n-poulsen I tried running this piece of code after manually correcting the project path and got this error if I only used the project path as input for the read_config() function. 
<img width="610" alt="Capture" src="https://github.com/DeepLabCut/DeepLabCut/assets/100157212/c389bfff-e2e2-4663-8b6c-f4d57519ca76">

If I instead used the config file path in the read_config() function I got it to work and it did not end up altering the project pathing. 
<img width="906" alt="Capture1" src="https://github.com/DeepLabCut/DeepLabCut/assets/100157212/8a26ffeb-151b-4a4a-95c1-0d0882632eef">

Hope this helps and please let me know if there is anything else that I can do to help diagnose this issue!

Thanks

**Comment by RolfSkyberg** [comment]
And just in case this is related and helps with the diagnosis (it seems related) when I try and click the edit pose.yaml button in the GUI under the train network tab I get a similar error regarding "/" and "\" in the pose.yaml pathing. 
<img width="812" alt="related issuer with edit pose_cfg" src="https://github.com/DeepLabCut/DeepLabCut/assets/100157212/a4a9f994-ed16-4aa5-9abc-eec68571cd30">

**Comment by RolfSkyberg** [comment]
@n-poulsen @MMathisLab @nicolej113 @tom221085 

Ok I think I figured out the problem, or at least a work around. The issue (for me at least) was occurring in line 203 of the visualization.py function (see screenshot). Essentially, the file path that the code was trying to save the figures to was too long so it was activating the if statement in line 200 of that same function, which appends \\\\?\\ to the beginning of the file path. I think this was causing the issue because I was able to avoid the error that @tom221085 posted about and evaluate my network by making my file path shorter than 260 characters and avoid activating that if statement. 

To do this I just made a copy of my whole DLC project in the root directory of one of my drives and then edited the new copy of the config file to direct toward the new copy of the DLC project. So essentially if you can get your file path that the evaluation images are being saved to below 260 characters then you can avoid the issue. It looks like @tom221085's evaluation results file path (where the .png is attempting to be saved) was also longer than 260 characters so I bet this work around will work for you too!

I havent made it any further down the DLC pipeline yet so I can't be sure that this is a total fix but it did get me one step further! Hope this helps everyone else.

<img width="466" alt="problem location" src="https://github.com/DeepLabCut/DeepLabCut/assets/100157212/1046af48-1d89-4925-8c6d-089905928abd">

**Comment by n-poulsen** [comment]
@RolfSkyberg Thank you for your help, and good catch! 

@tom221085 I'll close this as resolved, you can re-open it if @RolfSkyberg's solution doesn't work for you
