### ISSUE TITLE
deeplabcut.evaluate_network() Index error for multianimal project iteration

### ISSUE THREAD

**Issue by samsnowscience** [DeepLabCut/DeepLabCut#2539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi all!

I am running into an issue attmepting to do an evaluation on the second iteration of a multianimal network that I have just trained. I had no problems with iterations 0 and 1, but now in iteration 2, it is giving an IndexError (see log output below) and not proceeding with the evaluation. I have not adjusted any configuration settings interms of snapshot or shuffle. The main difference between previous iterations and now is that I have added more videos and labeled frames, including some derived from extracted outliers. I have run the merge_datasets function before creating the training dataset and running the training. 

As part of my attempts to fix the issue, I backed up all my iteration-1 materials and deleted them from the project, and reset the interation number to 1 in the config file, but re-training again and then running evaluation on the "new" interation 1 threw the same error.

I saw there was a similar issue previously that was solved (https://github.com/DeepLabCut/DeepLabCut/issues/1386) but it does not appear to extend to my particular case?

Any advice would be greatly appreciated!

Thanks very much for your time and consideration

### Operating System

Ubuntu 22.04

### DeepLabCut version

dlc version 2.3.9

### DeepLabCut mode

multi animal

### Device type

NVIDIA RTX 4090 gpu

### Steps To Reproduce

1. After training a new iteration of an existing project,
2. Begin in the standard deeplabcut conda environment based on the provided .yaml file
3. run ipython in the terminal
4. import deeplabcut, set config path and run deeplabcut.evaluate_network(config_path, plotting=True,gputouse=0)

### Relevant log output

```shell
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[7], line 1
----> 1 deeplabcut.evaluate_network(config_path, plotting=True,gputouse=0)

File ~/anaconda3/envs/DEEPLABCUT_pytorch/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/core/evaluate.py:667, in evaluate_network(config, Shuffles, trainingsetindex, plotting, show_errors, comparisonbodyparts, gputouse, rescale, modelprefix, per_keypoint_evaluation)
    664     from .evaluate_multianimal import evaluate_multianimal_full
    666     # TODO: Make this code not so redundant!
--> 667     evaluate_multianimal_full(
    668         config=config,
    669         Shuffles=Shuffles,
    670         trainingsetindex=trainingsetindex,
    671         plotting=plotting,
    672         comparisonbodyparts=comparisonbodyparts,
    673         gputouse=gputouse,
    674         modelprefix=modelprefix,
    675         per_keypoint_evaluation=per_keypoint_evaluation,
    676     )
    677 else:
    678     from deeplabcut.utils.auxfun_videos import imread, imresize

File ~/anaconda3/envs/DEEPLABCUT_pytorch/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/core/evaluate_multianimal.py:420, in evaluate_multianimal_full(config, Shuffles, trainingsetindex, plotting, show_errors, comparisonbodyparts, gputouse, modelprefix, per_keypoint_evaluation)
    415 min_dists = np.linalg.norm(
    416     xy_gt_values[found] - xy[neighbors[found]],
    417     axis=1,
    418 )
    419 inds = np.flatnonzero(all_bpts == bpt)
--> 420 sl = imageindex, inds[inds_gt[found]]
    421 dist[sl] = min_dists
    422 conf[sl] = probs_pred[n_joint][
    423     neighbors[found]
    424 ].squeeze()

IndexError: index 10 is out of bounds for axis 0 with size 10
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @samsnowscience, I agree I think your issue is different.

Did you change which bodyparts/individuals are in your project? 

And to help me reproduce this, could you share the header of your `CollectedData_scorer.csv` in the `training-datasets/iteration-2/...` folder as well as your `individuals`, `bodyparts`, `uniquebodyparts` and `multianimalbodyparts` in your project's `config.yaml` file?

**Comment by samsnowscience** [comment]
Hi @n-poulsen ! Thanks veruy much for taking this on. 

Indeed, I did change the max number of individuals to 10 (up from 5) between the iterations! I'm sorry I hadn't thought to mention that. The labeling GUI seemed to be handling that fine. 

I will add that between the last iteration and this one I also extracted some outlier frames and corrected the machine labels. During that process I noticed that the model has labeled the individuals as s"ind1," "ind2," etc. although they are called "individual1" and so on in the config.yaml file. 

Here is the requested info from the config (collected data csv is attached):

```yaml
individuals:
- individual1
- individual2
- individual3
- individual4
- individual5
- individual6
- individual7
- individual8
- individual9
- individual10
uniquebodyparts: []
multianimalbodyparts:
- nose
- btweyes
- dorsal1
- dorsal2
- dorsal3
- dorsal4
- dorsal5
- tailbase
- tailtip
- analfinbase
- analfintip
- chin
- tailbottom

bodyparts: MULTI!
```

[CollectedData_Sam.csv](https://github.com/DeepLabCut/DeepLabCut/files/14671795/CollectedData_Sam.csv)

Thanks again!

**Comment by n-poulsen** [comment]
Thanks @samsnowscience! I believe this change in the maximum number of individuals is at the root of the problem. When I look at your `CollectedData_Sam.csv` file, there are actually 15 individuals labeled (`idv1`, `idv2`, ..., `idv5`, `individual1`, `individual2`, ..., `individual10`). So there are actually 15 individuals defined in your collected data.

I believe the best thing to do is to fix your `CollectedData_Sam.csv` annotation file, so that all annotations are for individuals with names `[individual1, individual2, ..., individual10]`. Do you have enough experience with pandas to do this? You need to update both the `csv` and the `h5` files.

**Comment by samsnowscience** [comment]
Hi @n-poulsen ! Thanks so much for digging in this, I really appreciate it! Unfortunately, I do not have much pandas experience, but I suppose now is the time to learn. 

Is there a way to avoid this in the future? Those extra ID designations were produced by the machine label predictions on extracted outlier frames from videos. Is it the change in max number of individuals that caused the program to make up new names instead of using the names from the config, or is it the fact that the video I extracted outliers from only had 5 individual in it instead of ten?

**Comment by n-poulsen** [comment]
Yes, the change to the ID designations comes from the change in the max number of individuals (it's fine to use that option, it's using it and then extracting outlier frames from the analyzed videos that caused the issue).

I think the easiest way to fix your issue (without having to work with pandas at all) would be to update your project's `config.yaml` to contain the 15 animal names you have in your `CollectedData.csv` file: 

```yaml
individuals:
- ind1
- ind2
- ind3
- ind4
- ind5
- individual1
- individual2
- individual3
- individual4
- individual5
- individual6
- individual7
- individual8
- individual9
- individual10
```

This should allow you to successfully train and evaluate your model. Let me know if this fixes your issue! You'll just need to create a new training dataset to start training again (and increasing your project's iteration would be a good idea).

**Comment by samsnowscience** [comment]
I implemented your latter solution and updated my config.yaml file with the additional animal names, and it worked! I was able to successfully evaluate the model. Thanks so much again for your help!
