### ISSUE TITLE
deeplabcut.extract_frames(crop=True) does not crop the first extracted frame

### ISSUE THREAD

**Issue by auesro** [DeepLabCut/DeepLabCut#254]
**Your Operating system and DeepLabCut version**
Linux Mint 19.1. Anaconda environment. Deeplabcut 2.0.5
 
**Describe the bug**
Use of argument crop=True in deeplabcut.extract_frames raises the proper GUI to crop the frames. After setting the bounding box and extracting the frames, always the first extracted frame from each video is uncropped.

**Expected behavior**
All framse should be cropped according to the bounding box.

**Comment by MMathisLab** [comment]
We do this on purpose actually, for data augmentation. If you can label on one full frame this helps if cropping if different in the future. If you don’t want to use this frame, simply delete it from the folder before labeling and it will never be included.

**Comment by auesro** [comment]
It does not bother me at all, just reporting it in case it was a bug.
Thanks for the explanation.
