### ISSUE TITLE
Deeplabcut: Labeling Frames Issue

### ISSUE THREAD

**Issue by Scarlett-gaga** [DeepLabCut/DeepLabCut#2540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

1. I open the GUI
2. everything goes well in the "manage project" and "extract frames" tab
3. In the "Extract Frames" tab it gives me a message that says, "Frames were successfully extracted, for the videos of interest".
4. 【**This is where the problem occurs**】In the "Label Frames" tab, I click on the "Label Frames" button and open the folder that popped out, but there is no frame image in that folder. However, when I open the project file (which contains that popped-out folder in "labeled-data" folder) on my desktop, I can see the frames image in PNG format in the folder that just pops out. 

So why I can't see the image in that folder in GUI? But I can see those frames if I open project file on my desktop. Here are the screenshots.
<img width="838" alt="pic 1(Those frame pictures in folder)" src="https://github.com/DeepLabCut/DeepLabCut/assets/159801694/384870e1-c187-4d6b-baef-2063e0526c43">
<img width="679" alt="pic 2(no frame pictures in the folder that pops out)" src="https://github.com/DeepLabCut/DeepLabCut/assets/159801694/89cb453d-2215-4b9a-bfae-acef61b7b5c2">

### Operating System

operating system: windows 11 home

### DeepLabCut version

dlc version: 2.3.9

### DeepLabCut mode

multi animal

### Device type

gpu 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by wyclearnpy** [comment]
Maybe you can try clicking the Select Folder button.

**Comment by Scarlett-gaga** [comment]
> Maybe you can try clicking the Select Folder button.

Oh my god, It works!!! Looking back at this question I feel it's so silly hh.
Thank you so much!
