### ISSUE TITLE
Questions about training networks

### ISSUE THREAD

**Issue by wyclearnpy** [DeepLabCut/DeepLabCut#2541]
I saw the pre-trained network ResNet, etc. Are there any newer ones, or can I train them myself?

**Comment by n-poulsen** [comment]
Hi @wyclearnpy,

Our pre-trained networks (ResNets, EfficientNets, MobileNets, the URLs are [here](https://github.com/DeepLabCut/DeepLabCut/blob/main/deeplabcut/pose_estimation_tensorflow/models/pretrained/pretrained_model_urls.yaml)) come from TensorFlow directly, and are trained on ImageNet.

If you want to train your own backbone on ImageNet (or any other dataset) you can do so, but I don't think you'll gain performance (after transfer learning) by doing so. If you want to use different backbone architectures you can, but you'll have to implement them yourself (and either find pretrained weights or train a model).
