### ISSUE TITLE
Unstable GPU Utilization

### ISSUE THREAD

**Issue by Vaccummer** [DeepLabCut/DeepLabCut#2542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When I use tesla V100 16GB to train network, I set batch_size at 4 and global_scale at 0.6. In the start, the ultilization can be up to 98%, but after several minutes, the ultilization become low and unstable, varing from 0 to 20%, and the speed is very slow, even can't catch up with my 2080ti.  

### Operating System

Ubuntu-20.06LTS

### DeepLabCut version

2.3.9

### DeepLabCut mode

single animal

### Device type

tesla V100 16G sxm2

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @Vaccummer, is there any way you can profile what is happening (to see where the slow-down happens)?

And could you please provide the `tensorflow` and `cuda` versions that you are using?

**Comment by Vaccummer** [comment]
tensorflow: 2.12.0
cuda:11.8
cudnn:8.8.0
I have tried to use tensorflow profiler to supervise gpu expense, but the output file format is abnormal.
I guess there are some data preprocess by CPU during training, which limits the performance of GPU, but I don't know where it is.

**Comment by Vaccummer** [comment]
I find out the reason. In train.py, there is a function named "load and queue", and the line "batch_np = dataset.next_batch()" demands high performance of CPU, and it's single-thread! To conduct this line consume too much time, which limits the speed of the whole process.

**Comment by n-poulsen** [comment]
@Vaccummer that might be the bottleneck - we'll have parallel data loading in the upcoming PyTorch implementation of DeepLabCut, so we won't work on implementing this now. Thanks for going through the code and spotting this!

I'll close this issue as not planned, but if you want to implement multi-threading for data loading we would welcome the PR!

**Comment by loganwread** [comment]
I've noticed what I think is a similar issue using the same GPU (Tesla V100 32GB) but with analyzing videos. Inconsistent, if any, GPU usage for analyzing videos resulting in greatly inflated processing time. Would you prefer I make a new issue since it's for analyzing videos and not training?
