### ISSUE TITLE
Unable to Save Training Data Points

### ISSUE THREAD

**Issue by abiyarb** [DeepLabCut/DeepLabCut#2543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When I go to save my labeled data points before training a network, they do not save. I have tried both command + S and doing it manually through the 'File' dropdown menu. Neither of these options work. When I go to close the window after trying to save, it says that the points are not saved. I am not sure how to fix this issue. 

### Operating System

operating system : Mac Ventura 

### DeepLabCut version

dlc version : 2.3.9

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @abiyarb, did you make sure the "CollectedData" points layer is selected when saving (as shown in the screenshot below, the `CollectedData_b` layer is selected)?

<img width="918" alt="collectedDataSelected" src="https://github.com/DeepLabCut/DeepLabCut/assets/45132115/6414bc37-3c25-493a-9707-86a5961d337e">

**Comment by abiyarb** [comment]
Yes, I have had that selected each time.

**Comment by ffranzoniAI** [comment]
Im having the same issue, in previos versions there was a save button on the bottom right. Now i dont have it anymore.

**Comment by n-poulsen** [comment]
Are you able to save with `File > Save Selected Layer(s)`? And if not, do you get an error message printed (either in the shell where you launched the GUI, or at the bottom of the GUI, as shown in the attached screenshot)?

![Screenshot 2024-04-02 at 15 06 16](https://github.com/DeepLabCut/DeepLabCut/assets/45132115/70951da2-f4dd-4c39-8c2f-fd6ff7ac86c3)

**Comment by n-poulsen** [comment]
Closing as stale
