### ISSUE TITLE
Issue with starting DLC via conda on Apple M1. Numpy Issue.

### ISSUE THREAD

**Issue by jamiewilbraham** [DeepLabCut/DeepLabCut#2544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Installed using the DEEPLABCUT_M1 conda file. When trying to run DLC using python I get the following.

```
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
Traceback (most recent call last):
File "/opt/homebrew/Caskroom/miniconda/base/envs/DEEPLABCUT_M1/lib/python3.9/runpy.py", line 188, in _run_module_as_main
mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
File "/opt/homebrew/Caskroom/miniconda/base/envs/DEEPLABCUT_M1/lib/python3.9/runpy.py", line 147, in _get_module_details
return _get_module_details(pkg_main_name, error)
File "/opt/homebrew/Caskroom/miniconda/base/envs/DEEPLABCUT_M1/lib/python3.9/runpy.py", line 111, in _get_module_details
__import__(pkg_name)
File "/opt/homebrew/Caskroom/miniconda/base/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/deeplabcut/__init__.py", line 16, in <module>
import tensorflow as tf
File "/opt/homebrew/Caskroom/miniconda/base/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/tensorflow/__init__.py", line 37, in <module>
from tensorflow.python.tools import module_util as _module_util
File "/opt/homebrew/Caskroom/miniconda/base/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 42, in <module>
from tensorflow.python import d
```

### Operating System

macOS M1

### DeepLabCut version

dlc version - latest

### DeepLabCut mode

single animal

### Device type

cpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @jamiewilbraham, how did you install DeepLabCut (which commands did you use)?

And could you share the output of `pip list` in your conda environment?

**Comment by ErikDerGute** [comment]
Same issue here. I cloned the repo on my Mac (M1 chip) and creating a corresponding env using the DEEPLABCUT_M1.yaml. After that I installed dlc using `pip install e .` inside the cloned repo. After running in to some issues, I was able to complete the installation successfully (uninstalled tables and reinstalled tables==3.7.0). 
`pip list` gives me:  

> Package                       Version
> ----------------------------- --------------
> absl-py                       2.1.0
> alabaster                     0.7.16
> anyio                         4.3.0
> app-model                     0.2.5
> appdirs                       1.4.4
> appnope                       0.1.4
> argon2-cffi                   23.1.0
> argon2-cffi-bindings          21.2.0
> arrow                         1.3.0
> asttokens                     2.4.1
> astunparse                    1.6.3
> attrs                         23.2.0
> Babel                         2.14.0
> beautifulsoup4                4.12.3
> bleach                        6.1.0
> blosc2                        2.5.1
> build                         1.1.1
> cached-property               1.5.2
> cachetools                    5.3.3
> cachey                        0.2.1
> certifi                       2024.2.2
> cffi                          1.16.0
> charset-normalizer            3.3.2
> click                         8.1.7
> cloudpickle                   3.0.0
> comm                          0.2.2
> contourpy                     1.2.0
> cycler                        0.12.1
> dask                          2024.3.1
> dask-expr                     1.0.4
> dask-image                    2023.8.1
> debugpy                       1.8.1
> decorator                     5.1.1
> deeplabcut                    2.3.9
> defusedxml                    0.7.1
> dlclibrary                    0.0.6
> docstring_parser              0.16
> docutils                      0.17.1
> e                             1.4.5
> entrypoints                   0.4
> exceptiongroup                1.2.0
> executing                     2.0.1
> fastjsonschema                2.19.1
> filelock                      3.13.1
> filterpy                      1.4.5
> flatbuffers                   24.3.7
> fonttools                     4.50.0
> fqdn                          1.5.1
> freetype-py                   2.4.0
> fsspec                        2024.3.1
> gast                          0.4.0
> google-auth                   2.29.0
> google-auth-oauthlib          1.0.0
> google-pasta                  0.2.0
> grpcio                        1.62.1
> h5py                          3.6.0
> HeapDict                      1.0.1
> hsluv                         5.0.4
> huggingface-hub               0.21.4
> idna                          3.6
> imageio                       2.34.0
> imageio-ffmpeg                0.4.9
> imagesize                     1.4.1
> imgaug                        0.4.0
> importlib_metadata            7.1.0
> importlib_resources           6.4.0
> in-n-out                      0.2.0
> ipykernel                     6.29.3
> ipython                       8.18.1
> ipython-genutils              0.2.0
> ipywidgets                    8.1.2
> isoduration                   20.11.0
> jax                           0.4.25
> jedi                          0.19.1
> Jinja2                        3.1.3
> joblib                        1.3.2
> jsonpointer                   2.4
> jsonschema                    4.21.1
> jsonschema-specifications     2023.12.1
> jupyter                       1.0.0
> jupyter_client                7.4.9
> jupyter-console               6.6.3
> jupyter_core                  5.7.2
> jupyter-events                0.10.0
> jupyter_server                2.13.0
> jupyter_server_terminals      0.5.3
> jupyterlab_pygments           0.3.0
> jupyterlab_widgets            3.0.10
> keras                         2.12.0
> kiwisolver                    1.4.5
> lazy_loader                   0.3
> libclang                      18.1.1
> llvmlite                      0.42.0
> locket                        1.0.0
> magicgui                      0.8.2
> Markdown                      3.6
> markdown-it-py                3.0.0
> MarkupSafe                    2.1.5
> matplotlib                    3.8.3
> matplotlib-inline             0.1.6
> mdurl                         0.1.2
> mistune                       3.0.2
> ml-dtypes                     0.3.2
> msgpack                       1.0.8
> msgpack-numpy                 0.4.8
> napari                        0.4.18
> napari-console                0.0.9
> napari-deeplabcut             0.2.1.5
> napari-plugin-engine          0.2.0
> napari-svg                    0.1.10
> natsort                       8.4.0
> nb_conda                      2.2.1
> nb_conda_kernels              2.3.1
> nbclassic                     1.0.0
> nbclient                      0.10.0
> nbconvert                     7.16.3
> nbformat                      5.10.3
> ndindex                       1.8
> nest_asyncio                  1.6.0
> networkx                      3.2.1
> notebook                      6.5.6
> notebook_shim                 0.2.4
> npe2                          0.7.5
> numba                         0.59.1
> numexpr                       2.9.0
> numpy                         1.22.4
> numpydoc                      1.5.0
> oauthlib                      3.2.2
> opencv-python                 4.9.0.80
> opencv-python-headless        4.9.0.80
> opt-einsum                    3.3.0
> overrides                     7.7.0
> packaging                     24.0
> pandas                        2.2.1
> pandocfilters                 1.5.0
> parso                         0.8.3
> partd                         1.4.1
> patsy                         0.5.6
> pexpect                       4.9.0
> pickleshare                   0.7.5
> pillow                        10.2.0
> PIMS                          0.6.1
> Pint                          0.23
> pip                           24.0
> pkgutil_resolve_name          1.3.10
> platformdirs                  4.2.0
> pooch                         1.8.1
> prometheus_client             0.20.0
> prompt-toolkit                3.0.42
> protobuf                      4.25.3
> psutil                        5.9.8
> psygnal                       0.10.2
> ptyprocess                    0.7.0
> pure-eval                     0.2.2
> py-cpuinfo                    9.0.0
> pyarrow                       15.0.2
> pyasn1                        0.5.1
> pyasn1-modules                0.3.0
> pyconify                      0.1.6
> pycparser                     2.21
> pydantic                      1.10.14
> pydantic-compat               0.1.2
> Pygments                      2.17.2
> pyobjc-core                   10.2
> pyobjc-framework-Cocoa        10.2
> PyOpenGL                      3.1.7
> pyparsing                     3.1.2
> pyproject_hooks               1.0.0
> PySide6                       6.3.1
> PySide6-Addons                6.3.1
> PySide6-Essentials            6.3.1
> python-dateutil               2.9.0
> python-json-logger            2.0.7
> pytz                          2024.1
> PyYAML                        6.0.1
> pyzmq                         24.0.1
> QDarkStyle                    3.1
> qtconsole                     5.5.1
> QtPy                          2.4.1
> referencing                   0.34.0
> requests                      2.31.0
> requests-oauthlib             1.4.0
> rfc3339-validator             0.1.4
> rfc3986-validator             0.1.1
> rich                          13.7.1
> rpds-py                       0.18.0
> rsa                           4.9
> ruamel.yaml                   0.18.6
> ruamel.yaml.clib              0.2.8
> scikit-image                  0.22.0
> scikit-learn                  1.4.1.post1
> scipy                         1.12.0
> Send2Trash                    1.8.2
> setuptools                    69.2.0
> shapely                       2.0.3
> shiboken6                     6.3.1
> six                           1.16.0
> slicerator                    1.1.0
> sniffio                       1.3.1
> snowballstemmer               2.2.0
> soupsieve                     2.5
> Sphinx                        4.5.0
> sphinxcontrib-applehelp       1.0.8
> sphinxcontrib-devhelp         1.0.6
> sphinxcontrib-htmlhelp        2.0.5
> sphinxcontrib-jsmath          1.0.1
> sphinxcontrib-qthelp          1.0.7
> sphinxcontrib-serializinghtml 1.1.10
> stack-data                    0.6.2
> statsmodels                   0.14.1
> superqt                       0.6.2
> tables                        3.7.0
> tabulate                      0.9.0
> tensorboard                   2.12.3
> tensorboard-data-server       0.7.2
> tensorflow-estimator          2.12.0
> tensorflow-macos              2.12.0
> tensorflow-metal              1.1.0
> tensorpack                    0.11
> termcolor                     2.4.0
> terminado                     0.18.1
> tf-slim                       1.1.0
> threadpoolctl                 3.4.0
> tifffile                      2024.2.12
> tinycss2                      1.2.1
> tomli                         2.0.1
> tomli_w                       1.0.0
> toolz                         0.12.1
> torch                         1.12.0
> tornado                       6.4
> tqdm                          4.66.2
> traitlets                     5.14.2
> typer                         0.9.0
> types-python-dateutil         2.9.0.20240316
> typing_extensions             4.10.0
> typing-utils                  0.1.0
> tzdata                        2024.1
> uri-template                  1.3.0
> urllib3                       2.2.1
> vispy                         0.12.2
> wcwidth                       0.2.13
> webcolors                     1.13
> webencodings                  0.5.1
> websocket-client              1.7.0
> Werkzeug                      3.0.1
> wheel                         0.43.0
> widgetsnbextension            4.0.10
> wrapt                         1.14.1
> zipp                          3.17.0

**Comment by ErikDerGute** [comment]
Maybe I found a solution for our problem. After some investigations I think I figured out that 

> 0x10 but this version of numpy is 0xf

means that the numpy version in your env is not the same used during the pip installation of DLC. So my first try was to upgrade numpy to the latest version, only to the see that this only results in compatibility issues. After uninstalling numpy and installing a numpy version (1.23.5) that requires all dependencies from the other packages I also set line 36 of setup.py to `"numpy==1.23.5"`. Afterwards I uninstalled and reinstalled dlc using the manipulated setup.py version and it worked. Now I ran in to some other errors, but at least I got the bootscreen of dlc. Maybe this works for you too.

Edit: I could also resolve my other issue. Somehow in the env the x86_64 version of vsipy was installed, which obviously not work for arm. Uninstalling vispy and reinstalling vispy using `ARCHFLAGS="-arch arm64" pip install vispy==0.12.2` solved the issue. Maybe you run in to the same error.

**Comment by hummuscience** [comment]
We had a similar issue with the YAML file installing `numpy `version `1.22.4 `and `tensorflow-macos 2.12.0` and `tensorflow-metal 1.1.0` 

upgrading `numpy` to `1.26.4 `solved the issue

**Comment by n-poulsen** [comment]
Thanks @hummuscience and @ErikDerGute! I can confirm that things run smoothly for me with more recent versions of `numpy`.

@jamiewilbraham can you confirm that upgrading `numpy` fixes your issue?

**Comment by n-poulsen** [comment]
As described [here](https://forums.developer.apple.com/forums/thread/723468), please try installing `numpy==1.23.2` to fix this issue.
