### ISSUE TITLE
FileNotFoundError when run model zoo Colab tutorial on local computer

### ISSUE THREAD

**Issue by zhuzhuhaor** [DeepLabCut/DeepLabCut#2547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi, I'm running model zoo locally on our lab computer which follows the Colab tutorial. When I ran the function create_pretrained_project(...) the FileNotFoundError occurs:
![Screenshot_model_zoo_error](https://github.com/DeepLabCut/DeepLabCut/assets/63587462/28af9d0a-9c2c-49bb-9a81-ef81fae5935b)
 
The full error text shows below on the log section ↓

As you can see on the path, there are strange characters which indicates its a folder. But I checked it which turns out to be a "file".'

I tried 3 pretrained model: superanimal_topviewmouse; superanimal_topviewmouse_dlcrnet and superanimal_topviewmouse_hrnetw32 all of them have similar FileNotFoundError. I guess other pretraind model will have same issue and I think it's something wrong with my lab computer or the environment. The environment installed based on the DLC website tutorial, by running conda env create -f DEEPLABCUT.yaml. And then run pip install deeplabcut[tf,gui]
Please help :frowning: Thanks.

By the way. I noticed in the paper of model zoo shown on the website. It seems that some model zoo pretrained model on mice can recognize multiple mouse (i.e. has multiple animal recognize model on). I wonder which model can do this. I tested the superanimal_topviewmouse which can't recognize 2 mouse... All points only tracked on single mouse. Thanks for your help!

### Operating System

operating system: Win11 23H2

### DeepLabCut version

dlc version: 2.3.9

### DeepLabCut mode

single animal

### Device type

GPU: RTX 4070 Ti 12GB
CPU: AMD Ryzen 5 5600X 6 cores

### Steps To Reproduce

import os
import deeplabcut

video_path = r"D:\chenhzhu_folder\video_copy_chenhzhu.mp4"

import ipywidgets as widgets
from IPython.display import display

model_options = deeplabcut.create_project.modelzoo.Modeloptions
model_selection = widgets.Dropdown(
    options=model_options,
    value=model_options[0],
    description="Choose a DLC ModelZoo model!",
    disabled=False
)
display(model_selection)

project_name = 'myDLC_modelZoo'
your_name = 'chenhzhu'
# model2use = model_selection.value
model2use = "superanimal_topviewmouse_dlcrnet"
videotype = os.path.splitext(video_path)[-1].lstrip('.') #or MOV, or avi, whatever you uploaded!

# Error: can't find a file after downloding the pretrained model. WEIRD

config_path, train_config_path = deeplabcut.create_pretrained_project(
    project_name,
    your_name,
    [video_path],
    videotype=videotype,
    model=model2use,
    analyzevideo=True,
    createlabeledvideo=True,
    # multianimal=True,
    copy_videos=True, #must leave copy_videos=True
)

### Relevant log output

```shell
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[39], line 3
      1 # Error: can't find a file after downloding the pretrained model. WEIRD
----> 3 config_path, train_config_path = deeplabcut.create_pretrained_project(
      4     project_name,
      5     your_name,
      6     [video_path],
      7     videotype=videotype,
      8     model=model2use,
      9     analyzevideo=True,
     10     createlabeledvideo=True,
     11     # multianimal=True,
     12     copy_videos=True, #must leave copy_videos=True
     13 )

File c:\Anaconda\envs\DLC_zoo\lib\site-packages\deeplabcut\create_project\modelzoo.py:261, in create_pretrained_project(project, experimenter, videos, model, working_directory, copy_videos, videotype, analyzevideo, filtered, createlabeledvideo, trainFraction)
    259 # Download the weights and put then in appropriate directory
    260 print("Downloading weights...")
--> 261 download_huggingface_model(model, train_dir)
    263 pose_cfg = deeplabcut.auxiliaryfunctions.read_plainconfig(path_train_config)
    264 pose_cfg["dataset_type"] = "imgaug"

File c:\Anaconda\envs\DLC_zoo\lib\site-packages\dlclibrary\dlcmodelzoo\modelzoo_download.py:122, in download_huggingface_model(model_name, target_dir, remove_hf_folder, rename_mapping)
    119 url = url.split("/")
...
    267             # macOS
    268             if _HAS_FCOPYFILE:
    269                 try:

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\chenhzhu_folder\\myDLC_modelZoo-chenhzhu-2024-03-20\\dlc-models\\iteration-0\\myDLC_modelZooMar20-trainset95shuffle1\\train\\models--mwmathis--DeepLabCutModelZoo-SuperAnimal-TopViewMouse\\snapshots\\ca3245fa86115dd2b717d0fa33fbf2b0986b3bf6\\DLC_ma_supertopview5k_resnet_50_iteration-0_shuffle-1.tar.gz
```

### Anything else?

Here's more log output and screenshot that shows another error when I choose superanimal_topviewmouse_dlcrnet:
Log output:
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
File c:\Anaconda\envs\DLC_zoo\lib\shutil.py:825, in move(src, dst, copy_function)
    824 try:
--> 825     os.rename(src, real_dst)
    826 except OSError:

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\chenhzhu_folder\\myDLC_modelZoo-chenhzhu-2024-03-21\\dlc-models\\iteration-0\\myDLC_modelZooMar21-trainset95shuffle1\\train\\models--mwmathis--DeepLabCutModelZoo-SuperAnimal-TopViewMouse\\blobs\\0e8574860943385cf83a3949e42658dfade4d4cfc3884d267feb2bd8a9e02bbd' -> 'D:\\chenhzhu_folder\\myDLC_modelZoo-chenhzhu-2024-03-21\\dlc-models\\iteration-0\\myDLC_modelZooMar21-trainset95shuffle1\\train\\models--mwmathis--DeepLabCutModelZoo-SuperAnimal-TopViewMouse\\snapshots\\ca3245fa86115dd2b717d0fa33fbf2b0986b3bf6\\DLC_ma_supertopview5k_resnet_50_iteration-0_shuffle-1.tar.gz'

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
Cell In[5], line 3
      1 # Error: can't find a file after downloding the pretrained model. WEIRD
----> 3 config_path, train_config_path = deeplabcut.create_pretrained_project(
      4     project_name,
      5     your_name,
      6     [video_path],
      7     videotype=videotype,
      8     model=model2use,
      9     analyzevideo=True,
     10     createlabeledvideo=True,
     11     # multianimal=True,
     12     copy_videos=True, #must leave copy_videos=True
     13 )
...
    267             # macOS
    268             if _HAS_FCOPYFILE:
    269                 try:

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\chenhzhu_folder\\myDLC_modelZoo-chenhzhu-2024-03-21\\dlc-models\\iteration-0\\myDLC_modelZooMar21-trainset95shuffle1\\train\\models--mwmathis--DeepLabCutModelZoo-SuperAnimal-TopViewMouse\\snapshots\\ca3245fa86115dd2b717d0fa33fbf2b0986b3bf6\\DLC_ma_supertopview5k_resnet_50_iteration-0_shuffle-1.tar.gz'

Screenshots:
![another_model_error_1](https://github.com/DeepLabCut/DeepLabCut/assets/63587462/99f812c9-e414-4c22-bbeb-1a53a8252e0e)
![another_model_error_2](https://github.com/DeepLabCut/DeepLabCut/assets/63587462/2bea9eef-065d-4d5b-a37d-19b53fea2342)
![another_model_error_3](https://github.com/DeepLabCut/DeepLabCut/assets/63587462/e2d9d609-22ca-41db-9b3a-aae805c114a2)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
hi @zhuzhuhaor I'll let @n-poulsen @yeshaokai comment on the superanimal download issues, but for the supernaimal mutli-animal, this requires you use the detector; which is not intrgrated into this code yet, as the paper is not published. It should be by May :)

**Comment by siddypot** [comment]
Any update on this?
