### ISSUE TITLE
ValueError: numpy.ufunc size changed (.h5 not created during label_frames) 

### ISSUE THREAD

**Issue by mgparish01** [DeepLabCut/DeepLabCut#255]
Windows 10, with an Anaconda Env, & DeepLabCut 2.0.5.1

**Describe the problem**
When labeling the body parts for the extracted frames a CSV file was created. I found the command that would convert the csv files to hdf.       [deeplabcut.convertcsv2h5(config_path)] 

When I run the code a prompt asks me if I want to convert the file and I enter yes. However, I get an error that says "ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject" 

When I googled the error, a few suggestions came up to update Numpy. I used the anaconda navigator to update and Numpy is currently 1.16.0 while Numpy-base is 1.16.2. I still get the error and am unsure what to do. 

Error is on line 59 of OF_LgTraining.py Script (attached) 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/49172549/55365362-83d8c480-54a1-11e9-9d8c-0065065121fc.PNG)

**Additional context**
OF_LgTraining.py script 
[OF_LgTraining.txt](https://github.com/AlexEMG/DeepLabCut/files/3031688/OF_LgTraining.txt)

**Comment by MMathisLab** [comment]
Curious why you are using the csvtoh5 function though, the h5 is written in the label frames step as well (and assumes you have an h5, just you needed to manually edit something). So you needed to edit values? If the h5 was not created initially, you likely had a pytables installation error. Are you using the supplied Anaconda env? Please check the other GitHub issues for pytable related issues, installation can be an issue if you don’t use conda forge (and/or it’s not an issue with the supplied Anaconda env we provide).

**Comment by mgparish01** [comment]
Just to clarify,
I was using the csvtoh5 because the instructions said a hdf file would be created after labeling the videos. When I checked the labels it said that there was no labels for any of the videos. I just assumed it was because the labels were csv and not hdf.

Any suggestions on how to fix pytables?

As for the environment, I just used one I created with conda. We're are running on CPU as well.

Thanks for the quick reply!

**Comment by MMathisLab** [comment]
Okay good to know, so likely it’s just the h5 step (which will keep popping up for you). Here is the env I recommend using! Just download and run this line: https://github.com/AlexEMG/DeepLabCut/tree/master/conda-environments

**Comment by mgparish01** [comment]
When I try to follow the solution provided in the link and create the environment i get the message 
"'git' is not recognized as an internal or external command,
operable program or batch file."

I have tried the command in both the cmd and anaconda prompt. Both give me the same error. Even when i go to the folder I would like to folder I want deeplabcuts in.

**Comment by MMathisLab** [comment]
yes, on windows you need to first install Gitbash: 

For Windows, also please install GITBASH https://gitforwindows.org/ and OPEN cmd by right-clicking "run as ADIM"

https://github.com/AlexEMG/DeepLabCut/wiki/Troubleshooting-Tips
