### ISSUE TITLE
Software crashing while training network

### ISSUE THREAD

**Issue by pkobor** [DeepLabCut/DeepLabCut#2550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello,

my software crashes while trying to train my network without any error output. It crashes right at the beginning when I try to train my network.

### Operating System

operating system:

MacOs Ventura 13.6.4

### DeepLabCut version

dlc version:

### DeepLabCut mode

single animal

### Device type

gpu
Intel Iris Plus Graphics 640 1536 MB

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Hi @pkobor we are going to need more information and the relevant log output from you! :)

**Comment by n-poulsen** [comment]
Closing as stale
