### ISSUE TITLE
Multi-person 3D tracking

### ISSUE THREAD

**Issue by ChristianNSchmitz** [DeepLabCut/DeepLabCut#2554]
Dear developer team,

we are interested in a multi-person multi-camera motion capturing experiment and would like to ask you whether this would be possible with deeplabcut3d?

Thanks and best wishes
Christian

**Comment by MMathisLab** [comment]
Hi @ChristianNSchmitz DLC support human pose tracking; there are more advances in 3D that are not yet in this package though, so while it's coming it's likely not the absolutely state of the art.

**Comment by ChristianNSchmitz** [comment]
Dear Mackenzie, thank you very much for your reply. It's great that DLC supports 3d pose tracking. Can it also track multiple people at once over multiple cameras?
