### ISSUE TITLE
Deeplabcut Crashes when training model, or analyzing videos

### ISSUE THREAD

**Issue by YUNoSol** [DeepLabCut/DeepLabCut#2557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

We have been working with DeepLabCut for months (GUI-version) with little to no issues, up until Friday (4th of april)

The previous day(3rd of april) I had successfully created a new configuration, trained the model, and analyzed some of the videos without an issue(Like I have done many times now), but when attempting to continue the analysis on friday, Napari closed down, and the terminal is as seen below (I apologize for image and not text)

![Terminal right after crash](https://github.com/DeepLabCut/DeepLabCut/assets/157392652/8c4768b6-2489-4727-b5cb-8a152c4f2da1)

Similarly, when I tried to train a new model, Napari closed down, and there was a similar error in the termial (UserWarning: 'layer.apply')

Restarting the PC will sometimes result in one video being analyzed, but Napari will close down during the analysis of the first or second video. 

Memory on PC is 50GB+, so not a memory issue.

We created a new environment, with a fresh DeepLabCut version, with the same result (Napari crashing)

No recent windows update (latest was on the 19'th of march)

I attempted to analyze videos which previously analysed without an issue, and napari still shut down, so it shouldnt be an issue with the files.

I am puzzled as to how it could work perfectly one day, and then not the next.
I must admit that I am not particularly profitient in programming/coding, so there might be something simple that I have missed. I am just

I have attached the conda-info, conda-list and pip-list. 
[conda-info.txt](https://github.com/DeepLabCut/DeepLabCut/files/14922233/conda-info.txt)
[Conda-list.txt](https://github.com/DeepLabCut/DeepLabCut/files/14922234/Conda-list.txt)
[pip list.txt](https://github.com/DeepLabCut/DeepLabCut/files/14922235/pip.list.txt)

Let me know if I can provide more info!

Thank you in advance

Best regards, 
Sol

### Operating System

Windows 11

### DeepLabCut version

dlc version:  2.3.9

### DeepLabCut mode

single animal

### Device type

gpu: Geforce RTX 3080-ti 12 -GB

### Steps To Reproduce

1: Environment:
[conda-info.txt](https://github.com/DeepLabCut/DeepLabCut/files/14922315/conda-info.txt)
[Conda-list.txt](https://github.com/DeepLabCut/DeepLabCut/files/14922316/Conda-list.txt)
[pip list.txt](https://github.com/DeepLabCut/DeepLabCut/files/14922317/pip.list.txt)

2: Configuration:
[config.zip](https://github.com/DeepLabCut/DeepLabCut/files/14922430/config.zip)

I cannot attach all files within my project folder, since it is too big. if necessary, please advise me as to where I can upload it, so you can get access

3: in the GPU, press 'train network'

4: see error:
![Terminal right after crash](https://github.com/DeepLabCut/DeepLabCut/assets/157392652/0d82338e-ce39-4d84-8ced-2be3f5bd23c5)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @YUNoSol! From the output of `pip list`, it seems that you have `PyQt5` installed in the environment, which may be causing the issue.

Could you please try to remove it (with `pip uninstall PyQt5`)?

And could you also provide the output of `napari --info`?

**Comment by YUNoSol** [comment]
Hi @n-poulsen

So I was about to uninstall PyQt5, but wanted to recreate the error before changing anything. 
The training started and finished without an issue, same with the video analysis. I have no Idea about what solved the issue, since no one has changed anything in the environment since the error started occurring. 
Only thing that I can think of, is the fact that we have removed and reinserted the GPU, but I'm not sure if that could have been what solved it.

I have not uninstalled PyQt5, since it now works despite it being installed.

I have attached the output from napari --info
[napari --info.txt](https://github.com/DeepLabCut/DeepLabCut/files/15010510/napari.--info.txt)

If anyone has an idea about what else might have solved the issue, please enlighten me, otherwise we are just happy that it is working again.

Best regards, 
Sol
