### ISSUE TITLE
Evaluate the RMSE and map for each ID

### ISSUE THREAD

**Issue by SCsleepy** [DeepLabCut/DeepLabCut#2560]
Hello! 
I am using MADLC and I know that the Euclidean distance for each ID can be obtained during evaluation. Is there currently a method to obtain the RMSE and map for each ID. 
Thank you for your help.

**Comment by n-poulsen** [comment]
Hi @SCsleepy, by each ID do you mean each bodypart (e.g., "nose", "left_eye", "right_eye") or individual?

**Comment by SCsleepy** [comment]
> Hi @SCsleepy, by each ID do you mean each bodypart (e.g., "nose", "left_eye", "right_eye") or individual?

@n-poulsen  Thank you for your reply. What I mean is individual. My dataset contains scenes of mother tigers and young tigers. I always label the mother tigers as id1, and the young tigers as id2-4. Now I hope to obtain RMSE and mAP for both the mother tiger and the young tiger during the evaluation phase.

**Comment by MMathisLab** [comment]
It it printed in the terminal when you run evaluation.
