### ISSUE TITLE
GUI cannot open files from mapped network drives on Windows 11 and changes the drive letter to network address automatically for the YAML file

### ISSUE THREAD

**Issue by nexflatline** [DeepLabCut/DeepLabCut#2564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

The window for selecting files on the GUI doesn't show mapped network drives and can't open them through the drive letter. Same for Napari.

If searching the mapped drive through its network address instead of drive letter, files can be opened.
For example:
- Typing `Z:\DLC` on the file selection window give an error "Drive Z does not exist"
- Typing instead `//192.168.0.145//DLC` opens the drive correctly.

If the files are added through the headless version, they can be still accessed by the GUI, so the issue is limited to the file selection window (adding videos, labeling, etc). With one caveat:
- The "project_path" in the YAML file is automatically converted from drive letter to network address whenever opened, even if the path only contains backslashes.
- The videos stay as originally added (either drive letter or network address), can still be accessed and are not automatically converted to network address.

On previous versions of DLC, access by drive letter was possible (maybe 2.3.1, not sure), but I don't know if it's due to some change in Windows or on DLC itself.

The advantage of accessing files by mapped drive letter is not needing to rename all files when changing the file server's network address.

### Operating System

Windows 11

### DeepLabCut version

dlc version 2.3.9

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

1. Map a network location in Windows by assigning it to a drive letter, for example `//192.168.0.145` mapped to `Z:\`
2. Click "add new videos" on the GUI. The drive is not shown on the left side menu together with the local drives.
3. Try going to the address bar of the file selection window and type `Z:\`. An error that the drive doesn't exist appears.
4. If the YAML file is saved in the mapped drive, the project_path is automatically converted from `Z:\` to `//192.168.0.145`

The error happens in all file selection windows (open project, add videos, label frames, etc...).

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by nexflatline** [comment]
I just found another related problem with the file selection window that was also not in previous versions:

MKV video files cannot be viewed or selected in the GUI, although the files are correctly processed if using command line instead.

**Comment by n-poulsen** [comment]
@nexflatline thanks for reporting this! I'm looking into it
