### ISSUE TITLE
Error in model performance labeled DLC videos

### ISSUE THREAD

**Issue by khadija-ch** [DeepLabCut/DeepLabCut#2568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I am using DLC for the the tracking of human finger movements and I trained the model on the videos of my data set so I obtained the csv file for each video and its labeled video created but I noticed some bugs in the video where the labels are missing on some fingers when moving. I expected seeing the full skeleton in a precise way on all the fingers. Here are some screenshots: (You can see where the skeleton misses the finger movement)
I am wondering what could be the problem and how can I fix this issue if someone could help please?

### Operating System

Windows system opening deeplabcut environment and usin python scripts 

### DeepLabCut version

dlc version 2.3.8

### DeepLabCut mode

single animal

### Device type

gpu

### Anything else?

![Capture d’écran (48)](https://github.com/DeepLabCut/DeepLabCut/assets/152179681/944ab6e4-a171-47be-9f3e-274f1d3e633e)
![Capture d’écran (49)](https://github.com/DeepLabCut/DeepLabCut/assets/152179681/a628f00f-136e-46aa-a014-e6c49deb14a8)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
The videos display points above a pcutoff threshold; you need to set this in the function, see the docs here: https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html#l-create-labeled-videos
