### ISSUE TITLE
PiCamera (Raspberry Pi videos) .h264 video support in opencv

### ISSUE THREAD

**Issue by AmandineCornil** [DeepLabCut/DeepLabCut#257]
**Your Operating system and DeepLabCut version**
Ubuntu 18.04 LTS, Anaconda Env, DeepLabCut 2

**Describe the problem**
Dear all. 
This project is amazing. I'm working with mice and tested DeepLabCut on Ethovision (Noldus) tracking videos (.mp4) and it works perfectly. But, because I prefer working with open-source, I'm also working with a Raspberry Pi and the PiCamera v2. Videos are saved in .h264 and I cannot change that. I would like to use DeepLabCut with these videos but it seems that DeepLabCut doesn't like this format. There is a problem in frame_extraction.py. Metadata are not well extracted (framerate, number of frames, duration). Have you ever seen this problem? 

If I convert these .h264 videos with MP4Box (.mp4), DeepLabCut works. But I don't really like the idea of conversion.

I know that OpenCv is able to deal with .h264 because I made a script to do mice paws tracking and it works.

Thanks a lot,
Best,
Amandine Cornil

**Comment by MMathisLab** [comment]
Thanks for the kind words - always nice to hear from users :). So, I’m the frame extraction step does use openCV (if you are using the latest 2.0.5.1), and there is a flag to set: opencv=True (false uses moviepy). Check out the function here (or in the terminal check the docs by deeplabcut.extract_frames? https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/generate_training_dataset/frame_extraction.py

**Comment by AmandineCornil** [comment]
Dear. Thanks a lot for your quick answer ! I add the flag to opencv=True but the error occurs before. You can see below the process (with the error) --> I add some print for fps, duration & nframes in the frame_extraction.py and you can see that the values are super strange (the real fps is 20 and not 25):

In [3]: deeplabcut.extract_frames(config_path,"automatic","uniform", userfeedbac
   ...: k=True, crop=True, opencv=True
   ...: )
/home/amandine/anaconda3/envs/Tracking/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/frame_extraction.py:100: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg = yaml.load(ymlfile)
Config file read successfully.
Do you want to extract (perhaps additional) frames for video: /home/amandine/Bureau/TestRaspTracking/Test1.h264 ?
yes/noyes
**fps 25.0
nframes -192153584101141
duration -7686143364045.64**
/home/amandine/anaconda3/envs/Tracking/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/frame_extraction.py:145: RuntimeWarning: invalid value encountered in log10
  indexlength = int(np.ceil(np.log10(nframes)))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-ff8694e32821> in <module>()
----> 1 deeplabcut.extract_frames(config_path,"automatic","uniform", userfeedback=True, crop=True, opencv=True
      2 )

/home/amandine/anaconda3/envs/Tracking/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/frame_extraction.py in extract_frames(config, mode, algo, crop, userfeedback, cluster_step, cluster_resizewidth, cluster_color, opencv)
    143                     duration=clip.duration
    144                     nframes=int(np.ceil(clip.duration*1./fps))
--> 145                 indexlength = int(np.ceil(np.log10(nframes)))
    146                 if crop==True:
    147                     if opencv:

ValueError: cannot convert float NaN to integer

**Comment by MMathisLab** [comment]
Hmm, seems an opencv loading issue then. maybe post to opencv/search there is .h264 is usable (I know the compression codec is, but store videos as .mp4 with the h264 codec, not named .h264 :/ or, you can just add a line of code to convert file to .mp4 as before/as it loads?

**Comment by AmandineCornil** [comment]
I don't have the choice with the Raspberry Pi, it's .h264. And it's working with opencv with my scripts, it's why I don't understand why there is a problem here. I also tried to run my scripts with the same env and it works, so it's not a possible version problem. But don't worry, when I will have more time I can go deeper in your script to dissect the problem.
Best !

**Comment by MMathisLab** [comment]
Thanks (sorry I don't have more time now). If you want to post the code you use to load the video so I can compare though, that would be great. I will "close" the issue for now, but please keep us updated on this thread :).

**Comment by AlexEMG** [comment]
Seems like opencv cannot deal with your video? You could try (to use moviepy): deeplabcut.extract_frames(config_path,"automatic","uniform", userfeedback=True, crop=True, opencv=False)

or convert them?
or make sure you have the right codec for your video in opencv?
