### ISSUE TITLE
Can not remove extraneous output and logging goes to root logger

### ISSUE THREAD

**Issue by pedson** [DeepLabCut/DeepLabCut#2577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

There does not appear to be any way to turn off messages such as `Loading DLC 2.3.9...` and `DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)` in the console output, e.g., they are not done through logging.

What messages are done through logging appear to be done through the root logger, e.g. `INFO:root:Config:<displays DLC config...>` which means they cannot be turned off w/o changing the root log level.  This can affect other modules.

There does not appear to be a way to fully manage console output and logging for the module.

### Operating System

All

### DeepLabCut version

2.3.9

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

Use DLC

### Relevant log output

```shell
Loading DLC 2.3.9...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
INFO:root:Config:
{'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]],
 'all_joints_names': [<redacted>],
 'batch_size': 1,
 'crop_pad': 0,
 'dataset': '<redacted>',
 'dataset_type': 'imgaug',
 'deterministic': False,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': '<redacted>',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 1.0,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'mean_pixel': [123.68, 116.779, 103.939],
 'mirror': False,
 'net_type': 'resnet_50',
 'num_joints': 10,
 'optimizer': 'sgd',
 'pairwise_huber_loss': True,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'regularize': False,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': '<redacted>',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Hi @pedson that is true; we don't plan on changing this, but if you can make a case of it and consider contributing, please do!
