### ISSUE TITLE
Multilanguage support on user input is inconsistent

### ISSUE THREAD

**Issue by CBroz1** [DeepLabCut/DeepLabCut#2578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

`extract_frames`, `convertcsv2h5`, `extract_outlier_frames`, `returnlabelingdata` and `create_training_dataset` each have an implementation of what is considered a 'yes' or 'no' response. 

Within `extract_frames`, I might use `oui` [here](https://github.com/DeepLabCut/DeepLabCut/blob/main/deeplabcut/generate_training_dataset/frame_extraction.py#L313-L318) but be unable to use it [here](https://github.com/DeepLabCut/DeepLabCut/blob/main/deeplabcut/generate_training_dataset/frame_extraction.py#L344-L347).

### Operating System

n/a

### DeepLabCut version

2.3.9

### DeepLabCut mode

single animal

### Device type

n/a

### Steps To Reproduce

1. Run `extract_frames` in `automatic` mode with `userfeedback=True` for a video with previously extracted frames
2. When prompted to extract frames, input `oui`
3. When prompted regrading an existing directory, input `oui`
4. System exits, as `oui` is not in the set of yes responses

### Relevant log output

```shell
n/a
```

### Anything else?

These prompts could be standardized by centralizing lists of yes and no responses.

```python
YES_RESPONSES = ['y', 'yes', 'ja', ...]

if askuser.lower() in YES_RESPONSES:
    pass
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
hi @CBroz1 indeed we had a little fun at some point :D but we only plan to support "Yes/No" going forward 🤗
