### ISSUE TITLE
Bug: FileNotFoundError when training network from script in DLC 2.3.9

### ISSUE THREAD

**Issue by snawarhussain** [DeepLabCut/DeepLabCut#2579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

**Description**
When using DeepLabCut version 2.3.9, training the network via a Python script results in a `FileNotFoundError`. This issue does not occur when training is initiated through the GUI.

### Operating System

operating system
Bug can be reproduced  in Linux, WSL, and windows 

### DeepLabCut version

2.3.9

### DeepLabCut mode

single animal

### Device type

gpu/cpu  (both)

### Steps To Reproduce

**Steps to Reproduce**
1. Label frames using the GUI.
2. Create a simple Python script as follows:
    ```python
    import deeplabcut as dlc

    dlc.create_training_dataset('config.yaml')
    dlc.train_network('config.yaml')
    ```
3. Run the script.

### Relevant log output

```shell
The following error is encountered:
File "C:\Users\user\AppData\Local\anaconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_tensorflow\config.py", line 49, in cfg_from_file
with open(filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'dlc-models\iteration-0\BioFace_face_trackingMay15-trainset95shuffle1\train\pose_cfg.yaml'
```

### Anything else?

**Temporary Fix**
Commenting out the following [lines](https://github.com/DeepLabCut/DeepLabCut/blob/fbaf36aee285564f18f78384bb94cc20c116297c/deeplabcut/pose_estimation_tensorflow/core/train.py#L157C1-L159C8) in the source code allows the training to proceed:
```python
# Comment out these lines
# os.chdir(
#     str(Path(config_yaml).parents[0])
# )  # switch to folder of config_yaml (for logging)
```
Since the directory is changed before loading the config file, this results in the aforementioned error.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @snawarhussain! Try putting the full path to the project configuration file in your script:

```python
import deeplabcut as dlc

config_path = r"C:\Users\my-name\path\to\project\config.yaml"
dlc.create_training_dataset(config_path)
dlc.train_network(config_path)
```

Let me know if that fixes your issue!

**Comment by snawarhussain** [comment]
Hi, thank you for the response. that did the trick for me. I was adding the full project path but **in the config file**.
Seems like I have to provide the full path **to the config file** as an argument ---while creating the training dataset, calling in the train function, etc. --- every single time
