### ISSUE TITLE
How similar should the videos be?

### ISSUE THREAD

**Issue by Gaelic98** [DeepLabCut/DeepLabCut#258]
Hi,

I have a query regarding the use of videos for training. How similar should the videos in question be?

For example in the demos, multiple videos of mice reaching are used. These are quite similar. However, if I wanted to look at different species of lizard videos (geckos, iguanas, komodo dragons e.t.c) for example, would it be wise to use the same overarching project for all the videos or should I use a project for each distinct video?

Many Thanks.

**Comment by MMathisLab** [comment]
Hi there, for general questions we ask you use the image forum: https://forum.image.sc/tags/deeplabcut

**Comment by MMathisLab** [comment]
(If they look highly different, the background is very different, and you will track different parts, I would make separate networks) I would still ask the forum as other users will chip in too

**Comment by Gaelic98** [comment]
Thanks for the response.
