### ISSUE TITLE
SuperAnimal models with EfficientNet

### ISSUE THREAD

**Issue by vonaviv** [DeepLabCut/DeepLabCut#2580]
Hello DLC-Contributors,

First of all, many thanks for the great tool!

Is there any plans for the SuperAnimal model based on EfficientNet (b0)? I would be specifically interested in the SuperAnimal-Quadruped model.  I have quite a performance sensitive situation, where even a 10% gain in inference speed would result in a major amount of saved computational hours. I have relatively big frames (1280x1024px), 100fps recordings from 18 cameras with duration of 1-2.5h. I have tried the ResNet-50 version of SuperAnimal-Quadruped model with transfer-learning and it performs great in my case! It basically allows to skip massive annotation efforts given multiple viewing angles, a huge variability in animal sizes due to distances to cameras, and individual differences. 
It would be amazing if the power of transfer-learning would be unlocked for EfficientNet (b0) out-of-the-box too!

Best, 
Vladyslav

**Comment by MMathisLab** [comment]
Hi Vladyslav, unfortunately no we don't plan to re-train for EfficientNet, but will have the top-down version with HRNet coming out in pytorch soon, so stay tuned!
