### ISSUE TITLE
Matlplotlib after installed by CONDA missing matplotlib.cm.cmap

### ISSUE THREAD

**Issue by chz31** [DeepLabCut/DeepLabCut#2581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi, I am trying the [demo ](https://colab.research.google.com/github/DeepLabCut/DeepLabCut/blob/master/examples/COLAB/COLAB_DEMO_mouse_openfield.ipynb#scrollTo=RiDwIVf5-3H_). I used conda to install DeepLabCut.

However, I got this error of not finding `cmap `in `matplotlib` when I finished training and ran the evaluation  `deeplabcut.evaluate_network(path_config_file,plotting=True)`:

```
Results for 10000  training iterations: 95 1 train error: 4.09 pixels. Test error: 5.71  pixels.
With pcutoff of 0.4  train error: 4.09 pixels. Test error: 5.71 pixels
Thereby, the errors are given by the average distances between the labels by DLC and the scorer.
Plotting...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chz31/DeepLabCut/deeplabcut/pose_estimation_tensorflow/core/evaluate.py", line 1019, in evaluate_network
    Plotting(
  File "/home/chz31/DeepLabCut/deeplabcut/pose_estimation_tensorflow/core/evaluate.py", line 201, in Plotting
    colors = visualization.get_cmap(len(comparisonbodyparts), name=cfg["colormap"])
  File "/home/chz31/DeepLabCut/deeplabcut/utils/visualization.py", line 36, in get_cmap
    return plt.cm.get_cmap(name, n)
AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap'
```
After activating `conda activate DEEPLABCUT`, the Python used is 3.9. 19 in the conda environment. In the base environment, matplotlib.cm.cmap still exists with Python 3.11 but the method appeared to be deprecated.

Tensorflow 2.10 also could not find CUDA. The CUDA installed in my machine is 11.8, which appears to not be compatible with Tensorflow, but I think it's not relevant to this issue.

### Operating System

WSL2 (Ubuntu) under Windows 11

### DeepLabCut version

dlc version 2.3.9

### DeepLabCut mode

single animal

### Device type

gpu NVIDIA Geforce GTX 1070 Max Q
nvidia-smi returns NVIDIA-SMI 550.76.01              Driver Version: 552.22         CUDA Version: 11.8

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by elahehbastani** [comment]
I am getting the same error when evaluating using Colab

**Comment by chz31** [comment]
> I am getting the same error when evaluating using Colab

Thanks for confirming it. The Docker version works fine. I think the Docker version is also older.

**Comment by n-poulsen** [comment]
@chz31 Thanks for spotting this! It indeed looks like an issue with the latest `matplotlib` release. I was able to fix the issue in COLAB by running `!pip install "matplotlib<3.9"` in a cell before importing anything (and make sure you restart the runtime!).

I'll ensure the `matplotlib` version is pinned for DeepLabCut so this manual fix doesn't need to be made anymore.

**Comment by chz31** [comment]
> @chz31 Thanks for spotting this! It indeed looks like an issue with the latest `matplotlib` release. I was able to fix the issue in COLAB by running `!pip install "matplotlib<3.9"` in a cell before importing anything (and make sure you restart the runtime!).
> 
> I'll ensure the `matplotlib` version is pinned for DeepLabCut so this manual fix doesn't need to be made anymore.

Thanks! `!pip install "matplotlib<3.9` also works in conda deeplabcut envrionment for testscript.py, so I think it fixed this problem at this moment!

**Comment by elahehbastani** [comment]
> @chz31 Thanks for spotting this! It indeed looks like an issue with the latest `matplotlib` release. I was able to fix the issue in COLAB by running `!pip install "matplotlib<3.9"` in a cell before importing anything (and make sure you restart the runtime!).
> 
> I'll ensure the `matplotlib` version is pinned for DeepLabCut so this manual fix doesn't need to be made anymore.

Thank You! I used it at Colab too and all good.

**Comment by jennymed33** [comment]
> @chz31 Thanks for spotting this! It indeed looks like an issue with the latest `matplotlib` release. I was able to fix the issue in COLAB by running `!pip install "matplotlib<3.9"` in a cell before importing anything (and make sure you restart the runtime!).
> 
> I'll ensure the `matplotlib` version is pinned for DeepLabCut so this manual fix doesn't need to be made anymore.

Thank you so much! It seems to be a update recently and the problem is solved!

**Comment by Astercan** [comment]
Hi, 
I have been facing this same problem but cannot fix it. I have zero coding knowledge / experience, but have installed (as far as I know) either version 3.7.3 or 3.5.2 of matplotlib following instructions from here: 
[https://forum.image.sc/t/attributeerror-of-testscript-module-matplotlib-cm-has-no-attribute-get-cmap/96444/4]
but nothing has worked (I keep getting "AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap'"). Installing version 3.9 of matplotlib did not work either. 

I am running deep lab cut on an iMac; and everything seems to go fine until I click on "analyze videos". 
By the way, not sure if this matters in any way, but I run deeplabcut by going to Anaconda-Navigator, then on "deeplabcut_M1" I go to "open terminal" and I run the GUI from there. To install the different versions of matplotlib I open a "normal" terminal and run pip install matplotlib==3.5.2 (or 3.7.2, or python -m pip install matplotlib --upgrade for 3.9)
Every time I change the version of matplotlib I close everything and restart deeplabcut, but still not working
Any ideas of how I may be able to solve this? 

Thanks!

**Comment by n-poulsen** [comment]
@Astercan you need to run `pip install "matplotlib<3.9.0"` from the `deeplabcut_M1` conda environment. You can do this by running it in the terminal opened from the Anaconda Navigator, or opening a "normal" terminal and running:

```bash
conda activate deeplabcut_M1
pip install "matplotlib<3.9.0"
```

**Comment by MikuChenOwO** [comment]
@n-poulsen Thanks! My problem occurred when i tried to draw a wordcloud pic using JupyterNotebook, and my version of matplotlib was 3.9.0,after degrading to the version of 3.8.4,my code is well fixed now.

**Comment by Astercan** [comment]
@n-poulsen Thank you!

**Comment by Mijar007** [comment]
Thank you. In my case the error appeared during the "Extract outlier frames" step in the GUI.
Downgrading matplotlib solved it.
