### ISSUE TITLE
DeepLabCut extract frames GUI feature

### ISSUE THREAD

**Issue by Timokleia** [DeepLabCut/DeepLabCut#2584]
**Is your feature request related to a problem? Please describe.**
Improving the frame extraction interface in the GUI and make it more user friendly. 

**Describe the solution you'd like**
When the user wants to extract frames manually it is necessary to select a video. Currently the video selection has the title: Optional frame extraction from a video subset. While this title is informative is not linked to the manual extraction. 
For example: Frame Extraction from a Video Subset (Mandatory Step for Manual Extraction)

In edition when the user tries to extract frames manually without choosing a video first there is an error that is not clear
'Traceback (most recent call last):
  File "/Users/tomdeadman/miniforge3/envs/DEEPLABCUT_M1/lib/python3.9/site-packages/deeplabcut/gui/tabs/extract_frames.py", line 197, in extract_frames
    _ = launch_napari(list(self.video_selection_widget.files)[0])
IndexError: list index out of range'

We could add some information. An example:
No video file selected. Please upload a video to proceed with manual frame extraction.

**Comment by Timokleia** [comment]
@n-poulsen I added a brief description and solutions in this feature request 💪

**Comment by jeylau** [comment]
Good catch @Timokleia, I'll push a fix!
