### ISSUE TITLE
Pin Keras 2

### ISSUE THREAD

**Issue by CBroz1** [DeepLabCut/DeepLabCut#2585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

After installing DLC in my gh-actions, I try to import some helper functions

```python
from deeplabcut.utils.auxiliaryfunctions import read_config, write_config
```

I then hit the following error stack also reported [here](https://forum.image.sc/t/batchnormalization-is-not-available-with-keras-3/94374/3)

<details><summary>Error stack</summary>

```text
| Loading DLC 2.3.9...
| DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
| ImportError while loading conftest '/home/cb/wrk/spyglass/tests/conftest.py'.
| tests/conftest.py:21: in <module>
|     from deeplabcut.utils.auxiliaryfunctions import read_config, write_config
| 3/envs/spyglass/lib/python3.9/site-packages/deeplabcut/__init__.py:37: in <module>
|     from deeplabcut.create_project import (
| 3/envs/spyglass/lib/python3.9/site-packages/deeplabcut/create_project/__init__.py:12: in <module>
|     from deeplabcut.create_project.demo_data import load_demo_data
| 3/envs/spyglass/lib/python3.9/site-packages/deeplabcut/create_project/demo_data.py:16: in <module>
|     from deeplabcut.utils import auxiliaryfunctions
| 3/envs/spyglass/lib/python3.9/site-packages/deeplabcut/utils/__init__.py:11: in <module>
|     from deeplabcut.utils.auxfun_multianimal import *
| 3/envs/spyglass/lib/python3.9/site-packages/deeplabcut/utils/auxfun_multianimal.py:34: in <module>
|     from deeplabcut.utils import auxiliaryfunctions, conversioncode
| 3/envs/spyglass/lib/python3.9/site-packages/deeplabcut/utils/auxiliaryfunctions.py:31: in <module>
|     from deeplabcut.pose_estimation_tensorflow.lib.trackingutils import TRACK_METHODS
| 3/envs/spyglass/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/__init__.py:20: in <module>
|     from deeplabcut.pose_estimation_tensorflow.core.train import *
| 3/envs/spyglass/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/core/train.py:32: in <module>
|     from deeplabcut.pose_estimation_tensorflow.nnets import PoseNetFactory
| 3/envs/spyglass/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/nnets/__init__.py:13: in <module>
|     from .efficientnet import PoseEfficientNet
| 3/envs/spyglass/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/nnets/efficientnet.py:20: in <module>
|     import deeplabcut.pose_estimation_tensorflow.backbones.efficientnet_builder as eff
| 3/envs/spyglass/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/backbones/efficientnet_builder.py:21: in <module>
|     import deeplabcut.pose_estimation_tensorflow.backbones.efficientnet_model as efficientnet_model
| 3/envs/spyglass/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/backbones/efficientnet_model.py:26: in <module>
|     import deeplabcut.pose_estimation_tensorflow.nnets.utils as utils
| 3/envs/spyglass/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/nnets/utils.py:164: in <module>
|     class TpuBatchNormalization(tf.compat.v1.layers.BatchNormalization):
| 3/envs/spyglass/lib/python3.9/site-packages/tensorflow/python/util/lazy_loader.py:207: in __getattr__
|     raise AttributeError(
| E   AttributeError: `BatchNormalization` is not available with Keras 3.
```

</details>

Related to restructuring of Keras in version 3. DLC may want to pin Keras 2 in `requirements.txt`

### Operating System

ubuntu-latest

### DeepLabCut version

dlc version

### DeepLabCut mode

single animal

### Device type

n/a

### Steps To Reproduce

1. On ubuntu
2. bash: `pip install deeplabcut==2.3.9` - by default, keras 3.3 is installed
3. `from deeplabcut.utils.auxiliaryfunctions import read_config`

### Relevant log output

```shell
see error stack above
```

### Anything else?

I found [this](https://deeplabcut.github.io/DeepLabCut/docs/recipes/installTips.html) as the only mention of keras in the docs when searching. It is possible that one of the [conda dependencies](https://github.com/DeepLabCut/DeepLabCut/blob/main/conda-environments/DEEPLABCUT.yaml) is being relied on to pin Keras, but pinning in [requirements](https://github.com/DeepLabCut/DeepLabCut/blob/main/requirements.txt) would help out those of us using DLC as a dependency. 

Thanks!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @CBroz1! How do you install `tensorflow` on your system?

Running `pip install deeplabcut` shouldn't install `tensorflow` - that can be done on Ubuntu with `pip install deeplabcut[tf]`, which pins `tensorflow<=2.10` (the last supported TF version on Windows Native) and should install `keras<=2.12.0`.

DeepLabCut is not compatible with `tensorflow>2.12`.

**Comment by CBroz1** [comment]
Right! Thanks for the help. Using the `[tf]` extras-install inherited the keras pin from the appropriate tensorflow pin. I'll use that
