### ISSUE TITLE
how to crop a video for analysis

### ISSUE THREAD

**Issue by StHeindl** [DeepLabCut/DeepLabCut#259]
**Your Operating system and DeepLabCut version**

Ubuntu 14.04 LTS (pre-installed on a cluster) , DLC 2.0.5 (latest version) 

**Describe the problem**

I have videos from the behaviour test called "cylinder test" (see screenshot below) and would like to try the analysis with Deeplabcut. The question is, what is the best way to analyse a video containing 6 (2 mice, 3 sights per mouse) fields of view and how can the data be combined afterwards? 
I would really appreciate it, if someone had a suggestion for me. I did a trial once with loading the whole video as input, but with cropping coordinates. The cropping worked for the labelling, but the training and analysis was done on the whole video. Would it be better to crop the video before giving it as input to Deeplabcut? 
Thank you!

**Screenshots**
<img width="1908" alt="image" src="https://user-images.githubusercontent.com/49393203/55712379-e9233d00-59ee-11e9-9087-04f8f0452b13.png">

**Additional context**

**Comment by MMathisLab** [comment]
To crop videos for analysis, you just need to add the cropping values to the config.yaml file and set cropping to true. See: https://github.com/AlexEMG/DeepLabCut/blob/3b10ea5bbb4cdba6ee6c0cc2481f4058f71fe5da/examples/openfield-Pranav-2018-10-30/config.yaml#L37

For all the parameters, please see [Box 1](https://camo.githubusercontent.com/9cbe71d962bc6eb4ceb3bdf788fed6bdb86229ac/68747470733a2f2f737461746963312e73717561726573706163652e636f6d2f7374617469632f3537663664353163396637343536366635356563663237312f742f3563343066343132346437613963306232636536353163312f313534373736303731363239382f426f78312d30312e706e673f666f726d61743d3130303077).

**Comment by AlexEMG** [comment]
Cropping is useful for speed reasons (see https://www.biorxiv.org/content/early/2018/10/30/457242.full.pdf). However, then you want to crop similarly in the future. 

In your case, I would perhaps create different labels per body part (i.e. leftear_leftmirror, left_ear_middle, etc.) and then from the 2D predictions you can recreate the 3D predictions (through some calibration step). However, you can probably also just use the multiple 2D predictions corresponding to one body-part of the mouse for subsequent analysis without fusing.

**Comment by StHeindl** [comment]
Thank you very much! I will try these settings. 
I am just wondering, if the training and analysis becomes very slow when there are so many labels. 
Or would it be more useful to analyze every mirror individually?





On 10. Apr 2019, at 17:45, Alexander Mathis <notifications@github.com> wrote:


Cropping is useful for speed reasons (see 
https://www.biorxiv.org/content/early/2018/10/30/457242.full.pdf). However, then you want to crop similarly in the future.
In your case, I would perhaps create different labels per body part (i.e. leftear_leftmirror, left_ear_middle, etc.) and then from the 2D predictions you can recreate the 3D predictions (through some calibration step). However, you can probably
 also just use the multiple 2D predictions corresponding to one body-part of the mouse for subsequent analysis without fusing.
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

**Comment by AlexEMG** [comment]
The analysis speed only mildly attenuated with # body parts (if at all). The robustness of pose estimation, however, is much higher with more bodyparts.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by AmandineCornil** [comment]
Dear all,

Is it a way to crop videos for analysis with different x1,x2,y1,y2 values for each video (like in the training)? 
For the moment I plan to use a loop to update the config.yalm for each video but it's maybe not the faster way to do.

Best,
Amandine
