### ISSUE TITLE
Update the YAML file for Apple Silicon (M1, M2, M3) Macs, new working environment file below.

### ISSUE THREAD

**Issue by slagathor69** [DeepLabCut/DeepLabCut#2590]
**Is your feature request related to a problem? Please describe.**
The current yaml file does not correctly install on Apple Silicon Macs using anaconda. There are pandas, tables, tensorflow, and other errors when trying to run.

**Describe the solution you'd like**
I have created an updated yaml file that works on Apple Silicon Macs that I recommend to be added to installation instructions with the added bonus of working with Python 3.10.

**Describe alternatives you've considered**
I tried original way and after a lot of troubleshooting was able to create a functional, simpler yaml environment file for installing DeepLabCut seamlessly on Apple Silicon Macs (I have not tested it however on any Intel Macs).

**Additional context**
Updated YAML File below:

```
name: deeplabcut
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipython
  - jupyter
  - python.app
  - ffmpeg
  - pytables
  - pandas
  - pip:
    - tensorflow
    - tensorflow-macos==2.9.0
    - tensorflow-metal==0.5.0
    - "deeplabcut[gui,apple_mchips]"
    - deeplabcut==2.3.9
```

**Comment by MMathisLab** [comment]
thanks! Also note this month we are switching to pytorch, making this pain all go away!

**Comment by MMathisLab** [comment]
I made a PR here, if you can check it @slagathor69 https://github.com/DeepLabCut/DeepLabCut/pull/2595

**Comment by fffllllxxxxxxxx** [comment]
I kept failing to install it on my M3 Pro macbook
i tried this .YAML, but i got error again.
NEED SOME HELP.

<img width="1497" alt="image" src="https://github.com/user-attachments/assets/b9b4a975-4af3-4b4e-9e4e-6dfe0ccb72a1">

**Comment by Scientific1** [comment]
updated everything just 'slightly' and now it should work (because of different dependencies) on apple m4pro chips. Hope it helps someone:

name: deeplabcut
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipython
  - jupyter
  - python.app
  - ffmpeg
  - pytables
  - pandas
  - pip:
     - tensorflow-macos==2.12.0
     - tensorflow-metal
     - deeplabcut[apple-mchips,gui]==2.3.9

**Comment by Scientific1** [comment]
find the updated .yaml file for m4pro chips on apple machines. 

`
name: deeplabcut
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipython
  - jupyter
  - python.app
  - ffmpeg
  - pytables
  - pandas
  - pip:
     - tensorflow-macos==2.12.0
     - tensorflow-metal
     - deeplabcut[apple-mchips,gui]==2.3.9`

**Comment by Scientific1** [comment]
updated .yaml file for apple m4pro users. Works now because of altered dependencies tensor flow-issues. 

```
name: deeplabcut
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipython
  - jupyter
  - python.app
  - ffmpeg
  - pytables
  - pandas
  - pip:
     - tensorflow-macos==2.12.0
     - tensorflow-metal
     - deeplabcut[apple-mchips,gui]==2.3.9
    
```
