### ISSUE TITLE
Increasign Error After relabelling and retrain network

### ISSUE THREAD

**Issue by DanieleRomeo** [DeepLabCut/DeepLabCut#2598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello,

I am working with videos where 2 fish interact in the same tank. I created a multi-animal project with 2 individuals (in this case a cleaner and a client, the two fish I have in the video) with 8 body parts.
I worked on 4 videos, extracting and labelling 60 frames per videos (Videos are 10 minutes, 1920x1080, 30fps).
I trained the model (500k iteration, batch size 1, and I got a train error (px) of 4.01, and a test error of 6.04.
Therefore, I analyzed other two videos, and extracted the outliers with “uncertain” parameter. I relabelled the outlier frames (saving the machinelabels-iter.h5 file and then working directly on CollectedData.5 and saving only the CollectedData.5 file.
After that, I merged the dataset and recreated a training dataset and I retrain the model, putting as init_weight the last snapshot of the last model, and retraining for 300k batch size 1.
After that, the trainerror increased at 4.36 and the test error at 8.1.

Could anyone explain me what I am doing wrong please? I am attaching the pse_cgf.yaml file for the two networks.
Thank you so much for your time and for your help!

### Operating System

Ubuntu 20.04

### DeepLabCut version

dlc version 2.3.9

### DeepLabCut mode

multi animal

### Device type

gpu Quadro P620

### Anything else?

pose_cfg first network
all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
all_joints_names:
- HeadTerminalMouth
- HeadBasisUp
- HeadBasisDown
- TailBottomCorner
- TailUpperCorner
- TailJunctionBody
- BodyMidUp
- BodyMidDown
alpha_r: 0.02
apply_prob: 0.5
batch_size: 1
contrast:
  clahe: true
  claheratio: 0.1
  histeq: true
  histeqratio: 0.1
convolution:
  edge: false
  emboss:
    alpha:
    - 0.0
    - 1.0
    strength:
    - 0.5
    - 1.5
  embossratio: 0.1
  sharpen: false
  sharpenratio: 0.3
crop_sampling: hybrid
crop_size:
- 400
- 400
cropratio: 0.4
dataset: training-datasets/iteration-0/UnaugmentedDataSet_Dimidiatus_10MinMay13/Dimidiatus_10Min_Daniele95shuffle1.pickle
dataset_type: multi-animal-imgaug
decay_steps: 30000
display_iters: 500
global_scale: 0.8
init_weights: /home/fishlab4/anaconda3/envs/DEEPLABCUTAUD/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
max_shift: 0.4
metadataset: training-datasets/iteration-0/UnaugmentedDataSet_Dimidiatus_10MinMay13/Documentation_data-Dimidiatus_10Min_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.0001
  - 7500
- - 5.0e-05
  - 12000
- - 1.0e-05
  - 500000
net_type: resnet_50
num_idchannel: 2
num_joints: 8
num_limbs: 28
optimizer: adam
pafwidth: 20
pairwise_huber_loss: false
pairwise_loss_weight: 0.1
pairwise_predict: false
partaffinityfield_graph:
- - 0
  - 1
- - 0
  - 2
- - 0
  - 3
- - 0
  - 4
- - 0
  - 5
- - 0
  - 6
- - 0
  - 7
- - 1
  - 2
- - 1
  - 3
- - 1
  - 4
- - 1
  - 5
- - 1
  - 6
- - 1
  - 7
- - 2
  - 3
- - 2
  - 4
- - 2
  - 5
- - 2
  - 6
- - 2
  - 7
- - 3
  - 4
- - 3
  - 5
- - 3
  - 6
- - 3
  - 7
- - 4
  - 5
- - 4
  - 6
- - 4
  - 7
- - 5
  - 6
- - 5
  - 7
- - 6
  - 7
partaffinityfield_predict: true
pos_dist_thresh: 17
pre_resize: []
project_path: /home/fishlab4/Desktop/Dimidiatus_10Min
rotation: 25
rotratio: 0.4
save_iters: 10000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
weigh_only_present_joints: false

pose_cfg_retrain network

all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
all_joints_names:
- HeadTerminalMouth
- HeadBasisUp
- HeadBasisDown
- TailBottomCorner
- TailUpperCorner
- TailJunctionBody
- BodyMidUp
- BodyMidDown
alpha_r: 0.02
apply_prob: 0.5
batch_size: 1
contrast:
  clahe: true
  claheratio: 0.1
  histeq: true
  histeqratio: 0.1
convolution:
  edge: false
  emboss:
    alpha:
    - 0.0
    - 1.0
    strength:
    - 0.5
    - 1.5
  embossratio: 0.1
  sharpen: false
  sharpenratio: 0.3
crop_sampling: hybrid
crop_size:
- 400
- 400
cropratio: 0.4
dataset: training-datasets/iteration-1/UnaugmentedDataSet_Dimidiatus_10MinMay13/Dimidiatus_10Min_Daniele95shuffle1.pickle
dataset_type: multi-animal-imgaug
decay_steps: 30000
display_iters: 500
global_scale: 0.8
init_weights: /home/fishlab4/Desktop/Dimidiatus_10Min/dlc-models/iteration-0/Dimidiatus_10MinMay13-trainset95shuffle1/train/snapshot-500000
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
max_shift: 0.4
metadataset: training-datasets/iteration-1/UnaugmentedDataSet_Dimidiatus_10MinMay13/Documentation_data-Dimidiatus_10Min_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.0001
  - 7500
- - 5.0e-05
  - 12000
- - 1.0e-05
  - 300000
net_type: resnet_50
num_idchannel: 2
num_joints: 8
num_limbs: 28
optimizer: adam
pafwidth: 20
pairwise_huber_loss: false
pairwise_loss_weight: 0.1
pairwise_predict: false
partaffinityfield_graph:
- - 0
  - 1
- - 0
  - 2
- - 0
  - 3
- - 0
  - 4
- - 0
  - 5
- - 0
  - 6
- - 0
  - 7
- - 1
  - 2
- - 1
  - 3
- - 1
  - 4
- - 1
  - 5
- - 1
  - 6
- - 1
  - 7
- - 2
  - 3
- - 2
  - 4
- - 2
  - 5
- - 2
  - 6
- - 2
  - 7
- - 3
  - 4
- - 3
  - 5
- - 3
  - 6
- - 3
  - 7
- - 4
  - 5
- - 4
  - 6
- - 4
  - 7
- - 5
  - 6
- - 5
  - 7
- - 6
  - 7
partaffinityfield_predict: true
pos_dist_thresh: 17
pre_resize: []
project_path: /home/fishlab4/Desktop/Dimidiatus_10Min
rotation: 25
rotratio: 0.4
save_iters: 10000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
weigh_only_present_joints: false

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Hi @DanieleRomeo this is more of a user question than a bug report, so I'd ask you use Image Forum in the future please! 

In short, the RMSE is not that different, and your data is more diverse; the more diverse the data the error can go up as you are not over-fitting to one scenario. We also have a lot of material (YouTube, DLC-Tutorials, etc) and docs to explain there are several ways to merge and retrain; you can load the old weights, you can start with new weights, etc. so it's completely user defined and these choices affect performance. Hope that helps!

**Comment by DanieleRomeo** [comment]
Okay sorry, will do it!

Thank you so much for your time and your help!

**Comment by MMathisLab** [comment]
Not a worry
