### ISSUE TITLE
IndexError running "Step1_EvaluateModelonDataset.py" (Run training until at least 1 snapshot is stored before proceeding to "Step1_EvaluateModelonDataset.py")

### ISSUE THREAD

**Issue by cathy-liu23** [DeepLabCut/DeepLabCut#26]
The error produced is:
"  File "/data/home/jli819/deeplabcut/DeepLabCut/Evaluation-Tools/Step1_EvaluateModelonDataset.py", line 68, in <module>
    cfg['init_weights'] = os.path.join(modelfolder,'train',Snapshots[snapIndex])
IndexError: index -1 is out of bounds for axis 0 with size 0"

We saw the other issue with an IndexError running the same file, but their solution did not fix our problem.

Did anyone else also run into this error? If so, what is a possible fix? Error occurred on Red Hat Enterprise Linux Server release 7.5 (Maipo). 

Thanks!!

**Comment by MMathisLab** [comment]
Can you double check that you saved snapshot(s)? As default, the `save_iters` is set to 50,000 so if you stopped training before that point you would not have anything saved. (You should see them in the models/train folder)

**Comment by cathy-liu23** [comment]
Thank you so much for the quick reply and for solving our problem! We stopped training before the 50,000 cutoff, so we didn't have the saved snapshot(s). Thank you again!

**Comment by MMathisLab** [comment]
no problem, happy DeepLabCutting!
