### ISSUE TITLE
How to use train script on Pytorch framework?

### ISSUE THREAD

**Issue by Vaccummer** [DeepLabCut/DeepLabCut#2603]
"deeplabcut.train_network" function use script in "pose_estimation_tensorflow" by default. How to use that in "pose_tracking_pytorch".  Is these two scripts have different functions or  Pytorch script is still in debug stage?

**Comment by Vaccummer** [comment]
I want to use mix prescision and DDP but Tensorflow1.x code is a torture for me.

**Comment by MMathisLab** [comment]
`pose_tracking_pytorch` is currently only the self-supervised reID as shown in nature methods 2022 https://www.nature.com/articles/s41592-022-01443-0, specifically: 

![image](https://github.com/DeepLabCut/DeepLabCut/assets/28102185/cc15bfa3-a352-4604-8b2a-1b337533a8a1)


However, in lucky timing, we are prepping a public PR of a full pytorch backend in the next 72 hours 🔥... so stay tuned, the pain will go away (we hear you!) 

sneak-peek from the internal dev repo for you ;)

![Screen Shot 2024-06-07 at 5 51 35 PM](https://github.com/DeepLabCut/DeepLabCut/assets/28102185/38ca2c33-c15a-4ba3-835d-0d93fe58fe08)

**Comment by Vaccummer** [comment]
Looking forward to it!
