### ISSUE TITLE
Napari crashes when trying to label the frames

### ISSUE THREAD

**Issue by ANNIhilation010** [DeepLabCut/DeepLabCut#2604]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Bug description

Hey,
I have only recently started working with deeplabcut and ipython and unfortunately have the problem that napari crashes with the following error message every time I try to label the extracted frames. The suggestions on the issues from other forums have unfortunately not helped. I have been working with the help of ChatGPT for days now, but unfortunately I have not really made any progress. 

Do any of you have an idea and could help me?

All the best!

### Operating System

Windows 10

### DeepLabCut version

dlc version 2.3.9

### DeepLabCut mode

multi animal

### Device type

cpu

### Steps To Reproduce

I work in the anaconda prompt terminal.

I already tried:
- `python -m pip install --upgrade pip`

- `pip uninstall deeplabcut pyqt6` and `python -m venv deeplabcut-env
deeplabcut-env\Scripts\activate
pip install --upgrade pip
pip install deeplabcut[gui] pyqt6`

- repeating all of the steps of the guide (https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html) from scratch

- checking the config path, the files
- checking the compatability of my python version with deeplabcut and napari

### Relevant log output

```shell
# I already created the project and edited the yaml file the time before. The output you see is my 2nd or 3rd attempt. 

(base) C:\Users\renac>conda activate deeplabcut
(deeplabcut) C:\Users\renac>ipython
Python 3.8.19 | packaged by conda-forge | (default, Mar 20 2024, 12:38:07) [MSC v.1929 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.2 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import deeplabcut
2024-06-07 11:55:29.843718: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2024-06-07 11:55:29.843981: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Loading DLC 2.3.9...

In [2]: config_path = 'C:\\Users\\renac\\(...)\\config.yaml'

In [3]: deeplabcut.label_frames(config_path)
Installed qt6 event loop hook.
WARNING: DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="MS Sans Serif", pointsize=12, pixelsize=16, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("MS Sans Serif", lfWidth=0, lfHeight=-16) dpi=120

In [4]:
(deeplabcut) C:\Users\renac>
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
hi @ANNIhilation010 please update to 2.9.10 by running `pip install deeplabcut[gui,tf]==2.1.10` and `pip install --upgrade napari-deeplabcut`

and can you launch by running in the terminal `python -m deeplabcut` - thanks!

**Comment by MMathisLab** [comment]
and, please be aware we dropped support for python 3.8 some time ago; the min. is python 3.9 (see docs), so that is also likely related! HTH
