### ISSUE TITLE
maxiters not set when creating training dataset

### ISSUE THREAD

**Issue by tom21100227** [DeepLabCut/DeepLabCut#2611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi, I am relatively new to DeepLabCut so this might seems like a bad question, I read the docs and searched for issues and couldn't seem to find an explanation as the API docs just said "This variable is actually set in pose_config.yaml". Sorry if this is redundant! 

When creating a training dataset with either GUI or deeplabcut.create_training_dataset(), there's no default value for `maxiters` in `pose_cfg.yaml`. And when running train_network it seems to train non-stop (there's no ending to the training loop, or at least I think so since it's still going at 447_000 iters). 

### Operating System

DLC runs in Ubuntu based SLURM cluster, GUI ran on macOS Sonoma forwarded from HPC using X11 connection. 

### DeepLabCut version

2.3.10

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

1. On a newly created project (with labelled data), create a training dataset (I did`deeplabcut.create_training_dataset(config_path, augmenter_type='imgaug', num_shuffles = 4)`)
2. When calling `train_network` on the corresponding data, both the printed config on output and the `pose_cfg.yaml` does not have maxiters set. 

### Relevant log output

```shell
# pose_cfg.yaml: 
all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
- - 12
- - 13
- - 14
- - 15
- - 16
- - 17
- - 18
- - 19
- - 20
- - 21
all_joints_names:
- Anchor
- Abdomen_Tip
- RightFrontJoint
- RightFrontKnee
- RightFrontLeg
- LeftFrontJoint
- LeftFrontKnee
- LeftFrontLeg
- RightMidJoint
- RightMidKnee
- RightMidLeg
- LeftMidJoint
- LeftMidKnee
- LeftMidLeg
- RightHindJoint
- RightHindKnee
- RightHindKnee-Leg
- RightHindLeg
- LeftHindJoint
- LeftHindKnee
- LeftHindKnee-Leg
- LeftHindLeg
alpha_r: 0.02
apply_prob: 0.5
batch_size: 1
contrast:
  clahe: true
  claheratio: 0.1
  histeq: true
  histeqratio: 0.1
convolution:
  edge: false
  emboss:
    alpha:
    - 0.0
    - 1.0
    strength:
    - 0.5
    - 1.5
  embossratio: 0.1
  sharpen: false
  sharpenratio: 0.3
cropratio: 0.4
dataset: training-datasets/iteration-0/UnaugmentedDataSet_2024_BehavioralJun10/2024_Behavioral_Tom
  Han95shuffle1.mat
dataset_type: imgaug
decay_steps: 30000
display_iters: 1000
global_scale: 0.8
init_weights: /mnt/local/python-venv/dlc-2.3.9/lib64/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
metadataset: training-datasets/iteration-0/UnaugmentedDataSet_2024_BehavioralJun10/Documentation_data-2024_Behavioral_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: resnet_50
num_joints: 22
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
project_path: /mnt/research/hhorch/chan/2024_DLC/2024_Behavioral-Tom Han-2024-06-10
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25


# config.yaml:     # Project definitions (do not edit)
Task: 2024_Behavioral
scorer: Tom Han
date: Jun10
multianimalproject: false
identity:

    # Project path (change when moving around)
project_path: /mnt/research/hhorch/chan/2024_DLC/2024_Behavioral-Tom Han-2024-06-10

    # Annotation data set configuration (and individual video cropping parameters)
video_sets:
  /mnt/research/hhorch/chan/2024_DLC/test vids/2024-06-10 13-43-04.mp4:
    crop: 0, 1920, 0, 1080
  /mnt/research/hhorch/chan/2024_DLC/test vids/2024-06-10 14-19-53.mp4:
    crop: 0, 1920, 0, 1080
  /mnt/research/hhorch/chan/2024_DLC/test vids/2024-06-10 15-11-06.mp4:
    crop: 0, 1920, 0, 1080
  /mnt/research/hhorch/chan/2024_DLC/test vids/2024-06-10 15-18-03.mp4:
    crop: 0, 1920, 0, 1080
  /mnt/research/hhorch/chan/2024_DLC/test vids/2024-06-10 15-45-00.mp4:
    crop: 0, 1920, 0, 1080
bodyparts:
- Anchor
- Abdomen_Tip
- RightFrontJoint
- RightFrontKnee
- RightFrontLeg
- LeftFrontJoint
- LeftFrontKnee
- LeftFrontLeg
- RightMidJoint
- RightMidKnee
- RightMidLeg
- LeftMidJoint
- LeftMidKnee
- LeftMidLeg
- RightHindJoint
- RightHindKnee
- RightHindKnee-Leg
- RightHindLeg
- LeftHindJoint
- LeftHindKnee
- LeftHindKnee-Leg
- LeftHindLeg

    # Fraction of video to start/stop when extracting frames for labeling/refinement

    # Fraction of video to start/stop when extracting frames for labeling/refinement

    # Fraction of video to start/stop when extracting frames for labeling/refinement
start: 0
stop: 1
numframes2pick: 20

    # Plotting configuration
skeleton:
skeleton_color: black
pcutoff: 0.6
dotsize: 12
alphavalue: 0.7
colormap: rainbow

    # Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 0
default_net_type: resnet_50
default_augmenter: default
snapshotindex: -1
batch_size: 8

    # Cropping Parameters (for analysis and outlier frame detection)
cropping: false
    #if cropping is true for analysis, then set the values here:
x1: 0
x2: 640
y1: 277
y2: 624

    # Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 50
- 50
move2corner: true
```

### Anything else?

I know the file directory seems to suggest I am running DLC 2.3.9 but the actual DLC version we're running is 2.3.10 as it is a recent update. 

Also, a few questions that I still have when reading the documentation, sorry if this is not the right place to ask. 
- `gputouse` flag: From the documentation it seems like if I put `None`, DLC would not use GPU for training, but if I choose to not add the `gputouse` argument, a GPU is still used. 
- is it possible to use Napari and/or the skeleton builder on a remote server without OpenGL installed? If not, what is the best way to get labelling done when project is located on a remote server? I tried locally mounting the directory to my mac and load the project but because macOS have mounted folder as  `/Volumes/...` and server had it on `/mnt/...` it could not work. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
when you train, you pass the value:  `deeplabcut.train_network( ..., max_iters = 50000)`. 

Labeling one should do locally, and then move the project folder to the cluster for training, evaluation, and video_analysis. 

If a GPU is available, it will use it. CPU training can take up to 1 week otherwise...
