### ISSUE TITLE
Tag accidentally called 2.9.10 instead of 2.3.10???

### ISSUE THREAD

**Issue by hmaarrfk** [DeepLabCut/DeepLabCut#2618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Did you accidentally call the tag 2.9.10 instead of 2.3.10?

### Operating System

github

### DeepLabCut version

2.3.10

### DeepLabCut mode

single animal

### Device type

web

### Steps To Reproduce

https://github.com/DeepLabCut/DeepLabCut/releases/tag/v2.9.10

### Anything else?

it seems that pypi is correctly versionned.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
🤦‍♀️ my fault, will fix asap thanks @hmaarrfk
