### ISSUE TITLE
 deeplabcut.refine_labels does not allow selection of labeled frames

### ISSUE THREAD

**Issue by effiek9999** [DeepLabCut/DeepLabCut#262]
**Environment**

DeepLabCut version: 2.0.5
OS: Windows 10
Environment: Anaconda 3 using GeoForce GTX 1080ti GPU

**Problem Description**

 deeplabcut.refine_labels call brings up GUI for loading labels but hitting the 'Load labels' button requires a 'machinelabels-iter0.h5 files' type which cannot be found and I am unable to load any labeled frames.

See screenshots.

**Screenshots**

![Screenshot (30)](https://user-images.githubusercontent.com/3596849/55889191-b0b26900-5b7e-11e9-9a19-299d5dc2bc88.png)

![Screenshot (32)](https://user-images.githubusercontent.com/3596849/55889198-b7d97700-5b7e-11e9-9d7d-4443653c1d64.png)

**Comment by MMathisLab** [comment]
The refinement GUI is for adjusting machine applied, i.e. DeepLabCut applied labels. This would be you run deeplabcut.anayze_videos then deeplabcut.extract_outlier_frames first. Please see here for more details: 

Overview: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/UseOverviewGuide.md#overview-of-the-work-flow

- https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#i-video-analysis-and-plotting-results

- https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#j-refinement-extract-outlier-frames

- https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#k-refine-labels-augmentation-of-the-training-dataset

**Comment by effiek9999** [comment]
My apologies if I missed a step. Thank you.

**Comment by MMathisLab** [comment]
no problem
