### ISSUE TITLE
Deeplabcut has no attribute 'label_frames' 

### ISSUE THREAD

**Issue by natelam21** [DeepLabCut/DeepLabCut#2621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I successfully created a project and extracted frames, but using label_frames gave me AttributeError: module 'deeplabcut' has no attribute 'label_frames'

I am running Deeplabcut using Slurm + python scripts, not the GUI

### Operating System

CentOS 7 

### DeepLabCut version

dlc version 2.3.9

### DeepLabCut mode

single animal

### Device type

gpu

### Anything else?

![b10b458af709d9761394b4d7b80fde5ea2a26150](https://github.com/DeepLabCut/DeepLabCut/assets/173103393/da47026b-5c3e-49c2-a096-bd453051d854)

This is what I get when I look at the available DLC functions, which is notably missing label_frames. Any idea how to fix this?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hi @natelam21, this is expected: when running on a headless system (where the GUI is not supported), `label_frames` and other refinement functions are not available. One would typically label frames locally before uploading the images and annotations to the remote machine.
