### ISSUE TITLE
attribute error on running the label_frames function (matplotlib issue)

### ISSUE THREAD

**Issue by rajatsaxena** [DeepLabCut/DeepLabCut#263]
I am using windows 10 with an Anaconda Env and DeepLabCut2.0.5.1. I tried running one of the jupyter notebook tutorials: https://github.com/AlexEMG/DeepLabCut/blob/master/examples/Demo_yourowndata.ipynb on one of the datasets recorded in my lab. 

Running the part of the script below:
```
%gui wx
deeplabcut.label_frames(path_config_file)
```
gives me the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\deeplabcut\generate_training_dataset\labeling_toolbox.py in browseDir(self, event)
    364         self.alpha = self.cfg['alphavalue']
    365         self.colormap = plt.get_cmap(self.cfg['colormap'])
--> 366         self.colormap = self.colormap.reversed()
    367         self.project_path=self.cfg['project_path']
    368         self.index =np.sort([fn for fn in glob.glob(os.path.join(self.dir,'*.png')) if ('labeled.png' not in fn)])

AttributeError: 'LinearSegmentedColormap' object has no attribute 'reversed'

```

Steps to reproduce the problem:
1. Run the `label_frames` function
2. Click on Load frames
3. Select folder with the extracted frames

**Comment by MMathisLab** [comment]
Hello, I tried to reproduce the error, but I cannot. Here I used this notebook: https://github.com/AlexEMG/DeepLabCut/blob/master/examples/Demo_labeledexample_Openfield.ipynb
and added this cell to launch the GUI and load the images:
```
%gui wx
deeplabcut.label_frames(path_config_file)
```
and I have no issues. 

Video here: https://youtu.be/cxL3xR9PknQ


Perhaps check that your config path is correct. 

```
import os
from pathlib import Path
path_config_file = os.path.join(os.getcwd(),'openfield-Pranav-2018-10-30/config.yaml')
```
And, can you confirm your version:`deeplabcut.__version__` 
 and for matplotlib:
```

import matplotlib
matplotlib.__version__
```

**Comment by AlexEMG** [comment]
What color-map do you use?

**Comment by rajatsaxena** [comment]
deeplabcut version = 2.0.05.1
matplotlib version = 2.0.2

color-map = jet

The one difference I noticed compared to the video you sent and my dataset is at 0:43 when you:

1. click on the 'Load frame' button
2. went inside the 'labeled_data/m4s1' folder and there are the images inside the m4s1 folder

When I follow the exact same steps and go inside the labeled_data folder, I do not see images under the subfolders. Check the 2 images attached below:

![c1](https://user-images.githubusercontent.com/5181888/56039008-29810480-5ce8-11e9-82fd-6debd47c6362.png)
![c2](https://user-images.githubusercontent.com/5181888/56039016-2c7bf500-5ce8-11e9-92f9-f671b5498faa.png)


Although in reality, I have multiple images under both the subfolders in the labeled_data: 

![c3](https://user-images.githubusercontent.com/5181888/56039080-56351c00-5ce8-11e9-9d10-1122dcb3e1bc.png)


Thanks for the quick reply and help!

**Comment by MMathisLab** [comment]
Can you confirm you can run this on the demo data?

**Comment by rajatsaxena** [comment]
Same error log on the demo data

**Comment by MMathisLab** [comment]
could you update to `matplotlib 2.2.2` (or the most current version) by running `pip install matplotlib==2.2.2`

**Comment by rajatsaxena** [comment]
that worked. Thanks a lot!
