### ISSUE TITLE
Modelzoo SSLerror campanyPC

### ISSUE THREAD

**Issue by Cadaqoes** [DeepLabCut/DeepLabCut#2636]
Hi all

When I tried to use Modelzoo, I got the following error and could not download the models.

```
requests.exceptions.SSLError:
(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443):
Max retries exceeded with url: /mwmathis/DeepLabCutModelZoo-SuperAnimal-Quadruped_DLC2/resolve/main/DLC_ma_superquadruped_resnet_50_iteration-0_shuffle-1.tar.gz
(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1131)')))"), '(Request ID: fb422eff-6d26-4e17-bf01-1d45520f6f36)')
```

  I think it is probably due to the security of the PC I am using at company.
 Any ideas on how to make it possible to use the Modelzoo?

OS windows 10
Deeplabcut version 2.3.10

Thanks

**Comment by n-poulsen** [comment]
Hi @Cadaqoes! That does seem like a security issue from your PC - what are you trying to run exactly?

**Comment by Cadaqoes** [comment]
Thank you @n-poulsen 

It is simple.
I'm trying to move the model zoo with a GUI.
SuperAnimal-Quadruped and SuperAnimal-TopViewMouse.

Best

**Comment by MMathisLab** [comment]
@Cadaqoes are you based in china; others have reported issues with using huggingface; that is my only guess.

**Comment by Cadaqoes** [comment]
Thank you ! @MMathisLab 
I live in Japan, no china.
It's probably a company security issue, but I'm looking for a way to get around it, like a workaround or trick.

For example, is it possible to execute by moving the superanimal weights downloaded from huggingface to C\\....\anaconda3\Lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained

**Comment by Cadaqoes** [comment]
I downloaded the weights manually and changed the path and it worked!


Thanks.
