### ISSUE TITLE
DLC 3.0: Filter Predictions not working in GUI

### ISSUE THREAD

**Issue by roaldarbol** [DeepLabCut/DeepLabCut#2641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

After analysing a video from the GUI with `Filter predictions` checked, no filtered predictions have been generated. 

### Operating System

Windows 10.

### DeepLabCut version

DLC 3.0.0rc1

### DeepLabCut mode

single animal

### Device type

NVIDIA Quadro M5000

### Steps To Reproduce

1. Install the rc version
2. Open the GUI
3. Analyze video with `Filter predictions` ticked
4. No filtered predictions are generated

### Relevant log output

```shell
INFO:console:Saving results in C:\Users\mr630\Desktop\DLC-Mouthparts\DLC-Project\videos\front2024-01-15T14_31_22shortdownsampledDLC_Resnet50_BeetleMouthpartsJun25shuffle1_snapshot_200.h5 and C:\Users\mr630\Desktop\DLC-Mouthparts\DLC-Project\videos\front2024-01-15T14_31_22shortdownsampledDLC_Resnet50_BeetleMouthpartsJun25shuffle1_snapshot_200_full.pickle
INFO:console:The videos are analyzed. Now your research can truly start!
```

Found out trying to create a labelled video, which gave me this:
```python
INFO:console:No filtered data file found in C:\Users\mr630\Desktop\DLC-Mouthparts\DLC-Project\videos for video front2024-01-15T14_31_22shortdownsampled and scorer DLC_Resnet50_BeetleMouthpartsJun25shuffle1_snapshot_200.
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@roaldarbol thanks for the report! this is now fixed, if you can pull the branch again, it's updated!
