### ISSUE TITLE
Installing DeepLabCut 3.0 , Pytorch doesn't natively install its own CUDA and cuDNN as advertised, windows 11

### ISSUE THREAD

**Issue by camilletestard** [DeepLabCut/DeepLabCut#2644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Trying to install DLC 3.0 with GPU. Here are my specs: 
1. Windows 11
2. GPU: NVIDIA RTX A2000 12GB, GPU driver: 552.55
3. CUDA Toolkit 12.1
4. Visual Studio 2022

I followed exactly the installation instructions but find that Pytorch is *not* installing its own nvcc and cudnn though advertised that it should based on both DLC installation Guide and Pytorch documentation. 

After installing a compatible driver for NVIDIA, a compatible toolkit with Pytorch's latest version (just in case) and the latest DeepLabCut with either pip or the yml, DLC installs but does not use the GPU. 

According to what I read Pytorch installs its own CUDA and cuDNN. So I opened a python command line and imported torch and checked for torch.cuda.is_available() = False and torch.backend.cudnn.is_available()=False. So It seems for some people Pytorch doesn't natively install what is necessary? 

Is there any specific configuration required by Pytorch and DLC for Pytorch to install these things automatically? Have other people experienced this? Thanks for your help! 

### Operating System

operating system Windows 11

### DeepLabCut version

dlc version 3.0

### DeepLabCut mode

multi animal

### Device type

NVIDIA RTX A2000 12GB

### Steps To Reproduce

1. Install Visual Studio 2022
2. Install NVIDIA driver 
3. Install CUDA Toolkit
4. Install deelabcut in conda environment

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by gmarsha** [comment]
I seem to be having a similar issue...

Using windows, with GEforce RTX 4080

Downloaded anaconda
Downloaded CUDA 12.1
Downloaded and manually installed CUDNN 8.9.7 for CUDA 12.x
Installed visualstudio 2022

Installed deeplabcut from YAML file

At this stage if I run "analyze videos" in DLC, it can go for days with no sign of CPU or GPU usage ( i.e. not doing anything)

Ran `python -c "import torch;print(torch.cuda.is_available())"` inside DLC environment, returns FALSE, so pytorch not detecting CUDA.

Inside DLC environemnt, tried 

`conda install cudnn`
and
`conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia`

At this stage `python -c "import torch;print(torch.cuda.is_available())"` inside DLC environment, returns TRUE

BUT

DLC will only load in light mode and I cant open the GUI...... so i cant do anything with my existing model. 

Seems that something is goign wrong with the environemtn detecting the system level CUDA/ Cudnn so pytorch just isnt working.

**Comment by n-poulsen** [comment]
Hi @camilletestard! If you get a working version of PyTorch installed in a conda environment that has cuda available, you can then use your GPU with DeepLabCut (only PyTorch connects to the GPUs from DeepLabCut). 

I don't have a Windows machine with a GPU available under hand, but PyTorch should install CUDA in the `conda` environment for you. According to their docs, if you run:

```bash
conda create -n deeplabcut3 python=3.11
conda activate deeplabcut3
conda install pytorch torchvision pytorch-cuda=12.1 -c pytorch -c nvidia
```

You should be able to have access to your GPU in the `conda` environment (which as you noted, you can check with `python -c "import torch;print(torch.cuda.is_available())"`). If that prints `True`, then DeepLabCut should be able to use the GPU (once installed).

One **important** thing to note is that you need to install `torch` **before** you install DeepLabCut in your conda environment (as is specified in the [pull request](https://github.com/DeepLabCut/DeepLabCut/pull/2613)). So you should be able to install everything (including CUDA) by running (in this order, in your specific Windows configuration):

```bash
conda create -n deeplabcut3 python=3.11
conda activate deeplabcut3
conda install pytorch torchvision pytorch-cuda=12.1 -c pytorch -c nvidia
conda install -c conda-forge pytables==3.8.0
pip install "git+https://github.com/DeepLabCut/DeepLabCut.git@pytorch_dlc#egg=deeplabcut[gui,modelzoo,wandb]"
```

Let me know if that solves the issue for you!

**Comment by n-poulsen** [comment]
@gmarsha DeepLabCut loading in "light mode" means the GUI is not installed, not that the GPU cannot be used. To install the GUI in your environment, you can simply run (note the `[gui,modelzoo,wandb]` at the end - this specifies that the GUI for DeepLabCut needs to be installed as well):

```
pip install "git+https://github.com/DeepLabCut/DeepLabCut.git@pytorch_dlc#egg=deeplabcut[gui,modelzoo,wandb]"
```

**Comment by shawnoh8** [comment]
I had the same error as @camilletestard .
My error was resolved by updating two things.
 1. numexpr from 2.7.3 (default after downloading) to 2.8.4
 2. pillow from 10.3.0 (default after downloading) to 10.4.0

Hope this helps someone who is in the same situation as me!

**Comment by gmarsha** [comment]
Hey [n-poulsen](https://github.com/n-poulsen) and [shawnoh8](https://github.com/shawnoh8)

Thanks so much for the codes (!) but I am still having problems. I completely uninstalled anaconda from my Windows machine and started again from scratch. 

I then ran:

```shell
conda create -n deeplabcut3 python=3.11
conda activate deeplabcut3
conda install pytorch torchvision pytorch-cuda=12.1 -c pytorch -c nvidia
conda install -c conda-forge pytables==3.8.0
pip install "git+https://github.com/DeepLabCut/DeepLabCut.git@pytorch_dlc#egg=deeplabcut[gui,modelzoo,wandb]"
```

I then ran

```shell
Pip install numexpr==2.8.4
Pip install pillow==10.4.0
```

DLC now loads the GUI and torch can detect CUDA :D

BUT there is still pretty much no CPU or GPU usage when I hit "analyze videos". When I clock, pthon takes about a gig of RAM then appears to do nothing, although the little loading bar on the bottom right is moving...

**Comment by n-poulsen** [comment]
@gmarsha do you get anything logged in the anaconda prompt?

**Comment by vidursa** [comment]
> @gmarsha do you get anything logged in the anaconda prompt?

I have the same issue. The anaconda prompt shows the following error even though I'm using the pytorch backend. Installation steps were the same as @gmarsha followed above.

> QPixmap::scaled: Pixmap is a null pixmap
Traceback (most recent call last):
 File "D:\miniconda3\envs\deeplabcut3\Lib\site-packages\deeplabcut\gui\utils.py", line 22, in run
  self.func()
 File "D:\miniconda3\envs\deeplabcut3\Lib\site-packages\deeplabcut\compat.py", line 818, in analyze_videos
  from deeplabcut.pose_estimation_tensorflow import analyze_videos
 File "D:\miniconda3\envs\deeplabcut3\Lib\site-packages\deeplabcut\pose_estimation_tensorflow\__init__.py", line 16, in <module>
  import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

**Comment by gmarsha** [comment]
@n-poulsen 

Hi, 

I ended up terminating the analysis as it ran for several days with no progress. This was for a total of about 50 minutes of video at 30 fps.

I dont get anything coming up on the anaconda prompt really after loading the GUI. Like @vidursa mentioned there is a error saying ModuleNotFoundError: No module named 'tensorflow' but I am using pytorch.

**Comment by vidursa** [comment]
> @n-poulsen
> 
> Hi,
> 
> I ended up terminating the analysis as it ran for several days with no progress. This was for a total of about 50 minutes of video at 30 fps.
> 
> I dont get anything coming up on the anaconda prompt really after loading the GUI. Like @vidursa mentioned there is a error saying ModuleNotFoundError: No module named 'tensorflow' but I am using pytorch.

I just solved it. Apparently its better to install tensorflow with deeplabcut as it exists right now. Otherwise, a lot of functions have dependency issues. I guess tensorflow 2.10.0 is not supported on python 3.11 yet. So to solve it I deleted the previous conda installation and followed the same steps with python 3.10. Also, instead of 

`pip install "git+https://github.com/DeepLabCut/DeepLabCut.git@pytorch_dlc#egg=deeplabcut[gui,modelzoo,wandb]"`

I ran 
`pip install "git+https://github.com/DeepLabCut/DeepLabCut.git@pytorch_dlc#egg=deeplabcut[gui,modelzoo,wandb,tf]"`

**Comment by gmarsha** [comment]
@vidursa 

Thanks, I'll try that today! Just to check, are all the other installation steps the same? And does this install the correct CUDA for tensorflow?

**Comment by vidursa** [comment]
Yes, I followed all the same installation steps apart from the ones I mentioned (python 3.10 instead of 3.11, and the tf argument with deeplabcut). I didn't have any problems setting up CUDA, so I guess the correct CUDA for tensorflow got installed. Although, I already had CUDA drivers before in the base system.

**Comment by gmarsha** [comment]
OMG its finally doing something!

Its fully utilising my CPU but not using my GPU at all, is there some way I can get it to use the GPU instead?

**Comment by MMathisLab** [comment]
I assure you one does not need TensorFlow installed 🙏🏼; you can install the updated pypi rc3 version now and first just follow the instructions from PyTorch to provide GPU support.

I strongly recommend reading: https://deeplabcut.github.io/DeepLabCut/docs/beginner-guides/beginners-guide.html#let-s-learn-a-bit-and-create-a-deeplabcut-env

**Comment by gmarsha** [comment]
@MMathisLab 

Thanks but that just takes me back to square one...

I created a new env with:

conda create -n deeplabcut python=3.10
conda activate deeplabcut
conda install pytorch cudatoolkit=11.8 -c pytorch
conda install -c conda-forge pytables==3.8.0
pip install "git+https://github.com/DeepLabCut/DeepLabCut.git@pytorch_dlc#egg=deeplabcut[gui,modelzoo,wandb]"
python -m deeplabcut

Everything loads fine but when I click analyse videos there is no CPU or GPU usage, just the endless loading bar in the bottom right of the GUI.

**Comment by MMathisLab** [comment]
Are you sure 11.8 is the correct version of CUDA for your system?

**Comment by gmarsha** [comment]
Oh I'm not sure how to check - python -c "import torch;print(torch.cuda.is_available())" returns false in the DLC env.

**Comment by MMathisLab** [comment]
you need to know which NVIDA driver you have installed, then follow the pytorch guide, as our docs say. Namely, you need to look here: 

https://pytorch.org/get-started/locally/

<img width="823" alt="Screenshot 2024-07-25 at 11 28 03" src="https://github.com/user-attachments/assets/94023484-74b4-44f7-8804-8976e341186a">


to find your driver version of your GPU, if you don't remember: 

``nvidia smi`` in your terminal

**Comment by gmarsha** [comment]
I think I need to downgrade CUDA to 11.8 or 12.1 on my system (i.e. not the conda env?)

![image](https://github.com/user-attachments/assets/dc031342-7ef0-4b1f-bfb8-7cb146cef4bc)

nvcc --V gives this:

![image](https://github.com/user-attachments/assets/06a255c3-0ca3-41c2-9315-f124efd9c97c)

**Comment by MMathisLab** [comment]
It means you have CUDA 12.6 installed, so you should not install pytorch for 11.8 support ... you should install GPU support for CUDA 12.6: 

``conda install pytorch cudatoolkit=12.6 -c pytorch``

**Comment by gmarsha** [comment]
Sadly  get an error trying to install with CUDA 12.5 or 12.6:

PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit=12.6*

Should I just downgrade my system CUDA?

**Comment by MMathisLab** [comment]
Did you first try just installing the version they recommend, if you fill out the chart I linked to you? 

``pip3 install torch ... etc? ``

**Comment by gmarsha** [comment]
If I fill out the chart for windows they dont recommend any version, just give the options of 11.8, 12.1 or 12.4. 

Apologies, do you mean install that version in my conda env or on the PC itself?

**Comment by gmarsha** [comment]
Okay I downgraded my PC to CUDA 12.4.

I then ran:

conda create -n deeplabcut python=3.10
conda activate deeplabcut
conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia
conda install -c conda-forge pytables==3.8.0
pip install "git+[https://github.com/DeepLabCut/DeepLabCut.git@pytorch_dlc#egg=deeplabcut[gui,modelzoo,wandb]](https://github.com/DeepLabCut/DeepLabCut.git@pytorch_dlc#egg=deeplabcut%5Bgui,modelzoo,wandb%5D)"
python -m deeplabcut

I open the GUI and analyze videos and again nothing happens...

![image](https://github.com/user-attachments/assets/1327317f-ba17-4083-8277-ae51efc06848)

Nothing in the console after clicking analyse videos:

![image](https://github.com/user-attachments/assets/6664656f-2b65-4c45-8d72-81518f104949)

**Comment by vidursa** [comment]
> Okay I downgraded my PC to CUDA 12.4.
> 
> I then ran:
> 
> conda create -n deeplabcut python=3.10 conda activate deeplabcut conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia conda install -c conda-forge pytables==3.8.0 pip install "git+[https://github.com/DeepLabCut/DeepLabCut.git@pytorch_dlc#egg=deeplabcut[gui,modelzoo,wandb]](https://github.com/DeepLabCut/DeepLabCut.git@pytorch_dlc#egg=deeplabcut%5Bgui,modelzoo,wandb%5D)" python -m deeplabcut
> 
> I open the GUI and analyze videos and again nothing happens...

I just noticed that the TensorFlow ModuleNotFoundError/AttributeError arise when using a previous project's config file that was used with TensorFlow. I changed the "engine" definition to pytorch, but that does not resolve the error. I'm unsure what the old config file is referring to in the project that requires importing TensorFlow. If I install deeplabcut with tensorflow and use the old config file, it ignores the pytorch backend even if selected and just uses TensorFlow for training and analyzing videos.

If I initialize a new project and copy the labelled data, all steps execute correctly with pytorch as a backend without needing TensorFlow installed. I'm not sure if you are facing the same issue, but worth a try if you haven't done so already.

**Comment by gmarsha** [comment]
Hey @vidursa 

Thanks for the idea - I also thought editing the config YAML to pytorch would work even if the project previously used tensorflow. 

When you say create a new project, do you only copy across the labelled data folder? And can you go straight to analyse videos after that? Or do I need to remake the models?

![image](https://github.com/user-attachments/assets/7d6aaf7f-7701-4e55-8d28-612a7644b223)

**Comment by MMathisLab** [comment]
@gmarsha you would need to train a pytorch model; but you can use the same split of training data to directly compare cc @n-poulsen https://deeplabcut.github.io/DeepLabCut/docs/pytorch/user_guide.html#creating-shuffles-and-model-configuration

**Comment by gmarsha** [comment]
Hey, 

I am trying this. I have made a new project adn am trying to move the annotated frames over but when I try to create a training dataset with the annotated frames from a previous project I get this error. 

![image](https://github.com/user-attachments/assets/a01cbe2f-1f8c-40a9-8b65-72674eb91a98)

Really hoping I dont need to annotate the frames again?

**Comment by gmarsha** [comment]
EDIT:

Network is currently training on pytorch. CPU is maxed out.

**Comment by gmarsha** [comment]
Okay I have retrained the model on pytorch and have hit analyze videos. CPU is maxed out so it is finally working! But no GPU usage...

![image](https://github.com/user-attachments/assets/1c6b75d5-c3f0-4f35-a91d-0701ef38b81c)

![image](https://github.com/user-attachments/assets/c51176d2-5b1a-468d-a4a1-d7a063779904)

**Comment by vidursa** [comment]
Your CUDA version still shows 12.6. I guess there's still a mismatch between the CUDA version on your PC and the one you installed for pytorch, which is why the GPU isn't used.

If you installed CUDA 12.4 as you stated previously, you could follow the steps in the link [https://github.com/bycloudai/SwapCudaVersionWindows](url) to add it as the default in your environment variables.

**Comment by gmarsha** [comment]
@vidursa nvidia-smi shows 12.6 which I believe means that is the max version my GPU can run, but nvcc -V shows 12.4 which is what I have installed. System PATH variables for CUDA are correct as well. 

I'm going to recreate my environment from scratch later today and see if I can get the GPU working. 

I'm sure that I have installed the GPU version of pytorch with:

```python
conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia
```
I will try the nightly version of pytorch as well...

Also wondering if I should install cuDNN on my machine rather than just hoping the correct one is present in the conda env?

**Comment by gmarsha** [comment]
Hey all - I have finally got everything working! Thanks everyone for your patience and help with this newbie :D

For future reference here is what worked for me:

1. Installed visual studio community 2022
2. Installed CUDA 12.4 onto PC
3. Installed cudnn 9.2.1 with installer. Defo follow a guide if you want to install cudnn manually!
4. Installed anaconda
5. Open anaconda prompt as admin

Run following:
```python
conda create -n deeplabcut python=3.10
conda activate deeplabcut
conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch-nightly -c nvidia
conda install -c conda-forge pytables==3.8.0
pip install "git+[https://github.com/DeepLabCut/DeepLabCut.git@pytorch_dlc#egg=deeplabcut[gui,modelzoo,wandb]](https://github.com/DeepLabCut/DeepLabCut.git@pytorch_dlc#egg=deeplabcut%5Bgui,modelzoo,wandb%5D)"
Pip install numexpr==2.8.4
python -m deeplabcut
```

NB: the above code is for the 'nightly' version of pytorch, which is running the video analysis faster than pytorch stable release and is way less CPU heavy, at least for me… if you build your env with the nightly version you will get two errors when you open the GUI (procedure entry point not found for \pytorch\_C.pyd and \pytorch\image.pyd). These errors do not stop the model from being trained or the videos being analysed. 

If you don’t want to use pytorch-nightly it replace 
```python
conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch-nightly -c nvidia
```
with [edit CUDA version as appropriate]
```python
conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia
```

If you want to move an old tensorflow project to a pytorch model and don’t want to re-annotate frames:

1. Create a new project in a pytorch env. 
2. Use the exact same experimenter name as the tensorflow project.  
3. At the project creation stage add ONLY the videos that you want to train the model on. This will require creating a folder with only those videos you have previously annotated within it.
4. Create project then close GUI.
5. Copy files from labeled-data in tensorflow project over to the same folder in the new pytorch project
6. Open the config.YAML of the old tensorflow project and the new pytorch project. Copy the “Bodyparts” under "annotation data config" from the old project to the new. Do the same for the “Skeleton” under "plotting configuration".
7. Reopen GUI and open the new project. Open the labelled frames box, check the annotated frames have copied over then and resave with ctrl+S. You can then go straight to “Create training dataset” then through to training the network and analysing the videos you want using pytorch.

**Comment by PetraMocellin** [comment]
Hi,

On a related topic: can you clarify what are the dependencies between python version, cuda version, cudnn version and cudatoolkit? And how do they relate within the environment?

I am running into similar problems when trying to install DLC 3.0

Here are my specs:

Windows 11 Pro
GPU: NVIDIA GeForce RTX 4080 SUPER, 
CUDA Toolkit 12.1
Visual Studio 2022

I run 

```
conda create -n deeplabcut3 python=3.11
conda activate deeplabcut3
conda install pytorch torchvision pytorch-cuda=12.1 -c pytorch -c nvidia
conda install -c conda-forge pytables==3.8.0
pip install "git+https://github.com/DeepLabCut/DeepLabCut.git@pytorch_dlc#egg=deeplabcut[gui,modelzoo,wandb]"
```

Once in the deeplabcut3 environment I run 

```
python
import torch
torch.cuda.is_available()
torch.cuda.device_count()
torch.cuda.current_device()
torch.cuda.get_device_name(0)

```

The output is:

python 3.11.10
>>> torch.cuda.is_available()
True
>>> torch.cuda.device_count()
1
>>> torch.cuda.current_device()
0
>>> torch.cuda.get_device_name(0)
'NVIDIA GeForce RTX 4080 SUPER'

However when launching the GUI and extracting frames the GPU is not used at all (CPU 100%).

If I go to the terminal and type nvidia-smi CUDA version appear to be 12.6
Even more confusing, if I go to the Environment Variables CUDA_PATH gives version 12.4

I tried deleting everything and re-installing but I cannot manage to have a "unified" version of CUDA, cudnn and torch working.

**Comment by n-poulsen** [comment]
Hi @PetraMocellin! The GPU is not used when extracting frames; the CUDA toolkit is only used for deep learning related code, which means that your GPU will be used when training models, evaluating them or running inference on videos. As `torch.cuda.is_available()` returns `True`, you've installed PyTorch correctly and the GPU will be used correctly.

**Comment by PetraMocellin** [comment]
Hi @n-poulsen 
Indeed in the task manager I do see the GPU being used for training, but not in the terminal if I type nvidia-smi. That's why I thought there may be issues with the versions of cuda. 

Moreover, with batch size of 4 or 8 the GPU memory is constantly at 100%. Should I be concerned or it does not matter at all?

Thanks!
