### ISSUE TITLE
Analyze Videos GUI Bug? 3.0.0rc1

### ISSUE THREAD

**Issue by dlhagger** [DeepLabCut/DeepLabCut#2646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When using the GUI to analyze videos after training and evaluation, when clicking plot trajectories box, the options remain bodypart1,2,3, and objectA which are the default values. Even though they are updated in the config.yaml file, they are not updating in the GUI. Picture for reference attached.

![Screenshot 2024-07-01 at 4 03 43 PM](https://github.com/DeepLabCut/DeepLabCut/assets/44274286/60cb8b77-0680-4906-a281-7d5fbd953822)

<img width="1129" alt="Screenshot 2024-07-01 at 4 03 38 PM" src="https://github.com/DeepLabCut/DeepLabCut/assets/44274286/0a6f64be-1e80-4f2f-a9bf-46545867eda2">

### Operating System

operating system

MacOS 15.0

### DeepLabCut version

dlc version

3.0.0rc1

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by li1901** [comment]
I meat the same problem .
<img width="786" alt="1a9af6e4db07ff15fb60120c25f92c2" src="https://github.com/DeepLabCut/DeepLabCut/assets/49360142/932751ee-7831-474a-9286-35a7b3b6ed1e">
<img width="783" alt="0fb477283cf1841a85610cf9d7c29c1" src="https://github.com/DeepLabCut/DeepLabCut/assets/49360142/49e2c292-f731-4d33-a848-6f0dbf6f2897">

**Comment by MMathisLab** [comment]
fixed @dlhagger please re-pull the branch!
