### ISSUE TITLE
run annotations on each browser

### ISSUE THREAD

**Issue by KeiPome** [DeepLabCut/DeepLabCut#2647]
I want to  run DLC on colb only. but now we have to annot on our own pc.

**Comment by n-poulsen** [comment]
Hi @KeiPome, am I correct that you want to run DeepLabCut only on Google COLAB, with no installation on your own computer?

While you can run all of the deep learning parts of the code (training, evaluation, video analysis, ...) on COLAB, the GUI used to annotate the images needed to train the models must be installed locally (as it's not a browser-based application). You can do so by simply running `pip install deeplabcut[gui]` in a local conda environment.

You can annotate the data locally, and then upload the project folder to Google Drive to train in COLAB.

If you have issues in the future, please use the provided template to formulate them.
