### ISSUE TITLE
3D reconstruction

### ISSUE THREAD

**Issue by caniko** [DeepLabCut/DeepLabCut#265]
**Your Operating system and DeepLabCut version**
Windows 10; Anaconda ENV; DeepLabCut 2.x.

**Describe the solution you'd like**
Could you make a guide on how to setup a 3d reconstruction pipeline.

I am currently working on it myself, and using this as [guide](https://docs.opencv.org/2.4.9/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html). I am interested in exactly how you implemented it, hence my request.

Thank you

**Comment by MMathisLab** [comment]
we will include a notebook when the paper is published (in about 1 month). As is posted on the Image Forum, here are tips to get you started: https://forum.image.sc/t/reconstruct-3d-from-2d-images/22514/5?u=mwmathis

**Comment by AlexEMG** [comment]
Basically the pipeline is:
- calibrate your cameras with OpenCV
- undistort images with OpenCV, run DLC
- use DLC 2d-predictions + OpenCV triangulation for 3D estimates
