### ISSUE TITLE
AttributeError: module 'deeplabcut' has no attribute 'pose_estimation_tensorflow'. Did you mean: 'pose_estimation_pytorch'? DLC 3.0.0rc1 GUI

### ISSUE THREAD

**Issue by JLluck** [DeepLabCut/DeepLabCut#2654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

After processing my videos (which appear to have been processed) the "Unsupervised ID Tracking with Transformers" step in the GUI just hangs and doesn't do anything. Additionally, if I try to skip this step the Create Video function also does not work.

### Operating System

Mac OS Sonoma 14.5 on an M1 MacBook Air. 

### DeepLabCut version

3.0.0rc1

### DeepLabCut mode

single animal

### Device type

Apple M1 chip in a MacBook Air. 

### Steps To Reproduce

- conda activate new_dlc_env
- python -m deeplabcut 

### Relevant log output

```shell
Loading DLC 3.0.0rc1...
Starting GUI...
QPixmap::scaled: Pixmap is a null pixmap
Traceback (most recent call last):
  File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/site-packages/deeplabcut/gui/window.py", line 359, in <lambda>
    QTimer.singleShot(1000, lambda: _check_for_updates(silent=True))
  File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/site-packages/deeplabcut/gui/window.py", line 66, in _check_for_updates
    update_btn = msg.addButton("Update", msg.AcceptRole)
AttributeError: 'PySide6.QtWidgets.QMessageBox' object has no attribute 'AcceptRole'. Did you mean: 'acceptDrops'?
Traceback (most recent call last):
  File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/site-packages/deeplabcut/gui/utils.py", line 22, in run
    self.func()
  File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/site-packages/deeplabcut/pose_tracking_pytorch/apis.py", line 97, in transformer_reID
    deeplabcut.pose_estimation_tensorflow.create_tracking_dataset(
AttributeError: module 'deeplabcut' has no attribute 'pose_estimation_tensorflow'. Did you mean: 'pose_estimation_pytorch'?
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @JLluck, did you run "analyze videos" on your video first?

**Comment by JLluck** [comment]
I did - I got these output files. 
<img width="743" alt="Screenshot 2024-07-05 at 9 19 10 AM" src="https://github.com/DeepLabCut/DeepLabCut/assets/33733493/acf850e2-d77e-4838-b6a6-62b44528b474">

**Comment by JLluck** [comment]
I reran the video "analyze video" to test it again and it still creates the files, but I get the following errors in terminal. (The GUI hangs at this point but if I restart the program, I can skip to the unsupervised ID tracking but then I get the "AttributeError: module 'deeplabcut' has no attribute 'pose_estimation_tensorflow'. Did you mean: 'pose_estimation_pytorch'?" from above. 

Below is the output: 

Starting GUI...
QPixmap::scaled: Pixmap is a null pixmap
Traceback (most recent call last):
  File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/site-packages/deeplabcut/gui/window.py", line 359, in <lambda>
    QTimer.singleShot(1000, lambda: _check_for_updates(silent=True))
  File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/site-packages/deeplabcut/gui/window.py", line 66, in _check_for_updates
    update_btn = msg.addButton("Update", msg.AcceptRole)
AttributeError: 'PySide6.QtWidgets.QMessageBox' object has no attribute 'AcceptRole'. Did you mean: 'acceptDrops'?
INFO:console:Analyzing videos with /Users/Desktop/Projects/Slugs_1-2024-06-15/dlc-models-pytorch/iteration-0/Slugs_1Jun15-trainset95shuffle1/train/snapshot-200.pt
INFO:console:  -> Using detector /Users/Desktop/Projects/Slugs_1-2024-06-15/dlc-models-pytorch/iteration-0/Slugs_1Jun15-trainset95shuffle1/train/snapshot-detector-300.pt
INFO:console:Starting to analyze /Users/Desktop/Projects/Slugs_1-2024-06-15/videos/0-8_hrs_short_compressed.mp4
INFO:console:Video metadata: 
  Overall # of frames:    17
  Duration of video [s]:  0.57
  fps:                    30.0
  resolution:             w=3840, h=2160

INFO:console:Running Detector
100%|███████████████████████████████████████████| 17/17 [00:11<00:00,  1.44it/s]
  0%|                                                    | 0/17 [00:00<?, ?it/s]INFO:console:Running Pose Prediction
100%|███████████████████████████████████████████| 17/17 [00:56<00:00,  3.33s/it]
INFO:console:Saving results in /Users/Desktop/Projects/Slugs_1-2024-06-15/videos/0-8_hrs_short_compressedDLC_AnimaltokenposeBase_Slugs_1Jun15shuffle1_detector_300_snapshot_200.h5 and /Users/Desktop/Projects/Slugs_1-2024-06-15/videos/0-8_hrs_short_compressedDLC_AnimaltokenposeBase_Slugs_1Jun15shuffle1_detector_300_snapshot_200_full.pickle
INFO:console:Processing... 
INFO:console: 
INFO:console:/Users/Desktop/Projects/Slugs_1-2024-06-15/videos/0-8_hrs_short_compressed.mp4
INFO:console:Loading From None/0-8_hrs_short_compressedDLC_AnimaltokenposeBase_Slugs_1Jun15shuffle1_detector_300_snapshot_200.h5
Traceback (most recent call last):
  File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/site-packages/deeplabcut/utils/auxfun_multianimal.py", line 217, in LoadFullMultiAnimalData
    with open(data_file, "rb") as handle:
FileNotFoundError: [Errno 2] No such file or directory: 'None/0-8_hrs_short_compressedDLC_AnimaltokenposeBase_Slugs_1Jun15shuffle1_detector_300_snapshot_200_full.pickle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/site-packages/deeplabcut/gui/utils.py", line 22, in run
    self.func()
  File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/site-packages/deeplabcut/compat.py", line 851, in analyze_videos
    return analyze_videos(
  File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/analyze_videos.py", line 375, in analyze_videos
    convert_detections2tracklets(
  File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/convert_detections_to_tracklets.py", line 123, in convert_detections2tracklets
    data, metadata = auxfun_multianimal.LoadFullMultiAnimalData(str(data_filename))
  File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/site-packages/deeplabcut/utils/auxfun_multianimal.py", line 220, in LoadFullMultiAnimalData
    data = shelve.open(data_file, flag="r")
  File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/dbm/__init__.py", line 85, in open
    raise error[0]("db file doesn't exist; "
dbm.error: db file doesn't exist; use 'c' or 'n' flag to create a new db

**Comment by JLluck** [comment]
Initially the video file appeared have corrupted metadata as it appeared to have an incorrect number of frames. I compressed the same file using as noted on the instructions for this on the DLC site. 

ffmpeg -i "/Users/Desktop/Projects/Slugs_1-2024-06-15/videos/0-8_hrs_short.mp4" -c:v h264 -crf 18 -preset fast "/Users/Desktop/Projects/Slugs_1-2024-06-15/videos/0-8_hrs_short_compressed.mp4"

It solved the incorrect frame number issue but still gives me the output above and prevents me from moving forward with the Unsupervised ID tracking.

**Comment by ipconfig2316** [comment]
> I reran the video "analyze video" to test it again and it still creates the files, but I get the following errors in terminal. (The GUI hangs at this point but if I restart the program, I can skip to the unsupervised ID tracking but then I get the "AttributeError: module 'deeplabcut' has no attribute 'pose_estimation_tensorflow'. Did you mean: 'pose_estimation_pytorch'?" from above.
> 
> Below is the output:
> 
> Starting GUI... QPixmap::scaled: Pixmap is a null pixmap Traceback (most recent call last): File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/site-packages/deeplabcut/gui/window.py", line 359, in QTimer.singleShot(1000, lambda: _check_for_updates(silent=True)) File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/site-packages/deeplabcut/gui/window.py", line 66, in _check_for_updates update_btn = msg.addButton("Update", msg.AcceptRole) AttributeError: 'PySide6.QtWidgets.QMessageBox' object has no attribute 'AcceptRole'. Did you mean: 'acceptDrops'? INFO:console:Analyzing videos with /Users/Desktop/Projects/Slugs_1-2024-06-15/dlc-models-pytorch/iteration-0/Slugs_1Jun15-trainset95shuffle1/train/snapshot-200.pt INFO:console: -> Using detector /Users/Desktop/Projects/Slugs_1-2024-06-15/dlc-models-pytorch/iteration-0/Slugs_1Jun15-trainset95shuffle1/train/snapshot-detector-300.pt INFO:console:Starting to analyze /Users/Desktop/Projects/Slugs_1-2024-06-15/videos/0-8_hrs_short_compressed.mp4 INFO:console:Video metadata: Overall # of frames: 17 Duration of video [s]: 0.57 fps: 30.0 resolution: w=3840, h=2160
> 
> INFO:console:Running Detector 100%|███████████████████████████████████████████| 17/17 [00:11<00:00, 1.44it/s] 0%| | 0/17 [00:00<?, ?it/s]INFO:console:Running Pose Prediction 100%|███████████████████████████████████████████| 17/17 [00:56<00:00, 3.33s/it] INFO:console:Saving results in /Users/Desktop/Projects/Slugs_1-2024-06-15/videos/0-8_hrs_short_compressedDLC_AnimaltokenposeBase_Slugs_1Jun15shuffle1_detector_300_snapshot_200.h5 and /Users/Desktop/Projects/Slugs_1-2024-06-15/videos/0-8_hrs_short_compressedDLC_AnimaltokenposeBase_Slugs_1Jun15shuffle1_detector_300_snapshot_200_full.pickle INFO:console:Processing... INFO:console: INFO:console:/Users/Desktop/Projects/Slugs_1-2024-06-15/videos/0-8_hrs_short_compressed.mp4 INFO:console:Loading From None/0-8_hrs_short_compressedDLC_AnimaltokenposeBase_Slugs_1Jun15shuffle1_detector_300_snapshot_200.h5 Traceback (most recent call last): File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/site-packages/deeplabcut/utils/auxfun_multianimal.py", line 217, in LoadFullMultiAnimalData with open(data_file, "rb") as handle: FileNotFoundError: [Errno 2] No such file or directory: 'None/0-8_hrs_short_compressedDLC_AnimaltokenposeBase_Slugs_1Jun15shuffle1_detector_300_snapshot_200_full.pickle'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/site-packages/deeplabcut/gui/utils.py", line 22, in run self.func() File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/site-packages/deeplabcut/compat.py", line 851, in analyze_videos return analyze_videos( File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/analyze_videos.py", line 375, in analyze_videos convert_detections2tracklets( File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/convert_detections_to_tracklets.py", line 123, in convert_detections2tracklets data, metadata = auxfun_multianimal.LoadFullMultiAnimalData(str(data_filename)) File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/site-packages/deeplabcut/utils/auxfun_multianimal.py", line 220, in LoadFullMultiAnimalData data = shelve.open(data_file, flag="r") File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/shelve.py", line 243, in open return DbfilenameShelf(filename, flag, protocol, writeback) File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/shelve.py", line 227, in **init** Shelf.**init**(self, dbm.open(filename, flag), protocol, writeback) File "/Users/miniconda3/envs/new_dlc_env/lib/python3.10/dbm/**init**.py", line 85, in open raise error[0]("db file doesn't exist; " dbm.error: db file doesn't exist; use 'c' or 'n' flag to create a new db

I get the same error when analyzing my videos. I hope there is a solution to this.

**Comment by MMathisLab** [comment]
please re-install! fixed: https://github.com/DeepLabCut/DeepLabCut/pull/2691
