### ISSUE TITLE
dlc3.0 cannot find 'pose_estimation_pytorch/config/dlcrnet/dlcrnet_ms5.yaml' when creating training data

### ISSUE THREAD

**Issue by chz31** [DeepLabCut/DeepLabCut#2655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I installed deeplabcut 3.0 with pytorch in both Windows 11 and Ubuntu 22.04 in WSL2 in Windows 11 following the instruction here: https://github.com/DeepLabCut/DeepLabCut/issues/2644#issuecomment-2203795883. I created a project and labeled video. However, when I tried to create a training dataset by simply running `deeplabcut.create_multianimaltraining_dataset(config_path)`

It showed below error.
`No such file or directory: '/home/chz31/anaconda3/envs/deeplabcut3/lib/python3.11/site-packages/deeplabcut/pose_estimation_pytorch/config/dlcrnet/dlcrnet_ms5.yaml'`

Just by looking at the pytorch-dlc branch, the location only has `dlcrnet_stride16_ms5.yaml `and `dlcrnet_stride17_ms5.yaml`

Using `conda env create -f DEEPLABCUT.yaml` produced the same error.

### Operating System

Windows 11 and Ubuntu 22.04 WSL2 in Windows 11

### DeepLabCut version

deeplabcut 3.0 with pytorch

### DeepLabCut mode

multi animal

### Device type

GPU should be able to be accessed.  `python -c "import torch;print(torch.cuda.is_available())` returns `True`.

### Relevant log output

```shell
FileNotFoundError                         Traceback (most recent call last)
Cell In[8], line 1
----> 1 deeplabcut.create_multianimaltraining_dataset(config_path)

File ~/anaconda3/envs/deeplabcut3/lib/python3.11/site-packages/deeplabcut/generate_training_dataset/multiple_individuals_trainingsetmanipulation.py:581, in create_multianimaltraining_dataset(config, num_shuffles, Shuffles, windows2linux, net_type, numdigits, crop_size, crop_sampling, paf_graph, trainIndices, testIndices, n_edges_threshold, paf_graph_degree, userfeedback, weight_init, engine)
    574         pytorch_cfg = make_super_animal_finetune_config(
    575             project_config=cfg,
    576             pose_config_path=path_train_config,
    577             net_type=net_type,
    578             weight_init=weight_init,
    579         )
    580     else:
--> 581         pytorch_cfg = make_pytorch_pose_config(
    582             project_config=cfg,
    583             pose_config_path=path_train_config,
    584             net_type=net_type,
    585             top_down=top_down,
    586             weight_init=weight_init,
    587         )
    589     auxiliaryfunctions.write_plainconfig(pose_cfg_path, pytorch_cfg)
    591 print(
    592     "The training dataset is successfully created. Use the function 'train_network' to start training. Happy training!"
    593 )

File ~/anaconda3/envs/deeplabcut3/lib/python3.11/site-packages/deeplabcut/pose_estimation_pytorch/config/make_pose_config.py:107, in make_pytorch_pose_config(project_config, pose_config_path, net_type, top_down, weight_init)
    104         default_value_kwargs.update(_get_paf_parameters(project_config, bodyparts))
    106     cfg_path = configs_dir / architecture / f"{net_type}.yaml"
--> 107     model_cfg = read_config_as_dict(cfg_path)
    108     model_cfg = replace_default_values(
    109         model_cfg,
    110         num_bodyparts=len(bodyparts),
    111         num_individuals=len(individuals),
    112         **default_value_kwargs,
    113     )
    115 is_top_down = model_cfg.get("method", "BU").upper() == "TD"

File ~/anaconda3/envs/deeplabcut3/lib/python3.11/site-packages/deeplabcut/pose_estimation_pytorch/config/utils.py:186, in read_config_as_dict(config_path)
    178 def read_config_as_dict(config_path: str | Path) -> dict:
    179     """
    180     Args:
    181         config_path: the path to the configuration file to load
   (...)
    184         The configuration file with pure Python classes
    185     """
--> 186     with open(config_path, "r") as f:
    187         cfg = YAML(typ='safe', pure=True).load(f)
    189     return cfg

FileNotFoundError: [Errno 2] No such file or directory: '/home/chz31/anaconda3/envs/deeplabcut3/lib/python3.11/site-packages/deeplabcut/pose_estimation_pytorch/config/dlcrnet/dlcrnet_ms5.yaml'
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @chz31, thanks for reporting this I'll look into reproducing it

**Comment by chz31** [comment]
> Hi @chz31, thanks for reporting this I'll look into reproducing it

Thank you! I did the conda installation and got the same issue. `print(torch.cuda.is_available())` did report TRUE.

**Comment by n-poulsen** [comment]
@chz31 As you mentioned, this error is because we changed the naming from `dlcrnet_ms5` to specify the backbone stride. I'll open a pull request to make this backwards compatible. 

You can fix this error immediately by changing the `default_net_type` in your project configuration to `dlcrnet_stride16_ms5` or creating your training dataset with

```python
deeplabcut.create_training_dataset(
    config="...",
    net_type="dlcrnet_stride16_ms5",
)
```

You can also try some of our new multi-animal model architectures (e.g. `dekr_w32`, `top_down_resnet_50`, `top_down_hrnet_w32`) :)
