### ISSUE TITLE
Problem in creating labeled videos DLC 2.3.10

### ISSUE THREAD

**Issue by Salmanzubedat** [DeepLabCut/DeepLabCut#2656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I recently installed DLC through Anaconda environment, through this link:
https://deeplabcut.github.io/DeepLabCut/docs/beginner-guides/beginners-guide.html
as well as the suitable PyTorch.
and the Stable release, using: pip install "deeplabcut[gui,modelzoo,tf]"
all the steps worked fine [extracting frames, labeling, training, analyzing (plotting the coordinates from the .csv file looks ok)]  but I can't create the labeled video. I get the following error in the GUI:
"Plots could not be created for C:\.... videos were not evaluated with the current scorer DLC_resnet50...."

What could be the problem?
![dlc 3](https://github.com/DeepLabCut/DeepLabCut/assets/174943387/d11045d9-1322-49eb-a158-d8c75d891e82)
![dlc 4](https://github.com/DeepLabCut/DeepLabCut/assets/174943387/136882ab-bf67-4da3-b5e8-40539ccf7164)

### Operating System

operating system Windows 10

### DeepLabCut version

dlc version 2.3.10

### DeepLabCut mode

single animal

### Device type

GPU: nvidia gtx 1650 super
Driver installed 462.59

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @Salmanzubedat - I believe this is might be a bug with the GUI (thinking "filtered data" is selected). Could you please share the full error message that's printed (it should be printed in the anaconda prompt)?

**Comment by Salmanzubedat** [comment]
Thanks for your answer,
There is nothing written in the prompt, only the warning at the bottom of the GUI.
![dlc_b1](https://github.com/user-attachments/assets/7526b2e6-e686-4d54-bcf1-0f4c21f15871)
![dlc_b2](https://github.com/user-attachments/assets/6843c1f2-30b6-42c1-90df-9dd14ea048f8)

I tried to select/unselect all of the other options, and there was no response.
Salman

BTW:
1- Attached the output printed in the prompt during analyzing this video:
![dlc analysis2](https://github.com/user-attachments/assets/df658834-b423-4734-9ff5-06a3d2220104)

2- In other project, using the multi-animal project, The option for creating a labeled video is already optional in the analysis Tab, and this option worked well.

**Comment by Salmanzubedat** [comment]
@n-poulsen 
Could you help please?

**Comment by n-poulsen** [comment]
Hi @Salmanzubedat - sorry for the slow response. Could you try using `ipython` to create the labeled videos? This should output a full stack trace that I can use to figure out what's happening. You can open an `ipython` shell by typing `ipython` in your Anaconda prompt, and then:

```python
import deeplabcut

config = r"C:\Users\new\DLC Projects\One_animal_sal-Salman-2024-07-06\config.yaml"
deeplabcut.create_labeled_video(
    config,
    ["C:\Users\new\DLC Projects\One_animal_sal-Salman-2024-07-06\videos\20240214_124150_ERC_dDG1_Day7_alone\trial0000_cams.avi"]
)
```

**Comment by Salmanzubedat** [comment]
Thanks for the response.
