### ISSUE TITLE
problem while refining outlier frames 

### ISSUE THREAD

**Issue by ghost** [DeepLabCut/DeepLabCut#266]
**Your Operating system and DeepLabCut version**
 Ubuntu 16.04 LTS, Anaconda Env, DeepLabCut2.0

**Describe the problem**
after extracting outlier frames I started to refine them using the GUI. I had to stop in the middle of the refinement process, so I saved the GUI and closed it.
 when entering the GUI again in order to finish the frames refinement, after loading the
 'machinelabelsiter0.h5' file from the folder labeled video, I can't see the frames that iv'e already edited and I have to refine all the frames all over again.

I tried also to merge the dataset after refining part of the frames, and even though the iteration changed in the config file I still can't load the outlier frames in a way that i'll be able to see the editted frames and continue from the point I stopped earlier.

(I can't refine all the labels in one time due to a bug in the GUI that makes it stuck and forces me to exit the GUI and opening it again).

**How to Reproduce the problem**
1. extract_outlier_frames with method 'jump'
2. refine_labels
3. saving the GUI and closing it 
4. merge_dataset
5. refine_labels

**Comment by MMathisLab** [comment]
yes, as you are opening the machine-labeled file, with the relabeling GUI you can either finish it in one go, or you save. Then everything is transferred to the CollectedData_userxyz.h5 file and thus can be edited with the labeling GUI (if there are already some labeled frames then the new ones will be added)

**Comment by AlexEMG** [comment]
So in other words, **saving** saves the machine-labeled file into CollectedData... including the "uncorrected frames".

**Comment by MMathisLab** [comment]
could you tell me more about this?

>  "due to a bug in the GUI that makes it stuck"

If you can take a screen capture, that would be useful... We don't have this behavior.
