### ISSUE TITLE
Major identity swaps 

### ISSUE THREAD

**Issue by qarden** [DeepLabCut/DeepLabCut#2662]
Hello,

I am using Deeplabcut to track two C57 black mice, one is test one is sham, in an openfield. I am having couple of major identity swaps in the videos. An example, in the one of my videos test mouse starts as animal 1 and it swaps to animal 2 at 2nd min and it swaps back at 4th min. 
They are so similar mice and we cant do anything to make them look different except tail marking. Is there anything to fix this swaps in the refinement function? I tried it but it is impossible to change all the frames one by one. Is there any function to fix it as a bulk? I wrote a matlab code to fix the CSV files and using it before Simba. It would be useful if there is something like that in the GUI.

Thanks!

**Comment by jeylau** [comment]
Hi @qarden, could you please fill the issue template? This helps us determine (among other things) what version of DeepLabCut you're running. Are you tracking your animals with `identity=True`? If so, were your mice labeled consistently according to the tail marking?
