### ISSUE TITLE
Automatic save model snapshots with best test error in DLC3.0

### ISSUE THREAD

**Issue by tom21100227** [DeepLabCut/DeepLabCut#2663]
**Is your feature request related to a problem? Please describe.**
In the new dlc3.0.0 release with PyTorch, some metrics are displayed after every epoch (test error / test recall/precision). But the model snapshots are saved solely on iteration/step/epoch numbers. When going through the logs I can see (for example) the metrics after epoch 178 is performing really well, but the only snapshots of models I have is 175 or 200. 

**Describe the solution you'd like**
Having an additional option during `train_network` that allows DLC to save the 5 model snapshots with the best `metrics/test.rmse` or the best `metrics/test.mAP_pcutoff`. 

**Describe alternatives you've considered**
I could make save epoch being 1 and just save all model snapshots after every epoch to cherry pick. But that would take up a lot of storage space and still kind of frustrating to navigate through a sea of snapshots. 

**Additional context**
N/A

**Comment by n-poulsen** [comment]
Hi @tom21100227! I think that's a good idea - we're working on adding this to the code
