### ISSUE TITLE
Snapshot Files Not Detected Due to Prefix Mismatch  Description

### ISSUE THREAD

**Issue by Chap5732** [DeepLabCut/DeepLabCut#2665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I encountered an issue while evaluating my model using DeepLabCut. Despite having snapshot files in the specified directory, the program reports that no snapshots were found. 
![1720818152226](https://github.com/user-attachments/assets/b50f66a5-3de0-4b23-bdd2-a67008c82166)

The detailed error message is as follows:
ValueError: Found 0 snapshots in C:\Users\lgx\OneDrive\work\LiAnglab\TrackingProgram\Oppa'sTracker-Oppa-2024-07-10\dlc-models-pytorch\iteration-0\Oppa'sTrackerJul10-trainset90shuffle1\train (with names []) with prefix snapshot. Could not return snapshot with index -1.

### Operating System

Win11

### DeepLabCut version

3.0.0.rc2

### DeepLabCut mode

multi animal

### Device type

nvidia rtx 3060

### Relevant log output

```shell

Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.02s).
Accumulating evaluation results...
DONE (t=0.01s).
Plot predictions ENABLED
Traceback (most recent call last):
  File "C:\Users\lgx\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\gui\tabs\evaluate_network.py", line 207, in evaluate_network
    deeplabcut.evaluate_network(
  File "C:\Users\lgx\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\compat.py", line 471, in evaluate_network
    return evaluate_network(
  File "C:\Users\lgx\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_pytorch\apis\evaluate.py", line 415, in evaluate_network
    snapshots = get_model_snapshots(
  File "C:\Users\lgx\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut\pose_estimation_pytorch\apis\utils.py", line 175, in get_model_snapshots
    raise ValueError(
ValueError: Found 0 snapshots in C:\Users\lgx\OneDrive\work\LiAnglab\TrackingProgram\Oppa'sTracker-Oppa-2024-07-10\dlc-models-pytorch\iteration-0\Oppa'sTrackerJul10-trainset90shuffle1\train (with names []) with prefix snapshot. Could not return snapshot with index -1.
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @Chap5732 - in your directory you have snapshots for the object detector of a top-down pose model - but no pose model trained. To use `evaluate_network`, you'll need to train a pose model as well.

How did you train the model exactly?

**Comment by rrr9444** [comment]
請問如何解決

**Comment by Youngzooo** [comment]
I meet the same question. May I ask how it was resolved?

**Comment by n-poulsen** [comment]
@Youngzooo do you have any trained models in your shuffle's folder?

**Comment by Youngzooo** [comment]
@n-poulsen I trained the model according to the default settings, but only snapshot-detector in the folder. 
![e1f230b733bf566b3d6e3ee83a9dc0ce](https://github.com/user-attachments/assets/fd292119-56bf-47e2-bc39-d823872a2980)

**Comment by n-poulsen** [comment]
You only have snapshots for your object detection model. Did you also train a pose estimation model? If so, did the training fail (you can see that in the `train.txt` file which should contain training logs)
