### ISSUE TITLE
deeplabcut.filterpredictions failing when passing a list

### ISSUE THREAD

**Issue by dlhagger** [DeepLabCut/DeepLabCut#2669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When passing a list of videos to filterpredictions only the first element in the list is filtered, and the other elements are wrongly saying there are no unfiltered predictions to filter. 

<img width="982" alt="Screenshot 2024-07-15 at 10 32 25 AM" src="https://github.com/user-attachments/assets/16ce1680-f396-44f1-9ad8-ca1a1887b754">

When you pass an element of the list, it works correctly. Screenshots below to describe.

<img width="962" alt="Screenshot 2024-07-15 at 10 32 37 AM" src="https://github.com/user-attachments/assets/8ea64679-0de8-47db-8d1c-acd0cf1a5776">

Also returning a future warning they may or may not be related 

FutureWarning: Starting with pandas version 3.0 all arguments of to_hdf except for the argument 'path_or_buf' will be keyword-only.
  data.to_hdf(outdataname, "df_with_missing", format="table", mode="w")

### Operating System

operating system MacOS 14.5

### DeepLabCut version

dlc version 3.0.01rc2

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
Hello @dlhagger, good catch. I've just spotted a bug in the code, which I'll fix right now. Meanwhile, you should be able to specify a path to your video folder, and all videos within should be correctly found.
