### ISSUE TITLE
why increase learning rate after 10000 iteration  

### ISSUE THREAD

**Issue by Jerry-Jincheng** [DeepLabCut/DeepLabCut#267]
** Operating system and DeepLabCut version**

OS and Deeplabcut version : Ubuntu 18.04 LTS, with an Anaconda Env, & DeepLabCut 2.0.

**Describe the problem**

I found the training rate increased from 0.005 to 0.02 after iteration reached 10000. Normally learning rate decreases as iteration increases. I found  it was caused by the parameter of `multi_step` in `pose_cfg.ymal` as follows
` multi_step`:
 -[  0.005,  10000]
 -[ 0.02,  430000]
 -[ 0.002, 730000]
 -[0.001, 1030000 ]

Is there a good reason for that or it is typing error in the code?

**Comment by MMathisLab** [comment]
Not a typo. This was validated to work best (all videos you see on our website used this for training).

**Comment by AlexEMG** [comment]
Initially the learning rate is kept low for stability.

**Comment by lauraangeja** [comment]
could you further explain why you choose to inscrease it nd then lower it again? I am doing my thesis using DLC and i would like to understand why this parameter is set like this. Thank you in advance!
