### ISSUE TITLE
Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.7.3' currently installed).

### ISSUE THREAD

**Issue by dlhagger** [DeepLabCut/DeepLabCut#2674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Clean environment install of  DLC 3.0.0rc2 and getting the following error when opening the GUI (same error throws in command line as well, without the pixelmap error). 

![image](https://github.com/user-attachments/assets/b591b88b-17ea-401e-a960-8b7ef9754bc2)

![image](https://github.com/user-attachments/assets/343a9b50-1b1c-4f22-adb6-54e74c172e75)

Double checking mamba & pip list and numexpr is 2.7.3

Trying to force the package to 2.8.4 is not allowed because itll break pytorch (I used CUDA version 11.8 as suggested on the install docs)

### Operating System

operating system  Win 11

### DeepLabCut version

dlc version rc2

### DeepLabCut mode

single animal

### Device type

gpu 4060 TI

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @dlhagger - could you please let me know which package versions you have installed (the output of `pip list` would do).

I've had some difficulties with `pandas` due to the release of `numpy 2.0` recently, but have always been able to fix them (and haven't had this particular issue).

Currently the environment I'm using has:

```
pandas                        2.2.2
numexpr                       2.8.7
```

Which version of PyTorch do you have installed?

**Comment by dlhagger** [comment]
# Name                    Version                   Build  Channel
alabaster                 0.7.16                   pypi_0    pypi
albumentations            1.4.3                    pypi_0    pypi
app-model                 0.2.7                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
babel                     2.15.0                   pypi_0    pypi
blas                      2.112                       mkl    conda-forge
blas-devel                3.9.0              12_win64_mkl    conda-forge
blosc                     1.21.6               h85f69ea_0    conda-forge
brotli-python             1.1.0           py310h00ffb61_1    conda-forge
build                     1.2.1                    pypi_0    pypi
bzip2                     1.0.8                h2466b09_7    conda-forge
c-blosc2                  2.12.0               h183a6f4_0    conda-forge
ca-certificates           2024.7.4             h56e8100_0    conda-forge
cachey                    0.2.1                    pypi_0    pypi
certifi                   2024.7.4           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py310h8d17308_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7                    pypi_0    pypi
cloudpickle               3.0.0                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
comm                      0.2.2                    pypi_0    pypi
contourpy                 1.2.1                    pypi_0    pypi
cuda-cccl                 12.5.39                       0    nvidia
cuda-cccl_win-64          12.5.39                       0    nvidia
cuda-cudart               12.1.105                      0    nvidia
cuda-cudart-dev           12.1.105                      0    nvidia
cuda-cupti                12.1.105                      0    nvidia
cuda-libraries            12.1.0                        0    nvidia
cuda-libraries-dev        12.1.0                        0    nvidia
cuda-nvrtc                12.1.105                      0    nvidia
cuda-nvrtc-dev            12.1.105                      0    nvidia
cuda-nvtx                 12.1.105                      0    nvidia
cuda-opencl               12.5.39                       0    nvidia
cuda-opencl-dev           12.5.39                       0    nvidia
cuda-profiler-api         12.5.39                       0    nvidia
cuda-runtime              12.1.0                        0    nvidia
cuda-version              12.5                          3    nvidia
cycler                    0.12.1                   pypi_0    pypi
dask                      2024.7.0                 pypi_0    pypi
dask-expr                 1.1.7                    pypi_0    pypi
dask-image                2024.5.3                 pypi_0    pypi
debugpy                   1.8.2                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
deeplabcut                3.0.0rc2                 pypi_0    pypi
dlclibrary                0.0.6                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
docstring-parser          0.16                     pypi_0    pypi
docutils                  0.17.1                   pypi_0    pypi
einops                    0.8.0                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
filelock                  3.15.4             pyhd8ed1ab_0    conda-forge
filterpy                  1.4.5                    pypi_0    pypi
flexcache                 0.3                      pypi_0    pypi
flexparser                0.3.1                    pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
freetype                  2.12.1               hdaf720e_2    conda-forge
freetype-py               2.4.0                    pypi_0    pypi
fsspec                    2024.6.1                 pypi_0    pypi
git                       2.45.2               h57928b3_1    conda-forge
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.43                   pypi_0    pypi
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
hdf5                      1.14.3          nompi_h2b43c12_105    conda-forge
heapdict                  1.0.1                    pypi_0    pypi
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
hsluv                     5.0.4                    pypi_0    pypi
huggingface-hub           0.23.5                   pypi_0    pypi
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
imageio                   2.34.2                   pypi_0    pypi
imageio-ffmpeg            0.5.1                    pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
importlib-metadata        8.0.0                    pypi_0    pypi
in-n-out                  0.2.1                    pypi_0    pypi
intel-openmp              2021.4.0                 pypi_0    pypi
ipykernel                 6.29.5                   pypi_0    pypi
ipython                   8.26.0                   pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
joblib                    1.4.2                    pypi_0    pypi
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
jupyter-client            8.6.2                    pypi_0    pypi
jupyter-core              5.7.2                    pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
krb5                      1.21.3               hdf4eb48_0    conda-forge
lazy-loader               0.4                      pypi_0    pypi
lcms2                     2.16                 h67d730c_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libaec                    1.1.3                h63175ca_0    conda-forge
libblas                   3.9.0              12_win64_mkl    conda-forge
libcblas                  3.9.0              12_win64_mkl    conda-forge
libcublas                 12.1.0.26                     0    nvidia
libcublas-dev             12.1.0.26                     0    nvidia
libcufft                  11.0.2.4                      0    nvidia
libcufft-dev              11.0.2.4                      0    nvidia
libcurand                 10.3.6.82                     0    nvidia
libcurand-dev             10.3.6.82                     0    nvidia
libcurl                   8.8.0                hd5e4a3a_1    conda-forge
libcusolver               11.4.4.55                     0    nvidia
libcusolver-dev           11.4.4.55                     0    nvidia
libcusparse               12.0.2.55                     0    nvidia
libcusparse-dev           12.0.2.55                     0    nvidia
libdeflate                1.20                 hcfcfb64_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libhwloc                  2.11.1          default_h8125262_1000    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
liblapack                 3.9.0              12_win64_mkl    conda-forge
liblapacke                3.9.0              12_win64_mkl    conda-forge
libnpp                    12.0.2.50                     0    nvidia
libnpp-dev                12.0.2.50                     0    nvidia
libnvjitlink              12.1.105                      0    nvidia
libnvjitlink-dev          12.1.105                      0    nvidia
libnvjpeg                 12.1.1.14                     0    nvidia
libnvjpeg-dev             12.1.1.14                     0    nvidia
libpng                    1.6.43               h19919ed_0    conda-forge
libsqlite                 3.46.0               h2466b09_0    conda-forge
libssh2                   1.11.0               h7dfc565_0    conda-forge
libtiff                   4.6.0                hddb2be6_3    conda-forge
libuv                     1.48.0               hcfcfb64_0    conda-forge
libwebp-base              1.4.0                hcfcfb64_0    conda-forge
libxcb                    1.16                 hcd874cb_0    conda-forge
libxml2                   2.12.7               h0f24e4e_4    conda-forge
libzlib                   1.3.1                h2466b09_1    conda-forge
llvmlite                  0.43.0                   pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
lz4-c                     1.9.4                hcfcfb64_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
magicgui                  0.8.3                    pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.5           py310h8d17308_0    conda-forge
matplotlib                3.8.4                    pypi_0    pypi
matplotlib-inline         0.1.7                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2021.4.0                 pypi_0    pypi
mkl-devel                 2021.4.0           h57928b3_730    conda-forge
mkl-include               2021.4.0           h0e2418a_729    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
napari                    0.4.18                   pypi_0    pypi
napari-console            0.0.9                    pypi_0    pypi
napari-deeplabcut         0.2.1.7                  pypi_0    pypi
napari-plugin-engine      0.2.0                    pypi_0    pypi
napari-svg                0.2.0                    pypi_0    pypi
natsort                   8.4.0                    pypi_0    pypi
nest-asyncio              1.6.0                    pypi_0    pypi
networkx                  3.3                pyhd8ed1ab_1    conda-forge
npe2                      0.7.6                    pypi_0    pypi
numba                     0.60.0                   pypi_0    pypi
numexpr                   2.7.3           py310hf5e1058_2    conda-forge
numpy                     1.26.4          py310hf667824_0    conda-forge
numpydoc                  1.5.0                    pypi_0    pypi
opencv-python             4.10.0.84                pypi_0    pypi
opencv-python-headless    4.10.0.84                pypi_0    pypi
openjpeg                  2.5.2                h3d672ee_0    conda-forge
openssl                   3.3.1                h2466b09_2    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2                    pypi_0    pypi
parso                     0.8.4                    pypi_0    pypi
partd                     1.4.2                    pypi_0    pypi
patsy                     0.5.6                    pypi_0    pypi
pillow                    10.4.0          py310h3e38d90_0    conda-forge
pims                      0.7                      pypi_0    pypi
pint                      0.24.3                   pypi_0    pypi
pip                       24.0               pyhd8ed1ab_0    conda-forge
platformdirs              4.2.2                    pypi_0    pypi
pooch                     1.8.2                    pypi_0    pypi
prompt-toolkit            3.0.47                   pypi_0    pypi
protobuf                  5.27.2                   pypi_0    pypi
psutil                    6.0.0                    pypi_0    pypi
psygnal                   0.11.1                   pypi_0    pypi
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pure-eval                 0.2.2                    pypi_0    pypi
py-cpuinfo                9.0.0              pyhd8ed1ab_0    conda-forge
pyarrow                   17.0.0                   pypi_0    pypi
pycocotools               2.0.8                    pypi_0    pypi
pyconify                  0.1.6                    pypi_0    pypi
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pydantic                  1.10.17                  pypi_0    pypi
pydantic-compat           0.1.2                    pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyopengl                  3.1.7                    pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pyproject-hooks           1.1.0                    pypi_0    pypi
pyside6                   6.4.2                    pypi_0    pypi
pyside6-addons            6.4.2                    pypi_0    pypi
pyside6-essentials        6.4.2                    pypi_0    pypi
pysocks                   1.7.1              pyh0701188_6    conda-forge
pytables                  3.8.0           py310hde27e41_4    conda-forge
python                    3.10.14         h4de0772_0_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
python_abi                3.10                    4_cp310    conda-forge
pytorch                   2.3.1           py3.10_cuda12.1_cudnn8_0    pytorch
pytorch-cuda              12.1                 hde6ce7c_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2024.1                   pypi_0    pypi
pywin32                   306                      pypi_0    pypi
pyyaml                    6.0.1           py310h8d17308_1    conda-forge
pyzmq                     26.0.3                   pypi_0    pypi
qdarkstyle                3.1                      pypi_0    pypi
qtconsole                 5.5.2                    pypi_0    pypi
qtpy                      2.4.1                    pypi_0    pypi
referencing               0.35.1                   pypi_0    pypi
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
rich                      13.7.1                   pypi_0    pypi
rpds-py                   0.19.0                   pypi_0    pypi
ruamel-yaml               0.18.6                   pypi_0    pypi
ruamel-yaml-clib          0.2.8                    pypi_0    pypi
safetensors               0.4.3                    pypi_0    pypi
scikit-image              0.24.0                   pypi_0    pypi
scikit-learn              1.5.1                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
sentry-sdk                2.10.0                   pypi_0    pypi
setproctitle              1.3.3                    pypi_0    pypi
setuptools                70.3.0             pyhd8ed1ab_0    conda-forge
shapely                   2.0.5                    pypi_0    pypi
shellingham               1.5.4                    pypi_0    pypi
shiboken6                 6.4.2                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
slicerator                1.1.0                    pypi_0    pypi
smmap                     5.0.1                    pypi_0    pypi
snappy                    1.2.1                h23299a8_0    conda-forge
snowballstemmer           2.2.0                    pypi_0    pypi
sphinx                    4.5.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.8                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.6                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.5                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.7                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.10                   pypi_0    pypi
stack-data                0.6.3                    pypi_0    pypi
statsmodels               0.14.2                   pypi_0    pypi
superqt                   0.6.7                    pypi_0    pypi
sympy                     1.13.0             pyh04b8f61_3    conda-forge
tbb                       2021.13.0                pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tifffile                  2024.7.2                 pypi_0    pypi
timm                      1.0.7                    pypi_0    pypi
tk                        8.6.13               h5226925_1    conda-forge
tomli                     2.0.1                    pypi_0    pypi
tomli-w                   1.0.0                    pypi_0    pypi
toolz                     0.12.1                   pypi_0    pypi
torchaudio                2.3.1                    pypi_0    pypi
torchvision               0.18.1                   pypi_0    pypi
tornado                   6.4.1                    pypi_0    pypi
tqdm                      4.66.4                   pypi_0    pypi
traitlets                 5.14.3                   pypi_0    pypi
typer                     0.12.3                   pypi_0    pypi
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024.1                   pypi_0    pypi
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   2.2.2              pyhd8ed1ab_1    conda-forge
vc                        14.3                h8a93ad2_20    conda-forge
vc14_runtime              14.40.33810         ha82c5b3_20    conda-forge
vispy                     0.12.2                   pypi_0    pypi
vs2015_runtime            14.40.33810         h3bf8584_20    conda-forge
wandb                     0.17.4                   pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
wrapt                     1.16.0                   pypi_0    pypi
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zipp                      3.19.2                   pypi_0    pypi
zlib-ng                   2.0.7                hcfcfb64_0    conda-forge
zstandard                 0.23.0          py310he5e10e1_0    conda-forge
zstd                      1.5.6                h0ea2cb4_0    conda-forge

**Comment by dlhagger** [comment]
Here is my pip list :Package                       Version
----------------------------- -----------
alabaster                     0.7.16
albumentations                1.4.3
app-model                     0.2.7
appdirs                       1.4.4
asttokens                     2.4.1
attrs                         23.2.0
Babel                         2.15.0
Brotli                        1.1.0
build                         1.2.1
cachey                        0.2.1
certifi                       2024.7.4
cffi                          1.16.0
charset-normalizer            3.3.2
click                         8.1.7
cloudpickle                   3.0.0
colorama                      0.4.6
comm                          0.2.2
contourpy                     1.2.1
cycler                        0.12.1
dask                          2024.7.0
dask-expr                     1.1.7
dask-image                    2024.5.3
debugpy                       1.8.2
decorator                     5.1.1
deeplabcut                    3.0.0rc2
dlclibrary                    0.0.6
docker-pycreds                0.4.0
docstring_parser              0.16
docutils                      0.17.1
einops                        0.8.0
exceptiongroup                1.2.2
executing                     2.0.1
filelock                      3.15.4
filterpy                      1.4.5
flexcache                     0.3
flexparser                    0.3.1
fonttools                     4.53.1
freetype-py                   2.4.0
fsspec                        2024.6.1
gitdb                         4.0.11
GitPython                     3.1.43
h2                            4.1.0
HeapDict                      1.0.1
hpack                         4.0.0
hsluv                         5.0.4
huggingface-hub               0.23.5
hyperframe                    6.0.1
idna                          3.7
imageio                       2.34.2
imageio-ffmpeg                0.5.1
imagesize                     1.4.1
imgaug                        0.4.0
importlib_metadata            8.0.0
in-n-out                      0.2.1
intel-openmp                  2021.4.0
ipykernel                     6.29.5
ipython                       8.26.0
jedi                          0.19.1
Jinja2                        3.1.4
joblib                        1.4.2
jsonschema                    4.23.0
jsonschema-specifications     2023.12.1
jupyter_client                8.6.2
jupyter_core                  5.7.2
kiwisolver                    1.4.5
lazy_loader                   0.4
llvmlite                      0.43.0
locket                        1.0.0
magicgui                      0.8.3
markdown-it-py                3.0.0
MarkupSafe                    2.1.5
matplotlib                    3.8.4
matplotlib-inline             0.1.7
mdurl                         0.1.2
mkl                           2021.4.0
mpmath                        1.3.0
napari                        0.4.18
napari-console                0.0.9
napari-deeplabcut             0.2.1.7
napari-plugin-engine          0.2.0
napari-svg                    0.2.0
natsort                       8.4.0
nest-asyncio                  1.6.0
networkx                      3.3
npe2                          0.7.6
numba                         0.60.0
numexpr                       2.7.3
numpy                         1.26.4
numpydoc                      1.5.0
opencv-python                 4.10.0.84
opencv-python-headless        4.10.0.84
packaging                     24.1
pandas                        2.2.2
parso                         0.8.4
partd                         1.4.2
patsy                         0.5.6
pillow                        10.4.0
PIMS                          0.7
Pint                          0.24.3
pip                           24.0
platformdirs                  4.2.2
pooch                         1.8.2
prompt_toolkit                3.0.47
protobuf                      5.27.2
psutil                        6.0.0
psygnal                       0.11.1
pure-eval                     0.2.2
py-cpuinfo                    9.0.0
pyarrow                       17.0.0
pycocotools                   2.0.8
pyconify                      0.1.6
pycparser                     2.22
pydantic                      1.10.17
pydantic-compat               0.1.2
Pygments                      2.18.0
PyOpenGL                      3.1.7
pyparsing                     3.1.2
pyproject_hooks               1.1.0
PySide6                       6.4.2
PySide6-Addons                6.4.2
PySide6-Essentials            6.4.2
PySocks                       1.7.1
python-dateutil               2.9.0.post0
pytz                          2024.1
pywin32                       306
PyYAML                        6.0.1
pyzmq                         26.0.3
QDarkStyle                    3.1
qtconsole                     5.5.2
QtPy                          2.4.1
referencing                   0.35.1
requests                      2.32.3
rich                          13.7.1
rpds-py                       0.19.0
ruamel.yaml                   0.18.6
ruamel.yaml.clib              0.2.8
safetensors                   0.4.3
scikit-image                  0.24.0
scikit-learn                  1.5.1
scipy                         1.10.1
sentry-sdk                    2.10.0
setproctitle                  1.3.3
setuptools                    70.3.0
shapely                       2.0.5
shellingham                   1.5.4
shiboken6                     6.4.2
six                           1.16.0
slicerator                    1.1.0
smmap                         5.0.1
snowballstemmer               2.2.0
Sphinx                        4.5.0
sphinxcontrib-applehelp       1.0.8
sphinxcontrib-devhelp         1.0.6
sphinxcontrib-htmlhelp        2.0.5
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.7
sphinxcontrib-serializinghtml 1.1.10
stack-data                    0.6.3
statsmodels                   0.14.2
superqt                       0.6.7
sympy                         1.13.0
tables                        3.8.0
tbb                           2021.13.0
threadpoolctl                 3.5.0
tifffile                      2024.7.2
timm                          1.0.7
tomli                         2.0.1
tomli_w                       1.0.0
toolz                         0.12.1
torch                         2.3.1
torchaudio                    2.3.1
torchvision                   0.18.1
tornado                       6.4.1
tqdm                          4.66.4
traitlets                     5.14.3
typer                         0.12.3
typing_extensions             4.12.2
tzdata                        2024.1
urllib3                       2.2.2
vispy                         0.12.2
wandb                         0.17.4
wcwidth                       0.2.13
wheel                         0.43.0
win-inet-pton                 1.1.0
wrapt                         1.16.0
zipp                          3.19.2
zstandard                     0.23.0

**Comment by dlhagger** [comment]
So, I think I have narrowed it down to torch install methods. This error occurs when you install torch from conda/mamba as follows:

"conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia"

but if you pip install torch with:

pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

there is no error

seems like different dependencies are used during the different install methods - 

maybe something to note in the install docs?

**Comment by MMathisLab** [comment]
okay grea, thanks for following up!
