### ISSUE TITLE
Maybe update yaml loader? 

### ISSUE THREAD

**Issue by mschart** [DeepLabCut/DeepLabCut#268]
Hello,

There's just that deprecation warning you may want to be aware of:

```
In [24]: deeplabcut.create_training_dataset(config_path)

/home/mic/anaconda3/envs/DLC/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py:328: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  docs.append(yaml.load(raw_doc))
docs.append(yaml.load(raw_doc))
The training dataset is successfully created. Use the function 'train_network' to start training. Happy training!
```

Overall I'm super happy with DLC, what a great toolbox, thanks again for creating it!
Cheers,
Michael

**Comment by AlexEMG** [comment]
Yes, will do that. Thanks @mschart

**Comment by MMathisLab** [comment]
Hey @mschart - sorry for the delay, we were traveling, but will update it still!

**Comment by mschart** [comment]
No worries, that's just a deprecation warning, everything runs smoothly!

**Comment by MMathisLab** [comment]
agreed, but also it's mildly annoying, and likely confusing for newcomers to Python, so best to take care of it since it's very easy to do so, thanks!

**Comment by AlexEMG** [comment]
Just updated it, will be in the 2.0.6. release. It is also backwards compatible, but from now on pyyaml >= 5.1 is recommended.

**Comment by MMathisLab** [comment]
done!
