### ISSUE TITLE
typo on wiki

### ISSUE THREAD

**Issue by kyleok** [DeepLabCut/DeepLabCut#2690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

not really a bug, comma is missing in given command.

deeplabcut.create_labeled_video(config_path, [‘path of video 1’,‘path of video2’,..]filtered=True)
should be 
deeplabcut.create_labeled_video(config_path, [‘path of video 1’,‘path of video2’,..], filtered=True)

@
https://github.com/DeepLabCut/DeepLabCut/wiki/DeepLabCut2.x-Quick-Guide-to-Commands

### Operating System

operating system

### DeepLabCut version

dlc version

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Thanks for spotting this! It's fixed :)
