### ISSUE TITLE
3d DEEPLABCUT  didnt give me the 3d csv file 

### ISSUE THREAD

**Issue by hussainabdullah300** [DeepLabCut/DeepLabCut#2692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

https://github.com/user-attachments/assets/27c853a4-5b4c-4400-bf0a-3a474149b56d

I did record 2d videos from 2 cameras fixed at a fixed distance, I calibrated the camera as told I also got the 3d video 

### Operating System

operating system = ubuntu 22

### DeepLabCut version

dlc version 2.3.10

### DeepLabCut mode

3d

### Device type

gpu 1080 ti

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @hussainabdullah300, could you let me know the exact steps you took to try and obtain the 3d CSV file?
