### ISSUE TITLE
No correct results were output, all were blank icons. There are no error prompts either. After creating the video, there are no plots inside the video.

### ISSUE THREAD

**Issue by Niklaus-v** [DeepLabCut/DeepLabCut#2694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

No correct results were output, all were blank icons. There are no error prompts either. After creating the video, there are no tags inside the video.

### Operating System

win11

### DeepLabCut version

DLC 3.0.0RC3

### DeepLabCut mode

single animal

### Device type

3080TI

### Steps To Reproduce

<img width="628" alt="image" src="https://github.com/user-attachments/assets/39c0580f-cf0c-4955-984e-84441f894a19">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by CoderYangQi** [comment]
So am I. Blank plots and didn't show any track. Should we use the previous version?

**Comment by n-poulsen** [comment]
Hi @Niklaus-v and @CoderYangQi - I'm looking into this and will get back to you

**Comment by CoderYangQi** [comment]
> Hi @Niklaus-v and @CoderYangQi - I'm looking into this and will get back to you
I used my own data to train. So I changed the training iterations as the Default(1000,000 times), and got the good result.
BTW, I suggest that the demo video could emphasize using large iterations to train your own datasets. I utilized the same number as the video showed ( just 100 iterations), and did not get result.

**Comment by n-poulsen** [comment]
I've tested this with the latest release and no longer have this problem. I'll close the issue, please re-open it if you can reproduce it with the latest release.
