### ISSUE TITLE
Step3_CheckLabels.py KeyError: 'No object named df_with_missing in the file' (Images not correctly loaded in step2)

### ISSUE THREAD

**Issue by cathy-liu23** [DeepLabCut/DeepLabCut#27]
**Describe the problem**
When running "Step3_CheckLabels.py", the following is outputted to the terminal.
$ python3 Step3_CheckLabels.py
4
<map object at 0x7f12408cdac8>
['nose', 'leftEye', 'rightEye', 'fin']
Traceback (most recent call last):
  File "Step3_CheckLabels.py", line 65, in <module>
    'CollectedData_' + cfg_scorer + '.h5', 'df_with_missing')
  File "/data/home/jli819/install/anaconda3/envs/deeplabcut/lib/python3.6/site-packages/pandas/io/pytables.py", line 394, in read_hdf
    return store.select(key, auto_close=auto_close, **kwargs)
  File "/data/home/jli819/install/anaconda3/envs/deeplabcut/lib/python3.6/site-packages/pandas/io/pytables.py", line 723, in select
    raise KeyError('No object named %s in the file' % key)
KeyError: 'No object named df_with_missing in the file'

**To Reproduce**
1. Create and label images in FIJI.
2. Run "Step2_ConvertingLabels2DataFrame.py"
(The following is produced in the data-Task folder:
-rw-r--r--. 1 jli819 2626  156 Jul  5 16:27 CollectedData_Trinity.csv
-rw-r--r--. 1 jli819 2626 1.0K Jul  5 16:27 CollectedData_Trinity.h5
drwxr-xr-x. 2 jli819 2626 8.0K Jul  5 16:26 fishvideo2)
3. Run "Step3_CheckLabels.py"
4. Error is produced

**Additional Information**
We have been skipping step 1 and labelling the images ourselves using FIJI. In our CSV file, the slices do not correspond to the image orders since some images were skipped and deleted. (For example, the slices may be 1, 2, 3, 6, 8, etc... and the images associated with slices 4 and 5 have been deleted from the folder.) 
In addition, we were able to train the CNN last week by labelling the images ourselves, so we are not sure why we are suddenly getting this error and smaller .h5 files produced in step 2. (The .h5 file produced in Step2 from the first time we ran it when it worked was 83K)

**Comment by MMathisLab** [comment]
The actual error you post seems to suggest that the h5 file does not exist. However the h5 file seems to be in the sub folder? Can you find out why it couldn’t load.

More importantly: don’t delete frames after labeling with Fiji. This is because the slice column of the Fiji csv files is used to locate the corresponding image. Deleting images misalignes the Indices.

Can you check if the h5 / csv file output from csv is correct?

**Comment by cathy-liu23** [comment]
Would Steps 2 and 3 work if some images were not labelled but still imported into Fiji? For example, if 20 images were imported into Fiji and only 17 of the images were labelled, and thus had points corresponding to them in the csv file and the Slice value corresponded to the correct images. (An example of our current csv output (images 6 and 7 were skipped but still included in the folder): https://user-images.githubusercontent.com/26770167/42352291-7f9ea02c-8087-11e8-844a-5f094c9d86d6.png) 

It doesn't seem as though the output in the csv file is correct because there are many Nan values.

**Comment by MMathisLab** [comment]
Correct, if you load 20 images into a stack, and then only label 17, that is fine. 


The trainigdata folder will contain all images (it just copies the folder), but the h5 file contains only the labeled ones

**Comment by ctrlshiftq** [comment]
I'm having the same problem.  However, i've definitely got the right number of points in the csv file with every image annotated with four points (251 pngs in the directory, 251 slices in the file totalling 1004 points).  Any ideas?  Thanks!

**Comment by ctrlshiftq** [comment]
I am actually still very much facing this issue.  I would really appreciate suggestions about what could be causing it.  Interestingly, a properly formatted csv with commas is parsed by the Step2 script (my previous comma-separated csv had extra commas -- I know that it is now working because I am printing out the Pandas dataframe object), whereas a csv formatted identically to the repo's sample data (with tabs) causes errors and does not yield a valid dataframe.

**Comment by MMathisLab** [comment]
Let’s discuss on slack since it’s not a bug in the code. :)

**Comment by AlexEMG** [comment]
If you are skipping step1 (i.e. don't use our png file extractor), then you need to do several things (to make sure that the csvs from Fiji and the images are correctly imported in Step2 and subsequently processed in Step3 & 4.)

A) change the file-ending in the myconfig file to the image format you are using: imagetype=".png". 
B) make sure that the folder structure is like after "our step1", i.e. a create a folder with "data-TASKNAME" that contains several subfolders each containing images + annotation csv files
C) Ordering. It is key that the order of the Fiji annotation files (csv) and the python loading of the images will match! For this purpose we suggest you either carefully check that manually, or just use a scheme like e.g.:
img0000.jpg
img0001.jpg
...
img9999.jpg
etc. to be sure! (make sure the number of digits is constant, i.e. pad img1.jpg to img0001.jpg). 

Then everything should work! However, make sure you get labeled images after Step3 that match what you annotated in Fiji, before you proceed to training DeepLabCut!


P.S. Why should "img" be a subset of the filename? - Consider line 88 of https://github.com/AlexEMG/DeepLabCut/blob/master/Generating_a_Training_Set/Step2_ConvertingLabels2DataFrame.py

fn for fn in os.listdir(os.curdir)
                if (**"img" in fn** and imagetype in fn and "_labelled" not in fn)
            ]

this is why. The same import is done in Step3. Perhaps in the next push we plan to make this more general by removing this affix. However, this is the current naming convention.

**Comment by ctrlshiftq** [comment]
Thanks!  I was using images extracted from multiple videos, so I had replaced the "img" prefix with numbers to ensure they'd load in the correct order.

**Comment by ctrlshiftq** [comment]
Figured out my issue which might be helpful to others.  In the Step2 script, the "try" on line 66 will continue to evaluate if the scorer's .h5 file is present, as it will be if you've previously run the script.  For me, this leads to the error being discussed.  Try deleting your CollectedData_<Name>.h5 and .csv files from your Data-<project>/ directory before rerunning the script.

**Comment by AlexEMG** [comment]
Indeed! However, I am ambivalent about the optimal behavior. Somehow, I think this is the indented behavior as the h5 file should not be overwritten, so one has to manually remove it. However, that could be confusing for users (that don't look at the code).
