### ISSUE TITLE
Cannot refine user labels - use labeling toolbox for refining in version >=2.05

### ISSUE THREAD

**Issue by jayepi** [DeepLabCut/DeepLabCut#270]
**System setup**
Ubuntu 16.04 LTS, with an Anaconda Environment and DLC 2.0.5.1

**Problem**
I am unable to edit user-generated labels using the steps provided in the bioRxiv user guide. In particular, the user is instructed in Step E that

> [i]f [the user-generated labels] are not correct, the user can call the refinement GUI (Step K and check the tick box for "adjust original labels" to adjust the location of the labels).

 However, no such tick box appears, and there appears to be no way to select the user-generated labels.

**Steps to reproduce issue**

1. Run "dlc.refine_labels(config_path)"
2. Screenshot 1 appears (no tick box)
3. Clicking "Load labels" only allows for machine-created labels to be edited (restricted to files that match: "machinelabels-iter0.h5") (see Screenshot 2)  
Is there a different way to adjust the user-generated labels?  I have looked over the labels and see I need to adjust a number of them.

**Screenshots**

Screenshot 1 (GUI)
![refinement-toolbox-gui](https://user-images.githubusercontent.com/48773647/56546204-d446bd80-6547-11e9-80fb-2dfc7fdade98.png)

Screenshot 2 (GUI dialog box)
![refinement-toolbox-gui--dialog-box](https://user-images.githubusercontent.com/48773647/56546220-e0cb1600-6547-11e9-9d91-2649ea50ae2e.png)

**Comment by MMathisLab** [comment]
Yes, the documents on GitHub are updated such that now you can edit your labels in the normal GUI (i.e. `deeplabcut.label_frames`) 

Please ref the docs: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#d-label-frames
