### ISSUE TITLE
Issues Installing DeepLabCut 3.0.0rc4 on Ubuntu 22.04 

### ISSUE THREAD

**Issue by slagathor69** [DeepLabCut/DeepLabCut#2706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Installing using just the environment YAML complains of missing PyTorch. 

### Operating System

Linux

### DeepLabCut version

3.0.0rc4 

### DeepLabCut mode

single animal

### Device type

GeForce 4090

### Steps To Reproduce

Installing DeepLabCut on Linux using just environment YAML and importing it.

## What solved issue was 

First creating environment:
```mamba create -n DEEPLABCUT python=3.10```

Activating environment and installing PyTorch with:
```mamba install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia```

Then using environment yaml to update environment
```mamba env update --name DEEPLABCUT --file deeplabcut.yaml```

Then running:
```mamba install cudnn -c conda-forge```

*Note I use mamba instead of conda due to its vastly superior speed but you can replace with conda here and it should be same result just slower*

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by rrr9444** [comment]
python -m deeplabcut

SyntaxError: invalid or missing encoding declaration for 'C:\\Users\\ACER\\anaconda3\\envs\\DEEPLABCUT\\lib\\site-packages\\pywin32_system32\\pywintypes39.dll'

**Comment by slagathor69** [comment]
> python -m deeplabcut
> 
> SyntaxError: invalid or missing encoding declaration for 'C:\Users\ACER\anaconda3\envs\DEEPLABCUT\lib\site-packages\pywin32_system32\pywintypes39.dll'

@rrr9444 You're using Windows, what I described above is for Linux.

**Comment by n-poulsen** [comment]
Hi @slagathor69 - could you let me know what the error message is?
