### ISSUE TITLE
issue opening .sh files - downloading pre-trained weights

### ISSUE THREAD

**Issue by KingLunLi** [DeepLabCut/DeepLabCut#271]
**Your Operating system and DeepLabCut version**
Please state your operating system, env, and which version of DeepLabCut you are using.

Windows 10.  Anaconda environment.  DeepLabCut 2.0 (CPU version)

**Describe the problem**
Hi, I have just installed DeepLabCut (CPU) and tried to run the "Demo_labeledexample_MouseReaching".  The line `deeplabcut.load_demo_data(path_config_file)` is giving me an error.  

I believe that .sh files are not associated with anaconda. Any suggestions or comments would be greatly appreciated.  Thank you!

**How to Reproduce the problem**
Open Demo_labeledexample_MouseReaching in jupyter notebook
run `import deeplabcut`
run `import tensorflow as tf`
run `tf.__version__`

run `import os`
run `from pathlib import Path`
run `path_config_file = os.path.join(os.getcwd(),'Reaching-Mackenzie-2018-08-30/config.yaml')`
run `deeplabcut.load_demo_data(path_config_file)`

**Screenshots**
![opening sh file](https://user-images.githubusercontent.com/41491620/56770929-422af900-6783-11e9-8610-a090828074e0.png)

**Comment by MMathisLab** [comment]
you likely need to install GitBash first! .sh are just bash scripts. 

Install git using https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

**Comment by KingLunLi** [comment]
It worked.  Thank you!!
