### ISSUE TITLE
DeepLabCut   python -m deeplabcut

### ISSUE THREAD

**Issue by rrr9444** [DeepLabCut/DeepLabCut#2710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

DeepLabCut   python -m deeplabcut   
SyntaxError: invalid or missing encoding declaration for 'C:\\Users\\ACER\\anaconda3\\envs\\DEEPLABCUT\\lib\\site-packages\\pywin32_system32\\pywintypes39.dll'
  not open

### Operating System

win 11

### DeepLabCut version

dlc version

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Looks like you are trying to use python 3.9; only 3.10+ is suported with the current version of DLC!
