### ISSUE TITLE
Memory Allocation in Pytorch

### ISSUE THREAD

**Issue by VAmoroso13** [DeepLabCut/DeepLabCut#2719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have run into a situation where Python is holding 15.99GiB of RAM on my GPU, 14.45GiG is allocated and 620.83MiB is reserved but unallocated. I am getting an error, `torch.OutOfMemoryError: CUDA out of memory.`

It's trying to allocate 140MiB. I would need to reduce batch size from 8 to 4 to run, which would be against most cudnn documents on maximizing performance. The error recommends:

` If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)`

### Operating System

Windows 11

### DeepLabCut version

3.0.0rc4

### DeepLabCut mode

multi animal

### Device type

RTX4800

### Steps To Reproduce

1. Create training dataset with 'Transfer Learning - Superanimal Quadraped' and Network "DEKR_w32"
2. Set batch size to 16, 8, 4, 1
3. Train

### Relevant log output

```shell
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 140.00 MiB. GPU 0 has a total capacity of 15.99 GiB of which 0 bytes is free. Of the allocated memory 14.45 GiB is allocated by PyTorch, and 620.83 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

### Anything else?

Great job on the new back-end and GUI options. Really impressed!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @VAmoroso13 - quick questions on your data:

- how large are your images?
- which model are you training?

And if I understand correctly, you were able to train with batch size 4?

**Comment by VAmoroso13** [comment]
Hello!

It's the DEKR_w32 model.
Images are 800*716px.

Yes, it will train with batch size of 1 or 4. I can also train HRNET_w32 with 1 or 4, but can't scale beyond without the same memory management error. 

Any insight would be very helpful. Thank you!

**Comment by n-poulsen** [comment]
Then the memory issues make sense - DEKR is a large model, and your images are quite large as well. So training with batch size 4 is your only option, and shouldn't be an issue (I've trained models with batch size 4 with good performance). I'll close this issue, but let me know if you have any other questions!
