### ISSUE TITLE
pose_estimation_pytorch torch.load warning

### ISSUE THREAD

**Issue by dlhagger** [DeepLabCut/DeepLabCut#2725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When running analyze_videos on rc4, a future warning that seems reasonable to update is presenting:

FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  snapshot = torch.load(snapshot_path, map_location=device)

Is it possible to add the files to the allowlist by default or load with weights_only in the future? Many of us are on security managed compute by our institutes or corporations, so might be worth while to address before a public release?

Thanks!

David

### Operating System

operating system

MacOS 14.6.1

### DeepLabCut version

dlc version

pytorch rc4

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @dlhagger! I think this is a good point and I'll address it before the full release (this warning was [just added in PyTorch 2.4](https://github.com/pytorch/pytorch/releases/tag/v2.4.0) :) so we'll make the change before PyTorch changes the default).

Generally, there should be no security issue as long as you only load checkpoints that you created for your models (and not load a random checkpoint found on the internet).

Meanwhile, in `torch>=2.4`, if you want to ensure that the weights are loaded safely, you can set the environment variable `TORCH_FORCE_WEIGHTS_ONLY_LOAD=1`, which will ensure that `weights_only` will be used, no matter what's written in the code. In a Python script, you can do so with the following code:

```python
import os

os.environ["TORCH_FORCE_WEIGHTS_ONLY_LOAD"] = "1"
```

You can also set environment variables in your shell directly.

**Comment by dlhagger** [comment]
Hey!

Thanks for the clarification. Totally makes sense and easy to implement by the looks of it. Just wanted to make sure I could load the weights only without breaking anything.

Thanks!

David

**Comment by Hydra9268** [comment]
> ```python
> import os
> 
> os.environ["TORCH_FORCE_WEIGHTS_ONLY_LOAD"] = "1"
> ```

I was encountering the same FutureWarning with Real-ESRGAN's `utils.py`. I was able to successfully suppress the warning using this. Thanks, @n-poulsen !

At the time of writing this I have the following libraries installed:

torch            2.4.1+cu121
torchaudio   2.4.1+cu121
torchvision   0.19.1+cu121
