### ISSUE TITLE
Query regarding the #Plotting Configuration. in config.yaml 

### ISSUE THREAD

**Issue by Gaelic98** [DeepLabCut/DeepLabCut#274]
Hello,

I had a slight query regarding the p-cutoff parameter in config.yaml for a project,  I'm assuming  that when using the create_labeled_video() function, the final video produced has labels where the likelihood of the joint is greater than the p-cutoff in the config.yaml file.

Is this assumption correct. 

Regards.

**Comment by AlexEMG** [comment]
Hi @Gaelic98 

Yes, indeed the points with likelihood > p-cutoff are included. You can use the plot_trajectory function to have a look at the likelihoods and eyeball what a good p_cutoff would be... 

Cheers,
Alexander
