### ISSUE TITLE
issue with “weights” masks always zero-ed out during training

### ISSUE THREAD

**Issue by thuann2cats** [DeepLabCut/DeepLabCut#2751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi, I observe this behavior during DLC training that I have yet to understand. I was wondering if you could clarify.
Before line 162 in this file: `<DLC environment>/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/models/target_generators/heatmap_targets.py`
`weights` was an all-one tensors.
```
# heatmap (batch_size, height, width, num_kpts)
        # coords (batch_size, num_kpts, num_individuals, 3)
        for b in range(batch_size):
            for heatmap_idx, group_keypoints in enumerate(coords[b]):
                for keypoint in group_keypoints:
                    # FIXME: Gradient masking weights should be parameters
                    if keypoint[-1] == 0:
                        # full gradient masking
                        weights[b, heatmap_idx] = 0.0
                    elif keypoint[-1] == -1:
                        # full gradient masking
                        weights[b, heatmap_idx] = 0.0

                    elif keypoint[-1] > 0:
                        # keypoint visible
                        self.update(
                            heatmap=heatmap[b, :, :, heatmap_idx],
                            grid=grid,
                            keypoint=keypoint[..., :2],
                            locref_map=self.get_locref(locref_map, b, heatmap_idx),
                            locref_mask=self.get_locref(locref_mask, b, heatmap_idx),
                        )

```

But after this code block, `weights` seems to be all zero-ed out to be an all-zero tensors, leading to difficulty in training the model.
The problem seems to be that the innermost loop is iterating through each row in this `group_keypoints` 2-D array. For example,
```
group_keypoints
array([[ 74.45522, 308.99606,   2.     ],
       [322.70728, 156.14667,   2.     ],
       [ -1.     ,  -1.     ,  -1.     ],
       [ -1.     ,  -1.     ,  -1.     ],
       [ -1.     ,  -1.     ,  -1.     ],
       [ -1.     ,  -1.     ,  -1.     ],
       [ -1.     ,  -1.     ,  -1.     ],
       [ -1.     ,  -1.     ,  -1.     ],
       [ -1.     ,  -1.     ,  -1.     ],
       [ -1.     ,  -1.     ,  -1.     ]], dtype=float32)
```
(where its shape is (10, 3) – 10 animals maximum)
Then at least one of the iteration will have `keypoint[-1] == -1` and if so, the entire section of `weights` will be zero-ed out. This doesn’t seem to be the intended behavior of masking. Could you please double check? Thanks.
The DLC version is: Loading DLC 3.0.0rc4...

### Operating System

RH9

### DeepLabCut version

The DLC version is: Loading DLC 3.0.0rc4...

### DeepLabCut mode

multi animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by thuann2cats** [comment]
Hi, just a follow up with more details...

More specifically, here’s a visualization of the model’s outputs, the target and weight heatmaps for one body part right before a loss computation. As you can see (if you squint at the values of the colorbar as well), the`weights` heatmap is all zero-values.
 
![image](https://github.com/user-attachments/assets/e9f1fe98-5432-4cc8-a32b-d74695c0840f)

The same behavior is repeated for the model’s `output`, `target`, and `weights` for another body part right before loss computation:
 
![image](https://github.com/user-attachments/assets/ee6a1937-2ded-46ee-8f50-f723ccea014a)

That  means the entire body-part heatmaps are masked out during loss calculation and gradient backprop, which clearly is not an intended behavior.
I  think as a result of zero-ed out `weights` masking, when I did evaluation, the model’s body-part output heatmaps are mostly 0.5 values – since the model’s not been allowed to train. For example, here’s the visualization of the tensors at the end of this code block during the evaluation step. As you can see, model's output heatmap (leftmost figure) is mostly 0.5-values, as indicated by yellow color according to the colorbar on the side:
<DLC env folder>/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/models/predictors/paf_predictor.py
```
    @staticmethod
    def find_local_peak_indices_maxpool_nms(
        input_: torch.Tensor, radius: int, threshold: float
    ) -> torch.Tensor:
        pooled = F.max_pool2d(input_, kernel_size=radius, stride=1, padding=radius // 2)
        maxima = input_ * torch.eq(input_, pooled).float()
        peak_indices = torch.nonzero(maxima >= threshold, as_tuple=False)
        return peak_indices.int()
```

 
![image](https://github.com/user-attachments/assets/31b2bb19-b6b4-4cfc-915f-e74afbe57782)


# Possible solutions
When I modified the weight-masking code such that a heatmap for a body part is masked out only when there’s no keypoint that has been annotated for that body part in any animal in the frame, then the training worked and the evaluation yielded accurate results. (Essentially, leaving the `weights` heatmaps to have all-one values most of the time.)

```
for b in range(batch_size):
            for heatmap_idx, group_keypoints in enumerate(coords[b]):
                # THUAN's modification (next 2 lines and two 'pass' statements below)
                if not np.any(group_keypoints[:, 2] > 0):
                    weights[b, heatmap_idx] = 0.0
                # END of modification
                for keypoint in group_keypoints:
                    if keypoint[-1] == 0:
                        # full gradient masking
                        pass # weights[b, heatmap_idx] = 0.0
                    elif keypoint[-1] == -1:
                        # full gradient masking
                        pass # weights[b, heatmap_idx] = 0.0

                    elif keypoint[-1] > 0:
                        # keypoint visible
                        self.update(
                            heatmap=heatmap[b, :, :, heatmap_idx],
                            grid=grid,
                            keypoint=keypoint[..., :2],
                            locref_map=self.get_locref(locref_map, b, heatmap_idx),
                            locref_mask=self.get_locref(locref_mask, b, heatmap_idx),
                        )

```
The evaluation yielded accurate results, with test pixel distance error of about 6 pixels.
Here’s a visualization of the model’s output after this code block:
```
<DLC env folder>/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/models/predictors/paf_predictor.py
    @staticmethod
    def find_local_peak_indices_maxpool_nms(
        input_: torch.Tensor, radius: int, threshold: float
    ) -> torch.Tensor:
        pooled = F.max_pool2d(input_, kernel_size=radius, stride=1, padding=radius // 2)
        maxima = input_ * torch.eq(input_, pooled).float()
        peak_indices = torch.nonzero(maxima >= threshold, as_tuple=False)
        return peak_indices.int()
```
As you can see on the leftmost figure, the model output a body-part heatmap that is mostly zero and only with a few small speaks, as intended, instead of just all 0.5 values as in previous case.
 
![image](https://github.com/user-attachments/assets/bdde28cf-01b3-4588-ac5f-9a4d775fca4c)

**Comment by n-poulsen** [comment]
Hi @thuann2cats! Thanks for reporting this, I'd spotted it as well and it was fixed last week in #2747. If you re-install the code from the source, the issue should be fixed. We now deal with it in the following way:

```python
                   if self.gradient_masking and keypoint[-1] == 0:
                         # apply background weight if keypoints are missing
                         weights[b, heatmap_idx] = self.background_weight
                     elif keypoint[-1] == -1:
                         # always mask weights when the keypoint is undefined
                         weights[b, heatmap_idx] = 0.0
```

The `gradient_masking` attribute is False as a default, so the default behavior is to not mask the gradient when the keypoint visibility is 0. Let me know if this solution works for you!

**Comment by thuann2cats** [comment]
Hi @n-poulsen , thanks for your reply. I did notice that another version few days later had this fix (rc5, I believe). I actually did the same exact training with this rc5, and I had the same issue where the model wasn't really trained.

With the rc5 code, I was still wondering why the change had these lines:
```
 elif keypoint[-1] == -1:
                         # always mask weights when the keypoint is undefined
                         weights[b, heatmap_idx] = 0.0
```
if so, the for loop would get into this `elif` branch eventually, if `group_keypoints` is like this:
```
group_keypoints
array([[ 74.45522, 308.99606,   2.     ],
       [322.70728, 156.14667,   2.     ],
       [ -1.     ,  -1.     ,  -1.     ],
       [ -1.     ,  -1.     ,  -1.     ],
       [ -1.     ,  -1.     ,  -1.     ],
       [ -1.     ,  -1.     ,  -1.     ],
       [ -1.     ,  -1.     ,  -1.     ],
       [ -1.     ,  -1.     ,  -1.     ],
       [ -1.     ,  -1.     ,  -1.     ],
       [ -1.     ,  -1.     ,  -1.     ]], dtype=float32)
```
and the `weights` would end up being zero-ed out for that particular batch-index and heatmap-index, thus messing up with the training.

I will inspect that specific breakpoint with rc5 again to be sure. But I just want to raise these thoughts. Thanks!

**Comment by n-poulsen** [comment]
@thuann2cats that's correct - the `-1` flag can be used when training on datasets where keypoints aren't labeled on some images, such as when merging multiple datasets with SuperAnimal models (see the [paper here](https://www.nature.com/articles/s41467-024-48792-2)). 

This allows to mask the gradient for specific keypoints that have not been labeled, while _not_ masking the gradient when a keypoint was labeled but isn't visible in the image.

This `-1` visibility flag is not used in the "normal" DeepLabCut workflow - keypoints that weren't labeled are assumed not to be visible, and the visibility flag is set to `0`.

Let me know if that's clear! And thank you for raising issues when you spot bugs in the code, it's very helpful for us!
