### ISSUE TITLE
`analyze_video` encountered an error due to for-loop over a NoneType - possibly because of frame with no animals

### ISSUE THREAD

**Issue by thuann2cats** [DeepLabCut/DeepLabCut#2754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi DLC team, 
I observed a potential error with `analyze_videos`.
This is around the block at line 179 (`assemblies, unique = … `) of this file: /home/hice1/tnguyen868/scratch/DLC_dnv/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/models/predictors/paf_predictor.py

```
        for i, data_dict in enumerate(preds):
            assemblies, unique = self.assembler._assemble(data_dict, ind_frame=0)
            for j, assembly in enumerate(assemblies):
                poses[i, j, :, :4] = torch.from_numpy(assembly.data)
                poses[i, j, :, 4] = assembly.affinity
            if unique is not None:
                poses_unique[i, 0, :, :4] = torch.from_numpy(unique)
```
After that line (`assemblies, unique = … `) , if `assemblies` is None, then the  for loop gives an error for having to iterate over a `NoneType`.
For example, here’s a situation that led to `assemblies` having `None` value. Please refer to my debugging console below:
```
i
4

preds[4]['confidence']
[array([], shape=(0, ...e=float32), array([], shape=(0, ...e=float32), array([], shape=(0, ...e=float32), array([], shape=(0, ...e=float32), array([], shape=(0, ...e=float32), array([], shape=(0, ...e=float32), array([], shape=(0, ...e=float32), array([], shape=(0, ...e=float32), array([], shape=(0, ...e=float32)]

preds[4]['coordinates']
([array([], shape=(0, ...e=float32), array([], shape=(0, ...e=float32), array([], shape=(0, ...e=float32), array([], shape=(0, ...e=float32), array([], shape=(0, ...e=float32), array([], shape=(0, ...e=float32), array([], shape=(0, ...e=float32), array([], shape=(0, ...e=float32), array([], shape=(0, ...e=float32)],)

```
In other words, a situation where the model didn’t seem to detect any keypoint coordinates. Then `assemblies` would be `None` after `_assemble()` function call. That happens quite often because my video had many frames where no animal was present.
# Possible fix
Should we put a check for None-valued `assemblies` before the for-loop?
For example, if I modified the code like this, `analyze_video` proceeded without any NoneType error.
```
        for i, data_dict in enumerate(preds):
            assemblies, unique = self.assembler._assemble(data_dict, ind_frame=0)
            # modification
            if assemblies is not None:
            # end of modification
                for j, assembly in enumerate(assemblies):
                    poses[i, j, :, :4] = torch.from_numpy(assembly.data)
                    poses[i, j, :, 4] = assembly.affinity
            if unique is not None:
                poses_unique[i, 0, :, :4] = torch.from_numpy(unique)
```

### Operating System

RH 9

### DeepLabCut version

dlc version 3.0.0 rc4 (PyTorch)

### DeepLabCut mode

multi animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @thuann2cats! This was fixed in #2747 - updating your code should fix the issue
