### ISSUE TITLE
`deeplabcut.create_video_with_all_detections`: `p` has 3 values, leading to error in `p.item()`; annotated video cannot be created

### ISSUE THREAD

**Issue by thuann2cats** [DeepLabCut/DeepLabCut#2755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hi DLC team,
During the execution of `deeplabcut.create_video_with_all_detections`, my code ran into errors where the value of `p` is an array with shape `(1,3)`. In other words, there are 3 probability values for each joint when each joint is instantiated with `Joint()`. And thus there’s an error when we call `p.item()` and the annotated frame could not be saved in order to create a new annotated video.

More specifically, the error was: `“no data: can only convert an array of size 1 to a Python scalar” error`

Why are there three probability values? 

These `p`s would have values such as [0.988, -1, 0.334] or [0.99, -1, 0.5004] for example, and so if I comment out the original line and just take the first value of `p` and then call `.item()` on it, then the code works fine at the `Joint()` instantiation call, and the annotated frame was properly saved into the annotated video clip.

Could you explain the purpose of having 3 probability values when the code executes to `p.item()`?

Specifically, line 433 in this file: `/home/hice1/tnguyen868/scratch/DLC_dnv/lib/python3.10/site-packages/deeplabcut/core/inferenceutils.py `
```
            for xy, p, g in zip(coords, conf, id_):
                # joint = Joint(tuple(xy), p.item(), i, ind, g)
                joint = Joint(tuple(xy), p[0].item(), i, ind, g)
                ind += 1
                yield joint
```

### Operating System

operating system RH9

### DeepLabCut version

dlc version DLC 3.0.0 rc 4 PyTorch

### DeepLabCut mode

multi animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @thuann2cats! Could you please let me know which model architecture you're using so I can reproduce the issue?

**Comment by thuann2cats** [comment]
Hi @n-poulsen , during inference, what I'm using is the PoseModel / DCLRHead and a PartAffinityField predictor. Does that identify the architecture that you need or do you need further information? Thanks!!

**Comment by n-poulsen** [comment]
Thanks @thuann2cats - I'll work on reproducing your error
