### ISSUE TITLE
The DLC GUI cannot be launched and there are no error messages.

### ISSUE THREAD

**Issue by li1901** [DeepLabCut/DeepLabCut#2758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

launched  DLC GUI

### Operating System

Windos 11

### DeepLabCut version

DLC 3.0.0rc5...

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by li1901** [comment]
![image](https://github.com/user-attachments/assets/d7c2a225-8dc6-47da-acd0-d6c25e64dd34)

**Comment by li1901** [comment]
![image](https://github.com/user-attachments/assets/8ea6d277-17e5-4784-93a8-d1ae4d768ff2)

**Comment by n-poulsen** [comment]
Hi @li1901, could you please let me know:
1. which package versions you have installed (the output of `pip list` in your conda environment )
2. the output of `napari --info`

**Comment by n-poulsen** [comment]
Closing as stale
