### ISSUE TITLE
DeepLabCut uses up whole GPU then says gives CUDA memory error when I attempt to train

### ISSUE THREAD

**Issue by sjakes201** [DeepLabCut/DeepLabCut#2759]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Bug description

I followed the steps to install and use DeepLabCut from the github. I downloaded and successfully created my conda environment. I was able to extract and label frames. But when I go to train the network, if I have batch_size set to anything > 1, it gives CUDA memory error. I set batch_size to 8, then 4, then 2, and got the same error every time. Here is the error (in log output) for when I tried 2. I set it to 1 and it finally worked, but I don't think it is utilizing my GPU. I am setting batch_size in both pose_cfg.yaml and config.yaml.

I ran nvidia-smi before running deeplabcut, and there were no processes running on the gpu. I then ran nvidia-smi while deeplabcut was running (before pressing train network), and it said the GPU was almost entirely full, and no other processes. So when I pressed train network, it gave the CUDA memory error. Please help, I have been trying for a long time and cannot get it to work.

I have also noticed this warning message before it starts training that says "Note: According to your model configuration, you're training with batch size 1 and/or ``freeze_bn_stats=false``. This is not an optimal setting if you have powerful GPUs.
This is good for small batch sizes [...]", but this is not true. It even says in the previous log output that my batch_size in this example was set to 2, so I don't understand why it's changing this and could be related.

### Operating System

Linux Ubuntu 20.04.6

### DeepLabCut version

DLC 3.0.0rc5

### DeepLabCut mode

single animal

### Device type

2080ti GPU

### Steps To Reproduce

Follow steps 1-3 in the docs
https://deeplabcut.github.io/DeepLabCut/docs/installation.html

I installed Python and miniconda, and downloaded the DEEPLABCUT.yaml file.

I ran created and then activated the conda env from the .yaml file, ran "python -m deeplabcut" and it opened the DLC GUI.

I created a project with pytorch engine, extracted frames, and labelled the frames.

I then went to the two configs mentioned in the description and set batch_size to 8 (then also tried 4 and 2 when it didn't work).

When I pressed train it gave me this error.

### Relevant log output

```shell
Training with configuration:
data:
  colormode: RGB
  inference:
    normalize_images: True
  train:
    affine:
      p: 0.5
      rotation: 30
      scaling: [1.0, 1.0]
      translation: 0
    collate:
      type: ResizeFromDataSizeCollate
      min_scale: 0.4
      max_scale: 1.0
      min_short_side: 128
      max_short_side: 1152
      multiple_of: 32
      to_square: False
    covering: False
    gaussian_noise: 12.75
    hist_eq: False
    motion_blur: False
    normalize_images: True
device: auto
metadata:
  project_path: /home/jdsweet_umass_edu/Desktop/dlc_model/marmoset_reaching-jake-2024-10-10
  pose_config_path: /home/jdsweet_umass_edu/Desktop/dlc_model/marmoset_reaching-jake-2024-10-10/dlc-models-pytorch/iteration-0/marmoset_reachingOct10-trainset95shuffle1/train/pose_cfg.yaml
  bodyparts: ['left_pinkie', 'left_ring', 'left_middle', 'left_pointer', 'left_thumb', 'left_backhand', 'left_palm', 'right_pinkie', 'right_ring', 'right_middle', 'right_pointer', 'right_thumb', 'right_backhand', 'right_palm', 'left_forearm', 'right_forearm']
  unique_bodyparts: []
  individuals: ['animal']
  with_identity: None
method: bu
model:
  backbone:
    type: ResNet
    model_name: resnet50_gn
    output_stride: 16
    freeze_bn_stats: True
    freeze_bn_weights: False
  backbone_output_channels: 2048
  heads:
    bodypart:
      type: HeatmapHead
      weight_init: normal
      predictor:
        type: HeatmapPredictor
        apply_sigmoid: False
        clip_scores: True
        location_refinement: True
        locref_std: 7.2801
      target_generator:
        type: HeatmapGaussianGenerator
        num_heatmaps: 16
        pos_dist_thresh: 17
        heatmap_mode: KEYPOINT
        gradient_masking: False
        generate_locref: True
        locref_std: 7.2801
      criterion:
        heatmap:
          type: WeightedMSECriterion
          weight: 1.0
        locref:
          type: WeightedHuberCriterion
          weight: 0.05
      heatmap_config:
        channels: [2048, 16]
        kernel_size: [3]
        strides: [2]
      locref_config:
        channels: [2048, 32]
        kernel_size: [3]
        strides: [2]
net_type: resnet_50
runner:
  type: PoseTrainingRunner
  gpus: None
  key_metric: test.mAP
  key_metric_asc: True
  eval_interval: 10
  optimizer:
    type: AdamW
    params:
      lr: 0.0001
  scheduler:
    type: LRListScheduler
    params:
      lr_list: [[1e-05], [1e-06]]
      milestones: [160, 190]
  snapshots:
    max_snapshots: 5
    save_epochs: 50
    save_optimizer_state: False
train_settings:
  batch_size: 2
  dataloader_workers: 0
  dataloader_pin_memory: False
  display_iters: 1000
  epochs: 200
  seed: 42
Loading pretrained weights from Hugging Face hub (timm/resnet50_gn.a1h_in1k)
[timm/resnet50_gn.a1h_in1k] Safe alternative available for 'pytorch_model.bin' (as 'model.safetensors'). Loading weights using safetensors.
Data Transforms:
  Training:   Compose([
  Affine(always_apply=False, p=0.5, interpolation=1, mask_interpolation=0, cval=0, mode=0, scale={'x': (1.0, 1.0), 'y': (1.0, 1.0)}, translate_percent=None, translate_px={'x': (0, 0), 'y': (0, 0)}, rotate=(-30, 30), fit_output=False, shear={'x': (0.0, 0.0), 'y': (0.0, 0.0)}, cval_mask=0, keep_ratio=True, rotate_method='largest_box'),
  GaussNoise(always_apply=False, p=0.5, var_limit=(0, 162.5625), per_channel=True, mean=0),
  Normalize(always_apply=False, p=1.0, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], max_pixel_value=255.0),
], p=1.0, bbox_params={'format': 'coco', 'label_fields': ['bbox_labels'], 'min_area': 0.0, 'min_visibility': 0.0, 'min_width': 0.0, 'min_height': 0.0, 'check_each_transform': True}, keypoint_params={'format': 'xy', 'label_fields': ['class_labels'], 'remove_invisible': False, 'angle_in_degrees': True, 'check_each_transform': True}, additional_targets={}, is_check_shapes=True)
  Validation: Compose([
  Normalize(always_apply=False, p=1.0, mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], max_pixel_value=255.0),
], p=1.0, bbox_params={'format': 'coco', 'label_fields': ['bbox_labels'], 'min_area': 0.0, 'min_visibility': 0.0, 'min_width': 0.0, 'min_height': 0.0, 'check_each_transform': True}, keypoint_params={'format': 'xy', 'label_fields': ['class_labels'], 'remove_invisible': False, 'angle_in_degrees': True, 'check_each_transform': True}, additional_targets={}, is_check_shapes=True)
Using custom collate function: {'type': 'ResizeFromDataSizeCollate', 'min_scale': 0.4, 'max_scale': 1.0, 'min_short_side': 128, 'max_short_side': 1152, 'multiple_of': 32, 'to_square': False}

Note: According to your model configuration, you're training with batch size 1 and/or ``freeze_bn_stats=false``. This is not an optimal setting if you have powerful GPUs.
This is good for small batch sizes (e.g., when training on a CPU), where you should keep ``freeze_bn_stats=true``.
If you're using a GPU to train, you can obtain faster performance by setting a larger batch size (the biggest power of 2 where you don't geta CUDA out-of-memory error, such as 8, 16, 32 or 64 depending on the model, size of your images, and GPU memory) and ``freeze_bn_stats=false`` for the backbone of your model. 
This also allows you to increase the learning rate (empirically you can scale the learning rate by sqrt(batch_size) times).

Using 244 images and 13 for testing

Starting pose model training...
--------------------------------------------------
Traceback (most recent call last):
  File "/home/jdsweet_umass_edu/miniconda3/envs/DEEPLABCUT/lib/python3.10/site-packages/deeplabcut/gui/tabs/train_network.py", line 190, in train_network
    compat.train_network(config, shuffle, **kwargs)
  File "/home/jdsweet_umass_edu/miniconda3/envs/DEEPLABCUT/lib/python3.10/site-packages/deeplabcut/compat.py", line 245, in train_network
    return train_network(
  File "/home/jdsweet_umass_edu/miniconda3/envs/DEEPLABCUT/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/train.py", line 333, in train_network
    train(
  File "/home/jdsweet_umass_edu/miniconda3/envs/DEEPLABCUT/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/apis/train.py", line 183, in train
    runner.fit(
  File "/home/jdsweet_umass_edu/miniconda3/envs/DEEPLABCUT/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/runners/train.py", line 166, in fit
    train_loss = self._epoch(
  File "/home/jdsweet_umass_edu/miniconda3/envs/DEEPLABCUT/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/runners/train.py", line 217, in _epoch
    losses_dict = self.step(batch, mode)
  File "/home/jdsweet_umass_edu/miniconda3/envs/DEEPLABCUT/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/runners/train.py", line 307, in step
    outputs = self.model(inputs)
  File "/home/jdsweet_umass_edu/miniconda3/envs/DEEPLABCUT/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jdsweet_umass_edu/miniconda3/envs/DEEPLABCUT/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jdsweet_umass_edu/miniconda3/envs/DEEPLABCUT/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/models/model.py", line 78, in forward
    features = self.backbone(x)
  File "/home/jdsweet_umass_edu/miniconda3/envs/DEEPLABCUT/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jdsweet_umass_edu/miniconda3/envs/DEEPLABCUT/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jdsweet_umass_edu/miniconda3/envs/DEEPLABCUT/lib/python3.10/site-packages/deeplabcut/pose_estimation_pytorch/models/backbones/resnet.py", line 80, in forward
    return self.model.forward_features(x)
  File "/home/jdsweet_umass_edu/miniconda3/envs/DEEPLABCUT/lib/python3.10/site-packages/timm/models/resnet.py", line 614, in forward_features
    x = self.conv1(x)
  File "/home/jdsweet_umass_edu/miniconda3/envs/DEEPLABCUT/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jdsweet_umass_edu/miniconda3/envs/DEEPLABCUT/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jdsweet_umass_edu/miniconda3/envs/DEEPLABCUT/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/jdsweet_umass_edu/miniconda3/envs/DEEPLABCUT/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 288.00 MiB. GPU 0 has a total capacity of 10.75 GiB of which 89.62 MiB is free. Including non-PyTorch memory, this process has 10.66 GiB memory in use. Of the allocated memory 10.46 GiB is allocated by PyTorch, and 19.87 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @sjakes201! How big are the images in your dataset (or what is the resolution of the videos)?

You seem to have a pretty small GPU, which is why it might be struggling with bigger batch sizes. If you get CUDA out-of-memory errors with batch size 2, then your GPU will also be used when running with batch size 1. If you want to check that that's the case, you can always run `nvidia-smi` to check that it's being used (or [`nvitop`](https://nvitop.readthedocs.io/en/latest/), which is a tool I love).

It's not an issue to train with batch size 1, it's just a bit slower: so if your model trains fast enough and converges, I wouldn't worry about it. If you do want to train with higher batch size, you can always try to reduce the image size that you're training with. This is handled by the `collate` settings:

```yaml
data:
  colormode: RGB
  inference:
    normalize_images: True
  train:
    ...
    collate:
      type: ResizeFromDataSizeCollate
      min_scale: 0.4
      max_scale: 1.0
      min_short_side: 128
      max_short_side: 1152
      multiple_of: 32
      to_square: False
```

You could reduce `max_short_side: 640` or some similar value, depending on how your model is performing (see the docs for `collate` [here](https://deeplabcut.github.io/DeepLabCut/docs/pytorch/pytorch_config.html#data))

**Comment by sjakes201** [comment]
Hi, thanks so much for the response.

The images are high resolution, 4k images, and they are 'cropped' in config.yaml to 3840x2160 (so not cropped). Should I manually reduce the resolution, or can deeplabcut automatically do that before training? Also, where are the data settings you just referenced? I can't seem to find them in config.yaml or pose_cfg.yaml. 

Also, I am training on my University's computer cluster. They have a lot of GPU's available, I only requested one because I didn't know if deeplabcut would utilize them. If I have multiple GPU's, will deeplabcut automatically use them or will it only use one gpu?

Thanks,
Jake

**Comment by AlexEMG** [comment]
Unless you need this high resolution, e.g. because you have lots of small animals that you want to track I would really recommend to downsample the video first. That will make training and inference much faster, as well as the performance more robust. Be sure to apply the same downsampling consistently. 

Check out this old white paper for some quantification: https://www.biorxiv.org/content/10.1101/457242v1

**Comment by n-poulsen** [comment]
Some more technical/practical answers as well:

> Should I manually reduce the resolution, or can deeplabcut automatically do that before training

The collate function will lower the resolution for you:

```yaml
collate:
      type: ResizeFromDataSizeCollate
      min_scale: 0.4
      max_scale: 1.0
      min_short_side: 128
      max_short_side: 1152
      multiple_of: 32
      to_square: False
```

The `min_scale`/`max_scale` means batches of images will be randomly resized from 40% to 100% of their original size when training. Images given to the model to train would then be between 1536x864 and 3840x2160 pixels. But as the `max_short_side` is set to `1152`, any image greater than 2048x1152 would be resized to 2048x1152. As @AlexEMG said, that's still way too big to train.

You can take two paths to lower the image resolution while training.

**Option 1 (faster way to do it)**: Update the collate function, reducing the `min_scale`/`max_scale` parameters. An example would be setting the values to `min_scale: 0.2` and `max_scale: 0.4` so the model will get batches of images that will be between `768x432` and `1536x864` pixels, which is much more reasonable (read https://www.biorxiv.org/content/10.1101/457242v1 to decide which image/video size you want to use!).

Note that you then need to resize your videos before running inference! You can do so with DeepLabCut:
- GUI: downsample in the video editor tab, all the way to the right
- Code: with [`deeplabcut.DownSampleVideo`](https://github.com/DeepLabCut/DeepLabCut/blob/ffcd2908cdf6d5a6cd36ae980433a7a895b183d1/deeplabcut/utils/auxfun_videos.py#L522)

**Option 2 (better way to do it)**: Downsample the videos and images you extracted. This will take a bit more time, but is the more robust option. If you take this approach, make sure you backup your data before starting (or do this in a new "copy" of the project) so you can 

1. Downsample your video
2. Re-extract the same frames from the video as you have already labeled
3. Update your labels to reflect the smaller frames (in the `CollectedData_....h5` files!) - the labels you created are stored in pixels, so smaller images means the labels are scaled true 
4. Retrain on the smaller images

> If I have multiple GPU's, will deeplabcut automatically use them or will it only use one gpu?

DeepLabCut won't automatically do multi-GPU training, but it can be done through the GPUs parameter when training (see the code [here](https://github.com/DeepLabCut/DeepLabCut/blob/ffcd2908cdf6d5a6cd36ae980433a7a895b183d1/deeplabcut/pose_estimation_pytorch/apis/train.py#L64)). If you have multiple GPUs, you can also use them to run video analysis in parallel (analyze different videos on different GPUs).
