### ISSUE TITLE
ResNet weights not downloaded

### ISSUE THREAD

**Issue by jchutrue** [DeepLabCut/DeepLabCut#276]
I was going through the `Demo_yourowndata notebook`; when I came to the step
`deeplabcut.train_network(path_config_file)`, there was an error:

ValueError: The passed save_path is not a valid checkpoint: /home/jc/applications/anaconda3/envs/dlc/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt

After I checked the path, there was indeed no `resnet_v1_50.ckpt` file.

I have v2.0.6 installed, and I believe the problem code is here:

https://github.com/AlexEMG/DeepLabCut/blob/20bb84dcdb740a73c8644d8abe70c5b20e64078f/deeplabcut/generate_training_dataset/trainingsetmanipulation.py#L544-L545

I saw the print statement execute, but it seems there may not have been a download.sh script to run (aside from the fact that this code will not work cross-platform)

Assistance would be much appreciated, thanks!

**Comment by MMathisLab** [comment]
HI @jchutrue - perhaps you don't have permission to download; typically only comes up for windows users, but based on your paths seems you use linux; either way, here is the solution, as on the wiki: https://github.com/AlexEMG/DeepLabCut/wiki/Troubleshooting-Tips (and issues #217 , #150 and here:https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#f-create-training-dataset)

**Weights not downloaded.** If you get permission errors FileNotFound (or ValueError: The passed save_path is not a valid checkpoint: xxx\Deeplabcut\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt) when you run training, first check if the RestNet weights downloaded.

This is an error more common in Windows, but some docker containers might not have privileges for this (it can be user specific). They should be under 'init_weights' (see path in the pose_cfg.yaml file). For Windows, also please install GITBASH https://gitforwindows.org/ and OPEN cmd by right-clicking "run as ADIM"

You can "cd" in the terminal to the package location!

i.e. in linux copy and paste this in: cd usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/

in Windows: cd C:\Users\YourComputerName\Anaconda3\envs\DLC\Lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained

And if you type "ls" to see the list of files, you should see the resnet: resnet_v1_50.ckpt

If it is not there, run sudo download.sh then change the permissions: sudo chown yourusername:yourusername resnet_v1_50.ckpt

See more tips here: https://github.com/MMathisLab/Docker4DeepLabCut2.0#using-the-docker-for-training-and-video-analysis

**Comment by jchutrue** [comment]
This might have been an issue with multiple deeplabcut versions on my machine. So I attempted to do a fresh install in a new conda environment:
```
conda create -n dlc python=3.6
source activate dlc
pip install deeplabcut
pip install https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04/wxPython-4.0.3-cp36-cp36m-linux_x86_64.whl
pip install tensorflow==1.13.1
```
But when I tried to test the installation:
```
import deeplabcut
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jc/applications/anaconda3/envs/dlc/lib/python3.6/site-packages/deeplabcut/__init__.py", line 54, in <module>
    from deeplabcut.pose_estimation_tensorflow import train_network, train_network_path
ImportError: cannot import name 'train_network_path'
```

**Comment by MMathisLab** [comment]
Oh shoot... can you pip install deeplabcut==2.0.6 instead for now.
 Will fix this, thanks!

**Comment by jchutrue** [comment]
2.0.6 worked, thanks!

**Comment by MMathisLab** [comment]
2.0.6.2 is up now! Since original issue is resolved I will close it. 
Thanks for finding the 🐛 otherwise!
