### ISSUE TITLE
mp4 files don't show up in create project GUI if extension in uppercase

### ISSUE THREAD

**Issue by the-me-0** [DeepLabCut/DeepLabCut#2760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hello there !
I'm trying to use DeepLabCut and I'm very new to all this, but I fell upon a minor issue with the app. When trying to load some videos from a directory, DLC did not seem to detect my videos. I found the answer to my question here : https://forum.image.sc/t/video-files-not-appearing-when-creating-new-project-in-gui/85614
TL;DR : when mp4 videos have their extension in uppercase (".MP4" instead of ".mp4"), DLC does not find them.

But as mentionned in this forum, shouldn't this case be handled in the code, and should be easy to fix ?

### Operating System

WSL Ubuntu

### DeepLabCut version

3.0.0rc5

### DeepLabCut mode

multi animal

### Device type

GeForce 3060 RTX (laptop version)

### Steps To Reproduce

1. Install DLC using the official guide (conda)
2. Start DLC in the environment created during the install
3. Click on "create a new project"
4. Try to load mp4 files with uppercase extension
5. Videos don't show up

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by ronensgv** [comment]
If you have small number of files to analyze, just change it manually to lower case extension and it works.

**Comment by n-poulsen** [comment]
Fixed in the latest code, run  `pip install "git+https://github.com/DeepLabCut/DeepLabCut.git@pytorch_dlc#egg=deeplabcut"` to update

**Comment by the-me-0** [comment]
Thks for taking the time !
I know switching from MP4 to mp4 in my files does the trick (it's what I ended up doing), but I figured it would be such an easy fix in the code that an issue was welcomed.
Have a nive day all !
