### ISSUE TITLE
Linux 6.8.0-40-generic / Ubuntu 22.04.5 LTS segment fault error when trying to label frames 

### ISSUE THREAD

**Issue by gothinred** [DeepLabCut/DeepLabCut#2762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

was able to create a dataset from an avi video, already had frames cut from previous research so i tried to implement them through "label frames" from a different folder. dlc crashes as soon as i try to open the frames with error: 
RuntimeWarning: divide by zero encountered in dividenp.divide(data.shape, MAX_TEXTURE_SIZE) 
RuntimeWarning: invalid value encountered in cast).astype(int) 
WARNING: vispy: OpenGl version could not be determined, which might be a sign that OpenGL is not loaded correctly.
Segment fault (core dumped) 

### Operating System

 Ubuntu 22.04.5 LTS

### DeepLabCut version

dlc version: 3.0.0 rc5

### DeepLabCut mode

single animal

### Device type

gpu

### Anything else?

I'm extremely new to python, DLC, and coding in general. Any advice would be helpful. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
hi @gothinred strange! the GUI works for my on 22.04 LTS. Can you tell me a bit how you installed the software, i.e. all steps I would beed to review to give better feedback.
