### ISSUE TITLE
3D-pose-reconstruction of Multiple Interacting Individuals?

### ISSUE THREAD

**Issue by iandol** [DeepLabCut/DeepLabCut#277]
**Your Operating system and DeepLabCut version**

Ubuntu 18.04, Conda, & DeepLabCut 2.x.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Our potential use case is to track social relationships amongst 9 group house macaque monkeys. Individuals move around the home environment (a rectangular room), and individuals who spend more time in physical interaction (i.e. grooming) have closer relationships. Ideally we'd like to track the 3D pose to measure specific types of physical interaction, rather than just proximity.

**Describe alternatives you've considered**
Well, currently this needs to be done manually...

**Additional context**
We will place multiple cameras in the home environment. Although social relationships can most simply be inferred from proximity, this fails to account for the actual social interaction among pairs of monkeys (grooming as the canonical example). We have the luxury of adding additional data, in the form of digital accelerometers on each individual, and so we can try to combine the two data streams post-hoc. But I wondered how to use the accelerometer data to feed in to improve DLC estimation? Another option is to try to use a parallel face recognition network (macaques are pretty distinguishable) to create the individual subject labels. What other features would be required for this kind of use case to be viable?

**Comment by arnitkun** [comment]
Hi!

 They have extensively defined the process [https://www.biorxiv.org/content/10.1101/476531v1.full](here).

Although I wonder how the system would perform given that the entities would be in close proximity, more so when there are more than one.

**Comment by iandol** [comment]
Yes, this is what I am concerned about, grooming involves very close proximity in any body configuration, so was wondering if accelerometer data could help somehow?

**Comment by arnitkun** [comment]
The issue IMO would be straight up the system getting confused which part belongs where, or rather to which subject. 

I have seen DLC trying to estimate position for occluding parts to some accuracy( a while ago), and while it might be possible to predict the movement of some part at time T using acceleration, someone who might have augmented DLC with extra sensors can tell how that worked out.

**Comment by MMathisLab** [comment]
New 3D tools will be out soon, and as we have discussed in other issues (#50 #71, #228) we will be releasing multi-animal tracking in the future ;)

**Comment by AlexEMG** [comment]
Starting with https://github.com/DeepLabCut/DeepLabCut/tree/v2.2b5 there is (finally) very strong multi-animal support built in! Please let us know how it goes.
