### ISSUE TITLE
DLC Gitter Spam 

### ISSUE THREAD

**Issue by Tetra-quark** [DeepLabCut/DeepLabCut#2777]
Sorry I'm not sure this is the best place to raise this issue but the DLC gitter has become unusable due to spam bots for the last month. I notice there aren't many mods, any chance of assigning some trusted people to kick out any accounts like this?
Happy to volunteer myself although I'm of course thinking of @KonradDanielewski given how consistently active he is on the forums. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @Tetra-quark! Thanks for reporting this - we're working on it

**Comment by MMathisLab** [comment]
Both yourself and @KonradDanielewski we can happily make mods!! @n-poulsen

**Comment by n-poulsen** [comment]
Fixed!
