### ISSUE TITLE
Can't label frames in napari: no frames displayed

### ISSUE THREAD

**Issue by anthoni0n** [DeepLabCut/DeepLabCut#2783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I try to use DLC in a jupyter notebook. Everything is fine till the frame labelling. Napari opens but no frames is displayed. 

![image](https://github.com/user-attachments/assets/ac66d732-5efd-4811-a9a4-3abbd89a9018)

Here is my jupyter:
[dlctest - Copie.zip](https://github.com/user-attachments/files/17706945/dlctest.-.Copie.zip)

PS: I tried the GUI but had some bugs, that's why I use a jupyter notebook

### Operating System

Windows 10

### DeepLabCut version

dlc version 3.0.0rc6
Anaconda
I installed dlc with the DEEPLABCUT.yalm file

### DeepLabCut mode

multi animal

### Device type

Intel(R) Core(TM) i5-10200H 2.4GHz
Geforce RTX 3050 laptop gpu

### Steps To Reproduce

Run script in with virtual environment.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by n-poulsen** [comment]
Hi @anthoni0n! Could you please run `napari --info` and `pip list` in your conda environment and share the output so I can try to reproduce your issue?
