### ISSUE TITLE
.h5 File Cannot be Found in ../Evaluation-Tools/Results

### ISSUE THREAD

**Issue by cathy-liu23** [DeepLabCut/DeepLabCut#28]
Thank you so much for the help!!

**Describe the problem**
While running CUDA_VISIBLE_DEVICES=0 python3 Step1_EvaluateModelonDataset.py in Evaluation-Tools, the .h5 file that should be in the Results folder seems to be missing.

Previously, we had trained using a different dataset, and the .h5 file from that training is still in the Results folder. After terminating the second training, should the .h5 file for the second dataset be generated automatically in the Results folder? Will it cause any issues if there already exists a Results folder (from the first training set) in Evaluation-Tools? 

**Here is the exact error that appeared in terminal:**
Traceback (most recent call last):
  File "EvaluateNetwork.py", line 89, in <module>
    Data = pd.read_hdf(os.path.join("Results",DLCscorer + '.h5'),'df_with_missing')
  File "/data/home/jli819/install/anaconda3/envs/deeplabcut/lib/python3.6/site-packages/pandas/io/pytables.py", line 371, in read_hdf
    'File %s does not exist' % path_or_buf)
FileNotFoundError: File Results/DeepCut_resnet_50_95shuffle1_400000forTask_fish0817v3.h5 does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "EvaluateNetwork.py", line 111, in <module>
    outputs_np = sess.run(outputs, feed_dict={inputs: image_batch})
  File "/data/home/jli819/install/anaconda3/envs/deeplabcut/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/data/home/jli819/install/anaconda3/envs/deeplabcut/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 944, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 972, 1296, 4) for Tensor 'Placeholder:0', which has shape '(1, ?, ?, 3)'

**To Reproduce**
Not sure if it can be described, but the .h5 file just doesn't seem to be generated.

**Screenshots**

**Additional context**

**Comment by MMathisLab** [comment]
Hello. yes, you need either keep the second training set in a separate folder, re-name the outputs, etc. I would recommend making a new training set, (new date, etc in config file), and keeping it separate...

**Comment by cathy-liu23** [comment]
After placing the new training set in a new folder, we still get the same error after training. Is it possible that this error is generated because Ctrl-C was pressed twice to terminate the training (otherwise the training seems to terminate for an infinite amount of time even after it has been interrupted with a keyboard interrupt). Thank you so much for the help!

Here is the error that appears in the terminal:
Analyzing data...
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "EvaluateNetwork.py", line 89, in <module>
    Data = pd.read_hdf(os.path.join("Results",DLCscorer + '.h5'),'df_with_missing')
  File "/data/home/jli819/install/anaconda3/envs/deeplabcut/lib/python3.6/site-packages/pandas/io/pytables.py", line 371, in read_hdf
    'File %s does not exist' % path_or_buf)
FileNotFoundError: File Results/DeepCut_resnet_50_95shuffle1_550000forTask_fish0817.h5 does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "EvaluateNetwork.py", line 111, in <module>
    outputs_np = sess.run(outputs, feed_dict={inputs: image_batch})
  File "/data/home/jli819/install/anaconda3/envs/deeplabcut/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/data/home/jli819/install/anaconda3/envs/deeplabcut/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 944, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 972, 1296, 4) for Tensor 'Placeholder:0', which has shape '(1, ?, ?, 3)'

**Comment by MMathisLab** [comment]
It appears that your video frames have 4 color channels, but training had 3. If that is true then just slice the image array before feeding it to the estimator

**Comment by cathy-liu23** [comment]
Thank you so much for your help!!

**Comment by banningjoe** [comment]
@cathy-liu23 Any possibility you could show the line of code which you need to modify in order to fix this? Having trouble debugging this myself.

**Comment by banningjoe** [comment]
That would be wonderful, thank you!

**Comment by Donnypickels** [comment]
During the evaluation I too get an error when I try with my own data. It seems that a file is not created?
this is the error i get:

```
FileNotFoundError                         Traceback (most recent call last)
C:\Users\Beheerder\Anaconda3\envs\dlc2-backup181115\lib\site-packages\deeplabcut\pose_estimation_tensorflow\evaluate.py in evaluate_network(config, Shuffles, plotting, show_errors, comparisonbodyparts, gputouse)
    152                 try:
--> 153                     DataMachine = pd.read_hdf(resultsfilename,'df_with_missing')
    154                     print("This net has already been evaluated!")

C:\Users\Beheerder\Anaconda3\envs\dlc2-backup181115\lib\site-packages\pandas\io\pytables.py in read_hdf(path_or_buf, key, mode, **kwargs)
    337             raise compat.FileNotFoundError(
--> 338                 'File %s does not exist' % path_or_buf)
    339 

FileNotFoundError: File C:\Users\Beheerder\Videos\DLC\test2\Testing 2-Donny-2018-11-20\evaluation-results\iteration-0\Testing 2Nov20-trainset95shuffle1\DeepCut_resnet50_Testing 2Nov20shuffle1_300-snapshot-300.h5 does not exist

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-9-0101317f4faf> in <module>()
----> 1 deeplabcut.evaluate_network(path_config_file)

C:\Users\Beheerder\Anaconda3\envs\dlc2-backup181115\lib\site-packages\deeplabcut\pose_estimation_tensorflow\evaluate.py in evaluate_network(config, Shuffles, plotting, show_errors, comparisonbodyparts, gputouse)
    166 
    167                         # Compute prediction with the CNN
--> 168                         outputs_np = sess.run(outputs, feed_dict={inputs: image_batch})
    169                         scmap, locref = ptf_predict.extract_cnn_output(outputs_np, dlc_cfg)
    170 

C:\Users\Beheerder\Anaconda3\envs\dlc2-backup181115\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    875     try:
    876       result = self._run(None, fetches, feed_dict, options_ptr,
--> 877                          run_metadata_ptr)
    878       if run_metadata:
    879         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

C:\Users\Beheerder\Anaconda3\envs\dlc2-backup181115\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1074                              'which has shape %r' %
   1075                              (np_val.shape, subfeed_t.name,
-> 1076                               str(subfeed_t.get_shape())))
   1077           if not self.graph.is_feedable(subfeed_t):
   1078             raise ValueError('Tensor %s may not be fed.' % subfeed_t)

ValueError: Cannot feed value of shape (1, 777, 1382, 4) for Tensor 'Placeholder:0', which has shape '(1, ?, ?, 3)'
```

During testing with the labelled data set it didn't give an error. I don't know what I'm doing different.
Anyone any idea? 

Thanks! :)

**Comment by MMathisLab** [comment]
`ValueError: Cannot feed value of shape (1, 777, 1382, 4) for Tensor 'Placeholder:0', which has shape '(1, ?, ?, 3)'` do your files have 4 channels?

**Comment by Donnypickels** [comment]
Oh damn, it only has 1.. The only thing I didn't see when comparing....
Guess I'm not fully awake.

Thanks a thousand times!

**Comment by MMathisLab** [comment]
No problem but it does seem to have 4 vs. 3 ... or at least DLC thinks it has 4... it may look monochrome, but typically they are 3 channels - maybe @AlexEMG has some code to slice this/test this... 

also, the spaces are not ideal in your files names, is the file actually in the folder? ... `evaluation-results\iteration-0\Testing 2Nov20-trainset95shuffle1\DeepCut_resnet50_Testing 2Nov20shuffle1_300-snapshot-300.h5` 

i.e. remove spaces between Testing and 2: `C:\Users\Beheerder\Videos\DLC\test2\Testing 2-Donny-2018-11-20\evaluation-results\iteration-0\Testing 2Nov20-trainset95shuffle1\DeepCut_resnet50_Testing 2Nov20shuffle1_300-snapshot-300.h5`

**Comment by Donnypickels** [comment]
The file was not in the folder. And where can I change the channel size?
My config as it shows right now is:
Config:
```
{'all_joints': [[0], [1], [2], [3], [4]],
 'all_joints_names': ['Thumb', 'Finger1', 'Finger2', 'Finger3', 'Finger4'],
 'batch_size': 1,
 'bottomheight': 400,
 'crop': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Testing2Nov21\\Testing2_Mitchel95shuffle1.mat',
 'dataset_type': 'default',
 'display_iters': 30,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'C:\\Users\\Beheerder\\Anaconda3\\envs\\dlc2-backup181115\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1000,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Testing2Nov21\\Documentation_data-Testing2_95shuffle1.pickle',
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 5,
 'optimizer': 'sgd',
 'pos_dist_thresh': 17,
 'project_path': 'C:\\Users\\Beheerder\\Videos\\DLC\\test2\\Testing2-Mitchel-2018-11-21',
 'regularize': False,
 'rightwidth': 400,
 'save_iters': 60,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'C:\\Users\\Beheerder\\Videos\\DLC\\test2\\Testing2-Mitchel-2018-11-21\\dlc-models\\iteration-0\\Testing2Nov21-trainset95shuffle1\\test\\snapshot',
 'stride': 8.0,
 'topheight': 400,
 'use_gt_segm': False,
 'video': False,
 'video_batch': False,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Config:
{'all_joints': [[0], [1], [2], [3], [4]],
 'all_joints_names': ['Thumb', 'Finger1', 'Finger2', 'Finger3', 'Finger4'],
 'batch_size': 1,
 'bottomheight': 400,
 'crop': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Testing2Nov21\\Testing2_Mitchel95shuffle1.mat',
 'dataset_type': 'default',
 'display_iters': 30,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'C:\\Users\\Beheerder\\Anaconda3\\envs\\dlc2-backup181115\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1000,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Testing2Nov21\\Documentation_data-Testing2_95shuffle1.pickle',
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 5,
 'optimizer': 'sgd',
 'pos_dist_thresh': 17,
 'project_path': 'C:\\Users\\Beheerder\\Videos\\DLC\\test2\\Testing2-Mitchel-2018-11-21',
 'regularize': False,
 'rightwidth': 400,
 'save_iters': 60,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'C:\\Users\\Beheerder\\Videos\\DLC\\test2\\Testing2-Mitchel-2018-11-21\\dlc-models\\iteration-0\\Testing2Nov21-trainset95shuffle1\\test\\snapshot',
 'stride': 8.0,
 'topheight': 400,
 'use_gt_segm': False,
 'video': False,
 'video_batch': False,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
```

Sorry for all the questions. And thanks for your answers! Really helps me a lot :)

**Comment by Donnypickels** [comment]
Were should I change the channel size? My configurations are as follows right now, but I get the same error:

```
Config:
{'all_joints': [[0], [1], [2], [3], [4]],
 'all_joints_names': ['Thumb', 'Finger1', 'Finger2', 'Finger3', 'Finger4'],
 'batch_size': 1,
 'bottomheight': 400,
 'crop': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Testing2Nov21\\Testing2_Donny95shuffle1.mat',
 'dataset_type': 'default',
 'display_iters': 30,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'C:\\Users\\Beheerder\\Anaconda3\\envs\\dlc2-backup181115\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1000,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Testing2Nov21\\Documentation_data-Testing2_95shuffle1.pickle',
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 5,
 'optimizer': 'sgd',
 'pos_dist_thresh': 17,
 'project_path': 'C:\\Users\\Beheerder\\Videos\\DLC\\test2\\Testing2-Donny-2018-11-21',
 'regularize': False,
 'rightwidth': 400,
 'save_iters': 60,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'C:\\Users\\Beheerder\\Videos\\DLC\\test2\\Testing2-Donny-2018-11-21\\dlc-models\\iteration-0\\Testing2Nov21-trainset95shuffle1\\test\\snapshot',
 'stride': 8.0,
 'topheight': 400,
 'use_gt_segm': False,
 'video': False,
 'video_batch': False,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Config:
{'all_joints': [[0], [1], [2], [3], [4]],
 'all_joints_names': ['Thumb', 'Finger1', 'Finger2', 'Finger3', 'Finger4'],
 'batch_size': 1,
 'bottomheight': 400,
 'crop': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Testing2Nov21\\Testing2_Donny95shuffle1.mat',
 'dataset_type': 'default',
 'display_iters': 30,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'C:\\Users\\Beheerder\\Anaconda3\\envs\\dlc2-backup181115\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1000,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_Testing2Nov21\\Documentation_data-Testing2_95shuffle1.pickle',
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 5,
 'optimizer': 'sgd',
 'pos_dist_thresh': 17,
 'project_path': 'C:\\Users\\Beheerder\\Videos\\DLC\\test2\\Testing2-Donny-2018-11-21',
 'regularize': False,
 'rightwidth': 400,
 'save_iters': 60,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'C:\\Users\\Beheerder\\Videos\\DLC\\test2\\Testing2-Donny-2018-11-21\\dlc-models\\iteration-0\\Testing2Nov21-trainset95shuffle1\\test\\snapshot',
 'stride': 8.0,
 'topheight': 400,
 'use_gt_segm': False,
 'video': False,
 'video_batch': False,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
```

Sorry for all the questions, And thank you so much for answering. Helps me a lot :)

**Comment by MMathisLab** [comment]
okay, it might also be a video type error, i.e. the default is .avi, and if your videos are something else, you need to set `videotype=mp4` for example)

**Comment by Donnypickels** [comment]
I just was typing that I was using an mp4 video, I'll try changing the videotype. I'll let it know if it worked

Edit: Changing the videotype works!

**Comment by MMathisLab** [comment]
excellent, okay I will add this error to the https://github.com/AlexEMG/DeepLabCut/wiki/Troubleshooting-Tips

**Comment by Donnypickels** [comment]
Seems to be a little bit confusion at my side, My `deeplabcut.analyze_videos(path_config_file,[videofile_path])` works. 

However, now when I'm trying to run it again, I again got stuck at the same place, the evaluation. 
I get the same error (as I posted few posts above), produced by `deeplabcut.evaluate_network(path_config_file)`

(seems that I was trying to get evaluate working and just replaced the evaluate call with analyze and thought it worked...)

Still have the error that the snapshot is not found and the value error.

(When i change my path_config_file to the labelled example, I don't get this error and it runs just fine. So is it the difference in the videos or the labelling/training process?)

**Comment by imagejan** [comment]
@Donnypickels could you check if the extracted frames (`*.png`) in your folders are still the correct ones (i.e. not containing any labels, as opposed to the files in the `*_labelled` subfolders), and otherwise start again and extract new frames?

That's what seems to have been the issue in #127.

**Comment by MMathisLab** [comment]
^good point: delete the frames that say “labeled” at the end and then it will work. This was fixed in dev7, but also fixed in 2.0.0 - so also you can update your package! :) `pip install deeplabcut==2.0.0`

**Comment by Donnypickels** [comment]
My folder  `labelled data` contains two folders, `*projectname*`, which contains a few `.png` which seem to have double labels (3 where I put them and 3 shifted to "south east") but they don't say labelled in the name,  and `*projectname*_labelled`, which is empty. Deleting `png` in the `*projectname*` folder results in an error saying `img011.png can't be found`.

I think I'll label them again and hope that solves it. I'll let it know.

ps. If I'm right I've the latest version of DLC

**Comment by MMathisLab** [comment]
(I just triple checked, in 2.0.0 we are good to go!)

**Comment by Donnypickels** [comment]
When I update Deeplabcut, and look for it with `conda list` I see I've got Deeplabcut 2.0.0.dev6
This is after running both `pip install deeplabcut --upgrade` and the `setup.py` from the github. Is that right? Because you were talking about dev7

**Comment by MMathisLab** [comment]
no, do `pip install deeplabcut==2.0.0` there was dev7, but now it's the first package release (we were beta testing for 14 days before officially releasing ;) also no need to run setup.py actually... that is done with the pip install (also here is the releases, if you want to keep up to date in the future/just in case! https://pypi.org/project/deeplabcut/#history)

**Comment by Donnypickels** [comment]
Cool thanks! It appeared that I had a double version somehow (I'm somehow unable to get rid of dev6) and might be the case that dev6 overruled... It's caused by some weird problem I was never able to fix than to just start with a clean environment. I'll do that and let you guys know! Thanks again for all the help

**Comment by MMathisLab** [comment]
you also don' t have to label again, you can just delete the labeled folder and any frames with your labels applied if that happened, and then run the next steps! The training was fine, it's just the evaluation step finds the funny images with 4 channels (the 4th being the applied labels).
