### ISSUE TITLE
i am planning to to do a multianimal project of snake and mangoose . i want to know , how can I label different body parts.please help me setting config file

### ISSUE THREAD

**Issue by cpchandrasekharan** [DeepLabCut/DeepLabCut#2808]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by maximpavliv** [comment]
Hello,

Please follow the documentation for [Single-Animal](https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html) and [Multi-Animal](https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html) projects.
If you have any further questions after reading this, feel free to ask them on [the forum](https://forum.image.sc/tag/deeplabcut), GitHub Issues should be used to report bugs / request features.
