### ISSUE TITLE
"module 'deeplabcut' has no attribute 'create new project' "

### ISSUE THREAD

**Issue by xt17** [DeepLabCut/DeepLabCut#282]
**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.
Windows 10, with an Anaconda Env, DeepLabCut (newest, downloaded yesterday (5.6.2019))
**If applicable, please also complete the following information:**
 - Browser [e.g. chrome, safari] Chrome
 
**Describe the bug**
A clear and concise description of what the bug is!

**To Reproduce**
1. Create a new Python project
2. run the code: 
import deeplabcut
task='xxx'
experimenter='xxxx'
video=['C:/xxx']
3. Then run the code:
path_config_file=deeplabcut.create_new_project(task,experimenter,video, working_directory='C:/Users/lenovo/deeplabcut',copy_videos=True) #change the directory as needed
AttributeError: module 'deeplabcut' has no attribute 'create_new_project'
**Expected behavior**
A new project (path_config_file) be created.
**Screenshots**
![image](https://user-images.githubusercontent.com/50376505/57318743-09671a00-70c9-11e9-99cb-cd74070c5640.png)
![image](https://user-images.githubusercontent.com/50376505/57318802-27cd1580-70c9-11e9-87b5-4a7a3d974b50.png)

**Additional context**

**Comment by MMathisLab** [comment]
Can you give more context? We cannot reproduce this on our local computers or on colab (check here: https://github.com/AlexEMG/DeepLabCut/blob/master/examples/Colab_DEMO_mouse_openfield.ipynb )

The only way I can imagine this happening is if you downloaded the code, it was corrupted or not fully downloaded, and you are running this code inside the “deeplabcut” folder, which would import locally. You can see where you are importing from by running: 

`Deeplabcut.__file__` and post that? 
Also, please try running your code from another folder (and fix the paths ;) see below).

**Comment by MMathisLab** [comment]
Also, unrelatedly, on Windows the paths must be formatted differently that you have in your screenshot - please check the docs under function details for the correct formatting.  

https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#a-create-a-new-project

**Comment by xt17** [comment]
> Also, unrelatedly, on Windows the paths must be formatted differently that you have in your screenshot - please check the docs under function details for the correct formatting.
> 
> https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#a-create-a-new-project

I guess the problem may be something is missing and the package is incomplete? 
By inputing, deeplabcut.__file__, I get 
![image](https://user-images.githubusercontent.com/50376505/57331056-b9e31700-70e5-11e9-9f3e-a45d705b8430.png)
And I also tried "dir(deeplabcut)". The output was 
![image](https://user-images.githubusercontent.com/50376505/57331124-e008b700-70e5-11e9-9d6c-47f8cc9f34ab.png)

**Comment by MMathisLab** [comment]
Yes, so please delete the folder and either use pip or if you want local code, download again.

**Comment by xt17** [comment]
> Yes, so please delete the folder and either use pip or if you want local code, download again.

![image](https://user-images.githubusercontent.com/50376505/57339139-68935180-70fe-11e9-93eb-0bd66fc6c30d.png)
When installing deeplabcut using pip, I encountered the following errors. Any suggestions? Thank you in advance!

**Comment by MMathisLab** [comment]
I highly recommend using this: https://github.com/AlexEMG/DeepLabCut/blob/master/conda-environments/README.md 

Simply download and run the one line of code :)

**Comment by xt17** [comment]
> I highly recommend using this: https://github.com/AlexEMG/DeepLabCut/blob/master/conda-environments/README.md
> 
> Simply download and run the one line of code :)

Thanks. I followed your instruction. But seems like another issue occurred... Below is the error report after I input " import deeplabcut":
C:\Users\lenovo\DeepLabCut\deeplabcut\__init__.py:32: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'module://ipykernel.pylab.backend_inline' by the following code:
  File "D:\anaconda\lib\site-packages\spyder\utils\ipython\start_kernel.py", line 269, in <module>
    main()
  File "D:\anaconda\lib\site-packages\spyder\utils\ipython\start_kernel.py", line 253, in main
    kernel.initialize()
  File "<decorator-gen-122>", line 2, in initialize
  File "D:\anaconda\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "D:\anaconda\lib\site-packages\ipykernel\kernelapp.py", line 472, in initialize
    self.init_code()
  File "D:\anaconda\lib\site-packages\IPython\core\shellapp.py", line 261, in init_code
    self._run_exec_lines()
  File "D:\anaconda\lib\site-packages\IPython\core\shellapp.py", line 287, in _run_exec_lines
    self.shell.run_cell(line, store_history=False)
  File "D:\anaconda\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "D:\anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2693, in run_cell
    self.events.trigger('post_run_cell')
  File "D:\anaconda\lib\site-packages\IPython\core\events.py", line 73, in trigger
    func(*args, **kwargs)
  File "D:\anaconda\lib\site-packages\ipykernel\pylab\backend_inline.py", line 160, in configure_once
    activate_matplotlib(backend)
  File "D:\anaconda\lib\site-packages\IPython\core\pylabtools.py", line 309, in activate_matplotlib
    matplotlib.pyplot.switch_backend(backend)
  File "D:\anaconda\lib\site-packages\matplotlib\pyplot.py", line 231, in switch_backend
    matplotlib.use(newbackend, warn=False, force=True)
  File "D:\anaconda\lib\site-packages\matplotlib\__init__.py", line 1410, in use
    reload(sys.modules['matplotlib.backends'])
  File "D:\anaconda\lib\importlib\__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "D:\anaconda\lib\site-packages\matplotlib\backends\__init__.py", line 16, in <module>
    line for line in traceback.format_stack()


  mpl.use('TkAgg')
Traceback (most recent call last):

  File "<ipython-input-3-52d2df9c7fa5>", line 1, in <module>
    import deeplabcut

  File "C:\Users\lenovo\DeepLabCut\deeplabcut\__init__.py", line 33, in <module>
    from deeplabcut import generate_training_dataset

  File "C:\Users\lenovo\DeepLabCut\deeplabcut\generate_training_dataset\__init__.py", line 15, in <module>
    from deeplabcut.generate_training_dataset.auxfun_drag_label import *

  File "C:\Users\lenovo\DeepLabCut\deeplabcut\generate_training_dataset\auxfun_drag_label.py", line 18, in <module>
    import wx

ModuleNotFoundError: No module named 'wx'

Where should I find this "wx"?

Many thanks!

**Comment by AlexEMG** [comment]
The conda environment will have installed wx... https://github.com/AlexEMG/DeepLabCut/blob/master/conda-environments/dlc-windowsCPU.yaml

or ```   pip install -U wxPython```
see https://wiki.wxpython.org/How%20to%20install%20wxPython

**Comment by xt17** [comment]
> The conda environment will have installed wx... https://github.com/AlexEMG/DeepLabCut/blob/master/conda-environments/dlc-windowsCPU.yaml
> 
> or ` pip install -U wxPython`
> see https://wiki.wxpython.org/How%20to%20install%20wxPython

Thank you Finally it works!!!! FYI, it only works when I use anaconda prompt to use python, but it doesn't work when I use Spyder. Still have no idea why it didn't work, but I hope this information can somehow provide some evidence. Again, than you sooooooooooooooo much!

**Comment by AlexEMG** [comment]
Keep in mind that spyder can be linked to different versions of python you might have installed... https://stackoverflow.com/questions/43592879/how-to-change-python-version-in-anaconda-spyder
