### ISSUE TITLE
.h5 file and .pickle file can't be found

### ISSUE THREAD

**Issue by LiuXin-Chern** [DeepLabCut/DeepLabCut#284]
**Your Operating system and DeepLabCut version**
 Windows10, with an Anaconda Env, & DeepLabCut2.0.6.
 
**Describe the bug**
When I run the code:deeplabcut.analyle_video(path_config_file,videofile_path,videotype='.avi'),
the error is： reachingvideo1DeepCut_resnet101_MouseMay6shuffle1_30000.h5 and reachingvideo1DeepCut_resnet101_MouseMay6shuffle1_30000includingmetadata.pickle can't be foud.
When was the files generated?What function generates this file?
Loook forward to your assistence.

**Comment by MMathisLab** [comment]
You said the same in issue #283 (under a different name?) and I responded. Please don’t open new issues with the identical question.
