### ISSUE TITLE
Cannot find the right path to download the pretrained model

### ISSUE THREAD

**Issue by afunTW** [DeepLabCut/DeepLabCut#288]
**Your Operating system and DeepLabCut version**

Ubuntu 16.04 LTS on server
DeepLabCut 2.0.6.2
Python 3.6 with pipenv

**Describe the problem**

invoke `deeplabcut.create_training_dataset(config_path)` in virtualenv cannot find the directory
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/afun/.local/share/virtualenvs/buried-mouse-track-4ezhdAuL/lib/python3.6/site-packages/deeplabcut-2.0.6.2-py3.6.egg/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 548, in create_training_dataset
NotADirectoryError: [Errno 20] Not a directory: '/home/afun/.local/share/virtualenvs/buried-mouse-track-4ezhdAuL/lib/python3.6/site-packages/deeplabcut-2.0.6.2-py3.6.egg/deeplabcut/pose_estimation_tensorflow/models/pretrained'
```

**Comment by MMathisLab** [comment]
Please check out the wiki for tips on “manually” downloading the weights then.

**Comment by AlexEMG** [comment]
Copied instructions:

Weights not downloaded. If you get permission errors FileNotFound (or ValueError: The passed save_path is not a valid checkpoint: xxx\Deeplabcut\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt) when you run training, first check if the RestNet weights downloaded.

This is an error more common in Windows, but some docker containers might not have privileges for this (it can be user specific). They should be under 'init_weights' (see path in the pose_cfg.yaml file). For Windows, also please install GITBASH https://gitforwindows.org/ and OPEN cmd by right-clicking "run as ADIM"

You can "cd" in the terminal to the package location!

i.e. in linux copy and paste this in: cd usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/

in Windows: cd C:\Users\YourComputerName\Anaconda3\envs\DLC\Lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained

And if you type "ls" to see the list of files, you should see the resnet: resnet_v1_50.ckpt

If it is not there, run sudo download.sh then change the permissions: sudo chown yourusername:yourusername resnet_v1_50.ckpt

From: https://github.com/AlexEMG/DeepLabCut/wiki/Troubleshooting-Tips

**Comment by AlexEMG** [comment]
Also check out: https://github.com/AlexEMG/DeepLabCut/pull/280 
This could be simplified in the future...

**Comment by afunTW** [comment]
I checked this out and download the weight manually. **But the same error occurred.**
My error is `NotADirectoryError` rather than `FileNotFound` or `ValueError`.
Also, my platform is ubuntu 16.04 server, not the Windows.

Any other suggestion there? Thanks for the reply.

**Comment by AlexEMG** [comment]
Can you confirm that the weights are downloaded to the correct DLC path. I.e. in the subfolder of ```deeplabcut.__file__```?

**Comment by afunTW** [comment]
It's under the `DeepLabCut/deeplabcut/pose_estimation_tensorflow/models/pretrained`

```
drwxrwxr-x 2 afun afun      4096 May 13 12:16 ./
drwxrwxr-x 3 afun afun      4096 May  7 11:19 ../
-rw-rw-r-- 1 afun afun       180 May  7 11:19 download.sh
-rw-rw-r-- 1 afun afun         0 May  7 11:19 __init__.py
-rw-r----- 1 afun afun 178740809 Aug 29  2016 resnet_v1_101.ckpt
-rw-r----- 1 afun afun 102500712 Aug 29  2016 resnet_v1_50.ckpt
```

**Comment by afunTW** [comment]
**Some workaround for this issue**

The egg file is just the zip file so we can unzip it.

```
$ cd PATH_TO_EGG_IN_VIRTUALENV
$ unzip deeplabcut-2.0.6.2-py3.6.egg # and you will get a directory named `deeplabcut/`
$ cd deeplabcut/pose_estimation_tensorflow/models/pretrained
$ sh download.sh
```

If you clone DeepLabCut from GitHub and manually run the download shell, the model checkpoint will  store in that repo (source from GitHub), but it's not the path from egg file (placed in virtualenv)

Moreover, I tried to run the download.sh in the repo from GitHub and install by `python3 setup.py install` again, but it doesn't work.

**Comment by AlexEMG** [comment]
Great, you just need to copy the snapshots to he virtualenv path.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jchutrue** [comment]
Hope I'm not interrupting, but this is an interesting issue that's probably related to the way different virtual environment managers work. 

@afunTW it sounds like the parent directory of `deeplabcut.__file__` is a zip file. This will clearly not work, resulting in the error you described. Yet you are still able to `import deeplabcut` so the source files must be somewhere. Do you know how and where `pipenv` extracts the source files of installed packages? That's the directory the downloaded models should go.

**Comment by afunTW** [comment]
@jchutrue Thanks for your notification, I tried the different way to install deeplabcut in `pipenv`

## Case 1 `python setup.py install` in virtualenv
```
(project) afun@ubuntu-server:~/project/DeepLabCut/deeplabcut$ python3 setup.py install
```

Although this method will install the deeplabcut in the virtualenv (at the `$(pipenv --venv)/lib/python3.6/site-packages`), but it will be the egg file.


## Case 2 `pipenv install deeplabcut` after ensuring dependencies
```
# ensure the python version is 3.6
afun@ubuntu-server:~/project/DeepLabCut/deeplabcut$ pipenv shell --python=python3.6

# fixed the bug of pipenv
afun@ubuntu-server:~/project/DeepLabCut/deeplabcut$ pipenv run pip install pip==18.0

# manually install the wxPython for python 3.6
afun@ubuntu-server:~/project/DeepLabCut/deeplabcut$ pipenv run pip -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 wxPython

# install the deeplabcut and unzip by pipenv
afun@ubuntu-server:~/project/DeepLabCut/deeplabcut$ pipenv install deeplabcut
```

@AlexEMG I think it's the right steps to install the deeplabcut in `pipenv` without any code modification

**Comment by jchutrue** [comment]
@afunTW There are some things in this installation that are unexpected, but glad you were able to get a working solution. Just for reference:

## Case 1
I am unable to replicate the issue you ran into i.e. the parent directory of `deeplabcut.__file__` points to an egg file. Usually I install from source with the following commands:
```
jchu@ubuntu:~/code$ git clone https://github.com/AlexEMG/DeepLabCut
jchu@ubuntu:~/code$ cd DeepLabCut
jchu@ubuntu:~/code/DeepLabCut$ pip install .
```

Then after importing `deeplabcut`, `deeplabcut.__file__` is `/home/jchu/code/DeepLabCut/deeplabcut/__init__.py`, which is the expected output.

Regarding virtual environment setup, so far docker and conda are the only de-facto methods that are officially supported. Unless you are required to use `virtualenv` or `pipenv`, I would highly recommend `conda`. It solves a lot of the dependency issues people have run into. Also there are advantages of using `conda` packages. For example, `numpy` will already be BLAS-optimized, `tensorflow-gpu` installs cuDNN and the CUDA toolkit so you don't have to use a system-wide installation, etc.

**Comment by afunTW** [comment]
@jchutrue thanks to your advisement, but my developer environment is limited.

Also `conda` is a well-known tool but somehow the package source is different from pip, there's' still some consideration to choose between `conda` and `pipenv` / `virtualenv`
