### ISSUE TITLE
Issue with AnalyseVideos.py (Moviepy installation problem) 

### ISSUE THREAD

**Issue by neurvanna** [DeepLabCut/DeepLabCut#29]
Thanks in advance for any comments or suggestions.

 **Describe the problem**
An error occurred in AnalyseVideos.py
After running the evaluation, I now have a file named "DeepCut_resnet_50_95shuffle1_50000forTask_reaching.h5" in Evaluation-Tools/Results folder.
I also have a video named "MovieS2_Perturbation_noLaser_compressed" in DeepLabCut/videos folder.
I called AnalyseVideos.py from Analysis-tools folder, and the path to videos in myconfig_analysis.py is set to videofolder = '../videos/'. Therefore, it should have the video file in it. However when I run the script I get an error saying that the file could not be found. Please help me!

**Here is the exact error that appeared in terminal:**

FileNotFoundError: File MovieS2_Perturbation_noLaser_compressedDeepCut_resnet50_
reachingJan30shuffle1_50000.h5 does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "AnalyzeVideos.py", line 124, in <module>
    clip = VideoFileClip(video)
  File "C:\Users\annaL\AppData\Local\Programs\Python\Python35\lib\site-packages\
moviepy\video\io\VideoFileClip.py", line 91, in __init__
    fps_source=fps_source)
  File "C:\Users\annaL\AppData\Local\Programs\Python\Python35\lib\site-packages\
moviepy\video\io\ffmpeg_reader.py", line 33, in __init__
    fps_source)
  File "C:\Users\annaL\AppData\Local\Programs\Python\Python35\lib\site-packages\
moviepy\video\io\ffmpeg_reader.py", line 272, in ffmpeg_parse_infos
    "path.")%filename)
OSError: MoviePy error: the file MovieS2_Perturbation_noLaser_compressed.avi cou
ld not be found!
Please check that you entered the correct path.

**Comment by AlexEMG** [comment]
Hey,

You seem to mix up 2 things:

"Evaluation-Tools/Results"  contains evaluation files of the train/test set. I.e. DeepCut_resnet_50_95shuffle1_50000forTask_reaching.h5 is one of those

In https://github.com/AlexEMG/DeepLabCut/tree/master/Analysis-tools one runs the trained network for videos (e.g. in ../videos/) Did you do that? Does "MovieS2_Perturbation_noLaser_compressedDeepCut_resnet50_
reachingJan30shuffle1_50000.h5" 

exist there?

Cheers,
Alexander

**Comment by neurvanna** [comment]
Hello Alex, thank you for your reply.

I ran the evaluation successfully. 
I wasn't able to run the analysis. I thought the problem might have emerged because something went wrong at one of the previous steps.. The only file that I have in the ../videos/ folder is the video itself.

Thank you.

**Comment by AlexEMG** [comment]
I see. Judged by "Traceback (most recent call last):
File "AnalyzeVideos.py", line 124, in 
clip = VideoFileClip(video)
File "C:\Users\annaL\AppData\Local\Programs\Python\Python35\lib\site-packages
moviepy\video\io\VideoFileClip.py", line 91, in init
fps_source=fps_source)
File "C:\Users\annaL\AppData\Local\Programs\Python\Python35\lib\site-packages
moviepy\video\io\ffmpeg_reader.py", line 33, in init
fps_source)
File "C:\Users\annaL\AppData\Local\Programs\Python\Python35\lib\site-packages
moviepy\video\io\ffmpeg_reader.py", line 272, in ffmpeg_parse_infos
"path.")%filename)
OSError: MoviePy error: the file MovieS2_Perturbation_noLaser_compressed.avi cou
ld not be found!
Please check that you entered the correct path." 

I wonder if your MoviePy works correctly? Can you open videos?

**Comment by neurvanna** [comment]
No, it doesn't! Just tried to open the video "MovieS2_Perturbation_noLaser_compressed.avi" with MoviePy, it doesn't work. Trying to understand why. Thanks for your help!

**Comment by AlexEMG** [comment]
Ok, I suppose linking ffmpeg to moviepy is your problem. Please check out the help for [moviepy](http://zulko.github.io/moviepy/install.html):

MoviePy depends on the software FFMPEG for video reading and writing. You don’t need to worry about that, as FFMPEG should be automatically downloaded/installed by ImageIO during your first use of MoviePy (it takes a few seconds). If you want to use a specific version of FFMPEG, you can set the FFMPEG_BINARY environment variable See moviepy/config_defaults.py for details.
