### ISSUE TITLE
Video path disallowed the special character and space

### ISSUE THREAD

**Issue by afunTW** [DeepLabCut/DeepLabCut#290]
**Your Operating system and DeepLabCut version**

Ubuntu 16.04 server, DeepLabCut 2.0.6.2 Python 3.6
 
**Describe the bug**

As the title described, if the video path contains whitespace or special character (e.g. [ ] )
In my case, the video name from the third party may contain the whitespace.

```
Traceback (most recent call last):                                                                                                                                                        
  File "/home/afun/.local/share/virtualenvs/buried-mouse-track-4ezhdAuL/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/labeling_toolbox.py", line 438, in browseDir     
    self.img = self.index[self.iter]                                                                                                                                                      
IndexError: index 0 is out of bounds for axis 0 with size 0                                                                                                                               
Segmentation fault (core dumped)
```
https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/generate_training_dataset/labeling_toolbox.py#L438

However, it's a minor bug and it could be easily avoided if and only if the user changed the path name.

**Comment by MMathisLab** [comment]
for robustness you really should not have characters or spaces in directories for file names or images - I wouldn’t consider this a bug, and this notation is very standard. https://superuser.com/questions/29111/what-technical-reasons-exist-for-not-using-space-characters-in-file-names

**Comment by Mahathy95** [comment]
Hi, I have the same error and was wondering which file you are referring to? (that cannot have spaces and or characters) - My video is named demo1... do you think including the number caused this error?
Error: 
←[1;31mIndexError←[0m: index 5 is out of bounds for axis 0 with size 5

**Comment by mizasquare** [comment]
I also experienced similar thing today. 
there is still possibility that even though the initial video path has no spacial character, 
1. due to that DLC-gui allows space/special character in the scorer name field, 
2. which affect the project folder 
3. and DLC-gui also offers option copying video files into it, 
4. boom. problem occurs.
