### ISSUE TITLE
Available to discard the label

### ISSUE THREAD

**Issue by afunTW** [DeepLabCut/DeepLabCut#291]
**Your Operating system and DeepLabCut version**
Ubuntu 16.04 server, DeepLabCut 2.0.6.2 Python 3.6

**Is your feature request related to a problem? Please describe.**
In the step of `label_frames` with occlusion scenario, we might not label the whole data.
When we click and mark the label which belongs to the occlusion part, it cannot remove now.

![image](https://user-images.githubusercontent.com/4820492/57691777-aac90f80-7677-11e9-9c09-f22076cc0ed3.png)

**Describe the solution you'd like**
More key binding or shortcut.

**Comment by meet10may** [comment]
You can use the mouse middle button to remove the label.

**Comment by afunTW** [comment]
@meet10may Thanks for the notification.
