### ISSUE TITLE
skeleton formation using labeleled parts

### ISSUE THREAD

**Issue by vijaysamula** [DeepLabCut/DeepLabCut#292]
Hi 
I am using Deeplabcut to detect the Cow behavior. I need a help that, I have to join the labeled parts (forming a skeleton). Can anyone help me in this?

**Comment by meet10may** [comment]
We are currently working on this feature and will be released in the next version. 
However, as an interim solution, you can define the pair of body parts you want to join in a list and use matplotlib to plot lines between the pairs. Hope it helps!

**Comment by MMathisLab** [comment]
We will update the package in the future, so stay tuned.

**Comment by vijaysamula** [comment]
or else can you help me in finding code. so i can try changing it.
