### ISSUE TITLE
no hdf or csv after analyze_videos

### ISSUE THREAD

**Issue by haofanglee** [DeepLabCut/DeepLabCut#294]
Hi! I successfully trained the network and it looked good to go. So I ran the analyze_video section. The program didn't give me any error message, but when I look into the directory of my video, there's no HDF or csv files created. Why is that? Can anyone help please? I'm using Windows 10, anaconda with python 3.6.6 with the environment setup file provided by Deeplabcut.

 deeplabcut.analyze_videos(config_path,r'D:\Haofang\deeplabcut_openfield\openfield_tracking-haofang-2019-05-16\
    ...: videos\behavior_video2019-04-10T15_44_39.avi', save_as_csv=True)

c:\users\yinlab\anaconda3\envs\dlc-windowsgpu\lib\site-packages\deeplabcut\pose_estimation_tensorflow\config.py:43: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_cfg = edict(yaml.load(f))
Config:
{'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10]],
 'all_joints_names': ['spine0',
                      'spine1',
                      'spine2',
                      'tail0',
                      'tail1',
                      'tail2',
                      'tail3',
                      'FL',
                      'BL',
                      'FR',
                      'BR'],
 'batch_size': 1,
 'bottomheight': 400,
 'crop': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_openfield_trackingMay16\\openfield_tracking_haofang95shuffle1.mat',
 'dataset_type': 'default',
 'display_iters': 100,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'c:\\users\\yinlab\\anaconda3\\envs\\dlc-windowsgpu\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_openfield_trackingMay16\\Documentation_data-openfield_tracking_95shuffle1.pickle',
 'min_input_size': 64,
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.005, 1000], [0.02, 43000], [0.002, 73000], [0.001, 103000]],
 'net_type': 'resnet_50',
 'num_joints': 11,
 'optimizer': 'sgd',
 'pos_dist_thresh': 17,
 'project_path': 'D:\\Haofang\\deeplabcut_openfield\\openfield_tracking-haofang-2019-05-16',
 'regularize': False,
 'rightwidth': 400,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'D:\\Haofang\\deeplabcut_openfield\\openfield_tracking-haofang-2019-05-16\\dlc-models\\iteration-0\\openfield_trackingMay16-trainset95shuffle1\\test\\snapshot',
 'stride': 8.0,
 'topheight': 400,
 'use_gt_segm': False,
 'video': False,
 'video_batch': False,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Using snapshot-103000 for model D:\Haofang\deeplabcut_openfield\openfield_tracking-haofang-2019-05-16\dlc-models\iteration-0\openfield_trackingMay16-trainset95shuffle1
INFO:tensorflow:Restoring parameters from D:\Haofang\deeplabcut_openfield\openfield_tracking-haofang-2019-05-16\dlc-models\iteration-0\openfield_trackingMay16-trainset95shuffle1\train\snapshot-103000
Restoring parameters from D:\Haofang\deeplabcut_openfield\openfield_tracking-haofang-2019-05-16\dlc-models\iteration-0\openfield_trackingMay16-trainset95shuffle1\train\snapshot-103000
The videos are analyzed. Now your research can truly start!
 You can create labeled videos with 'create_labeled_video'.
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract any outlier frames!

**Comment by MMathisLab** [comment]
You need to put the video in brackets. Please see more info by typing: ‘deeplabcut.analyze_videos?’ For more help. Also I suggest upgrading your package. Also, please in the future use the template provided - I don’t know which version, etc so it’s difficult to help...

**Comment by haofanglee** [comment]
Your Operating system and DeepLabCut version

Windows10, DeepLabCut 2.0.6  Python 3.6.6 

Describe the bug
My apology for not paying attention to the template. I have tried putting the video in brackets, but in the case when there's only one video in the brackets, I always get this error. And this error doesn't occur when i don't put the path in brackets.

Here is the error message:
In [6]: deeplabcut.analyze_videos(config_path,[r'D:\Haofang\Haofang_Calcium_videos\VGLUT2_651-1\04112019-1\behavior_vid
   ...: eo2019-04-10T15_44_39.avi'], save_as_csv=True, destfolder=[r'D:\Haofang\Haofang_Calcium_videos\VGLUT2_651-1\041
   ...: 12019-1'])

Config:
{'all_joints': [[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10]],
 'all_joints_names': ['spine0',
                      'spine1',
                      'spine2',
                      'tail0',
                      'tail1',
                      'tail2',
                      'tail3',
                      'FL',
                      'BL',
                      'FR',
                      'BR'],
 'batch_size': 10,
 'bottomheight': 400,
 'crop': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_openfield_trackingMay17\\openfield_tracking_haofang95shuffle1.mat',
 'dataset_type': 'default',
 'display_iters': 100,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'c:\\users\\yinlab\\anaconda3\\envs\\dlc-windowsgpu\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_openfield_trackingMay17\\Documentation_data-openfield_tracking_95shuffle1.pickle',
 'min_input_size': 64,
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 43000],
                [0.002, 100000],
                [0.001, 150000]],
 'net_type': 'resnet_50',
 'num_joints': 11,
 'optimizer': 'sgd',
 'pos_dist_thresh': 15,
 'project_path': 'C:\\Users\\yinlab\\Documents\\deeplabcut_data\\openfield_tracking-haofang-2019-05-17',
 'regularize': False,
 'rightwidth': 400,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'C:\\Users\\yinlab\\Documents\\deeplabcut_data\\openfield_tracking-haofang-2019-05-17\\dlc-models\\iteration-0\\openfield_trackingMay17-trainset95shuffle1\\test\\snapshot',
 'stride': 8.0,
 'topheight': 400,
 'use_gt_segm': False,
 'video': False,
 'video_batch': False,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Using snapshot-150000 for model C:\Users\yinlab\Documents\deeplabcut_data\openfield_tracking-haofang-2019-05-17\dlc-models\iteration-0\openfield_trackingMay17-trainset95shuffle1
INFO:tensorflow:Restoring parameters from C:\Users\yinlab\Documents\deeplabcut_data\openfield_tracking-haofang-2019-05-17\dlc-models\iteration-0\openfield_trackingMay17-trainset95shuffle1\train\snapshot-150000
Restoring parameters from C:\Users\yinlab\Documents\deeplabcut_data\openfield_tracking-haofang-2019-05-17\dlc-models\iteration-0\openfield_trackingMay17-trainset95shuffle1\train\snapshot-150000
Starting to analyze %  D:\Haofang\Haofang_Calcium_videos\VGLUT2_651-1\04112019-1\behavior_video2019-04-10T15_44_39.avi
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-b420edc9c101> in <module>()
----> 1 deeplabcut.analyze_videos(config_path,[r'D:\Haofang\Haofang_Calcium_videos\VGLUT2_651-1\04112019-1\behavior_video2019-04-10T15_44_39.avi'], save_as_csv=True, destfolder=[r'D:\Haofang\Haofang_Calcium_videos\VGLUT2_651-1\04112019-1'])

c:\users\yinlab\anaconda3\envs\dlc-windowsgpu\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py in analyze_videos(config, videos, videotype, shuffle, trainingsetindex, gputouse, save_as_csv, destfolder)
    157         #looping over videos
    158         for video in Videos:
--> 159             AnalyzeVideo(video,DLCscorer,trainFraction,cfg,dlc_cfg,sess,inputs, outputs,pdindex,save_as_csv, destfolder)
    160
    161     os.chdir(str(start_path))

c:\users\yinlab\anaconda3\envs\dlc-windowsgpu\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py in AnalyzeVideo(video, DLCscorer, trainFraction, cfg, dlc_cfg, sess, inputs, outputs, pdindex, save_as_csv, destfolder)
    264     if destfolder is None:
    265         destfolder = str(Path(video).parents[0])
--> 266     dataname = os.path.join(destfolder,vname + DLCscorer + '.h5')
    267     try:
    268         # Attempt to load data...

c:\users\yinlab\anaconda3\envs\dlc-windowsgpu\lib\ntpath.py in join(path, *paths)
     74 # Join two (or more) paths.
     75 def join(path, *paths):
---> 76     path = os.fspath(path)
     77     if isinstance(path, bytes):
     78         sep = b'\\'

TypeError: expected str, bytes or os.PathLike object, not list

**Comment by MMathisLab** [comment]
^ its an issue with the destination folder.. since it’s the same as the folder with the video, that is the default behavior anyhow, so you can drop “destfolder” (and keep Video path in brackets ;).

**Comment by haofanglee** [comment]
Thank you for the quick reply! I have tried dropping the destfolder, same output (no error or warning) but no CSV or HDF were created. What could be causing this problem? anything else I can try to solve this? Thanks!

**Comment by MMathisLab** [comment]
Can you try updating ffmpeg?  https://www.wikihow.com/Install-FFmpeg-on-Windows (I haven’t tried that exactly, but looks well documented)


And just to confirm, you are using the supplied Anaconda env for Windows?

**Comment by MMathisLab** [comment]
Also, it shouldn’t be necessary, but can you also add videotype=‘.avi’

**Comment by haofanglee** [comment]
Hi! Yes I am using the supplied anaconda environment for windwos. 

I installed ffmpeg as directed and tried adding videotype='.avi' as another input argument, but no avail. In the userGuide I read that analyzed_video should take several minutes to finish, however mine was done almost instantaneously. Does that indicate the analyzing actually wasn't executed but somehow was not caught by errors? In your mind what could cause problems like this? Thank you so much for the help!

Here's the output: no error message or warning, but no files generated in the video subfolder~
 deeplabcut.analyze_videos(config_path,['D:\\Haofang\\Haofang_Calcium_videos\\VGLUT2_651-1\\04112019-1\behavior_
   ...: video2019-04-10T15_44_39.avi'], save_as_csv=True, videotype='.avi')
Using snapshot-150000 for model C:\Users\yinlab\Documents\deeplabcut_data\openfield_tracking-haofang-2019-05-17\dlc-models\iteration-0\openfield_trackingMay17-trainset95shuffle1
INFO:tensorflow:Restoring parameters from C:\Users\yinlab\Documents\deeplabcut_data\openfield_tracking-haofang-2019-05-17\dlc-models\iteration-0\openfield_trackingMay17-trainset95shuffle1\train\snapshot-150000
INFO:tensorflow:Restoring parameters from C:\Users\yinlab\Documents\deeplabcut_data\openfield_tracking-haofang-2019-05-17\dlc-models\iteration-0\openfield_trackingMay17-trainset95shuffle1\train\snapshot-150000
The videos are analyzed. Now your research can truly start!
 You can create labeled videos with 'create_labeled_video'.
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract any outlier frames!

**Comment by MMathisLab** [comment]
It just means it finds no new videos to analyze. Try another video?

**Comment by haofanglee** [comment]
it works for a new video! I moved this video to a new path and it worked! Thank you!
