### ISSUE TITLE
Play videos in Label Frames tool

### ISSUE THREAD

**Issue by Clyde92** [DeepLabCut/DeepLabCut#295]
Firstly, 

I just want to say thank you, sincerely, DeepLabCut is an awesome tool! 
I have a feature request that I know I personally would find useful, and hopefully others might too.

**Your Operating system and DeepLabCut version**

OS: Ubuntu 16.04 LTS
env: Anaconda
DLC version: 2.0.6.3

**Is your feature request related to a problem? Please describe.**
It's not really a problem that's specific to DLC, but in single frames it can be hard to manually identify features to label with no motion context.

**Describe the solution you'd like**
I would like the ability to play the last 20-50 frames leading up to the one I'm currently labeling in order to increase my contextual understanding of the points I'm labeling. By seeing how something moves I'm more accurately able to identify and label points. 

**Describe alternatives you've considered**
Sometimes I try and play the video along side the labeling software.

**Comment by MMathisLab** [comment]
glad you like it :) 

I once had this feeling too, but the "truth" is you should have individual frames that are easy to label, as that is what the network gets. So, while it's easier for our visual system if you have low quality videos to label to use the time information, the "best practice" is to record videos with more resolution  or higher frame rate (if blur is an issue for you). If you can't do that, then I suggest opening the video in Fiji as the frame # at the top will be the same frame # in the GUI for labeling...
