### ISSUE TITLE
Deeplabcut training doesn't speed up on Cloud TPU. Why could this be?

### ISSUE THREAD

**Issue by Umar-Ayub** [DeepLabCut/DeepLabCut#297]
**Your Operating system and DeepLabCut version**
Google Colab Unix based OS
https://colab.research.google.com/github/AlexEMG/DeepLabCut/blob/master/examples/Colab_TrainNetwork_VideoAnalysis.ipynb#scrollTo=RiDwIVf5-3H_

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

**If applicable, please also complete the following information:**
chrome
latest
 
**Describe the bug**
Hi I wanted to train a model on Cloud TPU to take advantage of it's speed up effects for training. However, when I ran it on the TPU runtime inside the colab notebook there wasn't a speedup on TPU and in fact it was performing much slower than a GPU. Would you have any insight on why this is? Theoretically, cloud TPU should perform way faster than cloud GPU (this is the case for example models shared by google cloud). Could there be something on the backend that needs to be implemented in deeplabcut for TPU. Thanks

**To Reproduce**
 I just followed the intructions for both GPU and TPU on the colab notebook released by the authors:
https://colab.research.google.com/github/AlexEMG/DeepLabCut/blob/master/examples/Colab_TrainNetwork_VideoAnalysis.ipynb#scrollTo=RiDwIVf5-3H_

**Expected behavior**
TPU training should be faster. It's much slower for first 1000 iterations about 20 min on TPU and about 10 min on GPU.

Any insight on faster training (hours to minutes) would be appreciated. Thanks

**Comment by MMathisLab** [comment]
Hey, since not a code issue, would be better to post discussion points on Image Forum....

But, I note this in the demo Notebook itself that we too observe this behavior. It’s not a priority for us to look into this at this time. The GPU is quite fast though, ;). Enjoy DeepLabCutting...
