### ISSUE TITLE
No module named 'moviepy' (Windows installation) 

### ISSUE THREAD

**Issue by bill-connelly** [DeepLabCut/DeepLabCut#30]
I have probably done something stupid, but I believe I followed the installation instructions, and I got a "No module named moviepy error'

I've included everything that happened in the Anaconda Prompt (including my various stupid mistakes)

[dlc_fail.txt](https://github.com/AlexEMG/DeepLabCut/files/2243695/dlc_fail.txt)

I've since "pip install moviepy" which seems to have fixed things, but I thought you might be interested to know anyway.

**Comment by AlexEMG** [comment]
Dear Bill,

You seem to have created two conda environments: one called "tensorflow" and one called "DLCdependencies" (as provided by our yaml file). Note that you cannot be in multiple environments simultaneously.

Thus, when you ```conda activate tensorflow```, you are leaving the DLCdependencies environment. Thus, moviepy, easydict etc. (which are installed in this environment), but not canonically in your tensorflow environments are missing. 

Thus, if you want *TensorFlow* and everything else in one environment then consider using:

https://github.com/AlexEMG/DeepLabCut/blob/master/dlcDependenciesFORWINDOWSwTF.yaml

Alternatively, you could have installed *TensorFlow* in the *DLCdependencies* environment. 

Happy pose-estimating! 
Alexander

**Comment by MMathisLab** [comment]
(you also updated tensorflow to a version not supported, i.e. 1.9, so that would also likely not work)

**Comment by AlexEMG** [comment]
I think it might work. E.g. 1.8 works...

**Comment by GPU-Shuttle** [comment]
While in the environment, 
'pip install easydict'
worked just fine for me!
