### ISSUE TITLE
Implementation of fast create_labeled_video with cropping

### ISSUE THREAD

**Issue by AmandineCornil** [DeepLabCut/DeepLabCut#301]
**Your Operating system and DeepLabCut version**
Ubuntu LTS 18.04
Deeplabcut 2.06

** Implementation
Dear Deeplabcut Team,
It would be super cool if you can add the possibility to generate the labeled video with cropping and the parameter save_as_frame = False. 
Thanks a lot !
Best

**Comment by AmandineCornil** [comment]
Dear Deeplabcut Team,
Instead of cropping the video and put the label on it, I took the problem in an other way : keeping the raw images and modify the x-y coordinates of labels. I know it's not really the proper way to do but it's sufficient to have a faster idea of the results ;-)
Even if it's not a huge modification in the code, I can share if you want
Have a nice evening !

**Comment by MMathisLab** [comment]
feel free to make a pull request, and we are happy to take a look.

**Comment by MMathisLab** [comment]
https://github.com/AlexEMG/DeepLabCut/pull/309

**Comment by AlexEMG** [comment]
@AmandineCornil,  thanks for the https://github.com/AlexEMG/DeepLabCut/pull/309. I added the possibility to also plot it on the cropped video, i.e.:

Now the user can crop during analysis and then:
- by default ```deeplabcut.create_labeled_video``` will plot the detected bodyparts in the full-sized frame at the correct location (by shifting them)
- plot them on the cropped video itself. This can be done with:
```deeplabcut.create_labeled_video(path_config_file,[video],displaycropped=True)```
