### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by nickkaliss** [DeepLabCut/DeepLabCut#302]
First off, let me say please bear with me because I am fairly new to using Python, or programming languages in general. 
I am using Windows 10 with an Anaconda Environment and DeepLabCut 2.0. I am using the CPU conda environment because the GPU on the computer I am using is an AMD GPU and not a Nvidia GPU.

The following error occurs when I attempt to import deeplabcut in ipython:
In [3]: import deeplabcut
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
c:\users\nick.kaliss\appdata\local\continuum\anaconda3\envs\dlc-windowscpu\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     57
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

c:\users\nick.kaliss\appdata\local\continuum\anaconda3\envs\dlc-windowscpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>()
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

c:\users\nick.kaliss\appdata\local\continuum\anaconda3\envs\dlc-windowscpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

c:\users\nick.kaliss\appdata\local\continuum\anaconda3\envs\dlc-windowscpu\lib\imp.py in load_module(name, file, filename, details)
    242         else:
--> 243             return load_dynamic(name, filename, file)
    244     elif type_ == PKG_DIRECTORY:

c:\users\nick.kaliss\appdata\local\continuum\anaconda3\envs\dlc-windowscpu\lib\imp.py in load_dynamic(name, path, file)
    342             name=name, loader=loader, origin=path)
--> 343         return _load(spec)
    344

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-3-52d2df9c7fa5> in <module>()
----> 1 import deeplabcut

c:\users\nick.kaliss\appdata\local\continuum\anaconda3\envs\dlc-windowscpu\lib\site-packages\deeplabcut\__init__.py in <module>()
     31 else:
     32     mpl.use('TkAgg')
---> 33     from deeplabcut import generate_training_dataset
     34     from deeplabcut import refine_training_dataset
     35

c:\users\nick.kaliss\appdata\local\continuum\anaconda3\envs\dlc-windowscpu\lib\site-packages\deeplabcut\generate_training_dataset\__init__.py in <module>()
     14 else:
     15     from deeplabcut.generate_training_dataset.auxfun_drag_label import *
---> 16     from deeplabcut.generate_training_dataset.labeling_toolbox import *
     17     from deeplabcut.generate_training_dataset.frame_extraction_toolbox import *
     18

c:\users\nick.kaliss\appdata\local\continuum\anaconda3\envs\dlc-windowscpu\lib\site-packages\deeplabcut\generate_training_dataset\labeling_toolbox.py in <module>()
     24 import argparse
     25 from deeplabcut.generate_training_dataset import auxfun_drag_label
---> 26 from deeplabcut.utils import auxiliaryfunctions
     27 from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg as FigureCanvas
     28 from matplotlib.backends.backend_wxagg import NavigationToolbar2WxAgg as NavigationToolbar

c:\users\nick.kaliss\appdata\local\continuum\anaconda3\envs\dlc-windowscpu\lib\site-packages\deeplabcut\utils\__init__.py in <module>()
----> 1 from deeplabcut.utils.make_labeled_video import *
      2 from deeplabcut.utils.auxiliaryfunctions import *
      3 from deeplabcut.utils.video_processor import *
      4 from deeplabcut.utils.plotting import *
      5

c:\users\nick.kaliss\appdata\local\continuum\anaconda3\envs\dlc-windowscpu\lib\site-packages\deeplabcut\utils\make_labeled_video.py in <module>()
     36
     37 from deeplabcut.utils import auxiliaryfunctions
---> 38 from deeplabcut.pose_estimation_tensorflow.config import load_config
     39 from skimage.util import img_as_ubyte
     40 from skimage.draw import circle_perimeter, circle

c:\users\nick.kaliss\appdata\local\continuum\anaconda3\envs\dlc-windowscpu\lib\site-packages\deeplabcut\pose_estimation_tensorflow\__init__.py in <module>()
     15 from deeplabcut.pose_estimation_tensorflow.dataset import *
     16 from deeplabcut.pose_estimation_tensorflow.models import *
---> 17 from deeplabcut.pose_estimation_tensorflow.nnet import *
     18 from deeplabcut.pose_estimation_tensorflow.util import *
     19

c:\users\nick.kaliss\appdata\local\continuum\anaconda3\envs\dlc-windowscpu\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\__init__.py in <module>()
     12 pose_estimation_tensorflow is based of Eldar's repository.
     13 """
---> 14 from deeplabcut.pose_estimation_tensorflow.nnet.losses import *
     15 from deeplabcut.pose_estimation_tensorflow.nnet.net_factory import *
     16 from deeplabcut.pose_estimation_tensorflow.nnet.pose_net import *

c:\users\nick.kaliss\appdata\local\continuum\anaconda3\envs\dlc-windowscpu\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\losses.py in <module>()
      3 https://github.com/eldar/pose-tensorflow
      4 '''
----> 5 import tensorflow as tf
      6
      7 from tensorflow.python.ops import math_ops

c:\users\nick.kaliss\appdata\local\continuum\anaconda3\envs\dlc-windowscpu\lib\site-packages\tensorflow\__init__.py in <module>()
     22
     23 # pylint: disable=g-bad-import-order
---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     25
     26 try:

c:\users\nick.kaliss\appdata\local\continuum\anaconda3\envs\dlc-windowscpu\lib\site-packages\tensorflow\python\__init__.py in <module>()
     47 import numpy as np
     48
---> 49 from tensorflow.python import pywrap_tensorflow
     50
     51 from tensorflow.python.tools import component_api_helper

c:\users\nick.kaliss\appdata\local\continuum\anaconda3\envs\dlc-windowscpu\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "c:\users\nick.kaliss\appdata\local\continuum\anaconda3\envs\dlc-windowscpu\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\nick.kaliss\appdata\local\continuum\anaconda3\envs\dlc-windowscpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\nick.kaliss\appdata\local\continuum\anaconda3\envs\dlc-windowscpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\nick.kaliss\appdata\local\continuum\anaconda3\envs\dlc-windowscpu\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\nick.kaliss\appdata\local\continuum\anaconda3\envs\dlc-windowscpu\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

------------------------------------------------------

For context, I downloaded deeplabcut and created the conda environment using the instructions here: https://github.com/AlexEMG/DeepLabCut/blob/master/conda-environments/README.md . 
I then used pip install to install deeplabcut and tensorflow, then I switched over to ipython to import deeplabcut but keep getting the above error. 

Thank you in advance for the help!

**Comment by MMathisLab** [comment]
If you used the environment for Windows CPU, deeplabcut and tensorflow are installed already. Given your error, "ImportError: DLL load failed: The specified module could not be found." Is is unlikely you used our supplied file. Please download this: http://www.mousemotorlab.org/s/dlc-windowsCPU.yaml  

Then you just need to type:
```
conda env create -f dlc-windowsCPU.yaml
activate dlc-windowsCPU
```

**Comment by MMathisLab** [comment]
more information here: https://forum.image.sc/t/tensorflow-dlc-2-0-importerror-dll-load-failed-the-specified-module-could-not-be-found/22991

**Comment by nickkaliss** [comment]
Thank you for the help. When I download the file and then type in the "conda env create -f dlc-widnwosCPU.yaml" it gives me the error:
EnvironmentFileNotFound: 'C:\Users\nick.kaliss\dlc-windowsCPU.yaml' file not found

any thoughts on this?

**Comment by MMathisLab** [comment]
you will need to have the file in the folder you are working in, namely, let's say you download the file and place it on your desktop...

In terminal go to:
```
cd C:\Users\nick.kaliss\Desktop\
```

then type: 
```
conda env create -f dlc-windowsCPU.yaml
activate dlc-windowsCPU
```

**Comment by nickkaliss** [comment]
I am definitely in the dlc-windowsCPU environment, and the same error occurs. I tried the solutions in the page you linked and unfortunately, none of them worked either. Any other thoughts?

**Comment by MMathisLab** [comment]
Can you share a screenshot?

**Comment by nickkaliss** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/51176519/58596655-bf85d580-8229-11e9-938d-f6347ef6f8e2.png)
![Screenshot (3)](https://user-images.githubusercontent.com/51176519/58596658-c1e82f80-8229-11e9-9968-13d4a9a9074d.png)
![Screenshot (4)](https://user-images.githubusercontent.com/51176519/58596660-c3b1f300-8229-11e9-8f87-af23f7da48d3.png)

**Comment by MMathisLab** [comment]
Can you show how you activated the env? Thanks!

**Comment by MMathisLab** [comment]
Seems you aren't using the env we supply though, as the top says it was made with python=3.6.8 and -msvc_runtime, so namely not the downloaded one I provide?

**Comment by nickkaliss** [comment]
Hi, I apologize for the lat response, but I tried deleting my previous environment and uninstalling deeplabcut, then following the steps at this link exactly: https://github.com/AlexEMG/DeepLabCut/blob/master/conda-environments/README.md . Basically I

1. (Already having had Anaconda installed) used the git clone command
2. cd'd into deeplabcut and then conda-environments 
3. created and then activated the dlc-windowsCPU environment
4. installed deeplabcut and entered ipython
5. Tried to import deeplabcut, but got the same "The specified module could not be found" error message. 

Sorry to bother again, but any other ideas for things to try?

**Comment by nickkaliss** [comment]
I was able to fix this problem by installing a newer version of tensorflow (1.5). Thanks for the help!

**Comment by Simian1** [comment]
Hi nickkaliss

> I was able to fix this problem by installing a newer version of tensorflow (1.5). Thanks for the help!

Could you give me a bit more details on what you did? I think I have the same problem, but my version of tensorflow is up to date. Do you mean to say you reverted to v1.5?

**Comment by nickkaliss** [comment]
> Hi nickkaliss
> 
> > I was able to fix this problem by installing a newer version of tensorflow (1.5). Thanks for the help!
> 
> Could you give me a bit more details on what you did? I think I have the same problem, but my version of tensorflow is up to date. Do you mean to say you reverted to v1.5?

Yes, reverting to v1.5 worked at the time, although I'm running DLC on a computer with a GPU now, and tensorflow-gpu 1.10.0 has been working fine. But when I was running it on only a CPU on my older computer, I used
`pip install tensorflow==1.5`
and I believe that worked for me to solve this problem.
