### ISSUE TITLE
Terminal stuck at "Starting training..."

### ISSUE THREAD

**Issue by nickkaliss** [DeepLabCut/DeepLabCut#303]
I am using Windows 10 and DeepLabCut 2.0

I was able to import deeplabcut and everything else necessary to train the demo data, but the terminal gets stuck on the message "Starting training...". There are no pop-ups or anything.

Steps I took that led to the behavior:
1. `Import deeplabcut` 
2. `Import os`
3. `from pathlib import Path`
4.  `path_config_file = os.path.join(os.getcwd(),'openfield-Pranav-2018-10-30/config.yaml')`
5. `deeplabcut.load_demo_data(path_config_file)`
6. `deeplabcut.train_network(path_config_file)`

![Screenshot (5)](https://user-images.githubusercontent.com/51176519/58668454-d4c43800-82ed-11e9-9320-bf8e024ea5de.png)
![Screenshot (6)](https://user-images.githubusercontent.com/51176519/58668457-d7269200-82ed-11e9-81f3-b03593e5a5fe.png)

**Comment by MMathisLab** [comment]
what did you set the `display iterations` to? If on a CPU and only at defaults, it would take an hour or so to see this running this... (i.e. at default 1000)

OR

please check if the weights are downloaded...

**From the wiki Troubleshooting:**
https://github.com/AlexEMG/DeepLabCut/wiki/Troubleshooting-Tips

Weights not downloaded. If you get permission errors FileNotFound (or ValueError: The passed save_path is not a valid checkpoint: xxx\Deeplabcut\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt) when you run training, first check if the RestNet weights downloaded.

This is an error more common in Windows, but some docker containers might not have privileges for this (it can be user specific). They should be under 'init_weights' (see path in the pose_cfg.yaml file). For Windows, also please install GITBASH https://gitforwindows.org/ and OPEN cmd by right-clicking "run as ADIM"

You can "cd" in the terminal to the package location!

i.e. in linux copy and paste this in: cd usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/

in Windows: cd C:\Users\YourComputerName\Anaconda3\envs\DLC\Lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained

And if you type "ls" to see the list of files, you should see the resnet: resnet_v1_50.ckpt

If it is not there, run sudo download.sh then change the permissions: sudo chown yourusername:yourusername resnet_v1_50.ckpt

**Comment by nickkaliss** [comment]
The cd command results in the message "The system cannot find the path specified."  Additionally, I apologize for my ignorance but how do I check/set display iterations?

**Comment by MMathisLab** [comment]
Please see the docs on how to set these:

https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#g-train-the-network

in your case, you need to cd to the path that is shown in your last screenshot, after "INFO Tensorflow: restoring parameters from XXX
