### ISSUE TITLE
How to generate the labeled video like the first gif in README.md?

### ISSUE THREAD

**Issue by AdriandLiu** [DeepLabCut/DeepLabCut#304]
Hi, 

I really enjoy using DeepLabCut in my research, thank you very much for the contribution. 

I was wondering how could I generate the labeled video like the one shows below? Which .py file should I refer to? Thank you so much in advance. 

![687474703a2f2f7777772e70656f706c652e6661732e686172766172642e6564752f7e616d61746869732f646c632f4d41544849535f323031385f6f646f72747261696c2e676966](https://user-images.githubusercontent.com/38824707/58726045-91bd9f80-8395-11e9-9280-2959ec1058b6.gif)

**Comment by MMathisLab** [comment]
all the tools to do so will be in the new release actually (2.0.7), so within the next week ;) I'll post here when it's released (or click "watch" above to get notifications).
