### ISSUE TITLE
Supported video file formats

### ISSUE THREAD

**Issue by JohnCraigPublic** [DeepLabCut/DeepLabCut#306]
Can you list the supported video file formats?   For example, .mov files?

**Comment by AlexEMG** [comment]
The code uses throughout: https://opencv.org/ So anything that can be read by this is fine. Some functions also support https://zulko.github.io/moviepy/ (which supports some other video types).

**Comment by JohnCraigPublic** [comment]
Thanks. I've pre-converted all my videos to .mp4 to avoid any issues.
