### ISSUE TITLE
create_training_dataset -- curl not found

### ISSUE THREAD

**Issue by JohnCraigPublic** [DeepLabCut/DeepLabCut#307]
Linux 16.04 LTS 
DeepLabCut 2.0  (installed yesterday)
Anaconda Env named DLC

The create_training_dataset call tries to download the resnet pretrained model and appears to fail, saying "curl not found"

terminal transcript:

deeplabcut.create_training_dataset(config_path,num_shuffles=1)
Downloading the pretrained model (ResNets)....
/home/john/anaconda3/envs/DLC/bin/download.sh: 3: /home/john/anaconda3/envs/DLC/bin/download.sh: curl: not found

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by JohnCraigPublic** [comment]
installed curl, and now weights are downloading.
Is it left out of your (otherwise excellent) instructions, that one has to install curl manually?

**Comment by MMathisLab** [comment]
That’s possible :). I’ll add to the troubleshooting guide under downloading weights.
