### ISSUE TITLE
Tensorboard cannot be displayed

### ISSUE THREAD

**Issue by leiyaohui** [DeepLabCut/DeepLabCut#308]
**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

**If applicable, please also complete the following information:**
 
**Describe the bug**
A clear and concise description of what the bug is!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by leiyaohui** [comment]
Hello, how can the log files generated during my training not be displayed in tensorboard? I look forward to your reply. Thank you very much.

**Comment by MMathisLab** [comment]
the log files are found under dlc-models .. train...` log.txt.` The tensorboard is going to be specific to tensorflow and tensorboard you installed, and not the DLC package itself though...

**Comment by leiyaohui** [comment]
Thank you for your reply. I have installed tensorboard. During the training process, there is a log folder under the train folder, which generates events.out.tfevents.1559660002.DESKTOP-3TJ45ET. I want to know how this is displayed in tensorboard to see the training process and network structure.
