### ISSUE TITLE
No module named 'easydict'

### ISSUE THREAD

**Issue by bill-connelly** [DeepLabCut/DeepLabCut#31]
I'm working through the demo guide

https://github.com/AlexEMG/DeepLabCut/blob/master/docs/demo-guide.md

and in running python ../../../train.py

I get 

ModuleNotFoundError: No module named 'easydict'

See attached for full command history (takes off from where the last issue started)

[dlc_fail2.txt](https://github.com/AlexEMG/DeepLabCut/files/2243753/dlc_fail2.txt)

**Comment by AlexEMG** [comment]
Thanks for your interest in DeepLabCut and detailed txt log of your problem. This is related to #30 . Will answer there.
