### ISSUE TITLE
conv_3 bank?

### ISSUE THREAD

**Issue by jbohnslav** [DeepLabCut/DeepLabCut#310]
Hi there,

Thanks for the great work. I'm not used to TensorFlow, so it could be due to my inability to read tf code, but I'm confused about the prediction layers in the model. In both the DeeperCut paper and DeepLabCut paper, the authors describe using a ResNet base followed by 2x upsampling with deconvolution layers. Then, the authors "connect the final output to the output of the conv3 bank."

 In the code, features are extracted with the `net_funcs` imported from `tf.slim`: `resnet_v1.resnet_v1_50` and ` resnet_v1.resnet_v1_101`. Due to the use of atrous convolutions, and the lack of global average pooling (etc)., I think the features should be of shape `(N, H/16, W/16, 2048)`. 

They are then, I believe, passed to the following prediction layer:
```python
def prediction_layer(cfg, input, name, num_outputs):
    with slim.arg_scope([slim.conv2d, slim.conv2d_transpose], padding='SAME',
                        activation_fn=None, normalizer_fn=None,
                        weights_regularizer=slim.l2_regularizer(cfg.weight_decay)):
        with tf.variable_scope(name):
            pred = slim.conv2d_transpose(input, num_outputs,
                                         kernel_size=[3, 3], stride=2,
                                         scope='block4')
            return pred
```

This just means that the output of the ResNet is passed into a deconvolution layer, without any connection to `conv3`. Did I miss it somewhere? 

Both papers use the phrasing "connected to", so I'm not sure if it's supposed to be concatenate + conv2d, addition, and whether or not the connection happens to the upsampled features or original features. I expected to see (in pseudocode) the prediction layer be something like this:
```
upsampled_features = conv2d_transpose(features)
outputs = conv2d(concatenate(upsampled_features,conv3))
```

**Comment by MMathisLab** [comment]
Howdy Jim (from across the river!). So, here: https://github.com/AlexEMG/DeepLabCut/blob/887814e960ef70d193745c9716c1cf9a871abe33/deeplabcut/pose_estimation_tensorflow/nnet/pose_net.py#L66

 is the part where you will find the intermediate supervision. You can set if you want this supervision in the pose_config.yaml file. here is the default one for reference: https://github.com/AlexEMG/DeepLabCut/blob/887814e960ef70d193745c9716c1cf9a871abe33/deeplabcut/pose_estimation_tensorflow/default_config.py#L25
 Namely, you can set this to True (and it links to layer 12). However, this is only used when this ResNet-101, not 50. There is a supplementary figure in the [Nature Neuro](https://www.nature.com/articles/s41593-018-0209-y#Sec25) paper showing the improvements:

<p align="center">
<img src="https://static1.squarespace.com/static/57f6d51c9f74566f55ecf271/t/5c4d2045bba22374afafaef0/1548558416389/SupplFig2-01.png?format=1000w">
</p>

**Comment by jbohnslav** [comment]
Appreciate it! I thought that intermediate supervision was separate from the link to conv3.

**Comment by kkaganovsky** [comment]
I also thought intermediate supervision was separate from the link to conv3. In Insafutdinov et al. 2016 (DeeperCut), the paragraph discussing intermediate supervision mentions: "we add part loss layers inside the conv4 bank of ResNet." Is this implemented in DeepLabCut?

Cheers,
-Konstantin Kaganovsky
p.s. Thank you for the amazing tool and continued online support!

**Comment by lauritk** [comment]
>... In Insafutdinov et al. 2016 (DeeperCut), the paragraph discussing intermediate supervision mentions: "we add part loss layers inside the conv4 bank of ResNet." Is this implemented in DeepLabCut?

DeepLabCut uses part detector of eldar's DeeperCut Tensorflow implementation and the intermediate supervision is implemented, but it is not used in the DeepLabCut, when using default configs.

According to eldar (see https://github.com/eldar/pose-tensorflow/issues/1#issuecomment-288826074), the intermediate supervision implementation is designed for ResNet-101 and is not neccessary for ResNet-50.

This might be late, but answered anyways if somebody else also wonders.
