### ISSUE TITLE
Multiple indistinguishable animals

### ISSUE THREAD

**Issue by bouracha** [DeepLabCut/DeepLabCut#312]
Hi,

Great package!

I am trying parameterise the joints of mice in a cage. There are multiple (3) mice in my footage that are quite indistinguishable from each other. I don't mind only parameterising one of them, however the issue is that a body part, say, the 'left ear' of one mouse may flicker between one mouse to another. What is the best way to handle this such that I can stay consistently with the same subject?

Your preprint does suggest using an autoregressive model to extract, and add to the training set, frames where the position has changed by > epsilon pixels but it is not an issue of the accuracy of the network as they are indistinguishable to the human eye- the model does a great job- and thus at labelling stage it is also impossible to be sure that I am consistently labelling the same mouse. 

Thanks,
Anthony

**Comment by MMathisLab** [comment]
Hi. so, there are more elegant ways to handle this, but the new code is not yet released. As we have discussed in other issues (#50 #71, #228. #277 ) we will be releasing multi-animal tracking in the near future ;)

**Comment by AlexEMG** [comment]
Starting with https://github.com/DeepLabCut/DeepLabCut/tree/v2.2b5 there is (finally) very strong multi-animal support built in! Please let us know how it goes.

**Comment by bouracha** [comment]
Thank you for the update!

We have moved on from that project for the moment but hopefully we will be
able to avail of of the new model in the future.

Kind Regards,
Anthony
