### ISSUE TITLE
"UnboundLocalError: local variable 'cfg' referenced before assignment"

### ISSUE THREAD

**Issue by nickkaliss** [DeepLabCut/DeepLabCut#313]
I am using Windows 10 with the supplied dlc-windowsGPU Anaconda Env and Deeplabcut 2.0

I successfully imported dlc and created a new project, but when I attempt to extract frames to label, I get the error "UnboundLocalError: local variable 'cfg' referenced before assignment". I've checked the path to the config file and it seems to me that it should be correct. The only things I edited in the config file were the body parts to be labeled. 
Here's a screenshot: 
![screenshot 1](https://user-images.githubusercontent.com/51176519/59072655-406f4d80-8878-11e9-9293-dfa0f2ae1c30.png)

I saw this fix to this error: https://forum.image.sc/t/colab-deeplabcut-create-training-dataset/23855/7 but I'm not sure what is or could be wrong with my config file, and I'm also not sure how I would fix any issues with it. Any thoughts on what the issue with the config file, or anything else, might be? (I edited the config file in Notebook, if that is important)

Thank you in advance!

**Comment by MMathisLab** [comment]
the path to your config file is improperly formatted for Windows. 

Please see: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#a-create-a-new-project
```
NOTE: Windows users, you must input paths as: r`C:\Users\computername\Videos\reachingvideo1.avi' or

`C:\\Users\\computername\\Videos\\reachingvideo1.avi'

```

**Comment by nickkaliss** [comment]
Strangely enough, the same error occurs when I set the path like you suggested above and then extract frames. Any other thoughts?

**Comment by MMathisLab** [comment]
seems it cannot find the ``config.yaml`` fie, so I would just triple check everything! 
And, if you moved the project, you need to re-set the ``project_path`` in the ``config.yaml`` file.

**Comment by nickkaliss** [comment]
Never mind, I realized I had an unnecessary space in the config file. Sorry about that, and thanks!

**Comment by fliessen** [comment]
its really wired, I got the same error after added the _'num_outputs:3'_ as discription in _functionDetails.md_ while using _deeplabcut.analyze_videos_ . and delete this line, the program would run successfully and do not occur any error.
version of DLC is 2.1.1

**Comment by MMathisLab** [comment]
This error happens anytime something is broken in config.yaml - ie a typo or incorrect formatting.

**Comment by fliessen** [comment]
> This error happens anytime something is broken in config.yaml - ie a typo or incorrect formatting.

I change the extension  to .yml and use notepad++ to edit it, it got to work. BUT...... can not reproduce the result like Fig.4 in the paper with 200 literation train on 1 mice.

**Comment by MMathisLab** [comment]
.yml or .yaml is not the error, likely you had some other error inside your file. 

Note figure 4 is trained for 500K+ iterations, and I have no clue what your data is like, so I have no clue how to advise you...

**Comment by fliessen** [comment]
> .yml or .yaml is not the error, likely you had some other error inside your file.
> 
> Note figure 4 is trained for 500K+ iterations, and I have no clue what your data is like, so I have no clue how to advise you...

sorry, i miss K in my reply, i got 200k iterations in trainning operation. the data of mine is 2 1hr .mp4 videos for and really like the Fig.4 in paper,the one contains 1 mice is used for trainning and the one contain 3 to analyze and testing. but  the result i got with _num_outputs:3_ in has no difference from without this one.

**Comment by MMathisLab** [comment]
The network is not trained on videos, only on 95% of whatever individual frames you labeled. 

Do you mean the resulting .h5 file does not have three rows for outputs, or? Note, There is no function to create a video with 3 outputs currently.

**Comment by ghost** [comment]
I got the same error when I tried to run my runDeepLabCut.sh inside the cluster, but not in my personal laptop. I have checked the config.yaml as you said but the problem is still not solved. I don't really understand why.

**Comment by MMathisLab** [comment]
Clusters you need to export DLClight=True before calling python

**Comment by ghost** [comment]
I exported DLClight=True as you mentioned, but keep having problems: 

DLC loaded in light mode; you cannot use the relabeling GUI!
DLC loaded in light mode; you cannot use the labeling GUI!
Traceback (most recent call last):
  File "deeplabcut_cluster.py", line 28, in <module>
    deeplabcut.create_training_dataset(config_path)
  File "/opt/sci-soft/software/DeepLabCut/2.1.3-Anaconda3-CPU/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 566, in create_training_dataset
    cfg = auxiliaryfunctions.read_config(config)
  File "/opt/sci-soft/software/DeepLabCut/2.1.3-Anaconda3-CPU/lib/python3.6/site-packages/deeplabcut/utils/auxiliaryfunctions.py", line 125, in read_config
    return(cfg)
UnboundLocalError: local variable 'cfg' referenced before assignment

Do you know what else could be? Thank you for your time

**Comment by MMathisLab** [comment]
> UnboundLocalError: local variable 'cfg' referenced before assignment

this means you have an error in your config.yaml file. Double check your formatting.

**Comment by ShoufaChen** [comment]
I met this problem because I assign `cfg` values in the func. Problem like this one  https://stackoverflow.com/a/10852003/7701908
