### ISSUE TITLE
Can't create_labeled_video !

### ISSUE THREAD

**Issue by JohnCraigPublic** [DeepLabCut/DeepLabCut#314]
Ubuntu 16.04 LTS
DLC version 2.0.6.3
Anaconda Python3.6

First time using DLC and all has gone rather well!   Created Project, Labelled Frames, Trained, Evaluated, Analyzed Video, Ploted Trajectories, ....

But when I get to the much-anticipated-moment to "create_labeled_video" -- FAILURE!

oh, how frustrating... I am at the edge of my seat, wanting to see this video...  So, what could be wrong.  Here are the final few commands that work fine:

// works
deeplabcut.analyze_videos(config_path,['~/V/P/Epona-J-2019-06-02/AnalyzeVideos/3320.mp4'],shuffle=1)

// works
deeplabcut.filterpredictions(config_path, ['~/V/P/Epona-J-2019-06-02/AnalyzeVideos/3320.mp4'])

// works
deeplabcut.plot_trajectories(config_path,['~/V/P/Epona-J-2019-06-02/AnalyzeVideos/3320.mp4'], filtered=True)

But then....

// fails!
deeplabcut.create_labeled_video(config_path,['~/V/P/Epona-J-2019-06-02/AnalyzeVideos/3320.mp4'], filtered=True)

With the complaint....

FileNotFoundError: File ~/V/P/Epona-J-2019-06-02/AnalyzeVideos/3320DeepCut_resnet50_EponaJun2shuffle1_100000filtered.h5 does not exist

BUT THAT FILE *DOES* EXIST!

Any ideas?   You can create an .mp4 video?  or is it because you default to .avi?  or something else entirely.  Thanks for your help!

**Comment by MMathisLab** [comment]
Awe, add videotype=‘.mp4’

**Comment by JohnCraigPublic** [comment]
That didn't help.  Argh.  I will double check all things again....

**Comment by MMathisLab** [comment]
Double check ffmpeg is installed then! 

sudo apt-get update
sudo apt-get install ffmpeg


Also try adding “save_frames=True” as that relies on other backend code, and makes nicer videos anyhow (if your trajectories look good, then this extra time is worth it)

**Comment by JohnCraigPublic** [comment]
ffmpeg was not installed.  I think you need to add that to your otherwise fantastic instructions.

**Comment by JohnCraigPublic** [comment]
installed ffmpeg, re-checked everything -- but get the same error!  It complains that the *.h5 file doesn't exist, but it does.   Is there some other package I need?

**Comment by MMathisLab** [comment]
Strange! ( typically ffmpeg is installed with DLC on Ubuntu systems without issue - this happens during install ;) also check out the Docker container for more information for Ubuntu users) 

Back to the issue:
Would you mind sending a screenshot/log of the steps from analyze_video to create_labeled_video? If you don’t want to post publicly you can email me: mackenzie@post.harvard.edu 

Also can you confirm the plot_trajectories made 4 plots in “plot-poses”?

**Comment by JohnCraigPublic** [comment]
I sent you the info via email.  Thanks!

**Comment by JohnCraigPublic** [comment]
Got rid of the use of "~" in all my paths - now it works!!   Thanks Mackenzie.
