### ISSUE TITLE
Manual extraction frame slider width too narrow

### ISSUE THREAD

**Issue by alchemyconsulting** [DeepLabCut/DeepLabCut#315]
**Your Operating system and DeepLabCut version**

Any OS, DeepLabCut 2.0.6.3

**Is your feature request related to a problem? Please describe.**
When doing manual frame extraction from a video with a lot of frames (eg. 10k+), the narrow slider makes it very difficult to move within the video, as any small movement changes by a lot of frames.  Trying to find quick actions within a video is nearly impossible.

**Describe the solution you'd like**
A config parameter to change the width of the slider if required.

**Describe alternatives you've considered**
A microsopic mouse.

**Comment by MMathisLab** [comment]
solution PR and merged #316
