### ISSUE TITLE
Lost in how to write myconfig.py (Where to put self-extracted frames & csv files?)

### ISSUE THREAD

**Issue by bill-connelly** [DeepLabCut/DeepLabCut#32]
I've gone through an made a folder that is full of img000.png .... image200.png and labelled all of the parts in Fiji, [generating a randomly selected set wouldn't work very well here] and saved it in Results.csv, all of which are in 

C:\Users\wmkc\Documents\DeepLabCut\Generating_a_Training_Set\bill-reaching

So that means
vidpath = '.'
filename = 'reachingvideo1.avi'

are irrelevant, as I don't need DLC to select my frames.

I've set cropping = False, as I've already cropped the video.

I've set multibodypartsfilename like this:
multibodypartsfilename="C:\Users\wmkc\Documents\DeepLabCut\Generating_a_Training_Set\bill-reaching\Results.csv"
As I can't see where else the directory was set

But where do I set where the PNGs are stored?

**Comment by FedeClaudi** [comment]
You don't need to specify the path of Results.csv .

When you run Step_2 of generating a training set (which is the one that looks at Results.csv), this is already within your `"C:\Users\wmkc\Documents\DeepLabCut\Generating_a_Training_Set"`, it then derives which folder contains your images like this:
`basefolder = 'data-' + Task + '/'` (where Task is specified in myconfig.py) is where your training images are. It then looks for subfolders within the basefolder which contain the the Results.cvs file [See lines 40-49 of Step2].  So it might be that in your case you need to put your images and .csv files into a subfolder of data-'Task'.

Hope this helps, 
Federico

**Comment by AlexEMG** [comment]
Alternatively you can change the paths accordingly in Step_2, and so on.
