### ISSUE TITLE
check_labels -- is it supposed to be displaying each image?

### ISSUE THREAD

**Issue by JohnCraigPublic** [DeepLabCut/DeepLabCut#322]
Ubuntu 16.04 LTS
DLC 2.06
Anaconda Env

When I do:

deeplabcut.check_labels(config_path)

The screen flashes and I see each image in my training set flash by at the rate of about one image per second - but they are semi-transparent with the desktop and/or other windows showing thru them - very weird looking -- don't know how to stop, pause, or what to do with this...

Is this a bug or a mis-feature?

**Comment by MMathisLab** [comment]
you mean `deeplabcut.check_labels(config_path, plotting=True)`? They are stored in a folder, so you can open and inspect them individually!

https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#e-check-annotated-frames
