### ISSUE TITLE
"import deeplabcut" error Windows 7

### ISSUE THREAD

**Issue by Simian1** [DeepLabCut/DeepLabCut#323]
Hi, I'm not a programmer and have a very limited experience of installing/running programs. Thank you for your time.

OS: Windows 7, 64 bit, no GPU

Tried to install and use DeepLabCut using the following steps:

1. Installed Anaconda 3.7 for Windows
2. Downloaded the DeepLabCut-master zip and extracted in C:\Users
3. Opened Anaconda Prompt:
3.1. cd C:\Users\DeepLabCut-master\conda-environments
3.2. conda env create -f dlc-windowsCPU.yaml
3.3. Installed/upgraded the following:
pip install --upgrade tensorflow
pip install --upgrade numpy
pip install easydict
pip install scikit-image

4. Opened Anaconda Prompt with admin rights
4.1 conda activate dlc-windowsCPU
4.2 cd C:\Users
4.3 ipython
4.4 import deeplabcut

... And then I get the following error(s).

![dlc-error1](https://user-images.githubusercontent.com/51838892/59542390-93c64900-8ed3-11e9-9f74-92ab93812ac5.JPG)

![dlc-error2](https://user-images.githubusercontent.com/51838892/59542392-9628a300-8ed3-11e9-966c-7fa729f82be6.JPG)

I searched for similar issues, but none of the suggestions helped, unfortunately.

**Comment by MMathisLab** [comment]
please do not do:
```
3.3. Installed/upgraded the following:
pip install --upgrade tensorflow
pip install --upgrade numpy
pip install easydict
pip install scikit-image
```

JUST use the file as it is supplied:
```
3.1. cd C:\Users\DeepLabCut-master\conda-environments
3.2. conda env create -f dlc-windowsCPU.yaml
4.1 conda activate dlc-windowsCPU
```
But, that being said, unfortunately we do not support Windows 7, please see user guide here: https://www.biorxiv.org/content/10.1101/476531v1

**Comment by MMathisLab** [comment]
But now, before you try to create it again, you MUST delete it first. 

https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

`conda remove --name dlc-windowsCPU --all`

**Comment by Simian1** [comment]
Thank you! 

For those of you with no choice but to use Windows 7, downgrading to TF 1.5 in the environment worked for me. I'll now upgrade to Windows 10 as I move to a more powerful computer with GPU.
c.f. https://github.com/AlexEMG/DeepLabCut/issues/302

**Comment by MMathisLab** [comment]
Great! Thanks for following up too!
