### ISSUE TITLE
"Not a valid checkpoint" error when running the demo

### ISSUE THREAD

**Issue by vigji** [DeepLabCut/DeepLabCut#326]
Installed DeepLabCut 2.0 in an Anaconda3 env created with the provided configuration files, on a Windows10 machine (actually, on 2 different machines).

Running the Openfield DEMO notebook, I get up to the train_network cell. When running it, I get the following error:

"ValueError: The passed save_path is not a valid checkpoint: C:\Users\lpetrucco\AppData\Local\Continuum\anaconda3\envs\dlc-windowsCPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt"

The path is correct, but when I get there there is actually no file called that way. Was it supposed to be generated before? I am running the load_demo_data and get no error after the "Downloading the pretrained model (ResNets)...." print.

**Comment by vigji** [comment]
Sorry, privileges problem, now solved.

**Comment by MMathisLab** [comment]
^ in case others find this error, please see our [Troubleshooting Tips section](https://github.com/AlexEMG/DeepLabCut/wiki/Troubleshooting-Tips) (and search other GitHub issues first). 

section from https://github.com/AlexEMG/DeepLabCut/wiki/Troubleshooting-Tips reproduced here:

Weights not downloaded. If you get permission errors FileNotFound (or ValueError: The passed save_path is not a valid checkpoint: xxx\Deeplabcut\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt) when you run training, first check if the RestNet weights downloaded.

This is an error more common in Windows, but some docker containers might not have admin privileges for this (it can be user specific). They should be under 'init_weights' (see path in the pose_cfg.yaml file). For Windows, also please install GITBASH https://gitforwindows.org/ and OPEN cmd by right-clicking "run as ADIM"

You can "cd" in the terminal to the package location!

i.e. in linux copy and paste this in: cd usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/

in Windows: cd C:\Users\YourComputerName\Anaconda3\envs\DLC\Lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained

And if you type "ls" to see the list of files, you should see the resnet: resnet_v1_50.ckpt

If it is not there, run sudo download.sh then change the permissions: sudo chown yourusername:yourusername resnet_v1_50.ckpt

See more tips here: https://github.com/MMathisLab/Docker4DeepLabCut2.0#using-the-docker-for-training-and-video-analysis

Troubleshooting (2): if it appears the training does not start (i.e. "Starting training..." does not print immediately), then you have another session running on your GPU. Go check "nvidia-smi" and look at the process names. You can only have 1 per GPU!)
