### ISSUE TITLE
Score Map Question

### ISSUE THREAD

**Issue by nickkaliss** [DeepLabCut/DeepLabCut#328]
Hello,

I've been using DeepLabCut for a few weeks now, and I would like to generate Score Maps like those in Figure 7 of this paper: https://www.nature.com/articles/s41593-018-0209-y.epdf?author_access_token=WWjWAHwCNMade8t_UQmpKNRgN0jAjWel9jnR3ZoTv0Mb0PEGIa3bu2e-LlyLrwFZlGVjSJpvn8Y1mKcatZBte5k0VIAM2K8VG_i7ooxRRcfduiyk0Ljk1CzqQdllt7REwOEeh8tU5ldLBk613zOdmA%3D%3D .

I found this script for it: https://github.com/AlexEMG/DeepLabCut/blob/1.11/Analysis-tools/AnalyzeVideosAndExtractScoreMaps.py , but I'm a little confused on how to run this script, as the DeepLabCut which I git cloned does not have an "Analysis-Tools" folder and so I can't specify the path to run this script. Any help is greatly appreciated, thanks in advance and please let me know if you have any further questions!

**Comment by MMathisLab** [comment]
I @nickkaliss first, we'd really prefer if users posted questions here: https://forum.image.sc/tags/deeplabcut

 As we state on the README: https://github.com/AlexEMG/DeepLabCut#community-support-developers--help

That function works for DeepLabCut 1 code base, whereas you are likely using 2. It might be put into 2 soon though.

**Comment by nickkaliss** [comment]
My apologies, thank you for the quick response.
