### ISSUE TITLE
Uncorrect matching between frames and analyze plotting

### ISSUE THREAD

**Issue by gillescourtand** [DeepLabCut/DeepLabCut#329]
**Your Operating system and DeepLabCut version**
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut 2.0.6.2

**Describe the bug**
bad frame extraction with extract_outlier_frames function (opencv as reader can't read correctly our video) : Is the problem due to video compression format ?
![Capture2](https://user-images.githubusercontent.com/45424082/59833047-8aab0100-9345-11e9-959c-b2c46d07e30e.png)
![Capture5](https://user-images.githubusercontent.com/45424082/59833067-94346900-9345-11e9-9ddb-9dd66f60bd0c.png)

**To Reproduce**
After analyze_videos 
- We check the labels with create_labeled_video : The plotting is almost ok, and we would like to correct some positions. 
- We run extract_outlier_frames : the fonction give us a huge quantity of outlier frames (ie : 180/200 !) 
- We open them with refine_labels we can observe that almost all positions are shifted (seem correct relative to each other but don't match the positions on the frame).
The explanation is that the video is not correctly read by opencv, and some frames are duplicated (we can see it when running "refine" with manual option to display all the frames) . So the analysis function open and analyze all the frames correctly but the extract_outlier can't and when the refine function read a frame the overlayed plot come from another frame. 

**Expected behavior**

**Screenshots**

**Additional context**

sincerely

gilles

**Comment by MMathisLab** [comment]
Seems to very likely to a codec issue! If you can convert you video to ``mp4``, that is a good test. ffmpeg is installed with deeplabcut, so you can run this inside the same conda env. 

namely, something like this (not in ipython):
```
ffmpeg -i LostInTranslation.mkv -codec copy LostInTranslation.mp4
```
(example from here: https://askubuntu.com/questions/396883/how-to-simply-convert-video-files-i-e-mkv-to-mp4)

**Comment by gillescourtand** [comment]
ok, you 're right about the codec : it seems that ffmpeg and opencv don't read videos the same way.
"copy" don't solve the problem but "libx264" does :
ffmpeg -i input.avi -c:v libx264 -preset ultrafast -crf 22 output.avi

Our error was to record at 120fps which is 8.333333ms interframe

thanks
