### ISSUE TITLE
Extracting Frames - Multiple videos

### ISSUE THREAD

**Issue by FedeClaudi** [DeepLabCut/DeepLabCut#33]
Hi, 

When creating the training set, the first step is to extract a predetermined number of randomly selected frames from a video that will be subsequently manually labelled. To increase the effectiveness of the training, the training set should be composed of frames extracted from multiple videos. However, currently it is possible to extract frames only from one video at the time, it would be easier/faster if one could put all the training videos in a folder and have the code go through each of them automatically. So one would simply specify the folder with the videos and the code would extract the same number of frames from each video in the folder, without requiring further manual input. 

Thank you, 
Federico

**Comment by MMathisLab** [comment]
If you just leave the video name blank it does loop over folders to generate frames to label already - hope that helps.

**Comment by AlexEMG** [comment]
Hi Federico,

the intended method so far was to do this manually. However, I updated the [code](https://github.com/AlexEMG/DeepLabCut/blob/master/Generating_a_Training_Set/Step1_SelectRandomFrames_fromVideos.py). We also added another frame selection method (other than temporally uniform), which works well to extract distinct frames for sparse behaviors. 

Anyway, to extract frames from all videos in a particular folder just set the filename in [myconfig.py](https://github.com/AlexEMG/DeepLabCut/blob/master/myconfig.py) to "all".

Alexander
