### ISSUE TITLE
.h5 FileNotFoundError - Evaluate Results

### ISSUE THREAD

**Issue by jeschole** [DeepLabCut/DeepLabCut#330]
**Your Operating system and DeepLabCut version**
CentOS 7 using an Anaconda Environment and DeepLabCut 2.0.6.

Using an HPC Grid to complete the evaluation (which worked successfully to train the network)

**Describe the problem**

When I try to evaluate the trained video results, I get a filenotfounderror return saying that the .h5 file does not exist in the newly created evaluation_results folder. Does not appear to be a channels issue as is the case in issue #28.

**How to Reproduce the problem**
import deeplabcut
config_path = '/mnt/research/hhorch/jeschole/190618-Julie-2019-06-18/config.yaml'
deeplabcut.evaluate_network(config_path, plotting=True)

Error returned:

Use standard file APIs to check for files with this prefix.

0it [00:00, ?it/s]
DLC loaded in light mode; you cannot use the labeling GUI!
DLC loaded in light mode; you cannot use the relabeling GUI!
Running  DeepCut_resnet50_190618Jun18shuffle1_1030000  with # of trainingiterations: 1030000
Analyzing data...
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/evaluate.py", line 153, in evaluate_network
    DataMachine = pd.read_hdf(resultsfilename,'df_with_missing')
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/pandas/io/pytables.py", line 371, in read_hdf
    'File %s does not exist' % path_or_buf)
FileNotFoundError: File /mnt/research/hhorch/jeschole/190618-Julie-2019-06-18/evaluation-results/iteration-0/190618Jun18-trainset95shuffle1/DeepCut_resnet50_190618Jun18shuffle1_1030000-snapshot-1030000.h5 does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/research/hhorch/jeschole/190618-Julie-2019-06-18/HPC_Scripts/evaluate_network-190618.py", line 3, in <module>
    deeplabcut.evaluate_network(config_path, plotting=True)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/evaluate.py", line 163, in evaluate_network
    image = io.imread(os.path.join(cfg['project_path'],imagename),mode='RGB')
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/skimage/io/_io.py", line 61, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/skimage/io/manage_plugins.py", line 210, in call_plugin
    return func(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/imageio/core/functions.py", line 202, in imread
    raise TypeError('Invalid keyword argument "mode", '
TypeError: Invalid keyword argument "mode", perhaps you mean "pilmode"?

**Additional context**
I trained a new project with a different video and got the same error when I tried the evaluate_network command. 
Thanks for your help!

**Comment by MMathisLab** [comment]
Looks like you don't have write permissions on the HPC, as it cannot write the .h5 file

can you also check which version of imageio you have, it should be ``imageio==2.3.0``

And, just double checking the network weights are in the folder i.e. ... DeepCut_resnet50_190618Jun18shuffle1_1030000

**Comment by jeschole** [comment]
Thank you! I have full permissions on the HPC and imageio is version 2.3.0 so that is good. However, I do not have any of the network weightsin the folder... I'm going to try starting from scratch and training in a new project to see if the error happens again.

**Comment by MMathisLab** [comment]
Be sure to set save_iters :)

**Comment by MMathisLab** [comment]
@jeschole - any updates?

**Comment by jeschole** [comment]
After training again (and making sure that save_iters set to every 50,000) I'm still getting a file not found error on the resnet and am not seeing the .h5 file saved anywhere else...

**Comment by MMathisLab** [comment]
Then you probably don't have permission to write files the resnets are not downloaded, or pytables is not installed correctly... here is how to check this: https://github.com/AlexEMG/DeepLabCut/wiki/Troubleshooting-Tips

can you send me a screenshot of this folder? "dlc-models"

**Comment by jeschole** [comment]
<img width="523" alt="Annotation 2019-06-24 114444" src="https://user-images.githubusercontent.com/52043900/60032917-8ea48f00-9675-11e9-8acb-a1afdc2eb6f1.png">
This is the train folder from within dlc-models, the only subdirectory that has content in dlc-models

**Comment by MMathisLab** [comment]
okay great that means it IS saving the models... 

are you using the supplied anaconda env? You should have pytables ``pytables==3.4.4`` in the environment. If you are not using the supplied, env, be sure you run ``conda forge pytables==3.4.4``

as here: https://github.com/AlexEMG/DeepLabCut/issues/63

**Comment by jeschole** [comment]
Currently pytables is installed as version 3.5.1. Should I reinstall it as 3.4.4?

**Comment by MMathisLab** [comment]
Yes! That should solve the issue. But, I, personally, would just create a new conda environment and work with your project inside there (no need to re-do anything else): https://github.com/AlexEMG/DeepLabCut/tree/master/conda-environments

**Comment by jeschole** [comment]
Great, thank you! I will try that!

**Comment by jeschole** [comment]
Downgrading to pytables 3.4.4 was the fix! Thanks so much for your help.

**Comment by uros171513** [comment]
Hi @MMathisLab, I have everything installed like you suggest and I have a full permissions. Also, I have my weights saved but I cannot successfully run the evaluation. This wasn't the issue before, when I was trained by using resnet_51, now, I used resnet_101 and the problem occurred. Any suggests on what should I look at other than this what you suggested earlier in this post.
