### ISSUE TITLE
No Images Created when extracting frames

### ISSUE THREAD

**Issue by tomaitagaki** [DeepLabCut/DeepLabCut#332]
Windows, DeepLabCut 2.0.6.3

When following the deeplabcut demos (Reaching Mackenzie, Open Field, Demo Your Own Data), I keep running into the issue of not having any images after using extract_frames (both automatically and manually). 

**Specifically for 'reaching mackenzie, open field':**
deeplabcut.check_labels(path_config_file) does not produce images with labels as the tutorial assumes and displays the message (not an error): 

Creating images with labels by Mackenzie.
C:\Users\Toma\Documents\DLC2019\DeepLabCut\examples\Reaching-Mackenzie-2018-08-30\labeled-data\reachingvideo1_labeled  already exists!
They are stored in the following folder: C:\Users\Toma\Documents\DLC2019\DeepLabCut\examples\Reaching-Mackenzie-2018-08-30\labeled-data\reachingvideo1_labeled.
Attention: C:\Users\Toma\Documents\DLC2019\DeepLabCut\examples\Reaching-Mackenzie-2018-08-30\labeled-data\reachingvideo1 does not appear to have labeled data!

The images are not stored in the labeled-data folder but does not throw out an error, just an Attention PSA.

**Specifically for 'your own data':**
The video file path is correct in the config.yaml and the extracting process works fine using the GUI:
In [7]: deeplabcut.extract_frames(path_config_file,'manual')
Quitting for now!

Frames were selected.
You can now label the frames using the function 'label_frames' (if you extracted enough frames for all videos).

But when going to label the data, there are no images in the labeled_data folder. There are no errors and I am stuck.

Any insight helps, thanks,
Toma

**Comment by MMathisLab** [comment]
I'm a bit confused: 

> "I keep running into the issue of not having any images after using extract_frames (both automatically and manually)." 


but then you post: 

> 
> deeplabcut.check_labels(path_config_file) does not produce images with labels as the tutorial assumes and displays the message (not an error):
> 
> Creating images with labels by Mackenzie.
> C:\Users\Toma\Documents\DLC2019\DeepLabCut\examples\Reaching-Mackenzie-2018-08-30\labeled-data\reachingvideo1_labeled already exists!
> They are stored in the following folder: C:\Users\Toma\Documents\DLC2019\DeepLabCut\examples\Reaching-Mackenzie-2018-08-30\labeled-data\reachingvideo1_labeled.
> Attention: C:\Users\Toma\Documents\DLC2019\DeepLabCut\examples\Reaching-Mackenzie-2018-08-30\labeled-data\reachingvideo1 does not appear to have labeled data!

Which is related to `check_labels` 

The demo data allows for training and evaluation, etc, but because it was created on Linux, you won't be able to do some early steps with the project due to you using windows. 

Then:

> 
> The video file path is correct in the config.yaml and the extracting process works fine using the GUI:
> In [7]: deeplabcut.extract_frames(path_config_file,'manual')
> Quitting for now!
> 

Are you using the supplied Anaconda Env? If no images are saved, perhaps you are not running as a admin, and or you have issues with some package installations. I would use one of these files here to work within an anaconda env:

https://github.com/AlexEMG/DeepLabCut/tree/master/conda-environments

**Comment by tomaitagaki** [comment]
Hello and thanks for the reply,

I am running this on a windows host which makes the errors with the demos understandable. I was able to extract frames manually and was successfully able to create a video after running as admin.

**Comment by MMathisLab** [comment]
Great, yeah the admin step is easy to overlook and strangely hard to troubleshoot sometimes! Glad it’s resolved.
