### ISSUE TITLE
Docker container not able to import deeplabcut in Jupyter notebook because of wx import call

### ISSUE THREAD

**Issue by achamess** [DeepLabCut/DeepLabCut#333]
**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

DeepLabCut Docker on AWS Deep Learning v20 (Ubuntu)
Ubuntu 16.04.5 LTS

**Describe the problem**

I installed the Docker as described in the setup instructions.
I suppressed the GUI using the `export DLClight=True` option.
However, when I access iPython then from the terminal, it says it can't find deeplabcut.

So I tried another way, since I know DLC is in this Docker container.

I used the Jupyter notebook interface.

Now it seems that the `deeplabcut` module is found, but it's getting hung up at the import `wx`. I thought that the DLClight option was supposed to turn that off. 

Anyway, I'm not sure what's going on. 

```

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-52d2df9c7fa5> in <module>()
----> 1 import deeplabcut

/usr/local/lib/python3.6/dist-packages/deeplabcut/__init__.py in <module>()
     27     else:
     28         mpl.use('Agg')
---> 29     from deeplabcut import generate_training_dataset
     30     from deeplabcut import refine_training_dataset
     31     from deeplabcut.generate_training_dataset import label_frames, dropannotationfileentriesduetodeletedimages, comparevideolistsanddatafolders

/usr/local/lib/python3.6/dist-packages/deeplabcut/generate_training_dataset/__init__.py in <module>()
     16     pass
     17 else:
---> 18     from deeplabcut.generate_training_dataset.auxfun_drag_label import *
     19     from deeplabcut.generate_training_dataset.labeling_toolbox import *
     20     from deeplabcut.generate_training_dataset.frame_extraction_toolbox import *

/usr/local/lib/python3.6/dist-packages/deeplabcut/generate_training_dataset/auxfun_drag_label.py in <module>()
     17 
     18 import numpy as np
---> 19 import wx
     20 
     21 class DraggablePoint:

ModuleNotFoundError: No module named 'wx'

```

**Screenshots**

![Screen Shot 2019-06-24 at 12 01 10 AM](https://user-images.githubusercontent.com/7445362/59992807-32108800-9613-11e9-908a-00c922223e25.png)

**Comment by MMathisLab** [comment]
HI, please open docker code related issues here: https://github.com/MMathisLab/Docker4DeepLabCut2.0

**Comment by MMathisLab** [comment]
^ Also, since the main repo has two dockers, please state which container/image you are using.  

To note, when you open the jupyter interface, you need to run ``!export DLClight=True`` inside the notebook, please see here:

https://github.com/AlexEMG/DeepLabCut/blob/master/examples/Docker_TrainNetwork_VideoAnalysis.ipynb

lastly, there should be no anaconda inside the Docker, so for your second error, it looks like you are not inside the docker container image I provide.

![image](https://user-images.githubusercontent.com/28102185/60038170-8d795f00-9681-11e9-9da7-a39e0234eeb5.png)

**Comment by achamess** [comment]
﻿Thank you. Sorry for not placing this comment in the right area.

So the confusion came from following the instructions exactly from this tutorial page:
https://github.com/MMathisLab/Docker4DeepLabCut2.0

I went into the terminal as described and set the DLClight. But then I was trying to work from the Jupyter notebook. I didn’t know that you had to set the DLClight from within the notebook.

Your notebook though explains that and now I’m training. So thanks!
Maybe link to the that notebook from the page above (https://github.com/MMathisLab/Docker4DeepLabCut2.0) and clarify that if you use the notebook, you need to set from within it? For future users. I’m set now.

As an aside, I had the problem with the resnet weights permission and worked through it. I’m using Linux Deep Learning AWS 20.0.

Thanks for your hard work and sharing this with us all.
-Alex

**Comment by MMathisLab** [comment]
great, I added a note to the project readme: https://github.com/MMathisLab/Docker4DeepLabCut2.0/blob/master/README.md
