### ISSUE TITLE
How to create lines connecting the dots?

### ISSUE THREAD

**Issue by Zackhardtoname** [DeepLabCut/DeepLabCut#334]
**Environment**
Windows 10
DeepLabCut version: 2.0.6.3

**Problem**
I can't find where to set the lines (connecting the labeled dots) in the final outcome. The lines should be like these: 

1. https://static1.squarespace.com/static/57f6d51c9f74566f55ecf271/t/5c474ec040ec9a88e4d67842/1548176652470/MousereachGIF.gif?format=750w
2. https://twitter.com/DeepLabCut/status/1141895149519163397

I looked into the user guide as well as the source code but have not been able to find it so far. Thank you for your help!

**Comment by MMathisLab** [comment]
Please look at the documentation: 

https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#create-labeled-videos

(also, we'd really prefer only code bugs here, and questions please post on the user forum: https://forum.image.sc/tags/deeplabcut

**Comment by MMathisLab** [comment]
an, it's ONLY in 2.0.7

**Comment by Zackhardtoname** [comment]
Got it... Thank you for your quick response.

**Comment by MMathisLab** [comment]
no problem!
