### ISSUE TITLE
Cropping after labeling

### ISSUE THREAD

**Issue by rnewsome6** [DeepLabCut/DeepLabCut#336]
Hi I'm running deeplabcut and I recently ran into a 'ResourceExhaustedError' when I went to use the train_network() command. It seems like the filesize of the frames might just be too big for my GPU to handle. There's part of the frame I could crop out, and hopefully reduce the file size enough to solve the problem, I would just rather not have to start back over from the labeling step, and have to label each frame again if that'd be possible. Is that something I could do?

**Comment by AlexEMG** [comment]
You can also change the global_scale... (will downsample during training) to figure out what your system can stomach.
