### ISSUE TITLE
Classification of behaviors tracked by DLC

### ISSUE THREAD

**Issue by DavidacusLeGrande** [DeepLabCut/DeepLabCut#34]
I have been using your software for a little under a month now and have been able to train it to track a few different behaviors. However, it does not appear that the software can classify behaviors based on the pose-data. My lab would like to use your software to detect and classify certain behaviors so that we can run more targeted experiments on our mice. The idea is that based on the pose-data, the software can classify the behavior it's tracking. For example, if I were to pick out a random frame from the analyzed video, it would tell me that at this frame the mouse was rearing, grooming, etc. The closest program that I found with this capability is this: 

print: http://serre-lab.clps.brown.edu/wp-content/uploads/2012/10/ncomms1064.pdf
code: http://cbcl.mit.edu/software-datasets/mouse/

To be completely honest, I am not sure how difficult this will be to implement into your code but I think it would be a rather useful addition. 

More than happy to chat more about this if you'd like a more detailed description of the feature request!

Best,

DavidSBU

**Comment by AlexEMG** [comment]
Indeed, DeepLabCut's raison d'être is creating tailored pose-estimation networks based on supervised learning with a few images. There are many methods for behavioral classification as reviewed, e.g., in this [excellent recent article](https://bmcbiol.biomedcentral.com/articles/10.1186/s12915-018-0494-7). For many behaviors the output of DLC should be very efficient for classifying simple (kinematic) behaviors without much hassle (e.g. turning, rearing, etc). That said, it would be great to interface with some of the open source software for behavioral classification out there.

**Comment by AlexEMG** [comment]
There is some MotionMapper interface here: https://github.com/AlexEMG/DLCutils
Perhaps other import functions to other packages can also be added there.
