### ISSUE TITLE
deeplabcut.refine_labels has no labeled data to load [pass analyzed video not labeled video]

### ISSUE THREAD

**Issue by kellykim5** [DeepLabCut/DeepLabCut#342]
**Linux Mint, with anaconda env,  deeplabcut 2.0**

**Describe the problem**
Hi, 
We're having problems loading labeled data at Step K (refine labels), even after doing all the steps up to J. 

At Step J, the video path path file we're feeding into is the .mp4 file that has the labels.

After Step J where we extract outlier frames, ipython gives me this output: 
network parameters: DeepCut_resnet50_TrackHydraJun18shuffle1_1030000
but no errors.

At Step K where I do deeplabcut.refine_labels(config_path), the GUI is up but when I click "load labels" nothing is selectable.

Is there a solution to this? Could I be missing something?

Thank you in advance for your help! 

 

**Screenshots**

**Additional context**

**Comment by MMathisLab** [comment]
normally you just see an empty folder, but you click select and they load, is that not the case? Can you post a screen shot?

**Comment by kellykim5** [comment]
![Screenshot from 2019-06-28 13-56-43](https://user-images.githubusercontent.com/52329772/60364830-c761a280-99ac-11e9-9928-55c217f3a5ab.png)

Thank you for getting back!
I do see an empty folder, and the "open" button is grayed out so I can't load any files at all, it seems like. Here's the screenshot.

I tried every folder possible, but all of them are like the above. :')

**Comment by MMathisLab** [comment]
Which deeplabcut version are you using? You said 2.0 but that’s very old. 

In the folder you can see the images and the machine-labeled.h5 file? Ie you ran analyze-videos them extracted outlier frames?

**Comment by kellykim5** [comment]
I did install deeplabcut 2.0, basically followed the instructions on gitHub. (It also says "DeepLabCut 2.0 - Refinement ToolBox" - does this not mean it's 2.0?)

Also analyzed videos and extracted outlier frames, but I cannot see any machine-labeled.h5 files anywhere.
As stated above, after running extracting outlier frames,  "network parameters: DeepCut_resnet50_TrackHydraJun18shuffle1_1030000" is the message I get.

**Comment by MMathisLab** [comment]
Okay then it didn’t extract anything. So check the video path you put in carefully (or post here so we can take a look). 

Also you can check version by: 
```
Import deeplabcut 
deeplabcut.__version__ 
```
^ this is true for any python package :)

**Comment by kellykim5** [comment]
Deeplabcut version is 2.0.6.3

The video path that I need to feed in the extract_outlier_franes should be the one that has the labeled videos, is this right? (The video that has gone through video analysis and has labeled dots in the video) 

Here is the screenshot of it :)
Thanks for the help!

 
![image](https://user-images.githubusercontent.com/52329772/60367089-f844d600-99b2-11e9-9722-308629c06556.png)

**Comment by MMathisLab** [comment]
no it should not have the dots, that is the issue - it should be the original video that you ran analyze_videos on! :)

**Comment by kellykim5** [comment]
Oh I see! It works now, thank you so much!! :)

One final question is, I have multiple videos so when I did glob.glob() it didn't work, but when I fed one file it did. Is there a way to feed in multiple video files at once?

**Comment by MMathisLab** [comment]
not for manual, as that brings up a GUI for an individual video, If you want to extract from more but use the other settings, i.e. automatically, you can type:

```
deeplabcut.extract_outlier_frames?
```
to see all the options.
