### ISSUE TITLE
deeplabcut.check_labels: Attention: 'video...' does not appear to have labeled data!

### ISSUE THREAD

**Issue by Yaraat92** [DeepLabCut/DeepLabCut#344]
**Your Operating system and DeepLabCut version**

Windows 10, with an Anaconda Env, & DeepLabCut 2.0.7.
Browser: chrome

**Describe the problem**

After labeling all the extracted frames, I tried to run deeplabcut.check_labels(), but I got the message:

In [5]: deeplabcut.check_labels(r'D:\Mouse_top_view-Goldberg lab-2019-06-30\config.yaml')
Creating images with labels by Goldberg lab.
Attention: D:\Mouse_top_view-Goldberg lab-2019-06-30 lab-2019-06-30\labeled-data\cam12019-06-17T14_08_27 does not appear to have labeled data!
................. (for all videos)
and obviously the function does not create a 'labeled' directory with labeled frames.

**Screenshots**

![Picture1](https://user-images.githubusercontent.com/52376512/60397136-48a66a00-9b52-11e9-9de1-1169a45d1ec4.png)
![Picture2](https://user-images.githubusercontent.com/52376512/60397175-c2d6ee80-9b52-11e9-9c43-4a2c6859dfb0.png)
![Picture3](https://user-images.githubusercontent.com/52376512/60397183-f31e8d00-9b52-11e9-8fc9-8e4124a3072e.png)

**Additional context**

The config file path is correct.
I tried to re-label the same frames and when I load them to the GUI everything seems to be labeled. (3rd screenshot)
The .csv and .h5 files exist in all the directories. It seems that the labels do exist but the function cannot read the files.

How can I fix this?

**Comment by MMathisLab** [comment]
Double check the video path is correctly in your config.yaml file

**Comment by Yaraat92** [comment]
All paths are in the config.yaml file and they are all correct...
All other functions wokred fine (extract_frames, label_frames..)

**Comment by MMathisLab** [comment]
hmm... I (perhaps obviously) cannot reproduce your error. There may be issues with the name having a space, hence why [we say you](https://www.nature.com/articles/s41596-019-0176-0) must create the project without spaces in the "name" and "expt" variables. 

![Screen Shot 2019-06-30 at 11 40 56 AM](https://user-images.githubusercontent.com/28102185/60398949-0d914000-9b2c-11e9-8454-05d4b18f5e23.png)

You can try to add the videos to the config.yaml again (you didn't type in the paths by hand into the config, right?) i.e. the only ways to add videos to the project are (1) when you create the project, or (2) [using the function](https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#a-create-a-new-project) ``deeplabcut.add_new_videos``

**Comment by MMathisLab** [comment]
You can however, fix your scorer name, as we have a function for it. Please see the doc string and details here (perhaps make a back-up copy of your labeled-data folder just in case). You will need to hand-rename the files (i.e. those in screenshot 2) without the space, i.e. not "Goldberg Lab" but "CollectedData_Goldberg_Lab.csv" but the function fixes all the lines inside the files, which would be a ton of work manually ;)

``deeplabcut.convertcsv2h5(config,userfeedback=True,scorer=None)``

https://github.com/AlexEMG/DeepLabCut/blob/2a2ad95a1ec35ad7f98d0155b4aa0d3ecedaefac/deeplabcut/utils/conversioncode.py#L19

Convert csv annotation files for reaching-task project into hdf while changing the scorer/annotator in all annotation files to Albert!
    >>> deeplabcut.convertcsv2h5('/analysis/project/reaching-task/config.yaml',scorer='Albert')

**Comment by Yaraat92** [comment]
Thanks.

First I tried to change the scorer name as you suggested and this is what i got:

![Picture4](https://user-images.githubusercontent.com/52376512/60399325-85328f80-9b6b-11e9-9a0a-398315ead820.png)


Then I tried to add the videos using the deeplabcut.add_new_videos() and got this:

![Picture5](https://user-images.githubusercontent.com/52376512/60399317-67fdc100-9b6b-11e9-8bf4-142856628457.png)

**Comment by MMathisLab** [comment]
Okay, so did you rename the files first as I said? Then it will convert them... (also you need to have .csv in the file name)

 And the second error tells you the problem, you can add only one at a time....
