### ISSUE TITLE
ubuntu 19.04 and wxPython [question]

### ISSUE THREAD

**Issue by ghost** [DeepLabCut/DeepLabCut#345]
For installing wxPython there are only two options (16.04 and 18.04) - Would it be best to install the 18.04 version as i am running ubuntu 19.04? Apologies if its a stupid question!

**Comment by MMathisLab** [comment]
We do not support 19.04. And correct, 16.04 and 18.04 wxPython will not work. 

Yet a quick google search yields options.... https://tutorialforlinux.com/2019/03/28/how-to-install-python-3-wxpython-for-ubuntu-19-04-disco-easy-guide/


We **please** ask users **don't ignore the issue template** and also to **post questions on [Image Forum](https://forum.image.sc/tags/deeplabcut)**, as stated in the readme - issues are for bug reports, feature requests, or issues using the software. 

![Screen Shot 2019-07-01 at 1 57 28 AM](https://user-images.githubusercontent.com/28102185/60413640-9f885f80-9ba3-11e9-9df2-49bd4204622c.png)
