### ISSUE TITLE
Cannot load frames

### ISSUE THREAD

**Issue by Lerichey** [DeepLabCut/DeepLabCut#346]
Windows 10, Anaconda Env, DeepLabCut 2.0.7, firefox

I am new to deeplabcut.  The initial creation of the project proceeded without issue. The config file has been edited to include the list of body parts I will be labeling and all other sections have been left as is. I received no error messages when extracting frames and can see all of the png images in the labeled data folder.  However, when I use the label frames command and try to load the frames, the labeled data video folders appear empty and I cannot access the images. I have tried deleting the images and extracting the frames again but the same issue occurs. If I select one of the video folders which should have the png files in it and click select folder, the error messages in the attached screenshot appear.  

Any help would be greatly appreciated!!

Lynnet

top of screen
![image](https://user-images.githubusercontent.com/52416491/60446993-7d68fe80-9bf0-11e9-855f-92b55d24cbda.png)
bottom of screen
![image](https://user-images.githubusercontent.com/52416491/60447008-878afd00-9bf0-11e9-9408-60ed3d431856.png)

**Comment by MMathisLab** [comment]
Could you please try with our supplied anaconda env? 

https://github.com/AlexEMG/DeepLabCut/tree/master/conda-environments

You likely have the wrong matplotlib and/or pytables installed for our package.
