### ISSUE TITLE
ResolvePackageNotFound

### ISSUE THREAD

**Issue by tochenan** [DeepLabCut/DeepLabCut#347]
**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.
Windows10 using the newest DeepLabCut version
**Describe the problem**

A clear and concise description of what the problem is.
when I was trying to create the conda environment using dlc-windowsGPU, I go the following error message:

C:\Users\analysis\DeepLabCut\conda-environments>conda env create -f dlc-windowsGPU.yaml
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - msvc_runtime

**Additional context**
I have followed the installation guide and installed NVIDIA driver, CUDA and visual studio.
Before I tried to create the dlc-windowsGPU environment, I have once used the dlc-winowsCPU environment and everything works, however, followed the installation of these drivers, when I tried to create the dlc-windowsCPU environment, the same error message was given.

Thank you very much.

Best,
Mingran

**Comment by MMathisLab** [comment]
you can just remove that line from the conda file, since you installed visual studio already.

**Comment by tochenan** [comment]
I tried that as well but another error arose afterwards:
:\Users\analysis\DeepLabCut\conda-environments>conda env create -f dlc-windowsGPU.yaml

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\exceptions.py", line 1043, in __call__
        return func(*args, **kwargs)
      File "C:\Users\analysis\Anaconda3\lib\site-packages\conda_env\cli\main.py", line 73, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Users\analysis\Anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 77, in execute
        directory=os.getcwd())
      File "C:\Users\analysis\Anaconda3\lib\site-packages\conda_env\specs\__init__.py", line 40, in detect
        if spec.can_handle():
      File "C:\Users\analysis\Anaconda3\lib\site-packages\conda_env\specs\yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "C:\Users\analysis\Anaconda3\lib\site-packages\conda_env\env.py", line 144, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "C:\Users\analysis\Anaconda3\lib\site-packages\conda_env\env.py", line 129, in from_yaml
        data = yaml_load_standard(yamlstr)
      File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\common\serialize.py", line 76, in yaml_load_standard
        return yaml.load(string, Loader=yaml.Loader, version="1.2")
      File "C:\Users\analysis\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 640, in load
        return loader._constructor.get_single_data()  # type: ignore
      File "C:\Users\analysis\Anaconda3\lib\site-packages\ruamel_yaml\constructor.py", line 102, in get_single_data
        node = self.composer.get_single_node()
      File "C:\Users\analysis\Anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 83, in get_single_node
        event.start_mark)
    ruamel_yaml.composer.ComposerError: expected a single document in the stream
      in "<unicode string>", line 1, column 1:
        ï»¿# dlc-windowsGPU.yaml
        ^ (line: 1)
    but found another document
      in "<unicode string>", line 18, column 1:
        name: dlc-windowsGPU
        ^ (line: 18)

`$ C:\Users\analysis\Anaconda3\Scripts\conda-env-script.py create -f dlc-windowsGPU.yaml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
                CONDA_EXE=C:\Users\analysis\Anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\analysis\Anaconda3\condabin\..\Scripts\conda.exe"
               CONDA_ROOT=C:\Users\analysis\Anaconda3
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
                 HOMEPATH=\Users\analysis
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=C:\Users\analysis\Anaconda3;C:\Users\analysis\Anaconda3\Library\mingw-
                          w64\bin;C:\Users\analysis\Anaconda3\Library\usr\bin;C:\Users\analysis\
                          Anaconda3\Library\bin;C:\Users\analysis\Anaconda3\Scripts;C:\Users\ana
                          lysis\Anaconda3\bin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v10.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\C
                          UDA\v10.1\libnvvp;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\syste
                          m32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPow
                          erShell\v1.0\;C:\Program Files (x86)\Wolfram
                          Research\WolframScript\;C:\Program
                          Files\MATLAB\R2019a\runtime\win64;C:\Program
                          Files\MATLAB\R2019a\bin;C:\Program Files\Git\cmd;C:\Program
                          Files\dotnet\;C:\Program Files\NVIDIA Corporation\Nsight Compute
                          2019.3.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Us
                          ers\analysis\Anaconda3;C:\Users\analysis\Anaconda3\Library\mingw-w64\b
                          in;C:\Users\analysis\Anaconda3\Library\usr\bin;C:\Users\analysis\Anaco
                          nda3\Library\bin;C:\Users\analysis\Anaconda3\Scripts;C:\Users\analysis
                          \AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\analysis\App
                          Data\Local\Programs\Python\Python37\;C:\Users\analysis\AppData\Local\M
                          icrosoft\WindowsApps;C:\Users\analysis\AppData\Local\atom\bin
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\analysis\.condarc
 populated config files :
          conda version : 4.7.5
    conda-build version : 3.18.5
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.2
       base environment : C:\Users\analysis\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\analysis\Anaconda3\pkgs
                          C:\Users\analysis\.conda\pkgs
                          C:\Users\analysis\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\analysis\Anaconda3\envs
                          C:\Users\analysis\.conda\envs
                          C:\Users\analysis\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.5 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.17134
          administrator : True
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

**Comment by MMathisLab** [comment]
I believe you just need to delete the conda env first, then re-create it

**Comment by tochenan** [comment]
I checked for the environments, here is what I have got:
C:\Users\analysis\DeepLabCut\conda-environments>conda info --envs
# conda environments:
#
base                  *  C:\Users\analysis\Anaconda3

So I don't think I have successfully created any conda environment

I have also tried to uninstall and reinstall anaconda but I got the same error message

**Comment by MMathisLab** [comment]
can you create a basic env?, i.e. `conda create -n testing python=3.6` 

as you say you could make it before 

> 
> I have followed the installation guide and installed NVIDIA driver, CUDA and visual studio.
> Before I tried to create the dlc-windowsGPU environment, I have once used the dlc-winowsCPU environment and everything works, however, followed the installation of these drivers, when I tried to create the dlc-windowsCPU environment, the same error message was given.

It is hard for us to troubleshoot for you... 

(also, PS we never say to install visual studio, which can be an issue)

**Comment by tochenan** [comment]
thank you for the comment.
I tried to uninstall the visual studio and reinstalled everything basically. A new error has arose ( at least some improvement),
UnsatisfiableError: The following specifications were found to be in conflict:
  - msvc_runtime
  - tensorflow-gpu==1.13.1 -> tensorflow==1.13.1 -> tensorboard[version='>=1.13.0,<1.14.0'] -> vc[version='>=14.1,<15.0a0']

do you know what was causing that? 
thank you very much for the help

best.
Mingran

**Comment by tochenan** [comment]
update:
I updated conda use the command line conda update conda and the old error popped up:
ResolvePackageNotFound:
  - msvc_runtime

however, before the update and after the update , when I tried to search for information related to msvc_tuntime, it gives me different information:

before update:
C:\Users\analysis\DeepLabCut\conda-environments>conda search msvc_runtime
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Loading channels: done
# Name                       Version           Build  Channel
msvc_runtime                   1.0.0          vc10_0  pkgs/free
msvc_runtime                   1.0.0          vc14_0  pkgs/free
msvc_runtime                   1.0.0           vc9_0  pkgs/free
msvc_runtime                   1.0.1          vc10_0  pkgs/free
msvc_runtime                   1.0.1          vc14_0  pkgs/free
msvc_runtime                   1.0.1           vc9_0  pkgs/free

after update:
C:\Users\analysis\DeepLabCut\conda-environments>conda search msvc_runtime
Loading channels: done
No match found for: msvc_runtime. Search: *msvc_runtime*

PackagesNotFoundError: The following packages are not available from current channels:

  - msvc_runtime

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by MMathisLab** [comment]
Yes, please remove the mscv_runtime, as I stated before, then try the conda env again... as it seems it's otherwise in a better state :)

**Comment by tochenan** [comment]
oh no. I tried it again and the same just happened for both the CPU and GPU environment

**Comment by KBillel** [comment]
> 
> 
> I tried that as well but another error arose afterwards:
> :\Users\analysis\DeepLabCut\conda-environments>conda env create -f dlc-windowsGPU.yaml
> # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\exceptions.py", line 1043, in __call__
>     return func(*args, **kwargs)
>   File "C:\Users\analysis\Anaconda3\lib\site-packages\conda_env\cli\main.py", line 73, in do_call
>     exit_code = getattr(module, func_name)(args, parser)
>   File "C:\Users\analysis\Anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 77, in execute
>     directory=os.getcwd())
>   File "C:\Users\analysis\Anaconda3\lib\site-packages\conda_env\specs\__init__.py", line 40, in detect
>     if spec.can_handle():
>   File "C:\Users\analysis\Anaconda3\lib\site-packages\conda_env\specs\yaml_file.py", line 18, in can_handle
>     self._environment = env.from_file(self.filename)
>   File "C:\Users\analysis\Anaconda3\lib\site-packages\conda_env\env.py", line 144, in from_file
>     return from_yaml(yamlstr, filename=filename)
>   File "C:\Users\analysis\Anaconda3\lib\site-packages\conda_env\env.py", line 129, in from_yaml
>     data = yaml_load_standard(yamlstr)
>   File "C:\Users\analysis\Anaconda3\lib\site-packages\conda\common\serialize.py", line 76, in yaml_load_standard
>     return yaml.load(string, Loader=yaml.Loader, version="1.2")
>   File "C:\Users\analysis\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 640, in load
>     return loader._constructor.get_single_data()  # type: ignore
>   File "C:\Users\analysis\Anaconda3\lib\site-packages\ruamel_yaml\constructor.py", line 102, in get_single_data
>     node = self.composer.get_single_node()
>   File "C:\Users\analysis\Anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 83, in get_single_node
>     event.start_mark)
> ruamel_yaml.composer.ComposerError: expected a single document in the stream
>   in "<unicode string>", line 1, column 1:
>     ï»¿# dlc-windowsGPU.yaml
>     ^ (line: 1)
> but found another document
>   in "<unicode string>", line 18, column 1:
>     name: dlc-windowsGPU
>     ^ (line: 18)
> ```
> 
> `$ C:\Users\analysis\Anaconda3\Scripts\conda-env-script.py create -f dlc-windowsGPU.yaml`
> 
> environment variables:
> CIO_TEST=
> CONDA_AUTO_UPDATE_CONDA=false
> CONDA_EXE=C:\Users\analysis\Anaconda3\condabin..\Scripts\conda.exe
> CONDA_EXES="C:\Users\analysis\Anaconda3\condabin..\Scripts\conda.exe"
> CONDA_ROOT=C:\Users\analysis\Anaconda3
> CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
> HOMEPATH=\Users\analysis
> NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt
> PATH=C:\Users\analysis\Anaconda3;C:\Users\analysis\Anaconda3\Library\mingw-
> w64\bin;C:\Users\analysis\Anaconda3\Library\usr\bin;C:\Users\analysis
> Anaconda3\Library\bin;C:\Users\analysis\Anaconda3\Scripts;C:\Users\ana
> lysis\Anaconda3\bin;C:\Program Files\NVIDIA GPU Computing
> Toolkit\CUDA\v10.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\C
> UDA\v10.1\libnvvp;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\syste
> m32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPow
> erShell\v1.0;C:\Program Files (x86)\Wolfram
> Research\WolframScript;C:\Program
> Files\MATLAB\R2019a\runtime\win64;C:\Program
> Files\MATLAB\R2019a\bin;C:\Program Files\Git\cmd;C:\Program
> Files\dotnet;C:\Program Files\NVIDIA Corporation\Nsight Compute
> 2019.3.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Us
> ers\analysis\Anaconda3;C:\Users\analysis\Anaconda3\Library\mingw-w64\b
> in;C:\Users\analysis\Anaconda3\Library\usr\bin;C:\Users\analysis\Anaco
> nda3\Library\bin;C:\Users\analysis\Anaconda3\Scripts;C:\Users\analysis
> \AppData\Local\Programs\Python\Python37\Scripts;C:\Users\analysis\App
> Data\Local\Programs\Python\Python37;C:\Users\analysis\AppData\Local\M
> icrosoft\WindowsApps;C:\Users\analysis\AppData\Local\atom\bin
> PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
> PowerShell\v1.0\Modules
> REQUESTS_CA_BUNDLE=
> SSL_CERT_FILE=
> 
> ```
>  active environment : None
>    user config file : C:\Users\analysis\.condarc
> ```
> 
> populated config files :
> conda version : 4.7.5
> conda-build version : 3.18.5
> python version : 3.7.3.final.0
> virtual packages : __cuda=10.2
> base environment : C:\Users\analysis\Anaconda3 (writable)
> channel URLs : https://repo.anaconda.com/pkgs/main/win-64
> https://repo.anaconda.com/pkgs/main/noarch
> https://repo.anaconda.com/pkgs/r/win-64
> https://repo.anaconda.com/pkgs/r/noarch
> https://repo.anaconda.com/pkgs/msys2/win-64
> https://repo.anaconda.com/pkgs/msys2/noarch
> package cache : C:\Users\analysis\Anaconda3\pkgs
> C:\Users\analysis.conda\pkgs
> C:\Users\analysis\AppData\Local\conda\conda\pkgs
> envs directories : C:\Users\analysis\Anaconda3\envs
> C:\Users\analysis.conda\envs
> C:\Users\analysis\AppData\Local\conda\conda\envs
> platform : win-64
> user-agent : conda/4.7.5 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.17134
> administrator : True
> netrc file : None
> offline mode : False
> 
> An unexpected error has occurred. Conda has prepared the above report.
> 
> If submitted, this report will be used by core maintainers to improve
> future releases of conda.
> Would you like conda to send this report to the core maintainers?

Hi, I just had this problem while editing the *.yaml file with notepad from windows. you should try using notepad++ or similar program as it is probably just a encoding problem.
