### ISSUE TITLE
Triangulation output to CSV

### ISSUE THREAD

**Issue by CMGreenspon** [DeepLabCut/DeepLabCut#348]
Line 197 of triangulation.py:
Best I can tell pandas .to_csv() has no format option and its inclusion produced the following error:

  File "xxx\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_3d\triangulation.py", line 197, in triangulate
    df_3d.to_csv(str(output_filename+'.csv'),'df_with_missing',format='table', mode='w')

TypeError: to_csv() got an unexpected keyword argument 'format'

Replacing:
 df_3d.to_csv(str(output_filename+'.csv'),'df_with_missing',format='table', mode='w')
with
df_3d.to_csv(str(output_filename+'.csv'), mode='w')

fixed the issue.
Windows 10/ DLC 2.0.7-GPU

**Comment by AlexEMG** [comment]
Thanks for your comment:

Perhaps this is already fixed in DLC 2.0.7.1.

https://github.com/AlexEMG/DeepLabCut/blob/af037324ac0676927a5e619c196b7c2084440921/deeplabcut/pose_estimation_3d/triangulation.py#L215
