### ISSUE TITLE
Step2 Converting labels | ValueError: cannot reindex from a duplicate axis

### ISSUE THREAD

**Issue by lemoz** [DeepLabCut/DeepLabCut#35]
**Describe the problem**
I'm trying to create a dataset to train a multi-person tracker. I've followed the tutorial to a T but seem to be hitting an error. I'm not really sure what is causing it to happen. 

The images I used have multiple of the same body part but on different subjects. I think this might be what is causing the problem, but I'm not sure

I've attached the traceback below. Would appreciate some feedback.

**Additional context**
ValueError                                Traceback (most recent call last)
<ipython-input-4-6be081cecc66> in <module>()
     50 #                     dframe.set_index('Slice')
     51                     new_index=pd.Index(np.arange(len(files))+1,name='Slice')
---> 52                     dframe=dframe.set_index('Slice').reindex(new_index)
     53                     dframe=dframe.reset_index()
     54 

~/anaconda3/lib/python3.6/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    184         @wraps(func)
    185         def wrapper(*args, **kwargs):
--> 186             return func(*args, **kwargs)
    187 
    188         if not PY2:

~/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py in reindex(self, *args, **kwargs)
   3561         kwargs.pop('axis', None)
   3562         kwargs.pop('labels', None)
-> 3563         return super(DataFrame, self).reindex(**kwargs)
   3564 
   3565     @Appender(_shared_docs['reindex_axis'] % _shared_doc_kwargs)

~/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py in reindex(self, *args, **kwargs)
   3683         # perform the reindex on the axes
   3684         return self._reindex_axes(axes, level, limit, tolerance, method,
-> 3685                                   fill_value, copy).__finalize__(self)
   3686 
   3687     def _reindex_axes(self, axes, level, limit, tolerance, method, fill_value,

~/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py in _reindex_axes(self, axes, level, limit, tolerance, method, fill_value, copy)
   3496         if index is not None:
   3497             frame = frame._reindex_index(index, method, copy, level,
-> 3498                                          fill_value, limit, tolerance)
   3499 
   3500         return frame

~/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py in _reindex_index(self, new_index, method, copy, level, fill_value, limit, tolerance)
   3507         return self._reindex_with_indexers({0: [new_index, indexer]},
   3508                                            copy=copy, fill_value=fill_value,
-> 3509                                            allow_dups=False)
   3510 
   3511     def _reindex_columns(self, new_columns, method, copy, level,

~/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py in _reindex_with_indexers(self, reindexers, fill_value, copy, allow_dups)
   3804                                                 fill_value=fill_value,
   3805                                                 allow_dups=allow_dups,
-> 3806                                                 copy=copy)
   3807 
   3808         if copy and new_data is self._data:

~/anaconda3/lib/python3.6/site-packages/pandas/core/internals.py in reindex_indexer(self, new_axis, indexer, axis, fill_value, allow_dups, copy)
   4412         # some axes don't allow reindexing with dups
   4413         if not allow_dups:
-> 4414             self.axes[axis]._can_reindex(indexer)
   4415 
   4416         if axis >= self.ndim:

~/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py in _can_reindex(self, indexer)
   3557         # trying to reindex on an axis with duplicates
   3558         if not self.is_unique and len(indexer):
-> 3559             raise ValueError("cannot reindex from a duplicate axis")
   3560 
   3561     def reindex(self, target, method=None, level=None, limit=None,

ValueError: cannot reindex from a duplicate axis

**Comment by vncntprvst** [comment]
The one time I had this issue was when I had multiple markers (labels) for one of the body parts I was tracking, but `multibodypartsfile` was set to False (since each body part had its own separate label file). I ended up splitting that body part in two subregions, and kept `multibodypartsfile = False`. 
Hope that helps.

**Comment by lemoz** [comment]
I'm tracking people in webcam footage. There can be multiple people per image so, when I go to map the body parts I end up marking multiple places per images for r_ankle. Does DeepLabCut support multiple people?

**Comment by MMathisLab** [comment]
It’s completely possible with the feature detectors, but not supported currently by the training data generation code/import code at this time.

**Comment by caniko** [comment]
Hello,

This future is non-existant at the moment if I understand correctly. I took this future for granted as we also have multiple mice in the sessions to be analysed. As a result, I got this error in step 2 (Step2_ConvertingLabels2DataFrame.py):
ValueError: cannot reindex from a duplicate axis

This error is raised because of multiple points in for single file with multibodypartsfile set to False (=False). Am I correct? In that case, consider this a plus one for this future.

Thank you for your time and great work
Best
Can

**Comment by edumagol** [comment]
Hi @lemoz , I had the same issue. To solve that, I printed the data frame and also printed the folders that is used in the Step2 python code when you choose "multibodypartsfile=True".

I could see the my *csv was not formatted properly.

Try to use the "multibodypartsfile=True", cause it will save you some time when you have many body parts to track.

Please, see the code with more print options below.

Best regards

`###################################################
# Code if all bodyparts (per folder are shared in one file)
# This code below converts it into multiple csv files per body part & folder
# Based on an idea by @sneakers-the-rat
###################################################

if multibodypartsfile==True:
    folders = [name for name in os.listdir(basefolder) if os.path.isdir(os.path.join(basefolder, name))]
    print(basefolder)
    print(folders)
    print(multibodypartsfilename)
    for folder in folders:
        # load csv, iterate over nth value in a grouping by frame, save to bodyparts files
        dframe = pd.read_csv(os.path.join(basefolder,folder,multibodypartsfilename))
        print(dframe)
        frame_grouped = dframe.groupby('Slice') #Note: the order of bodyparts list in myconfig and labels must be identical!
        for i, bodypart in enumerate(bodyparts):
            part_df = frame_grouped.nth(i)
            part_fn = os.path.join(basefolder,folder,bodypart+'.csv')
            part_df.to_csv(part_fn)`
