### ISSUE TITLE
Labeled images folder not created in evaluation-results after evalutating trained network

### ISSUE THREAD

**Issue by kellykim5** [DeepLabCut/DeepLabCut#351]
Linux Mint with Anaconda env and deeplabcut 2.0

Hi, I have two issues:

1.
I've re-trained the data (merged with original data + relabeld data using outlier frames + new data), which finished successfully. Then I evaluated the network.

The first time I did this (before re-training), a folder called "LabeledImages_DeepCut_resnet50_TrackHydraJun18shuffle1_1030000_snapshot-1030000" was created under "evaluation-results > iteration 0.  However when I re-trained and evaluated the network, it does not create the folder even with plotting=True parameter. 

![image](https://user-images.githubusercontent.com/52329772/60619161-a7abef00-9d9d-11e9-8ce6-a702aaf9cca3.png)

![image](https://user-images.githubusercontent.com/52329772/60619782-002fbc00-9d9f-11e9-811a-73e86650ce46.png)

So I cannot see the labeled data.

2. 
Also, when I try to re-analyze the videos using the re-trained network, it gives me a message saying "this video has already been analyzed" so it doesn't re-analyze it. After executing "create_labeled_video" command   I checked the folder, but the labeled videos are all the videos from before and not the newly labeled videos.

How could I fix this? 

Thanks in advance.

**Comment by MMathisLab** [comment]
did you change the interation # in the config.yaml file? It should be 2, since it seems 1 is deleted?

**Comment by kellykim5** [comment]
the iteration number in the config.yaml file says 2!

**Comment by MMathisLab** [comment]
oh, for labeled videos you need to re-name or delete the older video; you can also delete the evaulation folder and re-run the analysis, as it was perhaps run without plotting=True before, and if so, it will not create the plots.
