### ISSUE TITLE
Issue with refining labels

### ISSUE THREAD

**Issue by whsu2s** [DeepLabCut/DeepLabCut#353]
**Describe the bug**
The labels in the first frame got messed up when refining the labels.

**To Reproduce**
1. Follow the steps in "Demo_yourowndata.ipynb"
2. Use "%gui wx" and "deeplabcut.refine_labels(path_config_file)" to refine labels.
3. In the GUI, refine the labels in the first frame, and go to the next frame.
4. Go back to the first frame, and the labels were messed up and not at the manually refined positions.
5. This can be seen from the labeled images after using "deeplabcut.check_labels(path_config_file)".

**Desktop (please complete the following information about your system):**
 - OS: Ubuntu 18.04
 - DeepLabCut Version: 2.0.5.1
 - Browser: Firefox

**Additional context**
I tried using another computer (Ubuntu 14.04) with an earlier version of DeepLabCut (2.0.2.1) and the issue did not occur. I am not sure if the problem is in my computer or the codes. Any comment or suggestion would be appreciated.

**Comment by MMathisLab** [comment]
can you please try with 2.0.7.1?

**Comment by whsu2s** [comment]
Thanks! I tried with version 2.0.7.1, but the issue is still there, however.

**Comment by MMathisLab** [comment]
are you saying you tried with the same dataset and the different versions have diff outputs? I cannot reproduce the error with the demo data or otherwise; can you share a screenshot?

**Comment by whsu2s** [comment]
It does not matter which dataset to use. The issue is the labels of the first frame fall out of place as I refine the labels using the GUI. The image shown below is the labeled first frame (after calling the function check_labels()).

<img src="https://user-images.githubusercontent.com/22023623/60998139-a90a8800-a358-11e9-8048-b9debd144290.png" width="500" >

The labels of other frames are fine:
<img src="https://user-images.githubusercontent.com/22023623/60998714-c8ee7b80-a359-11e9-9534-f04687edc5f8.png" width="500" >

**Comment by meet10may** [comment]
We are unable to reproduce the issue at our end. Could you please explain the steps in detail that led to this error? 

While testing this issue multiple times, essentially with the following steps:

1. Extracted outlier frames manually (just 2 frames for testing purpose). 
2. Used the refinement GUI to move around the labels...put them to extreme locations to test.
3. Checked the labels using check_lables() and labels looked fine i.e. they were at the extreme locations, which was expected.

Is that what you did too? You can also open the labeling GUI and test the labels. Does it appear off in the labeling GUI too?

**Comment by MMathisLab** [comment]
can you share a screenshot of your folder with the image names? 

Edited to add: this seems strange to me that so many are outside the frame; are the cropped differently during analysis vs. extraction or such? 

> Found head outside the image labeled-data/cow274/img151.png.Setting it to NaN
> Found hoofFR outside the image labeled-data/cow274/img151.png.Setting it to NaN
> Found hoofHL outside the image labeled-data/cow274/img151.png.Setting it to NaN

**Comment by whsu2s** [comment]
@meet10may I did do the steps as you described, the only difference is that I moved the labels to the correct rather than extreme locations.
I don't quite understand what you mean by opening the labeling GUI to test the labels. As far as I know, the GUI only allows to open the (machinelabels) h5 file with all the extracted frames, but not the file with refined labels. Please correct me if I am wrong. 

@MMathisLab The screenshot is shown below. "img005.png" is the first frame that I manually extracted. 
<img src="https://user-images.githubusercontent.com/22023623/61188879-f56e0480-a685-11e9-9dac-287c93e4f862.png" width="500" >
I didn't change anything about the crop.

**Comment by MMathisLab** [comment]
After you merge you can open the file with the labeling GUI (not refinement), and see how the labels look there. You can also move them and save. We can’t figure out why your first frame is off... for now perhaps open them with deeplabcut.Label_frames, adjust that one frame, hit save, then check labels again?

**Comment by whsu2s** [comment]
Thanks for your quick response! I tried using "deeplabcut.label_frames" to open the labeled frames, but the files could not be opened (as shown below).

<img src="https://user-images.githubusercontent.com/22023623/61215752-fea1b480-a70b-11e9-8604-41ea367d1a49.png" width="500" >

**Comment by MMathisLab** [comment]
Then I’m doubly confused, can you re-open your original labels?

**Comment by whsu2s** [comment]
I can open the machinelabels.h5 using "deeplabcut.refine_labels".

**Comment by whsu2s** [comment]
But it seems CollectedData.h5 cannot be opened. I tried with both refine_labels and label_frames.

**Comment by meet10may** [comment]
It is very strange! Can you show us some screenshots/videos that you are unable to open the CollectedData_fkie.h5 using deeplabcut.label_frames? What do you mean you cannot open it? Are you not able to select the CollectedData_fkie.h5 file when you click the load frames?
FYI, you can open the CollectedData_fkie.h5 using deeplabcut.label_frames and machinelabels.h5 using the deeplabcut.refine_labels.

**Comment by whsu2s** [comment]
Whenever I use deeplabcut.label_frames or deeplabcut.refine_labels, the CollectedData.h5 files are not clickable from the pop-up screen. I guess there is a mechanism that prevents the user from editing the refined labels. 

<img src="https://user-images.githubusercontent.com/22023623/61376407-705f3700-a8a1-11e9-859b-5dc4c7d3b44a.png" width="800" >

**Comment by MMathisLab** [comment]
Just click open and it will load the collected data, which now contains your refined frames.... 

Also please update to 2.0.7; that GUI is very old.
