### ISSUE TITLE
Issues with export DLClight = True 

### ISSUE THREAD

**Issue by veronikasamborska1994** [DeepLabCut/DeepLabCut#355]
Hi there, 
when importing deeplabcut I keep getting these errors. I set  DLClight = True but it doesn't seem to help:

DLC loaded in light mode; you cannot use the relabeling GUI!
DLC loaded in light mode; you cannot use the labeling GUI!

**Comment by MMathisLab** [comment]
That is the expected behavior....  you set it to light mode for training on a cluster/computer without a screen.

**Comment by veronikasamborska1994** [comment]
sorry I don't think I understand what you mean. How do I get the labeling gui to work again?

**Comment by veronikasamborska1994** [comment]
If I set it false I get the following error 
---> 19 import wx
     20 
     21 class DraggablePoint:

/home/veronika/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/wx/__init__.py in <module>()
     15 # Import all items from the core wxPython module so they appear in the wx
     16 # package namespace.
---> 17 from wx.core import *
     18 
     19 

/home/veronika/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/wx/core.py in <module>()
     10 """
     11 
---> 12 from ._core import *
     13 
     14 #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

ImportError: libpng12.so.0: cannot open shared object file: No such file or directory


[21]+  Stopped                 ipython

**Comment by veronikasamborska1994** [comment]
Fixed it by reinstalling libpng12.so.0 with the following command for anyone who is using ubuntu 18.04 and has the same problem 

wget -q -O /tmp/libpng12.deb http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb \
  && sudo dpkg -i /tmp/libpng12.deb \
  && rm /tmp/libpng12.deb

**Comment by meet10may** [comment]
For the labeling GUI or any other GUI of the toolbox to work again, you need to unset the DLClight. You do not set it to False, rather you can do it as:

For Linux: 
```unset DLClight```
For Windows: 
```set DLClight=```

It is explained here (specifically page 2158): https://www.nature.com/articles/s41596-019-0176-0.pdf
