### ISSUE TITLE
Question: how to use human-pretrained network ResNet-101 pre-trained on MPII

### ISSUE THREAD

**Issue by phcao101** [DeepLabCut/DeepLabCut#356]
**Your Operating system and DeepLabCut version**

Windows 10 with an anaconda env

Please complete the following information about your system:

OS: Windows 10
DeepLabCut Version: 2.0.7
Browser: chrome

**Describe the problem**

Hi, I'm trying to train my network using this pretrained resnet 101 on mpii. I was wondering how exactly you were able to do that. After using curl to download:

mpii-single-resnet-101.data-00000-of-00001
mpii-single-resnet-101.index
mpii-single-resnet-101.meta

I then moved all three of these files to:
C:\Users\phcao\Miniconda3\envs\ecog\Lib\sitepackages\deeplabcut\pose_estimation_tensorflow\models\pretrained

Then, I figured the next step would be to edit:
init_weights

in the pose_cfg.yaml file and assign it to the path of the mpii-single-resnet-101 , specifically:

C:\Users\phcao\Miniconda3\envs\ecog\Lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\mpii-single-resnet-101

When I did this, and called

deeplabcut,train_network(config_path, shuffle=1, displayiters=1, sasveiters=1000)

I got the error:

Also trying to train my network using this pretrained resnet 101 on mpii. I was wonder how exactly you were able to do that. After using curl to download:

mpii-single-resnet-101.data-00000-of-00001
mpii-single-resnet-101.index
mpii-single-resnet-101.meta

I then moved all three of these files to:
C:\Users\phcao\Miniconda3\envs\ecog\Lib\sitepackages\deeplabcut\pose_estimation_tensorflow\models\pretrained

Then, I figured the next step would be to edit:
init_weights

in the pose_cfg.yaml file and assign it to the path of the mpii-single-resnet-101 , specifically:

C:\Users\phcao\Miniconda3\envs\ecog\Lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\mpii-single-resnet-101

When I did this, and called

deeplabcut,train_network(config_path, shuffle=1, displayiters=1, sasveiters=1000)

I got the error:

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta not found in checkpoint
[[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, …, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Can someone please explain what I’m doing wrong?
Can someone please explain what I’m doing wrong?

**Comment by sebo361** [comment]
Hi @phcao101, try to change `net_type: resnet_50` to `net_type: resnet_101` in the pose_cfg.yaml. This should work

**Comment by MMathisLab** [comment]
(also please no not post question here and on the Image Forum... it doesn't make us help you faster, and it just annoys the developers ;) https://forum.image.sc/t/unable-to-use-human-pretrained-network-resnet-101-pre-trained-on-mpii/27483

**Comment by phcao101** [comment]
Thanks so much!

Best,
Paul Huu Cao
UC Berkeley, Class of 2022
Bioengineering, B.S.
paulcao@berkeley.edu

**Comment by phcao101** [comment]
Hi all,

I changed net_type to resnet_101 but now I am getting this error:

ValueError: The passed save_path is not a valid checkpoint:
C:\Users\phcao\AppData\Local\Programs\Python\Python36\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\mpii-single-resnet-101


Thanks so much for the help!


Paul Huu Cao
UC Berkeley, Class of 2022
Bioengineering, B.S.
paulcao@berkeley.edu

**Comment by MMathisLab** [comment]
Are you sure you changed this to 101?  in the config.yaml file?
 https://github.com/AlexEMG/DeepLabCut/blob/master/examples/openfield-Pranav-2018-10-30/config.yaml#L33

**Comment by phcao101** [comment]
Solved! My path was messed up. Thank you!

Paul Huu Cao
UC Berkeley, Class of 2022
Bioengineering, B.S.
paulcao@berkeley.edu
