### ISSUE TITLE
Analyze_videos only analyses 2% of the video

### ISSUE THREAD

**Issue by caniko** [DeepLabCut/DeepLabCut#357]
**Describe the bug**
When I try to analyse my videos using analyze_videos(), it only analyses 1-2% of the video, and goes on to the next video. It does this for every video.

**To Reproduce**
Analyse .mp4 videos:
```
import glob
import os

video_filepaths = glob.glob(os.path.join(VIDEO_DIR, '**/*.mp4'))
deeplabcut.analyze_videos(path_config_file, video_filepaths, videotype='mp4', save_as_csv=True)
```

**Expected behavior**
Stop at 2%, and skip the rest of the frames

**Desktop**
 - OS: Windows 10
 - DeepLabCut Version 2.0.7.1
 - Browser: Chrome

**Additional context**
Videos were shot with a GoPro

**Screenshots**
![image](https://user-images.githubusercontent.com/29519599/60888980-43cf6d80-a258-11e9-8935-f6e3c5fb5b03.png)

**Comment by AlexEMG** [comment]
Dear @caniko2,

Can you reproduce this with the openCV loader itself? 

```
video='abc.avi'
loadedframes=0

import cv2
cap=cv2.VideoCapture(video)
        
fps = cap.get(5) 
nframes = int(cap.get(7))
size=(int(cap.get(4)),int(cap.get(3)))
        
ny,nx=size
print("Overall # of frames: ", nframes," found with (before cropping) frame dimensions: ", nx,ny)

while(cap.isOpened()):
            ret, frame = cap.read()
                 if ret:
                      frame=cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                      loadedframes+=1
```

And then compare loadedframes and nframes?

**Comment by caniko** [comment]
I am pretty sure that this part of the GetPoseF function is initiated as I do get ret that are False several times:
```
else:
    nframes = counter
    print("Detected frames: ", nframes)
    if batch_ind>0:
        pose = predict.getposeNP(frames, dlc_cfg, sess, inputs, outputs)
        PredicteData[batch_num*batchsize:batch_num*batchsize+batch_ind, :] = pose[:batch_ind,:]
    break
```

**Comment by caniko** [comment]
I don't think it is the same issue, as the latest release of opencv is able to read the file, but only to an extent:
https://stackoverflow.com/questions/22422569/reading-mp4-go-pro-video-using-opencv

**Comment by caniko** [comment]
I tried within a virtual environment, and anaconda environment. Same problem

**Comment by AlexEMG** [comment]
So OpenCV relases your video after 2%.... Perhaps you can open an issue there?

**Comment by caniko** [comment]
The problem was indeed the same as mentioned in the beforementioned article:
https://stackoverflow.com/questions/22422569/reading-mp4-go-pro-video-using-opencv

The simplest solution is converting the gopro .mp4 files to .avi files using VLC. The issue is the proprietary H264 encoder used by GoPro cameras. It isn't supported by OpenCV.
