### ISSUE TITLE
question about extract_outlier_frames and refine_labels

### ISSUE THREAD

**Issue by davidSafeloc** [DeepLabCut/DeepLabCut#359]
**Your Operating system and DeepLabCut version**

Windows 10 with an Anaconda Env, & DeepLabCut2.05.

**Describe the problem**

After a first run of the training algorithm I wanted to extract new frames to reduced the testing error so I went through all the process of extracting outliers and refining labels. However, when i finished and merged the datasets and realised that the frames had different resolutions.

Initially, i cropped the videos when i extracted the labels for the first time, but apparently when i do this with extract outliers the frames cannot be cropped and it generates images with the original resolution. I was looking at the help of extract_outliers and couldn't find any option to crop.

Will the algorithm work if i train the algorithm with labelled images with two different resolutions? If not (most probably) what can i do?

Best,

David

**Comment by MMathisLab** [comment]
Different resolutions are fine
