### ISSUE TITLE
 Cannot find installation of real FFmpeg (scikit-video installation)

### ISSUE THREAD

**Issue by bill-connelly** [DeepLabCut/DeepLabCut#36]
My understanding is that FFmpeg was installed during DLC installation, so I'm not sure what to do about this.  Any ideas appreciated

EDIT: I was able to manually install FFMPEG, and set the PATH variables to this. But it seems like this isn't the ideal approach.

(DLCdependencies) C:\Users\wmkc\Documents\DeepLabCut\Analysis-tools>python MakingLabeledVideo_fast.py
Starting  ../videos/ ['mouse_reaching_crop.avi']
Error: %s Cannot find installation of real FFmpeg (which comes with ffprobe).
Loading  mouse_reaching_crop.avi and data.
The video was not analyzed with this scorer: DeepCut_resnet50_reachingJan30shuffle1_500
Other scorers were found, however: ['mouse_reaching_cropDeepCut_resnet50_reachingJan30shuffle1_37500.h5']
Creating labeled video for: mouse_reaching_cropDeepCut_resnet50_reachingJan30shuffle1_37500.h5  instead.
Error: %s Cannot find installation of real FFmpeg (which comes with ffprobe).
Duration of video [s]:  325.03333333333336 , recorded with  30 fps!
Overall # of frames:  9751 with cropped frame dimensions:  0 0
Generating frames
  0%|                                                                                                | 0/9751 [00:00<?, ?it/s]Error: %s 'VideoProcessorSK' object has no attribute 'vid'

Traceback (most recent call last):
  File "MakingLabeledVideo_fast.py", line 110, in <module>
    Dataframe = pd.read_hdf(dataname)
  File "C:\Users\wmkc\AppData\Local\Continuum\anaconda3\envs\DLCdependencies\lib\site-packages\pandas\io\pytables.py", line 371, in read_hdf
    'File %s does not exist' % path_or_buf)
FileNotFoundError: File mouse_reaching_cropDeepCut_resnet50_reachingJan30shuffle1_500.h5 does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MakingLabeledVideo_fast.py", line 125, in <module>
    CreateVideo(clip,Dataframe)
  File "MakingLabeledVideo_fast.py", line 88, in CreateVideo
    clip.save_frame(frame)
  File "C:\Users\wmkc\Documents\DeepLabCut\Analysis-tools\VideoProcessor.py", line 137, in save_frame
    self.svid.writeFrame(frame)
AttributeError: 'VideoProcessorSK' object has no attribute 'svid'

**Comment by AlexEMG** [comment]
Based on your edit, I suspect that you resolved this? (*EDIT: I was able to manually install FFMPEG, and set the PATH variables to this. But it seems like this isn't the ideal approach.*)

Why do you think this is not ideal?

**Comment by bill-connelly** [comment]
Why do I think that isn't ideal? Because python reports that FFMPEG is installed when you install DLC. Having done some more research, I *think* it's installed when you install the scikit dependency: You definitely get a message about FFMPEG being downloaded and installed. I suppose this means that it isn't really your problem, but it still might be worth making a note of this, and if anyone else has this problem put it in the docs.

**Comment by AlexEMG** [comment]
Fair enough - the path to ffmpeg can be set as described here: http://www.scikit-video.org/stable/faq.html?highlight=ffmpeg

**Comment by mschart** [comment]
I had exactly the same error after installing DLC via Docker. Still trying to figure out where to rectify which path. My work-around was to go out of the Docker container (in which all steps up to MakingLabeledVideo.py worked well - so I didn't have to install cuda ect, which is great) start a normal terminal and run python3 MakingLabeledVideo_fast.py there (after conda install -c conda-forge sk-video, having python 3 via anaconda).
