### ISSUE TITLE
[question] filterpredictions and outlier extraction in Colab?

### ISSUE THREAD

**Issue by marcpisansky** [DeepLabCut/DeepLabCut#361]
I'm using Colab to refine my training set and it doesn't appear that either deeplabcut.extract_outlier_frames or deeplabcut.filterpredictions are working (see image below). Are these functions supported by the Google Colab environment? Any advice would be tremendously helpful!! 
![Capture](https://user-images.githubusercontent.com/52841226/61187789-94b9da00-a63b-11e9-92dd-bb28929c6043.JPG)

**Comment by MMathisLab** [comment]
They are not supported in Colab: 

From the notebook:
```
import os
os.environ["DLClight"]="True"
os.environ["Colab"]="True"

import deeplabcut
```
output:
```

Project loaded in colab-mode. Apparently Colab has trouble loading statsmodels, so the smoothing & outlier frame extraction is disabled. Sorry!
DLC loaded in light mode; you cannot use the labeling GUI!
```

**Comment by AlexEMG** [comment]
Note that once the videos where analyzed, the frame outlier extraction does not require the GPU (only the inference). Thus, you can do the frame extraction on your laptop... 

The problem is that in our experience statsmodels is buggy on Colab. (this should be fixed at some point)
