### ISSUE TITLE
Extract outlier frames finds a lo of outlier frames but chooses none!

### ISSUE THREAD

**Issue by Yaraat92** [DeepLabCut/DeepLabCut#363]
**Your Operating system and DeepLabCut version**
Windows 10, with an Anaconda Env, & DeepLabCut 2.0.7.
Browser: chrome

**Describe the problem**
After analyzing a new video using the trained network, I wanted to do some refinement by extracting outlier frames and re-training the network. However, when I run the function deeplabcut.extract_outlier_frames() on that same video it finds lots of outlier frames but does not extract any! Any help?

![issue dlc](https://user-images.githubusercontent.com/52376512/61372389-a6032080-a89f-11e9-8af4-8ee6057a94b5.png)

**Comment by MMathisLab** [comment]
Because it says “ please implement this method yourself!” 

You misspelled kmeans

**Comment by AlexEMG** [comment]
If you upgrade to the latest version, then the error message would also be a bit more informative (it suggests what methods exist). https://github.com/AlexEMG/DeepLabCut/blob/a09bb5296428b161fd53900f45107523ea6452a7/deeplabcut/refine_training_dataset/outlier_frames.py#L346
