### ISSUE TITLE
Error when using "import deeplabcut" (CentOS)

### ISSUE THREAD

**Issue by phcao101** [DeepLabCut/DeepLabCut#365]
**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: CentOS Linux release 7.6.1810 through PuTTY

DeepLabCut Version: trouble with import deeplabcut so cannot run "deeplabcut.__version__"

**Describe the problem**

When I run:

import deeplabcut

and received this error now:
```

Traceback (most recent call last):
File "", line 1, in 
File "/home/knight/cmerrick/.conda/envs/ecog/lib/python3.6/site-packages/deeplabcut/init.py", line 29, in 
from deeplabcut import generate_training_dataset
File "/home/knight/cmerrick/.conda/envs/ecog/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/init.py", line 18, in 
from deeplabcut.generate_training_dataset.auxfun_drag_label import *
File "/home/knight/cmerrick/.conda/envs/ecog/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/auxfun_drag_label.py", line 19, in 
import wx
File "/home/knight/cmerrick/.local/lib/python3.6/site-packages/wx/init.py", line 17, in 
from wx.core import *
File "/home/knight/cmerrick/.local/lib/python3.6/site-packages/wx/core.py", line 12, in 
from ._core import *
ImportError: libjpeg.so.8: cannot open shared object file: No such file or directory

```
I had read online that a solution to this would be to run:

sudo apt-get install libjpeg-turbo8

However, I'm using the secure shell PuTTY, and "sudo" is disabled for me so I can't run that command. Do you have any solution to that? Thanks so much once again!

**How to Reproduce the problem**
I'm not quite sure how one might reproduce this problem because I had no trouble using deeplabcut on my laptop, but after trying to transfer the network onto a cluster of computers remotely using PuTTY I'm suddenly getting this error.

Any advice would be appreciated!

**Comment by AlexEMG** [comment]
Perhaps try 

```export DLClight=True```

this will suppress the GUI. If you can then import DLC, the problem is with the installation of wxpython...

**Comment by phcao101** [comment]
I tried that, and then ran

import deeplabcut

again. Now, I get this readout:


>>> import deeplabcut
DLC loaded in light mode; you cannot use the relabeling GUI!
Illegal instruction

and then I just exit out of python.

**Comment by MMathisLab** [comment]
We don't have any expertise with CentOS via PuTTY, and this seems to be specific to this use case....

**Comment by tbenst** [comment]
I ran into this issue as well. The problem is that WxPython looks for a specific version of the original libjpeg (version 8). This can be downloaded [here](https://www.ijg.org/files/jpegsrc.v8d.tar.gz). libjpeg-turbo may also work, but needs to be compiled with `"-DWITH_JPEG8=1"` for partial ABI compatability. See [here](https://github.com/libjpeg-turbo/libjpeg-turbo#libjpeg-v7-and-v8-apiabi-emulation) for more details.
