### ISSUE TITLE
installation problem [incorrectly launching conda envs]

### ISSUE THREAD

**Issue by anastasiya-larkina** [DeepLabCut/DeepLabCut#367]
Hello!
I can't solve the problem.
I did all steps in that manual [https://github.com/AlexEMG/DeepLabCut/blob/master/docs/installation.md]   and that https://github.com/AlexEMG/DeepLabCut/blob/master/conda-environments/README.md .  After installation  I'm trying to import deeplabcut in the cmd and this error appears.
`(jane) C:\Users\Administrator>python
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import deeplabcut
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\jane\lib\site-packages\deeplabcut\__init__.py", line 29, in <module>
    from deeplabcut import generate_training_dataset
  File "C:\ProgramData\Anaconda3\envs\jane\lib\site-packages\deeplabcut\generate_training_dataset\__init__.py", line 18, in <module>
    from deeplabcut.generate_training_dataset.auxfun_drag_label import *
  File "C:\ProgramData\Anaconda3\envs\jane\lib\site-packages\deeplabcut\generate_training_dataset\auxfun_drag_label.py", line 19, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'
>>> import deeplabcut
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\jane\lib\site-packages\deeplabcut\__init__.py", line 29, in <module>
    from deeplabcut import generate_training_dataset
  File "C:\ProgramData\Anaconda3\envs\jane\lib\site-packages\deeplabcut\generate_training_dataset\__init__.py", line 18, in <module>
    from deeplabcut.generate_training_dataset.auxfun_drag_label import *
  File "C:\ProgramData\Anaconda3\envs\jane\lib\site-packages\deeplabcut\generate_training_dataset\auxfun_drag_label.py", line 19, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'
>>> import tensorflow
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
2019-07-18 18:34:11.410519: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr`

Can you help me with that?
Thank you!

**Comment by bkacsoh** [comment]
Hello,

I am having the same issue, running the software on a mac. I am new to programming but would very much like to use this software.

Thanks!





Last login: Thu Jul 18 16:20:08 on ttys000
(base) MacBook-Pro-203:~ user$ cd /Users/user/Desktop/Berger\ Lab/bioinformatics/DeepLabCut 
(base) MacBook-Pro-203:DeepLabCut user$ ipython
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import deeplabcut                                                       
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-cfa4f159dfc5> in <module>
----> 1 import deeplabcut

~/Desktop/Berger Lab/bioinformatics/DeepLabCut/deeplabcut/__init__.py in <module>
     27     else:
     28         mpl.use('Agg')
---> 29     from deeplabcut import generate_training_dataset
     30     from deeplabcut import refine_training_dataset
     31     from deeplabcut.generate_training_dataset import label_frames, dropannotationfileentriesduetodeletedimages, comparevideolistsanddatafolders

~/Desktop/Berger Lab/bioinformatics/DeepLabCut/deeplabcut/generate_training_dataset/__init__.py in <module>
     16     pass
     17 else:
---> 18     from deeplabcut.generate_training_dataset.auxfun_drag_label import *
     19     from deeplabcut.generate_training_dataset.labeling_toolbox import *
     20     from deeplabcut.generate_training_dataset.multiple_individual_labeling_toolbox import *

~/Desktop/Berger Lab/bioinformatics/DeepLabCut/deeplabcut/generate_training_dataset/auxfun_drag_label.py in <module>
     17 
     18 import numpy as np
---> 19 import wx
     20 
     21 class DraggablePoint:

ModuleNotFoundError: No module named 'wx'

In [2]:

**Comment by MMathisLab** [comment]
Are you using the supplied Anaconda env?

**Comment by anastasiya-larkina** [comment]
> Are you using the supplied Anaconda env?

Yes.

**Comment by MMathisLab** [comment]
Please fill out the issue template completely. Which env, as yours is called “Jane” I have no idea what env, please link, what computer OS, etc.

**Comment by anastasiya-larkina** [comment]
> Please fill out the issue template completely. Which env, as yours is called “Jane” I have no idea what env, please link, what computer OS, etc.

Win 10 Enterprise LTSC, 64-bit, Radeon(TM) RX 460 Graphics

There is full code which I did following steps in the manual I send before.
[error_deeplabcut.txt](https://github.com/AlexEMG/DeepLabCut/files/3410857/error_deeplabcut.txt)
 Thank you very much!

**Comment by bkacsoh** [comment]
I also used the supplied Anaconda. I am using MacOS 10.13.4 (17E199)
3.1 GHz Intel Core i7
Radeon Pro 560 4096 MB
Intel HD Graphics 630 1536 MB

**Comment by MMathisLab** [comment]
@anastasiya-larkina - so, you did something strange here; you indeed created the windowsCPU, but then you never launched it with:

`conda activate dlc-windowsCPU`

See here, from your file, it tells you what you need to do to open the env:
```

Successfully installed PyWavelets-1.0.3 chardet-3.0.4 click-7.0 cloudpickle-1.2.1 cycler-0.10.0 deeplabcut-2.0.7.2 easydict-1.9 idna-2.8 imageio-2.3.0 intel-openmp-2019.0 ipython-6.0.0 kiwisolver-1.1.0 matplotlib-3.0.3 moviepy-0.2.3.5 networkx-2.3 numpy-1.14.5 opencv-python-3.4.5.20 pandas-0.21.0 patsy-0.5.1 pillow-6.1.0 prompt-toolkit-1.0.16 pyparsing-2.4.0 python-dateutil-2.7.3 pytz-2019.1 pyyaml-5.1.1 requests-2.22.0 ruamel.yaml-0.15.0 scikit-image-0.14.3 scikit-learn-0.19.2 simplegeneric-0.8.1 six-1.11.0 statsmodels-0.9.0 tqdm-4.32.2 urllib3-1.25.3 wheel-0.31.1

#
# To activate this environment, use
#
#     $ conda activate dlc-windowsCPU
#
# To deactivate an active environment, use
#
#     $ conda deactivate


(base) C:\Users\Administrator>conda install nb_conda
```

Then you ran `conda install nb_conda `outside of the env, then created a new conda env, named Jane, that is incorrectly installed; i.e. you didn't install wxPython or tensorflow, but this is irrelevant, you JUST need to run:

`conda activate dlc-windowsCPU`

Then my guess is everything will work. 
Also, once you activate it THEN you run `conda install nb_conda`

**Comment by MMathisLab** [comment]
@bkacsoh seems you also did not activate the correct environment, and you have path errors:

source activate nameoftheenvironment

```
(base) MacBook-Pro-203:~ user$ cd /Users/user/Desktop/Berger\ Lab/bioinformatics/DeepLabCut
(base) MacBook-Pro-203:DeepLabCut user$ ipython
```
