### ISSUE TITLE
Confused about resuming training from a snapshot (Colab)

### ISSUE THREAD

**Issue by nicthib** [DeepLabCut/DeepLabCut#368]
I'm using DLC in a colab environment, and when I pause training and attempt to resume it, it seems to start over. I'm editing the pose_cfg.yaml file to point to the snapshot I want to resume from (via init_weights), but the loss function and speed seems identical to when I first started training. Also, my old snapshot files are being overwritten.

Any ideas? Am I missing a field update in pose_cfg.yaml besides init_weights?

CUDA v10.0.130
DLC version: 1.14.0
GPU

**Comment by MMathisLab** [comment]
It indeed starts counting at 0 again; if you don't move the old snapshots, it will overwrite them if you have not created a new merge. If you are loading previous snapshot, then the new snapshot are 0+previous_snapshot.

**Comment by nicthib** [comment]
Ok, so it must continue from the snapshot I'm indicating. One worry I have is that when resuming, the message "Starting with standard pose-dataset loader" pops up, which makes me worry that it is indeed starting from the resnet model.

**Comment by sebo361** [comment]
Hi @nicthib, there is the "standard pose-dataset loader" and the "deterministic pose-dataset loader", which trains the model deterministically. Both start with your indicated resnet model, so you dont have to worry about that.

**Comment by nicthib** [comment]
Awesome, thanks @MMathisLab and @sebo313 for the clarification!
