### ISSUE TITLE
Impossible x and y positions

### ISSUE THREAD

**Issue by bouracha** [DeepLabCut/DeepLabCut#370]
I'm using ubuntu 18.04 and deeplabcut version 2.0.6.3

When producing csv from analysed videos I occasionally get impossible values of the position ie + or - 10e8. These impossible values seem to be accompanied with a likelihood of 1.0 for that body part. Are these the default values when a bodypart can't be found or is there some issue in my implementation?

Not all the videos I analyze have this issue but many do. Here is an example, the 18th value is impossible.

![Screenshot from 2019-07-21 13-16-04](https://user-images.githubusercontent.com/17855974/61591090-c4c42880-abb9-11e9-8786-38e56b3502d3.png)

**Comment by AlexEMG** [comment]
This is indeed strange behavior. Perhaps there is an overflow in some computation? -- however this is neither close to 2^16 or 2^32. Can you reproduce this with different TF versions? Do you get the same numbers when you run it multiple times?

Please report back, I want to dig into this (but have never seen this behavior myself)

**Comment by bouracha** [comment]
I think the problem must be related to the issue that I am now unable to retrain (issue #62) due LossTensor is inf or nan. So while train_network is failing due to this it look like analyse_videos is just producing (reasonable) results with some nans. As I have mentioned in the other thread, reinstalling tensorflow has not solved the problem.

**Comment by MMathisLab** [comment]
is this resolved now, based on the discussion on #62?

**Comment by AlexEMG** [comment]
So, I guess the problem is your networks has some overflows...
