### ISSUE TITLE
create_labeled_video creates a video shorter than the original one

### ISSUE THREAD

**Issue by luciedescamps** [DeepLabCut/DeepLabCut#372]
**Describe the bug**
When running create_labeled_video, the labeled video has a shorter duration than the original video

**To Reproduce**
1. create_labeled_video
2. Click on the properties of the original and of the labeled video 
3. In the details tab scroll down to length: they are different even though the frame rate is the same

**Expected behavior**
Creation of labeled video similar to the original video in duration.

**Screenshots**
![dlc_create_labeled_video_bug](https://user-images.githubusercontent.com/41382274/61651764-e0612900-acb6-11e9-826a-eb20af1eb569.PNG)

**Desktop (please complete the following information about your system):**
 - Windows 10
 - DeepLabCut Version: 2.0.7.2

Thank you for any help that can be given

**Comment by AlexEMG** [comment]
I wonder if this is just in the metadata -- can you open the videos and check if the number of frames are the same? (which should be the case).

You can open the videos like this:
```
video='abc.avi'
loadedframes=0

import cv2
cap=cv2.VideoCapture(video)
        
fps = cap.get(5) 
nframes = int(cap.get(7))
size=(int(cap.get(4)),int(cap.get(3)))
        
ny,nx=size
print("Overall # of frames: ", nframes," found with (before cropping) frame dimensions: ", nx,ny)
```

**Comment by luciedescamps** [comment]
Hi! Thanks for the help, indeed the number of frames is the same - so I guess that the tracking data has been correctly extracted for each frame when analyzing the video. When I saw that the duration was different I was afraid it had skipped some frames and didn't label them.

**Comment by AlexEMG** [comment]
Great, so this is fine then.
