### ISSUE TITLE
How to calibrate more than two cameras?

### ISSUE THREAD

**Issue by luigimvargas** [DeepLabCut/DeepLabCut#373]
Hello,

I am wondering if the current 3D reconstruction capability of DLC allows it to combine coordinates from more than two cameras. I saw this in the preprint, but did not see it in the documentation.

Basically, I want to use three cameras that are 60 degrees apart and surrounding the video area. Roughly, it would look like this:
$              Cam 1
$          /            \
$        /   Mouse   \
$     /                      \
$   Cam 2 ________ Cam 3

I imagine the only way to get all three cameras looking at the checkerboard for calibration is to have them all slightly raised above it, looking down at a small angle. Will that work with the current deeplabcut functions? 

Thanks!

**Comment by luigimvargas** [comment]
![sketch (3)](https://user-images.githubusercontent.com/46249584/61662505-8f443b80-ac9c-11e9-994a-658b40ba90a9.png)

**Comment by AlexEMG** [comment]
In the preprint we used the [easyWand](http://biomech.web.unc.edu/wand-calibration-tools) toolbox to calculate the required sparse bundle adjustment calibration coefficients for reconstruction and applied these to the DeepLabCut output files (per camera)

Theriault, D. H. et al. A protocol and calibration method for accurate multi-camera field videography. J. Exp. Biol. 217, 1843–1848 (2014).

The DLC code contains OpenCV code for triangulation and currently only supports pairs of cameras. But you can of course define 3 pairs with your 3 cameras... Or for now use different methods like EasyWand, or https://github.com/lambdaloop/anipose
