### ISSUE TITLE
Train Starting from Checkpoint resets to zero [question]

### ISSUE THREAD

**Issue by phcao101** [DeepLabCut/DeepLabCut#376]
**Your Operating system and DeepLabCut version**
Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: Windows 7
DeepLabCut Version 2.0.7.2
Browser: Chrome

**Describe the problem** 
I've been trying to restart the training at a specific checkpoint but when I begin training the network, it just starts back from 0.

I have followed instructions in regards to changing init_weights.

init_weights: C:\Users\Alit\overhead3-Paul_Cao-2019-07-25\dlc-models\iteration-0\overhead3Jul25-trainset95shuffle1\train\snapshot-750

Is there anything else I need to do in order to retrain starting at a checkpoint?

**Screenshots**
![Capture](https://user-images.githubusercontent.com/52678719/61976014-83f45700-af9f-11e9-9d1c-462126caff1c.PNG)
![Capture2](https://user-images.githubusercontent.com/52678719/61976021-88207480-af9f-11e9-8acd-f534ffec08c8.PNG)

[pose_cfg.txt](https://github.com/AlexEMG/DeepLabCut/files/3437028/pose_cfg.txt)

**Comment by MMathisLab** [comment]
yes, it resets to 0, but if you loaded the weights, it will be using them! (it also states this in our user-guide and documentation)

https://camo.githubusercontent.com/663a60c8ec32c35be321b4c827fe415a839a4e05/68747470733a2f2f737461746963312e73717561726573706163652e636f6d2f7374617469632f3537663664353163396637343536366635356563663237312f742f3563343065666265626261323233373330383832633264652f313534373735393635363332342f426f78322d30312e706e673f666f726d61743d3130303077

also, if you are using 101, you should set `intermediate_supervision` to True

**Comment by phcao101** [comment]
Thanks so much!!

**Comment by MMathisLab** [comment]
no problem. if you like the package, would consider giving us a star :)

**Comment by phcao101** [comment]
One last question: If doing this enables the network to retrain from a loaded weight, why does the loss still start off so high?
