### ISSUE TITLE
Issue with PyTables installation 

### ISSUE THREAD

**Issue by Charly77220** [DeepLabCut/DeepLabCut#377]
**Your Operating system and DeepLabCut version :**

Windows 10, Anaconda env and Deeplabcut v2.0.7.2
Browser : Chrome

**Describe your problem :**

After labeling frames, I try to save it but I got this message : 
[DLC Troubleshooting.pdf](https://github.com/AlexEMG/DeepLabCut/files/3443758/DLC.Troubleshooting.pdf)

I have a csv file but not a h5 one. I tried to update numpy and PyTables but the error is still the same.

Here is a screen shot of my config : 
[Configpath.pdf](https://github.com/AlexEMG/DeepLabCut/files/3443778/Configpath.pdf)

Do you know where it could come from ?

Thanks,
Charly

**Comment by MMathisLab** [comment]
can you confirm which conda file: https://github.com/AlexEMG/DeepLabCut/tree/master/conda-environments

**Comment by Charly77220** [comment]
I use the dlc-Windows GPU

**Comment by MMathisLab** [comment]
are you running the terminal as an administrator? it will not let you create the file without running as an admin. 

Also, you can try this (from here: https://github.com/AlexEMG/DeepLabCut/wiki/Troubleshooting-Tips)

Windows: one user reports an issue with PyTables (i.e. here) pd.read_hdf(path). The solution was to upgrade tables from 3.4.4 to 3.4.5.dev using: pip install git+https://github.com/PyTables/PyTables

**Comment by Charly77220** [comment]
Yes I am running the terminal as an administrator.

Thanks for your tip, I tried it, but a long error message appears running the pip install. Maybe because I already have a more recent of tables, 3.5.2 ...

**Comment by MMathisLab** [comment]
yeah the most recent version does not work; it needs to be 3.4.4

**Comment by Charly77220** [comment]
I tried to run this pip install but it install the 3.6.0 version ... And I can't find how I can downgrade my version

**Comment by MMathisLab** [comment]
``pip install pytables==3.4.4`` or please just use the original conda env. you can delete the one you created and re-create.

**Comment by Charly77220** [comment]
It works creating a new env. Thanks for your advice

**Comment by mariadorofeikova** [comment]
Hi! I get an error when I try to create a training dataset, which did not happen last week. 

> Traceback (most recent call last):
>   File "C:\ProgramData\anaconda3\lib\site-packages\deeplabcut\gui\tabs\create_training_dataset.py", line 105, in create_training_dataset
>     deeplabcut.create_training_dataset(
>   File "C:\ProgramData\anaconda3\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 861, in create_training_dataset
>     Data = merge_annotateddatasets(
>   File "C:\ProgramData\anaconda3\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 482, in merge_annotateddatasets
>     data = pd.read_hdf(file_path)
>   File "C:\ProgramData\anaconda3\lib\site-packages\pandas\io\pytables.py", line 437, in read_hdf
>     raise ValueError(
> ValueError: key must be provided when HDF5 file contains multiple datasets.
> 


After trying to install pytables 3.4.4:

> > pip install pytables==3.4.4
> ERROR: Could not find a version that satisfies the requirement pytables==3.4.4 (from versions: none)
> ERROR: No matching distribution found for pytables==3.4.4

Any ideas?

**Comment by MMathisLab** [comment]
hi @mariadorofeikova can you give us more context; did you update DLC // tables for a reason, etc?

**Comment by mariadorofeikova** [comment]
Hi! Full story: 
I installed the latest version of DLC and, when trying to do the labeling, I could only drop one frame into Napari. So I tried to install different versions of pytable, panda, etc, according to the errors. Nothing worked, so I did the labeling on another PC with an older version of DLC.
Now I am trying to reinstall DeepLabCut completely anew because it was not working after all my troubleshooting by using "pip uninstall deeplabcut", " conda env remove --name DEEPLABCUT" and then "git clone https://github.com/DeepLabCut/DeepLabCut.git". Here is the error that I get when I try to "conda env create -f DEEPLABCUT.yaml":

> Downloading and Extracting Packages
> 
> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: / Enabling nb_conda_kernels...
> CONDA_PREFIX: C:\ProgramData\anaconda3\envs\DEEPLABCUT
> Status: enabled
> 
> | Config option `kernel_spec_manager_class` not recognized by `EnableNBExtensionApp`.
> Enabling notebook extension nb_conda/main...
>       - Validating: ok
> Enabling tree extension nb_conda/tree...
>       - Validating: ok
> Config option `kernel_spec_manager_class` not recognized by `EnableServerExtensionApp`.
> Enabling: nb_conda
> - Writing config: C:\ProgramData\anaconda3\envs\DEEPLABCUT\etc\jupyter
>     - Validating...
>       nb_conda 2.2.1 ok
> 
> done
> Installing pip dependencies: / Ran pip subprocess with arguments:
> ['C:\\ProgramData\\anaconda3\\envs\\DEEPLABCUT\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\Users\\mdorofey\\DeepLabCut\\conda-environments\\condaenv.y_y3he0h.requirements.txt', '--exists-action=b']
> Pip subprocess output:
> 
> Pip subprocess error:
> WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))': /simple/deeplabcut/
> WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))': /simple/deeplabcut/
> WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))': /simple/deeplabcut/
> WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))': /simple/deeplabcut/
> WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))': /simple/deeplabcut/
> ERROR: Could not find a version that satisfies the requirement deeplabcut[gui,tf] (from versions: none)
> ERROR: No matching distribution found for deeplabcut[gui,tf]
> 
> failed
> 
> CondaEnvException: Pip failed


After updating conda, still the same problem with pip persists:

> Installing pip dependencies: / Ran pip subprocess with arguments:
> ['C:\\ProgramData\\anaconda3\\envs\\DEEPLABCUT\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\Users\\mdorofey\\DeepLabCut\\conda-environments\\condaenv.mcd9y41f.requirements.txt', '--exists-action=b']
> Pip subprocess output:
> 
> Pip subprocess error:
> WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))': /simple/deeplabcut/
> WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))': /simple/deeplabcut/
> WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))': /simple/deeplabcut/
> WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))': /simple/deeplabcut/
> WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))': /simple/deeplabcut/
> ERROR: Could not find a version that satisfies the requirement deeplabcut[gui,tf] (from versions: none)
> ERROR: No matching distribution found for deeplabcut[gui,tf]
> 
> failed
> 
> CondaEnvException: Pip failed

After I set up proxy, I tried to install DLC again... and it worked! But when trying to train the network, I ran into another error:

> ImportError: cannot import name 'dtensor_api' from 'keras.dtensor' (C:\ProgramData\anaconda3\lib\site-packages\keras\dtensor\__init__.py)

So I did "pip install keras==2"
And now I'm waiting for  Downloading tensorflow_intel-2.12.0-cp310-cp310-win_amd64.whl (272.8 MB)...

**Comment by mariadorofeikova** [comment]
After getting "ImportError: cannot import name 'dtensor_api' from 'keras.dtensor' (C:\ProgramData\anaconda3\lib\site-packages\keras\dtensor\__init__.py)" error, I "pip install keras==2.6".
-->

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> tensorflow 2.10.0 requires keras<2.11,>=2.10.0, but you have keras 2.6.0 which is incompatible.
> tensorflow 2.10.0 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.23.3 which is incompatible.
> -->
> pip install tensorflow==2.8 to get rid of all the incompatibility
> -->
> "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> tf-nightly-intel 2.14.0.dev20230622 requires tf-estimator-nightly~=2.14.0.dev, but you have tf-estimator-nightly 2.8.0.dev2021122109 which is incompatible.
> tf-nightly-intel 2.14.0.dev20230622 requires typing-extensions<4.6.0,>=3.6.6, but you have typing-extensions 4.6.3 which is incompatible."
> -->
> pip install tf-estimator-nightly==2.14.dev2023062508
> pip install typing-extensions==4.2.0
> pip install tf-estimator-nightly==2.8.0.dev2021122109
> pip install tf-estimator-nightly==2.14.0.dev2023052008

Basically, tensorflow and tf-estimator-nightly are not compatible...
So, pip install tensorflow --upgrade, then pip install tf-estimator-nightly==2.14.0.dev2023052008
AttributeError: module 'tensorflow' has no attribute 'compat'
-->
conda install tensorflow-estimator==2.1.0
conda remove tensorflow
conda install tensorflow-gpu=2.1
-still error-
pip uninstall keras
pip install tensorflow
Again, "AttributeError: module 'tensorflow' has no attribute 'compat'"
So I tried pip install tensorflow==2.11

> Installing collected packages: keras, tensorboard, tensorflow
>   Attempting uninstall: keras
>     Found existing installation: keras 2.11.0
>     Uninstalling keras-2.11.0:
>       Successfully uninstalled keras-2.11.0
>   Attempting uninstall: tensorboard
>     Found existing installation: tensorboard 2.11.2
>     Uninstalling tensorboard-2.11.2:
>       Successfully uninstalled tensorboard-2.11.2
>   Attempting uninstall: tensorflow
>     Found existing installation: tensorflow 2.11.0
>     Uninstalling tensorflow-2.11.0:
>       Successfully uninstalled tensorflow-2.11.0
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> tensorflow-intel 2.11.0 requires keras<2.12,>=2.11.0, but you have keras 2.8.0 which is incompatible.
> tensorflow-intel 2.11.0 requires tensorboard<2.12,>=2.11, but you have tensorboard 2.8.0 which is incompatible.
> Successfully installed keras-2.8.0 tensorboard-2.8.0 tensorflow-2.8.0
> (base) PS C:\Windows\system32> python -m deeplabcut
> Loading DLC 2.3.5...
> 

ImportError: DLL load failed while importing _pywrap_dtensor_device: The specified procedure could not be found.
So then I did as written in https://www.tensorflow.org/install/pip#windows-wsl2

conda install -c conda-forge cudatoolkit=11.8.0
pip install nvidia-cudnn-cu11
pip install tensorflow==2.12.*

And still **AttributeError: module 'tensorflow' has no attribute 'compat'**

Hope you can help!!
