### ISSUE TITLE
Incomplete line in example notebook

### ISSUE THREAD

**Issue by ambareeshsrja16** [DeepLabCut/DeepLabCut#379]
Not a bug/ feature request per se. Was going through: https://github.com/AlexEMG/DeepLabCut/blob/master/examples/Demo_labeledexample_MouseReaching.ipynb
Markup cell above Cell number 11 seems to be incomplete -  _"Various parameters can be set with regard to the colormap and the dotsize. The parameters of the "_

Pointing out for completeness sake. Great repo and toolbox! Thank you!

**Comment by MMathisLab** [comment]
i'll update the notebook in the next update, thanks.
