### ISSUE TITLE
Unable to save label corrections in the "Manually correct labels" part

### ISSUE THREAD

**Issue by ambareeshsrja16** [DeepLabCut/DeepLabCut#380]
OS: Windows 10
DeepLabCut Version:  '2.0.7.2' 
Browser: Chrome

**Problem**

Unable to save the labels after manually correcting them in"Manually correct labels" part as given in the demo notebook. (Demo_labeledexample_MouseReaching)

**Steps to reproduce the behavior:**

1. Go to Demo_labeledexample_MouseReaching notebook
2. Run cell under "## Manually correct labels":
```
 %gui wx
deeplabcut.refine_labels(path_config_file)
```
3. GUI pops up, Click on load labels, and load the correct .h5 file
4. Check labels, modify/delete them. 
5. Click on save - No response (later on checking, no change is saved)
6. Close the GUI window, repeat until steps 5 again. 
7. Close the GUI window, and notice that JNotebook cell is still running (* mark next to it) Interrupting the kernel doesn't seem to stop the widget either. 
8. Has to restart the kernel.

Attaching screen recording:
https://drive.google.com/open?id=12g6HvqkA9OZESVElsP_jYqKNJnb3IOF3
The part where the pointer is hovering the menu buttons (like save, zoom, etc, I'm left clicking but it is not responding)

Any workarounds, since relabelling the part is a major step?

Thank you!

**Comment by MMathisLab** [comment]
seems you are not inside the anaconda env (see top right corner) says "python 3" not the environment name. 

First, be sure you are in the Anaconda Python! Go to ``"Kernel > Change Kernel > and selection Python [conda enc: DLC2]`` (or whatever you call your conda environment)! 
From: https://github.com/AlexEMG/DeepLabCut/blob/e0bc796bd118057ea33b3793ae27d0686afddb5c/examples/Demo_labeledexample_MouseReaching.ipynb

If this is not possible first run: conda install nb_conda then restart the terminal, and then in Jupyter now you can change the kernel to specific environments in Jupyter
From: 
https://github.com/AlexEMG/DeepLabCut/wiki/Troubleshooting-Tips



ALSO, you didn't click "Save" --> you need to drag the GUI to be wider, then you will see the save button.

(**Note,** these:
![image](https://user-images.githubusercontent.com/28102185/62167812-08254200-b2f2-11e9-994b-5406a4744b4e.png)
 are just for matplotlib, they don't work, you need to hit "SAVE")

This is what the GUI should look like when you adjust the size:
https://github.com/AlexEMG/DeepLabCut/blob/master/docs/UseOverviewGuide.md#label-frames

**Comment by MMathisLab** [comment]
If this is not possible first run: ``conda install nb_conda`` then restart the terminal, and then in Jupyter now you can change the kernel to specific environments in Jupyter

**Comment by ambareeshsrja16** [comment]
I had activated the environment from my anaconda prompt and opened a Jupyter Notebook from the prompt, and then navigated to the right path. I am not able to change the kernel, following steps you suggested, but I'm guessing it's working on the correct kernel since I am able to run everything. 

Also dragging it wide- Save button, should be working, I tried the same on Demo_yourowndata.ipynb labeling part, so I guess, that should work here as well!

Thank you!

**Comment by MMathisLab** [comment]
No problem. 

But, sometimes there can be funny errors/crashes if not in the kernel, although it lets you run. Anyhow, next time you are in your env but before you launch Jupyter, just run “conda install nb_conda” then you’re all set ;)
