### ISSUE TITLE
YAMLLoadWarning [older version]

### ISSUE THREAD

**Issue by jcm2222** [DeepLabCut/DeepLabCut#382]
OS: MacOS 10.14.5, with an Anaconda Env & DeepLabCut2.0
DeepLabCut Version 2.0
Browser - Firefox

I cannot import deeplabcut to my ipython or notebook. I get the following: "YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}"

Whether I type "ipython" in the terminal or navigate to the jupyter notebook, the same error appears. 

Thank you!

**Comment by MMathisLab** [comment]
please update your package.

`pip install deeplabcut==2.0.7.2`
