### ISSUE TITLE
How to export the model?

### ISSUE THREAD

**Issue by JohnCraigPublic** [DeepLabCut/DeepLabCut#383]
I would like to try to "export" the model which has resulted from my training with DLC.  That is, DLC uses Tensorflow so I assume that the result of training is a Tensorflow model.  But where is this model?   I'm not usually a Tensorflow user, so I'm not very knowledgeable there -- I thought that a Tensorflow model would be stored in a *.pb file -- but I don't see that anywhere.  What I would really like to do is to convert the Tensorflow model into an ONNX model - so the inference could be done elsewhere in another software system.   Does anyone know if the model used in DLC is representable in ONNX?   Any tips or pointers to help me on this project?  Thanks!

**Comment by AlexEMG** [comment]
The models are stored as Tensorflow checkpoints called "snapshots" and are stored in` /dlc-models/.... `
Also check out this answer: https://github.com/AlexEMG/DeepLabCut/issues/241

**Comment by IamNaQi** [comment]
@JohnCraigPublic  Hi, did you get ONNX model if yes please guide ?

**Comment by JohnCraigPublic** [comment]
Nope, never figured it out.

Regards,
John J Craig, PhD
www.EponaMind.com  ~  Technology Devoted to the Horse
www.MetronMind.com  ~  Deep Learning Enabled Software for Veterinarians
www.SmartRayVision.com  ~  High-Tech Security Systems
