### ISSUE TITLE
Issue with data output

### ISSUE THREAD

**Issue by nickkaliss** [DeepLabCut/DeepLabCut#384]
**Is your feature request related to a problem? Please describe.**
Hello, my lab has been using DeepLabCut to track mouse movements and then create heatmaps based off of this movement. I noticed that when I plot trajectories, the graphs DLC creates have their maximum y-value at the bottom of the frame and the 0-point for y at the top. Being that our lab has been using the data DLC produces to create heatmaps, we need the y-values of the data to be reversed (i.e., if a mouse is at the top of the frame, we need their positional y-value at that point to be the maximum value rather than 0). Is there anyway to have DLC produce data with y-values which are larger the further up the mouse is in the frame? 

Please let me know if you have any clarifying questions, and thank you in advance for your help.

**Comment by MMathisLab** [comment]
You can customize the plots as you like in this code: 
https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/utils/plotting.py

**Comment by MMathisLab** [comment]
you might also consider looking at this: https://github.com/AlexEMG/DLCutils/blob/master/Demo_loadandanalyzeDLCdata.ipynb

**Comment by AlexEMG** [comment]
The trajectory plots etc. of DLC are correctly oriented with respect to the frame. You can of course invert axes if necessary. If you plot heatmaps with imshow, you can customize them like this: https://stackoverflow.com/questions/8396101/invert-image-displayed-by-imshow-in-matplotlib
