### ISSUE TITLE
create_labeled_video_3d deeplabcut

### ISSUE THREAD

**Issue by Ko-White** [DeepLabCut/DeepLabCut#385]
Having issues with labeling 3d videos. 

error 
In [42]: deeplabcut.create_labeled_video_3d(config_path,['C:/Users/white/DeepLabCut/Test-Shirakawa-2019-08-04-3d/videos/test2_DLC_3D.h5'],start=50,end=250, trailpoints=3)

KeyError                                  Traceback (most recent call last)
<ipython-input-42-219f9a07ce97> in <module>()
----> 1 deeplabcut.create_labeled_video_3d(config_path,['C:/Users/white/DeepLabCut/Test-Shirakawa-2019-08-04-3d/videos/test2_DLC_3D.h5'],start=50,end=250, trailpoints=3)

C:\Users\white\DeepLabCut\deeplabcut\pose_estimation_3d\plotting3D.py in create_labeled_video_3d(config, path, videofolder, start, end, trailpoints, videotype, view, xlim, ylim, zlim, draw_skeleton)
     82     # Read the config file and related variables
     83     cfg_3d = auxiliaryfunctions.read_config(config)
---> 84     cam_names = cfg_3d['camera_names']
     85     pcutoff = cfg_3d['pcutoff']
     86     markerSize = cfg_3d['dotsize']

c:\users\white\anaconda3\envs\dlc-windowscpu\lib\site-packages\ruamel\yaml\comments.py in __getitem__(self, key)
    689         # type: (Any) -> Any
    690         try:
--> 691             return ordereddict.__getitem__(self, key)
    692         except KeyError:
    693             for merged in getattr(self, merge_attrib, []):

KeyError: 'camera_names'

I can't understand KeyError: 'camera_names'  
Can you please help to resolve this??

**Comment by MMathisLab** [comment]
First, please always fill out the template. 

You need to pass the **folder path**, not the h5 file. This is stated in the docs: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/Overviewof3D.md#5-visualize-your-3d-deeplabcut-videos

**Comment by Ko-White** [comment]
Thank you for your response.
What's triangulated folder?  I can't find it.

"Note that the triangulated_file is the newly created file that ends with yourDLC_3D_scorername.h5"

**Comment by MMathisLab** [comment]
The folder it is in: 

deeplabcut.create_labeled_video_3d(config_path,['C:/Users/white/DeepLabCut/Test-Shirakawa-2019-08-04-3d/videos/'],start=50,end=250, trailpoints=3)

**Comment by Ko-White** [comment]
I tried it, but the same error occurs.

**Comment by MMathisLab** [comment]
Then something is wrong with your config path or config file; I cannot help without the full information and template filled out.

**Comment by Ko-White** [comment]
Thank you so much!
I'll try again.

**Comment by MMathisLab** [comment]
Please do not open another issue... you can edit your original post.

**Comment by MMathisLab** [comment]
also, I edited the docs to be more clear, thanks for your feedback: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/Overviewof3D.md

**Comment by Erinlin10** [comment]
Hi all,
   I met the same issue:
   config_path1 is the path of config.yaml for a 2D project
   triangulated_file_folder is where .h5 file has been located.
   When I ran the command: deeplabcut.create_labeled_video_3d(config_path1, triangulated_file_folder, start=50, end=250),
   it reports: KeyError: 'camera_names'

   May I ask how to solve this problem?
