### ISSUE TITLE
python/tuple error [old config.yaml to newer]

### ISSUE THREAD

**Issue by Clyde92** [DeepLabCut/DeepLabCut#386]
**Your Operating system and DeepLabCut version**

OS: Ubuntu 16.04 LTS
DeepLabCut Version: 2.07
Browser: Firefox

**Describe the problem**

I've added a body part to the config.yaml and I'm getting an error when I try to load frames. The original labeling was done with an older version of deeplabcut, I don't recall the version, however the project was created on the 10th January 2019 and would have been the most up-to-date version at the time.

Error:
ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/tuple'

**How to Reproduce the problem**

1. Add a body part in the config.yaml 
2. Run the deeplabcut.label_frames function in an ipython session.
3. Click on 'Load Frames', and select a folder for labeling.
4. Error is outputted to ipython session
5. Quit session

Please see attached .txt file for full error log.
[deeplabcut_error.txt](https://github.com/AlexEMG/DeepLabCut/files/3465496/deeplabcut_error.txt)

Thank you so much for deeplabcut and your support!

**Comment by MMathisLab** [comment]
Just delete the line from config file that contains  tuple'

**Comment by Clyde92** [comment]
Yep, that's done it. 

Absolute legend! Thanks so much.
