### ISSUE TITLE
Error in 3D demo: deeplabcut.calibrate_cameras()

### ISSUE THREAD

**Issue by caniko** [DeepLabCut/DeepLabCut#387]
**Describe the bug**
Please provide the minimal required code to re-produce the error.

**To Reproduce**
1. Workflow for deeplabcut 3d
2. Run: `deeplabcut.calibrate_cameras(config_path3d, cbrow=9, cbcol=6, calibrate=True, alpha=0.9)`

**Expected behavior**
```
Corners not found for the image south-left-20.jpg
...
Corners not found for the image south-left-121.jpg
Corners not found for the image south-right-121.jpg
Saving intrinsic camera calibration matrices for south-left as a pickle file in \\Rxamd\d\Projects\DobleCameraPerSide_test\DeepLabCut_folders\3d_0_south_right_south_left-Can-2019-07-01-3d\camera_matrix
Mean re-projection error for south-left images: 0.073 pixels 
Saving intrinsic camera calibration matrices for south-right as a pickle file in \\Rxamd\d\Projects\DobleCameraPerSide_test\DeepLabCut_folders\3d_0_south_right_south_left-Can-2019-07-01-3d\camera_matrix
Mean re-projection error for south-right images: 0.090 pixels 
Computing stereo calibration for 
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-8-2766e48e8cd0> in <module>()
----> 1 deeplabcut.calibrate_cameras(config_path3d, cbrow=9, cbcol=6, calibrate=True, alpha=0.9)

C:\Users\Can\Miniconda3\envs\dlc\lib\site-packages\deeplabcut\pose_estimation_3d\camera_calibration.py in calibrate_cameras(config, cbrow, cbcol, calibrate, alpha)
    156         for pair in camera_pair:
    157             print("Computing stereo calibration for " %pair)
--> 158             retval, cameraMatrix1, distCoeffs1, cameraMatrix2, distCoeffs2, R, T, E, F = cv2.stereoCalibrate(objpoints[pair[0]],imgpoints[pair[0]],imgpoints[pair[1]],dist_pickle[pair[0]]['mtx'],dist_pickle[pair[0]]['dist'], dist_pickle[pair[1]]['mtx'], dist_pickle[pair[1]]['dist'],(h,  w),flags = cv2.CALIB_FIX_INTRINSIC)
    159 
    160             # Stereo Rectification

error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\calib3d\src\calibration.cpp:3352: error: (-215:Assertion failed) nimages > 0 && nimages == (int)imagePoints1.total() && (!imgPtMat2 || nimages == (int)imagePoints2.total()) in function 'cv::collectCalibrationData'
```

**Desktop (please complete the following information about your system):**
 - OS: Windows 10
 - DeepLabCut Version: 2.0.8
 - Browser: Chrome

**Comment by MMathisLab** [comment]
As we say in docs, you cannot run calibrate=True until you remove any bad pairs from the folder, you must use calibrate=False, carefully check the images, then once completely cleaned up and you have 30-50 pairs, then run calibrate=True

Also you are using a different version of OpenCV than we require. Please look at the conda-env files we supply.

**Comment by caniko** [comment]
Should I remove the pair if one of pictures in a pair is bad? Why don't your script just ignore the bad pairs after I remove one of the images from corners? The pairs share indexes.

I used dlc-windowsGPU.yaml to create my conda env. Recently, I also updated using the provided commands. This is the version of open-cv that was installed. Should I re-create the env?

**Comment by MMathisLab** [comment]
> error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\calib3d\src\calibration.cpp:3352: error: (-215:Assertion failed) nimages > 0 && nimages == (int)imagePoints1.total() && (!imgPtMat2 || nimages == (int)imagePoints2.total()) in function 'cv::collectCalibrationData'

strange that 4.1.0 was installed; in our setup.py file it is set to ``opencv-python~=3.4`` https://github.com/AlexEMG/DeepLabCut/blob/master/setup.py; perhaps recreate it. 

> C:\Users\Can\Miniconda3\envs\dlc

We also don't use Miniconda, so perhaps there is something different about what is installed. 

> Should I remove the pair if one of pictures in a pair is bad?

Yes, the images need to be removed from the folder if they are not found correctly. 

> Why don't your script just ignore the bad pairs after I remove one of the images from corners?

Feel free to make a PR to remove the other image if one is deleted; we felt it was easy enough for users to do this, since they needed to have some manual intervention anyhow. We cannot anticipate all the various naming conventions, so this was out attempt.

**Comment by caniko** [comment]
> > Why don't your script just ignore the bad pairs after I remove one of the images from corners?
> 
> Feel free to make a PR to remove the other image if one is deleted; we felt it was easy enough for users to do this, since they needed to have some manual intervention anyhow. We cannot anticipate all the various naming conventions, so this was out attempt.

I made some modifications to the functions. The 3d camera calibrate functions ignores bad pairs after the user deletes pictures with improper corners from the corners folder (pictures from initial run with calibrate=False). The error mentioned in this issue is no longer a problem. [Here](https://github.com/caniko2/DeepLabCut/commit/ed97f43ed1169583bd5c73f1c2c8ce1b16d83743) is a link to my version of the functions. 

I may have stumbled upon a bug, #389. I will make a pull request after solving the mentioned bug.

> > error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\calib3d\src\calibration.cpp:3352: error: (-215:Assertion failed) nimages > 0 && nimages == (int)imagePoints1.total() && (!imgPtMat2 || nimages == (int)imagePoints2.total()) in function 'cv::collectCalibrationData'
> 
> strange that 4.1.0 was installed; in our setup.py file it is set to `opencv-python~=3.4` https://github.com/AlexEMG/DeepLabCut/blob/master/setup.py; perhaps recreate it.

I did a force install `pip install --force opencv-python~=3.4`, and this is the version that is installed according to python. I am in the same conda environment:
```
Found existing installation: opencv-python 3.4.5.20
    Uninstalling opencv-python-3.4.5.20:
      Successfully uninstalled opencv-python-3.4.5.20
Successfully installed numpy-1.17.0 opencv-python-3.4.5.20
```
I am not sure why jupyter notebook suggests that I am on 4.1.0.
> > C:\Users\Can\Miniconda3\envs\dlc
> 
> We also don't use Miniconda, so perhaps there is something different about what is installed.

This should not have an effect, you can read more about it [here](https://stackoverflow.com/a/45421527/9793651).

**Comment by MMathisLab** [comment]
Then you are clearly in the wrong environment, since it says 4.1.0- top right corner should say what env your in.  Go to kernels, change kernel and select dlc (seems to be the name of your env)

**Comment by caniko** [comment]
You are wrong:
![image](https://user-images.githubusercontent.com/29519599/62534577-c6445080-b849-11e9-8c5d-20b2dc426bfd.png)

There is only one kernel available:
![image](https://user-images.githubusercontent.com/29519599/62534671-f7248580-b849-11e9-9c56-ef8615c05eb4.png)

Are you sure that you are not mixing opencv-python with cv2?
![image](https://user-images.githubusercontent.com/29519599/62534756-191e0800-b84a-11e9-9008-4d11def25e4a.png)

**Comment by caniko** [comment]
I have successfully triangulated using your function with my own modifications.

**Comment by MMathisLab** [comment]
I am not wrong, and your attitude is really rude. Please read the installation docs which say if you need to use Jupyter notebook, you have to first run conda install nb_conda.

**Comment by caniko** [comment]
> I am not wrong, and your attitude is really rude.

Oh that was sad to hear. In all fairness you said I was "clearly wrong" first (in the case that I wasn't), and I was just trying to be explicit to solve the issue. I did not mean to be crude; my apologies for the misunderstanding.

> Please read the installation docs which say if you need to use Jupyter notebook, you have to first run conda install nb_conda.

I already used this command during setup:

![image](https://user-images.githubusercontent.com/29519599/62551992-331d1200-b86d-11e9-9e80-5f9c83962602.png)

You are completely right, cv2 is in fact version 4.1.0, but as you can see above I did install python-opencv, and it was in fact [3.4.5.20](https://github.com/opencv/opencv/blob/8f1356c3c5b16721349582db461a2051653059e8/modules/core/include/opencv2/core/version.hpp). Luckily, this version of cv2 seem to work fine so far. I will revisit this in the case of a problem.
