### ISSUE TITLE
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'wx' is currently running

### ISSUE THREAD

**Issue by mfranch** [DeepLabCut/DeepLabCut#388]
Hi, 

When I run the following step, it displays the crop gui, I select the red area to crop, quit and save, the GUI closes, but the terminal remains stuck here: deeplabcut.extract_frames(config_path,'automatic','uniform', userfeedback=False, crop=True)
Config file read successfully.

The extracted frames never appear in the folder. I end up having to type Ctrl C to get out of it in terminal.  In my config.yaml file, I have:
```
# Cropping Parameters (for analysis and outlier frame detection)
cropping: true
#if cropping is true for analysis, then set the values here:
x1: 471
x2: 288
y1: 958
y2: 0
```
These are the values I use when cropping in ffmpeg, but I didn't think the values specified here matter at all since it should pull the values selected from the GUI and use those.  I should note that, anytime I run a step that requires the GUI, like the label frames step, it returns an error saying" ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'wx' is currently running." 

To proceed, I type import matplotlib then matplotlib.use('Agg')  and then re-run the deeplabcut step. After doing this, the GUI will appear, but deeplabcut terminal always gets stuck when the gui closes.  Any suggestions? I am using python in conda on Windows 10 computer.

**Comment by MMathisLab** [comment]
>  ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'wx' is currently running.

Can you please report which version of matplotlib you are running, and then  ``run pip install matplotlib==3.0.3`` if it's not that one inside your environment please. (https://forum.image.sc/t/error-running-label-frames-or-refine-labels/26071/15?u=mwmathis)

Those cropping are just used in the analysis step; the GUI writes the values under the video in the config file, i.e.:
```
video_sets:
  /home/mackenzie/DEEPLABCUT/bryan4.mp4:
    crop: 0, 360, 0, 640
```

**Comment by mfranch** [comment]
ah I see! in regard to the crop parameters.  Ok, I had matplotlib version 3.1.0 but I installed 3.0.3 and it works great, thank you!  One last question, during this extract frames and crop step, it returned the warning: 
warn('%s is a low contrast image' % fname)
Frame 70797  not found!
Frame 70822  not found!

What does this mean?  thanks!

**Comment by MMathisLab** [comment]
can you post the full call + print statement? 

this appears if there is an invalid image in the video:
https://github.com/AlexEMG/DeepLabCut/blob/2a2ad95a1ec35ad7f98d0155b4aa0d3ecedaefac/deeplabcut/generate_training_dataset/frame_extraction.py#L237

you can use another method, or just don't use those frames in the video (perhaps check your video too). i.e. you can set ``opencv=False`` to use our other loading method.

**Comment by mfranch** [comment]
ok, thanks! I will look into it.  This was the full call and error:

![warning](https://user-images.githubusercontent.com/53794486/62495037-78244400-b79a-11e9-86cf-1f70cc0d2d6c.PNG)

**Comment by MMathisLab** [comment]
^ cool, thanks; yeah I was wondering where the error came from, as it's not in our code directly, but seems from skimage io.py
