### ISSUE TITLE
deeplabcut.check_undistortion(): (-215:Assertion failed) count >= 0 in function 'cv::cornerSubPix

### ISSUE THREAD

**Issue by caniko** [DeepLabCut/DeepLabCut#389]
**Describe the bug**
I get this bug when I run deeplabcut.check_undistortion() as instructed by the 3D reconstruction DEMO jpynb. It should be noted that I am using a modified version of the function. Discussion on the changes can be found #387, and the source is [here](https://github.com/caniko2/DeepLabCut/commit/ed97f43ed1169583bd5c73f1c2c8ce1b16d83743). The modifications should have no effect on the portion of the code where the error occurs, but I am mentioning it just in case.

**To Reproduce**
Follow the instruction on examples\DEMO_3D_DeepLabCut.ipynb, and run the cell with deeplabcut.check_undistortion()

**Expected behavior**
`error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\imgproc\src\cornersubpix.cpp:58: error: (-215:Assertion failed) count >= 0 in function 'cv::cornerSubPix'`

**Screenshots**
Here is a picture of the error:
![image](https://user-images.githubusercontent.com/29519599/62503502-bea68c80-b7f4-11e9-9cae-085416cbd2f0.png)

My modifications checks if both images, comprising a pair, are present in the corners folder. For instance, if the user deletes camera-1-14, and leaves camera-2-14;  camera-2-14 will be ignored. The function **crashes at the first pair**, which is in fact valid (check below).

The image that raises the error (south-left-14_corner):
![south-left-14_corner](https://user-images.githubusercontent.com/29519599/62504106-5c9b5680-b7f7-11e9-9e8d-446a25378ae9.jpg)
The 2nd image (south-right-14_corner):
![south-right-14_corner](https://user-images.githubusercontent.com/29519599/62504129-70df5380-b7f7-11e9-8b65-e6ba70272b2d.jpg)

These pictures were created by deeplabcut.calibrate_cameras with calibrate set to False.

**Desktop (please complete the following information about your system):**
 - OS: Windows 10
 - DeepLabCut Version: 2.0.8
 - Browser: Chrome

Thank you for your time

**Comment by caniko** [comment]
Looking into the [assertion](https://github.com/opencv/opencv/blob/174b4ce29d8e1ddbd899095c4b9fb4443444af45/modules/imgproc/src/cornersubpix.cpp#L58) now. How can `int count` be less than 0?

**Comment by caniko** [comment]
I figured it out, it was a very simple mistake. My checkerboard is 9x6, your default values are 8x6. deeplabcut.check_undistortion() takes cbrow and cbcol, but these parameters are omitted in the notebook. I will include a version of the notebook, where these are included in my pull request.

**Comment by JialinKang** [comment]
hello, I want to know how to solve this error finally?
@caniko
oh! I get it! thank you for this issue!
