### ISSUE TITLE
all points are occluded in one frame (relates to old version of DLC)

### ISSUE THREAD

**Issue by mschart** [DeepLabCut/DeepLabCut#39]
Hi there,

Assume all four points that I want to track are occluded in a frame. Then typing

```
~/DeepLabCut-master/pose-tensorflow/models/aliAugust10-trainset95shuffle1/train$ TF_CUDNN_USE_AUTOTUNE=0 CUDA_VISIBLE_DEVICES=0 python ../../../train.py

```
results in this error: 

```
 Traceback (most recent call last):
  File "../../../train.py", line 140, in <module>
    train()
  File "../../../train.py", line 80, in train
    dataset = create_dataset(cfg)
  File "/home/mic/DeepLabCut-master/pose-tensorflow/dataset/factory.py", line 16, in create
    data = PoseDataset(cfg)
  File "/home/mic/DeepLabCut-master/pose-tensorflow/dataset/pose_dataset.py", line 50, in __init__
    self.data = self.load_dataset()
  File "/home/mic/DeepLabCut-master/pose-tensorflow/dataset/pose_dataset.py", line 78, in load_dataset
    joint_id = joints[:, 0]
IndexError: index 0 is out of bounds for axis 1 with size 0

```
So one needs to change something to handle that empty joint index list.

**Comment by AlexEMG** [comment]
Indeed, however line 141 in https://github.com/AlexEMG/DeepLabCut/blob/master/Generating_a_Training_Set/Step4_GenerateTrainingFileFromLabelledData.py should take care of this, i.e.

```
            if np.size(joints)>0: #exclude images without labels
                    data.append(H)
```

Do you know why this item was not omitted from the training set?

**Comment by mschart** [comment]
Aha, I have an older version of your scripts, in my Step4_GenerateTrainingFileFromLabelledData.py this line doesn't exist. Ok, will update, issue solved, thanks!

**Comment by AlexEMG** [comment]
Great - I guess in that case quite a few things changed, so that the newest version should be much better!

**Comment by mschart** [comment]
It all works like a charm now. I'm a huge fan of your toolbox, currently tracking mice, lemurs and soon monkeys. Cheers!
