### ISSUE TITLE
how to plot "skeleton" and trailing points in video [question]

### ISSUE THREAD

**Issue by bkacsoh** [DeepLabCut/DeepLabCut#392]
**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
MacOS version 10.13.4 (17E199) using Deeplabcut 2, with conda environment dlc-macOS-CPU

Please complete the following information about your system:

OS: iOS
DeepLabCut Version 2
Browser firefox

<img width="431" alt="Screen Shot 2019-08-06 at 2 36 28 PM" src="https://user-images.githubusercontent.com/53061481/62566707-9b60f900-b857-11e9-8207-77e23b506475.png">

**Describe the problem**

A clear and concise description of what the problem is.

I am having difficulty providing the directionality over lay on the video (i.e. the attached image) where the path of the animal is outlined during the entirety of the video. This feature is shown on the deeplabcut homepage with the mouse video and I would like to utilize this function, but am having trouble finding the appropriate output.

Thank you!

**Comment by MMathisLab** [comment]
How to draw a skeleton and points are in the documentation, here: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#create-labeled-videos

PS - For questions not bug reports, we prefer you use Image Forum.  
https://forum.image.sc/tags/deeplabcut

https://github.com/AlexEMG/DeepLabCut#community-support-developers--help

**Comment by bkacsoh** [comment]
Thank you! Sorry about the incorrect posting location!

**Comment by MMathisLab** [comment]
no problem.
