### ISSUE TITLE
SystemExit : "This program needs access to the screen. Please run with a Framework build of python, and only when you are logged in on the main display of your Mac."

### ISSUE THREAD

**Issue by DmitryOskolkov** [DeepLabCut/DeepLabCut#394]
**MacOS and 2.0.8**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: MacOS
DeepLabCut Version [e.g. 22] 2.0.8
Browser yandex browser

After applying deeplabcut.extract_frames(config_path) and answering "yes" in the window i get the following SystemExit : "This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac." How can i solve this problem? Thank you in advance

A clear and concise description of what the problem is.

**How to Reproduce the problem**
1. Open dlc-macOS-CPU form Anaconda with Jupiter Notebook
2. Import everything needed
3. make 
os.environ["DLClight"]="True"
os.environ["Colab"]="True"
4. Make the config_path variable
5. apply deeplabcut.extract_frames(config_path,'automatic','uniform',crop=True)
6. See error

**Screenshots**

<img width="1080" alt="Снимок экрана 2019-08-08 в 16 42 11" src="https://user-images.githubusercontent.com/44604439/62708193-8e7d0a80-b9fb-11e9-9e09-5f2fe3b4e219.png">
<img width="1080" alt="Снимок экрана 2019-08-08 в 16 41 53" src="https://user-images.githubusercontent.com/44604439/62708198-9046ce00-b9fb-11e9-9b03-d7e6d49d8491.png">

**Additional context**

**Comment by MMathisLab** [comment]
Yes, for MacOS you need to use terminal, please see the docs here: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/UseOverviewGuide.md#option-2-using-the-program-terminal-start-ipython

also note that if you set these variables, you are inactivating any GUI from running.

> os.environ["DLClight"]="True"
> os.environ["Colab"]="True"
