### ISSUE TITLE
Error installing Deeplabcut

### ISSUE THREAD

**Issue by jesusdpa1** [DeepLabCut/DeepLabCut#395]
Hi, 

I am having troubles with Deeplabcut 2.0.8. After updating to the new version I haven't been able to run my python console. When I open pycharm in my project it always exits with error code 1 in the python console

From my tests, I have deduce that it is one of the complementary libraries that are installed when using the command "pip install deeplabcut" but haven't been able to figure out the rest.

**Comment by AlexEMG** [comment]
That doesn't sound DLC specific - but can you perhaps post more details?

**Comment by jesusdpa1** [comment]
Yes, no problem. I did figure it out this morning. Apparently there is an issue with the version of Ipython that is installed with the pip command (pip install deeplabcut). 

I had to update to the most recently version of Ipython and update also numpy since it was giving some errors with tensorflow-gpu 1.14. 

But problem solved. Thanks for your reply

**Comment by MMathisLab** [comment]
PS - if you are getting the DLL error with tensorflow, you will hit more errors later, hence why we fixed the versions in the conda environment file. https://forum.image.sc/t/tensorflow-dlc-2-0-importerror-dll-load-failed-the-specified-module-could-not-be-found/22991 It has to do with the python version! Not numpy or tensorflow, or deeplabcut ;)

**Comment by jesusdpa1** [comment]
Good to know. Thank you very much!
