### ISSUE TITLE
analying part of the video

### ISSUE THREAD

**Issue by xcharxlie** [DeepLabCut/DeepLabCut#397]
Hi everyone, I am not sure if this is the right place to ask a quick question. When using method to analyze a video, what should I do to just analyze a small part of a certain video since the majority of this video is irrelative. Thank you!

**Comment by MMathisLab** [comment]
this is indeed not the correct location, hence the bug report templates. Please see the main README that highlights the places you can ask questions, and chat: https://github.com/AlexEMG/DeepLabCut#community-support-developers--help
