### ISSUE TITLE
Error when save labeling 

### ISSUE THREAD

**Issue by katemartian** [DeepLabCut/DeepLabCut#398]
Windows 10, DeepLabCut 2.0.8, Anaconda3 env. dlc-windowsCPU

**Describe your problem:**
After labeling frames, I try to save them but always get an error message:
![error](https://user-images.githubusercontent.com/20586089/63035532-4b9eb500-be89-11e9-8105-3dd8f222358f.png)

Could you help me to solve my problem?

Thanks,
Kate

**Comment by MMathisLab** [comment]
Hi Kate, your pytables installation is broken. 
Please see issues: #377 #210 #164

**Comment by MMathisLab** [comment]
In particular: https://github.com/AlexEMG/DeepLabCut/issues/164#issuecomment-465704245

**Comment by katemartian** [comment]
I install pytables using the line: `conda install -c conda-forge pytables`.
I run cmd as admin and created and use dlc-windowsCPU environment.
But I still have the same error. What could I try more? 
Thanks a lot for your help!

**Comment by MMathisLab** [comment]
you need to (1) open cmd as a ADMIN, then launch the environment, then install the specific version of pytables that works

**Comment by katemartian** [comment]
I added the version of pytables and it finally worked. Thanks!
