### ISSUE TITLE
3D camera calibration finds no corners

### ISSUE THREAD

**Issue by rattey** [DeepLabCut/DeepLabCut#399]
**Your Operating system and DeepLabCut version**
Ubuntu 16.04 LTS, with an Anaconda Env & supplied docker container for DeepLabCut 2.0.8. I have also tried working outside the docker container (but still in the Anaconda Env and still with DeepLabCut 2.0.8) and I got the exact same results.

**Describe the problem**
Hello,
I am trying to calibrate cameras for a 3D project. I took videos that can be viewed here (https://www.dropbox.com/s/q3mspucicm8fhfo/SideProfile2019-08-15T10_57_42.avi?dl=0) and here (https://www.dropbox.com/s/76o64f9vwznv42g/FromBelow2019-08-15T10_57_42.avi?dl=0) and then used the suggested command in Anaconda to extract the frames from each. I have looked through those extracted images and verified that the images in the calibration_images folder are correct. 

When I run the command to calibrate cameras, it doesn't find corners for any of the images. 
I am running the command: 
deeplabcut.calibrate_cameras(config_path_3d, cbrow = 4, cbcol = 9, calibrate=False, alpha=0.9)
it outputs:
Corners not found for the image SideProfile-001.jpg
Corners not found for the image FromBelow-001.jpg
Corners not found for the image SideProfile-002.jpg
Corners not found for the image FromBelow-002.jpg
Corners not found for the image SideProfile-003.jpg
Corners not found for the image FromBelow-003.jpg
Corners not found for the image SideProfile-004.jpg
Corners not found for the image FromBelow-004.jpg
Corners not found for the image SideProfile-005.jpg
Corners not found for the image FromBelow-005.jpg
...
Corners not found for the image FromBelow-483.jpg
Corners not found for the image SideProfile-484.jpg
Corners not found for the image FromBelow-484.jpg
Corners not found for the image SideProfile-485.jpg
Corners not found for the image FromBelow-485.jpg
Corners not found for the image SideProfile-486.jpg
Corners not found for the image FromBelow-486.jpg
Corners not found for the image FromBelow-487.jpg
Corners not found for the image SideProfile-487.jpg
Corners extracted! You may check for the extracted corners in the directory /home/smearlab/New Rig 3D DLC-Robin Attey-2019-08-15-3d/corners and remove the pair of images where the corners are incorrectly detected. If all the corners are detected correctly with right order, then re-run the same function and use the flag ``calibrate=True``, to calbrate the camera.

The corners folder is empty, because no corners were ever found.

Is the problem with my images or with the way I am running the command? 

Something to note is that the videos/images labeled "Side Profile" come from filming the reflection in an angled mirror. We are actually filming with one camera from below and using the mirror so we can see the side profile of the mouse as well as the underside (example here: https://www.dropbox.com/s/l2345bav342t2v3/Uncropped2019-08-14T16_51_35.avi?dl=0). The videos are automatically cropped and saved separately, so I was planning to treat them as if they were coming from separate cameras for DeepLabCut purposes.

Any advice is appreciated! Thank you!

**Comment by MMathisLab** [comment]
so the reflection view (https://www.dropbox.com/s/76o64f9vwznv42g/FromBelow2019-08-15T10_57_42.avi?dl=0) is an issue, as the contrast is too low. Check out the demo images; these are going to be what is required...

**Comment by meet10may** [comment]
Hi,
You need to adjust the ``cbrow`` and ``cbcol``. ``cbrow``  and ``cbcol`` represents the number of interior corners (i.e. the intersection of black and white boxes) in the checkerboard. e.g ``cbrow = 8`` and ``cbcol=6`` in our example notebook.
https://github.com/AlexEMG/DeepLabCut/blob/master/examples/DEMO_3D_DeepLabCut.ipynb
So, in your case, it should be ``cbrow=3`` and ``cbcol=8``. 

The view from below has some black spots, so it might cause some issues while detecting the corner points of the checkerboard, as corner detection algorithm of OpenCV is a bit sensitive to noise.

Hope it helps!

**Comment by rattey** [comment]
Thank you for the responses! It seems both of these issues were contributing. I have fixed cbrow and cbcol, and it was able to find the corners for all the Side Profile images. I then fixed the contrast issues Dr. Mathis brought up, and now it recognizes corners on the From Below images as well.

Thank you for your fantastic support!
