### ISSUE TITLE
Is it possible to use the trained model to predict on an image by image basis?

### ISSUE THREAD

**Issue by ambareeshsrja16** [DeepLabCut/DeepLabCut#401]
Wondering if it's possible to expose the prediction part of the model, on an image rather than on an entire video? 

I'm trying to use it to perform predictions on a set of disparate images. Assuming a behavior of say, a model like in TF/PyTorch, where I can do a simple:
`pred_image = model(input_image)`
where the predicted image has all the labeling done. 

I'm assuming the model does this since the video is made after doing predictions on all frames. 

Thank you!

**Comment by MMathisLab** [comment]
yes, see the code you ref. in #402 ;) will check in PR, thanks!

**Comment by ambareeshsrja16** [comment]
Hi,

Is it possible to extract the forward pass of the trained model to do a forward pass?

My use case is a real-time prediction on an image to image basis.  For an input image that I get every second, I am trying to get an output of prediction points! The workflow I am following right now involves calling analyze_time_lapse_frames and getting the output the .h5/.csv file and reading the output file. But , this is not fast enough. 

@MMathisLab  Could you suggest an alternative?

**Comment by ambareeshsrja16** [comment]
Also, a follow-up question, is analyze_time_lapse frames (current implementation) using CPU for inference? Or GPU?

**Comment by MMathisLab** [comment]
We will release code in the future to do this efficiently

**Comment by ambareeshsrja16** [comment]
Okay, I just saw that it is using setup_pose_prediction. I'll try with setup_GPUpose_prediction and see if it improves results!

Thank you for getting back, quickly!

**Comment by dsvilarkovic** [comment]
@MMathisLab any updates on this feature?

**Comment by MMathisLab** [comment]
yes, you can run `deeplabcut.analyze_time_lapse_frames` which allows you to run inference on images vs video input! https://deeplabcut.github.io/DeepLabCut/docs/HelperFunctions.html?highlight=time_lapse and for the real-time point (which I mentioned in https://github.com/DeepLabCut/DeepLabCut/issues/401#issuecomment-539270741) this is released in: Kane et al. 2020 eLife: https://elifesciences.org/articles/61909 and all associated code: dlclive.deeplabcut.org
