### ISSUE TITLE
ImportError: HDFStore requires PyTables, "numpy.core.multiarray failed to import" problem importing

### ISSUE THREAD

**Issue by rlkrup** [DeepLabCut/DeepLabCut#404]
Windows 10, Anaconda Env, DeepLabCut 2.0.8, google chrome

Please complete the following information about your system:

After labeling frames and pressing 'save' I get this error: ImportError: HDFStore requires PyTables, "numpy.core.multiarray failed to import" problem importing.

 I know this problem has been addressed several times before in various threads, and I have tried all of those solutions:

Running as an administrator
Using the provided environment
Upgrading pytables
Downgrading pytables
Wiping the environment and starting fresh

I haven't had any luck getting past this point. Are there any other solutions out there?

Screenshot of error message below:

![screenshot](https://user-images.githubusercontent.com/54401027/63512538-1231ff00-c4b2-11e9-80de-13afc20e9d58.png)

**Comment by MMathisLab** [comment]
could you check which versions of numpy and pytables you have installed? 

Typically all the fixes you mentioned are the issue, so i'm not quite sure... 

ps - if the csv files are saving, you don't need to relabel. We have a function to convert the csv to h5!: `deeplabcut.convertcsv2h5`

**Comment by pfelramos** [comment]
> Thank you! I had to reinstall numpy and it works now.

I'm having the same problem with a new pc build(Windows10). Which version of numpy did you installed?

I have in my dlc-windowsGPU environment:
- numpy                   1.14.5               
- pytables                 3.4.4            
- h5py                      2.9.0           
- hdf5                      1.10.4              

![saveLabelsError](https://user-images.githubusercontent.com/16214953/64082321-f4d70f00-ccc1-11e9-9d80-3d934f533db7.png)

**Comment by pfelramos** [comment]
> > Thank you! I had to reinstall numpy and it works now.
> 
> I'm having the same problem with a new pc build(Windows10). Which version of numpy did you installed?
> 
> I have in my dlc-windowsGPU environment:
> 
> * numpy                   1.14.5
> * pytables                 3.4.4
> * h5py                      2.9.0
> * hdf5                      1.10.4
> 
> ![saveLabelsError](https://user-images.githubusercontent.com/16214953/64082321-f4d70f00-ccc1-11e9-9d80-3d934f533db7.png)

Apparently the issue was resolved by using: **pip install numpy --upgrade**

After that, I was able to save the labeled images and check the labels.
