### ISSUE TITLE
Minimum no. dataset to predict every video

### ISSUE THREAD

**Issue by vijaysamula** [DeepLabCut/DeepLabCut#407]
I am using Docker4DeepLabCut2.0 to detect the cow pose. I have created until now 930 images dataset with different videos. But the test giving false predictions for non-trained videos. 
Can I know the minimum no. of the dataset to train and predict the video exactly?

**Comment by MMathisLab** [comment]
This strongly depends on your training data, and the novel videos. If they look similar, then it generalizes very well. If it does not, that is why provide you with [refinement tools ](https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#j-optional-active-learning---network-refinement-extract-outlier-frames) for you to augment the dataset with data that is  similar to the novel videos. We discuss this in the [Nature Neuroscience paper](https://t.co/Grkqck2tka); i.e. we labeled 10,80 frames and show that with even 50 you can get great performance on unseen mice in a simple lab setting (what DeepLabCut is designed for). We also discuss this in the [Nature Protocols paper](https://rdcu.be/bHpHN) about the cheetah dataset, which is much more complicated... 

Also, **please post questions** on [Image Forum](https://forum.image.sc/tags/deeplabcut), **not** on github, which is only for code bug reports.
