### ISSUE TITLE
How do I check refined labels?

### ISSUE THREAD

**Issue by neha28wsu** [DeepLabCut/DeepLabCut#412]
**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: Ubuntu 16.04 LTS
DeepLabCut Version 2.0.8
Browser safari

**Describe the problem**

after extracting outlier frames i go for refine label step and relabel the frames that are misplaced on the body part. i load the frames and try to label it and after saving it if i again check those labels they go back to their previous position as if the changes made by me did not get saved 

**How to Reproduce the problem**
1. Go to step deeplabcut.refine_labels(config_path)
2. Click on load labels
3. click OK on the user instructions window 
4. click OK to the threshold value entered as 0.1
5. start correcting the labels on every image and save it 
6. then I again check the corrected labels for same images by loading them ,find the same issue i.e misplaced dots on the body parts

**Screenshots**

**Additional context**
 hope i may able to explain my problem this time

**Comment by MMathisLab** [comment]
I cannot understand this. Please edit the post to fill out the template.

**Comment by MMathisLab** [comment]
You cannot load them again in the refinement GUI. That GUI loads the “machine-labeled” file, which one should always keep. If you want to look at the corrected labels, you need to run “check labels” and if you want to adjust them further you have to load them in the “labeling GUI”
