### ISSUE TITLE
Loading h5 file for analyzed video

### ISSUE THREAD

**Issue by souvikces** [DeepLabCut/DeepLabCut#413]
It would be great to have a simple function to return the analyzed h5 file for a video if one is working in ipython!

**Comment by MMathisLab** [comment]
I don’t understand, that is literally the output when you run analyze_videos is you get an .h5 plus an optional .csv

Plus, we have a whole repository for analysis tools post-deeplabcut: 

https://github.com/AlexEMG/DLCutils

**Comment by MMathisLab** [comment]
@AlexEMG - close or update so this is clear?
