### ISSUE TITLE
Problem loading video when a project is created

### ISSUE THREAD

**Issue by c3618** [DeepLabCut/DeepLabCut#414]
Hello,

I'm using Windows 10, the GPU DeepLabCut environment, and deeplabcut version 2.0.8 with OpenCV version  3.4.5.20, in iPython.  When I go to create a new project I use an AVI file video and it creates the project but returns an error saying "warning: Error opening file (...file path…)" and another warning that has the file path to the video, then below it mentions that it "Cannot open the video file!" Then it goes on to state that the configuration file was made and lets me know where it's stored at.  Since it won't load the video I can't do anything else from there with it.  I'm fairly new to programming so I'm guessing there's some simple fix here and any help is appreciated!!

**Comment by meet10may** [comment]
Could you please provide more details about how did you run the command? Can you please share the screenshot of the error message? "Error opening the file path" could be because of incorrect file path to the video or corrupt video file. 
Please provide more details so that we can assist you.

**Comment by c3618** [comment]
![DLC pic](https://user-images.githubusercontent.com/54952139/64541786-1babcb80-d2e8-11e9-81d5-7c88a59f404e.jpg)

Yes I can, thank you!  The pic has what I entered to get to the error message.  Feel free to let me know if any other information would be useful.

**Comment by MMathisLab** [comment]
Your video file must end with a file type! Like “\\reaching.avi’]

(Also I see no error message)

**Comment by meet10may** [comment]
It seems you are missing the video file type i.e .avi or if it is a folder, then you need to specify the video file.  This is the reason you got the warning "Cannot open the video file". You can check the help file for this function using  
`deeplabcut.create_new_project?`
This is how you need to specify the arguments:
`deeplabcut.create_new_project('mouseReach','Carrie',['C:\\Users\\priebelab\\Desktop\\Carrie\\reachingvideo1\\video.avi'], copy_videos=True)`

**Comment by c3618** [comment]
Thank you so much that worked great and was very helpful!! You guys are awesome!  I figured it was probably something pretty simple.
