### ISSUE TITLE
Dynamic Target Point Uncertainty

### ISSUE THREAD

**Issue by Selmaan** [DeepLabCut/DeepLabCut#416]
I'm working on a multi-camera tracking application for freely moving animals, where frames from individual cameras will often have occluded body parts. However, the coarse location of occluded features can still be inferred. For example, the location of the animal's left eye is coarsely predictable from the right-hand side as somewhere behind the animal's head. 

It would seem useful to train DeepLabCut to predict the coarse location of these occluded parts, however I'm currently not aware of how this could be done. I could exclude a target point for the occluded part, but this does not encourage predictions to be in the generally correct area. I could manually estimate a precise location, but this assigns the arbitrarily chosen point comparable weight as visible parts during training and so introduces possible noise and/or human biases into predictions. It seems like a simple alternative would be to allow users to specify a level of spatial precision during the manual labeling process? This manual precision/uncertainty would then be propagated to the diameter of the target score map used during network training, for that specific frame and part. Apologies if this is currently possible and I just don't know how to do it...

(For context, I'm interested in appropriately calibrated uncertainties because I'd like to implement uncertainty-weighted estimation of 3d position from a multi-camera array. For 3d setups w/ freely moving animals, where this kind of occlusion might be present on >25% of frames, w/ partial occlusions even more frequent, properly weighting measurements from different cameras might substantially improve performance?)

**Comment by MMathisLab** [comment]
> (For context, I'm interested in appropriately calibrated uncertainties because I'd like to implement uncertainty-weighted estimation of 3d position from a multi-camera array. For 3d setups w/ freely moving animals, where this kind of occlusion might be present on >25% of frames, w/ partial occlusions even more frequent, properly weighting measurements from different cameras might substantially improve performance?)

- You can set the `num_parts` during video analysis, which can help with triangulating this. Of course, you would need to have multiple cameras for 3d freely moving behavior. 

> It seems like a simple alternative would be to allow users to specify a level of spatial precision during the manual labeling process?

- you can set a level of precision for training, i.e. pos_dist_threshold (see Box2), but not per body part. but you could create multiple models, one for course inference, one for fine and combine those results. 

 we will also release more code in the future that will help with these issues, but it's an active research area in our lab for now.

**Comment by MMathisLab** [comment]
Hey @Selmaan - hope you are well! Do you think you'd like to work on this? if not, I will close it ... 
I believe @lambdaloop is using >1 output per bodypart for effective weighting of 3d points in www.anipose.org, a nice wrapper package for DLC with much more 3d functionality that we provide. 

PS - in dlc you can not label occluded or missing bodyparts and use our imgaug data loader.
