### ISSUE TITLE
Markers are not visible

### ISSUE THREAD

**Issue by oludash02** [DeepLabCut/DeepLabCut#418]
Hi,
I have tried annotating new data using the video tutorial and instructions on this repo but the markers are not visible on the GUI whenever I clicked on the image. I tried this on both Windows and Ubuntu OS but had same issue. Am I doing anything wrong?

**Comment by MMathisLab** [comment]
Are you using the right click? See help button in GUI.

**Comment by oludash02** [comment]
Oh, I didn't see that...thanks!
