### ISSUE TITLE
Trouble importing deeplabcut

### ISSUE THREAD

**Issue by Tsugua5** [DeepLabCut/DeepLabCut#419]
**Describe the bug**
Please provide the minimal required code to re-produce the error.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information about your system):**
 - DeepLabCut Version [e.g. 22] (please check with ``import deeplabcut``, ``deeplabcut.__version__``)

**Additional context**

**Comment by MMathisLab** [comment]
see #420 - DUPLICATE ISSUE.
