### ISSUE TITLE
Trouble with import deeplabcut

### ISSUE THREAD

**Issue by Tsugua5** [DeepLabCut/DeepLabCut#420]
After creating and activating an environment using the dlc-windowsGPU.yaml file, I start a python session and try to import deeplabcut. This I can only do if if located in "C:\Users\rasmussen\Desktop\DeepLabCut-master". The following error then shows

![error](https://user-images.githubusercontent.com/11161583/64961945-d6af0880-d896-11e9-8d9f-d537a9166af5.png)

Any fix for this? 

I am running windows server 2019
I have a GeForce RTX 2080 Ti installed with a succesful install of CUDA

**Comment by Tsugua5** [comment]
I am using python 3.7.3

**Comment by MMathisLab** [comment]
You must use 3.6; also this issue is discussed quite a bit on the user forum, please check.

**Comment by MMathisLab** [comment]
responded in DUPLICATE ISSUE #421
