### ISSUE TITLE
Analyzer stuck at 2%

### ISSUE THREAD

**Issue by MorterzaAbbaszadeh** [DeepLabCut/DeepLabCut#423]
HI:)

a while ago I installed Ubuntu 18.4 on a workstation with a NVIDIA P4000 GPU with all required CUDA 10.1 accessories to start working with DLC (installed from the Yaml file). I came up across the the cuDNN handle error stemming from either cuDNN version mismatch or memory overflow, so I managed it by adding:

    gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.8) 
    sess = TF.Session(config=tf.ConfigProto(gpu_options=gpu_options))

to train.py, training.py, test.py and predict_videos.py in pose_estimation_tensorflow, right after tf/TF version verification. here:

    vers = (tf.__version__).split('.')
    if int(vers[0])==1 and int(vers[1])>12:
        TF=tf.compat.v1
    else:
        TF=tf

the training worked well, got 700k steps in 15hrs, converged to below 0.01 loss, but when I try to analyze the video it finishes the analysis at 2% and out of 5K frames in the video I get like 50 frame coordinates in the csv file. No error no nothing. It just gives up.
I have tried setting gputouse in Analyze_videos to =None, but it basically ignored me 
Thought I can get away with it, but apparently Nope. any solutions to this?

**Comment by AlexEMG** [comment]
My sense is that this has nothing to do with TF, but rather opencv, see e.g. https://github.com/AlexEMG/DeepLabCut/issues/357 and https://forum.image.sc/t/issue-to-align-detected-frames-with-time-scale/28710/5

Can you check this with your video?

**Comment by MorterzaAbbaszadeh** [comment]
belated thanks alex, It made sense so I focused on the video side rather than the GPU. my initial codec was MP4, openCV gave out the correct fps and frame count yet still I exported the video to .avi for which ffmpeg reads:

Input #0, avi, from 'bsum.avi':
  Metadata:
    encoder         : Lavf58.29.100
  Duration: 00:01:00.50, start: 0.000000, bitrate: 19223 kb/s
    Stream #0:0: Video: mjpeg (MJPG / 0x47504A4D), yuvj420p(pc, bt470bg/unknown/unknown), 1280x720 [SAR 1:1 DAR 16:9], 18954 kb/s, 59.94 fps, 59.94 tbr, 59.94 tbn, 59.94 tbc
    Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, fltp, 256 kb/s


which is correct and also I have:


In [5]: os.listdir(os.curdir)
Out[5]: ['bsum.avi']

but yet still when I run Analyze_video:

deeplabcut.analyze_videos(config_path,'/correct path to /videos' ,videotype='.avi', save_as_csv=True)

 it gives me the error:


No video was found in the path/ or single video with path: /(correct path to my videos)
Perhaps the videotype is distinct from the videos in the path, I was looking for: .avi
Out[3]: 'DeepCut_resnet50_Dyskinasia_paw_demo2Sep24shuffle1_700000'



I have checked the path and specified video type and all that.

**Comment by AlexEMG** [comment]
Can you reproduce being stuck with this with the openCV loader itself?

```
video='bsum.avi'
loadedframes=0

import cv2
cap=cv2.VideoCapture(video)
        
fps = cap.get(5) 
nframes = int(cap.get(7))
size=(int(cap.get(4)),int(cap.get(3)))
        
ny,nx=size
print("Overall # of frames: ", nframes," found with (before cropping) frame dimensions: ", nx,ny)

while(cap.isOpened()):
            ret, frame = cap.read()
                 if ret:
                      frame=cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                      loadedframes+=1
```

**Comment by MMathisLab** [comment]
@MorterzaAbbaszadeh - any updates?

**Comment by MorterzaAbbaszadeh** [comment]
Hi,
First and foremost thanks for the fantastic support.
I run alex's script and it came up with

ModuleNotFoundError: No module named 'cv2'

pip installed that on the env and:

Overall # of frames:  3626  found with (before cropping) frame dimensions:  1280 720


I was trying to figure what has happened,  made another env with the same yaml, again with cv2 installation worked. to this point I have no idea why and how and why the weird error.

**Comment by MMathisLab** [comment]
maybe just a broken installation then, but glad to hear this is resolved.
