### ISSUE TITLE
Option to remove tagged body part

### ISSUE THREAD

**Issue by Shachafbe** [DeepLabCut/DeepLabCut#424]
I tagged multiple body parts, one of them is hidden a lot during the video and therefore make more mistakes when analyzing the video. 
I sew there is an option to add more body parts, but is there an option to remove body parts after tagging? 

Many many thanks in advance! 
Shachaf.

**Comment by MMathisLab** [comment]
No, because you can just not use them for your analysis then, or plotting etc. 

Please post questions on the user forum (vs but report, thanks!)
