### ISSUE TITLE
misleading absolute video paths in config file

### ISSUE THREAD

**Issue by wzinke** [DeepLabCut/DeepLabCut#425]
**Describe the bug**
Videos will be copied into the `videos` subdirectory and specified with a full absolute path in the config file. I was renaming the project directory but forgot to adjust the video path. When I wanted to extract frames, I got a `ZeroDivisionError: float division by zero` error because of `--> 140                     duration=nframes*1./fps` instead of a file not found error. Once corrected, the frame extraction was not only limited to the video file specified in the config files, but attempted to extract frames for all movie files found in the movie directory. Therefore, it appears that specifying the video in the config file is not efficient and maybe not necessary if per default all videos in the subdirectory are used.

**To Reproduce**
A) ZeroDivisionError
1. rename video path in the config file in a way that there is no file found
2. execute `deeplabcut.extract_frames`

B) load additional movies not specified in config file
1. Copy an additional movie file into the videos subdirectory of the project
2. execute `deeplabcut.extract_frames`

**Expected behavior**
In the first case I would expect to get an error that indicates that a file is not found, instead the error refers to a problem with the frame rate.
In the second case I would expect to only use video specified in the config file. 
If videos are copied or linked into the videos subdirectory, there seems not to be a reason to specify videos by their absolute path, video names should be sufficient. 

**Desktop (please complete the following information about your system):**
 - OS :Linux Mint 19.1
 - DeepLabCut Version: 2.0.9
 - Browser: Firefox

**Comment by AlexEMG** [comment]
The problem is that the metadata regarding your framerate is 0 in your metadata.

**Comment by MMathisLab** [comment]
>  I was renaming the project directory but forgot to adjust the video path.

To be clear, you DO NOT need to re-name the video paths if you move the project folder, assuming you have extracted frames and labeled already, the project is fully portable as is. 

>  the frame extraction was not only limited to the video file specified in the config files, but attempted to extract frames for all movie files found in the movie directory. 

You can set this by changing `userfeedback=True`, the it asks you for each video if you want to extract frames. Please check the docstrings. 
```
deeplabcut.extract_frames?

Signature: deeplabcut.extract_frames(config, mode='automatic', algo='kmeans', cr
op=False, userfeedback=True, cluster_step=1, cluster_resizewidth=30, cluster_col
or=False, opencv=True, slider_width=25)
Docstring:
Extracts frames from the videos in the config.yaml file. Only the videos in the 
config.yaml will be used to select the frames.

Use the function ``add_new_video`` at any stage of the project to add new videos
 to the config file and extract their frames.

The provided function either selects frames from the videos in a randomly and temporally uniformly distributed way (uniform), 

by clustering based on visual appearance (k-means), or by manual selection. 

Three important parameters for automatic extraction: numframes2pick, start and stop are set in the config file. 

Please refer to the user guide for more details on methods and parameters https://www.biorxiv.org/content/biorxiv/early/2018/11/24/476531.full.pdf
```
