### ISSUE TITLE
question with analyzing new video COLAB; destfolder?

### ISSUE THREAD

**Issue by davidjamespritchard** [DeepLabCut/DeepLabCut#428]
**Your Operating system and DeepLabCut version**

Please complete the following information about your system:

OS: Windows 10
DeepLabCut Version: 2.0.9 (in CoLab)
Browser: Chrome

**Describe the problem**

I have a trained model which I have evaluated and what to apply to a new video. When I run the code: deeplabcut.analyze_videos(path_config_file,['/content/drive/My Drive/Tests/mov.mp4'],destfolder = '/content/drive/My Drive/Tests')

I get an error saying that "File /content/drive/My Drive/Tests/movDeepCut_resnet50_HummingbirdsSep23shuffle1_21000.h5 does not exist"

**How to Reproduce the problem**
I am not sure how to reproduce the problem here. I am happy to provide more information if it would help.

**Screenshots**

![image](https://user-images.githubusercontent.com/46787309/65601423-f8487800-df99-11e9-92b5-3c15a618ae96.png)

**Additional context**

**Comment by MMathisLab** [comment]
please try without setting destfolder, in colab you don't have admin writes to write to a user-forced folder.
`
deeplabcut.analyze_videos(path_config_file,['/content/drive/My Drive/Tests/mov.mp4'])`

**Comment by davidjamespritchard** [comment]
That seems to have solves it, which is a bit weird as I had the same problem before I added the destfolder argument. But seems to work now.
