### ISSUE TITLE
Issues using Tensorpack for data augmentation

### ISSUE THREAD

**Issue by eleonoreduroyon** [DeepLabCut/DeepLabCut#429]
Hello everyone!

**Your Operating system and DeepLabCut version**
Ubuntu 16.04 LTS with Anaconda Env & DLC version 2.0.9 (using a GPU as well)

**Describe the problem**
After the new DLC release, I have been trying to use the feature for data augmentation. To do so, I modified the pose_cfg.yaml and set dataset_type to tensorpack. When I put the network to train (deeplabcut.train_network(config_path, shuffle=1, gputouse=0)), I get this error: OSError: [Errno 12] Cannot allocate memory. I added screenshots of the error below. 

Thank you for your help!

![Screenshot from 2019-09-26 15-31-10](https://user-images.githubusercontent.com/32446840/65729378-e686d380-e072-11e9-9ef1-8cd6a679ba3d.png)
![Screenshot from 2019-09-26 15-30-52](https://user-images.githubusercontent.com/32446840/65729379-e686d380-e072-11e9-8d97-9f6263fd0f00.png)

**Comment by AlexEMG** [comment]
Perhaps consider changing how many items are fetched etc.
see: https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/pose_estimation_tensorflow/dataset/pose_dataset_tensorpack.py#L187

https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/pose_estimation_tensorflow/dataset/pose_dataset_tensorpack.py#L255

**Comment by eleonoreduroyon** [comment]
Hi AlexEMG! 
I tried playing with different combinations but I still get the same error...

**Comment by AlexEMG** [comment]
I could just run the code on various machines (laptop, server etc.). Probably best to directly look for tensorpack issues?

@katierupp - have you seen this?

**Comment by katierupp** [comment]
@AlexEMG, Thanks for bringing this to my attention!

@eleonoreduroyon, I have a couple of suggestions. First, you could try decreasing the process_ratio variable in deeplabcut/pose_estimation_tensorflow/dataset/pose_dataset_tensorpack.py. The default is set to 6, which is relatively high, so you could begin by training your network with a process ratio of 1 or 2. 

If you continue getting the same error after decreasing the process ratio, here’s something else you can try. There is a warning at the top of your second image that mentions starting a process with ‘fork’ may consume extra memory, and suggests using ‘forkserver/spawn’ instead. It points you to this link to find out more: https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods. You can use this library to change the start process to ‘forkserver/spawn’. Alternatively, you could navigate to the directory where you have Tensorpack installed, then go to /tensorpack/utils/concurrency.py and manually change the start process from ‘fork’ to ‘forkserver/spawn’. 

Hopefully this helps, let me know if you are still running into problems after trying these.

**Comment by AlexEMG** [comment]
@katierupp  thanks for your comments!

**Comment by ppwwyyxx** [comment]
Setting `processratio` to a number > 1 does not make sense. There should be no benefit starting more processes than the number of CPU cores available. And each process will take memory, leading to OOM.
Setting `processratio` to 1 or 0.5 or smaller would be better. `num_prefetch` can also be smaller to reduce RAM usage.

**Comment by AlexEMG** [comment]
@eleonoreduroyon: can you test a small processratio? We will update the default in 2.1.

**Comment by eleonoreduroyon** [comment]
Hi everyone!

Thank you for all your input!
I modified the processratio to 0.5 and then 0.1. I also dropped num_prefetch to 50 and then 10. Additionally, I modified 'fork' to 'forkserver/spawn'. Despite all that, the error hasn't left... I added below the screenshots of my error and the modifications I've made. Any other ideas?


![Screenshot from 2019-09-30 16-03-56](https://user-images.githubusercontent.com/32446840/65922950-f6b4f080-e39b-11e9-9184-38e7152637f2.png)
![Screenshot from 2019-09-30 16-03-35](https://user-images.githubusercontent.com/32446840/65922951-f6b4f080-e39b-11e9-8cda-2f0dbc3abc61.png)
![Screenshot from 2019-09-30 16-02-55](https://user-images.githubusercontent.com/32446840/65922952-f6b4f080-e39b-11e9-924d-0fba94b8740b.png)
![Screenshot from 2019-09-30 16-02-33](https://user-images.githubusercontent.com/32446840/65922953-f74d8700-e39b-11e9-84a7-f8b61f6cdd0d.png)

**Comment by ppwwyyxx** [comment]
I think `cfg.get('processratio', .1)` does not change the `processratio` to .1, if `processratio` is already set in config. 

Please just set it with `cfg['processratio'] = 0.1`, and verify whether you successfully set it, by printing its value in `pose_dataset_tensorpack.py`.

Same goes with the other options.

**Comment by AlexEMG** [comment]
This is indeed the case, if the config file already contains the variable (which is true, after you run training once) then its value will not be overwritten.

**Comment by eleonoreduroyon** [comment]
Hi, 
Yes, you're right. In fact none of my modifications are being taken into account because I can see at the beginning processratio is not modified and it is still trying to call 'fork'. The warning message for fork is not modified although I changed it in the file. I got an additional error without calling anything after I tried to train once. Tried to train again the warning message is gone but it is still set to 'fork'...
![Screenshot from 2019-09-30 17-00-59](https://user-images.githubusercontent.com/32446840/65925150-8068bc00-e3a4-11e9-8b54-a0beecb2464a.png)
![Screenshot from 2019-09-30 17-01-17](https://user-images.githubusercontent.com/32446840/65925155-8363ac80-e3a4-11e9-852b-17be20b311b8.png)
![Screenshot from 2019-09-30 17-01-31](https://user-images.githubusercontent.com/32446840/65925160-86f73380-e3a4-11e9-8ccf-59e4597e30b9.png)
![Screenshot from 2019-09-30 16-59-07](https://user-images.githubusercontent.com/32446840/65925170-8bbbe780-e3a4-11e9-9118-7b1986e7f558.png)
![Screenshot from 2019-09-30 17-02-22](https://user-images.githubusercontent.com/32446840/65925184-9a0a0380-e3a4-11e9-94d8-4010b217354b.png)
![Screenshot from 2019-09-30 17-02-46](https://user-images.githubusercontent.com/32446840/65925182-99716d00-e3a4-11e9-9ec8-a29d17475819.png)
![Screenshot from 2019-09-30 17-03-03](https://user-images.githubusercontent.com/32446840/65925181-99716d00-e3a4-11e9-9d07-7e1504d99669.png)



![Screenshot from 2019-09-30 17-03-17](https://user-images.githubusercontent.com/32446840/65925191-9c6c5d80-e3a4-11e9-8903-8a61b6a52d1e.png)
![Screenshot from 2019-09-30 17-04-09](https://user-images.githubusercontent.com/32446840/65925188-9c6c5d80-e3a4-11e9-8273-e47056f69385.png)
![Screenshot from 2019-09-30 17-03-40](https://user-images.githubusercontent.com/32446840/65925190-9c6c5d80-e3a4-11e9-86bf-5f091e8f8234.png)

**Comment by eleonoreduroyon** [comment]
Hey guys!
I tried to use the other types of data augmentation by setting dataset_type to deterministic. This works with the default processratio and num-prefetch...
![Screenshot from 2019-09-30 17-16-13](https://user-images.githubusercontent.com/32446840/65925514-1c46f780-e3a6-11e9-8a9d-32bd42a8eea4.png)

**Comment by AlexEMG** [comment]
Firstly when training with setting dataset_type to deterministic, tensorpack and hence these variables will not be used... 

Secondly, for me on my desktop (and even laptop) the code runs & trains. Perhaps you do not have enough memory? Do you have an outdated computer? Are the frames very large?

**Comment by MMathisLab** [comment]
@eleonoreduroyon as an aside, for resnet_101 you will want to set `intermediate_supervision=True` ; I think that's not super clear in the docs, so I'll update this.

**Comment by eleonoreduroyon** [comment]
Hello everyone,

@AlexEMG: I'm not sure I understood your first comment. I don't see why I can't change the values of processratio in pose_dataset_tensorpack.py or /tensorpack/utils/concurrency.py.
 The computer I am using is new, I added below a screenshot of its general overview.If setting deterministic works, why wouldn't tensorpack not work?
The biggest frame size is :1920x1080. Is that too big? 

@MMathisLab: Will do, thank you for clarifying that!

![Screenshot from 2019-10-01 15-33-13](https://user-images.githubusercontent.com/32446840/66005656-f92d4e00-e460-11e9-8376-64af3ed20809.png)

**Comment by eleonoreduroyon** [comment]
Today I tried to continue training of a dataset with tensorpack (originally trained with deterministic setting) and I got a new error. I will add the screenshots below if it could possibly help...
![Screenshot from 2019-10-01 16-35-10](https://user-images.githubusercontent.com/32446840/66008164-1e728a00-e46a-11e9-8d2a-9b70b0d58745.png)
![Screenshot from 2019-10-01 16-35-41](https://user-images.githubusercontent.com/32446840/66008167-22061100-e46a-11e9-9251-c022a290b6e9.png)
![Screenshot from 2019-10-01 16-35-59](https://user-images.githubusercontent.com/32446840/66008173-25010180-e46a-11e9-8399-fa975ca06ce4.png)
![Screenshot from 2019-10-01 16-36-17](https://user-images.githubusercontent.com/32446840/66008175-26cac500-e46a-11e9-84c1-cd3ab9d07e70.png)
![Screenshot from 2019-10-01 16-36-31](https://user-images.githubusercontent.com/32446840/66008182-28948880-e46a-11e9-978d-7f9b71228cb2.png)

**Comment by AlexEMG** [comment]
Maybe I'm misunderstanding what you did, but what I meant is that the deterministic loader (https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/pose_estimation_tensorflow/dataset/pose_dataset_deterministic.py) does not use tensorpack, so it is not a test of tensorpack. 

The error looks like the same problem: resource exhaust error... 

1920x1080 is pretty big for a GTX 1070 (but could work), I guess it works with the **default loade**r? Can you try to set global_scale to 0.2 and scaleratio=1.0 (in the pose_config file) and then run it with tensorpack?

**Comment by eleonoreduroyon** [comment]
Oh yeah okay I get it!
I changed the global_scale and the modification was taken into account. However for scaleratio, I modified it in pose_dataset_tensorpack.py and those modifications are not being taken into account (just like processratio).

Yes the default and deterministic are both working. Tensorpack still isn't..

**Comment by eleonoreduroyon** [comment]
I am getting a new error today, if that can help:
![Screenshot from 2019-10-02 16-07-11](https://user-images.githubusercontent.com/32446840/66088246-4b3ca500-e52f-11e9-9054-3e98faa53155.png)
![Screenshot from 2019-10-02 16-07-38](https://user-images.githubusercontent.com/32446840/66088249-4d9eff00-e52f-11e9-8196-d7cca188c7c7.png)
![Screenshot from 2019-10-02 16-07-54](https://user-images.githubusercontent.com/32446840/66088252-4f68c280-e52f-11e9-8cee-76bf95cbdd0f.png)
![Screenshot from 2019-10-02 16-08-14](https://user-images.githubusercontent.com/32446840/66088257-51328600-e52f-11e9-9901-f1e4f3add129.png)
![Screenshot from 2019-10-02 16-08-27](https://user-images.githubusercontent.com/32446840/66088259-5263b300-e52f-11e9-9dbc-073969be92a9.png)
![Screenshot from 2019-10-02 16-08-42](https://user-images.githubusercontent.com/32446840/66088260-5394e000-e52f-11e9-80d8-c9a478bf8ce7.png)

**Comment by ppwwyyxx** [comment]
Your error logs show the same error : memory error.

Your logs show that you are still openning way too many processes. The log shows "Worker-54" which mean you start at least 54 processes.

The safest way to change the number of processes is to modify https://github.com/AlexEMG/DeepLabCut/blob/e3cb6a96e52f7a16195a59cab4a403ff51fd337a/deeplabcut/pose_estimation_tensorflow/dataset/pose_dataset_tensorpack.py#L256-L259 directly: just change both `num_proc` to 1. Your changes on `processratio` still seem to be ineffective in reducing the number of processes.

**Comment by eleonoreduroyon** [comment]
I have modified that line directly but it is still not being taken into account..
![Screenshot from 2019-10-03 15-49-12](https://user-images.githubusercontent.com/32446840/66169740-4262d680-e5f6-11e9-92c1-9649edc42d0b.png)

![Screenshot from 2019-10-03 15-47-00](https://user-images.githubusercontent.com/32446840/66169681-15aebf00-e5f6-11e9-8329-b77c4e940510.png)

**Comment by ppwwyyxx** [comment]
That probably means you're not running the version of code that you're modifying

**Comment by eleonoreduroyon** [comment]
I completely agree with you but I am editing the only version of the file I have as you can see in the screenshot. If you compare the location to the ones in the errors, they are the same... I am very confused...
![Screenshot from 2019-10-03 17-06-00](https://user-images.githubusercontent.com/32446840/66172392-7f33cb00-e600-11e9-8a17-481c3001b62e.png)

**Comment by ppwwyyxx** [comment]
![1003-17:11:31](https://user-images.githubusercontent.com/1381301/66172527-e05b9e80-e600-11e9-8712-ce3bdc08e7d5.png)
That doesn't read the same to me. But anyway I don't think I would be able to give help on installation.

**Comment by eleonoreduroyon** [comment]
Hi everyone!

@ppwwyyxx Thank you for pointing it out. Indeed, I was editing the wrong file; the real file was a hidden file that's why I couldn't see it. 

After modifying the processratio to 1,global_scale to 0.2,  scaleratio to 1.0, num_prefetch to 10 and ''fork'' to ''forkserver/spawn'', training with tensorpack works!

Thank you for all your help & patience,
Eleonore
