### ISSUE TITLE
Missing optional dependency 'tables'

### ISSUE THREAD

**Issue by freesdyla** [DeepLabCut/DeepLabCut#431]
OS: Windows 10
DeepLabCut Version 2.0.9
Installed DeepLabCut anaconda environment dlc-WindowsGPU.

I was trying to run the Deom_labeledexample_Openfield, but ran into this problem. I tried different versions of pytables, but that did not help.
![missing optinal dependency 'tables'](https://user-images.githubusercontent.com/10214200/65837468-66a07980-e2bd-11e9-96c0-e2ef87a73d5d.PNG)

**Comment by MMathisLab** [comment]
could you please check out some these other issues/solutions? https://github.com/AlexEMG/DeepLabCut/search?q=pytables&type=Issues

https://github.com/AlexEMG/DeepLabCut/issues/377 

https://github.com/AlexEMG/DeepLabCut/issues/398

**Comment by cgutierrez-Ibanez** [comment]
This happened to me the other day in a new Windows 10 install (installed from the conda GPU environment files).

what fixed it was:

pip uninstall numpy==1.14.5
conda install numpy==1.14.5

**Comment by freesdyla** [comment]
The following solution solved the problem. Thanks!


> This happened to me the other day in a new Windows 10 install (installed from the conda GPU environment files).
> 
> what fixed it was:
> 
> pip uninstall numpy==1.14.5
> conda install numpy==1.14.5

**Comment by MMathisLab** [comment]
great, I will update the conda file, thanks @cgutierrez-Ibanez

**Comment by linussun** [comment]
Still an issue, I had to uninstall with pip and reinstall with conda and dependency on 'tables' error went away.
