### ISSUE TITLE
Label not refreshing on GUI

### ISSUE THREAD

**Issue by shreyapandit** [DeepLabCut/DeepLabCut#432]
Hi there,

Thanks for your amazing work! 

I am on Windows and facing some issues.

1. Trying to add a label to pre-config but after re-running label_frames script, the new label doesn't appear on labeling GUI.
<img width="1280" alt="Screen Shot 2019-10-01 at 12 17 38 AM" src="https://user-images.githubusercontent.com/836757/65933820-0dca0180-e3e1-11e9-94ca-c149b6c7b587.png">

2. I have two projects, in the first, the labeled info is saved in the same folder whereas in the other, a separate folder called <video_id>_labelled is created. Could you help explain why?

<img width="1280" alt="Screen Shot 2019-10-01 at 12 18 44 AM" src="https://user-images.githubusercontent.com/836757/65933824-13bfe280-e3e1-11e9-921e-3babcef1b57f.png">

**Comment by meet10may** [comment]
There is no pre-config file in the project. Have you changed the file names and structure? Ideally, once you have created the project, you should have the **config.yaml** file. The entire project is linked to this specific file. I do not see the "**else**" as a body part in the yaml file. Have you deleted some of the bodyparts? 
Also, which version of DLC are you using? Please fill out the template

**Comment by AlexEMG** [comment]
Indeed, you need to add the new `bodypart` in the corresponding `config.yaml` file of the project.

**Comment by shreyapandit** [comment]
Thanks! that was the issue, I was editing the wrong file. Once I changed the config.yaml, everything was smooth. I am on deeplabcut 2.0.9
