### ISSUE TITLE
ModuleNotFoundError: pandas.io.formats.csvs

### ISSUE THREAD

**Issue by 165shadow11** [DeepLabCut/DeepLabCut#434]
**Windows 10 , Deep Lab Cut 2.0.9**

OS: [Windows 10]
DeepLabCut Version [2.0.9] 
Browser [Chrome (Google Colab)]

I am using the GPU, Python 3, run time in Google Colab.

When trying to create a training data set in Colab, i receive an error, that the pandas.io.format.csvs module is not found. Specifically, this error occurs when I run the function deeplabcut.create_training_dataset().

**Screenshots**
![image](https://user-images.githubusercontent.com/55115888/65994814-36461000-e462-11e9-9c72-051fd14c20a9.png)

**Comment by MMathisLab** [comment]
Hi, when you import deeplabcut, did you click "reset runtimes?"

**Comment by 165shadow11** [comment]
Hey,

Thanks for the response. No, I didn't because whenever I do, the runtime
crashes and Colab refuses to reconnect until I reset all of the runtimes.

**Comment by MMathisLab** [comment]
could also be related to #433; either you can locally import and/or this will be updated in the next release!
