### ISSUE TITLE
Octopus eye-tracking

### ISSUE THREAD

**Issue by markt** [DeepLabCut/DeepLabCut#435]
Hello DeepLabCut team!

I study neuroscience and computer science at Dartmouth College and work in a lab studying octopus cognition. For my senior thesis in CS, I am developing an eye-tracking tool for octopus researchers. My plan is to map out the environment of the tank and use DeepLabCut to track the eye locations of the octopus, then from there determine what the octopus is looking at.

While I intend to start experimenting with 3D calibration in the underwater environment, I was first wondering if you had any suggestions as I began my project (e.g. what is the best configuration of cameras? Can the cameras be outside of the tank? etc.) Also if you have any advice about generally tracking octopuses using DeepLabCut that would be greatly appreciated.

Thank you,
Mark

**Comment by MMathisLab** [comment]
Dear Mark, as we please ask on the main README, please only post code bug reports and issues on GitHub. We have two forums for other questions: https://forum.image.sc/tags/deeplabcut and https://gitter.im/DeepLabCut/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge  ie see here: https://github.com/AlexEMG/DeepLabCut/blob/master/README.md
