### ISSUE TITLE
Hi, I am currently using 3D DLC 2.0.9 and so far I think it is not possible to use more than 2 cameras, is that correct or am I doing it wrong?

### ISSUE THREAD

**Issue by schrista** [DeepLabCut/DeepLabCut#436]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MMathisLab** [comment]
you can use the 3D code for 2 cameras: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/Overviewof3D.md or use anipose that is built for  > 2 cameras with deeplabcut: https://github.com/lambdaloop/anipose.
