### ISSUE TITLE
Running examples on MacOS using Jupyter notebook

### ISSUE THREAD

**Issue by shreyapandit** [DeepLabCut/DeepLabCut#439]
**Your Operating system and DeepLabCut version**
MacOSX High Sierra,  anaconda environment, dlc 2.0.9
Browser [e.g. chrome, safari]: Chrome

**Describe the problem**
I wish to run the Reaching example as documented here: https://github.com/AlexEMG/DeepLabCut/blob/master/examples/Demo_labeledexample_MouseReaching.ipynb
When I run the notebook, it says I need a framework build of python and the kernel dies. I do have wxpython installed in my environment.

Does this mean I can't run the example notebooks on MacOS?

**How to Reproduce the problem**
1. Launch jupyter notebook using the python kernel set to the conda envieonment that has DLC installed.
2. Try running an example notebook. I ran https://github.com/AlexEMG/DeepLabCut/blob/master/examples/Demo_labeledexample_MouseReaching.ipynb

**Screenshots**

<img width="799" alt="Screen Shot 2019-10-02 at 4 57 11 PM" src="https://user-images.githubusercontent.com/836757/66081298-b8ebcf80-e535-11e9-9bc7-08aee5598e22.png">

**Additional context**

**Comment by shreyapandit** [comment]
A note: This is my own custom anaconda environment, which might be the issue? Trying to create a fresh env using the supplied CPU yaml for DLC and will report back

**Comment by shreyapandit** [comment]
Update: I made a fresh conda environment using the dlc-MaOS-CPU yaml file which went through successfully. However, I get the same error when I try to run the demo notebook (screenshots below)

My conda env is the deeplabcut recommended one (Marked by * on the menu)
<img width="767" alt="Screen Shot 2019-10-02 at 5 16 54 PM" src="https://user-images.githubusercontent.com/836757/66082681-9f985280-e538-11e9-94c5-5e024ad08458.png">

Launched the notebook theough the correct recommended conda env


<img width="1031" alt="Screen Shot 2019-10-02 at 5 18 58 PM" src="https://user-images.githubusercontent.com/836757/66082738-c5255c00-e538-11e9-9872-eeee1385491e.png">

Any help would be appreciated, thanks!

**Comment by MMathisLab** [comment]
>  Does this mean I can't run the example notebooks on MacOS?

You must use a framework build, correct. Please see the docs: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/UseOverviewGuide.md#option-1-demo-notebooks

**Comment by shreyapandit** [comment]
Got it, thanks for sharing the link!
