### ISSUE TITLE
Logic in pose-tensorflow/nnet/pose_net.py fails for tensorflow vsn. 1.10

### ISSUE THREAD

**Issue by wagenadl** [DeepLabCut/DeepLabCut#44]
**Describe the bug**
The file "pose-tensorflow/nnet/pose_net.py" tests for tensorflow version using logic that worked great for versions up to 1.9, but fails for versions beyond that.

**To Reproduce**
1. Follow the instructions for training on the website, using tensorflow vsn. 1.10
2. Run the "train.py" script
4. Observe error about "False" not being a legal value for scale.

**To Fix**
(Sorry, I could have created a pull request, but I didn't want to clone the whole project just for one trivial bug.)
Replace code
        vers = tf.__version__
        if float(vers[0:3]) < 1.4:
(line 51 and 52 in pose-tensorflow/nnet/pose_net.py)
with something like
        vers = tf.__version__
        vers = vers.split(".")
        if float(vers[0]) < 1 or (float(vers[0])==1 and float(vers[1])<10):
Thanks for great code. You are helping my student very kindly.
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by imagejan** [comment]
Just an aside:

> (Sorry, I could have created a pull request, but I didn't want to clone the whole project just for one trivial bug.)

Did you know you can edit files directly on GitHub (using the pencil icon)? If it's just a small change, you can submit pull requests like this without having to clone the repository.

**Comment by AlexEMG** [comment]
Thanks for raising this issue. Did you/anybody test if TF 1.10 works otherwise (with training, evaluation, etc)?

**Comment by wagenadl** [comment]
Yes, we did. It appears to work fine.

________________________________
