### ISSUE TITLE
pip install deeplabcut failed on Colab env

### ISSUE THREAD

**Issue by waterstar** [DeepLabCut/DeepLabCut#441]
**Your Operating system and DeepLabCut version**

Colab 

Please complete the following information about your system:

Colab

**Describe the problem**
1.  Login to colab.research.google.com
2. Open new Python 3 notebook
3. run a cell - !pip install deeplabcut
4. result as in following screenshot

**Screenshots**
![Screenshot 2019-10-05 at 9 17 23 PM](https://user-images.githubusercontent.com/8625997/66255498-a3d1a380-e7b6-11e9-979e-57c79cf0145c.png)

**Additional context**

**Comment by MMathisLab** [comment]
Yes, please look at other open issues - it will not work until we update the package later today. #434, #433 #440
