### ISSUE TITLE
label_frames() GUI: "Error - bodyparts must have unique labels! Please choose unique bodyparts in config.yaml file and try again"

### ISSUE THREAD

**Issue by sachaker** [DeepLabCut/DeepLabCut#443]
## Error with label_frames()
**System Specs**
Windows 10 10.0.16299 SP0, with an Anaconda Env, using DeepLabCut 2.0.8

**Problem**
With no notable changes to the system, in the past few days the label_frames() GUI crashes when I try to select data to label for new DLC models. When I run the function on an old config file it still works. However, I am able to create a new project, add videos and extract frames. The GUI loads at first, but as soon as I select a folder to label, the GUI crashes and a ValueError is thrown. This problem crashes Python sometimes as well. I have seen past errors with regards to wxPython and the solutions posed have not fixed my problem. It should also be noted that the DLC error regarding unique labels is not reflected in the cfg['bodyparts']. Finally, please note that we are storing and accessing the config files from a network server. I have tried storing both the project and videos locally, but to no avail, nor when I open a new command prompt.

**How to Reproduce the problem**
1. Create a new project
2. Extract frames
3. deeplabcut.label_frames()
4. Select a folder

**Screenshots**
![error1](https://user-images.githubusercontent.com/25079885/66273702-210c1f80-e86e-11e9-8d3a-b6e5484d9e32.PNG)
![error2](https://user-images.githubusercontent.com/25079885/66273704-22d5e300-e86e-11e9-87bb-84c5a6c9380d.PNG)

**Additional context**
I have had a similar issue in the past that was apparently related to wx, but it seemed resolved overnight.

**Comment by MMathisLab** [comment]
The error states you have non-unique labels in the config.yaml file - did you edit the file to include more body parts?

**Comment by sachaker** [comment]
Hi there,

The labels are unique and identical to all other config files for working projects.

Thank you for your timely response. Any other things I could be missing?

**Comment by sachaker** [comment]
Hi there,

Thanks for your timely response. 

The labels are unique and identical to all other config files for working projects. Anything obvious besides that that I could be missing?

**Comment by MMathisLab** [comment]
I’m not sure, as the error message in your screenshot seems quite clear to me - can you post the config file?

Here is the code: https://github.com/AlexEMG/DeepLabCut/blob/9a98571412e6770069577a12ed26e8f6a0462b8c/deeplabcut/generate_training_dataset/labeling_toolbox.py#L489


Which version of matplotlib do you have? (check with `matplotlib.__version__`), but given where the error occurs, this seems and issue with your config.yaml file

**Comment by sachaker** [comment]
You were right, there was a repeated body part hidden in the config file... I even had a colleague check and we didn't catch it! Thanks so much

**Comment by MMathisLab** [comment]
No problem ;)
