### ISSUE TITLE
Error Label Frames GUI: Gtk-WARNING (deeplabcut 2.1)

### ISSUE THREAD

**Issue by dtsaop** [DeepLabCut/DeepLabCut#444]
**Describe the bug**
By following the DeepLabCut Project Manager GUI: Tutorial i realised that during the step3: labeling process i am getting the following error: (part of the error)
```
(ipython:16313): Gtk-WARNING **: 10:50:25.172: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(ipython:16313): Gtk-WARNING **: 10:50:25.173: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(ipython:16313): Gtk-WARNING **: 10:53:02.007: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(ipython:16313): Gtk-WARNING **: 10:53:02.007: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

(ipython:16313): Gtk-WARNING **: 10:53:02.007: Negative content height -11 (allocation 1, extents 6x6) while allocating gadget (node button, owner GtkButton)

```
**To Reproduce**
1. Go to 'Label Frames'
2. Click on 'Ok' and then Load frames
3. Try to click on the bodyparts

**Screenshots**
![Screenshot from 2019-10-07 10-52-59](https://user-images.githubusercontent.com/55577749/66294490-c87e6600-e8f1-11e9-8644-40b20e82f57b.png)

**Desktop (please complete the following information about your system):**
 - OS: Ubuntu 18.04
 - DeepLabCut Version: 2.1

**Additional context**

**Comment by MMathisLab** [comment]
thanks. It's just a warning though, so it won't affect functionality.

**Comment by dtsaop** [comment]
Unfortunately affects the labelling process. I cannot select body parts for labelling and the "adjust marker size" box is not clickable.

**Comment by MMathisLab** [comment]
strange, meaning if you RIGHT click on the nose, for example, that does not work? the same error appears?

How did you install the package, i.e. what version of python and matplotlib do you have installed?

**Comment by dtsaop** [comment]
After reinstalling all the packages it seems it works now but the GTK warning is still on!
