### ISSUE TITLE
Error when upgrading to 2.1 on Windows (shapely does not work with pip but with conda)

### ISSUE THREAD

**Issue by bergem1t** [DeepLabCut/DeepLabCut#445]
**Describe the bug**
When making the update to version 2.1 (pip install -U deeplabcut) on a Windows machine, an error occurs during the installation of "shapely". It seem to work if shapely is already installed via conda.

**To Reproduce**
On a Windows machine, do: `pip install -U deeplabcut` or `pip install shapely`

**Solution**
use conda
- `conda install shapely`
- `pip install -U deeplabcut`

**Screenshots**
![DLC_upgrade_error_screenshot](https://user-images.githubusercontent.com/16578927/66300491-b1417780-e8f5-11e9-86ef-09cfe90d55c9.PNG)
![shapely_error_screenshot](https://user-images.githubusercontent.com/16578927/66300506-b999b280-e8f5-11e9-8d2e-d95a26a96910.PNG)

**Desktop (please complete the following information about your system):**
 - OS: Win10/Win7 
-  Anaconda
 - DeepLabCut 2.0.9 -> Deeplabcut 2.1.0

**Comment by MMathisLab** [comment]
Indeed, please see the new conda env: https://github.com/AlexEMG/DeepLabCut/blob/master/conda-environments/dlc-windowsCPU.yaml

https://github.com/AlexEMG/DeepLabCut/blob/master/conda-environments/dlc-ubuntu-GPU.yaml
