### ISSUE TITLE
Shapely is required with DeepLabCut 2.1+ on WINDOWS!

### ISSUE THREAD

**Issue by cgutierrez-Ibanez** [DeepLabCut/DeepLabCut#446]
Hi

I had deeplabcut  (2.0.9) working on a Windows 10 machine.  When installing deeplabcut 2.1, using

pip install deeplabcut==2.1

I get this error: 

 Downloading https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz (225kB)
     |████████████████████████████████| 235kB ...
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\User\Anaconda3\envs\dlc-windowsGPU\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-lcxjp07d\\Shapely\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-lcxjp07d\\Shapely\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-lcxjp07d\Shapely\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\AppData\Local\Temp\pip-install-lcxjp07d\Shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\User\AppData\Local\Temp\pip-install-lcxjp07d\Shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "C:\Users\User\Anaconda3\envs\dlc-windowsGPU\lib\ctypes\__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

works (at least GUI loads, havent try anything else) if you first do :

conda install Shapely

and then: 

pip install deeplabcut==2.1

cheers. 

Cristian

**Comment by MMathisLab** [comment]
yes, same as issue #445 - please note we updated the conda files, to include Shapely. We suggest creating a new conda file, as several dependencies changed.

**Comment by MMathisLab** [comment]
A note to others, I would HIGHLY recommend just building a NEW env for 2.1, as Shapely is in the latest conda files! https://github.com/AlexEMG/DeepLabCut/tree/master/conda-environments

or here: www.deeplabcut.org
