### ISSUE TITLE
KeyError: 'No object named df_with_missing in the file'

### ISSUE THREAD

**Issue by 165shadow11** [DeepLabCut/DeepLabCut#447]
**Windows 10; DeepLabCut 2.1.0**

OS: [Windows 10]
DeepLabCut Version [2.1] 
Browser [Chrome]

When trying to create a training dataset in Colab, I run into the key error, 'No object named df_with_missing in the file'. I'm not sure what the issue actually is.

**How to Reproduce the problem**
1. Go to the DLC Colab notebook
2.  Run deeplabcut.create_training_dataset(path_config_file) after completing the previous appropriate steps.

**Screenshots**
![image](https://user-images.githubusercontent.com/55115888/66343781-5c642800-e91a-11e9-9b7d-f63e7df391e5.png)

**Comment by MMathisLab** [comment]
Can you be sure there is an .h5 file within your labeled-data folder? Seems it may be missing. it should say something like ``CollectedData_Matthew.h5``

**Comment by 165shadow11** [comment]
Yes there is one, which is why I'm confused.

**Comment by MMathisLab** [comment]
can you recreate the file, remove the older one, and then run: ``deeplabcut.convertcsv2h5`` to recreate it? 

Did you rename the scorer or video paths, etc? The only thing you should change when you put your project on google drive is the `project_path` in the `config.yaml` file. 

``
deeplabcut.convertcsv2h5(config, userfeedback=True, scorer=None)
``

**Comment by 165shadow11** [comment]
Sorry, do you want to me remake the related CSV file and then run `deeplabcut.convertcsv2h5` or remake the h5 file, and then run that function on it?

**Comment by 165shadow11** [comment]
Ok, I am no longer getting the 'df_with_missing' error, but now it is telling me my h5 file was not found.
![image](https://user-images.githubusercontent.com/55115888/66416792-aa396880-e9cc-11e9-8472-1aac1cac52b3.png)

**Comment by 165shadow11** [comment]
The problem has been fixed. When I used `%ls` on the video directory, the h5 file was showing up as `CollectedData_Ryan (1).h5`. So I used `rm` to remove that file and then reuploaded it. It took a couple of minutes for Colab and my Drive to sync up, but the training dataset has been created.
