### ISSUE TITLE
Video file path not found in Analysis_tools/MakingLabeledVideo.py

### ISSUE THREAD

**Issue by Umar-Ayub** [DeepLabCut/DeepLabCut#45]
**Describe the problem**
I think there is a bug in the MakingLabeledVideo.py and MakingLabeledVideo_fast.py
It basically doesn't generate the video for me due to a path syntax error (I think).

**Traceback**
C:\Users\ua12\Dropbox (Duke Bio_Ea)\Bhandawat Lab\Umar\Week of 8-13\DeepLabCut\Analysis-tools>py MakingLabeledVideo.py
Starting  ../videos/ ['4.avi']
Loading  4.avi and data.
The video was not analyzed with this scorer: DeepCut_resnet50_leg Wing TrackingAug15shuffle1_500
Other scorers were found, however: ['4DeepCut_resnet50_leg Wing TrackingAug15shuffle1_50000.h5']
Creating labeled video for: 4DeepCut_resnet50_leg Wing TrackingAug15shuffle1_50000.h5  instead.
Duration of video [s]:  32.23 , recorded with  30.0 fps!
Overall # of frames:  967 with cropped frame dimensions:  [1024, 736]
Generating frames
100%|████████████████████████████████████████████████████████████████████████████████| 967/967 [04:03<00:00,  3.97it/s]
Generating video
Traceback (most recent call last):
  File "MakingLabeledVideo.py", line 158, in <module>
    Dataframe = pd.read_hdf(dataname)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\pytables.py", line 347, in read_hdf
    'File %s does not exist' % path_or_buf)
FileNotFoundError: File 4DeepCut_resnet50_leg Wing TrackingAug15shuffle1_500.h5 does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MakingLabeledVideo.py", line 173, in <module>
    CreateVideo(clip,Dataframe)
  File "MakingLabeledVideo.py", line 131, in CreateVideo
    str(clip.fps), '-i', 'file%04d.png', '-r', '30', '../'+vname + '_DeepLabCutlabeled.mp4'])
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Additional Comments**
Any help would be appreciated in debugging this. I managed to train a model succesfully but am having trouble generating the videos for analysis.

**Comment by MMathisLab** [comment]
Looks like the frames are correctly created, in the subfolder. However, the line 129:

```
subprocess.call([
        'ffmpeg', '-framerate',
        str(clip.fps), '-i', 'file%04d.png', '-r', '30', '../'+vname + '_DeepLabCutlabeled.mp4'])
```

fails. It states that File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 997, in _execute_child
startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified. Is fffmpeg not found?

**Comment by Umar-Ayub** [comment]
Thanks @MMathisLab. It turned out that ffmpeg was not installed `conda install -c conda-forge ffmpeg` fixed the issue for me.

**Comment by MMathisLab** [comment]
great! thanks!
