### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by Angel113110** [DeepLabCut/DeepLabCut#452]
**My Operating system and DeepLabCut version**
windows 10, with an Anaconda Env, & Deeplabcut 2.0.8

**Describe the problem**
I want to use yourowndata.ipnnb to create my project. First several steps are ok, there was no mistake. But when I use deeplabcut.label_frames function, it appears ok, it can display the folders I have saved extract frames. When I select one of these folders and click button. It occurs typeerror like this:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
D:\Anaconda\envs\dlc-windowsGPU\lib\site-packages\deeplabcut-2.0.8-py3.6.egg\deeplabcut\generate_training_dataset\labeling_toolbox.py in browseDir(self, event)
    466         self.img = self.index[self.iter]
    467         img_name = Path(self.index[self.iter]).name
--> 468         self.norm,self.colorIndex = self.image_panel.getColorIndices(self.img,self.bodyparts)
    469 
    470 # Checking for new frames and adding them to the existing dataframe

D:\Anaconda\envs\dlc-windowsGPU\lib\site-packages\deeplabcut-2.0.8-py3.6.egg\deeplabcut\generate_training_dataset\labeling_toolbox.py in getColorIndices(self, img, bodyparts)
     84         im = cv2.imread(img)
     85         norm = mcolors.Normalize(vmin=0, vmax=np.max(im))
---> 86         ticks = np.linspace(0,np.max(im),len(bodyparts))[::-1]
     87         return norm, ticks
     88 

D:\Anaconda\envs\dlc-windowsGPU\lib\site-packages\numpy\core\function_base.py in linspace(start, stop, num, endpoint, retstep, dtype, axis)
    134     # and make sure one can use variables that have an __array_interface__, gh-6634
    135     start = asanyarray(start) * 1.0
--> 136     stop  = asanyarray(stop)  * 1.0
    137 
    138     dt = result_type(start, stop, float(num))

TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
```

Why this happened? Can you help me to handle it? Thanks!

**How to Reproduce the problem**

**Screenshots**

**Additional context**

**Comment by MMathisLab** [comment]
Seems an installation issue, also likely related to your other issue, #451- can you delete the environment and download the latest? 

Also, 2.1 has many new features you might want to use, including an easy GUI to run the whole project.

**Comment by Angel113110** [comment]
Dear author
  I have installed the latest version deeplabcut 2.1. But the same error is still exist. After select a folder which contain the extract images, it still say TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'. How to deal with this problem and use label GUI? Thanks!

**Comment by Angel113110** [comment]
I think it's not related to version.Above error in line 136, have  stop  = asanyarray(stop)  * 1.0 , and  asanyarray(stop) is NoneType. I think about this problem for long time and I still can't understand why it happened. I also try the easy GUI you supplied , the problem is the same. So I think it may be a bug in program and I wish I can get help from you. Thanks!

**Comment by MMathisLab** [comment]
It’s not a bug, it’s likely a broken numpy installation . Which version of numpy is installed? Can you import that alone, you are using our supplied yaml?

**Comment by MMathisLab** [comment]
^ are there extracted frames in the labeled-data folder?

**Comment by Angel113110** [comment]
Hi, author
Yes, I can find extracted images in labeled-data folder. I'm using the yaml you supplied. The numpy version is 1.17.2 . When I installed the Anaconda environment you supplied and deeplabcut 2.1 version, it automatically installed this numpy version. Is the numpy version wrong?

**Comment by MMathisLab** [comment]
No that’s fine, I’m just trying to understand what the error is. 

I cannot reproduce it, so I think there is something wrong with how it is installed. Could you just try to uninstall numpy and reinstall version numpy==1.15.4 ?

**Comment by Angel113110** [comment]
Hi, author
 When I installed the deeplabcut 2.1. I found the 2.1 has imageio 2.3.0. But one package named moviepy  1.0.1 need imageio version between 2.5.0 and 3.0.0. How to handle this problem?

**Comment by Angel113110** [comment]
I tried many version. But imageio version and moviepy version seemed always incompatible.

**Comment by Angel113110** [comment]
My installation steps are as follows:( I have installed all programs related to GPU before)
1. install the anaconda environment : dlc-windowsGPU
2. install nb_conda in dlc-windowsGPU 
3. pip install deeplabcut==2.1
Are my steps right?

**Comment by MMathisLab** [comment]
No, please delete the environment, then recreate it. Do not install anything else inside the environment, deeplabcut is already installed. You can open the yaml to see what is already installed.

**Comment by Angel113110** [comment]
Hi, author
That's impossible. I have tried in the environment. I use ipython and import deeplabcut. If I do not pip deeplabcut. I found I can't import deeplabcut. It said no module name 'deeplabcut'

**Comment by Angel113110** [comment]
Hi, author
  I delete and recreate the environment. But the same error happens. I have do nothing but install the environment. It really makes me confuse.  Can you help me?

**Comment by Angel113110** [comment]
Do I should change config.yaml content?

**Comment by MMathisLab** [comment]
You just commented on another thread asking how to label, seems the labeling GUI launches for you. I recommend reading the user guide.

**Comment by Ratoncito** [comment]
Hey Im having the same error... I installed the conda enviroment directly from the DEEPLABCUT.yaml file on your website. and create project worked fine. Then I labeled frames fine and then tries to check labels, I got an error from that and then when I fixed that error I rerun and now label frames doesnt work anymore... :(

**Comment by MMathisLab** [comment]
> Then I labeled frames fine and then tries to check labels, I got an error from that and then when I fixed that error 

can you please say what the error was, and what you did to fix it?

**Comment by Ratoncito** [comment]
okay yeah no problem. Here is a code chunk from my code, I move the DLC project off of anaconda and on to pycharm so I could debug easier and step through code. So basically when I would run  deeplabcut.check_labels(path_config_file)  command I would get this error -> https://stackoverflow.com/questions/12984426/python-pil-ioerror-image-file-truncated-with-big-images
so I added: from PIL import ImageFile and ImageFile.LOAD_TRUNCATED_IMAGES = True to my code and it fixed the error. Let me know if that was clear or not.

def check_labels():
    ImageFile.LOAD_TRUNCATED_IMAGES = True 
    deeplabcut.check_labels(path_config_file)

**Comment by Ratoncito** [comment]
I deleted old project and created new project so now things are working fine but I am concerned that this program is too unstable to use with actual large file sizes. I don't want to invest hours extracting and  labeling frames and training and then things break again...
