### ISSUE TITLE
Stuck on loading resnet (error in dataset)

### ISSUE THREAD

**Issue by ddonegan1** [DeepLabCut/DeepLabCut#453]
Ubuntu 18.04
Deeplabcut 2.1

I am able to get through to the start training but then stuck at loading the resnet.  It seems to be an error with Tensorflow: 
```


**_Starting with standard pose-dataset loader.
Initializing ResNet
WARNING:tensorflow:From /home/cns/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/cns/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/tensorflow/python/ops/losses/losses_impl.py:209: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Loading ImageNet-pretrained resnet_50_**

```

-I tried updating to the newer versions of TensorFlow (2.0) but that does not seem to help. 

Thanks,
Dane

**Comment by MMathisLab** [comment]
the error should not preclude training. Set the defaults display iterations (`display_iters`) to say 10 and then you will see the network training.

**Comment by ddonegan1** [comment]
I tried this earlier, but still does not load and ipython crashes. I had dlc 2.0 working before, but this new version seems to stop here.

**Comment by MMathisLab** [comment]
Can you post the log.txt file?

also we do not support tensorflow beyond 1.14 at this time.

**Comment by ddonegan1** [comment]
[log.txt](https://github.com/AlexEMG/DeepLabCut/files/3739312/log.txt)
I think this is it

**Comment by MMathisLab** [comment]
That log file seems it was never started, ie the message in your first post is not within it. Perhaps try to recreate the training set again and train. But, I cannot reproduce your error, as it seems all correct, and it does not crash for other users. 

Can you import TensorFlow and start a session independent of deeplabcut? https://github.com/AlexEMG/DeepLabCut/blob/master/docs/installation.md

**Comment by ddonegan1** [comment]
I reinstalled and tried again and still that problem. The log file is the same-without that error message. Also yes I can import tensorflow and start a session without the import deeplabcut.

**Comment by MMathisLab** [comment]
could you tell me what version of TF you have currently installed? could you take a screen video of the crash, if there is no error message?

**Comment by ddonegan1** [comment]
![Screenshot from 2019-10-17 17-08-40](https://user-images.githubusercontent.com/56432617/67022014-cfcb1e00-f100-11e9-9647-b9c998f2beed.png)
![Screenshot from 2019-10-17 17-07-10](https://user-images.githubusercontent.com/56432617/67022057-e4a7b180-f100-11e9-812a-bba589d08bd2.png)

Ill try the docker to see if that helps

**Comment by MMathisLab** [comment]
When it gets to the loading imagenet pretrained ... 

It just crashes the terminal? Or? and what does nvidia-smi say during this point?

**Comment by ddonegan1** [comment]
it stays like this and then python crashes.  Also I opened the nvidia-smi and there are no GPU processes running. Must be the issue

**Comment by MMathisLab** [comment]
yeah it's then likely not using your gpu and using your cpu, then it crashes due to out of memory error or such (depending on what your batch size is set to), so it's likely not installed correctly.

**Comment by ddonegan1** [comment]
Sorry I was wrong, the GPU is running (see bottom of nvidia-smi)

![Screenshot from 2019-10-17 19-01-54](https://user-images.githubusercontent.com/56432617/67030878-a2866c00-f110-11e9-9048-d94834e732b3.png)

**Comment by MMathisLab** [comment]
can you run the test script please? Download/git clone package, navigate to the terminal into examples, open in ipython, import deeplabcut and then run: ``run testscript.py``

**Comment by ddonegan1** [comment]
works with running the demo data! not sure why

**Comment by MMathisLab** [comment]
okay so it's something about your dataset; some inconsistency in config.yaml, or pose_cfg.yaml, or corrupted h5 data, but it's definitely not a bug or your installation. ;)

**Comment by ddonegan1** [comment]
the pose_cfg.yaml and config.yaml are identical.  not sure about h5 data?

**Comment by ddonegan1** [comment]
Figured it out.  The dimension of video was too small (76x70).  Thanks for your help!

**Comment by MMathisLab** [comment]
Awe, yes! There are min and max image inputs, glad it was just the data loading then!
