### ISSUE TITLE
how to use human-pretrained network ResNet-101 to train own dataset

### ISSUE THREAD

**Issue by Angel113110** [DeepLabCut/DeepLabCut#459]
**Your Operating system and DeepLabCut version**
win 10, with an Anaconda Env, & Deeplabcut 2.1

OS: Windows 10
DeepLabCut Version :2.1
Browser : IE

**Describe the problem**
I want to use pre-trained net resnet_101 on mpii to train my own net. I download and put all three files in ../pretrained/. I edit net_type to resnet_101 in config.yaml and pose_cfg.yaml. I also edit init_weights in pose_cfg.yaml. But when I run the code, it has this error:

ValueError                                Traceback (most recent call last)
<ipython-input-6-905ef229531c> in <module>
      1 path_config_file="D:\Body_analyse\Body_analyse-Angel-2019-10-18\config.yaml"
----> 2 deeplabcut.train_network(path_config_file)

D:\Anaconda\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py in train_network(config, shuffle, trainingsetindex, gputouse, max_snapshots_to_keep, autotune, displayiters, saveiters, maxiters, keepdeconvweights)
    127           train(str(poseconfigfile),displayiters,saveiters,maxiters,max_to_keep=max_snapshots_to_keep,keepdeconvweights=keepdeconvweights) #pass on path and file name for pose_cfg.yaml!
    128       except BaseException as e:
--> 129           raise e
    130       finally:
    131           os.chdir(str(start_path))

D:\Anaconda\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py in train_network(config, shuffle, trainingsetindex, gputouse, max_snapshots_to_keep, autotune, displayiters, saveiters, maxiters, keepdeconvweights)
    125 
    126       try:
--> 127           train(str(poseconfigfile),displayiters,saveiters,maxiters,max_to_keep=max_snapshots_to_keep,keepdeconvweights=keepdeconvweights) #pass on path and file name for pose_cfg.yaml!
    128       except BaseException as e:
    129           raise e

D:\Anaconda\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py in train(config_yaml, displayiters, saveiters, maxiters, max_to_keep, keepdeconvweights)
    135 
    136     # Restore variables from disk.
--> 137     restorer.restore(sess, cfg.init_weights)
    138     if maxiters==None:
    139         max_iter = int(cfg.multi_step[-1][1])

D:\Anaconda\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\training\saver.py in restore(self, sess, save_path)
   1266     if not checkpoint_management.checkpoint_exists(compat.as_text(save_path)):
   1267       raise ValueError("The passed save_path is not a valid checkpoint: "
-> 1268                        + compat.as_text(save_path))
   1269 
   1270     logging.info("Restoring parameters from %s", compat.as_text(save_path))

ValueError: The passed save_path is not a valid checkpoint: D:\Anaconda\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\mpii-single-resnet-101
 
How to solve the problem? Thanks!

**How to Reproduce the problem**
1. Download three files 
2. put in corresponding folder
3. edit init_weights
4. edit net_type

**Comment by AlexEMG** [comment]
Please check out this example notebook on how to use the pretrained human model: https://github.com/AlexEMG/DeepLabCut/blob/fafac2f9cdd91139e697cce46741532b86a01d20/examples/COLAB_Human_Project_DEMO.ipynb

Also check out the forum discussion on this: https://forum.image.sc/t/pretrained-resnet-on-mpii-human-pose-data/21567/9

**Comment by Angel113110** [comment]
Hi,author
  Thanks for replying. Unfortunately, the reply can't solve my problem. I want to use pre-trained model to train my network   on my own dataset. I download the files and update parameters , put files in corresponding folder. I have edit net type to resnet_101. I can't solve above error when I run deeplabcut. I meet value error.Can you give me some help? Thanks!

**Comment by Angel113110** [comment]
I should use full name or mpii-single-resnet-101?

**Comment by Angel113110** [comment]
My error:
ValueError: The passed save_path is not a valid checkpoint: D:\Anaconda\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\mpii-single-resnet-101

**Comment by Angel113110** [comment]
Hi, author
  If I directly use deeplabcut.create_pretrained_human_project to create my project on my computer rather than google colab. Can it work?

**Comment by AlexEMG** [comment]
Because it can be tricky to link the weights for some users, we made this function:
https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/create_project/human_dataset.py#L46

 The function works on colab/collaborators/ipython/... wherever you have Deeplabcut installed.

As indicated in the docstrings it creates a new project but with the pretrained human network that you can use on your data.

________________________________

**Comment by AlexEMG** [comment]
Yes there is a function called: analyze_time_lapse_frames

See:
https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/pose_estimation_tensorflow/predict_videos.py#L610

And of course the user guide https://www.nature.com/articles/s41596-019-0176-0


________________________________
