### ISSUE TITLE
nvidia-docker problems (DOCKER Question + GPU driver installation)

### ISSUE THREAD

**Issue by rglanz** [DeepLabCut/DeepLabCut#46]
I am having trouble launching the docker after installation. Here is the line where I get an error:

`GPU=1 bash ./dlc-docker run -d -p 2351:8888 -e USER_HOME=$HOME/DeepLabCut --name alex_GPU1 dlc_user/dlc_tf1.2`

The error is:

` initialization error: driver error: failed to process request\\\\n\\\"\"": unknown.`

I believe the issue is that nvidia-docker is no longer supported, and I had to install nvidia-docker2. The error seems to come when `nvidia-docker` is called from `./dlc docker`.

**Comment by MMathisLab** [comment]
can we move this to the docker4deeplabcut repo? [did nvidia-docker2 solved the error?; but this is not a error we see, and we run the nvidia-docker daily...]

**Comment by AlexEMG** [comment]
Also seems to be a driver issue? https://github.com/NVIDIA/nvidia-docker/issues/726

**Comment by rglanz** [comment]
Do you have any suggestions for installing the driver from Ubuntu 16?

I've been trying to install via the deb file at https://developer.nvidia.com/cuda-80-ga2-download-archive, but when I work through the workflow on the Docker4DeepLabCut repo, I get stuck after trying to check my nvidia-docker:

`nvidia-docker run --rm nvidia/cuda nvidia-smi`

with it telling me:

`Error: Could not load UVM kernel module.`

**Comment by MMathisLab** [comment]
Seems it's not installed correctly. It sounds like your driver, CUDA, and TF versions do not align. If you are using CUDA 8, then your driver cannot be the latest (check out the list: https://stackoverflow.com/questions/30820513/what-is-version-of-cuda-for-nvidia-304-125/30820690#30820690) 

also so this: https://github.com/NVIDIA/nvidia-docker/issues/319

However, you just need the correct **driver** installed to use the Docker for DeepLabCut (i.e. I don't have CUDA installed at all on my Ubuntu 16.04 computer, I just have an appropriate driver: 
```$ nvidia-smi
Wed Aug 22 15:26:17 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90

$ nvcc --version
The program 'nvcc' is currently not installed.

I would uninstall any CUDA you have, and just install the driver... good luck!

**Comment by MMathisLab** [comment]
also, if you don't have nvidia-docker, but instead installed nvidia-docker, you will have to modify the dlc-docker file: https://github.com/AlexEMG/Docker4DeepLabCut/blob/master/dlc-docker (as it calls nvidia-docker)

**Comment by rglanz** [comment]
So it looks like my issue is getting the driver installed successfully. I can install nvidia-384 with

`sudo apt-get install nvidia-384`

but anytime I run

`nvidia-smi`

it throws an error. I don't know if you remember how you initially installed the driver, but following directions [here](https://gist.github.com/wangruohui/df039f0dc434d6486f5d4d098aa52d07) and [here](https://gist.github.com/iSkore/ad043b64c8576d8eb818f7027da18b09) have not been successful for me.

**Comment by MMathisLab** [comment]
You might want to try to do a clean install, so I would first remove any NVIDIA items installed..... https://askubuntu.com/questions/206283/how-can-i-uninstall-a-nvidia-driver-completely 

and 

https://askubuntu.com/questions/902636/nvidia-smi-command-not-found-ubuntu-16-04 

(also, you might consider joining our slack group)

**Comment by rglanz** [comment]
That last link worked! Got stuck in a login loop afterwards, but just rebooted again and it was fine. However after installing the nvidia-docker, I couldn't run it using your test:

`nvidia-docker run --rm nvidia/cuda nvidia-smi`

I had to run this first:

`sudo service nvidia-docker start`

from [nvidia-docker issue #437](https://github.com/NVIDIA/nvidia-docker/issues/437).

Thanks!

**Comment by rckoepke** [comment]
> also, if you don't have **nvidia-docker**, but instead installed **nvidia-docker,** you will have to modify the dlc-docker file: https://github.com/AlexEMG/Docker4DeepLabCut/blob/master/dlc-docker (as it calls nvidia-docker)

Is the second 'nvidia-docker' here supposed to be 'nvidia-docker2'?
