### ISSUE TITLE
[Windows 10] Training in batches. How to use imgaug loader.

### ISSUE THREAD

**Issue by jinu-jang** [DeepLabCut/DeepLabCut#460]
**Operating system and DeepLabCut version**

**OS**: Windows 10 with Anaconda env built off of provided `windows-gpu.yaml`
**DeepLabCut Version**: 2.1.1
**GPU**: NVIDIA Quadro P5000 (16GB)

**Describe the problem**

When running `.train_network()`, we get the following output.

`Switching batchsize to 1, as default/tensorpack/deterministic loaders do not support batches >1. Use imgaug loader.`

With that output, our GPU usage goes up at most 15%, and our training speed is very slow.
We're hoping to be able to use batch training to improve our speed.

**Screenshots**

![image](https://user-images.githubusercontent.com/11640155/67356578-95aab380-f528-11e9-8e9e-0cdd7da8aeea.png)

**Comment by AlexEMG** [comment]
You just need to set: 
dataset_type='imgaug'
in the model's pose_config.yaml file!

Check out the docs: https://github.com/AlexEMG/DeepLabCut/blob/ca93b3e7a69c674abb31bfaa812cb38940a5d598/docs/functionDetails.md#g-train-the-network

And check out this testscript to see how to change the loader:
https://github.com/AlexEMG/DeepLabCut/blob/master/examples/testscript_openfielddata_augmentationcomparison.py

**Comment by AlexEMG** [comment]
Btw. also note that for training you need to set the batchsize also in the model's pose_config.yaml file (not the config file of the project, which is for inference).
