### ISSUE TITLE
how to add more frames to already trained network

### ISSUE THREAD

**Issue by mawaishafeez** [DeepLabCut/DeepLabCut#461]
**Your Operating system and DeepLabCut version**
Ubuntu 16.04 LTS, with a Docker4Deeplabcut, & DeepLabCut 2.1.

**Describe the problem**
trained a network for 20 videos and it worked well. But then I decided to train the network on 20 more videos. For that i created a new project with those 40 videos but labelled only new 20 videos and copy-pasted already labelled 20 videos (containing frames, .h5 & .csv files) from the previous project and then put the system on training. Upon evaluation it seems it was trained only on those new 20 videos. Now i have two projects trained separately on 20 videos each. Is there anyway that i can merge training dataset from those projects. Or what can i do to make a single project with already existing projects?

**Comment by AlexEMG** [comment]
Firstly, you could have added additional frames to the original project via the tools of DeepLabCut (outlier frame detection/relabeling or just plainly adding more data). Please check out the user guide: 
https://www.nature.com/articles/s41596-019-0176-0

Secondly, you can always "manually share labeled data" across projects (if they have the same scorer name/bodyparts) by copying the folders into the other folder and adding the corresponding video in the video_sets entry.  

See the user forum: https://forum.image.sc/t/merging-deeplabcut-training-sets/28140/2
