### ISSUE TITLE
Network Training Timeout?

### ISSUE THREAD

**Issue by nmtimme** [DeepLabCut/DeepLabCut#463]
Hello

Here is the background info:

OS: Windows 10
Anaconda 3
CPU
DeepLabCut Version: I'm not sure of the precise version. I downloaded it from git ~Oct. 24 2019.

See screen shots below that capture what I describe.

Similar to issue #303, my terminal gets stuck on "Starting training...". After about an hour of running, ipython stops without error. Based on the suggestions for issue #303, I checked to make sure the weights had been downloaded and were in the proper location, and they are. 

I adjusted the display_iters parameter from 1000 to 100 and reran the training. I can see that the training is running, but after about an hour (~900 iterations), ipython stops without error. I tried to evaluate the network, but I got an error saying that it hadn't been trained.

So, I adjusted save_iters to 100. Now, when I evaluate the network, the evaluation runs. 

However, I'm only able to get about 900 iterations completed because ipython (or something else) times out. Obviously, this is not ideal. Does anyone have any suggestions about how to fix this issue? I did a bit of searching for ipython time out errors, but I couldn't find much. Admittedly, I'm new to python, so perhaps I've just missed the answer. I'd greatly appreciate any advice. Thanks!

~Nick

![image](https://user-images.githubusercontent.com/38138179/67709683-ceb5ae80-f994-11e9-8100-e3fc2317a731.png)
![image](https://user-images.githubusercontent.com/38138179/67709702-dc6b3400-f994-11e9-8064-a2a97d09972e.png)
![image](https://user-images.githubusercontent.com/38138179/67709724-e68d3280-f994-11e9-9833-ad37e4bae837.png)

**Comment by MMathisLab** [comment]
in your display/power settings, do you have any sort of timer for low power mode/sleep or such?

**Comment by nmtimme** [comment]
Thanks for getting back to me! 

I looked through all the power management settings and I couldn't find anything that would cause this, to the best of my knowledge. To be clear, the terminal doesn't close and the computer doesn't shut down, ipython just stops.

**Comment by annieandbrianneedacode** [comment]
The same thing happened to me and stops at 872 iterations.

**Comment by AlexEMG** [comment]
I'm afraid that this is not a DeepLabCut issue. It might be CUDA/TF/your hardware/ etc. 

Can you train on your CPU for more iterations?

**Comment by MMathisLab** [comment]
Seems a windows only issue; now reported here (#463), and #468 https://github.com/AlexEMG/DeepLabCut/issues/479#issuecomment-549919559

Can all of you report:

CUDA version, TensorFlow Version, and how you are running the code (ipython, python, GUI, jupyter notebook, etc).

**Comment by wyattray1364** [comment]
Same problem. win10, cudatoolkit-10.0.130, tensorflow-1.13.1, jupyter lab, CUDA-10.1, nvidia driver-441.12

**Comment by AlexEMG** [comment]
Strange. Can you please share your complete conda environment so we can try to reproduce this.

________________________________

**Comment by annieandbrianneedacode** [comment]
Running on my CPU, Tensorflow version 1.12.0, on ipython

**Comment by annieandbrianneedacode** [comment]
Sure, how can I share the env?

**Comment by AlexEMG** [comment]
conda env export > environment.yml

Also can you share the pose_comfig.yaml file.

________________________________

**Comment by wyattray1364** [comment]
many thanks

Alexander Mathis <notifications@github.com> 于2019年11月6日周三 下午5:48写道：

**Comment by annieandbrianneedacode** [comment]
Here is the pose_config.yaml file 

[pose_cfg.zip](https://github.com/AlexEMG/DeepLabCut/files/3814515/pose_cfg.zip)

**Comment by annieandbrianneedacode** [comment]
Sorry forgot to send the env file. 
[environment.zip](https://github.com/AlexEMG/DeepLabCut/files/3814985/environment.zip)

**Comment by MMathisLab** [comment]
@wyattray1364 CUDA >10 will not work. Currently only up to CUDA 10 with TF 1.14 is supported. https://github.com/AlexEMG/DeepLabCut/blob/master/docs/installation.md#the-most-common-new-user-hurdle-is-installing-and-using-your-gpu

**Comment by MMathisLab** [comment]
please also see #468 

This turns out to be a size issue of the GPU, as mobileNet worked, and gpu was full. Please note we recommend a 1080 ti or higher, as most lab-applications use larger frames sizes, and the gpu memory size becomes very important for performance.

**Comment by AlexEMG** [comment]
This might be due to a corrupt image (see other issue), or an erroneous installation of TF.
