### ISSUE TITLE
Output scoremaps / render scoremap video

### ISSUE THREAD

**Issue by fps** [DeepLabCut/DeepLabCut#464]
Hi,

it would be awesome to be able to get the score maps from the inference process. Ideally it would be possible to render a scoremap video during analyze_video.

I looked at the code and it seems that the lower level inference functions do have an "outputall" parameter so it should be possible to get at those scoremaps. Before diving in though and producing a half-assed solution I reckoned it's smarter to maybe submit a feature request instead.

**Comment by fps** [comment]
OK, so I'll hack up my own solution then. Thanks for your comment!

**Comment by lambdaloop** [comment]
You can already get most of the valuable scoremap in DeepLabCut by setting the "num_outputs" parameter to something high, say 30, so that it outputs the top N points detected rather than the top 1. Beyond some point, the rest of the points have low probability and do not contribute much to the scoremap.

**Comment by fps** [comment]
That's a good point! Thanks!

**Comment by isaacrobinson2000** [comment]
Not sure if this is helpful, but I am currently working on bringing a back-end plugin system I wrote up to date with the latest DeepLabCut which already has a plugin that does this. I am hoping to have it done by the end of this month.

**Comment by MMathisLab** [comment]
^ this will be available in a upcoming package update (wanted to let others know so they don't spend dedicated time on this)

**Comment by MMathisLab** [comment]
Delighted to say this is possible in 2.2b5 ;) You can plot scoremaps, locref, and the new PAFs:

- please see the new fxn (see details under section “Evaluation”) https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/functionDetails.md#h-evaluate-the-trained-network

![Img0_locref_train_3_0 95_snapshot-30000](https://user-images.githubusercontent.com/28102185/82737547-c8f03380-9cff-11ea-923f-a6fef243d4ea.png)
![Img0_locrefzoom_train_3_0 95_snapshot-30000](https://user-images.githubusercontent.com/28102185/82737550-cab9f700-9cff-11ea-9676-e1aa4dd7d23f.png)

**Comment by fps** [comment]
Oh cool! Thanks a bunch! :)
