### ISSUE TITLE
How do you load the DLC GUI?

### ISSUE THREAD

**Issue by monajalal** [DeepLabCut/DeepLabCut#466]
I came across this tweet and I wonder how do you load the GUI for Deep Lab Cut from the Linux Terminal that does annotation and other things such as network selection:

https://twitter.com/DeepLabCut/status/1180689992122818560?s=20

**Comment by MMathisLab** [comment]
@monajalal I just responded on your other issue how to do this, also please don't open new code/bug reports here, we have a user forum for questions and help: https://forum.image.sc/tags/deeplabcut

**Comment by AlexEMG** [comment]
```
ipython
import deeplabcut 
deeplabcut.launch_dlc()
```
