### ISSUE TITLE
Training stops 

### ISSUE THREAD

**Issue by LuckyFace** [DeepLabCut/DeepLabCut#468]
**Your Operating system and DeepLabCut version**

I'm using Windows10, Anaconda3 and DeeplabCut 2.1.1 with GeForce 1060 6GB GPU.

**Describe the problem**
I have used Deeplabcut without any problem with Windows 7 and the prior version of deeplabcut (without GUI dlc) really well. I recently upgraded to Windows 10 and installed the most recent version of deeplabcut. I was impressed by the GUI dlc, but however unexpected problem occurred.
 I use resnet_50 to train my datasets. It is weird that it is much slower than before and it stops at around 100~2000 iteration. GPU engagement is about 10% and after a few hundred iterations suddenly it becomes 0% and freezes. First I wondered it is out of memory situation but the percent of memory used does not exceed 50%. (Memory is 36GB)

![image](https://user-images.githubusercontent.com/13765485/67831432-a4ddc280-fb21-11e9-8e19-fdace25ce1be.png)

![image](https://user-images.githubusercontent.com/13765485/67832184-233b6400-fb24-11e9-922a-a0cc83debbbb.png)

I know 1060 is not fast, but it worked quite well with the previous version of the deeplabcut!
I tried to go back to the previous version, and I find it really difficult to install the old version of the deeplabcut. 

By the way training works well with mobilenet (using over 70% of the GPU), however, performance is poor compared with resnet in my datasets. Cannot use it :(

Thx in advance!

**Comment by AlexEMG** [comment]
Are you using https://github.com/AlexEMG/DeepLabCut/pull/458, i.e. `deeplabcut.train_network(path_config_file,allow_growth=True)`?

Possibly related to https://github.com/AlexEMG/DeepLabCut/issues/463. As I said, I have never seen this. But to understand more, what is your TF version? (CUDA = 10.2)

**Comment by MMathisLab** [comment]
^ yes, at this time TF 2.X is not supported, and only up to CUDA 10.

**Comment by LuckyFace** [comment]
I'm using tensorflow version 1.13.1. Should I upgrade it? like 1.8?

**Comment by MMathisLab** [comment]
you are using CUDA 10.2 though, which will not work. 
https://github.com/AlexEMG/DeepLabCut/blob/master/docs/installation.md#the-most-common-new-user-hurdle-is-installing-and-using-your-gpu

![image](https://user-images.githubusercontent.com/28102185/67906821-2e09ef00-fb4c-11e9-91dd-70fe3c0cd90c.png)

Also, seems from your screenshot it's not using your GPU, it's only at 328 MiB; and you have a lot of other processes running on it, but not python.

**Comment by LuckyFace** [comment]
![image](https://user-images.githubusercontent.com/13765485/67992687-154f2580-fc81-11e9-8cc5-b7fc3fc84783.png)

![image](https://user-images.githubusercontent.com/13765485/67992703-25670500-fc81-11e9-9aad-3cda9b86bb30.png)

![image](https://user-images.githubusercontent.com/13765485/67992774-5d6e4800-fc81-11e9-93e7-3918b25235b9.png)

I installed Cuda 10.0. It appears to be 10.0 in nvcc --version but I don't know why it apprars 10.2 in nvidia-smi. You can see that GPU is engaged during the process (over 90% of CUDA). However, overall engage percentage is 10% and slow with interruption before 1000~2000 iterations. Please note that with mobilenet overall GPU engagement is over 70% and fast. I also tried allow growth option but nothing changed.

**Comment by MMathisLab** [comment]
any updates, @LuckyFace ?

**Comment by MMathisLab** [comment]
Another issuer reports this issue, but it was because the project went from windows to linux then back to windows for more labeling, then back to linux. Then, of course, the paths to the images used for training are completely screwed up. 

I would recommend checking the file Collected-Data.h5 / .csv to be sure the paths are correctly formatted. Otherwise, when it hits the image, it will crash. 


If someone does bring back a project from a linux system and labels in windows again, then you would need to force all paths back into linux format. There is a new function in 2.1.3 that allows one to fix the paths:

```
deeplabcut.convertannotationdata_fromwindows2unixstyle

convertannotationdata_fromwindows2unixstyle(config, userfeedback=True)
    Converts paths in annotation file (CollectedData_*user*.h5) in labeled-data/videofolder
    from windows to linux format. This is important when one e.g. labeling on Windows, but
    wants to re-label/check_labels/ on a Linux computer.
    
    Note for training data annotated on Windows in Linux this is not necessary, as the data
    gets converted during training set creation.
    
    config : string
        Full path of the config.yaml file as a string.
    
    userfeedback: bool, optional
        If true the user will be asked specifically for each folder in labeled-data if the containing csv shall be converted to hdf format.
```

Thus, if you paths are MIXED formatting with windows and linux, please re-format. Then you can train on a linux machine

**Comment by LuckyFace** [comment]
Thank you for your continuous attention on this issue. I'm now using mobilenet. As I mentioned above it is not as good as resnet, but the results are acceptable. I have never used linux system but I'll check the path. But, please note that it works fine using mobilenet. Would it cause trouble if it was the problem of the path?

**Comment by MMathisLab** [comment]
If mobileNet works (I missed that, sorry), then it’s definitely a memory issue- the ResNet is much larger than mobileNet... 

And here your GPU is entirely full with the Cuda process, so it’s the 6GB memory issue. Note, computer/CPU memory that you report (32GB) is not used; only the 6GB for gpu, and if you frames are a large size, the model will not work. 

![](https://user-images.githubusercontent.com/13765485/67992774-5d6e4800-fc81-11e9-93e7-3918b25235b9.png)

**Comment by MMathisLab** [comment]
Or a space issue, if you don’t have enough space to store the weights as it trains, as each is around 90 MB

**Comment by LuckyFace** [comment]
Thank you for the prompt reply! 
Yes, I understand that. But in previous deeplabcut version, it worked fine with resnet with the same computer. The GPU usage is really low using resnet with the current deeplabcut version (about 10%). My concern is that current deeplabcut version (at least in my occasion) is not optimized in using the GPU or maybe new version of deeplabcut requires much higher specification. If using mobilenet the GPU usage is over 70%.  I'm not sure about the storage issue as my SSD has more than 100GB of free space.  I wonder if I can install the previous version (not the prototype) of deeplabcut. I used it really well with the version I installed from around June 2018~March 2019.

**Comment by MMathisLab** [comment]
There is no difference in the ResNet with the default loader, if you use imgaug then you can use batch processing now but that is the only change. Are you using the default loader? 

You’re welcome to install any older version and see (or look through the code), ie pip install deeplabcut==2.0.5 brings you back to ~March 2019. 

Thus, the likely difference is your TensorFlow and Cuda version.
