### ISSUE TITLE
ImportError: libpng16.so.16: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by max1c** [DeepLabCut/DeepLabCut#469]
Please complete the following information about your system:

OS: $ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.5 (Maipo)

DeepLabCut Version: 2.1.1
Installed via conda using the following script:

```
$ cat dlc-ubuntu-GPU.yaml
# dlc-ubuntu-GPU.yaml
#
# DeepLabCut environment for Ubuntu (tested on 18.04)
#
# install: conda env create -f dlc-ubuntu-GPU.yaml
# update:  conda env update -f dlc-ubuntu-GPU.yaml

```
```
#DeepLabCut2.0 Toolbox (deeplabcut.org)
#© A. & M. Mathis Labs
#https://github.com/AlexEMG/DeepLabCut
#Please see AUTHORS for contributors.

#https://github.com/AlexEMG/DeepLabCut/blob/master/AUTHORS
#Licensed under GNU Lesser General Public License v3.0

#name: dlc-ubuntu-GPU
channels:
  - anaconda-fusion
  - defaults
dependencies:
  - pip
  - python=3.6.8
  - pip:
    - opencv-python==3.4.5.20
    - deeplabcut
    - matplotlib==3.0.3
    - tables==3.4.3
    - tensorflow-gpu==1.13.1
    - imgaug
    - https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/wxPython-4.0.3-cp36-cp36m-linux_x86_64.whl

```
Browser: Chrome

**Describe the problem**

The previous version 2.0.7 installed the exact same way worked without issues. I see that the recipe has changed significantly and is missing many things that were present in the old recipe. The error says that the libpng16.so.16 is missing:

$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import deeplabcut
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/apps/deeplabcut/2.1.1/lib/python3.6/site-packages/deeplabcut/__init__.py", line 29, in <module>
    from deeplabcut import generate_training_dataset
  File "/apps/deeplabcut/2.1.1/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/__init__.py", line 18, in <module>
    from deeplabcut.generate_training_dataset.auxfun_drag_label import *
  File "/apps/deeplabcut/2.1.1/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/auxfun_drag_label.py", line 19, in <module>
    import wx
  File "/apps/deeplabcut/2.1.1/lib/python3.6/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/apps/deeplabcut/2.1.1/lib/python3.6/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: libpng16.so.16: cannot open shared object file: No such file or directory

Are these expected to be installed in the system by default now? Even after conda installing the library it's still not being detected.

**Comment by AlexEMG** [comment]
Have you tried installing llibpng? 

e.g. https://stackoverflow.com/questions/18780219/importerrorlibpng16-so-16-cannot-open-shared-object-file

**Comment by max1c** [comment]
> Have you tried installing llibpng?
> 
> e.g. https://stackoverflow.com/questions/18780219/importerrorlibpng16-so-16-cannot-open-shared-object-file

As posted in the original comment, I installed it via conda: libpng                    1.6.37               hbc83047_0

This is the same version that was used previously in the older version conda recipe.

$ ls /apps/deeplabcut/2.1.1/lib/libpng*
/apps/deeplabcut/2.1.1/lib/libpng16.a   /apps/deeplabcut/2.1.1/lib/libpng16.so.16       /apps/deeplabcut/2.1.1/lib/libpng.a
/apps/deeplabcut/2.1.1/lib/libpng16.so  /apps/deeplabcut/2.1.1/lib/libpng16.so.16.37.0  /apps/deeplabcut/2.1.1/lib/libpng.so

**Comment by MMathisLab** [comment]
you are welcome to use the older yaml file that worked on your redhat system (we only test on ubuntu). The only addition is the installation of imgaug and tensorpack, so feel free to add those in.

**Comment by max1c** [comment]
> you are welcome to use the older yaml file that worked on your redhat system (we only test on ubuntu). The only addition is the installation of imgaug and tensorpack, so feel free to add those in.

I will try that. But could you please clarify. The old recipe had about 50+ different packages. All of those are gone from the new recipe. Do you expect these to be installed on the OS level now?

**Comment by MMathisLab** [comment]
Hi Max, so the setup.py file is used when creating deeplabcut using pip, and it has many of the dependencies now vs the conda file. So, it’s highly similar (just a cleaner version of the yaml file now ;). I’ve recently done fresh installs, and here is all I needed to get DLC up: https://github.com/MMathisLab/Docker4DeepLabCut2.0/wiki/Installation-of-NVIDIA-driver-and-CUDA-10

And you can use the old version too, it would install the latest deeplabcut anyhow, so truly fine to just use that conda file if you prefer. Fully backwards comparable.

**Comment by max1c** [comment]
> Hi Max, so the setup.py file is used when creating deeplabcut using pip, and it has many of the dependencies now vs the conda file. So, it’s highly similar (just a cleaner version of the yaml file now ;). I’ve recently done fresh installs, and here is all I needed to get DLC up: https://github.com/MMathisLab/Docker4DeepLabCut2.0/wiki/Installation-of-NVIDIA-driver-and-CUDA-10
> 
> And you can use the old version too, it would install the latest deeplabcut anyhow, so truly fine to just use that conda file if you prefer. Fully backwards comparable.

Thanks a ton for the explanation. I've installed it with the old recipe and it worked. I will stick to this method for now.

**Comment by achristensen56** [comment]
Just wanted to comment that on Ubuntu 16.04 with anaconda python I have the same issue, and also installing libpng doesn't solve the problem. Is there a chance someone could point me to the older yaml file to try?

**Comment by MMathisLab** [comment]
Hi Amy, Here is one: https://github.com/AlexEMG/DLCutils/blob/master/dlc_ubuntu18.yml, but hardcoded for an older version of DLC, so I would update that!

or this is an older one, not hard coded: https://github.com/AlexEMG/DeepLabCut/blob/dac03f962919e442526d3f113ffac9fb8c6f6ca0/conda-environments/dlc-ubuntu-GPU.yaml
