### ISSUE TITLE
Training on Google Cloud/Amazon Web Services

### ISSUE THREAD

**Issue by MoustafaAyoub** [DeepLabCut/DeepLabCut#47]
Has any one trained on google cloud, if yes can you post the steps?

**Comment by AlexEMG** [comment]
Dear Moustafa, 

We don't have any experience with this, but I heard that some users do so (perhaps with other services like amazon...). Perhaps this topic would be best discussed in the Slack user group: (deeplabcut.slack.com. Just email [Mackenzie](mackenzie@post.harvard.edu) to join.

However, would be great if people could add their experiences here.

Best,
Alexander

**Comment by brunoboivin** [comment]
If you have access to Amazon Web Services, I can confirm it works on there. They have instances designed for deep learning. You can use the following AMI **Deep Learning AMI (Ubuntu) Version 12.0 (ami-d1c9cdae)** on a GPU compute instance of your choice. Then, install the required packages as per DLC wikipage, follow their instructions for training and testing, and voila.

**Comment by MoustafaAyoub** [comment]
Same thing on Google Cloud. You just have to upload the the whole folder "DeepLabCut" in a bucket, then copy this folder into the directory you are working on.
Install the dependencies and start the training, and everthing works normally.

(I labelled my own data. So all the steps that were needed before the training where done on normally on the PC, and the training was done on the VM where I used Ubuntu 16.4)

**Comment by kaylago** [comment]
Hi, I'm attempting to use google cloud to run the training and I was wondering how those of you who have used google cloud updated the path on the config file for this?

And on google cloud, you can create specific deep learning vms that run on GNU/linux - would these be better or worse than the Ubuntu vms?

Thanks!
