### ISSUE TITLE
Issue encountered when creating training dataset [colab, path errors]

### ISSUE THREAD

**Issue by Charliehz** [DeepLabCut/DeepLabCut#471]
**Your Operating system and DeepLabCut version**
Windows10, with an Anaconda Env and Colab& DeepLabCut 2.1.1, chrome

**Describe the problem**
I use Jupyter Notebook to create a new project, extract frames and label frames, and then goes to Colab for the "create a training dataset" part. I uploaded my project folder and edited the path in config.yaml. But it appears error ether "Config file is not found" or "local variable 'cfg' referenced before assignment". I searched issues before and tried changed the format of path, but it still doesn't work. Any ideas? Very thanks in advance! 

**How to Reproduce the problem**
1. Go to 'Colab'
2. Click on buttons in the steps before "create a training dataset" 
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/57199835/67904965-3999ed80-fb2d-11e9-95b1-4385d8f04b4f.png)
![image](https://user-images.githubusercontent.com/57199835/67904989-44548280-fb2d-11e9-8125-253e45acd38c.png)
![image](https://user-images.githubusercontent.com/57199835/67905016-5d5d3380-fb2d-11e9-8ccf-c1cc1bd040e8.png)

**Additional context**

**Comment by MMathisLab** [comment]
Several issues:

**config.yaml issues:**

1) You never need to change the video path; that is for you to know where the video came from. 
2) you ONLY change the project path to where the project is. Your path is incorrect: COLAB is linux. 

please change to: `/content/drive/My Drive/DeepLabCut/Project3-Cong-2019-10-30`

(Do you have your project on google drive in a subfolder called Deeplabcut?)

Lastly, I just updated this notebook, please use this: https://github.com/AlexEMG/DeepLabCut/blob/master/examples/COLAB_YOURDATA_TrainNetwork_VideoAnalysis.ipynb

**Comment by Charliehz** [comment]
> Several issues:
> 
> **config.yaml issues:**
> 
> 1. You never need to change the video path; that is for you to know where the video came from.
> 2. you ONLY change the project path to where the project is. Your path is incorrect: COLAB is linux.
> 
> please change to: `/content/drive/My Drive/DeepLabCut/Project3-Cong-2019-10-30`
> 
> (Do you have your project on google drive in a subfolder called Deeplabcut?)
> 
> Lastly, I just updated this notebook, please use this: https://github.com/AlexEMG/DeepLabCut/blob/master/examples/COLAB_YOURDATA_TrainNetwork_VideoAnalysis.ipynb

Thank you very much! I edited the path as you suggested, then it works.  Sorry for this basic question.  This is really annoying for a newbee... Thanks! I will keep learning.
