### ISSUE TITLE
We are looking for a software Developer for DeepLabCut -- join the team! 

### ISSUE THREAD

**Issue by AlexEMG** [DeepLabCut/DeepLabCut#477]
![image](https://user-images.githubusercontent.com/20850270/68091383-02894c00-fe4d-11e9-9a62-5d7407ea80c1.png)

**Comment by MMathisLab** [comment]
This position is supported by CZI essential open source tools for science! Thank you CZI! https://chanzuckerberg.com/newsroom/chan-zuckerberg-initiative-awards-5-million-for-open-source-software-projects-essential-to-science/
