### ISSUE TITLE
DeepLabCut workshop and hackathons 2020! 

### ISSUE THREAD

**Issue by AlexEMG** [DeepLabCut/DeepLabCut#478]
**DeepLabCut Workshop Jan 15-17th, 2020**
Please [use this form to apply to participate in our 2nd annual DeepLabCut workshop](https://docs.google.com/forms/d/e/1FAIpQLSdeo8IeYHBgVs7bZD1a5oBJ-ruRulv7DQYay8RMD7IxunwsAw/viewform) to be held in Cambridge, MA (at the Rowland Institute at Harvard University) on Jan 16th and 17th, 2020 (starts early on the 16th, so arrival to Boston on the 15th is recommended). 

This workshop is geared towards users **with some experience that want to advance their knowledge as well as new users**. _Application closes Dec 1st. Selected participants will be notified 
by December 15th, 2019_!  (Please note, last year we could only accept ~20% of applications!)

**DeepLabCut Hackathon 2020**
Please [use this form to apply to participate in our 1st annual DeepLabCut hackathon](https://docs.google.com/forms/d/e/1FAIpQLSeBcqGFufAeBENBQcHBumvyekA6bs_LF1zZ4NPWnMe9v35MHA/viewform) to be held in Cambridge, MA (at the Rowland Institute at Harvard University) on  March 5th and 6th, 2020. This hackathon is for **advanced users who want to collectively code/discuss new additions to DLC as well as developers of other projects that want to discuss the API, etc.** _Application closes *Feb 1st*. Selected participants will be notified by Feb 10th, 2020!

More details and links to previous workshops: http://www.mousemotorlab.org/workshops
Previous workshop materials (they will be reworked for 2020): https://github.com/AlexEMG/DeepLabCut-Workshop-Materials

**Comment by LightingMc** [comment]
Is it still open? Could I just come by to visit, like not as a participant, but a visitor?

**Comment by MMathisLab** [comment]
@Beep-Boop-Bopa the workshop is closed, but the application for the hackathon is still open.

**Comment by BrianJLane** [comment]
I applied to the hackathon but never heard anything back.  Since it is after February 10, should I assume I was not selected to participate?  Thanks :)

**Comment by AlexEMG** [comment]
Responses go out today.

________________________________
