### ISSUE TITLE
Warning after running Step2_ConvertingLabels2DataFrame.py

### ISSUE THREAD

**Issue by chnanc001** [DeepLabCut/DeepLabCut#48]
I just wanted to know if this warning would cause any potential problems: 

It happened after I ran $python3 Step2_ConvertingLabels2DataFrame.py in cmd on ubuntu

the warning:

/home/gcp_instance-2/miniconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/gcp_instance-2/miniconda3/lib/python3.6/importlib/_bootstrap.py:219: Runti    meWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Not all data converted!
Merging scorer's data.

Thank you

**Comment by AlexEMG** [comment]
Hard to tell from a-far. Perhaps, just run ```Step3_..``` and see if the labels were imported correctly?

**Comment by chnanc001** [comment]
Would Step3_.. simply finish running with no errors if the labels were imported correctly?

**Comment by AlexEMG** [comment]
Yes, and it creates images with the labels plotted. So you can visually inspect them to see if they are correct. Did it show the images? 

The output suggests that you have more folders (videos) then different directories in the imported h5/csv file. You can also check the file manually and see if it is complete. If not delete both and run Step2_ again.

**Comment by chnanc001** [comment]
I'm running it on a gcp compute machine, Ubuntu 16.04
I set up tensorflow using the following:
https://github.com/williamFalcon/tensorflow-gpu-install-ubuntu-16.04
and ran Step2_.. again from the tensorflow environment created above and did not get the same error (or any error) after it finished.

Thank you.
