### ISSUE TITLE
Can I change the pointer size in create_video?

### ISSUE THREAD

**Issue by 1over137** [DeepLabCut/DeepLabCut#480]
**Is your feature request related to a problem? Please describe.**
The points drawn by `create_video` are too large.

**Describe the solution you'd like**
I want to be able to adjust the size like I can when I am labeling the video frames

**Comment by MMathisLab** [comment]
Please read the documentation.

Every function has a doc string: `deeplabcut.create_labeled_video? `

Plus here: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#create-labeled-videos

And here shows what features you can easily edit in your config file: https://github.com/AlexEMG/DeepLabCut/blob/ca93b3e7a69c674abb31bfaa812cb38940a5d598/examples/Reaching-Mackenzie-2018-08-30/config.yaml

Namely, change the size by changing "dotsize"
