### ISSUE TITLE
mklink not working

### ISSUE THREAD

**Issue by uttiyaroy** [DeepLabCut/DeepLabCut#481]
Background Info
Windows 10
NVIDIA P1000
32 GB RAM

I imported deeplabcut successfully and then launched the GUI using the deeplabcut.launch_dlc() command, and then navigated to "Manage Project"
There I added 1 video and tried to initialise the project
This gave me the error
```
Command 'mklink E:\Hey-Hey1-2019-11-08\videos\DIV5_CtrlMO_GFP_290719_2.Series079.avi E:\Shivani\CellBiology-Shivani Bodas-2019-11-05\videos\DIV5_CtrlMO_GFP_290719_2.Series079.avi' returned non-zero exit status 1.

```
What might be the problem here? I get numpy warnings that are standard because I have a more recent version of numpy but, as far as I know this did not affect the functioning.

**Comment by MMathisLab** [comment]
please fill out the issue template fully and completely.

**Comment by uttiyaroy** [comment]
Updated

**Comment by MMathisLab** [comment]
seems you don't have privileges to write into that folder.

Plus, seems you are trying to write into two different projects.... 

```
'mklink E:\Hey-Hey1-2019-11-08\videos\DIV5_CtrlMO_GFP_290719_2.Series079.avi
E:\Shivani\CellBiology-Shivani Bodas-2019-11-05\videos\DIV5_CtrlMO_GFP_290719_2.Series079.avi'
```

Did you open cmd with admin rights? 

From: https://github.com/AlexEMG/DeepLabCut/wiki/Troubleshooting-Tips


Access Denied. Insufficient permission to create directories. OSError: symbolic link privilege not held. This error is specific to the users of Windows operating system. Open command prompt with administrative rights. Use `Run as administrator' while opening the command prompt.

**Comment by MMathisLab** [comment]
also, to be clear, the add videos button only works for creating a new project, not adding additional videos...
