### ISSUE TITLE
ImportError: No module named deeplabcut

### ISSUE THREAD

**Issue by imduygusarikaya** [DeepLabCut/DeepLabCut#482]
I am working with Ubuntu 16.04 LTS, 

I installed deeplabcut using "pip install deeplabcut" and it was installed without any errors, however when I try to import it in python I get  the error: ImportError: No module named deeplabcut

How can I fix this problem? I tried to set a path at bashrc to /usr/local/deeplabcut and it didn't work out.

I downloaded the source code and tried to run setup.py but it gives an error:
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help
error: no commands supplied <--- this is the error I get when I run setup.py 

and then I tried to import it in ipython but got this error:

ImportError: No module named 'wx'

Although I installed the wx module by "sudo apt-get install python-wxtools" with no errors, I still get the same error when I try to import again: ImportError: No module named 'wx'

I a white paper I found, it recommends getting wx as below:
pip install https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04/wxPython-4.0.3-cp36-cp36m-linux_x86_64.whl 

- now I am able to import deeplabcut in ipython, however can I use it in python?

**Comment by MMathisLab** [comment]
Yes, both python and ipython (and pythonw) are supported.
