### ISSUE TITLE
deeplabcut.label_frames fails to load images

### ISSUE THREAD

**Issue by tbenst** [DeepLabCut/DeepLabCut#483]
**Describe the bug**
I'm using the latest `Demo_labeledexample_MouseReaching` notebook on DLC 2.1.1. the notebook generally works--I can create a labeled video that looks great, and the trajectory plots look good, but I'm having a few issues subsequently:

- `deeplabcut.extract_outlier_frames(path_config_file,videofile_path,outlieralgorithm='uncertain',p_bound=.2)` runs instantly with no output. Is this silently failing? Both paths are correct, trained for 1200 iterations.

- I think the instruction `Navigate to the folder corresponding to the video 'MovieS2_Perturbation_noLaser_compressed` is wrong. Should navigate to the folder `Reaching-Mackenzie-2018-08-30/labeled-data/reachingvideo1`.

- The cell with `%gui wx` pops up the GUI as expected, but it is blank. This happens if I'm in a random directory, and if I first `cd ~/lib/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30/videos/` in a cell above (is this what is meant by `?)

![blank_gui](https://user-images.githubusercontent.com/863327/68506092-a728d680-021d-11ea-8163-362feda1e45d.png)

- If I click `load` I see `looking for a folder to start refining` and then the kernel crashes. Clicking  `quit` also  crashes the kernel. The `help` button works however.

Any tips to troubleshoot? thanks so much!

Edit: the latter gui problem is specific to my setup--I had to set `GSETTINGS_SCHEMA_DIR` to the right path. Let me know if extract_outlier_frames should have an output?

Edit 2: I can get extract_frames to work by doing `python -c "import deeplabcut; path_config='/home/tyler/lib/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30/config.yaml'; deeplabcut.extract_frames(path_config, 'automatic')"`. This appears to add files to `/home/tyler/lib/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30/labeled-data/reachingvideo1/`. The directory contains the files `CollectedData_Mackenzie.csv`, `CollectedData_Mackenzie.h5`, and `imgXXX.png`. 

When I then try `python -c "import deeplabcut; path_config='/home/tyler/lib/DeepLabCut/examples/Reaching-Mackenzie-2018-08-30/config.yaml'; deeplabcut.label_frames(path_config, 'manual')"`, I select `labeled-data/reachingvideo1`, and immediately see this error:
```
Traceback (most recent call last):
  File "/home/tyler/.conda/envs/dlc-gpu/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/multiple_individual_labeling_toolbox.py", line 460, in browseDir
    self.multibodyparts = self.cfg['multianimalbodyparts']
  File "/home/tyler/.conda/envs/dlc-gpu/lib/python3.6/site-packages/ruamel/yaml/comments.py", line 753, in __getitem__
    return ordereddict.__getitem__(self, key)
KeyError: 'multianimalbodyparts'
```

Subsequently, if I hit `next`, I see this error:
```
Traceback (most recent call last):
  File "/home/tyler/.conda/envs/dlc-gpu/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/multiple_individual_labeling_toolbox.py", line 678, in nextImage
    self.individualrdb.SetSelection(0)
AttributeError: 'MainFrame' object has no attribute 'individualrdb'

Edit 3: Happy to say that labeling frames works when I launch with `python -c "import deeplabcut; deeplabcut.launch_dlc()". However, it fails when launched via the Demo notebook or `deeplabcut.label_frames`

**Comment by MMathisLab** [comment]
Last point: Seems you are calling the function incorrectly. It should just be deeplabcut.label_frames(configpath)
 - no argument “manual” 

First point: “ deeplabcut.extract_outlier_frames(path_config_file,videofile_path,outlieralgorithm='uncertain',p_bound=.2) runs instantly with no output. Is this silently failing? Both paths are correct, trained for 1200 iterations.”  

- double check your paths, if formatted with [ ] correctly. 


“ I think the instruction Navigate to the folder corresponding to the video 'MovieS2_Perturbation_noLaser_compressed is wrong. Should navigate to the folder Reaching-Mackenzie-2018-08-30/labeled-data/reachingvideo1.” 

- no, it’s correct, the workflow is you should run video analysis on that video, then if you want to extract outliers on that already analyzed video, so you have to go to that folder to extract outliers. This is independent of label_frames.

the Jupyter issue likely just means you need to restart the kernel, as this is very system dependent, but not the DLC code, ie it works, and you should see machine-labeled.h5 if outlier ran.

**Comment by tbenst** [comment]
Ah, thank you! `label_frames` works fine with proper function call. 

Thanks for the tip about formatting viedofile_path as a list. I believe there is a small error in the `Demo_labeledexample_MouseReaching.ipynb` notebook. The line currently reads, 

`deeplabcut.extract_outlier_frames(path_config_file, videofile_path, outlieralgorithm='uncertain', p_bound=.2)`

and this silently fails, but

`deeplabcut.extract_outlier_frames(path_config_file, [videofile_path], outlieralgorithm='uncertain', p_bound=.2)`

succeeds.

Re: `Navigate to the folder corresponding to the video 'MovieS2_Perturbation_noLaser_compressed`, note that the first time this video is mentioned in the notebook is under `Manually correct labels`. As such, there is no `machine-labeled.h5` file, so this gives an error. My understanding is that we need to first analyze and then extract frames, but the notebook does not do this for `MovieS2_Perturbation_noLaser_compressed`.
