### ISSUE TITLE
Loading old snapshot on Colab creates issue [body part ID mismatch]

### ISSUE THREAD

**Issue by byronrogers73** [DeepLabCut/DeepLabCut#487]
I loaded up an old pre-trained model in COLAB to use on a similar dataset. 

When I ran the training command it found the correct model 

'init_weights': '/content/drive/My '
                 'Drive/DLC/Lib/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/snapshot-850000',

under all of the standard load comments was the following....
```
Switching batchsize to 1, as default/tensorpack/deterministic loaders do not support batches >1. Use imgaug loader.
Starting with standard pose-dataset loader.
Initializing ResNet
Loading already trained DLC with backbone: resnet_50

INFO:tensorflow:Restoring parameters from /content/drive/My Drive/DLC/Lib/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/snapshot-850000
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1364     try:
-> 1365       return fn(*args)
   1366     except errors.OpError as e:

11 frames
InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [24] rhs shape= [44]
	 [[{{node save/Assign}}]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [24] rhs shape= [44]
	 [[node save/Assign (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
```

**Desktop (please complete the following information about your system):**
 - iOS
 - DeepLabCut Version 2.1.3
 - Chrome

**Comment by MMathisLab** [comment]
Are you sure the path is correct? This looks incorrect unless you truly have a folder on your google drive called site-packages, etc: 

'/content/drive/My '
'Drive/DLC/Lib/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/snapshot-850000',

Typically loading weights would come from the folder “dlc-models/...”

**Comment by byronrogers73** [comment]
I think so but I'll move the pre-trained model to a new folder within the DLC/deeplabcut/ and see if that makes a difference.

**Comment by MMathisLab** [comment]
Sounds good, be sure to grab all three files that have snapshot-850000 in them

**Comment by byronrogers73** [comment]
Uploaded and pointed to a more recent model

![Screen Shot 2019-11-14 at 4 42 36 PM](https://user-images.githubusercontent.com/6619599/68898726-03986400-06fe-11ea-9bdd-107a3605c8ab.png)

But still the same errors.
```
Switching batchsize to 1, as default/tensorpack/deterministic loaders do not support batches >1. Use imgaug loader.
Starting with standard pose-dataset loader.
Initializing ResNet
Loading already trained DLC with backbone: resnet_50
INFO:tensorflow:Restoring parameters from /content/drive/My Drive/DLC/deeplabcut/pretrained/snapshot-62000
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1364     try:
-> 1365       return fn(*args)
   1366     except errors.OpError as e:

11 frames
InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [3,3,12,2048] rhs shape= [3,3,23,2048]
	 [[{{node save/Assign_3}}]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [3,3,12,2048] rhs shape= [3,3,23,2048]
	 [[node save/Assign_3 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]

```

I have changed the pose_cfg.yaml files in both the train and test subdirectories to point to the right folder. init_weights: /content/drive/My Drive/DLC/deeplabcut/pretrained/snapshot-62000

**Comment by MMathisLab** [comment]
okay thanks - does seem a different error though, so thats good (at least I believe it's finding the correct weights). 

I see the default tensorflow has changed in colab, so I will need to look into it. I have not tested 1.15 yet, and TF 2.x is not yet supported. Could you check in your notebook which version is running?

```
import tensorflow
tensorflow.__version__
```
Also would you mind posting your train pose_cfg.yaml?

**Comment by MMathisLab** [comment]
Thanks! As colab is always updating, I double checked that the demo data works on COLAB (i.e. https://colab.research.google.com/github/AlexEMG/DeepLabCut/blob/master/examples/COLAB_DEMO_mouse_openfield.ipynb), trained great, and then used old weights, and that also worked. Then I made a typo in the path to double check, and that threw the correct error, i.e. no weights found. 

1) are you sure the old weights have the **identical bodyparts**? Seems the error: ``lhs shape= [3,3,12,2048] rhs shape= [3,3,23,2048]`` suggests that the old network was trained with **23** bodyparts, not **13**? To reuse the weights, the new data would have to be labeled with the idential named bosyparts. 

If so, can you confirm:

1) did you run `deeplabcut.create_training_dataset(path_config_file)` within colab? 
2) then you downloaded and edited pose_cfg.yaml and re-uploaded? (only train folder is required)?
3) could you attach the log.txt file from the train folder please

**Comment by byronrogers73** [comment]
1. No They dont have identical bodyparts. The new data I am training has a trimmed number of markers. I presume that is the error?
2. I did run deeplabcut.create_training_dataset(path_config_file) within colab
3. I downloaded, edited and uploaded the edited files. 
4. Log file attached
[log.txt](https://github.com/AlexEMG/DeepLabCut/files/3853089/log.txt)

**Comment by MMathisLab** [comment]
Correct. The old network is fixed for those specific bodyparts and bodypart names, that's the issue.
