### ISSUE TITLE
Any news about the multi-animal tracking?

### ISSUE THREAD

**Issue by qqspm** [DeepLabCut/DeepLabCut#488]
Any news about the multi-animal tracking?

**Comment by MMathisLab** [comment]
please do not post questions to github issues. We ask that users please post on the Image Forum. 

https://github.com/AlexEMG/DeepLabCut#community-support-developers--help

https://forum.image.sc/tags/deeplabcut

**Comment by AlexEMG** [comment]
Starting with https://github.com/DeepLabCut/DeepLabCut/tree/v2.2b5 there is (finally) very strong multi-animal support built in! Please let us know how it goes.
