### ISSUE TITLE
Fraction of images used as training and test sets seems to be wrong

### ISSUE THREAD

**Issue by emiwar** [DeepLabCut/DeepLabCut#49]
**Describe the bug**
Fraction of images used as training and test sets seems to be wrong when using the scripts in Generating_a_Training_Set. In particular, setting training fraction to 0.95 seems to give 5% training and 95% test.

**To Reproduce**
I followed the tutorial at https://alexemg.github.io/DeepLabCut/docs/demo-guide.html using my own video. The file `UnaugmentedDataSet_2choiceAug21/Documentation_data-2choice_95shuffle1.pickle` seems wrong to me:

```
>>> pickle.load(open("UnaugmentedDataSet_2choiceAug21/Documentation_data-2choice_95shuffle1.pickle", "rb"))

[[{'image': '../../UnaugmentedDataSet_2choiceAug21/data-2choice/20180404_144847_d1_3517-0000/img31550.png',
   'joints': array([[  0, 151, 103],
          [  1, 231, 160],
          [  2, 278, 191],
          [  3, 261, 218]]),
   'size': array([  3, 304, 400])},
  {'image': '../../UnaugmentedDataSet_2choiceAug21/data-2choice/20180404_144847_d1_3517-0000/img48931.png',
   'joints': array([[  0, 187, 240],
          [  1, 228, 153],
          [  2, 261,  80],
          [  3, 271, 111]]),
   'size': array([  3, 304, 400])},
  {'image': '../../UnaugmentedDataSet_2choiceAug21/data-2choice/20180404_144847_d1_3517-0000/img13289.png',
   'joints': array([[  0, 195, 241],
          [  1, 239, 152],
          [  2, 258,  87],
          [  3, 277, 110]]),
   'size': array([  3, 304, 400])}],
 array([14, 28,  3]),
 array([34, 19, 26, 12, 33, 22, 38, 39, 13, 30,  9, 17,  1, 32, 27, 23,  7,
         5, 35,  8, 25, 10, 24, 21, 37, 18, 20, 31, 29, 42,  0, 40, 15,  2,
         6, 11, 43, 41,  4, 16, 36]),
 0.95]
```
I would expect the last two arrays to be switched, and that the listed images would reflect the bigger split.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.10

Thanks for a promising package!

**Comment by AlexEMG** [comment]
Thanks for pointing this out - I noticed that the jupyter notebook had the train/test split wrongly. The python script for ```Step4_``` did it right. I just fixed this in a push!
