### ISSUE TITLE
How am I supposed to restore weights after interrupting training?

### ISSUE THREAD

**Issue by 1over137** [DeepLabCut/DeepLabCut#490]
**Your Operating system and DeepLabCut version**
Arch, DLC 2.1

**Describe the problem**

The way to restore model weights is undocumented and very non-obvious. It took me some time to dig into the source code to even figure this out. Apparently I should change the `init_weights` value in pose_cfg to `snapshot_$iteration`. Also, is there a way to continue the numbering of iterations after this.

**Comment by MMathisLab** [comment]
It's a FIGURE / BOX in the Protocol paper: https://www.nature.com/articles/s41596-019-0176-0
and in the documentation:  https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#f-create-training-datasets

![image](https://user-images.githubusercontent.com/28102185/68994230-9a743600-084e-11ea-9b83-a04bb526a4bd.png)


and you're welcome for the free code, happy deeplabcutting!
