### ISSUE TITLE
analyze video run slow 

### ISSUE THREAD

**Issue by Shachafbe** [DeepLabCut/DeepLabCut#492]
***closing cause I manage to solve it by using Jupiter notebook instead of IPython**

**windows 10, anaconda env for GPU, deepcutlab 2.0.8 **
OS: Windows 10
DeepLabCut Version [2.0.8]
Browser: chrome
using Ipython

I analyzed the same type of video before and it went well, usually, 24 hours was enough (the videos are long). Now the analyzation moved 3% after 3 days. I've tried to restart everything and it didn't help. I've tried to do it for a short video, the same. 
The only thing that has been changed is that I've tried to install the new version of Deepcutlab (in a different anaconda env) but eventually used the 2.0.8. 
![Picture1](https://user-images.githubusercontent.com/53897118/69004577-7849e900-091e-11ea-9610-eeae19e40b4f.png)
![Picture2](https://user-images.githubusercontent.com/53897118/69004576-7849e900-091e-11ea-9302-49a908b64900.png)

Many thanks in advance,
Shachaf

**Comment by catubc** [comment]
Hi, i'm also having a similar issue, analyzing videos is taking longer than real time.  This is a 24 hour video acquired at 25.0FPS, and 1280 x 1024 resolution.  DLC analyze video used to run much faster than real-time, but it's now quite slow. 

Any suggestions?

```

INFO:tensorflow:Restoring parameters from /home/cat/code/DeepLabCut/march_2-cat-2020-03-20/dlc-models/iteration-0/march_2Mar20-trainset95shuffle1/train/snapshot-1030000
Starting to analyze %  /media/cat/14TB/insync_cm5636/march_2/video/compressed/file_list_0_compressed.avi
Loading  /media/cat/14TB/insync_cm5636/march_2/video/compressed/file_list_0_compressed.avi
Duration of video [s]:  86388.84 , recorded with  25.0 fps!
Overall # of frames:  2159721  found with (before cropping) frame dimensions:  1280 1024
Starting to extract posture
  4%|████▋                                                                                                                 | 86388/2159721 [1:08:03<27:17:25, 21.10it/s]
```

**Comment by AlexEMG** [comment]
Not sure, depending on your hardware (CPU/GPU) this might just be the speed you get. 

You can always downsample, use MobileNet backbones or get a better GPU. Check out speeds here: https://www.biorxiv.org/content/10.1101/457242v1
and also here: 

https://github.com/AlexEMG/DeepLabCut/wiki/What-neural-network-should-I-use%3F
