### ISSUE TITLE
Ipython freezes after (-215:Assertion failed) !ssize.empty() in function 'resize'

### ISSUE THREAD

**Issue by ThejanW** [DeepLabCut/DeepLabCut#493]
**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: Ubuntu 18.04
DeepLabCut Version: 2.1.3
Browser: chrome
TensorFlow Version: tensorflow-gpu==1.14
CUDA 10
GPU: GeForce RTX 2080 Ti

**Describe the problem**

I am trying to train a model with a ResNet-50 backend. I have 1000+ annotations. Both training and validation functions were working pretty well. But after few runs, an error started to appear at the same iteration index. But the training session doesn't stop. However, It eventually freezes my ipython session, advising me to force quit the session. I tried running this multiple times, it freezes at the exact same iteration too. Perhaps, one of my images are corrupted as it is having trouble with cv2.resize. But the training continues even after the error. 
Why does it freeze only after few more iterations from the occurrence of the error?

**How to Reproduce the problem**
1. Run DLC GUI
2. Start a training session with a ResNet-50 while keeping all the other settings as defaults

**Screenshots**
Here's the error
![image](https://user-images.githubusercontent.com/17251474/69016103-0676ab80-09c1-11ea-822a-27bf363e1a2b.png)

After some time, it freezes the session
![image](https://user-images.githubusercontent.com/17251474/69016112-1f7f5c80-09c1-11ea-9c3f-f9b3d415a200.png)

![image](https://user-images.githubusercontent.com/17251474/69016293-2e670e80-09c3-11ea-8b19-7f9e8aca46c9.png)

**Additional context**
I'm pretty sure this is a data specific problem. I just need some help figuring out the origination of this.  

Thanks.

**Comment by AlexEMG** [comment]
Thanks @ThejanW for raising this -- this might be related to other issues: https://github.com/AlexEMG/DeepLabCut/issues/463 and https://github.com/AlexEMG/DeepLabCut/issues/468 that recently popped up. 

Can you make a catch for the cv2.resize and figure out why it fails? See e.g. https://github.com/aleju/imgaug/issues/205

Just to be sure this is for the default loader though? -- then the moment where it is called is here: https://github.com/AlexEMG/DeepLabCut/blob/ca93b3e7a69c674abb31bfaa812cb38940a5d598/deeplabcut/pose_estimation_tensorflow/dataset/pose_defaultdataset.py#L185 

Can you make sure the image is not empty, or the target size is not 0, or ...?

**Comment by ThejanW** [comment]
Hi @AlexEMG Thanks for the prompt response. My case is different from #463 and #468. In my case, I perform some preprocessing such as affine transformations on my data and generate the .csv and .h5 files with my own scripts. Apparently, few of my annotations are having negative coordinates due to those transformations. When the random crop function is executed on those negative coordinates, the image become an empty numpy array, raising this cv2.resize error. Initially, I changed this behaviour by editing the next_batch() function in pose_defaultdataset.py to skip such examples when training a model. But since the real cause of the error is in dataset creation step, I later changed trainingsetmanipulation.py to not to add such examples to the dataset. I will raise a PR, shortly.
