### ISSUE TITLE
Guide for cloud computing + DeepLabCut

### ISSUE THREAD

**Issue by caniko** [DeepLabCut/DeepLabCut#496]
**Is your feature request related to a problem? Please describe.**
I am sure there are many labs that want a plug n play solution without spending much money and time on hardware. Maybe provide some guidelines for picking the right cloud computing product that would enable DeepLabCut.

There are so many alternatives, and with many alternatives comes many pitfalls. There is even a long [list](https://aws.amazon.com/sagemaker/pricing/) of different sets of hardware to choose from on each platform.

**Describe the solution you'd like**
A simple wiki page, comparing different products, and how to use them with DeepLabCut.

**Describe alternatives you've considered**
I have considered AWS SageMaker and Google Cloud that has native support for jupyter notebooks.

**Comment by AlexEMG** [comment]
Technically, for running DeepLabCut on the cloud all one needs to to is to [suppress GUI output](https://github.com/AlexEMG/DeepLabCut/blob/b22532278a43f3def0ee99ca6fa243aa52115bb3/docs/functionDetails.md#f-create-training-datasets).
with: `DLClight=True`

I don't use AWS/Google Cloud etc. It would be great if users that use DLC on the cloud and have compared the different services could comment here. Although, I suppose with regard to DLC they are all equivalent.

**Comment by MMathisLab** [comment]
How to use our docker container is all here: https://github.com/DeepLabCut/Docker4DeepLabCut2.0/blob/master/README.md

And here is how to use Docker on AWS: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html
