### ISSUE TITLE
Error Creating New Project using GUI [open as admin]

### ISSUE THREAD

**Issue by jalapic** [DeepLabCut/DeepLabCut#497]
Windows 10 Enterprise v1903  with an Anaconda Env, - DeepLabCut version 2.1.3
Browser: Chrome

**Describe the problem**
We were able to download DeepLabCut and open the GUI.  When trying to create a new project using either only .avi video files or .mp4 files we get the following error messages (see screenshots for example using one video file called "bears.avi".

The other screenshot shows what we have typed into the boxes prior to hitting "ok" on the ManageProject>CreateNewProject interface.

```CalledProcessError: Command 'mklink C:\Users\ChampagneCurleyVideo\DeepLabCut\conda-environments\Bears-James-2019-11-19\videos\bears.avi C:\Users\ChampagneCurleyVideo\Desktop\bears.avi' returned non-zero exit status 1.```

**Screenshots**
![image](https://user-images.githubusercontent.com/7896861/69192674-a9771480-0aea-11ea-9811-a30cb4b4a052.png)

![image](https://user-images.githubusercontent.com/7896861/69192735-d3c8d200-0aea-11ea-8638-fd7b56db2577.png)

Thank you very much for your attention.

**Comment by AlexEMG** [comment]
Please, try to copy the video (by setting the radio button below).

**Comment by MMathisLab** [comment]
You need to open the program ”cmd” with admin privileges. You can otherwise click copy videos “yes” and that will not appear.

**Comment by jalapic** [comment]
Thanks.  Clicking the 'yes' on copy videos did not work, however, opening with admin privileges did the trick. Thank you.
