### ISSUE TITLE
During the refinement step, the labels for frame 0 are moved to the location of the last frame in the package

### ISSUE THREAD

**Issue by Rudgas** [DeepLabCut/DeepLabCut#502]
**Describe the bug**
In the refinement GUI after selecting the frames to be relabelled, frame 0 shows the labels in the position of the last frame. wriggling around with the arrow keys, it is also possible to move to frame -1 as shown in the title above the image. The image however stays the same as frame 0.
Readjusting the labels on frame 0 and moving to frame 1 and back to 0 resets the position to the last frame of the package.
What solved it was opening the frame-package, adjusting frame 0, saving and quitting without moving to other frames.

**To Reproduce**
1. Open relable GUI, open frame-package
2. Adjust labels for frame 0
3. Move to frame 1 and back to 0
4. see the labels are the same as last frame

**Expected behavior**
Labels shouldn't move on their own.

**Desktop (please complete the following information about your system):**
 - OS: win10
 - DeepLabCut Version 2.1.1.

**Comment by AlexEMG** [comment]
@meet10may

**Comment by MMathisLab** [comment]
@Rudgas Do you have any more insights on this? You mentioned on gitter you could take a video. I can’t reproduce this behavior locally (Ubuntu).
