### ISSUE TITLE
module 'deeplabcut' has no attribute 'load_demo_data'

### ISSUE THREAD

**Issue by salvatoreNRIM** [DeepLabCut/DeepLabCut#503]
Windows10, with Anaconda Env, DeepLabCut 2.0, Safari

I just installed dlc2 in my pc and when trying the demo file for mouse reaching (Demo_labeledexample_MouseReaching.ipynb), I get the following error by running the third cell with the command deeplabcut.load_demo_data(path_config_file):

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-1b4a212f9a3d> in <module>
      2 #(note, this function is not used when you create your own project):
      3
----> 4 deeplabcut.load_demo_data(path_config_file)AttributeError: module 'deeplabcut' has no attribute 'load_demo_data'

Would you have any recommendation on what to do to solve this issue?

**Comment by MMathisLab** [comment]
You are likely not in the correct env. In your notebook, select the dlc env under kernel

Also, you are likely not using “2.0” that’s more than a year old. To check a version: 

`Import deeplabcut` 
`deeplabcut.__version__`

**Comment by salvatoreNRIM** [comment]
Thanks, yep that solved the issue. Also you are right, the version is 2.1.3
