### ISSUE TITLE
displayedbodyparts for plot_trajectories

### ISSUE THREAD

**Issue by Shachafbe** [DeepLabCut/DeepLabCut#504]
Hello,
I would like to know if there is an option to get the plots (with plot_trajectories) for specific body parts and not all of them together, like the "displayedbodyparts" option for deeplabcut.create_labeled_video? 

Many thanks in advance, 
Shachaf.

**Comment by AlexEMG** [comment]
Currently not, but that should be updated.

________________________________

**Comment by MMathisLab** [comment]
You can also see how to plot as you like using our helper code on DLCUtils: https://github.com/AlexEMG/DLCutils/blob/master/Demo_loadandanalyzeDLCdata.ipynb

**Comment by AlexEMG** [comment]
Will be contained in DLC 2.1.5 > released tomorrow!

**Comment by AlexEMG** [comment]
Voila: https://github.com/AlexEMG/DeepLabCut/releases/tag/v2.1.5
