### ISSUE TITLE
Adding new body parts to existing project

### ISSUE THREAD

**Issue by Yaraat92** [DeepLabCut/DeepLabCut#506]
**Windows 10, with an Anaconda Env, & DeepLabCut 2.0.7.**
Browser: Chrome

I Tried adding new body parts to an existing project, but I cannot see my new labeled frames using deeplabcut.check_labels.
I added the body parts to the cofig.yaml file, used label_frames to add the new labels, checked the csv files, which do contain the new body parts (thought I did not add them to all the videos I used in the project). 
However the .h5 file does not seem to be updated (the last modified date does not change). 
Anyway, I tried to make sure that the labels are indeed added by using check_labels, but I get the following error:

![error_check_labels](https://user-images.githubusercontent.com/52376512/69605830-e2067900-1029-11ea-8d62-05e5272bec4c.png)

Using label_frames does show all the new labels that I added.

Any idea on how I can fix this?

**Comment by MMathisLab** [comment]
you would need to be sure all the files have the new body part included:
 _"thought I did not add them to all the videos I used in the project"_

**Comment by Yaraat92** [comment]
Does this mean I have to add the labels to all the extracted frames from every video I used in the project? (hundreds of them...?)

**Comment by AlexEMG** [comment]
Ideally yes. The goal is that for all (labeled-data) frames, where this new bodypart is visible you should have a label.

However there are multiple ways to achieve this:
- you can make a new project with fewer frames that are completely labeled (you can copy those folders over)
- you run prediction on all unlabeled frames to predict the missing/novel bodypart and fix it
- you exclude unlabeled points from training (i.e. the targetmap is zeroed fo the loss)

________________________________
