### ISSUE TITLE
Windows conda environment creation

### ISSUE THREAD

**Issue by FedeClaudi** [DeepLabCut/DeepLabCut#507]
**Describe the bug**
Cannot create a new environment using the yaml files in `conda-environments` on Windows 10.
The same error happens with both the CPU and GPU version of the environment. 

**To Reproduce**

1. Clone DeepLabCut
2. `cd conda-environments`
3. 'conda env create -f dlc-windowsCPU.yaml'
4. Read funny warning message about pip-install not being specified
4. error

**Expected behavior**
Should create the conda environment. 

**Screenshots**
![image](https://user-images.githubusercontent.com/17436313/69714564-82c66880-10fe-11ea-8499-bc384f56d19e.png)

**Desktop (please complete the following information about your system):**
 - OS: Windows10
 - DeepLabCut Version: latest
- conda version: 4.7.12

**Additional context**
I had an environment installed on this machine using this method before. 
The problem appeared after I wiped and updated conda.

Thank you, 
Federico

**Comment by MMathisLab** [comment]
I added `pip` to the conda evs: https://github.com/AlexEMG/DeepLabCut/tree/master/conda-environments

**Comment by MMathisLab** [comment]
@FedeClaudi did this solve the issue? also see: https://github.com/AlexEMG/DeepLabCut/issues/347 https://github.com/AlexEMG/DeepLabCut/issues/260

(also note this is no longer in our conda files, so you should use the latest)

**Comment by FedeClaudi** [comment]
Hi, 

Sorry I missed the last message. Yes now it installs fine, thank you for the fix. 

Cheers, 
Federico
