### ISSUE TITLE
Issue with Step 6 (TensorFlow installation problem)

### ISSUE THREAD

**Issue by omaghsoudi** [DeepLabCut/DeepLabCut#51]
Hi, 
Your work sounds so interesting. I have got a TitanXP GPU and using Linux 18.04. I installed all the required packages and tensorflow-gpu. The GPU can be found by tensorflow and all first five steps can be run. But, on step6, I get the following error after making chunks for training:

**Unfortunately, I made a mistake and instead of a new issue, which I was writing, I modified this one (I could not recover it so I removed the information; hopeful, you can recover it). sorry for the mistake.**

Any idea what can be the issue?
Thank you!

**Comment by AlexEMG** [comment]
Hi,

What if you use batch size 1? -  during training the memory demand of the feature detectors it actually quite demanding, so we only train with small batch sizes.

**Comment by omaghsoudi** [comment]
Batch size is already 1. The computer RAM is good enough also, 32GB. This is the Config:
``` 
{'all_joints': [[0], [1], [2], [3]],
 'all_joints_names': ['hand', 'Finger1', 'Finger2', 'Joystick'],
 'batch_size': 1,
 'crop': False,
 'crop_pad': 0,
 'dataset': '../../UnaugmentedDataSet_reachingJan30/reaching_Mackenzie95shuffle1.mat',
 'dataset_type': 'default',
 'display_iters': 1000,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': '../../pretrained/resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1000,
 'mean_pixel': [123.68, 116.779, 103.939],
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 4,
 'optimizer': 'sgd',
 'pos_dist_thresh': 17,
 'regularize': False,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.5,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': './snapshot',
 'stride': 8.0,
 'use_gt_segm': False,
 'video': False,
 'video_batch': False,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
``` 

I will play with training parameters to see if I can fix it. It would be great if you have any idea to help.

**Comment by omaghsoudi** [comment]
I reinstalled tensorflow, and after a reboot, it works.
Thank you so much or following up.
