### ISSUE TITLE
CPU conda environment for ubuntu (yaml file is missing)

### ISSUE THREAD

**Issue by MarineChap** [DeepLabCut/DeepLabCut#511]
Hi, 
How could I set up the conda environment for CPU in ubuntu ? I know a month ago (version 2.1.2) the yaml was in the repository, but now it disappeared in the actual version. could you hep me please with this?
Thanks.
Also, some parts of the documentation seem to be broken (the links do not open). When do you think it will be available again? 
Thank you for your help.

**Comment by AlexEMG** [comment]
They are at: http://deeplabcut.org/

[direct link for Ubuntu and CPU](http://www.mousemotorlab.org/s/dlc-ubuntu-CPU.yaml)

Also what part of the documentation is broken?

**Comment by MarineChap** [comment]
Thanks you. 
For the broken part, I think it was when I was redirected in your website. I try this morning and it is working again.
