### ISSUE TITLE
Problem with analyzing new video

### ISSUE THREAD

**Issue by strongzero** [DeepLabCut/DeepLabCut#512]
*Ubuntu 16.04, with an Anaconda Env, & DeepLabCut 2.08*

I tried to analyze new video, but there are some errors as follows.
I think there is a problem near "FileNotFoundError: [Errno 2]" because there is a folder whose name is "iteration-0" not "iteration-1", but I couldn't understand why "iteration-1" is specified.

<img width="782" alt="Screenshot 2019-12-04 at 01 44 24" src="https://user-images.githubusercontent.com/40532590/70102757-67e18000-1639-11ea-83eb-8155f1cc69bb.png">

---------------------------------------------------------------------------
In [7]: deeplabcut.analyze_videos(config_path,['/media/dlc/Data/Data/TurtleBehavData/E09/HV_Grating/2012.06.22-E09-avi'], shuff
   ...: le=1, save_as_csv=True, videotype='.avi')
FileNotFoundError                         Traceback (most recent call last)
/home/dlc/anaconda3/envs/dlc/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py in analyze_videos(config, videos, videotype, shuffle, trainingsetindex, gputouse, save_as_csv, destfolder, cropping)
    129     try:
--> 130         dlc_cfg = load_config(str(path_test_config))
    131     except FileNotFoundError:

/home/dlc/anaconda3/envs/dlc/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/config.py in load_config(filename)
     55 def load_config(filename = "pose_cfg.yaml"):
---> 56     return cfg_from_file(filename)
     57 

/home/dlc/anaconda3/envs/dlc/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/config.py in cfg_from_file(filename)
     41     """
---> 42     with open(filename, 'r') as f:
     43         yaml_cfg = edict(yaml.load(f,Loader=yaml.SafeLoader))

FileNotFoundError: [Errno 2] No such file or directory: '/media/dlc/Data/DLC/test-shohei-2019-11-28/dlc-models/iteration-1/testNov28-trainset95shuffle1/test/pose_cfg.yaml'

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-7-fd00a3e377e4> in <module>()
----> 1 deeplabcut.analyze_videos(config_path,['/media/dlc/Data/Data/TurtleBehavData/E09/HV_Grating/2012.06.22-E09-avi'], shuffle=1, save_as_csv=True, videotype='.avi')

/home/dlc/anaconda3/envs/dlc/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py in analyze_videos(config, videos, videotype, shuffle, trainingsetindex, gputouse, save_as_csv, destfolder, cropping)
    130         dlc_cfg = load_config(str(path_test_config))
    131     except FileNotFoundError:
--> 132         raise FileNotFoundError("It seems the model for shuffle %s and trainFraction %s does not exist."%(shuffle,trainFraction))
    133 
    134     # Check which snapshots are available and sort them by # iterations

FileNotFoundError: It seems the model for shuffle 1 and trainFraction 0.95 does not exist.

**Comment by AlexEMG** [comment]
Then just change the iteration back to 0, i.e. this variable in your config file: https://github.com/AlexEMG/DeepLabCut/blob/master/examples/openfield-Pranav-2018-10-30/config.yaml#L32

**Comment by strongzero** [comment]
Thank you for your prompt reply!
When I changed to iteration 0, I could analyze new video!
