### ISSUE TITLE
Issue encountered when creating dataset

### ISSUE THREAD

**Issue by Charliehz** [DeepLabCut/DeepLabCut#513]
Your Operating system and DeepLabCut version
Windows10, with an Anaconda Env and Colab& DeepLabCut 2.1.4, chrome

Describe the problem
I use Jupyter Notebook to create a new project, extract frames and label frames, and then go to Colab for the "create a training dataset" part. Everything goes well until creating dataset, it shows "TypeError: 'NoneType' object is not subscriptable" Thanks!

How to Reproduce the problem

Go to 'Colab'
Click on buttons in the steps before "create a training dataset"
See error
Screenshots
![image](https://user-images.githubusercontent.com/57199835/70104654-9177b880-15f3-11ea-87df-25d11deb39ac.png)
![image](https://user-images.githubusercontent.com/57199835/70104685-a2c0c500-15f3-11ea-9269-d20a240c7b0d.png)

**Comment by AlexEMG** [comment]
Are you sure the path to the config file is correct?

**Comment by Charliehz** [comment]
> Are you sure the path to the config file is correct?

Yes, I think so. I put the project folder in my root Google drive folder. I am pretty confused...

**Comment by AlexEMG** [comment]
Sorry to confuse you, the error suggests that cfg ( the config file is not loaded, thus a type error)

________________________________

**Comment by MMathisLab** [comment]
can you please show what you put into this cell, especially: `ProjectFolderName = 'testing-teamDLC-10-26-2019'`

```
#Setup your project variables:
  
ProjectFolderName = 'testing-teamDLC-10-26-2019'
VideoType = 'avi' 
videofile_path = ['/content/drive/My Drive/'+ProjectFolderName+'/videos/'] #Enter the list of videos or folder to analyze.
videofile_path
```

**Comment by Charliehz** [comment]
> can you please show what you put into this cell, especially: `ProjectFolderName = 'testing-teamDLC-10-26-2019'`
> 
> ```
> #Setup your project variables:
>   
> ProjectFolderName = 'testing-teamDLC-10-26-2019'
> VideoType = 'avi' 
> videofile_path = ['/content/drive/My Drive/'+ProjectFolderName+'/videos/'] #Enter the list of videos or folder to analyze.
> videofile_path
> ```
Sure. 
#Setup your project variables:
  
ProjectFolderName = 'Project1-Cong-2019-12-03'
VideoType = 'avi' 
videofile_path = ['/content/drive/My Drive/'+'Project1-Cong-2019-12-03'+'/videos/'] #Enter the list of videos or folder to analyze.
videofile_path

**Comment by MMathisLab** [comment]
Please do not change this: 

videofile_path = ['/content/drive/My Drive/'+'Project1-Cong-2019-12-03'+'/videos/'] #Enter the list of videos or folder to analyze.
videofile_path

ONLY edit this: ProjectFolderName

And, it seems it’s the incorrect format, please check the exact name of the folder. Typically ends in the year, not day.

**Comment by Charliehz** [comment]
I fixed the path as you suggested and checked the exact folder name, but the issue still exists...I can show you my folder and googledrive.
![image](https://user-images.githubusercontent.com/57199835/70168481-cf212380-167d-11ea-9f3d-a820bc12acb5.png)
![image](https://user-images.githubusercontent.com/57199835/70168512-e19b5d00-167d-11ea-8db1-b0e4012ad146.png)

**Comment by Charliehz** [comment]
> Please do not change this:
> videofile_path = ['/content/drive/My Drive/'+'Project1-Cong-2019-12-03'+'/videos/'] #Enter the list of videos or folder to analyze.
> videofile_path
> ONLY edit this: ProjectFolderName
> And, it seems it’s the incorrect format, please check the exact name of the folder. Typically ends in the year, not day.

I fixed the path as you suggested and checked the exact folder name, but the issue still exists...I can show you my folder and googledrive.
![image](https://user-images.githubusercontent.com/57199835/70174022-f3cec880-1688-11ea-89bd-f06f1c1901f0.png)
![image](https://user-images.githubusercontent.com/57199835/70174034-fb8e6d00-1688-11ea-8319-212ec4ac9401.png)

**Comment by MMathisLab** [comment]
What is the output of this? 
```
In [0]:
#create a path variable that links to your google drive copy:
# EDIT to be your project config.yaml:
path_config_file = '/content/drive/My Drive/'+ProjectFolderName+'/config.yaml'
path_config_file
```

**Comment by Charliehz** [comment]
> What is the output of this?
> In [0]:
> #create a path variable that links to your google drive copy:
> # EDIT to be your project config.yaml:
> path_config_file = '/content/drive/My Drive/'+ProjectFolderName+'/config.yaml'
> path_config_file

Never mind. I tried creating a new project and it worked. I think it might be some unnecessary space in the path. Thanks for the help. I'll triple check next time before asking.

**Comment by MMathisLab** [comment]
Glad it’s resolved!
