### ISSUE TITLE
Extra Labels Placed Durring Training When Not in Set 

### ISSUE THREAD

**Issue by ZenenHornstein** [DeepLabCut/DeepLabCut#518]
**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: Ubuntu 18.04.2 LTS
DeepLabCut Version: 2.0.7.1
Browser: firefox

**Describe the problem**
When taking a look at the results of create labeled video, I noticed peculiar results in certain frames in which one of the body parts of interest is not in view (We did not label body-parts in frames where said body-part is obscured as according to to the readme). In some frames, deep lab cut correctly identifies that the body part is obscured and does not apply a label, however; in some cases it seems deep lab cut will 'Force' the label of the obscured body-part, often putting it directly over top of another (Correct) label.

**Screenshots**
Good results when all body-parts visible:
![Training-2018121360-img1737](https://user-images.githubusercontent.com/49211357/70266611-aff3c600-1751-11ea-9d86-bcac4305ce31.png)

Tail gets placed on head when tail is not visible:
![Test-2018121290-img1510](https://user-images.githubusercontent.com/49211357/70266124-c4838e80-1750-11ea-8022-d108242f2033.png)

**Additional context**
These are the results form snapshot 650000, I am unsure how to evaluate earlier snapshots, which I feel may preform better so any help with that would be great.

**Comment by AlexEMG** [comment]
Notice that the tail point is placed as a "x" (rather than a dot), which means that DLC is confident that it is occluded. **So you can exclude those points during analysis (by thresholding).** See the discussion of p-cutoff in https://www.nature.com/articles/s41596-019-0176-0
