### ISSUE TITLE
Anaconda install failed

### ISSUE THREAD

**Issue by yinzixie** [DeepLabCut/DeepLabCut#521]
windows 10
 
I have tried several times "conda env create -f dlc-windowsGPU.yaml"
but it keeps pop up this error message.
Same problem as i tried "conda env create -f dlc-windowsCPU.yaml"

![image](https://user-images.githubusercontent.com/48106713/70298979-9df44f00-1847-11ea-8279-27b19a23915c.png)

**Comment by MMathisLab** [comment]
The error message suggests you have either several installations of anaconda and/or it is corrupted. I would remove anaconda and do a fresh install.
