### ISSUE TITLE
Lable_Video analysis - using compressed vs. uncompressed frames

### ISSUE THREAD

**Issue by JXXCgit** [DeepLabCut/DeepLabCut#525]
Hi, Dear all,
I am using DLC to analyse my video. 
My original video is big, and if i want to use the compressed video to analyse. Does it mean that  during the label process, i also need to use the compressed video rather than original video to label for further training and analysis, or can i use the original video to label and do the further training and video analysis with compressed ones? 
Thank you for suggestions, 
Shauyin

**Comment by AlexEMG** [comment]
See https://www.biorxiv.org/content/10.1101/457242v1

You can label the uncompressed image.


If you want, you could also use the labels for both the compressed and uncompressed frame...

________________________________

**Comment by JXXCgit** [comment]
Hi, Dear Alexander, 
Thank you for the fast reply. 
I read through your paper, there is no mention about whether you used the compressed video to label and then used the compressed video for further training and analysis. 
Can i understand that i can used the uncompressed video to label, then with these label data, i continue the further training and video analysis with the compressed video? Since i though if the use the uncompressed video to label and then use compressed video to train and further video analysis, whether DLC can learn that. 
Shauyin

**Comment by AlexEMG** [comment]
See section C -- "These experiments may underestimate the accuracy achievable using highly compressed videos. We trained a network on uncompressed videos but evaluated on compressed videos. Increased accuracy can likely be achieved by training and evaluating on videos compressed in the same manner." https://www.biorxiv.org/content/10.1101/457242v1.full

Yes, you can initially label on uncompressed data, then refine on compressed videos. Mixing and matching will make your DLC model more robust!

**Comment by JXXCgit** [comment]
> See section C -- "These experiments may underestimate the accuracy achievable using highly compressed videos. We trained a network on uncompressed videos but evaluated on compressed videos. Increased accuracy can likely be achieved by training and evaluating on videos compressed in the same manner." https://www.biorxiv.org/content/10.1101/457242v1.full
> 
> Yes, you can initially label on uncompressed data, then refine on compressed videos. Mixing and matching will make your DLC model more robust!

All right, 
nice to hear that. 
Thank you!
Shauyin
