### ISSUE TITLE
label

### ISSUE THREAD

**Issue by JXXCgit** [DeepLabCut/DeepLabCut#527]
Hi, Dear All, 
I plan to label two animals within a community at the same time. I define 8 labels and 4 for each. 
i come up with a problem. i extract 40 frames for label.  animals may hide or  be covered by other unlabel animal at some(not too much) frames, then should i omit the labeling for these frames or? 
Greetings, 
shauyin

**Comment by MMathisLab** [comment]
We please ask that you do not post usage questions on GitHub. Please see our community resources here: https://github.com/AlexEMG/DeepLabCut#community-support-developers--help.

**Comment by JXXCgit** [comment]
> We please ask that you do not post usage questions on GitHub. Please see our community resources here: https://github.com/AlexEMG/DeepLabCut#community-support-developers--help.

Hey, 
Thank you for notice. I will pose the question in the image.forum
Shauyin
