### ISSUE TITLE
Anchor-free

### ISSUE THREAD

**Issue by bhack** [DeepLabCut/DeepLabCut#529]
Have you already evaluated emerging anchor-free solutions like https://arxiv.org/abs/1911.07451?

**Comment by MMathisLab** [comment]
We please ask that you do not post usage questions on GitHub. Please see our community resources here: https://github.com/AlexEMG/DeepLabCut#community-support-developers--help.

**Comment by bhack** [comment]
Sorry but how a research paper is an usage question?

**Comment by MMathisLab** [comment]
You **asked** if we already have used DirectPose, which is a question. We would like to have GitHub be for code issues, if you have questions, please follow the user guidelines:  https://github.com/AlexEMG/DeepLabCut#community-support-developers--help.

**Comment by bhack** [comment]
Ok It Is a question but not an usage one but anyway I will go to in the chat.
