### ISSUE TITLE
GPU usage high, but training slow and "insufficient permissions" displayed

### ISSUE THREAD

**Issue by renniek** [DeepLabCut/DeepLabCut#530]
Operating system: Windows 10, 64-bit
Env: Anaconda env (dlc-windowsGPU)
Version: DeepLabCut 2.0
Have GeForce RTX 2080 GPU
CUDA: 10.0 
Driver: 441.6

How to reproduce problem:
1. Attempt to train network on Reaching-Mackenzie labeled dataset.
2. Iterations are displayed, but after several hours come back and the window has closed (I think the program crashed), and the training does not complete. 

It is strange because my GPU usage seems to be very high; it changes to 90% as soon as I start training the network. However, the process that begins once I start training the network is called "Insufficient permission" (the process with type "C") next to it. I have uninstalled and re-installed DLC several times (wiping the computer inbetween), and the last time I did this I was seeing high GPU usage, but I actually was able to see python, not insufficient permissions. 

It is also strange because I installed CUDA 10.0, but NVIDIA-smi command is showing CUDA 10.2.

I am thinking that the training should be able to complete without crashing, so I am wondering if there is a GPU issue. 

I completed all of the tests described in this post:
https://github.com/AlexEMG/DeepLabCut/issues/362

I also followed the tips given in the installation guide for checking if the GPU is engaging. I am a very new user so any help would be greatly appreciated. I have attached screenshots of what my NVIDIA-smi looks like. Finally, I am wondering: Could it be related to the computer idling overnight? I have read in other posts that maybe this is an issue. 

![GPU usage](https://user-images.githubusercontent.com/58533662/70855083-a832d080-1e79-11ea-8387-6f75bdc61b0e.PNG)

As a side note, when I originally activated the anaconda environment, DLC was not installed and a file titled "condaenv.cqm5tu9r.requirements" appeared in my Downloads. I haven't had this issue the past two installations (I made sure to activate the environment in administrator mode). When I activated the environment, I did "pip install numpy==1.17.2" because I think this might have been the issue. Then I did pip install deeplabcut, and deeplabcut seemed to be functioning normally. I doubt that these two issues are related, but I thought I would say so just in case.

Thank you in advance!

**Comment by renniek** [comment]
In fact, while I am running it right now. I noticed that soon after I stopped clicking around on the computer (screen was still on) GPU usage went down to 1%. 

Thanks, Rennie

**Comment by renniek** [comment]
Also, wondering if it has something to do with the tensorflow warning shown on my screen.
![window](https://user-images.githubusercontent.com/58533662/70855238-97d02500-1e7c-11ea-88e8-7768cdc64f96.PNG)
![window2](https://user-images.githubusercontent.com/58533662/70855239-9a327f00-1e7c-11ea-8a95-4274d726471d.PNG)

**Comment by MMathisLab** [comment]
> As a side note, when I originally activated the anaconda environment, DLC was not installed and a file titled "condaenv.cqm5tu9r.requirements" appeared in my Downloads

This is not normal. I would suggest deleting the env and re-creating it. There is no need to reinstall either numpy or deeplabcut. Please find the latest windows file here: https://github.com/AlexEMG/DeepLabCut/blob/master/conda-environments/dlc-windowsGPU.yaml

I would also triple check you have not installed BOTH CUDA 10 and CUDA 10.2; it is not trivial to remove CUDA if you installed the wrong version. https://dmitry.ai/t/topic/14

Lastly, if you computer goes to sleep, it will crash/stop training. Be sure you have all power/sleep modes correctly set.

**Comment by renniek** [comment]
Hi @MMathisLab 

Thanks for getting back to me!

I am pretty sure that I have CUDA 10.2 uninstalled, after checking my control panel (I wiped the whole computer):

![installations](https://user-images.githubusercontent.com/58533662/70856466-ac1f1c80-1e92-11ea-8b76-7d3ebdd6f8c1.PNG)

Is there another place I should look to check? After looking at the discussion on that article I am not 100% sure.

As for the installation, I am not sured what happened with the environment - I tried removing (using the conda remove --name my env --all) command, and checked that the environment had been removed, then re-installed. I downloaded the Windows environment file and did all of this yesterday. Each time I re-installed I got the text file that I mentioned above.

As for the training, it has gotten to 100,000 iters in ~3 hours on the Reaching video - I'm not sure how long it should take with the 2080, but reading that it can take up to 12 hours this seems possibly on par (as it has been accelerating while training). I'm still having some weird GPU stuff, though, with the "insufficient permission" and occasionally it dropping to 1% usage then going back up. Have you experienced any of this with a GPU?

Thank you again in advance,

**Comment by MMathisLab** [comment]
Sounds like it is working then. The GPU will occasionally drop to 1% as there are points when the CPU is used to process a new frame. I wouldn't train the reaching-fully, it's just a demo and not a working demo, i.e. it's just for you to get roughly familiar with the setup before moving on. https://github.com/AlexEMG/DeepLabCut/blob/master/examples/README.md#demo-1-run-deeplabcut-on-our-open-field-data

**Comment by renniek** [comment]
Thanks so much for explaining that! @MMathisLab
