### ISSUE TITLE
Label_iteration_evaluation results -- refinement

### ISSUE THREAD

**Issue by JXXCgit** [DeepLabCut/DeepLabCut#531]
Hi, Dear all, 
I am using DLC to train my data. I label 20 frames, 200000 iterations. 
The final evaluation for a video small as 15 MB(210 frames) is quite ok,  but  very bad for videos bigger as 400MB(3200 frames). And my original video is even larger as 3.5GB(54060 frames). 
So what I can do for improvement?
Thank you in advance for suggestions. 
Best, 
Chen

**Comment by AlexEMG** [comment]
Check out the DLC workflow --- you can label more frames, especially by picking the ones where your current DLC model fails! 
![image](https://user-images.githubusercontent.com/20850270/70931777-2de38700-2006-11ea-8d20-6625837bfb1c.png)

To do so check out: **"Stage X: (optional) network refinement—extraction of outlier frames"** in https://www.nature.com/articles/s41596-019-0176-0

P.S. he video size plays no role for performance beyond the frame number.
