### ISSUE TITLE
I could not crop the videos whether in automatic or manual way.

### ISSUE THREAD

**Issue by lovebaboon1989** [DeepLabCut/DeepLabCut#532]
windows 10, deeplabcut 2.1.4, NVIDIA driver 441.66, CUDA 10.2. Using local Spyder on Anaconda 3.7 GPU environment

I tried to use either dlc.extract_frames(config,'automatic',crop=True) or dlc.extract_frames(config,'manual')
But when I use the automatic way, there is "UnboundLocalError: local variable 'image' referenced before assignment";
And when I use the manual way, after I load the video on the GUI window,  there is "KeyError: D:\\lab\\1\\videos\\test.mp4"

Many thanks.

**Comment by MMathisLab** [comment]
Then there is a typo in your config.yaml file

**Comment by lovebaboon1989** [comment]
> Then there is a typo in your config.yaml file

Thanks for your reply, but the cropping parameters are all default settings  generated from dlc.create_new_project.  I will double check my config.yaml file because I created the new project on google colab and extract frames on laptop before the GUI error came out, but the cropping GUI will work when I do these two functions together on the same laptop. Will catch you later.

**Comment by MMathisLab** [comment]
Hi, 
I understand, but I know when those errors occur, there is a typo somewhere in the config.yaml file. PLease carefully check what you edited; i.e. bodyparts, skeleton, spacing, etc. You can look at the demo ones for correct formatting.
