### ISSUE TITLE
What does the x/y coordinate of labels in csv generated from dlc.analyze_videos mean?

### ISSUE THREAD

**Issue by lovebaboon1989** [DeepLabCut/DeepLabCut#533]
windows 10, deeplabcut 2.1.4, NVIDIA driver 441.66, CUDA 10.2. Using local Spyder on Anaconda 3.7 GPU environment

I am trying to use dlc.analyze_videos to generate a csv that could be read by matlab, but I am a little confused about the value of x,y coordinate. Let's say the original video is resoluted by 100*100 pixels, but the x/y coordinate of the generated csv can usually be non-integers with endless digits, but should the coordinate of the labels be based on the original integer pixel coordinate?

Many thanks.

**Comment by MMathisLab** [comment]
I answered on image forum: https://forum.image.sc/tags/deeplabcut

**Comment by lovebaboon1989** [comment]
> I answered on image forum: https://forum.image.sc/tags/deeplabcut

Dear Mathis,
Many thanks.
