### ISSUE TITLE
Docker-DLC not really used

### ISSUE THREAD

**Issue by JXXCgit** [DeepLabCut/DeepLabCut#535]
Hi, Dear all, 
I followed 'https://github.com/MMathisLab/Docker4DeepLabCut2.0' to build my docker env for using DLC. Everything seems to sucessfully until the training step. 
The followed is the status of my docker usage, which indicate it works:
![Screenshot from 2019-12-27 16-56-05](https://user-images.githubusercontent.com/40397232/71523547-d973bd80-28c9-11ea-9627-d088ef2f7669.png)
But when i start to do the training, 
it still takes a very long time to train as when i use cpu to do the training, i  go 'nvidia-smi' to check, 
still as like this 
![Screenshot from 2019-12-27 16-48-04](https://user-images.githubusercontent.com/40397232/71523613-1b9cff00-28ca-11ea-8c71-49d7989800b0.png)
NO CHANGE. I am really wonder whether it use the docker-gpu to do the training. 
Something wrong? Appreciate for help!! 
Best, 
Chen

**Comment by MMathisLab** [comment]
Hello, please post issues relating to https://github.com/MMathisLab/Docker4DeepLabCut2.0 on that repo so we can appropriately help. Thanks!
