### ISSUE TITLE
Issue with labeling frames

### ISSUE THREAD

**Issue by AneeshBoreda** [DeepLabCut/DeepLabCut#538]
**Your Operating system and DeepLabCut version**

OS: Windows 10
DeepLabCut Version: 2.1.4, using Anaconda
Browser: Firefox

**Describe the problem**
After running the basic setup code:
```
deeplabcut.create_new_project('test1','ab',[videos_folder+'p4.avi'])
deeplabcut.extract_frames(config_path)
```
The extract frames command runs successfully
> Config file read successfully.
> Frames were selected.
> You can now label the frames using the function 'label_frames' (if you extracted enough frames for all videos).

However, once I run the label_frames command and select the videos folder to load the data from in the GUI, it gives the following error:
```
IndexError                                Traceback (most recent call last)
D:\Users\Aneesh Boreda\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\generate_training_dataset\labeling_toolbox.py in browseDir(self, event)
    464 
    465 # Reading the image name
--> 466         self.img = self.index[self.iter]
    467         img_name = Path(self.index[self.iter]).name
    468         self.norm,self.colorIndex = self.image_panel.getColorIndices(self.img,self.bodyparts)

IndexError: index 0 is out of bounds for axis 0 with size 0
```

Any help on how to fix this? I feel like I may be choosing the wrong folder when using load frames in the GUI.

**Comment by MMathisLab** [comment]
are there images in the p4 folder?

**Comment by AneeshBoreda** [comment]
@MMathisLab There are no images in the folder that contains the p4.avi video. Is extract_frames supposed to create the images from the video frames?

**Comment by MMathisLab** [comment]
Then please carefully check you typed in your `config_path` correctly, as if you only do this (below), `config_path` is pointing to nothing, so it will not extract any frames. 

```
deeplabcut.create_new_project('test1','ab',[videos_folder+'p4.avi'])
deeplabcut.extract_frames(config_path)
```

**Comment by AlexEMG** [comment]
And "deeplabcut.extract_frames(config_path)" is supposed to extract frames. See "Stage III: data selection" in https://www.nature.com/articles/s41596-019-0176-0

Is your video readable?

**Comment by lielmoalem12** [comment]
Make sure your config path contains the path to the video.
You should find the images extracted in Project_folder/labeled-data. You should a see a folder with the same name as your video. try to load this one in the labeling tool. After you finish annotating don't forget to press save(I had to make the GUI full-screen to realize that there's save button, didn't appear in the default window size). Then you should see inside that folder a h5 file containing annotated data.

**Comment by Elizabethj310** [comment]
I am having this same issue where I am getting an IndexError: index 0 is out of bounds for axis 0 with size 0 and no images in the labeled frames folders but have the config path contains the path to the video and the project was created using the path to each specific video.

**Comment by Elizabethj310** [comment]
![image](https://user-images.githubusercontent.com/61161524/77971010-432daa00-72b3-11ea-950e-80c8ea155a4f.png)

**Comment by MMathisLab** [comment]
> no images in the labeled frames folders 

Then the extraction did not work; are you sure the video is being called correctly? Can you check your `config.yaml` file and see what the `video_sets`  says?

**Comment by Elizabethj310** [comment]
![image](https://user-images.githubusercontent.com/61161524/78089968-7abd5480-738e-11ea-8277-330c49494c92.png)

It has all of the videos listed correctly that I have added to the project.
