### ISSUE TITLE
FileNotFoundError: File *.h5 does not exist (MakingLabeledVideo.py fails if ffmpeg not installed)

### ISSUE THREAD

**Issue by caniko** [DeepLabCut/DeepLabCut#54]
**Describe the problem**
I am in the process of analyzing my videoes, but have a problem. I don't know what kind of an issue this is as this isn't my area of expertise.

**To Reproduce**
1. Configure myconfig_analysis.py (videotype='.mp4', scorer, task and date)
2. On elevated Anaconda Prompt, activate project env
3. set CUDA_VISIBLE_DEVICES=0
4. cd DeepLabCut/Analysis-tools
5. python AnalyzeVideos.py
6. python MakingLabeledVideo.py
7. Error: FileNotFoundError: File SocialNov1210_middleDeepCut_resnet50_socialSep02shuffle1_500.h5 does not exist
also:
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Screenshots**
![trouble](https://user-images.githubusercontent.com/29519599/44973069-99adf780-af5b-11e8-8d5d-fb4388328185.PNG)

**Additional context**
The video files are cropped. They are encoded from .avi to .mp4 with HEVC (H.265 format)

PC spec:
Windows 10 Pro
Ryzen 1700
gtx 1080 ti

**Comment by mmmlmmlml** [comment]
I have this probelm too. I find the name of *.h5 isn't as same as the one should be opened normorlly, But I can't solve this = =

**Comment by AlexEMG** [comment]
Looks like: https://github.com/AlexEMG/DeepLabCut/issues/45

The frames were created, but not the video?


@mmmmlmmlml can you post the output please?

**Comment by caniko** [comment]
This fixed it for me. I believe you mentioned this implicitely somewhere in the documentation:
`conda install -c conda-forge ffmpeg`

Thanks for pointing it out; great help.
Best regards

**Comment by mmmlmmlml** [comment]
And this is the output.
![1](https://user-images.githubusercontent.com/42773446/45006855-82d7d580-b02d-11e8-9aee-8caf0bbe5a4b.png)
![2](https://user-images.githubusercontent.com/42773446/45006867-95eaa580-b02d-11e8-849d-7ff0286f48e4.png)

**Comment by AlexEMG** [comment]
@mmmlmmlml 

That suggests that your video player does not support the codec with which the movie was generated.
Perhaps you can play around with the parameters the line 129 (or just run this in the console):

subprocess.call([
        'ffmpeg', '-framerate',
        str(clip.fps), '-i', 'file%04d.png', '-r', '30', '../'+vname + '_DeepLabCutlabeled.mp4'])

Perhaps make a wav if you are on windows (https://ffmpeg.org/ffmpeg.html#Video-Options).

**Comment by caniko** [comment]
You can also download VLC:
https://www.videolan.org/index.html

It is open source, efficient, and plays every format

**Comment by mmmlmmlml** [comment]
When I change the format of the video such as avi./wmv., it's worked but the video is not as clear as before. Ha~

Thank you for your help, Alex~  
And Thank you Caniko ~
