### ISSUE TITLE
LinAlgError when filtering DeepLabCut predictions using ARIMA

### ISSUE THREAD

**Issue by johnmbarrett** [DeepLabCut/DeepLabCut#540]
**Describe the bug**
It is possible for DeepLabCut to produce a set of trajectories that, when filtered using the `method='arima'` argument to the `filter_predictions` function, throw a LinAlgError. I believe this to be related to a known bug in statsmodels: [https://github.com/statsmodels/statsmodels/issues/5459](https://github.com/statsmodels/statsmodels/issues/5459)

**To Reproduce**
1. Download the attached ipynb  and minimal DeepLabCut project folder needed to reproduce the error: [pathological_sarimax.zip](https://github.com/AlexEMG/DeepLabCut/files/4043439/pathological_sarimax.zip)
2. Change the paths in the ipynb and config.yaml to point to wherever you downloaded them
3. Run the IPython notebook
4. You should get the error "LinAlgError: LU decomposition error." The full stack trace can be seen in the notebook before you run it, but I've copied a snippet below:

```
LinAlgError                               Traceback (most recent call last)
<ipython-input-1-f8cdb95d797e> in <module>
      4 videosToAnalyse = [r'Z:\LACIE\DATA\John\Videos\seed handling\dlc\Test-John-2020-01-05\videos\test.avi']
      5 
----> 6 deeplabcut.filterpredictions(path_config_file,videosToAnalyse,filtertype='arima')

~\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\post_processing\filtering.py in filterpredictions(config, video, videotype, shuffle, trainingsetindex, filtertype, windowlength, p_bound, ARdegree, MAdegree, alpha, save_as_csv, destfolder)
    113                         if filtertype=='arima':
    114                             meanx,CIx=FitSARIMAXModel(x,p,p_bound,alpha,ARdegree,MAdegree,False)
--> 115                             meany,CIy=FitSARIMAXModel(y,p,p_bound,alpha,ARdegree,MAdegree,False)
    116 
    117                             meanx[0]=x[0]

...

statsmodels\tsa\statespace\_representation.pyx in statsmodels.tsa.statespace._representation.dStatespace.initialize()

statsmodels\tsa\statespace\_initialization.pyx in statsmodels.tsa.statespace._initialization.dInitialization.initialize()

statsmodels\tsa\statespace\_initialization.pyx in statsmodels.tsa.statespace._initialization.dInitialization.initialize_stationary_stationary_cov()

statsmodels\tsa\statespace\_tools.pyx in statsmodels.tsa.statespace._tools._dsolve_discrete_lyapunov()

LinAlgError: LU decomposition error.
```

**Expected behavior**
The predictions are filtered without error.

**Desktop (please complete the following information about your system):**
 - OS: Windows 10 x64
 - DeepLabCut Version: 2.1.4
 - Statsmodels Version: 0.10.1
 - Python Version: Python 3.6.9 :: Anaconda, Inc.
 - Browser: Firefox 71.0

**Additional context**
Adding `initialization='approximate_diffuse'` to the SARIMAX call, as suggested in the linked statsmodels issue, on line 217 of outlier_frames.py fixes the issue (for this video and every other one I've tried so far, at least), so maybe this could be an option in `filter_predictions`/`extract_outliner_frames`. A more general fix would be let the user pass through all the various options to the SARIMAX model, but obviously that's a lot of effort for a bug that apparently only affects one video (given no one else seems to have reported this issue as far as I can tell from searching).

I appreciate this might be a fairly low priority issue if I am indeed the only DLC user to have ever run into it, so feel free to close/ignore, but I figure at least having this here will help point anyone who runs into it in the future to know which bit of the DLC code to fiddle to get around it :)

**Comment by MMathisLab** [comment]
@johnmbarrett firstly, thanks for the nicely formatted issue(s) and documentation of it.

I'll leave open and we can work it into a future version, although I agree it seems not many have hit this issue (but still good to fix!) thanks for contributing to DLC!

**Comment by MMathisLab** [comment]
@johnmbarrett I didn't test your specific issue again, but we tested the latest statsmodel is compatible now with DLC so perhaps you could test with `deeplabcut==2.1.6`; and if persistent please make a PR.

**Comment by linussun** [comment]
I have roughly the same set up as @johnmbarrett, and I am using deeplabcut==2.1.6.

I am also still getting a LinAlgError: LU decomposition error with filterpredictions method. Adding the initialization='approximate_diffuse' to line 217 of outlier_frames.py did not solve the error unfortunately.

**Comment by MMathisLab** [comment]
Hi @linussun can you try with the latest statsmodel version? Also, on their GitHub issue (linked above), another solution was: enforce_stationarity=False

**Comment by jeylau** [comment]
The latest statsmodels version may indeed help in some cases, as approximate diffuse initialization is used by default. @MMathisLab For the sake of robustness, what would you say about catching the error and falling back automatically to the non-stationary model?

**Comment by MMathisLab** [comment]
I think that's a great suggestion, thanks @jeylau !
