### ISSUE TITLE
extract_outlier_frames with extractionalgorithm='kmeans' fails if only one outlier is found

### ISSUE THREAD

**Issue by johnmbarrett** [DeepLabCut/DeepLabCut#542]
**Describe the bug**
`extract_outlier_frames` fails with a `ValueError` if run on a video with only one outlier when `extractionalgorithm='kmeans'`

**To Reproduce**
1a. Download the [minimal DLC project folder](https://drive.google.com/open?id=1TVLxHXWCD0Q8P2piD3bcHp1wubIwv4L5) needed to reproduce the issue (the original video that caused the issue is 4GB, so I didn't want to attach it directly, but in the end I replaced it with a smaller one)
1b. Alternatively, create your own DLC project and adjust the parameters to `extract_outlier_frames` (making sure `extractionalgorithm='kmeans'`) until you only get one outlier
2. Change the included IPython notebook and config.yaml to match the paths on your system
3. Run the included IPython notebook
4. Get the following error:

```
ValueError                                Traceback (most recent call last)
<ipython-input-3-d4318e33ff51> in <module>
----> 6     deeplabcut.extract_outlier_frames(path_config_file,videosToAnalyse,outlieralgorithm='jump',epsilon=100,extractionalgorithm='kmeans',automatic=True,comparisonbodyparts=['LD2','LD3','Nose','RD2','RD3'])

~\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\refine_training_dataset\outlier_frames.py in extract_outlier_frames(config, videos, videotype, shuffle, trainingsetindex, outlieralgorithm, comparisonbodyparts, epsilon, p_bound, ARdegree, MAdegree, alpha, extractionalgorithm, automatic, cluster_resizewidth, cluster_color, opencv, savelabeled, destfolder)
    194               if askuser=='y' or askuser=='yes' or askuser=='Ja' or askuser=='ha': # multilanguage support :)
    195                   #Now extract from those Indices!
--> 196                   ExtractFramesbasedonPreselection(Indices,extractionalgorithm,Dataframe,dataname,scorer,video,cfg,config,opencv,cluster_resizewidth,cluster_color,savelabeled)
    197               else:
    198                   print("Nothing extracted, please change the parameters and start again...")

~\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\refine_training_dataset\outlier_frames.py in ExtractFramesbasedonPreselection(Index, extractionalgorithm, Dataframe, dataname, scorer, video, cfg, config, opencv, cluster_resizewidth, cluster_color, savelabeled)
    340     elif extractionalgorithm=='kmeans':
    341         if opencv:
--> 342             frames2pick=frameselectiontools.KmeansbasedFrameselectioncv2(cap,numframes2extract,start,stop,cfg['cropping'],coords,Index,resizewidth=cluster_resizewidth,color=cluster_color)
    343         else:
    344             if  cfg['cropping']:

~\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\utils\frameselectiontools.py in KmeansbasedFrameselectioncv2(cap, numframes2pick, start, stop, crop, coords, Index, step, resizewidth, batchsize, max_iter, color)
    233 
    234         kmeans=MiniBatchKMeans(n_clusters=numframes2pick, tol=1e-3, batch_size=batchsize,max_iter=max_iter)
--> 235         kmeans.fit(data)
    236         frames2pick=[]
    237         for clusterid in range(numframes2pick): #pick one frame per cluster

~\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\sklearn\cluster\_k_means.py in fit(self, X, y, sample_weight)
   1507         if n_samples < self.n_clusters:
   1508             raise ValueError("n_samples=%d should be >= n_clusters=%d"
-> 1509                              % (n_samples, self.n_clusters))
   1510 
   1511         sample_weight = _check_normalize_sample_weight(sample_weight, X)

ValueError: n_samples=1 should be >= n_clusters=2
```

**Expected behavior**
`extract_outlier_frames` just gives you the one frame it found without running the kmeans step.

**Desktop (please complete the following information about your system):**
 - OS: Windows 10 x64
 - DeepLabCut Version: 2.1.4
 - Browser: Firefox 71.0

**Additional context**
Adding

```
    if len(Index) == 1:
        frames2pick=Index
    el
```

to the beginning of line 330 of outlier_frames.py is one possible way to fix the issue.

**Comment by johnmbarrett** [comment]
~~I just realised that when I discovered this it was after making some modifications to the jump outlier detection algorithm for my own needs, so this may not actually reproduce on other users' systems. I will try and come up with an even more minimal, actually working example and edit the issue.~~

The attached DLC project folder should now be sufficient to reproduce the issue even with the unmodified DLC 2.1.4 jump algorithm

**Comment by johnmbarrett** [comment]
Actually, turns out the issue is slightly more general than what I originally posted, as it seems you get the same error any time the number of detected frames is less than the number of frames to pick and the extraction algorithm is kmeans. For example, I just found a video with 3 outliers when I was trying to pick 4 and got `ValueError: n_samples=3 should be >= n_clusters=4`. One solution to this more general bug would be to add

```
        if len(Index) < numframes2extract:
            frames2pick=Index
        el
```

at the beginning of line 336 of outlier_frames.py, instead of my original suggestion.

**Comment by AlexEMG** [comment]
Thanks for raising this issue! We fixed it and it in release https://github.com/AlexEMG/DeepLabCut/releases/tag/v2.1.5
