### ISSUE TITLE
Issue Training Network:  Config file is not found. Please make sure that the file exists and/or there are no unnecessary spaces in the path of the config file!

### ISSUE THREAD

**Issue by NeuroKween** [DeepLabCut/DeepLabCut#547]
DLC version 2.1.5
Browser: Chrome 

I'm using the GUI to train a video. On the tab for "Train Network" I get the following error message when I click on "click to open the pose config file".  Any suggestions on how to rectify this? 
```
FileNotFoundError                         Traceback (most recent call last)
~\Anaconda3\lib\site-packages\deeplabcut\gui\train_network.py in edit_pose_config(self, event)
    206             self.file_open_bool = webbrowser.open(self.pose_cfg_path)
    207         if self.file_open_bool:
--> 208             self.pose_cfg = auxiliaryfunctions.read_config(self.pose_cfg_path)
    209         else:
    210             raise FileNotFoundError("File not found!")

~\Anaconda3\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py in read_config(configname)
    122                   write_config(configname,cfg)
    123     else:
--> 124         raise FileNotFoundError ("Config file is not found. Please make sure that the file exists and/or there are no unnecessary spaces in the path of the config file!")
    125     return(cfg)
    126

FileNotFoundError: Config file is not found. Please make sure that the file exists and/or there are no unnecessary spaces in the path of the config file!


```

**Comment by MMathisLab** [comment]
It works for me w/2.1.5. Did you edit the config file path (you shouldn't after you load the project)? Here is a demo on how to use it:


![ezgif com-video-to-gif](https://user-images.githubusercontent.com/28102185/72389295-057aa580-36f6-11ea-9f7c-f3c826b2ed9c.gif)

**Comment by plant1987** [comment]
> It works for me w/2.1.5. Did you edit the config file path (you shouldn't after you load the project)? Here is a demo on how to use it:
> 
> ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/28102185/72389295-057aa580-36f6-11ea-9f7c-f3c826b2ed9c.gif) [ ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/28102185/72389295-057aa580-36f6-11ea-9f7c-f3c826b2ed9c.gif) ](https://user-images.githubusercontent.com/28102185/72389295-057aa580-36f6-11ea-9f7c-f3c826b2ed9c.gif) [ ](https://user-images.githubusercontent.com/28102185/72389295-057aa580-36f6-11ea-9f7c-f3c826b2ed9c.gif)

Hi there,
I also get this error. And, I have fixed it by following the steps of the video, it works. 

 However, when I run the code in the terminal(ipython, or jupyternotebook), it get the error again. I think it was caused by the system that do not allow the access.  It may need to set the system variable so that the deeplabcut can read from the installation folder.


![Screenshot 2024-05-25 003533](https://github.com/DeepLabCut/DeepLabCut/assets/71976453/0d3eb5be-c1c5-4d76-a2c4-f0ffaa7f18cf)
