### ISSUE TITLE
draw_skeleton, "skeleton" key word error (typo in config.yaml file)

### ISSUE THREAD

**Issue by LightingMc** [DeepLabCut/DeepLabCut#548]
**Your Operating system and DeepLabCut version**
OS: Linux Mint Tara. However, this error is being faced on Google Colab (GPU is on).
DLC: 2.1.5
**Describe the problem**
![image](https://user-images.githubusercontent.com/42900802/72384489-90a26e00-36eb-11ea-8809-c0d064968d20.png)

It is gives an error when I try to plot the skeleton. Otherwise with the trailpoints and save_frames on, it works fine. 

I thought that the main issue might be how the skeleton is defined in the config.yaml file. I have tried various ways of writing this skeleton. This is what the current version looks like:
![image](https://user-images.githubusercontent.com/42900802/72384847-42419f00-36ec-11ea-85de-128ad374debd.png)

Things I have tried to resolve this:
1. Adding commas to the skeleton layout:
From    - - Head       ----->          - - 'Head'
or removing the empty line between the consecutive pairs.

2. I tried converting the skeleton to a list of the form: [['Head','Neck'],['Neck','rArm'],['Neck','lArm'],['Neck','Hip'],['rKnee','Hip'],['lKnee','Hip']]. Doing this destroys the config.yaml file. DLC won't accpet it. 
     
Also tried putting in spaces between the sublists in this list:
[['Head','Neck'],['Neck','rArm']] ----> [['Head','Neck'], ['Neck','rArm']] 
     

and removing the commas around the elements 
[['Head,'Neck'],['Neck','rArm']] ----> [[Head,Neck],[Neck,rArm]]

None of them work.

**Comment by LightingMc** [comment]
One more thing...it is a purely 2D video...I am not doing that 3D thing.

**Comment by AlexEMG** [comment]
There are mulitple ways to define the skeleton, but it should not be captitalized I think. See this example: https://github.com/AlexEMG/DeepLabCut/blob/master/examples/Reaching-Mackenzie-2018-08-30/config.yaml#L24

**Comment by MMathisLab** [comment]
I also just checked on colab, this demo notebook, and it works fine if I edit the config.yaml correctly to add a skeleton, so it's likely a typo in your `config.yaml` file. 

![image](https://user-images.githubusercontent.com/28102185/72388402-d8c58e80-36f3-11ea-9204-e524a09de816.png)

![image](https://user-images.githubusercontent.com/28102185/72388471-0d394a80-36f4-11ea-9b65-91976356f5f2.png)

**Comment by LightingMc** [comment]
[AlexEMG](https://github.com/AlexEMG/DeepLabCut/issues/548#issuecomment-574400597) was right. Skeleton is supposed to be all lower case. Thanks a lot. My bad.
And here are the results, feast your eyes because you all are awesome: [Link for video](https://youtu.be/a7HOXXoTZ08)
