### ISSUE TITLE
Making DeepLabCut a Python package

### ISSUE THREAD

**Issue by vvolhejn** [DeepLabCut/DeepLabCut#55]
Hi,   
DeepLabCut is very cool, however the structure of the project could be a bit more pythonic. Data and code are mixed freely in the directory structure, and there are some hacky bits, like in `Generating_a_Training_Set`, to import `myconfig`, there is `sys.path.append(os.getcwd().split('Generating_a_Training_Set')[0])`, which is very nonstandard.

To improve on this, I would suggest making DeepLabCut into a Python package installable using `setuptools`. Advantages include:
- A clear code x data split
- better `git ignore`ability
- ability to use relative imports, without modifying `sys.path`. In `Step2`, we could just `import .myconfig`
- being pythonic/idiomatic, more understandable by developers unfamiliar with the project
- the package could be made installable through `pip` which would simplify installation
- could be run as a module from anywhere using something like `python -m deeplabcut.train`

This would involve
- moving all source code into `deeplabcut/`, structuring it into directories
- making a `setup.py`
- fixing hardcoded paths currently in the project

What do you think? I would be willing to do this myself, however I would like to know whether the original devs would be interested, because I know this is not a trivial change.

**Comment by MMathisLab** [comment]
We agree it’s not very “Pythonisa,” but we decided to release this version 1.0 first as for new users to Python, and those new to coding, we hoped the code would be easy to follow and understand. We have a pip installable version that will be released very soon, so stay tuned! We welcome those interested to join the slack group if you would like to contribute to ongoing development and extension discussions

**Comment by vvolhejn** [comment]
Glad to hear that, I'd be happy to join!

**Comment by MMathisLab** [comment]
Can you shoot me an email at mathis@rowland.harvard.edu and I’ll add you to the group

**Comment by AlexEMG** [comment]
https://pypi.org/project/deeplabcut/
