### ISSUE TITLE
train_network.py IndexError: sequence index out of range

### ISSUE THREAD

**Issue by ghost** [DeepLabCut/DeepLabCut#552]
OS: Windows 10
DeepLabCut Version: 2.1.5, GUI

I receive the following error when attempting to initialize the Train Network step using the GUI defaults (Shuffle=1, trainingsetindex = 0). The error is thrown and the training does not start. 

It seems the frames extracted fine and I was able to successfully create the training data set. 

`---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
c:\anaconda3\envs\dlc-windowsgpu\lib\site-packages\deeplabcut\gui\train_network.py in train_network(self, event)
    230
    231     def train_network(self,event):
--> 232         shuffle = int(self.shuffles.Children[0].GetValue())
    233         trainingsetindex = int(self.trainingindex.Children[0].GetValue())
    234         max_snapshots_to_keep = int(self.snapshots.Children[0].GetValue())

IndexError: sequence index out of range`

pose_cfg.yaml files are successfully created in the train and test folders, and a CollectedData.h5 file is produced in the UnaugmentedDataSet subfolder. 

Seems like this is likely a fairly simple error, but I haven't been able to root out the issue... Any help would be greatly appreciated!

**Comment by MMathisLab** [comment]
https://github.com/AlexEMG/DeepLabCut/pull/555
