### ISSUE TITLE
Train network ERROR: 'sequence index out of range'

### ISSUE THREAD

**Issue by EmmettJT** [DeepLabCut/DeepLabCut#553]
Hi, 

System:
Ubuntu 18.04 using the anaconda env, TF and DLC version provided here: https://github.com/AlexEMG/DeepLabCut/tree/master/conda-environments

GPU/drivers/CUDA version:

![Screenshot from 2020-01-16 13-47-02](https://user-images.githubusercontent.com/43346332/72530685-c8cebb80-3867-11ea-9c9c-b2fd84441966.png)
                                                                              
I am trying DLC using the GUI for the first time and so attempting to train a network using a small data set (20 labelled images). Everything seems to be working smoothly and I am also able to import tf and start a session so tf seems to be working okay:

![Screenshot from 2020-01-16 13-49-33](https://user-images.githubusercontent.com/43346332/72530627-a6d53900-3867-11ea-80de-7f66d0aa4657.png)

However, when i click 'train network' I immediately see this error message:

![Screenshot from 2020-01-16 13-46-33](https://user-images.githubusercontent.com/43346332/72530662-bbb1cc80-3867-11ea-9d2c-66ed3b9e3548.png)

It seems like I have forgotten to do something when setting up the dataset but I cannot work out what it is, please help! Thanks!

**Comment by MMathisLab** [comment]
Fix coming up!

**Comment by MMathisLab** [comment]
https://github.com/AlexEMG/DeepLabCut/pull/555
