### ISSUE TITLE
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

### ISSUE THREAD

**Issue by angelgho** [DeepLabCut/DeepLabCut#556]
**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: Ubuntu 18.04.3 LTS
DeepLabCut Version: not sure, because I cannot import
but should be the latest version from github with conda-environment
Browser: no browser

**Describe the problem**
After creating the environment for Ubuntu, I activated the environment.
Then I activate ipython and type import deeplabcut.
It returns the following:
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

I checked the matplotlib is 3.0.3

**How to Reproduce the problem**
1. git cloned Deeplabcut
2. created environment in Anaconda
3. activated environment dlc-ubuntu-GPU
4. ipython
5. import deeplabcut
6. the following appeared

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/59353353/72605040-5d681500-395f-11ea-966e-e8890886680b.png)

**Comment by MMathisLab** [comment]
your screenshot looks like windows, not:


> OS: Ubuntu 18.04.3 LTS

If you are using Windows, you must use the dlc-windowsGPU or dlc-windowsCPU conda files. The ubuntu one will not work on windows.

If this is somehow ubuntu, then please check your backend settings for matplotlib.

**Comment by angelgho** [comment]
Hi, deeplabcut supporters,
Sorry I didn't specify my condition well enough.
I am using Windows Subsystem for Linux and install Ubuntu on my side.
I used SSH to connect my computer as a client to our lab computation cluster.
The cluster is using Ubuntu 18.04.3 LTS.
![Untitled](https://user-images.githubusercontent.com/59353353/72709729-da39ff80-3ba8-11ea-9025-7a11715d2e41.png)
On the server I installed the conda environment.
I think in this case I should use the Ubuntu version, am I right?
Also, I checked some old issues and found that maybe it is because the file server doesn't support GUI from deeplabcut.
I tried export DLClight=True and imported deeplabcut, it worked.
I guess that was the reason.
Please let me know if I was right on the above points or not.
Thank you very much.
Chen

**Comment by angelgho** [comment]
Just for documenting this issue.
I solved the problem.
It was because Windows Subsystem for Linux does not support X11 forwarding.
After I installed Xming and properly setup the monitor for output, everything worked.
Chen
