### ISSUE TITLE
extract_outlier_frames throws "UnboundLocalError"

### ISSUE THREAD

**Issue by rbpatt2019** [DeepLabCut/DeepLabCut#559]
**Describe the bug**
I have successfully trained my network and am looking to refine it's performance. When calling `extract_outlier_frames(config_path, [videos], videotype=".m4v")`, kmeans clustering proceeds as expected. After indicating which frames are to be selected, the codes fails with an UnboundLocalError that reads "local variable 'image' referenced before assignment. "

**To Reproduce**
1. Launch pythonw
2. Execute:
```python
import deeplabcut as dlc
config_path = "/your/path/here/config.yaml"
videos = "/your/path/here/videos/"
dlc.extract_outlier_frames(config_path, [videos], videotype=".m4v")
```

**Expected behavior**
The code should proceed through all videos, selecting the specified number of frames.

**Screenshots**
I have attached a screenshot of the executed code producing the error, and 2 additional photos, showing the results of `conda list` for the activated environment.
<img width="240" alt="UnboundLocalError" src="https://user-images.githubusercontent.com/43184541/72848442-96133180-3c72-11ea-987c-45262d1553ab.png">
<img width="320" alt="Conda environment 2" src="https://user-images.githubusercontent.com/43184541/72848443-96133180-3c72-11ea-9905-e1f177bdd64b.png">
<img width="240" alt="Conda environment 1" src="https://user-images.githubusercontent.com/43184541/72848444-96133180-3c72-11ea-82ae-20a637ffad51.png">

**Desktop (please complete the following information about your system):**
 - OS: iOS (Catalina)
 - DeepLabCut Version 2.1.5.2
 - No browser. In terminal.app.

**Additional context**

- The conda environment in which I am working was created using the `dlc-macOS-CPU.yaml` environment file provided in the `deeplabcut` module. 
- I suspect this is related to #190 , and #199. However, the bug was reported to fixed in 2.0.4.1, and I'm using 2.1+. 
- In line with #190, I tried running `dlc.extract_outlier_frames` with `opencv=False`. This produced the error "RuntimeError: imagio.ffmpeg.download() has been deprecated. Use 'pip install imageio-ffmpeg' instead." After trying `pip install` as instructed, the error persists - I suspect because I haven't changed that import in the source code.

Thanks for the help!

**Comment by jeylau** [comment]
The error occurs when a frame could not be read. Was it thrown right on the first selected frame?

**Comment by rbpatt2019** [comment]
Indeed! Kmeans clustering proceeded normally, the list of frames indices to be used was returned to the terminal, then the error was thrown. 
It's probably also worth noting that the error persisted regardless of videotype (I tried 4 different formats) and occurs when run through the new GUI manager as well.
I see you've already pushed a patch - thanks! Once it gets merged into master, I'll pull the new version and close this issue.

**Comment by rbpatt2019** [comment]
As a quick follow up, why would the frame not be read? The videos play properly, so they shouldn't be corrupted, etc.

**Comment by jeylau** [comment]
That could occur when there are no more frames to grab, or when trying to grab one at a position that exceeds the total number of frames. What are the 'start' and 'stop' values in your config.yaml?

**Comment by rbpatt2019** [comment]
My start is 0, stop is 1, and numframes2pick is 5 (as I'm extracting from a number of videos).

**Comment by MMathisLab** [comment]
Side note: Be sure when yo run this it is binding to the correct pythonw version: 

'pip install imageio-ffmpeg'

**Comment by MMathisLab** [comment]
this is now merged into the repo. https://github.com/AlexEMG/DeepLabCut/commit/9c32a3e006e7d8010eca5f58ca36cc5c35eead44
