### ISSUE TITLE
Real Time Webcam Analysis

### ISSUE THREAD

**Issue by MoustafaAyoub** [DeepLabCut/DeepLabCut#56]
When labeling any video you first have to run the AnalyzeVideos.py script then MakingLabeledVideos.py script. This will work only on pre-recorded videos.

Can someone assist me with the proccess of applying these labels live on webcam video?

I suppose we can also use a simpler model then resnet, something like mobilenet. Any suugestions?

**Comment by KennyTC** [comment]
Hello, 
I would like to continue this thread. 
Currently, does DLC support inference from Webcam? 
Or 
Is this ok to write a program to read each frame from Webcam, then use DLC to predict on each frame?
Thanks,

**Comment by sfdye** [comment]
It'd super interesting to integrate with something like
https://github.com/blakeblackshear/frigate

so that it can detect pets peeing/pooping in real-time from the webcam feed and send alerts through smart home system
