### ISSUE TITLE
'bool' object is not iterable (in main GUI, Analyze video with cropping the video)

### ISSUE THREAD

**Issue by Shachafbe** [DeepLabCut/DeepLabCut#560]
Windows 10, anaconda 3, GPU, DLC 2.1.5.2

After using DLC 2.0 for a few months (thank you for this tool!), I just updated to the new version of DLC. 
When using the new GUI, Analyze video **with cropping the video** gives the message:
"'bool' object is not iterable"
![dlc](https://user-images.githubusercontent.com/53897118/72875561-31e97f80-3cfd-11ea-9dd0-702e8e17d0aa.png)

Without cropping the analyzation now runs very slow. I must have deleted something with updating.. not sure what. 

Thank you so much for your amazing work, 
can't wait for the multiple animals' update!!!!

**Comment by jeylau** [comment]
Good catch! Rather than True/False, the GUI should rather ask the user for the cropping coordinates. Otherwise, there is no way to get them from the config when analyzing new videos. We will push a fix within the next couple of hours.
