### ISSUE TITLE
Ubuntu Docker Image - ERROR: No matching distribution found for intel-openmp (from deeplabcut)

### ISSUE THREAD

**Issue by kristakernodle** [DeepLabCut/DeepLabCut#565]
I looked through the issues and noticed this was flagged for mac OS, but I'm having issues on Linux?

The docker image runs into issues on the "pip3 install deeplabcut" command in the docker file. See below. Everything up to this step (11/14) works fine and my network connection does not appear to be the issue. I've attempted resetting docker, this also has not worked. 

I do get the cautionary line "debconf: delaying package configuration, since apt-utils is not installed"
during step 8/14: RUN apt-get -y install ffmpeg

But this seems to be a notice with little significance.

> Step 11/14 : RUN pip3 install deeplabcut
 ---> Running in 36a781759b54
Collecting deeplabcut
  Downloading deeplabcut-2.1.5.2-py3-none-any.whl (385 kB)
Requirement already satisfied: wheel in /usr/local/lib/python3.6/dist-packages (from deeplabcut) (0.30.0)
Collecting easydict
  Downloading easydict-1.9.tar.gz (6.4 kB)
Collecting numpy>=1.16.4
  Downloading numpy-1.18.1-cp36-cp36m-manylinux1_x86_64.whl (20.1 MB)
Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (from deeplabcut) (0.22.0)
Collecting requests
  Downloading requests-2.22.0-py2.py3-none-any.whl (57 kB)
Collecting tensorpack>=0.9.7.1
  Downloading tensorpack-0.9.8-py2.py3-none-any.whl (288 kB)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from deeplabcut) (1.11.0)
Requirement already satisfied: click in /usr/local/lib/python3.6/dist-packages (from deeplabcut) (6.7)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.6/dist-packages (from deeplabcut) (0.19.1)
Collecting patsy
  Downloading patsy-0.5.1-py2.py3-none-any.whl (231 kB)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.6/dist-packages (from deeplabcut) (2.6.1)
Collecting certifi
  Downloading certifi-2019.11.28-py2.py3-none-any.whl (156 kB)
Collecting h5py~=2.7
  Downloading h5py-2.10.0-cp36-cp36m-manylinux1_x86_64.whl (2.9 MB)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.6/dist-packages (from deeplabcut) (0.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from deeplabcut) (38.5.1)
Collecting matplotlib==3.0.3
  Downloading matplotlib-3.0.3-cp36-cp36m-manylinux1_x86_64.whl (13.0 MB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from deeplabcut) (4.19.5)
Collecting pyyaml>=5.1
  Downloading PyYAML-5.3.tar.gz (268 kB)
Collecting tables==3.4.3
  Downloading tables-3.4.3-cp36-cp36m-manylinux1_x86_64.whl (3.8 MB)
Requirement already satisfied: ipython in /usr/local/lib/python3.6/dist-packages (from deeplabcut) (6.2.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from deeplabcut) (1.0.0)
Collecting imgaug
  Downloading imgaug-0.3.0-py2.py3-none-any.whl (819 kB)
Collecting chardet
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
ERROR: Could not find a version that satisfies the requirement intel-openmp (from deeplabcut) (from versions: none)
ERROR: No matching distribution found for intel-openmp (from deeplabcut)
The command '/bin/sh -c pip3 install deeplabcut' returned a non-zero code: 1

**Comment by jeylau** [comment]
We are currently looking into it. Meanwhile, could you try downgrading pip using `pip install pip==19.3.1` and let us know if that works?

**Comment by SmoothCrimm** [comment]
Hi jeylau, using pip version 19.3.1 did not resolve this issue for me.

**Comment by MMathisLab** [comment]
Please post issues on Docker repo, not this one. This was just answered yesterday, see issues at our Docker repo.
