### ISSUE TITLE
Extract Outlier Frame Function (but No Errors)

### ISSUE THREAD

**Issue by zlevin2** [DeepLabCut/DeepLabCut#566]
**Your Operating system and DeepLabCut version**

Red Hat Enterprise Linux Server 7.3 on HPC, DeepLabCut/2.1.4, python/3.6.6 (tensorFlow 1.14.0)

**Describe the problem**

Running the function `deeplabcut.extract_outlier_frames(config_path,[video_path])` does not throw an error, but also does not extract frames or prompt the user at all. Have tried running the function in the GUI and command line with nothing happening in either case.

**Screenshots**

![image](https://user-images.githubusercontent.com/60200973/72938735-7e52b080-3d39-11ea-9031-58d94a8ac7af.png)

**Additional context**
numframes2pick set to 50 in config.yaml file. I had the same issue when running the demos.

I was able to extract frames with `deeplabcut.extract_frames(config_path, 'automatic')` for initial labeling to train the network, but did not get 50 frames, only got 23.

**Comment by rbpatt2019** [comment]
I'll second the last comment regarding `deeplabcut.extract_frames`. It worked successfully, but returned only 2/3 the number of frames as many could not be read.

**Comment by rbpatt2019** [comment]
Also, have you tried running `deeplabcut.analyze_videos` before extracting outliers? This is a necessary step, as the default selection algorithm uses information about the position labels to choose the outliers.

**Comment by zlevin2** [comment]
Yes, I've been making the video_path the path to the analyzed video (in my case .mp4).

**Comment by MMathisLab** [comment]
If the path is wrong, no error is thrown.

**Comment by zlevin2** [comment]
Thanks for the quick response. I checked the video path and am pretty sure that it is correct, but the function still does nothing.

**Comment by zlevin2** [comment]
Hi just wanted to follow up on this as I still haven't gotten the function to extract frames.

I've checked the path to the config file and the video file– both appear correct. I've also specified the video's format as '.mp4'. I tried specifying manual extraction, hoping to see the GUI pop up, but nothing happens this way either. 

Here is a screenshot of the string of commands I've tried (among others):

<img width="752" alt="Screen Shot 2020-01-27 at 7 35 16 PM" src="https://user-images.githubusercontent.com/60200973/73225960-65347000-413c-11ea-97a0-6c187e9fe913.png">


Thanks in advance.

**Comment by MMathisLab** [comment]
Two issues: 
Your path is incorrect. Config.yaml must be the FULL path to the file. 

You don’t pass the labeled video, you pass the video file that was analyzed in analyze_videos. 

Please check the docs as these steps are fully explained there.

**Comment by MMathisLab** [comment]
As a follow up:

- if your video is not analyzed first it says this:
```
deeplabcut.extract_outlier_frames(cfp,['/home/mackenzie/DEEPLABCUT/DeepLabCut/examples/openfield-Pranav-2018-10-30/videos/Cam0_sideView_Mausi_20190207_1.avi'])
It seems the video has not been analyzed yet, or the video is not found! You can only refine the labels after the a video is analyzed. Please run 'analyze_video' first. Or, please double check your video file path
```
- If your config.yaml path is not correct it throws this:

```
deeplabcut.extract_outlier_frames(cfp,['/home/mackenzie/DEEPLABCUT/DeepLabCut/examples/openfield-Pranav-2018-10-30/videos/Cam0_sideView_Mausi_20190207_1.avi'])
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-8-b07e4ab6b733> in <module>()
----> 1 deeplabcut.extract_outlier_frames(cfp,['/home/mackenzie/DEEPLABCUT/DeepLabCut/examples/openfield-Pranav-2018-10-30/videos/Cam0_sideView_Mausi_20190207_1.avi'])

/home/mackenzie/DEEPLABCUT/DeepLabCut/deeplabcut/refine_training_dataset/outlier_frames.py in extract_outlier_frames(config, videos, videotype, shuffle, trainingsetindex, outlieralgorithm, comparisonbodyparts, epsilon, p_bound, ARdegree, MAdegree, alpha, extractionalgorithm, automatic, cluster_resizewidth, cluster_color, opencv, savelabeled, destfolder)
    117     """
    118 
--> 119     cfg = auxiliaryfunctions.read_config(config)
    120     DLCscorer,DLCscorerlegacy=auxiliaryfunctions.GetScorerName(cfg,shuffle,trainFraction = cfg['TrainingFraction'][trainingsetindex])
    121     Videos=auxiliaryfunctions.Getlistofvideos(videos,videotype)

/home/mackenzie/DEEPLABCUT/DeepLabCut/deeplabcut/utils/auxiliaryfunctions.py in read_config(configname)
    125 
    126     else:
--> 127         raise FileNotFoundError ("Config file is not found. Please make sure that the file exists and/or that you passed the path of the config file correctly!")
    128     return(cfg)
    129 

FileNotFoundError: Config file is not found. Please make sure that the file exists and/or that you passed the path of the config file correctly!
```
