### ISSUE TITLE
is it possible to use the program with a non- NVIDIA GPU?

### ISSUE THREAD

**Issue by or-naim** [DeepLabCut/DeepLabCut#567]
Hi, is it possible to use DeepLabCut with a non NVIDIA GPU? (we are currently using Intel (r) UHD Graphics 630)

**Comment by MMathisLab** [comment]
https://github.com/AlexEMG/DeepLabCut/wiki/FAQ

**Comment by AlexEMG** [comment]
The short answer is no (due to TensorFlow)

________________________________

**Comment by or-naim** [comment]
Thanks. Trying to train with the CPU, hopefully will purchase a NVIDIA graphics card soon :)
