### ISSUE TITLE
Meaning of .h5 files obtained after using deeplabcut.triangulate( )

### ISSUE THREAD

**Issue by neuroscience-runner** [DeepLabCut/DeepLabCut#568]
OS: Ubuntu 16.04.6 LTS
DeepLabCut Version: 2.1.5
Browser: chrome

After running the function deeplabcut.triangulate( ) there are several data files that are placed into the video folder specified in the file path. It seems that for each video there are two .h5 files one filtered and one non-filtered as well as a file named _scorer3D.h5. Could you explain the differences between the filtered and non-filtered .h5 files as well as the meaning of the _scorer3D.h5 file?  

Thanks!

**Comment by MMathisLab** [comment]
Hi, we please ask you post questions on Image Forum: https://forum.image.sc/tag/deeplabcut

Please see here: https://github.com/AlexEMG/DeepLabCut/blob/master/README.md

Also, all files and functions are explained in the docs ;). 

Filtering: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#filter-data
3D file: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/Overviewof3D.md#4-triangulation----take-your-2d-to-3d
