### ISSUE TITLE
Modules in pose-tensorflow/nnet also in pose-tensorflow

### ISSUE THREAD

**Issue by vvolhejn** [DeepLabCut/DeepLabCut#57]
Hi,
each file in `pose-tensorflow/nnet/` has an identical or nearly identical counterpart in `pose-tensorflow/`; the ones in `pose-tensorflow/nnet/` are actually utilized while the others seem to be unused.

**Comment by AlexEMG** [comment]
Hi @IAmWave , this is useful for other calls of the functions that are not documented. Sorry for the confusion. Also the completely modularized DLC is coming soon...
