### ISSUE TITLE
Saving results in csv

### ISSUE THREAD

**Issue by NeuroKween** [DeepLabCut/DeepLabCut#570]
Hi, 

I'm using the DLC GUI and I've currently analyzed a video and forgot to select for a .csv output, so i've only got the .h5 file. I tried to analyze the video again after selecting to save it in .csv, but it says the video is already analyzed. Any suggestions on how to get the .csv?

**Comment by MMathisLab** [comment]
Yes, there is a function to do this so you don't have to re-analyze the data. Outside the GUI, in the terminal you can open you conda env, ipython, import dlc and use this:

` deeplabcut.analyze_videos_converth5_to_csv`
```
Signature: deeplabcut.analyze_videos_converth5_to_csv(videopath, videotype='.avi')
Docstring:
    By default the output poses (when running analyze_videos) are stored as MultiIndex Pandas Array, which contains the name of the network, body part name, (x, y) label position 

    in pixels, and the likelihood for each frame per body part. These arrays are stored in an efficient Hierarchical Data Format (HDF) 

    in the same directory, where the video is stored. If the flag save_as_csv is set to True, the data is also exported as comma-separated value file. However,
    if the flag was *not* set, then this function allows the conversion of all h5 files to csv files (without having to analyze the videos again)!

    This functions converts hdf (h5) files to the comma-separated values format (.csv), which in turn can be imported in many programs, such as MATLAB, R, Prism, etc.

    Parameters
    ----------

    videopath : string
        A strings containing the full paths to videos for analysis or a path to the directory where all the videos with same extension are stored.

    videotype: string, optional
        Checks for the extension of the video in case the input to the video is a directory.
Only videos with this extension are analyzed. The default is ``.avi``

    Examples
    --------

    Converts all pose-output files belonging to mp4 videos in the folder '/media/alex/experimentaldata/cheetahvideos' to csv files.
    deeplabcut.analyze_videos_converth5_to_csv('/media/alex/experimentaldata/cheetahvideos','.mp4')

```

**Comment by k8otter** [comment]
Is there a way to do this if the H5 files are saved in a different directory than the videos?

**Comment by koronfelina** [comment]
I have the same problem. Is there a fast way to convert  .h5 files to .csv for 55 videos saved in 11 folders? or do I have to insert each folder path separately? Thank you

**Comment by Ebrahimkarami** [comment]
hi
How can I convert a csv file from a file with timeserise.h5, which is the output of MintPy software, to include the latitude and longitude , the velocity  and  timeseries of each point ?

**Comment by MMathisLab** [comment]
hi @Ebrahimkarami welcome to the community, but this is beyond the scope of deeplabcut code; if you post on image forum your questions, people often kindly help :) https://forum.image.sc/tag/deeplabcut

**Comment by ellasommer** [comment]
I used this command and it says all pose files were converted in the command window, but I can't find any new csv files in my folders. Can I somehow specify where they should be saved? 
Thanks a lot for your help! 

Edit: It only took a couple seconds to run and I tried avi mp4 and pickle extensions as well as pointing to the folder where the videos are (avi format) and to the folder where my dlc output is (mp4 and pickle files) and searched the computer for csv files created on that date. I don't get any error messages, but it doesn't seem to be working. Would greatly appreciate some help with this! The tracking seems to have worked when I check the mp4 videos but I have been stuck at trying to get the coordinates for a while now...

**Comment by lukky-89** [comment]
> I used this command and it says all pose files were converted in the command window, but I can't find any new csv files in my folders. Can I somehow specify where they should be saved? Thanks a lot for your help!
> 
> Edit: It only took a couple seconds to run and I tried avi mp4 and pickle extensions as well as pointing to the folder where the videos are (avi format) and to the folder where my dlc output is (mp4 and pickle files) and searched the computer for csv files created on that date. I don't get any error messages, but it doesn't seem to be working. Would greatly appreciate some help with this! The tracking seems to have worked when I check the mp4 videos but I have been stuck at trying to get the coordinates for a while now...

Hej, its been a while, but maybe this is still helpful for some. The actual original videos, not the labeled versions need to be in the folder with the .h5 files, then the function should work perfectly fine :))
