### ISSUE TITLE
using crop=true without drawing bounding box option

### ISSUE THREAD

**Issue by AdoNunes** [DeepLabCut/DeepLabCut#572]
Hi

If in the yaml crop parameters are specified, DLC does not take them into account if crop=False, however, if crop=True, then it plots the video image and asks for cropping parameters. 

If the crop values were set in a previous step and saved in the yaml or if the defaults values are there, the extracted frames should have the size specified in the yaml file.

**Comment by MMathisLab** [comment]
this is the expected behavior of the code. Sometimes people want to crop, and other times not.

**Comment by AdoNunes** [comment]
The issue is that everytime crop is needed it has to be manually specified by creating a bounding box, instead, there should be the option of using the crop values in the yaml. 

Maybe I missed something, but if I run crop=True, a window pops up asking me to set the crop parameters.

**Comment by MMathisLab** [comment]
can you please fill out the template more specifically - many functions allow for `crop`, which fxn are you referring to.

**Comment by AdoNunes** [comment]
I was referring to the extract_frames function.
What I did, in order to get the frames cropped, was to remove the if crop conditional in this line:
[https://github.com/AlexEMG/DeepLabCut/blob/1fbb540d6ff3ca5ea4c64477191e6fc684030691/deeplabcut/generate_training_dataset/frame_extraction.py#L233](https://github.com/AlexEMG/DeepLabCut/blob/1fbb540d6ff3ca5ea4c64477191e6fc684030691/deeplabcut/generate_training_dataset/frame_extraction.py#L233)

**Comment by MMathisLab** [comment]
thanks for the clarification, we will look into adding an additional value, such that:

- crop=True (original behavior, read from config file) 
- crop=False (do not crop, default behavior)
- crop=GUI opens interactive GUI for drawing a box.

**Comment by MMathisLab** [comment]
This is now solved. https://github.com/AlexEMG/DeepLabCut/commit/1316927bbe22765fd89c5423ce5a3eb00aa0f7ec

 The behavior is as listed in https://github.com/AlexEMG/DeepLabCut/issues/572#issuecomment-580499475
