### ISSUE TITLE
How to use the source code

### ISSUE THREAD

**Issue by Felix1014** [DeepLabCut/DeepLabCut#573]
ubuntu18.04, Anaconda Env,  DeepLabCut 2.1.5.2
Browser: Chrome

Hi,  I have a question about how to use the source code. I mean, I have successfully use deeplabcut GUI to label images and test video by 'pip install deeplabcut'. But if I want to design a new algorithm or function according to your work, how can I do that?  In other words, how can I run the revised source code rather than using the unchangeable python package? Thanks.

**Comment by AlexEMG** [comment]
Just "import deeplacbut" in the folder with your edits. For more details check out this discussion: https://stackoverflow.com/questions/1112618/import-python-package-from-local-directory-into-interpreter


________________________________
