### ISSUE TITLE
Glitches in refine lables and labelling folders with refined labels

### ISSUE THREAD

**Issue by AdoNunes** [DeepLabCut/DeepLabCut#574]
There are several glitches when refining labels and re-labelling folders where there are "machine labels" used for re-labeling. Specifically:
- Some images for labeling have missing labels. These missing labels were present when visualizing the frame and manually selecting it.
- There seems to be an issue with indexing, if I go back to image 0 (for example, I move forward and go back) the labels in image 0 are displaced. 
- In order to mark missing labels, if I go to labels frames in the gui and select a folder with refined labels, the labels are wrong, as if they belonged to another frame.

I suspect that there might be an issue with the indexing, maybe in the .h5 files. In the machinelabels.csv the order of the images is not sorted, and this might call the wrong labels in the label frames function. 

 - OS: Windows 10
 - DeepLabCut Version 2.1.5.2

**Comment by AlexEMG** [comment]
We have not seen this issue (and many people have successfully used the refinement steps). Can you please submit a minimal working example?

**Comment by FancyBrush** [comment]
I am facing the same problem too. 

 OS: windows 10
 DLC : 2.0

When I use analyze_video, the programme cannot finish with 100%, but with 60%(6:33 min) ,95%(4:33 min) or lower. I searched on the user forum, and be suggested that to use CMD instead of IDE and use GPU. I tried, but analyse_video() still cannot reach 100% completion. 
   So the analyzed results might miss some frames due to the unfinished analyze_video() results. The index extracted in extract_outlier_frames() might not be consistent with the frames in the original video.

**Comment by AdoNunes** [comment]
Hi @AlexEMG 
I think I have a clue on why machine labeled (after selecting outliers) frames have wrong coordinates. 

The machinelabel.h5 or .csv have the right coordinates, however, somehow, when it gets written in the collecteddata.h5/.csv the indexing are wrong, thus when viewing the frames, the labels have the coordinates of another frame, and also if the right frame doesn't have a body part, in the wrong frame it won't show the body part. 

A minimal working example would just be to select outlier frames, save 5 frames, run refine labels, there is where problems arise, if I am on the 2nd frame [1] and go back to the first [0], I can go back even more to -n frame.
I tried to run it on my mac, and the same problem appeared. 
Is that more clear?

**Comment by AdoNunes** [comment]
below is an example with index -1 (masked the face for privacy). The labels belong to another frame, and in this case there should be left-hand labels:

![image](https://user-images.githubusercontent.com/17873774/73807728-6f3d1b00-479b-11ea-84f8-b7bfac06b2c0.png)

**Comment by FancyBrush** [comment]
Here is an example of 64% analyzed video, which generates missing frames labeled video after create_labeled_video()
![image](https://user-images.githubusercontent.com/23357454/73814155-29c13200-481d-11ea-9789-b819e8bbcfc6.png)

**Comment by MMathisLab** [comment]
I think there is some confusion - one should never load a _labeled video for selecting outliers in the manual GUI, only load original videos. The GUI would display the original video plus outputs. If one selects the “labeled.mp4” that will create issues. 

Not sure this is entirely the issue, but I suspect it is a part as I cannot replicate this issue (Ubuntu 16.04 or 18.04) 

@FancyBrush if it does not fully analyze the video is corrupt and should NOT be used until that is solved!

**Comment by FancyBrush** [comment]
@MMathisLab 
    Thank you for your advice. I have repaired the original video(the input original video can be normally played) with DivFix++, and use the fixed video as analyze_video() input. However, analyze_video() still can not fully finished(64%). How can I make sure that the corrupt issue is solved? Do you have any recommended tools for .avi corrupt reapir? 
    Same with AdoNunes's issue, **the input video is indeed the original video.** During refining the labels, as index moving forward, the labels seemed to belong to the frame that comes next a few.

**Comment by FancyBrush** [comment]
the input original video can be normally played.

**Comment by MMathisLab** [comment]
@FancyBrush yes I believe your issue is because the analyzed frames are not matching the video. Thanks for clarifying you did you used "labeled.mp4". You should try another video; if it is corrupt this will not work. I don't know how to fix corrupt videos, as often the metadata is broken.

**Comment by FancyBrush** [comment]
@MMathisLab 
Another two .avi videos still can not be fully analyzed, but with 93% and 94% completion.

**Comment by FancyBrush** [comment]
@MMathisLab 
Sorry for bothering, there is an condition I forgot, which is the input .avi is generated from a .wmv video by a videotype transformation software. If the .avi file is corrupt, is .wmv a suitable video type for DeepLabCut?

**Comment by AlexEMG** [comment]
In general both types are fine, just your specific video seems to be corrupt. (Try to load all frames with cv2)

________________________________

**Comment by MMathisLab** [comment]
Discussion now moved to #581
