### ISSUE TITLE
Problem importing tensorflow (DLL load failed)

### ISSUE THREAD

**Issue by Zoerew** [DeepLabCut/DeepLabCut#575]
Hi together, 

**Your Operating system and DeepLabCut version**
I work on Windows 10, Anaconda3, 2019.10 and use the "easy install" option for GPU (so using DeepLabCut 2.1.5).

**Describe the problem**
I am struggling for a couple of days in importing DeepLabCut. I always get the same error (see Screenshot 1). I am using the easy install procedure with "conda env create -f dlc-windowsGPU.yaml". But the same error appered in different environments if I tried to manually install DLC (I have also tried DLC 2.0.9, 2.0.8). The problem is shown on the screenshot. 

In the 2nd screenshot you see my GPU, CUDA settings.

**Screenshots**

![Capture](https://user-images.githubusercontent.com/60619918/73756340-b1e50000-4767-11ea-930d-d5718715b102.PNG)

![Capture2](https://user-images.githubusercontent.com/60619918/73756766-697a1200-4768-11ea-824e-4b705304b776.PNG)

**Additional context**
I went through all problems previously reported, however none could help me to solve the problem. Thank you for your help.

**Comment by ruslanrust1** [comment]
Hey Zoerew. I have EXACTLY the same problem. Can anyone help?

**Comment by AlexEMG** [comment]
https://stackoverflow.com/questions/43184887/dll-load-failed-error-when-importing-cv2

________________________________

**Comment by MMathisLab** [comment]
you cannot use CUDA 10.2; hence you have a mismatch in your Tensorflow version and CUDA. Please note we say you must use CUDA 10. or lower. 

> we tested up through TensorFlow 1.14 with CUDA 10

> TF 2.x is NOT supported, and CUDA > 10 is for Tensorflow 2.x

https://github.com/AlexEMG/DeepLabCut/blob/master/docs/installation.md#the-most-common-new-user-hurdle-is-installing-and-using-your-gpu

**Comment by Zoerew** [comment]
Thanks for the reply! I tried to fix it by using `pip install opencv-python` which worked, but when trying to import deeplabcut, I still get the same error (see screenshot 1). 
Next, I installed the Cuda Toolkit Version 10.0. However, when checking the NVIDIA system management interface,  it says that I am still using CUDA Version 10.2 (see screenshot 2). However, when checking the environment in Anaconda Navigator, it looks like version 10.0 is installed (see screenshot 3).

**Screenshots:**
![Capture1](https://user-images.githubusercontent.com/60619918/73837816-8d922d80-4812-11ea-9839-a21097426232.PNG)
![Capture2](https://user-images.githubusercontent.com/60619918/73837819-8ff48780-4812-11ea-82dc-5b1185dfab83.PNG)
![capture3](https://user-images.githubusercontent.com/60619918/73837829-93880e80-4812-11ea-886d-483bf897fb93.PNG)

Many thanks for your help!

**Comment by MMathisLab** [comment]
All the solutions I am aware of are in the post below; I will close for now, but let us know if a fresh install did not fix it. Note, removing CUDA 10.2 is not trivial, so please double check you fully uninstall before installing 10.0.

https://forum.image.sc/t/tensorflow-dlc-2-0-importerror-dll-load-failed-the-specified-module-could-not-be-found/22991
