### ISSUE TITLE
Import error:  Cannot import name 'ft2font'

### ISSUE THREAD

**Issue by ca-1836** [DeepLabCut/DeepLabCut#576]
Hello,  I'm trying to install the CPU version of deeplabcut (2.1.5.2) on Windows 10.  I have Python version 3.6.10 and am using the dlc-windowsCPU environment recently downloaded from your website.  However, every time I try to import deeplabcut in ipython I get an import error saying that it cannot import name 'ft2font' as stated in the title.  I'm fairly new to programming although I have managed to install an older version of deeplabcut on another computer that lacked the memory required to train the network but I can't figure out what's going on with this one.  Any help is greatly appreciated!  Thank you in advance for your time.  I'll attach a screenshot of the problem.   

![dlc error screenshot](https://user-images.githubusercontent.com/60626765/73762186-74677f00-4735-11ea-81cf-d4e9dd4b37ee.PNG)

**Comment by MMathisLab** [comment]
very odd! When you are inside the env, can you run `pip install matplotlib==3.0.3` and then try re-importing?

**Comment by ca-1836** [comment]
Yeah sure, that version was already there but I did anyways and got the same thing.  I've uninstalled and reinstalled it a couple times now and get the same issue.  

![dlc error after mpl](https://user-images.githubusercontent.com/60626765/73851873-dc7c9a80-47f3-11ea-8562-f3e310551839.png)

**Comment by MMathisLab** [comment]
Im not sure - you should check matplotlib issues then, as this isn’t a dlc code base issue: https://github.com/matplotlib/matplotlib/issues/15832

**Comment by ca-1836** [comment]
Okay, thanks for the tip.  I'll see what I can find.

**Comment by MMathisLab** [comment]
Great, sorry to not be more help, but seems a matplotlib install issue. I’ll close this, but please post back when you find a solution - my guess is a simple update to anaconda or such!
