### ISSUE TITLE
Add entry point to setup.py

### ISSUE THREAD

**Issue by FedeClaudi** [DeepLabCut/DeepLabCut#579]
**Is your feature request related to a problem? Please describe.**
Adding an entry point to `setup.py` to launch DLC from the anaconda prompt without having to launch ipython and import deeplabcut. 

**Describe the solution you'd like**
Adding something like this to `setup.py`:

```
setup(

...

entry_points={
          'console_scripts': [
              'deeplabcut = main.__init__:launch_dlc'
          ]
      },

...
)
```

would allow users to launch the GUI simply by using the `deeplabcut` command in their anaconda prompt (after having activate the environment where deeplabcut is installed). This would save users from having to launch ipython and then launch deeplabcut.

**Comment by MMathisLab** [comment]
Actually this is the case now: one just types python -m deeplabcut 

https://github.com/AlexEMG/DeepLabCut/blob/8c6a7669c1db33f002b548111d5f9d6b209dfc9a/deeplabcut/__main__.py

https://github.com/AlexEMG/DeepLabCut/blob/master/docs/PROJECT_GUI.md
