### ISSUE TITLE
Training and extracting features with multiple GPUs

### ISSUE THREAD

**Issue by YudiXie** [DeepLabCut/DeepLabCut#58]
I'm trying to run DeepLabCut on Harvard Odyssey cluster and happy to find out after correctly installing all the dependencies DeepLabCut works fine!
The problem is, you can use many GPUs on Harvard Odyssey cluster, but in terms of single GPU performance it is just normal.
Now it seems that I can only specify one GPU for training or extracting at a time.
` $ TF_CUDNN_USE_AUTOTUNE=0 CUDA_VISIBLE_DEVICES=0 python3 ../../../train.py `
` $ CUDA_VISIBLE_DEVICES=0 python3 AnalyzeVideos.py `

I'm wondering if we can use multiple GPUs for training or extracting, the speed might be dramatically improved. Is there a way to do that?

**Comment by AlexEMG** [comment]
Great to hear that it works for you on the cluster. Training is a rare occurrence (as the intended use is to train a universal decoder), so we are not keen on making this faster. 

Running the network on videos can be trivially parallelized for multiple GPUs by distributing the videos/frames etc.
