### ISSUE TITLE
DeepLabCut Training process

### ISSUE THREAD

**Issue by jernsting** [DeepLabCut/DeepLabCut#585]
Hi,
I want to understand, how DeepLabCut works under the hood.

I have read the corresponding papers and tried to understand the code, but I have one question which might be easy to answer for you:

in train.py the training loop looks like this:
` for it in range(max_iter+1):`

Is the it (count of iterations) in this case counting the batches, which are used for training or is it counting epochs of data (with epoch = all batches are passed).

As far as I understood, the weight updates take place after each batch, is this right?

Thank you in advance
Jan

**Comment by MMathisLab** [comment]
Hi @jernsting thanks for the question; in the future could you please post user questions on the forum? 

https://github.com/AlexEMG/DeepLabCut#community-support-developers--help

https://forum.image.sc/tags/deeplabcut

**Comment by AlexEMG** [comment]
This loop iterated over batches.

________________________________
