### ISSUE TITLE
import error with attempted switch in matplotlib backend

### ISSUE THREAD

**Issue by subhacom** [DeepLabCut/DeepLabCut#586]
**Describe the bug**
In an environment where matplotlib was installed with Qt5 support, importing deeplabcut throws an import error: 
`ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'qt5' is currently running`
**To Reproduce**

In an environment where matplotlib is installed with Qt5 support,  enter `import deeplabcut` in a python/jupyter prompt.

**Expected behavior**
No error message.

**Additional context**
I notice that deeplabcut code tries to set matplotlib backend in numerous places: 
- `generate_training_dataset/trainingsetmanipulation.py`
- `pose_estimation_tensorflow/util/visualize.py`
- `pose_estimation_tensorflow/vis_dataset.py`
- `utils/make_labeled_video.py` 
- `utils/visualization.py`
- `__init__.py`

Matplotlib backend setting should be the first statement in a script, and this exception occurs when that is violated. It may simplify things to remove these backend enforcements from the module and allow users to set it in their script.

**Comment by MMathisLab** [comment]
We highly suggest using our suggested anaconda envs to avoid any issues with competing package installation. Most of the users are not using scripts to run DLC, so it's not an option, and we need all OS support (which requires different backends). 

This has been discussed before in a few issues, ie. https://github.com/AlexEMG/DeepLabCut/issues/437#issuecomment-537578627 and https://github.com/AlexEMG/DeepLabCut/issues/388#issuecomment-518374113
