### ISSUE TITLE
cannot import name 'load_config' (Installation problem with folder structure)

### ISSUE THREAD

**Issue by eliezyer** [DeepLabCut/DeepLabCut#59]
Hi,

I could successfully go through the steps of training the network for my own dataset, but I'm having problems to evaluate, in _Step1_EvaluateModelonDataset.py_ in line 34

`from config import load_config`

gives me the following error

` File "Step1_EvaluateModelonDataset.py", line 34, in <module>
    from config import load_config
ImportError: cannot import name 'load_config'`

I've checked and I have the config library, but it says this functions doesn't exist. I'm running the code inside the DLC dependencies environment, in a Windows 10 machine. I've tried to upgrade config library but still not find the function. Am I missing something? Should I install another library?

Thank you,
Eliezyer

**Comment by MMathisLab** [comment]
You are likely in the wrong folder. Are you inside the Evaluate_... folder?

**Comment by eliezyer** [comment]
Yes, I am. I copy pasted the Evaluate-Tools folder in the same directory I have the Generating_a_Training_Set, where my data set is, and it doesn't work.

I also tried to evaluate from the original folder (from the DEMO) and it gives me the same error

**Comment by MMathisLab** [comment]
Please do not move the folders, as each has dependencies that rely on this structure. 

Run each script in the corresponding folder, without moving anything, and it will work. I would recommend making a new git clone just so you are sure the structure is intact. Hope that helps.

**Comment by eliezyer** [comment]
Hi @MMathisLab ,

Thank you for answer. 

If that's the case, I wonder why trying to run the original script in the original folder is not working, note that I didn't move the folders from the original, I just CP them to another folder to apply to my own dataset, so the original still intact.

I'll try a new git clone, I'll keep you updated if it works.

**Comment by MMathisLab** [comment]
I’m not sure, as others haven’t reported the issue and I cannot get this error; maybe you can provide more details of exactly what you run, and the error

**Comment by eliezyer** [comment]
Hi,

I cloned the repository again and it didn't work... the problem was fixed after I re-created the DLCdependencies environment, some library was not properly installed I guess. Thank you so much for the help.
