### ISSUE TITLE
Trained model not found when applied to new videos [broken config file]

### ISSUE THREAD

**Issue by salvatoreNRIM** [DeepLabCut/DeepLabCut#590]
I am using Windows 10 with Anaconda Env, DLC  2.1.3, Firefox.
I trained a network and happy with the tracking I was planning to use it on a new video I have saved in a separate folder. However, when I use analyze_video function I ran into the following issue: 
`FileNotFoundError: It seems the model for shuffle 1 and trainFraction 0.95 does not exist.`
This is the code I am using 
```
config = '/Video_Jan2020/config.yaml'
deeplabcut.analyze_videos(config, ['/Video_Feb2020/'], shuffle=1, trainingsetindex=0)
```
Also, I checked the folder and the model seems to be correctly created in the folder '/Video_Jan2020\dlc-models\iteration-0\Ridge_walkJan9-trainset95shuffle1'. Below the config file:

```
> # Project definitions (do not edit)
> Task: Ridge_walk
> scorer: SL
> date: Jan9
> 
> # Project path (change when moving around)
> project_path: C:\Users\Salvo\Desktop\DLC_Ridge_Jan10\Ridge_walk-SL-2020-01-09
> 
> # Annotation data set configuration (and individual video cropping parameters)
> video_sets:
>   C:\Users\Salvo\Desktop\DLC_Ridge_Jan10\Ridge_walk-SL-2020-01-09\videos\TrimTrajectory_BW.avi.avi:
>     crop: 0, 760, 0, 784
> bodyparts:
> - nose
> - tailbase
> - tailtip
> start: 0
> stop: 1
> numframes2pick: 20
> 
> # Plotting configuration
> skeleton:
> - - nose
> - - objectA
>   - tailbase
>   - tailtip
> skeleton_color: black
> pcutoff: 0.1
> dotsize: 9
> alphavalue: 0.7
> colormap: jet
> 
> # Training,Evaluation and Analysis configuration
> TrainingFraction:
> - 0.95
> iteration: 0
> resnet:
> snapshotindex: -1
> batch_size: 8
> 
> # Cropping Parameters (for analysis and outlier frame detection)
> cropping: false
> #if cropping is true for analysis, then set the values here:
> x1: 0
> x2: 640
> y1: 277
> y2: 624
> 
> # Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
> corner2move2:
> - 50
> - 50
> move2corner: true
> default_net_type: resnet_50
> default_augmenter: default
```

**Comment by MMathisLab** [comment]
Hi @salvatoreNRIM you need to set the **config.yaml file path and the video path** to be the **full path**, not relative, and it must be formatted for windows:

> I am using Windows 10 with Anaconda Env, DLC 2.1.3, Firefox.

```
config = '/Video_Jan2020/config.yaml'
deeplabcut.analyze_videos(config, ['/Video_Feb2020/'], shuffle=1, trainingsetindex=0)
```
NOTE: Windows users, you must input paths as: `r'C:\Users\computername\Videos\reachingvideo1.avi' `or

` 'C:\\Users\\computername\\Videos\\reachingvideo1.avi' `

**Comment by salvatoreNRIM** [comment]
Thanks for the fast reply. I am a windows user, but if I use the back slash as you said I get the following error 
`SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape`
Also. I used the full path as following, but I still cannot find the model
```
config = 'C:/Users/Salvo/Desktop/Ridge/DLC_videos/DLC_Ridge_Jan10/Ridge_walk-SL-2020-01-09/config.yaml'
deeplabcut.analyze_videos(config, ['C:/Users/Salvo/Desktop/Ridge/DLC_videos/DLC_Feb17'], shuffle=1, trainingsetindex=0)
```

**Comment by MMathisLab** [comment]
I promise you need to format for Windows. Can you run with correct formatting and post the full error

**Comment by MMathisLab** [comment]
Also you have several errors in you config file, so that is the syntax error... 

```
 # Plotting configuration
> skeleton:
> - - nose
> - - objectA
>   - tailbase
>   - tailtip
```

You cannot connect body parts like this, please see the docs. 

> resnet:

This is blank. It should have 50 afterwards.
