### ISSUE TITLE
Problem analyzing videos with a specific training set, restoring from checkpoint failed

### ISSUE THREAD

**Issue by Elizabethj310** [DeepLabCut/DeepLabCut#591]
Windows 10, Anaconda env & Deeplabcut 2.1.3, Chrome.

When trying to analyze videos or evaluate the network for our third training iteration an error appears. For other training iterations, previous and the fourth, it runs perfectly fine and analyzes videos.

The information within the config file is set to:
```
# Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 3
resnet: 101
snapshotindex: -1
batch_size: 8
```

Which is all correct for iteration 3.

Ex when trying to analyze videos:
```
NotFoundError                             Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

~\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320

~\AppData\Local\Continuum\anaconda3\envs\dlc-windowsGPU\lib\site-packages\tensorflow\python\client\session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408

NotFoundError: Key resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/BatchNorm/beta not found in checkpoint
         [[{{node save/RestoreV2}}]]
         [[{{node save/RestoreV2}}]]

```
![image](https://user-images.githubusercontent.com/61161524/74746906-bc090300-522b-11ea-81a0-96e659117672.png)
![image](https://user-images.githubusercontent.com/61161524/74747001-e1960c80-522b-11ea-81d3-bcefce9db4b4.png)

**Comment by MMathisLab** [comment]
Looks like your model is a resnet_50: 

> NotFoundError: Key resnet_v1_50/

Your screen shots are too small for me to see; can you copy/paste the exact call, and the relevant details are in `pose_cfg.yaml` (not config.yaml) about which model shuffle 3 actually is. 

lastly, please confirm there is indeed a folder called `iteration3` with `dlc-models`, which has meta file, snapshots, etc.

(I would also recommend upgrading to 2.1.6, it is fully backward compatible but has some important updates, just run `pip install --upgrade deeplabcut` in your conda env, or create a new one if you are concerned.)

**Comment by Elizabethj310** [comment]
Command given: 
deeplabcut.analyze_videos(config_path,[r'E:\VIDEOS ANALYZING ATM'],save_as_csv=True)
Using snapshot-500000 for model E:\R16p11 DLC Limbs\R16p11 Limbs-c_coleman-2019-11-19\dlc-models\iteration-3\R16p11 LimbsNov19-trainset95shuffle1

Iteration three is within the models folder with appropriate snapshots. After looking at the pose file within the test folder for the dlc_model iteration 3 the net type is: net_type: resnet_50. So it would make sense why it wasn't working with 101. However, I have previous csv files labeled as "DLC_resnet101_ ... 300000-results". 

So I believe what I may have done is originally trained it on 101 and then retrained it using 50? If I were to retrain it again on 101 I assume it would switch back over. Let me know if you think this would work.

Sorry hopefully these are better:
![photo 1](https://user-images.githubusercontent.com/61161524/74778038-63079200-5260-11ea-9322-466476f57cc0.PNG)
![photo 2](https://user-images.githubusercontent.com/61161524/74778040-63a02880-5260-11ea-8bb8-933c44f1812b.PNG)

**Comment by MMathisLab** [comment]
Okay that makes sense; I guess switching it back to 50 makes the model run (ie you closed the issue :)
