### ISSUE TITLE
bad_segmentation freeze the server

### ISSUE THREAD

**Issue by byronrogers73** [DeepLabCut/DeepLabCut#593]
Set up on UBUNTU server (Ubuntu, 18.04 LTS; n1-standard-4 (4 vCPUs, 15 GB memory))

Analyzing videos....in one in about every 100 videos it will kick out a video segmentation error....

Starting to analyze %  /home/OneDrive/Biomechanics/TheTortoise.mp4
Loading  /home/OneDrive/Biomechanics/TheTortoise.mp4
Duration of video [s]:  5.46 , recorded with  24.0 fps!
Overall # of frames:  131  found with (before cropping) frame dimensions:  3840 2160
Starting to extract posture
  0%|                                                   | 0/131 [00:00<?, ?it/s]terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by byronrogers73** [comment]
I dont think it is video size. 11 have failed and they have ranged in size from 4.5MB to 39.1MB

**Comment by byronrogers73** [comment]
I’ll look at Frame size

**Comment by MMathisLab** [comment]
(discussion ongoing on gitter) - will close here since I am assisting there.
