### ISSUE TITLE
filteredincludingmetadata.pickle not created 

### ISSUE THREAD

**Issue by davidSafeloc** [DeepLabCut/DeepLabCut#595]
I have DLC 2.1.3 on Mac OS. 

I execute the following command to run the filtering function and apparently a ....filteredincludingmetadata.pickle file is not created. 
```

deeplabcut.filterpredictions(config_path,['/Users/davidlopez/Documents/Babylab/Files/DeepLabCut/UAM/Musica/12months/EB05_12M-AS-2020-02-12/videos/EB05_12m_MUS_N.mp4'], videotype='.mp4',f
   ...: iltertype= 'arima',ARdegree=5,MAdegree=2)

```
Next when I try next to create a labelled video with filtered = True it tells me that:

```

_No filtered predictions found, using frame-by-frame output instead.
The video was not analyzed with this scorer: DLC_resnet50_EB05_12MFeb12shuffle1_850000
Other scorers were found, however: ['EB05_12m_MUS_NDeepCut_resnet50_EB05_12MFeb12shuffle1_850000.h5', 'EB05_12m_MUS_NDeepCut_resnet50_EB05_12MFeb12shuffle1_850000filtered.h5']
Creating output for: DeepCut_resnet50_EB05_12MFeb12shuffle1_850000  instead.

```
So at the end it is using the unfiltered data to create the labeled video. Do you have any idea why is that? I tried removing temporally the unfiltered files and then I get 

`No such file or directory: 'EB05_12m_MUS_NDeepCut_resnet50_EB05_12MFeb12shuffle1_850000filteredincludingmetadata.pickle'
`
That's why I think what I am missing is that the filtered function is creating this file.

**Comment by MMathisLab** [comment]
can you show me the list of files that are created when you run `deeplabcut.filterpredictions`

**Comment by davidSafeloc** [comment]
<img width="584" alt="Screenshot 2020-02-27 at 06 15 57" src="https://user-images.githubusercontent.com/18496488/75414391-b183f300-5928-11ea-9b89-1a7f87a2b626.png">

This is the full list

**Comment by MMathisLab** [comment]
Hi @Mirandeitor no specific filtered meta file is required. ItS likely your path is too long to be read... https://github.com/AlexEMG/DeepLabCut/issues/196

**Comment by davidSafeloc** [comment]
I moved it to the Desktop and same problem. the whole path for pickle has 137 caracteres in total (83 being the whole filename). So this did not solve the issue.

Did is the message I get just in case it helps:

<img width="1599" alt="Screenshot 2020-03-08 at 21 37 41" src="https://user-images.githubusercontent.com/18496488/76170751-2820bc00-6185-11ea-9fdf-e312d67039d4.png">

**Comment by MMathisLab** [comment]
Looks like you have analyzed the same video with a legacy version; i.e. the latest is prefaced with `DLC` whereas old versions have `DeepCut` (now DLC is so different from that original code we re-named it). So, indeed it is looked for `DLC ..` and your folder only has `DeepCut ..` 

Could you move the video to somewhere else, run `analyze_videos`, `filterperdictions` then create a video again?

**Comment by davidSafeloc** [comment]
So probably is because the server where I run the analyze_videos has an old version. I will try to run it locally as you sugest, since here I have a newer version and let you know.

**Comment by MMathisLab** [comment]
or if no GPU can run on COLAB quickly: https://github.com/AlexEMG/DeepLabCut/blob/master/examples/COLAB_YOURDATA_TrainNetwork_VideoAnalysis.ipynb

**Comment by MMathisLab** [comment]
closed due to inactivity 😊
