### ISSUE TITLE
Documentation update needed to improve description of installation

### ISSUE THREAD

**Issue by RichardChambers** [DeepLabCut/DeepLabCut#596]
I am working with a biologist who is trying to use Deep LabCut for marking video footage of fish eating as part of her research into fish mouth eating behavior and mouth biomechanics. She is not getting good results which we think has to do with insufficient training.

As I am starting from square one with TensorFlow and Deep LabCut, I thought to install the necessary software to a stand alone PC starting with Ubuntu and adding the additional bits following the installation documentation after which I would do some experiments with the software.

I am finding the install procedures to be confusing primarily because there are so many details with side branches and links to supporting materials and what appears to be multiple ways of doing the installation. And mixing Docker in with everything else isn't helping.

I would really like to have an overall description of the process the whys and whats of the procedures for the process with cleaner, separated out descriptions for Windows, MacOS, and Linux.

I would be happy to contribute to the installation documentation for Linux if I could just work through the actual process and successfully install and be able to do a first project.

What I am going to do is to start all over again from scratch and do a fresh install of Ubuntu then go through the procedures again. Perhaps after doing this a few times I will be able to complete the installation and a first project successfully.

**Comment by OptogeneticsandNeuralEngineeringCore** [comment]
I wrote up a slightly more user friendly installation procedure from a fresh install of Ubuntu here: https://optogeneticsandneuralengineeringcore.gitlab.io/ONECoreSite/projects/DeepLabCut/

Please let me know if you have any questions. Scope out other DLC projects on the site as well (updated PSEyeCamera stuff coming SOON!). 

Getting into this kind of stuff can be frustrating, but don't give up, it is so rewarding and helpful to others in the end!

**Comment by RichardChambers** [comment]
Thank you for the link to the optogenetics page on Deep LabCut installation. Those directions are a lot clearer and flow better. I'll try it out tonight and see how it goes.

One thing I get from that procedure is that Installing the GPU drivers is a separate step that is done after installing Anaconda, Deep LabCut, and before installing TensorFlow as a separate step.

However my understanding is that TensorFlow is part of Anaconda. Is the `pip install tensorflow-gpu==1.10` step an actual installation or is TensorFlow already installed and this is just to notify the python environment that it is available?

I notice that your instructions recommend Ubuntu 16 as most people in the Deep LabCut community are using that release. The latest release looks to be Ubuntu 19 and I was wondering about differences between 16, 18, and 19. Do you have any idea as to what those would be that would affect Anaconda and Deep LabCut?

**Comment by OptogeneticsandNeuralEngineeringCore** [comment]
The pip install is, as the name suggests, an installation. I don't think Anaconda installs tensorflow. What issue are you having?

Only use Ubuntu 16 for DLC. There are tons of resources online for the differences between releases of Ubuntu. Because of 'coding', different versions and releases of Ubuntu (and all software) do not work the same. Many AI implementations (!) are based on Ubuntu 16 only.

**Comment by MMathisLab** [comment]
Hi @RichardChambers, we strongly encourage beginners to simply use our conda files. Then it's a 1 step installation. The Nature Protocols paper, I think, spells this out nicely (or at least our reviewers felt it was fine ;): https://www.nature.com/articles/s41596-019-0176-0

So, could you perhaps be more specific on where we can improve this? I.e. 

https://github.com/AlexEMG/DeepLabCut/blob/master/docs/installation.md

In the latest doc updates, we clarify this quite strongly: 

https://github.com/AlexEMG/DeepLabCut/blob/master/conda-environments/README.md

Also, we don't have Docker in this repo because this is for more advanced users. Hence it's open repo and installation guide: https://github.com/DeepLabCut/Docker4DeepLabCut2.0

Note, this is not the correct order:

> One thing I get from that procedure is that Installing the GPU drivers is a separate step that is done after installing Anaconda, Deep LabCut, and before installing TensorFlow as a separate step.

And for fresh ubuntu installations, I use this:

https://github.com/DeepLabCut/Docker4DeepLabCut2.0/wiki/Installation-of-NVIDIA-driver-and-CUDA-10

And Ubuntu is the easiest to work within, hence why we suggest building your own conda file: https://github.com/AlexEMG/DeepLabCut/blob/master/conda-environments/README.md#creating-your-own-customized-conda-env if you want to use conda. 

Hope that helps.

**Comment by MMathisLab** [comment]
@OptogeneticsandNeuralEngineeringCore what would be helpful for the larger community is to not make entirely separate installation guides though, and make PR to help with the main docs :) 

To note, we also also working on specific installation guides here, sp please feel free to contribute: https://github.com/AlexEMG/DeepLabCut/wiki/Additional-notes-for-installations-(Centos,-etc.)

**Comment by MMathisLab** [comment]
@OptogeneticsandNeuralEngineeringCore please note that this is also inaccurate: 

> Only use Ubuntu 16 for DLC. There are tons of resources online for the differences between releases of Ubuntu. Because of 'coding', different versions and releases of Ubuntu (and all software) do not work the same. Many AI implementations (!) are based on Ubuntu 16 only.

We use 18.04 LTS , and many users use Centos, Mint, debian, ubuntu 19, etc. So it's not bound to a specific ubunut/linx version :)

**Comment by RichardChambers** [comment]
@MMathisLab I would like to help with the installation documentation for Ubuntu.

What I do not like about the documentation I have found thus far is there is no explanation as to the overall architecture and the various components and how functionality is partitioned among the various components. My primary impression is a series of steps that are described with little to no background that leads to an understanding of the goal of each step and how each step furthers reaching the overall goal of getting the software installed and ready to use.

I have found myself doing a lot of link clicking along with searches in order to better understand the installation process.

Another problem for me is that I do not know most of the tools involved. Anaconda was a species of snake from the Amazonian rainforest until a few weeks ago. So there is a lot of background information that I am missing which, if I already knew, would make all of this much less mysterious.

As an example in the installation.md at Step 3 there is a Please click here with a link followed by an note that says "*If you have a GPU, you should FIRST then install the NVIDIA CUDA (10 or LOWER) package and an appropriate driver for your specific GPU. .." so does this mean this is the first thing to do in Step 3 or not?

I'm not sure what a `conda` file is though I assume it is some kind of an Anaconda script that runs in an Anaconda session. However I am unsure the breadth of that functionality and how much it does and what do I have after it runs?

Then there is the use of `pip` which seems to be a python package installer which gets into the question of what done with `pip` and what is done with `conda` and what is done in a python shell.

There do seem to be decisions I must make such as the GPU driver to use as well as TensorFlow version and CUDA version yet I do not feel I have sufficient information and background knowledge to make an informed decision.

I do know that with my first install, which did not result in a usable system, I made choices about TensorFlow and GPU driver version and CUDA version which resulted in what appeared to be warnings about incompatibilities as well as warnings that CUDA was already installed and it also looked like the ipython shell crashed when I was doing the TensorFlow installation test step.


The problem with the paper in nature is in order to access it, I must pay for it though I do have access to a copy through the university and found a preprint PDF that looks to be reasonably complete.

The paper does have a nice flowchart for the workflow using the software however that made no sense until I worked in the biology lab this afternoon creating a new project, pulling in some of the video footage, extracted frames, and labeled the frames. That was as far as I got in an hour with Dr. Kane as she had other duties.

**Comment by MMathisLab** [comment]
Hi @RichardChambers The free link to the Protocol paper on www.deeplabcut.org, please see here:

Mathis et al, Nature Neuroscience 2018 or free link: rdcu.be/4Rep 
Nath*, Mathis* et al, Nature Protocols 2019 or free link: https://rdcu.be/bHpHN

Preprints: 
 
[1] arXiv (April 2018): Markerless tracking of user-defined features with deep learning (published in Nature Neuroscience)
[2] bioRxiv(Oct 2018):On the inference speed and video-compression robustness of DeepLabCut
 (presented at COSYNE 2019)

[3] bioRxiv (Nov 2018): Using DeepLabCut for 3D markerless pose estimation across species and behaviors (published in Nature Protocols)

[4] arXiv (Sept 2019): Pretraining boosts out-of-domain robustness for pose estimation

[5] arXiv (Oct 2019): Deep learning tools for the measurement of animal behavior in neuroscience (published in Current Opinion in Neurobiology)

I agree fully that starting off completely without any knowledge of what anaconda is, pip, and some command line knowledge is difficult. 

Our feelings are that we are a domain specific application, and as a deep learning tool, it's really hard to write a complete guide to using deep learning tools and building that knowledge. There are lots of amazing tools to get up and running with what is anaconda, what is pip, what is tensorflow/cuda etc. 

Here are a few resources that I think can help:

https://www.anaconda.com/why-anaconda/

https://carpentries.org/

https://developers.google.com/machine-learning/crash-course/

**Comment by RichardChambers** [comment]
@MMathisLab  Here is my understanding of the software stack and some considerations for the hardware. This is just an overview and I have not yet gotten into the actual installation yet. I need to scrap my last install and do it all over again now that I have a better understanding of the process. I also have new equipment coming in so as to build a new DeepLabCut workstation. I chose an Intel i3 9100F CPU and 16GB of motherboard RAM with an NVIDIA RTX 2070 with 8GB of RAM and an NVMe PCIe M.2 drive. The motherboard has 4 slots so I can add an additional pair of 8GB sticks later.

DeepLabCut is a machine learning application for the automated marking up of video footage to track the position of objects moving within the field of view of the camera. The software was originally created for research in animal biomechanics such as the limb movements of mice, horses, and other animals.

DeepLabCut is written in the Python 3 programming language and uses the TensorFlow machine learning library. TensorFlow assists with the machine learning functionality required for DeepLabCut to analyze the frames of video footage searching for the desired features to identify the objects being tracked.

The preferred installation for DeepLabCut is to use the Anaconda software to manage the installation of the various software components that make up the DeepLabCut application. Anaconda makes the installation and use of DeepLabCut easier.

The machine learning software that DeepLabCut uses, TensorFlow, can be used as either a CPU only package or it can use the GPU for processing data. The CPU only approach is simpler however the GPU approach can be much faster in processing data, delivering results quicker.

Anaconda packages all of the various software tools needed for an installation of DeepLabCut with one exception, the drivers and software libraries for a Graphical Processing Unit (GPU) or video card needed for using TensorFlow with a GPU. The GPU software is a separate installation step.

DeepLabCut can be used on any computer that provides the necessary environment (Python 3 and TensorFlow) since it is written in Python 3. However the most common use is with Ubuntu 64 bit Linux. It can also be used with Windows 10 and MacOS as there are versions of the underlying software, TensorFlow and Python 3, for those operating systems. However MacOS may have problems with using TensorFlow with a GPU.

We recommend that you have the following. A computer with at least an Intel i5 or comparable multi-core CPU with 16GB of RAM (more is better), a discrete NVIDIA GPU card comparable to the NVIDIA GTX 1080 or better with 8GB of RAM, and a Solid State Drive (SSD) with sufficient space for your data.

For the operating system we recommend Ubuntu 64 bit Linux version 16.x or later. A 64 bit operating system is needed for large amounts of RAM to be usable by the operating system and applications.

TensorFlow is multi-threaded which means it will use a multi-core CPU effectively. This implies that if you are using DeepLabCut with CPU, as opposed to GPU, then the choice of a multi-core CPU is preferred with the more cores on the CPU the better. See [How-to run TensorFlow on multiple core and threads](https://stackoverflow.com/questions/39415263/how-to-run-tensorflow-on-multiple-core-and-threads). Currently, AMD CPUs are a bit cheaper than Intel and the more expensive versions have more cores than the Intel line of CPUs.

While the CPU choice between Intel and AMD is not as important for using DeepLabCut with GPU, using an NVIDIA GPU rather than an AMD Radeon GPU is preferred as NVIDIA supports TensorFlow better and it is the preferred GPU by the TensorFlow community.

Each type of NVIDIA GPU has an assigned Compute Capacity score with a higher number being better because it is faster. The Compute Capacity score is derived from the type of processor used in the NVIDIA GPU which NVIDIA has improved over the years just as Intel and AMD have improved their CPUs. Older NVIDIA GPUs have a lower Compute Capacity score so will not process data as quickly.

The other consideration for the GPU is the amount of RAM that is on the GPU card. The amount of RAM is a limiting factor on the size and complexity of machine learning processing with more RAM being better.

**Comment by MMathisLab** [comment]
Thanks for the input! I’m working on some doc updates (you can check out my fork of the repo: https://github.com/MMathisLab/DeepLabCut), and will take this into consideration.
