### ISSUE TITLE
I can't find example m3m1.mp4. It can't show me an result

### ISSUE THREAD

**Issue by VISWIK** [DeepLabCut/DeepLabCut#598]
**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: [e.g. iOS, Windows 10, etc]
DeepLabCut Version [e.g. 22] (please check with import deeplabcut, deeplabcut.__version__)

**Describe the problem**

A clear and concise description of what the problem is.

**How to Reproduce the problem**

**Screenshots**
![image](https://user-images.githubusercontent.com/61525617/75412014-84553600-5964-11ea-9e70-43736058d1ca.png)

**Additional context**

**Comment by MMathisLab** [comment]
I’m not sure your issue, but it’s in the example openfield project video folder and it’s named m3v1mp4.mp4 

https://github.com/AlexEMG/DeepLabCut/tree/master/examples/openfield-Pranav-2018-10-30/videos

**Comment by VISWIK** [comment]
yes. I found that mp4 ins example folder but it didn't play. Just empty video

**Comment by MMathisLab** [comment]
Please use VLC to open it.
