### ISSUE TITLE
Openfield demo data: FileNotFoundError: Config file is not found. 

### ISSUE THREAD

**Issue by mli3333** [DeepLabCut/DeepLabCut#600]
Windows10, with an Anaconda Env, & DeepLabCut 2.x.

Hi, I am very new to DLC & python. When I was trying to run an example openfield test: DeepLabCut/examples/openfield-Pranav-2018-10-30/
I got stuck at the step to import openfield-Pranav-2018-10-30/config.yaml  (I guess). Thank you to anyone who can explain how to run this openfield demo. This is the same test I am working at this moment.

**Screenshots**
![image](https://user-images.githubusercontent.com/61539629/75546843-6a2d5d80-5a21-11ea-93dc-9c1d499ee6ac.png)

**Comment by MMathisLab** [comment]
hi @mli3333 are you sure you opened the notebook in the folder that has the project folder in it? I.e. you would have needed to git clone the repo, and then from the terminal launch jupyter notebook from the "Deeplabcut" folder. Maybe check out this demo (same data demo) which is made for COLAB, but has the paths perhaps more clearly laid out: https://github.com/AlexEMG/DeepLabCut/blob/master/examples/COLAB_DEMO_mouse_openfield.ipynb 

Depending on where you are, you can also change that cell to the exact path for your computer: 

` path_config_file = r'\yourname\DeepLabCut\examples\openfield-Pranav-2018-10-30\config.yaml' `
