### ISSUE TITLE
Update to tensorflow 2

### ISSUE THREAD

**Issue by tbenst** [DeepLabCut/DeepLabCut#601]
Support for tensorflow 1 is starting to drop-off, and eventually will stop being supported. It would be great to update to tensorflow 2!

https://www.tensorflow.org/guide/migrate

**Comment by MMathisLab** [comment]
Hi @tbenst thanks for the note. We haven’t migrated yet as some parts of TF1 (tf-slim) we rely on were dropped in 2; there are ongoing discussions with TF developers (on their GitHub) to restore this - not just for us but many people. Until that happens we won’t be supporting TF 2. 

If you’re interested, and/or want to contribute, this is the issue: https://www.tensorflow.org/guide/migrate#a_note_on_slim_contriblayers

**Comment by lauritk** [comment]
TF-Slim as separate package (v 1.1) should work with TF2.x. See https://github.com/google-research/tf-slim

**Comment by MMathisLab** [comment]
Thanks @lauritk! We are in the midst of a big update, but will check this out in the next weeks - appreciated! Or, if you get around to testing this, let me know. There is quite nice docs/tools for this now, but I haven't tried it for this repo: https://www.tensorflow.org/guide/migrate

**Comment by MMathisLab** [comment]
I started s WIP branch/issue on the dlccore repo is anyone wants to help chip away at this :) thanks! https://github.com/DeepLabCut/DeepLabCut-core/issues/6

**Comment by MMathisLab** [comment]
In case anyone wants to use TF 2.2, now it works: https://github.com/DeepLabCut/DeepLabCut-core/issues/6 ( <---you would need to install from this branch)
