### ISSUE TITLE
Select crop for each video individually (and interactively) when training or analysing

### ISSUE THREAD

**Issue by hummuscience** [DeepLabCut/DeepLabCut#604]
**Is your feature request related to a problem? Please describe.**
I have videos where the relevant area for tracking varies. Additionally, the relevant area is about half of the video while the rest is unimportant.
**Describe the solution you'd like**
While in the GUI, after choosing the videos to be analysed, give option to chose cropping area for each video. Instead of manually entering the pixels, a similar workflow to marking of features workflow, you would extract the first image of the video and click on the corners of the relevant rectangle.

**Comment by MMathisLab** [comment]
Hi @Cumol you should use dynamic cropping then, this automatically solves your issue. 

https://github.com/AlexEMG/DeepLabCut/wiki/DOCSTRINGS#analyze_videos

https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#dynamic-cropping-of-videos

**Comment by AlexEMG** [comment]
You could also easily use this function:
https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/generate_training_dataset/frame_extraction.py#L12

to extract coordinates (and then pass them to the analyze_videos). For that to work one would have to return the extracted coordinates, rather then write them to the config (i.e. here: https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/generate_training_dataset/frame_extraction.py#L55)

and then pass it to:
https://github.com/AlexEMG/DeepLabCut/blob/6398f623b2b69a5df3eaf3bc8d5f4a70960962e9/deeplabcut/pose_estimation_tensorflow/predict_videos.py#L35

I.e. after a simple edit to select_cropping_area one could do:
```
for video_i in videos:
   cropcoords=deeplabcut.select_cropping_area(config, videos=[video_i])
   deeplabcut.analyze_videos(config,[video_i],crop=cropcoords)
```

Would be great to do a PR for this.

**Comment by AlexEMG** [comment]
Dynamic cropping would of course work too, but only works with batchsize 1 right now.

**Comment by hummuscience** [comment]
Does that mean that if I run DLC over multiple videos, dynamic cropping wont work?

**Comment by MMathisLab** [comment]
No that would work!  :)

**Comment by hummuscience** [comment]
Actually, I saw that this video already implements this? Or am I mistaken?
https://twitter.com/DeepLabCut/status/1229544705492340736?s=20
Will this then be prompted for every video added?

**Comment by MMathisLab** [comment]
^ this is in the extract_frames code, but we could add to analyze videos. @jeylau

**Comment by MMathisLab** [comment]
@Cumol I made a new function called `dlc.CropVideo( )` - this compliments `dlc.DownSample` and `dlc.Shorten` where you can pass the video and you can interactively crop a video (i.e. it makes a new cropped video. Will be out in the next update. 

I did it this way, as we don't want to have GUIs in `analyze_videos`- then it makes access on servers (and COLAB) a nightmare ;). So, you can modify all your videos first, then simply run `analzye_videos` over a whole folder, etc! Hope that is helpful.

**Comment by MMathisLab** [comment]
CropVideo is in 2.1.8
