### ISSUE TITLE
AttributeError: module 'matplotlib.axis' has no attribute '_make_getset_interval'

### ISSUE THREAD

**Issue by maotinghsu** [DeepLabCut/DeepLabCut#605]
Hi,

I followed the install guide to install DLC-GPU on the linux cluster. When I imported deeplabcut the error came to me as below:
<pre>
In [1]: import deeplabcut                                                                                                                                     
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-cfa4f159dfc5> in <module>
----> 1 import deeplabcut

/apps/unit/WickensU/anaconda/3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/__init__.py in <module>
     28     else:
     29         mpl.use('Agg')
---> 30     from deeplabcut import generate_training_dataset
     31     from deeplabcut import refine_training_dataset
     32     from deeplabcut.generate_training_dataset import label_frames, dropannotationfileentriesduetodeletedimages, comparevideolistsanddatafolders, dropimagesduetolackofannotation

/apps/unit/WickensU/anaconda/3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/__init__.py in <module>
     17 else:
     18     from deeplabcut.generate_training_dataset.auxfun_drag_label import *
---> 19     from deeplabcut.generate_training_dataset.labeling_toolbox import *
     20     from deeplabcut.generate_training_dataset.multiple_individuals_labeling_toolbox import *
     21     from deeplabcut.generate_training_dataset.frame_extraction_toolbox import *

/apps/unit/WickensU/anaconda/3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/labeling_toolbox.py in <module>
     25 import argparse
     26 from deeplabcut.generate_training_dataset import auxfun_drag_label
---> 27 from deeplabcut.utils import auxiliaryfunctions
     28 from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg as FigureCanvas
     29 from matplotlib.backends.backend_wxagg import NavigationToolbar2WxAgg as NavigationToolbar

/apps/unit/WickensU/anaconda/3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/utils/__init__.py in <module>
----> 1 from deeplabcut.utils.make_labeled_video import *
      2 from deeplabcut.utils.auxiliaryfunctions import *
      3 from deeplabcut.utils.video_processor import *
      4 from deeplabcut.utils.plotting import *
      5 

/apps/unit/WickensU/anaconda/3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/utils/make_labeled_video.py in <module>
     35 import matplotlib.pyplot as plt
     36 
---> 37 from deeplabcut.utils import auxiliaryfunctions
     38 from deeplabcut.pose_estimation_tensorflow.config import load_config
     39 from skimage.util import img_as_ubyte

/apps/unit/WickensU/anaconda/3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/utils/auxiliaryfunctions.py in <module>
     15 import ruamel.yaml
     16 import matplotlib.pyplot as plt
---> 17 from mpl_toolkits.mplot3d import Axes3D
     18 import cv2
     19 

/apps/unit/WickensU/anaconda/3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/__init__.py in <module>
----> 1 from .axes3d import Axes3D

/apps/unit/WickensU/anaconda/3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axes3d.py in <module>
     32 from . import art3d
     33 from . import proj3d
---> 34 from . import axis3d
     35 
     36 

/apps/unit/WickensU/anaconda/3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axis3d.py in <module>
    455 
    456 
--> 457 class XAxis(Axis):
    458     get_view_interval, set_view_interval = maxis._make_getset_interval(
    459         "view", "xy_viewLim", "intervalx")

/apps/unit/WickensU/anaconda/3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axis3d.py in XAxis()
    456 
    457 class XAxis(Axis):
--> 458     get_view_interval, set_view_interval = maxis._make_getset_interval(
    459         "view", "xy_viewLim", "intervalx")
    460     get_data_interval, set_data_interval = maxis._make_getset_interval(

AttributeError: module 'matplotlib.axis' has no attribute '_make_getset_interval'
</pre>

Thank you!

**Comment by AlexEMG** [comment]
export DLClight=True 

>> for clusters :)

**Comment by MMathisLab** [comment]
It is likely related it it being a cluster, as "screens" are not supported. 

> DLC-GPU on the linux cluster.

You would need to first `export DLClight=True` before launching `ipython/import deeplabcut`

See more [here](https://rdcu.be/bHpHN), and here about clusters, etc: 

https://github.com/DeepLabCut/Docker4DeepLabCut2.0

**Comment by maotinghsu** [comment]
Thank you for your reply and suggestions! As you mention, I tried your way, export DLClight=True before launching ipython but still got the same error.
<pre>
In [1]: import deeplabcut                                                       
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-cfa4f159dfc5> in <module>
----> 1 import deeplabcut

/apps/unit/WickensU/anaconda/3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/__init__.py in <module>
     41     print("Project loaded in colab-mode. Apparently Colab has trouble loading statsmodels, so the smoothing & outlier frame extraction is disabled. Sorry!")
     42 else:
---> 43     from deeplabcut.refine_training_dataset import extract_outlier_frames, merge_datasets
     44     from deeplabcut.post_processing import filterpredictions, analyzeskeleton
     45 

/apps/unit/WickensU/anaconda/3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/refine_training_dataset/__init__.py in <module>
     18     from deeplabcut.refine_training_dataset.auxfun_drag import *
     19 
---> 20 from deeplabcut.refine_training_dataset.outlier_frames import *

/apps/unit/WickensU/anaconda/3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/refine_training_dataset/outlier_frames.py in <module>
     15 import pandas as pd
     16 import statsmodels.api as sm
---> 17 from deeplabcut.utils import auxiliaryfunctions, visualization
     18 from deeplabcut.utils import frameselectiontools
     19 import argparse

/apps/unit/WickensU/anaconda/3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/utils/__init__.py in <module>
----> 1 from deeplabcut.utils.make_labeled_video import *
      2 from deeplabcut.utils.auxiliaryfunctions import *
      3 from deeplabcut.utils.video_processor import *
      4 from deeplabcut.utils.plotting import *
      5 

/apps/unit/WickensU/anaconda/3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/utils/make_labeled_video.py in <module>
     35 import matplotlib.pyplot as plt
     36 
---> 37 from deeplabcut.utils import auxiliaryfunctions
     38 from deeplabcut.pose_estimation_tensorflow.config import load_config
     39 from skimage.util import img_as_ubyte

/apps/unit/WickensU/anaconda/3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/utils/auxiliaryfunctions.py in <module>
     15 import ruamel.yaml
     16 import matplotlib.pyplot as plt
---> 17 from mpl_toolkits.mplot3d import Axes3D
     18 import cv2
     19 

/apps/unit/WickensU/anaconda/3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/__init__.py in <module>
----> 1 from .axes3d import Axes3D

/apps/unit/WickensU/anaconda/3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axes3d.py in <module>
     32 from . import art3d
     33 from . import proj3d
---> 34 from . import axis3d
     35 
     36 

/apps/unit/WickensU/anaconda/3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axis3d.py in <module>
    455 
    456 
--> 457 class XAxis(Axis):
    458     get_view_interval, set_view_interval = maxis._make_getset_interval(
    459         "view", "xy_viewLim", "intervalx")

/apps/unit/WickensU/anaconda/3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axis3d.py in XAxis()
    456 
    457 class XAxis(Axis):
--> 458     get_view_interval, set_view_interval = maxis._make_getset_interval(
    459         "view", "xy_viewLim", "intervalx")
    460     get_data_interval, set_data_interval = maxis._make_getset_interval(

AttributeError: module 'matplotlib.axis' has no attribute '_make_getset_interval'
</pre>

I'll also try to use Docker as you descript. Thank you for your help anyway!

**Comment by MMathisLab** [comment]
can you tell me what happens when you:

```
 import matplotlib

matplotlib.__version__
```

**Comment by maotinghsu** [comment]
<pre>
In [1]: import matplotlib                                                       

In [2]: matplotlib.__version__                                                  
Out[2]: '3.0.3'
</pre>

**Comment by MMathisLab** [comment]
really strange, can you run:  `pip install --ignore-installed matplotlib==3.0.3`

**Comment by maotinghsu** [comment]
<pre>
Traceback (most recent call last):
  File "/apps/unit/WickensU/anaconda/3/envs/DLC-GPU/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal.cli.main'</pre>

**Comment by MMathisLab** [comment]
hmm... something is very strange for your env to not have pip installed;i.e. if you open the DLC-GPU.yaml file you will see what is installed:
```
name: DLC-GPU
dependencies:
  - python=3.7
  - pip
  - tensorflow-gpu==1.13.1
  - cudnn=7
  - wxpython
  - jupyter
  - nb_conda
  - Shapely
  - pip:
    - deeplabcut
```

I would guess your env is broken. I would remove it, and try again:

```
deactivate DLC-GPU

conda remove -n DLC-GPU --all

conda env create -f DLC-GPU.yaml 

```

**Comment by maotinghsu** [comment]
The pip error was solved after running <pre>pip install --upgrade pip</pre>
But even I run pip install --ignore-installed matplotlib==3.0.3, the error of importing deeplabcut still came to me.
<pre>
AttributeError: module 'matplotlib.axis' has no attribute '_make_getset_interval'
</pre>

**Comment by MMathisLab** [comment]
Yeah i would still start with a fresh environment. 

I would also strongly recommend if it's a linux cluster making your own env, as we suggest here. the conda files are for windows/macos, so I have not tested on a cluster.

https://github.com/AlexEMG/DeepLabCut/tree/master/conda-environments#creating-your-own-customized-conda-env-recommended-route-for-linux-ubuntu-centos-mint-etc

In the terminal type:

`conda create -n DLC python=3.7 tensorflow-gpu=1.13.1`

Then:
`source activate DLC`
```

export DLClight=True 

ipython 

import deeplabcut
```
