### ISSUE TITLE
machine-labeled.h5 file not found [incorrect formatting for extract_outlier_frames]

### ISSUE THREAD

**Issue by Jaclyneisdorfer** [DeepLabCut/DeepLabCut#607]
OS: Linux
Browser FireFox

When we run deeplabcut.extract_outlier_frames(), a machine-labeled.h5 file is not saving. So we can't run deeplabcut.refine_labels(config_path). 

We are running an atom file in the terminal with DLCdependences activated. This is what we have in our atom file...
```
import deeplabcut
import os

working_dir = "/home/spencelab/Desktop/shriners_hemisection_jte/batch_4/week_-4/cam_1/shriners_batch4_cam1-JTE-2020-03-02"
config_path = os.path.join(str(working_dir),'config.yaml')

deeplabcut.extract_outlier_frames(config_path,['/media/spencelab/shriners_hemisection/Shriners/batch_4/week_-4/cam_1/rat_168/2020-02-20_16_58_58/fr_wbgam_h264_nearlossless_safeDeepCut_resnet50_shriners_batch4_cam1Feb21shuffle1_600000_labeled'], outlieralgorithm='uncertain',extractionalgorithm='k-means', p_bound=0.75)
```

When we run this, it does not save a machine-labeled.h5 file. Can you help? Thank you!

**Comment by MMathisLab** [comment]
Okay, lots of issues here ;) 

(1) you can't refine on a **labeled** video, you must extract from the **original video** 
```
deeplabcut.extract_outlier_frames(config_path,['/media/spencelab/shriners_hemisection/Shriners/batch_4/week_-4/cam_1/rat_168/2020-02-20_16_58_58/fr_wbgam_h264_nearlossless_safeDeepCut_resnet50_shriners_batch4_cam1Feb21shuffle1_600000_labeled'], outlieralgorithm='uncertain',extractionalgorithm='k-means', p_bound=0.75)
```
guessing this video should be: `/media/spencelab/shriners_hemisection/Shriners/batch_4/week_-4/cam_1/rat_168/2020-02-20_16_58_58/fr_wbgam_h264_nearlossless_safe.mp4`

(also don't forget video type... default is avi: `videotype='avi'`)

(2) This is also incorrect/does not exist:
`
extractionalgorithm='k-means'`

It should be: 

`extractionalgorithm='kmeans'`

(3)  p_bound is only used with `outlieralgorithm= 'uncertain' `

I suggest you check the docstring, which for every function details what is possible: 

`deeplabcut.extract_outlier_frames?`

```
Signature:
deeplabcut.extract_outlier_frames(
    config,
    videos,
    videotype='avi',
    shuffle=1,
    trainingsetindex=0,
    outlieralgorithm='jump',
    comparisonbodyparts='all',
    epsilon=20,
    p_bound=0.01,
    ARdegree=3,
    MAdegree=1,
    alpha=0.01,
    extractionalgorithm='kmeans',
    automatic=False,
    cluster_resizewidth=30,
    cluster_color=False,
    opencv=True,
    savelabeled=True,
    destfolder=None,
)
Docstring:
   Extracts the outlier frames in case, the predictions are not correct for a certain video from the cropped video running from
   start to stop as defined in config.yaml.

   Another crucial parameter in config.yaml is how many frames to extract 'numframes2extract'.

   Parameter
   ----------
   config : string
       Full path of the config.yaml file as a string.

   videos : list
       A list of strings containing the full paths to videos for analysis or a path to the directory, where all the videos with same extension are st
ored.

   videotype: string, optional
       Checks for the extension of the video in case the input to the video is a directory.
Only videos with this extension are analyzed. The default is ``.avi``

   shuffle : int, optional
       The shufle index of training dataset. The extracted frames will be stored in the labeled-dataset for
       the corresponding shuffle of training dataset. Default is set to 1

 trainingsetindex: int, optional
       Integer specifying which TrainingsetFraction to use. By default the first (note that TrainingFraction is a list in config.yaml).

   outlieralgorithm: 'fitting', 'jump', 'uncertain', or 'manual'
       String specifying the algorithm used to detect the outliers. Currently, deeplabcut supports three methods + a manual GUI option. 'Fitting'
       fits a Auto Regressive Integrated Moving Average model to the data and computes the distance to the estimated data. Larger distances than
       epsilon are then potentially identified as outliers. The methods 'jump' identifies larger jumps than 'epsilon' in any body part; and 'uncertain'
       looks for frames with confidence below p_bound. The default is set to ``jump``.

   comparisonbodyparts: list of strings, optional
       This select the body parts for which the comparisons with the outliers are carried out. Either ``all``, then all body parts
       from config.yaml are used orr a list of strings that are a subset of the full list.
       E.g. ['hand','Joystick'] for the demo Reaching-Mackenzie-2018-08-30/config.yaml to select only these two body parts.

   p_bound: float between 0 and 1, optional
       For outlieralgorithm 'uncertain' this parameter defines the likelihood below, below which a body part will be flagged as a putative outlier.

   epsilon; float,optional
       Meaning depends on outlieralgoritm. The default is set to 20 pixels.
       For outlieralgorithm 'fitting': Float bound according to which frames are picked when the (average) body part estimate deviates from model fit
       For outlieralgorithm 'jump': Float bound specifying the distance by which body points jump from one frame to next (Euclidean distance)

   ARdegree: int, optional
       For outlieralgorithm 'fitting': Autoregressive degree of ARIMA model degree. (Note we use SARIMAX without exogeneous and seasonal part)
       see https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.sarimax.SARIMAX.html

   MAdegree: int
       For outlieralgorithm 'fitting': MovingAvarage degree of ARIMA model degree. (Note we use SARIMAX without exogeneous and seasonal part)
       See https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.sarimax.SARIMAX.html

   alpha: float
       Significance level for detecting outliers based on confidence interval of fitted ARIMA model. Only the distance is used however.

   extractionalgorithm : string, optional
       String specifying the algorithm to use for selecting the frames from the identified putatative outlier frames. Currently, deeplabcut
       supports either ``kmeans`` or ``uniform`` based selection (same logic as for extract_frames).
       The default is set to``uniform``, if provided it must be either ``uniform`` or ``kmeans``.

   automatic : bool, optional
       Set it to True, if you want to extract outliers without being asked for user feedback.

   cluster_resizewidth: number, default: 30
       For k-means one can change the width to which the images are downsampled (aspect ratio is fixed).

 cluster_color: bool, default: False
       If false then each downsampled image is treated as a grayscale vector (discarding color information). If true, then the color channels are considered. This increases
       the computational complexity.

   opencv: bool, default: True
       Uses openCV for loading & extractiong (otherwise moviepy (legacy))

   savelabeled: bool, default: True
       If true also saves frame with predicted labels in each folder.

   destfolder: string, optional
       Specifies the destination folder that was used for storing analysis data (default is the path of the video).

   Examples

   Windows example for extracting the frames with default settings
   >>> deeplabcut.extract_outlier_frames('C:\myproject\reaching-task\config.yaml',['C:\yourusername\rig-95\Videos\reachingvideo1.avi'])
   --------
   for extracting the frames with default settings
   >>> deeplabcut.extract_outlier_frames('/analysis/project/reaching-task/config.yaml',['/analysis/project/video/reachinvideo1.avi'])
   --------
   for extracting the frames with kmeans
   >>> deeplabcut.extract_outlier_frames('/analysis/project/reaching-task/config.yaml',['/analysis/project/video/reachinvideo1.avi'],extractionalgorithm='kmeans')
   --------
   for extracting the frames with kmeans and epsilon = 5 pixels.
   >>> deeplabcut.extract_outlier_frames('/analysis/project/reaching-task/config.yaml',['/analysis/project/video/reachinvideo1.avi'],epsilon = 5,extractionalgorithm='kmeans')
   --------
   
File:      ~/anaconda3/envs/DLC3_7/lib/python3.7/site-packages/deeplabcut/refine_training_dataset/outlier_frames.py
Type:      function
```

**Comment by Jaclyneisdorfer** [comment]
Oh my goodness! That's a lot of issues! Haha I apologise, I do not have a coding background. 

I will make adjustments and try it out. Thank you for your speedy reply! I will comment again if it works or if I'm still having issues. :)

**Comment by MMathisLab** [comment]
:) No problem, you might try just the default settings at first to be sure it's all working for you, i.e. just pass the config file then a video file. You could only extract say 5 frames with default then try the other algorithms as to not overload your labeling efforts.

**Comment by Jaclyneisdorfer** [comment]
Hmm that's interesting you said that.. when I tried the default settings with the original video (not the labeled video as I listed in my question) the error I got was "video hasn't been analyzed. Please use analyze_video first." But I did analyze the video and got plot trajectories and likelihood plots and labeled videos. So that is where my confusion started haha

**Comment by MMathisLab** [comment]
can you share the code you ran for that, and perhaps a screenshot of the folder with the video and the.h5 file? thanks!

**Comment by Jaclyneisdorfer** [comment]
I apologise, I am not at my desk again until Thursday. I will share everything as soon as I get in. I didn't not expect you to reply so speedily hehe :) I really appreciate it!

May I ask 1 more question while I have you? I have 2 days of videos. On day 1, the aperture is set to normal and the videos are tracked extremely well by DLC. On day 2, I set the aperture very high (i.e. the videos have high contrast) because I thought it would make certain features stand out more and make for easier tracking by DLC. I found that the videos from day 2 are not nearly tracked as well as the videos from day 1. I have trained DLC on the same number of videos from day 1 and day 2 so it shouldn't be a training issue. Do you think it is better to keep the lighting normal?

**Comment by MMathisLab** [comment]
If the video is saturated that could be an issue (but still a bit surprising if you train equally from both days - always the more days plus diverse animals are best). I would take videos/pictures that look best to you, i.e. "instagram quality" :) vs what is typical pre-deep learning (i.e. saturate black mouse on white background, etc)

**Comment by Jaclyneisdorfer** [comment]
Yes I was surprised too because the day 1 videos were tracked with almost perfect accuracy! And I chose the same animal diversity for day 1 and day 2 (i.e. different sexes, coat colors, etc.). It was likely my fault for saturating the videos on day 2! I will attach images for day 1 and day 2 when I attach the files for my other question about extract_outlier_images() hehe thank you SO much!! :)

**Comment by MMathisLab** [comment]
sounds great! thanks!

**Comment by Jaclyneisdorfer** [comment]
Based on the changes you suggested, the code is working perfectly now! I now have a machine-labeles-iter0.h5 file saved right in my labeled-data folder! I really want to thank you for your patience with a coding noob like myself hehe :) 

I do have one more question if you have a spare moment! Once I refine the extracted outlier frames and retrain the network, can I add more manually tracked videos at a later date and then train the network again? The reason I ask is because we take videos at different time points during recovery from spinal cord injury and I want to keep up with analyzing the videos as I take them. So let's say I manually track videos from week 1 after injury, train the network on iteration-0, extract outlier frames, refine the outlier frames, and retrain the network on iteration-1. Can I then add manually tracked videos from week 2 using the add_new_videos() function and then go through the whole cycle again (i.e. train the network on iteration-1, extract outlier frames, refine the outlier frames, and retrain the network on iteration-2)? Thank you kindly :)

**Comment by MMathisLab** [comment]
Yep! You can add more videos always, as exactly as you describe.  add videos, then extract, label, and then run "merge_datasets" which will make a new iteration, then run create_training_set, then train, etc...
