### ISSUE TITLE
DeepLabCut2.0 seems not using GPU even though it is recognizing the GPU.

### ISSUE THREAD

**Issue by Oga-Jun** [DeepLabCut/DeepLabCut#609]
I am currently trying to run DLC2.1.5.2 on Windows 10 with Anaconda Env. and chrome.
I am using desktop PC with GPU 2080Ti, and Zbook with GPU M1000M.

Importing the DLC was smooth and I confirmed the Tensorflow was recognizing the GPU. 
However, as I start training the model, the GPU seems not working. I confirmed the usage rate of GPU with Windows Task Manager and it was lower than 2%.

I thought this problem was due to the version mismatch of the NVIDIA driver, Python, TensorFlow-GPU, CUDA, and cuDNN, I tried all the possible combinations of the versions below but still unable to solve the situation.

NVIDIA driver: 442.19, 431.36
Python: 3.6.8, 3.6.10
TensorFlow-GPU: 1.10.0, 1.13.1, 1.14.0
CUDA: 10.0.130, 10.1, 10.2
cuDNN: 7.3.0, 7.6.5

Would you please tell me the way to solve this issue.
Since I am new to this field, if I am missing any information, please let me know.

I look forward to hearing from you.

Oga-Jun

**Comment by MMathisLab** [comment]
Hi Oga-Jun, 

CUDA >10 is not supported. So, it can only be 10.0 or less (i.e. we recommend CUDA 9.0): https://github.com/AlexEMG/DeepLabCut/blob/master/docs/installation.md#the-most-common-new-user-hurdle-is-installing-and-using-your-gpu

You should also check your GPU by looking at "nvidia-smi" in the terminal, vs. task manager. Hope this helps

**Comment by Oga-Jun** [comment]
Thank you for your kind reply.
I reconstruct the environment with CUDA 9.0.
Also, I use nvidia-smi command. Thank you.
