### ISSUE TITLE
I want to know standard of learning rate that shows to me on training

### ISSUE THREAD

**Issue by VISWIK** [DeepLabCut/DeepLabCut#612]
**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: [e.g. iOS, Windows 10, etc]
DeepLabCut Version [e.g. 22] (please check with import deeplabcut, deeplabcut.__version__)

**Describe the problem**

A clear and concise description of what the problem is.

**How to Reproduce the problem**

**Screenshots**
![KakaoTalk_20200305_173105973](https://user-images.githubusercontent.com/61525617/75962594-6610ac80-5f07-11ea-9a6c-11a7a2fe64e8.jpg)

**Additional context**

**Comment by MMathisLab** [comment]
The learning rate is set in the pose_config.yaml file.
