### ISSUE TITLE
Shrinking the marker points

### ISSUE THREAD

**Issue by NeuroKween** [DeepLabCut/DeepLabCut#614]
Hello, 

I've had DLC spit out videos (pupillometry with mice), and although I labeled the frames with 3 point markers in the GUI, the videos markers are much larger. Is there any way to shrink the size of the markers? It's a bit too big to really see what's going on with the pupil.

**Comment by MMathisLab** [comment]
Yes, please see the docs which describe the many functions. In the config.yaml file, you set the marker size (i.e. `dotsize`):

https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md

![image](https://user-images.githubusercontent.com/28102185/76024248-c3e9c800-5ef8-11ea-9075-0879397a92ea.png)
