### ISSUE TITLE
I want to get Image Type like EPS or SVG

### ISSUE THREAD

**Issue by Xieyuanting** [DeepLabCut/DeepLabCut#618]
**Your Operating system and DeepLabCut version**

 Windows 10, with an Anaconda3, & DeepLabCut 2.x.

**Describe the problem**

when I used my network to analyzed a new video, It creates a folder called plot-poses. But the the format of the generated image is PNG, I want to get the image type like EPS or SVG, what should I do?
I just know a little about this, so I using the Project Manger GUI to training my network.

**How to Reproduce the problem**
<img width="412" alt="plot-poses" src="https://user-images.githubusercontent.com/48749851/76398790-7c5fb200-63b8-11ea-9fce-40b064662d0d.png">

**Screenshots**

**Additional context**

**Comment by hugofluhr** [comment]
I don't think that DeepLabCut allows you to do this in a direct manner.
However, the function that is used to save these figures is `matplotlib.pyplot.savefig()` which gives the possibility of saving figures in different formats. 
For now, I think the only way of doing what you want is to go into the implementation of `deeplabcut.plot_trajectories()` (/deeplabcut/utils/plotting.py) and to edit the code to change the output format of the figures.

**Comment by MMathisLab** [comment]
(@hugofluhr thanks SO much for jumping in!!! It's truly appreciated and really brought a smile to my face!)

**Comment by Xieyuanting** [comment]
> deeplabcut.plot_trajectories

I got it! your advice is very helpful! thank you very much!
