### ISSUE TITLE
Limited labeling dots or just me? 

### ISSUE THREAD

**Issue by jiaruchung** [DeepLabCut/DeepLabCut#619]
Hi DeepLabCut,

I was wondering if I can label more than four dots for the body parts with your GUI interface. 
I've seen your paper that multiple dots can be labelled like mice' paw digits (around 10 dots) with your demo, but every time I open the GUI, only 4 body parts and 1 object are available. I hope to label more dots for my videos. 

Thanks, 

Edith

**Comment by hugofluhr** [comment]
Hi Edith,

The number of "dots" you can label depends on the config.yaml file that is in your project folder.
Every time you create a new project, you should edit this file to define which body
parts you want to label. There are also a couple of other parameters you might want to edit, check the [Nature Protocols Paper](https://www.nature.com/articles/s41596-019-0176-0) for full instructions. 
Once you have edited the body parts in the config file, there will be one "dot" per body part when you label the frames and as far as I know you can have as many as you want.
