### ISSUE TITLE
Creating Training Dataset on cluster file unable to open/create file

### ISSUE THREAD

**Issue by MarwaMikati** [DeepLabCut/DeepLabCut#620]
Mac OS Mojave, Deeplabcut 2.1.6.2, anaconda environment, 

Browser Chrome

I ran through the first steps of DeepLabCut on my local CPU up until checking labeled data.

I then moved the directory onto our university cluster. I created an environment, installed deeplabcut, etc. I am trying to create the training dataset with no luck.  Here's a screenshot. 
<img width="1808" alt="Screen Shot 2020-03-13 at 5 53 35 PM" src="https://user-images.githubusercontent.com/57199523/76664842-a7cad400-6553-11ea-9ffe-ae3a34b74599.png">
<img width="1148" alt="Screen Shot 2020-03-13 at 6 18 02 PM" src="https://user-images.githubusercontent.com/57199523/76666965-ffb70a00-6556-11ea-92fd-1c5203ba2283.png">

I know that the path is correct and I have corrected the config file path when I moved to the cluster as well as the project path. Not sure what else to do. I also suppressed GUIs.

Thanks so much for your help!

**Comment by AlexEMG** [comment]
The displayed part does not look like a full path (I.e /supercomputer/...) .

________________________________

**Comment by MarwaMikati** [comment]
That's correct. It's the path relative to the home directory we are supplied on the cluster. Do you think that's what's causing this?

**Comment by AlexEMG** [comment]
Yes, you need to include the home directory path. Dlc likes full paths.

________________________________

**Comment by MarwaMikati** [comment]
I tried correcting the path, but I keep running into the error. I am thinking it's probably a permission block on the cluster. I am going to try your suggested docker container and see if that solves it. Thank you so much for your help.
