### ISSUE TITLE
Trained labeled video is not having markers

### ISSUE THREAD

**Issue by manishinala** [DeepLabCut/DeepLabCut#621]
**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: MacOS Catalina  10.15.3, with an Anaconda Env, & DeepLabCut2.x.

Please complete the following information about your system:

OS: [MacOS Catalina 10.15.3]
DeepLabCut Version: 2.1.6.2
Browser: Safari

**Describe the problem**

I was training an octopus arm using my MacOS for initial configuration and then later trained it through Google Colab. After training with markers when I am exporting the labelled video I am not getting the markers on the octopus arm video. I tried with different video and with number of markers and number of frames. Nothing worked. 

**Additional context**

**Comment by AlexEMG** [comment]
Please note, for those videos only "confident" bodyparts are included that are above the threshold set in your config.yaml. So perhaps all predictions are not confident. You can of course check that.
Perhaps to see the range you could create these plots and post them here for troubleshooting (we would see the predictions (irrespective of confidence and the range of likelihoods):
```deeplabcut.plot_trajectories(path_config_file,[newvideo], destfolder=dfolder)```

**Comment by AlexEMG** [comment]
@technomanish did you resovle this?
