### ISSUE TITLE
Issues with DLL load

### ISSUE THREAD

**Issue by patoch01220** [DeepLabCut/DeepLabCut#622]
Hey,
For my studies, i need to use deeplabcut. I tried to install it this afternoon but i can't resolve my problem : i have the error : DLL load failed : le module spécifié est introuvable (i am french that's why the end of the error is in french).

OS: [Windows 10]

I did all the commands : conda env create -f DLC-GPU.yaml , conda activate DLC-GPU ... but when I do ipython and try to import deeplabcut, i have this error. 

I really don't know what to do next, i already tried to remove the environnement, re add it. I also tried doing it witf the CPU version but it does not work. 
 
Do you have any solutions ? 

Thanks a lot

![Capture](https://user-images.githubusercontent.com/62348996/76985349-63b74500-6940-11ea-863b-5416b9f244cd.PNG)

**Comment by MMathisLab** [comment]
hi @patoch01220 please see the forum answers here: 

https://forum.image.sc/t/tensorflow-dlc-2-0-importerror-dll-load-failed-the-specified-module-could-not-be-found/22991

https://forum.image.sc/t/problems-with-deeplabcut-installation-on-windows-10/23847

**Comment by patoch01220** [comment]
Hello @MMathisLab , thanks for the awnser.

I tried every command they say on this topics just now but i still have the same error. 
But, when i uninstall and re install numpy, i have a error message that says :
ERROR : deeplabcut 2.1.6.2 ha requirement numpy == 1.16.4 but you'll have numpy 1.16.6 which is incompatible. 
And i have the numpy version :1.18.2

I don't know if this has a link to my error with the DLL load. 

I really don't know what to do, do you have some more things i could try ? 
Thanks for the time you gave me

**Comment by patoch01220** [comment]
i also had an issue with cv2, but i did some command and not i returned to the dLL error

**Comment by MMathisLab** [comment]
sounds like your conda env is somehow corrupted; I would remove it and restart :)

and you can install a specific version with: `pip install numpy==1.16.4`

**Comment by patoch01220** [comment]
Okay, but what should i do ? unistall and re install anaconda or there is some commads to do ?

**Comment by patoch01220** [comment]
For info, i can import tensorflow, but i can't import deeplabcut. I have this error with DLL

**Comment by MMathisLab** [comment]
You don’t need to reinstall anaconda. You can simply remove the env, see here: https://kapeli.com/cheat_sheets/Conda.docset/Contents/Resources/Documents/index 

Then rebuild it.

**Comment by patoch01220** [comment]
i removed all envs abd then rebuilt it, but i still have the same issue. Should i unistall deeplabcut and reinstall it maybe or do you have any new ideas ?

**Comment by patoch01220** [comment]
when i do ipython, then import tensorflow as tf, and then do sess = tf.Session(config=tf.ConfigProto(log_device_placement=True)), this works.

**Comment by patoch01220** [comment]
I have this error and when i  check the code __init__.py, the code imports the directory .data that works, and the directory . cv2 and i went check in the directory. 
I have a directory .data, yes but i don't have the directory cv2. I only have a file named : cv2.cp37-win_amd64.pyd


![Capture](https://user-images.githubusercontent.com/62348996/77232802-7d0bfb80-6ba3-11ea-9b21-70f7961359cd.PNG)

**Comment by MMathisLab** [comment]
If you keep starting a tf session, you need to close the terminal/session before starting deeplabcut.... can you please just not run the script and just import deeplabcut ?

**Comment by patoch01220** [comment]
If i open a new anaconda prompt and try import deeplabcut, i have DLL  error.

What do you mean by not run the script and just import dlc ?

**Comment by MMathisLab** [comment]
cv2 is openCV

**Comment by patoch01220** [comment]
yeah, but what should i do to have this directory ?

**Comment by MMathisLab** [comment]
You said you deleted the env and made a new one, which would uninstall and re-install openCV. 

Seems like that is not working. Can you `import cv2`
