### ISSUE TITLE
Training more number of dataset 

### ISSUE THREAD

**Issue by manishinala** [DeepLabCut/DeepLabCut#626]
I have been training my network with 150000 iterations which took 5 hours of time which consists of only one video. If I would like to train the network with a new network but with a same object. will it automatically train itself with less amount of time or will it take again 5 hours?

**Comment by AlexEMG** [comment]
Please read the user-guide. https://www.nature.com/articles/s41596-019-0176-0

_Also check out these related posts:_
https://forum.image.sc/t/adding-additional-data-to-a-trained-iteration/21357/4

https://forum.image.sc/t/can-anybody-explain-me-why-we-use-multiple-videos-while-creating-the-project/33037

https://forum.image.sc/t/creating-a-new-training-dataset-when-there-are-previous-datasets/32554

**Short answer:**
Yes, if you start from the last snapshot (after training). Note that you want to use data from multiple videos to make robuster networks.
