### ISSUE TITLE
Can I directlty use video frame images as DLC's input? 

### ISSUE THREAD

**Issue by FancyBrush** [DeepLabCut/DeepLabCut#628]
OS: Windows 10

1) I have frame images acquired from video by matlab comupter vision toolbox. 
2) But I don't want to transfrom them into .avi or .wmv format due to drop of frames, polluting the video
3) Therefore, is it possible that use frame images as DLC's input? Can I put them into the "labeled-data"folder and then starting labeling?  

Glad for offering any advice !

**Comment by MMathisLab** [comment]
Hi, we please ask users to not post questions on GitHub, only bug reports. Please see our guidelines here: https://github.com/AlexEMG/DeepLabCut/blob/master/README.md#community-support-developers--help

Please post questions on the forum in the future. 

But yes, if yo search the GitHub, we also have functions for loading frames: 

`analyze_time_lapse_frames `

Which is described in the helper functions section: https://github.com/AlexEMG/DeepLabCut/blob/199f387b50df1f32ded6ac5d54b68f08f009661b/docs/HelperFunctions.md

**Comment by MMathisLab** [comment]
And if you want to input as images for labeling, you need to add the frames to a specific folder that is also referenced in the config.yaml file as a video - this is used to grab folders at later points in the code. Thus you need to have at minimum a fake video path with the same video name as the folder inside labeled-data.

**Comment by FancyBrush** [comment]
Sorry for my mistaking the rules here.
Deeply sorry for that.



---Original---
