### ISSUE TITLE
Bugs in extracting outline frames and refining function

### ISSUE THREAD

**Issue by chinlinCHEN** [DeepLabCut/DeepLabCut#629]
Hi,

It seems that the version of Pandas no longer support DataFrame.ix() which generate error in outlier_frames.py
Also in refinement.py, there is an issue in making the path for reading the images, error starts from line 402, self.img = os.path.join(self.project_path,self.index[self.iter]).

Thank you

**Comment by MMathisLab** [comment]
If you install from the repo, this is not an issue. Our code was updated to account for this.
