### ISSUE TITLE
Plot train and test error during training

### ISSUE THREAD

**Issue by zashwood** [DeepLabCut/DeepLabCut#631]
I was just wondering if there is a way I can view the train and test error over the course of training?  I see that within the dlc-models directory, for the particular iteration of interest, there is a log file that contains tensorboard output that I can look at.  I assume this is the training error across training iterations.  Is the test error also recorded somewhere?  Thanks!

**Comment by AlexEMG** [comment]
Test error is not recorded currently; to some extend because RMSE is more meaningful in practice and that's calculated when evaluating. Feel free to add and PR though for cross entropy + locref loss.

**Comment by zashwood** [comment]
Thanks!  If I write code to do this, I'll be sure to submit a PR.

**Comment by JanErikDoornweerd** [comment]
@zashwood Did you get around to writing this?

**Comment by zashwood** [comment]
I am afraid that I didn't get around to doing this yet.

**Comment by MMathisLab** [comment]
I think we can sun-set this, since not much community boosts/enthusiasm for it. But, if someone comes back to it, please do ref this issue in your PR 💜

**Comment by davidpagnon** [comment]
I can't do this, but I would be interested :)
