### ISSUE TITLE
"analyze video" running very slow (< real-time)

### ISSUE THREAD

**Issue by catubc** [DeepLabCut/DeepLabCut#634]
**Desktop (please complete the following information about your system):**
 - OS: Ubuntu 18.04
 - DeepLabCut Version 2.1.4:
- GPU: Titan Xp

Hi, i'm having an issue analyzing videos, seem it is taking longer than real time.  I ran analyze video on a 24 hour video acquired at 25.0FPS, and 1280 x 1024 resolution.  This step used to run faster than real-time (if my memory serves right) but it's now slow.  Any suggestions?

```

INFO:tensorflow:Restoring parameters from /home/cat/code/DeepLabCut/march_2-cat-2020-03-20/dlc-models/iteration-0/march_2Mar20-trainset95shuffle1/train/snapshot-1030000
Starting to analyze %  /media/cat/14TB/insync_cm5636/march_2/video/compressed/file_list_0_compressed.avi
Loading  /media/cat/14TB/insync_cm5636/march_2/video/compressed/file_list_0_compressed.avi
Duration of video [s]:  86388.84 , recorded with  25.0 fps!
Overall # of frames:  2159721  found with (before cropping) frame dimensions:  1280 1024
Starting to extract posture
  4%|████▋                                                                                                                 | 86388/2159721 [1:08:03<27:17:25, 21.10it/s]
```

**Comment by AlexEMG** [comment]
A double post: https://github.com/AlexEMG/DeepLabCut/issues/492#issuecomment-603314892

**Comment by AlexEMG** [comment]
My answer: 

Not sure, depending on your hardware (CPU/GPU) this might just be the speed you get.

You can always downsample, use MobileNet backbones or get a better GPU. Check out speeds here: https://www.biorxiv.org/content/10.1101/457242v1
and also here:

https://github.com/AlexEMG/DeepLabCut/wiki/What-neural-network-should-I-use%3F

**Comment by catubc** [comment]
Thanks Alex, very helpful.  The y-scale (FPS) for the 512x512 image says ~0.5-0.75FPS x batch size of 32-64 per batch would give about ~25FPS overall.  I'm now getting about ~20FPS for 1280x1024 videos on a Titan Xp, so I guess that's good relative these figures.

My main concern was whether I was doing something wrong - and that doesn't seem to be the case.  So thanks for clarifying that and for the links.

Btw: the videos contain multiple animals and I wonder whether resnet101 would be faster on these?  Do you have any recommendations on speed using resnet101?

Thanks so much

[EDIT:] Actually, my mistake - I think I misread the information and relied on the CPU speed chart (and also misinterpreted the graphs). The GPU speed for 1080Ti I see it now, says ~60FPS for larger batches of 554 video;  So for 1280x1024 videos I think 20-25FPS (what I am getting) seems also in line with your tests.

**Comment by MMathisLab** [comment]
@catubc resnet101 would be slower. Check out our wiki on model selection advice: https://github.com/AlexEMG/DeepLabCut/wiki/What-neural-network-should-I-use%3F

The color code is not super obvious but the lowest is ResNet 101, then 50 etc. (typically deeper means slower)

**Comment by AlexEMG** [comment]
> Actually, my mistake - I think I misread the information and relied on the CPU speed chart (and also misinterpreted the graphs). The GPU speed for 1080Ti I see it now, says ~60FPS for larger batches of 554 video; So for 1280x1024 videos I think 20-25FPS (what I am getting) seems also in line with your tests.

Yes! -- which is why if you want to be faster: you can downsample, get a better GPU or use MobileNets... Also there is dynamic cropping: which during inference follows the object (which depending on the size of the object reduces the pixel size and speeds up the inference)
