### ISSUE TITLE
Colab Tensorflow 2.x Update Error

### ISSUE THREAD

**Issue by nmtimme** [DeepLabCut/DeepLabCut#638]
When running DLC on Colab, I receive an error related to tensorflow.contrib running as slim. I believe Colab updated to assume tensorflow 2.x. 

For instance, using this Colab document:
https://colab.research.google.com/github/AlexEMG/DeepLabCut/blob/master/examples/COLAB_YOURDATA_TrainNetwork_VideoAnalysis.ipynb

I believe this can be fixed by adding a code box with something like the following immediately before installing deeplabcut:

#Set tensorflow_version
%tensorflow_version 1.x

Making this change resolved the error for me.

**Comment by AlexEMG** [comment]
Thanks for raising this, @MMathisLab is updating the colab notebooks! https://github.com/AlexEMG/DeepLabCut/tree/master/examples

Commit: f83ae3eda08c8116eafdd57bfa195e828a857ffe
