### ISSUE TITLE
Labeled data of verified experiments 

### ISSUE THREAD

**Issue by xiangcong** [DeepLabCut/DeepLabCut#64]
Awesome job!
Wonder is it possible that you provided  the labeled data of your experiments, e.g. rice tails, drosophila. 
so that we can easily reproduce the results ? As the detailed example only provides tens of labeled images.
thanks!

**Comment by AlexEMG** [comment]
We are working on releasing some of the data for benchmarking models. We will post a link here, once that happens. Keep in mind, as the message of our paper is that one can train feature detectors for typical lab experiments with little data, you can verify this broader statement on lots of data sets.
