### ISSUE TITLE
Running deeplabcut.create_labeled_video_3d leads me to KeyError: 'alphaValue'

### ISSUE THREAD

**Issue by paulavillafulton** [DeepLabCut/DeepLabCut#640]
Linux- Ubuntu 16.04.6 LTS with Anaconda Env and DeepLabCut version 2.1.6.2

Please complete the following information about your system:

OS: Linux
DeepLabCut Version 2.1.6.2
Browser: chrome

**Describe the problem**

When I run deeplabcut.create_labeled_video_3d(), I get **KeyError: 'alphaValue'** as seen in screenshot(1).
My alphavalue was automatically set to 0.7 in all config files (camera-1, camera-2 and 3D projects) - as seen in screenshot(2).

**Screenshots**
(1)
![image](https://user-images.githubusercontent.com/56651907/77880807-c8866f80-725d-11ea-8d27-b7c5664dc671.png)
(2)
![Screenshot from 2020-03-30 08-14-37](https://user-images.githubusercontent.com/56651907/77881191-b6f19780-725e-11ea-8ce5-573705dddbef.png)

**Additional context**
Thank you for your tips!
Best,

**Comment by MMathisLab** [comment]
my guess it's a mismatch between `alphaValue` and `alphavalue`; can you change `alphavalue` in the 3d config.yaml to `alphaValue` and run again?

(but also, it does seem that the 3d config.yaml SHOULD already be capitalized, not sure why yours it not. Here is where the config.yaml is created: https://github.com/AlexEMG/DeepLabCut/blob/2f5d32884da2e5c3e4b6ef2a2126f6bb61579060/deeplabcut/create_project/new_3d.py#L77)

**Comment by paulavillafulton** [comment]
Thank you. 
Although now I get an error when creating labeled video 3D:
![image](https://user-images.githubusercontent.com/56651907/78334439-136cf380-758c-11ea-8fe2-d55457cbe5f5.png)

![image](https://user-images.githubusercontent.com/56651907/78334523-2f709500-758c-11ea-9eb3-9a9a7ea2214b.png)

![image](https://user-images.githubusercontent.com/56651907/78334571-44e5bf00-758c-11ea-81b9-8d1a5b42dd4e.png)

![image](https://user-images.githubusercontent.com/56651907/78334604-54650800-758c-11ea-80ab-4e6f82ae957b.png)

**Comment by MMathisLab** [comment]
@paulavillafulton seems you deleted your last comment, but it seems solved

**Comment by paulavillafulton** [comment]
Thank you, it now works! Best,

**Comment by paulavillafulton** [comment]
Hi there, 

I tried running the 3D Triangulation on a snippet of the video. By this I mean that I cut the original video files to show a 2 minute section of the behavior I am interested in. 
... but am not getting this error:

could not broadcast input array from shape (1603) into shape (1550)

![image](https://user-images.githubusercontent.com/56651907/78816604-40793600-79d2-11ea-8ef8-30768c0707e7.png)

Thank you for any suggestions
