### ISSUE TITLE
Multi-animal tracking is poor: looking for improvement or advice on better approaches

### ISSUE THREAD

**Issue by catubc** [DeepLabCut/DeepLabCut#641]
**Is your feature request related to a problem? Please describe.**
I've trained DLC resnet50 and resnet152 on 425 images of 4 gerbils in a home cage.  The features tracked were nose, head and tail for the 4 animals (plus 6 wooden blocks in the cage).  The results are not very good (even slightly worse for resnet152). Here's the link to the video:

https://www.dropbox.com/s/fnxz0q8dhoctqey/2020-3-14_09_resnet50_SmallSquare_resnet152_LargeSquare.avi?dl=0

**Describe the solution you'd like**
Is there something else I can do to improve these results aside from adding several hundred more training images?  Should I not track the wooden blocks in the cage (not visualized here)? Does that make things worse for tracking the moving animals?

**Describe alternatives you've considered**
I've tried training using resnet152, but the result is somewhat worse than resnet50.

**Additional context**
In the video the smaller square is resnet50 and the larger is resnet152.  The squares are slightly shifted for visualization purpose (and we only show them for likelihood > 0.9).  The colors are 3 features per each animal (nose, head, tail) and each animal has a distinct color. As you can see there are multiple kinds of errors including: both networks continue to mix labels from other animals; the tail is a challenging feature to track; and there are periods where isolated / well visible animals aren't labeled at all (e.g. 1min22sec region where there's a pup just walking around).

Thanks so much for your help.

**Comment by MMathisLab** [comment]
hi @catubc we would really prefer questions to be on Image Forum (see guidelines here: https://github.com/AlexEMG/DeepLabCut#community-support-developers--help)

In short, DLC 2.x - 2.1.6.4 (current) is for SINGLE animal pose estimation. We have been discussing this in several issues #488  #528, Twitter, in our docs: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/UseOverviewGuide.md

> Coming soon: as of 2.2 we support multi-animal projects. The workflow is highly similar, but with some key steps that differ. Please carefully review the functions below for more details. You can search/look for maDeepLabCut for specific steps that are changed. But until the package (2.2) is released, these steps are not functional.

And have a sneak peak here on youtube ( https://www.youtube.com/watch?v=_qbEqNKApsI). We will be releasing a major update soon that allows for multi-animal pose estimation ... please stay tuned! Rest assured we are working hard to bring the latest/greatest updates for multi-animal pose estimation to our users :)

**Comment by MMathisLab** [comment]
Moreover, er suggest basically never using resnet 101, 152 unless you are doing very difficult in the wild pose estimation and you have thousands of images labeled; you will massively overtrain these networks on so little (425 frames data). Please see the wiki: https://github.com/AlexEMG/DeepLabCut/wiki/What-neural-network-should-I-use%3F

**Comment by catubc** [comment]
Thanks so much for the detailed information.

**Comment by AlexEMG** [comment]
Starting with https://github.com/DeepLabCut/DeepLabCut/tree/v2.2b5 there is (finally) very strong multi-animal support built in! Please let us know how it goes.
