### ISSUE TITLE
The problem has to do with the machinelabels-iter0.h5

### ISSUE THREAD

**Issue by zhenhuaFu** [DeepLabCut/DeepLabCut#643]
**Your Operating system and DeepLabCut version**
OS: Ubuntu 16.04
DeepLabCut Version :2.1.5.2
Browser: chrome

**Describe the problem**
I've already used the function analyze_video() and create_labeled_video().There are some outlier frames,so I want to use extract_outlier_frames() to fix it. But it raise an FileNotfounderror,machinelabels-iter0.h5 does not exist.I have no idea how to generate this file.

**Screenshots**
![image](https://user-images.githubusercontent.com/45234593/78112374-b7da2300-7430-11ea-848f-8740d4c1af6e.png)
![QQ截图20200401153622](https://user-images.githubusercontent.com/45234593/78112266-90835600-7430-11ea-8846-1a11c977d372.png)

**Additional context**
This is the first time for me to ask a question. Please point out any irregularities。

**Comment by AlexEMG** [comment]
Exactly, you need to use: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#j-optional-active-learning---network-refinement-extract-outlier-frames

Is this on Windows? It appears that your filename is too long (>250 characters), see: https://github.com/AlexEMG/DeepLabCut/issues/196

**Comment by AlexEMG** [comment]
To check, copy the whole project in a shallower folder and run again (after changing the project path)

**Comment by MMathisLab** [comment]
Hi @zhenhuaFu welcome. Also, you should update your DLC package, as I see the .ix warning, but this is now fixed. You can run `pip install deeplabcut==2.1.6.4` it's backwards compatible so your older project still works :) 

Q: did you first run an `automatic` outlier frame extraction step? 
The idea for manual is to just grab a few frames, but let the clustering find the bulk of them. i.e. first run `deeplabcut.extract_outlier_frames(configfilepath)` then you can also do the manual after that is created. 

Perhaps we should change the behavior such that if someone does not run the extract outlier `automatic` then it still creates the appropriate folder?

**Comment by zhenhuaFu** [comment]
Thank you for your help. I did not run automatic. I'd like to see that you can make such an update, which is a good idea. Thanks again. I will close this issue.
