### ISSUE TITLE
If NumPy is locked to v. 1.16, moviepy should be locked to 1.0.1 or less to avoid dependency hell.

### ISSUE THREAD

**Issue by jpellman** [DeepLabCut/DeepLabCut#644]
**Describe the bug**
Within _setup.py_ [here](https://github.com/AlexEMG/DeepLabCut/blob/master/setup.py#L30), NumPy is locked to version 1.16.4.  The latest release of moviepy (1.0.2), however, requires a version of NumPy greater than or equal to 1.17.3 (see [here](https://github.com/Zulko/moviepy/blob/master/setup.py#L75)).  This causes a dependency hell issue.  moviepy 1.0.1 does not mandate a specific version of numpy (see [here](https://github.com/Zulko/moviepy/blob/v1.0.1/setup.py#L70)).  Proposed fix would be to lock moviepy at version <= 1.0.1 in _setup.py_.

**To Reproduce**

```
(foo) [jsp2205@ax08 ~]$ pip install deeplabcut
Collecting deeplabcut
...
moviepy 1.0.2 has requirement numpy>=1.17.3; python_version != "2.7", but you'll have numpy 1.16.4 which is incompatible.
Installing collected packages: proglog, numpy, imageio-ffmpeg, moviepy, intel-openmp, tabulate, msgpack-numpy, termcolor, tensorpack, opencv-python, Shapely, imgaug, ruamel.yaml.clib, ruamel.yaml, easydict, deeplabcut, mock
```

**Comment by AlexEMG** [comment]
Fair enough, note that moviepy is anyway only used, if there a video doesn't play well with OpenCV (which is very rare).
