### ISSUE TITLE
problems to use analysis tools 

### ISSUE THREAD

**Issue by jiaruchung** [DeepLabCut/DeepLabCut#65]
**Describe the problem**
A clear and concise description of what the problem is.

Hi, 
I constantly run into the problem as below when I (8) Run the trained network on videos and analyze results. This error occurs when I am in this folder:  

(dlcdependencies) C:\Users\labadmin\DeepLabCut\Analysis-tools>python AnalyzeVideos.py

I hit:  

python3 AnalyzeVideos.py

It shows: 

FileNotFoundError: [Errno 2] No such file or directory: '..\\pose-tensorflow\\models\\phase1Sept19-trainset95shuffle1\\test\\pose_cfg.yaml'

I swear that I have this file in that directory, since I followed the instructions from 1 to 7, and no errors occurred. This last error does not seem to make sense to me. 

attached image: 

![untitled](https://user-images.githubusercontent.com/40964269/45890147-37912700-bd90-11e8-9b20-9bb6b8d96c8e.png)

**Comment by AlexEMG** [comment]
Did you change ```Task, date, shuffle, trainingset fraction``` in ```https://github.com/AlexEMG/DeepLabCut/blob/master/myconfig_analysis.py``` so it is consistent with the network during training from ```myconfig.py```? [I.e. is the "
modelfolder" correct for loading the data?]

**Comment by jiaruchung** [comment]
Hi, Alexander,

Yes, I did change those so these info on myconfig.py and
myconfig_analysis.py are pretty much the same.

Thanks,
Edith

**Comment by MMathisLab** [comment]
In your image, it looks like the file name has many ` \\` in it, which could be the issue? (I'm not a Windows user, so maybe someone else can chime in). I also suggest joining the deeplabcut.slack.com to ask other users who use Windows...
