### ISSUE TITLE
Import wx while using Colab to import dlc

### ISSUE THREAD

**Issue by bwtan** [DeepLabCut/DeepLabCut#653]
**Colab**

**Describe the problem**

A clear and concise description of what the problem is.

When I was importing deeplabcut in Colab, it reported an error 'ModuleNotFoundError: No module named 'wx''. Then I tried to install the wxPython module, however it further reported a failure of installation. Please see the screenshots below.

**Screenshots**

![DLC error](https://user-images.githubusercontent.com/27016603/79262543-7fd6d500-7e5f-11ea-9aa2-9b5c054977a5.PNG)
![DLC error2](https://user-images.githubusercontent.com/27016603/79262649-a39a1b00-7e5f-11ea-88b5-30e43fa29a91.PNG)

**Additional context**

**Comment by MMathisLab** [comment]
@KnightyOwl wx is not supported. Please follow the docs here to use COLAB correctly. https://github.com/AlexEMG/DeepLabCut/blob/master/examples/README.md

![Screen Shot 2020-04-14 at 4 27 45 PM](https://user-images.githubusercontent.com/28102185/79270926-fb8b4e80-7e6c-11ea-9ec1-78721cc22bf6.png)


This is the important part where we note that GUIs don't work on the cloud, so you have to use DLC in light mode.
```
#GUIs don't work on the cloud, so label your data locally on your computer! This will suppress the GUI support
import os
os.environ["DLClight"]="True"
```
