### ISSUE TITLE
How to analyze 'one image' with deeplabcut

### ISSUE THREAD

**Issue by Injee-Park** [DeepLabCut/DeepLabCut#658]
Anaconda Env. & DeepLabCut 2.1.6.4

OS: Windows 10, 
deepLabCut Version  : 2.1.6.4
Browser : chrome

Hello, I’m trying to analyze ‘only one image’ with deeplabcut.

I already got labeled video using demo video(mouse), and now, using this training network, I want to upload another one image(exactly, captured mouse image of demo video) to analyze and label it.

Do I need to create new project with this image? or Load existing project that I already finished labelling?

I have no idea.

Anyone can answer me?

![캡처11](https://user-images.githubusercontent.com/63034135/79682229-741e5080-825b-11ea-874c-ef34103e5581.PNG)
->I trained demo video and got this labeled video

![capture](https://user-images.githubusercontent.com/63034135/79682253-931ce280-825b-11ea-8778-58485c7220dd.PNG)
->This is an image that I want to analyze(label) using training network made above.

I think analyzing an image, not video, with deeplabcut is possible, because image is one of the frames of video. 
But, when I try to include path of image(rather than video path) and extract frames, error occurs. 

My ultimate goal is to analyze new images with training data created through video analysis.

If you know how, please reply me.

**Comment by MMathisLab** [comment]
yes, you can analyze images with:

```python
deeplabcut.analyze_time_lapse_frames(config,directory,frametype='.png',shuffle=1,
                trainingsetindex=0,gputouse=None,save_as_csv=False,rgb=True)
```

https://github.com/AlexEMG/DeepLabCut/blob/f1f3aac06ca88ad477b3c1e18e64c3cd7381e759/deeplabcut/pose_estimation_tensorflow/predict_videos.py#L618

**Comment by Injee-Park** [comment]
Thank you so much!!
