### ISSUE TITLE
Tracking only one point (this is now possible)

### ISSUE THREAD

**Issue by mschart** [DeepLabCut/DeepLabCut#66]
If you want to track only one body part (one point, joint), then there is the following error when running 

`python Step1_EvaluateModelonDataset.py`

```
Traceback (most recent call last):
  File "EvaluateNetwork.py", line 113, in <module>
    scmap, locref = predict.extract_cnn_output(outputs_np, cfg)
  File "/home/angelakilab/DeepLabCut/pose-tensorflow/nnet/predict.py", line 42, in extract_cnn_output
    print(shape(scmap))
TypeError: 'tuple' object is not callable
```
As the dimensions of that scmap array don't match. For four points it'll have that shape (14, 14, 4), no idea what the first two 14 are, but the last is the 4 points. If you have 1 point only the dims would be  (14, 14) but you'd want (14, 14,1) for the later functions. 

To fix that and make one-point-only tracking possible, I suggest expanding the dimension by one in case you just have one point, using np.expand_dims on the scmap array in the pose-tensorflow//mnet/predict.py script as follows:

```
def extract_cnn_output(outputs_np, cfg):
    scmap = outputs_np[0]
    scmap = np.squeeze(scmap)
    locref = None
    if cfg.location_refinement:
        locref = np.squeeze(outputs_np[1])
        shape = locref.shape
        locref = np.reshape(locref, (shape[0], shape[1], -1, 2))
        locref *= cfg.locref_stdev
    if len(scmap.shape)==2:
     scmap=np.expand_dims(scmap,axis=2)
    return scmap, locref
```

**Comment by AlexEMG** [comment]
I never came round to push a fix, sorry! I just fixed it... see:
https://github.com/AlexEMG/DeepLabCut/commit/a116f498464a61a63e6e51dc29e6242b70c4ee91

Will also be here:
https://github.com/AlexEMG/DeepLabCut/blob/master/deeplabcut/pose_estimation_tensorflow/nnet/predict.py

Thanks!
