### ISSUE TITLE
Extracting Outliers

### ISSUE THREAD

**Issue by RigarZ** [DeepLabCut/DeepLabCut#660]
windows version: 10.0.19041 Build 19041, with an Anaconda Env, & DeepLabCut  2.1.3.

I have analysed multiple videos but I cannot seem to extract outliers through the GUI and through python code.  It just seems to do nothing and I'm not sure if it is doing anything as nothing is produced in the folders.

![DLC](https://user-images.githubusercontent.com/57967575/80144128-da7dd880-85a5-11ea-80b8-dc4e87636213.png)

**Comment by MMathisLab** [comment]
Hi @RigarZ -- setting automatic to `false `would indeed do nothing. I suggest only inputting the config.yaml file path and testing defaults. 

Also, you don't put the "R" and the "\\" you need to pick one, see here: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/UseOverviewGuide.md#configure-the-project

Lastly, you should update your code. The current version would tell you the error, i.e. please run `pip install deeplabcut==2.1.6.5`

**Comment by RigarZ** [comment]
I've updated to 2.1.6.5 but it still seems to do nothing even after using default the code and using the GUI.

**Comment by MMathisLab** [comment]
Then please put your full call and your terminal output copy/pasted here, not as an image. Also confirm you have analyzed videos and have h5 files in the folder.

**Comment by RigarZ** [comment]
(base) C:\Users\wwwad\Documents\DLC\DeepLabCut>activate dlc-windowsGPU

(dlc-windowsGPU) C:\Users\wwwad\Documents\DLC\DeepLabCut>python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import deeplabcut
>>> import tensorflow as tf
>>> config = tf.ConfigProto()
>>> config.gpu_options.allow_growth = True
>>> sess = tf.Session(config=config)
>>> deeplabcut.launch_dlc()
>>> conﬁg_path = r'C:\Users\wwwad\Documents\DLC\LowerBackPain-AdamGillespie-2020-03-04\config.yaml'
>>> deeplabcut.extract_outlier_frames(conﬁg_path,[r'C:\Users\wwwad\Documents\DLC\Neural 2 videos\Unseen H06\GOPR2746DLC_resnet50_LowerBackPainMar4shuffle1_1030000_labeled.mp4'])
>>>

This is the point it gets to and seems to do nothing and there is a .h5 file for the analyzed video. Will it be affected by CUDA versions?

**Comment by MMathisLab** [comment]
you cannot pass it a labeled video, you need to pass the ORIGINAL video. 

ie.. not this: ,[r'C:\Users\wwwad\Documents\DLC\Neural 2 videos\Unseen H06\GOPR2746DLC_resnet50_LowerBackPainMar4shuffle1_1030000_labeled.mp4'])

also this is not necessary:

config = tf.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.Session(config=config)
