### ISSUE TITLE
Out of memory error at train network

### ISSUE THREAD

**Issue by mich11** [DeepLabCut/DeepLabCut#662]
Hi,
I'm getting an out of memory error when I try to train the network, using either my data or the example data (run testscript.py).  I'm wondering if there's something wrong with our installation. 

**Operating system and DeepLabCut version**
Centos 7.7
Anaconda Env, Python 3.6.8
DeepLabCut 2.1.6
Tensorflow 1.14
Cuda 10.0
GPU Tesla P-100 (12GB RAM)
Data: mp4, 646x482 frame size, <500MB/video

**Describe the problem**
When I try to train the classifier, I get the following error: CUDA_ERROR_OUT_OF_MEMORY, followed by a core dump. I've tried reducing the number of display iterations, and I've tried running with some of the provided example data (testscript.py). Each time, the error happens after the command line report "Loading ImageNet-pretrained resnet_50", and I've confirmed with nvidia-smi that deeplabcut does put something on the GPU before running out of memory. 

**How to Reproduce the problem**
To try with the example data, in ipython: 
import deeplabcut
run testscript.py

**Context**

NVIDIA-SMI output just before/during error
```
Mon Apr 20 16:17:29 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.129      Driver Version: 410.129      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:81:00.0 Off |                    0 |
| N/A   78C    P0    47W / 250W |   4444MiB / 12198MiB |      9%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2953      C   ...y/.conda/envs/dlc-ubuntu-GPU/bin/python  3607MiB |
|    0      9214      C   /oldhome/MATLAB/R2019a/bin/glnxa64/MATLAB    827MiB |
+-----------------------------------------------------------------------------+
```

Command-line output after running testscript.py
```
run testscript.py                                                                                                                                                                               
Imported DLC!
CREATING PROJECT
Created "/home/melody/DeepLabCut-master/examples/TEST-Alex-2020-04-20/videos"
Created "/home/melody/DeepLabCut-master/examples/TEST-Alex-2020-04-20/labeled-data"
Created "/home/melody/DeepLabCut-master/examples/TEST-Alex-2020-04-20/training-datasets"
Created "/home/melody/DeepLabCut-master/examples/TEST-Alex-2020-04-20/dlc-models"
Copying the videos
/home/melody/DeepLabCut-master/examples/TEST-Alex-2020-04-20/videos/reachingvideo1.avi
Generated "/home/melody/DeepLabCut-master/examples/TEST-Alex-2020-04-20/config.yaml"

A new project with name TEST-Alex-2020-04-20 is created at /home/melody/DeepLabCut-master/examples and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
EXTRACTING FRAMES
Config file read successfully.
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 8.53  seconds.
Extracting and downsampling... 256  frames from the video.
256it [00:01, 220.90it/s]
Kmeans clustering ... (this might take a while)

Frames were selected.
You can now label the frames using the function 'label_frames' (if you extracted enough frames for all videos).
CREATING-SOME LABELS FOR THE FRAMES
Plot labels...
Creating images with labels by Alex.
They are stored in the following folder: /home/melody/DeepLabCut-master/examples/TEST-Alex-2020-04-20/labeled-data/reachingvideo1_labeled.
If all the labels are ok, then use the function 'create_training_dataset' to create the training dataset!
CREATING TRAININGSET
The training dataset is successfully created. Use the function 'train_network' to start training. Happy training!
CHANGING training parameters to end quickly!
TRAIN
Config:
{'all_joints': [[0], [1], [2], [3]],
 'all_joints_names': ['bodypart1', 'bodypart2', 'bodypart3', 'objectA'],
 'batch_size': 1,
 'bottomheight': 400,
 'crop': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_TESTApr20/TEST_Alex80shuffle1.mat',
 'dataset_type': 'default',
 'deterministic': False,
 'display_iters': 2,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': '/home/melody/.conda/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_TESTApr20/Documentation_data-TEST_80shuffle1.pickle',
 'min_input_size': 64,
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.001, 5]],
 'net_type': 'resnet_50',
 'num_joints': 4,
 'optimizer': 'sgd',
 'pos_dist_thresh': 17,
 'project_path': '/home/melody/DeepLabCut-master/examples/TEST-Alex-2020-04-20',
 'regularize': False,
 'rightwidth': 400,
 'save_iters': 5,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': '/home/melody/DeepLabCut-master/examples/TEST-Alex-2020-04-20/dlc-models/iteration-0/TESTApr20-trainset80shuffle1/train/snapshot',
 'stride': 8.0,
 'topheight': 400,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Switching batchsize to 1, as default/tensorpack/deterministic loaders do not support batches >1. Use imgaug loader.
Starting with standard pose-dataset loader.
Initializing ResNet
WARNING:tensorflow:From /home/melody/.conda/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/nnet/pose_net.py:62: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/melody/.conda/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/nnet/pose_net.py:160: The name tf.losses.sigmoid_cross_entropy is deprecated. Please use tf.compat.v1.losses.sigmoid_cross_entropy instead.

WARNING:tensorflow:From /home/melody/.conda/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/tensorflow/python/ops/nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /home/melody/.conda/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/nnet/losses.py:38: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
Loading ImageNet-pretrained resnet_50
2020-04-20 16:17:28.765790: E tensorflow/stream_executor/cuda/cuda_driver.cc:828] failed to allocate 10.28G (11037684480 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-20 16:17:28.765865: E tensorflow/stream_executor/cuda/cuda_driver.cc:828] failed to allocate 9.25G (9933916160 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-20 16:17:28.765884: E tensorflow/stream_executor/cuda/cuda_driver.cc:828] failed to allocate 8.33G (8940524544 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-20 16:17:28.765900: E tensorflow/stream_executor/cuda/cuda_driver.cc:828] failed to allocate 7.49G (8046471680 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-20 16:17:28.765915: E tensorflow/stream_executor/cuda/cuda_driver.cc:828] failed to allocate 6.74G (7241824256 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-20 16:17:28.765934: E tensorflow/stream_executor/cuda/cuda_driver.cc:828] failed to allocate 6.07G (6517641728 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-20 16:17:28.765949: E tensorflow/stream_executor/cuda/cuda_driver.cc:828] failed to allocate 5.46G (5865877504 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-20 16:17:28.765963: E tensorflow/stream_executor/cuda/cuda_driver.cc:828] failed to allocate 4.92G (5279289856 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-20 16:17:28.765978: E tensorflow/stream_executor/cuda/cuda_driver.cc:828] failed to allocate 4.42G (4751360512 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-20 16:17:28.765993: E tensorflow/stream_executor/cuda/cuda_driver.cc:828] failed to allocate 3.98G (4276224256 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-20 16:17:28.766024: E tensorflow/stream_executor/cuda/cuda_driver.cc:828] failed to allocate 3.58G (3848601856 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-04-20 16:17:28.929887: F tensorflow/stream_executor/cuda/cuda_driver.cc:175] Check failed: err == cudaSuccess || err == cudaErrorInvalidValue Unexpected CUDA error: out of memory
Aborted (core dumped)
```

**Comment by MMathisLab** [comment]
are you sure the GPU is free? It looks like from `nvidia-smi` you have several running processes. If you try to run this code while the GPU is allocated elsewhere you will get an out of memory error. You can kill those two processes and try the test script again (be sure to delete the `TEST-ALEX-...` directory first too).

i.e. minimally, you will have to kill the MATLAB process...

**Comment by mich11** [comment]
I killed the one other process and tried again with testscript.py and got the same error. Here are 3 sequential nvidia-smi calls.  Running testscript.py starts up the process listed in the second call, and the error kills python and the process.

```
Fri Apr 24 09:19:11 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.129      Driver Version: 410.129      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:81:00.0 Off |                    0 |
| N/A   77C    P0    45W / 250W |      0MiB / 12198MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
Fri Apr 24 09:19:21 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.129      Driver Version: 410.129      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:81:00.0 Off |                    0 |
| N/A   78C    P0    46W / 250W |   3545MiB / 12198MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     17263      C   ...y/.conda/envs/dlc-ubuntu-GPU/bin/python  3535MiB |
+-----------------------------------------------------------------------------+
Fri Apr 24 09:19:31 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.129      Driver Version: 410.129      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:81:00.0 Off |                    0 |
| N/A   78C    P0    45W / 250W |      0MiB / 12198MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by MMathisLab** [comment]
I guess i should also ask, did you set `allow_growth=True` when you run `train_network`?

[ Although this should not be necessary for small images/the testsscript... ]


you can also run `watch nvidia-smi` as I would like to see that the GPU memory really maxes out...

**Comment by mich11** [comment]
I just added allow_growth=True in testscript.py, and it makes it a little farther before dying at the "starting training..." step.  I also ran watch nvidia-smi while it ran, and I see the following:

Loading ImageNet-pretrained resnet_50 - process initialized on GPU with 281MB memory allocated
Training parameter{} - increases memory allocated to 881MB on same process
Starting training - increases memory allocated to 1013MB on same process

Then I start getting the same CUDA_OUT_OF_MEMORY error, which looks like it fails to allocate 4GB memory even though there should still be ~11GB available. I then have to kill ipython to remove the process. 

Here's the full command line output when I run testscript.py with allow_growth=True:
[cmdline-output-testscriptpy-allowgrowth.txt](https://github.com/AlexEMG/DeepLabCut/files/4541083/cmdline-output-testscriptpy-allowgrowth.txt)

Running testscript.py without allow_growth=True and watching nvidia-smi, I see that 281MB gets allocated first, and then 3545MB is allocated to the same process as it throws the out of memory error and kills ipython.

Could it be that there's something that's not reported as a process that's taking up GPU memory, or that there's some GPU setting limiting the memory allocation per process?  Thanks for being patient with me -- I'm new to Tensorflow and GPUs.

**Comment by MMathisLab** [comment]
To me it's not a DLC issue, namely we know all the testscripts, etc work on the GPUs and configurations we suggest; of course I cannot test all configurations. At this point I would suggest going through some of the GPU-tensorflow workflows: 

- https://www.tensorflow.org/guide/gpu

- https://github.com/AlexEMG/DeepLabCut/blob/master/docs/installation.md#the-most-common-new-user-hurdle-is-installing-and-using-your-gpu

I'll keep an eye on this issue, and please do report back, but I can't think of anything else for you to check at this time :)

**Comment by FilippoHei** [comment]
I have very similar issues, but have been using deeplabcut-core for tensorflow 2 compatibility.

OS: Windows 10
GPU: RTX3070 8GB
CUDA Toolkit: 11.1.105 (Build: cuda_11.1.relgpu_drvr455TC455_06.29190527_0)
-  I had to change the name of cusolver64_11.dll in the bin folder to cusolver64_10.dll

Cudnn: 8.0.5.39 (CUDA 11.1 build)
Tensorflow GPU: 2.4.1

This setting has worked well so far. The quickstart of Tensorflow (see: https://www.tensorflow.org/tutorials/quickstart/advanced) passed the configuration without any problems and in fact I could already train other DLC modules with that same GPU sufficiently.

Of course I also set allow_growth=True and even added following lines after "import tensorflow as tf" in \Lib\site-packages\deeplabcutcore\pose_estimation_tensorflow\train.py:

_physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)_

I have already tried different augmenters and batch-sizes, but at most this delayed the OOM (out of memory) error by a few seconds. 

The videos I am training with are comparably big (mkv, 1920x1088, ~500MB/video), but I am already cropping them and actually, I was able to do a couple of trainings already in the past. Only when I refined and merged a few frames these problems occurred. 

I would be extremely grateful if someone could help me. Do I need to change any user variables for the train_network function? What would be the most memory friendly configuration of the config/pose_config file (i.e., batch-size, cropping, augmenter etc.)? Is this a known problem of Deeplabcut-Core, maybe because some TF1 functions are no longer supported?

I can also open a new issue if you like (maybe on DLC-Core) :)

**Comment by MMathisLab** [comment]
@FilippoHei - just to be clear, videos are not used for training. Only frames you label. so only the frame size matters. Your GPU is perhaps too small to use such big images. https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/installation.md#technical-considerations

>> physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)

also, you don't need to do this, you just add `allow_growth=True` in the command when you run `deeplabcut.train_network(config,allow_growth=True)`. In ipython, you can see all the options to set by running: `deeplabcut.train_network?` in the terminal. 

You can set `batchsize=1` if you want, but then you should not use adam optimizer, use sgd. The batchsize is set in the main config.yaml file (or you can overwrite it when you run train_network, again see the docstring with the `?`)

**Comment by FilippoHei** [comment]
Thanks for the quick response!

> @FilippoHei - just to be clear, videos are not used for training. Only frames you label. so only the frame size matters. Your GPU is perhaps too small to use such big images. 

The only thing that surprises me is that I could already train the same module with satisfaction. This is iteration -2. Could it be that the new frames suddenly overload the GPU? 8GB are not little either, are they?

> also, you don't need to do this, you just add `allow_growth=True` in the command when you run `deeplabcut.train_network(config,allow_growth=True)`. In ipython, you can see all the options to set by running: `deeplabcut.train_network?` in the terminal.

Yes, a bit unnecessary, I know ^^ That is still a relict from an earlier trouble-shooting.

> You can set `batchsize=1` if you want, but then you should not use adam optimizer, use sgd. The batchsize is set in the main config.yaml file (or you can overwrite it when you run train_network, again see the docstring with the `?`)

SGD is default, right? Is there any other possible solution than further cropping the frames or buying a new GPU (a actually just recently updated from a GTX1060 to the RTX3070)? Would e.g. using a different network make any difference (right now I am using resnet_101)?

**Comment by MMathisLab** [comment]
>> I could already train the same module with satisfaction. This is iteration -2. 

then I am worried about your extra edits, like these physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True), which could cause you to start a TF session and not close it properly, taking up memory. I would really not do this ;). The only thing you can do it edit batchsize then to be sure it's 1, and be sure you clear your GPU. Check the GPU monitor (be sure you aren't running other items on the GPU, i.e. even your mointors should be on another GPU, etc)
