### ISSUE TITLE
Automatic adding of video to config file fails when extracting outliers

### ISSUE THREAD

**Issue by pauljerem** [DeepLabCut/DeepLabCut#663]
OS: MacOS 10.14.6
DeepLabCut Version: 2.1.6.4 (used within Anaconda DLC-CPU environment)

Hi, 

When running `extract_outlier_frames` I get the message:

`AUTOMATIC ADDING OF VIDEO TO CONFIG FILE FAILED! You need to do this manually for including it in the config.yaml file!`

The extracted frames are still added to the labeled-data folder, inside a subfolder with the name of the video. Plus, `refine_labels` worked, in that it allowed me to label the frames (I didn't spot the error message until afterwards), and created `Collected_Data_Username.h5` files.

However, subsequently running `merge_datasets` appears to fail (despite not throwing any errors) as `check_labels` does not create images with labels for the new videos. Presumably, this is because they're not referenced in `config.yaml`?.

Do you have any idea what might be causing the automatic adding failure, and are there any potential fixes?

Also, if I [manually add the videos](https://github.com/AlexEMG/DeepLabCut/issues/232) at this stage (having refined the outlier labels), will I still be able to use my newly refined labels?

Thanks v. much

Paul.

**Comment by MMathisLab** [comment]
typically it's a windows permission issue, but surprising to see it on a mac! No, There is no issue with adding it manually to the config.yaml file, even putting: a fake path but the correct video name and dimensions will work fine; then you should again check labels and merge.

**Comment by pauljerem** [comment]
It does seem to be a corrupt permissions issue (one that requires a complete erase and re-install, frustratingly...).

In the meantime, I've successfully added the videos, and everything works - currently training the next iteration.

Thanks very much!
