### ISSUE TITLE
my deeplabcut.analyze_video finish faster then expected

### ISSUE THREAD

**Issue by Doohyeong-Jang** [DeepLabCut/DeepLabCut#664]
**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Window 10 x64
anaconda 3
DeepLabCut 2.1.7
Chrome

(under // conda list cudnn,)
# Name                    Version                   Build  Channel
cudnn                     7.6.5                cuda10.0_0

(under // nvidia-smi)
Sun Apr 26 18:39:20 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 445.87       Driver Version: 445.87       CUDA Version: 11.0     |

→ i have no idea why different CUDA version is shown... but i believe this is not related to the problem... 

**Describe the problem**

(first of all, since I am a very newbie of this field(programming, computer, etc....), the word I use may be ambigious....)

Every time I type 
`deeplabcut.analyze_videos(config_path,[Full path of video],shuffle=1, save_as_csv=True,videotype='.avi')`

it shows that Detected frames(?) are very small....  and it seems that  the program don't analyze the full video.

and i am sure that i followed every steps written in the paper "Using DeepLabCut for .....", and made network trained over 100,000 iterations

how can i solve this problem???

![analyzing_video](https://user-images.githubusercontent.com/62524182/80304136-2ec7c900-87ef-11ea-9184-1b920a1dad21.png)
![evaluate_network](https://user-images.githubusercontent.com/62524182/80304137-2ff8f600-87ef-11ea-82d5-99e613dfba71.png)

**Screenshots**

**Comment by MMathisLab** [comment]
(1) your video path is incorrectly formatted. For Windows you need to make sure that `[Full path of video]` is correct. If you type `deeplabcut.analyze_videos?` you will get the DOCSTRING which has examples of the correct inputs: 

```python
.....

Windows example for analyzing 1 video
    >>> deeplabcut.analyze_videos('C:\\myproject\\reaching-task\\config.yaml',['C:\\yourusername\\rig-95\\Videos\\reachingvideo1.avi'])
    --------
```
(2) if the issue persists, can you check the video; it may be corrupted at frame 49 for example...
