### ISSUE TITLE
How to continuously receive and analyze images in real time

### ISSUE THREAD

**Issue by Injee-Park** [DeepLabCut/DeepLabCut#666]
Anaconda Env. & DeepLabCut 2.1.6.4

OS: Windows 10,
deepLabCut Version : 2.1.6.4
Browser : chrome

Hello, I'm working on analyzing images (frames) from servers in real time.
I know that the function for analyzing frames is deepplabcut.analyze_time_lapse_frames(). 
Now, whenever I get an image from the server, I want to make it possible to analyze it in a DeepLabCut. I want to check in real time whether images are coming into a specific folder on the desktop within the DeepLabCut, and analyze them as soon as new frames come in. I'd like to know if this is possible in DeepLabCut and what I can do if there is a way. Or should I modify the code in the deepplabcut.analyze_time_lapse_frames() function?

**Comment by MMathisLab** [comment]
Welcome to the community. Firstly, we ask all questions be posted on the forum: https://forum.image.sc/tags/deeplabcut 

Please see community guidelines here: https://github.com/AlexEMG/DeepLabCut#community-support-developers--help

In short, if you are simply trying to scale your analysis I suggest you use bash scripts + cronjobs on the server. 

If you are trying to do closed-loop or really need real time from a camera stream, we don't recommend that function, but rather grabbing a live video stream from analyze_videos; we have a function to export trained models for this now (see 2.1.7 release statement). But, our real-time module will be fully out in the next months.

**Comment by Injee-Park** [comment]
I got it. Thank you so much! And I'll post a question on the forum, next time.
