### ISSUE TITLE
Install on Mac

### ISSUE THREAD

**Issue by tbfranklin** [DeepLabCut/DeepLabCut#668]
Python 3.7.6. Macbook.

I'm just getting started with the install and everytime I  type...
 
import deeplabcut

...I get the following error:

>>> import deeplabcut
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Tamara/Desktop/DeepLabCut/deeplabcut/__init__.py", line 30, in <module>
    from deeplabcut import generate_training_dataset
  File "/Users/Tamara/Desktop/DeepLabCut/deeplabcut/generate_training_dataset/__init__.py", line 19, in <module>
    from deeplabcut.generate_training_dataset.labeling_toolbox import *
  File "/Users/Tamara/Desktop/DeepLabCut/deeplabcut/generate_training_dataset/labeling_toolbox.py", line 17, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

(I am not a programmer)

**Comment by MMathisLab** [comment]
Not sure if you closed this as it was reolved or not, but be sure to use the [conda file DLC-CPU for MacOS](https://github.com/AlexEMG/DeepLabCut/blob/master/conda-environments/README.md), and it just seems the dependency packages are not properly installed.

**Comment by tbfranklin** [comment]
Actually, I did figure this out.  I used this help message and it worked great.


gcc: error: unable to find utility "gcc"
xcrun: error: invalid active developer path
These errors often occur after updating MacOS. The fix is to upgrade the Xcode toolkit as follows.
Open Terminal, and run xcode-select --install, followed by xcode-select --reset. Restart Terminal for changes to take effect. If the error persists, enter the command sudo xcode-select -switch /Library/Developer/CommandLineTools. Terminal will ask for your password; note that the password is not shown as you type.

Thanks!


Tamara B. Franklin, PhD

Assistant Professor

Department of Psychology and Neuroscience

Dalhousie University

1355 Oxford Street

Halifax, NS B3H 4R2


Phone: (902) 494-2923

website: https://www.dal.ca/sites/franklin-lab.html

@LabFranklin

________________________________
