### ISSUE TITLE
Issue with repeating refining labels

### ISSUE THREAD

**Issue by hosuk88** [DeepLabCut/DeepLabCut#670]
**Describe the bug**
The first frame's label is not matched when repeating the refining labels.
It seems the same issue as #353 and #374 

**To Reproduce**
1. Run deeplabcut.refine_labels(path_config_file)
2. In the GUI, load data, refine all frames, save, and click yes for repeating.
3. In the second data, refine the labels in the first frame, and go to the next frame. Go back to the first frame, and the labels were messed up and not at the manually refined positions.

**Expected behavior**
The previous data's last frame labels are not cleared, still remained, and affect to the next data's 1st frame. This issue consecutively happens - second data's last frame affects the third data's first frame, etc - during keep clicking yes for the repeating refining. Maybe the GUI issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/24601048/80803260-9c188880-8b66-11ea-82a1-11dbac465edf.png)

**Desktop (please complete the following information about your system):**
 - OS: Windows 10
 - DeepLabCut Version: 2.1.6.2
 - Browser: both in chrome & edge

**Additional context**
It did not happen when I refine data separately (close the GUI and re-run deeplabcut.refine_labels),  not repeated in the same GUI.

**Comment by MMathisLab** [comment]
Thanks for this detailed report! We will look into it ASAP

**Comment by MMathisLab** [comment]
Hi @hosuk88 - I have made a PR (#671), if you'd like to checkout that branch and double check it fixed the behavior you describe, that would be great.

**Comment by MMathisLab** [comment]
#671 should fix this, thanks!

**Comment by AlexEMG** [comment]
Thanks for your documentation, this was very useful for reproducing the error!

**Comment by hosuk88** [comment]
Thanks a lot! I'll try this ASAP.
Also, found something in the committed file. Should change this
remove_data() function as following "delete_data()"?
[image: image.png]

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
