### ISSUE TITLE
Unlabeled Demo video 

### ISSUE THREAD

**Issue by chanduborkar** [DeepLabCut/DeepLabCut#674]
Hi, I could successfully run the "Colab_DEMO_mouse_openfield.ipynb"
However, the analyzed video does not have the ear and tail labeling. 

**Screenshots**
![image](https://user-images.githubusercontent.com/53411725/80932471-1fafc080-8d85-11ea-8d18-56fd01cc705a.png)

**Comment by MMathisLab** [comment]
The plots you show in the screen cap have 4 colors, i.e. 4 body points - so everything works ;)

What is plotted in the video is up to you - i.e. you need to set the `pcutoff` in the config.yaml file. `0` would plot everything, even low confidence points. `0.9` would only plot high confidence points - which for the demo would not yet be good, as the network is undertrained as to make the DEMO fast for you. 

See [Figure 6a](https://t.co/Grkqck2tka) in our paper for more details:

![Screen Shot 2020-05-04 at 9 39 38 AM](https://user-images.githubusercontent.com/28102185/80971736-2ffa8680-8deb-11ea-957d-40a0e909e112.png)


[Box 1](https://camo.githubusercontent.com/9cbe71d962bc6eb4ceb3bdf788fed6bdb86229ac/68747470733a2f2f737461746963312e73717561726573706163652e636f6d2f7374617469632f3537663664353163396637343536366635356563663237312f742f3563343066343132346437613963306232636536353163312f313534373736303731363239382f426f78312d30312e706e673f666f726d61743d3130303077) on how to set `pcutoff`

![Box1_updated](https://user-images.githubusercontent.com/28102185/80971657-18bb9900-8deb-11ea-99e9-130e7dbea70e.png)
