### ISSUE TITLE
Problem extracting frames

### ISSUE THREAD

**Issue by AlvaroTRB** [DeepLabCut/DeepLabCut#675]
macOS Catalina 10.15.4, with Anaconda Env, & DeepLabCut 2.x.

OS: iOS
DeepLabCut Version 2.1.7
Chrome

**Describe the problem**

I´m trying to extract frames from a series of videos. When I try to extract them, the reading of the config.yalm gives me an error, saying that the video is corrupt. I can play those videos on my mac without problems. I´ve tried deactivating opencv and installing homebrew in my mac. 

**Screenshots**
![image](https://user-images.githubusercontent.com/64780017/80960606-7b239200-8e09-11ea-9c96-277a009f6749.png)

Thanks for your help!

**Comment by MMathisLab** [comment]
In the docs we note that you need to use pythonw in MacOS: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/UseOverviewGuide.md#option-3-using-the-program-terminal-start-ipython

> *please note, we provide a quick-guide of the commands at the bottom of this page. Also, if you are using MacOS, you must use pythonw vs. typing ipython, but otherwise it's the same. If you are using DeepLabCut on the cloud, you cannot use the GUIs and you need to first set DLClight=True. Please read more here, and in our Protocol paper here.

- so simply exit ipython, open pythonw, and you're all set.
