### ISSUE TITLE
DLC-CPU, Floating point exception

### ISSUE THREAD

**Issue by genio0815** [DeepLabCut/DeepLabCut#676]
Hi,

**Describe the bug**
python crashes with Floating point exception at 'import deeplabcut' in DLC-CPU version and disabled GUI (export DLClight=True). 

**To Reproduce**
1. download DLC-CPU.yaml (from github repo or hp)
2. `conda env create -f DLC-CPU.yaml`
3. `conda activate DLC-CPU`
4. `export DLClight=True`
5. `python -c 'import deeplabcut'`

DLC-CPU.yaml:
> name: DLC-CPU
dependencies:
        - python=3.7
        - pip
        - jupyter
        - nb_conda
        - tensorflow==1.13.1
        - wxpython
        - Shapely
        - pip:
                  - deeplabcut

`conda list deeplabcut`

> Name                    Version                   Build  Channel
> deeplabcut                2.1.7.1                  pypi_0    pypi

`python`
Python 3.7.7 (default, Mar 26 2020, 15:48:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
`import deeplabcut`
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Floating point exception

Operating System: CentOS Linux 7 (Core)

**Comment by MMathisLab** [comment]
The environments we provide only work for windows and MacOS - please see to docs on how to make your own environment for Linux systems: 

https://github.com/AlexEMG/DeepLabCut/blob/master/conda-environments/README.md#creating-your-own-customized-conda-env-recommended-route-for-linux-ubuntu-centos-mint-etc
