### ISSUE TITLE
Problem in creating new project

### ISSUE THREAD

**Issue by chanduborkar** [DeepLabCut/DeepLabCut#677]
Hi,
As you can see in the screenshot, I couldn't create the new project.
Please suggest.
Thanks
**Screenshots**
![image](https://user-images.githubusercontent.com/53411725/81240014-e321d600-8fcb-11ea-841a-ce8f1820e2b9.png)

**Additional context**

**Comment by MMathisLab** [comment]
you are formatting the file incorrectly, Please carefully check the docs here:https://github.com/AlexEMG/DeepLabCut/blob/master/docs/UseOverviewGuide.md#create-a-new-project

> Note, if you are a Ubuntu user the path should look like: ['/home/username/yourFolder/video1.mp4']; if you are a Windows user, it should look like: [r'C:\username\yourFolder\video1.mp4']
