### ISSUE TITLE
Consider using the image scientific community forum for feedback, instead of Slack group

### ISSUE THREAD

**Issue by imagejan** [DeepLabCut/DeepLabCut#68]
I'd like to suggest that you consider pointing to the [image.sc forum](https://forum.image.sc/) in your README, and using this forum as a support channel (instead of, or in addition to, your Slack group).

The forum aims to be a central resource to discuss scientific image analysis, and it is the official discussion channel of the Fiji and ImageJ projects, among others. As I expect most users of DeepLabCut will use Fiji to create training data (i.e. labels), I would expect users to appreciate if they can ask questions about both Fiji and DeepLabCut on a central resource.

From the support point of view, you can subscribe to the `deeplabcut` tag to get notified about questions concerning DeepLabCut. The forum moderators try their best to tag new posts appropriately, which works fine for all partner projects so far.

Let me know what you think, and thanks for this awesome project!

**Comment by MMathisLab** [comment]
Sure! I think it’s great that there are so many users at this point, and making it easier to use is important. To note, however, we are releasing a full package that no longer uses imageJ for labeling - it’s a fully self contained package for easily using DeepLabCut. The plan is a release very soon. Thanks for your support of this project.
