### ISSUE TITLE
Issue deleting labels during refinement step

### ISSUE THREAD

**Issue by brandon-hastings** [DeepLabCut/DeepLabCut#681]
**Describe the bug**
After confirming to delete a label in the refinement toolbox the label is not deleted.

**Steps to reproduce the behavior:**
1. Run deeplabcut.refine_labels(path_config_file)
2. Delete label and click yes to confirm deletion
3. See error message

**Expected behavior**
Delete label and click yes to confirm deletion, after which the label is deleted.

**Screenshots**
The output after attempting to delete a label:

```
Traceback (most recent call last):
  File "/Users/brandonhastings/opt/miniconda3/envs/deeplabcut/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 215, in process
    func(*args, **kwargs)
  File "/Users/brandonhastings/opt/miniconda3/envs/deeplabcut/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/auxfun_drag.py", line 75, in on_press
    self.remove_data()
AttributeError: 'DraggablePoint' object has no attribute 'remove_data'
```

**Desktop (please complete the following information about your system):**
 - OS: iOS 10.15.3
 - DeepLabCut Version: 2.1.7.1
 - Browser: safari

**Additional context**
This error only occurred when deleting points during refinement, but I had no problem deleting points during the initial labelling process.

**Comment by MMathisLab** [comment]
Hey @bhastings98 thanks - could you confirm it does not work if you hit the "delete" or "backspace" key (or is this with the right button click?)

I don't get this behavior on my Mac (i.e. no warning in the terminal):

```
>>> deeplabcut.__version__
'2.1.7.1'
```

![Screen Shot 2020-05-09 at 2 21 20 PM](https://user-images.githubusercontent.com/28102185/81481784-76dbe800-9200-11ea-9fe4-39686c606d67.png)
![Screen Shot 2020-05-09 at 2 21 29 PM](https://user-images.githubusercontent.com/28102185/81481785-780d1500-9200-11ea-90ba-5c3e89042513.png)

**Comment by MMathisLab** [comment]
actually, I was working on my branch that had 1 missing push to the main repo which would have fixed this  :neutral_face: - should be fixed now. https://github.com/AlexEMG/DeepLabCut/commit/98699c73f395df327d5d2a346ce17690f78cf115

Here is how to work from the latest code on github (before we make a new release): https://github.com/AlexEMG/DeepLabCut/wiki/How-to-use-the-latest-GitHub-code
