### ISSUE TITLE
Moving project from windows to Linux?

### ISSUE THREAD

**Issue by tbenst** [DeepLabCut/DeepLabCut#686]
**Is your feature request related to a problem? Please describe.**
I have a bunch of frames that were labeled on Windows. I initially trained a network on this computer. Now, I want to switch to a Linux box with a better GPU. I copied the project folder, and updated the paths in config.yaml. Some features are working out of the box, like analyze and extract outliers. Others are not, like Check labeled frames and Create training dataset and Train. 

It seems the main culprit is the .h5 files in labele-data that use windows paths. I think all I need to do is write a script to convert the path in each of these h5 files? Or is there something else I need to do? Thanks!

**Describe the solution you'd like**
Ideally, relative paths would always be stored using the Unix standard, and converted as appropriate using the python os or pathlib standard libraries. This way the project directory could be moved across platforms.

**Describe alternatives you've considered**

Alternatively, DLC could have a tool for converting / importing between OS.

**Comment by AlexEMG** [comment]
There is indeed a function for this:

https://github.com/AlexEMG/DeepLabCut/blob/01f97b53e9681c226b17db6aa8e399cebe61a1f6/deeplabcut/utils/conversioncode.py#L17

Let me know how it goes. Just to be very save, I recommend backing up the labeling data. I use this often.

Please let us know if it does the trick!

________________________________

**Comment by tbenst** [comment]
🙏 that’s amazing! Glad I asked. Thank you!
