### ISSUE TITLE
running MakingLabeledVideo.py  frames created, video not (ffmpeg not found)

### ISSUE THREAD

**Issue by leiyaohui** [DeepLabCut/DeepLabCut#69]
Hi,
Great software and am enjoying using it.
However，I have a question when  running MakingLabeledVideo.py:

Starting G:\DeepLabCut-master ['reachingvideo1.avi']
Loading reachingvideo1.avi and data.
Duration of video [s]: 8.53, recorded with 30 FPS!
Overall of frames: 256 with cropped frame dimensions: [832 747]
Generating frames
100%| 256/256 [01:44<00:00 2.46it/s]
Generating video
The video was not analyzed with this scorer: DeepCut_resnet50_reachingJan30shuffle1_100000
No other scorers were found, please run AnalysisVideos.py first.

I've already run AnalysisVideos.py. What's the matter?

**Comment by MMathisLab** [comment]
Please check that ffmeg is correctly installed, and run pip install ffmeg again

**Comment by AlexEMG** [comment]
Yes, the frames seem to have been created, thus ffmpeg is not found. Perhaps also consider using the latest version: https://github.com/AlexEMG/DeepLabCut/blob/master/Analysis-tools/MakingLabeledVideo.py

Then the error message would be more to the point and state:
print("Ffmpeg not correctly installed, see https://github.com/AlexEMG/DeepLabCut/issues/45")

**Comment by leiyaohui** [comment]
Hello! I am looking at this project recently, and I have encountered several problems. See you recently updated AnalyzeVideosAndExtractScoreMaps.py

I also ran the script successfully. But how do we generate scoremaps diagrams? Do you want to run MakingLabeledVideo.py directly?

**Comment by leiyaohui** [comment]
Where else is the generated pickle file used?
