### ISSUE TITLE
GetPoseF_GTF in predict_videos reads in more frames than .mpg has

### ISSUE THREAD

**Issue by KidElectric** [DeepLabCut/DeepLabCut#691]
**Describe the bug**
For many .mpg videos, entire video will be processed and then cap.read() somehow returns True even when counter  > nframes (i.e. it somehow reads in frames beyond nframes).. This then throws errors later when trying to put these frames into PredictedData, giving error "could not broadcast input array from shape (6,30) into shape (5,30)" [or whatever the case may be]. I don't know if this is an issue with openCV, DLC, or a common way that .mpg files themselves can be corrupted. but it's pretty frustrating (because it happens allll the way at the end of a long video analysis session ;-). Really hard to predict which videos it will happen to. I was able to get around it by adding an if statement checking that counter  < nframes instead of relying on ret from cap.read().  I.e.
```
            if counter < nframes:
                ret, frame = cap.read()
            else:
                ret = False
```
Not sure if this generalizes because it also appears GetPoseF_GTF dynamically re-assigns nframes at the end ( nframes = counter)... even though PredictedData is already initialized to the original nframes? Not sure what's going on there. 

**To Reproduce**
I can attempt to send an example video and model this happens on if needed (they are large). Hoping that the above description is precise enough.

**Expected behavior**
Video analysis completing.

**Screenshots**
N/A

**Desktop (please complete the following information about your system):**
 - OS: Windows 10 and also Linux Ubuntu  (DLC Docker)
 - DeepLabCut Version 2.1.7
 - Browser: N/A

**Additional context**

**Comment by MMathisLab** [comment]
> This then throws errors later when trying to put these frames into PredictedData, giving error "could not broadcast input array from shape (6,30) into shape (5,30)" [or whatever the case may be].

Could you please provide the full traceback?

Otherwise, we hope you find DLC helpful for your research ;)

**Comment by KidElectric** [comment]
Sure! 
```
Traceback (most recent call last):
  File "test_dlc_jobarray.py", line 13, in <module>
    deeplabcut.analyze_videos(path_config_file,[video_path + video],gputouse=0,batchsize=8,save_as_csv = True)
  File "/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py", line 220, in analyze_videos
    DLCscorer=AnalyzeVideo(video,DLCscorer,DLCscorerlegacy,trainFraction,cfg,dlc_cfg,sess,inputs, outputs,pdindex,save_as_csv, destfolder,TFGPUinference,dynamic)
  File "/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py", line 497, in AnalyzeVideo
    PredictedData,nframes=GetPoseF_GTF(cfg,dlc_cfg, sess, inputs, outputs,cap,nframes,int(dlc_cfg["batch_size"]))
  File "/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py", line 395, in GetPoseF_GTF
    PredictedData[batch_num*batchsize:batch_num*batchsize+batch_ind, :] = pose[:batch_ind,:]
ValueError: could not broadcast input array from shape (6,30) into shape (5,30)
```

**Comment by KidElectric** [comment]
Also: yes! DLC is amazing and I am excited to make it a permanent part of my workflow. Thank you so much for this amazing project. I suspect the .mpg's are just corrupted somehow due to shoddy encoding by EthoVision. I can replicate the .mpg reading issues (frames read beyond nframes) without DLC so sorry to waste your time-- this is not specifically a DLC issue.

**Comment by MMathisLab** [comment]
NO worries - it's good to know/document for others. In fact, in a forthcoming update we have a backup video reader one can use that "might" deal with this- although I have not tried a .mpg file.
