### ISSUE TITLE
Evaluation Issue

### ISSUE THREAD

**Issue by AmeetR** [DeepLabCut/DeepLabCut#693]
**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: Google Colab
DeepLabCut Version [e.g. 22]: 2.1.8.1
Browser: Chrome

A clear and concise description of what the problem is.

On evaluation, I get the following issue. It seems that something is missing from the save file of the checkpoint. I can still predict videos. 

<img width="1482" alt="Screen Shot 2020-05-21 at 7 54 50 AM" src="https://user-images.githubusercontent.com/21989628/82572143-cf807e80-9b38-11ea-9595-8433962a0157.png">

**Comment by MMathisLab** [comment]
Did you click restart runtime after `pip install deeplabcut` ? Appears to be a matplotlib issue (could be the wrong version), but without seeing the full traceback hard to diagnose.

**Comment by AmeetR** [comment]
Looks like upgrading my matplotlib fixed it (and restarting the env) - there were matplotlib warnings early on in the stack trace that I didn't see. Thanks!
