### ISSUE TITLE
Extract frames error with crop w/GUI=true on Windows

### ISSUE THREAD

**Issue by inoejj** [DeepLabCut/DeepLabCut#694]
**Describe the bug**
Couldn't extract frames with the crop option enabled.
```
Config file read successfully.
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 0.0  seconds to 55.0  seconds.
Extracting and downsampling... 1650  frames from the video.
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "C:\Users\NAPEadmin\anaconda3\envs\dlc_jj\lib\site-packages\deeplabcut\gui\extract_frames.py", line 240, in extract_frames
    slider_width=slider_width,
  File "C:\Users\NAPEadmin\anaconda3\envs\dlc_jj\lib\site-packages\deeplabcut\generate_training_dataset\frame_extraction.py", line 279, in extract_frames
    color=cluster_color,
  File "C:\Users\NAPEadmin\anaconda3\envs\dlc_jj\lib\site-packages\deeplabcut\utils\frameselectiontools.py", line 374, in KmeansbasedFrameselectioncv2
    interpolation=cv2.INTER_NEAREST,
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
```
Please provide the minimal required code to re-produce the error.
1. Create a new project
2.  Click `Ok` button at the `Extract frames` tab.
![image](https://user-images.githubusercontent.com/48458315/82720697-ca235100-9c6a-11ea-91d7-f9bc499bba76.png)

error out on both cases ( using or not using opencv)
![image](https://user-images.githubusercontent.com/48458315/82720716-08207500-9c6b-11ea-9477-d223203c8905.png)

**Desktop (please complete the following information about your system):**
 - OS: windows10
 - DeepLabCut Version 2.2b5
 - Python 3.6.10

**Comment by inoejj** [comment]
I was able to extract frames without cropping. However, when I tried to label frames. This happened.

![image](https://user-images.githubusercontent.com/48458315/82720813-e83d8100-9c6b-11ea-8cd8-da092d6559cf.png)

**Comment by MMathisLab** [comment]
Please downgrade wxPython (this is a wxPython bug). https://github.com/DeepLabCut/DeepLabCut/issues/682

**Comment by MMathisLab** [comment]
@inoejj did the wx change fix your issue?

**Comment by inoejj** [comment]
Yes it did. I was able to extract frames without cropping the frames.

However, when I chose `GUI` to crop frame, I was not able to do it, but it is not a big deal.

Thanks,
JJ

**Comment by MMathisLab** [comment]
I'll look into it; working on MacOS and Ubuntu (don't have a windows machine at home right now).

**Comment by jeylau** [comment]
Hi @inoejj! The bug you reported is squashed in ad10f9186cc2e88690dadda4b75098089825693b. Happy cropping 😄

**Comment by MMathisLab** [comment]
this breaks on ubuntu though; should be fixed to revert and just added: 
```
if platform.system() == "Windows":
     fig.canvas.start_event_loop(timeout=-1)
```

**Comment by inoejj** [comment]
Alright. Thanks, I will give it a shot.
