### ISSUE TITLE
pose_estimation_tensorflow.lib

### ISSUE THREAD

**Issue by lukehshaw** [DeepLabCut/DeepLabCut#696]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Describe the bug**

Hi! Heads up for you. Trying to get newest version running from a local directory. 
on import getting this:  No module named 'deeplabcut.pose_estimation_tensorflow.lib'
when it's running this: deeplabcut\pose_estimation_tensorflow\__init__.py
i suspect on account of there being no lib subdirectory in pose_est_tf at the moment!

**Desktop (please complete the following information about your system):**
 - OS: Win10
 - DeepLabCut Version 2.2b5

**Additional context**
Thanks!!

**Comment by MMathisLab** [comment]
awe yes, if you pip install (`pip install deeplabcut==2.2b5`) you will get it, but indeed it's not in the source code right now.

**Comment by lukehshaw** [comment]
Grand. Thanks for the swift reply!

**Comment by msadeghm** [comment]
> awe yes, if you pip install (`pip install deeplabcut==2.2b5`) you will get it, but indeed it's not in the source code right now.

Does not work for me.

**Comment by MMathisLab** [comment]
you can run `pip install --upgrade deeplabcut` or `pip install deeplabcut==2.1.9` for the latest (be sure you do so in your enviroment)

**Comment by msadeghm** [comment]
> you can run `pip install --upgrade deeplabcut` or `pip install deeplabcut==2.1.9` for the latest (be sure you do so in your enviroment)

Thanks for swift reply. Actually, I want to use DLC for multiple animals, does deeplabcut v2.1.9 support this?

**Comment by MMathisLab** [comment]
yep! it was just released ~30 min ago :)
