### ISSUE TITLE
MA conversion animal list

### ISSUE THREAD

**Issue by PolarBean** [DeepLabCut/DeepLabCut#697]
Just a quick bug, apologies for not following the scaffold. 
When running deeplabcut.convert2_maDLC(path_config_file, userfeedback=True) there was an error which stated 
ScannerError: while scanning a simple key
  in "config.yaml", line 7, column 1
could not find expected ':'
  in "config.yaml", line 8, column 1

the solution for this was to instead list the mouse name as a list like this:
individuals: ['mouse1']

instead of the suggested;
individuals:
-mouse1

Easy fix and hope this helps others.

**Comment by MMathisLab** [comment]
Actually,  it cannot be `-mouse1` but must be `- mouse1` (i.e. the space is crucial). 

(so the docs are correct: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/convert_maDLC.md)
