### ISSUE TITLE
convert2_maDLC scorer issue

### ISSUE THREAD

**Issue by lukehshaw** [DeepLabCut/DeepLabCut#699]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Describe the bug**

After reformatting my config, I run convert2_maDLC and am asked whether I want the first labeled file to be converted. I answer, yes, and I get a key error related to scorer name.

Please place code inside this:
<details><summary>Code output</summary><p>

```python
KeyError                                  Traceback (most recent call last)
<ipython-input-9-ed816a58913b> in <module>
----> 1 deeplabcut.convert2_maDLC(config_path, userfeedback=True)

~\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\utils\auxfun_multianimal.py in convert2_maDLC(config, userfeedback, forceindividual)
    181                 )
    182
--> 183                 if bpt in Data[cfg["scorer"]].keys():
    184                     frame = pd.DataFrame(
    185                         Data[cfg["scorer"]][bpt].values, columns=index, index=imindex

~\anaconda3\envs\DLC-GPU\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   2797         if is_single_key:
   2798             if self.columns.nlevels > 1:
-> 2799                 return self._getitem_multilevel(key)
   2800             indexer = self.columns.get_loc(key)
   2801             if is_integer(indexer):

~\anaconda3\envs\DLC-GPU\lib\site-packages\pandas\core\frame.py in _getitem_multilevel(self, key)
   2847     def _getitem_multilevel(self, key):
   2848         # self.columns is a MultiIndex
-> 2849         loc = self.columns.get_loc(key)
   2850         if isinstance(loc, (slice, Series, np.ndarray, Index)):
   2851             new_columns = self.columns[loc]

~\anaconda3\envs\DLC-GPU\lib\site-packages\pandas\core\indexes\multi.py in get_loc(self, key, method)
   2660         if not isinstance(key, (tuple, list)):
   2661             # not including list here breaks some indexing, xref #30892
-> 2662             loc = self._get_level_indexer(key, level=0)
   2663             return _maybe_to_slice(loc)
   2664

~\anaconda3\envs\DLC-GPU\lib\site-packages\pandas\core\indexes\multi.py in _get_level_indexer(self, key, level, indexer)
   2927         else:
   2928
-> 2929             code = self._get_loc_single_level_index(level_index, key)
   2930
   2931             if level > 0 or self.lexsort_depth == 0:

~\anaconda3\envs\DLC-GPU\lib\site-packages\pandas\core\indexes\multi.py in _get_loc_single_level_index(self, level_index, key)
   2596             return -1
   2597         else:
-> 2598             return level_index.get_loc(key)
   2599
   2600     def get_loc(self, key, method=None):

~\anaconda3\envs\DLC-GPU\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2646                 return self._engine.get_loc(key)
   2647             except KeyError:
-> 2648                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2649         indexer = self.get_indexer([key], method=method, tolerance=tolerance)
   2650         if indexer.ndim > 1 or indexer.size > 1:

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'luke'

```

```python

deeplabcut.convert2_maDLC(config_path, userfeedback=True)

```
</p></details>

Here is my config:

[configtxt.txt](https://github.com/DeepLabCut/DeepLabCut/files/4678157/configtxt.txt)

**Desktop (please complete the following information about your system):**
 - OS: [e.g. Windows10
 - DeepLabCut Version 2.2b5

**Comment by AlexEMG** [comment]
Is the scorer for the previous project 'luke'?

**Comment by lukehshaw** [comment]
![image](https://user-images.githubusercontent.com/26383714/82836583-c246f500-9e94-11ea-9f75-8dde100961e1.png)
Correct. Pasted a screen grab from collecteddata_luke.csv

**Comment by AlexEMG** [comment]
The error suggest that the key "luke" does not exist... The code will look for a h5 - is present as well? Also the name is capitalized, i.e. `CollectedData_ luke.h5`

For ref, here are the docs:
https://github.com/DeepLabCut/DeepLabCut/blob/e5c3384897b39e3e33ca440ffef9a7830bb02a70/docs/convert_maDLC.md

**Comment by lukehshaw** [comment]
Everything appears to be formatted properly. Strangely, I ran the script and skipped over (said no for) the first labeled-data folder accidentally and it successfully ran (upon prompting yes) for all the subsequent labeled-data folders. Upon trying to run again on the first folder, it returns the same error. Idk what's up but i'll just figure out how to add the forceindividual into the .h5 manually for that one using your script. curious if others will find similar behavior.

**Comment by MMathisLab** [comment]
> and it successfully ran (upon prompting yes) for all the subsequent labeled-data folders

I'm not sure what the behavior would be on a second run; what is now inside the one folder it did not convert?

**Comment by lukehshaw** [comment]
In folder one there are the CollectedData_luke .csv and .h5 files and there are .png files. In subsequent folders there are those plus additional singleanimal .csv and .h5 files. Opening the new CollectedData_luke.csv in one of these subsequent folders I see the additional individuals line.

**Comment by AlexEMG** [comment]
Ok, so all well that ends well?

**Comment by lukehshaw** [comment]
Yes, I was able to add the individuals row in the .csv and then your csv2h5 script worked perfectly. Thanks!!
