### ISSUE TITLE
Manage Project menu tab can't be clicked on / activated

### ISSUE THREAD

**Issue by catubc** [DeepLabCut/DeepLabCut#700]
**Describe the bug**

After the latest fix to missing file DLC starts up but I can't seem to be able to click on the Manage Project tab in the GUI.  I repulled on another workstation and the menu is available there.  Any suggestions?  There are no printed errors in the ipython logs.

**To Reproduce**
Steps to reproduce the behavior, i.e.:
1. deeplbacut.launch_dlc()
2. Try to click on "Manage Project"

**Desktop (please complete the following information about your system):**
 - OS: Ubuntu 18.04
 - DeepLabCut Version 2.2b5

**Comment by MMathisLab** [comment]
can you try `python -m deeplabcut` in your terminal? I not getting issues

**Comment by AlexEMG** [comment]
Does the "old GUI" work (i.e. of a previous version)? I suppose its a wxpython version issue @MMathisLab?

**Comment by MMathisLab** [comment]
@AlexEMG I am assuming @catubc comment that your last push causes this, but it's working fine for me, and your commit only added a sub-mod of `pose_estimation_tensorflow` (that is already available in the pip package, so no worries ;)

but yes, @catubc be sure you have  `wxpython<4.1.0` wheels installed; the latest has issues for all operating platforms (i.e. not a DLC issue, but a wx issue)

**Comment by catubc** [comment]
Yes, the one that doesn't work has wxPython 4.0.3 installed
The one that works has wxPython 4.0.7.post2 installed

**Comment by AlexEMG** [comment]
Use the last 4.0.x (the 4.1.x are the troublemakers in our experience)

**Comment by catubc** [comment]
Sorry, just to clarify, the menu wasn't broken by the latest fix, but by 2.2b5 update. 
I will try upgrading wxPython module, but the pip wheels are kind of broken. Will post updates later.
Thanks!

PS: python -m deeplabcut also has same menu disabled issue.

**Comment by MMathisLab** [comment]
Yes, it will require an update to wx (i.e. wxPython 4.0.7.post2 works), but 4.1.0 will not. For 18.04; and here is a list of wheels: https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/
```
pip install -U \
    -f  https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/wxPython-4.0.7.post2-cp37-cp37m-linux_x86_64.whl \
    wxPython
```

**Comment by catubc** [comment]
Thanks, but that install method doesn't work.  I've tried a few other pip install options, and I think source compilation might be the only one that works on my end.

**Comment by MMathisLab** [comment]
I think we can close this though, since we know it's working with: 

> The one that works has wxPython 4.0.7.post2 installed

**Comment by catubc** [comment]
Ok,
So for those still looking at this, the simple solution is:

1.  Uninstall all wxpython using:

`pip uninstall wxpython` (<- might have to run this 2 x to make sure it's fully gone).

2.  Use conda install option to install wxpython.  This installs the current version which is 4.0.4:

` conda install -c anaconda wxpython `

This method seems to have re-enabled the menus to work in the GUI.

catubc
