### ISSUE TITLE
"import deeplabcut" produces " 'TkAgg' which requires the 'tk' " error when remote accessing from Mac OS

### ISSUE THREAD

**Issue by vanburet** [DeepLabCut/DeepLabCut#701]
Tyler VanBuren	“import deeplabcut” disabled due to remote access from Mac OS

Remote Access Computer:
        VERSION="16.04.6 LTS (Xenial Xerus)"
        PRETTY_NAME="Ubuntu 16.04.6 LTS"

Your Operating system:
        System Version: macOS 10.15.4 (19E287)
      	Kernel Version: Darwin 19.4.0

Please complete the following information about your system:

OS: [Ubuntu 16.04.6 LTS] DeepLabCut Version: [2.X] (issue with “import deeplabcut”) Anaconda env used: Python 3

Describe the problem:
When typing into jupyter notebook, that is running on linux from a remote Mac, it gives the error code: 
Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

A clear and concise description of what the problem is:

import deeplabcut on linux is producing an error when using remote access from Mac. Error posted below.

Please place code inside this:
<details><summary>Code output</summary><p>

```python

Full Error Report:

ImportError                               Traceback (most recent call last)
<ipython-input-1-cfa4f159dfc5> in <module>()
----> 1 import deeplabcut

/home/vanbur28/.local/lib/python3.6/site-packages/deeplabcut/__init__.py in <module>()
     28     else:
     29         mpl.use('Agg')
---> 30     from deeplabcut import generate_training_dataset
     31     from deeplabcut import refine_training_dataset
     32     from deeplabcut.generate_training_dataset import label_frames, dropannotationfileentriesduetodeletedimages, comparevideolistsanddatafolders, dropimagesduetolackofannotation

/home/vanbur28/.local/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/__init__.py in <module>()
     17 else:
     18     from deeplabcut.generate_training_dataset.auxfun_drag_label import *
---> 19     from deeplabcut.generate_training_dataset.labeling_toolbox import *
     20     from deeplabcut.generate_training_dataset.multiple_individuals_labeling_toolbox import *
     21     from deeplabcut.generate_training_dataset.frame_extraction_toolbox import *

/home/vanbur28/.local/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/labeling_toolbox.py in <module>()
     25 import argparse
     26 from deeplabcut.generate_training_dataset import auxfun_drag_label
---> 27 from deeplabcut.utils import auxiliaryfunctions
     28 from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg as FigureCanvas
     29 from matplotlib.backends.backend_wxagg import NavigationToolbar2WxAgg as NavigationToolbar

/home/vanbur28/.local/lib/python3.6/site-packages/deeplabcut/utils/__init__.py in <module>()
----> 1 from deeplabcut.utils.make_labeled_video import *
      2 from deeplabcut.utils.auxiliaryfunctions import *
      3 from deeplabcut.utils.video_processor import *
      4 from deeplabcut.utils.plotting import *
      5 

/home/vanbur28/.local/lib/python3.6/site-packages/deeplabcut/utils/make_labeled_video.py in <module>()
     32     mpl.use('WxAgg') #TkAgg
     33 else:
---> 34     mpl.use('TkAgg')
     35 import matplotlib.pyplot as plt
     36 

/opt/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/matplotlib/__init__.py in use(arg, warn, force)
   1389         if force:
   1390             from matplotlib.pyplot import switch_backend
-> 1391             switch_backend(name)
   1392     # Finally if pyplot is not imported update both rcParams and
   1393     # rcDefaults so restoring the defaults later with rcdefaults

/opt/anaconda3/envs/dlc-ubuntu-GPU/lib/python3.6/site-packages/matplotlib/pyplot.py in switch_backend(newbackend)
    220                 "Cannot load backend {!r} which requires the {!r} interactive "
    221                 "framework, as {!r} is currently running".format(
--> 222                     newbackend, required_framework, current_framework))
    223 
    224     rcParams['backend'] = rcParamsDefault['backend'] = newbackend

ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running


```
</p></details>
How to Reproduce the problem Steps to reproduce the behavior:

Remote access to computer: 
Using Mac computer to log into campus network using pulse secure -> 

Enter into Mac terminal to access linux computer: ssh -L localhost:8888:localhost:8888 <username>@xx.xx.xxx.xxx                                                                         -->

Type into linux computer terminal: conda activate dlc-ubuntu-GPU                    -->

Type into linux computer terminal: jupyter notebook --no-browser --port=8888          -->

Type into Mac browser (used chrome and safari): The link given for jupyter session     -->
	
In jupyter notebook opened from Mac entered: import deeplabcut

**Comment by AlexEMG** [comment]
Not sure if you use ubuntu/macOS from how you filled out the template. But on macOS you need to use pythonw. 

> In jupyter notebook opened from Mac entered: import deeplabcut

Note jupyter notebooks do not work on MacOS at this time (as stated in the docs): https://github.com/DeepLabCut/DeepLabCut/blob/e5c3384897b39e3e33ca440ffef9a7830bb02a70/docs/UseOverviewGuide.md#option-1-demo-notebooks

**Comment by vanburet** [comment]
> Not sure if you use ubuntu/macOS from how you filled out the template. But on macOS you need to use pythonw.
> 
> > In jupyter notebook opened from Mac entered: import deeplabcut
> 
> Note jupyter notebooks do not work on MacOS at this time (as stated in the docs): https://github.com/DeepLabCut/DeepLabCut/blob/e5c3384897b39e3e33ca440ffef9a7830bb02a70/docs/UseOverviewGuide.md#option-1-demo-notebooks

I am on a Mac computer and accessing a linux computer

**Comment by AlexEMG** [comment]
I see -- in such forwarding cases you need to check carefully.. see e.g. https://github.com/DeepLabCut/DeepLabCut/issues/556
I also believe this has nothing to do with DLC, rather a general feature for your setup.

**Comment by vanburet** [comment]
To re-clarify again I am working on a Mac accessing a Linux using terminal ssh command for remote access. 

I got the "import deeplabcut" command in juypter notebooks to work by doing following steps:
1.) installing Xquartz on the Mac.
2.) Editing ssh config file using mac's terminal: sudo nano /etc/ssh/ssh_config
Adding: 
X11Forwarding yes
X11UseForwarding yes
3.) Opening Xquartz in the background
4.) Terminal command to connect to computer: 
ssh -X -L localhost:8888:localhost:8888 username@<IP_Adress>

**Comment by Alyetama** [comment]
> To re-clarify again I am working on a Mac accessing a Linux using terminal ssh command for remote access.
> 
> I got the "import deeplabcut" command in juypter notebooks to work by doing following steps:
> 1.) installing Xquartz on the Mac.
> 2.) Editing ssh config file using mac's terminal: sudo nano /etc/ssh/ssh_config
> Adding:
> X11Forwarding yes
> X11UseForwarding yes
> 3.) Opening Xquartz in the background
> 4.) Terminal command to connect to computer:
> ssh -X -L localhost:8888:localhost:8888 @<IP_Adress>

I am having the same problem.  Unfortunately, this doesn't work for me since I don't have sudo access on my machine.
