### ISSUE TITLE
Unable to create training dataset on google colab

### ISSUE THREAD

**Issue by Kat-8-S** [DeepLabCut/DeepLabCut#704]
Thank you for the new release! Very exciting!

Please state your operating system, env, and which version of DeepLabCut you are using.
Windows 10, with an Anaconda Env, & DeepLabCut 2.2.b5

Please complete the following information about your system:

OS: Windows 10
DeepLabCut Version: 2.2.b5
Anaconda env used: yes

I used the GUI to create the new project. I was able to label the frames and can see that the new folders marked "_labelled" are created in the labelled data folder. The "crop and label images" function did not work for me in the GUI. I then unchecked the "Crop and Label Images" box in the GUI to try creating the multi animal training dataset without this function, but ran into another error. Finally, I tried uploading the folder onto my google colab script to create the dataset in colab, which I would have done even if the GUI steps had all worked, because I train my model on google colab, however, I ran into an error on colab.

Please place code inside this:

**a)** Crop and Label Images- checked "yes" in GUI, followed by clicking "Ok."
**b)** Crop and Label Images- checked "no" in GUI, followed by clicking "Ok."
**c)** deeplabcut.create_multianimaltraining_dataset(path_config_file).

[Please copy/paste the full terminal output of the error here!!!]

**a)** 
```
ValueError                                Traceback (most recent call last)
~\Anaconda3\envs\dlc-windowsCPU\lib\site-packages\deeplabcut\gui\create_training_dataset.py in create_training_dataset(self, event)
    337         if config_file.get("multianimalproject", False):
    338             if self.cropandlabel.GetStringSelection() == "Yes":
--> 339                 deeplabcut.cropimagesandlabels(self.config, userfeedback=userfeedback)
    340             else:
    341                 random = False

~\Anaconda3\envs\dlc-windowsCPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py in cropimagesandlabels(config, numcrops, size, userfeedback, cropdata, excludealreadycropped, updatevideoentries)
    340                     dd = np.array(data[ind].copy(), dtype=float)
    341                     y0, x0 = (
--> 342                         np.random.randint(h - size[0]),
    343                         np.random.randint(w - size[1]),
    344                     )

mtrand.pyx in mtrand.RandomState.randint()

ValueError: Range cannot be empty (low >= high) unless no samples are taken
```
**b)**
```
C:\Users\kat8s\Desktop\DLC_MultiAnimal2020\Test-Kat-2020-05-25\training-datasets\iteration-0\UnaugmentedDataSet_TestMay25  already exists!
C:\Users\kat8s\Desktop\DLC_MultiAnimal2020\Test-Kat-2020-05-25\labeled-data\Feb.11_c1-001_0001_cropped\CollectedData_Kat.h5  not found (perhaps not annotated). If training on cropped data, make sure to call `cropimagesandlabels` prior to creating the dataset.
C:\Users\kat8s\Desktop\DLC_MultiAnimal2020\Test-Kat-2020-05-25\labeled-data\Feb.11_c1-001_0002_cropped\CollectedData_Kat.h5  not found (perhaps not annotated). If training on cropped data, make sure to call `cropimagesandlabels` prior to creating the dataset.
C:\Users\kat8s\Desktop\DLC_MultiAnimal2020\Test-Kat-2020-05-25\labeled-data\Feb.11_c1-001_0003_cropped\CollectedData_Kat.h5  not found (perhaps not annotated). If training on cropped data, make sure to call `cropimagesandlabels` prior to creating the dataset.
C:\Users\kat8s\Desktop\DLC_MultiAnimal2020\Test-Kat-2020-05-25\labeled-data\Feb.11_c1-001_0004_cropped\CollectedData_Kat.h5  not found (perhaps not annotated). If training on cropped data, make sure to call `cropimagesandlabels` prior to creating the dataset.
Annotation data was not found by splitting video paths (from config['video_sets']). An alternative route is taken...
The following folders were found: ['C:\\Users\\kat8s\\Desktop\\DLC_MultiAnimal2020\\Test-Kat-2020-05-25\\labeled-data\\Feb_cropped']
C:\Users\kat8s\Desktop\DLC_MultiAnimal2020\Test-Kat-2020-05-25\labeled-data\Feb_cropped\CollectedData_Kat.h5  not found (perhaps not annotated)
No data was found!
```
**c)** 
```
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-22-33e81968c718> in <module>()
      1 ##Newly added May 26/2020
      2 
----> 3 deeplabcut.create_multianimaltraining_dataset(path_config_file)

7 frames
/usr/local/lib/python3.6/dist-packages/imageio/core/request.py in _parse_uri(self, uri)
    271                 # Reading: check that the file exists (but is allowed a dir)
    272                 if not os.path.exists(fn):
--> 273                     raise FileNotFoundError("No such file: '%s'" % fn)
    274             else:
    275                 # Writing: check that the directory to write to does exist

FileNotFoundError: No such file: '/content/drive/My Drive/DLC/DLC_MultiAnimal2020/Test-Kat-2020-05-25/labeled-data/Feb.11_c1-001_0001_'
```
**How to Reproduce the problem**
1) I used the GUI to create a new project. 
2) I was able to label the frames from four videos and can see that the new folders marked "_labelled" are created in the labelled data folder.
3) In the "Create training dataset" tab, I clicked "yes" at Crop and Label Data. I then clicked "Ok," but was given an error message in the anaconda terminal window -> please see **a)**  
4) I then tried clicking "no" at Crop and Label Data. Then "Ok," but was given a different error message -> please see **b)**
5) I then decided to upload the folder onto my google drive to create the training dataset in a google colab script, which I would have also done anyhow if the "crop and save images" function had worked in the GUI, because I train the model using google colab, but ran into an error -> please see **c)**

**Screenshots**
![A](https://user-images.githubusercontent.com/65971162/82933033-55486380-9f57-11ea-9003-065aca73522e.PNG)
![C1](https://user-images.githubusercontent.com/65971162/82933042-58dbea80-9f57-11ea-8457-cf7e3cee6a76.PNG)
![C2](https://user-images.githubusercontent.com/65971162/82933090-6abd8d80-9f57-11ea-9880-112613ba73ba.PNG)

**Additional context**

**Comment by AlexEMG** [comment]
It appears that your video was not added correctly?

**Comment by MMathisLab** [comment]
Hi @Kat-8-S - 

couple of questions. what is the dimension of your frames? The `cropandlabel` by default crops to 400 by 400 (but if your images are smaller, perhaps you get your first error **a**.

Secondly, it is indeed important to create the trainingdataset on colab, but what happens when it runs cropandalablel is you will see your `video_path` in the `config.yaml` changed to append `_cropped.mp4` (etc) which now links to a "fake" video. 

So, in short, what you need to do is:

(1) fix you config.yaml file back to the original state. You will see at the very bottom, the "original video_set" is there, so just copy/paste back to the top. 

(2) run cropandlabel and create-training-set on COLAB (here is a WIP notebook from me - it work through training you can use; you can then, if your images are smaller than 400 x 400 pixels, edit the crop boundaries to be smaller: i.e., edit `size=(400, 400)` to something smaller than your images. Hope that helps!

Edit to add the notebook is now in the main repo: https://github.com/DeepLabCut/DeepLabCut/blob/master/examples/COLAB_maDLC_TrainNetwork_VideoAnalysis.ipynb

**Comment by Kat-8-S** [comment]
Hello,

Thank you so much for your fast response! I really appreciate your help.

I created a new project today using the GUI to avoid any potential concerns with changing the file names back incorrectly. The original file names were not listed at the bottom of the config file from yesterday, there was only a set of open curly brackets {}. 

My frame dimensions in the config file (from today) after cropping during manual frame extraction are (339, 905, 37, 322). I tried editing the crop boundaries in the cropimagesandlabels function on the colab script with a range of smaller values going down to (10,10) without any success.

One thing that I noticed in the output of the error message with the cropimagesandlabels function on the colab script is that the video path from my config file is being inserted into the path, which then states that the concatenated path does not exist. Could this be part of the problem? 

Image A shows the videofile path specified in the colab script. 
![A](https://user-images.githubusercontent.com/65971162/83061781-88f4bd80-a02b-11ea-82cd-bfb4c7feb44d.PNG)

Image B shows the error message when running the cropandlabels function in colab.
![B](https://user-images.githubusercontent.com/65971162/83061438-f6ecb500-a02a-11ea-9aa8-57cd175bd06e.png)

Image C shows the video path in the config file. 
![C](https://user-images.githubusercontent.com/65971162/83061452-fd7b2c80-a02a-11ea-97f6-585e54651dc7.PNG)

Thank you for any suggestions on how to fix this error!

**Comment by MMathisLab** [comment]
oh.... this is a windows to linux issue! I'm not sure we have it check to convert for this crop step actually; good beta test check :) Will look into it.

Otherwise, when you create the training set you will need to add `windows2linux=True` i.e., 

`deeplabcut.create_multianimaltraining_dataset(path_config_file, windows2linux=True)`

(i'll make this more obvious in the notebook!)
