### ISSUE TITLE
export score-map? [function to store those added]

### ISSUE THREAD

**Issue by xkcdfan** [DeepLabCut/DeepLabCut#71]
Could you add a script to export the score-map as an image like a jpg or tiff so that we can visualize it as a heat map like in Figure 7 of the paper? Or is there already an easy way to do this?

**Comment by AlexEMG** [comment]
Voila: https://github.com/AlexEMG/DeepLabCut/blob/1.11/Analysis-tools/AnalyzeVideosAndExtractScoreMaps.py

**Comment by ele-meni** [comment]
Is there an update for this function? Thanks

**Comment by MMathisLab** [comment]
The code is in Alexs response above...

**Comment by ele-meni** [comment]
I am not able to find the link/file

**Comment by AlexEMG** [comment]
https://github.com/AlexEMG/DeepLabCut/blob/1.11/Analysis-tools/AnalyzeVideosAndExtractScoreMaps.py
