### ISSUE TITLE
different body parts = different individuals in maDLC?

### ISSUE THREAD

**Issue by lukehshaw** [DeepLabCut/DeepLabCut#710]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Your Operating system and DeepLabCut version**

OS: Win10
DeepLabCut Version: 2.2b5
Anaconda env used: GPU

**Describe the problem**

I'm thinking about how to best utilize the new functionality of maDLC. I have a paradigm where marmosets reach for food rewards. See screenshot below. I have been labeling points on the right hand (wrist, knuckles, tips/fingernails), points on the left hand (same), and points on the face (nose and perimeter of white patch). In past DLC versions, points would occasionally jump from hand to hand - usually only at noncritical points of the reach, but it's still something I would like to miminize. Would it make sense to define each hand and the face as three separate individuals? We don't need true multianimal estimation b/c there's only one marmo at a time. But, the question is, should these three elements be defined as individuals or should they just be different, separate skeletons to best utilize the update? Thanks!! Appreciate your time and contributions so much!!

**Screenshots**

![img6812](https://user-images.githubusercontent.com/26383714/83071154-a715ea00-a03a-11ea-8791-03d2f1d46798.png)

**Additional context**

**Comment by MMathisLab** [comment]
Hi @turbolukeshaw thanks for the question. We would ask that user questions though get posted to ImageFourm: https://forum.image.sc/tags/deeplabcut 

In short, no they should NOT be individuals. 2.2 will already use the skeleton to build in relationships, which would help with swaps. 

Please see this video tutorial that explains more: https://www.youtube.com/watch?v=JDsa8R5J0nQ

and how to best use the skeleton feature: https://www.youtube.com/watch?v=fQSJ0S08UyY
