### ISSUE TITLE
deeplabcut.analyzeskeleton returns "Video not analyzed" even after video is analyzed

### ISSUE THREAD

**Issue by BKTidswell** [DeepLabCut/DeepLabCut#712]
OS: OS X 10.15.4
DeepLabCut Version: 2.2b5
Anaconda env used: DLC-CPU

**Describe the problem**

The issue I am running into is that `deeplabcut.analyzeskeleton` is telling me that I need to analyze the video first, but I have already analyzed the video.

When I run 
`deeplabcut.analyze_videos(config_path, '/Users/Ben/Desktop/DLC Test/Multi_Test_2-Ben-2020-05-27/videos/Trimmed_Out.mp4', videotype='.mp4', save_as_csv = True)` 
it returns 
`Video already analyzed! /Users/Ben/Desktop/DLC Test/Multi_Test_2-Ben-2020-05-27/videos/Trimmed_OutDLC_resnet50_Multi_Test_2May27shuffle1_500.h5
The videos are analyzed. Time to assemble animals and track 'em... `

When I then run 
`deeplabcut.analyzeskeleton(config_path, '/Users/Ben/Desktop/DLC Test/Trimmed_Out.mp4', videotype='mp4', shuffle=1, trainingsetindex=0, save_as_csv=True, destfolder='/Users/Ben/Desktop/DLC Test')` 
it returns 
`Processing /Users/Ben/Desktop/DLC Test/Trimmed_Out.mp4
Video not analyzed -- Run analyze_videos first.`

I can see the file "Trimmed_OutDLC_resnet50_Multi_Test_2May27shuffle1_500_sk.h5" which I believe was created by deeplabcut.analyze_videos in the folder with Trimmed_Out.mp4, and so I am unclear as to why deeplabcut.analyzeskeleton is telling me to analyze the video first.

Currently I have the tracked videos of the fish I am working with, and am just trying to extract the locations of each of the points along the body for further analysis. 

I am a new user and so may be doing something wrong here, but the condracticions between the deeplabcut.analyzeskeleton and deeplabcut.analyze_videos is confusing me. Thanks for your help!

**Comment by MMathisLab** [comment]
Hi @BKTidswell assuming this is a multi-animal project, this function (`analyzeskeleton`) isn't supported at this time (i.e. during the beta release). It will require a bit of refactoring to deal with the new pandas structure we have post tracking. 

other points: 

> "Trimmed_OutDLC_resnet50_Multi_Test_2May27shuffle1_500_sk.h5" 

If that file exists, I assume you converted to tracklets, then refined them, and saved in the GUI, i.e. in 2.2b5 in multi-animal mode one does not get an `.h5` until they assemble animals, etc :)

> Currently I have the tracked videos of the fish I am working with, and am just trying to extract the locations of each of the points along the body for further analysis.

the `.h5` file you reference has all the bodyparts per frame extracted. This is what is used to (1) create labeled videos, and plot the trajectories of each animal if you run `plot_trajectories`

**Comment by BKTidswell** [comment]
Thanks for clearing this up and your quick response! It’s a great program and I’m very excited that the beta is out.
