### ISSUE TITLE
Frame extraction failed. Video files must be corrupted.

### ISSUE THREAD

**Issue by kpeez** [DeepLabCut/DeepLabCut#719]
Hello, my apologies if this has been posted before but I searched through previous issues and did not see this. I am having an issue running extract_frames() after creating a new project, and the error message I receive does not provide me with any information about where to begin troubleshooting. Any help is greatly appreciated!

**Please state your operating system, env, and which version of DeepLabCut you are using.**
macOS 10.15.4, with an Anaconda Env, & DeepLabCut2.1.8.

**Describe the problem**

Any time I attempt to run extract_frames() after creating a new project it returns the error shown in the screenshot "Frame extraction failed. Video files must be corrupted." This happens regardless of what video I use, even the example open field video provided in the p

Please place code inside this:

<details><summary>Code output</summary><p>
deeplabcut.create_new_project('deeptfc', 'kpuhger', ['/Users/kpuhger/1-Projects/DeepTFC/videos/3_trial/train/tfc_3trial_run1_box1.wmv'], working_directory='/Users/kpuhger/1-Projects/DeepTFC/')

Created "/Users/kpuhger/1-Projects/DeepTFC/deeptfc-kpuhger-2020-06-01/videos"
Created "/Users/kpuhger/1-Projects/DeepTFC/deeptfc-kpuhger-2020-06-01/labeled-data"
Created "/Users/kpuhger/1-Projects/DeepTFC/deeptfc-kpuhger-2020-06-01/training-datasets"
Created "/Users/kpuhger/1-Projects/DeepTFC/deeptfc-kpuhger-2020-06-01/dlc-models"
Attempting to create a symbolic link of the video ...
Created the symlink of /Users/kpuhger/1-Projects/DeepTFC/videos/3_trial/train/tfc_3trial_run1_box1.wmv to /Users/kpuhger/1-Projects/DeepTFC/deeptfc-kpuhger-2020-06-01/videos/tfc_3trial_run1_box1.wmv
/Users/kpuhger/1-Projects/DeepTFC/deeptfc-kpuhger-2020-06-01/videos/tfc_3trial_run1_box1.wmv
Generated "/Users/kpuhger/1-Projects/DeepTFC/deeptfc-kpuhger-2020-06-01/config.yaml"

A new project with name deeptfc-kpuhger-2020-06-01 is created at /Users/kpuhger/1-Projects/DeepTFC and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
Out[3]: '/Users/kpuhger/1-Projects/DeepTFC/deeptfc-kpuhger-2020-06-01/config.yaml'

In [4]: cfg_path = '/Users/kpuhger/1-Projects/DeepTFC/deeptfc-kpuhger-2020-06-01/config.yaml'

In [5]: dlc.extract_frames(cfg_path)
Config file read successfully.
Do you want to extract (perhaps additional) frames for video: /Users/kpuhger/1-Projects/DeepTFC/videos/3_trial/train/tfc_3trial_run1_box1.wmv ?
yes/no yes
Frame extraction failed. Video files must be corrupted.

</p></details>

**How to Reproduce the problem**
1. Clone deeplabcut from repo
2. Create conda env for dlc-cpu
3. Activate dlc-cpu environment
4. Launch IPython
5. Import deeplabcut
6. Create new project
7. Attempt to extract frames.

**Screenshots**
![Screen Shot 2020-06-01 at 11 36 00 AM](https://user-images.githubusercontent.com/25070796/83442467-13a73500-a3fd-11ea-89fd-7fafd5e5b879.png)

**Comment by MMathisLab** [comment]
on MacOS you will need to use `pythonw` not `ipython` as it needs a framework build of python; also can you confirm you can open all the videos in VLC otherwise? 

> Attempting to create a symbolic link of the video ...
Created the symlink of /Users/kpuhger/1-

perhaps try with `copy video=True`; also you might want to upgrade (run  `pip install deeplabcut==2.2b5` while inside your env) as the GUI has some nice new features :)

**Comment by kpeez** [comment]
Yes I can open the videos without issue in VLC.

1. Tried repeating the process using `pythonw` instead of `ipython`, still receiving the same error.
2. Tried using `pythonw` and set `copy_videos=True`, still receiving error.
3. Upgraded package (`conda activate dlc-cpu` -> `pip install deeplabcut==2.2b5`) and repeated previous steps (using `pythonw` and `copy_videos=True`), still receiving the error.

**Comment by MMathisLab** [comment]
hm, well I can confirm it's working currently for me (on MacOS 10.15.4, and others) so it must be something specific to your installation. 

To be sure you don't have a typo or such, perhaps try from the GUI interface to create your project: https://www.youtube.com/watch?v=JDsa8R5J0nQ 

namely, 
```
conda activate DLC-CPU
pythonw -m deeplabcut
```

**Comment by kpeez** [comment]
Okay so running it from the terminal is still not working for me, but the GUI appears to be working. Thanks for your help! :)

**Comment by MMathisLab** [comment]
^okay great; so likely then it's just some difference in formatting that is going into either extract frames or how you created the project :) But, glad it's all working now.
