### ISSUE TITLE
config file format unclear

### ISSUE THREAD

**Issue by SebastianKloubert** [DeepLabCut/DeepLabCut#720]
OS: Ubuntu 18.04.3
DeepLabCut Version: Deeplabcut 2.1.6
Anaconda env used: yes

Hey guys,

I have two problems. The first one will be quite easy to answer, but i don't found the answer myself.

1.

When you refer to the numbers of frames which you use to train a network, does this number represent the total amount of frames or the frames per video that you use to train the network?

e.g.
you want to train a network based on three different videos and want to pick 150 frames.
Does this mean:
3 x 150 frames = 450 frames
or
3 x 50 frames = 150 frames
?

2.

The second problem is the format of the config file.
I want to implement a skeleton into my config file but i don't know whether i did it the correct way.
Additionally, i currently using DLC 2.1.6 but i want to switch to 2.2 as soon as the beta ends. 
Does this change the way to write the skeleton in the config file? E.g. because of the new skeleton builder?

Please tell me when this problem has been solved somewhere else!

![Screenshot_2020-06-02_10-19-37](https://user-images.githubusercontent.com/66300664/83497553-ecaf3880-a4ba-11ea-9fe8-df834e3311a7.png)

Thanks for your help!

**Comment by hugofluhr** [comment]
1. numframes2pick refers to the number of frames by video that are in the config file. In your case (`numframes2pick = 150`),  `extract_frames()` will extract 3x150 = 450 frames in total.

2. I am using 2.2 and have defined the skeleton in a similar manner so I imagine that this is the correct way.

**Comment by MMathisLab** [comment]
Th only issue I see is you have spaces in the bodyparts. See the conversion guide here: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/convert_maDLC.md 

Also, we please ask that you post questions on the user forum, vs. github to report code issues, thanks!

https://github.com/DeepLabCut/DeepLabCut#community-support-developers--help
