### ISSUE TITLE
"uniquebodyparts" dropped after "convert2_maDLC"

### ISSUE THREAD

**Issue by alesantuz** [DeepLabCut/DeepLabCut#725]
OS: Windows 10 build 18363
DeepLabCut Version: 2.2b5
Anaconda env used: dlc-windowsGPU

Following [these](https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/functionDetails.md#b-configure-the-project-) and [these](https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/convert_maDLC.md) instructions, I am trying to convert old labels to multianimal. While the "multianimalbodyparts" are correctly saved in the new .h5 file, the "uniquebodyparts" are dropped by the function "convert2_maDLC" (or perhaps the config.yaml is not correctly prepared?).

config.yaml reads as follows:

![image](https://user-images.githubusercontent.com/7524938/83756351-3e002900-a66f-11ea-9f67-283ac4e6cdc6.png)

Calib1 to Calib6 are not present in the new CollectedData[...].h5 file. I went through the code but could not find any issue.

Here a "check_labels" output (the six calibration markers are on the top-left corner of the snapshot):

![img0857_bodypart](https://user-images.githubusercontent.com/7524938/83757323-9683f600-a670-11ea-8247-a83b4587e306.png)

Would you have any hint? Thank you guys!

**Comment by MMathisLab** [comment]
Hi! If you pull from source this behavior is changed, ie unique will stay - we will update to 2.2b6 today (the docs got a little too far ahead; before I said leave unique blank - apologies!)

**Comment by alesantuz** [comment]
Thank you Mackenzie, helpful as usual! Will let you know how it works for me.

**Comment by alesantuz** [comment]
Wonderful, thanks Alex!

**Comment by alesantuz** [comment]
"uniquebodyparts" are not dropped any more with DLC 2.2b6 when converting labels from single-to multianimal. Thank you!
