### ISSUE TITLE
Is there a way to set path in YAML file to load an enviroment variable when sharing amoungst multiple computers.

### ISSUE THREAD

**Issue by suntzuisafterU** [DeepLabCut/DeepLabCut#726]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Your Operating system and DeepLabCut version**
DLC 2.2,
OSX, Windows, various Linux

**Describe the problem**

When sharing a DLC project across many computers, currently we manually edit the paths in the config file.
Is there currently a way built into DLC to avoid having to do this?

**Comment by MMathisLab** [comment]
> When sharing a DLC project across many computers, currently we manually edit the paths in the config file.
Is there currently a way built into DLC to avoid having to do this?

You only need to point to the location of the `config.yaml` file, and it automatically updates the project path. 

https://github.com/DeepLabCut/DeepLabCut/pull/680#pullrequestreview-409597920

Also, to be clear, the only path that ever needs update is just the `project_path` 


also, we would kindly ask that if you have questions, please post on the user forum: https://forum.image.sc/tags/deeplabcut (and gihutb issues for bug reports: https://github.com/DeepLabCut/DeepLabCut#community-support-developers--help thanks!

**Comment by suntzuisafterU** [comment]
So there is no way currently to do this. That is okay.

**Comment by MMathisLab** [comment]
I have no idea what you mean - I outlined you do not need to change ANY path?

**Comment by suntzuisafterU** [comment]
Sorry I misunderstood the implications of the issue you linked.
