### ISSUE TITLE
How to correct marked videos by hand? Import data into ImageJ?

### ISSUE THREAD

**Issue by aleksejs-fomins** [DeepLabCut/DeepLabCut#73]
Dear DeepLabCut,

Due to the nature of our experimental setup, it is inevitable that the observable object (mouse paw) will be partially or fully hidden in some frames, and will occasionally be partially out of focus. Thus, we do not expect that it is possible to mark our current videos with no mistakes at all.

We expect that it might be necessary for the user to look through the marked video, and correct some rare mistakes by hand. I'm sure we are not the first to have this question, but I did not see it on the issues.

**Question**: How to most efficiently correct the output of DeepLabCut by hand? Is there, for example, a script to import the resulting markings if DeepLabCut back into ImageJ for the user to move the points around? Or perhaps there is another tool?

**Comment by MMathisLab** [comment]
One should skip labeling frames they are not confident in labeling the feature - as we describe in the docs, the user should click near the origin of the image, as those points are then dropped. Training with bad labels is detrimental given the low amount of data required.

**Comment by aleksejs-fomins** [comment]
Can you please comment on whether you currently ever do correction of the automatic marking by hand afterwards. If yes, how?

**Comment by MMathisLab** [comment]
Could you email me please? Mathis@rowland.harvard.edu

**Comment by MMathisLab** [comment]
HI @aleksejs-fomins the refinement is now released in the current repo. Check out the refinement GUI and associated steps to automatically detect outliers, or grab them by "hand"
