### ISSUE TITLE
DLC 2.2+ backward compatibility for multianimal labels

### ISSUE THREAD

**Issue by catubc** [DeepLabCut/DeepLabCut#733]
Hi
I have a video analysis project involving hundreds of hours from 4 animals and 4 features each (16 features in total).  These features were labeled a few months ago (pre DLC 2.2) and I have ~2,000 labeled frames.  DLC < 2.2 did very poorly on these videos, and I was told that skeleton information would be used in DLC >=2.2.

I've now installed DLC 2.2.6b and specified the skeleton for pairwise features for each animal in these 2,000 previously labeled frames.  I am now training on this dataset.  However, it is not clear whether DLC 2.2.6b is taking advantage of the skeleton information for each of these 4 animals (which have some unique features including body markings and size: pups vs adults).  

Am I required to re-label all the data using the 2.2.6b multi-animal label tool?  Or does DLC 2.2.6b still use priors for each of these pair-wise features and will incorporate that information automatically.

Any clarification (or documentation link) is appreciated, the labeling took a student a few weeks, and we're trying to avoid redoing it.

**Comment by MMathisLab** [comment]
did you follow the conversion guide first? https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/convert_maDLC.md

**Comment by MMathisLab** [comment]
I would also suggest carefully read over the docs, as they have been significantly updated, and all maDLC points are highlighted: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/UseOverviewGuide.md#important-information-on-using-deeplabcut
