### ISSUE TITLE
Python ValueError when creating training dataset

### ISSUE THREAD

**Issue by Sunderbak** [DeepLabCut/DeepLabCut#734]
Hi! I hope you're well and healthy. Please forgive me as I am very new to DeepLabCut and coding in general. I will try to provide as much information as I can, and will be glad to give you more if needed.

**Ubuntu 16.04.6 LTS, DeepLabCut v2.2b6, with an Anaconda Environment (DLC)**

I created a project to track hand movements of people. After creating the project, I was successfully able to edit the config.yaml to my needs (see below), extract frames (50 total), and label the frames. However, when I went to create the training dataset, I got the following error. Any help is greatly appreciated; I am not understanding where it is getting more than two items from in the config.yaml file. Thank you!

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-39b975463e08> in <module>
----> 1 deeplabcut.create_training_dataset(path_config, augmenter_type='imgaug')

~/anaconda3/envs/dlc/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py in create_training_dataset(config, num_shuffles, Shuffles, windows2linux, userfeedback, trainIndices, testIndices, net_type, augmenter_type)
    899 
    900         Data = merge_annotateddatasets(
--> 901             cfg, Path(os.path.join(project_path, trainingsetfolder)), windows2linux
    902         )
    903         if Data is None:

~/anaconda3/envs/dlc/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py in merge_annotateddatasets(cfg, trainingsetfolder_full, windows2linux)
    591     videos = cfg["video_sets"].keys()
    592     for video in videos:
--> 593         _, filename, _ = _robust_path_split(video)
    594         if cfg.get("croppedtraining", False):
    595             filename += "_cropped"

~/anaconda3/envs/dlc/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py in _robust_path_split(path)
    575     sep = "\\" if "\\" in path else "/"
    576     parent, file = path.rsplit(sep, 1)
--> 577     filename, ext = file.split(".")
    578     return parent, filename, ext
    579 

**ValueError: too many values to unpack (expected 2)**

![119](https://user-images.githubusercontent.com/66268566/84094789-d3c2ed80-a9ba-11ea-9014-e8e3f01487ca.JPG)
![120](https://user-images.githubusercontent.com/66268566/84094790-d45b8400-a9ba-11ea-9a86-37265e38f479.JPG)
![121](https://user-images.githubusercontent.com/66268566/84094792-d45b8400-a9ba-11ea-8cc2-6d5c22e51e6b.JPG)

**Additional context**

**Comment by jeylau** [comment]
Hi @Sunderbak! That's a great catch (and issue report!); we were not handling multiple periods in the video name well. I've just added a fix [https://github.com/DeepLabCut/DeepLabCut/commit/92292b5b0c8b040185b1e8775bcb92c851fee925](url). Feel free to reopen the issue if that does not work for you :-)

**Comment by Sunderbak** [comment]
Hi! Thank you so much for the insight. Unfortunately, this edit did not work; I got the same error message in the same lines (901, 593, and 577) of the trainingsetmanipulation.py. I wonder if I should try different path/file manipulations?

**Comment by Sunderbak** [comment]
Nevermind! I believe it worked; there was a whole separate error contributing to this too. Thanks!
