### ISSUE TITLE
no refresh of text between frames with label_frames?

### ISSUE THREAD

**Issue by EricThomson** [DeepLabCut/DeepLabCut#735]
**Your Operating system and DeepLabCut version**
Windows 10, conda 4.8.2, DLC version 2.1.6.4

**Describe the problem**
When running `label_frames()` in a notebook, after clicking `Next>>`  the text (title, xlabels, and ylabels) does not refresh so I can no longer see what frame I am on as the text all overlaps and becomes jumbled together. I typically zoom when annotating, in case that matters.

Command I use to run `label_frames()`:
```
%gui wx
deeplabcut.label_frames(path_config_file)
```

I am not getting any errors, just not working as expected. 

Here is a screenshot:

<img width="895" alt="dlc_norefresh" src="https://user-images.githubusercontent.com/6643322/84207573-af7d1480-aa7f-11ea-94e8-2b930038dabb.png">

**Comment by MMathisLab** [comment]
If you upgrade to 2.1.8.2 the GUIs have been updated.

**Comment by MMathisLab** [comment]
Hi Eric, my guess it’s it’s something specific to your Jupyter set up; I can confirm on windows10 I don’t get this issue if launch from the terminal or main GUI. 
Ie activate env then type:
`Python -m deeplabcut`

**Comment by EricThomson** [comment]
Yep you are right from within the GUI it looks great -- crisp and clean no issues. This GUI is pretty amazing I think I might port our workflow over to it.
