### ISSUE TITLE
Create training data: KeyError

### ISSUE THREAD

**Issue by catubc** [DeepLabCut/DeepLabCut#739]
Hi

I'm getting an error during the generate training data step with the crop and label data feature. There is no crash when I generate training data without the "Crop and Label Data" feature.

**Desktop (please complete the following information about your system):**
 - OS: Ubuntu
 - DeepLabCut Version: 2.26b

```
In [2]: deeplabcut.launch_dlc()                                                                              
note to user: currently only ResNet50-v1 is available for maDLC
note to user: currently model comparison is not available in maDLC
/home/cat/code/DeepLabCut/deeplabcut/utils/skeleton.py:63: UserWarning: A fully labeled animal could not be found. lefteye, righteye will need to be manually connected in the config.yaml.
  f"A fully labeled animal could not be found. "
/home/cat/code/DeepLabCut/deeplabcut/utils/skeleton.py:135: UserWarning: Unconnected lefteye, righteye. It is desirable that all bodyparts be connected for multi-animal projects.
  f'Unconnected {", ".join(self.bpts[unconnected])}. '
100%|████████████████████████████████████████████████████████████████████████| 50/50 [01:55<00:00,  2.32s/it]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/code/DeepLabCut/deeplabcut/gui/create_training_dataset.py in create_training_dataset(self, event)
    368                 ]
    369                 deeplabcut.cropimagesandlabels(
--> 370                     self.config, n_crops, (height, width), userfeedback
    371                 )
    372             else:

~/code/DeepLabCut/deeplabcut/generate_training_dataset/trainingsetmanipulation.py in cropimagesandlabels(config, numcrops, size, userfeedback, cropdata, excludealreadycropped, updatevideoentries)
    380                 # moving old entry to _original, dropping it from video_set and update crop parameters
    381                 video_orig = sep.join((vidpath, vidname + "." + videotype))
--> 382                 cfg["video_sets_original"][video_orig] = cfg["video_sets"][video_orig]
    383                 cfg["video_sets"].pop(video_orig)
    384                 cfg["video_sets"][video_orig.replace(vidname, new_vidname)] = {

~/anaconda3/envs/DLC-GPU/lib/python3.7/site-packages/ruamel/yaml/comments.py in __getitem__(self, key)
    751         # type: (Any) -> Any
    752         try:
--> 753             return ordereddict.__getitem__(self, key)
    754         except KeyError:
    755             for merged in getattr(self, merge_attrib, []):

KeyError: '/media/cat/4TBSSD/dlc_models/movies/2020-3-8_12:08:57:943006_compressed..avi'

```

**Comment by MMathisLab** [comment]
>  UserWarning: Unconnected lefteye, righteye. It is desirable that all bodyparts be connected for multi-animal projects.

**Comment by MMathisLab** [comment]
> KeyError: '/media/cat/4TBSSD/dlc_models/movies/2020-3-8_12:08:57:943006_compressed..avi'

also does your video really have two . . before `avi` ?

**Comment by catubc** [comment]
Thanks, I did fix the connect parts.

I don't know why there are two . before the file extension.  I noticed them as well, and tried changing the file name to match but it didn't work.

Any other suggestions?

**Comment by MMathisLab** [comment]
the odd file name is going to be the issue; I would remove special characters like `:` and `..`

**Comment by catubc** [comment]
Thanks so the issue is that if I rename the directory to convert the ":" characters to "_" or another simpler character, the labeled data becomes corrupted.  It seems the .h5 files in the /labeled_data directories save the absolute location of the files.  I tried for past few hours to edit and correct the .h5 file so I can save my labeled data - but I couldn't figure it out.  Just to clarify, it seems DLC up to labeling worked ok with the ":" but after that the pipeline broke.

I will start re labeling again with just a few frames to make sure this works - and update this. 

Thanks so much!
