### ISSUE TITLE
What to do if DLC makes mistakes?

### ISSUE THREAD

**Issue by aleksejs-fomins** [DeepLabCut/DeepLabCut#74]
Dear DLC,

We have marked our videos by hand, run DLC, and in some cases DLC makes mistakes. Our idea was to manually extract some of the frames where DLC made a mistake, mark them by hand, and re-train the network including those frames to the training sample. Is this a good strategy? If yes, what steps need to be taken to manually add marked frames to the training sample? As I understood, currently the training frames are selected algorithmically, and their indices are probably stored in some temporary files, right?

**Comment by AlexEMG** [comment]
We have marked our videos by hand, run DLC, and in some cases DLC makes mistakes. Our idea was to manually extract some of the frames where DLC made a mistake, mark them by hand, and re-train the network including those frames to the training sample. Is this a good strategy?

Yes, we think this is a good approach, as we discussed in our paper (https://www.nature.com/articles/s41593-018-0209-y)

 If yes, what steps need to be taken to manually add marked frames to the training sample? As I understood, currently the training frames are selected algorithmically, and their indices are probably stored in some temporary files, right?

Correct, you can at any stage of a project add additional folders with annotated frames and create a new training set. Then you can train your network. You might also want to start from a particular snapshot (to speed up training).


That said, we will release code soon with outlier frame detection heuristics + relabeling GUIs (that allow the user to manually correct rare errors and refine the network). This work is currently under review and there are some beta-testers checking it out.
