### ISSUE TITLE
Kernel dies unexpectedly when importing DeepLabCut-CPU on Windows or Mac

### ISSUE THREAD

**Issue by cd3128** [DeepLabCut/DeepLabCut#744]
My OS:  Anaconda environment Python 3.6 or 3.7

OS: MacOS 10.15.1 (Catalina), MacBook Pro (Retina, 15-inch, Mid 2014) 2.2 GHz Quad-Core Intel Core i7, 16 GB 1600 MHz DDR3. Confirmed on other MacOS Macbook Pros and Windows 10 Laptops

DeeplabCut versions 2.1.6, 2.1.7, 2.1.8, 2.1.9

Anaconda env used: DLC-CPU:
name: DLC-CPU
dependencies:
  - python=3.6 or 3.7
  - pip
  - jupyter
  - nb_conda
  - tensorflow==1.12.0 up to 1.13.x
  - wxpython
  - Shapely
  - pip:
    - deeplabcut==2.1.6 to 2.1.9

**Describe the problem**
When importing DeepLabCut in Jupyter notebook using import deeplabcut, the kernel timesout, then dies, restarting. There are no useful STDOUT error messages when running jupyter notebook --debug:

The following output occurs when import deeplabcut is run:

<details><summary>STDOUT output from jupyter notebook --debug when kernel dies</summary><p>

[D 13:36:26.903 NotebookApp] activity on 0b50f062-539f-413f-b237-ca05e554483f: execute_input
[D 13:36:27.915 NotebookApp] 304 GET /static/base/images/favicon-busy-1.ico (::1) 0.96ms
[D 13:36:39.104 NotebookApp] activity on 0b50f062-539f-413f-b237-ca05e554483f: status (idle)
[I 13:36:41.942 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel 0b50f062-539f-413f-b237-ca05e554483f restarted
[D 13:36:41.943 NotebookApp] Starting kernel: ['/Users/chris/opt/anaconda3/envs/DLC-CPU/bin/python', '-m', 'ipykernel_launcher', '-f', '/Users/chris/Library/Jupyter/runtime/kernel-0b50f062-539f-413f-b237-ca05e554483f.json']
[D 13:36:41.946 NotebookApp] Connecting to: tcp://127.0.0.1:60934
[D 13:36:44.955 NotebookApp] KernelRestarter: restart apparently succeeded

</p></details>

**How to Reproduce the problem**
1. Install DeepLabCut-CPU with conda env create -f DLC-CPU.yaml 
2. Launch a Jupyter notebook
3. execute cell with import deeplabcut

**Additional context**
We tried DLC-CPU this on other Macbook pros, Windows 10 Laptops, and the same kernel dies in those environments as well with the most recent .yaml easy installs.

**Comment by MMathisLab** [comment]
Hi @cd3128 its' true that DLC is not supported in Jupyter Notebooks in MacOS, see here: https://github.com/DeepLabCut/DeepLabCut/blob/9928ce90d68f22571f760d14f9751bcbdbc8f39a/docs/UseOverviewGuide.md#option-1-demo-notebooks

>We provide Jupyter and COLAB notebooks for using DeepLabCut on both a pre-labeled dataset, and on the end user’s own dataset. See all the demo's here! Please note that GUIs are not easily supported in Jupyter in MacOS, as you need a framework build of python. While it's possible to launch them with a few tweaks, we recommend using the Project Manager GUI or terminal, so please follow the instructions below.

But it is working for me on Windows: see this file here (which is different that what you posted above as the latest DLC-CPU env:

```python
name: DLC-CPU
dependencies:
  - python=3.7
  - pip
  - jupyter
  - nb_conda
  - tensorflow==1.13.1
  - wxpython<4.1.0
  - pip:
    - deeplabcut
```

ps - to add, 2.1.9 does not exist yet ;) but you could try [deeplabcutcore](https://github.com/DeepLabCut/DeepLabCut-core) -> ``pip install deeplabcutcore`` which has no GUI dependencies and would load okay.

Otherwise, we recommend using the terminal or the Project Manager GUI, which was upgrade a lot with 2.2.
