### ISSUE TITLE
Suggestions for improvement of DLC multi-animal tracking 

### ISSUE THREAD

**Issue by catubc** [DeepLabCut/DeepLabCut#747]
Hi
Our lab managed to train DLC 2.26b on a 50 labeled frame dataset (1024 x 1280 images).  The frames contain 4 animals of slightly different sizes and each animal was uniquely labeled in each frame with unique identifiers as they had markers on their back.

[EDIT]: I should mention that we only trained this NN for 2500 iterations.

1.  The Analyze Video step took about 13 minutes (on a Titan XP 12GB) to process a 15second recording (25FPS).  That seemed very slow, and we're wondering if there are any suggestions for speeding this step up.  

2.  The results for a 15sec video are below.  The results shows promise, and we're excited about the possibility of improving this.  There are many dropouts (frames without labels) as well as animal ID switching even between 2 sequential frames.  If there are any obvious errors we made, we would appreciate any input.

Thanks so much!

https://drive.google.com/file/d/1Ox9SbKcYyW2jAfhfqDL1Mfgl_nI9mvFp/view?usp=sharing

**Comment by MMathisLab** [comment]
please see: https://github.com/DeepLabCut/DeepLabCut#community-support-developers--help

**Comment by LJ-lab** [comment]
I would re-open this as a bug. ´

There seems to be quite a few people having difficulties in getting good tracking out of maDLC. I wonder if anyone has had good tracking results after the convert to tracklets / refine tracklets stages on multi-animal projects.

I have posted about this issue on image.sc forum, but on a improvement suggestion thread: 
https://forum.image.sc/t/multi-animal-refining-training-workflow-suggestions/40338/13

**Comment by MMathisLab** [comment]
Yes, we get good tracking and our alpha testers did. I think people aren’t following instructions clearly, not using evaluation metrics properly, and expecting it to just work without any input; maDLC is more complex, requires good decisions at every step, and before our paper is out it’s not production ready.... it’s not a bug.

**Comment by catubc** [comment]
FYI: From our end, we've re-run maDLC since June 12th (posting above) and trained on 50k iterations and it does do better than posted above. Dropouts and animal ID switching still occur and we're writing post-maDLC tools to fix tracklets using statistical approaches.  There's also room for improvement using maDLC parameter which we haven't fully explored. But overall, for our project 1hr recordings we don't expect DLC to perform perfectly. 

However, we also don't think this is a bug, as maDLC provides a good ground on which to build further analyses/tools.

**Comment by LJ-lab** [comment]
DLC is great, don't get me wrong. I wouldn't expect maDLC to run out of the box, and also understand that there are multiple knobs to turn. But would you be able to provide users with some guidance which knobs to turn and in which direction. We have spent countless hours changing every parameter (and combination of parameters) in every direction in the inference_cfg file and never got good tracking output. (we have also tried evaluating the network for different targets and cross-validade from there, but without any improvement in tracking results). What else can we try? Any help would be sincerely appreciated.
