### ISSUE TITLE
Network taking a long time to train

### ISSUE THREAD

**Issue by alisonsin** [DeepLabCut/DeepLabCut#749]
Hello! I have had my network trained for a few days now (using the GUI). There are progress being made at each time, however, it has been a very long time (a week!), and it is still iterating. Therefore, I would like to ask if this is normal or is there something that I did wrong?  Thank you! :)

**Comment by MMathisLab** [comment]
HI @alisonsin welcome to the DLC community. We ask that user questions go on the forum, see here: https://github.com/DeepLabCut/DeepLabCut#community-support-developers--help

https://forum.image.sc/tags/deeplabcut

but to answer, it sounds like you are using a CPU, not a GPU. whereas a GPU takes ~6 -10 hours, a CPU will take 6-10 days. We highly recommend using a GPU, and indeed you can move your project to google drive and use COLAB to train for free, search COLAB and you will find many docs, videos, and notebooks to do this with.

ps - if you find DLC helpful, please consider giving us a "star" on github, thanks!

**Comment by alisonsin** [comment]
@MMathisLab ok thank u!
