### ISSUE TITLE
Issues Filtering, Labeling Videos, and Learning

### ISSUE THREAD

**Issue by BKTidswell** [DeepLabCut/DeepLabCut#754]
OS: OS X 10.15.4
DeepLabCut Version: 2.2b5
Anaconda env used: DLC-CPU

**Describe the problem**

I am having issues running multiple commands with the new MA Deeplabcut. 
After training and then refining a video with refine_tracklets to create an .h5 file I ran a few subsequent commands to filter the data, create a labeled video, as well as refine the network.

When I run
`deeplabcut.filterpredictions(config_path,['/Users/Ben/Desktop/DLC_Tracking_2/Multi_Vids-Ben-2020-06-03/videos/N_LLine_A_1_Trimmed.mp4'])`
it returns
`No unfiltered data file found in /Users/Ben/Desktop/DLC_Tracking_2/Multi_Vids-Ben-2020-06-03/videos for video N_LLine_A_1_Trimmed and scorer DLC_resnet50_Multi_VidsJun3shuffle1_3000.` 

When I run
`deeplabcut.create_labeled_video(config_path, ['/Users/Ben/Desktop/DLC_Tracking_2/Multi_Vids-Ben-2020-06-03/videos/N_LLine_A_1_Trimmed.mp4'],track_method='skeleton', draw_skeleton = True)`
It creates the video with labeled points, however the points are the original ones, and not the refined ones that I fixed with refine_tracklets. 
It also returns
`No unfiltered data file found in /Users/Ben/Desktop/DLC_Tracking_2/Multi_Vids-Ben-2020-06-03/videos for video N_LLine_A_1_Trimmed and scorer DLC_resnet50_Multi_VidsJun3shuffle1_3000.`
If the track method is not skeleton. 

When I run
`deeplabcut.extract_outlier_frames(config_path,['/Users/Ben/Desktop/DLC_Tracking_2/Multi_Vids-Ben-2020-06-03/videos/N_LLine_A_1_Trimmed.mp4'])`
it returns
`It seems the video has not been analyzed yet, or the video is not found! You can only refine the labels after the a video is analyzed. Please run 'analyze_video' first. Or, please double check your video file path`
The video has already been analyzed and does exist.

Finally, running
`deeplabcut.refine_labels(config_path)`
Does open up a dialog, however there is not a machinelabels.h5 file in the labeled-data folder. 

I am still getting used to MA Deeplabcut, and was wondering if these are working as expected currently. I am hoping to be able to retrain the network with my refined videos. If there is a way to do that with the current setup I would appreciate knowing. Thank you for your work.

**Comment by MMathisLab** [comment]
My guess it most all are just errors in formatting. Double check the maDLC COLAB notebook for formatting: https://github.com/DeepLabCut/DeepLabCut/blob/master/examples/COLAB_maDLC_TrainNetwork_VideoAnalysis.ipynb

i.e., for example:

> deeplabcut.filterpredictions(config_path,['/Users/Ben/Desktop/DLC_Tracking_2/Multi_Vids-Ben-2020-06-03/videos/N_LLine_A_1_Trimmed.mp4'])

You need to pass the `videotype='mp4' ` (avi is default)
```
deeplabcut.filterpredictions(path_config_file, 
                                 videofile_path, 
                                 videotype=VideoType, 
                                 track_method = tracktype)
```
also roll up to 2.2b6 ;)

**Comment by BKTidswell** [comment]
Thank you for your response. I apologize for the confusion, I am up to date with 2.b6, I just wrote in the wrong version by accident. However, even with the formatting the problem still seems to persist.

**For Filtering**
Running this based on the COLAB Notebook:
`deeplabcut.filterpredictions(config_path,
'/Users/Ben/Desktop/DLC_Tracking_2/Multi_Vids-Ben-2020-06-03/videos/N_LLine_A_1_Trimmed.mp4',
videotype=".mp4",
track_method = "box")`
Still returns this error:
`No unfiltered data file found in /Users/Ben/Desktop/DLC_Tracking_2/Multi_Vids-Ben-2020-06-03/videos for video N_LLine_A_1_Trimmed and scorer DLC_resnet50_Multi_VidsJun3shuffle1_3000 and box tracker.`

**For Creating Videos**
Running this:
`deeplabcut.create_labeled_video(config_path,
                                '/Users/Ben/Desktop/DLC_Tracking_2/Multi_Vids-Ben-2020-06-03/videos/N_LLine_A_1_Trimmed.mp4', 
                                shuffle=1, 
                                draw_skeleton=True, 
                                videotype=".mp4", 
                                save_frames=False,
				filtered=False,
                                track_method ="box")`
Returns this:
`No unfiltered data file found in /Users/Ben/Desktop/DLC_Tracking_2/Multi_Vids-Ben-2020-06-03/videos for video N_LLine_A_1_Trimmed and scorer DLC_resnet50_Multi_VidsJun3shuffle1_3000 and box tracker.`

Running it with ` track_method ="skeleton"` does create a video, but again not with the most updated .h5 file.

**Comment by MMathisLab** [comment]
Can you post the list of files in the directory that accompany your video after you run analyze videos and convert to tracklets?

**Comment by BKTidswell** [comment]
Currently I have:
N_LLine_A_1_Trimmed.mp4
N_LLine_A_1_TrimmedDLC_resnet50_Multi_VidsJun3shuffle1_3000_full.pickle
N_LLine_A_1_TrimmedDLC_resnet50_Multi_VidsJun3shuffle1_3000_meta.pickle
N_LLine_A_1_TrimmedDLC_resnet50_Multi_VidsJun3shuffle1_3000_sk_bp_labeled.mp4

There is also the folder N_LLine_A_1_Trimmed which contains a PNG of each frame

**Comment by MMathisLab** [comment]
Then the error message is correct; you have no ... bx.pickle (which is loaded into refine tracklets step), and when you wave in gui you get a bx.h5...

**Comment by MMathisLab** [comment]
Did you run “convert2trackelts” and use the refinement GUI?

**Comment by BKTidswell** [comment]
Sorry, I don't know why I missed copying and pasting them, but I do also have:
N_LLine_A_1_TrimmedDLC_resnet50_Multi_VidsJun3shuffle1_3000_sk.h5
N_LLine_A_1_TrimmedDLC_resnet50_Multi_VidsJun3shuffle1_3000_sk.pickle

I ran deeplabcut.convert_detections2tracklets. That created N_LLine_C_1_TrimmedDLC_resnet50_Multi_VidsJun3shuffle1_3000_sk.pickle for me. 

I then ran:
deeplabcut.refine_tracklets(config_path, '/Users/Ben/Desktop/DLC_Tracking_2/Multi_Vids-Ben-2020-06-03/videos/N_LLine_A_1_TrimmedDLC_resnet50_Multi_VidsJun3shuffle1_3000_sk.pickle', '/Users/Ben/Desktop/DLC_Tracking_2/Multi_Vids-Ben-2020-06-03/videos/N_LLine_A_1_Trimmed.mp4', min_swap_frac=0.0, min_tracklet_frac=0.0, trail_len=50)

That created N_LLine_A_1_TrimmedDLC_resnet50_Multi_VidsJun3shuffle1_3000_sk.h5, which I can load in using the refinement GUI to see my refined points.

**Comment by MMathisLab** [comment]
> deeplabcut.filterpredictions(config_path, '/Users/Ben/Desktop/DLC_Tracking_2/Multi_Vids-Ben-2020-06-03/videos/N_LLine_A_1_Trimmed.mp4', videotype=".mp4", track_method = "box")

should be: see `video_path` in COLAB has [ ]

`deeplabcut.filterpredictions(config_path, ['/Users/Ben/Desktop/DLC_Tracking_2/Multi_Vids-Ben-2020-06-03/videos/N_LLine_A_1_Trimmed.mp4'], videotype='mp4', shuffe=1, track_method = 'skeleton')`

^ also you sometimes say `box` but you don't have a bx.h5 file, per what you posted above..

**Comment by BKTidswell** [comment]
Ok, so that fixed the filtering.

What seemed to be happening with the videos was that even after I adjusted the points manually, the likelihood was still kept the same, which meant that points that had been off target and were manually corrected were not plotted on the video. In order to plot all of the points I reduced the `pcutoff` in the config.yaml.

The issue with `deeplabcut.extract_outlier_frames` seemed to be similar to `deeplabcut.filterpredictions` in that I was missing the `videotype='mp4', shuffe=1, track_method = 'skeleton'` arguments.

Thank you for helping me with this. I really appreciate you taking the time to help me correct my errors.

**Comment by MMathisLab** [comment]
No problem. 

Yes, so one thing to keep on mind is that the tracklets GUI shows everything, even low conf points, we are considering changing this so people don’t think the tracking is “bad” ie there will always be low conf points, ie a part is hidden or occluded. So, maybe I can make this more clear in the tracklets GUI, ie maybe low conf points can be toggled on and off, I think this could be helpful for people to get a better intuition of the tracking anyhow. If you have feed back for us on this, let me know.


Also cc @jeylau

Right now you could also create a video of all detections before even converting to tracklets, to be sure the pose estimation quality is high - a crucial step :).
