### ISSUE TITLE
Clear videos from log (Project Manager GUI)

### ISSUE THREAD

**Issue by catubc** [DeepLabCut/DeepLabCut#759]
Hi
Is there a way that we can clear the videos from the list of videos in the log.  Otherwise, every time I run Analyze Video it reruns all the previously completed videos.

Here's the button I'm referring to.

https://drive.google.com/file/d/1fpVE4eRh9w6gtFU-qoSv01x0szZwwQx9/view?usp=sharing

**Comment by AlexEMG** [comment]
Well, I guess it should not rerun them, but realize that they were analyzed and then skip. Does that happen? But "clear list" in the GUI would be a good feature.

**Comment by MMathisLab** [comment]
you can click "reset" and the videos are cleared. You can either (1) load the config.yaml again, or (2) go to manage project and click "load" to load config file again rapidly, but then videos are cleared.

**Comment by catubc** [comment]
I'm not sure where the "reset" button is in the latest GUI.

But yes, reloading the entire project did work!

Thanks.
