### ISSUE TITLE
Performance on CPU vs GPU

### ISSUE THREAD

**Issue by aleksejs-fomins** [DeepLabCut/DeepLabCut#76]
Dear DLC,

You have mentioned in the docs that GPU is ~100 times faster than CPU for the purposes of running DLC. Is it possible to elaborate a bit on this point? For example, how would 32 core CPU compare to 1 GPU? Or 1 GPU vs 4 GPU. Do you maybe have strong/weak scaling plots? Would be cool to add them to the wiki if you have them

**Comment by AlexEMG** [comment]
We plan to release some benchmarking for CPU vs GPU. I have not benchmarked multi-CPU use, but but my understanding is that multi CPU use does not scale, as one expects naively (and only mildly improves performance for ResNets, see table 7 in [Benchmarking State-of-the-Art Deep Learning Software Tools](https://arxiv.org/pdf/1608.07249.pdf)). I would recommend single GPUs.

**Comment by AlexEMG** [comment]
Dear @aleksejs-fomins 

We ran quite a lot of benchmarking to illustrate the speed of [DeepLabCut] (https://www.biorxiv.org/content/early/2018/10/30/457242) on CPUs, GPUs etc. Hope this is helpful!
