### ISSUE TITLE
userfeedback=False for extract_outlier_frames?

### ISSUE THREAD

**Issue by tbenst** [DeepLabCut/DeepLabCut#760]
When extracting outlier frames for a lot of videos, hitting `y` for each prompt is laborious. It'd be great to have a `userfeedback=False` option for `extract_outlier_frames`, just like `extract_frames`

**Comment by AlexEMG** [comment]
Great idea, want to do a PR? ;)

**Comment by tbenst** [comment]
found a simple bash solution ;).

```bash
yes | python -c 'import deeplabcut as dlc; dlc.extract_outlier_frames("/data/d
eeplabcut_projects/open-field-2020-06-10/config.yaml", ["/data/deeplabcut_projects/open-field--2020-06-10/videos/myvid.MPG"])'
```
