### ISSUE TITLE
Installation check failed GPU Windows10

### ISSUE THREAD

**Issue by neurologic** [DeepLabCut/DeepLabCut#761]
Thank you for all of the detailed instructions on the installation process. I tried to methodically followed all of the steps, and I read the linked docs for version compatability, but one of the first tests of success has already failed. I know that there are a lot of versions and parameters so it might be difficult for you to help. But I am new to using many of these components so I may have just misunderstood something in all of the documentation that you provided and I am hoping my issue is apparent to you.

OS: Windows10
GPU: Quadro P4000 8GB
DeepLabCut Version: 2.1.8.2 (the version that came with the DLC-GPU environment, though I will ultimately be using the multianimal tracking versions once I get the basics working.**
Anaconda env used: created using DLC-GPU.yaml

All of the install GUIs completed successfully (driver, CUDA, VS2017)
My build has failed the following error check that was suggested:
```
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
```
Here is the output of that command (in ipython after importing tensorflow):
<details><summary>Code output</summary><p>

```python
[In [2]: tf.Session(config=tf.ConfigProto(log_device_placement=True))
2020-06-20 14:08:29.820950: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2020-06-20 14:08:30.246933: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: Quadro P4000 major: 6 minor: 1 memoryClockRate(GHz): 1.48
pciBusID: 0000:65:00.0
totalMemory: 8.00GiB freeMemory: 6.65GiB
2020-06-20 14:08:30.252835: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
<ipython-input-2-45efb92717fc> in <module>
----> 1 tf.Session(config=tf.ConfigProto(log_device_placement=True))

~\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py in __init__(self, target, graph, config)
   1549
   1550     """
-> 1551     super(Session, self).__init__(target, graph, config=config)
   1552     # NOTE(mrry): Create these on first `__enter__` to avoid a reference cycle.
   1553     self._default_graph_context_manager = None

~\Anaconda3\envs\DLC-GPU\lib\site-packages\tensorflow\python\client\session.py in __init__(self, target, graph, config)
    674     try:
    675       # pylint: disable=protected-access
--> 676       self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
    677       # pylint: enable=protected-access
    678     finally:

InternalError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version
]
```

</p></details>

**The following are the steps that I took to install on my new computer**
1. Installed most recent Anaconda with python 3.7 64bit (I have done this before and am very familiar using python, etc)
2. Downloaded and Installed an NVIDIA driver that is compatible with my GPU and with CUDA 9.1: 
Quadro Driver 390 -- R390 U13 392.59; Windows10 64 bit standard.
Install was via the .exe GUI
https://www.nvidia.com/Download/driverResults.aspx/157261/en-us
3. Downloaded and attempted to install CUDA 9.1:
CUDA 9.1.85_Win10 (+the three patches)
https://developer.nvidia.com/cuda-91-download-archive?
Install was via the .exe GUItarget_os=Windows&target_arch=x86_64&target_version=10&target_type=exelocal
**The GUI install stalled and gave feedback that no visual studio was installed and asked me to install it.
4. I quit the CUDA install GUI
5. Downloaded and installed Visual studio 2017 Community.
From googling, I found numerous threads naming compatibility between CUDA 9.1 and VS2017 community. However, there was also lots of information that CuDA9.1 specifically needed VS 2017 15.4.5 and that this was no longer available. I could not find it and decided to try whichever VS2017 I could get.
Install of VS via GUI but WITHOUT workstation packages.
6. Tried CUDA install GUI again. This time is succeeded to completion.
7. Installed and created the conda environment from DLC-GPU.yaml

Phew....
I think that is all of the steps laid out in the instructions and sub-linked instructions.

I then went on in the instructions to check the CUDA and tensorflow installation:
ipython
import tensorflow as tf
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

This failed (the error output is posted above in this message where I stated my problem).

I did dig a little bit through the troubleshooting links so far and as per this site (https://www.pytorials.com/install-tensorflow-gpu-windows/) I tried nvcc --version to check if CUDAtoolkit is set to path.
Code Output was successful:
<details><summary>Code output</summary><p>

[C:\Users\kperks>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:08:12_Central_Daylight_Time_2017
Cuda compilation tools, release 9.1, V9.1.85]
]

</p></details>
I also downloaded and installed cuDNN 7.0.5 as per the extract/copy instructions on that page 

The tensorflow check in ipython still fails in the same way. 

I feel very stuck and this is the first time I am working with GPU computing so do not have a lot of background to contextualize the troubleshooting. 
Any help/advice would be deeply appreciated. 

Thank you again for all your work on DLC! I am really excited to implement it in my research.

-Krista

**Comment by neurologic** [comment]
Could an issue be that CUDA 9.1 needs tensorflow<1.12 (https://www.tensorflow.org/install/source_windows#tested_build_configurations) but the tensorflow version in DLC-GPU env is 1.13.1?

**Comment by neurologic** [comment]
I uninstalled Visual Studio 2017 and all of the CUDA installations as per this resource and am now trying the steps outlined here:
https://www.pytorials.com/how-to-install-tensorflow-gpu-with-cuda-10-0-for-python-on-windows/

**Comment by neurologic** [comment]
Ok. I think I got somewhere! 
Using a combination of the following two resources you linked in the troubleshooting section and have not uninstalled my original VisualStudio 2017 and CUDA packages and have installed Visual Studio 2015 and CUDA10.0 (as per the instructions in the linked page, this CUDA installation automatically installed the relevant driver for the GPU apparently):
https://www.pytorials.com/how-to-install-tensorflow-gpu-with-cuda-10-0-for-python-on-windows/
and
http://blog.nitishmutha.com/tensorflow/2017/01/22/TensorFlow-with-gpu-for-windows.html


The output of 
```
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
```
within the DLC-GPU environment is now:
<details><summary>Code output</summary><p>

```python
[(DLC-GPU) PS C:\Users\kperks> python
Python 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
2020-06-20 19:30:03.038997: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2020-06-20 19:30:03.077769: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2020-06-20 19:30:03.093473: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:161] retrieving CUDA diagnostic information for host: DESKTOP-JLLU9JK
2020-06-20 19:30:03.099162: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:168] hostname: DESKTOP-JLLU9JK
Device mapping: no known devices.
2020-06-20 19:30:03.107158: I tensorflow/core/common_runtime/direct_session.cc:317] Device mapping:
] 
```

</p></details>

I guess I jumped the gun on asking for help on that install process, but I was feeling pretty defeated. I will see what questions/stumbling blocks I come across next.

Thank you for your patience and assistance in getting this working in my hands.

**Comment by MMathisLab** [comment]
what happens when you run 
`nvidia-smi` in the terminal?

I don't have a lot of experience with GPU and windows. I agree it sounds like you can just use tf 1.8 (can edit the yaml file) and you would be fine with the original configuration! otherwise, here is my general cuda install advice beyond what you found (and got very far!): https://github.com/DeepLabCut/Docker4DeepLabCut2.0/wiki/Installation-of-NVIDIA-driver-and-CUDA-10

**Comment by neurologic** [comment]
Hmmm. 
``` nvidia-smi ``` was not recognized in the Command Prompt, Conda powershell, nor conda powershell inside DLC-GPU.
Does this need to be added to my PATH variable in order for DLC functions to operate correctly?
After editing PATH variable, ```nvidia-smi``` command outputs the following:
<details><summary>NVIDIA-SMI OUTPUT</summary><p>
[Microsoft Windows [Version 10.0.18363.900]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\kperks>nvidia-smi
Sun Jun 21 13:29:24 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 442.50       Driver Version: 442.50       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P4000       WDDM  | 00000000:65:00.0  On |                  N/A |
| 46%   31C    P8     6W / 105W |    461MiB /  8192MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1316    C+G   Insufficient Permissions                   N/A      |
|    0      5000    C+G   ...osoft.LockApp_cw5n1h2txyewy\LockApp.exe N/A      |
|    0      5944    C+G   C:\Windows\explorer.exe                    N/A      |
|    0      6356    C+G   ...dows.Cortana_cw5n1h2txyewy\SearchUI.exe N/A      |
|    0      6988    C+G   ...6.102.0_x64__kzf8qxf38zg5c\SkypeApp.exe N/A      |
|    0      7064    C+G   ....148.0_x64__8wekyb3d8bbwe\YourPhone.exe N/A      |
|    0      7088    C+G   ...hell.Experiences.TextInput.InputApp.exe N/A      |
|    0      7284    C+G   ...dows.Cortana_cw5n1h2txyewy\SearchUI.exe N/A      |
|    0      8032    C+G   ...6)\Google\Chrome\Application\chrome.exe N/A      |
|    0      9128    C+G   ...x64__8wekyb3d8bbwe\Microsoft.Photos.exe N/A      |
|    0      9600    C+G   ...mmersiveControlPanel\SystemSettings.exe N/A      |
|    0      9828    C+G   ...oftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe N/A      |
+-----------------------------------------------------------------------------+]
</p></details>

***IT SAYS CUDA 10.2 even though I explicitly downloaded and installed 10.0***
This will be a DLC compatibility issue, correct?

Thank you for that extra Linux doc that you made. I hadn't come across that yet. In the near future I will be setting up a dual boot on this computer anyway so the Linux advice will be useful when I get that going. (In the meantime I figured it would be useful to get it working on the native Windows since the OS came with the computer anyway and it might be handy in case students wanted to get going working on it with me who did not have any Linux experience.)

**QUESTION*:* in that document I notice that one of the steps specifies CUDA 10.1:
```
wget http://developer.download.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.243_418.87.00_linux.run
sudo sh cuda_10.1.243_418.87.00_linux.run
```
I thought that CUDA10.1+ was unsupported?
