### ISSUE TITLE
Labelling issue: impossible to check the labels.

### ISSUE THREAD

**Issue by DorianBattivelli** [DeepLabCut/DeepLabCut#766]
Hello, 

I am using DLC 2.2.b6 with anaconda, on windows 10.

I used GUI until the labeling, saved all the labeled frame, but I cannot neither "check Labels individuals" nor "check labels". It systematically generate the error message : 
![Untitled](https://user-images.githubusercontent.com/66886884/85304688-51532700-b4ac-11ea-9ce9-e59cc3e01291.png)

The most surprising point is that when I click "build skeleton", the building is perfect, and automatically generated. 

FYI: in my labeled-data folder, no new folder with my labeled data has been created.

Would you have some suggestion to help me fixing that issue?

Thank you, 
best, 
Dorian

**Comment by jeylau** [comment]
Hello @DorianBattivelli, could you please post your config.yaml here?

**Comment by DorianBattivelli** [comment]
Here it is (yalm and text file format are not supported here, so I took 3 screenshots):

![1](https://user-images.githubusercontent.com/66886884/85318364-2541a100-b4c0-11ea-9d62-db4efe232afc.png)
![2](https://user-images.githubusercontent.com/66886884/85318370-28d52800-b4c0-11ea-9dcf-c68894c28925.png)
![3](https://user-images.githubusercontent.com/66886884/85318375-2a9eeb80-b4c0-11ea-911b-f6fb8d7b6d5d.png)

Thank you for the help, 
Dorian

**Comment by jeylau** [comment]
I just spotted it! Just fix the line with the single keypoint and you are good to go :)
<img width="329" alt="snapshot" src="https://user-images.githubusercontent.com/30733203/85320068-d0ebf080-b4c2-11ea-81b4-10dddb87bbba.png">

**Comment by DorianBattivelli** [comment]
Awesome, it works! You are my hero, 
Thank you very much
Dorian
