### ISSUE TITLE
UnboundLocalError: local variable 'cfg' referenced before assignment

### ISSUE THREAD

**Issue by Alyetama** [DeepLabCut/DeepLabCut#767]
> No, you add the path **without** the ending; as it loads multiple files, so you just point it to a snapshot: 
> i.e.  ``init_weights: /fullpathtothisfolder/ProjectFolder/dlc-models/iteration-0/train/snapshot-20000``
> Here is an updated graphic for important **pose_config.yaml** file settings:
> ![image](https://user-images.githubusercontent.com/28102185/51443998-8e1b5d00-1cbf-11e9-8614-be3b2745e4a5.png)

_Originally posted by @MMathisLab in https://github.com/DeepLabCut/DeepLabCut/issues/180#issuecomment-455894913_

I reproduced these instructions to load a training snapshot, but I got this error:

```
In [10]: deeplabcut.train_network(path_config_file, shuffle=1, saveiters=1000, d
    ...: isplayiters=10)
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-10-65221a812201> in <module>
----> 1 deeplabcut.train_network(path_config_file, shuffle=1, saveiters=1000, displayiters=10)

~/.conda/envs/DLC-GPU/lib/python3.6/site-packages/deeplabcut/pose_estimation_tensorflow/training.py in train_network(config, shuffle, trainingsetindex, max_snapshots_to_keep, displayiters, saveiters, maxiters, allow_growth, gputouse, autotune, keepdeconvweights, modelprefix)
    136
    137     # Read file path for pose_config file. >> pass it on
--> 138     cfg = auxiliaryfunctions.read_config(config)
    139     modelfoldername = auxiliaryfunctions.GetModelFolder(
    140         cfg["TrainingFraction"][trainingsetindex], shuffle, cfg, modelprefix=modelprefix

~/.conda/envs/DLC-GPU/lib/python3.6/site-packages/deeplabcut/utils/auxiliaryfunctions.py in read_config(configname)
    188             "Config file is not found. Please make sure that the file exists and/or that you passed the path of the config file correctly!"
    189         )
--> 190     return cfg
    191
    192

UnboundLocalError: local variable 'cfg' referenced before assignment
```

**Version:** 2.2b6
*Also tested on: `2.1.8.2` and DeepLabCutCore's latest version.*

**Steps to reproduce:**
- Open `.../project/dlc-models/iteration-0/1angleJun21-trainset95shuffle1/train/pose_cfg.yaml`
- Edit `init_weights:` to add the snapshot (e.g., `.../project/dlc-models/iteration-0/project-trainset95shuffle1/train/snapshot-125000`)
- Run ` deeplabcut.train_network(path_config_file, shuffle=1, saveiters=1000, displayiters=10)`

**Comment by MMathisLab** [comment]
> UnboundLocalError: local variable 'cfg' referenced before assignment


This means there is a typo introduced into the config file.

**Comment by Alyetama** [comment]
> > UnboundLocalError: local variable 'cfg' referenced before assignment
> 
> This means there is a typo introduced into the config file.

Yes, it seems like that was actually the problem.  Thank you!
