### ISSUE TITLE
CollectedData_user.h5 does not exist

### ISSUE THREAD

**Issue by ajclaros** [DeepLabCut/DeepLabCut#768]
Hi

I'm getting an error when using the GUI,
I'm running Ubuntu 19.10 & DeepLabCut 2.2b6 through Anaconda Env file

**Describe the problem**

After selecting the .yaml and Label Frames tab. Clicking on the "Build Skeleton" or "Label Frames" button produces the following output:

<details><summary>Code output</summary><p>

FileNotFoundError                         Traceback (most recent call last)
/home/username/Documents/DeepLabCut/deeplabcut/gui/label_frames.py in build_skeleton(self, event)
    141
    142     def build_skeleton(self, event):
--> 143         skeleton.SkeletonBuilder(self.config)
    144
    145     def select_config(self, event):

/home/username/Documents/DeepLabCut/deeplabcut/utils/skeleton.py in __init__(self, config_path)
     51                 break
     52         self.df = pd.read_hdf(
---> 53             os.path.join(folder, f'CollectedData_{self.cfg["scorer"]}.h5')
     54         )
     55         # Handle data previously annotated on a different platform

/usr/local/lib/python3.7/dist-packages/pandas/io/pytables.py in read_hdf(path_or_buf, key, mode, errors, where, start, stop, columns, iterator, chunksize, **kwargs)
    393
    394         if not exists:
--> 395             raise FileNotFoundError(f"File {path_or_buf} does not exist")
    396
    397         store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)

FileNotFoundError: File /home/username/Documents/DeepLabCut/fish01-user-2020-06-24/labeled-data/fishT/CollectedData_user.h5 does not exist

</p></details>

**Comment by jeylau** [comment]
Hi @ajclaros, make sure you click on Label Frames first (that is, when you first land on that tab) before attempting to build the skeleton :)
