### ISSUE TITLE
How to analyze videos in different locations?

### ISSUE THREAD

**Issue by aleksejs-fomins** [DeepLabCut/DeepLabCut#77]
Dear DLC,

We would like to set up an experiment to run many video tracking in the coming few weeks. The current structure of DLC is to put results directly into git repository. I assume it would change in the pip version. Question is: do we set up our analysis pipeline based on current version of DLC, or wait for the pip version?

**Comment by AlexEMG** [comment]
Once trained, you can analyze data in any folder you fancy. The videos can be in arbitrary directories on your computer (or mounted network drives) and the results are stored there. 

To reiterate, the results are not put into your local DLC folder. You can obviously change the video folder (```videofolder = 'CoolLocation/Myawesomeexperimentalvideos1/December24/'``` in ```myconfig_analysis.py```) and the result files (```h5 files```) are then stored, where the videos are. 

However, you could most certainly also change, where the h5 are stored by editing lines 122: 
```
dataname = video.split('.')[0] + scorer + '.h5'
```
in 
https://github.com/AlexEMG/DeepLabCut/blob/master/Analysis-tools/AnalyzeVideos.py

While the pip installable package has many advantages (including GUIs etc.), already with this version you can analyze data at lots of locations.
