### ISSUE TITLE
Still not able to analyze data related to #711 and #713

### ISSUE THREAD

**Issue by barefood** [DeepLabCut/DeepLabCut#772]
OS: Windows 10
DeepLabCut Version: DeepLabCut2.2b6
Anaconda env used: DLC-GPU or DLCC-CPU

Hello,
I still can't analyze any videos with DeepLabCut2. because of an ffprobe error. I tried the solutions suggested in #711 and #713 (I am not using COLAB) but I still get the same error:

![grafik](https://user-images.githubusercontent.com/67417382/85712943-21449780-b6e9-11ea-8c3c-daed4a658df1.png)

Steps to reproduce the behavior in the GUI:
1. Go to 'Analyze videos'
2. Set video type to mp4 and Run with Default Options
3.  See error

![grafik](https://user-images.githubusercontent.com/67417382/85713430-a62fb100-b6e9-11ea-9907-34a442324a02.png)

**Comment by jeylau** [comment]
Hi @barefood, could you please retry _not_ using OpenCV to read the video? The video total number of frames will be evaluated differently, but that should not be a problem in most cases. Let us know if that helps! 😃

**Comment by barefood** [comment]
Unfortunately it doesn't. I get the exact same output.

**Comment by jeylau** [comment]
Let us try without the GUI then. Do you get the same error with the following command?
`deeplabcut.analyze_videos('N:\DeepLabCut\skeleton_test-hje-2020-06-15\config.yaml', ['N:\DeepLabCut\skeleton_test-hje-2020-06-15\videos\MVI_0249.mp4'], 'mp4')`

**Comment by barefood** [comment]
Yes, I get the same error. It is independent of the GUI and occurs also independently of CPU/GPU. 
after modifying to:
deeplabcut.analyze_videos('N:\\DeepLabCut\\skeleton_test-hje-2020-06-15\\config.yaml', ['N:\\DeepLabCut\\skeleton_test-hje-2020-06-15\\videos\\MVI_0249.mp4'], 'mp4')

**Comment by jeylau** [comment]
Alright, it still failed because getting video duration happens to also rely on ffprobe. I will push a fix in a couple of minutes :)

**Comment by MMathisLab** [comment]
you need to pass:

`deeplabcut.analyze_videos(r'N:\DeepLabCut\skeleton_test-hje-2020-06-15\config.yaml', [r'N:\DeepLabCut\skeleton_test-hje-2020-06-15\videos\MVI_0249.mp4'], videotype='mp4')`

i.e you dropped videotype, and it's formatted incorrectly for Windows. That is why you get the ffmprobe error, i.e. it's a formatting issue. 

and be sure ffmpeg is installed ;)

**Comment by barefood** [comment]
I do get the same error even with the corrected command.
I also checked: imageio-ffmpeg version 0.4.1 is installed in anaconda.

**Comment by jeylau** [comment]
If you open the command prompt and type `ffmpeg -version`, what is the output?

**Comment by barefood** [comment]
Hello,
you were right, ffmpeg wasn't installed. Now, after installing it properly and including it into the windows user environment I can run the analysis. I didn't know I had to do an independent installation apart from deeplabcut/anaconda itself. 

Thank you for your help!

**Comment by jeylau** [comment]
Awesome! Perhaps you could submit a PR to update the docs with the installation procedure you followed :) I'm sure that would help a lot of Windows users!

**Comment by or-naim** [comment]
Had the same issue and installing ffmpeg finally solved it. Many thanks!

Additionally, I thought it would be helpful to notate that it took me a while to realize how exactly to download it as @barefood mentioned. For python and anaconda users like me, just use this simple line: "conda install -c conda-forge ffmpeg", a time saver.
