### ISSUE TITLE
Unable to convert raw tracks to h5

### ISSUE THREAD

**Issue by Xiaoyu-Tong** [DeepLabCut/DeepLabCut#775]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

_I was using Google Colab to analyze videos after trained my own model. I was using the code provided by your maDLC Jupyter notebook ( have tried both DLC 2.2b5 and 2.2b6. Neither of them worked)_

Please complete the following information about your system:

OS: [e.g. MacOS, Windows 10, etc]
DeepLabCut Version: [e.g. 2.2] (please check with import deeplabcut, deeplabcut.__version__)
Anaconda env used:
_N/A_

**Describe the problem**

A clear and concise description of what the problem is.

I could not convert raw tracks to h5 using the Jupyter notebook you provided. After done training my own maDLC model, I tried to analyze an example video. First, I ran deeplabcut.analyze_videos, which gave me 2 pickle files and nothing else (no h5/csv files). Pickles were meta.pickle and full.pickle. I could generate videos with all detections using deeplabcut.create_video_with_all_detections. But then when I tried to generate videos with identities, the function deeplabcut.convert_raw_tracks_to_h5 failed with an error message of KeyError: 'header'.

Please place code inside this:

This is the Jupyter notebook I was using: https://colab.research.google.com/drive/1omLcDLjn49f61Xs5R3_bubNcnypj9kCw#scrollTo=a6izVWX8sdzL

[Please copy/paste the full terminal output of the error here!!!]

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-3acda52a2051> in <module>()
      4 vid ='/content/drive/My Drive/2BM Videos/190912-FMfor2BM_8524_72040.mp4'
      5 
----> 6 deeplabcut.convert_raw_tracks_to_h5(path_config_file, picklefile)
      7 #deeplabcut.filterpredictions(path_config_file,
      8 #                                 videofile_path,

2 frames
/usr/local/lib/python3.6/dist-packages/deeplabcut/refine_training_dataset/tracklets.py in convert_raw_tracks_to_h5(config, tracks_pickle, output_name)
   1071 def convert_raw_tracks_to_h5(config, tracks_pickle, output_name=""):
   1072     manager = TrackletManager(config, 0, 0)
-> 1073     manager.load_tracklets_from_pickle(tracks_pickle)
   1074     manager.save(output_name)

/usr/local/lib/python3.6/dist-packages/deeplabcut/refine_training_dataset/tracklets.py in load_tracklets_from_pickle(self, filename, auto_fill)
    330         with open(filename, "rb") as file:
    331             tracklets = pickle.load(file)
--> 332         self._load_tracklets(tracklets, auto_fill)
    333         self._xy = self.xy.copy()
    334 

/usr/local/lib/python3.6/dist-packages/deeplabcut/refine_training_dataset/tracklets.py in _load_tracklets(self, tracklets, auto_fill)
    171 
    172     def _load_tracklets(self, tracklets, auto_fill):
--> 173         header = tracklets.pop("header")
    174         self.scorer = header.get_level_values("scorer").unique().to_list()
    175         frames = sorted(

KeyError: 'header'

**How to Reproduce the problem**
1. Go to maDLC COLAB Jupyter notebook.
2. Run deeplabcut.analyze_videos, create_video_with_all_detections, deeplabcut.convert_detections2tracklets (these 3 functions worked)
3. Run deeplabcut.convert_raw_tracks_to_h5

**Screenshots**

**Additional context**
Please let me know if you need more information! I suspect this issue is relevant to DLC version. It is also possible that this issue comes from some unexpected error before training process.

**Comment by jeylau** [comment]
Hello @Xiaoyu-Tong, you are likely selecting the _full.pickle instead of the _bx or _sk.pickle file. Please take a look here for more details https://forum.image.sc/t/multianimalproject-key-error-header/39343/4!

**Comment by Xiaoyu-Tong** [comment]
Hi Jeylau, thank you for your reply. I have tried to select _sk.pickle instead. The previous error has been solved, but the Colab session always crashed when I ran deeplabcut.convert_raw_tracks_to_h5. There was no output message from the cell I was running, rather, a pop-up window from Colab said my session crashed after using all RAMs. I am attaching the runtime log it showed me for your reference. Thank you for your help in advance!
![image](https://user-images.githubusercontent.com/55998514/86304937-63d10d00-bbde-11ea-8378-61d8c15425e3.png)

**Comment by Xiaoyu-Tong** [comment]
Hi, @jeylau, in case you are not notified. Do you have any idea about the issue I just commented? Thank you!

**Comment by jeylau** [comment]
Hey @Xiaoyu-Tong, that is odd. Could you try it locally? It is a very fast step, and if you happen to need to refine the tracklets, at least you will be able to use the GUI.

**Comment by Xiaoyu-Tong** [comment]
@jeylau Thanks for the reply! I have tried it. And it took forever to run convert_raw_tracks_to_h5 and there was no output message at all. Seems to be the same issue as the one on Colab. I suspect that something is wrong with the sk.pickle file. Is it possible that you take a look at the sk.pickle file I am using to see if there is something unexpected happening?

**Comment by Xiaoyu-Tong** [comment]
For your reference, here is the error message I got when I manually interrupted the process after hours.
![image](https://user-images.githubusercontent.com/55998514/86392569-a8ee5100-bc69-11ea-9e38-816081321a13.png)

**Comment by PolarBean** [comment]
I am having the same issue, convert_raw_tracks uses a ton of ram and takes hours. I am using the bx.pickle file. for reference my videos are 45 minutes long and recorded at 90fps so the bx_pickles are often over 100MB and the full_pickles are over 1GB
