### ISSUE TITLE
DLC Windows not saving data: "AttributeError: "StatusBar" object has not attribute "set_function"

### ISSUE THREAD

**Issue by catubc** [DeepLabCut/DeepLabCut#780]
Hi

I've installed DLC2.2b6 on Windows and it seems that the data is not being saved.  In particular, I can label a bunch of features and they appear on the screen, and are present if I scroll back and forth over new frames, but after saving they cannot be reloaded.   I was not having this issue in linux with DLC2.2b6

Also, it seems that with the Label frames GUI open, there is a constant error being printed, not sure if these are related.

https://drive.google.com/file/d/1x6JVsAtSwS0ErBC67RXyiLHPuQ5hZoIm/view?usp=sharing

**Comment by MMathisLab** [comment]
seems the wrong version of wxPython, it must be `  wxpython<4.1.0` and likely related: https://github.com/DeepLabCut/DeepLabCut/issues/682

**Comment by catubc** [comment]
Ok, I spent a lot of time on this lol, but  the issue was matplotlib 3.2.2 was not installed.  Thanks again!

**Comment by MMathisLab** [comment]
no worries!
