### ISSUE TITLE
KeyError: 'header'

### ISSUE THREAD

**Issue by neuropsycher** [DeepLabCut/DeepLabCut#782]
Anaconda env, Google colab, Deeplabcut 2.26b
OS: Windows 10

Hello, I have come across a 'header' error after trying to refine tracklets. I cannot seem to run this part correctly. I attached a file to show my error.

**Edit:** After attempting more times, I found another error after setting my paths for 'refine_tracklets.' This is a OSerror: HD5 error back trace. The other concern I had was on setting the correct path for 'pickle_or_h5_file', as I have three different pickle files that were in my videos folder (full, meta, and bx). 

Thank you so much for the time and help! 

![header error](https://user-images.githubusercontent.com/64938386/86507658-98d88d80-bd9f-11ea-9519-dca2ee1971df.PNG)
![new error](https://user-images.githubusercontent.com/64938386/86517750-fb0dae80-bdf0-11ea-95ac-d789653f3c5e.PNG)

**Comment by Alyetama** [comment]
This might help: [MultiAnimalProject, key error: header](https://forum.image.sc/t/multianimalproject-key-error-header/39343).
