### ISSUE TITLE
[Inquiry] Best video compression?

### ISSUE THREAD

**Issue by ghost** [DeepLabCut/DeepLabCut#784]
Hello,

I know that "best" is a relative term, but I understand that some video compressions are more "optimal" than others.  Could you recommend a video compression (with its ffmpeg command, if possible) to use? I would really appreciate it! Thank you!

**Comment by AlexEMG** [comment]
I think I would suggest H.264, as it is broadly available with highly optimized implementations across platforms. You can play it everywhere and it looks "nice" for good compression rates. Check this out, plus the references mentioned in there: https://www.biorxiv.org/content/10.1101/457242v1.full
