### ISSUE TITLE
IndexError when using multi-animal DLC_TrainNetwork_VideoAnalysis

### ISSUE THREAD

**Issue by Hydraulic343** [DeepLabCut/DeepLabCut#788]
I am using the DeepLabCut 2.2 Toolbox - COLAB to run a multi-animal analysis. It can be accessed from this link:

https://colab.research.google.com/github/MMathisLab/DeepLabCut/blob/master/examples/COLAB_maDLC_TrainNetwork_VideoAnalysis.ipynb#scrollTo=xNi9s1dboEJN

I keep running into this error when I try to run it.

_IndexError: index 0 is out of bounds for axis 0 with size 0_

I specifically get this error when I run this code at the step where I run the "Create a multi-animal training dataset" step

_deeplabcut.cropimagesandlabels(path_config_file, size=(400, 400), userfeedback=False)

#if you labeled on Windows, please set the windows2linux=True:
deeplabcut.create_multianimaltraining_dataset(path_config_file, windows2linux=True)_

I am not very familiar with Python or coding in general, but I am trying to figure out what is causing this error.

  0%|          | 0/20 [00:00<?, ?it/s]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-5-29b016bd3374> in <module>()
      
      1 deeplabcut.cropimagesandlabels(path_config_file, size=(400, 400), userfeedback=False)
      2 
      3 #if you labeled on Windows, please set the windows2linux=True:
      4 deeplabcut.create_multianimaltraining_dataset(path_config_file, windows2linux=True)

/usr/local/lib/python3.6/dist-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py in cropimagesandlabels(config, numcrops, size, userfeedback, cropdata, excludealreadycropped, updatevideoentries)

    333                 frame = ic[i]
    334                 imagename = os.path.relpath(ic.files[i], cfg["project_path"])
    335                 ind = np.flatnonzero(df.index == imagename)[0]
    336                 h, w = np.shape(frame)[:2]
    337                 cropindex = 0

IndexError: index 0 is out of bounds for axis 0 with size 0

Please let me know if anyone else has encountered this error or what is causing it. Let me know if you need more information.

**Comment by MMathisLab** [comment]
Please fill out the template.

**Comment by jeylau** [comment]
Hi @Hydraulic343, could you please tell us if you face the same issue with DLC 2.2b6? I think this is something that got fixed with #715.

**Comment by jeylau** [comment]
Any news @Hydraulic343?
