### ISSUE TITLE
Avoiding the tracklet refinement GUI

### ISSUE THREAD

**Issue by xneven** [DeepLabCut/DeepLabCut#790]
**Your Operating system and DeepLabCut version**

OS: Ubuntu 20.04 LTS
DeepLabCut Version: 2.2b6 multianimal
Anaconda env used: DLC-CPU

**Describe the problem**

Following on from issue #778 I am trying to generate the .h5 tracklet files from .pickle files without using the tracklet refinement GUI due to RAM constraints. As advised, I tried using the deeplabcut.convert_raw_tracks_to_h5() function to circumvent the GUI after optimising inference parameters on a shorter video, however, that still leads to a memory crash:

<details><summary>Code output</summary><p>

MemoryError                               Traceback (most recent call last)

in

      1 for pickle_file in pickles:

      2     print(pickle_file)

----> 3     dlc.convert_raw_tracks_to_h5(config_path, pickle_file)

      4

~\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\refine_training_dataset\tracklets.py in convert_raw_tracks_to_h5(config, tracks_pickle, output_name)

   1071 def convert_raw_tracks_to_h5(config, tracks_pickle, output_name=""):

   1072     manager = TrackletManager(config, 0, 0)

-> 1073     manager.load_tracklets_from_pickle(tracks_pickle)

   1074     manager.save(output_name)

~\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\refine_training_dataset\tracklets.py in load_tracklets_from_pickle(self, filename, auto_fill)

    330         with open(filename, "rb") as file:

    331             tracklets = pickle.load(file)

--> 332         self._load_tracklets(tracklets, auto_fill)

    333         self._xy = self.xy.copy()

    334

~\anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\refine_training_dataset\tracklets.py in _load_tracklets(self, tracklets, auto_fill)

    205                 is_single = np.isnan(to_fill[:, mask_multi]).all()

    206                 if is_single:

--> 207                     to_fill = to_fill[:, mask_single]

    208                 else:

    209                     to_fill = to_fill[:, mask_multi]

MemoryError:

</p></details>

Is this expected behaviour and if so, is there another way to generate tracklet files without downsampling and reanalysing the videos.

**Additional context**
Tracklet files are up to 30MB big.

**Comment by MMathisLab** [comment]
I am working on this issue here: https://github.com/DeepLabCut/DeepLabCut/issues/778--, I would ask that you please don't open new issues when one of the dev-core are working on it :)

**Comment by MMathisLab** [comment]
resolved: https://github.com/DeepLabCut/DeepLabCut/issues/778#issuecomment-655704552
