### ISSUE TITLE
Pick up training from were you left

### ISSUE THREAD

**Issue by ghost** [DeepLabCut/DeepLabCut#794]
It's not clear to me how to resume training a dataset that was once closed.  Could you please explain the process?

**Comment by MMathisLab** [comment]
We kindly ask that you reserve github for code issues, and ask questions on the user forum: https://github.com/DeepLabCut/DeepLabCut#community-support-developers--help

How to reload snapshots is described in Box2 of the Nature Protocols paper, and in the detailed functions document here on hithub. 

![bx2](https://user-images.githubusercontent.com/28102185/87117260-18ee6f80-c246-11ea-8155-112dbb7d4fb7.png)
