### ISSUE TITLE
docker wrong docker image build -t dlc_username/dlcdocker .

### ISSUE THREAD

**Issue by liqier** [DeepLabCut/DeepLabCut#796]
When I create the Docker Environment for DeepLabCut2.0+
According to readme.md，run:docker image build -t dlc_username/dlcdocker .
![2020-07-10 16-12-36屏幕截图](https://user-images.githubusercontent.com/55725190/87146515-a0d38880-c2dd-11ea-8259-bf25bcd885e7.png)
Can you tell me how to fix it?
Thank you!

**Comment by MMathisLab** [comment]
Please post issues related to another code base, i.e., on the Docker4DeepLabCut2.0 repo: https://github.com/DeepLabCut/Docker4DeepLabCut2.0
