### ISSUE TITLE
Issue with step 6 training network on CPU

### ISSUE THREAD

**Issue by ChengYu0921** [DeepLabCut/DeepLabCut#80]
**Describe the problem**
Hi, I recently started learning and using DeepLabCut and I am trying to run through the demo. I got through Step (5) smoothly, however, in step (6), when I try to train the network by entering: 
$ TF_CUDNN_USE_AUTOTUNE=0 CUDA_VISIBLE_DEVICES=0 python3.6 ../../../train.py
and I got the following error:
'TF_CUDNN_USE_AUTOTUNE' is not recognized as an internal or external command, operable program or batch file.
I installed TensorFLow and then DeepLabCut under Windows 10 system via "simplified installation with conda environments for a CPU". I'm not sure what is going wrong (I am a beginner with python), so any suggestion would be helpful. Thanks.

**Comment by MMathisLab** [comment]
Hi, from the demo guide, on Windows you don’t type in TF_CUDNN.... See here: https://github.com/AlexEMG/DeepLabCut/blob/master/docs/demo-guide.md “ If you are running the code on a CPU you can ommit that command (also in step 7).” - so also don’t type it into the terminal in step 7. :)
