### ISSUE TITLE
How to get the skeleton picture？

### ISSUE THREAD

**Issue by liqier** [DeepLabCut/DeepLabCut#803]
By reading the paper _Using DeepLabCut for 3D markerless poseestimation across species and behaviors_
For our own project, how to obtain the skeleton picture shown in Figure 7.d in the paper：
![image](https://user-images.githubusercontent.com/55725190/87265909-80324b00-c4f6-11ea-80d8-a1304410621e.png)
Looking forward to your reply！
Thank you!

**Comment by MMathisLab** [comment]
you can connect the skeleton in the config.yaml file, then analyze the video; you can customize any plots, etc. Here are tools to do so: https://github.com/DeepLabCut/DLCutils/blob/master/Demo_loadandanalyzeDLCdata.ipynb and the Cheetah project is here: https://github.com/MMathisLab/3D-DeepLabCut-Cheetah

We also please ask you don't post questions here, please reserve github for code issues; we have a user forum for questions: https://forum.image.sc/tags/deeplabcut
