### ISSUE TITLE
-results.csv not created after running deeplabcut.evaluate_network

### ISSUE THREAD

**Issue by CarmenWinters** [DeepLabCut/DeepLabCut#807]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

Window 10 professional, with an Anaconda Env, DeepLabCut 2.2b6 & COLAB_maDLC

When I run deeplabcut.evaluate_network(path_config_file,Shuffles=[1], plotting=True) in COLAB_maDLC, the results are not stored (neither as .h5, nor .csv) in a subdirectory under evaluation-results. I do not get an error code,... If I re-run this step I even get that a .h5 file already exists, but is not in the folder. 

Running  DLC_resnet50_MultiMouse_MaternalPreference_RestrictedJul10shuffle1_13000  with # of trainingiterations: 13000
Initializing ResNet
Activating extracting of PAFs
0it [00:00, ?it/s]Analyzing data...
396it [01:14,  5.30it/s]
Done and results stored for snapshot:  snapshot-13000

</p></details>

**How to Reproduce the problem**

**Comment by jeylau** [comment]
@CarmenWinters, do you face the same problem if setting `plotting=False`? Also, have you checked only the file tree in Colab or in your Drive? Sometimes, it takes a bit before newly-written files show up.

**Comment by CarmenWinters** [comment]
> Also, have you checked only the file tree in Colab or in your Drive? Sometimes, it takes a bit before newly-written files show up.

Yes, I changed these settings and tried a few times over. 
I just checked the evaluate_multianimal.py code and the evaluate.py file, in neither one of those I can find the following code.
 ]
    df = pd.DataFrame(final_result, columns=col_names)
    output_path = os.path.join(str(evaluationfolder), DLCscorer + "-results.csv")
    if os.path.exists(output_path):
        temp = pd.read_csv(output_path, index_col=0)
        df = pd.concat((df, temp)).reset_index(drop=True)

    df.to_csv(output_path)
    # df.to_hdf(output_path.replace('csv', 'h5'), 'df_with_missing', format='table', mode='w')

Could it be possible that this is preventing it from writing it away?

**Comment by jeylau** [comment]
@CarmenWinters, I just remembered that related issue #707. You do get evaluation results after running the cross-validation. There is also #716 that should be merged soon, and will include a more comprehensive error report :)

**Comment by CarmenWinters** [comment]
> uld be merged soon

I'm sorry but I am somewhat confused now. 
So I ran the x-validation as well now. I get an .h5-file, json-file and 2 .pickle-files, but still no results.csv-file. 
Is that normal?

**Comment by jeylau** [comment]
Train–test errors must have been printed in the console; and you'll also find them in inference_cfg.h5 and inference_cfg.csv in the folder dlc-models/iteration-0/.../test.

**Comment by CarmenWinters** [comment]
I see! 
I now have a slightly different problem: I made a model but I suspect one of my labeled bodyparts (tail_base) is predicted worse than my others. Now, I do not necessarily need that bodypart for the output I want (just added it to have a more stable tracking). 
Therefore I tried to evaluate the 'all bodyparst comparison' to separate bodypart comparison in Colab, but I have no idea which code that actually requires. I now tried the following, but my results keep being the same.

#%matplotlib notebook
#let's evaluate first:
deeplabcut.evaluate_network(path_config_file,Shuffles=[shuffle],plotting=False,show_errors=True,c_engine=False, comparisonbodyparts=['Tail_base'])
#plot a few scoremaps:
deeplabcut.extract_save_all_maps(path_config_file, shuffle=shuffle, Indices=[0])

#and begin to cross-validate:
deeplabcut.evaluate_multianimal_crossvalidate(
            path_config_file,
            Shuffles=[shuffle],
            edgewisecondition=True,
            leastbpts=1,
            init_points=20,
            n_iter=50,
            target='rpck_train',
        )

**Comment by CarmenWinters** [comment]
> Train–test errors must have been printed in the console; and you'll also find them in inference_cfg.h5 and inference_cfg.csv in the folder dlc-models/iteration-0/.../test.

I see!
I now have a slightly different problem: I made a model but I suspect one of my labeled bodyparts (tail_base) is predicted worse than my others. Now, I do not necessarily need that bodypart for the output I want (just added it to have a more stable tracking).
Therefore I tried to evaluate the 'all bodyparst comparison' to separate bodypart comparison in Colab, but I have no idea which code that actually requires. I now tried the following, but my results keep being the same.

#%matplotlib notebook
#let's evaluate first:
deeplabcut.evaluate_network(path_config_file,Shuffles=[shuffle],plotting=False,show_errors=True,c_engine=False, comparisonbodyparts=['Tail_base'])
#plot a few scoremaps:
deeplabcut.extract_save_all_maps(path_config_file, shuffle=shuffle, Indices=[0])

#and begin to cross-validate:
deeplabcut.evaluate_multianimal_crossvalidate(
path_config_file,
Shuffles=[shuffle],
edgewisecondition=True,
leastbpts=1,
init_points=20,
n_iter=50,
target='rpck_train',
)

**Comment by jeylau** [comment]
`comparisonbodyparts` is currently only taken into consideration when plotting (with DLC2.2). Animal- and bodypart-wise results will come soon with #716 😃

**Comment by CarmenWinters** [comment]
> `comparisonbodyparts` is currently only taken into consideration when plotting. Animal- and bodypart-wise results will come soon with #716 😃

Oh, I am so happy I asked now :D Would have taken me a very long time

**Comment by jeylau** [comment]
No problem! 😄
