### ISSUE TITLE
Name error in google colab training dataset 

### ISSUE THREAD

**Issue by ayah1126** [DeepLabCut/DeepLabCut#809]
Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: MacOS
DeepLabCut Version: 2.1.8.2
Anaconda env used: 3

I am trying to begin training the dataset for DLC in my google drive. The folder is already uploaded and I am really new to this so please help. I am not sure how to explain the problem but I have attached a screenshot. 

![Screen Shot 2020-07-18 at 3 54 18 AM](https://user-images.githubusercontent.com/68462324/87849096-7704fd80-c8ab-11ea-8e61-16838cbd3d6d.png)

**Comment by backyardbiomech** [comment]
Hi, @ayah1126 
There is a cell higher up in the Colab notebook that defines `path_config_file`. You need to make sure you edit that cell as described, and run it. And if you left Colab and came back, you need to re-run the top cells.
