### ISSUE TITLE
dropping uniquebodyparts at refine tracklets step

### ISSUE THREAD

**Issue by blogeman** [DeepLabCut/DeepLabCut#811]
OS: Windows 10
DeepLabCut Version: 2.2b7
Anaconda env used: DLC-GPU

I'm using the GUI and working on a multi-animal project in which there are 2 indistinguishable animals and 1 animal that can be distinguished (similar to the sheepdog herding sheep example mentioned in the docs). In the config file, the 2 indistinguishable animals are are labeled with "multianimalbodyparts" and the single animal is labeled with "uniquebodyparts". Everything is working well though the "Analyze videos" tab. When I click the radio button "create video for checking detections" and analyze video I get the output that I am expecting. Namely, both the multi-animal points and the unique points are visible in the video.

The problem begins after I convert to tracklets and move onto the Refine tracklets tab. When launching the GUI, it only shows multianimal points and I can never again see the unique points. I've tried tinkering around with some of the options, but have become stuck. 

Why are the uniquebodyparts disappearing?

Thanks.

**Comment by jeylau** [comment]
Hi @blogeman, could you please re-try by specifying 0 as the min relative tracklet length in the GUI? If that does not help, I would encourage you to have a look at `create_video_from_pickled_tracks`, which creates a video after the detections were assembled into animals and helps assess tracking quality :)

**Comment by blogeman** [comment]
Setting the min relative tracklet length to 0 did the trick. Thanks @jeylau !
