### ISSUE TITLE
Unable to automatically extract frames

### ISSUE THREAD

**Issue by SophiePinder** [DeepLabCut/DeepLabCut#813]
Hi, 

I'm using the below code to extract frames

In [10]: deeplabcut.extract_frames(config_path,'automatic','kmeans',crop=False, userfeedback=True)                                                    
Config file read successfully.
Do you want to extract (perhaps additional) frames for video: /lustre/ahome3/s/scp27/BM-sophie-2020-07-19/videos/NHAA22.mp4 ?
yes/no

I type yes and when I go to the labeled-data file there are no selected frames. I'm able to select frames manually, but I would prefer the frames to be selected automatically. Can anyone suggest what might be going wrong?

Many Thanks, 

Sophie

**Comment by jeylau** [comment]
Hi @SophiePinder, after typing 'yes', was there something written in the console? Or a red progress bar?

**Comment by MMathisLab** [comment]
@SophiePinder please fill out the template as requested.

**Comment by MMathisLab** [comment]
closed due to inactivity (and not clear how to reproduce said issue)
