### ISSUE TITLE
Colab RAM Overload when Analyzing Large Video Files in a Multi-Animal Project

### ISSUE THREAD

**Issue by LucasBoldrini** [DeepLabCut/DeepLabCut#814]
OS: Windows 7
DeepLabCut Version: 2.2b5

Greetings, DLC community! I have an issue when trying to analyze a two-animal project 2h videos on Google Colab. It's RAM overloads when converting the analysis to pickle files, regardless of video file format and number of videos analyzed simultaneously (it crashes when converting the pickle files for the first video). I was able to solve it by splitting the videos into several 15 min videos, but it is very time consuming and I have many videos to work with. I understand this is not a DLC issue but a Colab one, however I'm not based in the US so I can't sign up for a pro license. My available machines have less RAM than Colab so it's impractical to run the analysis on DLC's GUI. Do you have any suggestions on how to proceed?

Thank you in advance!

Best,

Lucas Boldrini.

**Comment by jeylau** [comment]
Hello @LucasBoldrini, that is a ton of data you have here! 😄 To be sure I get you right: does it crash when analyzing the video or when converting the detections to tracklets?
Splitting the videos is smart. I do not know how you specifically did it, but a simple loop using `deeplabcut.ShortenVideo()` and then passing a list of the newly created files to `analyze_videos` should not be that tedious. Let me know if that helps :)

**Comment by LucasBoldrini** [comment]
Thanks for the reply, @jeylau! It crashes when running the command to analyze the video (right in the end when the analysis is already done but the data is being converted to a pickle file).

I split the videos using FFmpeg prior to using them on DLC.

**Comment by jeylau** [comment]
A guess is that your video is truly too large, and trying to dump that much data causes the crash :/
Take a look at that function, it should make it easier to analyze your large video: [https://github.com/DeepLabCut/DeepLabCut/blob/10f5057ede4ea4e18a91e1731a14a3af5a8c026a/deeplabcut/utils/auxfun_videos.py#L233](url)
You could use it as follows:
`clips = split_video(path_of_your_large_video, n_splits=10)`
`deeplabcut.analyze_videos(config, clips, 'mp4')`

**Comment by AlexEMG** [comment]
Please also try out the bleeding edge, or see this PR: https://github.com/DeepLabCut/DeepLabCut/pull/826
