### ISSUE TITLE
extract w/cropping twice the same video (and labeling in-between) is not supported

### ISSUE THREAD

**Issue by JoeH92** [DeepLabCut/DeepLabCut#816]
**Describe the bug**

After run deeplabcut.check_labels, annotations in  some of the output images are not on  the positions where I have annotated in label_frame step. 

**Desktop (please complete the following information about your system):**
 - OS: Windows10
 - DeepLabCut Version : 2.2b7
 - Browser: chrome

**Comment by jeylau** [comment]
Hi @JoeH92, could you upload a couple of screenshots to illustrate the issue? Are the images cropped?

**Comment by MMathisLab** [comment]
@JoeH92 can you also re-load them into the labeling GUI to confirm you think it's the plotting, i.e. the data is correct?please fill out the template as requested.

**Comment by JoeH92** [comment]
> Hi @jeylau @MMathisLab 

I find  the reason for the problem, which is the cropped coordinates are inconsistent. The 'crop  coordinates' in config.yaml is not correct for each labelled image.

**Comment by MMathisLab** [comment]
Hi @JoeH92 thanks! I can't reproduce the issue, i.e. when I crop the coordinates are updated correctly in my config.yaml. Note there are two places the coordinates are saved; original at the bottom of the config file, and as "cropped"; did you edit the values by hand by chance?

**Comment by JoeH92** [comment]
> Hi @MMathisLab, I'll create a new project to check whether the issue is due to human error.

**Comment by JoeH92** [comment]
> Hi @MMathisLab, I extracted 20 cropped frames(crop coords:119,1084,196,714) from video_A(1280x720) . Then, I extracted another 2 cropped frames(crop coords:25,1225,160,712) from  video_A. The crop coordinates in config.yaml were updated to (25,1225,160,712) from (119,1084,196,714). Next I labelled the 22 frames and run check_labels. When I checked the check_labels outputs folder, I found that the later 2 frames  I extracted from video_A which size was 965x518 rather than 1200x552, and the annotations on them were not  the positions where I had labelled in label_frame step. So I wonder if a video can only be cropped once ?

**Comment by MMathisLab** [comment]
Hi @JoeH92 can you run `pip install --upgrade matplotlib` and see if this is the same?

**Comment by MMathisLab** [comment]
Awe, I see you edited you comment; yes, you can only crop once per video, as the coordinates are stored per video file, not per frame, so that is the issue!
