### ISSUE TITLE
ResourceExhaustedError

### ISSUE THREAD

**Issue by liqier** [DeepLabCut/DeepLabCut#817]
**MY Operating system and DeepLabCut version**
OS:  Windows 10
DeepLabCut Version: 2.1.4
Anaconda env used:4.8.0

**Describe the problem**
When I run the code:
>> deeplabcut.analyze_videos(config_path,[‘Full path of video or videofolder’], shuffle=1, save_as_csv=True, videotype=‘.avi’)
error as followes:
![image](https://user-images.githubusercontent.com/55725190/88031007-8ff10580-cb6e-11ea-8e36-a984457ea0ab.png)

At first I thought it was not enough memory, but there is still 8.8GB available through Task Manager, so how can I solve this problem?
Thank you very much!

**Comment by jeylau** [comment]
Hey @liqier, being a MacOS user I'm not too familiar with the Task Manager; is that the GPU memory still available? Does nvidia-smi return the same value?

**Comment by AlexEMG** [comment]
You are using a ResNet101, for large images that can easily require more than 8GB in memory...
