### ISSUE TITLE
Issue using Lasso to swap label IDs on DLC 2.2b7

### ISSUE THREAD

**Issue by LJ-lab** [DeepLabCut/DeepLabCut#819]
Using Lasso to select a number of labels and then clicking on another animal's ID name to swap the ID of the labels has apparentely stopped working on version 2.2b7 (on windows). I can lasso the labels but when I click on the other animal's ID the ID of the labels does not change.

It was working fine on all previous versions.

**Comment by jeylau** [comment]
Fixed here https://github.com/DeepLabCut/DeepLabCut/commit/d2ce225c8be31c8da0cc449c72b58a389cddfb47!
