### ISSUE TITLE
Frame correspondence issue with Handbrake

### ISSUE THREAD

**Issue by alexcwsmith** [DeepLabCut/DeepLabCut#820]
**Ubuntu 18.04, DLC 2.1.8.2 installed via pip**

I recorded .mp4 videos in on a GoPro Hero3 at 30FPS (original size 1920x1080), then used Handbrake (installed via sudo apt install handbrake) to crop and downsample to 798x354 @ 15 FPS. I prefer handbrake to ffmpeg simply because the Handbrake gui and queue makes it very nice and easy to crop videos in batches with specific crop coordinates for each video.

After training a model for 300K iterations and analyzing videos, the dlc.extract_outlier_frames function detects 50%-75% of frames as outliers (using all default parameters for extract_outlier_frames). When I run refine_labels, the labels appear to be relatively close to correct, but possibly in the location where the mouse was one frame previously, so I am wondering if this could be an issue of frame correspondence.

<img width="1149" alt="Screen Shot 2020-07-22 at 9 29 42 AM" src="https://user-images.githubusercontent.com/47009665/88185211-ab592080-cc01-11ea-8d62-d0a38d0583b6.png">

DLC is accurately detecting the frame rate, so it isn't an issue similar to #475, though the screenshot posted [here](https://github.com/DeepLabCut/DeepLabCut/issues/475#issuecomment-549157610) looks somewhat similar, with more offset.

I am now downsampling all of my videos without changing the frame rate, to see if that changes the results, but I am hoping one of you can share insight on why this may be happening, and if this may indeed be a frame shift, or if I just need to create better training data and label more frames or run for more iterations.

**Comment by jeylau** [comment]
Hey @alexcwsmith, the default extraction method identifies frames where at least a bodypart jumps over 20 pixels from a frame to the other; given your relatively wide video, this is likely too low to be truly indicative of a frame requiring refinement. That being said, this does not explain the shift 🤔 I tried to reproduce it on 2 raw videos, and could not reproduce it. Do you face the issue on the untouched video file too?

**Comment by alexcwsmith** [comment]
It looks like it is an issue with downsampling from 30 FPS to 15, as the issue doesn't occur with videos maintained at 30FPS. I have a feeling that it is an issue with Handbrake re-encoding the cropped/downsampled video files, it is probably dropping a frame or two somewhere, rather than an issue with DLC.
