### ISSUE TITLE
Error with Extracting Frames (DLC 2.2b6)

### ISSUE THREAD

**Issue by davidfslab** [DeepLabCut/DeepLabCut#821]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Information**
Windows 10, with an Anaconda Env, & DeepLabCut 2.2b6

**Describe the problem**
- importing DLC, opening GUI, and creating new project works fine.
- when attempting to extract frames from the GUI, and after  typing "yes", an error pops up saying "Frame extraction failed. Video files must be corrupted."
- upon checking the video in my files however, the video loads and plays just fine.

Please place code inside this:
(I also added a screenshot below, under **Screenshots** > 2)

<details><summary>Code output</summary><p>

[In [1]: import deeplabcut

In [2]: deeplabcut.__version__
Out[2]: '2.2b6'

In [3]: deeplabcut.launch_dlc()
Created "D:\anaconda3\envs\DLC-GPU\d197test-david-2020-07-26\videos"
Created "D:\anaconda3\envs\DLC-GPU\d197test-david-2020-07-26\labeled-data"
Created "D:\anaconda3\envs\DLC-GPU\d197test-david-2020-07-26\training-datasets"
Created "D:\anaconda3\envs\DLC-GPU\d197test-david-2020-07-26\dlc-models"
Copying the videos
D:\anaconda3\envs\DLC-GPU\d197test-david-2020-07-26\videos\D1-97.mov
Generated "D:\anaconda3\envs\DLC-GPU\d197test-david-2020-07-26\config.yaml"

A new project with name d197test-david-2020-07-26 is created at D:\anaconda3\envs\DLC-GPU and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
Config file read successfully.
Do you want to extract (perhaps additional) frames for video: D:\anaconda3\envs\DLC-GPU\d197test-david-2020-07-26\videos\D1-97.mov ?
yes/no yes
Frame extraction failed. Video files must be corrupted.]

</p></details>

**How to Reproduce the problem**
1. Run Command Prompt as Administrator
2. Change directory to location of anaconda env
3. Type "activate DLC-GPU"
4. Type "ipython"
5: Type "import deeplabcut"
6: Type "deeplabcut.launch_dlc()
7: In the GUI, create a new project and check "Copy Videos" under Optional Attributes, click "Ok"
8: Once project is created, click the "Extract frames" tab on the GUI
9: Settings in order from left to right: (automatic, GUI, yes, yes, kmeans, 1, 25)
10: Click "Ok" after changing ^ settings.
11: Once "Do you want to extract ... yes/no" comes up in Command Prompt, type "yes"
12: **error occurs**

**Screenshots**
1: Settings in GUI, "Extract frames":
![DLC Extract Frames](https://user-images.githubusercontent.com/68831269/88493929-b5707b80-cf81-11ea-80ce-55ce5d3b79be.png)

2: Image of Command Prompt + error:
![Command Prompt Error](https://user-images.githubusercontent.com/68831269/88493998-fe283480-cf81-11ea-8cab-b0c9083eb1d9.png)

**Additional context**
1: I have tried updating DLC to 2.2b7, error persists
2: Cuda version 10.0 (which others have had success using DLC with)
3: I have tried using the Command Prompt to extract frames instead of using the GUI, error persists

**Comment by jeylau** [comment]
Hi @davidfslab, does the error occur when not cropping the frames?

**Comment by MMathisLab** [comment]
@davidfslab if you click use OpenCV = no, does that work? Also, when you say it works to open it, you mean with OpenCV or elsewhere?
