### ISSUE TITLE
Issue with updating DLC to version 2.2

### ISSUE THREAD

**Issue by Scompton90** [DeepLabCut/DeepLabCut#822]
Ubuntu 16.04 with Anaconda Env and DLC 2.1.8

I have tried to update to version 2.2 with no luck. I have followed the update instructions and it only updates to 2.1.8. I have provided screenshots. I have also removed DLC from my OS, and reinstalled it per DLC instructions. The version I have is still 2.1.8. I unfortunately do not have screen shots of this instance.
<img width="1092" alt="Screen Shot 2020-07-27 at 10 37 27 AM" src="https://user-images.githubusercontent.com/68859509/88555435-d5da1d80-cff5-11ea-8e79-992e5eb71859.png">
<img width="1092" alt="Screen Shot 2020-07-27 at 10 38 34 AM" src="https://user-images.githubusercontent.com/68859509/88555441-d8d50e00-cff5-11ea-8900-6fcc490d4ffd.png">
<img width="1092" alt="Screen Shot 2020-07-27 at 10 38 56 AM" src="https://user-images.githubusercontent.com/68859509/88555444-d96da480-cff5-11ea-86b2-178cd462338a.png">
<img width="1092" alt="Screen Shot 2020-07-27 at 10 39 06 AM" src="https://user-images.githubusercontent.com/68859509/88555446-da063b00-cff5-11ea-9a42-1bc9340d016e.png">
<img width="1092" alt="Screen Shot 2020-07-27 at 10 40 39 AM" src="https://user-images.githubusercontent.com/68859509/88555450-db376800-cff5-11ea-95a1-11df80308e1d.png">
<img width="1092" alt="Screen Shot 2020-07-27 at 10 41 13 AM" src="https://user-images.githubusercontent.com/68859509/88555453-dbcffe80-cff5-11ea-8437-12b338a72fdd.png">

**Comment by Scompton90** [comment]
<img width="1092" alt="Screen Shot 2020-07-27 at 10 44 23 AM" src="https://user-images.githubusercontent.com/68859509/88555711-25b8e480-cff6-11ea-8b11-c8ddce12a2a5.png">

**Comment by jeylau** [comment]
Hi @Scompton90, `pip install deeplabcut==2.2b7`should work!
