### ISSUE TITLE
Disappearance of body parts in the Refine Tracklets GUI

### ISSUE THREAD

**Issue by or-naim** [DeepLabCut/DeepLabCut#827]
Hello again, and many thanks for this amazing software!

(my operating system and dlc version:) Windows 10, Anaconda 3 Env (GPU)  & DeepLabCut 2.2b6 (multi)

The issue I'm dealing with occurs when opening the GUI in the Refine Tracklets tab. I have one animal with 9 body parts, but when I open the GUI I can only see 4 of the body parts (see picture below:)

![image](https://user-images.githubusercontent.com/59688604/88919684-36768e00-d274-11ea-9cd0-85cfff06195d.png)

I will mention that I did try to play around with the tracking parameters in the inference_cfg.yaml file as suggested in similar discussions, but nothing seems to change the GUI.  
Attached below are the inference_cfg.yaml and config.yaml information:

```
addlikelihoods: 0.15
averagescore: 0.1
boundingboxslack: 0
detectionthresholdsquare: 0
distnormalization: 1000
distnormalizationLOWER: 0
iou_threshold: 0.2
lowerbound_factor: 0.5
max_age: 100
method: m1
min_hits: 3
minimalnumberofconnections: 0
pafthreshold: 0.1
topktoretain: 1
upperbound_factor: 1.25
variant: 0
withid: false
```

```
    # Project definitions (do not edit)
Task: multianimal_test
scorer: ornaim
date: Jul8
multianimalproject: true
    # Project path (change when moving around)
project_path: C:\Users\orna\Desktop\dlc_projects\multianimal_test-ornaim-2020-07-08
    # Annotation data set configuration (and individual video cropping parameters)
video_sets:
  C:\Users\orna\Desktop\dlc_projects\multianimal_test-ornaim-2020-07-08\videos\trimmed-small.avi:
    crop: 0, 720, 0, 480
individuals:
- mouse
uniquebodyparts: []
multianimalbodyparts:
- snout
- whisker1
- whisker2
- whisker3
- right_hand
- left_thumb
- left_finger
- leg
- back
skeleton:
- - snout
  - whisker1
- - left_finger
  - back
- - right_hand
  - back
- - left_thumb
  - left_finger
- - snout
  - whisker3
- - snout
  - back
- - leg
  - back
- - snout
  - whisker2
- - left_thumb
  - back
bodyparts: MULTI!
start: 0
stop: 1
numframes2pick: 120
    # Plotting configuration
skeleton_color: white
pcutoff: 0.6
dotsize: 12
alphavalue: 0.5
colormap: Set1
    # Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 0
default_net_type: resnet_50
default_augmenter: multi-animal-imgaug
snapshotindex: -1
```

Thanks!

**Comment by MMathisLab** [comment]
Can you drop the p-cutoff to 0 and see what is displayed? 

Also I assume the video you can create post-training is fine/ evaluation numbers looked good?

But also the Skeleton does not look over-complete. Ie see docs where we explain you much over-connect prior to training.
![image](https://user-images.githubusercontent.com/28102185/88933886-4005f300-d280-11ea-8747-11ace30fc37d.png)

**Comment by or-naim** [comment]
Thanks! and sorry for the delay.
So I tried to drop the p-cutoff to 0 in the config file, but nothing has really changed. 
Yes, I've created a video that looks fine overall and consists all of the nine body parts as well. This is why I got a bit frustrated with the refine tracklets GUI results. 

Will try to train the network again and let you know if there are any changes.

Many thanks.

**Comment by onurserce** [comment]
I am having the same issue, although the skeleton is fully connected.

**Comment by MMathisLab** [comment]
The Skeleton is for training pose estimation. Inference_cfg.yaml is for tracking plus settings in the GUI. For example, setting fill in as zero fills in everything: https://youtu.be/YSRQT8N2vFE

**Comment by or-naim** [comment]
so for some reason now after I trained the network again I get this new error while evaluating:

`Running  DLC_resnet50_multianimal_testJul8shuffle1_20000  with # of trainingiterations: 20000
Initializing ResNet
Activating extracting of PAFs
Analyzing data...
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "C:\Users\orna\AppData\Roaming\Python\Python36\site-packages\deeplabcut\gui\evaluate_network.py", line 340, in evaluate_network
    comparisonbodyparts=self.bodyparts,
  File "C:\Users\orna\AppData\Roaming\Python\Python36\site-packages\deeplabcut\pose_estimation_tensorflow\evaluate.py", line 583, in evaluate_network
    c_engine=c_engine,
  File "C:\Users\orna\AppData\Roaming\Python\Python36\site-packages\deeplabcut\pose_estimation_tensorflow\evaluate_multianimal.py", line 236, in evaluate_multianimal_full
    image_path = os.path.join(cfg["project_path"], imagename)
  File "C:\Users\orna\Anaconda3\envs\dlc-windowsGPU\lib\ntpath.py", line 115, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Users\orna\Anaconda3\envs\dlc-windowsGPU\lib\genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'int'`

Couldn't understand what exactly happend... (I only changed the p-cutoff to 0 and the skeleton options). Also I tried to change the p-cutoff back again and still got the same results. Any idea?

**Comment by MMathisLab** [comment]
Can you explain what skeleton options you changed?

**Comment by pbugneac** [comment]
Having the same issue. Is there any update on this? 
I have ma with numerous body parts which are all correctly detected (when using deeplabcut.create_video_with_all_detections).
However, the tracking is missing most body parts.
