### ISSUE TITLE
Retrieving distance/coordinates?

### ISSUE THREAD

**Issue by Charlottewiltshire97** [DeepLabCut/DeepLabCut#828]
I am using deeplabcut to recognise features of an ape's face. I am interested in how the lips move over the duration of the video. Is there a way to retrieve the distance across frames between two marked features on novel videos? Or the coordinates of the features so I can calculate the distance? 

Thank you in advance!

**Comment by MMathisLab** [comment]
Hi @Charlottewiltshire97 thanks for the post. In general, we are that users post on Image Forum and tag DeepLabCut, and reserve GitHub for bug reports, etc. Please see here: https://github.com/DeepLabCut/DeepLabCut#community-support-developers--help

To get coordinates, you can simply read out the h5 file data that is produced when you analysis a video. See here on how to load this elsewhere: https://github.com/DeepLabCut/DLCutils/blob/master/Demo_loadandanalyzeDLCdata.ipynb You can also see this in the traces that are produced with you run `deeplabcut.plot_trajectories`

lastly, I hope you see the Model Zoo Ape model is available: http://modelzoo.deeplabcut.org
