### ISSUE TITLE
Video path conflict with training

### ISSUE THREAD

**Issue by hobbitsyfeet** [DeepLabCut/DeepLabCut#829]
**Describe the bug**

This is describing an issue second hand, so I do not have specific commands.

A video with periods was accepted, but when we got to training, it gave issues, I cannot quote what happened.
It led to a rabbit hole of fixing attempts, but we believe this can be avoided by handling that is how the program accepts the videos.
We eventually fixed it, but we believe this issue could simply be avoided.

**Desktop (please complete the following information about your system):**
 - OS: Windows10
 - DeepLabCut Version: 2.2b6

**To Reproduce**

1. Open GUI with python -m deeplabcut
2. load a video that contains a period (.) in the name, excluding the extension. We had a multi-animal project.
  example "this.is.a.filename.mp4"
3. extract and label frames
4. create a training dataset
5. Attempt to start training (resnet-50)

We experienced an issue where this video could not be trained with a video filename containing periods.

6. We renamed the video to exclude the periods
 example "thisisafilename.mp4"
We also renamed the folder names and everything related to that.

7. labels cannot be adjusted, and training is 

From here on it causes many issues which we resolved by adjusting the paths in the labeleddata.csv for that file, deleting the .h5 file, calling deeplabcut.convertcsv2h5(config) and relaunching. 

We propose that videos with periods (if that is the issue is caused by periods in the filename) that the program refuses the video with this format to avoid this issue.

**Comment by jeylau** [comment]
Hi @hobbitsyfeet, I have followed carefully what you described and did not experience issues with DLC 2.2b7. What error did you specifically get? Perhaps try to update and let us know!

**Comment by AlexEMG** [comment]
Thanks for raising this, at least on Linux, I have also used videos with periods without any problem.
