### ISSUE TITLE
How to create a project without assigning any videos?

### ISSUE THREAD

**Issue by Skydddoogg** [DeepLabCut/DeepLabCut#833]
As I already have extracted image frames (not extracted from DLC), I would like to go on a project without doing the process of extracting frames. However, it requires at least one video path to create a project.

**Comment by AlexEMG** [comment]
That is correct -- one non-corrupt video is required for project creation, as everything else would fail down the line if one does not have a video... Why do you want to create a project without a video?

**Comment by jeylau** [comment]
There is a workaround here [https://forum.image.sc/t/skip-extract-frames-labeling-images-without-a-video/40912](url). It is not ideal, but the idea is to have a dummy video and to store your images in a folder bearing the video name.

**Comment by Skydddoogg** [comment]
> That is correct -- one non-corrupt video is required for project creation, as everything else would fail down the line if one does not have a video... Why do you want to create a project without a video?

**Comment by Skydddoogg** [comment]
> That is correct -- one non-corrupt video is required for project creation, as everything else would fail down the line if one does not have a video... Why do you want to create a project without a video?

I am working for a company. The company doesn't provide me with any videos and just give me a collection of extracted frames.

**Comment by Skydddoogg** [comment]
> There is a workaround here [https://forum.image.sc/t/skip-extract-frames-labeling-images-without-a-video/40912](url). It is not ideal, but the idea is to have a dummy video and to store your images in a folder bearing the video name.

Thank you I will have a try.
