### ISSUE TITLE
Evaluate Network function not running

### ISSUE THREAD

**Issue by imgross** [DeepLabCut/DeepLabCut#835]
Hi there, 

I am using DLC for tracking multiple animals. Up to the point where I want to evaluate the network, everything works fine. But when hitting evaluate network I run into problems and the important pickle file is not created.

**Your Operating system and DeepLabCut version**
Windows 10 with an Anaconda Env, & DeepLabCut 2.2b4, Python 3.7.7

**Describe the problem**
After running evaluate network in the project manager GUI I get the following error messages:

```
Initializing ResNet
Activating extracting of PAFs
Analyzing data...
1219it [09:57,  2.04it/s]
Traceback (most recent call last):
  File "C:\Users\imgross\.conda\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\evaluate_network.py", line 257, in evaluate_network
    plotting=plotting,show_errors=True,comparisonbodyparts=self.bodyparts)
  File "C:\Users\imgross\.conda\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\evaluate.py", line 340, in evaluate_network
    comparisonbodyparts,gputouse,modelprefix,c_engine=c_engine)
  File "C:\Users\imgross\.conda\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\evaluate_multianimal.py", line 177, in evaluate_multianimal_full
    cfg['dotsize'], cfg['alphavalue'], cfg['pcutoff'])
  File "C:\Users\imgross\.conda\envs\DLC-GPU\lib\site-packages\deeplabcut\utils\visualization.py", line 180, in make_multianimal_labeled_image
    fig, ax = prepare_figure_axes(w, h)
  File "C:\Users\imgross\.conda\envs\DLC-GPU\lib\site-packages\deeplabcut\utils\visualization.py", line 225, in prepare_figure_axes
    fig = plt.figure(frameon=False, figsize=(width * scale / dpi, height * scale / dpi))
  File "C:\Users\imgross\.conda\envs\DLC-GPU\lib\site-packages\matplotlib\pyplot.py", line 525, in figure
    **kwargs)
  File "C:\Users\imgross\.conda\envs\DLC-GPU\lib\site-packages\matplotlib\backends\backend_wx.py", line 2132, in new_figure_manager
    return super().new_figure_manager(num, *args, **kwargs)
  File "C:\Users\imgross\.conda\envs\DLC-GPU\lib\site-packages\matplotlib\backend_bases.py", line 3218, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "C:\Users\imgross\.conda\envs\DLC-GPU\lib\site-packages\matplotlib\backends\backend_wx.py", line 2136, in new_figure_manager_given_figure
    frame = cls._frame_class(num, figure)
  File "C:\Users\imgross\.conda\envs\DLC-GPU\lib\site-packages\matplotlib\backends\backend_wx.py", line 1170, in __init__
    self.toolbar = self._get_toolbar(self.statusbar)
  File "C:\Users\imgross\.conda\envs\DLC-GPU\lib\site-packages\matplotlib\backends\backend_wx.py", line 1207, in _get_toolbar
    toolbar = NavigationToolbar2Wx(self.canvas)
  File "C:\Users\imgross\.conda\envs\DLC-GPU\lib\site-packages\matplotlib\backends\backend_wx.py", line 1495, in __init__
    NavigationToolbar2.__init__(self, canvas)
  File "C:\Users\imgross\.conda\envs\DLC-GPU\lib\site-packages\matplotlib\backend_bases.py", line 2593, in __init__
    self._init_toolbar()
  File "C:\Users\imgross\.conda\envs\DLC-GPU\lib\site-packages\matplotlib\backends\backend_wx.py", line 1531, in _init_toolbar
    self.Realize()
wx._core.wxAssertionError: C++ assertion "Assert failure" failed at ..\..\src\msw\toolbar.cpp(938) in wxToolBar::Realize(): Could not add bitmap to toolbar
```
Do you have an idea what could be the problem?

Best,
Isa

**Comment by jeylau** [comment]
Hello @imgross, what versions of wxpython are you using? I feel that ensuring you have the right version installed via `pip install -U wxPython==4.0.7.post2` would work.

**Comment by imgross** [comment]
Hi @jeylau thanks for the reply! 

I am using wxpython version 4.0.4. Is that a problem cause it is too old? 

I will try updating it as you recommended.

**Comment by imgross** [comment]
Unfortunately this does not solve the problem. I am getting the same error message:

wx._core.wxAssertionError: C++ assertion "Assert failure" failed at ..\..\src\msw\toolbar.cpp(938) in wxToolBar::Realize(): Could not add bitmap to toolbar

**Comment by MMathisLab** [comment]
please also use 2.2b7; 

but this is 100% a wxPython issue: `wx._core.wxAssertionError: C++ assertion "Assert failure" failed at ....\src\msw\toolbar.cpp(938) in wxToolBar::Realize():` see here: https://github.com/DeepLabCut/DeepLabCut/issues/682#issuecomment-627307639

**Comment by imgross** [comment]
Thanks for your help. I updated the DLC version to 2.2b7 but I am still receiving the same error message. My wxPython version is 4.0.7.post2. So I am prob doing sth else wrong?

**Comment by jeylau** [comment]
What is the version of matplotlib you're using? I'll try to reproduce the error.

**Comment by imgross** [comment]
I also thought that could be a problem and ran 

pip install --upgrade matplotlib

So I have version 3.3.0 of matplotlib

But I am still ending up with the same error message.

**Comment by jeylau** [comment]
While we look into it, I would encourage you to pass `plotting=False` so you can move forward 😃.  You will then be able to analyze your videos and evaluate prediction quality via `deeplabcut.create_video_with_all_detections` 😊.

**Comment by imgross** [comment]
Okay thank you! Is it possible that I enter that command via the terminal and still do the rest with the project manager GUI? or is that option selectable via the GUI already?

**Comment by jeylau** [comment]
Sure, you should find "Want to plot predictions (as in standard DLC projects)?" in the middle of that GUI page. Set it to False and you are fine!

**Comment by imgross** [comment]
hey there, so I tried to continue without the plotting that did not work.

I encountered more problems and will post the respective error messages here (maybe some of them are not a problem that will stop me from proceeding)

1. during network evaluation I try to do x-validation and then the following error pops up:
![DLCerror_xval](https://user-images.githubusercontent.com/36044114/90793074-8f819100-e30b-11ea-99ae-5a5050657cbe.png)

2. when I proceed to editing videos and analyzing them, I can successfully crop them, but if I want to convert the analzed videos into tracklets, I obtain the following error:
![DLCerror_create_tracklets](https://user-images.githubusercontent.com/36044114/90793243-c788d400-e30b-11ea-91f3-1ead12f815eb.png)

3. also after that I cannot open the refining tracklets GUI, and I receive this error message:
![DLCerror_trackletGUI](https://user-images.githubusercontent.com/36044114/90793348-eb4c1a00-e30b-11ea-8278-ae31d44d566c.png) 

Do you have an idea of what I might be doing wrong here?

Thanks very much for your support :)
Isa

**Comment by imgross** [comment]
In my case the video editor is not creating a new video after I cropped it. The cropping GUI pops up, I draw the rectangle, but how can I then save this or apply this to the video?

And regarding the tracklet GUI: 
What can I do about it giving me the error as described in my previous comment (error no.1) when I want to relaunch the tracklet GUI as you describe in your tutorial to test out certain parameters, as for example the min swap fraction?

And do you have an idea of why certain frames in the tracklet GUI do not contain any labels? And weirdly in the .mp4 video that was created before through analyze videos, there are not any frames detectable that have missing labels. Why could there be a mismatch between that 'pre-tracked' video and the tracklets from the GUI?

**Comment by jeylau** [comment]
The cropped video is normally automatically created after you draw the rectangle and hit Crop. "Cropping and saving to name...", as well as red info about video creation, should normally be seen in the console.
Until wxpython fixes the leak (error 1), the solution is simply to restart the GUI. That's not ideal but I'll try to find a way around it meanwhile.
The missing labels are indicative of very short tracklets that were discarded because their lengths was < min_track_length; while this is done to prevent the propagation of false alarms, you could set it to 0 to make sure all tracklets are retained.

**Comment by imgross** [comment]
Ah ok. In my case unfortunately the cropped video is not created automatically. Instead I get this error message:
![DLC_crop](https://user-images.githubusercontent.com/36044114/91040411-8431ac80-e60e-11ea-84b9-dc34f8805346.png)

I changed the min swap fraction to 0 in the project manager GUI. But still there are some frames in which not all the animals have labels, and I guess there is no way to add them that way, only to shift them around. Is there something else I am missing?

And one more question :) do you know why the hot keys might not work in some cases? Cause in my case none of the listed ones work, especially the one where you can go through single frames would be useful to have.

Thanks for all the help!

**Comment by MMathisLab** [comment]
Hi @imgross, then you will just need to reinstall ffmpeg into youre env: https://ffmpeg.org/download.html or https://pypi.org/project/ffmpeg-python/

**Comment by imgross** [comment]
Ok nice, thank you! I did that and had to additionally execute this: conda develop <directory> to add the installed software to the environment paths. And now the cropping works :)

Do you think the missing of labels in the tracklet GUI might be due to the fact that I did not label enough frames? 

And what can I do about the hot key usage that is not really working?

**Comment by imgross** [comment]
And another question to the cropping. I get the following message when cropping all my videos:
![DLC_crop_warning](https://user-images.githubusercontent.com/36044114/91145788-4be5a900-e6b6-11ea-9b2c-c6f482a0d1f4.png)
The warning about data being not aligned, is that a problem, or what does it mean in this case?
- Thanks, Isa

**Comment by imgross** [comment]
Hi there, sorry for posting so many comments, but it just came to me that I thought I get these frames with missing labels in them because the network might be not trained well enough? 

Could it be that in the case of tracking one adult mouse and several pups during pup retrieval, it requires much more frames to be annotated to train the network properly? Cause atm I have labeled 20 frames in 30 videos, so a total of 600 frames. They cover all the extreme cases (different lighting etc., some with pups and some without pups). But maybe this is not enough?
