### ISSUE TITLE
DLC Inference is good - but Assemble Animal function drops many frames

### ISSUE THREAD

**Issue by catubc** [DeepLabCut/DeepLabCut#838]
System: Ubuntu 18.04 LTS, with Anaconda Env, & DeepLabCut 2.2b7.

**Describe the problem**

1. We've now trained DLC NN on 4 animals with about 1,500 frames.  Inference is pretty amazing!, great job guys!  However, the assemble animal step is not as good and throws out a lot of data.  Here's a video:

https://drive.google.com/file/d/1A1l56OEDWz0vNZqkiNKB0VQnmlzdujCg/view?usp=sharing

2.  Here's another view of these issues using a GUI that I built to correct them:

https://drive.google.com/file/d/1_BayKa_i9HamD7ko98IRP4VYtA8yoIDK/view?usp=sharing

3.  Here's the inference_cfg.yaml file info:

```
addlikelihoods: 0.15
averagescore: 0.1
boundingboxslack: 0
detectionthresholdsquare: 0.1
distnormalization: 1000
distnormalizationLOWER: 0
iou_threshold: 0.2
lowerbound_factor: 0.5
max_age: 100
method: m1
min_hits: 3
minimalnumberofconnections: 7
pafthreshold: 0.1
topktoretain: 4
upperbound_factor: 1.25
variant: 0
withid: false
```

And here's the link to the config.yaml file:  https://drive.google.com/file/d/1iRoZwWrMWnD7h3vehm39oZtAnI7S-R9c/view?usp=sharing

Any advice on how to decrease the frame dropouts post assemble animal step?

Thank you guys so much for this amazing tool!

**Comment by MMathisLab** [comment]
can you please paste the line of code you use to create the tracklets? as there are also many variables there, including "fill in everything" at your own risk.

https://www.youtube.com/watch?v=YSRQT8N2vFE&list=PLjpMSEOb9vRGRckk5Fmh-SPflnOPsZ6Fs&index=5&t=0s

**Comment by catubc** [comment]
Hi.  Thanks so much for the reply.

1.  Re: the native DLC GUI, it's not working very well for our recordings (25FPS, 1280 x 1024 x 1hr) - it can take up to 1min to just load, and then gets stuck during plotting.  So I've written a different GUI for analysis.  I have explored the "fill in everything" and some of the other windows - and it helps merge lot of small snippets, so that's very useful. For example, for our 4 animal recordings, we are initaitlly missing between 18% to 58% of the data, and after connecting some of the snippets, we are only missing between 11% and 47% of the data. So 5-10% additional frames/connections are created.

2.  Our question is whether this is the best we can do when the inference step looks much better?  Is the animal assembly step  throwing too much good inference information?  Here's the steps for creating tracklets:

i)  Run DLC-GUI to analyze videos;

ii) drop into jupyter notebook DLC and generate the bx.pickle file with this command:

```
convert_detections2tracklets(config,
    videos,
    videotype="avi",
    shuffle=1,
    trainingsetindex=0,
    overwrite=False,
    destfolder=None,
    BPTS=None,
    iBPTS=None,
    PAF=None,
    printintermediate=False,
    inferencecfg=None,
    modelprefix="",
    track_method="box",
    edgewisecondition=True)
```

where the inference yaml config like this:

```
addlikelihoods: 0.15
averagescore: 0.1
boundingboxslack: 0
detectionthresholdsquare: 0.1
distnormalization: 1000
distnormalizationLOWER: 0
iou_threshold: 0.2
lowerbound_factor: 0.5
max_age: 100
method: m1
min_hits: 3
minimalnumberofconnections: 7
pafthreshold: 0.1
topktoretain: 4
upperbound_factor: 1.25
variant: 0
withid: false
```

iii) we then convert the pickle to h5:

`convert_raw_tracks_to_h5(config, picklefile)`

So the videos above show the inference works really well, but there are a lot of unlabeled frames / animal.  Here's a time vs. y location plot. 

https://drive.google.com/file/d/1ZAhCeN5zPWXAHVaLRPTItSKOSpao47rX/view?usp=sharing

 Are there other parameters that we can play with?

**Comment by MMathisLab** [comment]
Maybe it's just me, but instead of writing your own GUI and yet still coming to us for help, maybe help DLC by improving the GUI we already have, or detailing and helping point us to why it's not working for you? Also, as you likely can see from other issues @jeylau has been hard at work to adapt the GUI for long videos, which is now in the code base: https://github.com/DeepLabCut/DeepLabCut/pull/826

lastly, this has more features: `convert_raw_tracks_to_h5(config, tracks_pickle, output_name="", min_tracklet_len=5, max_gap=5)` (and a lot of features in the GUI: https://github.com/DeepLabCut/DeepLabCut/blob/7b96ebe05f54c684ec9958870675fb54c15dbcf4/deeplabcut/refine_training_dataset/tracklets.py)
