### ISSUE TITLE
Restoring Model and Activation Maps (Function to save scoremaps in dictionary added)

### ISSUE THREAD

**Issue by cvKDean** [DeepLabCut/DeepLabCut#84]
Good day,
I would like to know if it is possible to generate activation maps for the models/snapshots generated by train.py? I would like to visualize which particular areas of an image for each particular body part observed (e.g. nose, eyes, hands, feet).

Thank you very much.

**Comment by AlexEMG** [comment]
Voila: https://github.com/AlexEMG/DeepLabCut/blob/master/Analysis-tools/AnalyzeVideosAndExtractScoreMaps.py

**Comment by cvKDean** [comment]
This is perfect! Thank you very much.

**Comment by cvKDean** [comment]
> Voila: https://github.com/AlexEMG/DeepLabCut/blob/master/Analysis-tools/AnalyzeVideosAndExtractScoreMaps.py

Sorry for the dumb question, but why is the shape for `scmap` and `locref` (90,160, 17) and (90, 160, 17, 2) respectively? I understand that the axis 3 value 17 correspond to 17 features that I have used for my model, but I can't figure out why there is 90, 160, and an additional axis for locref with size of 2. For reference, I am analyzing a video with 376 detected frames @25fps, and a resolution of 1280 x 720. Thank you.

**Comment by AlexEMG** [comment]
90 x 160 are the downsampled dimensions of the input image (transposed). So scmap[:,:,0] is the scoremap for feature  0...

**Comment by leiyaohui** [comment]
Thank you！But I have new problems.After running AnalyzeVideosAndExtractScoreMaps.py, only two files were generated. How do I generate scoremap?

**Comment by leiyaohui** [comment]
Thank you！But I have new problems.After running AnalyzeVideosAndExtractScoreMaps.py, only two files were generated. How do I generate scoremap?Is it running MakingLabeledVideo.py directly?
