### ISSUE TITLE
Problem of switching identities

### ISSUE THREAD

**Issue by DorianBattivelli** [DeepLabCut/DeepLabCut#842]
Hello,

We built a multi-animal project with two black mice, and we seen, once we switched on simba that the identities of the animal regularly switched when the animals are close. 
To avoid this problem we shaved one animal on the back, so that back body part label of this animal is now brighter than the one of the other mouse. But the identities still switch when the animal are close.

Here an illustration of a sequence when it switches (on simba):

![id1](https://user-images.githubusercontent.com/66886884/89543653-78b64700-d801-11ea-905e-a32dc0e12c69.png)

![id2](https://user-images.githubusercontent.com/66886884/89543667-7d7afb00-d801-11ea-8263-63c25e9a3b68.png)

I wrote a similar issue on the Simba github, because I don't know at which stage precisely we should change our parameters to avoid this problem. But I guess the problem could appear as early as during the training/analyzing of the model/videos. 

FYI: I am using dlc 2.b7, on windows 7. We labeled 100 frames, and run 75000 iterations. 
Our videos are in mp4, with a  640x480 resolution. 

The shaved spot was pretty small (but still visible to the naked eye, so that we have been able to systematically label the shaved animal with the same identity) . Do you think that expending the shaving, and increasing the visibility of the brighter spot could help dlc to distinguish the two mice? (if the problem comes from dlc). Please let me know if you have any suggestion that could fix this problem, 

Thank you,
Best, 
Dorian

**Comment by jeylau** [comment]
Hello @DorianBattivelli, have you labeled a bodypart only? Is that switch already present in the video produced by `create_video_with_all_detections`? That would help diagnose whether this is a tracking issue. If the video does look great, I am not convinced that increasing the visibility of that spot would help tracking (although labeling more bodyparts probably would). Could you also tell us what settings you used to refine the tracklets (e.g., were tracking parameters cross-validated?, was it with the box tracker?)?

**Comment by MMathisLab** [comment]
In the future @DorianBattivelli please post questions here: https://forum.image.sc/tags/deeplabcut

**Comment by DorianBattivelli** [comment]
Hi @jeylau ,

Thank you for your answer. I actually did not managed the refine tracklet module yet. I directly switched to SimBA program.  
I'll manually refine the tracklets these days and I'll let you know if it fixed the problem. 
Just one question: when a body part is not detected in a frame, it's not possible to add it "ex nihilo" right? It's only possible to drag or invert bp ALREADY detected? 

Best, 
Dorian

**Comment by MMathisLab** [comment]
You can make all points show up; please review the docs on Creating Tracklets; this is not optional and jumping to SimBA before this is not advisable.
