### ISSUE TITLE
Can I downsample my video to lower resolution for analyzing?

### ISSUE THREAD

**Issue by neugun** [DeepLabCut/DeepLabCut#843]
Desktop (please complete the following information about your system):
windows, with an Anaconda Env, & DeepLabCut 2.0.9.

Hi, i'm having an issue analyzing videos, seem it is taking longer than real time. I train a new model with the video acquired at 30 FPS, and 1280 x 720 resolution. This video analysis step run much slow. 

Can I downsample my video to 640 x 360 resolution for analyzing? I have tried it but it seems doesn't work very well, Any suggestions?

**Comment by jeylau** [comment]
Hi @neugun, have you tried `deeplabcut.DownSampleVideo()`? Alternatively you could analyze the video in Google Colab with a free GPU instance, that would be much faster 😊

**Comment by MMathisLab** [comment]
When you train the network, you set the scaling parameters, i.e., how much smaller and how much larger you want to go. the default is 0.5-1.25, and you should stay well within the bound, so for you I would either retrain at 0.1 - 1.25 or run at 0.75 the size.

Also, please only post bug reports on GitHub. We really ask users to post user questions here: https://forum.image.sc/tags/deeplabcut

**Comment by neugun** [comment]
Got it, Thank you!
