### ISSUE TITLE
cannot save as csv 

### ISSUE THREAD

**Issue by bkacsoh** [DeepLabCut/DeepLabCut#844]
Hi everyone,

I am trying to save video analysis to be a csv and am getting no luck with this. I have changed some of the code to be save_cvs= TRUE but still no luck.

I also ran  this code: 
 deeplabcut.analyze_videos_converth5_to_csv('/home/exx/bioinformatics/untitled/July2020_OLM-Balint-2020-08-06/videos/'  , videotype='.mp4')

But again, no conversion to csv. 

Please help!!

I am using ubuntu, 18 with DLC2.2alpha
![Screenshot from 2020-08-09 19-00-15](https://user-images.githubusercontent.com/53061481/89743589-99d19e80-da72-11ea-8343-492edb7359d8.png)
![Screenshot from 2020-08-09 18-56-03](https://user-images.githubusercontent.com/53061481/89743590-9a6a3500-da72-11ea-9d41-174b4ceb9427.png)

**Comment by bkacsoh** [comment]
if I run the code  deeplabcut.analyze_videos(config_path,['/home/exx/Downloads/M4v videos'], videotype='.mp4', save_as_csv = True)
it still doesnt make csv files 
![Screenshot from 2020-08-09 19-19-57](https://user-images.githubusercontent.com/53061481/89743863-53ca0a00-da75-11ea-9650-ddec484e66b5.png)

**Comment by jeylau** [comment]
Hello @bkacsoh! With multi-animal DLC, `analyze_video` produces a pickle file of detections that need to be assembled into distinct animals. It is only after refining the tracklets that a h5 file is written (which can ultimately be converted to CSV).

**Comment by bkacsoh** [comment]
Hi @jeylau , I tried running the convert code on the H5, but had no luck there. Any pointers on how to get the csv? That is to say, I have refined tracklets, even have great labelled videos! I am just stuck on getting a CSV file. Should be easy, I think, but I am totally lost and the tricks I am trying from the docstring arent working

i.e. this code on the folder with the h5:

deeplabcut.analyze_videos_converth5_to_csv('/home/exx/bioinformatics/untitled/July2020_OLM-Balint-2020-08-06/videos/' , videotype='.mp4')

**Comment by jeylau** [comment]
Shouldn't `videotype` be 'm4v'?

**Comment by bkacsoh** [comment]
Even then it doesn’t work :(

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jeylau** [comment]
Updating DLC to 2.2b7 should do the trick; could you let me know?

**Comment by bkacsoh** [comment]
Hi @jeylau, I will try that! What is the command for that one? i.e. pip ....


I'll try later this evening when I am back at the computer. Thank you!!

**Comment by jeylau** [comment]
`pip install deeplabcut==2.2b7`

**Comment by bkacsoh** [comment]
ah, thought so. I was just checking because the 'b' is new :)

**Comment by bkacsoh** [comment]
Just to confirm @jeylau , will I need to run the terminal command to convert in the updated DLC?

**Comment by jeylau** [comment]
Yes, that's correct 😊

**Comment by bkacsoh** [comment]
@jeylau it worked with some finnesse!! for some reason the h5 had to be in the same folder as the original video
