### ISSUE TITLE
Analyze videos: filtered csv is saved even when not requested

### ISSUE THREAD

**Issue by joeyo** [DeepLabCut/DeepLabCut#845]
**Describe the bug**

The "Analyze Videos" GUI step saves a csv file for filtered data, even when the csv option is unset. 

**Desktop (please complete the following information about your system):**
 - OS: Ubuntu 18.04
 - DeepLabCut Version: 2.2b7

**To Reproduce**
Steps to reproduce the behavior, i.e.:
1. Go to "Step 7. Analyze Videos"
2. For "Want to save result(s) to csv?", select "no"
3. For "Want to filter the predictions?", select "yes"

</p></details>

**Expected behavior**
The "analyze videos" step is has options to 1) save the results as a csv and 2) to filter the predictions. When save as csv is false and filter the predictions is true (see screenshot), the following files are saved:

```
foo_k_filtered.csv
foo_k_filtered.h5
foo_k.h5
```

My expectation is that _only_ h5 files would be saved (ie the save results to csv boolean should apply to both filtered and unfiltered data, but this does not seem to be the logic that is implemented.

**Screenshots**
![dlc_analyze_videos_bug](https://user-images.githubusercontent.com/372147/89851086-8856c800-db40-11ea-8884-a63e7c6daf9e.png)

**Comment by jeylau** [comment]
Fixed with https://github.com/DeepLabCut/DeepLabCut/commit/26448809671590dd6642bc1662feb1354f8a1145.
