### ISSUE TITLE
Network does not generalize

### ISSUE THREAD

**Issue by MaximilianUwe** [DeepLabCut/DeepLabCut#846]
System: Windows 10, latest DLC Version with Anaconda Env

Problem: For a couple of weeks I have been trying to train a network on an extremely simple and uniform human hand movement (finger tapping) which generalizes extremely poor, if at all. The Videos are cropped by GUI, labelled in a reproducible manner with 5-12 labels. The network has been trained in numerous approaches with 50-250 frames from different individuals, cameras, backgrounds, lighting conditions, selected either manually or automatically, with different augmentations (Default, imgaug, tensorpack), iterations (50k to 1 Million) and up to 7 refinement steps. Care was taken as to include Frames with obscured bodyparts which are not labeled. Known videos are predicted robustly with around 2-6 Pixel Errors. The function "check labels" after labelling frames has never worked on our system, but labelled frames were visually checked in their respective Folders.
I would be very thankful for some more input on troubleshooting, as I am slowly running out of ideas.

Cheers,
Max

**Comment by AlexEMG** [comment]
The function "check labels" after labelling frames has never worked on our system >> that sounds like a problem. What is the issue? Also can you share results to give us any sense of the problem (i.e. train / test errors; train /test images etc).

**Comment by AlexEMG** [comment]
Please also follow the template, and consider the forum, as your question seems more appropriate for user advice (https://forum.image.sc/tag/deeplabcut)

**Comment by MaximilianUwe** [comment]
Hi Alex,

after extraction and labelling, trying the check labels function creates this:
```
ValueError                                Traceback (most recent call last)
~\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\label_frames.py in check_labelF(self, event)
    130         )
    131         result = dlg.ShowModal()
--> 132         deeplabcut.check_labels(self.config, visualizeindividuals=False)
    133
    134     def check_labelInd(self, event):
~\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py in check_labels(config, Labels, scale, dpi, draw_skeleton, visualizeindividuals)
    506                 keypoint=Labels[0],
    507                 draw_skeleton=draw_skeleton,
--> 508                 color_by=color_by,
    509             )
    510         except FileNotFoundError:
~\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\utils\visualization.py in make_labeled_images_from_dataframe(df, cfg, destfolder, scale, dpi, keypoint, draw_skeleton, color_by)
    255     bones = []
    256     if draw_skeleton:
--> 257         for bp1, bp2 in cfg["skeleton"]:
    258             match1, match2 = [], []
    259             for j, bp in enumerate(bodyparts):
ValueError: not enough values to unpack (expected 2, got 1)
```
As pointed out, the Network Evaluation Shows test Errors around 2-4 Pixels and Train Errors around 4-8 Pixels, which, given the Videos which are shot pretty close up, is more than sufficiently precise. 

Going through the labeled data Folder, I can see the extracted Frames, however, the labels seem to be missing on These Pictures, however, a csv file with the respective label coordinates is to be found in the Folder. Could this be the Problem? If no labels were found, why should the Network create such small Pixel Errors?

Thank you for your assistance,
Max

**Comment by MMathisLab** [comment]
@MaximilianUwe looks like you don't have a valid skeleton drawn, but are requesting to plot the skeleton.

**Comment by MMathisLab** [comment]
also you posted the same information on ImageForum, so I will close this.
