### ISSUE TITLE
issue with version 2.2b7 gui fonts (CentOS 7 only)

### ISSUE THREAD

**Issue by denisovg** [DeepLabCut/DeepLabCut#848]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). 
Please fill out the template completely, including the full "TRACEBACK" and input code that you ran to hit this error.

On a Linux platform running CentOS 7, after running the following commands:
python
>>> import deeplabcut
>>> deeplabcut.launch_dlc()
I get the GUI shown at the attached screenshot.  Looks to me like a fonts problem. 

The previous version I tried (2.1.8.2) works fine.

Please provide the minimal required code to reproduce the error and the full output (please edit ONLY the section below that says `PLACE YOUR CODE HERE!!! `.

python
>>> import deeplabcut
>>> deeplabcut.launch_dlc()

**Desktop (please complete the following information about your system):**
 - OS: [e.g. Windows10, MacOS version, Linux, etc.]
 - DeepLabCut Version [e.g. 22] (please check with ``import deeplabcut``, ``deeplabcut.__version__``)
 - Browser, if applicable [e.g. chrome, safari]

Linux CentOS 7
DeepLabCut version 2.2b7

**To Reproduce**
Steps to reproduce the behavior, i.e.:
4. the input code you used (i.e. `deeplabcut.train_network( .... )`)
4. See error:
[](url)
<details><summary>TRACEBACK</summary><p>

```python

Please place code inside this!!!
PLACE YOUR CODE HERE!!!  


```
</p></details>

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. (but please post the code output above!)

![DLC_GUI_issue](https://user-images.githubusercontent.com/1093770/90166574-76f00480-dd68-11ea-8db6-ce0c9fca0d6f.png)

**Additional context**

**Comment by MMathisLab** [comment]
We have never tried CentOS, but Ubuntu 16-20 works fine with 2.2b7! very oodd, but hard for us to tackle as we don't have CentOS in the lab ;(

**Comment by MMathisLab** [comment]
anyone else reporting this?

**Comment by MMathisLab** [comment]
@denisovg could you try our new release, 2.2b8?

**Comment by MMathisLab** [comment]
stale issue.
