### ISSUE TITLE
pose_cfg file not found in aws sagemaker

### ISSUE THREAD

**Issue by amaanda** [DeepLabCut/DeepLabCut#850]
I am trying to train the network using aws sagemaker, therefore I am using red hat linux.
Deeplabcut version: '2.1.8.2'

I got on the data marked on a windows machine, uploaded it to a s3 bucket and now i am trying to start the training process. I get the following message after preparing my dataset for training:

![image](https://user-images.githubusercontent.com/20389222/90289013-594a9a00-de51-11ea-90cc-062a336d0683.png)

But then, when I try training, I keep getting the following error:

![image](https://user-images.githubusercontent.com/20389222/90288663-b8f47580-de50-11ea-9609-7060e632d1f3.png)

You can check on the picture above that the pose_cfg.yaml file was indeed created by dlc on the previous step.
If someone could help me find what is causing this error, I would highly appreciate it! Thanks :)

**Comment by MMathisLab** [comment]
sounds like a permissions issue; I don't use sagemaker, so not sure how to help. 

another thought, your config.yaml has an incorrect project_path; why is it not looking in /home/ec2 .... ?

**Comment by amaanda** [comment]
I see what you mean with the incorrect project_path. I will try using /home/ec2 ....
I find it weird that I'm running into a permission issue because deeplabcut just wrote the files on that folder before running into that error.

**Comment by amaanda** [comment]
@MMathisLab I forgot to give you some feedback. It worked fine after changing the project_path, it was what was causing the other problem. Thanks!
