### ISSUE TITLE
Frame extraction failure (for corrupted videos)

### ISSUE THREAD

**Issue by jonas4climate** [DeepLabCut/DeepLabCut#851]
**Your Operating system and DeepLabCut version**

OS: macOS Catalina 10.15.6
DeepLabCut Version: 2.1.8.2
Anaconda env used: default anaconda DLC_CPU.yaml

**Describe the problem**

When trying to extract frames manually from a .avi file a traceback error occurs breaking the image loading process and stops the GUI labeling process to start (grey screen with no image loading for labeling). The videos did have error messages for missing frames which maybe relate to this issue.

Please place code inside this:

<details><summary>Code output</summary><p>

pythonw launch.py
2.1.8.2
Created "/Users/jonasschafer/CS/Additional/Learn/AI/deeplabcut/Animal Behaviour Small-Jonas Schäfer-2020-08-14/videos"
Created "/Users/jonasschafer/CS/Additional/Learn/AI/deeplabcut/Animal Behaviour Small-Jonas Schäfer-2020-08-14/labeled-data"
Created "/Users/jonasschafer/CS/Additional/Learn/AI/deeplabcut/Animal Behaviour Small-Jonas Schäfer-2020-08-14/training-datasets"
Created "/Users/jonasschafer/CS/Additional/Learn/AI/deeplabcut/Animal Behaviour Small-Jonas Schäfer-2020-08-14/dlc-models"
Copying the videos
/Users/jonasschafer/CS/Additional/Learn/AI/deeplabcut/Animal Behaviour Small-Jonas Schäfer-2020-08-14/videos/20191113090848_01.avi
[h264 @ 0x7ff6d3132600] non-existing PPS 0 referenced
[h264 @ 0x7ff6d3132600] non-existing PPS 0 referenced
[h264 @ 0x7ff6d3132600] decode_slice_header error
[h264 @ 0x7ff6d3132600] no frame!

// Numerous identical messages as above would be here, cut out for readability

/Users/jonasschafer/CS/Additional/Learn/AI/deeplabcut/Animal Behaviour Small-Jonas Schäfer-2020-08-14/videos/20191113091718_01.avi
[h264 @ 0x7ff6b81a0c00] non-existing PPS 0 referenced
[h264 @ 0x7ff6b81a0c00] non-existing PPS 0 referenced
[h264 @ 0x7ff6b81a0c00] decode_slice_header error
[h264 @ 0x7ff6b81a0c00] no frame!

// Numerous identical messages as above would be here, cut out for readability

/Users/jonasschafer/CS/Additional/Learn/AI/deeplabcut/Animal Behaviour Small-Jonas Schäfer-2020-08-14/videos/20191113092627_01.avi
[h264 @ 0x7ff6d2ab9e00] non-existing PPS 0 referenced
[h264 @ 0x7ff6d2ab9e00] non-existing PPS 0 referenced
[h264 @ 0x7ff6d2ab9e00] decode_slice_header error
[h264 @ 0x7ff6d2ab9e00] no frame!

// Numerous identical messages as above would be here, cut out for readability

/Users/jonasschafer/CS/Additional/Learn/AI/deeplabcut/Animal Behaviour Small-Jonas Schäfer-2020-08-14/videos/20191113094247_01.avi
[h264 @ 0x7ff6b80f9600] non-existing PPS 0 referenced
[h264 @ 0x7ff6b80f9600] non-existing PPS 0 referenced
[h264 @ 0x7ff6b80f9600] decode_slice_header error
[h264 @ 0x7ff6b80f9600] no frame!

// Numerous identical messages as above would be here, cut out for readability

/Users/jonasschafer/CS/Additional/Learn/AI/deeplabcut/Animal Behaviour Small-Jonas Schäfer-2020-08-14/videos/20191113094643_01.avi
[h264 @ 0x7ff6d2a99600] non-existing PPS 0 referenced
[h264 @ 0x7ff6d2a99600] non-existing PPS 0 referenced
[h264 @ 0x7ff6d2a99600] decode_slice_header error
[h264 @ 0x7ff6d2a99600] no frame!

// Numerous identical messages as above would be here, cut out for readability

/Users/jonasschafer/CS/Additional/Learn/AI/deeplabcut/Animal Behaviour Small-Jonas Schäfer-2020-08-14/videos/20191113095009_01.avi
[h264 @ 0x7ff6b80f9600] non-existing PPS 0 referenced
[h264 @ 0x7ff6b80f9600] non-existing PPS 0 referenced
[h264 @ 0x7ff6b80f9600] decode_slice_header error
[h264 @ 0x7ff6b80f9600] no frame!

// Numerous identical messages as above would be here, cut out for readability

/Users/jonasschafer/CS/Additional/Learn/AI/deeplabcut/Animal Behaviour Small-Jonas Schäfer-2020-08-14/videos/20191113095648_01.avi
[h264 @ 0x7ff6b80efc00] non-existing PPS 0 referenced
[h264 @ 0x7ff6b80efc00] non-existing PPS 0 referenced
[h264 @ 0x7ff6b80efc00] decode_slice_header error
[h264 @ 0x7ff6b80efc00] no frame!

// Numerous identical messages as above would be here, cut out for readability

/Users/jonasschafer/CS/Additional/Learn/AI/deeplabcut/Animal Behaviour Small-Jonas Schäfer-2020-08-14/videos/20191113095959_01.avi
[h264 @ 0x7ff6c5f5de00] non-existing PPS 0 referenced
[h264 @ 0x7ff6c5f5de00] non-existing PPS 0 referenced
[h264 @ 0x7ff6c5f5de00] decode_slice_header error
[h264 @ 0x7ff6c5f5de00] no frame!

// Numerous identical messages as above would be here, cut out for readability

Generated "/Users/jonasschafer/CS/Additional/Learn/AI/deeplabcut/Animal Behaviour Small-Jonas Schäfer-2020-08-14/config.yaml"

A new project with name Animal Behaviour Small-Jonas Schäfer-2020-08-14 is created at /Users/jonasschafer/CS/Additional/Learn/AI/deeplabcut and a configurable file (config.yaml) is stored there. Change the parameters in this file to adapt to your project's needs.
 Once you have changed the configuration file, use the function 'extract_frames' to select frames for labeling.
. [OPTIONAL] Use the function 'add_new_videos' to add new videos to your project (at any stage).
[h264 @ 0x7ff6b809b400] non-existing PPS 0 referenced
[h264 @ 0x7ff6b809b400] non-existing PPS 0 referenced
[h264 @ 0x7ff6b809b400] decode_slice_header error
[h264 @ 0x7ff6b809b400] no frame!

// Numerous identical messages as above would be here, cut out for readability

Traceback (most recent call last):
  File "/Users/jonasschafer/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/frame_extraction_toolbox.py", line 339, in browseDir
    self.update()
  File "/Users/jonasschafer/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/frame_extraction_toolbox.py", line 374, in update
    self.ax = self.axes.imshow(frame)
  File "/Users/jonasschafer/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/matplotlib/__init__.py", line 1810, in inner
    return func(ax, *args, **kwargs)
  File "/Users/jonasschafer/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 5494, in imshow
    im.set_data(X)
  File "/Users/jonasschafer/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/matplotlib/image.py", line 634, in set_data
    raise TypeError("Image data cannot be converted to float")
TypeError: Image data cannot be converted to float
Traceback (most recent call last):
  File "/Users/jonasschafer/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/frame_extraction_toolbox.py", line 403, in grabFrame
    self.chooseFrame()
  File "/Users/jonasschafer/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/frame_extraction_toolbox.py", line 384, in chooseFrame
    frame=cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(3.4.10) /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

</p></details>

**How to Reproduce the problem**
1. import deeplabcut and run the GUI deeplabcut.launch_dlc()
2. Create project with .avi video files
3. Extraction method: manual, click "OK"
4. "Load video" and select a single .avi video file, see first Traceback error
5. Select "Grab frames" for followup Traceback error from above

**Screenshots**
N/A

**Additional context**
Maybe the missing frames are related to this issue and it breaks conversion to float?

**Comment by AlexEMG** [comment]
I think the paths to the videos are wrong or the videos corrupt?

**Comment by jonas4climate** [comment]
I used the CLI yesterday after this and when choosing manual selection was in fact told that the video file is corrupted. What does that mean and can I fix that? When extracting automatically with kmeans I had issues too but uniform extraction worked just fine (found missing frames but no traceback errors).

**Comment by MMathisLab** [comment]
Typically corrupted means the meta data is not intact. You can try to re-code the video, i.e. perhaps covert to h264 - or you will need to use other videos...

**Comment by jonas4climate** [comment]
Thank you so much, I managed to recode it using ffmpeg and fix the meta data this way.
