### ISSUE TITLE
small shifting issue with labeling frames

### ISSUE THREAD

**Issue by or-naim** [DeepLabCut/DeepLabCut#854]
Hi all, 
I have noticed for a time now that there is a very small (but yet annoying) shifting problem with the GUI labeling option. 
Each time I'm labeling some frames, if I go back to some previous frames which I already labeled I see that some of the placements had changed. This is a very small shifting, but yet important for the accuracy of the training. 

(my operating system and dlc version:) Windows 10, Anaconda 3 Env (GPU) & DeepLabCut 2.2b6

Attached are some screenshots of the same labeled frame with the noticeable shifting:

![image](https://user-images.githubusercontent.com/59688604/90330993-03453600-dfba-11ea-8fe5-41426b27fe74.png)
![image](https://user-images.githubusercontent.com/59688604/90330995-05a79000-dfba-11ea-9ce1-179a5994bb53.png)

**Comment by MMathisLab** [comment]
can you upgrade to the current repo, i.e. run `pip install git+https://github.com/DeepLabCut/DeepLabCut.git` and see if this persists? Indeed that is an issue! 

can you also tell me the versions of pandas and matplotlib you are using?
```
import matplotlib
matplotlib.__version__

import pandas
pandas.__version__
```

**Comment by AlexEMG** [comment]
(NOTE: this was introduced only in 2.2beta; before this bug didn't exist and is not fixed).

**Comment by jeylau** [comment]
@AlexEMG, that's incorrect. I can reproduce it too with 2.1.8.2; and the PR now addresses both single and multi-animal labeling.

**Comment by AlexEMG** [comment]
Oh!

**Comment by alec-hoyland** [comment]
I am having this issue on Centos with v2.1.8.2. We are *not* having this problem with .mp4 video files but *are* with .wmv files after extraction.

**Comment by MMathisLab** [comment]
@alec-hoyland you can `pip install git+ https://github.com/DeepLabCut/DeepLabCut.git` To update.

**Comment by jeylau** [comment]
Ups, we should merge the PR first 😄

**Comment by or-naim** [comment]
On the very same day (21.8.20)

**Comment by jeylau** [comment]
Would you mind sharing a short GIF of you triggering that label shift? That'd be super helpful :)

**Comment by or-naim** [comment]
Sure. As soon as possible 👍

**Comment by or-naim** [comment]
![gif shift problem](https://user-images.githubusercontent.com/59688604/91292635-76f7f780-e79f-11ea-9699-7ae9a7d05db5.gif)

**Comment by MMathisLab** [comment]
^whoa, that is super odd. I have never seen this. what version of wxPython are you using?

**Comment by or-naim** [comment]
4.0.4
