### ISSUE TITLE
Initializing ResNet WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional. Conv2D object at  0x7ff16f86a9e8>> could not be transformed

### ISSUE THREAD

**Issue by rnrpereira** [DeepLabCut/DeepLabCut#860]
System: 
Ryzen 7 8 cores/16 threads
32 GB RAM

Ubuntu 18.04
Anaconda environment (DLCut)
DeepLabCut 2.2b7

GPU: RTX2060
NVIDIA-SMI 440.100 
Driver Version: 440.100
CUDA Version: 10.2

I tried Training Network from the GUI...
I used to do it from Docker (DLC 2.1.3) and it worked fine!
But I just installed maDLC and I'm having problems....
Obs: by the way, I don't known if it uses the GPU from the GUI !

ERROR MESSAGE:
```
Initializing ResNet
WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 
0x7ff16f86a9e8>> could not be transformed and will be executed as-is. 
Please report this to the AutgoGraph team. 
When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. 
Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.
Conv2D object at 0x7ff16f86a9e8>>: 
AssertionError: Bad argument number for Name: 3, expecting 4
```

**Comment by jeylau** [comment]
Hi @rnrpereira, `pip install gast==0.2.2` seems to be the solution (see here https://github.com/tensorflow/tensorflow/issues/32859 too). That's odd though: can you check your tensorflow version is <1.15.X?

**Comment by rnrpereira** [comment]
Hi, thanks:

tensorflow version = 1.8.0

I already have gast 0.3.2

**Comment by jeylau** [comment]
That's precisely the issue. `pip install gast==0.2.2` is the solution according to the tensorflow bug report above.
