### ISSUE TITLE
Failed extract outlier frames

### ISSUE THREAD

**Issue by chanduborkar** [DeepLabCut/DeepLabCut#861]
**Hi,
I am using DLC (ver 2.2.8.2) on Linux system (conda, python 3.7) from my remote computer (on PuTTY). 
I have installed xming to open DLC GUI. Mostly it runs well however I saw different problems here:
1) Lots of outliers in the labelled video and the extraction outlier function did not work. 
2) Refine label function did not work (although .h5 file in the correct path folder). 
3) The shadow on walls/fecal bouts are considered data points sometimes. Also its messier when you use opto patch cables. The data points keep on jumping to the patch cable.

Following are commands I used (when I did first installation):**
1. mkdir /home/cborkar/conda-envs
2. cd /home/cborkar/conda-envs/
3. export CONDA_ENVS_PATH=/home/cborkar/conda-envs/
4. module load anaconda3/2018.12
5. conda create -n DLC1 python=3.7 --yes
6. source activate DLC1
7. conda install jupyter nb_conda tensorflow==1.13.1 wxpython ruamel.yaml dask --yes
8. export PYTHONPATH=$CONDA_PREFIX/lib/python3.7/site-packages:$PYTHONPATH
9. export PYTHONUSERBASE=$CONDA_PREFIX
10. pip install deeplabcut --user --use-feature=2020-resolver
11. This failed so I ran it again without the –user-feature option
12. pip install deeplabcut --user
13. export LD_LIBRARY_PATH=/usr/lib64/gtk-2.0/modules:$LD_LIBRARY_PATH
14. pip install statsmodels --upgrade --user
15. ipython
16. import deeplabcut

Error
(ipython:62484): Gtk-WARNING **: 11:35:00.603: Attempting to store changes into                                                                                                                                            `/home/cborkar/.local/share/recently-used.xbel', but failed: Failed to create fi                                                                                                                                           le “/home/cborkar/.local/share/recently-used.xbel.SWRDP0”: No such file or direc                                                                                                                                           tory

(ipython:62484): Gtk-WARNING **: 11:35:00.603: Attempting to set the permissions                                                                                                                                            of `/home/cborkar/.local/share/recently-used.xbel', but failed: No such file or                                                                                                                                            directory

(ipython:62484): Gtk-WARNING **: 11:35:00.873: Attempting to store changes into                                                                                                                                            `/home/cborkar/.local/share/recently-used.xbel', but failed: Failed to create fi                                                                                                                                           le “/home/cborkar/.local/share/recently-used.xbel.B1O8O0”: No such file or direc                                                                                                                                           tory

(ipython:62484): Gtk-WARNING **: 11:35:00.873: Attempting to set the permissions                                                                                                                                            of `/home/cborkar/.local/share/recently-used.xbel', but failed: No such file or                                                                                                                                            directory

![Extract outlier frames](https://user-images.githubusercontent.com/53411725/90802637-271bbb00-e2dd-11ea-9cee-3168dd350dd6.jpg)

![trajectory_filtered](https://user-images.githubusercontent.com/53411725/90802835-6fd37400-e2dd-11ea-82f9-394610836d5f.png)

![Refine](https://user-images.githubusercontent.com/53411725/90805541-5af8df80-e2e1-11ea-8ab5-0eaa777ea828.jpg)

Thank you!
Chandu

**Comment by jeylau** [comment]
Hi @chanduborkar, could you tell us what did not work with extract_outlier_frames and refine_labels? The screenshot seems to indicate a permission issue, which is unrelated to DLC. As for the outliers, it is hard to give you tips without knowing more about your setup: what sort of videos do you have? What do you label? How did you train the network?
