### ISSUE TITLE
Issues with refining tracklets

### ISSUE THREAD

**Issue by akazawayukidai** [DeepLabCut/DeepLabCut#866]
Hi, 

I have just started to try maDLC recently. I have encountered 2 major issues when trying to refine tracklets. 

1) Some of the hot keys don't seem to work on my Windows 10 desktop and/or Mac. Tab for play/pause the videos doesn't work on both of them, left/right arrow for changing the frames don't work on my Windows 10 desktop. I'm wondering if you know any tips to make these work? It's been difficult to navigate through the videos without these functions..

2) I am trying to track 8 points per animal with 2 animals in a video (i.e. example image 1), in some frames there are missing points (i.e. example image 2), I'm wondering if I can still add points during this step? Or what I can do to avoid missing points from happening?

example image 1
<img width="975" alt="WeChat Screenshot_20200821141943" src="https://user-images.githubusercontent.com/54284554/90922177-85b66700-e3b9-11ea-9f81-6357bdef8216.png">

example image 2
<img width="975" alt="WeChat Screenshot_20200821141932" src="https://user-images.githubusercontent.com/54284554/90922176-851dd080-e3b9-11ea-818f-f16131d8a162.png">

**Comment by MMathisLab** [comment]
the hotkeys do work on windows if you install from the repo, but we will bump up to 2.2b8 very soon!

**Comment by akazawayukidai** [comment]
> the hotkeys do work on windows if you install from the repo, but we will bump up to 2.2b8 very soon!

I tried to install it again from the repo but it still didn't work, the only key worked was Alt+arrows, but once it starts to play the video I can't stop it.. I asked 2 people who were also using DLC and they said the hotkeys don't work for them either.. So I'm not sure if there's anything we need to setup or adjust for. But hopefully 2.2b8 would fix this issue!

**Comment by MMathisLab** [comment]
can you clarify which buttons you are using? to scroll through the frames, you hit the left and right arrow keys' this doen't work?

**Comment by akazawayukidai** [comment]
> can you clarify which buttons you are using? to scroll through the frames, you hit the left and right arrow keys' this doen't work?

I tried N/B or left/right arrows for moving forward and backward the frames, tab or space to start/pause the videos and they don't work on my Windows 10 pro computer, only keys that work are L for Lasso, D for Drag, Alt+arrows for fast playing the videos (although once it started to play, I can't pause the video). Also Lasso points and swap between animals don't seem to work on my computer as well... I have read the other issues carefully (i.e. #873, #865, and #810), tried to clone the repository from Git and re-install everything, I'm not sure what's wrong with it...

**Comment by akazawayukidai** [comment]
> can you clarify which buttons you are using? to scroll through the frames, you hit the left and right arrow keys' this doen't work?

I actually tried to replace my old trackets.py file with the new one that's in #810 and now all the keys are working! Thank you so much for your help!
