### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Alberto100591** [DeepLabCut/DeepLabCut#868]
**Your Operating system and DeepLabCut version**
Ubuntu 20.04 LTS, with an Anaconda Env, & deeplabcut 2.1.8.2 

Please complete the following information about your system:

OS: [Ubuntu 20.04 LTS,]
DeepLabCut Version: deeplabcut 2.1.8.2 
Anaconda env used:

When running testscript.py , I get the following error on 
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~/Desktop/DeepLabCut1/DeepLabCut/examples/testscript.py in <module>
    214 
    215 print("RELABELING")
--> 216 DF = pd.read_hdf(file, "df_with_missing")
    217 DLCscorer = np.unique(DF.columns.get_level_values(0))[0]
    218 DF.columns.set_levels([scorer.replace(DLCscorer, scorer)], level=0, inplace=True)

~/anaconda3/envs/DLC-GPU/lib/python3.7/site-packages/pandas/io/pytables.py in read_hdf(path_or_buf, key, mode, errors, where, start, stop, columns, iterator, chunksize, **kwargs)
    385 
    386         if not exists:
--> 387             raise FileNotFoundError(f"File {path_or_buf} does not exist")
    388 
    389         store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)

```

**How to Reproduce the problem**
1. conda activate DLC-GPU
2. ipython testscript.py
3. appears error

**Screenshots**
![Screenshot from 2020-08-24 11-49-30](https://user-images.githubusercontent.com/68699532/91074284-ec2dc600-e601-11ea-8ed7-81d335858c23.png)

**Additional context**
 i am trying to install deeplabcut on ubutu but i have a lot of problems, also i am beginner in DeepLabCut

**Comment by jeylau** [comment]
@Alberto100591, the strange part is that it says that no video is found for analysis. In the test folder just created, do you have extracted frames in labeled-data?

**Comment by MMathisLab** [comment]
related to his prior issue I believe: https://github.com/DeepLabCut/DeepLabCut/issues/869

**Comment by Alberto100591** [comment]
Ok it works thanks


Enviado desde Outlook<http://aka.ms/weboutlook>

________________________________
De: Jessy Lauer <notifications@github.com>
Enviado: miércoles, 26 de agosto de 2020 08:18 a. m.
Para: DeepLabCut/DeepLabCut <DeepLabCut@noreply.github.com>
CC: Alberto100591 <descargas117@outlook.com>; Mention <mention@noreply.github.com>
Asunto: Re: [DeepLabCut/DeepLabCut] FileNotFoundError (#868)


@Alberto100591<https://github.com/Alberto100591>, the strange part is that it says that no video is found for analysis. In the test folder just created, do you have extracted frames in labeled-data?
