### ISSUE TITLE
ValueError: ('Invalid augmenter type:', 'scalecrop')

### ISSUE THREAD

**Issue by Alberto100591** [DeepLabCut/DeepLabCut#869]
Hello my Name is Albert Moreno, in this moment i am trying to use DeepLabCut , but i have a problem when i am using DeepLabCut (in this moment i just followed the tutorial (https://www.youtube.com/watch?v=IOWtKn3l33s))

**Your Operating system and DeepLabCut version**
Ubuntu 20.04 LTS, with an Anaconda Env, & deeplabcut 2.1.8.2

**Describe the problem**

My problem occurs when appears the next message :
```

ValueError                                Traceback (most recent call last)
~/Desktop/DeepLabCut1/DeepLabCut/examples/testscript.py in <module>
    237 print("CREATING TRAININGSET")
    238 deeplabcut.create_training_dataset(
--> 239     path_config_file, net_type=net_type, augmenter_type=augmenter_type2
    240 )
    241 

~/anaconda3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py in create_training_dataset(config, num_shuffles, Shuffles, windows2linux, userfeedback, trainIndexes, testIndexes, net_type, augmenter_type)
    650             pass
    651         else:
--> 652             raise ValueError('Invalid augmenter type:', augmenter_type)
    653 
    654     import deeplabcut

ValueError: ('Invalid augmenter type:', 'scalecrop')
```
 

Please place code inside this:

<details><summary>Code output</summary><p>

```
[---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/Desktop/DeepLabCut1/DeepLabCut/examples/testscript.py in <module>
    237 print("CREATING TRAININGSET")
    238 deeplabcut.create_training_dataset(
--> 239     path_config_file, net_type=net_type, augmenter_type=augmenter_type2
    240 )
    241 

~/anaconda3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py in create_training_dataset(config, num_shuffles, Shuffles, windows2linux, userfeedback, trainIndexes, testIndexes, net_type, augmenter_type)
    650             pass
    651         else:
--> 652             raise ValueError('Invalid augmenter type:', augmenter_type)
    653 
    654     import deeplabcut

ValueError: ('Invalid augmenter type:', 'scalecrop')
]
```
</p></details>

**Comment by MMathisLab** [comment]
Hi, 

right now the repo is slightly ahead of 2.1.8.2, so you use the testscript you will need to pip install from the repo, so in your env just run:

pip install git+https://github.com/DeepLabCut/DeepLabCut.git 

then it will work!

**Comment by timtensor** [comment]
I have been trying to run the `testscript.py ` by enabling the DLC-CPU enviroment , and following the above mentioned steps. However i get the following error . 
`[1017 17:38:24 @parallel.py:366] ERR Exception '<class 'TypeError'>' in worker:`

And the training is stuck in the loop. I wonder if its a problem , running it in a CPU ? 
`[1017 17:38:24 @parallel.py:366] ERR Exception '<class 'TypeError'>' in worker:`

**Comment by sumankguha** [comment]
> Hi,
> 
> right now the repo is slightly ahead of 2.1.8.2, so you use the testscript you will need to pip install from the repo, so in your env just run:
> 
> pip install git+https://github.com/DeepLabCut/DeepLabCut.git
> 
> then it will work!

Ran into same issue, this solves it. Cheers!
