### ISSUE TITLE
tracklet GUI navigation hotkeys not working & missing labels in single frames

### ISSUE THREAD

**Issue by imgross** [DeepLabCut/DeepLabCut#873]
Hi there,

**My Operating system and DeepLabCut version**
Windows 10 with an Anaconda Env, & DeepLabCut 2.2b7, wx Python 4.0.7.post2, using maDLC working with the Project Manager GUI

**Describe the problem**
I have two questions regarding the refine tracklets GUI. 

1) When I load tracklets in and launch the GUI, the hotkeys for navigating through single frames are not working for me. I have tried out different keyboards and different computers, but could not solve the problem

2) What does it mean when single frames that were loaded into the tracklet GUI do not have any labels on the individual animals? Could it be that the network is not trained well enough?

Thanks for your support!

Best,
Isa

**Comment by backyardbiomech** [comment]
@jeylau can confirm, but I thought my pull request #810 was merged into the master a few weeks ago to fix the hotkey problem on Windows 10. You may have to install directly from GitHub if it hasn't been included in a pip release yet. Try "n" for next frame, "b" for back a frame, and space for play/pause. Details in #810 .

**Comment by jeylau** [comment]
@imgross, I confirm what @haliaetus13 says: you'll have to clone the repo using `pip install git+https://github.com/DeepLabCut/DeepLabCut.git` as 2.2b8 is not yet released.
As for the single frames with missing labels, perhaps min_hits > 1 in the inference_cfg.yaml; i.e., detections that are not matched by a tracker for at least 2 consecutive frames would be considered false alarms. This is no problem though, as you can set max_gap = 2 for example and fill these gaps of up to 2 frames.

**Comment by imgross** [comment]
okay great, thanks very much for the help! will test it out as soon as the labeling for my new project is done.
