### ISSUE TITLE
No working: python dlc.py  create-new-project,  no such option: -c

### ISSUE THREAD

**Issue by chenxinfeng4** [DeepLabCut/DeepLabCut#876]
While run the code like:

> python3 dlc.py create_new_project reaching-task Tanmay /data/videos/mouse1.avi /data/videos/mouse2.avi /data/videos/mouse3.avi /analysis/project/ -c False

It shows the ERROR:
> Usage: dlc.py create-new-project [OPTIONS] PROJECT EXPERIMENTER [VIDEOS]...
Try 'dlc.py create-new-project -h' for help.
>
> Error: no such option: -c

the source code in dlc.py, line [41] shows that:
```
@click.option(

    "--copy_videos/--dont_copy_videos",

    is_flag=True,

    default=True,

    help="Specify if you need to create the symlinks of the video and store in the videos directory. Default is True.",

)
```

There is no code option "-c"

**Comment by jeylau** [comment]
@chenxinfeng4, try with this command rather
`python3 dlc.py create-new-project reaching-task Tanmay /data/videos/mouse1.avi /data/videos/mouse2.avi /data/videos/mouse3.avi -d /analysis/project/ --dont_copy_videos`
create-new_project is spelled with dashes (we'll fix the typos in the example), you'll need -d to flag the destination directory and either --copy_videos or --dont_copy_videos (have a look here [https://github.com/DeepLabCut/DeepLabCut/blob/99155c7f1175c697c04093780fe546a1f17b91a2/deeplabcut/cli.py#L34](url) if needed) 😊
