### ISSUE TITLE
float division by zero error on create_labeled_video function [ path errors windows vs unix]

### ISSUE THREAD

**Issue by nschapp** [DeepLabCut/DeepLabCut#881]
**Your Operating system and DeepLabCut version**

Windows 10 Enterprise, Version 10.0.18363 Build 18363
Anaconda Env, DeepLabCut Version 2.1.8.2

**Describe the problem**

I'm encountering a divide by zero error consistently on the last step of the pipeline for deeplabcut, the create_labeled_videos step for different videos and projects created.  Error prevents the completion of this last step for processing data.  I've run this through the basic pipeline detailed in the "Demo your own data" section here on the Github, so I wanted to know if there was a variable that needed to be defined on by myself as the user, or if it's perhaps some other issue.  Posted below is the entire output of the command prompt for the previous attempt:
```
In [1]: import deeplabcut

In [2]: path_config_file = 'Social Interaction-Maha-2020-08-25/config.yaml'

In [3]: deeplabcut.evaluate_network(path_config_file, plotting=True)
Running  DLC_resnet50_Social InteractionAug25shuffle1_25000  with # of trainingiterations: 25000
Initializing ResNet
WARNING:tensorflow:From C:\Users\malavikalabuser\Anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\malavikalabuser\Anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\malavikalabuser\Anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\training\saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
WARNING:tensorflow:From C:\Users\malavikalabuser\Anaconda3\envs\DLC-CPU\lib\site-packages\tensorflow\python\training\saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from C:\Users\malavikalabuser\Social Interaction-Maha-2020-08-25\dlc-models\iteration-0\Social InteractionAug25-trainset95shuffle1\train\snapshot-25000
INFO:tensorflow:Restoring parameters from C:\Users\malavikalabuser\Social Interaction-Maha-2020-08-25\dlc-models\iteration-0\Social InteractionAug25-trainset95shuffle1\train\snapshot-25000
Analyzing data...
99it [04:32,  2.76s/it]
Done and results stored for snapshot:  snapshot-25000
Results for 25000  training iterations: 95 1 train error: 4.0 pixels. Test error: 22.78  pixels.
With pcutoff of 0.6  train error: 3.99 pixels. Test error: 22.01 pixels
Thereby, the errors are given by the average distances between the labels by DLC and the scorer.
Plotting...
100%|██████████████████████████████████████████████████████████████████████████████████| 99/99 [01:16<00:00,  1.30it/s]
The network is evaluated and the results are stored in the subdirectory 'evaluation_results'.
If it generalizes well, choose the best model for prediction and update the config file with the appropriate index for the 'snapshotindex'.
Use the function 'analyze_video' to make predictions on new videos.
Otherwise consider retraining the network (see DeepLabCut workflow Fig 2)

In [4]: videofile_path=['Videos/Maha/Maha_vid1.mp4']

In [5]: deeplab.analyze_videos(path_config_file, videofile_path, videotype='.mp4')
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-5-1e7f2377434b> in <module>
----> 1 deeplab.analyze_videos(path_config_file, videofile_path, videotype='.mp4')

NameError: name 'deeplab' is not defined

In [6]: deeplabcut.analyze_videos(path_config_file, videofile_path, videotype='.mp4')
Using snapshot-25000 for model C:\Users\malavikalabuser\Social Interaction-Maha-2020-08-25\dlc-models\iteration-0\Social InteractionAug25-trainset95shuffle1
Initializing ResNet
INFO:tensorflow:Restoring parameters from C:\Users\malavikalabuser\Social Interaction-Maha-2020-08-25\dlc-models\iteration-0\Social InteractionAug25-trainset95shuffle1\train\snapshot-25000
INFO:tensorflow:Restoring parameters from C:\Users\malavikalabuser\Social Interaction-Maha-2020-08-25\dlc-models\iteration-0\Social InteractionAug25-trainset95shuffle1\train\snapshot-25000
Starting to analyze %  Videos/Maha/Maha_vid1.mp4
Loading  Videos/Maha/Maha_vid1.mp4
Duration of video [s]:  119.99 , recorded with  100.0 fps!
Overall # of frames:  11999  found with (before cropping) frame dimensions:  1920 1200
Starting to extract posture
12019it [8:20:51,  2.53s/it]                                                                                           Detected frames:  11999
12019it [8:25:15,  2.52s/it]
Saving results in Videos\Maha...
The videos are analyzed. Now your research can truly start!
 You can create labeled videos with 'create_labeled_video'.
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract any outlier frames!
Out[6]: 'DLC_resnet50_Social InteractionAug25shuffle1_25000'

In [7]:  deeplabcut.create_labeled_Video(path_config_file, videofile_path)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-8cc0b6979ab3> in <module>
----> 1 deeplabcut.create_labeled_Video(path_config_file, videofile_path)

AttributeError: module 'deeplabcut' has no attribute 'create_labeled_Video'

In [8]:  deeplabcut.create_labeled_video(path_config_file, videofile_path)
Starting %  Videos\Maha ['Videos/Maha/Maha_vid1.mp4']
Loading  Videos/Maha/Maha_vid1.mp4 and data.
The video was not analyzed with this scorer: DLC_resnet50_Social InteractionAug25shuffle1_25000
Other scorers were found, however: ['Maha_vid1DLC_resnet50_Social InteractionAug25shuffle1_25000.h5']
Creating output for: DLC_resnet50_Social InteractionAug25shuffle1_25000  instead.
warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:940)
warning: Videos/Maha/Maha_vid1.mp4 (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:941)
0
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-8-d8d98a0e91a1> in <module>
----> 1 deeplabcut.create_labeled_video(path_config_file, videofile_path)

~\Anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\utils\make_labeled_video.py in create_labeled_video(config, videos, videotype, shuffle, trainingsetindex, filtered, save_frames, Frames2plot, delete, displayedbodyparts, codec, outputframerate, destfolder, draw_skeleton, trailpoints, displaycropped)
    395                     else: #then the full video + the (perhaps in cropped mode analyzed labels) are depicted
    396                         clip = vp(fname = video,sname = videooutname,codec=codec)
--> 397                         CreateVideo(clip,Dataframe,cfg["pcutoff"],cfg["dotsize"],cfg["colormap"],DLCscorer,bodyparts,trailpoints,cropping,x1,x2,y1,y2,bodyparts2connect,skeleton_color,draw_skeleton,displaycropped)
    398
    399     os.chdir(str(start_path))

~\Anaconda3\envs\DLC-CPU\lib\site-packages\deeplabcut\utils\make_labeled_video.py in CreateVideo(clip, Dataframe, pcutoff, dotsize, colormap, DLCscorer, bodyparts2plot, trailpoints, cropping, x1, x2, y1, y2, bodyparts2connect, skeleton_color, draw_skeleton, displaycropped)
     71         fps=clip.fps()
     72         nframes = len(Dataframe.index)
---> 73         duration = nframes/fps
     74
     75         print("Duration of video [s]: ", round(duration,2), ", recorded with ", round(fps,2),"fps!")

ZeroDivisionError: float division by zero

In [9]:                 
```

**Comment by MMathisLab** [comment]
(1) your video is possibly corrupted, so the FPS is not recorded correctly. You can set the FPS. For every function you need to type a `?` to get all the functionality:

`deeplabcut.create_labeled_video?`

(2) ffmpeg is not super robust to spaces in filenames, such as `DLC_resnet50_Social Interaction`; as we ask, please do not create projects or video with spaces or special characters.

**Comment by nschapp** [comment]
I do not believe the video is corrupted, and I have done this with two different videos now recorded entirely separately and gotten the same error.

Also, if it would help find the problem, after I encounter this error, for some reason the path_config_file variable I set becomes 'not found' if referenced again in another command line, despite working fine prior and still existing in the same location in my directory as prior.

I could try and rename the files to remove spaces.  As I have already done manual labeling, would it be possible to do this without redoing the whole project?  Besides the name of the project folder and the name given within the config file, would anything else need to be changed.

**Comment by MMathisLab** [comment]
can you first run: `pip install --upgrade deeplabcut` and then run: `import deeplabcut` then: `deeplabcut.__version__` and past the result?

**Comment by MMathisLab** [comment]
also, I assume you edited this for privacy, but if this is your path, this is wrong in the example above: `path_config_file = 'Social Interaction-Maha-2020-08-25/config.yaml'` 

your path MUST be `path_config_file = '/yourComputer/yourFolder/Social Interaction-Maha-2020-08-25/config.yaml'` i.e. the FULL path to the file. 

And, if you are using Windows as you say, it's really wrong ;) 

it must be: 

`path_config_file = r'C:\yourComputer\yourFolder\Social Interaction-Maha-2020-08-25\config.yaml'`

this is also wrong too:  `videofile_path=['Videos/Maha/Maha_vid1.mp4']`
```
warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:940)
warning: Videos/Maha/Maha_vid1.mp4 (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:941)
```
please see the docs here: 
https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/functionDetails.md#a-create-a-new-project

>>NOTE: Windows users, you must input paths as: r'C:\Users\computername\Videos\reachingvideo1.avi' or

>>'C:\\Users\\computername\\Videos\\reachingvideo1.avi'

**Comment by nschapp** [comment]
So a few things.  A few of these might be errors of translating code intended for a non-Windows system to a Windows system, although it seems strange that I was able to get all the way to the create_labeled_video step if my path_config_file was improperly labeled (I did not edit it for privacy, that was the specified path in my command window).  My understanding was that in specifying paths in the directory the computer should automatically start in the folder of the logged-in user unless specified otherwise.  I can try with your correction, however, I think there was a pretty big issue with the pip install --upgrade deeplabcut command as my current method of activating deeplabcut doesn't seem to work anymore after running that, and there were quite a few errors (code will be posted at the bottom).

For reference, I used the installation method where I have an env dlc I activate first in conda before I run ipython (in this case, conda activate dlc.cpu).  That could be another source of errors if this is an unintended install method.  I could try just reinstalling the entire setup if needed, but I can post the code here to see if you can make anything of it.

(base) C:\Users\malavikalabuser>pip install --upgrade deeplabcut

**Comment by MMathisLab** [comment]
Firstly, please don't dump thousands of lines of code here. If you ever need to do this, you need to use the template provided for such a "dump," - in short, my job is not to be tech support ;). DLC is platform independent. There are no issues with it being a "non-Windows system." We are clear in the docs exactly what is required.

Here is how you do that, for the future: 

<details><summary>TRACEBACK</summary><p>

```python

^do not delete above
[ Please place code inside this!!!
PLACE YOUR CODE HERE!!!  ]
do not delete below:

```
</p></details>


Secondly, you must only run pip upgrade INTO your environment. Now you have it in (base). IN base, run `pip uninstall deeplabcut`

Secondly, some parts of the code can be forgiving, but the docs are not suggestions. when we say you must input the full path, we do mean it; you can create bad install, bad training files, etc etc etc... 

I'm 100% sure your errors are path/user input errors, and not a bug in the code based on all that you have posted.

**Comment by nschapp** [comment]
Gotcha, sorry about the big dump.  I will try your recommendation and hopefully get the code to run again.
