### ISSUE TITLE
How to compare results when different training data sets are different in the same data?

### ISSUE THREAD

**Issue by Jungjihyuk** [DeepLabCut/DeepLabCut#882]
When A is trained model using 150 data and B is trained model using 100 data, I try to compare the A with B.
Is there any way to reuse the A data without newly labelling data? 

And I have one more question. 
how to evaluate between two models? 
Just compare train/test error?  

Please let me know how to do. Thank you.

**Comment by MMathisLab** [comment]
thanks for the question; in general please post questions here: https://forum.image.sc/tags/deeplabcut

to answer, we have a model_comparision function you should use: https://github.com/DeepLabCut/DeepLabCut/wiki/What-neural-network-should-I-use%3F#how-can-i-compare-them

**Comment by AlexEMG** [comment]
I'm giving the updated answer: MODEL COMPARISON: You can also test several models by creating the same test/train split for different networks. You can easily do this in the Project Manager GUI, or use the function deeplabcut.create_training_model_comparison.

see here: https://deeplabcut.github.io/DeepLabCut/docs/standardDeepLabCut_UserGuide.html?highlight=comparison#deeplabcut.generate_training_dataset.trainingsetmanipulation.create_training_model_comparison
