### ISSUE TITLE
tracklet GUI usage and network refinement

### ISSUE THREAD

**Issue by imgross** [DeepLabCut/DeepLabCut#884]
Hi there,

**Your Operating system and DeepLabCut version**
Windows 10 with an Anaconda Env, & DeepLabCut 2.2b7, wx Python 4.0.7.post2, using maDLC working with the Project Manager GUI

I have a question regarding the usage of the tracklet GUI. 

Is the idea of the GUI, that you check the trajectories for every single video in the tracklet GUI and refine tracklets? Or should one do that for a couple of videos and then feed that back into network training, so that in the end you can use the network for all your videos, without having to using the tracklet GUI anymore? In that case, could you let me know what the best way of doing that is? I could not find this in the documentation.

Best wishes,
Isa

**Comment by MMathisLab** [comment]
Hi @imgross please post questions on the user forum: https://forum.image.sc/tags/deeplabcut 

We ask to reserve github for bug reports (see here: https://github.com/DeepLabCut/DeepLabCut#community-support-developers--help)

**Comment by MMathisLab** [comment]
also, note this is documented here, i,e, you should optimize parameters on a few short videos, then just auto-covert them. 

https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/functionDetails.md#madeeplabcut-critical-point---assemble--refine-tracklets

>> Lastly, let's say you've optimized the inference_cfg.yaml (i.e., tracking) parameters, and you want to just apply this to a set of videos and by-pass the tracklet GUI, you can pass the pickle file directly from analyze_videos (and your config.yaml full path) and run:

>> deeplabcut.convert_raw_tracks_to_h5(config_path, picklefile)
