### ISSUE TITLE
RMSE for individual body parts

### ISSUE THREAD

**Issue by blogeman** [DeepLabCut/DeepLabCut#885]
After training a model one can evaluate model performance by examining the RMSE of both the TRAIN and TEST data. I assume that the numbers reported are an aggregate of all body parts.

Is it possible to evaluate the RMSE (or other metric) for each body part individually?

**Comment by MMathisLab** [comment]
yes, you can pass which bodyparts to evaluate: `comparisonbodyparts="all"` is the default. 

For any fucntion, you can check the docstring in ipython by 

`deeplabcut.evaluate_network?

which then shows all the options and how to use them, 
```
( config,
    Shuffles=[1],
    trainingsetindex=0,
    plotting=None,
    show_errors=True,
    comparisonbodyparts="all",
    gputouse=None,
    rescale=False,
    modelprefix="",
    c_engine=False,
):
```

**Comment by AlexEMG** [comment]
Also in 2.2 this is now a possibility, see here: https://github.com/DeepLabCut/DeepLabCut/pull/716

Great to see you @blogeman on this platform :)

**Comment by blogeman** [comment]
This is great, thanks @MMathisLab and @AlexEMG! Just getting started using DLC and amazed at what it can do
