### ISSUE TITLE
3D Deeplabcut problem

### ISSUE THREAD

**Issue by Alberto100591** [DeepLabCut/DeepLabCut#886]
**Operation Systems**

Ubuntu 20.04 LTS, with an Anaconda Env, & deeplabcut 2.1.8.2

**Describe the problem**

Hello my name is Alberto Moreno, today ,i request your help with a problem that i will describe.

Problem:
In this moment i am working with 3D DeepLabCut, so i followed the instructions (https://github.com/DeepLabCut/DeepLabCut/blob/a3ff917fc04ae0199b051b1d0cc2f75c3700191a/docs/Overviewof3D.md ) ,everything was going fine until, i run the next command:

deeplabcut.calibrate_cameras(config_path3d,cbrow=8,cbcol=6,calibrate=False,alpha=0.4)

Then terminal shows me the next error:

**Code OUTPUT**

<details><summary>FileNotFoundError                         Traceback (most recent call last)
<ipython-input-9-8e9d0546cf06> in <module>
----> 1 deeplabcut.calibrate_cameras(config_path3d, cbrow=8, cbcol=6, calibrate=True, alpha=0.9)

~/anaconda3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/pose_estimation_3d/camera_calibration.py in calibrate_cameras(config, cbrow, cbcol, calibrate, alpha)
     73 
     74     # Read the config file
---> 75     cfg_3d = auxiliaryfunctions.read_config(config)
     76     img_path,path_corners,path_camera_matrix,path_undistort=auxiliaryfunctions_3d.Foldernames3Dproject(cfg_3d)
     77 

~/anaconda3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/utils/auxiliaryfunctions.py in read_config(configname)
    130     else:
    131         raise FileNotFoundError(
--> 132             "Config file is not found. Please make sure that the file exists and/or that you passed the path of the config file correctly!")
    133     return (cfg)
    134 

FileNotFoundError: Config file is not found. Please make sure that the file exists and/or that you passed the path of the config file correctly!</summary><p>

</p></details>

**How to Reproduce the problem**
In [1]: import deeplabcut                                                                                                                                                              
In [2]: import os                                                                                                                                                                      
In [3]: from pathlib import Path 
In [5]: config_path3d=os.path.join(os.getcwd(),'Project1-NameofLabele1r-2020-08-25-3d/config.yaml')    

**Screenshots**
![image](https://user-images.githubusercontent.com/68699532/92021088-d2396500-ed1e-11ea-9dda-ff66dbedd902.png)

**Additional context**
In the picture we can appreciate which commands i used, but i did not find the mistake , please somebody could help me?

**Comment by MMathisLab** [comment]
you have not passed the `config_path3d` correctly, i.e. you need to pass the full path, with a single quote to start and stop:

`deeplabcut.calibrate_cameras('/yourfullpath/Project1-NameofLabele1r-2020-08-25-3d/config.yaml', cbrow=8, cbcol=6, calibrate=True, alpha=0.9)`
