### ISSUE TITLE
question about training data shape

### ISSUE THREAD

**Issue by amaanda** [DeepLabCut/DeepLabCut#888]
Hello,

I am currently trying to train dlc using a custom dataset containing images from different sizes. From the tutorials, I do understand that the network can accept different resolutions, but is that a problem to have different resolutions within the same training data? If so, I would appreciate any suggestions on how to overcome this problem.

My data is originated from a number of different videos, and the input I am giving DLC is the ROI of the frames.

Thank you.

**Comment by MMathisLab** [comment]
Hi @amaanda  please post questions on the user forum: https://forum.image.sc/tags/deeplabcut

We ask to reserve github for bug reports (see here: https://github.com/DeepLabCut/DeepLabCut#community-support-developers--help)

but, yes, you can run batchsize=1 and use any frame sizes / resolutions you want, and any number of cameras. These do not need to be the same as the videos you then run analysis on later (i.e., they also can have any size/shape).
