### ISSUE TITLE
ResolvePackageNotFound when creating env from dlcdependencieswTF1.2.yml

### ISSUE THREAD

**Issue by hengzhangmiivii** [DeepLabCut/DeepLabCut#89]
Running 'conda env create -f dlcdependencieswTF1.2.yml', many packages fail from ResolvePackageNotFound.
ResolvePackageNotFound:
  - xz==5.2.4=h14c3975_4
  - tk==8.6.7=hc745277_3
  - zlib==1.2.11=ha838bed_2
  - openssl==1.0.2o=h20670df_0
  - libffi==3.2.1=hd88cf55_4
  - libedit==3.1.20170329=h6b74fdf_2
  - libstdcxx-ng==7.2.0=hdf63c60_3
  - ncurses==6.1=hf484d3e_0
  - python==3.6.5=hc3d631a_2
  - libgcc-ng==7.2.0=hdf63c60_3
  - sqlite==3.24.0=h84994c4_0
  - readline==7.0=ha6073c6_4

my computer env is :
mac os 10.14
tensorflow 1.10

How can I resovel this problem?

**Comment by MMathisLab** [comment]
We don’t support MacOS at this time - one file is for Ubuntu and one for Windows ( You could create your own environment and install the required packages though ).

**Comment by hengzhangmiivii** [comment]
got it. thanks
