### ISSUE TITLE
Creating a New Project

### ISSUE THREAD

**Issue by Marvellous12** [DeepLabCut/DeepLabCut#890]
Hello, 
I tried creating a new project and was able to get to this step but after answering no to the query, it proceeds to say that the frame extraction failed. I checked the video and it does not seem to be corrupted. Attach below is the code

deeplabcut.extract_frames(config_path,'automatic','kmeans')
Config file read successfully.
Do you want to extract (perhaps additional) frames for video: D:\deeplabcut\demo-Marvellous-2020-09-08\videos\ET131566_RB391_S10322.avi ?
yes/no=no
Do you want to extract (perhaps additional) frames for video: D:\deeplabcut\demo-Marvellous-2020-09-08\videos\ET131566_RB412_S11616.avi ?
yes/no= no
Frame extraction failed. Video files must be corrupted.

**Comment by MMathisLab** [comment]
if you say no, then it aborts extracting frames. Curious why you say no?

**Comment by AlexEMG** [comment]
Good point -- now it prints: "Frames were successfully extracted, for the videos of interest.", if you type "no" for all videos...

**Comment by Marvellous12** [comment]
Thank you!
