### ISSUE TITLE
When running plotting = True get 'The filename or extension is too long' error

### ISSUE THREAD

**Issue by wweertman** [DeepLabCut/DeepLabCut#891]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). 
Please fill out the template completely, including the full "TRACEBACK" and input code that you ran to hit this error.

**Describe the bug**

When I run deeplabcut.evaluate_network(path_config, plotting = True) I get FileNotFoundError: [WinError 206] The filename or extension is too long. Additionally, only the .h5 file file is created in the evaluation-results folder, no .csv file is created. If I run with plotting = False the .csv file gets created (so the filename error is hit before the .csv file is created). 

Please provide the minimal required code to reproduce the error and the full output (please edit ONLY the section below that says `PLACE YOUR CODE HERE!!! `.

**Desktop (please complete the following information about your system):**
 - OS: [e.g. Windows10, MacOS version, Linux, etc.]
 - DeepLabCut Version [e.g. 22] (please check with ``import deeplabcut``, ``deeplabcut.__version__``)
 - Browser, if applicable [e.g. chrome, safari]

OS: Windows 10 Pro
Deeplabcut version:  2.1.6.3 
Browser: Chrome

**To Reproduce**
Steps to reproduce the behavior, i.e.:
4. the input code you used (i.e. `deeplabcut.train_network( .... )`)
4. See error:

<details><summary>TRACEBACK</summary><p>

```python

Please place code inside this!!!
PLACE YOUR CODE HERE!!!  

path_config = r"C:\Users\wlwee\Documents\python\fhl_flume_dlc\MODELS\eyes_and_mantle_tip-weertman-2020-09-05\config.yaml"

deeplabcut.evaluate_network(path_config, 
                            plotting = True)

```
</p></details>

deeplabcut.evaluate_network(path_config, plotting = True)
Config:
{'all_joints': [[0], [1], [2]],
 'all_joints_names': ['left_eye', 'right_eye', 'mantle_tip'],
 'batch_size': 1,
 'bottomheight': 400,
 'crop': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_eyes_and_mantle_tipSep5\\eyes_and_mantle_tip_weertman95shuffle1.mat',
 'dataset_type': 'default',
 'deconvolutionstride': 2,
 'deterministic': False,
 'display_iters': 1000,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'C:\\Users\\wlwee\\Anaconda3\\envs\\DLC-GPU\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_eyes_and_mantle_tipSep5\\Documentation_data-eyes_and_mantle_tip_95shuffle1.pickle',
 'min_input_size': 64,
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 3,
 'optimizer': 'sgd',
 'output_stride': 16,
 'pos_dist_thresh': 17,
 'project_path': 'C:\\Users\\wlwee\\Documents\\python\\fhl_flume_dlc\\MODELS\\eyes_and_mantle_tip-weertman-2020-09-05',
 'regularize': False,
 'rightwidth': 400,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'C:\\Users\\wlwee\\Documents\\python\\fhl_flume_dlc\\MODELS\\eyes_and_mantle_tip-weertman-2020-09-05\\dlc-models\\iteration-0\\eyes_and_mantle_tipSep5-trainset95shuffle1\\test\\snapshot',
 'stride': 8.0,
 'topheight': 400,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Running  DLC_resnet50_eyes_and_mantle_tipSep5shuffle1_300000  with # of trainingiterations: 300000
Initializing ResNet
INFO:tensorflow:Restoring parameters from C:\Users\wlwee\Documents\python\fhl_flume_dlc\MODELS\eyes_and_mantle_tip-weertman-2020-09-05\dlc-models\iteration-0\eyes_and_mantle_tipSep5-trainset95shuffle1\train\snapshot-300000
0it [00:00, ?it/s]Analyzing data...
329it [00:57,  5.76it/s]
Done and results stored for snapshot:  snapshot-300000
Results for 300000  training iterations: 95 1 train error: 2.36 pixels. Test error: 3.26  pixels.
With pcutoff of 0.6  train error: 2.36 pixels. Test error: 3.26 pixels
Thereby, the errors are given by the average distances between the labels by DLC and the scorer.
Plotting...
Traceback (most recent call last):

  File "<ipython-input-19-9370bd4d741b>", line 1, in <module>
    deeplabcut.evaluate_network(path_config, plotting = True)

  File "C:\Users\wlwee\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\evaluate.py", line 385, in evaluate_network
    auxiliaryfunctions.attempttomakefolder(foldername)

  File "C:\Users\wlwee\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py", line 187, in attempttomakefolder
    os.mkdir(foldername)

FileNotFoundError: [WinError 206] The filename or extension is too long: 'C:\\Users\\wlwee\\Documents\\python\\fhl_flume_dlc\\MODELS\\eyes_and_mantle_tip-weertman-2020-09-05\\evaluation-results\\iteration-0\\eyes_and_mantle_tipSep5-trainset95shuffle1\\LabeledImages_DLC_resnet50_eyes_and_mantle_tipSep5shuffle1_300000_snapshot-300000'

**Expected behavior**

plotting: bool, optional
    Plots the predictions on the train and test images. The default is ``False``; if provided it must be either ``True`` or ``False``

**Screenshots**
If applicable, add screenshots to help explain your problem. (but please post the code output above!)

**Additional context**

The images I am analyzing have a resolution of 1920x1200 so perhaps I need to change the max input size?

**Comment by AlexEMG** [comment]
FileNotFoundError: [WinError 206] The filename or extension is too long: 'C:\Users\wlwee\Documents\python\fhl_flume_dlc\MODELS\eyes_and_mantle_tip-weertman-2020-09-05\evaluation-results\iteration-0\eyes_and_mantle_tipSep5-trainset95shuffle1\LabeledImages_DLC_resnet50_eyes_and_mantle_tipSep5shuffle1_300000_snapshot-300000'


>> the file name is indeed to long. Windows does not allow file names with more than 250 characters.

**Comment by wweertman** [comment]
ah, of course, thank you :)
is there an easy way to rename a project?

**Comment by AlexEMG** [comment]
Yes, you can just copy it somewhere else and then just change the project folder!
