### ISSUE TITLE
Batch Processing Script Example

### ISSUE THREAD

**Issue by YesterdaySam** [DeepLabCut/DeepLabCut#894]
The Wiki section on Batch Processing your Analysis indicates it should be possible to iterate through new videos outside the training set stored outside the main DLC project folder where an existing trained network and config file are stored.
The example script (https://github.com/AlexEMG/DLCutils/blob/master/scale_analysis_oversubfolders.py) provided in the link on that wiki page could not be found as of 9/9/2020.
An updated link would be much appreciated. Thank you!

**Comment by MMathisLab** [comment]
https://github.com/DeepLabCut/DLCutils/tree/master/SCALE_YOUR_ANALYSIS 

sorry, did some reshuffling of DLCUtils; I'll update the wiki link.
