### ISSUE TITLE
ERROR in "pose_cfg.yaml > project_path" while using GUI “Train Network”

### ISSUE THREAD

**Issue by chenxinfeng4** [DeepLabCut/DeepLabCut#895]
**Describe the bug**

ERROR in GUI “Train Network”, there is an error in "pose_cfg.yaml" --> the "project_path" is not correct.

**Desktop (please complete the following information about your system):**
 - OS:  Windows10
 - DeepLabCut Version 2.2b8

**To Reproduce**
Steps to reproduce the behavior, i.e.:
1. Go to deeplabcut.launch_dlc(). After finish "Create training dataset", I choosed "Train Network". However it report the error:

![image](https://user-images.githubusercontent.com/17546446/92683113-9e84bd80-f364-11ea-9378-9cb6b4e3390b.png)

2. Than I opened the 'dlc-models\iteration-0\crossMazeSep10-trainset80shuffle1\train\pose_cfg.yaml', and saw the context in the pose_cfg.yaml.
![image](https://user-images.githubusercontent.com/17546446/92683190-d55ad380-f364-11ea-84c2-5d0dabdd6e64.png)

3. The "project_path" is just the error, so I must manually corrected it everytime:
>project_path: E:\cxf\crossMaze-FanLab-2020-09-10

<details><summary>TRACEBACK</summary><p>

**Comment by jeylau** [comment]
Good catch @chenxinfeng4! I have just pushed a fix 😊.
