### ISSUE TITLE
To add a supplementary bodypart after training.

### ISSUE THREAD

**Issue by Agulore** [DeepLabCut/DeepLabCut#898]
Hi,

Is it possible to add another bodypart after a training? 
I realized I need to add it after seeing the result of the training, but I would like to not start from scratch.
Can I just modify the config file? Will it appear maybe on the refining process to add it to the training?

Best

**Comment by MMathisLab** [comment]
yep! just add them to you config.yaml file, then open the labeling GUI. It will automatically ask you want to you want to see, i.e. display all or just the new ones to be labeled. Then you can re-train.
