### ISSUE TITLE
deeplabcut.triangulate

### ISSUE THREAD

**Issue by Alberto100591** [DeepLabCut/DeepLabCut#899]
Hello my name is Alberto, today i would like to request help with the followed problem, but first i will describe it

*My Operating system and DeepLabCut version**
Ubuntu 20.04 LTS, with an Anaconda Env, & deeplabcut 2.1.8.2

Please complete the following information about your system:

OS: [Ubuntu 20.04 LTS]
Deeplabcut 2.1.8.2
Anaconda env used:

**Describe the problem**

In this moment i am working with 3D DeepLabCut, so i followed the instructions (https://github.com/DeepLabCut/DeepLabCut/blob/a3ff917fc04ae0199b051b1d0cc2f75c3700191a/docs/Overviewof3D.md ) ,everything was going fine until, i run the next command:

### **_deeplabcut.triangulate('/home/dell1/Desktop/DeepLabCut1/Project1-NameofLabele1r-2020-08-25-3d/config.yaml', '/home/dell1/Desktop/DeepLabCut1/Project1-NameofLabele1r-2020-08-25-3d', filterpredictions=False)_**

It is important to say, that i have my videos ready, so would like to ask for help.  because when i type the previous command i get the next answer from deeplabcut

Please place code inside this:

<details><summary>In [11]: deeplabcut.triangulate('/home/dell1/Desktop/DeepLabCut1/Project1-NameofLabele1r-2020-08-25-3d/config.yaml', '/home/dell1/Desktop/DeepL
    ...: abCut1/Project1-NameofLabele1r-2020-08-25-3d', filterpredictions=False)                                                               
Strange naming convention on your part. Respect.

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-11-bf8937fe34e6> in <module>
----> 1 deeplabcut.triangulate('/home/dell1/Desktop/DeepLabCut1/Project1-NameofLabele1r-2020-08-25-3d/config.yaml', '/home/dell1/Desktop/DeepLabCut1/Project1-NameofLabele1r-2020-08-25-3d', filterpredictions=False)

~/anaconda3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/pose_estimation_3d/triangulation.py in triangulate(config, video_path, videotype, filterpredictions, filtertype, gputouse, destfolder, save_as_csv)
     95     if isinstance(video_path, str)==True:
     96         flag=True
---> 97         video_list = auxiliaryfunctions_3d.get_camerawise_videos(video_path,cam_names,videotype=videotype)
     98     else:
     99         video_list = video_path

~/anaconda3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/utils/auxiliaryfunctions_3d.py in get_camerawise_videos(path, cam_names, videotype)
    131                     putativecam2name=os.path.join(path,pref+cam_names[1]+suf+ending)
    132             #print([os.path.join(path,pref+cam+suf+ending),putativecam2name])
--> 133             if os.path.isfile(putativecam2name):
    134                 #found a pair!!!
    135                 video_list.append([os.path.join(path,pref+cam+suf+ending),putativecam2name])

UnboundLocalError: local variable 'putativecam2name' referenced before assignment
</summary><p>

[Please copy/paste the full terminal output of the error here!!!]

</p></details>

**How to Reproduce the problem**
import deeplabcut
import os
from pathlib import Path
config_path3d=os.path.join(os.getcwd(),'Project1-NameofLabele1r-2020-08-25-3d/config.yaml')
print(config_path3d)   
deeplabcut.calibrate_cameras('/home/dell1/Desktop/DeepLabCut1/Project1-NameofLabele1r-2020-08-25-3d/config.yaml', cbrow=7, cbcol=7, calibrate=False, alpha=0.9) 
deeplabcut.calibrate_cameras('/home/dell1/Desktop/DeepLabCut1/Project1-NameofLabele1r-2020-08-25-3d/config.yaml', cbrow=7, cbcol=7, calibrate=True, alpha=0.9) 
import matplotlib
%matplotlib inline
deeplabcut.check_undistortion('/home/dell1/Desktop/DeepLabCut1/Project1-NameofLabele1r-2020-08-25-3d/config.yaml', cbrow=7, cbcol=7)  

**Screenshots**
![DeeplabcutTRingulation](https://user-images.githubusercontent.com/68699532/92812586-2975b000-f385-11ea-95f5-ca7972166987.jpg)

**Comment by MMathisLab** [comment]
yes, you will get the error: `Strange naming convention on your part. Respect.`

when you don't have videos that conform to the guidelines. Firstly, you need to have the videos the folder that you pass, and they need to have the same root name and differ in the camera name - otherwise, how can we pair them?

 See docs here for full overview:

https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/Overviewof3D.md#4-triangulation----take-your-2d-to-3d
