### ISSUE TITLE
counting frames in MakingLabeledVideo is slow

### ISSUE THREAD

**Issue by sneakers-the-rat** [DeepLabCut/DeepLabCut#9]
quick fix - line 93 in MakingLaveledVideo is:

`nframes = np.sum(1 for j in clip.iter_frames())`

which is slow (8.4s for a 2 minute video) because it has to iterate through frames in the video.

`nframes = np.ceil(clip.fps*clip.duration).astype(np.int)` 

gives identical results in 0.0002 seconds.

**Comment by AlexEMG** [comment]
Thanks @sneakers-the-rat , I agree! However, I had tried a similar implementation in the past, but found it can be inaccurate by +/- 1 frames from time to time... But I guess to improve speed one could add some safety factor (+1) and then check in the loop below where to stop!

**Comment by AlexEMG** [comment]
Updated the code.
