### ISSUE TITLE
"Tracklet filter" did not work on "create video"

### ISSUE THREAD

**Issue by chenxinfeng4** [DeepLabCut/DeepLabCut#900]
OS: Windows 10
DeepLabCut Version:2.2b8

**Describe the problem**
I've applied "GUI > Refine tracklets > max gap to fill =7", and then I did the "GUI > Create video > Use filtered=Yes".
However, that "gap filter" did not work on "create video". What' more, the filter-created video seems no smoother compared to the "non filter" option.

**Screen Shoot** 
max gap to fill =7, but still loss label in these 3-frames.
![image](https://user-images.githubusercontent.com/17546446/92859002-4ebbfa00-f429-11ea-9688-afc129a0138a.png)
![image](https://user-images.githubusercontent.com/17546446/92859239-98a4e000-f429-11ea-9cec-4167282b1aac.png)

Should I edit the "config.yaml" file, and how??

**Comment by MMathisLab** [comment]
The gap filler is only when you load the tracklet GUI, hence with the pickle file. Then, once you click save, you get an .h5 file. Then, you can click "filter" at the bottom of the same screen. 

then you get a filtered.h5 file that is used in the next tab. 

See here, you need to run Step 2: 

<img width="1283" alt="Screen Shot 2020-09-11 at 11 24 49 AM" src="https://user-images.githubusercontent.com/28102185/92902273-6abb9d80-f421-11ea-8c6a-7d2df4f55d94.png">

**Comment by chenxinfeng4** [comment]
**Problem not resolved!**
I have run the "Step1 & Step2 in [Refine tracklets]", and got the "filtered.h5" and "filtered.csv" at the same time.

I did the procedure below:

![image](https://user-images.githubusercontent.com/17546446/92924841-25708d80-f46c-11ea-928e-d06c93ac1828.png)

![image](https://user-images.githubusercontent.com/17546446/92924352-62885000-f46b-11ea-9f07-7c3cd2ba1524.png)


But I still got the same result, it still did not work on "create video"

**Comment by MMathisLab** [comment]
okay thanks for clarify, we will look into it!

Also, note that if you want EVERY thing filled in you need to set gap to ZERO: https://www.youtube.com/watch?v=YSRQT8N2vFE

**Comment by jeylau** [comment]
Hello @chenxinfeng4! Missing data were correctly filled (as they are present in the output file). By default though, we decided to assign these artificial points a very low confidence (0.01); you would need to change pcutoff in your config.yaml to visualize them in the video.

**Comment by chenxinfeng4** [comment]
**Oh, it really works for me**. Now the video is correctly labeled after changing "pcutoff". It's very nice of you.

Besides, I hope you to add this operation into your documents. I see no such statement in your DOCs nor YOUTUBE.
