### ISSUE TITLE
After TRACKLETS  analysis, need to summery animal in certain ROIs.

### ISSUE THREAD

**Issue by chenxinfeng4** [DeepLabCut/DeepLabCut#901]
**Is your feature request related to a problem? Please describe.**
After got perfect "TRACKLETS.CSV" and ".H5", I need to calculate when and how long the animal be in a REGION.  Just like the ANYMAZE. That can be helpful for the common [open field & elevated cross maze & water maze] tests.

Is there any down-stream software of Deeplabcut to do this ROI summery for TRACKLETS? I guest python-video-annotator might suite for it, not sure. Any suggestions?

Thanks,

**Comment by MMathisLab** [comment]
we suggest posting questions to other users here: https://forum.image.sc/tags/deeplabcut and check out the helper packages here: https://github.com/DeepLabCut/DLCutils including ROI tools. 


Glad to hear it;s working well for you - if you have a nice video you can share on twitter, it is appreciated :) @deeplabcut
