### ISSUE TITLE
DeepLabCut Live "Request of Help"

### ISSUE THREAD

**Issue by Alberto100591** [DeepLabCut/DeepLabCut#902]
Hello my name is Alberto Moreno, currently I am working with deepLabCut live but i newbie with deeplabcut , so I have a few questions, so i wonder if you can help me with followed questions.

My Operating system and DeepLabCut version*
Ubuntu 20.04 LTS, with an Anaconda Env, & deeplabcut 2.1.8.2

**Describe the problem**

1.-I would like to run a example, so I located the examples in the followed direction **_“/home/dell1/Desktop/DeepLabCut-live/example_processors”_**, my question is in the option of Proccesor, should I put the direction where are the examples **“/home/dell1/Desktop/DeepLabCut-live/example_processors”** ?, in other words, what I have to select in Proccesor Dir?

![live1](https://user-images.githubusercontent.com/68699532/92953644-b40eeb80-f427-11ea-9b55-ddcf33de1381.jpg)

2.-   I am going to describe my  problem :

In the section of DeepLabCut , I selected Edit DLC Setting , then DLC settings  windows appeared, so my question is , What I should select for **_Model path_**?, I should select the folder which have the examples in my case :
**_“/home/dell1/Desktop/DeepLabCut-live/example_processors”_**    

![d2](https://user-images.githubusercontent.com/68699532/92953680-c38e3480-f427-11ea-8540-482a5462413b.jpg)

**_Sorry to ask too much, but I'm new to this_**

**Comment by MMathisLab** [comment]
Hi @Alberto100591 could you please post this issue in the DLC-live repo; the authors are not overlapping, so you will get DLC-lIve help there! 

(but the model path is the exported dlc model you have made, or you can download some demos from us)
