### ISSUE TITLE
During Saving the Labels: stuck after SAVE/QUIT the GUI   

### ISSUE THREAD

**Issue by juliencatanese** [DeepLabCut/DeepLabCut#903]
**My Operating system and DeepLabCut version**
OS: Windows 10
DeepLabCut Version: 2.2b8 
conda version: 4.8.3

Anaconda env used: 
I Installed Anaconda from: https://www.anaconda.com/distribution/) 
During Anaconda install I chose to add Anaconda to my PATH environment variable.
I used: Python 3.8, 64-Bit Graphical Installer (466 MB)
then in cmd I did: 
conda env create -f DLC-CPU.yaml 
pip install --upgrade deeplabcut

**problem Description**
in administrator mode I open Jupiter Notebook with Kernel: Python [conda env:.conda-DLC-CPU] *
I use the code from: Demo_yourowndata
Everything works fine until I run something invovling the GUI. 
when I run the cell:   
%gui wx
deeplabcut.label_frames(path_config_file)

the gui windows pop up and I can use it to label the frames. 
But once I am done I click the SAVE button (the real one at the bottom right of the gui window)   
a prompt say : file saved (at the bottom left of the gui window)
An Excel file and an H5 file are created in the Labelled data folder. 
 
But I can't run an other cell because the current cell is still busy In[*]
even when I QUIT the GUI (the GUI windows disapear) but the cell 
In[*] 	%gui wx
	deeplabcut.label_frames(path_config_file)
is still busy 
When I start to run any other cell nothing happen other than changing this [] into [*] for the other cells. 

**How to Reproduce the problem**
1. Go to 'Demo_yourowndata'
2. run cells in this order: 
In [1]: 'import deeplabcut'
In [2]: task='Reaching',  experimenter='Mackenzie', video=['videos/vid1.avi', 'videos/vid2.avi'] 
	path_config_file=deeplabcut.create_new_project(task,experimenter,video,copy_videos=True) 
In [3]: %matplotlib inline
	deeplabcut.extract_frames(path_config_file) 
In [*]: %gui wx
	deeplabcut.label_frames(path_config_file)
3. Use the GUI to label frames
4. click SAVE, 
5. click QUIT.
6. Do you want to label another dataset: No    
7. At this point I got no error message but I can't run the next cell 
if I try I see: 
In [*]: %gui wx
	deeplabcut.label_frames(path_config_file)
In [*]: deeplabcut.create_training_dataset(path_config_file)
both cells seems busy,... but nothing happen. 

In that case I really don't know what to do since I have no error message and things seems to works well, 
except that I am stuck every time I quit the GUI. 

Thank you for reading this and let me know if you have ideas that could help me to solve this issue.

**Comment by MMathisLab** [comment]
just to let you know, if you run `pip install --upgrade deeplabcut` you won't have 2.2b8 installed; it's a beta release such that it's not the latest on pypi, if you want to use it, you need to run `pip install deeplabcut==2.2b8` 

Otherwise, sounds like a bad wxPython + windows issue; I don't have a windows machine to test on right now, but I would recommend to get you going, once you enter the environment just run:

`python -m deeplabcut` and that GUI works - it will take you through the whole process in a more streamlined manner.

**Comment by juliencatanese** [comment]
Hi, Thank you so much, problem solved! 

in my Anaconda env I wrote:  
pip install deeplabcut==2.2b8
pip install wxPython==4.0.7.post2  (I had Version: 4.1.0 and that seems to have been the problem)
python -m deeplabcut

it works! and I like the GUI version.  
I have been able start the training, looking good so far, I will let you know if I run into other issues. 
Thank you!
