### ISSUE TITLE
Unable to delete label when refining labels

### ISSUE THREAD

**Issue by BubbaChungus** [DeepLabCut/DeepLabCut#904]
![error with refining labels](https://user-images.githubusercontent.com/71154162/92973157-90609b00-f451-11ea-8f27-20cdb46e98f2.png)
Hello!
I'm currently trying to refine some labels using the Refine Labels optional step. 
It shows the prompt asking if I'm sure that I want to delete the label; however even when I select yes it doesn't delete the selected labels. 
Not quite sure how to go about addressing this.
Thank you.

**Comment by MMathisLab** [comment]
hi @Finkbe46 did you resolve this?
