### ISSUE TITLE
How to  label multi-mouse pose

### ISSUE THREAD

**Issue by Felix1014** [DeepLabCut/DeepLabCut#906]
**Your Operating system and DeepLabCut version**
MacOS, with an Anaconda Env, & DeepLabCut 2.1.6.4

**Describe the problem**

Hello,  I can use DLC for labelling single-mouse pose.  But if I want to label multi-mouse pose, how can I  use DLC for this? 
According to my understanding, I need to label the bounding box and keypoints of each animal. Thank you very much.

**Comment by AlexEMG** [comment]
Check out this section of the guide: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/maDLC_AdvUserGuide.md#configure-the-project

You can also label bounding box edges and detect those, and then use DLC as a top-down approach if you wish. The guide mostly discusses the bottom up approach, also see here for some explanation: https://arxiv.org/abs/2009.00564
