### ISSUE TITLE
Flipped manual labeling

### ISSUE THREAD

**Issue by ssapir** [DeepLabCut/DeepLabCut#908]
Error in labeling result (location is horizontally flipped). 

Result (right-clicked, on laptop):
![image](https://user-images.githubusercontent.com/51719243/93204896-872c4280-f75f-11ea-848c-505a328174b4.png)
Pressed (white circles added manually to image shows where marker should be):
![image](https://user-images.githubusercontent.com/51719243/93205019-c3f83980-f75f-11ea-883d-075ac7d96b48.png)

wxPython version is 4.0.7.post2. 
Code (deeplabcut\generate_training_dataset\multiple_individuals_labeling_toolbox.py line 289) uses widgetsizer.Add(self.quit, 1, wx.ALL | wx.ALIGN_RIGHT, 15) flag. 
DeepLabCut is latest version (date 13.9.20).
OS: windows 10
Python 3.7.4 

Thank you

**Comment by jeylau** [comment]
I cannot reproduce the issue on my Mac, but I'll try later on Windows later on and keep you posted.

**Comment by MMathisLab** [comment]
I can't reproduce this. @ssapir what version of matplotlib?

**Comment by MMathisLab** [comment]
any updates, @ssapir ?

**Comment by ssapir** [comment]
matplotlib             3.1.1

**Comment by MMathisLab** [comment]
Could you try with 3.1.3, just in case? And could you share your project folder with me, if not resolved? It’s quite wild, and I can’t reproduce it :/. Admin@deeplabcut.org

**Comment by ssapir** [comment]
Reproduce with 3.1.3. 

Might be related: https://github.com/wxWidgets/Phoenix/issues/1008
My OS language is RTL, and when running the app my default setting is also RTL (should it be?). 
I'll check later if I can change it and what is the result.

**Comment by MMathisLab** [comment]
^ interesting, that seems very likely...

**Comment by ssapir** [comment]
Changing the layout to LTR indeed fix the problem mentioned above (correct labeling position).

The following code fix the layout (set after init), on labeling frame: 
multiple_individuals_labeling_toolbox.py, line 199:
        wx.Frame.__init__(...)
        self.SetLayoutDirection(wx.Layout_LeftToRight)

Changing only main frame (launch_script.py line 40) didn't permeate labeling frame.

I didn't fine yet a way to force global LTR layout. But SetLayoutDirection after frame init should fix the problem
