### ISSUE TITLE
multiple skeletons for animals with different bodyparts (e.g. sheep and a sheepdog)

### ISSUE THREAD

**Issue by blogeman** [DeepLabCut/DeepLabCut#909]
My question/feature request is regarding the use of the skeleton for training. Based on reading the docs and others comments it seems like only the "multi-animal" points use a skeleton for training while the "unique" points do not. Is this correct and if so, are there any plans for future use of multiple skeletons? For example, the docs points out a use case involving multiple sheep and a single sheepdog. While the sheep benefit from having a skeleton, is there any way (current or future) to enable a skeleton for the sheepdog?

**Comment by AlexEMG** [comment]
This is possible and can be done. Imagine a,b,c are the body parts of the sheep and d, e of the sheepdog (note they have to be different) then you can define a skeleton that connects within a,b,c (e.g. a-b, b-c, a-c) for the sheep and also has edges within the sheepdog d-e. But you do not want to connect across them! Then it will work... (this is a suboptimal solution as the other bodyparts will be added to each individual as NANs after inference... we will certainly think about this in the future!

**Comment by blogeman** [comment]
Thanks for the reply @AlexEMG!

**Comment by arjunt19** [comment]
> Thanks for the reply @AlexEMG!

I know this is an old thread, but did this work for you @blogeman? I have just used unique body parts and created a skeleton with them for my project, but my convert_detections2tracklets is not working and I suspect that it may be the skeleton.

**Comment by blogeman** [comment]
@arjunt19 I never ended up trying this trick but rather made two completely separate models (i.e. one I ran one model for the sheep and a separate model for the sheepdog) and concatenated the output. Its more work, but in my case it made training simpler and was worth it.

**Comment by arjunt19** [comment]
> @arjunt19 I never ended up trying this trick but rather made two completely separate models (i.e. one I ran one model for the sheep and a separate model for the sheepdog) and concatenated the output. Its more work, but in my case it made training simpler and was worth it.

Thanks for the reply! So did you use maDLC in both models? Or just single animal tracking for the unique individual

**Comment by blogeman** [comment]
I use maDLC for both, even the single animal. This lets you take advantage of the skeleton.
