### ISSUE TITLE
How to launch GPU support with Jupyter?

### ISSUE THREAD

**Issue by saritma** [DeepLabCut/DeepLabCut#91]
Hi,
I'm on step 6, using Jupyter notebook.
the code I'm running is:
"TF_CUDNN_USE_AUTOTUNE=0 
CUDA_VISIBLE_DEVICES=0 
%run ../../../train.py"

I have GPU 1- NVIDIA GeForce GT 730 and I installed CUDA, but still the code is running on my CPU.
What am I doing wrong?

Thanks
Sarit

**Comment by MMathisLab** [comment]
We typically run this in the terminal, so I’m not entirely clear on the binding for Jupyter - let me check into it and get back to you! 

(Quick thought, in top right corner make sure your in your anaconda environment)

**Comment by saritma** [comment]
I can't find what you meant. That's my screen:
![capture](https://user-images.githubusercontent.com/31058799/47812812-02460480-dd52-11e8-8f67-c5cfbda97c92.PNG)

**Comment by MMathisLab** [comment]
Can you describe your system, i.e. are you using an Anaconda environment, or how did you install DLC? If so, you need to select the correct kernel to connect to... Click on "Kernel > Change Kernel > then selection conda env: deeplabcut (or whatever you named it)"

**Comment by zxy126** [comment]
Hello, maybe you installed TF, not TF-GPU?
how can I know whether the TF use CPU or GPU, looking at the task manager?
I installed TF-GPU, in the task manager, the GPU memory is fully used.
I noticed that your iteration reached 7k, how long does it spend?

**Comment by MMathisLab** [comment]
OKAY! I found the solution: https://github.com/jupyter/notebook/issues/2836

first install:

conda install -c conda-forge nb_conda_kernels

then type: 

``source activate <yourCondaname>``

then you need to:
``export BROWSER=google-chrome``

then, ``jupyter notebook``

Once in the notebook, go to "Kernel > Change Kernel > and select Python [conda enc: DLC2]" (or whatever you call your conda environment!"

**Comment by saritma** [comment]
I installed anaconda and downloaded the files with git, just followed the guide instructions.

**Comment by MMathisLab** [comment]
Did my suggestion solve it for you?

**Comment by AlexEMG** [comment]
I think you may want to install this: https://stackoverflow.com/questions/47191297/how-to-switch-environment-on-jupyter-notebook-for-new-notebook (in order to be able to switch environments in jupyter)

**Comment by vinod-13** [comment]
Hello, i have a Gaming laptop with Intel HD graphics and Nvidia 1050ti 4gb descrete graphic card. When i run the code in jupyter notebook, i can see in task manager only Intel graphics is being used. How do i make sure my code used Nvidia GPU
