### ISSUE TITLE
extracting additional frames for labeling after creating training dataset with cropping

### ISSUE THREAD

**Issue by backyardbiomech** [DeepLabCut/DeepLabCut#912]
**Your Operating system and DeepLabCut version**
Windows 10, DLC 2.2b8, DLC-GPU anaconda env

**Describe the problem**

When trying to extract additional frames for labeling after a full training round when crop and label was true, DLC can't find videos because it's looking for \*_cropped.mov videos (looking in config file at video_sets, rather than video_sets_original). 

Please place code inside this:

<details><summary>Code output</summary><p>

```python
Do you want to extract (perhaps additional) frames for video: C:\Users\__\Box\research\studentProjects\birdTails\__\data\20190606\wand01\trial01\cam1_06-Jun-19_12-00-08_cropped.mov ?
yes/noy
Traceback (most recent call last):
  File "C:\Users\__\Miniconda3\envs\dlc\lib\site-packages\deeplabcut\gui\extract_frames.py", line 243, in extract_frames
    slider_width=slider_width,
  File "C:\Users\__\Miniconda3\envs\dlc\lib\site-packages\deeplabcut\generate_training_dataset\frame_extraction.py", line 212, in extract_frames
    cap = VideoReader(video)
  File "C:\Users\__\Miniconda3\envs\dlc\lib\site-packages\deeplabcut\utils\auxfun_videos.py", line 22, in __init__
    raise ValueError(f'Video path "{video_path}" does not point to a file.')
ValueError: Video path "C:\Users\__\Box\research\studentProjects\birdTails\__\data\20190606\wand01\trial01\cam1_06-Jun-19_12-00-08_cropped.mov" does not point to a file.
```

</p></details>

**How to Reproduce the problem**
1. Label, create training dataset with crop and label, train, evaluate, create a video with all detections
2. **realize that you should extract and label more frames**
2. extract frames (with user feedback on so as to select videos for extraction)
3. answer yes for any video

**Screenshots**

Sample directory organization:
![image](https://user-images.githubusercontent.com/9662673/93487782-9cc27900-f8d3-11ea-9d1f-6efaf6e12198.png)

**Additional context**
[Line 184 in frame_extraction.py](https://github.com/DeepLabCut/DeepLabCut/blob/v2.2b8/deeplabcut/generate_training_dataset/frame_extraction.py#L184) loops through files in cfg: video_sets. But if crop and label was set to true on first pass, video_sets contains paths to "cropped" videos, which don't actually exist as videos, just as directories in labeled-images. So, frame extraction fails.

Changing L184 to 'video_sets_original' fixes the problem, but then breaks the code when creating a project and extracting frames the first time around. 

Unless I'm missing something in the suggested workflow, I think this is a bug?

I can see two possible fixes: 
1. create video_sets_original when creating config file the first time, and any time code needs to reference actual videos (as in frame_extraction.py) have it reference cfg['video_sets_original']
2. In frame_extraction.py use some kind of check (e.g. if video doesn't exist and 'cropped' is in video name), then try again after removing -cropped.

For now, my workaround is to change the keys in config.yaml, but I know I'll eventually forget to change them and mess something up.

**Comment by jeylau** [comment]
Thanks for raising this issue @backyardbiomech!
That definitely looks like a bug. I'll have a look at it and let you know once this is patched :)

**Comment by MMathisLab** [comment]
Hi @jeylau any updates on this? (I thought this behavior was changed post 2.2b6 actually)

**Comment by MMathisLab** [comment]
bump @jeylau
