### ISSUE TITLE
analyze_videos causes ValueError

### ISSUE THREAD

**Issue by shinhs0506** [DeepLabCut/DeepLabCut#913]
**Describe the bug**

running analyze_videos causes ValueError

**Desktop (please complete the following information about your system):**
 - OS: Ubuntu 18.04
 - DeepLabCut Version [2.1.8.2]
 - Browser, [Firefox, using Jupyter]
 
**To Reproduce**
Steps to reproduce the behavior, i.e.:
I simply followed the guide on the GitHub page

<details><summary>TRACEBACK</summary><p>

```python

deeplabcut.analyze_network(config_path, video_paths, save_frames=True)

ValueError                                Traceback (most recent call last)
~/anaconda3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/gui/analyze_videos.py in analyze_videos(self, event)
    262         deeplabcut.analyze_videos(self.config, self.filelist, videotype=self.videotype.GetValue(), shuffle=shuffle,
    263                                   trainingsetindex=trainingsetindex, gputouse=None, save_as_csv=save_as_csv,
--> 264                                   destfolder=self.destfolder, crop=crop, dynamic=dynamic)
    265         if self.filter.GetStringSelection() == "Yes":
    266             deeplabcut.filterpredictions(self.config, self.filelist, videotype=self.videotype.GetValue(), shuffle=shuffle, trainingsetindex=trainingsetindex, filtertype='median', windowlength=5, p_bound=0.001, ARdegree=3, MAdegree=1, alpha=0.01, save_as_csv=True, destfolder=self.destfolder)

~/anaconda3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py in analyze_videos(config, videos, videotype, shuffle, trainingsetindex, gputouse, save_as_csv, destfolder, batchsize, crop, get_nframesfrommetadata, TFGPUinference, dynamic)
    218         #looping over videos
    219         for video in Videos:
--> 220             DLCscorer=AnalyzeVideo(video,DLCscorer,DLCscorerlegacy,trainFraction,cfg,dlc_cfg,sess,inputs, outputs,pdindex,save_as_csv, destfolder,TFGPUinference,dynamic)
    221 
    222         os.chdir(str(start_path))

~/anaconda3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py in AnalyzeVideo(video, DLCscorer, DLCscorerlegacy, trainFraction, cfg, dlc_cfg, sess, inputs, outputs, pdindex, save_as_csv, destfolder, TFGPUinference, dynamic)
    496             if int(dlc_cfg["batch_size"])>1:
    497                 if TFGPUinference:
--> 498                     PredictedData,nframes=GetPoseF_GTF(cfg,dlc_cfg, sess, inputs, outputs,cap,nframes,int(dlc_cfg["batch_size"]))
    499                 else:
    500                     PredictedData,nframes=GetPoseF(cfg,dlc_cfg, sess, inputs, outputs,cap,nframes,int(dlc_cfg["batch_size"]))

~/anaconda3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py in GetPoseF_GTF(cfg, dlc_cfg, sess, inputs, outputs, cap, nframes, batchsize)
    380                     pose[:, [0,1,2]] = pose[:, [1,0,2]] #change order to have x,y,confidence
    381                     pose=np.reshape(pose,(batchsize,-1)) #bring into batchsize times x,y,conf etc.
--> 382                     PredictedData[batch_num*batchsize:(batch_num+1)*batchsize, :] = pose
    383 
    384                     batch_ind = 0

ValueError: could not broadcast input array from shape (8,12) into shape (3,12)


```
</p></details>

**Screenshots**
![Screen Shot 2020-09-17 at 11 43 19 AM](https://user-images.githubusercontent.com/51249639/93652656-a7136e80-f9ca-11ea-9ef2-84e5c7579fc9.png)

**Additional context**
The whole workflow was working just fine, but started having this problem since yesterday. No upgrades done in-between.
NOTE: same thing happens when using the GUI. Only thing I touched was maxiteration=2000 and saveiteration=1000. Other than that, just simply clicked 'okay'

**Comment by AlexEMG** [comment]
That happens when the model and project have different numbers of bodyparts (among other reasons)

Sent from my iPhone

**Comment by MMathisLab** [comment]
@shinhs0506 you likely edited the config file to change the bodypart #, perhaps inadvertently when you edited save_iters, max_iters

(also note your code above must be incorrect, as there is no "analyze_network" function. could you update to the exact thing you ran to help us help you please?)

**Comment by shinhs0506** [comment]
@MMathisLab "analyze_network" was a typo, please ignore that. 

here is what I run. all the videos are under the '/videos' directory

import deeplabcut as dlc
import os

project_name = 'testing'
your_name = 'name'

video_dir = os.path.join(os.getcwd(), 'videos')
video_paths = [os.path.join(video_dir, x) for x in os.listdir(video_dir)]

config_path = dlc.create_new_project(project_name, your_name, video_paths, copy_videos=False)

dlc.extract_frames(config_path, mode='automatic', algo='kmeans', crop=False)

dlc.label_frames(config_path)
dlc.check_labels(config_path)

dlc.create_training_dataset(config_path)

maximum_iterations = 2000
save_iterations = 1000
dlc.train_network(config_path, maxiters=maximum_iterations, saveiters=save_iterations)

dlc.evaluate_network(config_path, plotting=False)

dlc.analyze_videos(config_path, video_paths, save_as_csv=True)
 * fails here

**Comment by MMathisLab** [comment]
Yep, makes sense - you should pass full path/videos/ not video paths

**Comment by shinhs0506** [comment]
@MMathisLab sorry, I don't quite understand what that means. the "video_paths" variable is a list of full paths to each videos under the '/videos' directory

**Comment by MMathisLab** [comment]
Just point to the video folder ;)

**Comment by shinhs0506** [comment]
@MMathisLab @AlexEMG I ran 'deeplabcut.analyze_videos(config_path, ['/full/path/videos/'], videotype='.wmv', save_as_csv=True)' and it did not fix it. the progress bar hits 100% then fails for both cases. I was able to successfully run the entire workflow on a different machine, so might be a dependency issue.
