### ISSUE TITLE
Not all the frames shown in Refinement Toolbox have dots in them to improve them

### ISSUE THREAD

**Issue by monajalal** [DeepLabCut/DeepLabCut#915]
This is my second time using the Refinement Toolbox. The first time I used it for another project with same version of DLC, it shows all the 100 frames with dots in them (predicted by machine learning algorithm).

This time in a different project, in nearly half of the shown frames there is no dot (filled or empty --an empty circle).

I am wondering what could be the cause and why those frames are shown since I cannot add annotations of my own or improve the machine created ones.
```
In [2]: deeplabcut.__version__                                                                                                                                                                             
Out[2]: '2.1.8.2'

```

**Comment by MMathisLab** [comment]
likely they are outside the image then, meaning the pose estimation quality is poor. You can drag the image to see outside the box. there is a function in the config.yaml that says move2corner = True, and then the coordinates, 50, 50 you ca edit this. Hope that helps.
