### ISSUE TITLE
Multianimal DLC stops tracking animals after various periods of time

### ISSUE THREAD

**Issue by tkr789** [DeepLabCut/DeepLabCut#917]
OS: Ubuntu 20.04
DeepLabCut Version: 2.2b8
Anaconda env used: Running the Docker4DeepLabCut2.0 image (so no environment needed)
For the GUI I use conda env DLC-CPU as provided

**Describe the problem**

I am tracking 4 animals in 4 separate boxes (see pics below). Animal tracking appears to degrade and totally stop in longer videos. It seems the longer the video, the faster the animal tracking degrades. For example a 30 minute video seems to track all the animals for ~25-30 mins, before it stops tracking them. A 3 hour video will stop tracking all animals in the first 10 minutes. It is tracking them decently beforehand. You'll see the tracks switch animals below, but this is easily accountable post-hoc by designating boundaries. 

Within Docker4DeepLabCut2.0:

```
!export DLClight=True

import deeplabcut
import glob

path = '/home/tom/data/behavior/cropped/analyze/'

videos = [path + video for video in videos];

deeplabcut.analyze_videos(config_path, videos, videotype='mp4', gputouse=0) 

deeplabcut.convert_detections2tracklets(config_path, videos, videotype='mp4', shuffle=1, trainingsetindex=0, track_method='box') 

pickles = glob.glob(path + '*bx*')

deeplabcut.convert_raw_tracks_to_h5(config_path, pickles)

for pickle in pickles:                                                                                                          
   ...:     deeplabcut.convert_raw_tracks_to_h5(config_path, pickle)

deeplabcut.analyze_videos_converth5_to_csv(path, videotype='.mp4')
```
</summary><p>

**Screenshots**
![image](https://user-images.githubusercontent.com/48607760/93750302-1e562780-fbb0-11ea-9918-1f0e7d97d17a.png)
![image](https://user-images.githubusercontent.com/48607760/93750515-6f661b80-fbb0-11ea-984c-38d3a37e1303.png)
![image](https://user-images.githubusercontent.com/48607760/93750550-7f7dfb00-fbb0-11ea-8e19-dddfbb1e7c46.png)

**Additional context**
As you can see in the pics above, tracking is lost very early in the video and never recovered. Animals appear to drop off one at a time. You can see this happens early in the video (The video is ~3 hours long and this happens in about the first 5 minutes). 

The pics below are from a shorter video (~35 mins), but you can see the dropout occurring as well, just further on:
![image](https://user-images.githubusercontent.com/48607760/93750969-2d89a500-fbb1-11ea-9cb7-c57a5b143344.png)
![image](https://user-images.githubusercontent.com/48607760/93751054-51e58180-fbb1-11ea-8954-ad388d792f46.png)
![image](https://user-images.githubusercontent.com/48607760/93751092-5f9b0700-fbb1-11ea-8ac5-820d78f06823.png)

This has happened with ~10 videos so far. 

Any ideas on why this is happening would be much appreciated.

**Comment by jeylau** [comment]
Hi @tkr789, thanks for reporting this issue! Does the same happen if you load directly a .pickle file in the GUI rather than a h5 file? Can you also confirm that data are missing in the csv you produced?

**Comment by jeylau** [comment]
@tkr789, any news?
