### ISSUE TITLE
Colab for building Skeleton for Single Animal

### ISSUE THREAD

**Issue by Hydraulic343** [DeepLabCut/DeepLabCut#919]
Is there a colab available that allows me to build a skeleton for only one animal? I am trying to build an animal model video, such as in Colab_TrainNetwork_VideoAnalysis.ipynb, but with the ability to add a skeleton on. Can someone help me with this, or point me toward an existing colab that already does this?

**Comment by AlexEMG** [comment]
You mean, just plotting a skeleton? Then just put a skeleton in the config file and then when you create the labeled video, pass `draw_skeleton = True `(see user guide: https://github.com/DeepLabCut/DeepLabCut/blob/73580e39fe36bde8fc86125daafd6d915e4dbdc4/docs/functionDetails.md#create-labeled-videos)

Here is an example how to define the skeleton:
`https://github.com/DeepLabCut/DeepLabCut/blob/master/examples/testscript.py#L60`
