### ISSUE TITLE
Issue when importing labeled frame

### ISSUE THREAD

**Issue by DorianBattivelli** [DeepLabCut/DeepLabCut#921]
Hello, 

I am trying to refine labels frame by frame using the deeplabcut.refine_labels(config_path) function, but once the refinement toolbox pops out, I cannot load any frame. 
Can you confirm me, please, that I should load the frames stored in "labeled-data" > "NAMEVIDEO_labeled", and there to load the png files? 
I tried to navigate in this folder from the "load" button, but then, in the browser, the "NAMEVIDEO_labeled" folder appears empty (which is not true; its contains png frames that are indeed labeled).

Am I wrong with the files to load or is that a bug? 
FYI: I am using windows 10 and dlc 2.2b6 (and I cannot use the new version for this video, because the refining tracklet function is not compatible from one version of dlc to the other, as I explained in my last issue), 

Thank you very much, 
Best, 
Dorian

**Comment by jeylau** [comment]
Hello @DorianBattivelli! You're trying to load the frames that were labeled with check_labels(); they visually have labels, but there is no data associated with them. You must navigate to the regular labeled-data/videoname folder, where you'll find the CollectedData.h5 and machinelabels.h5.

**Comment by DorianBattivelli** [comment]
Thank you @jeylau ,
Indeed I found the CollectedData.h5 but not the machinelabels.h5 file, is that normal?

**Comment by DorianBattivelli** [comment]
In the labeled-data/videoname folder, I find 3 types of items: png files, CollectedData.csv and CollecteData.h5 files, but no machinelabels, how could I obtain this file?

**Comment by jeylau** [comment]
It is normal if you haven't called `deeplabcut.extract_outlier_frames`before; otherwise that's a bug 😄.

**Comment by DorianBattivelli** [comment]
Indeed I did not do it, sorry ^^; I am using now the deeplabcut.extract_outlier_frames command, but when I specify the path of the video, it returns: 

"No suitable videos founds in PATH "

I path the original video from my video folder, is that right?

**Comment by jeylau** [comment]
Even if it is a single video, pass it as a list, and make sure `videotype` also matches your video extension.
In IPython, I'd encourage you to use `?deeplabcut.extract_outlier_frames` or with any other function name, it's super useful to understand what parameters do (as sometimes there are optional arguments that may be relevant).

**Comment by DorianBattivelli** [comment]
Ok thank you, precising the vidotype fixed the problem apparently, but now it returns this: 

![Untitled](https://user-images.githubusercontent.com/66886884/94131932-e0caf600-fe5e-11ea-9ea3-ffcd63ce2285.png)

Have you an idea of the issue here?

**Comment by jeylau** [comment]
Yes, the video path should point to the video within the DLC project. Otherwise the code won't know where to search for data and snapshots.

**Comment by DorianBattivelli** [comment]
Not sur to understand. The path is pointing to the DLC project ("multi_camera" is the name of my DLC project folder). The path I passed is pointing to the "videos" subfolder of the DLC folder, is that not good? In which folder should I path?

**Comment by jeylau** [comment]
Your DLC project's name does not contain an experimenter name nor the date; I do not know how it was created it but this does not look right. And the videos subfolder indeed is spelled with an S, whereas your path points to a 'video' folder.

**Comment by DorianBattivelli** [comment]
I see. Indeed I seen the missing S in the meantime, I tried but still the same error occurs. 
On the other hand, concerning the format of the LDC project folder name, I created the folder from the GUI, when it is requiered to precise the experimenter and the name of the project. And for the 6 projects I already created, it always created folders with this format (experimenter name and date have never been included in the title...), is there a way to change that?

**Comment by DorianBattivelli** [comment]
I corrected it manually, but the error still appears :/

![Untitled](https://user-images.githubusercontent.com/66886884/94136041-a2d0d080-fe64-11ea-89ee-1dfea883ae97.png)

**Comment by DorianBattivelli** [comment]
Here my config file: 

![Untitled](https://user-images.githubusercontent.com/66886884/94136432-386c6000-fe65-11ea-9ab1-6dcf13e882f0.png)

I think that there is an issue concerning the difference for the path for my DLC project and the path of the videos (multi_camera vs. Multicamera), I'll try to figure out trying different paths. Thank you :)

**Comment by DorianBattivelli** [comment]
Well actually, it did not fix the bug:

![Untitled](https://user-images.githubusercontent.com/66886884/94138286-2dff9580-fe68-11ea-8bbb-657828a5dbb5.png)

the problem could not come from the modelprefix ? 
I looked for explanation about this argument in the ?deeplabcut.extract_outlier_frames command, but I did not find explanation.

**Comment by jeylau** [comment]
Your DLC project was correctly created within the Multicamera folder in your Desktop. As said earlier, it does contain a task 'multicamera', your experimenter name and the date. I do not understand why you pulled the config out of its folder; it should normally be found in C:\Users\battivel\Desktop\Multicamera\multicamera-Dorian-2020-08-19 (which should be your project path).

**Comment by DorianBattivelli** [comment]
I pulled it out of its folder because I was having troubles with the path for colab analysis, but I don't remember exactly what was the problem.
Anyway, I re dragged everything inside the original folder, including the config file: 

![Untitled](https://user-images.githubusercontent.com/66886884/94139283-adda2f80-fe69-11ea-8f2c-99033cf84161.png)

But the error persists

**Comment by DorianBattivelli** [comment]
Here a picture of my video folder, maybe it contains some useful information to help understand the problem:

![Untitled](https://user-images.githubusercontent.com/66886884/94139661-4b356380-fe6a-11ea-9cd5-d654d39d8759.png)

**Comment by jeylau** [comment]
Can you show your dlc-models folder too?

**Comment by DorianBattivelli** [comment]
![1](https://user-images.githubusercontent.com/66886884/94143462-2512c200-fe70-11ea-97da-8532fc0d4f27.png)

![2](https://user-images.githubusercontent.com/66886884/94143468-280db280-fe70-11ea-8bf4-80e673e43c29.png)

![3](https://user-images.githubusercontent.com/66886884/94143478-2b08a300-fe70-11ea-9064-f7d51fca4ae1.png)

![4](https://user-images.githubusercontent.com/66886884/94143483-2e039380-fe70-11ea-873a-c72eeffeb74c.png)

**Comment by DorianBattivelli** [comment]
For precision, when I run the analysis on Drive/Colab, I loaded my DLC project in the "multi_camera" folder, so I did not directly dragged the original Multicamera folder automatically created via the DLC GUI: 

![Untitled](https://user-images.githubusercontent.com/66886884/94144358-5049e100-fe71-11ea-969a-3cbc88b17a4b.png)
 
I think there is some path names issue here

**Comment by DorianBattivelli** [comment]
Since I read that (https://github.com/DeepLabCut/DeepLabCut/blob/a09bb5296428b161fd53900f45107523ea6452a7/deeplabcut/refine_training_dataset/outlier_frames.py#L29) : 

I also precise that on my config file I have no numframes2extract section.

**Comment by jeylau** [comment]
This line is outdated; the actual parameter is numframes2pick.
https://github.com/DeepLabCut/DeepLabCut/blob/a09bb5296428b161fd53900f45107523ea6452a7/deeplabcut/refine_training_dataset/outlier_frames.py#L176

**Comment by DorianBattivelli** [comment]
I see, thank you for the precision. 
Concerning the error 'list index out of range', did you see anything in the dlc-models folder that could explain it?

**Comment by DorianBattivelli** [comment]
If it can help, here you can see the other configurations of the config file:

![Untitled](https://user-images.githubusercontent.com/66886884/94246529-2699c400-ff1c-11ea-8981-103bea23beec.png)
