### ISSUE TITLE
 h5py is running against HDF5 1.10.5 when it was built against 1.10.4

### ISSUE THREAD

**Issue by byronrogers73** [DeepLabCut/DeepLabCut#924]
In [1]: import deeplabcut
C:\Users\byron\Anaconda3\envs\DLC\lib\site-packages\h5py\__init__.py:40: UserWarning: h5py is running against HDF5 1.10.5 when it was built against 1.10.4, this may cause problems
  '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.10.4, library is 1.10.5

**Comment by byronrogers73** [comment]
I should add that within the DLC env, it says it is running 1.10.4. and I was importing deeplabcut within that env.

**Comment by MMathisLab** [comment]
Hi @PerformanceGenetics can you fill out the template; which DLC version, which OS, etc thanks

**Comment by AlexEMG** [comment]
Hey Byron, apparently just:

```
pip uninstall h5py
pip install h5py
```

see here:
https://stackoverflow.com/questions/57842565/hdf5-library-version-error-hdf5-ver-1-10-4

**Comment by byronrogers73** [comment]
That solved it.
