### ISSUE TITLE
<Unsupported operand type(s) for *: 'NoneType' and 'Float'> only with new projects

### ISSUE THREAD

**Issue by Charly77220** [DeepLabCut/DeepLabCut#927]
Windows-GPU with an Anaconda Env & DeepLabCut 2.1.8.2 (re-uploaded today)

OS: Windows
DeepLabCut Version: 2.1.8.2
Anaconda env used: DLC-GPU

**Describe the problem**

Since few months I have a problem with DeepLabCut. As soon as I create a new project, when I label frames, this error message appears, without any other error messages before. Strangely, when I change the config.yaml for an old project and I want to label older frames, it works. It's really for a new project, to label the first videos. 
I tried to update everything, remove and reinstall the environment, install again DeepLabCut completely, nothing helps ...

**Screenshots**

![Screen Trouble](https://user-images.githubusercontent.com/53442625/94310162-2fec5600-ff47-11ea-9886-8ed0ca02bced.PNG)

**Comment by AlexEMG** [comment]
What is the value of "stop" in your config.yaml file?

**Comment by Charly77220** [comment]
For each config.yaml file (older and new), the value of "stop" is 1.

**Comment by AlexEMG** [comment]
Can you share a screenshot?

**Comment by Charly77220** [comment]
![Screen config](https://user-images.githubusercontent.com/53442625/94311096-a9d10f00-ff48-11ea-8338-da7ff40e5f53.PNG)
![Screen config2](https://user-images.githubusercontent.com/53442625/94311103-ac336900-ff48-11ea-8934-553010a15190.PNG)

**Comment by Hugues1273** [comment]
**I have exactly the same problem.** With an old project I did not meet this issue, and now I have this error message and I really do not get why. My DLC is updated. When comparing the old config file with the new one, the only thing different is the video format: before it was .mod and now it is .avi. But the frames are extracted and are in the good folder, with a .png format but when I want to label it, I load the frames (which therefore are existing) and the error message is appearing. However, when I choose from this new project, my old pictures in my old project, no probem... I do not get why...

**Comment by MMathisLab** [comment]
could you both run `pip install deeplabcut==2.2b8` , `pip install matplotlib==3.1.3`

**Comment by jeylau** [comment]
This is happening because the variable `im` is None; in other words, an image that is not found is trying to be read, and opencv silently returns None. Either the location of these images changed, or there is something wrong with the data index. And unrelated, but the definition of the skeleton is incorrect. It should look like:
```
- - a
  - b
- - b
  - c
```
I could not reproduce the issue with a fresh 2.1.8.2 project :/

**Comment by MMathisLab** [comment]
( @jeylau the skeleton can be that was as well actually) but yes, OP, you should check no image path is wrong in your config.yaml file. See the helper functions page for helper docs on this too

**Comment by Hugues1273** [comment]
I m sorry, it still does not work for me... the GUI changed with a new button called build skeleton so I guess I have not the same version of dlc but then the same error message is appearing, I m really sorry :(

**Comment by MMathisLab** [comment]
@Hugues1273 no worries; what is means is that your folder paths in the config.yaml might be pointing to a video that is no longer there; can you double check that within the project folder you have (1) subfolders under "labeled" that have images for each video in your config.yaml video list?

**Comment by Hugues1273** [comment]
I took pictures of my screen to be sure but I guess it's okay. 

![image](https://user-images.githubusercontent.com/71940901/94363520-00faef00-00c3-11eb-8571-18f59efcc203.png)
![image](https://user-images.githubusercontent.com/71940901/94363528-107a3800-00c3-11eb-9b85-d9ce47d7d4c7.png)
![image](https://user-images.githubusercontent.com/71940901/94363536-24259e80-00c3-11eb-8bda-5b081f70fa2d.png)

**Comment by Charly77220** [comment]
> could you both run `pip install deeplabcut==2.2b8` , `pip install matplotlib==3.1.3`

These commands don't work for me either...

**Comment by MMathisLab** [comment]
@Charly77220 can you explain what you are doing to run then, and what you mean by they don't work?

**Comment by Charly77220** [comment]
To run them,I wrote these lines. Everything is successfully installed, but my frames cannot be opened then. That's for this part, my frames, that I said "They don't work"

**Comment by Charly77220** [comment]
I managed to solve the problem by making a shorter path to my videos. I don't know why, but I think that when the pathway structure is too long, it causes problems

**Comment by sherrychopper** [comment]
@Charly77220 did you install DLC-CPU?

**Comment by Charly77220** [comment]
@sherrychopper No, I work on DLC-GPU

**Comment by backyardbiomech** [comment]
Windows has a 260 character limit for paths. Since deeplabcut makes folders in labeled-data named after the video, long video file names can very quickly lead to very long paths to the labeled-data folder. Also, you have spaces in your path and file names. Especially for windows, avoid spaces in paths and file names, and keep your deeplabcut project somewhere that the path doesn't get too long to avoid a lot of potential problems.
