### ISSUE TITLE
Issue with cropping (moviepy misuse > fixed)

### ISSUE THREAD

**Issue by tm2775** [DeepLabCut/DeepLabCut#93]
Hello,

I'm having an issue trying to analyze an ROI of my videos.  I've generated my training frames and trained using a cropped region of the video (x1=0, x2=1920, y1=380, y2=650).  The frames are correctly cropped in the UnaugmentedDataSet folders.  However, when I go to analyze the full video with the same ROI specified in myconfig_analysis.py, the whole frame is analyzed.  Since I didn't train with the whole frame, it picks out features that are incorrect outside of the ROI.  Is there a setting that I'm missing?

Thanks for you help.

Thong

**Comment by AlexEMG** [comment]
Dear @Thong,

Thanks for raising this issue. This is a problem with moviepy, I was not aware of. When one does clip.crop then clip.reader.... still refers to the full video!

I just pushed a fix.  Sorry for the inconvenience!

Alexander

**Comment by tm2775** [comment]
Hi Alexander,

The cropping works perfectly.  Thank you so much for working on it so quickly.  I'm new to this all and am trying to figure it out as I go!  Your efforts are greatly appreciated.

Thong
