### ISSUE TITLE
Issue with deeplabcut.extract_outlier_frames function. 

### ISSUE THREAD

**Issue by DorianBattivelli** [DeepLabCut/DeepLabCut#930]
Hello, 

I am facing an issue when I call deeplabcut.extract_outlier_frames command. 
Here what I obtain: 

![Untitled](https://user-images.githubusercontent.com/66886884/94436751-1b090000-019d-11eb-8ea1-79c87f49a459.png)

I tried with another project, I have exactly the same error. 
FYI. I use DLC 2.2b6 and windows 10.

Please let me know if you have any suggestion,
Thank you, 
Best, 
Dorian

**Comment by jeylau** [comment]
Do you face the same error with 2.2b8? I do not think I had asked you that earlier 😄

**Comment by DorianBattivelli** [comment]
Hi @jeylau , no I still did not install it because I manually labeled 400 frames for this project and I noticed that labeling on one DLC version and then refining the tracklets on another DLC version usually does not work. So for know I would privilege to keep the same version that I used for the labeling before updating the DLC version, in order to avoid to have to re do the labeling part ^^

**Comment by DorianBattivelli** [comment]
Well, I created a new environment with the 2.2b8 version. 
I get the same error:

![Untitled](https://user-images.githubusercontent.com/66886884/94448010-bc4a8300-01aa-11eb-92d2-1869fa67039d.png)

**Comment by DorianBattivelli** [comment]
ps: good news, with this version I can use the lasso function on a project labeled with the 2.2b6 version (while 2.2b6 and 2.2b7 did not seem compatible)

**Comment by MMathisLab** [comment]
@DorianBattivelli - can you confirm:

(1) you have a fully tracked filed, i.e. something that ends with bx.h5, or sk.h5 that is associated to this exact video?
(2) in your config.yaml file, what is snapshotindex set to? 

![Screen Shot 2020-09-28 at 5 19 20 PM](https://user-images.githubusercontent.com/28102185/94451507-c5d5ea00-01ae-11eb-9151-63c6f75585f5.png)

also, please fill out the provided template when you create issues; it really helps us to quickly assess the issue, and looking at pictures of code is difficult. Having the full code to copy/paste is very useful.

**Comment by DorianBattivelli** [comment]
@MMathisLab, sorry for not having created this issue in the good way, I'll provide the template the next time. 

Yes I confirm that I have a bx.h5 file associated with this video as you can see here in my videos folder:

![Untitled](https://user-images.githubusercontent.com/66886884/94459601-de96cd80-01b7-11eb-9425-a4bd0e47906c.png)

the bx.h5 file has been generated after that I corrected the ID swaps with the refine tracklets on GUI. Before that, I did not have any bx.h5 file from drive, as you can see here in my "videos" folder on drive:

![Untitled](https://user-images.githubusercontent.com/66886884/94459963-5533cb00-01b8-11eb-9b24-f675a7a1385e.png)

Concerning the snapshotindex, it is -1, as shown on your picture

**Comment by MMathisLab** [comment]
No problem, thanks. So, when you corrected in the GUI, did you click "merge refined data?" <-- this will grab frames if you manually moved any points, quite a nice feature (i'm biased ;) to build up an outlier dataset; then it's already labeled from your corrections in the tracklet GUI. 

<img width="362" alt="Screen Shot 2020-09-28 at 6 38 56 PM" src="https://user-images.githubusercontent.com/28102185/94461168-0dae3e80-01ba-11eb-999a-f6505373c738.png">

**Comment by DorianBattivelli** [comment]
No I did not clicked "merge" key. I just gave a go now, after having dragged one casual label on one frame, and it created a machinelabels...h5 file in my labeled-data > VIDEONAME.
With that I am now able to load this frame when I call the deeplabcut.refine_labels(config_path) command. 

To clarify what I am trying to do, my intention is to add labels on the frame where they are missing.  

At the beginning I though it was possible to edit missing labels with the "deeplabcut.refine_labels(config_path)" command but I was not able to load any frame (because the machine....h5 file was missing).  
But actually, now that I can load the frames, I only manage to drag the labels already present, but not to edit the missing ones. How should I proceed?

Concerning the deeplabcut.extract_outlier_frames commands, it still returns exactly the same error. Do I need to run this command to edit missing labels?

**Comment by DorianBattivelli** [comment]
Here the refinement toolbox that pops out (with deeplabcut.refine_labels):

![Untitled](https://user-images.githubusercontent.com/66886884/94465119-b317e100-01bf-11eb-9d64-60ce82b9fba6.png)

I don't understand how to edit/remove labels from here.

**Comment by MMathisLab** [comment]
okay, so two things:

(1) the `extract_outlier_frames` is to find frames with low confidence pose estimation; it's not directly linked to tracking performance. It then allows you to use `refine_labels` move labels around (you select the p-cutoff on launch) to signify high vs low confidence dots (filled or hollow circles). This is documented in the docs and more extensively in the Nature Protocols paper. You cannot add labels, as in pose estimation every label is there.

(2) Tracking is where you can loose labels, as there is an initial cutoff step. As we assume the pose estimation is very good. See here for the workflow of 2.2 (before we release the full paper): https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/maDLC_AdvUserGuide.md
Here the refine_labels is the only for pose estimation, not tracking. If you want everything to show up in the tracklet GUI, you need to firstly double check your inference_cfg.ayml parameters, then load the pickle file--you can set max gap to fill to "0" which fills in every point. If you do this, the confidence value of those filled in points is 0.01; so when you create_a_labled_video, if you want to see them all, you need to set `pcutoff `to 0 in your config.yaml file.

**Comment by MMathisLab** [comment]
^ and for the refine GUI, click help, but to remove a point you right click to delete.

**Comment by DorianBattivelli** [comment]
Amazing it works! I have been able to make all the bp appearing on all the frames, now it's just about dragging them when some are displaced, thank you so much!
