### ISSUE TITLE
Detected frames consistently lower than nframes

### ISSUE THREAD

**Issue by lolaBerkowitz** [DeepLabCut/DeepLabCut#932]
Colab Notebook DLCv.2.1.8.2 or DLCv.2.2b5

Running analyze_videos with these calls: 

for v.2.1.8.2 
```deeplabcut.analyze_videos(path_config_file,videofile_path, videotype=VideoType,save_as_csv=True,get_nframesfrommetadata=True)```

for v.2.2b5
```deeplabcut.analyze_videos(path_config_file,videofile_path, videotype=VideoType,save_as_csv=True,robust_nframes=True)```

Detected frames is consistently lower than nframes. I don't believe this was due to metadata corruption (as was the case in issue #422), but I tried robust_nframes as well without resolution. 

Is there a way to identify which frames are lost? I need to sync the DLC output with my ephys timestamps (from Neuralynx VT1 file).  I'm not sure if its just trailing frames or if frames are lost at any point. Is there a way to identify which frames are lost? 

Here is example output when using DLC 2.2b5: 

```Using snapshot-242500 for model /content/drive/My Drive/DLC_analysis/ephys-Berkowitz-2020-09-18/dlc-models/iteration-0/ephysSep18-trainset95shuffle1
Initializing ResNet
Analyzing all the videos in the directory...
Starting to analyze %  2020-09-24_16-16-57.mpg
.  already exists!
Loading  2020-09-24_16-16-57.mpg
  0%|          | 0/42224 [00:00<?, ?it/s]Duration of video [s]:  1408.87 , recorded with  29.97 fps!
Overall # of frames:  42224  found with (before cropping) frame dimensions:  720 480
Starting to extract posture
42622it [1:00:48, 11.59it/s]                           Detected frames:  42219
42622it [1:00:50, 11.68it/s]
Saving results in ....
Saving csv poses!
Starting to analyze %  2020-09-21_10-37-41.mpg
.  already exists!
Loading  2020-09-21_10-37-41.mpg
  0%|          | 0/9098 [00:00<?, ?it/s]Duration of video [s]:  303.57 , recorded with  29.97 fps!
Overall # of frames:  9098  found with (before cropping) frame dimensions:  720 480
Starting to extract posture
9180it [13:02, 11.59it/s]                          Detected frames:  9092
9180it [13:03, 11.72it/s]
Saving results in ....
Saving csv poses!```

**Comment by jeylau** [comment]
@lolaBerkowitz, with 2.2b8, we have added a new functionality to check the integrity of your video files. You could use the short piece of code here [https://forum.image.sc/t/didnt-analyze-all-the-frames/42576/3](url) to write video errors to a log file. That would hopefully help you identify the faulty frames 😊

**Comment by lolaBerkowitz** [comment]
Excellent will try it out. Thanks!

**Comment by Davidjtitus** [comment]
@lolaBerkowitz or @jeylau 
Is this issue resolved? I also have the same problem, where my video is saved in a compressed version with a length that is not equal to the actual duration of the experiment. Therefore, I have a mismatch between ephys and behavior.

**Comment by lolaBerkowitz** [comment]
@Davidjtitus My videos were synced with my ephys data, but the issue was that some frames were not detected by DLC. I ended up converting the .mpg to .avi using ffmpeg. That resolved the issue, though the functionality of DLC 2.2b8 was helpful for examining errors.

**Comment by Davidjtitus** [comment]
Thank you, would you mind sharing how you sync with Ephysdata? The electrophysiology is done with OpenEphys and the behavior is handled with Python-based open source.
