### ISSUE TITLE
ValueError while launching GUI in 'Refine Tracklets'

### ISSUE THREAD

**Issue by mattka65** [DeepLabCut/DeepLabCut#933]
**Desktop**
OS: Windowns 10
DeepLabCut Version: 2.2b8
Using the DLC GUI

**Describe the Bug**
I'm using maDLC to track two mice in an arena. I've already analyzed the video and converted it to tracklets. On the Refine Tracklets tab, I loaded the config file, original video, and the bx.pickle file(tracklet data), and I click on 'Step 1: Launch GUI,' I get the following error: "value error: all arrays must be the same length"

**How to Reproduce the problem**
1. In anaconda prompt: 
cd [...] 
conda activate dlc-gpu
ipython

2. In ipython: 
import deeplabcut
deeplabcut.launch_dlc() 

3. In GUI, I load the config file, and then go to Refine Tracklets tab where I load the config file, original vidoe, and the tracklet data(bx.pickle)

4. Set minswap=2, minrel=2, maxgap=2, trail length=0, viodetype=mp4, shuffle=1, trainingsetindex=0, filtertype:median, windowlength=5

5. Click on 'Step 1: Launch GUI'

6. See error 

**Prior to going to refine tracklets tab, all prior steps(tabs) were completed except for 'video editor'. 

Screenshot:
![ValueError_ArrayLength](https://user-images.githubusercontent.com/71092304/94599944-32102680-025f-11eb-83bf-c0f5475ced74.PNG)

**Comment by jeylau** [comment]
Hi @mattka65, what does your config.yaml look like? It looks like there is a mismatch between what bodyparts/animals are defined there and what has actually been stored in the pickle.

**Comment by mattka65** [comment]
# Project definitions (do not edit)
Task: TAT_TEST_MKA_9-24-2020
scorer: mka
date: Sep24
multianimalproject: true

    # Project path (change when moving around)
project_path: C:\DeepLabCut\TAT_TEST_MKA_9-24-2020-mka-2020-09-24

    # Annotation data set configuration (and individual video cropping parameters)
video_sets:
  C:\DeepLabCut\fc2_save_2020-06-28-134342-0000_cropped.mp4:
    crop: 0, 400, 0, 400
individuals:
- NYOB
- C57
uniquebodyparts: [8]
multianimalbodyparts:
- ear_left
- ear_right
- nose
- center
- lateral_left
- lateral_right
- tail_base
- tail_end
skeleton:
- - lateral_left
  - tail_end
- - ear_right
  - center
- - lateral_right
  - tail_base
- - ear_right
  - tail_base
- - ear_left
  - center
- - nose
  - lateral_right
- - ear_right
  - nose
- - tail_base
  - tail_end
- - ear_right
  - lateral_right
- - center
  - tail_base
- - ear_left
  - lateral_left
- - nose
  - tail_base
- - nose
  - center
- - center
  - lateral_right
- - ear_left
  - ear_right
- - nose
  - tail_end
- - lateral_left
  - tail_base
- - lateral_right
  - tail_end
- - ear_left
  - tail_base
- - center
  - lateral_left
- - ear_left
  - nose
bodyparts: MULTI!
start: 0
stop: 1
numframes2pick: 40

    # Plotting configuration
skeleton_color: black
pcutoff: 0.9
dotsize: 12
alphavalue: 0.7
colormap: plasma

    # Training,Evaluation and Analysis configuration
TrainingFraction:
- 0.95
iteration: 0
default_net_type: resnet_50
default_augmenter: multi-animal-imgaug
snapshotindex: -1
batch_size: 8

    # Cropping Parameters (for analysis and outlier frame detection)
cropping: false
croppedtraining: true
    #if cropping is true for analysis, then set the values here:
x1: 0
x2: 640
y1: 277
y2: 624

    # Refinement configuration (parameters from annotation dataset configuration also relevant in this stage)
corner2move2:
- 50
- 50
move2corner: true
video_sets_original:
  C:\DeepLabCut\fc2_save_2020-06-28-134342-0000.mp4:
    crop: 0, 400, 0, 400

**Comment by jeylau** [comment]
The value for uniquebodyparts does not look right; can you confirm it is [8]? This must be causing trouble, as it counts as 1 bodypart, whereas I doubt it was labeled and thus appears in the pickle file.

**Comment by mattka65** [comment]
Thank you for pushing me in the right direction. It was indeed the uniquebodyparts that was giving me issues. I had misinterpeted its meaning!
