### ISSUE TITLE
Label mismatch between the predictions and the human labels

### ISSUE THREAD

**Issue by mfkeles** [DeepLabCut/DeepLabCut#935]
I converted my single animal project into a multi-animal project to benefit from the skeleton feature. maDLC did a phenomenal job by the way and solved all my prev problems related to tracking. However, I noticed when I run evaluate network the colors don't match between the predictions and human labels. I have encountered this issue in 2.1.7 see [here](https://forum.image.sc/t/label-mismatch-between-plotted-labeled-frames-and-plotted-evaluation-results/37777) and [here](https://github.com/DeepLabCut/DeepLabCut/pull/689). I think I am running into a similar problem with 2.2b8. In 2.17 this issue was caused by changing the bodypart order in the config.yaml after adding new labels. This does not happen when I use the same labeled frames in 2.1.8.2

**Desktop (please complete the following information about your system):**
 - OS: Windows 10
 - DeepLabCut Version: 2.2b8
 - DeepLabCut mode: maDLC 

**To Reproduce**
Steps to reproduce the behavior, i.e.:

code used: `deeplabcut.evaluate_network(config_path,plotting=True)`
no error see below screenshots:

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/22876046/94756373-640bb080-0365-11eb-96ba-428808a4a18e.png)

**Additional context**
In the screenshot you see that the colors of the human labels and the predictions don't match. The ones that match are 3-4 bodyparts that stayed in the same order since I first created the project.  I don't get this mismatch when I run 2.1.8.2

**Comment by jeylau** [comment]
Great catch @backyardbiomech @mfkeles! I'm looking at it!

**Comment by jeylau** [comment]
I quickly tested #938 and it fixes the issue, but if you guys could confirm, that'd be awesome 😃

**Comment by backyardbiomech** [comment]
+ installed with `pip install git+https://github.com/DeepLabCut/DeepLabCut.git@fix_distcsv_order --user --upgrade`
+ ran on a newly trained dataset and the pictures in evaluation data look great!
+ Since it's a newly (re-)trained dataset, its difficult to tell if the distance statistics are improved, but they seem to be a little better.

Thanks for the quick fix Jessy!

**Comment by backyardbiomech** [comment]
But it seems to have created a downstream problem!
On running crossvalidation (either with the GUI or command line) I get a new error I've never had before:

```python
dlc.evaluate_multianimal_crossvalidate(config, Shuffles=[1], 
                                       edgewisecondition=True, 
                                       leastbpts=1, 
                                       init_points=20, 
                                       n_iter=50, 
                                       target='rpck_train'
                                      )
```

traceback:

```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\Miniconda3\envs\DLC\lib\site-packages\bayes_opt\target_space.py in probe(self, params)
    190         try:
--> 191             target = self._cache[_hashable(x)]
    192         except KeyError:

KeyError: (0.33708610696262625, 22.86642904742807, 0.5257960621774133)

During handling of the above exception, another exception occurred:

IndexError                                Traceback (most recent call last)
<ipython-input-7-486938fc3038> in <module>
      5                                        init_points=20,
      6                                        n_iter=50,
----> 7                                        target='rpck_train'
      8                                       )

~\AppData\Roaming\Python\Python37\site-packages\deeplabcut\pose_estimation_tensorflow\evaluate_multianimal.py in evaluate_multianimal_crossvalidate(config, Shuffles, trainingsetindex, pbounds, edgewisecondition, target, inferencecfg, init_points, n_iter, log_file, dcorr, leastbpts, printingintermediatevalues, modelprefix, plotting)
    635             leastbpts=leastbpts,
    636             modelprefix=modelprefix,
--> 637             printingintermediatevalues=printingintermediatevalues,
    638         )
    639 

~\AppData\Roaming\Python\Python37\site-packages\deeplabcut\pose_estimation_tensorflow\lib\crossvalutils.py in bayesian_search(config_path, inferencecfg, pbounds, edgewisecondition, shuffle, trainingsetindex, modelprefix, snapshotindex, target, maximize, init_points, n_iter, acq, log_file, dcorr, leastbpts, printingintermediatevalues)
    463     )
    464     opt.subscribe(Events.OPTIMIZATION_STEP, logger)
--> 465     opt.maximize(init_points=init_points, n_iter=n_iter, acq=acq)
    466 
    467     inferencecfg.update(opt.max["params"])

~\Miniconda3\envs\DLC\lib\site-packages\bayes_opt\bayesian_optimization.py in maximize(self, init_points, n_iter, acq, kappa, kappa_decay, kappa_decay_delay, xi, **gp_params)
    183                 iteration += 1
    184 
--> 185             self.probe(x_probe, lazy=False)
    186 
    187             if self._bounds_transformer:

~\Miniconda3\envs\DLC\lib\site-packages\bayes_opt\bayesian_optimization.py in probe(self, params, lazy)
    114             self._queue.add(params)
    115         else:
--> 116             self._space.probe(params)
    117             self.dispatch(Events.OPTIMIZATION_STEP)
    118 

~\Miniconda3\envs\DLC\lib\site-packages\bayes_opt\target_space.py in probe(self, params)
    192         except KeyError:
    193             params = dict(zip(self._keys, x))
--> 194             target = self.target_func(**params)
    195             self.register(x, target)
    196         return target

~\AppData\Roaming\Python\Python37\site-packages\deeplabcut\pose_estimation_tensorflow\lib\crossvalutils.py in dlc_hyperparams(**kwargs)
    421             upperbound,
    422             dcorr=dcorr,
--> 423             leastbpts=leastbpts,
    424         )
    425 

~\AppData\Roaming\Python\Python37\site-packages\deeplabcut\pose_estimation_tensorflow\lib\crossvalutils.py in compute_crossval_metrics_preloadeddata(params, columns, inference_cfg, data, trainIndices, testIndices, train_iter, train_frac, shuffle, lowerbound, upperbound, dcorr, leastbpts)
    271             train_frac,
    272             shuffle,
--> 273             np.nanmean(stats[trainIndices], axis=0),
    274             np.nanmean(stats[testIndices], axis=0),
    275         ]

IndexError: index 342 is out of bounds for axis 0 with size 342
```

**Comment by backyardbiomech** [comment]
Nevermind. I get that same error after changing back  to 2.2b8 master.
Somehow three videos paths were duplicated in my config among all of the refining, deleting frames etc., so the training dataset had duplicate entries in it.

**Comment by hummuscience** [comment]
@backyardbiomech I am having the same error you had in your last comment. How did you end up resolving it?

Creating a new training set?

**Comment by backyardbiomech** [comment]
@Cumol, Yes. I deleted the duplicate paths from my config file, created a new training set, and re-trained.
