### ISSUE TITLE
How to improve skeleton in maDLC

### ISSUE THREAD

**Issue by Hydraulic343** [DeepLabCut/DeepLabCut#936]
I have successfully created a labeled video with 2 mice and skeletons using the maDLC Colab. However, when watching the video, the skeletons do not appear for most of the video, and when they do appear they do not line up properly. I want to know what issues can cause this to happen.

For details, the video I used was more than 6 minutes long, I only labelled 20 frames during the labelling process, and the mice were moving very fast in water, and their bodies were being distorted by the water.

Let me know if you have any questions.

**Comment by jeylau** [comment]
Discussion moved here: [https://forum.image.sc/t/how-to-improve-skeleton-in-madlc/43506/3](url)
