### ISSUE TITLE
when is the "mirror" parameter used?

### ISSUE THREAD

**Issue by amaanda** [DeepLabCut/DeepLabCut#939]
Hello there!

I've been testing a lot of different combination of parameters when running DLC. I have a question and would highly appreciate it if you could help me. According to the documentation, one should set all the parameters related to data augmentation before creating the dataset but I got a little lost about this specific one.

The parameter `mirror` is used exactly in which step of the training?

What I mean is: If I set `mirror=True`, run `create_training_model_comparison()` and then set `mirror=False` before running `train_network()` will it run with or without mirror? I guess my question is if the data augmentation parameters have any influence on the step of `create_training_model_comparison`/`create_training_dataset` or if I can worry about them only when running `train_network()`.

Thanks in advance! :)

**Comment by MMathisLab** [comment]
Hi @amaanda we prefer questions to be posted on Image.SC Forum, please see out guides here: https://github.com/DeepLabCut/DeepLabCut#community-support-developers--help

But, mirror is used when you have two symmetrical points you want treated the same during training, like two knees. Typically this is rarely used.
