### ISSUE TITLE
Error in deeplabcut.create_labeled_video_3d

### ISSUE THREAD

**Issue by italab-git** [DeepLabCut/DeepLabCut#941]
Hello,

Thank for providing an exciting tool for motion analyses. I use the below codes and got an error with the last `create_labeled_video_3d` function (please see the screenshot 2). I guess that the error may be caused by the result with a `triangulate` function that says "Overall of frames=430, whereas Detected frames = 428" (screenshot 1), but I don't know how to fix it.

I'm also not sure that `config_path` in the sample code (`deeplabcut.create_labeled_video_3d(config_path, ['triangulated_file_folder'], start=50, end=250)`) mentions to the `config.yaml` file that was created by a `create_new_project_3d` function.

Thank you for your help.

**[Operating system and environment]**
 Ubuntu 18.04.5 LTS, with an Anaconda Env, & DeepLabCut2.2b7.

**[codes]**

```
deeplabcut.create_new_project_3d('3dmodel','kato',num_cameras = 2) 
deeplabcut.calibrate_cameras(config_path3d, cbrow=8, cbcol=6, calibrate=False, alpha=0.9) 
deeplabcut.calibrate_cameras(config_path3d, cbrow=8, cbcol=6, calibrate=True, alpha=0.9) 
deeplabcut.check_undistortion(config_path3d, cbrow=8, cbcol=6) 
deeplabcut.triangulate('/home/italab/DLC/3dmodel-kato-2020-09-25-3d/config.yaml', '/home/italab/DLC/sample', filterpredictions=True) 
deeplabcut.create_labeled_video_3d('/home/italab/DLC/3dmodel-kato-2020-09-25-3d/config.yaml', ['/home/italab/DLC/sample'], start=50, end=100)
```

**Screenshot 1 (deeplabcut.triangulate)**

![triangulate_result](https://user-images.githubusercontent.com/72374302/95046065-4bf9af80-071e-11eb-9205-9f3b4bedf285.png)

**Screenshot 2 (deeplabcut.create_labeled_video_3d)**
![labeled_result](https://user-images.githubusercontent.com/72374302/95046072-4ef4a000-071e-11eb-95f3-a2667ff005bf.png)

**Comment by MMathisLab** [comment]
you would need to make the videos the same length; if one is 2 frames shorter, this will happen. We are more lenient in the triangulation step, but not for the video; hard to know if first two frames are dropped, last two, etc :). Hope that helps.

**Comment by italab-git** [comment]
Thank you for your reply.

I found the reason that something wrong occurred with video converting software I used, and the DLC program cannot detect the correct number of frames. Thank you anyway.
