### ISSUE TITLE
maDLC Refine Tracklets memory error

### ISSUE THREAD

**Issue by Shachafbe** [DeepLabCut/DeepLabCut#943]
Hi there :)
Using maDLC 2.2b7, on windows with GeForce RTX 2080Ti GPU.
I'm working on 8 animals with 6 body parts each.
At the beginning I worked on my big 12 hours video and it went super well, recognizing 8 fish after labeling only 20 frames (exciting!).  
But when I tried to run Refine Tracklets it didn't let me launch the GUI with the memory error below. 
I tried to analyze a shorter 1 hour movie but same message. 
Is there any parameter I should try to change or maybe I should reduce the amount of animals being tracked (if so, can I use the same labeled frames somehow?)

Thanks a lot in advance, 
and for this incredible tool!

---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
C:\ProgramData\Anaconda3\envs\DLC-GPU1\lib\site-packages\deeplabcut\gui\refine_tracklets.py in refine_tracklets(self, event)
    272             min_tracklet_len=self.slider_track.GetValue(),
    273             max_gap=self.slider_gap.GetValue(),
--> 274             trail_len=self.length_track.GetValue(),
    275         )
    276         self.export.Enable()

C:\ProgramData\Anaconda3\envs\DLC-GPU1\lib\site-packages\deeplabcut\refine_training_dataset\tracklets.py in refine_tracklets(config, pickle_or_h5_file, video, min_swap_len, min_tracklet_len, max_gap, trail_len)
   1120     manager = TrackletManager(config, min_swap_len, min_tracklet_len, max_gap)
   1121     if pickle_or_h5_file.endswith("pickle"):
-> 1122         manager.load_tracklets_from_pickle(pickle_or_h5_file)
   1123     else:
   1124         manager.load_tracklets_from_hdf(pickle_or_h5_file)

C:\ProgramData\Anaconda3\envs\DLC-GPU1\lib\site-packages\deeplabcut\refine_training_dataset\tracklets.py in load_tracklets_from_pickle(self, filename, auto_fill)
    330         with open(filename, "rb") as file:
    331             tracklets = pickle.load(file)
--> 332         self._load_tracklets(tracklets, auto_fill)
    333         self._xy = self.xy.copy()
    334

C:\ProgramData\Anaconda3\envs\DLC-GPU1\lib\site-packages\deeplabcut\refine_training_dataset\tracklets.py in _load_tracklets(self, tracklets, auto_fill)
    203             completeness = nonempty.sum()
    204             if completeness >= self.min_tracklet_len:
--> 205                 is_single = np.isnan(to_fill[:, mask_multi]).all()
    206                 if is_single:
    207                     to_fill = to_fill[:, mask_single]

MemoryError:
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
C:\ProgramData\Anaconda3\envs\DLC-GPU1\lib\site-packages\deeplabcut\gui\refine_tracklets.py in refine_tracklets(self, event)
    272             min_tracklet_len=self.slider_track.GetValue(),
    273             max_gap=self.slider_gap.GetValue(),
--> 274             trail_len=self.length_track.GetValue(),
    275         )
    276         self.export.Enable()

C:\ProgramData\Anaconda3\envs\DLC-GPU1\lib\site-packages\deeplabcut\refine_training_dataset\tracklets.py in refine_tracklets(config, pickle_or_h5_file, video, min_swap_len, min_tracklet_len, max_gap, trail_len)
   1120     manager = TrackletManager(config, min_swap_len, min_tracklet_len, max_gap)
   1121     if pickle_or_h5_file.endswith("pickle"):
-> 1122         manager.load_tracklets_from_pickle(pickle_or_h5_file)
   1123     else:
   1124         manager.load_tracklets_from_hdf(pickle_or_h5_file)

C:\ProgramData\Anaconda3\envs\DLC-GPU1\lib\site-packages\deeplabcut\refine_training_dataset\tracklets.py in load_tracklets_from_pickle(self, filename, auto_fill)
    329         self.filename = filename
    330         with open(filename, "rb") as file:
--> 331             tracklets = pickle.load(file)
    332         self._load_tracklets(tracklets, auto_fill)
    333         self._xy = self.xy.copy()

MemoryError:

**Comment by jeylau** [comment]
Hi @Shachafbe, we had improved memory management with 2.2b8. Could you update and let us know if that fixes your issue?

**Comment by Shachafbe** [comment]
It worked!
Thank you
