### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not list

### ISSUE THREAD

**Issue by hackedintothemainframe** [DeepLabCut/DeepLabCut#946]
OS: macOS Catalina 10.15.6 with an Anaconda Env 
DeepLabCut Version:  2.2b8
Anaconda env used: DLC-CPU

*I am new to Python* I'm attempting a trial run using a single short video. I am attempting to label frames for a video containing 2 mice, but am encountering a type error that I can't decipher. I suspect this is related to the config (yaml) file.

Your help is **very** much appreciated!

<details><summary>Code output</summary><p>

Config file read successfully.
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 19.01  seconds to 23.01  seconds.
Extracting and downsampling... 241  frames from the video.
241it [00:00, 516.10it/s]
Kmeans clustering ... (this might take a while)
Frames were successfully extracted.

You can now label the frames using the function 'label_frames' (if you extracted enough frames for all videos).
Traceback (most recent call last):
  File "/Users/person/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/gui/label_frames.py", line 102, in label_frames
    deeplabcut.label_frames(self.config)
  File "/Users/person/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 253, in label_frames
    wd = Path(config).resolve().parents[0]
  File "/Users/person/opt/anaconda3/envs/DLC-CPU/lib/python3.7/pathlib.py", line 1027, in __new__
    self = cls._from_parts(args, init=False)
  File "/Users/person/opt/anaconda3/envs/DLC-CPU/lib/python3.7/pathlib.py", line 674, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/Users/person/opt/anaconda3/envs/DLC-CPU/lib/python3.7/pathlib.py", line 658, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not list

</p></details>

**How to Reproduce the problem**
1. Go to GUI
2. Extract frames (automatic, crop=false, feedback=no, OpenCV=yes, kmeans at 1 cluster step, GUI slider width=25)
3. Label frames

config file for reference:

![Screen Shot 2020-10-06 at 3 19 57 PM](https://user-images.githubusercontent.com/72467961/95250421-1620fd80-07e8-11eb-90b8-3843d7d5e3b8.png)

**Comment by jeylau** [comment]
Does this help? https://forum.image.sc/t/typeerror-expected-str-bytes-or-os-pathlike-object-not-list/42660
Also, note that in your config `uniquebodyparts` should be lower case, and those bodyparts should not be included in your skeleton.

**Comment by jeylau** [comment]
@hackedintothemainframe, did that fix your problem?

**Comment by jeylau** [comment]
Have you tried updating pandas?

**Comment by hackedintothemainframe** [comment]
Both Pandas (1.1.2) and DLC (2.2b8) are up-to-date. I also ran the command 

> pip install --upgrade matplotlib

 out of paranoia and it seems to have worked. However, I noticed when I launch DLC the GUI does not look the same as the one in the 2.2 multianimal youtube tutorial, and I do not have an option to click on 'is this a multianimal project?' when creating a new project. I'm able to extract frames, but when trying to label the frames, the pop-up window does not load the extracted frames.
Errorlog:
<details><summary>Code output</summary><p>

Last login: Wed Oct 14 12:59:08 on ttys000
(base) user@persons-MacBook-Pro ~ % conda activate DLC-CPU
(DLC-CPU) user@persons-MacBook-Pro ~ % pythonw -m deeplabcut
Starting GUI...
Traceback (most recent call last):
  File "/Users/user/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/gui/create_new_project.py", line 333, in create_new_project
    page7 = Evaluate_network(self.parent,self.gui_size,self.cfg)
  File "/Users/user/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/gui/evaluate_network.py", line 79, in __init__
    self.bodyparts_to_compare = wx.CheckListBox(self, choices=bodyparts, style=0,name = "Select the bodyparts")
TypeError: CheckListBox(): arguments did not match any overloaded call:
  overload 1: argument 'choices' has unexpected type 'NoneType'
  overload 2: too many arguments
Config file read successfully.
Extracting frames based on kmeans ...
Kmeans-quantization based extracting of frames from 19.01  seconds to 23.01  seconds.
Extracting and downsampling... 241  frames from the video.
241it [00:00, 475.29it/s]
Kmeans clustering ... (this might take a while)
Frames were successfully extracted.

You can now label the frames using the function 'label_frames' (if you extracted enough frames for all videos).
Traceback (most recent call last):
  File "/Users/user/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/labeling_toolbox.py", line 466, in browseDir
    self.dataFrame = pd.read_hdf(os.path.join(self.dir,'CollectedData_'+self.scorer+'.h5'),'df_with_missing')
  File "/Users/user/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/pandas/io/pytables.py", line 387, in read_hdf
    raise FileNotFoundError(f"File {path_or_buf} does not exist")
FileNotFoundError: File /Users/user/demo-user-2020-09-28/labeled-data/testvid/CollectedData_user.h5 does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/opt/anaconda3/envs/DLC-CPU/lib/python3.7/site-packages/deeplabcut/generate_training_dataset/labeling_toolbox.py", line 482, in browseDir
    for bodypart in self.bodyparts:
TypeError: 'NoneType' object is not iterable

</p></details>

**Comment by MMathisLab** [comment]
@hackedintothemainframe 

based on this comment: >>  I noticed when I launch DLC the GUI does not look the same as the one in the 2.2 multianimal youtube tutorial, and I do not have an option to click on 'is this a multianimal project?'

then you are not using 2.2b8. Please run:
```
pythonw 

import deeplabcut 

deeplabcut.__version__
```
what does that produce?

**Comment by hackedintothemainframe** [comment]
As suspected, it looks like the running version is 2.1.8.2. I don't know how this is the case, given I carefully followed the installation instructions, and my DLC folder looks like it contains the up-to-date 2.2b8 files. I've also tried running 
`pip install --upgrade deeplabcut`
while in my environment, but it still returns 2.1.8.2 for some reason. I've tried reinstalling the environment, and updating every library as well.

**Comment by jeylau** [comment]
`pip install --upgrade deeplabcut` grabs the latest official release, which is 2.1.8.2. You need to specify `pip install deeplabcut==2.2b8` to make sure you install the latest beta 😃

**Comment by hackedintothemainframe** [comment]
This seems to have done the trick, THANK YOU!

This may be a rookie mistake on my part, but it would be a really helpful addition to the installation page for people like me :)

**Comment by MMathisLab** [comment]
Hi @hackedintothemainframe right now we really encourage new users to only use the stable release; the beta is subject to change, and users should be comfortable with uninstalling, upgrading, using the code directly from github, etc, hence why we are not pinning it yet as stable, as it's for users to try it and give feedback. The stable multi-animal package will come out this fall though!
