### ISSUE TITLE
Retraining using predicted / inferred data - easiest method

### ISSUE THREAD

**Issue by catubc** [DeepLabCut/DeepLabCut#950]
**Is your feature request related to a problem? Please describe.**

Hello.  We're using maDLC to do multi-animal inference and it is doing pretty good now.  I have a couple of questions regarding retraining the nns with predicted results to get even better predictions.  So I would train on 1500 frames and predict / label ~ 2million. I would then pick 10,000 - 20,000 (or more?) of the predicted frames + initial labels and retrain DLC.

1.  I know DLC requires unique animal ID tracking - but this is obviously not going to be available on the predicted frames (and correcting the IDs is too much manual work).  Is it ok to train without animal ID preserved? 

2.  Is there a GUI or method already available that can generate the training .csv files from prediction data?

Thanks so much!

**Comment by MMathisLab** [comment]
>> I know DLC requires unique animal ID tracking - but this is obviously not going to be available on the predicted frames (and correcting the IDs is too much manual work). Is it ok to train without animal ID preserved?

Right now the ID part is actually not described; hence, you should try to label consistently. more will be described in the forthcoming preprint. 

For your desire to use the inference data for training, that is currently not implemented, but what is is if/when you make any corrections in the refine tracklets GUI, you can click merge, and this takes any frame you edited and places it into a new dataframe that you can use for re-training. You can use this as is, or of course edit code to just ask for it to grab all frames in every analyzed video for re-training.
