### ISSUE TITLE
Unable To Take and Process Camera Calibration Images

### ISSUE THREAD

**Issue by Dvirbs** [DeepLabCut/DeepLabCut#954]
**Operating system and DeepLabCut version**
OS: Windows 10
DeepLabCut Version: 2.1.3
Browser: Chrome

**Describe the problem**
Problem in the iterative process of the camera calibration.
A set of images are selected after I delete from the folder any bad pairs.
when I try to calibrate the two cameras using:
deeplabcut.calibrate_cameras(config_path3d, cbrow=8, cbcol=6, calibrate=True, alpha=0.9)
I am getting an error.
In order to solve the problem I repeatedly try to delete the bad pairs to improve the accuracy of the corners.
I still gets the same error when I try to perform the code of the calibration (using 'True' )

```

`error                                     Traceback (most recent call last)
<ipython-input-8-8e9d0546cf06> in <module>
----> 1 deeplabcut.calibrate_cameras(config_path3d, cbrow=8, cbcol=6, calibrate=True, alpha=0.9)

~\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_3d\camera_calibration.py in calibrate_cameras(config, cbrow, cbcol, calibrate, alpha)
    156         for pair in camera_pair:
    157             print("Computing stereo calibration for " %pair)
--> 158             retval, cameraMatrix1, distCoeffs1, cameraMatrix2, distCoeffs2, R, T, E, F = cv2.stereoCalibrate(objpoints[pair[0]],imgpoints[pair[0]],imgpoints[pair[1]],dist_pickle[pair[0]]['mtx'],dist_pickle[pair[0]]['dist'], dist_pickle[pair[1]]['mtx'], dist_pickle[pair[1]]['dist'],(h,  w),flags = cv2.CALIB_FIX_INTRINSIC)
    159 
    160             # Stereo Rectification

error: OpenCV(3.4.7) C:\projects\opencv-python\opencv\modules\calib3d\src\calibration.cpp:3120: error: (-215:Assertion failed) nimages > 0 && nimages == (int)imagePoints1.total() && (!imgPtMat2 || nimages == (int)imagePoints2.total()) in function 'cv::collectCalibrationData'`

```

**How to Reproduce the problem**

- Workflow for deeplabcut 3d

1. import deeplabcut
2. creating new project-
config_path3d=deeplabcut.create_new_project_3d('3DProject_try#7','Dvir',num_cameras = 2,working_directory=(r"C:\Users\Owner\Desktop\Dvir\DvirDLC\projects"))
3. place images into the calibration_images directory and set the camera names.
4.run 
deeplabcut.calibrate_cameras(config_path3d, cbrow=8, cbcol=6, calibrate=False, alpha=0.9)
5.delete any bad pairs 
5. run 
deeplabcut.calibrate_cameras(config_path3d, cbrow=8, cbcol=6, calibrate=True, alpha=0.9)
get error 

![image](https://user-images.githubusercontent.com/71714798/95682617-e199b100-0bee-11eb-8f3a-86a094e9527e.png)
![image](https://user-images.githubusercontent.com/71714798/95682367-83b89980-0bed-11eb-9bfa-f74501a1eff5.png)
![image](https://user-images.githubusercontent.com/71714798/95682379-8f0bc500-0bed-11eb-95eb-78c5ff15baa3.png)

This is folders of two experimental projects:
#1 https://drive.google.com/drive/folders/1OBmSmoNwQOBWTgmxPm-LmpNfIXFl4plY?usp=sharing
#2 https://drive.google.com/drive/folders/1OBmSmoNwQOBWTgmxPm-LmpNfIXFl4plY?usp=sharing

**Comment by MMathisLab** [comment]
could you try updating your OpenCV and DLC versions, since these are quite old? You can make a new env to use, vs. your old one. 

https://github.com/DeepLabCut/DeepLabCut/blob/master/conda-environments/README.md

seems related to your #948, so I will close that so we can focus here.

**Comment by radhamal** [comment]
@Dvirbs I'm currently getting the same error you were...did updating OpenCV and DLC solve the problem or did you do something else as well?
