### ISSUE TITLE
DLC option without GUI

### ISSUE THREAD

**Issue by raghavian** [DeepLabCut/DeepLabCut#959]
After making the training set using the GUI an option to suppress the GUI mode so that the training can be ported to a machine without display (for ex: a GPU cluster) might be useful. 

Currently, the matplotlib backend dependency on 'TkAgg' on Ubuntu does not allow this with this error:
"ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running"

Changing this to 'Agg' when running in a non-gui mode would be useful also during inference time.

**Comment by jeylau** [comment]
This is the behavior you get when using DeepLabCut in light mode, as follows:
```
import os
os.environ['DLClight'] = 'True'
import deeplabcut
```
