### ISSUE TITLE
setting config_path (and Comments on first usage of DLC2)

### ISSUE THREAD

**Issue by mschart** [DeepLabCut/DeepLabCut#96]
Hello,

Here just two comments when trying out DLC2:

The set_config_path step tries to use config as a command when one declares "config-path", so that's not good. Also it should be the path to the config.yaml file (that's not clear in the instructions). I'm sure this will confuse some users. 

The labelling toolbox has one strong disadvantage to fiji: There is no auto-advance option, so after labelling each body part one need to click next image, which is much slower than just annotating one body part at a time and using auto-next-image when marking the position.

Cheers,

Michael

**Comment by AlexEMG** [comment]
Hi Michael,

Thanks for your feedback. What do you mean by ```set_config_path```? Also when you create a new project, like:

```config_path=deeplabcut.create_new_project(`Name of the project',`Name of the experimenter', [`Full path of video 1'])```

Then it will create the project in that folder and return the projectpath. So for all next steps, you can just use that variable, i.e. 

```deeplabcut.extract_frames(config_path,`manual')```.

I really like the GUIs, especially the relabeling GUI! You can of course keep using Fiji (which is great!)

Cheers,
Alexander

**Comment by MMathisLab** [comment]
please see the detailed guide which states that the config-path (or whatever you want to call your path variable), must be the full path: 

https://github.com/AlexEMG/DeepLabCut/blob/master/docs/functionDetails.md#b-configure-the-project


I would also ask you look at the demo notebooks, as it is clear that the configuration-path must be the full path to the config.yaml file.

**Comment by mschart** [comment]
Yea, I'm the typical quick and dirty test-user I guess ;)

**Comment by MMathisLab** [comment]
docs updated.

**Comment by AlexEMG** [comment]
Finally some example conversion code here: https://github.com/AlexEMG/DLCutils
