### ISSUE TITLE
Skeleton for single animal tracking

### ISSUE THREAD

**Issue by bramn22** [DeepLabCut/DeepLabCut#960]
Hi,

Is it correct that a defined skeleton is not used for training, by default, in a single animal tracking project (also not multi-limb)? From the code, it seems that the pose_config parameter 'partaffinityfield_predict' controls whether the skeleton has an influence on the model loss? This parameter seems to be automatically set to False when initializing the project as a single animal project, and to True when initializing it as a multi animal project.

Also, if the skeleton is not used by default, is it known whether including the skeleton in training in the single animal tracking case, tracking performance is improved?

Thanks,
Bram

**Comment by mfkeles** [comment]
I think the skeleton is only used if you have a multi-animal project by definition. So you can create a multi-animal project and use single animal videos to analyze, that way you can benefit from the skeleton feature. However, there are some drawbacks to this. The analysis is significantly slower (5-6x in my experience, see [here)](https://forum.image.sc/t/slower-analysis-speed-with-2-2b8-vs-2-1-8-single-animal/43593/3) but you get improved tracking (again, in my experience).

**Comment by vivekhsridhar** [comment]
Hi,

I have 5 different objects in my scene that are static. This is recorded with an overhead camera that changes altitude sometimes over the course of the experiment. With the goal of tracking the camera motion, should I use:
 
a) Multi-animal tracking, treating each of these objects as being independent individuals OR
b) Single animal tracking including a skeleton as the relative distances between these objects is still conserved over the course of the experiment? 

Thank you.

Vivek

**Comment by MMathisLab** [comment]
neither; I would use normal DLC and define bodyparts per object. 
```
object1A
object1B .
.. 

object 5A
```

**Comment by vivekhsridhar** [comment]
Aaahh.. Thanks so much for the quick response! My only concern was that there are several similar looking objects (but not identical) in the scene. I essentially want DLC to pick out exactly these 5 among several other such objects. Essentially, I'm looking to identify location of 5 trees among several others on the video. They're all sufficiently spread out. Would this still be what you'd do?

Thanks again.

Vivek

**Comment by MMathisLab** [comment]
As long as you can label them and tell them apart, then it's not an issue :)

**Comment by vivekhsridhar** [comment]
Perfect!! Thanks so much again!!! I really appreciate it. :)
