### ISSUE TITLE
Splitting a large file before analysis

### ISSUE THREAD

**Issue by mfkeles** [DeepLabCut/DeepLabCut#966]
OS: Ubuntu 20.04 LTS
DeepLabCut Version: DLC2.2b8
Anaconda env used:

**Describe the problem**
I am trying to split a 17 gb vid into 10 smaller videos following [this issue](https://github.com/DeepLabCut/DeepLabCut/issues/814). However, I think the function name has changed. I can't find the `split_video` function in the auxfun_videos script. When I search the repo I also get nothing. 

So instead I have tried:
```
from import.deeplabcut.utils.auxfun_videos import VideoReader
vid_path = '/home/bfvideo.avi'
vid = VideoReader(vid_path)
clips = vid.split(n_splits=10)

```

I get a ffprobe error and I am not sure how to proceed.

Thank you!

**Comment by jeylau** [comment]
@mfkeles, great point! I forgot to document that the function had moved to the new video interface, although you did find the new one 😃 ffprobe should be bundled with ffmpeg; does `sudo apt-get install ffmpeg` fix it?

**Comment by mfkeles** [comment]
Thank you!! That did it!

For future reference people can split their videos by:
```
sudo apt-get install ffmpeg
from deeplabcut.utils.auxfun_videos import VideoWriter
vid_path = '/home/bfvideo' 
vid = VideoWriter(vid_path)
clips = vid.split(n_splits=10)
```
