### ISSUE TITLE
Problem labeling in 2.2b5 and above releases

### ISSUE THREAD

**Issue by jesmjones** [DeepLabCut/DeepLabCut#968]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Your Operating system and DeepLabCut version**

Please complete the following information about your system:

OS: Windows 10
DeepLabCut Version: 2.2b8, 2.2b7,b6, b5
Anaconda env used: python 3.6

I'm having issues labeling in multi-animal mode in version 2.2b7 and b8. It seems like the issue lies in wx and am wondering if its a compatibility issue between this latest version of DLC and wx? I attached the error message below. I've uninstalled and reinstalled wx python and the issue still stands

<details><summary>>>> import deeplabcut
>>>
>>> config_path = (r"C:\Users\NAPEadmin\Desktop\tr-project-2mouse-jj-agf-2020-10-08-20201015T230516Z-001\tr-project-2mouse-jj-agf-2020-10-08\config.yaml")
>>> deeplabcut.label_frames(config_path)

>>></summary><p>

[Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\NAPEadmin\.conda\envs\jess_dlc_multi\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 427, in label_frames
    multiple_individuals_labeling_toolbox.show(config)
  File "C:\Users\NAPEadmin\.conda\envs\jess_dlc_multi\lib\site-packages\deeplabcut\generate_training_dataset\multiple_individuals_labeling_toolbox.py", line 1344, in show
    frame = MainFrame(None, config).Show()
  File "C:\Users\NAPEadmin\.conda\envs\jess_dlc_multi\lib\site-packages\deeplabcut\generate_training_dataset\multiple_individuals_labeling_toolbox.py", line 289, in __init__
    widgetsizer.Add(self.quit, 1, wx.ALL | wx.ALIGN_RIGHT, 15)
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_RIGHT)" failed at ..\..\src\common\sizer.cpp(2098) in wxBoxSizer::DoInsert(): Horizontal alignment flags are ignored in horizontal sizers]

</p></details>

**Comment by jeylau** [comment]
Hey @jesmjones, your wxpython version is likely different from 4.0.7post2; please install this one. A quick search pointed me to [https://github.com/DeepLabCut/DeepLabCut/issues/682](url).
