### ISSUE TITLE
Matlab Version

### ISSUE THREAD

**Issue by nmtimme** [DeepLabCut/DeepLabCut#970]
Hello

Have you considered developing a matlab version of the code? I very much appreciate all the work you've done, the program is wonderful, and it is very nice that it is open source. However, it can be difficult and time consuming to get it working if you aren't super familiar with Python or if you don't have the right machine. If you aren't interested in doing it, I completely understand. I just think this would dramatically increase the number of users. Thanks again for all your hard work and have a good day!

~Nick

**Comment by MMathisLab** [comment]
thanks Nick for the feedback, but no we won't be offering Matlab, as it's not open source and expensive :). We hope that the DLC GUI provides the best of both worlds, i.e. zero programming experience is needed to use DLC and have access to state of the art pose estimation. For those wanting to learn more Python though, I recommend checking this out: http://DLCcourse.deeplabcut.org 

Cheers, 
Mackenzie

**Comment by nmtimme** [comment]
The deeplabcut GUI is very helpful, yes! While I managed to get it working without having to code in Python, it did take me about 15 hours to work through all the dependencies and issues surrounding which system I was running it on. So, I think it is important to remember that your code (which I greatly appreciate!) does come with a cost. It would be nice to offer users a different method of payment (i.e., paying money to Matlab). Furthermore, I think it would dramatically increase the number of users. Thank you again for all your hard work in producing this software!
