### ISSUE TITLE
Network Evaluation error.

### ISSUE THREAD

**Issue by Agulore** [DeepLabCut/DeepLabCut#972]
OS:  Windows 10
DeepLabCut Version: 2.2b7
Anaconda env used: DLC-GPU

**Describe the problem**

Hi, After training network, if I start an evaluation of the network the process stops halfway and give this error message. Please, can you help me to solve this issue?

Please place code inside this:

<details><summary>Code output</summary><p>

The network is now trained and ready to evaluate. Use the function 'evaluate_network' to evaluate the network.
C:\Users\labappelbaum\Nematostella_6bodyparts_1polypOct1/evaluation-results/  already exists!
Config:
{'all_joints': [[0], [1], [2], [3], [4], [5]],
 'all_joints_names': ['head',
                      'column1',
                      'column2',
                      'column3',
                      'column4',
                      'physa'],
 'batch_size': 1,
 'bottomheight': 400,
 'crop': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-9\\UnaugmentedDataSet_Nematostella_6bodyparts_1polypOct1Oct1\\Nematostella_6bodyparts_1polypOct1_Raph95shuffle1.mat',
 'dataset_type': 'imgaug',
 'deterministic': False,
 'display_iters': 1000,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'C:\\Users\\labappelbaum\\AppData\\Roaming\\Python\\Python37\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-9\\UnaugmentedDataSet_Nematostella_6bodyparts_1polypOct1Oct1\\Documentation_data-Nematostella_6bodyparts_1polypOct1_95shuffle1.pickle',
 'min_input_size': 64,
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 6,
 'optimizer': 'sgd',
 'pairwise_huber_loss': False,
 'pairwise_predict': False,
 'partaffinityfield_predict': False,
 'pos_dist_thresh': 17,
 'project_path': 'C:\\Users\\labappelbaum\\Nematostella_6bodyparts_1polypOct1',
 'regularize': False,
 'rightwidth': 400,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'C:\\Users\\labappelbaum\\Nematostella_6bodyparts_1polypOct1\\dlc-models\\iteration-9\\Nematostella_6bodyparts_1polypOct1Oct1-trainset95shuffle1\\test\\snapshot',
 'stride': 8.0,
 'topheight': 400,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Running  DLC_resnet50_Nematostella_6bodyparts_1polypOct1Oct1shuffle1_1030000  with # of trainingiterations: 1030000
Initializing ResNet
2020-10-25 09:38:53.123564: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2020-10-25 09:38:53.131999: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-25 09:38:53.146646: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2020-10-25 09:38:53.154815: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2020-10-25 09:38:53.161550: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6307 MB memory) -> physical GPU (device: 0, name: Quadro RTX 4000, pci bus id: 0000:b3:00.0, compute capability: 7.5)
Analyzing data...
2476it [01:24, 29.42it/s]
Done and results stored for snapshot:  snapshot-1030000
Results for 1030000  training iterations: 95 1 train error: 3.63 pixels. Test error: 6.07  pixels.
With pcutoff of 0.6  train error: 3.61 pixels. Test error: 6.07 pixels
Thereby, the errors are given by the average distances between the labels by DLC and the scorer.
Plotting...
 56%|███████████████████████████████████████████▉                                  | 1396/2476 [08:17<06:24,  2.81it/s]
---------------------------------------------------------------------------
wxAssertionError                          Traceback (most recent call last)
~\AppData\Roaming\Python\Python37\site-packages\deeplabcut\gui\evaluate_network.py in evaluate_network(self, event)
    338             plotting=plotting,
    339             show_errors=True,
--> 340             comparisonbodyparts=self.bodyparts,
    341         )
    342

~\AppData\Roaming\Python\Python37\site-packages\deeplabcut\pose_estimation_tensorflow\evaluate.py in evaluate_network(config, Shuffles, trainingsetindex, plotting, show_errors, comparisonbodyparts, gputouse, rescale, modelprefix, c_engine)
    919                                 trainIndices,
    920                                 DataCombined * 1.0 / scale,
--> 921                                 foldername,
    922                             )  # Rescaling coordinates to have figure in original size!
    923

~\AppData\Roaming\Python\Python37\site-packages\deeplabcut\pose_estimation_tensorflow\evaluate.py in Plotting(cfg, comparisonbodyparts, DLCscorer, trainIndices, DataCombined, foldername)
    218             comparisonbodyparts,
    219             DLCscorer,
--> 220             foldername,
    221         )
    222

~\AppData\Roaming\Python\Python37\site-packages\deeplabcut\utils\visualization.py in plot_and_save_labeled_frame(DataCombined, ind, trainIndices, cfg, colors, comparisonbodyparts, DLCscorer, foldername, scaling)
    158         colors,
    159         cfg,
--> 160         scaling=scaling,
    161     )
    162     save_labeled_frame(fig, fn, foldername, ind in trainIndices)

~\AppData\Roaming\Python\Python37\site-packages\deeplabcut\utils\visualization.py in make_labeled_image(DataCombined, imagenr, pcutoff, imagebasefolder, Scorers, bodyparts, colors, cfg, labels, scaling)
     50     else:
     51         h, w = np.shape(im)
---> 52     fig, ax = prepare_figure_axes(w, h, scaling)
     53     ax.imshow(im, "gray")
     54     for scorerindex, loopscorer in enumerate(Scorers):

~\AppData\Roaming\Python\Python37\site-packages\deeplabcut\utils\visualization.py in prepare_figure_axes(width, height, scale, dpi)
    182
    183 def prepare_figure_axes(width, height, scale=1.0, dpi=100):
--> 184     fig = plt.figure(frameon=False, figsize=(width * scale / dpi, height * scale / dpi))
    185     ax = fig.add_subplot(111)
    186     ax.axis("off")

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\pyplot.py in figure(num, figsize, dpi, facecolor, edgecolor, frameon, FigureClass, clear, **kwargs)
    675                                         frameon=frameon,
    676                                         FigureClass=FigureClass,
--> 677                                         **kwargs)
    678         fig = figManager.canvas.figure
    679         if figLabel:

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\pyplot.py in new_figure_manager(*args, **kwargs)
    297     """Create a new figure manager instance."""
    298     _warn_if_gui_out_of_main_thread()
--> 299     return _backend_mod.new_figure_manager(*args, **kwargs)
    300
    301

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\backends\backend_wx.py in new_figure_manager(cls, num, *args, **kwargs)
   1681             # garbage collected.
   1682             _BackendWx._theWxApp = wxapp
-> 1683         return super().new_figure_manager(num, *args, **kwargs)
   1684
   1685     @classmethod

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\backend_bases.py in new_figure_manager(cls, num, *args, **kwargs)
   3492         fig_cls = kwargs.pop('FigureClass', Figure)
   3493         fig = fig_cls(*args, **kwargs)
-> 3494         return cls.new_figure_manager_given_figure(num, fig)
   3495
   3496     @classmethod

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\backends\backend_wx.py in new_figure_manager_given_figure(cls, num, figure)
   1685     @classmethod
   1686     def new_figure_manager_given_figure(cls, num, figure):
-> 1687         frame = cls._frame_class(num, figure)
   1688         figmgr = frame.get_figure_manager()
   1689         if mpl.is_interactive():

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\backends\backend_wx.py in __init__(self, num, fig)
    935         self.figmgr = FigureManagerWx(self.canvas, num, self)
    936
--> 937         self.toolbar = self._get_toolbar()
    938
    939         if self.figmgr.toolmanager:

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\backends\backend_wx.py in _get_toolbar(self)
    970     def _get_toolbar(self):
    971         if mpl.rcParams['toolbar'] == 'toolbar2':
--> 972             toolbar = NavigationToolbar2Wx(self.canvas)
    973         elif mpl.rcParams['toolbar'] == 'toolmanager':
    974             toolbar = ToolbarWx(self.toolmanager, self)

~\AppData\Roaming\Python\Python37\site-packages\matplotlib\backends\backend_wx.py in __init__(self, canvas, coordinates)
   1134             self.AddControl(self._label_text)
   1135
-> 1136         self.Realize()
   1137
   1138         NavigationToolbar2.__init__(self, canvas)

wxAssertionError: C++ assertion "Assert failure" failed at ..\..\src\msw\toolbar.cpp(938) in wxToolBar::Realize(): Could not add bitmap to toolbar

</p></details>

**Comment by jeylau** [comment]
Hello @Agulore, this is an issue related to #910 that we recently fixed with #940. It is not yet merged, but you could pass `plotting=False` meanwhile 😃.
