### ISSUE TITLE
Problem single animal tracking between DLC versions

### ISSUE THREAD

**Issue by Siolaw** [DeepLabCut/DeepLabCut#973]
Hi, 

I started using DLC is June of this year. Right now I am using Spyder through the Anaconda suite to label images on my PC (Windows 10) and then train on google collab. I originally started using DLC 2.1.8 which produced really nice results
However, when I updated to DLC 2.2b5 I have been unable to get anything similar 
Any idea? In more recent versions I started saving as csv though I doubt that is the issue? Otherwise I have done everything else the same as day 1. Thanks

**Comment by jeylau** [comment]
Hello @Siolaw, this was a graphical bug we recently fixed. It should look good with 2.2b8! 😃

**Comment by Siolaw** [comment]
Hi @jeylau ok thank you! If I labeled my frames on 2.2b5 can I train on 2.2b8? Or should I start again using 2.2b8 in order to avoid this? Thanks

**Comment by jeylau** [comment]
You do not have to re-train. You can update dlc and simply re-evaluate the network, labeled images should be pretty! 😊

**Comment by Siolaw** [comment]
Hi and thanks. I did as you suggested and installed DLC 2.2b8 in google collab and re-evaluated the network but the same situation occurs. I've installed DLC 2.2b8 now on my PC so will start over and see if that fixes this. Do you think this makes sense or is there an easier solution? Thanks


Siobhán Lawless, B.S., M.S.
PhD Candidate, Neural and Behavioral Science

SUNY Downstate Medical Center

T: 240.305.2147

siobhan.lawless@downstate.edu

________________________________

**Comment by Siolaw** [comment]
Hi @jeylau and thanks. I did as you suggested and installed DLC 2.2b8 in google collab and re-evaluated the network but the same situation occurs. I've installed DLC 2.2b8 now on my PC so will start over and see if that fixes this. Do you think this makes sense or is there an easier solution? Thanks

**Comment by jeylau** [comment]
I realized I was mistaken: we merged #938 shortly after the b8 release. I'm sorry about that 😕. You'd actually need `pip install git+https://github.com/DeepLabCut/DeepLabCut.git`!

**Comment by Siolaw** [comment]
Thanks! I'll start over with this version just to be safe.

**Comment by Siolaw** [comment]
Hi @jeylau I installed as you suggested yesterday. Is the evaluate_multianimal.py file one of the files that needed to be edited? If so, when I open it it appears to be the same as before. Is that correct? Thanks

**Comment by jeylau** [comment]
Hey @Siolaw, these are the only (very small) changes you should see https://github.com/DeepLabCut/DeepLabCut/pull/938/files.

**Comment by Siolaw** [comment]
Hi @jeylau, that's what I thought. There should be 7 deletions and 1 addition in deeplabcut/pose_estimation_tensorflow/evaluate_multianimal.py, correct? At least when I have opened this file after running pip install git+https://github.com/DeepLabCut/DeepLabCut.git these minor edits don't seem to be present. I can edit them manually however my concern is that these edits will not be available when I train the network using google colab. Any suggestions? And thank you so much for your help!

**Comment by jeylau** [comment]
This is odd. You could try to uninstall deeplabcut first, and reinstall with the command above. If that still does not work, you could directly point to that specific commit: `pip install git+https://github.com/DeepLabCut/DeepLabCut.git@92d27dd116c4030bceda5a19f900d12d6caedf68`. That should not be needed though 😊
