### ISSUE TITLE
feature request dynamic cropping in maDLC (if only using 1 animal)

### ISSUE THREAD

**Issue by mfkeles** [DeepLabCut/DeepLabCut#974]
**Is your feature request related to a problem? Please describe.**
I have been getting superb tracking with maDLC (I am  using it with single animal videos). I think the skeleton feature saved us so much time and effort to clean little tracking issues we were having with the previous version. However, using maDLC for single animal tracking is not super ideal for a couple of reasons:
 - The assembly and refinement steps are not necessary for single animal videos. 
 - maDLC, naturally, can not benefit from features that are available for single animal tracking such as dynamic cropping. Thus, the analysis of videos are are slower and the speed is sacrificed in exchange of greater flexibility in refining after analysis.

**Describe the solution you'd like**
 - It would be great if there is a version of maDLC that uses dynamic cropping with single animal videos while benefiting from improved tracking with the skeleton feature. 

**Describe alternatives you've considered**
- I have tried refining my trained model as much as possible in 2.1.8.2. Labeled over 1k frames, from 10 different animals with a variety of training settings (different augmentation methods, different optimizers etc). However, it never reached the perfermonce of maDLC. 
- To circumvent the analysis speed I am currently paying for colab pro and running 4 sessions at a time plus the 1080 Ti on my computer. This setup can chew 170 gb of vid data in less than 24 hours. It pains me that my vid files are very large so to speed up processing I am also playing with diff compression methods. However, the model works great for the videos we have and storage is cheap.

**Comment by MMathisLab** [comment]
Hey @mfkeles hope you are well. Note we have a rather fully new version of maDLC out, rc3; the speed is faster and I also want to just correct 1 minor thing above, namely: The assembly is necessary for maDLC if you want to benefit from the PAFs and the graph assembly algo, which is responsible for the performance boost. Also check out DLCRNet, I am getting excellent perf. on single animal maDLC projects. 

Lastly I agree for dynamic - it's a good suggestion and still in the works; especially for when maDLC ports over to DLC-Live and you want to trigger on say 1 animal out of many ;).

**Comment by mfkeles** [comment]
Thank you @MMathisLab! I am stoked to try DLCRNet!

**Comment by MMathisLab** [comment]
Hey there @mfkeles :) SO, there is a new function for maDLC where you can pass in analyze_videos `auto_track= true` it will run the whole pipeline (track, stitch, etc). This is super useful in two ways: (1) for beginners there is less to worry about/do; (2) for those that use maDLC with a single animal, now you will get your H5, CSV, etc in 1 click :D 🎉 

I need to make a few tweaks, but it should be easier now to use dynamic cropping with single animal too (still pass the dynamic cropping). 

WIP i.e.:

```python
deeplabcut.analyze_videos(cfg, [video], videotype='mp4', auto_track=True, n_tracks = 1, dynamic=(True, 0.5, 10))
```

**Comment by MMathisLab** [comment]
closed due to being stale
