### ISSUE TITLE
How to label the key points when animal has occlusion.

### ISSUE THREAD

**Issue by ZimmerZheng** [DeepLabCut/DeepLabCut#976]
**Operating system and DeepLabCut version**

OS: Windows 10
DeepLabCut Version:  2.2b8
Anaconda env used:  DLC-GPU.yaml, downloaded from www.deeplabcut.org

**Describe the problem**

I trying to label the feature point of pig, eg. four feet. 
But it sometimes not complete, only half body remain. Should I label front feet or wait four feet appear.

**Screenshots**
If my body parts are: left-front, right-front, left-behind, right-behind. Can I only label left-front and right front when there are no hindlimbs in image.
![side](https://user-images.githubusercontent.com/20921980/97399422-22503480-1928-11eb-84f9-0e35981c2bda.PNG)
![complete](https://user-images.githubusercontent.com/20921980/97399473-3431d780-1928-11eb-82cb-9b28e52e4d14.PNG)

**Comment by MMathisLab** [comment]
In general you should not label occlusions, hope that helps!

**Comment by ZimmerZheng** [comment]
> In general you should not label occlusions, hope that helps!

Thanks, I will try and test which labeled dataset is better.
