### ISSUE TITLE
 install Camera Control

### ISSUE THREAD

**Issue by Alberto100591** [DeepLabCut/DeepLabCut#979]
Hello my name is Alberto Lopez , today i would like to request help with the followed problem , currently i am working with DeepLabCut 3D, but i have had few problem with the installation of Camera Control , so i will describe the problem:
Problem Description:
My problem is that i cannot install Camera Control because ffmpeg library can not download because de link of the page is broken
Image 1.- damaged link
![f](https://user-images.githubusercontent.com/68699532/97610185-29d01600-19da-11eb-8213-663cbad8410c.png)

Image 2.- damaged link (the page closed 18/Sep/2020)

![2](https://user-images.githubusercontent.com/68699532/97610214-318fba80-19da-11eb-9391-5fa6b3413332.png)

Could you help me?

**Comment by MMathisLab** [comment]
please post issues for that code base; the developers of DLC do not manage Camera Control: https://github.com/AdaptiveMotorControlLab/Camera_Control
