### ISSUE TITLE
[Multiple Pose prediction] cfg.stride is not present in pose_cfg.yaml (pose-tensorflow/model/XY/test)

### ISSUE THREAD

**Issue by JensBlack** [DeepLabCut/DeepLabCut#98]
I was using the new AnalyzeVideosAndExtractScoreMaps.py to use the ScoreMap with local maxima identification to find multiple bodyparts of the same kind (e.g. nose) and it works fine (Thanks for the suggestion btw).

As i am adapting my own little "predict.argmax_pose_predict", I noticed that to successfully calculate back to the origal image/video size the original code uses: 

`def argmax_pose_predict(scmap, offmat, stride):

        pos_f8 = (np.array(maxloc).astype('float') * stride + 0.5 * stride +
                  offset)
        pose.append(np.hstack((pos_f8[::-1],
                               [scmap[maxloc][joint_idx]])))
    return np.array(pose)`

**stride** is taken from the config file pose_cfg.yaml (pose-tensorflow/model/XY/test)
If I open the file to look for the value, I cannot find it. Am I missing something here?

The variable pos_f8 should have values that represent the coordinates according to the original file resolution.
_maxloc_ has the shape (72, 88, #bodyparts, 2) in my case and my images/videos have the resolution 704 x 576. 
If i fix **stride** manually (e.g. "8") I can get a slighty distorted version of the originally (by DLC "normal") correct-identified bodyparts.

**Comment by AlexEMG** [comment]
This will work, not all pose_cfg variables need to be shown in a pose_cfg file. If you load it, the rest will be read from the default list (just like in the inference step of DLC).
