### ISSUE TITLE
Delay in Refine Tracklets GUI between Labels and Individuals

### ISSUE THREAD

**Issue by mattka65** [DeepLabCut/DeepLabCut#980]
**Desktop**
OS: Windowns 10
DeepLabCut Version: 2.2b8
Using the DLC GUI

**Describe the Bug**
I'm using maDLC to track four mice in an arena. I've already analyzed the video and converted it to tracklets. On the Refine Tracklets tab, I loaded the config file, original video, and the tracklet data(bx_filtered.h5), and I click on 'Step 1: Launch GUI.' When using the GUI, I notice that the labels for the mice are ahead of where the mice actually are. Eventually, the mouse does go to the spot where the labels previously were, but at this point in time, the labels have moved further, continuing this cycle of the tracklet data and the mice in the video not matching up in real time(the labels being ahead).

I've noticed that for the bodypart detection video produced when you analyze the video(when 'yes' is checked for 'Create video for checking detections'), the bodyparts for each respective mouse stays attached to the mouse's body part, and there is no delay whatsoever. I'm not sure if this has any significance or not.

**How to Reproduce the problem**

1. Launch DeepLabCut GUI
2. Load config file
3. Go to Refine Tracklets, load the config file, load the video that was analyzed in the 'analyze videos' step, and load the tracklet data(bx_filtered.h5). All other settings on default.
4. Launch Refine Tracklets GUI
5. Play video and see that the mice are delayed in relation to where their tracklets are(tracklets are labeled ahead of the mice)

**Comment by MMathisLab** [comment]
This is likely because you filtered the data and then are using this; load the normal .pickle file first please in the GUI to refine tracklets.

**Comment by mattka65** [comment]
Unfortunately, when I load the normal .pickle file(in my case bx) the delay still persists

**Comment by MMathisLab** [comment]
@mattka65 are you still having this issue? I cannot reproduce it; can you roll up to the latest version; my only suspicion if your video was somehow corrupted then the frame count does not match video frame length, so perhaps a mismatch is occuring.
