### ISSUE TITLE
Return ability to select multiple videos from search results

### ISSUE THREAD

**Issue by hummuscience** [DeepLabCut/DeepLabCut#984]
**Is your feature request related to a problem? Please describe.**
It used to be possible to search for video files (in windows or ubuntu) and then select all the files from the search results to add to the GUI. Now it is not possible anymore with the output message: "You can choose multiple items only if they in the same folder".

So I end up going into every folder manually and clicking the videos (that all have the same name). 

Quality of life problem, I guess.

**Describe the solution you'd like**
Use the paths of the videos in search, which are definitely unique.

**Describe alternatives you've considered**
In a jupyter notebook I could just grep the necessary videos. But the jupyter notebook if being buggy on me and the GUI is more convenient.

**Comment by jeylau** [comment]
I am sorry, I can only confirm that this works properly on MacOS. Perhaps you'd find more answers asking on our forum https://forum.image.sc/tag/deeplabcut 😊.
