### ISSUE TITLE
Run two trainings in parallel

### ISSUE THREAD

**Issue by Charly77220** [DeepLabCut/DeepLabCut#985]
Dear DLC team,

I don't know if it's the good place to ask you that. But I want to know if it's possible to run several trainings in paralell in different windows ?

Thanks by advance,

Charly

**Comment by MMathisLab** [comment]
Hi Charly, in general we ask you post questions on Image Forum here:, https://forum.image.sc/tag/deeplabcut

but in short, you need 1 GPU per process; of course you can open DLC in as many terminals as you want.

**Comment by Charly77220** [comment]
Thanks for the link, I will keep it 

Just to clarify, and after the ticket could be closed. I can open DLC in several terminals but if I have only one GPU, I can run only one training at time ?

**Comment by MMathisLab** [comment]
Correct!
