### ISSUE TITLE
trainFraction parameter misspelled in create_pretrained_project

### ISSUE THREAD

**Issue by ehsainit** [DeepLabCut/DeepLabCut#986]
Hey,

The parameter `trainFraction` in `create_pretrained_project` was probably accidentally misspelled, causing NameError: name 'tranFraction' is not defined upon initializing `trainFraction` with a value other that `None` :
https://github.com/DeepLabCut/DeepLabCut/blob/92e579a7e4283c91c58088c2950a8ced98fc2835/deeplabcut/create_project/modelzoo.py#L174

Best

**Comment by jeylau** [comment]
Good catch @ehsainit, thanks a lot!
