### ISSUE TITLE
Unable to Evaluate Training Set

### ISSUE THREAD

**Issue by WrathUM** [DeepLabCut/DeepLabCut#988]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

Please complete the following information about your system:

OS: Windows 10
DeepLabCut Version :2.2
Anaconda env used: GPUC

I ran the train dataset command for multi-animal pose estimation. It just completed, and then I went to click evaluate the network. It says that there is no such file or directory. 

**How to Reproduce the problem**
1. Train the network. Shuffle = 5. Display iterations = 10. Save Iterations = 500. Maximum Iteration = 50000. 
2. Click on train network
3. Click on Evaluate Network

**Screenshots**
![image](https://user-images.githubusercontent.com/57931859/98485885-9a431800-21ce-11eb-902c-dd353146373d.png)

**Additional context**
I am on the administrator account of the device and also working through the command prompt (anaconda prompt) as administrator.

**Comment by jeylau** [comment]
Did you select shuffle 5 in the evaluate network tab? DLC looks for a ...shuffle1.pickle, so it may be that the value remained at its default.

**Comment by WrathUM** [comment]
Ah that was it. Thank you very much!
