### ISSUE TITLE
Cannot load backend 'TkAgg' which requires the 'tk' interactive framework

### ISSUE THREAD

**Issue by ceradini** [DeepLabCut/DeepLabCut#993]
OS: Ubuntu 18.04
DeepLabCut: 2.1.8.2
Python version: 3.6
Python Virtual Env (the problem persist also with anaconda env and without env)

I'm facing this problem when I try to import the deeplabcut package:

`ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running`

<img width="959" alt="Schermata 2020-11-13 alle 14 29 05" src="https://user-images.githubusercontent.com/20844492/99077268-c38fe980-25bc-11eb-88b8-0490e460367c.png">

I have the correct version (3.0.3) of Matplot lib that is usually related to this problem.

Any suggestions?

Thank you

UPDATE:

I was able to "fix" this problem disabling all the loads of the TkAgg from matplotlib usages in the deeplabcut packages, of course is not a long term solution but it works for now. 
Anyone has a solution to fix this problem without disabling TkAgg?

Thank you.

**Comment by MMathisLab** [comment]
Can you try the latest matplotlib, also the latest DeepLabCut, please install 2.2b8

**Comment by ceradini** [comment]
> Can you try the latest matplotlib, also the latest DeepLabCut, please install 2.2b8

It works now, either with last matplotlib the 3.3.3 and the 3.1.3 that is required by DeepLabCut.

Thank you.
