### ISSUE TITLE
What is the difference of 'skeleton' in config.yaml(multianimal=False) and config.yaml(multianimal=True)

### ISSUE THREAD

**Issue by JoeH92** [DeepLabCut/DeepLabCut#997]
OS: Windows 10
DeepLabCut Version: 2.2b8
Anaconda env used: yes

Hi,
I want to konw whether the link information(skeleton) between two joints is trained when multianimal=False. In other words, whether the link inforation was trained only when  multianimal=True. What is the difference of 'skeleton' in config.yaml(multianimal=False) and config.yaml(multianimal=True) 

Thanks

**Comment by MMathisLab** [comment]
the skeleton is only used when a multianimal project is created (and then set to true); you can still use this feature for single animals, see here: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/UseOverviewGuide.md#important-information-on-using-deeplabcut 

Hope that helps!
