### ISSUE TITLE
auxiliaryfunctions.GetScorerName() not working

### ISSUE THREAD

**Issue by brettellebi** [DeepLabCut/DeepLabCut#998]
**Description**

Following the multi-animal tracking workflow described here: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/functionDetails.md, in section (I) when trying to create a video with all detections, the function `auxiliaryfunctions.GetScorerName(config_path, shuffle, trainFraction)` is causing an error.

**Desktop**
 - OS: Ubuntu 18.04 (Google Colab)
 - DeepLabCut Version: 2.2b8
 - DeepLabCut mode: multi-animal tracking
 - Browser: Mozilla Firefox 82.0.3

**To Reproduce**
1. Follow all steps up to here: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/functionDetails.md#i-novel-video-analysis
2. After running `deeplabcut.analyze_videos()` successfully,  I want to obtain the `scorername` to include in:
```python
deeplabcut.create_video_with_all_detections(config_path, video_path, DLCscorername=scorername)
```
3. See error:

<details><summary>TRACEBACK</summary><p>

```python

scorername, DLCscorerlegacy = deeplabcut.auxiliaryfunctions.GetScorerName(config_path, shuffle=1, trainFraction=0.95)
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-13-3f2ba0942ea3> in <module>()
----> 1 scorername, DLCscorerlegacy = deeplabcut.auxiliaryfunctions.GetScorerName(config_path, shuffle=1, trainFraction=0.95)

/usr/local/lib/python3.6/dist-packages/deeplabcut/utils/auxiliaryfunctions.py in GetScorerName(cfg, shuffle, trainFraction, trainingsiterations, modelprefix)
    529     """
    530 
--> 531     Task = cfg["Task"]
    532     date = cfg["date"]
    533 

TypeError: string indices must be integers

```
</p></details>

**Expected behavior**
A tuple `(scorername, DLCscorerlegacy)` to be returned.

**Screenshots**
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/42971601/99594239-05021800-2a47-11eb-8a59-222b92a8425a.png">

**Additional context**
The documentation provides the line:
```python
scorername, DLCscorerlegacy = auxiliaryfunctions.GetScorerName(config_path, shuffle, trainFraction)
```
I needed to add `deeplabcut.` in front of the function.
It may also be good to get some guidance on what the `trainFraction` is (i.e. where to find it in the `config.yaml`). I used `0.95` because that's what is underneath `TrainingFraction:` in that file.

Cheers,

Ian

**Comment by brettellebi** [comment]
I could work around the issue by running:
```python
from deeplabcut import auxiliaryfunctions
cfg = auxiliaryfunctions.read_config(config_path)
scorername, DLCscorerlegacy = auxiliaryfunctions.GetScorerName(cfg, shuffle=1, trainFraction=0.95)
```

But then I tried to run `deeplabcut.create_video_with_all_detections()` and got the following error:

<details><summary>TRACEBACK</summary><p>

```python

target_video = '/gdrive/MyDrive/pilot_paper/pp_proj-ian_brettell-2020-11-17/videos/20190611_1552_icab_hni_R_q3_novel_object.mp4'
deeplabcut.create_video_with_all_detections(config_path, target_video, DLCscorername=scorername)

Creating labeled video for  

---------------------------------------------------------------------------

FileNotFoundError                         Traceback (most recent call last)

<ipython-input-41-a06930cdcd31> in <module>()
----> 1 deeplabcut.create_video_with_all_detections(config_path, target_video, DLCscorername=scorername)

/usr/local/lib/python3.6/dist-packages/deeplabcut/utils/make_labeled_video.py in create_video_with_all_detections(config, videos, DLCscorername, displayedbodyparts, destfolder)
    808         if not (os.path.isfile(outputname)):
    809             print("Creating labeled video for ", str(Path(video).stem))
--> 810             with open(full_pickle, "rb") as file:
    811                 data = pickle.load(file)
    812 

FileNotFoundError: [Errno 2] No such file or directory: '/DLC_resnet50_pp_projNov17shuffle1_50000_full.pickle'

```
</p></details>

**Comment by jeylau** [comment]
@Ian-Brettell, your second use of `GetScorerName` is the intended one: the config dictionary should be passed in, rather than a string of its path. Pass also a list of videos (even when you analyze only one; e.g., `[target_video]`) and that will work fine!

**Comment by brettellebi** [comment]
Thank you!
